mullvad/mullvadvpn-app

.travis.yml
app/components/styled/Button.js

I broke the travis build, this PR fixes that breakage and also updates our test environment to node 8 and 9 which is the LTS and the latest versions.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/13)

Travis maintenance

---

app/components/CustomScrollbars.css
app/components/CustomScrollbars.js
app/components/PreferencesStyles.js
app/components/Settings.js
app/components/SettingsStyles.js

Makes sure the quit button is anchored to the bottom om the settings screen. The render method is simply split up into parts and then some flex magic pushes the quit button to the bottom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/12)

Anchor the quit button to the bottom of the settings page

---

app/components/SelectLocation.js
test/components/SelectLocation.spec.js

A little defect that @mjhomer noticed after a design review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/26)

Hide the list of cities when there is only one available within the country

---

app/components/Account.js
app/components/Connect.js
package.json
yarn.lock

Since react-if adds more code, is unmaintained and is/was incompatible with react-native …
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/31)

Remove react-if

---

app/app.js
app/containers/AccountPage.js
app/containers/AdvancedSettingsPage.js
app/containers/ConnectPage.js
app/containers/LoginPage.js
app/containers/SelectLocationPage.js
app/containers/SettingsPage.js
app/containers/SupportPage.js
app/lib/backend.js
app/lib/jsonrpc-ws-ipc.js
app/lib/platform.android.js
app/lib/platform.js
app/main.js

Moving logging to platform.js (because of issues with conditional imports using electron-log and react-native at the same time) and renaming open -> openLink to enable openItem (file).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/30)

Logging xp

---

app/lib/backend.js

Removes unused EventEmitter from backend.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/33)

Remove EventEmitter

---

CHANGELOG.md
README.md
mullvad-daemon/src/cli.rs
mullvad-daemon/src/main.rs

Fixes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/37)

Add resource flag

---

app/components/PreferencesStyles.js
app/components/Settings.js
app/components/SettingsStyles.js

Some changes in the styles to not crash on android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/35)

Reacxp-style fixes for react-native

---

talpid-core/src/tunnel/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/38)

Fix names of OpenVPN binary and OpenVPN plugin

---

app/lib/backend.js

This can be reproduced by adding something like `1.1.1.1 api.mullvad.net` to `/etc/hosts`
I also introduce an unknown error type to avoid future similar issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/43)

Inform the user if they cannot react api.mullvad.net when trying to log in

---

CHANGELOG.md

Not sure why I did this change, you guys are the ones who really care about it. So feel free to push any changes you want on this branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/47)

Update changelog for beta 9

---

app/components/Support.js
app/components/SupportStyles.js
package.json
test/components/Support.spec.js
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/46)

Email confirmation

---

app/components/Settings.js
app/components/SettingsStyles.js
app/config.json
app/containers/SettingsPage.js
test/components/Settings.spec.js

@anderklander Should I put the version stuff in `app/lib/platform.js`?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/49)

Show the app version in the settings view

---

app/components/SupportStyles.js

Very minor update to the back button's position in support view. All "back buttons" across settings are fixed at `[12, 12]`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/70)

Adjust the back button's position in support view

---

CHANGELOG.md
app/components/Support.js
app/lib/problem-report.js
app/main.js

This PR fixes:
1. Bumps timeout for problem-report tool from 1s to 10s. I have observable delay (up to 4s) before the response arrives
2. Funnels the entire account history into problem-report collection tool.
3. A rewrite of `collectProblemReport` that fixes a memory leak in IPC
4. Renames `.report` logs back to `.log` since macOS does not recognize the `report` extension and unable to determine the right program to open such extension.
@faern  Ping me if you're going to update `CHANGELOG` or me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/77)

Fix problem report

---

build.sh

I noticed that just removing the binaries prior to a build is not enough of a cleanup. The buildscript, `build.sh` is not re-executed in this case and the new build can then contain old information collected in the last build. This happened just now when I built `2018.1`. To prevent this I do a full `cargo clean` before the `cargo build`. The re-build after that will take significantly longer, but since we don't use this release build script that often I think this is fully OK.
I also added a safety check that the correct stable compiler version is installed. I want the build script to be as strict as possible, too many things that are easy to forget when building a release and the tighter the automatic checks can be, the better. So we'll have to update the version variable approximately …

Add rustc version check to build.sh and do more cleaning prior to build

---

app/lib/tempdir.js
app/main.js

This PR adds the system temporary directory lookup for windows: 
```
%windir%\TEMP
```
I've assigned all of you to keep you in the loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/72)

Fix the path to system temp directory on windows

---

CHANGELOG.md
mullvad-cli/src/main.rs
mullvad-cli/src/rpc.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/86)

Improve rpc file permission error message

---

CHANGELOG.md
mullvad-daemon/src/main.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/84)

Create openvpn log backup

---

package.json
yarn.lock

We don't really want forks of packages on our private accounts, so I have forked the three forks we had to the mullvad organization instead. This PR updates package.json to point to the new forks .
Not worth mentioning in the changelog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/93)

Move my and Andrei's forks over to the Mullvad organization

---

CHANGELOG.md
mullvad-cli/src/cmds/mod.rs
mullvad-cli/src/cmds/version.rs
mullvad-daemon/src/cli.rs
mullvad-daemon/src/main.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/version.rs
mullvad-rpc/src/lib.rs
mullvad-types/src/lib.rs
mullvad-types/src/version.rs

I've added a couple of RPCs to get info from the master API about app versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/105)

Version status RPCs

---

mullvad-daemon/src/management_interface.rs

Version used: rustfmt 0.4.1-nightly (a4462d1 2018-03-26)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/110)

Fix formatting issue reported by latest rustfmt

---

Cargo.lock
mullvad-daemon/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/112)

Update app_dirs to version 1.2.1 to fix CI build

---

CHANGELOG.md
app/main.js
electron-builder.yml
uninstall.sh

Moving this change (product name) into its own dedicated PR.
For more background: #115 
* [ X ] Describe the change in **`CHANGELOG.md`**. Only applicable if the change has any impact for a user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/117)

Correct product name

---

CHANGELOG.md

I have imagined these format rules for the changelog. But they have not been written anywhere. So everyone has used some other format at at least one occasion. So I felt like writing them down, which can have one of two outcomes:
* We merge this and thus have a written style to follow, makes it easier to keep the file consistent.
* We disagree on the rules and say there are no rules. The changelog will become messy, but I can stop pointing it out in PRs.
Also added a forgotten change entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/118)

Add changelog instructions

---

app/components/Accordion.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/125)

Re-render Accordion on children prop change

---

Cargo.lock
mullvad-rpc/Cargo.toml
mullvad-rpc/src/https_client_with_sni.rs
mullvad-rpc/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/131)

Configure SNI domain for TLS handshake with master

---

CHANGELOG.md
Cargo.lock
mullvad-rpc/src/lib.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/138)

Reduce master RPC timeout

---

CHANGELOG.md
app/components/Connect.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/142)

Fix login screen status icon position

---

Cargo.lock
app/main.js
mullvad-daemon/Cargo.toml
mullvad-daemon/src/cli.rs
mullvad-daemon/src/main.rs
mullvad-daemon/src/system_service.rs
talpid-core/Cargo.toml
talpid-core/src/lib.rs
talpid-core/src/process/openvpn.rs
windows-service/examples/simple_service.rs
windows-service/src/service.rs

Baby steps towards a complete windows service implementation of daemon.
Checklist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/137)

Windows service integration

---

CHANGELOG.md
app/components/Login.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/145)

Increase placeholder account token length

---

Cargo.lock
Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-daemon/tests/common/mod.rs
mullvad-daemon/tests/startup.rs
mullvad-ipc-client/Cargo.toml
mullvad-ipc-client/src/lib.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/146)

Create separate crate for Mullvad RPC client

---

mullvad-ipc-client/src/lib.rs
talpid-ipc/src/client.rs
talpid-ipc/tests/ipc-client-server.rs
talpid-openvpn-plugin/src/processing.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/153)

Reuse WebSocket connection in `WsIpcClient`

---

CHANGELOG.md
mullvad-daemon/src/bin/problem-report.rs
mullvad-daemon/src/logging.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/148)

Platform specific newlines in log file

---

Cargo.lock
mullvad-daemon/src/bin/problem-report.rs
talpid-core/Cargo.toml
talpid-core/src/lib.rs
talpid-core/src/tunnel/openvpn.rs
windows-service/examples/simple_service.rs

This PR mostly moves imports around to remove warnings when building on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/165)

Fix warnings on Windows

---

CHANGELOG.md
dist-assets/pkg-scripts/preinstall
mullvad-daemon/src/settings.rs
package.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/171)

Move settings on unix

---

Cargo.lock
talpid-ipc/Cargo.toml
talpid-ipc/src/client.rs
talpid-ipc/src/lib.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/159)

Add support for JSON-RPC PubSub subscriptions

---

.babelrc
package.json
yarn.lock

This PR removes unused `babel-plugin-inline-react-svg` babel plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/194)

Remove babel-plugin-inline-react-svg

---

mullvad-cli/src/cmds/relay.rs
mullvad-daemon/src/bin/problem-report.rs

No user facing change. Just updating source with the latest rustfmt as usual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/196)

Update formatting with the latest rustfmt

---

package.json

This PR moves babel plugin to `devDependencies`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/193)

Move 'babel-plugin-transform-builtin-extend' to devDependencies

---

package.json
yarn.lock

This PR bumps the versions of `NSEventMonitor` and `windows-security` packages to the latest. Both packages received security updates last week.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/191)

Update our dependencies

---

CHANGELOG.md
app/components/Settings.js

User facing change. As discussed in https://trello.com/c/O12IvHgs, this PR changes "Contact support" to "Report a problem" to align with original design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/198)

Update contact support label in settings

---

app/app.js
flow-libs/electron.js.flow
package.json
yarn.lock

No user facing changes. This PR updates Electron from 1.8.x to 2.0.x.
I'll rebase once approved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/200)

Electron 2.0

---

Cargo.lock
talpid-core/Cargo.toml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/205)

Use `resolv-conf` version in crates.io

---

app/app.js
app/lib/jsonrpc-ws-ipc.js
app/lib/problem-report.js
app/main.js
app/tray-icon-controller.js
app/window-controller.js
flow-libs/electron.js.flow
package.json
scripts/serve.js
yarn.lock

1. This PR refactors `main.js` and incorporates a fare share of it into `WindowController`.
2. Renames `TrayIconManager` to `TrayIconController` because `manager` is a bad bad name.
3. Changes verbosity of Websocket IPC which used to log every packet with debug level, I changed that to `silly` (AKA `trace` in other logging systems)
4. Upgrades reactxp to 1.3.0 RC which addresses some of the issues I had upgrading from 1.1 RC to 1.2.0 that introduced some of regressions
5. Moves problem-report execution from renderer to main process.
6. Removes timeout for problem-report collection.
7. Stops passing `--enable-logging` to Electron when developing. `electron-log` funnels renderer logs to main automatically and vise-versa so there is no point to dupe the same messages.
No …

Modernize app

---

CHANGELOG.md
app/components/Account.js
app/containers/AccountPage.js
app/lib/app-visibility.js
app/lib/backend.js
app/main.js
app/redux/account/actions.js
app/redux/account/reducers.js
app/redux/store.js
test/components/Account.spec.js
test/ipc.spec.js

This PR adds automatic refresh for account expiration each time Account view appears. This includes the situation if the view is already rendered but the window toggles between visible/hidden. 
There is really not much indication that the account expiration is being refreshed but hopefully that shouldn't matter now as it should happen fast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/209)

Refresh expiry time

---

app/app.js
app/lib/backend.js
app/lib/ipc-facade.js
app/main.js
app/shutdown-handler.js
app/tray-icon-controller.js

This PR refactors the shutdown coordination between main and renderer processes into one class and one function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/211)

Add ShutdownHandler

---

talpid-core/src/tunnel/openvpn.rs
talpid-openvpn-plugin/src/lib.rs
talpid-openvpn-plugin/src/processing.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/214)

Talpid OpenVPN plugin IPC credentials

---

package.json
test/components/Account.spec.js
test/components/AccountInput.spec.js
test/components/HeaderBar.spec.js
test/components/Login.spec.js
test/components/Preferences.spec.js
test/components/Settings.spec.js
test/components/Support.spec.js
test/setup/renderer.js
yarn.lock

1. Configure Enzyme once globally for the renderer process using `--preload` option of `electron-mocha`. 
2. Remove `react-test-renderer` from dependencies since `enzyme-adapter-react-16` already includes it.
3. Upgrade `sinon` from v3 to v6. The change is minimal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/216)

Fix enzyme configuration

---

app/app.android.js
app/app.js
app/components/Connect.js
app/lib/backend.js
app/lib/jsonrpc-ws-ipc.js
app/redux/account/actions.js
app/redux/account/reducers.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/217)

Refactor backend error types

---

app/routes.js

Although they can be fixed by updating to Flow 0.71, the `validated`
package is not compatible with that version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/218)

Ignore Flow errors in `app/routes.js`

---

talpid-core/src/firewall/linux/dns.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/220)

Linux DNS backup

---

app/components/Login.js

No user facing changes worth to mention.
This PR refactors Login in order to sort out couple of outstanding issues:
1. Too much state in the component. Most of data that currently resides in component's state can be moved out of state because it's not used during component's rendering.
2. Prevent running animations when there is nothing to animate. Can't help myself adding another flag.
3. Auto-focus bug, when failure to log in would trap user in account input field without any way to lose focus to it to reveal the footer view.
4. Fix for convoluted UI logic when using `onLayout` instead of simply going with `UserInterface.measureLayoutRelativeToWindow` to get the footer dimensions when animating.
5. Migrate from `componentWillReceiveProps` to `componentDidUpdate` …

Refactor Login

---

geo-data/README.md

Since README is rendered as plain text on Github, I figured we should rename it to `.md` since it's mostly markdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/229)

Update and rename README to README.md

---

mullvad-daemon/src/bin/problem-report.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/241)

Use `systeminfo` command to get Windows version

---

README.md
package.json

We discussed on slack that this command could go. Also update documentation accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/242)

Remove pack command

---

CHANGELOG.md
mullvad-cli/src/cmds/status.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/247)

Add `status listen` sub-command to Mullvad CLI

---

Cargo.lock
mullvad-ipc-client/Cargo.toml
mullvad-ipc-client/src/lib.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/236)

Ensure RPC address file is owned by administrator

---

package.json
yarn.lock

Fixing the problem where building for windows just hangs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/254)

Upgrade electron-builder to solve Windows bug

---

package.json
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/264)

Update electron-builder to get improvements to signing on Windows

---

.travis.yml
Cargo.lock
README.md
build.sh
talpid-core/Cargo.toml
talpid-core/src/firewall/linux/mod.rs
talpid-core/src/firewall/macos/mod.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/lib.rs

Here comes the Linux firewall integration.
Beware, I have not tested it very extensively yet. There might even be an entire class of rules missing or misbehaving. I just feel like I have been massaging this for long enough without any insight into what I'm doing. So I don't think I can make it much better without having a round of feedback first. I have probably become blind to my own errors by now.
Sorry for it being a bit of a large PR. You can follow some changes commit for commit at first, but then the entire firewall implementation comes in one commit sadly.
Our netfilter library is very low level, and as such creating the rules here becomes very low level. Ask about anything you don't understand and I'll try to answer as best as I can :)
--- …

Linux firewall integration

---

mullvad-ipc-client/Cargo.toml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/263)

Add all used `winapi` features

---

app/components/Support.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/265)

Add `(optional)` text to email input

---

.eslintrc
app/components/Connect.js
app/components/HeaderBar.js
app/components/Settings.js
app/lib/backend.js
app/lib/keyframe-animation.js
app/main.js
test/components/Login.spec.js
test/components/Settings.spec.js
test/keyframe-animation.spec.js

This PR adds a linter option to warn a developer when declaring immutable variables as mutable.
Also I ran a `lint --fix` to automatically fix all of such occurrences.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/261)

Add option to prefer const over let for immutable variables

---

talpid-core/src/firewall/linux/mod.rs

I *think* this should make it `Send` again. I was not able to generate the docs so I could check...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/267)

Don't store Table in Linux firewall to make it impl Send

---

mullvad-tests/src/bin/mock_openvpn.rs
mullvad-tests/src/lib.rs
mullvad-tests/src/mock_openvpn/mod.rs
mullvad-tests/tests/account.rs
mullvad-tests/tests/connection.rs

This is the last regression test PR before the state refactor. It contains some commits to refactor some test helper code, and also two tests related to the usage of account tokens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/255)

Account tests

---

talpid-core/src/firewall/linux/dns.rs

While testing the app on Linux, I ran into some DNS errors during initialization. From the error alone, it was hard to find out what was going wrong, so this PR attempts to refactor the errors so that finding the point of failure becomes easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/262)

Refactor Linux DNS errors

---

mullvad-tests/tests/connection.rs

What sometimes happened was that the assertion that the file existed was
successful, but the file hadn't finished being written to, so an attempt
to read data from it failed.
The fix is to assert that the full open, write, close cycle has been applied to
the mock OpenVPN arguments file before attempting to read data from it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/271)

Fix race condition on mock OpenVPN arguments file

---

mullvad-tests/src/lib.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/275)

Use provided API server CA in integration tests

---

CHANGELOG.md
windows/winfw/src/winfw/fwcontext.cpp
windows/winfw/src/winfw/mullvadguids.cpp
windows/winfw/src/winfw/mullvadguids.h
windows/winfw/src/winfw/rules/permitvpntunnelservice.cpp
windows/winfw/src/winfw/rules/permitvpntunnelservice.h
windows/winfw/src/winfw/winfw.vcxproj
windows/winfw/src/winfw/winfw.vcxproj.filters

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/280)

Enable port forwarding

---

CHANGELOG.md
build.sh
dist-assets/windows/version.h
mullvad-cli/Cargo.toml
mullvad-cli/build.rs
mullvad-cli/version.rc
mullvad-daemon/Cargo.toml
mullvad-daemon/build.rs
mullvad-daemon/version.rc
mullvad-problem-report/Cargo.toml
mullvad-problem-report/build.rs
mullvad-problem-report/version.rc
talpid-openvpn-plugin/Cargo.toml
talpid-openvpn-plugin/build.rs
talpid-openvpn-plugin/version.rc
windows/windns/src/windns/windns.rc
windows/windns/src/windns/windns.vcxproj
windows/windns/src/windns/windns.vcxproj.filters
windows/winfw/src/winfw/winfw.rc
windows/winfw/src/winfw/winfw.vcxproj
windows/winfw/src/winfw/winfw.vcxproj.filters
windows/winroute/src/winroute/winroute.rc
windows/winroute/src/winroute/winroute.vcxproj
windows/winroute/src/winroute/winroute.vcxproj.filters

Adds version information (right-click -> properties -> details) for all executables and DLLs that are shipped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/285)

Windows versioninfo

---

CHANGELOG.md
mullvad-daemon/src/main.rs
mullvad-daemon/src/relays.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/281)

Download relay list more often

---

dist-assets/linux/mullvad-daemon.service

Will always attempt to restart the daemon, unless the daemon fails to
start five times within twenty seconds.
The values I chose are arbitrary, so if anyone has better suggestions please let me know :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/286)

Configure systemd to restart daemon when necessary

---

electron-builder.yml

The other dependencies in the list are what I assume the "default" dependencies, as they were present in the previously built RPM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/289)

Add libnsl dependency to RPM package

---

CHANGELOG.md
mullvad-daemon/src/system_service.rs

This PR fixes the omission in the service status updates to SCM in the event of service initialization failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/301)

Notify the system in the event of service initialization failure

---

mullvad-daemon/src/relays.rs

Making the error chain less absurd when there is an error in reading both the relays cache and the resource dir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/309)

Don't chain cache and resource reading errors on each other

---

README.md
build.sh

This PR basically makes my _improvements_ to `build.sh` from yesterday actually work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/310)

Fix relay list download

---

mullvad-cli/src/cmds/mod.rs
mullvad-cli/src/cmds/relay.rs
mullvad-cli/src/cmds/tunnel.rs
mullvad-types/src/custom_tunnel.rs
talpid-types/src/net.rs

Just implementing some of the things clippy warned me about when running it on this project. It warned about a billion more things, but I think this can be a soft and nice start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/306)

Fix clippy warnings

---

app/components/HeaderBar.js
app/components/HeaderBarStyles.js
test/components/HeaderBar.spec.js

We used to have an option to "hide" the header bar with logo in the app but we haven't used this feature since pre-beta. This PR simply cleans up unused code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/317)

Remove "hidden" prop from HeaderBar

---

Cargo.lock
integration-tests.sh
mullvad-tests/Cargo.toml
mullvad-tests/src/lib.rs
mullvad-tests/tests/account.rs
mullvad-tests/tests/connection.rs
mullvad-tests/tests/startup.rs

This PR makes the integration tests also run on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/284)

Windows integration tests

---

app/components/PlatformWindow.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/320)

Make sure to apply the platform window mask only on mac

---

CHANGELOG.md
app/main.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/319)

Rotate GUI log

---

CHANGELOG.md
app/components/Account.js
app/containers/AccountPage.js
app/redux/account/actions.js
test/components/Account.spec.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/322)

Allow account token to be copied with a mouse click

---

CHANGELOG.md
app/components/Account.js
app/containers/AccountPage.js
test/components/Account.spec.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/321)

Localize expiry date and time

---

CHANGELOG.md
mullvad-problem-report/src/main.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/323)

Ignore requests to redact empty strings

---

CHANGELOG.md
app/components/Login.js
test/components/Login.spec.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/324)

Ignore accounts with less than ten digits

---

app/components/Preferences.js
app/lib/platform.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/331)

Implement auto-start on Linux

---

CHANGELOG.md
README.md
app/main.js
mullvad-paths/src/settings.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/332)

Use local path instead of roaming path on Windows

---

CHANGELOG.md
app/components/CustomScrollbars.js
app/components/SelectLocation.js

This PR brings back the automatic scroll restoration in locations view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/337)

Auto scroll to selected location

---

Cargo.lock
mullvad-problem-report/Cargo.toml
mullvad-problem-report/src/main.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/329)

Fallback to `os-release` file

---

app/app.js
app/components/Connect.js
app/errors.js
app/lib/daemon-rpc.js

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/246)

Refactor where `InvalidAccountError` is created

---

dist-assets/windows/installer.nsh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/343)

Remove roaming folder and all contents

---

.eslintrc
app/app.js
app/components/Account.js
app/components/Connect.js
app/errors.js
package.json
yarn.lock

Git checklist:
- Updated from Flow 0.66 to 0.78
- Removed `userFriendlyError` from Error subclasses and temporarily moved the error descriptions back to `Connect`. As I previously explained, it's best if we word errors based on view/context instead of having one title/message for everything.
- Fixed couple of code defects that  older version of Flow didn't catch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/344)

Update flow v0.78

---

CHANGELOG.md
app/app.js
app/main.js
app/notification-controller.js
flow-libs/notification.js.flow

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/340)

Notifications

---

app/components/Support.js
app/components/SupportStyles.js

Git checklist:
1. Fix vertical margin between "Edit/Retry" buttons that appear when the app is not able to submit a problem report
2. Uppercase "SECURE CONNECTION" to match with design and main view
3. Fix a regression in Contact form where the spinner was aligned by the left edge instead of being centered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/348)

Contact form tweaks

---

CHANGELOG.md
dist-assets/windows/installer.nsh
windows/nsis-plugins/nsis-plugins.sln
windows/nsis-plugins/src/cleanup/cleaningops.cpp
windows/nsis-plugins/src/cleanup/cleaningops.h
windows/nsis-plugins/src/cleanup/cleanup.cpp
windows/nsis-plugins/src/cleanup/cleanup.def
windows/nsis-plugins/src/cleanup/cleanup.vcxproj
windows/nsis-plugins/src/cleanup/cleanup.vcxproj.filters
windows/nsis-plugins/src/cleanup/dllmain.cpp
windows/nsis-plugins/src/cleanup/stdafx.cpp
windows/nsis-plugins/src/cleanup/stdafx.h
windows/nsis-plugins/src/cleanup/targetver.h

Platform: Windows.
This is an update to the uninstaller: Remove logs, cache and optionally settings.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/385)

Uninst clean logs

---

CHANGELOG.md
dist-assets/windows/installer.nsh
windows/nsis-plugins/nsis-plugins.sln
windows/nsis-plugins/src/driverlogic/context.cpp
windows/nsis-plugins/src/driverlogic/driverlogic.cpp
windows/nsis-plugins/src/driverlogic/driverlogic.vcxproj
windows/nsis-plugins/src/log/dllmain.cpp
windows/nsis-plugins/src/log/log.cpp
windows/nsis-plugins/src/log/log.def
windows/nsis-plugins/src/log/log.h
windows/nsis-plugins/src/log/log.vcxproj
windows/nsis-plugins/src/log/log.vcxproj.filters
windows/nsis-plugins/src/log/logger.cpp
windows/nsis-plugins/src/log/logger.h
windows/nsis-plugins/src/log/stdafx.cpp
windows/nsis-plugins/src/log/stdafx.h
windows/nsis-plugins/src/log/targetver.h

Add logging in installer that covers all the failure cases we've currently seen on customer machines. If something fails there will be enough data to troubleshoot on our end.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/399)

Installer log

---

windows/nsis-plugins/src/cleanup/cleaningops.cpp

Adjust some code here now that libcommon was updated to remove duplicated functionality already present in the standard library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/407)

C++17 fixes

---

gui/packages/desktop/src/renderer/components/Connect.js

Git checklist:
This PR removes the dead code which previously used to calculate the vertical offset for the map view in order to align the spinner view that appears when connecting the tunnel, with the marker view on the map. The offset is constant 123 anyway and not dynamic (defined in `_getMapProps()`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/434)

Remove dead code

---

build.sh

We have noticed for quite a while that sometimes the buildscript fails to clean up the backed up version metadata files. This was because we started `cd`ing into the `gui/` directory, and thus the relative paths were wrong when the backup restore function executed.
This PR makes it possible to run the script from anywhere (it `cd`s to the correct folder directly) and it also makes sure to go to the correct dir before cleaning up on exit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/438)

Fix build.sh so it cleans up version changes on exit

---

talpid-core/src/security/windows/dns.rs
windows/windns/src/extras/loader/loader.cpp
windows/windns/src/windns/configmanager.cpp
windows/windns/src/windns/configmanager.h
windows/windns/src/windns/confineoperation.cpp
windows/windns/src/windns/confineoperation.h
windows/windns/src/windns/iclientsinkproxy.h
windows/windns/src/windns/netconfigeventsink.cpp
windows/windns/src/windns/netconfigeventsink.h
windows/windns/src/windns/netsh.cpp
windows/windns/src/windns/netsh.h
windows/windns/src/windns/windns.cpp
windows/windns/src/windns/windns.h
windows/windns/src/windns/windns.vcxproj
windows/windns/src/windns/windns.vcxproj.filters
windows/windns/src/windns/windnscontext.cpp
windows/windns/src/windns/windnscontext.h

-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/442)

Windns improve logging

---

CHANGELOG.md
talpid-core/src/security/linux/mod.rs
talpid-core/src/security/macos/mod.rs
talpid-core/src/security/mod.rs

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/470)

Allow IPv6 on LAN if enabled

---

gui/packages/components/package.json
gui/packages/components/src/ClipboardLabel.tsx
gui/packages/components/src/SecuredLabel.tsx
gui/packages/components/src/index.ts
gui/packages/components/tsconfig.json
gui/packages/desktop/src/renderer/components/Account.js
gui/packages/desktop/src/renderer/components/Connect.js
gui/packages/desktop/src/renderer/components/ConnectStyles.js
gui/packages/desktop/test/components/Connect.spec.js
gui/yarn.lock

Git checklist:
This PR breaks the `Connect` component on many smaller ones. Most of the components are stateless.
It became fairly difficult to describe the interface of `Connect` view. 
1. By hiding the complexity of the entire view behind many smaller ones
2. By using stateless components to do bindings behind the scenes and describe interface without repeating the data bindings over and over again.
PS: tests are broken still.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/456)

Break down Connect on many smaller components

---

CHANGELOG.md
gui/packages/desktop/package.json
gui/packages/desktop/src/main/index.js
gui/yarn.lock

Git checklist:
This PR updates the app to the most recent stable Electron 3.0 and disables double click handling of tray icon which significantly improves response times when clicking fast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/465)

Update to Electron 3.0

---

mullvad-cli/src/cmds/account.rs
mullvad-cli/src/cmds/auto_connect.rs
mullvad-cli/src/cmds/lan.rs
mullvad-cli/src/cmds/relay.rs
mullvad-cli/src/cmds/tunnel.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/main.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/relays.rs
mullvad-daemon/src/shutdown.rs
mullvad-ipc-client/src/lib.rs
mullvad-problem-report/src/main.rs
mullvad-rpc/src/rest.rs
mullvad-tests/src/lib.rs
mullvad-types/src/custom_tunnel.rs
talpid-core/src/security/macos/dns.rs
talpid-core/src/security/macos/mod.rs
talpid-core/src/security/windows/dns.rs
talpid-core/src/security/windows/mod.rs
talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/openvpn.rs
talpid-ipc/src/lib.rs

Reformat with the latest release candidate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/479)

Reformat with rustfmt 0.99.5

---

gui/packages/components/test/test-stub.spec.tsx
gui/packages/desktop/src/main/index.js
gui/packages/desktop/src/renderer/components/Connect.js

This PR cleans up some of the remaining issues after merging the electron v3.0 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/477)

Fix flow issues and drop unused testName props

---

CHANGELOG.md
Cargo.lock
gui/packages/desktop/package.json
mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-problem-report/Cargo.toml

This PR just prepares the changelog and version numbers for release. I usually don't run these through review. Only reason for that is that I slightly modified the changelog, so I wanted a second pair of eyes on it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/484)

Prepare release

---

talpid-core/src/security/linux/dns/mod.rs

It's kind of hard to know which DNS manager is being used, until it has an error and the manager itself logs for that reason or similar. I find it handy for myself, and likely in problem reports in the future, to be able to know which DNS handler is being used when users have DNS problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/516)

Debug log which Linux DNS manager is being used

---

CHANGELOG.md
gui/flow-libs/electron.js.flow
gui/packages/desktop/src/renderer/app.js
gui/packages/desktop/src/renderer/components/NotificationArea.js
gui/packages/desktop/src/renderer/components/NotificationBanner.js
gui/packages/desktop/src/renderer/lib/daemon-rpc.js
gui/packages/desktop/src/renderer/lib/notification-controller.js
gui/packages/desktop/src/renderer/redux/version/actions.js
gui/packages/desktop/src/renderer/redux/version/reducers.js

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/518)

Add unsupported/inconsistent app system notifications

---

gui/packages/desktop/src/renderer/lib/daemon-rpc.js
gui/packages/desktop/test/components/SelectLocation.spec.js

Git checklist:
I bet @faern you worked on this so I've added you to the review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/530)

Clean up occurrences of ipv4AddrExit

---

gui/packages/desktop/src/assets/css/global.css
gui/packages/desktop/src/renderer/components/AdvancedSettings.js
gui/packages/desktop/src/renderer/components/AdvancedSettingsStyles.js
gui/packages/desktop/src/renderer/components/Cell.js
gui/packages/desktop/src/renderer/components/Login.js
gui/packages/desktop/src/renderer/components/NavigationBar.js

Git checklist:
1. Make mssfix field to look less bulky
2. Make navigation bar title brighter in Settings views to add some contrast between the title and "back" button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/536)

Visual appearance tweaks

---

gui/packages/desktop/src/renderer/components/Cell.js

Git checklist:
I rushed and merged before tests passed. 😢 because I was sure they will, but it seems that rebase screwed something.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/537)

Fix some rebase issues raised by previous PRs

---

gui/packages/components/src/ConnectionInfo.tsx
gui/packages/desktop/src/renderer/components/Connect.js

Git checklist:
This PR refines some of the recent work. 
1. In essence both `TunnelControl` and `ConnectionInfo` components maintain the internal state that tells whether the `ConnectionInfo` details should be expanded. This is excessive, and we could turn `ConnectionInfo` intro controlled component instead since `TunnelControl` maintains the same flag anyway.
2. There is been some nullability madness, this PR untangles it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/544)

Refactor connection info

---

talpid-core/src/security/linux/mod.rs

It turns out we weren't blocking DNS requests at the firewall level on Linux on all the interfaces. This meant that DNS could leak. This change fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/549)

Block all traffic on port 53 on Linux

---

talpid-core/src/security/linux/dns/systemd_resolved.rs

On 18.10 and possibly other systems, when using `systemd-resolved` to manage DNS, even though the tunnel interface has it's DNS servers set correctly, if there are other interfaces which have a `.` entry in their search domains, our tunnel interface's DNS server will never be used to resolve anything. This change fixes that by also setting the search domain for our tunnel interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/553)

Set search domains for tunnel interface with systemd-resolved

---

CHANGELOG.md

Adding things to changelog that were not added during development of them. And move one Linux specific item to the `#### Linux` section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/556)

Add Linux changes to changelog. Mostly DNS

---

gui/packages/desktop/package.json

Git checklist:
Fix quotes in the babel command to be Windows friendly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/560)

Fix quotes

---

mullvad-cli/src/main.rs

I ran the CLI with the daemon not running and noticed that the error message doesn't really tell me much. So I've added a new error type just for this, and made it append a small `Is the daemon running` message at the end of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/561)

Improve error message in CLI when daemon is not running

---

Cargo.lock
mullvad-tests/Cargo.toml
mullvad-tests/src/lib.rs
talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/openvpn.rs
talpid-openvpn-plugin/src/lib.rs
talpid-openvpn-plugin/src/processing.rs

Updating to the latest version of the code in the `openvpn-plugin` crate that you recently reviewed. The only noticeable difference is the name of the event type enum I think.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/564)

Use latest changes to openvpn-plugin library

---

gui/packages/desktop/src/main/index.js
gui/packages/desktop/src/renderer/app.js

Git checklist:
This PR moves relay list management and periodic updates from renderer to main process.
Because browser windows will be disposable and throttled, so no app critical logic should be contained in them.
1. Pull relays and starts relays periodic updates when connected to daemon
2. Stop periodic relays updates when disconnected from daemon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/597)

Move relay updates to the main process

---

gui/packages/desktop/scripts/serve.js

Git checklist:
Restart Electron on changes to the main process sources. (in development only)
Currently changing the sources of the main process requires a developer to restart the Electron manually in order for changes to kick in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/601)

Restart Electron on changes to the main process sources

---

gui/packages/desktop/src/renderer/app.js

During the refactor to move some code from the renderer process to the main process, the auto-connect behavior was removed. This PR restores the specific part that handles the auto-connect, so that the behavior is restored.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/623)

Fix auto-connect when app starts

---

mullvad-cli/src/cmds/tunnel.rs
talpid-core/src/network_interface.rs
talpid-core/src/routing/linux.rs
talpid-core/src/routing/macos.rs
talpid-core/src/routing/subprocess.rs

I had the first commit in this PR laying around in my git history. And since I have not been able to focus on a single large task today I felt it was time to catch up on older smaller things. Rebased and was able to fix a few more things Clippy recommended.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/622)

Clippy cleanup

---

gui/packages/desktop/src/renderer/app.js
gui/packages/desktop/src/renderer/containers/ConnectPage.js

Git checklist:
This PR increases the responsiveness of the application when connecting or disconnecting the tunnel in response to the user interaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/643)

Connect when disconnecting

---

CHANGELOG.md
gui/package.json
gui/packages/components/src/Modal.tsx
gui/packages/components/src/index.ts
gui/packages/desktop/src/renderer/components/Support.js
gui/packages/desktop/src/renderer/components/SupportStyles.js
gui/yarn.lock

Git checklist:
Add custom modal alert when submitting a report without an email.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/662)

Confirm no email dialog

---

talpid-core/src/security/windows/dns.rs
talpid-core/src/security/windows/mod.rs
talpid-core/src/winnet.rs

Nightly changes strike again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/669)

Adjust #[link_name] attributes

---

gui/packages/desktop/src/renderer/app.js

Git checklist:
Currently, the GUI attempts to automatically connect the tunnel each time it established the connection with daemon.
The auto-connect option was meant to happen only once on startup.
With the power of a `boolean` flag 🎏
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/668)

Skip auto-connect if it was done before

---

gui/packages/desktop/src/main/jsonrpc-client.js

Git checklist:
This PR fixes the reconnection loop caused by internal state inconsistency in the socket transport.
Based on Node.js documentation, the `close` event is always emitted after the `error` event. The `error` event simply registers an error, and the `close` event receives a `boolean` argument that tells whether the connection had been closed due to an error or maybe deliberately.
We used to report the error back immediately upon receiving the `error` event. At this point the app would attempt to reconnect the socket. However the `close` event scheduled right after the `error` and being unrelated to the newly established connection, was still fired and mistakenly interpreted as if the …

Refactor the socket transport and fix the reconnection loop

---

gui/packages/desktop/src/main/index.js
gui/packages/desktop/src/renderer/app.js
gui/packages/desktop/src/renderer/lib/daemon-rpc-proxy.js
gui/packages/desktop/src/shared/ipc-event-channel.js

Git checklist:
This PR migrates the account management from the `DaemonRpcProxy` to `IpcEventChannel`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/673)

Add IPC events for manipulating the account

---

CHANGELOG.md

I went through the merged PRs and found a few that I thought affected behavior but was not mentioned in the changelog. So I added them. I want your feedback on if these should be added or not, and their formulation. And/or if you know anything else that changed that I missed to mention.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/675)

Update changelog with not yet mentioned changes

---

appveyor_gui.yml

Git checklist:
This PR adds a build phase to Appveyor tasks to make sure that there are no errors when transpiling TypeScript. This is equivalent to building the project for release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/687)

Transpile TS on appveyor

---

README.md
gui/packages/components/package.json
gui/packages/desktop/package.json
gui/packages/desktop/src/renderer/components/AdvancedSettings.tsx
gui/packages/desktop/src/renderer/components/AdvancedSettingsStyles.tsx
gui/packages/desktop/src/renderer/components/Cell.tsx
gui/packages/desktop/src/renderer/containers/AdvancedSettingsPage.tsx
gui/yarn.lock

Git checklist:
1. Refactor `AdvancedSettings`
2. Update TS to 3.3.3 - No action required
3. Update README.md to reflect the recent changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/689)

Improve advanced settings

---

talpid-core/src/dns/linux/network_manager.rs

Just fixing a tiny spelling error pointed out by Richard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/695)

Fix minor spelling "managing"

---

CHANGELOG.md
mullvad-daemon/src/lib.rs
windows/windns/src/windns/dnsagent.cpp
windows/windns/src/windns/dnsagent.h

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/704)

Windns improve error handling

---

windows/windns/src/windns/windnscontext.cpp
windows/winfw/src/winfw/fwcontext.cpp
windows/winfw/src/winfw/rules/restrictdns.cpp
windows/winfw/src/winfw/rules/restrictdns.h

This PR fixes the small faults left by my recent PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/715)

Fix Emil's bad cpp

---

build.sh

The build server broke because of broken build script. I think this should be the correct new path?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/717)

Update package.json path in build.sh

---

talpid-core/src/tunnel/wireguard/wireguard_go.rs

There was an issue with the tunnel not getting shut down properly if it fails to connect because the first ping times out. So now I've made sure that the appropriate FFI calls are made when the tunnel is shut down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/728)

Stop wireguard-go tunnel on drop

---

gui/locales/README.md
gui/scripts/crowdin.sh
gui/scripts/update-translations.sh
gui/src/shared/gettext.ts

Git checklist:
This PR adds a shell script to sync the Crowdin translations and adjusts the existing gettext integration to support the naming convention for gettext catalogues used by Crowdin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/729)

Crowdin integration

---

README.md
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/shared/ipc-event-channel.ts

Git checklist:
This PR adds a switch to toggle the UI language using the `MULLVAD_LOCALE` environment variable. 
For testing the UI in different languages.
The UI picks up the language either from `MULLVAD_LOCALE` or from the system using Electron facilities, i.e `app.getLocale()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/731)

Add ui language env switch

---

dist-assets/windows/installer.nsh
windows/nsis-plugins/src/log/log.cpp
windows/nsis-plugins/src/log/log.def
windows/nsis-plugins/src/log/log.vcxproj

These changes extend the installer log file with information about the system's Windows edition and exact version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/735)

Installer log, add Windows version

---

gui/src/renderer/components/NavigationBar.tsx

Git checklist:
This PR improves the navigation bar to be more resilient when it comes to displaying long labels.
Because some of the languages have long words that cause the title view to overlap with other UI elements inside of the navigation bar.
Just like it used to be, the navigation bar will attempt to align the title view in the middle. However in situations when it's simply impossible to achieve, the navigation bar will push the title view to prevent the overlap with buttons. 
When a title view does not have enough space to display the text, it will chop the text and add a trailing ellipsis. 
See the screenshots below that demonstrate the described behavior:
--- …

Improve the navigation bar resilience

---

gui/assets/css/global.css
gui/src/renderer/components/Settings.tsx
gui/src/renderer/components/SettingsHeader.tsx
gui/src/renderer/components/SettingsStyles.tsx
gui/src/renderer/index.html

Git checklist:
1. Remove a temporary CSS fix that we used up until the placeholder color support landed in ReactXP. (long ago)
1. Adjust the line height for the title label in SettingsHeader to fix the huge spacing between the lines. (See the screenshots below)
<table>
<tr>
<th align="center">Before</th>
<th align="center">After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
1. Fix the version label in Settings to never break because it's normally very short.
<table>
<tr>
<th align="center">Before</th>
<th align="center">After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
1. Remove the unused `#app` ID from the root container DIV. The `.app-container` is used by ReactXP instead and …

UI adjustments for upcoming localizations

---

gui/src/renderer/app.tsx

A small PR to sort relay list countries and cities lexicographically in GUI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/753)

Sort relay list countries and cities by name in GUI

---

gui/src/renderer/app.tsx

Slight improvement to the way the city and country names are sorted - with this sorting method, the strings will be compared appropriately for the current locale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/757)

Improve alphabetical sorting in GUI

---

mullvad-daemon/src/relays.rs

I've changed the code that reads the relay list from disk to prefer the newer version rather than always using the cached one.
I tested that this actually works on all 3 platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/765)

Use the most up-to-date relay list file

---

README.md
gui/package.json
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AdvancedSettingsStyles.tsx
gui/src/renderer/components/Cell.tsx
gui/yarn.lock

Git checklist:
This PR upgrades electron-builder and removes the spacer view in advanced settings in favour of using `style` attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/770)

Small fixes

---

Cargo.lock
talpid-core/Cargo.toml
talpid-core/src/firewall/linux.rs

Upgrade `nftnl` to what we just merged in https://github.com/mullvad/nftnl-rs/pull/21
Also got rid of `error_chain!` in this module while I was at it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/794)

Upgrade nftnl and get rid of one error_chain!

---

talpid-ipc/src/lib.rs

If the thread we start that runs `tokio::run(fut)` stops before a message is sent on the `start` channel, then the channel is cancelled. This for example happens if `tokio::run` fails to create the runtime. This leads to the `expect("server panicked")` panicking the current thread and later the main thread of the daemon panics because of this.
With this tiny fix the panic is turned into an error. So a proper `Err` is returned from `IpcServer::start_with_metadata` instead. This does not solve the root problem. But at least the daemon can log the error chain and handle everything much better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/808)

Map an error instead of panicing when starting tokio runtime

---

CHANGELOG.md
windows/windns/src/windns/netsh.cpp

As above. From 3 to 10 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/810)

Increase timeout when updating DNS settings

---

.gitignore
gui/package-lock.json
gui/package.json
gui/src/main/index.ts
gui/src/shared/gettext.ts

Git checklist:
This PR upgrades Electron to v4.1.4 and NSEventmonitor which will soon have prebuilt binaries available for Electron 4.x.
We need to test this seemingly small PR and produce artefacts for all possible OSes to make sure that this stuff works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/805)

Upgrade to Electron 4.1.4

---

gui/locales/messages.pot
gui/src/config.json
gui/src/renderer/app.tsx
gui/src/renderer/components/ErrorBoundary.tsx
gui/src/renderer/components/Support.tsx

Git checklist:
This PR adds error boundary to catch and log all errors originating from React componetns and display a custom view to inform the user that something bad happened.
It looks like this, but I'd appreciate any input on how to make it look more alarming I'd say :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/809)

Add error boundary

---

gui/locales/de/relay-locations.po
gui/locales/es/relay-locations.po
gui/locales/fr/relay-locations.po
gui/locales/relay-locations.pot
gui/locales/sv/relay-locations.po
gui/locales/zh-TW/relay-locations.po
gui/scripts/integrate-into-app.py

Git checklist:
This PR updates `relay-locations.pot` based on the most recent changes in the relays list. Also adds some logging around the command we run in the `integrate-into-app` script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/817)

 Update relay-locations

---

gui/package-lock.json
gui/package.json
gui/src/renderer/components/Cell.tsx

Git checklist:
Running `npm audit` today left me petrified – 11 vulnerabilities (10 of them - code injection)
So basically `npm` suggested to update `electron-builder` to the `20.40.2` pre-release. Also `tslint` had the same vulnerable dependency so I've updated it along with its "plugins".
Since `electron-builder`'s changelog referenced NSIS, I figured Odd could have a look at it to see if this update may cause any issues.
https://github.com/electron-userland/electron-builder/releases
```
➜  gui git:(update-electron-builder) ✗ npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ …
```

Update dependencies to fix the security vulnerabilities

---

mullvad-cli/src/cmds/tunnel.rs
mullvad-daemon/src/relays.rs
mullvad-types/src/relay_constraints.rs
mullvad-types/src/settings.rs
talpid-types/src/net/openvpn.rs

Some various cleanup I found when working on integrating bridges. I thought I should get this merged asap instead of having them laying around in my branch. Will minimize risk of rebase problems in my actual feature branch, and will make that PR more focused on the feature itself.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/826)

Misc cleanup before bridges

---

gui/package-lock.json
gui/package.json
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/shared/logging.ts
gui/test/setup/main.js
gui/test/setup/renderer.ts

Git checklist:
1. Bump `electron-log` to v3.0.5
1. With v3, the logging has to be initialised on per process basis
1. Log each Electron process to separate file because of certain difficulties surrounding the v3 update
1.1 `frontend.log` - main process
1.1 `frontend-renderer.log` - renderer process
1. Move all log related functions to `shared/logging.ts`
1. Only the main process makes sure to backup old log files and create the necessary folders
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/827)

Update electron-log @ v3

---

gui/locales/de/messages.po
gui/locales/de/relay-locations.po
gui/locales/es/messages.po
gui/locales/es/relay-locations.po
gui/locales/fr/messages.po
gui/locales/fr/relay-locations.po
gui/locales/messages.pot
gui/locales/sv/messages.po
gui/locales/sv/relay-locations.po
gui/locales/zh-TW/messages.po
gui/locales/zh-TW/relay-locations.po
gui/scripts/README.md
gui/scripts/extract-translations.js

Git checklist:
This PR cleans up the file references after extracting the translations from the source code. This should likely result in less noise in git diffs in the future, when updating translations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/830)

Remove file refs in pot

---

gui/electron-builder.yml
gui/package-lock.json
gui/package.json
gui/tsconfig.json

Git checklist:
This PR updates TypeScript to 3.4 and enables incremental build that speed up subsequent builds.
More on this here: https://devblogs.microsoft.com/typescript/announcing-typescript-3-4/#faster-subsequent-builds-with-the---incremental-flag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/842)

Update to 3.4 and enable incremental builds

---

ci/buildserver-build.sh

This should improve the security of the build servers, as well as the ergonomics of restarting them.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/863)

More wholesome signing solution

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs

For Android to use `mullvad-daemon` as a library, it needs two interfaces. The first one is a way to send daemon commands, which was implemented by a previous PR. The second is a way to listen for daemon events. This PR implements this second interface.
Previously, both interfaces were tightly coupled to the management interface. On Android, that management interface isn't necessary. Therefore, a generic parameter was added to the daemon that can is constrained to a new `EventBroadcaster` trait. Implementations of such trait provide a way to handle notification of daemon events.
A separate constructor can be used to specify a custom `EventBroadcaster`. It is also possible to not specify one, which keeps the previous behavior of using the management interface (through the usage of a …

Create `EventBroadcaster` trait

---

Cargo.lock
android/src/main/kotlin/net/mullvad/mullvadvpn/LoginFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/AccountData.kt
mullvad-jni/Cargo.toml
mullvad-jni/src/daemon_interface.rs
mullvad-jni/src/from_java.rs
mullvad-jni/src/into_java.rs
mullvad-jni/src/lib.rs

This PR prepares some basic infrastructure for communicating with the daemon thread. A simple RPC call is implemented to get the account data, and is used to verify the account token during login.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/868)

Account verification during login on Android

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
mullvad-jni/src/daemon_interface.rs
mullvad-jni/src/lib.rs

This PR implements the operations to request to connect and disconnect the tunnel on Android. Note that the screen isn't yet updated based on the events sent by the daemon.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/873)

Control the tunnel on Android

---

CHANGELOG.md
windows/winfw/src/winfw/fwcontext.cpp
windows/winfw/src/winfw/mullvadguids.cpp
windows/winfw/src/winfw/mullvadguids.h
windows/winfw/src/winfw/rules/blockall.cpp
windows/winfw/src/winfw/rules/permitdhcp.cpp
windows/winfw/src/winfw/rules/permitdhcp.h
windows/winfw/src/winfw/rules/permitdhcpserver.cpp
windows/winfw/src/winfw/rules/permitdhcpserver.h
windows/winfw/src/winfw/rules/permitlan.cpp
windows/winfw/src/winfw/rules/permitlanservice.cpp
windows/winfw/src/winfw/rules/permitloopback.cpp
windows/winfw/src/winfw/rules/permitndp.cpp
windows/winfw/src/winfw/rules/permitndp.h
windows/winfw/src/winfw/rules/permitvpntunnel.cpp
windows/winfw/src/winfw/rules/permitvpntunnelservice.cpp
windows/winfw/src/winfw/rules/restrictdns.cpp
windows/winfw/src/winfw/winfw.vcxproj
windows/winfw/src/winfw/winfw.vcxproj.filters

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/860)

Windows firewall updates (mDNS, NDP, etc)

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-types/src/location.rs
mullvad-types/src/relay_constraints.rs
mullvad-types/src/relay_list.rs
mullvad-types/src/settings.rs

This PR adds bridges to the relay list and functionality to select bridges based on constraints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/864)

Shadowsocks bridges in relay list

---

gui/package-lock.json
gui/package.json

Git checklist:
This PR fixes the security vulnerability found in axios, one of the dependencies of browser-sync [dev].
https://nvd.nist.gov/vuln/detail/CVE-2019-10742
https://github.com/axios/axios/issues/2164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/895)

Patch CVE-2019-10742 in axios via browser-sync

---

mullvad-daemon/src/relays.rs

This PR starts an implementation for selecting among Wireguard and OpenVPN endpoints when `Constraint::Any` is set. The algorithm is to generate a random number and use it to select either an OpenVPN endpoint or a Wireguard endpoint, depending on which range the number lands on.
Currently the range is limited by platform. On Android, only Wireguard tunnels are selected and on all other platforms only OpenVPN tunnels are selected. The plan is to tweak the range to include both tunnel types for the desktop in the future.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/893)

Select Wireguard tunnels on Android

---

gui/src/main/index.ts

Your own commit on logging an error in the frontend
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/901)

Log deserialization error

---

gui/package-lock.json
gui/package.json

Git checklist:
This PR update browser-sync to fix the vulnerability found in its nested dependency: `axios`. 
Browser-sync PR: https://github.com/BrowserSync/browser-sync/pull/1697
https://npmjs.com/advisories/880
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/906)

Update browser-sync to fix the vulnerability found in axios

---

talpid-core/src/dns/linux/network_manager.rs

I've added extra checks in the `NetworkManager` DNS implementation to check if the DNS management mode allows us to set DNS globally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/907)

Improve NetworkManager compatibility.

---

android/src/main/AndroidManifest.xml
android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt

This PR started as an investigation and attempt to fix crashes caused by rotating the screen on Android. The root cause was that the daemon thread was started every time the `MainActivity` was created, but when rotating the device the activity was destroyed and recreated without stopping the daemon thread, so two instances entered a conflict leading to a crash. More specifically, the second thread would crash when attempting to start the logger again.
Three solutions were possible:
1. Preventing screen rotation. This is the simplest solution, but doesn't fix the root cause.
2. Stopping the daemon thread when the activity is destroyed. This fixes the root cause, but leads to the undesired behavior of disconnecting the tunnel.
3. Only starting the thread if it hasn't started already.
While …

Run the daemon thread in an Android service

---

CHANGELOG.md

I went through the git history and compared with the changelog. Making sure nothing was missing ahead of the release. Most changes were tiny cosmetic changes. But I also added two larger entries.
* The one about improving NetworkManager probing.
* Re-write the shadowsocks support entry to be more generic about the app supporting automatic shadowsocks rather than specific about one setting in the UI.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/908)

Slightly update the changelog ahead of release

---

CHANGELOG.md
gui/locales/de/messages.po
gui/locales/de/relay-locations.po
gui/locales/es/messages.po
gui/locales/es/relay-locations.po
gui/locales/fr/messages.po
gui/locales/fr/relay-locations.po
gui/locales/it/relay-locations.po
gui/locales/ja/messages.po
gui/locales/ja/relay-locations.po
gui/locales/messages.pot
gui/locales/nl/messages.po
gui/locales/nl/relay-locations.po
gui/locales/no/messages.po
gui/locales/no/relay-locations.po
gui/locales/pt/messages.po
gui/locales/pt/relay-locations.po
gui/locales/relay-locations.pot
gui/locales/ru/messages.po
gui/locales/ru/relay-locations.po
gui/locales/sv/messages.po
gui/locales/tr/messages.po
gui/locales/tr/relay-locations.po
gui/locales/zh-TW/messages.po
gui/locales/zh-TW/relay-locations.po

Git checklist:
This PR adds norwegian translations and brings the rest of translations up to date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/922)

Add norwegian translations and update existing ones

---

android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/AccountFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/RemainingTimeLabel.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/SettingsFragment.kt
android/src/main/res/anim/fragment_enter_from_right.xml
android/src/main/res/anim/fragment_exit_to_right.xml
android/src/main/res/anim/fragment_half_enter_from_left.xml
android/src/main/res/anim/fragment_half_exit_to_left.xml
android/src/main/res/drawable/cell_button_background.xml
android/src/main/res/drawable/icon_back.xml
android/src/main/res/drawable/icon_chevron.xml
android/src/main/res/layout/account.xml
android/src/main/res/layout/settings.xml
android/src/main/res/values/colors.xml
android/src/main/res/values/plurals.xml
android/src/main/res/values/strings.xml

This PR adds the Account screen present in the Settings menu. The Settings menu is updated to have a clickable entry with the Account's remaining time. A new fragment is created for the Account screen, containing the Account number and its expiration date. The data is managed by an `AccountCache` helper class.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/921)

Account screen on android

---

README.md
android/proguard-rules.pro

Add instructions for how to build on Android. First dependencies and how to set up the build toolchain. Then some build instructions.
I think this covers most of what we discussed today and the problems I ran into. Hopefully it should work to follow these steps for someone trying from scratch.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/929)

Add install and toolchain setup instructions for Android

---

gui/locales/messages.pot
gui/src/renderer/components/ConnectionInfo.tsx
gui/src/renderer/components/ConnectionInfoDisclosure.tsx

Git checklist:
This PR refactors the connection info panel and removes the fixed width from the In and Out labels which was causing layout issues in different languages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/933)

Fix in and out label width in connection info panel

---

windows/windns/src/windns/windns.rc
windows/winfw/src/winfw/winfw.rc
windows/winnet/src/winnet/winnet.rc

Mainly to correct the winnet module's description. I also updated the copyright year since I believe all of these modules have been changed recently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/943)

Update version information in C++ DLLs

---

Cargo.lock

As per the title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/955)

Update Cargo.lock to use updated netlink library

---

mullvad-problem-report/src/lib.rs

We had a bug where we called `metadata::collect()` both in the collect and the send stages of the problem report. Yielding two completely different UUIDs. This caused a bit of a mess on the support side since the UUIDs did not match.
Fixed by parsing all metadata from the reports when sending instead of assuming `metadata::collect()` is idempotent and calling it multiple times.
It still falls back to calling `metadata::collect()` if it fails parsing it from the input report.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/960)

Parse problem report metadata from file

---

CHANGELOG.md

Looking at the git history it seems these changes are user facing but not mentioned.
We still don't mention the automatic wireguard key generation. But given that we are not yet sure if/how it will be active in the actual release we can add that when we have better knowledge what will make it to the release.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/963)

Add missing items to changelog

---

CHANGELOG.md
gui/locales/README.md
gui/locales/de/messages.po
gui/locales/de/relay-locations.po
gui/locales/es/messages.po
gui/locales/es/relay-locations.po
gui/locales/fr/messages.po
gui/locales/fr/relay-locations.po
gui/locales/it/messages.po
gui/locales/it/relay-locations.po
gui/locales/ja/messages.po
gui/locales/ja/relay-locations.po
gui/locales/nl/messages.po
gui/locales/nl/relay-locations.po
gui/locales/no/messages.po
gui/locales/no/relay-locations.po
gui/locales/pt/messages.po
gui/locales/pt/relay-locations.po
gui/locales/ru/messages.po
gui/locales/ru/relay-locations.po
gui/locales/sv/messages.po
gui/locales/sv/relay-locations.po
gui/locales/tr/messages.po
gui/locales/tr/relay-locations.po
gui/locales/zh-CN/messages.po
gui/locales/zh-CN/relay-locations.po
gui/locales/zh-TW/messages.po
gui/locales/zh-TW/relay-locations.po

Integrate the latest translations from Crowdin.
* Adds the new language: Simplified Chinese
* Adds the new strings and a few new locations for all languages
* Add some translation README instructions to make the process easier to follow.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/971)

Integrate translations

---

mullvad-jni/src/lib.rs

This PR changes the `mullvad-jni` initialization so that logging is only configured once, the class references are only loaded once, and an exception is thrown back to the calling Java code if logging fails to be configured. Without the exception, the code would previously panic without producing any helpful output. The exception still causes the app to crash, but at least the error cause is logged by the Android app.
These changes fix a crash that happened in some rare cases, where the app wouldn't open again after an unrelated crash had occurred.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/988)

Improve `mullvad-jni` initialization

---

CHANGELOG.md
Cargo.lock
mullvad-daemon/Cargo.toml
mullvad-daemon/src/account_history.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/system_service.rs

I've been a bit too quick to merge the `factory-reset` feature, as the CLI wouldn't wait until the daemon would restart, and it would not work out on Android at all. With these changes, I aim to fix the shortcomings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/984)

Fix factory-reset RPC

---

android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/ConnectionProxy.kt

This PR fixes a bug where selecting the same location twice in the relay list while connected would lead the UI into an inconsistent state. The cause was that the UI would try to anticipate the state change to "Connecting" before actually receiving the event in order to present quick user feedback. However, if the new relay constraint didn't change anything in settings, the daemon thread would never actually enter the "Connecting" state, so the UI would get stuck in the "Pre-connecting" state.
The fix implemented here is to guard both "anticipation" state changes, so that there's a check to see if changing the state makes sense. If it does, the state is anticipated and the request to change state made. Otherwise, the request that would be ignored by the daemon is also ignored by the UI. …

Add UI state anticipation guards

---

windows/nsis-plugins/src/log/logger.cpp
windows/nsis-plugins/src/log/logger.h

Now using same format as used in `daemon.log`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1013)

Change timestamp format in 'install.log'

---

gui/src/renderer/components/NotificationArea.tsx

Adding more error details on Windows if managing the firewall fails.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1029)

Add message about third party software on Windows

---

gui/package-lock.json
gui/package.json

Git checklist:
This PR updates `electron-builder` to the latest (`21.2.0`). Seems to work just fine out of box on macOS. 
Could you please test if installer properly builds and runs on Debian? I'll give it a spin on Windows on Monday.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1047)

Update electron-builder to 21.2.0

---

gui/src/main/jsonrpc-client.ts

Git checklist:
* [X ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)
I've spotted that the `close` handler was called twice, first when the socket connection is lost, second time when attempting to reconnect. 
The reason for that is because the app would always attempt to close the socket before reconnecting, and since the `SocketTransport.connection` would still be set, it would proceed to calling `onClose` the second time, this time around without any error. 
No biggie but it's kinda weird that we would tell the delegate that we've lost the connection in the first place, and then that we've kinda got it closed the second time which is …

Fix the double call of "close" handler

---

talpid-core/src/routing/android.rs

This PR changes the stub `RouteManagerImpl` on Android to live as long as it's expected by the cross-platform code. Previously it would just drop the sender, which led to some error messages being present in the log file. Now it will correctly wait for a shutdown event to be received before it finishes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1059)

Improve Android `RouteManagerImpl` stub

---

gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/shared/daemon-rpc-types.ts

Git checklist:
This is the first step to supporting the bridge location in the UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1073)

Add set_bridge_settings RPC call

---

android/src/main/kotlin/net/mullvad/mullvadvpn/WireguardKeyFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/PublicKey.kt
android/src/main/res/layout/wireguard_key.xml
android/src/main/res/values/strings.xml
mullvad-jni/src/into_java.rs
mullvad-jni/src/lib.rs

This PR adds a small TextView displaying the age of the currently set WireGuard key in the WireGuard key fragment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1086)

Android show key age

---

gui/src/renderer/app.tsx

Git checklist:
This PR sorts relays by hostname

Sort relays

---

gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/CityRow.tsx
gui/src/renderer/components/CountryRow.tsx
gui/src/renderer/components/RelayRow.tsx
gui/src/renderer/components/RelayStatusIndicator.tsx
gui/src/renderer/components/SelectLocation.tsx
gui/src/renderer/components/SelectLocationStyles.tsx
gui/src/renderer/containers/AdvancedSettingsPage.tsx
gui/src/renderer/containers/SelectLocationPage.tsx
gui/src/shared/bridge-settings-builder.ts
gui/src/shared/ipc-event-channel.ts
gui/src/shared/relay-location-builder.ts
gui/src/shared/relay-settings-builder.ts
gui/test/relay-settings-builder.spec.ts

Git checklist:
1. Reset the bridge constraints to `any` when bridge state is changed to `auto` or `off`
1.  Hack together the `Closest to exit server` option at the top of the list of bridge locations. The equivalent for that is setting the bridge constraints to `any`.

Add bridge location reset

---

dist-assets/windows/installer.nsh
gui/tasks/distribution.js

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1117)

Windows: Fix installer registry paths

---

gui/src/renderer/components/BridgeLocations.tsx
gui/src/renderer/components/ExitLocations.tsx
gui/src/renderer/components/LocationList.tsx
gui/src/renderer/components/SelectLocation.tsx

Git checklist:
That's an attempt to break down the SelectLocation view on multiple smaller components that we can compose together to produce two sets of lists:
1. Special locations, like "Closest to exit"
2. Relay locations tree
Additionally this PR takes a snapshot of each tab respectively and restores the expanded elements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1119)

Refactor SelectLocation

---

CHANGELOG.md
gui/src/renderer/app.tsx
gui/src/renderer/components/LocationList.tsx
gui/src/renderer/components/TunnelControl.tsx
gui/src/renderer/containers/ConnectPage.tsx

Git checklist:
1. Sort relay locations *after* translating the relay locations list
2. Translate locations only once when receiving the relay list. This makes sure that no other controls in the app need to call to gettext.
3. Update translations template (POT).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1122)

Fix relay list sorting

---

gui/locales/de/messages.po
gui/locales/es/messages.po
gui/locales/fr/messages.po
gui/locales/it/messages.po
gui/locales/ja/messages.po
gui/locales/messages.pot
gui/locales/nl/messages.po
gui/locales/no/messages.po
gui/locales/pt/messages.po
gui/locales/ru/messages.po
gui/locales/sv/messages.po
gui/locales/tr/messages.po
gui/locales/zh-CN/messages.po
gui/locales/zh-TW/messages.po
gui/locales/zh-TW/relay-locations.po

Update all translations for the coming 2019.8 release. City and country names were ignored for this release, since I don't think we added many locations.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1127)

Update translations for 2019.8

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/ApplicationConfiguration.swift
ios/MullvadVPN/RelayCache.swift
ios/MullvadVPN/RelayList.swift
ios/MullvadVPN/SelectLocationController.swift

Git checklist:
This PR adds a relay cache that stores relays on disk that maintains a `relays.json` in a shared container on iOS. 
The `relays.json` file is automatically updated every hour upon the read access, it felt like the easiest way to keep it up to date so far because both processes (the tunnel and the GUI app) will be accessing it so there is really no central place to keep it up to date.
A shared container is supposed to be a sandbox extension for the file system and can be accessed by both processes (Tunnel and the GUI app). I utilise a file coordinator to make sure that all reads and writes are atomic across processes.
--- …

Add RelayCache

---

talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/ping_monitor.rs

While testing on Android, I noticed that there a few dozen pinger threads running. It seems to have triggered the perfect storm for pinger threads to not stop when the tunnel is disconnected as it usually does. The pinger would previously only stop when a ping fails, but the test scenario connects and disconnects on a fixed interval, and the interval seemed to be within the window for previous pinger threads to receive a response after the tunnel disconnected and connected again.
This PR adds a `mpsc::Sender<()>` to notify the pinger thread to stop when it's no longer needed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1141)

Stop ping monitor when it's no longer necessary

---

gui/src/renderer/components/Selector.tsx

Git checklist:
This PR fixes the missing title labels under advanced settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1149)

Fix missing section titles

---

CHANGELOG.md
dist-assets/windows/installer.nsh
windows/nsis-plugins/nsis-plugins.sln
windows/nsis-plugins/src/pathedit/dllmain.cpp
windows/nsis-plugins/src/pathedit/pathedit.cpp
windows/nsis-plugins/src/pathedit/pathedit.def
windows/nsis-plugins/src/pathedit/pathedit.vcxproj
windows/nsis-plugins/src/pathedit/pathedit.vcxproj.filters
windows/nsis-plugins/src/pathedit/stdafx.cpp
windows/nsis-plugins/src/pathedit/stdafx.h
windows/nsis-plugins/src/pathedit/targetver.h

Adds the resource/ dir to PATH when installing and removes it when uninstalling.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1160)

Add CLI to PATH on Windows

---

CHANGELOG.md
windows/winnet/src/winnet/netmonitor.cpp

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1166)

Win adjust offline logic

---

gui/src/renderer/components/CountryRow.tsx

Git checklist:
Selected countries in the relay list do not show the green highlight. This is a regression since last release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1169)

Add missing .selected prop

---

gui/src/config.json

The updated FAQ URL got lost in a rebase, so here it is, reintroduced anew.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1174)

Change FAQ URL

---

gui/src/renderer/app.tsx

Use bridge list instead of relay list when constructing bridges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1180)

Use bridge list to display bridges, not relays

---

CHANGELOG.md

Fine tuning the changelog before the release. Adding some stuff I saw in git that I thought might make sense to mention. Also fixing some small stuff in existing entries where I thought appropriate. Please leave feedback if you don't agree or have a better idea.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1177)

Fine tune changelog for 2019.9-beta1

---

CHANGELOG.md
mullvad-cli/src/cmds/account.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-ipc-client/src/lib.rs
mullvad-rpc/src/lib.rs
mullvad-types/src/account.rs

As per the title, adding a new RPC to submit vouches in the daemon and exposing it in the CLI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1181)

Add RPC to redeem vouchers

---

gui/package-lock.json
gui/package.json

Git checklist:
Since we don't use `run-s` and `run-p` anymore in our `package.json` scripts, we don't need `npm-run-all` anymore.
This PR simply removes the package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1187)

Remove unused dependency: npm-run-all

---

.travis.yml
README.md
appveyor_gui.yml
build.sh
gui/package-lock.json
gui/package.json
prepare_release.sh
version_metadata.sh

Git checklist:
Since @DMarby published nseventmonitor for us, we can actually now reference it directly from npm which should enable us to use `npm ci` to install deps on CI.
https://www.npmjs.com/package/nseventmonitor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1183)

Install nseventmonitor from NPM

---

talpid-core/src/firewall/windows.rs

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1200)

Fix Rust code (short term) that receives error messages from 'winfw'

---

gui/src/renderer/app.tsx

A user reported we use the wrong spelling for German in German :)
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1202)

Change Deutsche to Deutsch

---

gui/scripts/extract-geo-data.py
gui/scripts/integrate-into-app.py
gui/src/renderer/app.tsx

Git checklist:
This PR moves the country name into `relay-locations.pot`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1203)

Move country name into relay-locations.pot

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/NotificationBanner.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/WireguardKeyFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/KeyStatusListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/WwwAuthTokenRetriever.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/BlockingController.kt
android/src/main/res/layout/wireguard_key.xml
android/src/main/res/values/strings.xml
mullvad-jni/src/daemon_interface.rs
mullvad-jni/src/lib.rs

This PR allows users to login to their accounts on our website automatically from the Android application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1198)

Use auth tokens in URLs to get to WireGuard key page

---

CHANGELOG.md
dist-assets/windows/installer.nsh

Install Wintun the recommended way, by including an .msi file generated for the Mullvad app. Described [here](https://git.zx2c4.com/wintun/about/msi-example/README.md). This avoids conflicts with other programs using Wintun.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1212)

Install Wintun

---

README.md
docs/architecture.md
docs/security.md

We decided to improve the documentation of our product. If the entire team does documentation at the same time it's a very high chance we do quite some double work and quite some git conflicts. So we at least need to get the fundamentals in place. Which documents should exist and roughly what sections they should contain.
Do you agree these documents make sense, and their headers? What more should we write about?
When these documents are populated we can link to them from the README. I did not feel I should do this already, since I did not know where in the README the links will fit in. That will probably be more apparent after some sections of the README has moved over to here.
--- …

Bootstrap documentation improvement process

---

windows/nsis-plugins/nsis-plugins.sln
windows/nsis-plugins/src/driverlogic/context.cpp
windows/nsis-plugins/src/pathedit/pathedit.vcxproj

Correcting some issues in the code that prevented me from building locally.
The dependency issues would sometimes allow the code the be built anyway, because the solution projects aren't being built in a deterministic order.
The return statements I have no idea how these are able to compile on CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1241)

Fix dependency issues

---

CHANGELOG.md
windows/windns/src/windns/windns.cpp

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1244)

Windows: Restrain DNS assignment

---

CHANGELOG.md
Cargo.lock
mullvad-daemon/Cargo.toml
mullvad-daemon/src/system_service.rs

Adjust settings for service recovery actions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1245)

Windows: Adjust service settings

---

CHANGELOG.md
dist-assets/windows/installer.nsh

Changes:
* New TAP driver fixes some resume/suspend issues on Windows.
* Fix TAP renaming issue on upgrades.
* Update OpenVPN and OpenSSL library binaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1246)

Update TAP driver and binaries submodule

---

README.md

Reflect in the feature matrix that we now support WireGuard on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1264)

Update feature matrix

---

CHANGELOG.md
windows/winnet/src/winnet/offlinemonitor.cpp

As above. Additional inline comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1266)

Windows: Adjust adapter filter in offline logic

---

ios/MullvadVPN/KeychainError.swift
ios/MullvadVPN/RelayConstraints.swift
ios/MullvadVPN/TunnelConfiguration.swift
ios/MullvadVPN/TunnelConfigurationCoder.swift
ios/MullvadVPN/TunnelConfigurationManager.swift
ios/MullvadVPN/WireguardPrivateKey.swift

Git checklist:
1. Add `TunnelConfiguration` that contains `RelayConstraints` and `WireguardPrivetKey`
1. Add `TunnelConfigurationCoder` for encoding and decoding the `TunnelConfiguration` from into the data blob. I use JSON behind the scenes for simplicity.
1. Add `TunnelConfigurationManager` to be able to access and store serialised `TunnelConfiguration` bound by _Service name_ and _Account token_. Apart from that, this manager provides facilities for producing and accessing the stored data in Keychain across processes using _persistent keychain references_.
1. Add structures to express basic `RelayConstraints`. Only `RelayLocation` constraint is supported at the moment.
---
This change …

Add tunnel configuration

---

ios/MullvadVPN/PacketTunnelIpc.swift
ios/MullvadVPN/ReplaceNilWithError.swift

Git checklist:
1. Add Tunnel IPC for communication between the GUI app the Packet tunnel process (which is going to be added in the coming PRs)
1. Add extension to Combine framework's `Publisher` to be able to replace `nil` elements in streams with `Error`s. 
Combine is a new framework from Apple that provides means for processing and transforming values over time, in a declarative fashion using the same familiar `map`, `flatMap`, `collect` operators (and so forth). 
Operations are more imperative approach and heavy and I think we'll be transitioning away from them where possible. However Operations are also very powerful because of their dependency resolution system, so I think both approaches …

Add PacketTunnel IPC

---

ios/MullvadVPN/MutuallyExclusive.swift
ios/MullvadVPN/RelayCache.swift

Git checklist:
1. Migrate `RelayCache` to use Combine framework
1. Add `MutuallyExclusive` publisher to be able to chain publishers in sequence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1293)

Migrate RelayCache to Combine

---

gui/src/renderer/components/WireguardKeys.tsx

As instructed by Kat :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1296)

Update text shown in WireGuard key view while blocked

---

talpid-core/src/routing/windows.rs

This should fix the race condition with us waiting for the thread to terminate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1306)

Fix race condition for routing manager

---

ios/MullvadVPN/Base.lproj/Main.storyboard
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/CustomButton.swift
ios/MullvadVPN/RootContainerViewController.swift
ios/MullvadVPN/SegueIdentifier.swift
ios/MullvadVPN/TunnelControlViewController.swift
ios/MullvadVPN/UIColor+Palette.swift

Git checklist:
This PR wires up the "Connect" controller with `TunnelManager`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1324)

Wire up "Connect" controller

---

ios/MullvadVPN/RelayStatusIndicatorView.swift
ios/MullvadVPN/SelectLocationCell.swift
ios/MullvadVPN/SelectLocationController.swift

Git checklist:
1. Highlight the selected location in Select Location controller
1. Scroll to selected location
1. Show spinner while loading relays
1. Introduce "disabled" style for inactive locations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1330)

Show selected location on iOS

---

android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/Relay.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountInputContainer.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConfirmNoEmailDialogFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RemainingTimeLabel.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt

This PR includes a number of small fixes to the Kotlin code to reduce warnings and remove obsolete and unused code.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1328)

Fix some small issues in Kotlin code

---

windows/nsis-plugins/src/driverlogic/context.cpp

Minor update to provide more information in case of failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1348)

Add more logging to driverlogic

---

README.md
docs/security.md
talpid-core/src/firewall/mod.rs

This is currently an initial draft of the security documentation. At the time of writing this it does not yet contain anything on platform specific deviations. I want some feedback on the content and overall layout and structure before I dig too deep.
It's probably easiest to read this in the [Rendered version](https://github.com/mullvad/mullvadvpn-app/blob/security-docs/docs/security.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1282)

Add security documentation

---

ios/MullvadVPN/Base.lproj/Main.storyboard
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/RelayConstraints.swift
ios/MullvadVPN/SelectLocationController.swift

Git checklist:
iOS 13 introduced a set of classes that automatically animate the changes in data source of table views. This PR migrates the "Select location" view to these new classes. Keeps code a lot cleaner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1380)

Use diffable datasource in Select location view

---

ios/MullvadVPN/AccountViewController.swift
ios/MullvadVPN/Base.lproj/Main.storyboard

Git checklist:
This PR adds a feature where tapping on the account token in Account view copies the token into pasteboard (aka clipboard) and temporarily turns the label into "Copied ...".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1381)

Add function to copy account token to pasteboard

---

mullvad-daemon/src/windows_exception_logging.rs

The file is saved in `%LOG_PATH%\DAEMON.DMP`.
Related: #1252 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1353)

Generate a minidump for unhandled SEH exceptions

---

mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-problem-report/Cargo.toml
talpid-openvpn-plugin/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1393)

Update copyright notices

---

windows/libshared/src/libshared/logging/logsinkadapter.cpp
windows/nsis-plugins/src/cleanup/cleaningops.cpp
windows/nsis-plugins/src/driverlogic/driverlogic.cpp
windows/nsis-plugins/src/tray/tray.cpp
windows/windns/src/windns/netsh.cpp
windows/windns/src/windns/netsh.h
windows/winnet/src/winnet/winnet.cpp
windows/winutil/src/winutil/winutil.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1404)

Refactor ValueMapper and process headers in libcommon

---

.gitmodules
mullvad-daemon/src/system_service.rs

No longer required as we're only using Microsoft's testing framework.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1422)

Remove submodule googletest

---

ios/BuildInstructions.md
ios/ExportOptions.plist
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/build.sh

Git checklist:
This PR adds a build script for iOS and build instructions along with distribution certificates and provisioning profiles configuration instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1403)

Add build script for iOS

---

talpid-core/src/tunnel/wireguard/connectivity_check.rs

Since I was trying to use the same timeout calculations for establishing connectivity and maintaining the lieveliness of a tunnel, the timeout logic was somewhat convoluted. I'm not sure if the following 232 lines are a massive improvement in that front, but at least now it's testable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1425)

Fix connectivity check.

---

CHANGELOG.md

I went through the git history and updated the changelog. Almost nothing from the git history was forgotten in the changelog, so that's great. I re-worded and moved around some entries between categories though. Feedback welcome.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1442)

Update changelog prior 2020.1 release

---

CHANGELOG.md
gui/assets/images/icon-reload.svg
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/Connect.tsx
gui/src/renderer/components/TunnelControl.tsx
gui/src/renderer/containers/ConnectPage.tsx
gui/src/shared/ipc-event-channel.ts

This PR adds a reconnect button to the desktop gui.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1457)

Desktop add reconnect button

---

gui/src/config.json
gui/src/renderer/components/AppButton.tsx
gui/src/renderer/components/MultiButton.tsx
gui/src/renderer/components/TunnelControl.tsx

Updated appearance of reconnect button.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1469)

Improve appearance of reconnect button

---

Cargo.lock
android/src/main/kotlin/net/mullvad/mullvadvpn/model/Constraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayConstraintsUpdate.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettingsUpdate.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
mullvad-jni/Cargo.toml
mullvad-jni/src/classes.rs
mullvad-jni/src/lib.rs
mullvad-types/Cargo.toml
mullvad-types/src/relay_constraints.rs
talpid-core/Cargo.toml
talpid-types/Cargo.toml

This PR replaces the manual `mullvad_jni::FromJava` implementations with `jnix::FromJava` derivations.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1386)

Use `jnix::FromJava`

---

CHANGELOG.md
mullvad-rpc/src/lib.rs

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1482)

Update the API IP

---

gui/src/renderer/app.tsx

Finnish and danish language options were missing, even though the languages are supported
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1489)

Add finnish and danish options to language picker

---

windows/driverlogic/src/driverlogic.cpp

Instead of hardcoding output to `stderr` and `stdout`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1504)

Abstract logging functions in driverlogic

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Base.lproj/Main.storyboard
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/ConnectionPanelView.swift
ios/MullvadVPN/GeoLocation.swift
ios/MullvadVPN/PacketTunnelIpc.swift
ios/MullvadVPN/RelaySelector.swift
ios/MullvadVPN/SimulatorTunnelProviderHost.swift
ios/PacketTunnel/PacketTunnelProvider.swift

Git checklist:
This PR adds the connection info panel and displays the server location when connected. Also slightly refines the font sizes in the main view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1500)

Show relay location and connection info

---

ios/Snapfile

Git checklist:
This PR disables running simulators concurrently when taking screenshots to avoid the "Too many wireguard keys" error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1512)

Disable concurrent simulators

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/relays.rs
mullvad-daemon/src/version_check.rs
mullvad-daemon/src/wireguard.rs

Some small cleanup changes for the `mullvad-daemon` crate, mostly inspired by Clippy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1527)

Small daemon fixes

---

docs/architecture.md
docs/relay-selector.md
mullvad-daemon/src/relays.rs
mullvad-types/src/relay_constraints.rs

This document outlines how relays and endpoints are selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1506)

Document relay and endpoint selection

---

ios/MullvadVPN/Base.lproj/Main.storyboard
ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift

Git checklist:
This PR adds a few commands to skip the consent screen when taking screenshots
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1544)

Skip consent screen when taking screenshots

---

CHANGELOG.md
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AdvancedSettingsStyles.tsx
gui/src/renderer/components/Cell.tsx
gui/src/renderer/components/CellStyles.tsx
gui/src/renderer/containers/AdvancedSettingsPage.tsx
gui/src/renderer/redux/settings/actions.ts
gui/src/renderer/redux/settings/reducers.ts
gui/src/shared/ipc-event-channel.ts

This PR adds the WireGuard MTU setting.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1562)

Add WireGuard MTU setting

---

CHANGELOG.md
mullvad-daemon/src/lib.rs
talpid-core/src/tunnel_state_machine/mod.rs

Force daemon to wait at most 5 seconds for the tunnel state machine to shut down during the daemon's shutdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1561)

Verify tunnel state machine's shutdown

---

gui/package-lock.json

Bump `kind-of` and the `minimist` dependency where possible.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1573)

Bump kind-of dependency to 6.0.3

---

.gitignore
CHANGELOG.md
build.sh
dist-assets/linux/before-install.sh
dist-assets/linux/before-remove.sh
dist-assets/pkg-scripts/postinstall
gui/tasks/distribution.js

Related PR: https://github.com/mullvad/mullvadvpn-app/pull/1554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1574)

Block when upgrading on MacOS and Linux

---

talpid-core/src/routing/linux/mod.rs

Previously, the status returned by `ip` was ignored (probably by design). But since it can fail, non-zero codes should be treated as errors.
There is another case in `get_default_routes_inner`, but this should fail if the output is incorrect, so it might not need to be updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1590)

Check exit statuses in RouteManager

---

CHANGELOG.md

Some small changelog updates. Some things was under the wrong category or platform unless I misunderstood things. And some I felt could be either better explained or written in a more concise way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1593)

Rearrange and fix some stuff in the changelog

---

gui/src/renderer/components/SvgMap.tsx

If the connection was established during the map transition, the bounding box was based on the two last versions of the props when it should be based on the initial position as well since the transition from that position is still going on. This PR changes the bounding box calculation to use all old bounding boxes that are related to an active transition.
I'm not happy with the use of a timeout to detect when the transition is finished, but as far as I can tell there is no other way to do it. `react-simple-maps@1.0.0-beta` has added the possibilty to send additional props which are forwarded to the svg element, which would probably make it possible to use the `onTransitionEnd` prop.
Git checklist:
--- …

Keep old viewport bounding boxes until animation is done

---

gui/src/main/index.ts

This PR ensures that the notification, about being close to expiry, don't show if it's already expired.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1600)

Prevent expiry notification from showing if account has expired

---

gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/containers/PreferencesPage.tsx
gui/src/shared/ipc-event-channel.ts

This PR implements the toggle for the beta program in preferences.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1602)

Add beta program toggle in preferences

---

CHANGELOG.md

Add changlog entry about https://github.com/mullvad/mullvadvpn-app/pull/1596 and https://github.com/mullvad/mullvadvpn-app/pull/1597.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1608)

Add changelog entry about map improvements

---

.travis.yml

Git checklist:
This PR adds the iOS job for running tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1610)

Add iOS to travis builds

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Account.swift
ios/MullvadVPN/AccountViewController.swift
ios/MullvadVPN/String+Split.swift
ios/MullvadVPNTests/StringTests.swift

Git checklist:
1. Add extension to split the `String` on substrings of the given length
1. Add tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1614)

Format account token in Account view

---

ios/MullvadVPN/SettingsViewController.swift

Git checklist:
This PR adds automatic expiry reload in the root settings view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1617)

Reload account expiry after purchase

---

ios/MullvadVPN/Account.swift
ios/MullvadVPN/AccountViewController.swift
ios/MullvadVPN/Base.lproj/Main.storyboard
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/LoginState.swift
ios/MullvadVPN/LoginViewController.swift
ios/MullvadVPN/MullvadAPI.swift
ios/MullvadVPN/RootContainerViewController.swift
ios/MullvadVPN/SegueIdentifier.swift
ios/MullvadVPN/SettingsViewController.swift
ios/MullvadVPN/ViewControllerIdentifier.swift

Git checklist:
1. Re-add the "create account" button on Login screen
1. Stop pulling the keyboard automatically on Login screen
1. Automatically show the account view when the main controller appears given that the current account has expired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1622)

Create account in the iOS app

---

ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift

Git checklist:
Yet another update to screenshots automation due to recent changes to UI. I use an account with credits so I don't have to account for the account view to pop up on login. Also keyboard does not appear automatically anymore so I don't wait for it anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1626)

Update screenshot script

---

gui/src/config.json
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/Login.tsx
gui/src/renderer/components/Settings.tsx
gui/src/renderer/containers/LoginPage.tsx
gui/src/renderer/redux/account/actions.ts
gui/src/renderer/redux/account/reducers.ts
gui/src/shared/ipc-event-channel.ts

This PR makes the "Create Account" button create an account instead of opening the website. It also makes the "Create account" button always visible. See screenshots here https://github.com/mullvad/mullvadvpn-app/pull/1571.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1604)

Create account in app

---

CHANGELOG.md

This PR adds the create account feature to the changelog.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1631)

Add create account feature to changelog

---

CHANGELOG.md
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/components/RedeemVoucherStyles.tsx
gui/src/renderer/containers/RedeemVoucherContainer.tsx
gui/src/shared/daemon-rpc-types.ts
gui/src/shared/ipc-event-channel.ts

This PR adds the submit voucher functionality to the out-of-time/new-account view. Screenshots can be found in: https://github.com/mullvad/mullvadvpn-app/pull/1571
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1632)

Add submit voucher function

---

.github/ISSUE_TEMPLATE.md

The issue template was quite outdated. No need to talk about the ancient python client any more, no one knows about it any longer :)
I also want to make it more clear that people should usually not report problems here, they should send problem reports directly to support.
And finally, if people go ahead with the issues, it would help a lot if they specified which OS they run and so on.
[Rendered version](https://github.com/mullvad/mullvadvpn-app/blob/improve-github-issue-template/.github/ISSUE_TEMPLATE.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1639)

Replace old issue template with newer one

---

.github/ISSUE_TEMPLATE.md

Follow up to #1639. Since the format did not look very nice on github.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1640)

Fix some style in the issue template that did not turn out very good

---

ios/BuildInstructions.md

Git checklist:
The build instructions list the direct URL to create a new certificate (https://developer.apple.com/account/resources/certificates/add) however it doesn't load the list of available certificates on Linux, so as a workaround the new instructions suggest to visit the page with all certificates and click the plus button (+) to navigate to the "Create a new certificate" page, it seems to work fine in that case on both Linux and macOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1646)

Update build instructions to account for bugs on apple.developer.com

---

README.md
ios/CHANGELOG.md
ios/README.md

Adding links to the App Store for discoverability.
Adding changelog so we can start tracking changes.
Adding link to changelog for discoverability.
:)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1642)

Ios changelog

---

ios/BuildInstructions.md

Git checklist:
This PR updates the keychain related instructions for adding the keychain item for the use with `altool`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1658)

Update keychain related instructions

---

gui/src/renderer/components/Login.tsx

This PR updates the title and subtitle on the login screen.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1661)

Update title and subtitle on login screen

---

CHANGELOG.md
talpid-core/src/offline/windows.rs
windows/winnet/src/winnet/offlinemonitor.cpp
windows/winnet/src/winnet/offlinemonitor.h

Complement the logging with a distinct entry for when connectivity is restored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1660)

Windows: Fix connectivity logging

---

gui/package-lock.json
gui/package.json
gui/src/shared/gettext.ts
gui/tasks/distribution.js

Git checklist:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43822 was merged so we can update too. Also reformatted some of the bits of distribution script with the newer prettier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1666)

Update node gettext typings

---

CHANGELOG.md
gui/package-lock.json
gui/package.json
gui/src/main/index.ts
gui/src/shared/ipc-event-channel.ts
gui/test/setup/main.js

Revert Electron upgrade due to issue with tray icon implementation on Linux in new chromium version. Related to https://github.com/mullvad/mullvadvpn-app/issues/1659.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1670)

Revert electron 8

---

talpid-core/src/routing/linux.rs

The recently merged changes had a major flaw - it had one loop too few. Instead of listening for netlink messages, it would exit after receiving a single one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1686)

Actually loop over netlink messages

---

gui/package-lock.json
gui/package.json
gui/src/renderer/components/Accordion.tsx
gui/src/renderer/components/Account.tsx
gui/src/renderer/components/AccountStyles.tsx
gui/src/renderer/components/AccountTokenLabel.tsx
gui/src/renderer/components/ClipboardLabel.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx
gui/src/renderer/components/Layout.tsx
gui/src/renderer/components/LayoutStyles.tsx
gui/src/renderer/components/Switch.tsx

This PR converts `Accordion.tsx` and `Switch.tsx` to using styled compnents.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1672)

Styled components experimentation

---

talpid-core/src/tunnel/wireguard/config.rs

The change to disregard MTU when deciding if IPv6 should be used was liberal, it completely disregarded the user option to enable or disable IPv6. These changes are being reverted to take the options into account, whilst still disregarding the MTU.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1689)

Disable IPv6 in WireGuard according to options

---

gui/src/renderer/components/Cell.tsx
gui/src/renderer/components/CellStyles.tsx
gui/src/renderer/components/ChevronButton.tsx
gui/src/renderer/components/CityRow.tsx
gui/src/renderer/components/CountryRow.tsx
gui/src/renderer/components/ErrorBoundary.tsx
gui/src/renderer/components/HeaderBar.tsx
gui/src/renderer/components/ImageView.tsx
gui/src/renderer/components/Launch.tsx
gui/src/renderer/components/Login.tsx
gui/src/renderer/components/LoginStyles.tsx
gui/src/renderer/components/NavigationBar.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/components/RedeemVoucherStyles.tsx
gui/src/renderer/components/Selector.tsx

This PR converts `ImageView` from a ReactXP comonent to a Styled component.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1717)

Convert ImageView into a styled component

---

ios/MullvadVPN/RelayCache.swift
ios/MullvadVPN/SimulatorTunnelProvider.swift

Git checklist:
1. It seems like I forgot to add some of the fields related to on-demand support in the simulated tunnel which caused errors when compiling on simulator
1. Fix a comment in `RelayCache`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1727)

Add tunnel simulator on-demand fields

---

.travis.yml
android/src/main/AndroidManifest.xml
android/src/main/res/drawable/account_history_background.xml
android/src/main/res/drawable/blue_button_background.xml
android/src/main/res/drawable/cell_button_background.xml
android/src/main/res/drawable/cell_input_background.xml
android/src/main/res/drawable/green_button_background.xml
android/src/main/res/drawable/red_button_background.xml
android/src/main/res/drawable/transparent_red_button_background.xml
android/src/main/res/drawable/transparent_red_left_half_button_background.xml
android/src/main/res/drawable/transparent_red_right_half_button_background.xml
android/src/main/res/drawable/white20_button_background.xml
android/src/main/res/layout/account.xml
android/src/main/res/layout/advanced.xml
android/src/main/res/layout/connect.xml
android/src/main/res/layout/login.xml
android/src/main/res/layout/preferences.xml
android/src/main/res/layout/problem_report.xml
android/src/main/res/layout/wireguard_key.xml
android/src/main/res/values/attrs.xml
android/src/main/res/values/strings.xml
android/src/main/res/values/styles.xml
ci/ci-android-xml.sh

This PR fixes the CI script to verify the XML formatting and also fixes the formatting of some XML files.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1730)

Fix XML formatting check in Android CI builds

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Keychain.swift
ios/MullvadVPN/KeychainAttributes.swift
ios/MullvadVPN/KeychainClass.swift
ios/MullvadVPN/KeychainError.swift
ios/MullvadVPN/KeychainMatchLimit.swift
ios/MullvadVPN/KeychainReturn.swift

Git checklist:
This PR adds keychain abstractions so it's easier to read and write keychain items vs. working with raw dictionaries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1728)

Add keychain abstractions

---

ios/MullvadVPN.xcodeproj/project.pbxproj

Git checklist:
That should fix the iOS tests and CI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1742)

Add Keychain related files to test target

---

ios/MullvadVPN.xcodeproj/project.pbxproj

Git checklist:
Bump 2020.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1745)

Bump iOS version (2020.3, build 1)

---

gui/src/renderer/components/Account.tsx
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/Support.tsx
gui/src/renderer/components/WireguardKeys.tsx

This PR corrects some localization contexts and groups text that refer to the same things into the same context.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1750)

Improve localization contexts

---

gui/src/renderer/components/RedeemVoucher.tsx
gui/src/shared/scheduler.ts

This PR adds a 1 second delay between successfully redeeming voucher and closing the modal.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1766)

Add delay before closing voucher modal on success

---

ios/MullvadVPN/AutomaticKeyRotationManager.swift

Git checklist:
Simply prepared a PR that swaps 1 to 4 day interval for key rotation as earlier agreed with @faern
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1767)

Change key rotation interval to 4 days

---

gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx
gui/src/renderer/components/Modal.tsx

This PR converts the components in `Modal.tsx` from ReactXP components to React components.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1776)

Convert modal components to styled components

---

gui/src/renderer/components/Account.tsx
gui/src/renderer/components/AccountStyles.tsx
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AppButton.tsx
gui/src/renderer/components/AppButtonStyles.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx
gui/src/renderer/components/Login.tsx
gui/src/renderer/components/MultiButton.tsx
gui/src/renderer/components/NotificationBanner.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/components/Settings.tsx
gui/src/renderer/components/Support.tsx
gui/src/renderer/components/SupportStyles.tsx
gui/src/renderer/components/TunnelControl.tsx
gui/src/renderer/components/WireguardKeys.tsx

This PR converts `AppButton.tsx` to a styled component.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1784)

Convert AppButton from ReactXP

---

gui/src/renderer/components/WireguardKeys.tsx

This PR adds automatic WireGuard key verification when entering the WireGuard key view. The spinner and the "Key is valid" message doesn't show unless the user initiates the validation, only the "Key is invalid" message is shown as a result of the automatic verification.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1796)

Add automatic WireGuard key verification

---

ios/CHANGELOG.md
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/TunnelManager.swift
ios/MullvadVPN/WireguardKeysViewController.swift

Git checklist:
1. Reload tunnel state when the app comes back from suspended state.
1. Keep track of the public key in `TunnelManager` and refresh it automatically for the UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1798)

Handle app suspension

---

mullvad-exclude/src/main.rs

`mullvad-exclude` seems to fail on NixOS with a permissions error when
trying to open /sys/fs/cgroup/net_cls/mullvad-exclude/cgroup.procs. I
noticed that the daemon did not have such issues, so I presumed it's the
options with which the procs file is opened with that are to blame. As
such, I've set the changed the code to use the same options in
`mullvad-exclude` as in `talpid-core`. This does indeed fix the issue.
I assume we don't import `talpid-core` into `mullvad-exclude` as to not inflate the size of the binary, right?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1825)

Improve mullvad-exclude

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

Currently there's a bug in the app where sometimes it refuses to quit, restarting itself after the user pressing the "Quit" button. It's currently unknown why that happens or what is the scenario that triggers the bug. In an attempt to try to understand what is happening, this PR adds some log messages to the service and the daemon lifecycle. Hopefully this can give a glue at the order of operations in the scenario that triggers the bug.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1841)

Add logs to debug the service lifecycle

---

mullvad-types/src/settings/mod.rs

Previously, the `show_beta_releases` field could contain a `null` value. Since now the field cannot be nullable in the settings struct, the deserialization must be updated to work around the nullability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1844)

Fix settings deserialization

---

Cargo.lock
mullvad-daemon/Cargo.toml
mullvad-daemon/src/system_service.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1858)

Bump windows-service-rs

---

CHANGELOG.md
gui/src/main/index.ts

This PR disables the window animations on Windows to fix the flickering that happens when opening the window.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1842)

Disable window animations on Windows

---

audits/2020-06-12-cure53.md

Backporting the language fixes from the copywriter :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1877)

Improve language in 2020 app audit document

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1883)

readme: add missing punctuation

---

gui/src/renderer/components/Connect.tsx
gui/src/renderer/components/SecuredLabel.tsx
gui/src/renderer/components/TunnelControl.tsx

This PR converts components in `Connect.tsx` and `TunnelControl.tsx` from ReactXP components to React components and Styled components.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1886)

Convert Connect and TunnelControl from ReactXP

---

android/src/main/res/values/strings.xml

This PR fixes the `strings.xml` file to satisfy the XML formatter.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1898)

Fix XML formatting

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/Base.lproj/Main.storyboard
ios/MullvadVPN/HeaderBarView.swift
ios/MullvadVPN/HeaderBarView.xib
ios/MullvadVPN/RootContainerViewController.swift
ios/MullvadVPN/ViewControllerIdentifier.swift

Git checklist:
In this PR I am moving the root view controller from storyboard into code entirely. The header bar view is loaded from a separately designed XIB file, which is very simple. Given that iPad support will be coming sometime soon, it feels that it will be easier to configure controllers exclusively in code, as opposed to fighting storyboards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1903)

Move header to xib

---

CHANGELOG.md
dist-assets/windows/installer.nsh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1914)

Bump Wintun to 0.8

---

android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemHolder.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountInput.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/CellInput.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/CellSwitch.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectionStatus.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/HeaderBar.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RemainingTimeLabel.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/InAppNotificationController.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/InformationView.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/UrlButton.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/LinearInterpolation.kt

This PR refactors parts of the code to remove most of the Kotlin compiler warnings. The `ConnectivityListener` class still has some warnings, but that class needs to be rewritten using a newer API.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1917)

Clean up most of Kotlin compiler warnings

---

CHANGELOG.md
talpid-core/src/firewall/linux.rs
talpid-core/src/split_tunnel/linux.rs
talpid-types/src/cgroup.rs

Fix the issues outlined in #1947 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1950)

Fix NET_CLS changes.

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Base.lproj/Main.storyboard
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/DisplayChainedError.swift
ios/MullvadVPN/SegueIdentifier.swift
ios/MullvadVPN/SelectLocationCell.swift
ios/MullvadVPN/SelectLocationController.swift
ios/MullvadVPN/SelectLocationHeaderView.swift
ios/MullvadVPN/SelectLocationNavigationController.swift
ios/MullvadVPN/UIColor+Palette.swift

Git checklist:
This PR moves the `SelectLocationController` out of Storyboard. Mainly a refactoring effort to get rid of storyboards in the near future for more flexibility as we will need to adapt the UI for iPad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1948)

Move SelectLocationController from Storyboard into code

---

CHANGELOG.md
talpid-core/src/tunnel_state_machine/connecting_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1956)

Return specific error to the frontend when setting the firewall policy fails in ConnectingState

---

CHANGELOG.md
mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-rpc/src/bin/relay_list.rs
mullvad-rpc/src/relay_list.rs

Reworked the relay list downloader to use new style futures and add exponential backoff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1949)

Add exponential backoff for relay list downloader

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/ApplicationConfiguration.swift
ios/MullvadVPN/Base.lproj/Main.storyboard
ios/MullvadVPN/LogStreamerViewController.swift
ios/MullvadVPN/Logging/CustomFormatLogHandler.swift
ios/MullvadVPN/Logging/LogEntryParser.swift
ios/MullvadVPN/Logging/LogStreamer.swift
ios/MullvadVPN/Logging/StringStreamIterator.swift
ios/MullvadVPN/Logging/TextFileStream.swift
ios/MullvadVPN/SettingsViewController.swift
ios/PacketTunnel/WireguardDevice.swift

Git checklist:
1. Add runtime log viewer in debug builds.
1. Wireguard-go appends the newline to the logged strings, trim it before logging it to file to prevent the newline from appearing twice in log files.
1. Add milliseconds to the logged timestamps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1991)

Add log viewer

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AdvancedSettingsStyles.tsx
gui/src/renderer/components/ConnectionPanel.tsx
gui/src/renderer/components/ConnectionPanelDisclosure.tsx
gui/src/renderer/components/ErrorBoundary.tsx
gui/src/renderer/components/Launch.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/components/PreferencesStyles.tsx
gui/src/renderer/components/SelectLanguage.tsx
gui/src/renderer/components/Settings.tsx
gui/src/renderer/components/SettingsStyles.tsx

This PR converts a few components from ReactXP.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1986)

Convert components from ReactXP

---

gui/src/renderer/components/Support.tsx
gui/src/renderer/components/SupportStyles.tsx

This PR converts the problem report component from ReactXP.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1987)

Convert Support from ReactXP

---

gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx

This PR convert `ExpiredAccountErrorView` from ReactXP
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1995)

Convert ExpiredAccountErrorView from ReactXP

---

mullvad-jni/src/lib.rs

The current daemon log on Android sometimes shows some errors with RPC requests being cancelled. That's not actually an error, since the requests are automatically aborted when the tunnel state changes. This PR changes the log code to handle aborted requests as `debug` information.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1992)

Don't log cancelled RPC requests as errors

---

gui/src/main/daemon-rpc.ts

This PR removes the event listeners on the daemon event stream before calling cancel. This is a workaround for the error that occurred on macOS when quitting the application.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2002)

Fix error caused by calling cancel on open gRPC stream

---

gui/src/renderer/components/Login.tsx
gui/src/renderer/components/LoginStyles.tsx

This PR convert the components in `Login.tsx` from ReactXP
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2030)

Convert Login.tsx from ReactXP

---

README.md

Reorganize them slightly, update some outdated information, and add a missing dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2026)

Update build instructions for Android

---

gui/src/renderer/components/SelectLocation.tsx
gui/src/renderer/components/TransitionContainer.tsx

This PR converts the components in `TransitionContainer.tsx` from ReactXP.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2042)

Convert components in TransitionContainer.tsx from ReactXP

---

mullvad-daemon/Cargo.toml
talpid-core/Cargo.toml
talpid-core/src/process/mod.rs
talpid-core/src/tunnel/openvpn.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2048)

Remove unused Android dependencies

---

ios/MullvadVPN/MullvadRest.swift

Git checklist:
Percent encode all characters except alphanumerics `[a-zA-Z0-9]` in public keys in path components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2055)

REST: Percent encode public keys

---

ios/PacketTunnel/WireguardDevice.swift
ios/wireguard-go-bridge/api-ios.go

Git checklist:
This PR updates `wireguard-go-bridge` that [automatically calls `dup()`](https://git.zx2c4.com/wireguard-apple/commit/?id=737f847c0db36429f7136fb514409c22e13a70ee) on the `utun`. Therefore we don't have to do that manually on Swift side.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2064)

Remove dup() calls on iOS

---

Cargo.lock
mullvad-rpc/Cargo.toml

I have not yet had the time to test this on any platform. But we should stay on top of things, stay updated. So let's go!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2067)

Upgrade to rustls 0.18

---

Cargo.lock
mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-management-interface/Cargo.toml
mullvad-problem-report/Cargo.toml
mullvad-tests/Cargo.toml
talpid-core/Cargo.toml
talpid-core/src/offline/linux.rs
talpid-core/src/routing/linux.rs
talpid-openvpn-plugin/Cargo.toml
talpid-types/Cargo.toml

* Update dependencies: base64, tonic-build, netlink-packet-route, netlink-sys, rtnetlink, uuid.
* Update semver-compatible dependencies using `cargo update`.
* Removed futures 0.1 from `mullvad-cli`.
Nothing of importance or relevance changed between the versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2072)

Upgrade some dependencies

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/IPAddress+Codable.swift
ios/MullvadVPN/IPAddressRange.swift
ios/MullvadVPNTests/IPAddressRangeTests.swift

Git checklist:
1. Add missing copyright notice to `IPAddressRange.swift`
1. Rework `IPAddressRange` and add tests
1. Rename `IpAddress+Codable` to `IPAddress+Codable` (uppercase `IP` to align the naming convention with other files)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2087)

Improve IPAddressRange

---

ios/MullvadVPN/Curve25519.swift
ios/PacketTunnel/AnyIPEndpoint+DNS64.swift
ios/PacketTunnel/WireguardCommand.swift
ios/PacketTunnel/WireguardDevice.swift

Git checklist:
1. Add missing copyright notices in `Curve25519.swift` & `AnyIPEndpoint+DNS64.swift`
1. Refactor DNS64 resolution code and align with [the recommended approach by Apple](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-DontLinkElementID_4).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2089)

Improve DNS64 resolution

---

ios/CHANGELOG.md

Added the release headers for yesterday's release. Also modified some changelog entries where I thought they could be clearer. What do you think?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2105)

Edit changelog and add iOS 2020.4 release header

---

Cargo.lock
mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-daemon/src/logging.rs
mullvad-exclude/Cargo.toml
mullvad-exclude/src/main.rs
mullvad-jni/Cargo.toml
mullvad-management-interface/Cargo.toml
mullvad-paths/Cargo.toml
mullvad-problem-report/Cargo.toml
mullvad-setup/Cargo.toml
talpid-core/Cargo.toml
talpid-core/src/tunnel/wireguard/logging.rs
talpid-openvpn-plugin/Cargo.toml
talpid-types/Cargo.toml

Upgrade or remove the following dependencies:
* Remove void
* Remove tokio-io
* Remove async-stream
* winreg 0.6.2 → 0.7.0
* x25519-dalek 0.6.0 → 1.1.0
* tun 0.4.4 → 0.5
* nix 0.17 → 0.18
* fern 0.5 → 0.6
* which 3.1 → 4.0
* os_pipe 0.8 → 0.9
* parking_lot 0.9 → 0.11
* dirs 2.0 → 3.0
Nothing relevant changed.
Unused `tokio` features were also removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2120)

Upgrade dependencies

---

talpid-core/src/tunnel/wireguard/mod.rs

Setting `TALPID_FORCE_USERSPACE_WIREGUARD` to anything other than `0` now causes the user-space implementation to be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2118)

Add an environment variable for overriding the preference for the WireGuard kernel module

---

Cargo.lock
talpid-core/Cargo.toml
talpid-core/src/dns/linux/network_manager.rs
talpid-core/src/dns/linux/systemd_resolved.rs

I followed the instructions [here](https://github.com/diwic/dbus-rs/blob/master/dbus/changes-in-0.7.md) to get things compiling without making any more changes than were necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2133)

Upgrade dbus-rs

---

gui/src/renderer/components/Support.tsx
gui/src/renderer/components/SupportStyles.tsx

This PR updates the problem report view according to the new mockup. It includes:
* Removing the "SECURE CONNECTION" label
* Make "Thanks!" green
* Fix the previously non-working "Try again" button in the failed state.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2139)

Update desktop support view

---

talpid-core/src/routing/linux.rs

Remove some spam from the logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2157)

Don't log unimportant events in the Linux route monitor

---

docs/security.md
windows/winfw/README.md

This updates the security document to explain the changes made in #2168.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2176)

Explain persistent filters in the security document

---

mullvad-daemon/src/system_service.rs

A race condition occurs in `system_service`. `service_dispatcher::start` usually returns before `run_service` has logged errors returned by the daemon, causing the daemon to exit before they are logged. This was fixed by calling `persistent_service_status.set_stopped` *after* logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2190)

Log errors before stopping the service on Windows

---

mullvad-cli/src/cmds/custom_dns.rs

A small CLI improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2204)

Add 'reset' command for custom DNS instead of allowing 'set' without additional arguments

---

mullvad-jni/src/lib.rs

There have been a few problem reports with logs that seem a bit odd. It appears that multiple daemon instances could be running, which would cause problems. In order to try to figure out if that is what is happening, this PR adds an atomic counter to the `mullvad-jni` crate that is incremented whenever a new daemon instance is created and decremented whenever an instance finishes. In theory it should always be zero when the daemon is starting, and the PR will log an error message if the counter is not zero.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2200)

Detect and log if multiple daemon instances are running

---

mullvad-cli/src/cmds/custom_dns.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/settings.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-types/src/settings/mod.rs
talpid-types/src/net/mod.rs
windows/winfw/src/winfw/winfw.cpp

The GUI will include an on/off switch. That means that the list must survive if custom DNS is disabled. Currently, disabling custom DNS will wipe the list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2205)

Make custom DNS settings toggleable

---

CHANGELOG.md
mullvad-cli/src/cmds/mod.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/settings.rs
mullvad-types/src/settings/mod.rs
talpid-core/src/firewall/linux.rs
talpid-core/src/firewall/macos.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/tunnel_state_machine/connected_state.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/tunnel_state_machine/disconnected_state.rs
talpid-core/src/tunnel_state_machine/disconnecting_state.rs
talpid-core/src/tunnel_state_machine/error_state.rs
talpid-core/src/tunnel_state_machine/mod.rs

Support custom DNS on macOS. The details are essentially the same as in https://github.com/mullvad/mullvadvpn-app/pull/2210.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2214)

Support custom DNS on macOS

---

gui/.eslintrc.js
gui/src/main/daemon-rpc.ts
gui/src/main/linux-split-tunneling.ts
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/ImageView.tsx
gui/src/renderer/components/LinuxSplitTunnelingSettings.tsx
gui/src/renderer/components/Modal.tsx
gui/src/renderer/components/PlatformWindow.tsx
gui/src/renderer/components/Support.tsx
gui/src/renderer/components/TransitionContainer.tsx
gui/src/renderer/redux/settings/reducers.ts
gui/src/shared/daemon-rpc-types.ts
gui/types/linux-app-list/index.d.ts

This PR is the first in a series of improvements to our ESLint configuration, it includes these new rules:
* Require single quotes unless the string contains `'`, then double quotes are allowed to avoid escaping. This required a few code changes.
* Don't allow arrow funtions or bind in jsx props. This didn't require any code changes.
* Require a specific naming convention for variables, types, class members etc. This required some changes, mostly ignore-comments but also a few actual naming changes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2221)

Improve ESLint configuration

---

gui/.eslintrc.js
gui/src/main/daemon-rpc.ts
gui/src/renderer/components/Accordion.tsx
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/Map.tsx
gui/src/renderer/components/Marquee.tsx
gui/src/renderer/components/WireguardKeys.tsx

This PR adds the the ESLint member ordering rule. It required quite a few code changes but all changes should be movement of definitions and nothing should affect the logic.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2225)

Add ESLint member ordering rule

---

ios/MullvadVPN.xcodeproj/project.pbxproj

Git checklist:
Bump 2020.5-b1 on iOS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2233)

Bump 2020.5-b1

---

CHANGELOG.md
gui/src/renderer/components/KeyboardNavigation.tsx
gui/src/renderer/components/Modal.tsx
gui/src/renderer/lib/history.ts
gui/src/renderer/routes.tsx

This PR adds an escape hatch which navigates back to the main view when escape is pressed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2202)

Add escape hatch

---

android/src/main/res/values-da/strings.xml
android/src/main/res/values-de/strings.xml
android/src/main/res/values-es/strings.xml
android/src/main/res/values-fi/strings.xml
android/src/main/res/values-fr/strings.xml
android/src/main/res/values-it/strings.xml
android/src/main/res/values-ja/strings.xml
android/src/main/res/values-ko/strings.xml
android/src/main/res/values-nb/strings.xml
android/src/main/res/values-nl/strings.xml
android/src/main/res/values-pl/strings.xml
android/src/main/res/values-pt/strings.xml
android/src/main/res/values-ru/strings.xml
android/src/main/res/values-sv/strings.xml
android/src/main/res/values-th/strings.xml
android/src/main/res/values-tr/strings.xml
android/src/main/res/values-zh-rCN/strings.xml
android/src/main/res/values-zh-rTW/strings.xml

This PR is just some translation updates after running the translation converter tool. This should update a few messages and pull a few new ones that were translated for the desktop app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2253)

Update translation strings on Android

---

gui/src/main/index.ts

This PR fixes a race condition in the `updateLocation` function when the function is called again before the previous location result as been received.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2265)

Fix race condition in updateLocation

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

Sometimes the app would launch and not exclude any apps from the tunnel, which meant that the split-tunneling options weren't properly applied. A [previous PR](https://github.com/mullvad/mullvadvpn-app/pull/2223) attempted to fix the cause of that issue, where a race condition caused a reconnect to be requested while already reconnecting, which meant that it would discard the second reconnect request. This caused the issue because the second reconnect was necessary in order to recreate the tunnel with the exclusion list applied.
However, the issue was still happening sometimes. Upon further investigation, there appears to be another race condition. This time, the app starts the daemon and it connects successfully, but the "connecting" state event is received a little after the split …

Fix apps still not being excluded when starting with Auto-Connect enabled

---

gui/src/main/index.ts
gui/src/main/notification-controller.ts
gui/src/renderer/components/NotificationBanner.tsx
gui/src/shared/auth-failure.ts
gui/src/shared/notifications/account-expired.ts
gui/src/shared/notifications/block-when-disconnected.ts
gui/src/shared/notifications/close-to-account-expiry.ts
gui/src/shared/notifications/connected.ts
gui/src/shared/notifications/connecting.ts
gui/src/shared/notifications/disconnected.ts
gui/src/shared/notifications/error.ts
gui/src/shared/notifications/inconsistent-version.ts
gui/src/shared/notifications/notification.ts
gui/src/shared/notifications/reconnecting.ts
gui/src/shared/notifications/unsupported-version.ts
gui/src/shared/notifications/update-available.ts

This PR changes the system notification messages and in-app notification titles, bodies and indicators in accordance with the new notification style guide.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2264)

Update notification messages

---

CHANGELOG.md
windows/winfw/src/winfw/sessioncontroller.cpp

Related PR: https://github.com/mullvad/libwfp/pull/29
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2298)

Bump libwfp to fix memory leak

---

CHANGELOG.md

Making some clarifications and cleanups to the changelog prior release. Some entries have been made obsolete by other later changes. Some entries I thought could simply be made a bit clearer, or were better suited for another category of changes.
But you know more about the details of the changes than me. So double check my changes and give feedback!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2318)

Clarify things in the changelog and clean up obsolete entries

---

talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs

When creating a Wintun device, a couple of registry values belonging to the device are not initialized on some machines. Most importantly `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\<DEVICE>\ComponentId`. This is presumably due to a bug in either Windows or Wintun.
While `wireguard-go` ignores this registry value, OpenVPN uses it to determine whether a particular network device is a tunnel device. As a result, connecting using OpenVPN fails. Beyond that, though, it doesn't appear to be crucial. This patch simply creates the registry value if it does not exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2338) …

Work around non-existent 'ComponentId' registry value

---

dist-assets/windows/installer.nsh
windows/driverlogic/src/driverlogic.cpp

wintun.dll triggers an "untrusted publisher" dialog on Windows 7, if the driver is not already installed. When this is done from a service, this dialog cannot be shown, so instead it fails. This PR creates a temporary Wintun adapter in the installer whose purpose is just to install or upgrade the driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2340)

Add hack to circumvent driver signing issues on Windows 7

---

README.md

This PR updates the description of the GUI app structure in the main readme.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2355)

Update structure of GUI app in readme

---

mullvad-cli/src/cmds/split_tunnel/linux.rs
mullvad-exclude/src/main.rs

This makes it easier to find.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2364)

Mention 'mullvad-exclude' in 'mullvad split-tunnel'

---

gui/src/main/index.ts

This PR is a step in the direction to secure the frontend further. It disables all network communication from the renderer process by intercepting and cancelling web requests. There are a few exception when running in development mode which are described in a comment in the code.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2365)

Intercept and cancel web requests originating from renderer process

---

talpid-core/src/firewall/windows.rs

`allowed_endpoint_ip` was dropped before a pointer to it was dereferenced. Introduced in #2356.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2373)

Initialize firewall correctly on Windows

---

talpid-core/src/dns/linux/systemd_resolved.rs

To allow for better compatibility with more distros, the daemon will now check the contents for `/etc/resolv.conf` against _known good paths_ when detecting systemd-resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2374)

Match content of /etc/resolv.conf for systemd-resolved

---

android/.idea/.gitignore
android/.idea/compiler.xml
android/.idea/jarRepositories.xml
android/.idea/misc.xml
android/.idea/modules.xml
android/.idea/modules/android.iml
android/build.gradle
android/gradle.properties

Added auto-generated config files for idea IDE to be able use Android Studio.
Also, added **gitignore** for idea folder with basic rules. 
Added **gradle.properties** file and updated **build.gradle** script with link for kotlin src directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2376)

Android idea config files added

---

gui/package-lock.json

This PR updates the dependencies of `browser-sync` which included a high-severity vulnerability.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2383)

Update transitive dependencies of browser-sync

---

gui/src/main/gui-settings.ts

This PR makes the `GuiSettings.load()` call check whether or not the settings file exist before loading it, and if it doesn't it creates the file with the default settings.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2400)

Create gui-settings file on launch if it doesn't already exist

---

mullvad-daemon/src/lib.rs

The daemon can get into a deadlock if it's _awaiting_ on a response from the REST service if the REST service needs to rotate to a new API address. I've fixed this by bypassing the daemon in the change handler for the address cache and just sending the new API IP over to the TSM directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2404)

Send API address to TSM directly

---

CHANGELOG.md
gui/package-lock.json
gui/package.json

This PR updates Electron to 11.2.1.
Here's the most interesting changes:
https://github.com/electron/electron/releases/tag/v11.1.0
https://github.com/electron/electron/releases/tag/v11.2.0
https://github.com/electron/electron/releases/tag/v11.2.1
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2414)

Update Electron to 11.2.1

---

gui/src/renderer/components/Account.tsx
gui/src/renderer/components/AccountStyles.tsx

This PR moves the buttons on the account page to the bottom of the page. This makes the button placement more consistent across the app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2452)

Move buttons on account page to bottom

---

talpid-core/src/future_retry.rs

Gets rid of the unnecessary PRNGs (#2455) by just taking a `u64` as input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2466)

Simplify jitter test

---

README.md
gui/package-lock.json
gui/package.json
gui/scripts/README.md
gui/scripts/prepare-rtree.ts

This PR contains changes made by npm 7 to the `package.json` and `package-lock.json` files. It also contains som documentation changes related to the upgrade.
Information/changes:
https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
https://github.blog/2021-02-02-npm-7-is-now-generally-available/
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2467)

Changes for npm 7

---

gui/src/main/index.ts
gui/src/main/logging.ts
gui/src/shared/logging-types.ts
gui/src/shared/logging.ts

This PR prevents our logging implementation from outputting to the console when encountering errors while running tests.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2474)

Prevent logging when running tests

---

gui/src/renderer/components/Support.tsx

This PR changes the placeholder in the problem report message textarea.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2495)

Add language requirement to problem report message placeholder

---

ios/MullvadVPN/CustomTextView.swift
ios/MullvadVPN/ProblemReportViewController.swift

Git checklist:
This PR changes the message placeholder in problem report view.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2504)

Update the placeholder text for problem report message field

---

windows/winfw/src/extras/cli/commands/winfw/policy.cpp
windows/winfw/src/winfw/winfw.cpp
windows/winfw/src/winfw/winfw.h

It hasn't been possible to build this tool for a while.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2487)

Fix WinFw CLI/extras

---

talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs

Update that passes on Wintun logs to daemon.log. This should make it easier to figure out the cause of some errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2510)

Add Wintun logger

---

android/src/main/res/color/switch_thumb_fill_selector.xml
android/src/main/res/drawable/switch_thumb.xml
android/src/main/res/drawable/switch_track.xml
android/src/main/res/values/colors.xml
android/src/main/res/values/dimensions.xml
android/src/main/res/values/styles.xml

This PR is created a switch style and assets to match design. This will allow us to use standard switch component.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2519)

Create switch style and all needed assets for this

---

CHANGELOG.md
android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/NavigationBarPainter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ProblemReportFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/StatusBarPainter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SystemPainter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt
android/src/main/res/values/styles.xml

On this PR we colouring StatusBar based on connection status and on which fragment we are. Also, we colouring NavigationBar on some certain fragments to match the background colour.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2521)

Colouring StatusBar and NavigationBar

---

android/src/main/kotlin/net/mullvad/mullvadvpn/model/ListItemData.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/WidgetState.kt

This PR contains model classes for universal list items.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2522)

Create universal list item container

---

talpid-core/src/tunnel_state_machine/connecting_state.rs

Previously the tunnel state machine would instantly reconnect if `TunnelMonitor::start` failed and `should_retry` returned true. This could (at least as of #2514) result in the daemon constantly attempting to reconnect several times per second.
This PR reuses the tunnel monitor thread to prevent this. The thread is always alive for at least `MIN_TUNNEL_ALIVE_TIME` (1 second) before sending a close event.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2529)

Throttle reconnection attempts when the tunnel monitor fails to start

---

android/src/main/AndroidManifest.xml

Added extra permission to be able to read all installed packages
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2531)

Support Android 11

---

gui/src/renderer/components/Settings.tsx

This PR updates the version footer messages to contain the same texts as the corresponding notifications.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2558)

Update version information in settings with new notification texts

---

dist-assets/windows/installer.nsh

Previously, the service was forcibly killed if it was "marked for deletion" while installing the app. This would occur if the daemon refused to stop, or for some other unknown reason. If the daemon was still running, then the attempt to stop it would eventually time out, `mullvad-daemon.exe` would never be replaced, and the user would be left with an old version of the daemon.
The changes in this PR only try to make sure that the service is not running before continuing to install the app. It doesn't address the issue of the installer silently continuing if files cannot be replaced, or of the uninstaller not aborting upon failure.
--- …

Try to forcibly kill stuck service in Windows uninstaller

---

mullvad-daemon/src/relays.rs
mullvad-daemon/src/wireguard.rs
talpid-core/src/future_retry.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2562)

Simplify ExponentialBackoff

---

gui/src/renderer/components/Support.tsx

This PR updates the message displayed when the app fails to send a problem report since the app can now send problem reports even when blocked. The text in the successful case has also been improved.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2561)

Fix problem report failure message

---

CHANGELOG.md

This PR adds a changelog entry for https://github.com/mullvad/mullvadvpn-app/pull/2549 which I forgot when submitting that PR.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2571)

Add inconsistent version fix to changelog

---

.github/workflows/frontend.yml

This PR adds a GitHub actions job for the frontend checks.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2575)

Add GitHub actions frontend job

---

gui/package-lock.json

This PR is the result of running `npm audit fix`. A few transitive dependencies with known vulnerabilities has been updated.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2579)

Update packages with vulnerabilities

---

ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/RootContainerViewController.swift

Git checklist:
This PR adds the user interface orientation support to root container.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2584)

Handle interface orientation

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemsAdapter.kt

This PR is about to create universal list adapter. It has DiffUtil instance to handle animations for changes.
Adapter used different list items and introduce flexibility with usage of different list item types.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2567)

Create universal list adapter

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SplitTunnelingFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt

Simplify ListItemDecoration and remove unnecessary context link from it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2603)

Simplify ListItemDecoration

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/CustomNavigationBar.swift
ios/MullvadVPN/HeaderBarView.swift
ios/MullvadVPN/LocationDataSource.swift
ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift
ios/MullvadVPN/ProblemReportViewController.swift
ios/MullvadVPN/RelayConstraints.swift
ios/MullvadVPN/SelectLocationCell.swift
ios/MullvadVPN/SelectLocationHeaderView.swift
ios/MullvadVPN/SelectLocationNavigationController.swift
ios/MullvadVPN/SelectLocationViewController.swift
ios/MullvadVPN/UIMetrics.swift

Git checklist:
1. Introduce a custom `LocationDataSource` to animate the relay list. Makes dependency on `TableViewDiffableDataSource` obsolete.
2. Make a sticky header view in "Select Location" controller and make it look similar to what we have on desktop
3. Make it possible to browse the sub-trees with all inactive relays.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2582)

Introduce LocationDataSource

---

.github/workflows/ios.yml
ios/MullvadVPN.xcodeproj/project.pbxproj

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2606)

Add github workflow for iOS tests

---

gui/src/renderer/app.tsx

This PR strips error messages on errors sent over the IPC channel of the "Uncaught Error" prefix.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2614)

Remove "Uncaught Error" prefix on error messages

---

talpid-core/src/dns/linux/systemd_resolved.rs
talpid-dbus/src/systemd_resolved.rs

On some Ubuntu systems, it seems like the DNS watcher would deadlock - possibly because it's receiving too many DBus updates and the watcher thread is hogging the lock on the state. I've unloaded some of the responsibility from the _shared state_ so that no mutex is required to share the DNS config between threads and instead use an atomic bool to signal when the watcher thread should shut down. I'm still unsure if this whole cherade should be eschewed in favor of not reverting the config at all. I tested doing that, and it just works. My only concern would be that the watcher thread might not automatically stop. On the other hand, the watcher thread could always check if the link was removed - in which case it could stop.
--- …

Fix deadlock in systemd-resolved DNS management

---

docs/architecture.md

I've added a small paragraph about offline detection for each of the platforms we support in the architecture docs. I don't expect all of the reviewers to read all of the changes, only the bits you'd feel most comfortable reviewing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2629)

Add offline monitor docs

---

android/build.gradle
android/src/main/AndroidManifest.xml
android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadApplication.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt

In this PR we added Koin as main dependency injection tool and configure first and basic module.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2637)

Init Koin as DI for android project

---

ios/MullvadVPN/LocationDataSource.swift
ios/MullvadVPN/SelectLocationViewController.swift

Git checklist:
1. Lighten up `SelectLocationViewController` and move much of the data management outside of controller. I'll wire it up in the follow up PRs.
2. `LocationDataSource`: restore the selected relay in case when the data source is populated with relays after the selected relay was set. 
3. `SelectLocationViewController`: scroll to selected relay when rotating device. This is relevant to iPad builds where we support various interface orientations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2649)

Add select location delegate

---

ios/MullvadVPN/LoginViewController.swift

Git checklist:
1. Extend `LoginViewControllerDelegate` to move the `Account` interactions outside of controller. This will later be leveraged by `AppDelegate` to perform additional actions upon successful log in.
2. Add on-screen keyboard return key handler on iPad
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2651)

LoginViewController: add delegate

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppButton.swift
ios/MullvadVPN/ConnectMainContentView.swift
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/DisconnectSplitButton.swift
ios/MullvadVPN/UIMetrics.swift

Git checklist:
- Enable iPad support in Xcode project
- Make `AppButton` slightly larger on iPad
- Adapt `ConnectViewController` for iPad:
- Hide "Select location" button as the `SelectLocationViewController` is going to be displayed side-by-side with `ConnectViewController`
- Fix the maximum content width to avoid overly long buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2653)

Optimise main controller for iPad

---

android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt
android/src/test/kotlin/net/mullvad/mullvadvpn/di/AppModuleTest.kt

This is fix for proper create and use scoped components. We create a scoped component that contains scope and references for scoped instances. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2670)

Fix koin dependencies.

---

build.sh

This PR makes some changes to the build-script that was recommended by `shellcheck` and a few other improvements. I've added comments with links that explain the changes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2667)

Fix shellcheck recommendations in build.sh

---

android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionError.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt
mullvad-jni/src/lib.rs

This PR refactors the `VoucherSubmissionResult` to separate the error variants into a separate enumeration, called `VoucherSubmissionError`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2697)

Create an enumeration for the `VoucherSubmissionError`

---

ios/MullvadVPN/Account.swift
ios/MullvadVPN/AccountViewController.swift
ios/MullvadVPN/AppStorePaymentManager.swift
ios/MullvadVPN/SettingsViewController.swift

Git checklist:
This PR swaps the notification mechanism to observer mechanism we use elsewhere in the codebase and adds two more events to tell when user logs in and out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2654)

Add account observer

---

ios/MullvadVPN/AppButton.swift
ios/MullvadVPN/ConnectMainContentView.swift
ios/MullvadVPN/DisconnectSplitButton.swift

Git checklist:
1. Fix the button font size from 17pt to 18pt and removes the overrides in view controllers
2. Fix the default content alignment for link buttons from centre to leading.
3. Add `var titleString: String` property to control the label formatting in link buttons, as opposed to overriding the `setTitle(_: String, for:)`. This is a little cleaner way of doing that in my opinion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2708)

App button fixes and improvements

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/ConsentViewController.swift
ios/MullvadVPN/RelayCache.swift
ios/MullvadVPN/RootContainerViewController.swift

Git checklist:
1. Wire up delegates for `LoginViewController`, `ConnectViewController` and `SelectLocationViewController`.
2. Move relay constraints fetching and updating into `AppDelegate`
3. Handle `RelayCache` updates in `AppDelegate`
4. Overall consoldiate the view controller management in `AppDelegate`. Move showing the account controller for expired accounts after login from `ConnectViewController` to `AppDelegate`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2721)

Wireup controller delegates

---

ios/CHANGELOG.md
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/CustomSplitViewController.swift
ios/MullvadVPN/RootContainerViewController.swift
ios/MullvadVPN/UIMetrics.swift

Git checklist:
This PR adds split view controller UI on iPad and makes sure that we properly handle split screen on iPad where the app would resort to iPhone UI when in compact mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2723)

Add user interface for iPad

---

ios/MullvadVPN/ConnectViewController.swift

Git checklist:
This PR replaces "Unsecured connection" with "Unsecure connection"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2740)

Connect: update unsecure connection status string

---

ios/MullvadVPN/AppDelegate.swift

Git checklist:
Lotta PRs and rebasing and it looks like the same function was added twice after rebase, so this PR just drops it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2741)

Fix rebase artifacts

---

dist-assets/windows/installer.nsh
windows/driverlogic/driverlogic.vcxproj
windows/driverlogic/driverlogic.vcxproj.filters
windows/driverlogic/src/devenum.cpp
windows/driverlogic/src/devenum.h
windows/driverlogic/src/device.cpp
windows/driverlogic/src/device.h
windows/driverlogic/src/driverlogic.cpp
windows/driverlogic/src/log.cpp
windows/driverlogic/src/log.h
windows/driverlogic/src/service.cpp
windows/driverlogic/src/service.h
windows/driverlogic/src/util.cpp
windows/driverlogic/src/util.h
windows/driverlogic/src/version.cpp
windows/driverlogic/src/version.h
windows/driverlogic/src/wintun.h

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2666)

Windows: Update installer/uninstaller for split tunneling

---

ios/BuildInstructions.md

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2751)

Update instructions regarding removing old keys and certificates

---

gui/src/main/index.ts
gui/src/shared/logging.ts

This PR improves the format of the sandbox status log message and improves the message outputed to the console when the file-logger fails, it now includes the original error message.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2768)

Improve log messages

---

ios/MullvadVPN/SelectLocationHeaderView.swift
ios/MullvadVPN/SelectLocationViewController.swift

Git checklist:
This PR extracts the footer view from `UITableView` and instead pins it to the hosting view manually. This addresses some of the layout issues on iPad 12.9" with software home button.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2769)

SelectLocation: rework header footer view layout

---

ios/MullvadVPN/ConsentContentView.swift
ios/MullvadVPN/LoginContentView.swift
ios/MullvadVPN/LoginViewController.swift
ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift
ios/Snapfile

Git checklist:
This PR updates AppStore screenshots script to support iPad and adds back accessibility identifiers that were lost during refactoring and used by screenshots script to reference controls around the app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2771)

Add iPad support in screenshots script

---

ios/MullvadVPN/RootContainerViewController.swift

Git checklist:
This PR fixes the double call to `endAppearanceTransition()` on the top child controller. Since both `setViewControllers` and view lifecycle events trigger appearance events on its child controllers, we have to make sure that those are not being issued twice. 
This is the case when `setViewControllers()` is being called in the middle of the view appearance lifecycle, for instance after `viewWillAppear`. So when `viewDidAppear` is called, it naturally calls the `endAppearanceTransition()` on the top child controller, however the preceding call `setViewControllers()` already took care of that, which results in the double call to `endAppearanceTransition()` and "unbalanced appearance …

RootContainer: fix unbalanced appearance events

---

talpid-dbus/src/systemd_resolved.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2810)

Fix nightly compilation error

---

ios/CHANGELOG.md
ios/MullvadVPN/AccountInputGroupView.swift
ios/MullvadVPN/LoginContentView.swift
ios/MullvadVPN/LoginViewController.swift

Git checklist:
This PR adds the submit button next login text field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2805)

Login: add submit button

---

.github/workflows/frontend.yml
gui/package-lock.json
gui/package.json

This is primarily upgraded to customize uninstall code on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2813)

Upgrade electron-builder to v22.11.7

---

gui/locales/messages.pot
gui/src/renderer/components/ExpiredAccountAddTime.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/components/RedeemVoucherStyles.tsx

This PR changes the design of the voucher input dialog to better match the new account screens.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2817)

Redesign voucher dialog

---

talpid-core/src/routing/windows.rs

#2811 included an oversight on Windows. Because `RouteManager::new` was made async but still used [`block_on`](https://docs.rs/tokio/0.2.2/tokio/runtime/struct.Runtime.html#method.block_on), awaiting it caused a panic. `block_on` cannot be called on a tokio worker thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2818)

Remove block_on call from the route manager constructor on Windows

---

mullvad-daemon/src/settings.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2837)

Fix settings update

---

gui/scripts/extract-geo-data.py
gui/scripts/integrate-into-app.py

Git checklist:
This PR wraps the resource allocating calls to `with` statement to ensure that the resources are properly released upon leaving the scope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2839)

Scripts: use "with" statement with resource allocating calls

---

mullvad-setup/src/daemon_paths.rs
windows/nsis-plugins/src/cleanup/cleaningops.cpp
windows/nsis-plugins/src/log/log.cpp
windows/nsis-plugins/src/osinfo/update.cpp
windows/nsis-plugins/src/tray/tray.cpp
windows/windns/src/windns/netsh.cpp

Same as https://github.com/mullvad/windows-libraries/pull/39, but here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2844)

Fix use of `SHGetKnownFolderPath`

---

ios/MullvadVPN/CustomNavigationBar.swift
ios/MullvadVPN/SelectLocationNavigationController.swift
ios/MullvadVPN/SelectLocationViewController.swift

Git checklist:
This PR migrates `CustomNavigationBar` to new `UINavigationBarAppearance` API for appearance customisations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2850)

Migrate to UINavigationBarAppearance API

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/ConnectMainContentView.swift
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/en.lproj/Main.strings

Git checklist:
1. Group country, city and connection status labels in the same container view and assign accessibility label to it.
2. Move main screen localisations to `Main.strings`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2866)

Main controller accessibility + localization

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/SettingsAccountCell.swift
ios/MullvadVPN/SettingsViewController.swift
ios/MullvadVPN/en.lproj/Settings.strings

Git checklist:
This PR moves localizations found in Settings into a separate `Settings.strings` table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2869)

Settings localization

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/LoginContentView.swift
ios/MullvadVPN/LoginViewController.swift
ios/MullvadVPN/en.lproj/Login.strings

Git checklist:
This PR moves the localization strings found in Login controller into a separate table `Login.strings`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2871)

Login localization

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift
ios/MullvadVPN/ProblemReportViewController.swift
ios/MullvadVPN/en.lproj/ProblemReport.strings

Git checklist:
This PR moves localizable strings found in Problem report controller into a separate `ProblemReport.strings` table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2873)

ProblemReport localization

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/SelectLocationCell.swift
ios/MullvadVPN/SelectLocationHeaderView.swift
ios/MullvadVPN/SelectLocationViewController.swift
ios/MullvadVPN/en.lproj/SelectLocation.strings

Git checklist:
This PR moves localizable strings found in Select Location controller into a separate `SelectLocation.strings` table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2874)

SelectLocation localization 

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/ProblemReportReviewViewController.swift
ios/MullvadVPN/en.lproj/ProblemReportReview.strings

Git checklist:
This PR moves localizable strings found in Problem report review controller into a separate `ProblemReportReview.strings` table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2875)

ProblemReportReview localization

---

ios/MullvadVPN/LogStreamerViewController.swift

Git checklist:
Remove `NSLocalizableString` from `LogStreamerViewController` which is only used in development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2884)

Remove NSLocalizedString from LogStreamer

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AccountInputGroupView.swift
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/CustomDateComponentsFormatting.swift
ios/MullvadVPN/DisplayChainedError.swift
ios/MullvadVPN/HeaderBarView.swift
ios/MullvadVPN/MullvadRest.swift
ios/MullvadVPN/UIBarButtonItem+KeyboardNavigation.swift
ios/MullvadVPN/en.lproj/AccountInput.strings
ios/MullvadVPN/en.lproj/AppDelegate.strings
ios/MullvadVPN/en.lproj/AppStorePaymentManager.strings
ios/MullvadVPN/en.lproj/CustomDateComponentsFormatting.strings
ios/MullvadVPN/en.lproj/HeaderBar.strings
ios/MullvadVPN/en.lproj/KeyboardNavigation.strings
ios/MullvadVPN/en.lproj/MullvadRest.strings
ios/MullvadVPN/en.lproj/StoreKitErrors.strings
ios/MullvadVPN/en.lproj/TunnelManager.strings

Git checklist:
This PR adds localizations for the following classes and components: MullvadRest, StoreKit, AppStorePaymentManager, TunnelManager, KeyboardNavigation, AccountInput, AppDelegate, CustomDateComponentsFormatting, HeaderBar.
You can review that PR using commit-by-commit mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2882)

Localize various errors and messages

---

gui/src/main/account-data-cache.ts
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/main/notification-controller.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/Login.tsx
gui/src/renderer/components/SplitTunnelingSettings.tsx
gui/src/renderer/components/SvgMap.tsx
gui/src/renderer/containers/AccountPage.tsx
gui/src/renderer/containers/LoginPage.tsx
gui/src/renderer/containers/PreferencesPage.tsx
gui/src/renderer/containers/SupportPage.tsx
gui/src/renderer/lib/utilityHooks.ts
gui/src/shared/promise.ts

This PR removes some ESLint exceptions and fixes the related warnings/errors.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2886)

Fix a few ESLint exceptions

---

CHANGELOG.md

See https://github.com/mullvad/mullvadvpn-app-binaries/pull/87.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2903)

Update Wintun to version 0.13

---

CHANGELOG.md
gui/assets/images/icon-filter-round.svg
gui/locales/messages.pot
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/AppRouter.tsx
gui/src/renderer/components/FilterByProvider.tsx
gui/src/renderer/components/LocationRow.tsx
gui/src/renderer/components/SelectLocation.tsx
gui/src/renderer/components/SelectLocationStyles.tsx
gui/src/renderer/components/SettingsHeader.tsx
gui/src/renderer/containers/SelectLocationPage.tsx
gui/src/renderer/lib/routes.ts
gui/src/renderer/redux/settings/reducers.ts
gui/src/renderer/redux/store.ts
gui/src/shared/bridge-settings-builder.ts
gui/src/shared/daemon-rpc-types.ts
gui/src/shared/localization-contexts.ts

This PR implements the filter by provider UI in the desktop app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2905)

Filter by provider

---

README.md

Update the README to 1) have correct supported platforms and 2) Add some features we support but don't advertise well enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2899)

Update readme with more features and correct supported platforms

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Logging/Logging.swift
ios/MullvadVPN/Logging/OSLogHandler.swift

Git checklist:
This PR adds `OSLog` handler for Logging framework which enables me to monitor the logs in packet tunnel via Console app on macOS. So far it's been the best way to monitor tunnel process logs in real time while developing the app.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2925)

Add OSLogHandler

---

CHANGELOG.md
gui/src/main/index.ts
gui/src/main/window-controller.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/CustomScrollbars.tsx
gui/src/renderer/components/MacOsScrollbarDetection.tsx
gui/src/renderer/components/NavigationBar.tsx
gui/src/renderer/components/SelectLanguage.tsx
gui/src/renderer/components/SelectLocation.tsx
gui/src/renderer/components/SplitTunnelingSettings.tsx
gui/src/renderer/redux/userinterface/actions.ts
gui/src/renderer/redux/userinterface/reducers.ts
gui/src/shared/ipc-schema.ts

This PR reads the macOS scrollbar visibility setting and detects the visibility if the setting is set to `Automatic`. This is to behave the same as the OS.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2952)

Detect macos scrollbar visibility

---

.github/workflows/ios.yml
ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/build-wireguard-go.sh

Git checklist:
This PR adds caching of dependencies installed via Swift Package Manager (SPM). 
Configuration reference: https://github.com/actions/cache/blob/main/examples.md#swift---swift-package-manager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2971)

Actions: cache spm

---

gui/package-lock.json
gui/package.json
gui/src/main/daemon-rpc.ts

This PR updates gRPC-js to the latest version and updates the code to handle errors correctly in the new version.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2975)

Update grpc js

---

mullvad-cli/src/cmds/bridge.rs
mullvad-cli/src/cmds/relay.rs
mullvad-cli/src/location.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-management-interface/src/types.rs

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2976)

Deduplicate formatting of relays and bridges in CLI

---

talpid-core/src/tunnel/openvpn/windows.rs

Since it isn't necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2980)

Use casts instead of transmute for Wintun

---

talpid-core/src/split_tunnel/windows/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2985)

Remove needless use of lazy_static

---

ios/CHANGELOG.md
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/ApplicationConfiguration.swift
ios/MullvadVPN/Info.plist
ios/MullvadVPN/RelayCache/RelayCacheTracker.swift
ios/MullvadVPN/Result+UIBackgroundFetchResult.swift
ios/MullvadVPN/TunnelManager/TunnelManager.swift

Git checklist:
This PR adds background relay updates and private key rotation.
**iOS 12:**
Uses background fetch (`UIApplicationDelegate.performFetchWithCompletionHandler`) to update
relays and rotate the private key.
**iOS 13:**
Uses new `BackgroundTasks` framework on iOS 13 or newer.
1. Background refresh task to update relays once an hour.
2. Background processing task for private key rotation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2998)

Add background tasks

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/LoginContentView.swift
ios/MullvadVPN/en.lproj/WireguardKeys.strings

Git checklist:
1. Adapt `AppDelegate` to the new REST types.
2. Adapt `AppDelegate` to use new promise based `Account` interface.
3. Enable multiline support for message label in Login view to avoid trimming long error messages emitted during log in.
4. Add missing translation in WireGuarKeys controller.
5. Auto-sort files by name in Xcode project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3008)

Adapt `AppDelegate`

---

talpid-core/src/dns/linux/systemd_resolved.rs

A `MutexGuard` was held across an await boundary. This looks alright in the particular case, but the CI fails due to `must-not-suspend`, so I've worked around it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3013)

Fix mutex/await warning

---

ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/en.lproj/Main.strings

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3075)

Update unsecured connection label

---

ios/MullvadVPN/TunnelSettingsManager.swift

Git checklist:
This PR makes sure that we never force unwrap data coming from Keychain and instead return the appropriate error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3092)

TunnelSettings: improve code safety

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt

Removes SDK checks for non-supported versions (below version 26).
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3102)

Cleanup leftover SDK version checks

---

ios/MullvadVPN/ProblemReportSubmissionOverlayView.swift
ios/MullvadVPN/en.lproj/ProblemReport.strings

Git checklist:
Tiny PR that updates translations in problem report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3113)

ProblemReport: update translations

---

gui/src/main/index.ts

This PR disables the update notification and update text in settings when running Windows < 10.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3116)

Set suggestedUpgrade to undefined if Windows < 10

---

gui/src/main/index.ts

This PR prevent disconnecting from daemon on exit when not connected, and also catch connection error instead of letting it propagate.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3104)

Improve daemon connection error handling

---

build_windows_modules.sh

This is not required (anymore?). Related: #3119.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3125)

Don't copy windows modules to the cargo target directory

---

gui/src/renderer/components/CustomDnsSettings.tsx

Prevent multiple of the same IP in custom DNS address list.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3130)

Prevent duplicate custom DNS addresses

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/NSAttributedString+Markdown.swift
ios/MullvadVPN/PreferencesDataSource.swift
ios/MullvadVPN/PreferencesViewModel.swift
ios/MullvadVPN/en.lproj/Preferences.strings

Git checklist:
1. Add a very basic markdown parser that only supports bold text.
2. Update texts in Custom DNS UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3141)

Update texts in custom DNS UI

---

gui/src/main/index.ts

This PR adds logging for when a subprocess of the GUI exits unexpectedly.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3133)

Add logging when quitting or crashing

---

ios/CHANGELOG.md
ios/MullvadVPN/AppDelegate.swift

Git checklist:
This PR adds an occlusion window with launch controller that covers the application content when user leaves the application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3147)

Hide application content when leaving the app

---

ios/CHANGELOG.md
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/LaunchScreen.storyboard
ios/MullvadVPN/LaunchViewController.swift
ios/MullvadVPN/PreferencesDataSource.swift
ios/MullvadVPN/RootContainerViewController.swift

Git checklist:
1. Update launch screen.
2. Remove unused "segue" related code for Storyboards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3143)

Update launch screen

---

dist-assets/linux/before-remove.sh

This should be self-explanatory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3159)

Kill the GUI when uninstalling the app on Linux

---

CHANGELOG.md
talpid-types/src/net/wireguard.rs

As above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3115)

Use wireguard-nt by default

---

ios/CHANGELOG.md
ios/MullvadVPN/Account.swift

Git checklist:
This PR fixes crash occurring after completing in-app purchase. The cause of crash is related to the use of a wrong background queue for dispatching new account expiry to observers which update UI; main queue should be used instead for all UI related code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3199)

Fix crash occurring after completing in-app purchase

---

mullvad-daemon/src/system_service.rs

This attempts to make the `system_service` module conform a bit better to the [coding guidelines](https://github.com/mullvad/coding-guidelines).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3186)

Improve unsafe code usage in system service module

---

.github/workflows/android-audit.yml
android/app/build.gradle
android/build.gradle

Adds the OWASP Dependency-Check tool to the project to detect
potentially vulnerable dependencies.
The tool is configured to fail the analysis on high severity
vulnerabilities. A few high serverity issues were identified,
however these were suppressed as they are related to the IDE and build
system rather than the actual project itself.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3203)

Add Android dependency audit

---

Cargo.lock
talpid-core/Cargo.toml

Upgrading system-configuration as it's been updated to use newer dependencies, which allows us to drop some of the older ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3232)

Update system-confuguration to 0.5

---

android/app/build.gradle.kts

Fix gradle migration (groovy->kotlin) issue with release builds.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3239)

Fix gradle kotlin release build

---

CHANGELOG.md
gui/locales/messages.pot
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/components/CustomDnsSettings.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/redux/settings/reducers.ts
gui/src/shared/daemon-rpc-types.ts
mullvad-cli/src/cmds/dns.rs
mullvad-daemon/src/lib.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-management-interface/src/types.rs
mullvad-types/src/settings/mod.rs

This PR adds malware block setting to both the Daemon, CLI and GUI.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3245)

Add malware dns blocking

---

CHANGELOG.md
dist-assets/windows/installer.nsh

New driver version + new file locations in the binaries submodule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3255)

Update split tunnel driver to 1.2.0.0

---

gui/src/main/index.ts

This PR adds a call to `updateTrayIcon` when assuming what the next target state will be. The variable naming has also been changed from `ignoreTunnelStateUntil` to `optimisticTunnelState` in `index.tsx` to match `app.tsx`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3220)

Show tray icon matching expected state change

---

android/build.gradle.kts
android/buildSrc/src/main/kotlin/Dependencies.kt
android/buildSrc/src/main/kotlin/Extensions.kt
android/buildSrc/src/main/kotlin/Versions.kt

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3258)

Add Android version check plugin

---

mullvad-daemon/src/relays.rs

A small change to the relay selector to pick a relay with 0 weight if all matching relays have 0 weight.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3262)

If matching relays have 0 weight, pick one randomly

---

mullvad-daemon/mullvad-daemon.manifest

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3269)

Remove Windows 7 and 8/8.1 support from the manifest

---

CHANGELOG.md
gui/changelog.txt
gui/locales/messages.pot
gui/src/main/changelog.ts
gui/src/main/gui-settings.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/Account.tsx
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AppRouter.tsx
gui/src/renderer/components/Changelog.tsx
gui/src/renderer/components/Connect.tsx
gui/src/renderer/components/ErrorBoundary.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/Modal.tsx
gui/src/renderer/components/OpenVPNSettings.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/components/SplitTunnelingSettings.tsx
gui/src/renderer/components/Support.tsx
gui/src/renderer/components/WireguardSettings.tsx
gui/src/renderer/redux/settings/reducers.ts
gui/src/renderer/redux/userinterface/actions.ts
gui/src/renderer/redux/userinterface/reducers.ts
gui/src/shared/gui-settings-state.ts
gui/src/shared/ipc-schema.ts
gui/src/shared/ipc-types.ts
gui/src/shared/localization-contexts.ts
gui/tasks/distribution.js
gui/test/setup/changelog.spec.ts

This PR adds a changelog dialog the following changes was required as well:
* Wrap entire app in `ModalContainer` instead of individual views. This also makes it easier to use modals elsewhere.
* Make modal scrollable if the height wants to be more than `80vh`.
There were also some formatting errors in `distribution.js` which I've also fixed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3291)

Add change view

---

CHANGELOG.md
android/app/src/main/play/release-notes/en-US/default.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3301)

Update changelog from android 2022.1 release branch

---

Cargo.lock
talpid-core/Cargo.toml
talpid-core/src/resolver.rs

Use mainline `trust-dns` crates instead of our own fork.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3298)

Use mainline trust-dns

---

ios/MullvadVPN/AddressCache/UpdateAddressCacheOperation.swift

Git checklist:
This PR adds a `finish()` call to `UpdateAddressCacheOperation`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3309)

UpdateAddressCacheOperation: add missing finish() call

---

talpid-core/src/split_tunnel/windows/driver.rs

And add some docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3333)

Fix deprecation warning on Windows

---

talpid-core/src/split_tunnel/windows/path_monitor.rs

Currently, the path monitor stops if a path points to a volume with an unrecognized file system. It should instead simply ignore such volumes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3337)

Ignore volumes without a known file system in the ST path monitor

---

ios/CHANGELOG.md
ios/MullvadVPN/PreferencesDataSource.swift
ios/MullvadVPN/PreferencesViewModel.swift
ios/MullvadVPN/TunnelSettings.swift
ios/MullvadVPN/en.lproj/Preferences.strings
ios/PacketTunnel/PacketTunnelProvider.swift

Git checklist:
- Add malware blocking toggle to UI.
- Add `blockMalware` to `DNSSettings`. In hindsight, we could have stored a `UInt8` field instead of three boolean flags.
- Compute DNS server IP based on combination of enabled DNS blocking options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3334)

Add malware blocking

---

mullvad-daemon/src/relays/mod.rs

Currently, the relay selector may operate on relays containing nonsensical endpoint data - data containing no port ranges or other such invalid values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3319)

Filter invalid relay endpoints

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3341)

Update changelog for android/2022.1-beta3 and add header

---

gui/package-lock.json
gui/package.json

This PR updates NSEventMonitor and other dependencies that had known vulnerabilities. None of the vulnerabilities affects us.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3355)

Update npm dependencies

---

Cargo.lock
talpid-core/Cargo.toml
talpid-core/src/resolver.rs

Replace `trust-dns` git dependency with an alpha version from `crates.io`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3359)

Use alpha version of trust-dns

---

mullvad-daemon/Cargo.toml
mullvad-management-interface/Cargo.toml
mullvad-problem-report/Cargo.toml
mullvad-rpc/Cargo.toml
mullvad-setup/Cargo.toml
talpid-core/Cargo.toml
talpid-openvpn-plugin/Cargo.toml
talpid-types/Cargo.toml

These changes make all the feature declarations in our `Cargo.toml`s consistent in terms of whitespace usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3362)

Remove superfluous whitespace in feature arrays

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/Changelog.tsx
gui/src/renderer/components/CustomDnsSettings.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/Modal.tsx
gui/src/renderer/components/OpenVPNSettings.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/components/SplitTunnelingSettings.tsx
gui/src/renderer/components/Support.tsx
gui/src/renderer/components/WireguardSettings.tsx

This PR add animations when opening and closing dialogs. It also adds blur to the content behind a modal.
https://user-images.githubusercontent.com/3668602/154476065-0fa5d808-90de-4eff-a61d-488e3e60e87c.mov
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3366)

Add dialog animations

---

mullvad-daemon/src/lib.rs
talpid-core/src/tunnel_state_machine/mod.rs

This is slightly cleaner than dealing with a oneshot receiver in `mullvad-daemon`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3379)

Use tunnel state machine handle instead of plain oneshot

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Account.swift
ios/MullvadVPN/AppStoreReceipt.swift
ios/MullvadVPN/ChainedError.swift
ios/MullvadVPN/CodingErrors+ChainedError.swift
ios/MullvadVPN/ConsolidatedApplicationLog.swift
ios/MullvadVPN/Logging/LogRotation.swift
ios/MullvadVPN/REST/RESTError.swift
ios/MullvadVPN/RelayCache/RelayCacheError.swift
ios/MullvadVPN/TunnelIPC/TunnelIPCError.swift
ios/MullvadVPN/TunnelManager/TunnelManagerError.swift
ios/MullvadVPN/TunnelSettingsManager.swift

Git checklist:
1. Add human readable descriptions to `Account.Error` and `TunnelSettingsManager.Error`.
2. Add period at the end of error descriptions.
3. Add `CustomChainedErrorDescriptionProtocol` to be able to override the error messages printed to error chain.
4. Implement `CustomChainedErrorDescriptionProtocol` for `EncodingError` and `DecodingError`.
5. Make sure `AnyChainedError` handles the `source` properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3367)

Improve error output

---

gui/src/renderer/app.tsx

This PR adds sorting to the language list in the app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3392)

Sort language list

---

mullvad-daemon/src/api.rs
mullvad-daemon/src/lib.rs
mullvad-rpc/src/lib.rs
mullvad-rpc/src/rest.rs

This PR refactors the logic surrounding API endpoint updates and moves it to the `api` submodule. The main reason for doing this is to make it possible to create the REST client before the tunnel state machine is running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3394)

Refactor API endpoint updater

---

talpid-core/src/tunnel/wireguard/mod.rs

Due to #3385, all tunnel routes except `10.64.0.1` are added after the connectivity monitor has verified that the tunnel works. This means that the exit endpoint cannot be reached (as the monitor tries to send its packets outside the tunnel). This PR updates the code to add all routes _except_ the default route before the tunnel has been established.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3404)

Fix connectivity monitor for multihop

---

mullvad-rpc/src/https_client_with_sni.rs

This removes pointless copies by pinning some futures to the stack instead of the heap, and removes some other duplications.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3411)

Simplify the HTTPS connector

---

android/app/build.gradle.kts
android/buildSrc/src/main/kotlin/Versions.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3438)

Bump Android dependencies

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
android/app/src/main/kotlin/net/mullvad/talpid/util/EventNotifier.kt

Adapts the Android app to use the device login/logout functionality.
Limitations:
* State will not always be correctly propagated to all components of the
app (i.e. Settings). This will be fixed in later device commits.
* Some temporary error messages will be used in the Login view. These
will change in later commits and/or be replaced with new views (i.e.
when a user has too many devices registered).
Git checklist:
~~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~~ (not finalized)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3443)

Initial adaption of Android login to device flow

---

ios/MullvadVPN/ConnectMainContentView.swift
ios/MullvadVPN/ConnectViewController.swift
ios/MullvadVPN/LoginViewController.swift
ios/MullvadVPN/SpinnerActivityIndicatorView.swift
ios/MullvadVPN/TunnelIPC/PacketTunnelStatus.swift
ios/PacketTunnel/PacketTunnelProvider.swift

Git checklist:
1. Show activity spinner in the main UI when connecting and reconnecting. Change large spinner size from 48 -> 60.
2. Show location marker only when connected.
3. iPad: show "cancel" button instead of "disconnect" button when connecting.
4. Login: disable "Create account" button as user starts typing in the account token. iPad only as the on-screen keyboard overlays the "Create account" button on iPhone and it would be impossible for user to know what caused the button to be dimmed. I am open for discussion on this one though.
--- …

Improve main UI

---

ios/CHANGELOG.md
ios/MullvadVPN/Account.swift
ios/MullvadVPN/AccountViewController.swift
ios/MullvadVPN/AppStorePaymentManager/AppStorePaymentManager.swift
ios/MullvadVPN/AppStorePaymentManager/AppStorePaymentManagerError.swift
ios/MullvadVPN/AppStorePaymentManager/AppStorePaymentObserver.swift
ios/MullvadVPN/DisplayChainedError.swift
ios/MullvadVPN/en.lproj/AppStorePaymentManager.strings

Git checklist:
This PR adds additional account token validation before charging user (in-app purchases). Safeguards from trying to add credits on accounts that are no longer exist on our backend. Usually the case with newly created accounts that went stale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3445)

Validate account before in-app purchase

---

ios/CHANGELOG.md
ios/MullvadVPN/ApplicationConfiguration.swift
ios/MullvadVPN/ConsentViewController.swift
ios/MullvadVPN/SettingsCell.swift
ios/MullvadVPN/SettingsDataSource.swift
ios/MullvadVPN/SettingsViewController.swift
ios/MullvadVPN/en.lproj/Settings.strings

Git checklist:
- Add FAQ and Guides link in Settings, opens in-app Safari browser.
- Update privacy link URL.
- Implement new `safariViewControllerWillOpenInBrowser` Safari controller delegate method (iOS 14+) to automatically close the in-app safari controller, as user transitions to standalone Safari browser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3452)

Add FAQ and Guides link

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays/mod.rs

The Android build is failing because of these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3460)

Add missing cfg attributes

---

talpid-core/src/tunnel/wireguard/mod.rs

The route filter was broken on macOS (those 0-prefix routes were replaced before filtering them). Not sure how this could ever have worked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3457)

Filter routes correctly before starting the connectivity monitor

---

ios/MullvadVPN/SettingsDataSource.swift

Git checklist:
This PR fixes a small bug that prevented the account expiry from being refreshed in Settings controller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3463)

Settings: fix account expiry refresh

---

mullvad-daemon/src/device.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/migrations/device.rs
mullvad-daemon/src/migrations/mod.rs
mullvad-management-interface/proto/management_interface.proto

The GUI can use this to detect whether the daemon is being upgraded from a non-device-aware version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3478)

Add post-upgrade RPC

---

mullvad-cli/src/cmds/status.rs

This PR moves the verbose flag on `status listen` to `status` and makes it affect the tunnel state as well.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3492)

Make cli status verbose flag affect tunnel state

---

Cargo.lock
mullvad-api/Cargo.toml
talpid-core/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3498)

Bump shadowsocks

---

mullvad-api/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3509)

Use DDoS protection IP for the API

---

CHANGELOG.md

See the [changelog](https://github.com/mullvad/win-split-tunnel/blob/v1.2.1.0/CHANGELOG.md) for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3518)

Update split tunnel driver to 1.2.1.0

---

android/e2e/README.md

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3517)

Add Android e2e test readme

---

android/app/build.gradle.kts

Fixes an issue with the source directory configuration that affected release builds.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3523)

Fix Android gradle release config

---

talpid-core/src/dns/linux/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3542)

Fix log about selected DNS manager

---

mullvad-daemon/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3538)

Enter the error state immediately when the device is known to have been revoked

---

mullvad-api/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3546)

Ignore account number in all API responses except account creation

---

mullvad-daemon/src/device/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3551)

Wipe the device config if it cannot be parsed

---

mullvad-daemon/src/dns.rs
mullvad-daemon/src/lib.rs
mullvad-types/src/settings/dns.rs
mullvad-types/src/settings/mod.rs

This should not be handled by `Daemon`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3549)

Move conversion of DNS options to addresses to mullvad-types

---

mullvad-api/src/access.rs
mullvad-api/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3559)

Use stable device API endpoints

---

mullvad-daemon/src/api.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/macos.rs

Yet another tiny PR (continuation of #3556).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3557)

Move forwarding functions for the API client to the api module

---

mullvad-daemon/src/device/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3565)

Log WireGuard key rotation

---

talpid-dbus/src/network_manager.rs

Fixing small typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3585)

Fix small typo in DNS code

---

ios/PacketTunnel/Pinger.swift

Git checklist:
- Use custom sequence producing `UInt16` elements when computing [internet checksum](https://www.alpharithms.com/internet-checksum-calculation-steps-044921/).
- Accumulate sum into `UInt16` instead of `Int32`.
- Use [overflow operators](https://docs.swift.org/swift-book/LanguageGuide/AdvancedOperators.html#ID37) to safely produce the sum (`&+`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3596)

Refactor inet checksum computation

---

gui/src/renderer/app.tsx

This PR logs out the daemon when navigating from the revoked view to the login view.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3590)

Log out when exiting revoked view

---

gui/locales/README.md

This PR updates the locale documentation with instructions for how to integrate the new translations into the android app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3602)

Add android translation integration documentation

---

mullvad-cli/src/format.rs

Fixes #3620
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3626)

fix minor typo Deamon -> Daemon

---

.github/workflows/ios.yml
ios/BuildInstructions.md
ios/Configurations/.gitignore
ios/Configurations/App.xcconfig.template
ios/Configurations/Base.xcconfig.template
ios/Configurations/PacketTunnel.xcconfig.template
ios/Configurations/Screenshots.xcconfig.template
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/ApplicationConfiguration.swift
ios/MullvadVPN/Info.plist
ios/MullvadVPN/MullvadVPN.entitlements
ios/PacketTunnel/Info.plist
ios/PacketTunnel/PacketTunnel.entitlements
ios/README.md

Git checklist:
This PR makes it possible to customise bundle ID and generally override Xcode project settings via Xcode configuration files (`xcconfig`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3630)

Add Xcode build configuration

---

CHANGELOG.md
gui/src/main/index.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3631)

Force the right color profile to be used

---

ios/CHANGELOG.md
ios/MullvadVPN/DNSSettings.swift
ios/MullvadVPN/PreferencesDataSource.swift
ios/MullvadVPN/PreferencesViewModel.swift

Git checklist:
- Add blocking option for gambling and adult content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3634)

Add gambling adult content blocking

---

ios/MullvadVPN/Operations/AsyncOperation.swift

Git checklist:
This is a small PR that replaces tracking of `self.isReady` with tracking of individual dependencies to avoid dealing with KVO on `self.isReady` due to potential for an infinite feedback loop since modifying `state` from KVO observer could trigger another recursive KVO pass.
As per documentation definition for `NSOperation`, the operation should be `ready` to execute once all of its dependencies are finished:
> By default, an operation object that has dependencies is not considered ready until all of its dependent operation objects have finished executing. Once the last dependent operation finishes, however, the operation object becomes ready and able to execute.
---
This change …

Observe individual dependencies

---

talpid-core/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3672)

Add missing features for crate in talpid-core

---

ios/MullvadVPN/ApplicationConfiguration.swift

Git checklist:
This PR updates the default API endpoint to the new DDOS protected one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3675)

Update default API endpoint

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/Info.plist
ios/MullvadVPN/SceneDelegate.swift
ios/MullvadVPN/SimulatorTunnelProvider.swift
ios/MullvadVPN/TermsOfService.swift
ios/MullvadVPN/TermsOfServiceContentView.swift
ios/MullvadVPN/TermsOfServiceViewController.swift
ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift

Git checklist:
This is a draft PR that implements `UISceneDelegate` but also maintains a fallback for iOS 12.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3676)

Implement scene delegate

---

talpid-core/src/split_tunnel/windows/mod.rs
talpid-core/src/tunnel_state_machine/mod.rs

Same as #3649 but for all sleeping states, S1-S4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3666)

Reset ST driver state when resuming from suspended mode

---

ios/MullvadVPN/AccountInputGroupView.swift

Git checklist:
This PR improves accessibility in login view by adding appropriate labels around last used account and also notifying the accessibility engine when last account row is being collapsed or expanded, along with hiding accessibility elements when it's collapsed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3706)

Improve accessibility login view

---

Cargo.lock

Some of them were on alpha versions. Upgraded these to "stable" release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3724)

Upgrade all trust-dns related crates

---

CHANGELOG.md
Cargo.lock
mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-exclude/Cargo.toml
mullvad-problem-report/Cargo.toml
mullvad-setup/Cargo.toml
talpid-openvpn-plugin/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3728)

Add changelog header for `2022.3-beta2`

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt

Fixes issues with some text views sometime not being shown due to how the lifecycle of subscriptions are handled.
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header~ (fixed regression)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3731)

Fix text views sometimes missing

---

android/README.md
build.sh
gui/locales/README.md
scripts/localization
scripts/utils/log

This PR adds a localization helper script which helps with the localization/translation process to prevent mistakes. The locales readme has also been updated to reflect these changes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3744)

Add localization helper script

---

.github/workflows/verify-locked-down-signatures.yml

Add swift Package.resolved to the list of locked down paths
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3726)

Add swift Package.resolved

---

mullvad-daemon/src/version_check.rs

Previously, when you ran `mullvad version` in a dev build, you'd see the following error:
```
[2022-06-23 13:23:46.360][mullvad_daemon][DEBUG] No version cache found. Fetching new info
[2022-06-23 13:23:46.360][mullvad_daemon][ERROR] Error: Error running version check
Caused by: Version cache update was aborted
```
This is because all commands sent to the version check actor were dropped.
This PR makes the following changes:
1. When running a dev build, always return valid (fake) version info.
2. When running the version check explicitly, just log a message pointing out that version checks are disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3751)

Saner logging when version checks are disabled

---

CHANGELOG.md
gui/src/renderer/components/Filter.tsx
gui/src/renderer/containers/SelectLocationPage.tsx
gui/src/renderer/lib/filter-locations.ts

This PR makes the filtering lists adjust the available options based on the other filters to prevent incompatible combinations of filters.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3757)

Filter filters

---

Cargo.lock
mullvad-daemon/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3761)

Update windows-service crate

---

CHANGELOG.md
gui/locales/messages.pot
gui/src/renderer/components/TooManyDevices.tsx

This PR:
1. Fixes the behavior of the spinner during device removal
2. Correctly handles errors during device removal
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3771)

Handle error during device removal

---

CHANGELOG.md
gui/locales/messages.pot
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/ConnectionPanel.tsx
gui/src/renderer/components/Filter.tsx
gui/src/renderer/components/SelectLanguage.tsx
gui/src/renderer/components/WireguardSettings.tsx
gui/src/renderer/components/cell/Section.tsx
gui/src/renderer/components/cell/Selector.tsx
gui/src/renderer/redux/settings/actions.ts
gui/src/renderer/redux/settings/reducers.ts
gui/src/shared/daemon-rpc-types.ts
gui/src/shared/ipc-schema.ts

This PR adds the obfuscation options under "WireGuard settings". Fixes https://github.com/mullvad/mullvadvpn-app/issues/3742.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3772)

Add obfuscation settings

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt

Remove redudant expiry fetching which is already handled by the account repository.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3764)

Remove redundant expiry fetching

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3781)

Fix login error message

---

ios/MullvadVPN/HeaderBarView.swift

Git checklist:
Small PR that avoids force unwrap in header logo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3784)

Avoid force unwrapping in HeaderBar

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/ConnectContentView.swift
ios/MullvadVPN/NSLayoutConstraint+Helpers.swift
ios/MullvadVPN/SettingsStaticTextFooterView.swift

Git checklist:
This PR adds a chaining method `NSLayoutConstraint.withPriority(UILayoutPriority)`. Circumvents unnecessary assignment of constraint to a variable for the purpose of changing constraint priority.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3783)

Add NSLayoutConstraint priority helper

---

ios/MullvadVPN/ConnectViewController.swift

Git checklist:
1. Fix force UIImage force unwrapping
2. Return empty `MKOverlayRenderer` in place of normally unreachable `fatalError()` dead end.
3. Add reuse identifier for marker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3788)

Fix potentially unsafe code in main controller

---

gui/locales/README.md
scripts/localization

Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3780)

Add sync only localization script option

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Dialog.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/DeviceListUiState.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/model/DeviceList.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/DaemonDeviceDataSource.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/DeviceListFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/DeviceRepository.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionDeviceDataSource.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceListViewModel.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt
android/app/src/main/res/values/strings.xml
android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt

This PR aims to improve the device management by adding error handling as well as loading indicators to each item in the device management list UI.
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (fix for unreleased feature)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3797)

Improve device list management

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt

Fixes flicker on login to expired account which was caused by the transition Login->Connect->Expired rather than Login->Expired, which is fixed by awaiting updated expiry data on login.
Git checklist:
~* [] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (regression)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3798)

Fix flicker on login to expired account

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt

Reverts part of the changes in the following commit due to how scopes
are used: 9258a8825a9ffc5b30faad6700d71dde87680554
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (already in changelog)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3800)

Fix scope usage in tile service

---

gui/tasks/distribution.js

When we last ran `npm audit fix` some transitive dependency of `electron-builder` was updated which now fires the `afterPack` event for the universal packaging as well on macOS. This caused our build script to fail. This PR disables the code that checks that all resources exists for the universal packaging since it doesn't have any resources of its own.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3825)

Fix universal build after last npm audit fix

---

.github/workflows/verify-locked-down-signatures.yml

This ensures that commits that make changes to go dependencies must be signed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3830)

Detect changes to go.sum in lockfile signature workflow

---

gui/tsconfig.json

This PR adds the `forceConsistentCasingInFileNames` to `tsconfig.json` to ensure that all TS files are cased correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3845)

Add forceConsistentCasingInFileNames tsconfig flag

---

gui/src/main/account.ts
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/main/ipc-event-channel.ts
gui/src/main/notification-controller.ts
gui/src/main/problem-report.ts
gui/src/main/relay-list.ts
gui/src/main/settings.ts
gui/src/main/tray-icon-controller.ts
gui/src/main/tunnel-state.ts
gui/src/main/user-interface.ts
gui/src/main/version.ts
gui/src/main/window-controller.ts
gui/src/renderer/app.tsx
gui/src/shared/ipc-helpers.ts

This PR refactors `index.ts` and `app.tsx` by moving code out of the main classes since especially `index.ts` had become way to large and contained a lot of logic which was easily extracted. There's more work to do here but this serves as a good starting point.
The `notify` functions in `IpcMainEventChannel` is now also curried with the current `WebContents` to make it easier to call those functions. The function will be replaced by `undefined` if there's no `WebContents`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3820)

Refactor index.ts

---

ios/CHANGELOG.md
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/SceneDelegate.swift
ios/MullvadVPN/SettingsCell.swift
ios/MullvadVPN/SettingsDataSource.swift
ios/MullvadVPN/SettingsNavigationController.swift
ios/MullvadVPN/SettingsViewController.swift
ios/MullvadVPN/ShortcutsDataSource.swift
ios/MullvadVPN/ShortcutsDataSourceDelegate.swift
ios/MullvadVPN/ShortcutsManager.swift
ios/MullvadVPN/ShortcutsViewController.swift

PR adds setting to add, edit and delete shortcuts from the app.
It seems this is a more natural way to add shortcuts for most users rather than configure each of them manually via Shortcuts app on every device.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3850)

Add shortcuts

---

CHANGELOG.md
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AccountRepository.kt

Fixes an unsafe cast by using the Kotlin safe-cast mechanism.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3872)

Fix unsafe cast

---

mullvad-daemon/src/lib.rs

As above.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3888)

Swallow spurious 'failed to bypass socket' error

---

gui/locales/messages.pot
gui/src/renderer/components/BridgeLocations.tsx
gui/src/renderer/components/LocationList.tsx
gui/src/renderer/components/LocationRow.tsx

This PR fixes the appearance of the "Automatic" item in the bridge selection list. It also uses the same components as `LocationRow` to build the item.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3884)

Fix automatic item in bridge selector

---

.github/workflows/verify-locked-down-signatures.yml

This PR adds the following gradle lockfiles to the signature lockdown check:
```
android/gradle/verification-metadata.xml
android/gradle/wrapper/gradle-wrapper.properties
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3897)

Add gradle lockfiles to signature lockdown check

---

android/app/src/main/res/values-da/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-ja/strings.xml
android/app/src/main/res/values-nl/strings.xml
android/app/src/main/res/values-th/strings.xml
android/app/src/main/res/values-tr/strings.xml
android/app/src/main/res/values-zh-rTW/strings.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

This PR aims to fix the grammar of the message presented to a user after submitting a problem report in the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3917)

Fix problem report follow up text

---

android/app/src/main/res/values-da/strings.xml
android/app/src/main/res/values-de/strings.xml
android/app/src/main/res/values-es/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-it/strings.xml
android/app/src/main/res/values-ja/strings.xml
android/app/src/main/res/values-ko/strings.xml
android/app/src/main/res/values-my/strings.xml
android/app/src/main/res/values-nb/strings.xml
android/app/src/main/res/values-nl/strings.xml
android/app/src/main/res/values-pl/strings.xml
android/app/src/main/res/values-pt/strings.xml
android/app/src/main/res/values-ru/strings.xml
android/app/src/main/res/values-sv/strings.xml
android/app/src/main/res/values-th/strings.xml
android/app/src/main/res/values-tr/strings.xml
android/app/src/main/res/values-zh-rCN/strings.xml
android/app/src/main/res/values-zh-rTW/strings.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

This PR updates the problem report error text to match the desktop apps. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3916)

Fix problem report error text

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountInput.kt

"create account" button state in login page will change based on user's typing status
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3934)

Disable signup button after start typing

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

As above.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3961)

Fix links for third-party translation contributions

---

android/translations-converter/src/main.rs
mullvad-cli/src/cmds/auto_connect.rs
mullvad-cli/src/cmds/beta_program.rs
mullvad-cli/src/cmds/block_when_disconnected.rs
mullvad-cli/src/cmds/bridge.rs
mullvad-cli/src/cmds/lan.rs
mullvad-cli/src/cmds/obfuscation.rs
mullvad-cli/src/cmds/relay.rs
mullvad-cli/src/cmds/tunnel.rs
mullvad-daemon/build.rs
mullvad-daemon/src/cli.rs
mullvad-daemon/src/version_check.rs
talpid-core/src/dns/linux/static_resolv_conf.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/wireguard/config.rs
talpid-core/src/tunnel/wireguard/connectivity_check.rs
talpid-dbus/src/network_manager.rs
talpid-types/src/net/wireguard.rs

Clippy has been raising some complaints about various bits of code, so I went ahead and fixed all of them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3968)

Fix clippy complaints

---

dist-assets/pkg-scripts/postinstall

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3972)

Don't fail if brew is not installed

---

.github/workflows/android-app.yml
.github/workflows/cargo-audit.yml
.github/workflows/clippy.yml
.github/workflows/daemon.yml
.github/workflows/rust-unused-dependencies.yml
Cargo.lock
README.md
deny.toml
mullvad-cli/src/cmds/tunnel.rs
mullvad-management-interface/Cargo.toml
mullvad-management-interface/src/types.rs
talpid-core/Cargo.toml
talpid-openvpn-plugin/Cargo.toml
talpid-tunnel-config-client/Cargo.toml

As per the title, updating the tonic and prost dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3945)

Update tonic to 0.8 and prost to 0.11

---

Cargo.lock
mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-problem-report/Cargo.toml
mullvad-setup/Cargo.toml
mullvad-setup/src/daemon_paths.rs
talpid-core/Cargo.toml
talpid-core/src/dns/windows/dnsapi.rs
talpid-core/src/routing/windows.rs
talpid-core/src/split_tunnel/windows/driver.rs
talpid-core/src/split_tunnel/windows/mod.rs
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/wintun.rs
talpid-core/src/tunnel/windows.rs
talpid-core/src/tunnel/wireguard/wireguard_go.rs
talpid-core/src/tunnel/wireguard/wireguard_nt.rs
talpid-core/src/windows/mod.rs
talpid-core/src/windows/window.rs
talpid-openvpn-plugin/Cargo.toml
talpid-platform-metadata/Cargo.toml

This also replaces a couple of byte literals with [`w!`](https://docs.rs/windows-sys/latest/windows_sys/macro.w.html).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3976)

Bump windows-sys to 0.42.0

---

gui/locales/da/messages.po
gui/locales/de/messages.po
gui/locales/es/messages.po
gui/locales/fi/messages.po
gui/locales/fr/messages.po
gui/locales/it/messages.po
gui/locales/ja/messages.po
gui/locales/ko/messages.po
gui/locales/messages.pot
gui/locales/my/messages.po
gui/locales/nb/messages.po
gui/locales/nl/messages.po
gui/locales/pl/messages.po
gui/locales/pt/messages.po
gui/locales/ru/messages.po
gui/locales/sv/messages.po
gui/locales/th/messages.po
gui/locales/tr/messages.po
gui/locales/zh-CN/messages.po
gui/locales/zh-TW/messages.po
gui/src/renderer/components/AppRouter.tsx
gui/src/renderer/components/Settings.tsx
gui/src/renderer/components/UserInterfaceSettings.tsx
gui/src/renderer/lib/routes.ts
gui/src/shared/localization-contexts.ts
gui/test/unit/history.spec.ts

This PR changes the name of "Interface settings" to "User interface settings".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3973)

Change name of interface settings

---

ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/AutomaticKeyboardResponder.swift
ios/MullvadVPN/DataSourceSnapshot.swift
ios/MullvadVPN/DeviceManagementContentView.swift
ios/MullvadVPN/DeviceManagementViewController.swift
ios/MullvadVPN/NotificationController.swift
ios/MullvadVPN/SelectLocationViewController.swift
ios/MullvadVPN/TunnelManager/PacketTunnelOptions.swift
ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift
ios/Operations/AlertPresenter.swift

Changed content Inset adjustment behavior to always, This trick solves the scroll issue on iPhone 13 mini, and keeps our original implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3979)

Fix scrolling issue in device management view

---

ci/buildserver-build.sh
ci/buildserver-upload.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3974)

Add arm64 Linux packages to build server scripts

---

gui/src/renderer/components/CustomScrollbars.tsx
gui/src/renderer/components/NavigationBar.tsx

- Use rounded corners on Scrollbar backgrodun
- Remove unused code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3984)

Rounded background on scrolbars

---

docs/security.md

This PR aims to improve/clarify security documentation related to `MUL22-03` which highlighted traffic leaks caused by the Android system exempting certain traffic from having to use the VPN app/tunnel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3996)

Document Android leaks related to MUL22-03

---

android/app/src/main/res/values/strings.xml
android/translations-converter/src/normalize.rs
gui/locales/da/messages.po
gui/locales/de/messages.po
gui/locales/es/messages.po
gui/locales/fi/messages.po
gui/locales/fr/messages.po
gui/locales/it/messages.po
gui/locales/ja/messages.po
gui/locales/ko/messages.po
gui/locales/messages.pot
gui/locales/my/messages.po
gui/locales/nb/messages.po
gui/locales/nl/messages.po
gui/locales/pl/messages.po
gui/locales/pt/messages.po
gui/locales/ru/messages.po
gui/locales/sv/messages.po
gui/locales/th/messages.po
gui/locales/tr/messages.po
gui/locales/zh-CN/messages.po
gui/locales/zh-TW/messages.po
gui/src/renderer/components/ExpiredAccountAddTime.tsx
gui/src/renderer/components/Login.tsx
gui/src/renderer/components/ProblemReport.tsx

This PR changes change apostrophes in all texts from straight to curly apostrophes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3997)

Change straight apostrophes to curly apostrophes

---

gui/src/renderer/components/cell/Selector.tsx

This PR fixes the last known remaining issue of the custom port selection input. Previously the items flickered if an item was clicked while the input was focused. This is solved in this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4001)

Fix flickering when selecting a selector value while custom is focused

---

android/config/dependency-check-suppression.xml
android/e2e/e2e-suppression.xml

This suppression only affects the Android app.
The CVE will instead be tracked externally and will likely be mitigated by either updating affected dependencies or by identifying that it doesn't affect the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4006)

Suppress CVE-2022-3171 from automatic audit checks

---

BuildInstructions.md
android/BuildInstructions.md

This PR aims to fix/update a few minor things in the android build instructions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4013)

Fix android build instructions

---

gui/src/renderer/components/AppRouter.tsx

This PR makes AppRouter a functional component
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4028)

Make AppRouter a functional component

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/VpnServiceModule.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt

Also prevent foreground service notification from being dismissed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4018)

Add notification permission for android 13

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/DisplayChainedError.swift
ios/MullvadVPN/REST/RESTError.swift
ios/MullvadVPN/REST/RESTNetworkOperation.swift
ios/MullvadVPN/REST/RESTProxy.swift
ios/MullvadVPN/REST/RESTProxyFactory.swift
ios/MullvadVPN/REST/RESTTransport.swift
ios/MullvadVPN/REST/RESTTransportRegistry.swift
ios/MullvadVPN/REST/URLSessionTransport.swift
ios/MullvadVPN/SimulatorTunnelProviderHost.swift
ios/MullvadVPN/TransportMonitor/PacketTunnelTransport.swift
ios/MullvadVPN/TransportMonitor/TransportMonitor.swift
ios/MullvadVPN/TunnelManager/ProxyURLRequest.swift
ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift
ios/MullvadVPN/TunnelManager/Tunnel+Messaging.swift
ios/MullvadVPN/TunnelManager/TunnelManager.swift
ios/MullvadVPN/TunnelManager/TunnelProviderMessage.swift
ios/PacketTunnel/PacketTunnelProvider.swift

Created transport models,
Created cancel logic,
Created transport feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3998)

Packet tunnel transport for http(s) requests

---

android/README.md
gui/locales/README.md

This PR aims to document which phrases and terms shouldn't be translated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4035)

Document DNT phrases and terms

---

.github/workflows/unicode-check.yml

This PR updates actions/checkout to v3, which uses Node 16.
It removes the warning messages otherwise displayed, for instance here: https://github.com/mullvad/mullvadvpn-app/actions/runs/3249161714
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4046)

Update unicode-check workflow

---

CHANGELOG.md
windows/winfw/src/winfw/fwcontext.cpp
windows/winfw/src/winfw/mullvadguids.cpp
windows/winfw/src/winfw/mullvadguids.h
windows/winfw/src/winfw/rules/dns/blockall.cpp
windows/winfw/src/winfw/rules/dns/permitloopback.cpp
windows/winfw/src/winfw/rules/dns/permitloopback.h
windows/winfw/src/winfw/winfw.vcxproj
windows/winfw/src/winfw/winfw.vcxproj.filters

As above.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4047)

Allow loopback traffic in the DNS sublayer in WinFw

---

.github/workflows/android-ktlint.yml

This PR update actions/checkout to v3 that uses Node 16
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4053)

Update Android ktlint workflow

---

.github/workflows/frontend.yml
.github/workflows/translations.yml

This PR updates the Volta action from v1 to v4 due to it failing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4060)

Update volta-action to v4

---

gui/src/renderer/containers/SelectLocationPage.tsx

This PR makes SelectLocationPage use hooks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4040)

Make SelectLocationPage use hooks

---

.dockerignore
Dockerfile

Very very WIP! And I'm probably not the one who will complete this project. But I felt we needed to share this somewhere. I know @pinkisemils also has a WIP dockerfile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3986)

Setting up a dockerfile for building the desktop app

---

audits/2022-10-14-atredis.md

The better formulation you pointed out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4076)

Fix text around privesc in MUL22-01

---

Dockerfile

Adding description, license and repository URL to the container image. Clean metadata is :chefs-kiss:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4083)

Add LABELs to the Linux build container

---

.github/workflows/android-app.yml

This PR aims to switch to container builds of the android app in GitHub Actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4092)

Build android app using container in gh actions

---

ios/MullvadVPN/SceneDelegate.swift

This PR removes window factory that was previously used to produce instances of `UIWindow` for iOS 12 and newer. Scene based API can be used directly on iOS 13 or newer especially now when we're moving away from iOS 12.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4094)

Remove window factory

---

.github/workflows/android-app.yml

This PR aims to bump some actions used in for the android build in gh actions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4116)

Bump android build actions

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/RevokedDeviceInteractor.swift
ios/MullvadVPN/RevokedDeviceViewController.swift
ios/MullvadVPN/SceneDelegate.swift

This PR moves business logic of `RevokedDeviceViewController` into interactor class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4107)

Add revoked device interactor

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/OutOfTimeInteractor.swift
ios/MullvadVPN/OutOfTimeViewController.swift
ios/MullvadVPN/SceneDelegate.swift

1. Add interactor for `OutOfTimeViewController`
2. Replace `SettingsButtonInteractionDelegate` with `OutOfTimeViewControllerDelegate` in out of time controller.
3. Clean up `OutOfTimeViewController` code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4109)

Add interactor for out of time controller

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AccountInteractor.swift
ios/MullvadVPN/AccountViewController.swift
ios/MullvadVPN/PreferencesInteractor.swift
ios/MullvadVPN/PreferencesViewController.swift
ios/MullvadVPN/ProblemReportInteractor.swift
ios/MullvadVPN/ProblemReportViewController.swift
ios/MullvadVPN/SceneDelegate.swift
ios/MullvadVPN/SettingsDataSource.swift
ios/MullvadVPN/SettingsInteractor.swift
ios/MullvadVPN/SettingsInteractorFactory.swift
ios/MullvadVPN/SettingsNavigationController.swift
ios/MullvadVPN/SettingsViewController.swift

This PR adds interactors for settings and all child controllers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4112)

Add settings interactors

---

CHANGELOG.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4127)

Fix changelog header

---

ios/CHANGELOG.md
ios/MullvadTypes/PacketTunnelStatus.swift
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/TunnelManager/TunnelManager.swift
ios/PacketTunnel/PacketTunnelProvider.swift

When app tries to recover connection,
Counting number of failed attempts, and after an interval, trying to diagnostic the error:
1. Check if device is revoked,
2. Check if account ran out of time
3. Report error
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4124)

Detect revoked device and expired account

---

talpid-routing/src/windows/get_best_default_route.rs
talpid-routing/src/windows/route_manager.rs
talpid-wireguard/src/wireguard_go.rs

This PR refactors some routing code on Windows, primarily the function that fetches the routing table.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4134)

Refactor routing code on Windows

---

CHANGELOG.md
android/app/src/main/res/layout/settings.xml
android/app/src/main/res/values/strings.xml
android/app/src/main/res/values/strings_non_translatable.xml
gui/locales/messages.pot

This PR aims to add a privacy policy link settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4142)

Add privacy policy link in settings

---

CHANGELOG.md
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/PrivacyDisclaimerRepository.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/PrivacyDisclaimerFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionManager.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/PrivacyDisclaimerViewModel.kt
android/app/src/main/res/layout/settings.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

This PR aims to add an initial privacy disclaimer to the Android app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4145)

Add initial privacy disclaimer on android

---

ios/MullvadREST/RESTDefaults.swift
mullvad-api/src/lib.rs

Update default API endpoint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4155)

Update API IP

---

android/docker/Dockerfile

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4191)

Update Android container to java 11

---

android/app/build.gradle.kts
build-apk.sh
building/containerized-build.sh
ci/buildserver-build-android.sh
ci/buildserver-build.sh

This PR aims to create a new Android specific build server script that builds the Android app in a container.
This PR relies on: #4184
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4186)

Add container based android build server script

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/Notifications/InAppNotificationDescriptor.swift
ios/MullvadVPN/Notifications/InAppNotificationProvider.swift
ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryNotificationProvider.swift
ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift
ios/MullvadVPN/Notifications/NotificationManager.swift
ios/MullvadVPN/Notifications/NotificationManagerDelegate.swift
ios/MullvadVPN/Notifications/NotificationProvider.swift
ios/MullvadVPN/Notifications/NotificationProviderProtocol.swift
ios/MullvadVPN/Notifications/SystemNotificationProvider.swift
ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift
ios/MullvadVPN/Notifications/UI/NotificationContainerView.swift
ios/MullvadVPN/Notifications/UI/NotificationController.swift

- Extract notification related types into separate files.
- Move system notification response handling into notification manager and providers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4203)

Refactor notifications

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ConnectionProxy.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionDeviceDataSource.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/MessengerExtensions.kt
android/app/src/test/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxyTest.kt
android/app/src/test/kotlin/net/mullvad/mullvadvpn/service/ServiceConnectionDeviceDataSourceTest.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4158)

Fix DeadObjectException on connecting to the relay

---

android/config/dependency-check-suppression.xml
android/e2e/e2e-suppression.xml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4213)

Suppress CVE-2022-3510 and CVE-2022-41915

---

android/config/dependency-check-suppression.xml
android/e2e/e2e-suppression.xml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4214)

Set CVE suppression expiration to 2023-05-01

---

talpid-types/src/net/wireguard.rs

https://github.com/mullvad/mullvadvpn-app/issues/4133
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4161)

debug/display for PresharedKey

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/NotificationBanner.kt

this PR is a quick fix for showing wrong inAppNotifications
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4227)

Fix showing wrong inAppNotification

---

ios/MullvadVPN/DeviceManagementViewController.swift

Change `Are you sure you want to log out of X?` to `Are you sure you want to log X out?`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4234)

Changed logout device `x` text.

---

ios/MullvadVPN/OutOfTimeContentView.swift
ios/MullvadVPN/OutOfTimeViewController.swift

Changed "Either buy credit on our website or redeem a voucher." to "make an in-app purchase via the **Add 30 days time** button below".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4236)

Change texts related to redeem a voucher

---

android/e2e/e2e-suppression.xml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4240)

Suppress CVE-2022-41881

---

mullvad-management-interface/src/types/conversions/relay_constraints.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4178)

Implement `From<RelaySettingsUpdate>` for gRPC equivalent

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/extension/ContextExtensions.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/NotificationBanner.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorNotificationMessage.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

In case of failed to establishing tunnel connection because of lack of VPN permission app will check for 'Always-on VPN' enabled for other apps and show relevant in app notification
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4120)

Detect always on vpn

---

gui/package-lock.json

This PR updates a bunch of dependencies with known vulnerabilities, although none that affects us. The update was performed by running `npm audit fix`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4255)

Update some dependencies with known vulnerabilities

---

gui/src/main/errors.ts

This PR removes an unused error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4269)

Remove unused NoDaemonError

---

.editorconfig
.github/workflows/android-app.yml
.github/workflows/android-audit.yml
.github/workflows/android-ktlint.yml
.github/workflows/android-xml-tidy.yml
.github/workflows/cargo-audit.yml
.github/workflows/clippy.yml
.github/workflows/daemon.yml
.github/workflows/frontend.yml
.github/workflows/ios.yml
.github/workflows/rust-supply-chain.yml
.github/workflows/rust-unused-dependencies.yml
.github/workflows/rustfmt.yml
.github/workflows/translations-converter.yml
.github/workflows/translations.yml
.github/workflows/unicode-check.yml
.github/workflows/verify-locked-down-signatures.yml
.github/workflows/yamllint.yml
.yamllint
gui/.prettierrc.yml

We have extremely mixed indentation in our YAML files. And even if I go and manually fix it all, we will introduce new inconsistencies in the future. So experimenting with having a linter tell us when we do something bad!
You can see the output here if you are interested in what it complains about (mostly invalid indentation): https://github.com/mullvad/mullvadvpn-app/actions/runs/3903309451/jobs/6667502188
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4274)

Add YAML linting to CI

---

Cargo.lock

This workflow is currently failing: https://github.com/mullvad/mullvadvpn-app/actions/runs/3937856854/jobs/6735852569. This PR fixes this by updating a yanked dependency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4291)

Update ed25519 dependency

---

android/BuildInstructions.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4286)

Document gradle lockfile

---

README.md
android/scripts/generate-pngs.sh

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4293)

Move png generate script to script dir

---

android/README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4294)

Improve android readme intro and quick start

---

android/README.md
android/translations-converter/README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4296)

Improve android documentation

---

.github/workflows/android-app.yml

The list was outdated, so not triggering on a bunch of file changes it should have been triggering on. This might on the other hand trigger a few times when it's not needed. But better than too seldom
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4273)

Replace an include list with an exclude list for Android CI

---

android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiTest.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4313)

Log mockapi web server port during tests

---

ios/MullvadVPN/MapViewController.swift

`MKMapView.convert(_, toRegionFrom:)` may return a region with center set to `(-180, -180)` when it cannot compute the geo region. Normally this occurs before the first layout pass, i.e when the map view is squashed to zero (0,0,0,0). Passing such region back to map view results in `NSInvalidArgumentException`. This PR adds additional guards to prevent that and additional update after the first layout pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4309)

Fix invalid exception crash in map view

---

.github/workflows/android-app.yml

This PR aims temporarily disable the flaky android tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4320)

Disable flaky android tests

---

.github/workflows/android-app.yml
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AccountRepository.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/DeviceRepository.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionDeviceDataSource.kt
android/scripts/run-instrumented-tests-repeat.sh
android/test/mockapi/build.gradle.kts
android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/Extensions.kt
android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LoginMockApiTest.kt
android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt
android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/util/DateTimeUtils.kt
android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/util/JsonUtils.kt

This PR fixes a few issues detected by running the new instrumented tests that rely on a mocked api. Some of the issues were in the app and some were in the mocked web server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4326)

Fix flaky test and app behaviors

---

gui/src/renderer/redux/account/actions.ts

This PR fixes the sorting of devices which was previously sorted incorrectly and is now sorted by the creation dates timestamp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4331)

Fix device sorting

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/CustomDns.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4340)

Simplify setting dns options

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4351)

Expose dns option updates for android UI components

---

CHANGELOG.md

I forgot to add the notification improvements to the changelog in https://github.com/mullvad/mullvadvpn-app/pull/4278.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4352)

Add notification dot and throttling changelog item

---

.github/workflows/android-app.yml
android/app/build.gradle.kts
android/app/lint-baseline.xml
android/lib/endpoint/build.gradle.kts
android/test/common/build.gradle.kts
android/test/e2e/build.gradle.kts
android/test/mockapi/build.gradle.kts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4357)

Enable agp linting in gh actions

---

ios/MullvadVPN/TunnelManager/SetAccountOperation.swift

This PR removes a `NoFailedDependenciesCondition` from operation that unsets the device state, which enables it to proceed even if a dependent operation that removes device from API server had failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4358)

Ignore errors on logout

---

android/app/build.gradle.kts
android/app/proguard-rules.pro
android/gradle.properties

Enabling r8 minify and shrinking to reduce apk size (`31M` -> `26M`) and to apply code optimization. This seem to also improve the performance when using Jetpack Compose.
More info about minify and shrinking is available here: https://developer.android.com/studio/build/shrink-code
TODO:
Upload of `mapping.txt` will be done in a separate PR as it relies on some other build script changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4364)

Enable r8 minify and shrinking

---

CHANGELOG.md
gui/locales/messages.pot
gui/src/renderer/components/KeyboardNavigation.tsx
gui/src/renderer/components/NavigationBar.tsx
gui/src/renderer/components/NotificationArea.tsx
gui/src/renderer/components/NotificationBanner.tsx
gui/src/renderer/components/Settings.tsx
gui/src/renderer/components/select-location/SelectLocation.tsx
gui/src/shared/localization-contexts.ts
gui/src/shared/notifications/error.ts
gui/src/shared/notifications/notification.ts

This PR adds info buttons and dialogs to some in app notifications to help users troubleshoot errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4375)

Add info dialog to some in app notifications

---

android/app/src/main/res/layout/connect.xml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4367)

Change city and country order in connect view

---

ci/buildserver-build-android.sh
ci/buildserver-build.sh
ci/buildserver-upload.sh

Main difference here is the indentation change. I'd love to get that merged asap to unblock other improvement work to these scripts. I did sneak in a few more cleanups here also. Review per commit to see them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4393)

Reformat buildscripts

---

BuildInstructions.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4399)

Mention x86 Windows target in build instructions

---

CHANGELOG.md
talpid-core/src/tunnel_state_machine/connecting_state.rs

As above.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4398)

Retry if PSK negotiation fails for any reason

---

ios/Configurations/Version.xcconfig

Since a build was released to internal Test Flight, we didn't merge the commit used for the build to main. So, let's do that now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4403)

Bump iOS version to 6

---

README.md

Updating the tables in the main README outlining what we support and where. Please review what I have added and if you know any more cool feature we have, suggest it!
I took inspiration from, but did not mimic 1:1: https://mullvad.net/en/why-mullvad-vpn/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4411)

Update supported platform and available features table in README

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadREST.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNScreenshots.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNTests.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/Operations.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/OperationsTests.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/PacketTunnel.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/RelaySelector.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/TunnelProviderMessaging.xcscheme
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/WireGuardGoBridge.xcscheme

This PR simply upgrades Xcode schemas to the latest + it seems like Xcode trimmed some duplicate entries perhaps a result of rogue rebase of the past.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4428)

Xcode: upgrade schemas

---

ios/PacketTunnel/PacketTunnelProvider.swift

Let's wrap `startTunnel` and `stopTunnel` into `dispatchQueue.async {}` to align with `handleAppMessage()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4427)

PacketTunnel: wrap start/stop in dispatch queue

---

android/docker/Dockerfile

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4437)

Add tidy to container image

---

android/docker/Dockerfile

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4436)

Bump container build tools

---

Cargo.lock
mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-paths/Cargo.toml
mullvad-problem-report/Cargo.toml
mullvad-relay-selector/Cargo.toml
mullvad-types/src/relay_constraints.rs
talpid-core/Cargo.toml
talpid-openvpn-plugin/Cargo.toml
talpid-openvpn/Cargo.toml
talpid-platform-metadata/Cargo.toml
talpid-routing/Cargo.toml
talpid-routing/src/windows/route_manager.rs
talpid-tunnel/Cargo.toml
talpid-windows-net/Cargo.toml
talpid-windows-net/src/net.rs
talpid-wireguard/Cargo.toml
talpid-wireguard/src/wireguard_nt.rs

Mainly `windows-service` and `windows-sys`, but some others as well to reduce duplication.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4440)

Update Rust dependencies

---

.github/workflows/android-app.yml
building/android-container-image.txt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4444)

Bump android container image

---

talpid-core/src/firewall/linux.rs

Older kernels do not support inet tables with chains whose base type is `route` or `nat`. For that reason, we currently have two separate sets of tables and chains for IPv4 and IPv6. As we're dropping support for older kernels, we can simplify these rules now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4445)

Replace mullvadmangle tables with a single table

---

android/app/build.gradle.kts
android/app/lint-baseline.xml
android/build.gradle.kts
android/config/lint.xml
android/lib/endpoint/build.gradle.kts
android/test/common/build.gradle.kts
android/test/e2e/build.gradle.kts
android/test/mockapi/build.gradle.kts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4452)

Ignore missing translation lint issues

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/PreferencesCellFactory.swift
ios/MullvadVPN/PreferencesDataSource.swift
ios/MullvadVPN/PreferencesViewController.swift
ios/MullvadVPN/SettingsAddDNSEntryCell.swift

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4446)

Migrate PreferencesDataSource from traditional to diffable

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/LocationCellFactory.swift
ios/MullvadVPN/LocationDataSource.swift
ios/MullvadVPN/SelectLocationViewController.swift

Since we dropped iOS 12, we can move on and use modern classes to handle and animate changes in collections.
This PR is about migration from traditional UITableViewDataSource to modern UITableViewDiffableDataSource and NSDiffableDataSourceSnapshot.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4462)

Migrate LocationDataSource from traditional to diffable

---

.github/workflows/android-app.yml
.github/workflows/android-kotlin-format-check.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4464)

Fix kotlin formatting trigger path

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/PreferencesFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/PrivacyDisclaimerFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SettingsFragment.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4465)

Move remaining fragments into fragment package

---

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingsScreenTest.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AdvancedSettingsUiState.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4468)

Add automated UI tests for advanced settings

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4491)

Fix advanced settings dialog padding and title size

---

ios/MullvadVPN/View controllers/SelectLocation/SelectLocationViewController.swift
ios/MullvadVPN/View controllers/Settings/SettingsCellFactory.swift

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4488)

Change a few title texts

---

.clang-format
.github/workflows/proto-format-check.yml
mullvad-management-interface/proto/management_interface.proto
talpid-openvpn-plugin/proto/openvpn_plugin.proto
talpid-tunnel-config-client/proto/tunnel_config.proto

The formatting is inconsistent at the moment. I suggest we use `clang-format` to enforce consistency.
I'm simply using defaults here, the line length limit is shorter than you might expect. We could edit `.clang-format` if that's a problem.
Closes DES-115.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4492)

Check formatting of .proto files

---

CHANGELOG.md
gui/src/main/user-interface.ts

The tray window currently exhibits some small bugs when interacting with it in mission control and in full-screen spaces.
Since the app is intended as a menu bar panel, the window should not be presented in mission control. At the moment it is, and trying to interact with it causes it to immediately hide:
https://user-images.githubusercontent.com/70155116/222907056-ac45a660-f7a0-4a95-96a7-4b12fcc0bfa7.mov
The correct behaviour would be for it to not appear in mission control at all, hence the changes in d87514660ea16adc5aa39ebd5068d58a96e1863f which does this.
While the window correctly has set `appWindow.setVisibleOnAllWorkspaces(true);`, it does not pass the second parameter, an options object with `visibleOnFullScreen: true`. This means the app window does not have …

Fix mission control and workspace-related bugs in window behaviour on macOS

---

CHANGELOG.md
gui/src/renderer/lib/filter-locations.ts

This PR changes the location search to search in translated location names. Fixes https://github.com/mullvad/mullvadvpn-app/issues/4485
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4496)

Search in translated location names

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt
android/app/src/main/res/values-da/strings.xml
android/app/src/main/res/values-de/strings.xml
android/app/src/main/res/values-es/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-it/strings.xml
android/app/src/main/res/values-ja/strings.xml
android/app/src/main/res/values-ko/strings.xml
android/app/src/main/res/values-my/strings.xml
android/app/src/main/res/values-nb/strings.xml
android/app/src/main/res/values-nl/strings.xml
android/app/src/main/res/values-pl/strings.xml
android/app/src/main/res/values-pt/strings.xml
android/app/src/main/res/values-ru/strings.xml
android/app/src/main/res/values-sv/strings.xml
android/app/src/main/res/values-th/strings.xml
android/app/src/main/res/values-tr/strings.xml
android/app/src/main/res/values-zh-rCN/strings.xml
android/app/src/main/res/values-zh-rTW/strings.xml
android/app/src/main/res/values/strings.xml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4498)

Revert custom dns hint

---

ios/.swiftformat
ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift
ios/MullvadVPN/StorePaymentManager/SendStoreReceiptOperation.swift

I don't have any alternatives right now but a lot of existing code does not seem to be in need of being reformatted for 120 chars. So in this PR I am simply bumping the upper limit for characters per line which also reformats a couple of files but nothing big.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4500)

Set characters per line to 120

---

android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4545)

Clarify MTU placeholder

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4546)

Prevent submitting empty DNS server

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4543)

Improve alpha values in advanced settings

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4548)

Fix Custom DNS auto disabling regression

---

CHANGELOG.md
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/VersionInfoNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/NotificationBanner.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateCauseExtension.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/ErrorStateExtension.kt
android/app/src/main/res/values-da/strings.xml
android/app/src/main/res/values-de/strings.xml
android/app/src/main/res/values-es/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-it/strings.xml
android/app/src/main/res/values-ja/strings.xml
android/app/src/main/res/values-ko/strings.xml
android/app/src/main/res/values-my/strings.xml
android/app/src/main/res/values-nb/strings.xml
android/app/src/main/res/values-nl/strings.xml
android/app/src/main/res/values-pl/strings.xml
android/app/src/main/res/values-pt/strings.xml
android/app/src/main/res/values-ru/strings.xml
android/app/src/main/res/values-sv/strings.xml
android/app/src/main/res/values-th/strings.xml
android/app/src/main/res/values-tr/strings.xml
android/app/src/main/res/values-zh-rCN/strings.xml
android/app/src/main/res/values-zh-rTW/strings.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

This PR aims to rephrase and clarify some of the notifications/error messages in the Android app. Most of these are already part of the desktop app.
Fixes: DROID-42, DROID-64
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4368)

Improve android error messages

---

gui/locales/messages.pot
gui/src/shared/notifications/error.ts

After a translator pointed out that this message is a bit unclear we decided to scrap the last part.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4525)

Update troubleshoot instructions for block failure

---

android/app/src/main/res/values-da/strings.xml
android/app/src/main/res/values-de/strings.xml
android/app/src/main/res/values-es/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-it/strings.xml
android/app/src/main/res/values-ja/strings.xml
android/app/src/main/res/values-ko/strings.xml
android/app/src/main/res/values-my/strings.xml
android/app/src/main/res/values-nb/strings.xml
android/app/src/main/res/values-nl/strings.xml
android/app/src/main/res/values-pl/strings.xml
android/app/src/main/res/values-pt/strings.xml
android/app/src/main/res/values-ru/strings.xml
android/app/src/main/res/values-sv/strings.xml
android/app/src/main/res/values-th/strings.xml
android/app/src/main/res/values-tr/strings.xml
android/app/src/main/res/values-zh-rCN/strings.xml
android/app/src/main/res/values-zh-rTW/strings.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4573)

Change feedback text area's placeholder

---

ios/MullvadREST/RESTURLSession.swift

This PR adds HTTP proxy configuration for URLSession.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4592)

Add http proxy configuration

---

ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift
ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift
ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift
ios/MullvadVPN/View controllers/DeviceList/DeviceRowView.swift

As per above, the device name in the header should be capitalised.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4571)

Device in name in header bar should be capitalized

---

mullvad-daemon/src/exception_logging/win.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/logging.rs
mullvad-daemon/src/main.rs
mullvad-daemon/src/migrations/mod.rs
mullvad-daemon/src/system_service.rs
talpid-core/src/dns/windows/dnsapi.rs
talpid-core/src/dns/windows/iphlpapi.rs
talpid-core/src/firewall/windows.rs
talpid-core/src/offline/windows.rs
talpid-core/src/split_tunnel/windows/driver.rs
talpid-core/src/split_tunnel/windows/mod.rs
talpid-core/src/split_tunnel/windows/path_monitor.rs
talpid-core/src/split_tunnel/windows/volume_monitor.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/tunnel_state_machine/disconnected_state.rs
talpid-openvpn/src/lib.rs
talpid-openvpn/src/wintun.rs
talpid-platform-metadata/src/windows.rs
talpid-routing/src/windows/default_route_monitor.rs
talpid-routing/src/windows/get_best_default_route.rs
talpid-routing/src/windows/mod.rs
talpid-routing/src/windows/route_manager.rs
talpid-windows-net/src/net.rs
talpid-wireguard/src/lib.rs
talpid-wireguard/src/logging.rs
talpid-wireguard/src/wireguard_go.rs
talpid-wireguard/src/wireguard_nt.rs

This commit does not contain everything that `cargo clippy --fix` changed on Windows. But the least controversial and simplest subset. The remaining fixes I felt could use some manual cleanup also. And I did not want the PR to grow too large. Better have as much as possible merged with less friction and fix the rest later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4598)

Apply `cargo clippy --fix` fixes for Windows

---

dist-assets/pkg-scripts/preinstall
dist-assets/uninstall_macos.sh
mullvad-daemon/src/lib.rs
mullvad-daemon/src/macos.rs
talpid-core/src/tunnel_state_machine/mod.rs

Since we're not going to need it anymore.
Fixes DES-170.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4591)

Remove mullvad-exclusion group on macOS

---

CHANGELOG.md
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt
android/app/src/main/res/values-da/strings.xml
android/app/src/main/res/values-de/strings.xml
android/app/src/main/res/values-es/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-it/strings.xml
android/app/src/main/res/values-ja/strings.xml
android/app/src/main/res/values-ko/strings.xml
android/app/src/main/res/values-my/strings.xml
android/app/src/main/res/values-nb/strings.xml
android/app/src/main/res/values-nl/strings.xml
android/app/src/main/res/values-pl/strings.xml
android/app/src/main/res/values-pt/strings.xml
android/app/src/main/res/values-ru/strings.xml
android/app/src/main/res/values-sv/strings.xml
android/app/src/main/res/values-th/strings.xml
android/app/src/main/res/values-tr/strings.xml
android/app/src/main/res/values-zh-rCN/strings.xml
android/app/src/main/res/values-zh-rTW/strings.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

- Change programs to apps
- Add custom dns warning
- Add html-formatted text support to info dialog
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4604)

Update content blockers informational dialog

---

.github/workflows/clippy.yml
mullvad-cli/src/cmds/split_tunnel/windows.rs
mullvad-cli/src/cmds/tunnel.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/migrations/mod.rs
mullvad-daemon/src/migrations/v6.rs
mullvad-daemon/src/settings.rs
mullvad-daemon/src/system_service.rs
mullvad-version/build.rs
talpid-core/build.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/firewall/windows.rs
talpid-core/src/offline/windows.rs
talpid-core/src/split_tunnel/windows/driver.rs
talpid-core/src/split_tunnel/windows/path_monitor.rs
talpid-tunnel-config-client/src/kyber.rs

That and a few warnings that remained when I ran it using the msvc toolchain. I've also added Windows to the workflow for Clippy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4611)

Fix errors returned by Clippy on Windows

---

CHANGELOG.md
android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangelogDialogTest.kt
android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreenTest.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scrollbar.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Theme.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/DeviceListFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/DeviceRevokedFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/LoadingFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/PrivacyDisclaimerFragment.kt

- Change color, size and alpha of scrollbar
- Add rounding to scrollbar
- Add onSurfaceVariant color to theme
- Update theme to material v3
- Apply AppTheme to all screens
- Remove CollapsingToolbarTheme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4615)

Update compose scrollbar appearance

---

.github/workflows/clippy.yml
talpid-core/src/dns/macos.rs
talpid-core/src/firewall/macos.rs
talpid-core/src/resolver.rs
talpid-core/src/tunnel_state_machine/disconnected_state.rs
talpid-routing/src/macos.rs
talpid-types/src/tunnel.rs
talpid-wireguard/src/lib.rs

Basically a follow up to #4611. Fixes all complaints Clippy had on our Rust code for the macOS target. Also adds macOS into the automatic Clippy check in Github actions to prevent further regressions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4642)

Fix Clippy warnings on macOS and run in CI

---

android/config/dependency-check-suppression.xml
android/test/test-suppression.xml

Push suppression review date to: 2023-06-01
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4647)

Push suppression review date

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt

This PR aims to fix the current resume regression which causes the connect/main view to always open when the app is resumed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4648)

Fix app always resuming to the connect view

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4649)

Avoid spamming toast messages

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/BuildTypes.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/WelcomeFragment.kt

If building using the release build variant we will no longer show the "buy credit" button.
This affects AccountFragment, OutOfTimeFragment and WelcomeFragment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4650)

Remove buy credit buttons on build type release

---

ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift

Network status should be propagated to tunnel status even when there is no tunnel. Without this are occassions where the app will not tell the user that the network is down.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4658)

Propagate network status when there is no tunnel

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountManagementButton.kt
android/app/src/main/res/layout/account.xml
android/app/src/main/res/layout/account_buttons.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4662)

Restore payment button in account fragment for release builds and change the text to "manage accounts"

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4671)

Fix missing buy time text in out-of-time fragment

---

scripts/find-stale-remote-branches.sh

Can be used to clean out old cruft no longer needed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4674)

Add helper script for finding potentially stale remote branches

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/DnsTextField.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/MtuTextField.kt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4682)

Fix DNS input keyboard type

---

CHANGELOG.md
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/Typeface.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/DateExtensions.kt
android/app/src/main/res/values/colors.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

Also made some styling and theming improvements to Device List Screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4687)

Add creation date below device name in the device list screen

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt

Links removed in:
- Account page
- Account expiry in-app notification
- Account expiry system notification
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4716)

Hide account page links in release builds

---

CHANGELOG.md
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/WelcomeFragment.kt

This change is done to comply with Google Play payment policies. It does not affect F-Droid builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4721)

Remove purchasing information from release builds

---

ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift

when user buys more credit, the account data will be changed with more expiry time. it means it's look like to these states :
`logged out` -> `logged in` -> `logged in` with new data. in this case we shouldn't dismiss the banner view until user taps close button.
solution :
- When user buys more credit, the previous and current device state are `logged in` with different account data.we check if user dismissed the registered device in app banner then we show device info with new data otherwise we stay until user dismisses the banner
- Hide device info when user goes from `logged out` to `logged in` till user dismisses the in app banner
- Hide device info when user is in `revoked` or `logged out` state
- - - …

Device info should only be displayed once user dismissed "device created" notification

---

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/InformationComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/MtuComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/SpannedExtensions.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/VpnSettingsFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4727)

Update text and indentation for DNS content blockers

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/InformationComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/SpacedColumn.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Switch.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt
android/app/src/main/res/values-da/strings.xml
android/app/src/main/res/values-de/strings.xml
android/app/src/main/res/values-es/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-it/strings.xml
android/app/src/main/res/values-ja/strings.xml
android/app/src/main/res/values-ko/strings.xml
android/app/src/main/res/values-my/strings.xml
android/app/src/main/res/values-nb/strings.xml
android/app/src/main/res/values-nl/strings.xml
android/app/src/main/res/values-pl/strings.xml
android/app/src/main/res/values-pt/strings.xml
android/app/src/main/res/values-ru/strings.xml
android/app/src/main/res/values-sv/strings.xml
android/app/src/main/res/values-th/strings.xml
android/app/src/main/res/values-tr/strings.xml
android/app/src/main/res/values-zh-rCN/strings.xml
android/app/src/main/res/values-zh-rTW/strings.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

- Improve selectable cell to add support for checkmark
- Add preview to selectable cell
- Changed title to WireGuard obfuscation
- Replaced some hardcoded values in BaseCell with values from theme and dimensions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4750)

Improve wireguard obfuscation settings

---

ci/verify-locked-down-signatures.sh

Verify that we do not remove any file we deem important. If any such file is removed, they should also be removed from the list this CI job uses, and as such we raise a flag.
Update the CI job to also check that all files in the list of important files still exists in the working directory/at the HEAD where it's being executed from.
Hopefully this PR will solve DES-216.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4746)

Verify that important files have not been accidentally removed

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4769)

Update android feature list

---

ios/MullvadREST/RESTAPIProxy.swift
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/TunnelManager/RedeemVoucherOperation.swift

Implement redeeming the voucher code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4747)

Implement redeem voucher service

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/SpannedExtensions.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt
android/app/src/main/res/values-da/strings.xml
android/app/src/main/res/values-de/strings.xml
android/app/src/main/res/values-es/strings.xml
android/app/src/main/res/values-fi/strings.xml
android/app/src/main/res/values-fr/strings.xml
android/app/src/main/res/values-it/strings.xml
android/app/src/main/res/values-ja/strings.xml
android/app/src/main/res/values-ko/strings.xml
android/app/src/main/res/values-my/strings.xml
android/app/src/main/res/values-nb/strings.xml
android/app/src/main/res/values-nl/strings.xml
android/app/src/main/res/values-pl/strings.xml
android/app/src/main/res/values-pt/strings.xml
android/app/src/main/res/values-ru/strings.xml
android/app/src/main/res/values-sv/strings.xml
android/app/src/main/res/values-th/strings.xml
android/app/src/main/res/values-tr/strings.xml
android/app/src/main/res/values-zh-rCN/strings.xml
android/app/src/main/res/values-zh-rTW/strings.xml
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

- Replace HtmlText for custom dns subtitle with annotated string
- Use correct text style for custom dns subtitle
- Use extra bold instead of bold for emphasized words
- Fix magic numbers in expandable compose cell
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4774)

Fix vpn settings subtitles

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelState.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4778)

Fix auto connect and local network sharing showing default values

---

android/BuildInstructions.md

Added macOS variants whenever needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4740)

Improve the android build instructions for mac os

---

CHANGELOG.md
mullvad-daemon/src/lib.rs

This is obviously a problem because some endpoints might no longer be valid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4785)

Resume background API requests when logging in

---

gui/locales/messages.pot
gui/src/renderer/components/TooManyDevices.tsx

This PR adds the device creation date to the device list in the too many devices view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4788)

Add creation date to device list

---

gui/locales/messages.pot
gui/src/renderer/components/Account.tsx
gui/src/renderer/components/AccountStyles.tsx
gui/src/renderer/components/DeviceInfoButton.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx
gui/src/renderer/components/InfoButton.tsx
gui/src/renderer/components/NotificationArea.tsx
gui/src/renderer/components/NotificationBanner.tsx
gui/src/renderer/redux/account/actions.ts
gui/src/renderer/redux/account/reducers.ts
gui/src/shared/notifications/new-device.ts
gui/src/shared/notifications/notification.ts

This PR makes a few improvements for the device concept to make it clearer to users how it works. The changes include:
- Add info button to account view device row
- Add dive name to new account view
- Add new device in-app notification
Fixes DES-143, DES-142, DES-138
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4790)

Device concept improvements

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelState.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4793)

Order split tunneling apps by name

---

ios/MullvadREST/RESTError.swift
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/Classes/InputTextFormatter.swift
ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift
ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift
ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift
ios/MullvadVPN/Presentation controllers/SecondaryContextPresentationController.swift
ios/MullvadVPN/TunnelManager/TunnelManager.swift
ios/MullvadVPN/UI appearance/UIMetrics.swift
ios/MullvadVPN/View controllers/Account/AccountContentView.swift
ios/MullvadVPN/View controllers/Account/AccountInteractor.swift
ios/MullvadVPN/View controllers/Account/AccountViewController.swift
ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift
ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherCoordinator.swift
ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift
ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift
ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift
ios/MullvadVPN/View controllers/RedeemVoucher/VoucherTextField.swift

in the account flow, user is able to add more credit through voucher code.
- The voucher code can be a combination of ascii letter and number with 16 length that is grouped by `-` in 4 character
- The `Redeem` button shouldn't be enabled until the above condition is met.
- when user enters a valid voucher code and presses `Redeem` button.the service is revoked and if it's successful we show the `successful view` with the days are been added to the account.once user presses `Got it!` the view will be disappeared and the app stays on account page and each part of the app that shows remained time should be updated with the new expiry date.
- when the response of service wan't successful.we stay at the redeem voucher code  view and show the error message under `voucher text field`.when it …

Implement redeeming voucher UI part ios 193

---

ios/CHANGELOG.md

Add redeeming voucher code to `CHANGELOG.md` under the `[Unreleased]` header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4810)

Update change log
