dist-assets/linux/after-remove.sh
dist-assets/linux/before-install.sh
dist-assets/linux/before-remove.sh

1. If the root user has something other than our CLI as the command `mullvad` these scripts would probably do strange things. So I updated it to use the full path. That's usually preferred to not rely on the environment happening to be correctly set up. For example, on my machine `/usr/local/bin` comes before `/usr/bin` in my root's `PATH`. So if the user created some random script `/usr/local/bin/mullvad` it would be executed instead.
2. The `-f` flag to `rm` suppresses all output and makes it always exit with exit code zero. As such, appending `|| true` or `|| echo "oh no"` does not do anything. Either we remove those or we remove `-f`. Here I kept the `|| echo {log the error}` and replaced `-f` with `--interactive=never` to ensure it would not get stuck on a prompt.
While testing this …

Fix linux install scripts

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/SplitTunneling.kt

Previously, split tunneling would stop working after the user restarts the app. This happened because the split tunneling configuration was properly loaded on start, but it didn't notify the listeners until another event happened. This PR fixes that by notifying the listener as soon as the list is first loaded, and when the listener is first configured.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2075)

Fix split tunneling after restarting the app on Android

---

gui/src/renderer/components/NavigationBarStyles.tsx

This PR fixes an issue where the settings close button wasn't clickable when there was no title.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2076)

Fix settings close button not clickable

---

talpid-core/src/tunnel/wireguard/mod.rs

We want to make it simple to see from the logs which WireGuard implementation is actually used. So I add logging even in the case where the kernel one is used instead of staying silent. This makes it more explicit.
Also replaced some ` - ` delimiters and made them `: ` to be more consistent as well as used our `display_chain_with_msg` to print the entire chain and not just the top error.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2084)

Log better wg impl selection

---

gui/src/renderer/components/SvgMap.tsx

This PR optimizes the rendering of the map, and hopefully reduces lag, by:
1. Converting `SvgMap` to a functional component and hopefully reducing rerenders in children by memoizing objects, arrays and functions. This is done using `useMemo`.
2. Not changing width of country/state lines which makes the map transition appear more smooth.
3. Changing the transition function from `ease-in-out` to `ease-out`. The transition appeared choppy when the app connected while panning, since it switched from moving fast to a new transition starting from a standstill.
This PR also adds a workaround for the initial transition when mounting the map, to make it work the same as with `react-simple-maps@0.12.1`.
Git checklist:
--- …

Improve map transition performance

---

build-apk.sh
build.sh

`git describe` did not work very well any more when we might have two tags on the same commit. It could return the wrong one and the build scripts failed to realize it was a release build.
My change involves using `$PRODUCT_VERSION` (the version we think we are building) and checking what commit hash the corresponding release tag is on. We then get the commit hash for `HEAD`. If they are equal, it means this should be a release build for that `$PRODUCT_VERSION`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2085)

Fix build.sh for android tags

---

prepare_release.sh

Currently a single tag is used to represent releases for both the Android and the desktop app. Unfortunately, this makes it confusing to understand which platform the release is for when only one of them has a release. Therefore there was an agreement to improve the situation by adding an Android specific tag for versions that have a release for that platform, and use the previous tag format for desktop releases.
Note that this doesn't change that the versioning is still the same, i.e., both platforms follow the same version evolution, but each platform can have a release for that version or not.
This PR updates the `./prepare_release.sh` script to support the new tag scheme. Now either on or both of the flags `--android` and `--desktop` _must_ be specified for the script to tag the …

Update `prepare_release.sh` to support Android specific tags

---

build-apk.sh
build.sh

Follow up on #2085. Currently it crashes when trying to build and the version metadata files has a version that there is no tag for. this should not really ever happen in the real world. But during this transition period that will be true. And also, better to cover an edge case than crash.
`git rev-parse HEAD` should never fail. `HEAD` does always exist. But some arbitrary tag might not exist.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2088)

Allow build[-apk].sh to work even when release tag does not exist

---

CHANGELOG.md
gui/src/main/index.ts
gui/src/renderer/components/TunnelControl.tsx
gui/src/shared/localization-contexts.ts

This PR adds actions to the context menu displayed when clicking on the tray icon in some desktop environments. Since we have to have a context menu we want to make the most of it. To keep the old behavior in desktop environments that support listening on tray icon click, a list of DEs supporting it is used to decide the behavior.
In addition to adding actions to the context menu, this PR changes the behavior when clicking the tray icon (or "Open Mullvad VPN" in the context menu) to always showing and focusing the app. This was changed since the toggle behavior was a bit confusing when the app was open but hidden behind some other window. Now it will always be placed on top of other windows. Hiding the app will still be possible by pressing the "x" window icon.
Git checklist:
---
This …

Add actions to Linux tray context menu

---

CHANGELOG.md
android/src/main/AndroidManifest.xml
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

Previously, it was possible to make the Quit button not work by spawning more than one task with the `MainActivity`. One way to do this was by:
1. Logging out
2. Quitting the app
3. Trying to connect using the Quick-Settings tile, which would then open the login screen
4. Returning to the home screen
5. Opening the app from the launcher
6. Trying to Quit, which would then close the app but appear to reopen it right away.
This PR fixes that by marking the `MainActivity` as a single task, so that when opening the UI any previous instances are closed. The PR also takes a further precaution by requesting to clean the task stack when opening the UI, so that it will go to the intended screen without creating a weird navigation path for the back button.
Git checklist:
--- …

Use single task for app to prevent quitting from not closing the app

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

Previously, the quick settings tile would have an inconsistent behavior when there was no account set. If the service was already running, pressing the tile would make the daemon enter the blocked state. If it wasn't running, it would be started but the UI would be opened so that the user could log in first.
This PR makes the behavior consistent by always opening the UI if the user is logged out.
Unfortunately, on my test device there is still a small difference. For some unknown reason, Android will take a few seconds (3-5) to start the UI if the service is already running. I couldn't figure out what could cause this. The closest I came was with removing the `singleTask` configuration on the activity, which reduced the lag to less than one second. However, that would reintroduce the …

Fix inconsistent quick settings tile behavior

---

gui/package-lock.json
gui/package.json
gui/src/renderer/components/CustomScrollbars.tsx
gui/src/renderer/components/WireguardKeysStyles.tsx

This PR adds a `ResizeObserver` to listen to height changes of the content in `CustomScrollbars`. Previously the scrollbar length and position didn't update when the content changed, e.g. when expanding/collapsing countries or cities in the location picker, or when the split tunneling view finished loading the installed apps. With this PR the scrollbar is updated on every height change.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2095)

Make scrollbar update when content size changes

---

CHANGELOG.md
talpid-core/src/firewall/linux.rs

Ideally the rule should apply only to the interface that currently provides internet access. This requires monitoring and updating the `masq` rule based on the best default route, so the solution would be somewhat involved. Making an exception for `lo` is sufficient in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2099)

Fix masquerade rule interfering with systemd-resolved

---

gui/src/main/index.ts

This PR adds the left click action to the tray icon that was missing in https://github.com/mullvad/mullvadvpn-app/pull/2086.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2100)

Add Linux tray icon left click action

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt

Previously, the app didn't mark if the VPN connection was metered or not (i.e., charged by the amount of data transmitted). On recent Android versions, the default value is now set to `true`, which means some apps will behave differently while connected to the VPN server, in an attempt to reduce data charges.
This PR changes that so that the connection is marked as not metered. Since Mullvad does not charge per amount of data, it makes sense to mark the VPN connection as not metered. This has the effect of letting the underlying network decide if the connection is metered. If any of the transport layers is marked as metered, then the whole connection is marked as metered, otherwise it remains as not metered, and the behavior is as expected for the user.
Git checklist:
---
This change …

Mark VPN connection as not metered

---

CHANGELOG.md
gui/src/renderer/components/AppButton.tsx
gui/src/renderer/components/Connect.tsx
gui/src/renderer/components/ErrorBoundary.tsx
gui/src/renderer/components/HeaderBar.tsx
gui/src/renderer/components/ImageView.tsx
gui/src/renderer/components/Launch.tsx
gui/src/renderer/components/NavigationBar.tsx
gui/src/renderer/components/NavigationBarStyles.tsx
gui/src/renderer/components/NotificationArea.tsx
gui/src/renderer/components/NotificationBanner.tsx
gui/src/renderer/components/SecuredLabel.tsx
gui/src/renderer/components/SettingsHeader.tsx
gui/src/renderer/components/Switch.tsx
gui/src/renderer/components/TunnelControl.tsx

This is the first PR with improvements to aria-labeling/semantically correct elements/other accessibility fixes.
Changes:
* Changing some element types
* Adding some `aria-label`s
* Placing the notification area above the connection info in the code
* Making `NotificationArea` an `assertive` live region
* Making `SecuredLabel` a `polite` live region
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2102)

Improve accessibility

---

gui/src/main/index.ts

This PR adds a workaround for the delay when pressing a context menu action, as suggested in this gRPC-js issue https://github.com/grpc/grpc-node/issues/882.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2112)

Workaround for Linux tray context menu action delay

---

android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt

A recent PR introduced a call to the `setMetered` API to mark the VPN connection as not metered. Unfortunately, the `setMetered` API call is rather recent, and won't work on Android 9 and below.  This PR makes sure the function is only called on the Android versions that have the function.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2116)

Only use `setMetered` on newer Android versions

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AriaInputGroup.tsx
gui/src/renderer/components/Cell.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/LinuxSplitTunnelingSettings.tsx
gui/src/renderer/components/Modal.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/components/Support.tsx
gui/src/renderer/components/Switch.tsx

This PR:
* Makes input labels use the `<label>` tag
* Adds attributes to labels, inputs and descriptions (`id`, `for`, `aria-labelledby`, `aria-describedby`)
* Adds `aria-disabled` attribute to `Switch` to communicate whether or not it is disabled
* Makes it possible to close modal by pressing escape
* Prevents screenreaders from navigating to content behind modal
* (Random improvement): Replaces the use of `document.getElementById` in `ModalAlert` with a ref since there's now a context.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2117)

Improve accessibility for inputs and modals

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AriaGroup.tsx
gui/src/renderer/components/Cell.tsx
gui/src/renderer/components/ImageView.tsx
gui/src/renderer/components/Login.tsx
gui/src/renderer/components/LoginStyles.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/components/Selector.tsx
gui/src/shared/localization-contexts.ts

This PR:
* Makes `Selector` act as a listbox to screenreaders
* Adds the `aria-invalid` attribute to mssfix and mtu fields when an invalid value is entered
* Makes a lot of changes to `Login.tsx` to improve accessibility
* Adds the `accessibility` localization context.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2125)

Improve accessability in Selector component and Login view

---

talpid-core/src/routing/linux.rs

Currently the Linux routing module executes `ip rule ...` to add and remove the rule that directs marked packets to the `mullvad_exclusions` table. This refactoring accomplishes this using netlink messages, consistent with the rest of the module.
Another improvement can be made by not setting up the table using `/etc/iproute2/rt_tables`, which would remove the dependency on `iproute2`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2126)

Use netlink to add and remove the fwmark rule

---

talpid-core/src/firewall/linux.rs

The `masquerade` rule is slightly off. It has an "accept" verdict, but this makes no sense. If you attempt to add the same rule using `nft`, you will see that it rejects this, because `masquerade` is supposed to be used in place of a verdict. It already functioned normally, so this fix is technically correct but it does not seem to matter in practice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2128)

Remove verdict from masquerade rule

---

gui/src/renderer/components/SelectLanguage.tsx

This PR fixes an error which caused the language selection view to show the error view. The issue was that `SelectLanguage` used `AriaGroup` components without the wrapping group. This PR adds the group component around the selector.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2132)

Wrap language selector in AriaInputGroup

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt

When a reconnect is requested in the Kotlin side, the `ConnectionProxy` will attempt to "anticipate" the reconnecting state. That means that it will notify any UI state listeners to update to the reconnecting state _before_ the actual reconnecting state is received from the Rust side. This is done to improve the responsiveness of the UI so that the user feels a reaction to the command as soon as possible.
Previously, the reconnecting state would be incorrectly anticipated in a few cases. Most notably, when the tunnel was disconnected. This became apparent with the introduction of the split tunneling feature, because every change to the split tunneling configuration requested a reconnect, and the Rust side would correctly ignore the request if the target state was unsecured. This meant …

Fix conditions to anticipate reconnecting state

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt

Before adding the functionality to remove entries from the account history, I thought it was best to centralize where the account history was managed. This PR then moves the account history fetching and notification into the `AccountCache` class, which also knows if the account changed so it can re-fetch the history at the appropriate time.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2135)

Use the `AccountCache` to keep track of the account history

---

talpid-core/src/routing/linux.rs
talpid-core/src/routing/mod.rs

The daemon currently parses `rt_tables` to find a free slot for `mullvad_exclusions`. Aside from not being pretty, this can cause issues when `/etc/iproute2/rt_tables` does not exist or when `iproute2` is not installed. These changes instead look for an empty table using netlink and use that ID.
The route manager now also understands table IDs greater than 255.
https://github.com/mullvad/mullvadvpn-app/pull/2126 removes the use of `ip` subprocesses. With these two PRs, `iproute2` should no longer be required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2127)

Use netlink instead of iproute2/rt_tables to set up mullvad_exclusions

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
android/src/main/res/layout/settings.xml
android/src/main/res/values-da/strings.xml
android/src/main/res/values-de/strings.xml
android/src/main/res/values-es/strings.xml
android/src/main/res/values-fi/strings.xml
android/src/main/res/values-fr/strings.xml
android/src/main/res/values-it/strings.xml
android/src/main/res/values-ja/strings.xml
android/src/main/res/values-ko/strings.xml
android/src/main/res/values-nb/strings.xml
android/src/main/res/values-nl/strings.xml
android/src/main/res/values-pl/strings.xml
android/src/main/res/values-pt/strings.xml
android/src/main/res/values-ru/strings.xml
android/src/main/res/values-sv/strings.xml
android/src/main/res/values-th/strings.xml
android/src/main/res/values-tr/strings.xml
android/src/main/res/values-zh-rCN/strings.xml
android/src/main/res/values-zh-rTW/strings.xml
android/src/main/res/values/strings.xml

Most Android apps don't have a button to quit the app. It is usually handled by the system. Some apps that have long running tasks in the background have buttons to stop them, but for a VPN this is usually done by just disconnecting the tunnel. This PR removes the Quit button, and makes it so that Android will stop the background service whenever it needs to if the tunnel is disconnected.
This is a first step towards improving the user experience, and will be followed by making the background service run more smartly and more similar to other Android apps.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2123)

Remove Quit button from the Settings page

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt

Previously, the app used the `onBind` and `onUnbind` callbacks to determine if the UI was visible, since the UI connected to the service when it started and disconnected when it stopped. However, Android sometimes disconnects the UI from service and reconnects it when needed transparently, which makes the logic incorrect sometimes. An example is when the UI is open, the notification drawer is pulled down and the app's notification is used to connect and then disconnect the tunnel. Afterwards, the service thinks the UI is no longer visible and this can be seen because the notification can be dismissed away while the UI is visible.
This PR adds a `isUiVisible` flag to the `MullvadVpnService` which is set when the UI becomes visible and unset when it disappears. The logic to determine if the …

Improve how background service knows if the UI is visible

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SplitTunnelingFragment.kt

A crash report indicated that the `splitTunneling` property was used before it was initialized in the `SplitTunnelingFragment`. The stack trace showed that this happened inside the `onAttach` method. The property should be initialized in the call to `super.onAttach`, _as long as the service connection is already available_. If it's not available, it doesn't get initialized, and that shouldn't be a problem since the super `ServiceDependentFragment` class should handle it gracefully by showing a temporary screen and then returning to the launch screen. However, the `SplitTunnelingFragment` tries to use the property out of one of the "safe" methods, so the super-class handling of the situation doesn't get a chance to execute because the code crashes before that happens.
This PR fixes that by …

Fix crash if service connection is lost when opening the Split Tunneling settings screen

---

CHANGELOG.md
talpid-core/src/routing/linux.rs
talpid-core/src/routing/mod.rs
talpid-core/src/routing/unix.rs
talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/openvpn.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-openvpn-plugin/src/lib.rs

These changes cause the `mullvad_exclusions` table to mirror `main`, except that routes (unless manually added) for tunnel devices are ignored. Currently, LAN traffic will generally operate as you'd expect, assuming that the other host is on the same network. But monitoring the traffic reveals that the destination MAC address belongs to the gateway rather than the host. This is because the second table only tracks the default route belonging to the physical interface. Including all routes fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2106)

Improve routing for mullvad-exclude on Linux

---

android/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt
android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt

The previous `ConnectivityListener` listened for connection change intents to determine the current connectivity. This is working well, but the API has been deprecated for a while, which led to multiple warnings being emitted when compiling. This PR rewrites the `ConnectivityListener` to use a newer `NetworkCallback` API which should be more efficient.
The new callback is called whenever a network that satisfies the specified criteria (in the `NetworkRequest` instance) becomes available or is lost. The class then keeps a set of available networks and determines if connectivity is available or not based on if the set is empty or not.
Git checklist:
--- …

Refactor `ConnectivityListener` to remove deprecation warnings

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ListItemDividerDecoration.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SplitTunnelingFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountHistoryAdapter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountHistoryHolder.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt
android/src/main/res/drawable/account_history_list_divider.xml
android/src/main/res/layout/account_history_entry.xml
android/src/main/res/layout/account_login.xml

In order to add a remove button to each account history entry, more control over the entry views is needed. Therefore, this PR changes the account history to be stored in a `RecyclerView` instead of a `ListView`. This allows a custom adapter and view holder to be developed that can then have a custom button included in a future PR.
The change also simplifies the divider between the entries (and between the input and the list). The `ListItemDividerDecoration` was tweaked to allow the divider spacing to be in different places, and the other recycler views that use it were updated.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2137)

Use a `RecyclerView` for the account history

---

mullvad-cli/src/cmds/account.rs
mullvad-cli/src/cmds/tunnel.rs

Timestamps were being shown in UTC without any time zone info. Use local time instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2143)

Improve timestamp formatting in the CLI

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt

There was a single crash report of a `NullPointerException` inside the `MullvadTileService`. This is pretty easy to avoid, and we simply add a `null` check in `qsTile?.apply`. However, the reason that `qsTile` was (or rather, `getQsTile()` returned) `null` is unknown.
The documentation only says that the returned tile is only valid between the `onStartListening()` and the `onStopListening()` callbacks. I changed the `super` call in `onStopListening()` to be in the end of the callback, just to make sure we use a more cautious interpretation of the documentation by not calling `getQsTile()` after calling `super.onStopListening()`. Still, looking at the code in AOSP it seems that changing the order shouldn't change anything.
Looking at the `TileService` code in AOSP, I couldn't find a reason …

Fix `NullPointerException` inside `MullvadTileService`

---

android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayCity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayCountry.kt

Previously the Select Location screen would not show child items for locations that had only one relay. However, that might lead to some UX issues, where the user can't see what city is available in a country, and can't select a single server if more are added later without having to change the constraint again.
This PR changes that so that all locations with at least one relay can be fully expanded.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2142)

Allow expanding locations with one relay on Android

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountHistoryAdapter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountHistoryHolder.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountInput.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/SegmentedInputFormatter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/SegmentedTextFormatter.kt
android/src/main/res/layout/account_input.xml

This PR changes the Login screen so that the account number is shown with spaces separating every four digits. This is a minor UI tweak to improve readability and to make it more similar to the desktop app.
There was already a `SegmentedInputFormatter` helper class used in the Redeem Voucher dialog, and it was used for the account input widget. For the account history entries, a new and simpler `SegmentedTextFormatter` helper class was created.
Unfortunately, simply applying the `SegmentedInputFormatter` to the `AccountInput` widget didn't work initially. This was because setting the `digits` `TextView` attribute in the XML caused it to prohibit the space character from appearing in the widget. Adding a space character to that attribute value led the on-screen keyboard to change to not …

Format account number with spaces in the Login screen

---

gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/WireguardKeys.tsx
gui/src/renderer/containers/WireguardKeysPage.tsx
gui/src/renderer/redux/userinterface/actions.ts
gui/src/renderer/redux/userinterface/reducers.ts
gui/src/shared/ipc-event-channel.ts

This PR makes sure that the "Key generated" value is up to date by:
* Updating the value when the app is opened if the `WireguardKeys` view is the current view
* Every minute as long as the view is visible
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2144)

Keep key information up to date

---

CHANGELOG.md
mullvad-daemon/src/lib.rs
mullvad-daemon/src/wireguard.rs

When a new account is set, and a key is generated, the daemon previously didn't start the key rotation timer. The effect is that if a new user never reboots, the key would not be rotated indefinitely. I've changed the daemon so that whenever a new key event is received and the current account has no key, the key rotation would be started. The reason for not starting the key rotation whenever a new key is created is because the key rotation will almost always be started already.
The last commit here is a small refactoring to simplify the code for key rotation/generation. This is purely optional and I can drop it, since we're so close to a release.
--- …

Start key rotation after initial key is created.

---

CHANGELOG.md
dist-assets/linux/before-remove.sh
dist-assets/uninstall_macos.sh

When uninstalling, the Linux and MacOS uninstallers did not reset the firewall. This would leave the host without internet access if the user had enabled the _always require VPN_ setting. I've changed the uninstaller scripts for both Linux and MacOS to execute `mullvad-setup reset-firewall` after the daemon has been stopped. I've tested this on MacOS and Debian.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2152)

Unix reset firewall on uninstall

---

gui/src/renderer/components/Connect.tsx
gui/src/renderer/components/Focus.tsx
gui/src/renderer/components/HeaderBar.tsx
gui/src/renderer/components/ImageView.tsx
gui/src/renderer/components/Modal.tsx
gui/src/renderer/components/NotificationArea.tsx
gui/src/renderer/components/SecuredLabel.tsx
gui/src/renderer/components/TransitionContainer.tsx
gui/src/renderer/routes.tsx

This PR:
* Resets focus on navigation to either the first header or some fallback element
* Announces navigation with an invisible `div` that has the `aria-live` argument set
* Restores focus when closing a modal
* Makes notification area polite since that seems more correct
* Change `role` to `status` for `NotificationArea` and `SecuredLabel` since `alert` should be used for errors.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2148)

Reset focus on navigation and other accessibility improvements

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/LocationInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/ExponentialBackoff.kt

This PR creates an `ExponentialBackoff` helper class so that the logic that was originally in the `AccountCache` can be reused in the future when retrying to connect to Google's billing server. The class is implemented as an `Iterator`, meaning you can just use the `next()` method to get ever increasing delays, until the specified maximum delay. The scale factor was added because the exponential part is usually calculated in seconds, but must be scaled to milliseconds before being used.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2154)

Create an `ExponentialBackoff` helper class

---

dist-assets/windows/installer.nsh
windows/nsis-plugins/src/cleanup/cleaningops.cpp

The installer (due to `electron-builder`) dumps a copy of itself in `%LOCALAPPDATA%\mullvad-vpn-updater`. This file is not being removed by the uninstaller, and is only used for automatic updates. So it should be deleted during the installation. Ideally it would be fixed by patching upstream so that the file isn't copied in the first place, but this patch will do until the issue is fixed in `electron-builder`.
Related issue: https://github.com/electron-userland/electron-builder/issues/3831
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2155)

Clean up installer.exe copy in AppData

---

talpid-core/src/tunnel_state_machine/connected_state.rs

A tunnel close event is received if the tunnel monitor thread is shut down unexpectedly, for example if the virtual network adapter is missing on Windows. In case this happens, `ConnectedState::reset_dns` should be called to restore system DNS settings to their initial state, as is done elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2158)

Reset DNS config if the tunnel monitor thread goes down

---

android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/CopyableInformationView.kt

This PR updates the Kotlin Gradle plugin (which consequently updates the Kotlin compiler version) and some Kotlin libraries. The only problem with the update was that some Java setter methods don't seem to map to automatic property names anymore, but a simple change fixed it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2160)

Update Kotlin plugin, compiler and library versions

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountInput.kt

Recently, the Login screen was updated to show the account number with spaces separating every four digits. However, this formatted string was still used directly as the account token when attempting to login. This meant that login would fail because the spaces were still in the account token. This PR fixes that by removing any non-digit characters from the input before using it as the account token.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2163)

Remove spaces from account token before logging in

---

CHANGELOG.md
android/src/main/AndroidManifest.xml
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt

There have been a few reports of the app starting by itself (and connecting to the tunnel) when it's not supposed to (for example, after disconnecting while having the auto-connect setting enabled). The cause is still unknown, but this PR is an attempt to prevent this from happening by stopping the background service when the notification is dismissed. By stopping the service, there should be no way for it to start unless the user opens the app again.
Dismissing the notification is only possible if the notification is not on the foreground and the screen is unlocked, which means that it can only be dismissed while disconnected, the screen is unlocked and the tunnel is disconnected.
Git checklist:
--- …

Quit when notification is dismissed

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ProblemReportFragment.kt
android/src/main/res/layout/problem_report.xml
android/src/main/res/values-da/strings.xml
android/src/main/res/values-de/strings.xml
android/src/main/res/values-es/strings.xml
android/src/main/res/values-fi/strings.xml
android/src/main/res/values-fr/strings.xml
android/src/main/res/values-it/strings.xml
android/src/main/res/values-ja/strings.xml
android/src/main/res/values-ko/strings.xml
android/src/main/res/values-nb/strings.xml
android/src/main/res/values-nl/strings.xml
android/src/main/res/values-pl/strings.xml
android/src/main/res/values-pt/strings.xml
android/src/main/res/values-ru/strings.xml
android/src/main/res/values-sv/strings.xml
android/src/main/res/values-th/strings.xml
android/src/main/res/values-tr/strings.xml
android/src/main/res/values-zh-rCN/strings.xml
android/src/main/res/values-zh-rTW/strings.xml
android/src/main/res/values/strings.xml

This PR updates the "Report a Problem" screen on Android to match the new UI specification. The "Secure Connection" subtitle was removed and the the "Thanks!" part of the message shown after a successful send is now green. However, due to the need to split the message in two parts, the translations entries are no longer valid and were removed. They will match the translation entries on the desktop once they are updated, so the conversion should be simple using the translation converter tool.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2165)

Update "Report a Problem" screen UI on Android

---

CHANGELOG.md
Cargo.lock
android/build.gradle
dist-assets/windows/version.h
gui/package-lock.json
gui/package.json
mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-exclude/Cargo.toml
mullvad-problem-report/Cargo.toml
mullvad-setup/Cargo.toml
talpid-openvpn-plugin/Cargo.toml

Takes the version bumps and changelog changes from the 2020.6-beta3 release branch and merges them back into `master`. The changelog is somewhat changed. See if you think it makes sense.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2166)

Merge release changes to master

---

mullvad-management-interface/src/windows_permissions.rs

Taking a mut ref to a const object now produces a warning (on the beta and nightly channels).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2173)

Fix beta and nightly builds on Windows

---

CHANGELOG.md
dist-assets/windows/installer.nsh
mullvad-daemon/src/lib.rs
talpid-core/src/firewall/windows.rs
windows/winfw/src/winfw/mullvadguids.cpp
windows/winfw/src/winfw/mullvadguids.h
windows/winfw/src/winfw/mullvadobjects.cpp
windows/winfw/src/winfw/mullvadobjects.h
windows/winfw/src/winfw/objectpurger.cpp
windows/winfw/src/winfw/objectpurger.h
windows/winfw/src/winfw/rules/persistent/blockall.cpp
windows/winfw/src/winfw/rules/persistent/blockall.h
windows/winfw/src/winfw/sessioncontroller.cpp
windows/winfw/src/winfw/winfw.cpp
windows/winfw/src/winfw/winfw.h
windows/winfw/src/winfw/winfw.vcxproj
windows/winfw/src/winfw/winfw.vcxproj.filters

These changes cause the WinFw module to add persistent WFP filters when deinitialized with the "continue blocking" cleanup policy, and the daemon exits in a blocking state. This happens if "Always require VPN" is enabled, or if auto-connect is enabled.
Two sets of filters are required: Boot-time filters are used for blocking traffic before the BFE service has started. Persistent filters are used to block traffic after the BFE service has started, but before mullvad-daemon has started.
This prevents traffic leaks during boot when either "Always require VPN" or auto-connect is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2168)

Add persistent firewall filters on Windows

---

CHANGELOG.md
mullvad-cli/src/cmds/connect.rs
mullvad-cli/src/cmds/disconnect.rs
mullvad-cli/src/cmds/reconnect.rs
mullvad-cli/src/cmds/status.rs
mullvad-cli/src/format.rs
mullvad-cli/src/main.rs
mullvad-cli/src/state.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-jni/src/daemon_interface.rs
mullvad-management-interface/proto/management_interface.proto

This PR adds an argument (`--wait`) to the `connect`, `disconnect` and `reconnect` CLI commands which keeps the CLI running until the target state is reached. This will make it possible to run commands in sequence in a bash script, useful for automated testing for example.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2156)

Add option to make the CLI wait for the target state

---

CHANGELOG.md
mullvad-daemon/src/lib.rs

Previously, if auto-connect and "Always require VPN" were disabled, the service would reset the firewall upon starting back up, even if the tunnel was up when the crash occurred.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2172)

Restore the last target state if the daemon crashes

---

Cargo.lock
build.sh
mullvad-cli/Cargo.toml
mullvad-cli/src/main.rs
talpid-core/Cargo.toml
update-relays.sh

Currently, `build.sh` builds all dependencies three times: Once when `cargo build` is run, once before the CLI is used to generate shell completions, and once before running the relay list updater.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2174)

Avoid unnecessary rebuilds in build.sh

---

CHANGELOG.md
Cargo.lock
dist-assets/linux/before-remove.sh
dist-assets/uninstall_macos.sh
dist-assets/windows/installer.nsh
mullvad-daemon/src/account_history.rs
mullvad-daemon/src/lib.rs
mullvad-paths/src/lib.rs
mullvad-setup/Cargo.toml
mullvad-setup/build.rs
mullvad-setup/src/daemon_paths.rs
mullvad-setup/src/main.rs

These changes ensure that WireGuard keys are removed regardless of user's configuration. This is achieved by not relying on the daemon but rather `mullvad-setup` to clear the account history and removing the keys via communicating with the API. This is fairly straightforward on Linux and MacOS, but deducing the config directory's path on Windows was a bit more involved - there is now a feature (`deduce-system-service`) that enables `mullvad-paths` to properly deduce the daemon's config directory even when it's not ran from the context of a system service user. This feature is only used by `mullvad-setup`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2175)

Clear account history after unlocking firewall during uninstallation.

---

gui/src/renderer/components/NavigationBar.tsx
gui/src/renderer/lib/utilityHooks.ts
gui/src/renderer/redux/userinterface/actions.ts
gui/src/renderer/redux/userinterface/reducers.ts

This PR makes the app remember the scroll position when navigating to reset the scroll position to the correct location when navigating backwards.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2179)

Remember scroll position when navigating back

---

gui/src/renderer/components/ImageView.tsx
gui/src/renderer/components/TunnelControl.tsx

This PR fixes the occasional flicker of icons when navigating in the app. It was caused by
* an inefficiency in `styled-components` which makes the browser reload url-values when other styles are appended. This is solved by moving the CSS-property with the url-value to the inline `style` attribute.
* the `TunnelControl` buttons being remounted each rerender. This is fixed by defining the functional components outside of `render`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2180)

Fix icon flickering when navigating

---

gui/src/renderer/components/SvgMap.tsx

This PR:
* Makes the map marker the same size when it is disconnected as when it's connected, this issue was introduced when upgrading `react-simple-maps`.
* Adds a transition to the size change. The size and offset is added to the image inside the marker to allow it to transition without the whole marker transitioning when switching location.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2150)

Make map marker size consistent and animate changes

---

Cargo.lock
mullvad-daemon/Cargo.toml
talpid-core/Cargo.toml

Just upgrade `cfg-if` to the stable release. Should not make any difference in practice, except that we use the stable version and won't likely have to change this almost ever again :)
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2181)

Upgrade cfg-if to 1.0.0

---

gui/package-lock.json

This PR fixes the `fsevents` build error printed during `npm ci` on Windows by upgrading `gulp`'s dependency tree which includes fsevents. The error didn't stop the build and didn't affect the final build.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2182)

Upgrade gulp dependency tree

---

gui/.eslintrc.js
gui/package-lock.json
gui/package.json
gui/src/main/daemon-rpc.ts
gui/src/renderer/components/Connect.tsx
gui/src/renderer/components/SelectLocation.tsx
gui/src/shared/gettext.ts
gui/types/gettext-parser/index.d.ts

This PR upgrades the dependency on TypeScript to `4.0.3` and also updates `@typesscript-eslint/*` to correctly lint the new version. Some code adjustments were required to make the code conform to some new linting rules.
TypeScript changes: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2183)

Upgrade to TypeScript 4

---

gui/src/renderer/components/AppButton.tsx
gui/src/renderer/components/AppButtonStyles.tsx
gui/src/renderer/components/NotificationBanner.tsx

The buttons in the in-app notifications doesn't work since they don't pick up the `onClick` from the `BlockingContext`. This PR fixes that by adding an button without styling that can be used in such situations.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2184)

Fix non-working button in NotificationBanner

---

CHANGELOG.md
gui/src/renderer/components/SvgMap.tsx

This PR adds a custom `ZoomableGroup` component which doesn't contain the issue where the map zooms and pans to the initial location. As a result the other workaround can be removed and therefore both the initial transition issue and the missing transition issue caused by the first workaround is fixed.
The `ZoomableGroup` implementation can be removed when this issue has been solved:
https://github.com/zcreativelabs/react-simple-maps/issues/228
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2185)

Fix skipped map pan/zoom animation when switching location

---

gui/src/renderer/components/AppButton.tsx

The prop `textOffset` is passed to `SimpleButton` which passes it the `button` element causing React to log a warning. This doesn't affect behaviour of the button and the warning is only logged in development mode. This PR fixes this by not passing `textOffset` to `SimpleButton`.
The `textOffset` prop is only used in `MultiButton` which is only used for the disconnect/reconnect buttons.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2187)

Fix warning about unregocnized DOM element prop in AppButton

---

gui/package-lock.json
gui/package.json

This PR updates `browser-sync` which depends on an updated version of `object-path` that has fixed the vulnarability reported by `npm` and GitHub.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2194)

Update browser-sync to 2.26.13 to fix vulnerability in dependency tree

---

CHANGELOG.md
android/src/main/AndroidManifest.xml
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt

The app was previously configured to only run on portrait mode. However this led to a problem on some TVs which instead of showing the app with black bars, it showed the app side-ways. This PR is an attempt to workaround that so that the app becomes usable.
The PR includes two changes. The first is to change the app from `portrait` mode to `sensorPortrait`, which allows the sensor to be used to determine if the app should rotate 180 degrees (i.e., so that it rotates if the device is used upside down).
The second change forces the mode to be `sensorLandscape` if the device is detected to be a TV.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2193)

Work-around app being sideways on some TVs

---

Cargo.lock
mullvad-daemon/Cargo.toml
mullvad-exclude/Cargo.toml
mullvad-exclude/src/main.rs
mullvad-jni/Cargo.toml
talpid-core/Cargo.toml

Upgrade `nix`. `execvp` no longer forces you to pass `&[&CStr]` to it, so a tiny improvement was made in `mullvad-exclude`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2191)

Remove unnecessary vector from mullvad-exclude

---

android/src/main/res/layout/login.xml

[Previously](https://github.com/mullvad/mullvadvpn-app/pull/2177), the app got improved keyboard navigation in order to better support TVs. However, the login screen had a bug where it wouldn't focus the account input area when using the navigation arrow keys. It would only work with the tab key, which isn't available on most TV remotes.
This PR fixes that by making sure that pressing down when the background is focused moves the focus to the account input box. To improve the UX a little bit the app now starts with the background focused, so one press of the down key should allow the user to enter the account number.
I didn't automatically focus the account input area because on devices with no hardware keyboards it pops up the soft-keyboard which ends up hiding the "Create Account" …

Fix navigation on login screen

---

android/src/main/AndroidManifest.xml

Previous PRs improved how the app is used on TV devices (#2177, #2193, #2195). However, users still can't install the app on TVs using Google Play. That's because the app was previously had an implicit requirement for some hardware features (namely, touch screen support and portrait screen orientation).
This PR changes that so that the app can be found on Google Play on Android TV devices (when the next version is released). To do so, the screen orientation requirement was marked as optional (for both orientations) and the touch screen requirement was also marked as optional (along with "faketouch", which would be better named as "touch-like" input, and which includes mouse input).
Git checklist:
--- …

Make sure the app is marked with support TV devices

---

CHANGELOG.md
docs/security.md
mullvad-cli/src/cmds/custom_dns.rs
mullvad-cli/src/cmds/mod.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/settings.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-types/src/settings/mod.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/firewall/windows.rs
talpid-core/src/tunnel_state_machine/connected_state.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/tunnel_state_machine/disconnected_state.rs
talpid-core/src/tunnel_state_machine/disconnecting_state.rs
talpid-core/src/tunnel_state_machine/error_state.rs
talpid-core/src/tunnel_state_machine/mod.rs
talpid-types/src/net/mod.rs
windows/winfw/src/winfw/fwcontext.cpp
windows/winfw/src/winfw/fwcontext.h
windows/winfw/src/winfw/winfw.cpp
windows/winfw/src/winfw/winfw.h

This allows users to use DNS servers other than those provided by the relay server. One or more addresses can be set. For each address, the following applies:
* If an IP address is in a private network, non-tunnel interfaces are allowed by the firewall to send and receive DNS traffic to that address. However, the interfaces must be configured by the user to do so.
* For other IP addresses, the daemon configures the tunnel interface correctly to use the provided addresses. `WinFw` will allow traffic to pass to/from those addresses, and on that interface only. Due to hijacking, this currently has no effect.
Servers can be set or retrieved in the CLI as follows:
```
mullvad custom-dns set [addresses...]
mullvad custom-dns get
```
If `mullvad custom-dns set` is run without any arguments, the …

Support custom DNS servers on Windows

---

talpid-core/Cargo.toml
talpid-core/src/dns/windows/mod.rs

On Windows 10, the interface with the lowest metric is preferred for DNS resolution. When looking up hostnames using `getaddrinfo`, it will block until it has received a response from this interface (or times out after several seconds). It then uses responses from other interfaces as a fallback.
The metric also influences route priority. The metric of the tunnel interface is intentionally set to 1 in order for the default route belonging to the virtual adapter to always be preferred. This causes a huge lag because the tunnel interface is not allowed to request anything from local resolvers.
This was fixed by setting the DNS servers to use in the dnscache policy, which overrides the preference for a lower metric.
--- …

Speed up host resolution for local custom DNS

---

android/src/main/kotlin/net/mullvad/mullvadvpn/util/SegmentedInputFormatter.kt

Previously, a trailing separator was sometimes left in the input when entering a voucher code. This happened after entering a voucher code and pressing backspace repeatedly until it removed a character right before a separator. The logic in `SegmentedInputFormatter` would then try to help the user by placing the cursor before the previous character, skipping the separator. This meant that the separator would be left there.
It should be left there if it's not the last character, but otherwise it's best if it is removed. This PR removes it if it is the last character.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2201)

Remove trailing separator after updating selection

---

CHANGELOG.md
talpid-core/Cargo.toml
talpid-core/src/logging/windows.rs

Convert Windows log sink input to UTF-8

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/CustomItemAnimator.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/CustomRecyclerView.kt

When the collapsing title animation [was implemented for `RecyclerView`s](https://github.com/mullvad/mullvadvpn-app/pull/1859), it had to work around the fact that `RecyclerView`s don't actually keep track of the absolute scroll position. It only sends delta scroll events. The solution then was to create a `CustomRecyclerView` sub-class that integrated the deltas in order to keep track of the absolute scroll position.
That worked well in almost all cases. The exception was when enabling the split tunneling feature (which populates a long list of apps), scrolling down a bit in order to shrink the title, and then disabling the feature again, causing the apps to be removed from the list. After removing the items, the list would relayout to fill the empty space, and would send no scroll …

Fix screen title animation in Split Tunneling screen

---

talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/network_manager.rs
talpid-core/src/tunnel/wireguard/stats.rs
talpid-types/src/net/wireguard.rs

Since NetworkManager works best when it's the only entity trying to do anything with a specific interface, there were issues when using NM to manage DNS for a network interface the daemon had set up via netlink. To work around this, I've added a 3rd way of creating a WireGuard device on Linux - via DBus and NetworkManager. This seems to work well on Fedora 32, but more testing is required. From the outset, I tried to not worry about consolidating any of the NetworkManager code. These changes should fix #2186.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2209)

Create WireGuard interface via NetworkManager on Linux

---

CHANGELOG.md
talpid-core/src/routing/linux.rs

Up until now, when initializing the split tunneling routing table, the routes were being added in arbitrary order. Since routes can have dependencies, route application can fail if the routes are being set in the wrong order. This seems to happen often when the routes are set manually via `ip route add ...`. The solution is to sort the routes by prefix length so that the more specific routes are always applied first. 
In an unrelated note, I updated the changelog for both this issue and the issue with NM and periodic disconnection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2211)

Linux - sort routes by prefix length before application

---

CHANGELOG.md
mullvad-cli/src/cmds/mod.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/settings.rs
mullvad-types/src/settings/mod.rs
talpid-core/src/firewall/linux.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/routing/linux.rs
talpid-core/src/tunnel_state_machine/connected_state.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/tunnel_state_machine/disconnected_state.rs
talpid-core/src/tunnel_state_machine/disconnecting_state.rs
talpid-core/src/tunnel_state_machine/error_state.rs
talpid-core/src/tunnel_state_machine/mod.rs

Allow custom DNS resolvers to be used on Linux. For addresses in private IP ranges, DNS requests are permitted by the firewall on all non-tunnel interfaces. For other addresses, requests are only allowed on the tunnel interface.
Related PRs: #2205, #2188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2210)

Support custom DNS on Linux

---

CHANGELOG.md
gui/src/main/index.ts

The app isn't placed on top if the tray icon is pressed while the start menu is open. Additionally the focus events become broken until the user clicks on the app window, more specifically there's no `blur` event if the user focuses another application before clicking the app window.
This PR adds the `alwaysOnTop` flag to the `BrowserWindow` to ensure it's always placed on top. It doesn't fix the focus issue which is a bug in Electron: https://github.com/electron/electron/issues/25915
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2212)

Enable alwaysOnTop on Windows to ensure app is placed above other apps

---

ios/CHANGELOG.md
ios/MullvadVPN/DisplayChainedError.swift
ios/MullvadVPN/LoginViewController.swift
ios/MullvadVPN/MullvadRest.swift

… error (i.e too many WireGuard keys)
Git checklist:
- This PR fixes a regression where "Internal error" was displayed instead of server error (i.e too many WireGuard keys).
- Add missing CHANGELOG entry for a communication protocol transition from JSON-RPC -> REST (as per @faern's request)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2213)

Fix login screen error message

---

Cargo.lock
mullvad-problem-report/Cargo.toml

This PR switches to the official `rs-release` crate. We have previously used a git dependency pointing to our fork of the crate with a fix that hasn't been merged into `rs-release` (https://github.com/JIghtuse/rs-release/pull/2).
Now we want to get rid of git dependencies and I've looked into how to solve this and came to the conclusion that the escaped strings shouldn't cause any issues. Additionally I haven't found any distributions which use escaped characters in the `NAME` or `VERSION` values, which are the ones that we use. I've looked in the latest versions of Ubuntu, Fedora, Debian and Linux Mint.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app …

Switch to official rs-release crate

---

gui/src/main/index.ts

Currently the app version in settings is empty if the frontend fails to connect to the daemon. This PR fixes that by sending the version information to the renderer when frontend fails to connect to the daemon if it hasn't already been done.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2216)

Show app version in settings when failing to connect to daemon

---

dist-assets/windows/installer.nsh

`mullvad-setup.exe` and `winfw.dll` are extracted twice when the app is fully uninstalled, slowing things down slightly. Also, remove duplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2208)

Only extract mullvad-setup once

---

CHANGELOG.md
talpid-core/src/routing/linux.rs

On some older kernels, I've seen netlink report routes which seemingly route 0.0.0.0/0 through the loopback interface. This is bonkers and makes no sense. The changes I have here would just ignore such routes when parsing them. Another, not as destructive change, would be to parse them as is - if there is no destination NLA, just assume a default route and add it as such, and filter it out later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2218)

Ignore loopback routes on Linux.

---

gui/src/renderer/components/SelectLanguage.tsx

This PR fixes the non-working automatic scroll to the selected language in the language selector.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2220)

Fix initial scroll to selected item in language selector

---

CHANGELOG.md
talpid-core/src/dns/linux/network_manager.rs

Seems like on a lot of Ubuntu 20.04 machines (and sister-distros), NM takes some time to get to the final `NM_DEVICE_STATE_ACTIVATED` state, even though any device state after [`NM_DEVICE_STATE_IP_CHECK`](https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMDeviceState) should mean that the device is ready for our DNS config. Since sometimes NM can also be slow to detect that a device is ready, I made a drastic choice to bump the timeout to 15 seconds and also now more states are considered to be OK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2217)

Allow more device states with NM DNS

---

talpid-core/src/dns/linux/network_manager.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/network_manager.rs

Earlier, I made some changes to allow creating a WireGuard interface via NetworkManager. This code works, but improvements could be made to make it work with older NetworkManager versions - `AddConnection2` is only available as of NM 1.20, whereas WireGuard is supported as of version `1.16`.  So firstly, the NetworkManager WireGuard tunnel implementation checks if the NetworkManager that's available is new enough, then it attempts to apply the config, first via `AddConnection2`, and if that fails since that method doesn't exist, via `AddConnectionUnsaved`. There were also issues with IPv6 config when applying our DNS config via NM, which are resolved by checking what method is set for `ipv6` management.
--- …

Make NM WireGuard tunnel work on older NM versions

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt

Previously, sometimes the app would start with Auto-Connect enabled and connect automatically before the list of excluded apps was loaded from persistent storage. After loading is complete, the `SplitTunneling` class notifies the listener (`MullvadVpnService`) which then requests a reconnect.
However, if the reconnect is requested while the app is already reconnecting, the reconnect command wouldn't get sent to the daemon. That meant that the tunnel wouldn't be recreated to exclude the loaded apps, which led to the bug.
This PR fixes that by allowing the reconnect command to be sent to the daemon even if it is already reconnecting.
Git checklist:
--- …

Fix apps not being excluded sometimes when starting with Auto-Connect enabled

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

On Android 8.0 and up, apps can only start services from the background if they request the service to be on the foreground. However, that means that the service must call `startForeground` as soon as it starts or receives a start command after already having started. Otherwise, Android kills the service for bad behavior after a timeout.
Previously the app would mostly work, since the service would spend most of the time in the foreground. However, removing the Quit button and changing the dismiss behavior increased the rate of crashes.
This PR fixes the issue by placing the foreground on the foreground for a moment every time the service is created or requested to start. After placing the notification there it just restores the notification to the correct behavior (either on the …

Fix crashes caused by a missing call to `Service.startForeground()`

---

CHANGELOG.md
talpid-core/src/routing/linux.rs

`RouteManager::enable_exclusions_routes` is called when entering the connecting state, but `NLM_F_REPLACE` is ignored when the rule is added, causing duplicate rules to be added if it is called multiple times.
This may occur if connecting fails, for example, and the daemon attempts to reconnect. In this case, the disconnected state is not entered before the connecting state is entered again, and so `RouteManager::disable_exclusions_routes` is not called in between.
This should not cause any serious issues, but it does clutter the routing rules list seen with `ip rule`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2224)

Prevent duplicate fwmark rules

---

gui/.eslintrc.js
gui/src/renderer/components/LocationList.tsx
gui/src/renderer/components/SelectLanguage.tsx
gui/src/renderer/components/SelectLocation.tsx
gui/src/renderer/components/Selector.tsx

This PR:
* Enables the `react/find-dom-node` rule and replaces the last two usages of `ReactDOM.findDOMNode()`.
* Specifies the `ban-ts-comment` rule to only allow `@ts-ignore` instead of all ts-comments. One use of `@ts-ignore` is removed as well but there are still two left which can't be removed right now.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2226)

Improve ESLint rules

---

gui/locales/README.md

This PR moves the reference to the translation generation instructions for Android to the `messages.pot` section in `gui/locales/README.md` to prevent that they are forgotten when preparing a release.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2227)

Improve order of translation instructions

---

gui/src/renderer/components/Login.tsx

When improving the accessibility the login form was converted to a `form` element which caused the account history items to submit the form in addition to the intended logic. This resulted in `login()` being called twice. This wasn't very noticeable but if the app was set to auto connect on login and that connection took more than a second **and** the user entered the settings view before the connection completed or the second login call timed out, the app redirected back to `/connect`. Adding `type="button"` makes sure that the history items don't submit the form.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2229)

Set account history button type to "button" to prevent submitting twice

---

gui/package-lock.json
gui/package.json
gui/src/renderer/app.tsx
gui/src/renderer/containers/AccountPage.tsx
gui/src/renderer/containers/AdvancedSettingsPage.tsx
gui/src/renderer/containers/ConnectPage.tsx
gui/src/renderer/containers/PreferencesPage.tsx
gui/src/renderer/containers/SelectLanguagePage.tsx
gui/src/renderer/containers/SelectLocationPage.tsx
gui/src/renderer/containers/SettingsPage.tsx
gui/src/renderer/containers/SupportPage.tsx
gui/src/renderer/containers/WireguardKeysPage.tsx
gui/src/renderer/redux/store.ts

This PR removes the `connected-react-router` dependency since the same functionality can be achieved with the `withRouter` HOC.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2232)

Replace connected-react-router with use of withRouter()

---

scripts/install-mullvad

This adds a handy script that is useful to developers and testers. It takes a version of the app and downloads it, verifies its integrity and installs it. It grabs the installers from build.mullvad.net. So only versions available there will work of course.
This has been tested on Fedora 32, Debian 9 (we don't support that distro, but I did not have any newer apt based distro installed), and macOS 10.15.7.
Possible improvement includes you adding your build.mullvad.net parsing so a user can graphically select a version if they don't want to pass one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2239)

Add install-mullvad script. Useful to get dev builds

---

talpid-core/src/dns/linux/network_manager.rs

Fixes an error in the code waiting for the device to be activated.
Related PR: https://github.com/mullvad/mullvadvpn-app/pull/2217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2235)

Fix device state check when using NM

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/Cell.kt
android/src/main/res/values/dimensions.xml

While implementing the custom DNS UI, I realized that something was odd. The new UI elements seemed larger than the elements that were already present. After talking to Matilda about it, I realized that I made a mistake when I scaled down the UI dimensions following the desktop changes a few months ago. This PR fixes a few more noticeable issues, but o more thorough check should be done in the future comparing all screens to the source-of-truth.
In this PR, the text size of the label in the cell widget is fixed, as well as establishing a minimum height for the cell widget. The height is still allowed to grow (even though that might cause a few inconsistencies) because some languages have long text that end up spanning more than one line.
Git checklist:
--- …

Fix Android cell widget UI

---

talpid-core/src/dns/linux/systemd_resolved.rs

Currently, if systemd-resolved is not available, this is logged:
```
[ERROR] systemd-resolved is not being used because: Systemd resolved not detected
```
This is not an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2240)

Don't log absence of systemd-resolved as an error

---

talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/network_manager.rs
talpid-core/src/tunnel/wireguard/stats.rs
talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs
talpid-core/src/tunnel/wireguard/wireguard_kernel/netlink_tunnel.rs
talpid-core/src/tunnel/wireguard/wireguard_kernel/nm_tunnel.rs

One of the connectivity checker implementations uses D-Bus to check whether any traffic has been sent or received on the tunnel interface. This is preferentially used when setting up the kernel implementation of the WG tunnel.
At least one user has found that these D-Bus requests may time out and cause disconnects (apparently randomly). It isn't clear why this occurs, but it is possible that the time out is simply too ruthless on some slow systems. There should be no harm in giving the request more time to obtain the information. That is what this PR does.
```
[talpid_core::tunnel::wireguard::network_manager][ERROR] Failed to read tunnel stats from NM: "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked …
```

Use netlink for connectivity checking

---

CHANGELOG.md
talpid-core/src/dns/linux/network_manager.rs
talpid-core/src/dns/linux/systemd_resolved.rs

Originally, there were issues with NetworkManager not being able to set DNS servers per interface when it's managing DNS via systemd-resolved. Unfortunately, it fails silently and, worse still, there are users who have a config where `/etc/resolv.conf` is managed via NetworkManager but actual DNS management is done via systemd-resolved. In such a config, the daemon would fall back to using NetworkManager and it would fail silently. Whilst technically, NM is buggy here, the changes here would make the daemon prefer systemd-resolved over NM in a case where `/etc/resolv.conf` is still managed by NetworkManager yet DNS is actually managed via systemd-resolved's local resolver. This is achieved by verifying if NM is managing `/etc/resolv.conf` and relying on systemd-resolved when verifiying if …

Prefer systemd-resolved over NM if it's working

---

.travis.yml
Dockerfile
wireguard/build-wireguard-go.sh

This PR removes references to DockerHub for Docker images. The image hashes remain the same, but the tag is changed to reflect the new URL.
﻿Describe **what** this PR changes. **Why** this is wanted. And, if needed, **how** it does it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2244)

Move Docker images to Quay.io

---

talpid-core/src/routing/mod.rs
talpid-core/src/routing/unix.rs
talpid-core/src/routing/windows.rs
talpid-core/src/tunnel/openvpn.rs
talpid-core/src/tunnel_state_machine/mod.rs

On Linux, a channel can already be used to communicate with the route manager across different threads. This has been generalized to all OSes and abstracted behind a type `RouteManagerHandle`. It is a prerequisite for manually setting up routes in the OpenVPN tunnel monitor, which is part of a refactoring to rely less on route monitoring.
* No longer spawn a separate new runtime on Linux for the route manager.
* Don't rely on executors from `futures` while handling events from OpenVPN.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2231)

Generalize the route manager channel

---

CHANGELOG.md
README.md
talpid-core/src/dns/linux/mod.rs
talpid-core/src/dns/linux/systemd_resolved.rs
talpid-core/src/dns/mod.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs

Since NM has issues with managing routes and not hanging forever, I've changed it so that NM will never be used to create a WireGuard device by default. To use NM, one would have to set environment variable `TALPID_FORCE_NM_WIREGUARD` to anything but `0`. The previous behavior would be to try and use NM first, and if NM fails to create a device, depending on the error, either try userspace or netlink to create a WireGuard device. Finally, if the daemon fails to create a device via netlink, it would fall back to the userspace implementation. The current behavior is changed so that at first the daemon will check if we can use a kernel implementation at all by checking if NM would manage DNS. If NM is managing DNS, the userspace implementation will be used. Otherwise, if …

Prefer netlink over NM to create a WireGuard device on Linux

---

CHANGELOG.md
talpid-core/src/dns/linux/network_manager.rs
talpid-core/src/dns/linux/resolvconf.rs
talpid-core/src/dns/linux/systemd_resolved.rs
talpid-core/src/dns/mod.rs

In some cases when resetting the DNS config, the tunnel interface is already down. This must be done regardless, because some implementations of the DNS monitor modify a global state (e.g., on Windows and macOS, or when using a static resolv.conf). At the moment, two implementations may return an error if an interface cannot be found. This PR updates them to always treat this as an expected case and not log an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2243)

Always succeed in resetting the DNS config if the tunnel interface is not found

---

android/src/main/res/layout/split_tunneling_header.xml
android/src/main/res/values/strings.xml

This is a minor UI message tweak to make the Android app more consistent with the desktop app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2251)

Replace "Enabled" with "Enable" in Split Tunneling

---

CHANGELOG.md
talpid-core/src/dns/linux/network_manager.rs

Setting the searhc domain key in the IP configs for NetworkManager makes NetworkManager capable to manage DNS via systemd-resolved again. To test this, you'd have to remove the systemd-resolved's check for being managed via NM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2255)

Add search domain to NM DNS config

---

talpid-core/src/tunnel/wireguard/mod.rs

The previous state of the `master` branch would fail to connect the tunnel on Android, and the log would say that the error was in the `RouteManager`. On Android, there is no need to use the `RouteManager` so this PR provides a quick fix that avoids the call that adds the routes using the `RouteManager` instance.
In the future, it might be a good idea to revisit the `RouteManager` code itself and see if it can be compiled out on Android.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2256)

Don't add routes with `RouteManager` on Android

---

CHANGELOG.md
talpid-core/src/routing/linux.rs
talpid-core/src/routing/mod.rs

Currently on every start of the daemon the route manager logs an entry for each loopback route it sees. To deal with this somewhat nicer, I've changed the route parsing code to just parse a loopback device as a route with a gateway via `127.0.0.1`, which can then be counted and filtered later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2245)

Linux - parse loopback routes semi-correctly to count them and log less.

---

talpid-core/src/routing/android.rs
talpid-core/src/tunnel/wireguard/mod.rs

Some recent changes to the route monitor would cause methods to return errors if the underlying implementation didn't send back a correct response. The Android route manager essentially does nothing, but it should stlil respond. This was fixed.
Related: #2256, https://github.com/mullvad/mullvadvpn-app/commit/86170137bf1bc141b7bcff5e952121ac8784fb8c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2260)

Update the Android route manager

---

gui/src/renderer/components/NavigationBar.tsx

It has turned out that there was breaking changes in React 17 that has affected our app. This is the only regression I've found and I've searched through the codebase for other similar usages and didn't find any. The regression that this PR fixes is that the app failed to save the scroll position when leaving a view due to the fact that `useEffect` clean up function is now called asynchronously.
React 17 upgrade PR: https://github.com/mullvad/mullvadvpn-app/pull/2247
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2263)

Fix not saving scroll position before unmount

---

CHANGELOG.md
talpid-core/src/dns/linux/mod.rs
talpid-core/src/dns/linux/network_manager.rs
talpid-core/src/dns/linux/systemd_resolved.rs
talpid-core/src/dns/mod.rs
talpid-core/src/linux.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/tunnel_state_machine/disconnected_state.rs
talpid-core/src/tunnel_state_machine/error_state.rs
talpid-core/src/tunnel_state_machine/mod.rs

It seems that NetworkManager can hang if it can't do it's connectivity check - which can often be induced by applying our firewall rules. As such, I've changed the tunnel state machine to disable the connectivity check before applying the firewall rules, and restoring it afterwards. No effort is made to track the flag that enables the connectivity check - the user may enable it after the rules have been applied - I don't believe we should do anything about that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2249)

Disable NetworkManager's connectivity check.

---

CHANGELOG.md
gui/package-lock.json
gui/package.json
gui/tasks/distribution.js

This PR fixes the issue with downgrade warnings when installing a stable version over a beta with `apt`. The reason for the downgrade warnings is that the version strings are compared lexographically. The correct solution to this is to use a tilde between the different components in the version field in the .deb file, e.g. `2020.7.0~beta1~dev-111111` instead of `2020.7.0-beta1-dev-111111`.
In addition to changing the separator this PR also removes the `.0` from the version string, e.g. `2020.7~beta1~dev-111111` instead of `2020.7.0~beta1~dev-111111`.
https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
```
The lexical comparison is a comparison of ASCII values modified so that all the letters sort earlier than all the non-letters and so that a tilde sorts before …
```

Fix apt downgrade warnings when going from beta to stable

---

CHANGELOG.md
talpid-core/src/dns/linux/network_manager.rs
talpid-core/src/process/openvpn.rs
talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/openvpn.rs

Previously, OpenVPN would create routes for us. Instead, we now simply take the routes it gives us and pass them to the route manager. This allows for more flexibility in setting up routing. The step after this is to use rule-based routing in order to reduce the amount of monitoring and parsing required on Linux.
Also, the virtual interface is now also able to switch from one physical interface to another better one (e.g. when switching off of Wi-Fi), as is already the case for WireGuard. This should prevent disconnects when the original interface goes down, although I haven't tested this.
Related PRs: #2231 #2115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2254 …

Use the route manager to set up routes when using OpenVPN

---

gui/src/renderer/components/Switch.tsx
gui/src/renderer/components/cell/CellButton.tsx
gui/src/renderer/components/cell/Input.tsx
gui/src/renderer/components/cell/Label.tsx
gui/src/renderer/lib/utilityHooks.ts

This PR:
* Prevents the hover effect on `CellButton` when the button is disabled
* Prevents the hover effect on an icon in a `CellButton` when the button is disabled
* Make it possible to combine refs in class components
* Forward ref into `Switch`.
All these changes are required for my custom DNS UI implementation and is submitted as a separate PR to prevent the main PR from growing too big.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2270)

Improvements required for custom DNS UI

---

CHANGELOG.md
gui/src/main/gui-settings.ts
gui/src/main/index.ts
gui/src/main/window-controller.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/HeaderBar.tsx
gui/src/renderer/components/NavigationBar.tsx
gui/src/renderer/components/NavigationBarStyles.tsx
gui/src/renderer/components/PlatformWindow.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/containers/PlatformWindowContainer.tsx
gui/src/renderer/containers/PreferencesPage.tsx
gui/src/renderer/redux/settings/reducers.ts
gui/src/shared/gui-settings-state.ts
gui/src/shared/ipc-event-channel.ts

This PR adds a new setting which unpins the app from the taskbar in Windows. In addition to that it also:
* Makes sure that the size of the web content is the desired size
* Changes the menu close icon to the arrow when in unpinned mode
* Adds the context menu when in the unpinned mode
* Hides the app on macOS when the tray icon is right-clicked, to make it consistent with Windows
* Makes the start minimized setting visible and respected when in unpinned mode.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2273)

Add unpin window setting on Windows

---

CHANGELOG.md
talpid-core/src/firewall/linux.rs
talpid-core/src/tunnel_state_machine/connected_state.rs

This updates the firewall to disallow any traffic going inside the tunnel when using `mullvad-exclude`, excepting non-custom DNS. DNS traffic is also blocked in the tunnel if custom DNS servers are configured.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2274)

Block in-tunnel traffic for `mullvad-exclude`

---

talpid-core/src/routing/android.rs
talpid-core/src/routing/macos.rs

master does not build on macOS or Android, because `RouteManagerCommand` was changed from being public to `pub(crate)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2279)

Fix method visibility

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt

Previously, the tunnel state notification could be updated by two threads: the UI thread or a background thread that dispatches tunnel state events. This meant that there was a risk of a race condition. I'm not sure if this has happened before, because I found this issue while investigating another, but I think I might have seen it when swiping away the notification while disconnecting and then the notification reappeared shortly afterwards showing that the daemon was in the disconnected state.
This PR fixes that by dispatching tunnel state events (and settings change events, which also affect the notification because it may show or hide the action button based on the login status) solely on the UI thread.
Git checklist:
--- …

Avoid race condition when updating notification

---

CHANGELOG.md
mullvad-cli/src/cmds/relay.rs

Closes #2267.
Signed-off-by: Robin Gögge <r.goegge@outlook.com>
This PR changes the `mullvad relay set relay` CLI sucommad to `mullvad relay set hostname` in order to improve the CLI UX.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2287)

Rename `mullvad relay set relay` to `mullvad relay set hostname`

---

gui/src/main/index.ts
gui/src/shared/logging.ts
gui/test/logging.spec.ts

This PR:
* Changes the name of `frontend-renderer.log` to `renderer.log` to make sure that everything is added to the log, even errors from before the logging is set up
* Adds clean up of old log files
* Adds tests of log rotation and clean up
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2281)

Change renderer log file name

---

android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt

Historically, the Android app code-base has slowly accumulated Kotlin compiler warnings. This is entirely my fault for missing them and merging PRs that add more warnings. From time to time a PR would be merged to fix all of them on once, but that is not the ideal way to organize things.
This PR enables a flag for the Android build to treat warnings as errors. This will make it harder to ignore the warnings and the CI builds will fail if warnings are still left in PRs.
The PR also fixes the warnings that remained in the code base, mostly due to unused variables. There was also the requirement to opt-in into the API for coroutine channels, which is marked as obsolete. From what I could understand after a quick glance on the internet, there is no current substitute API, but the developers …

Treat Kotlin compiler warnings as errors

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
talpid-core/src/tunnel/tun_provider/android/mod.rs

The app can fail creating the tun device when auto-connect is enabled but the VPN permission is not granted. When that happens, the tunnel state machine proceeds to enter the error state. When entering that state, it requests a tunnel device to be created. Previously, the app did not check if the tunnel device was created or not in the Java side. This meant that the tunnel state machine would think that the creation of the tun device succeeded, and assume it was in the blocking state. However, if the VPN permission isn't granted, it will never be able to create the tun device. That meant that the app was reporting that it was blocking connections even if it wasn't.
This PR fixes that by returning a boolean flag to indicate if the tunnel is up or not, which the Rust side can then convert …

Fix app showing it was blocking connections when it wasn't when the VPN permission was denied

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt

Previously, the VPN permission was handled in two different ways. If the user asked the app to connect but then denied the VPN permission, the app would just stay in the disconnected state. If the user enabled auto-connect and restarted the app, the app would show a message saying that the VPN permission was denied.
This PR makes sure that an error message is always shown if the VPN permission is denied. That means that if the user asks the app to connect and then denies the permission, the app will still try to connect so that it ends up in the error state and shows the error message that the VPN permission wasn't granted.
Git checklist:
--- …

Always show error message when VPN permission is denied

---

CHANGELOG.md
Cargo.lock
talpid-core/Cargo.toml

Update `nftnl` crate to version 0.6 to fix memory leak in Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2291)

Update nftnl crate to 0.6

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
build-apk.sh

A previous PR (#2259) improved the API address cache in a few ways. One of them was to fetch an up-to-date address during the build procedure and distribute it with the app. However, although the file was included in the Android APK, it wasn't extracted during runtime, and the daemon would fail to start without it. On Android, unfortunately, files can't be included directly in the APK, and instead they must be included as byte stream "assets", which the app must then extract and store in files in the filesystem when it is first executed, before starting the daemon.
This PR fixes that by extracting the file during runtime together with the relay list file. The PR also updates Android's build script to also fetch an up-to-date address to be included in the APK, in case the desktop build …

Fix missing `api-ip-address.txt` file no Android

---

android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
mullvad-jni/src/lib.rs
mullvad-problem-report/src/lib.rs
mullvad-problem-report/src/main.rs

A previous PR (#2259) changed a bit how the RPC client is configured when sending problem reports. It now requires the resource directory path so that the RPC client can load the API IP address to use for connecting to the API. However, on Android, the resource directory is determined at runtime because the user can install the app on an SD card. This means that the path can only be determined from the Android `Context` object, and that must be sent from the Java side to the Rust side. The original PR used the static path specified in `mullvad_paths`, which meant that on Android sending problem reports failed because it couldn't initialize the RPC client because the resource directory path was incorrect.
This PR makes sure that the resource directory path on Android is correctly sent to …

Fix sending problem reports on Android

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/DaemonInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
mullvad-jni/src/lib.rs

Previously, it was possible to spawn multiple daemon instances in the right scenario because of a race condition. The condition happened when the service stopped right after it started, while the daemon was still starting. When the service stopped, the daemon had not finished setting up, so the stop handling code couldn't set a shutdown command to the daemon. Because Android may reuse the same process for the service, this meant that a second start would also try to start the daemon again, and the first instance would end up leaking and conflicting with the second instance (they would fight to set up the tunnel, for example).
This PR tries to fix the race condition by refactoring the daemon lifecycle handling code. It tries to use the same approach used …

Fix race condition that led to multiple daemon instances running at the same time

---

gui/src/main/index.ts

#2273 introduced an issue which causes the quit button to not function properly in Windows when the app is pinned to the taskbar. This was caused by `closable` being set to `false` for the window which wasn't correct.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2280)

Fix quit button in pinned mode on Windows

---

README.md
talpid-core/src/tunnel/wireguard/mod.rs

Since all the recent changes should have fixed the issues the daemon was experiencing when using NM to create WireGuard tunnels, I think it's reasonable to remove the environment variable gating the use of NM and try to use NM in all cases where NM would be managing DNS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2292)

Use NetworkManager to create a WireGuard device

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt

There was a previous fix (#2222) for an issue where Android would kill the service due to a missing call to `startForeground`. However, the issue reappeared after a previous PR (#2283) refactored the notification handling code. Unfortunately, the new code introduces a delay when updating the notification and also fails to run the clean-up operation of removing the notification when the actor has finished handling messages. The former happens because even though the call to `startForeground` happens on the UI thread, it has to wait until the main operation of the thread has finished (and the `Handler` starts handling scheduled tasks, including the co-routine). The latter happens because when stopping, the service closes the actor's channel but finishes executing `onDestroy` before the …

Fix regression that caused a missing call to `startForeground`

---

CHANGELOG.md
talpid-core/src/linux/network_manager.rs

NetworkManager will just not apply our DNS config when managing DNS via dnsmasq, so the correct thing to do is to fall back to `resolvconf` and using a static file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2296)

Stop using NM when it uses dnsmasq

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt
android/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt
android/src/main/res/values/strings.xml
mullvad-jni/src/classes.rs

Fixes an oversight in #2278.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2303)

Rename TAP adapter error state cause on Android

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

Android may decide to kill the service at any time. On Android 11, this is more frequent. If that happens, the daemon is stopped, but since there was no request for the service to stop, the `isStopping` flag was not set to `true`, and that makes the daemon restart, which then leads to a crash.
This PR fixes that by adding another flag, called `hasStopped`. It is only set in the `onDestroy` method, which is the last method called before the service is killed. This means that when the daemon is stopped, it will not restart if either the `isStopping` or the `hasStopped` flag is set.
This crash only happens due to the `DaemonInstance` refactor, because the channel to communicate with the actor is closed, and the restart tries to send a command through the closed channel. Before the refactor, …

Don't restart after `onDestroy` has been called

---

CHANGELOG.md
talpid-core/src/tunnel_state_machine/connected_state.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs

On Android, allow LAN is implemented by changing the routes that go through the tunnel. When it is enabled, LAN routes are excluded from the tunnel device. This means that enabling or disabling the feature requires the tunnel to be recreated for the changes to take effect.
Previously, the tunnel device would be recreated correctly, but the tunnel connection would not have been affected. This meant that the tunnel would simply not work, and all connections would be blocked. And that continued for a couple of minutes when the tunnel would actually reconnect and use the new tunnel device.
This PR changes the Connected and Connecting states of the tunnel state machine to force a reconnection when the Allow LAN setting changes.
Git checklist:
--- …

Reconnect after changing Allow LAN setting on Android

---

CHANGELOG.md
gui/package-lock.json
gui/package.json
gui/src/main/index.ts
gui/src/renderer/containers/SupportPage.tsx
gui/tasks/dev-server.js
gui/tasks/scripts.js
gui/tasks/watch.js
gui/test/setup/main.js

This PR upgrades Electron from 8.5.2 to 11.0.2 and also contains the following changes to adjust to braking changing/issues:
* Update to compatible NSEventMonitor
* Enable use of `remote` module in the renderer process
* Remove no longer needed assignment of `app.allowRendererProcessReuse`
* Replaced deprecated method `openItem` with correct one
* Prevent Electron from downloading spellcheck dictionaries (https://github.com/electron/electron/issues/22995)
* Serve renderer content with a web server in development to make devtools work (https://github.com/electron/electron/issues/23662, https://github.com/electron/electron/issues/24011)
* Switching to inline source maps was required to make source maps work
Changelogs for Electron:
9.0.0: https://www.electronjs.org/blog/electron-9-0
10.0.0: …

Upgrade to Electron 11

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

Android may at any moment decide to kill the service. Usually (exception is when swiping away the UI, and Android deciding to kill the hole process) Android calls `onDestroy` when doing that. Attempting to restart the daemon when that happens leads to a crash. A previous PR (#2299) implemented a partial fix to this issue, by avoiding to restart when the daemon stopped if `onDestroy` had been called.
This PR extends that fix to always check the state before restarting, and not just when the daemon has stopped.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2304)

Fix restarting after `onDestroy` has been called

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

A recent PR (#2286) fixed a race condition that ended up spawning multiple daemons. However, that surfaced an issue where Android kills the service prematurely and quickly after spawning it. When that happens, the daemon instance ends up shutting down before the service has fully initialized the classes that use the daemon. This ends up either setting the `instance` to a shut down daemon or having the dependent classes getting `null`s when requesting data from the daemon.
This PR ensures that the `instance` property is correctly set to `null` if Android kills it prematurely and prevents the race condition of the slow daemon startup to overwrite the `instance` property when the daemon has shut down.
Git checklist:
--- …

Fix daemon startup race condition

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
mullvad-jni/src/lib.rs

A previous issue surfaced a race condition when starting and stopping the daemon too quickly. The issue is fixed by a separate PR (#2305). However, one of the symptoms was a `NullPointerException` that was thrown when using a valued returned by the stopped daemon. The daemon proxy implementation returns `null` values when it has lost the connection to the daemon. In theory this shouldn't be an issue since when the daemon stops the UI returns to the launch screen and fetches are stopped. However, this may be an issue in some cases if some data is requested from the daemon right after it stopped and before the UI changes.
This PR improves the robustness of the daemon proxy by marking the returned values as nullable and handling `null` values where appropriate.
Git checklist:
---
This change …

Handle `null` values returned when daemon has stopped

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/CustomItemAnimator.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/CustomRecyclerView.kt

[Previously](https://github.com/mullvad/mullvadvpn-app/pull/2206), a workaround was implemented to listen for item animations in the `RecyclerView` in order to detect animations that should be treated as scroll events. However, the PR intercepted animations on all items. This led to a bug that was discovered while implementing the new custom DNS UI, where an item animation causes the title to collapse when it shouldn't.
This PR fixes that issue by only treating animations of the first visible item as animations that should be treated as scroll events.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2258)

Fix title collapse animation hook

---

talpid-core/src/routing/macos.rs

This PR pipes `stderr` to `/dev/null` when calling `route delete` on macOS. This is to prevent spamming of this message:
```
route: writing to routing socket: not in table
route: writing to routing socket: not in table
route: writing to routing socket: not in table
....
```
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2308)

Pipe route deletion stderr on macOS to /dev/null

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt

Previously, if the user left the login screen while logging in, when they returned to that screen it would seem that the login procedure was cancelled. What was actually cancelled was the coroutine that advanced to the next screen. This PR fixes that by checking if the user is already logged when showing the login screen.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2309)

Advance to next screen if already logged in

---

CHANGELOG.md
talpid-core/src/tunnel_state_machine/connecting_state.rs

All WireGuard tunnel errors were logged about with the warning level in the connecting state, which can be confusing to users and other developers, since a time out is a WireGuard tunnel error. With this I'm changing the logging to log about time outs with the debug level, all other errors are still logged about with the warning level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2312)

Log less about timeouts when connecting via WireGuard

---

Cargo.lock

Helps unblock https://github.com/rust-lang/rust/pull/78802
The linked PR is just a private project of mine. But the earlier crates can upgrade, the better.
I have not tried the result of this myself. But the test suites for `mio` passes with these bumped versions, I have tried that separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2316)

Upgrade net2 and miow dependencies

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt

Previously, the Login screen sometimes appeared without the account input area. This is likely caused by reusing the fragment after the account input was hidden after showing a login successful message. This PR makes sure to reset the state of the account input widget every time the screen is shown, to prevent that situation from happening.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2314)

Avoid starting with invisible account input

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt
android/src/main/res/layout/account_history_entry.xml

Previously, when navigating on the login screen with the keyboard (like on TVs), it was impossible to remove an account from the account history list on the login screen. This PR fixes that and also adds a small tweak to the behavior of the back button.
It is now possible to use the left and right arrows on the keyboard to move between the account history item and it's remove button.
And pressing the back button will first remove the focus of the account login widget in order to collapse the history. Pressing back again will then leave the app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2315)

Improve keyboard navigation in `AccountLogin` widget

---

CHANGELOG.md

A rebase after releasing version `2020.8-beta1` for Android caused some changelog entries related to unreleased changes to be included in the released section. This PR moves those entries to the "Unreleased" section.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2319)

Move entries related to unreleased changes to top

---

gui/src/main/index.ts

When upgrading to Electron 11 the app started appearing in the dock and app switcher. This PR fixes it by calling `app.dock.hide()` after the `BrowserWindow` has been created. Calling it before creating the window doesn't work. Electron seems to reset this setting after the first window has been created.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2322)

Hide app icon in dock and app switcher on macOS

---

mullvad-cli/src/cmds/bridge.rs
mullvad-cli/src/cmds/custom_dns.rs
mullvad-cli/src/cmds/tunnel.rs

For example, the argument `enabled` in `mullvad custom-dns set <enabled>` has the possible values `on` and `off`, which can be confusing. For consistency, this PR renames all arguments like this to `policy`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2321)

Name arguments that can be on or off consistently in the CLI

---

gui/package-lock.json
gui/package.json

This PR downgrades Styled components to 5.1.1 due an issue regarding encapsulation:
https://github.com/styled-components/styled-components/issues/3334
It can't be downgraded to 5.2.0 due to this issue:
https://github.com/styled-components/styled-components/issues/3269
In our case the encapsulation issue resulted in this:
> I noticed that when you go to the settings and hover your mouse over a menu it highlights the arrow with red color ... I figured out when it starts to happen. It's after you visit Split Tunneling and then go back.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2325)

Downgrade styled components to 5.1.1

---

Cargo.lock
talpid-core/src/routing/linux.rs

These crates had security advisories posted against them for the versions we were using.
https://rustsec.org/advisories/RUSTSEC-2020-0059.html
https://rustsec.org/advisories/RUSTSEC-2020-0060.html
I have not actually tested this. Since they are patch upgrades and only a few crates I really hope nothing breaks. We will do more testing before releasing very soon anyway. And there are not many alternatives to merging this either. Since it's a potential security issue.
I don't know if we use the vulnerable code or not. But even if we don't some dependency of ours might and that's a huge amount of work to check. Better to just upgrade upgrade upgrade.
--- …

Upgrade futures-util and futures-task

---

mullvad-setup/src/daemon_paths.rs
mullvad-setup/src/main.rs

`mullvad-setup` is run from a temporary directory on Windows, and `mullvad_paths::resource_dir()` simply returns the directory of the currently running executable. `api-ip-address.txt` will of course not be found there. This means that `mullvad-setup` cannot reach the API during uninstall unless there is an updated cache in SYSTEM's AppData directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2326)

Use correct resource path in mullvad-setup on Windows

---

windows/winfw/src/winfw/winfw.cpp

The `172.16.0.0/12` range cannot be used with local DNS resolvers on Windows due to a typo. This fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2328)

Fix private IPv4 range definition

---

android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/service/LocationInfoCache.kt

Previously, the `LocationInfoCache` had some slightly complex logic to make sure only one fetch was running and to make sure that fetches were serialized. This PR simplifies that by refactoring the class to use an actor to fetch the location.
The fetches now happen entirely in the background thread, where previously the management part happened in the UI thread. Running parts of it in the UI thread was unnecessary, because the only receiver of location events (the `ConnectFragment`) was already spawning a UI thread coroutine to handle the location updates.
The logic for fetching should stay the same. The actor waits for a request to fetch, and then retries the fetch with an exponential back-off until a valid location is fetched. Cancelling the fetch was removed, but since cancelling is a …

Refactor `LocationInfoCache` into actor

---

gui/src/renderer/components/TransitionContainer.tsx

This PR gets rid of the last deprecated React lifecycle method we had.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2310)

Replace use of deprecated React lifecycle method

---

Cargo.lock
android/src/main/kotlin/net/mullvad/mullvadvpn/model/DnsOptions.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/TunnelOptions.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/CustomDns.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/SettingsListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
mullvad-daemon/src/lib.rs
mullvad-daemon/src/settings.rs
mullvad-jni/Cargo.toml
mullvad-jni/src/classes.rs
mullvad-jni/src/daemon_interface.rs
mullvad-jni/src/lib.rs
mullvad-types/Cargo.toml
mullvad-types/src/settings/mod.rs
talpid-core/Cargo.toml
talpid-core/src/tunnel/tun_provider/android/mod.rs
talpid-core/src/tunnel_state_machine/connected_state.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/tunnel_state_machine/disconnected_state.rs
talpid-core/src/tunnel_state_machine/disconnecting_state.rs
talpid-core/src/tunnel_state_machine/error_state.rs
talpid-core/src/tunnel_state_machine/mod.rs
talpid-types/Cargo.toml

By default the app uses the DNS servers provided by the relay server. However, some users prefer to use custom DNS servers. This PR implements that and adds an initial entry in the Advanced Settings screen to configure the custom DNS server address. If left unspecified, the app falls back to using the DNS servers provided by the relay.
The current implementation is very simplified, supporting a single custom DNS server address. It is persisted as a shared preference, and how it is used to configure the tunnel is similar to how split-tunneling is implemented. When the setting is changed, the tun device is marked as stale and a reconnection is requested. When creating the tun device, `TalpidVpnService` will pass the DNS servers provided by the relay server to a `prepareDnsServers` method. …

Add support for custom DNS server on Android

---

mullvad-daemon/src/geoip.rs
mullvad-daemon/src/wireguard.rs
talpid-core/src/tunnel/openvpn/mod.rs

OpenVPN doesn't wait for the network interfaces to be fully usable before considering the tunnel to be up. As a result, there may be no connectivity for up to 3 seconds after the daemon enters the connected state. This can be verified by pinging any address immediately after connecting.
The docs for [CreateUnicastIpAddressEntry](https://docs.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-createunicastipaddressentry) state:
> The unicast IP address passed in the Address member of the MIB_UNICASTIPADDRESS_ROW pointed to by the Row parameter is not usable immediately. The IP address is usable after the duplicate address detection process has completed successfully. It can take several seconds for the duplicate address detection process to complete since IP packets need to be sent …

Wait for Wintun adapter's unicast addresses to be usable

---

docs/architecture.md
docs/split-tunneling.md

All combinations of split tunneling and custom DNS consist of many different states. This documentation aims to figure out what's actually going on and get it written down so it becomes easier to find than reading code or testing it out.
You three reviewers knows more about how it actually works. So please read carefully and tell me where the text is not fully correct.
Windows is not even merged yet. But the intention is that the documentation should explain how it works once it's "done". So for every platform, please point out if I'm confusing current behaviour with how it's planned for the future or something.
[Rendered version](https://github.com/mullvad/mullvadvpn-app/blob/add-split-tunneling-docs/docs/split-tunneling.md)
--- …

Add initial split tunneling documentation

---

talpid-core/src/tunnel_state_machine/mod.rs

The connectivity check disabling code currently will never reset the system to what it was before. This change fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2336)

Fix connectivity check disabling

---

gui/src/renderer/components/FormattableTextInput.tsx
gui/src/renderer/components/Login.tsx
gui/src/renderer/components/LoginStyles.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/components/RedeemVoucherStyles.tsx

This PR adds a component that enables formatting of input values, and makes use of it in the account token input and the redeem voucher inputs.
The voucher input is formatted as `XXXX-XXXX-XXXX-XXXX` and a trailing dash is added after each group of four has been entered. This input has a max length of 16 (excluding `-`)
The account token input is formatted as `NNNN NNNN NNNN NNNN` with the difference that no trailing space will be added during input. There is no max length for this input.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2337)

Automatically format text input for account token and voucher code

---

dist-assets/windows/installer.nsh

This fixes an issue where the Wintun driver signature is rejected on Windows 7 and must be manually approved. The dialog cannot be displayed when the driver is installed from a service and the driver is rejected instead, so no Wintun adapters can be created at all unless the driver is already installed on the machine. KB2921916 fixes this. It is not installed by Windows Update and is difficult to obtain, so it is included with the installer here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2342)

Fix "untrusted publisher" issue on Windows 7

---

android/translations-converter/src/android.rs
android/translations-converter/src/gettext.rs
android/translations-converter/src/main.rs

Previously, the translation converter helper tool would only load Android plural resources and append them as missing translations to the template file (`gui/locales/messages.pot`). This PR updates the tool so that it can properly read the plural messages from each translation file and then convert them and write them out as Android plural resources XML files.
Since different locales have different pluralization rules, this is a bit tricky. On Android, the options available to translators is rather limited, since the messages must specify the plural quantity based on five options (`zero`, `one`, `few`, `many` and `other`) while gettext allows a general formula than can produce an unlimited number of strings to use. To make the conversion possible, only known formulas are parsed from the …

Import plural translations into Android

---

docs/split-tunneling.md

This is the result of a recent Slack discussion. How should we talk about split tunneling so people understand us and so that we are consistent. The result was to continue calling the feature "split tunneling" but to refer to programs/apps as "excluded" and "included" not "split" and "unsplit" or some other variant. I added this to our documentation so we have it persisted somewhere and don't repeat the same discussion over and over.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2344)

Explain the vocabulary used around split tunneling

---

android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt
mullvad-jni/src/lib.rs
mullvad-jni/src/problem_report.rs

A previous PR (#2317) implemented the ability to view the collected logs in a separate screen. As part of that PR, a line was added to set the `collectJob` to `null` when deleting the problem report file. However, the method to delete the file was called by the `collectJob`, which meant that the reference to the job would be overwritten while it was executing, preventing further usages from waiting for it to complete. This broke sending problem reports.
To fix this issue and to avoid similar issues in the future, the `MullvadProblemReport` class was refactor to remove juggling all the coroutine jobs and just have one that is implemented using the actor model. This simplifies the logic, makes the behavior more predictable and easier to maintain.
The PR also moves the native JNI method …

Refactor problem report into an actor

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConfirmPublicDnsDialogFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsAdapter.kt
android/src/main/res/layout/confirm_public_dns.xml
android/src/main/res/values/strings.xml

Our servers intercept and redirect DNS requests to prevent DNS leaks. This means that configuring a custom DNS server address that needs to be routed through the tunnel doesn't work as expected. Until this is fixed server side, the app will show a dialog warning the user about the issue.
This PR implements that dialog. It uses the `MainActivity` class to synchronize the status between the fragments, which is not ideal, but this code should be removed when things are updated in the servers.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2343)

Warn if configured to use a public custom DNS server

---

CHANGELOG.md
talpid-core/src/dns/linux/systemd_resolved.rs

`systemd-resolved` has a new stub file path - `/usr/lib/systemd/resolv.conf`. But this one is non-dynamic, it should never be written to. Since `/etc/resolv.conf` can be symlinked to it, it's vulnerable to being overwritten by other software. This means that just checking if `/etc/resolv.conf` is symlinked to it is not enough, the contents have to be verified too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2353)

Add new systemd-resolved resolv.conf path

---

README.md

Not sure, but I think the iOS app handles "WireGuard" and "Optional local network access" as the Android app does.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2350)

Added iOS info

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt
android/src/main/kotlin/net/mullvad/talpid/CreateTunResult.kt
android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
android/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt
android/src/main/res/values/strings.xml
mullvad-jni/src/classes.rs
talpid-core/src/tunnel/tun_provider/android/mod.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-types/src/tunnel.rs

When specifying the DNS server addresses to use for the tunnel device, Android may throw an exception saying that the DNS server address is invalid. This has currently only been seen when using a localhost address (`127.0.0.1`), and the code for custom DNS already prevents using localhost addresses to avoid having issues. However, not only is it hard to be sure what the exact list of invalid DNS server addresses is, it is impossible to know if that list will change in future versions of Android. 
To prevent crashes from using an unexpected invalid custom DNS server address, this PR changes the tunnel creation code to handle that failure gracefully. If the invalid DNS server address exception is thrown, `TalpidVpnService` will still continue creating the tunnel, but it will return an error …

Handle DNS server addresses that Android consider invalid

---

gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/LinuxSplitTunnelingSettings.tsx
gui/src/renderer/components/NotificationArea.tsx
gui/src/renderer/containers/LoginPage.tsx
gui/src/renderer/containers/SettingsPage.tsx
gui/src/renderer/containers/SupportPage.tsx
gui/src/shared/ipc-event-channel.ts

This PR replaces the use of Electron API:s in the renderer process with IPC calls. The remaining use of `Electron.remote` is in the logging initialization which will need a lot more work when disabling `nodeIntegration`.
This is in preperation for the deprecation of the remote module and to get closer to being able to disable `nodeIntegration` and enable `contextIsolation` in the renderer process.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2347)

Remove use of remote module

---

CHANGELOG.md
talpid-core/src/tunnel/mod.rs
windows/winnet/src/winnet/routing/helpers.cpp

This PR fixes a couple of issues:
* The `TunnelMetadata` instance returned for OpenVPN tunnels does not include the IPv6 address in its `ips` field. This has long been the case, but it has never caused any issues because it was apparently only used in logging. Fixed because the split tunneling feature relies on this (on Windows).
* Unrelatedly, it also corrects the default route filter on Windows. `get_best_default_route` incorrectly returned the default route for the tunnel when the protocol was OpenVPN, since the switch to Wintun. Again, this doesn't fix anything in master, as the function is not used for OpenVPN there (and the WireGuard route is correctly identified because it has no gateway). But it is used on the split tunneling branch.
--- …

Fix tunnel metadata

---

Cargo.lock
talpid-core/Cargo.toml

In hopes of fixing issues with parsing newer resolv.conf options, I've updated the `resolv-conf` crate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2369)

Update to newer resolv-conf

---

CHANGELOG.md
gui/src/main/index.ts
gui/src/main/linux-desktop-entry.ts
gui/src/main/linux-split-tunneling.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/LinuxSplitTunnelingSettings.tsx
gui/src/shared/application-types.ts
gui/src/shared/ipc-event-channel.ts
gui/src/shared/linux-split-tunneling-application.ts

This PR adds an icon to `BrowserWindow` options to fix the missing icons on Xfce https://github.com/mullvad/mullvadvpn-app/issues/2363.
To use the correct icon the icon finding code from the Linux split tunneling app list is used which required some refactoring. The code related to desktop entries has been moved to it's own file and the application types have been split up into `IApplication` (which contains the basic information about an application), `ILinuxApplication` (linux specific properties from the `.desktop` file) and `ILinuxSplitTunnelingApplication` (added properties related to split tunneling).
The refactored parts include:
* linux-split-tunneling.ts:`shouldShowApplication` moved to linux-desktop-entry:`shouldShowApplication`
* linux-split-tunneling.ts:`replaceWithIconPath` …

Fix Xfce window icon

---

Cargo.lock
mullvad-daemon/Cargo.toml
mullvad-daemon/src/settings.rs
mullvad-paths/Cargo.toml
mullvad-paths/src/cache.rs
mullvad-paths/src/settings.rs
mullvad-problem-report/Cargo.toml
mullvad-problem-report/src/lib.rs

Since it is no longer being maintained: https://github.com/RustSec/advisory-db/blob/master/crates/dirs/RUSTSEC-2020-0053.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2372)

Migrate from deprecated dirs dependency

---

CHANGELOG.md
README.md
talpid-core/src/dns/windows/mod.rs

Support for custom DNS was included in the last beta release, and it involved some changes to how DNS is managed. This was because the interface metric was tied to DNS resolver preference in Windows 10, and this worked poorly with local resolvers.
This change caused problems for single-label names (e.g., NetBIOS names). If DNS resolution failed, it would not fall back on using LLMNR. Hence other hosts on a LAN were no longer being identified.
For whatever reason, the [least strict](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpnrpt/b5760f13-0a23-4e37-9253-ad12af60e8a6) setting must be used, i.e. "Always fall back to LLMNR and NetBIOS for any kind of name resolution error.". Otherwise, names do not resolve.
--- …

Fall back on LLMNR/NetBIOS name resolution

---

CHANGELOG.md
README.md
talpid-core/src/offline/linux.rs
talpid-core/src/offline/mod.rs

To improve offline detection on Linux and desktop in general, I've done two things:
- Add an environment variable to allow disabling the offline check entirely, leaving it in an open state. This could later be reworked to being a proper option.
- Change offline detection on Linux to query the routing table for a path to a public IPv4 address to infer connectivity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2377)

Rework offline detection on Linux

---

talpid-core/src/offline/linux.rs

To reduce false negatives in the offline monitor, the offline check should only take into account routes in the main routing table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2385)

Only inspect main table for offline check

---

README.md

The instructions for running the app on Windows (without using a service) are not up-to-date. One must launch a command prompt as the SYSTEM user, since the settings and cache cannot be not accessed otherwise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2379)

Update build instructions for Windows

---

CHANGELOG.md
README.md
dist-assets/pkg-scripts/preinstall
dist-assets/windows/installer.nsh
mullvad-daemon/src/lib.rs
mullvad-daemon/src/main.rs
mullvad-jni/src/lib.rs
mullvad-paths/src/cache.rs
mullvad-paths/src/lib.rs
mullvad-problem-report/src/lib.rs
mullvad-problem-report/src/main.rs
mullvad-setup/src/main.rs
windows/nsis-plugins/src/cleanup/cleaningops.cpp
windows/nsis-plugins/src/cleanup/cleaningops.h
windows/nsis-plugins/src/cleanup/cleanup.cpp
windows/nsis-plugins/src/cleanup/cleanup.def

The cache directory is currently found in `C:\Windows\System32\config\systemprofile\AppData\Local\Mullvad VPN`. This is a problem for the problem report tool, which needs to be able to obtain the API addresses, even if it is not run as the SYSTEM user (or even admin). For this reason, `api-ip-address.txt` is currently stored in a separate cache directory to which anyone has read access (but not write access). This PR consolidates the two cache directories into `C:\ProgramData\Mullvad VPN\cache`.
The above description is for Windows, but an analogous change had to be made for macOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2384)

Migrate cache files

---

talpid-core/src/process/openvpn.rs

Since our upgrade to OpenVPN 2.5 our `openvpn.log` has started out with:
```
2021-01-08 15:42:18 DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for cipher negotiations. Add 'AES-256-CBC' to --data-ciphers or change --cipher 'AES-256-CBC' to --data-ciphers-fallback 'AES-256-CBC' to silence this warning.
```
This PR fixes that.
I wanted to get rid of `--cipher AES-256-CBC` completely and only rely on `AES-256-GCM` since that's what we end up using anyway thanks to NCP. But this did not work. Our servers have `--cipher AES-256-CBC` specified, so if my `--cipher` or `--data-ciphers` did *not* contain CBC it failed with an error (unable to negotiate cipher) and if I did include it it did use …

Fix issue with --cipher argument

---

gui/src/main/index.ts

This PR disables the menubar in the Windows app. The menu should never be displayed but was possible to toggle by pressing `alt`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2393)

Remove menubar on Windows

---

dist-assets/pkg-scripts/preinstall

Fixes an issue where the daemon does not restore the correct target state after upgrading on macOS, if auto-connect is disabled and the target state is "secured". This is simply because `mullvad-setup prepare-restart` is run before the migration code (#2384), and `target-start-state.json` is not moved to the new cache directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2397)

Fix upgrade leak on macOS

---

gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/components/WireguardKeys.tsx

This PR enables buttons that perform API calls when the daemon blocks network traffic, since the daemon recently got support for this.
The changes are:
* Redeem voucher button in the account view and in the new account view is enabled
* The "Regenerate key" and "Verify key" buttons in the WireGuard key view is enabled
* Remove message in WireGuard key view saying that keys can't be managed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2403)

Enable GUI API calls when in the blocked state

---

README.md

Apps on the App Store can't be GPL licensed. Add a section clarifying that we release the *source code* as GPL-3. But that it's implicitly dual licensed and the binaries on the App Store are by definition licensed under Apple's EULA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2406)

Add license section about the iOS app

---

mullvad-platform-metadata/src/android.rs
mullvad-platform-metadata/src/linux.rs

This PR shortens the platform version value in the version check `M-Platform-Version` call on Linux and Android.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2407)

Shorten platform version header

---

CHANGELOG.md
mullvad-daemon/src/lib.rs

The daemon will fail to start if the target state cache cannot be read or parsed (as long as it exists). Obviously, it is safer to assume that the daemon should immediately connect if this is the case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2408)

Initialize target state to "secured" if the cache cannot be parsed

---

CHANGELOG.md
gui/src/main/gui-settings.ts
gui/src/main/index.ts

This PR changes the default value of the GUI auto-connect setting to `false` and respects the setting when logging in.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2409)

Respect auto-connect setting on login and change default value to false

---

CHANGELOG.md
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/version_check.rs
mullvad-jni/src/daemon_interface.rs

Makes a couple of simple changes:
* Instead of defaulting to incorrect information in the daemon when there is no cache, store an optional `AppVersionInfo`.
* If the daemon has no version info when it is requested by frontends, run the version check right away. If that fails, return a "not found" status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2405)

Improve version cache

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/DaemonInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt

@axti noticed that the `MullvadDaemon.finalize` method was incorrect, and therefore the daemon command sender endpoint was never closed correctly. Fixing the finalizer method is possible, but it leads to linter warnings.
This PR takes a different approach to fix the issue. Since the `MullvadDaemon` instance is only handled by the `DaemonInstance` actor, it can call the destructor once the daemon stops. Therefore, a new `onDestory` destructor method is created and called from `DaemonInstance`. This new destructor also cleans up all callbacks that were configured on the daemon.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2410)

Fix daemon cleanup on Android

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt

This is the first PR related to splitting the service into a separate process.
The first component that's being split is the `ConnectivityListener`. Since it's not used in the UI anymore it can be safely removed so that it's only referenced in the service side. This is what this PR does.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2411)

Remove `ConnectivityListener` reference from UI

---

gui/package-lock.json
gui/package.json

This PR updates NSEventMonitor to `1.0.0`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2413)

Update to NSEventMonitor 1.0.0

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
android/src/main/res/values-da/strings.xml
android/src/main/res/values-de/strings.xml
android/src/main/res/values-es/strings.xml
android/src/main/res/values-fi/strings.xml
android/src/main/res/values-fr/strings.xml
android/src/main/res/values-it/strings.xml
android/src/main/res/values-ja/strings.xml
android/src/main/res/values-ko/strings.xml
android/src/main/res/values-nb/strings.xml
android/src/main/res/values-nl/strings.xml
android/src/main/res/values-pl/strings.xml
android/src/main/res/values-pt/strings.xml
android/src/main/res/values-ru/strings.xml
android/src/main/res/values-sv/strings.xml
android/src/main/res/values-th/strings.xml
android/src/main/res/values-tr/strings.xml
android/src/main/res/values-zh-rCN/strings.xml
android/src/main/res/values-zh-rTW/strings.xml
android/src/main/res/values/strings.xml
ci/ci-android-xml.sh

Currently on Android, the UI components will disable buttons that interact with the API in blocked states. I've changed the respective components to instead only disable said buttons if the device is offline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2415)

Allow API calls in blocked state.

---

dist-assets/linux/mullvad-gui-launcher.sh
gui/src/main/index.ts

This PR enables the Chromium sandbox for the Electron renderer process on Linux when possible. There's still one situation when it's disabled which is when the `unprivileged_userns_clone` Debian kernel patch is enabled.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2419)

Enable Electron sandbox on Linux when possible

---

mullvad-cli/src/cmds/account.rs
mullvad-cli/src/cmds/bridge.rs
mullvad-cli/src/cmds/relay.rs
mullvad-cli/src/cmds/reset.rs
mullvad-cli/src/cmds/status.rs
mullvad-cli/src/cmds/tunnel.rs
mullvad-cli/src/cmds/version.rs
mullvad-cli/src/main.rs
mullvad-cli/src/state.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-jni/src/daemon_interface.rs

Main changes:
* Return errors from `mullvad-daemon` commands whenever it makes sense. Currently, channels are usually dropped whenever an error occurs, so there is no way to tell what went wrong. A lot of cases are then simply mapped to "internal error" in gRPC.
* In the CLI, state the RPC that failed when more than one thing can go wrong. E.g., show "failed to fetch account data" instead of only some REST error.
* Improve presentation in CLI. The implementation of `Display` returns an unfriendly string for tonic statuses, and some messages are misleading or incorrect. (E.g., "Failed to communicate with mullvad-daemon over RPC" may be shown when the gRPC server returns an error.)
For example, this was shown when `mullvad account get` is run and the API cannot be reached:
```
mullvad …
```

Improve error handling in IPC and CLI

---

CHANGELOG.md
mullvad-cli/src/main.rs
mullvad-daemon/src/lib.rs

MacOS get's very confused if we clear the DNS config and this makes the daemon confused, and all this confusion ends up with misery - the daemon gets stuck in the error state due to it detecting an offline state. Since it doesn't make much sense to apply an empty list of DNS servers, we can just not apply the custom DNS config if there are no servers in it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2427)

Only apply custom dns config if it's not empty

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/cell/Input.tsx

This PR changes the behavior of the custom DNS toggle. Previously enabled it in the daemon when the toggle became enabled, with an empty list of IPs. Now it keeps the toggle state internally and enables the setting in the daemon when the first IP is added to avoid using the feature with an empty list of IPs.
This PR also adds a placeholder to the custom DNS IP input that was previously missing.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2429)

Enable custom DNS when first IP is added instead of when toggled

---

talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs

wintun.dll is not [intended](https://git.zx2c4.com/wintun/commit/?id=7710ff187b5079d9f2573608b6cb33b15262b2b8) to be loaded and freed more than once by a given process, something that is currently done by `OpenVpnMonitor`. Creating a Wintun adapter can (rarely) fail due to `ERROR_FILE_NOT_FOUND`, which may be related to this, though this hasn't been verified. Regardless, this change lazily loads wintun.dll to ensure that it isn't incorrectly re-initialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2428)

Only unload Wintun when the daemon is stopped

---

CHANGELOG.md
mullvad-daemon/src/wireguard.rs

Ideally, it would be best to rotate the WireGuard key as much as possible in order to increase privacy. However, the more frequent the rotation occurs, the more likely the user will experience "connection hiccups" while the tunnel reconnects with a new key. On desktop, it was decided to keep the interval at once a week. However, on mobile this interval was decided to be reduced to once every four days.
This PR applies the new interval for Android. Since the Android code for the key rotation is the same code used by the desktop app, the constant for the default interval was split in two, one for Android and one for the other platforms. I also separated that constant from the rest with a new-line to emphasis that the two constant declarations refer to the same parameter, in an attempt to …

Rotate WireGuard key more frequently on Android

---

mullvad-daemon/src/wireguard.rs

A previous PR (#2432) reduced the default WireGuard key rotation interval on Android from 7 days to 4 days. This PR refactors that code to remove the repeated documentation attribute and the repeated variable name so that the code is easier to read and more resilient to the possibility of mistakes in the future.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2434)

Improve rotation interval constant declaration

---

gui/src/main/index.ts
gui/src/main/linux-desktop-entry.ts
gui/src/main/linux-split-tunneling.ts

This PR changes the window icon on Linux to use a path instead of a data URL. The function returning the image was changed to returning the data URL instead of the path since the path isn't usable in the now sandboxed renderer process. But for the window icon a path is more suitable since it's not running within the sandbox and with the data URL the image wasn't displayed and also causes a segmentation fault in Electron 11.2.0+.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2433)

Use path for app icon instead of data url

---

gui/gulpfile.js
gui/package.json
gui/tasks/distribution.js

This PR:
* Makes sure the renaming of `mullvad-vpn` to `mullvad-gui` and `mullvad-gui-launcher.sh` to `mullvad-gui` is done in sequence. I ran into this and realized that both `mullvad-gui` and `mullvad-vpn` had the contents of `mullvad-gui-launcher`.
* Removes the `rimraf` dependency and instead uses `fs.rmdir` with the `{ recursive: true }` option.
* Keeps the `chrome-sandbox` file. The sandbox seemed to work without it as well though.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2435)

Fix Linux bulid process race condition and cleanup

---

talpid-platform-metadata/src/windows.rs

I've changed windows version check to report the minor NT version alongside the major one, so we can properly discriminate against Windows 7, 8 and 8.1, and made those specific versions be pretty-printed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2437)

Windows: Add minor version to version check header

---

gui/src/renderer/components/Modal.tsx

This PR fixes a few issues with modals that are shown immediately when a view is loaded. The issues that have been fixed are:
* Throws an error. This was caused by the switch to using a ref instead of an id for the container element. This has been fixed by reverting that change. The error has also been replaced by a log message since it shouldn't break the whole app.
* The transition was omitted when `focus()` was called on the modal after a timeout. There are two possibilities, wait until after the transition or remove the timeout entirely. The second one has caused us trouble in the past but seems to be working well with the current solution and setup. I went with the second one.
These issues only affected modals that were shown immediately when a view was loaded and the only case of …

Fix crash when displaying modal immediately when a view is loaded

---

android/src/main/res/layout/account.xml

The WireGuard Key screen and the Account screen are very similar, but there is one inconsistency: the position of the buttons. This PR updates the Account screen to move the buttons down so that it has the same appearance as the WireGuard Key screen.
To push the buttons down, the same approach used in the WireGuard Key screen was used. A spacing view was added between the top information and the bottom buttons. The spacer is the only view inside the `LinearLayout` group that has a weight, so its height is calculated to be the maximum possible, pushing the buttons down. To make sure the `ScrollView` containing the `LinearLayout` fills the whole screen, it has been updated to have the `fillViewport` attribute enabled.
Git checklist:
--- …

Move down buttons in the Account screen on Android

---

gui/src/config.json
gui/src/main/index.ts
gui/src/renderer/components/Settings.tsx
gui/src/renderer/components/Support.tsx
gui/src/renderer/containers/SettingsPage.tsx
gui/src/renderer/containers/SupportPage.tsx
gui/src/renderer/redux/version/reducers.ts
gui/src/shared/daemon-rpc-types.ts
gui/src/shared/notifications/unsupported-version.ts
gui/src/shared/notifications/update-available.ts

This PR adds `#beta` to the download URL if the suggested upgrade version is a beta version. This ensures that the correct part of the download page is shown when opened in a browser.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2442)

Open correct part of download page when running a beta version

---

CHANGELOG.md
mullvad-cli/src/cmds/bridge.rs
mullvad-cli/src/cmds/relay.rs
mullvad-cli/src/location.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-types/src/relay_constraints.rs

#2018 added provider relay and bridge constraints, but these only allowed you to specify a single provider. This PR updates it so that one out of multiple providers may be selected.
Usage:
```
mullvad relay set provider any
mullvad relay set provider 31173 M247
mullvad bridge set provider M247
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2446)

Add multiple providers constraint

---

gui/package-lock.json
gui/package.json

This PR updates TypeScript from 4.1.2 to 4.1.4.
Changelogs:
https://github.com/microsoft/TypeScript/releases/tag/v4.1.3
https://github.com/microsoft/TypeScript/releases/tag/v4.1.4
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2450)

Update to TypeScript 4.1.4

---

CHANGELOG.md
mullvad-daemon/src/lib.rs
mullvad-daemon/src/version_check.rs

This PR updates the value of `suggested_upgrade` and emits it to clients when `set_show_beta_releases` is called. This fixes the issue where the GUI doesn't show/hide the notification telling the user to upgrade after the beta program toggle has been changed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2447)

Update suggested upgrade version when enabling/disabling beta program

---

Cargo.lock
talpid-core/Cargo.toml
talpid-core/src/future_retry.rs

This updates `quickcheck` and `quickcheck-macros` to 1.0. Unfortunately, it looks like `quickcheck::Gen` is now very limited, exposing only a `choose(slice)` method, so the provided PRNG cannot be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2455)

Upgrade quickcheck dependencies

---

mullvad-cli/src/cmds/bridge.rs
mullvad-types/src/settings/mod.rs
mullvad-types/src/wireguard.rs
talpid-types/src/net/proxy.rs

Rust nightly builds fail:
> warning: derive helper attribute is used before it is introduced
The PR fixes these and some warnings about panic string types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2456)

Fix Rust nightly issues

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/DaemonInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/Intermittent.kt
android/src/main/kotlin/net/mullvad/talpid/util/EventNotifier.kt

There are certain parts of the app that can only work if a daemon instance is available. Most of the time there will be an instance available, but there are situations where it's not available:
- When the service (and/or the daemon) is still starting
- When the daemon has crashed and is restarting
- When the service was requested to stop but then requested to start shortly afterwards, so it must perform a "soft restart"
Previously, the code that depended on the daemon instance availability would operate through callbacks, so that they can correctly handle the events of an instance becoming available or unavailable. This added complexity to the code, which is exacerbated by the refactor to split the app in two processes.
This PR attempts to collect that complexity into a single helper …

Implement Intermittent daemon

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AppVersionCell.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/Cell.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/MtuCell.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/UrlButton.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/UrlCell.kt
android/src/main/res/layout/settings.xml
android/src/main/res/values-da/strings.xml
android/src/main/res/values-de/strings.xml
android/src/main/res/values-es/strings.xml
android/src/main/res/values-fi/strings.xml
android/src/main/res/values-fr/strings.xml
android/src/main/res/values-it/strings.xml
android/src/main/res/values-ja/strings.xml
android/src/main/res/values-ko/strings.xml
android/src/main/res/values-nb/strings.xml
android/src/main/res/values-nl/strings.xml
android/src/main/res/values-pl/strings.xml
android/src/main/res/values-pt/strings.xml
android/src/main/res/values-ru/strings.xml
android/src/main/res/values-sv/strings.xml
android/src/main/res/values-th/strings.xml
android/src/main/res/values-tr/strings.xml
android/src/main/res/values-zh-rCN/strings.xml
android/src/main/res/values-zh-rTW/strings.xml
android/src/main/res/values/attrs.xml
android/src/main/res/values/strings.xml

The desktop app has an entry in the Settings page called "FAQs & Guides" that when pressed opens the browser on the help page for the app. This PR adds the same entry to the Android app.
To implement the new settings entry, a new `UrlCell` widget was created. It's based off the `AppVersionCell` widget, which also opens an external link when tapped. The new widget supports configuring the target URL through a style attribute.
As part of the PR, the `AppVersionCell` widget was refactored to sub-class the new `UrlCell` widget in order to reduce the repeated code.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2445)

Add FAQs and Guides entry in the Settings screen on Android

---

gui/src/renderer/components/NavigationBarStyles.tsx

This PR removes the `z-index` property on the navigation bar back button which was previously required due to some invisible element, used for measuring the title placement, being placed in front. I have a vague memory of fixing this in some other way at a later time and after removing the `z-index` property everything seems to work as expected.
The `z-index` property caused the button to be places on top of the modal background making it fully visible and clickable while a modal was showing.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2454)

Remove z-index property on navigation bar back button

---

CHANGELOG.md
gui/src/renderer/components/AdvancedSettings.tsx

This PR adds 51820 to the list of WireGuard ports.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2451)

Add WireGuard default port (51820) to list of ports

---

ios/CHANGELOG.md
ios/MullvadVPN/AccountTokenInput.swift

Git checklist:
This PR fixes a crash that may occur when pasting an empty string into empty account input field. The reason for that is that `String.prefix(through:)` picks the characters up to _and_ including the character at the given index, so the following just does not work:
```
var s = ""
s.prefix(through: s.startIndex) // Index is out of bounds
```
This PR addresses this by guarding against empty string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2459)

Fix crash when pasting empty string into account token input

---

CHANGELOG.md
talpid-core/src/routing/mod.rs
talpid-core/src/tunnel/openvpn/mod.rs

The OpenVPN event callback would panic when it fails to add an IPv6 route on machines that don't support IPv6. This is because the generic option for enabling IPv6 is not taken into account, and seemingly a considerable amount of users disable IPv6 in their kernels for _reasons_. As such, I've changed the callback to take the option into account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2471)

Stop applying IPv6 routes for OpenVPN

---

.github/workflows/android-app.yml
.github/workflows/android-ktlint.yml
.github/workflows/android-xml-tidy.yml
.travis.yml
wireguard/libwg/build-android.sh

This PR is based on some initial experimentation with GitHub Actions. I've managed to create three workflows that are roughly equivalent to the previous Travis CI job. I configured them so that they only run when Android relevant files change, so they should only be triggered when it's appropriate.
I'm still learning things, so we can probably tweak this a lot, but hopefully it's good enough to start migrating from Travis.
For building WireGuard-Go for Android, I tweaked the build script a bit so that the architectures to build for can be configured through an environment variable so that we don't waste time building for more than one architecture on CI.
Git checklist:
--- …

Migrate Android CI from Travis CI to GitHub Actions workflows 

---

CHANGELOG.md
mullvad-daemon/src/relays.rs
mullvad-rpc/src/bin/relay_list.rs
mullvad-rpc/src/lib.rs
mullvad-rpc/src/relay_list.rs
mullvad-rpc/src/rest.rs
mullvad-types/src/relay_list.rs

The relay list endpoint (https://api.mullvad.net/v1/relays) will soonish include ETags in its responses. Setting the `If-None-Match` header to this value allows the server to respond with 304 instead of sending back the entire unmodified list (saving ~0.166 MB per hour).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2462)

Only update the relay list if it has changed

---

android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/DispatchingHandler.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Message.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceAwareFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt

This PR creates the packages and classes that serve as the base for the IPC channel for communication between the UI and service once they become separate processes. To serialize and deserialize classes through the channel, they are converted to `Parcel`s using the Parcelize plugin. Two types of Parcels are implemented in this PR, an `Event` class for sending events from the service to the UI and a `Request` for sending requests from the UI to the service.
The only request that can be made is to register an event listener, and the only event that is currently sent is to notify that the listener was successfully registered. A `DispatchingHandler` helper class extends the Android message `Handler` class and servers as the incoming message dispatcher. Listeners can register handlers for …

Prepare Andorid IPC channel between UI and service

---

talpid-platform-metadata/src/macos.rs

Reporting the patch in the version of macOS in the version check is proving to be too granular, so I've changed the version check code to only report the full version in problem reports and only use the major and minor versions in the version check header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2479)

MacOS - Drop the patch from the short version

---

rustfmt.toml

As of some days ago, the nightly toolchain's `rustfmt` has been complaining about deprecating `merge_imports` in favor of the more versatile `imports_granularity` config option. So I went ahead and changed over to the new config option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2482)

Update rustfmt config

---

talpid-core/src/tunnel/wireguard/mod.rs

The daemon wasn't logging about falling back to WireGuard-go on Linux due to a typo of yours truly. This is a fix for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2483)

Fix log entry signaling use of wireguard-go

---

CHANGELOG.md
talpid-core/src/routing/linux.rs
talpid-core/src/routing/unix.rs
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/wireguard/config.rs
talpid-core/src/tunnel/wireguard/mod.rs

The route manager adds IPv6 routing rules even if IPv6 is disabled. On some machines, this fails spectacularly. As such, I've changed the code so IPv6 rules are only added if the user has enabled IPv6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2478)

Linux - only apply IPv6 routing rules when IPv6 is enabled.

---

CHANGELOG.md
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/wireguard_go.rs
windows/libshared/src/libshared/network/interfaceutils.cpp
wireguard/libwg/interfacewatcher/interfacewatcher_windows.go
wireguard/libwg/libwg.go
wireguard/libwg/libwg_android.go
wireguard/libwg/libwg_default.go
wireguard/libwg/libwg_windows.go
wireguard/libwg/logging/logging.go

Currently, if a non-Wintun device has an alias that conflicts with ours, starting the tunnel fails with `ERROR_ALREADY_EXISTS`. These changes make sure that whatever alias is assigned to the adapter is used instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2476)

Do not fail if Wintun adapter is assigned a different alias

---

mullvad-problem-report/src/lib.rs

Since the address cache calls `tokio::task::block_in_place` in a number of places in `mullvad-rpc`, we should be using a mutli-threaded runtime in the problem report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2484)

Use threaded scheduler in problem report

---

CHANGELOG.md
mullvad-rpc/src/https_client_with_sni.rs

Force rustls to only use TLS 1.3 when connecting to our API. 
For OpenVPN, we specify specific cyphersuits that we believe are not weak, should we do the same here?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2485)

Use only TLS 1.3 when connecting to the API

---

mullvad-types/src/relay_list.rs

A previous PR (#2462) added a new field to the `RelayList` type in order to only download the relay list if it hasn't changed. Unfortunately, the Android app doesn't use the new field, so the conversion from the Rust type to the Java type started failing. This PR marks the new field as to be ignored during the conversion.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2488)

Ignore new field in `RelayList` for JNI conversion

---

Cargo.lock
android/src/main/kotlin/net/mullvad/mullvadvpn/model/Constraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/GetAccountDataResult.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/KeygenEvent.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettings.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettingsUpdate.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/TunnelState.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/KeyStatusListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/LocationInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectActionButton.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LocationInfo.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/SwitchLocationButton.kt
android/src/main/kotlin/net/mullvad/talpid/CreateTunResult.kt
android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
android/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt
mullvad-jni/Cargo.toml
mullvad-types/Cargo.toml
talpid-core/Cargo.toml
talpid-types/Cargo.toml

This PR updates the `jnix` crate dependency to version `0.4`. This is needed for future PRs related to running the Android service in a separate process, because some types that can be converted between Rust and Java will have to implement `Parcelable`, so the type erasure that happens behind the scenes requires different type bounds. The new version of `jnix` allow specifying the bounds to be used for type erasure.
The new version of `jnix` also changes a few things about conversions, so this PR also updates that. Namely, `getN` methods are no longer necessary as long as the class is a Kotlin `data class` and Rust unit variants of enums are now mapped to singleton Java objects in a few cases.
A minor tweak was also included, changing the `KeygenFailure` type to be an `enum class` instead …

Update `jnix` dependency to version 0.4

---

talpid-core/Cargo.toml
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs

The previous code should not have caused any serious issues, except in the case where the requested GUID was not used, and the "ComponentId" workaround (#2338) happened to be needed. In that case, the workaround would have failed. Mostly, it filled the log with pointless error messages.
Other changes:
* Add `WintunAdapter::guid()`.
* Add `WintunAdapter::luid()`.
* Unit test for GUID to string conversion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2490)

Make sure the actual GUID is used for the ComponentId fix

---

gui/package.json
gui/src/main/logging.ts
gui/src/shared/logging.ts
gui/test/ip.spec.ts
gui/test/logging.spec.ts

This PR:
* Changes the frontend log file names to `frontend-main.log` and `frontend-renderer.log`
* Adds `main.log` and `renderer.log` for clean up
* Adds serialization for non-string values when sent to logger
* Adds test for serialization
* Adds test for log-level filtering
* Renames the test group for the IP tests which was forgotten while copy-pasting it
* Removes `nseventmonitor` from `dependencies` again since it was added again when doing the `2021.2` release.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2494)

Improve logger

---

dist-assets/windows/installer.nsh

The "you may need to restart your computer" message was pretty ambiguous, as rebooting is actually required. Simply setting the reboot flag gives users the option to reboot before the installer exits:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2499)

Give Windows 7 users the option to restart

---

CHANGELOG.md
talpid-core/src/tunnel_state_machine/disconnecting_state.rs

When `ConnectingState::enter` immediately fails and enters the disconnecting state, it sometimes passes a terminated (tunnel close event) future to `DisconnectingState::enter`. In `DisconnectingState::handle_event`, the "after-connect" action is immediately taken if the future is terminated, so as to not block until a command is sent.
The problem arises when the after-connect action is to reconnect, and the connecting state keeps failing in the same manner. The tunnel state machine becomes unresponsive to commands until the loop is broken. This can be verified by always returning `Err(RecoverableStartWireguardError);` from `WireguardMonitor::start`.
--- …

Fix unresponsive disconnecting state

---

dist-assets/windows/installer.nsh
windows/driverlogic/src/driverlogic.cpp

`WintunCreateAdapter` fails if the `requestedGuid` argument is in use by another network device that belongs to a different Wintun pool or is not a Wintun device at all. This can be verified by creating a Wintun interface in some pool other than `Mullvad` (e.g., using `driverlogic wintun create-adapter test test {AFE43773-E1F8-4EBB-8536-576AB86AFE9A}`) before running `mullvad connect`. This occurs using both wireguard-go and OpenVPN.
In practice, this would have occurred when older versions of the service created a Wintun adapter via wireguard-go and failed to clean up after themselves (e.g. if the daemon was suddenly killed). After upgrading, this adapter would be assigned the same GUID as our new adapter but belong to a different pool.
Previously, this had to be fixed by manually …

Remove any network device with a conflicting GUID

---

ios/CHANGELOG.md
ios/MullvadVPN/ConnectViewController.xib

Git checklist:
It looks like when using a custom _named_ color in XIB interfaces files, the label color is applied after the `viewDidLoad()` but only on iOS 12.
The comical fix is to use any standard color (i.e white) in interface files. Since we override the color in code, it doesn't really matter what color is set in interface builder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2517)

Fix invalid unsecured label color

---

android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/BaseFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt

This PR will help to keep track on enter transition animation. We will use it to present data and colouring StatusBar when fragments are changed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2516)

Add transition animation listener for enter

---

gui/src/config.json

This PR changes the download-url for beta versions from `https://mullvad.net/download/#beta` to `https://mullvad.net/download/beta`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2512)

Change beta update link

---

gui/src/renderer/components/NotificationArea.tsx

This PR changes the priority of the "Update available" notification banner to lower the "Account will soon expire" one.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2511)

Lower priority of update available notification banner

---

CHANGELOG.md
Cargo.lock
mullvad-cli/Cargo.toml
mullvad-cli/src/cmds/relay.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-types/src/relay_constraints.rs
talpid-types/src/net/mod.rs

This adds a relay constraint for connecting to relays over IPv6. It can be enabled in the CLI:
```
mullvad relay set tunnel wireguard --ipv 6
```
If the constraint is set to either `4` or `Any`, then the relay selector will always prefer the IPv4 address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2422)

Add IP version constraint for WireGuard

---

CHANGELOG.md
talpid-core/src/routing/windows.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/winnet.rs
windows/winnet/src/winnet/routing/routemanager.cpp
windows/winnet/src/winnet/routing/routemanager.h
windows/winnet/src/winnet/winnet.cpp
windows/winnet/src/winnet/winnet.h

Previously, if there was no default route, the daemon would transition to the error state and keep blocking even if such a route was later added. This might have occurred if the offline monitor reported the offline state too late (after attempting to connect), inaccurately reported "connected", or was disabled using `TALPID_DISABLE_OFFLINE_MONITOR=1`.
These changes cause the daemon to retry if the tunnel cannot be created because there's no default route.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2514)

Retry if creating a WG tunnel fails because there is no default route (Windows)

---

ios/CHANGELOG.md

As far as I know the problem report has been merged. But it was not in the changelog. Is this addition correct?
And minor nitpick cleanup: two empty lines between releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2523)

Add iOS changelog entry about problem reports

---

CHANGELOG.md
talpid-core/src/dns/linux/network_manager.rs
talpid-dbus/src/network_manager.rs
talpid-platform-metadata/src/linux.rs

As of 1.28, NM won't manage DNS for devices that it doesn't wholly manage when it manages DNS via `/etc/resolv.conf`. Of course, the daemon won't be able to notice this, so we cannot rely on newer versions of NM to manage DNS for us. So I've changed NM code to not manage DNS or create WireGuard devices if it's too new.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2524)

Stop using NM if it's too new

---

android/translations-converter/src/android.rs

A previous PR (#2449) improved string escaping when converting the translation strings for the desktop into translations strings for the Android app. However, it unfortunately included a small mistake where XML escaping was inverted. This PR fixes that.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2525)

Fix XML escaping in translations converter

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/MullvadVPN-Bridging-Header.h
ios/PacketTunnel/PacketTunnel-Bridging-Header.h
ios/build-wireguard-go.sh

Git checklist:
1. Removes Objective-C bridging headers and disable precompiled headers
2. Remove "Extract wireguard-go Version" build phase since we don't use it
3. Add custom build script for wireguard-go that detects the `SourcesPackages` directory where Swift Package Manager clones git repositories of third party dependencies. It turned out that when archiving the iOS app for distribution, the file structure looks very different from a regular Debug build which resulted in invalid path being passed to `/usr/bin/make` when building wireguard-go.
--- …

Fix ios build

---

CHANGELOG.md
Cargo.lock
talpid-core/src/dns/linux/mod.rs
talpid-core/src/dns/linux/systemd_resolved.rs
talpid-dbus/Cargo.toml
talpid-dbus/src/lib.rs
talpid-dbus/src/network_manager.rs
talpid-dbus/src/systemd_resolved.rs

Certain NM versions will overwrite systemd-resovled config when they're
reapplying existing config, this can be invoked 
`nmcli general reload dns-full`  or by receiving a new DHCP lease. NM will 
just wipe the config for interfaces it doesn't have the config for in
systemd-resolved, and since our daemon prefers systemd-resolved over NM, 
our config would be wiped. To fix this, I've changed the systemd-resolved DNS
code to listen to changes to the global DNS config and reapply the tunnel interface 
DNS config if it's changed in any way.
To better seperate the conecrns, the systemd-resolved DBus specific code
was moved to the `talpid-dbus` crate, and the DNS code that manages the
state and applies changes remains in `talpid-core`.
One other solution that was considered was to just prefer …

Watch DNS config changes in systemd-resolved

---

CHANGELOG.md
gui/locales/my/relay-locations.po
gui/src/renderer/app.tsx

This PR adds Burmese to the list of available languages and adds the corresponding directory `gui/locales/my`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2528)

Add Burmese as option in language picker

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/InAppNotificationController.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/StatusLevel.kt

Previously, the app would only consider the registration order when deciding which in-app notification to show. This led to a situation where an "Update available" message would have a higher priority than "Account expires in 1 day" message. It's desirable to have the account expiration message have a higher priority than the update warning.
This PR changes the logic to prioritize `StatusLevel.Error` messages over `StatusLevel.Warning` messages. Currently, the only notification that has `StatusLevel.Warning` is the update available message. This change also ensures any future warnings will have a lower priority than the error messages.
The way the prioritization was initially implemented was by having an `ArrayList` of registered notifications, and the lower the index of a notification …

Change in-app banner notification prioritization

---

gui/src/main/logging.ts

The last PR modifying the file names for the frontend logging was missing `frontend.log` in the list of files to clean up.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2530)

Add frontend.log to log file cleanup

---

README.md

A small addition to #2500: Go 1.13.6, mentioned in [All platforms](https://github.com/mullvad/mullvadvpn-app#all-platforms), will not work on Apple Silicon. 1.16 is the first version to add Apple Silicon support.
This slipped my attention in the original PR, sorry for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2520)

Add Go version requirement for Apple Silicon

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt

A recent PR (#2415) improved the way the app accesses the API server, allowing it to be reached even when the app is in the blocked state. As part of the PR, the name of a field was changed in a way that inverted its semantics, but one of the usages still considered the old semantics. More specifically, the field was previously `hasConnectivity`, and the "Manage Keys" button was enabled using the value of that field. When the PR was merged, the field changed to `isOffline`, but the code to update the "Manage Keys" button still used the value directly.
This PR fixes that by using the correct semantics.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/25 …

Fix "Manage Keys" button in the WireGuard Key screen always being disabled

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt

Previously, it was possible for the account input area to disappear from the Login screen sometimes. This could be reproduced by logging out, pressing back on the login screen to leave the app, and then opening the app again. The cause of the issue was that the custom animation code would reset the height of the account input area to a calculated `collapsedHeight` value. That value was only calculated after a layout change, and when recreating the widget there would be no layout change so the listener wouldn't get called, meaning the value stayed at zero.
This PR fixes that by forcing the initial value to be always calculated during initialization, and updated on layout changes. The PR also changes stopping the animation by using `cancel()` instead of `end()` to prevent the animation from …

Fix login input area disappearing sometimes

---

CHANGELOG.md
talpid-core/src/firewall/linux.rs

When the daemon runs on a system that attempts to do strict reverse path filtering, incoming relay traffic would be filtered out, leaving the user without a working connection, because the daemon would never receive the tunnel traffic, leaving it in a reconnection loop. This is because on Linux, we use policy based routing, and an incoming TCP or UDP packet does not have the necessary context at the filtering stage to determine if a response to said packet would be routed through the same interface. To fix this, I've added a new chain to our main table that will apply the correct firewall mark to the relay traffic so that it would still work.
--- …

Add rules to allow relay traffic through reverse path filtering on Linux.

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt
android/src/main/res/layout/account_login.xml
android/src/main/res/values/dimensions.xml

A previous PR (#2534) included a fix for the account input area sometimes disappearing from the Login screen. Unfortunately, the implementation wasn't correct. It was calculating the initial value using the configured height instead of the measured height. It worked with my internal testing because my debug build included some extra code that ended up not calling the `updateHeight` when it new that the height was zero, so that was what actually "fixed" the issue during testing.
After more research, I realized that using the measured height yielded bad aesthetics (because the measured height is the minimum height, and the actual height was configured by the container through `LayoutParams`). I also realized that the container was setting a fixed value `48dp` for the height, so there was …

Really fix disappearing account login input

---

android/src/main/AndroidManifest.xml

A recent PR improved support for Android TV (#2480). As part of the improvement, a new activity was created. The activity's declaration in the manifest is almost the same as the previous activity. Unfortunately, that led to a conflict where there were two intent-filters for the quick-settings tile long press intent. This caused long pressing the quick-settings tile to not work on recent Android versions.
This PR fixes that by removing the intent filter from the TV-specific activity. It will still be good to verify later if TVs have quick-settings tiles and if so what would be the best way to handle that. For now, this solution only fixes the problem on non-TV devices.
Git checklist:
--- …

Fix long press on quick-settings tile

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/main.rs

The daemon can fail to start if a subsequently started daemon didn't clean up it's RPC socket. So I've changed the startup code and shutdown code to remove the RPC socket. This is not done on Windows because it's not actually possible to remove a named pipe AFAICT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2540)

Remove old IPC socket during shutdown and startup of the daemon

---

CHANGELOG.md
mullvad-daemon/src/account_history.rs

Lower account history from 3 accounts to 1. This will result in people losing account entries in their account history once they log in with a new account again - the only entry left will be the one they log in to again. I've tested this and it just works on Linux. I'll try out what happens on Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2547)

Lower account history from 3 to 1 entry

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/main.rs

In a recent change to the daemon, I added logic to remove the IPC socket after the daemon has stopped and before it starts. This shouldn't be done on Android, because there is no IPC socket on Android. Thus the code has been changed to not do that on Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2546)

Ignore IPC socket on Android

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt

Previous PRs (#2534, #2538) fixed an issue where the account input area would sometimes disappear. Part of the fix involved changing the initial value used for the account login widget height. When I tested the fix, I only tested with the account history having at least one entry. I didn't realize that having an empty account history could lead to an issue.
Unfortunately, there was an issue when the account history was empty. The account history collapse-expand animation was initialized with zero source and target values, but they were updated when the account history was set. If it wasn't set, the values would stay zero, which meant that as soon as an animation condition started the animation, the login input area would disappear because its height would be set to zero.
This PR fixes …

Fix disappearing account input when account history is empty

---

CHANGELOG.md
README.md
talpid-core/src/firewall/linux.rs
talpid-core/src/linux/mod.rs

Some users will have enabled strict reverse path filtering in the kernel. To ensure that the daemon still works, we should set `sysctl net.ipv4.conf.all.src_valid_mark=1` when we connect to allow our traffic to pass through the filter. Now the linux firewall module will do that every time it's applying a connecting policy. This kernel config option will never be reverted by our code. The users can disable this behavior by setting `TALPID_FIREWALL_DONT_SET_SRC_VALID_MARK` environment variable to a non-zero value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2548)

Make the kernel take the firewall mark into account when doing RPF.

---

gui/package-lock.json
gui/package.json

This PR downgrades `grpc-js` to the version we used before https://github.com/mullvad/mullvadvpn-app/pull/2472. This is due to it not being possible to catch the `cancelled` exception which is thrown when the daemon is stopped. I will look into fixing this but for now we're better off with this version.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2552)

Downgrade grpc-js to 1.1.2

---

talpid-core/src/tunnel/openvpn/mod.rs
talpid-openvpn-plugin/src/lib.rs

The `OpenVPN event {:?}` log has two problems:
1) It's outputting debug formatting on a log level lower than DEBUG. We should not do this unless well motivated.
2) It's a very very verbose log line and as far as I know we never use/read this line for debugging.
So I moved it to TRACE to get rid of it from problem reports.
I also noticed on a Windows log the following line:
```
[talpid_core::tunnel::openvpn][DEBUG] Ignoring OpenVpnEvent Up
```
And I was confused for a while. But I then realized we use `RouteUp` to detect the tunnel up stuff. `Up` is Linux specific but has been registered as an interesting event on all platforms anyway back in #2106 .
--- …

Reduce superfluous openvpn logging

---

.travis.yml
Dockerfile
README.md

Bump go to 1.16 in the readme and CI (.travis.yml, GitHub Actions, and quay.io). The container used to build wireguard-go for Android (in `wireguard/build-wireguard-go.sh`) is not yet updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2539)

Upgrade go to 1.16

---

gui/src/main/index.ts
gui/src/main/window-controller.ts
gui/src/shared/ipc-helpers.ts

This PR changes `windowController.window` and `windowController.webContents` to return `undefined` if the window/webContents have been destroyed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2553)

Don't perform actions on a destroyed window

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsAdapter.kt

Previously, the Advanced screen would break the back button behavior after enabling and disabling custom DNS (while having no custom DNS servers configured). The back button is overridden in order to cancel editing the custom DNS server address. The bug happens because disabling custom DNS does not mark internally that editing has stopped, so the back button handler still thinks it should try to stop editing.
This PR fixes that by marking the editing position as `null` when custom DNS is disabled.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2560)

Clear editing position when disabling custom DNS

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/EditCustomDnsServerHolder.kt

Previously, pressing the "Done" key in the software keyboard while editing a custom DNS server address, it hides the keyboard but doesn't save the custom DNS address. This PR adds a listener for the "editor action" in order to save the DNS server address.
The listener returns `false` (as if the event wasn't handled) to allow the normal behavior (hiding the keyboard) to still work.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2556)

Save DNS server address on Enter key

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/EditCustomDnsServerHolder.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountInput.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/EditTextExt.kt

Previously, in order to log in the user had to type the account number and then press the green button next to the input area. This PR improves the user experience by allowing them to use the keyboard's enter key to log in.
Since this PR does something similar to PR #2560, an extension was implemented to contain the common code.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2563)

Log in after pressing the enter key when typing the account number

---

.github/workflows/daemon.yml
.github/workflows/rustfmt.yml
ci/check-rust.sh

We're planning on slowly migrating our CI from Travis to GitHub Actions. This PR adds workflows that are equivalent to the Rust jobs we have on Travis, with the small difference that the Rust formatting check is done in a separate workflow so that it runs separately in parallel.
The Travis job was not removed yet, because we will have some time with both CI jobs running for a while so that we can check for any inconsistencies.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2559)

Create GitHub Actions workflows for the Rust code

---

CHANGELOG.md
gui/src/renderer/app.tsx

This PR handles a race condition caused by the daemon stopping during the startup of the app. If the main process finishes fetching the account data before the daemon stops and the deamon stops before the initialization is done, the GUI will navigate to `/connect`. This PR ensures that the app is still connected to the daemon when navigating to `/login` and `/connect`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2566)

Require daemon-connection when navigating to connect or login

---

CHANGELOG.md
dist-assets/linux/before-install.sh
dist-assets/pkg-scripts/postinstall
dist-assets/windows/installer.nsh

To aid with debugging the issues with failing to upgrade the daemon, the daemon log from the old instance should be preserved - otherwise, by the time the user sends a problem report, the old daemon logs have been overwritten so no useful information about what happened during the installation can be inferred.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2573)

Preserve the daemon log from the old installation when upgrading

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt

The recent improvement to paint the navigation and status bars (#2521) surfaced a bug that was previously present on the Connect screen but hadn't manifested itself before. Since the new painting code makes the `HeaderBar` widget paint the status bar based on the tunnel state updates dispatched by the `ConnectFragment`, it was possible to see that when logging out the status bar would still get painted, even though the flow was theoretically was from `AccountFragment` to the `LoginFragment` (i.e., it doesn't pass through the `ConnectFragment`). Nevertheless, after debugging it was possible to see that because of how the back stack was managed, the `ConnectFragment` was started and then destroyed, which caused a tunnel state job to be scheduled and executed afterwards. So there are two …

Use lifecycle scope to update the tunnel state in the Connect screen

---

.github/workflows/frontend.yml
.travis.yml
gui/package-lock.json
gui/package.json
gui/test/logging.spec.ts

This PR adds Windows to the list of OSes to run the GitHub actions frontend job on. To get it to work a few changes were needed:
* Set the `autocrlf` git setting to prevent git from automatically converting `lf` to `crlf` which makes the linter fail
* Update `ts-node` since the previous version failed when running the tests
* Normalize paths in the logger tests. The tests haven't changed but they now handle paths with `\` as well.
The Travis job for the frontend has been removed as well since it didn't run properly.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2576)

Add Windows to frontend GitHub actions job

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/wireguard.rs
mullvad-rpc/src/lib.rs

If the API returned an invalid account error, the daemon would try to push a new key after a while. The maximum delay was 1 hour. This has been fixed. The code has been refactored in general as well.
Main changes:
* Stop trying to push a WireGuard key if the account token is invalid. It will stop after the first failed attempt.
* Increase the maximum retry delay for the initial key push from 1 hour to 1 day.
* Use exponential backoff for retrying automatic key rotation (instead of always retrying after 15 minutes).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2554)

Stop pushing WireGuard keys for invalid account tokens

---

gui/src/renderer/app.tsx
gui/src/renderer/lib/history.ts

This PR fixes and issue with the account not being set in the renderer if not connected to the daemon. This was introduced in https://github.com/mullvad/mullvadvpn-app/pull/2566.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2572)

Fix not setting account when not connected to daemon

---

CHANGELOG.md
talpid-core/src/firewall/linux.rs

This ensures that strict reverse-path filtering (`rp_filter = 1`) doesn't drop incoming packets for excluded processes. If the correct mark isn't set, RPF will think that most routes go via the tunnel interface and block any incoming traffic on other interfaces (except from the relay server).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2577)

Set fwmark on incoming packets for excluded processes

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AdvancedSettingsStyles.tsx

This PR adds a footer with a description of the WireGuard port selector. It also removes an assignment to `wireguardPortItems` which is identical to the one 19 lines above it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2586)

Add wireguard port explanation

---

CHANGELOG.md
mullvad-daemon/src/relays.rs

On macOS and Linux, when the location constraints contain no OpenVPN relays and the tunnel protocol is unconstrained (`Constraint::Any`), the daemon will fail to select a perfectly valid and available WireGuard relay if the daemon fails to connect more than 2 times. Since the tunnel protocol is not constrained, the daemon will try to use preferred constraints, but these will fail attempt to select an OpenVPN relay after the first 2 tries. The daemon should successfully fall back to using the original constraints rather than the preferred ones, but the relay selection will only use OpenVPN relays in the case that there is no tunnel protocol specified. 
Thus, the appropriate fix is to select a random relay on macOS and Linux when there is no tunnel protocol specified.
---
This change …

Pick random relay if no tunnel type is specified

---

CHANGELOG.md
mullvad-cli/src/cmds/account.rs

Entering the account token through the CLI can be a bit clunky at times. For one, the account token always ends up in the shell history, and the CLI doesn't trim whitespace of the input token, which makes it awkward to copy the token from the website.
I've changed the CLI to read the account token from STDIN by default, but the old behavior of passing it as a parameter is still available via a flag. And now the CLI will filter whitespace characters before sending the token to the daemon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2580)

CLI: Read account token from STDIN

---

README.md

I added a small section under the useful env var list in the readme about how to easily set the env vars on macOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2581)

Add macOS env var tips

---

wireguard/libwg/go.mod
wireguard/libwg/libwg_android.go

After updating Go to version 1.16 and the WireGuard-Go library (#2539), the Android app started crashing when trying to connect. The cause was that the new version of the library has a new wrapper type for bound sockets for Linux, but that shouldn't be used on Android. This PR fixes that issue by constructing the correct type on Android.
The PR also updates the Go version used for building the library for Android.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2587)

Fix WireGuard-Go usage on Android

---

ios/MullvadVPN/RelayStatusIndicatorView.swift

Git checklist:
1. Replace `CAShapeLayer` with rounded bezier path to a regular `CALayer` and `cornerRadius` instead. This is something that was suggested by Xcode as a potential performance optimisation. 
2. Use `CATransaction` to disable implicit animations when updating the color of a circle. This particularly was visible when scrolling the relay list very fast. Since the cells are reused in table view, if there is at least one relay that is down, it used to cause the red and green circle to animate like a semaphore.
3. Disable `isUserInteractionEnabled` on indicator view. Previously it was possible to tap on a green circle which would make the circle highlight but not the cell behind it.
--- …

Optimize RelayStatusIndicatorView

---

android/src/main/kotlin/net/mullvad/mullvadvpn/model/TunnelOptions.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/WireguardTunnelOptions.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/settings.rs
mullvad-types/src/custom_tunnel.rs
mullvad-types/src/settings/mod.rs
mullvad-types/src/wireguard.rs
talpid-types/src/net/wireguard.rs

Previously, this setting was stored in `talpid_types::wireguard::TunnelOptions`. Since the talpid layer doesn't implement key rotation, it does not belong there. It has been moved to `mullvad_types`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2585)

Move rotation interval setting to mullvad-types

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConfirmDnsDialogFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsAdapter.kt
android/src/main/res/layout/confirm_dns.xml
android/src/main/res/values/strings.xml

The ability to configure custom DNS servers was recently introduced (#2331). However, because the relay will intercept DNS requests sent through the tunnel, currently only DNS requests sent out of the tunnel (to the local LAN) work. There already was a warning when adding custom DNS servers that have a public IP, so that the user is aware that it won't work. This PR adds another warning saying that the "Allow LAN" setting must be enabled to allow the DNS requests to reach the local DNS server. The warning is not shown if "Allow LAN" is already enabled.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2592)

Warn when adding a local custom DNS server and "Allow LAN" is disabled

---

dist-assets/windows/installer.nsh
mullvad-setup/src/main.rs
windows/nsis-plugins/src/log/log.cpp
windows/nsis-plugins/src/log/log.def

This adds logging to the uninstaller. It also ensures that the uninstaller aborts if a serious error occurs. If the uninstaller aborts, the log file (`uninstall.log`) is kept. Otherwise, it is deleted. The presence of the log file is also used (imperfectly) to infer whether a previous version was removed. If it exists, the installer aborts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2590)

Add logging to the Windows uninstaller

---

ios/MullvadVPN/DisplayChainedError.swift

Git checklist:
This PR fixes the multiline error message where the newline characters `\n` were previously displayed as encoded sequence as opposed to line breaks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2589)

Fix multiline error message

---

CHANGELOG.md
talpid-core/src/offline/linux.rs

Previously, Linux connection check would request routes via NLM_F_REQUEST | NLM_F_DUMP, which would just return a list regardless of actual connectivity in some cases, sometimes having a loopback route, sometimes a real one. The end result was that the offline monitor was too permissive.  If this causes issues for users, they should probably use an env var to force the offline monitor off.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2591)

Improve Linux offline monitor

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Operations/AnyOperationObserver.swift
ios/MullvadVPN/Operations/AsyncOperation.swift
ios/MullvadVPN/Operations/OperationBlockObserver.swift
ios/MullvadVPN/Operations/OperationObserver.swift
ios/MullvadVPN/Operations/TransformOperationObserver.swift
ios/MullvadVPN/RelaySelector.swift
ios/MullvadVPN/SimulatorTunnelProvider.swift
ios/MullvadVPN/SimulatorTunnelProviderHost.swift
ios/PacketTunnel/PacketTunnelProvider.swift

Git checklist:
This PR makes simulated VPN tunnel (when running on iOS Simulator) to behave closer to the real one (when running on device), including emitting the `reasserting` events when "reconnecting" the tunnel and selecting relays with `RelaySelector`.
1. Add relay selector into the simulated tunnel.
1. Add `willExecute` observer to `AsyncOperation`
1. Emit `reasserting` events when reconnecting the simulated tunnel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2588)

Add relay selector into the simulated tunnel

---

mullvad-types/src/settings/migrations/mod.rs
mullvad-types/src/settings/migrations/v1.rs
mullvad-types/src/settings/mod.rs

Previously, `Settings` was duplicated in the migration module. This would result in lots of duplicate types (even for minor changes), and it also risked breaking if any of the non-duplicated types changed. A `serde_json::Value` is now passed to the migration code instead, so that only relevant parts need to be deserialized or modified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2599)

Partially deserialize settings to reduce duplication in settings migration

---

.github/workflows/android-app.yml
.github/workflows/android-xml-tidy.yml
android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparator.kt
android/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt

Previously sorting of Relays was based on string, so in this case it was not respected to numbers inside string. For example "se10" will be placed before "se5". In the new comparator we extract numbers and compare by string AND numbers.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2555)

Improve Relay items sorting

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt

The login screen currently doesn't automatically paint the navigation bar, which then ends up using the default blue color. However, the bottom of the login screen is painted dark blue, which leads to a minor inconsistency. This PR fixes that by painting the navigation bar dark blue.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2595)

Paint the navigation bar for the Login screen

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt

When logging out, the status bar keeps the last color of the header bar, while the login screen's header bar is reset to the default color (blue). This may lead to confusion, since the bar might be green while actually the tunnel is disconnected.
This PR fixes that by forcefully setting the `HeaderBar` widget's `tunnelState` to `null` when it is created, so that the setter repaints the status bar.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2594)

Initialize `HeaderBar` tunnel state to force painting the status bar

---

gui/scripts/README.md
gui/scripts/extract-geo-data.py

Git checklist:
- Installing Fiona without pre-installed GDAL throws an error, so I figured we should mention that in the `README.md`.
- I ran `extract-geo-data.py` on my macOS and it turned out that the import order between `Fiona` and `Shapely` causes the very same issues we had before. I have reported this issue to `Shapely` and flipped the import order again which seemingly resolved the issue.
Please check if `extract-geo-data.py` script runs on your computer.

Update supporting scripts

---

android/src/main/res/values/strings.xml
android/translations-converter/src/android.rs

Trying to update the translations template file revealed an issue with the Android translations converter tool. While it would properly add escaped double quotes to Android translations, it would not unescape these double quotes when extracting them to add them to the templates file. This PR fixes the issue by properly unescaping the double quotes when a `StringValue` type is normalized (i.e., unescaped and prepared for comparison with gettext translation messages).
This PR also adds a small fix to an Android string so that the tool can find it's respective translations correctly.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2602)

Fix double quotes escaping when extracting missing Android translations

---

.github/workflows/android-app.yml
android/fdroid-build/env.sh
build-apk.sh
wireguard/build-wireguard-go.sh
wireguard/libwg/Android.mk
wireguard/libwg/Dockerfile_AndroidPatchedGoruntime
wireguard/libwg/build-android.sh

A previous tool update (#2453) increased the size of the final APK (funny side note: the release notes for the new tool version says that in the new version ["App size significantly reduced for apps using code shrinking"](https://developer.android.com/studio/releases/gradle-plugin#4.1-app-size-reduction) ).
The root cause seems to be that the tool internally changed how it finds the NDK path and fails to find the `strip` tool, so it simply emits a warning and includes the unstripped library. A known workaround is to add a `ndk.dir` property to the `local.properties` file in order to force the old way to find the tool. However, that file should not be versioned since it's environment specific. Therefore, it's not a good solution and would require instead adding documentation for all build …

Manually strip native Android libraries

---

android/build.gradle
android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppData.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsIconManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt
android/src/test/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsIconManagerTest.kt
android/src/test/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProviderTest.kt

This PR separate logic for fetching applications info and filtering it and create an application icons cache manager to help optimise usage of memory and loading icons for installed application on the device. Contains tests for both classes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2605)

Create ApplicationsProvider and AppplicationsIcon cache

---

android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/RelayListListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/Constraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/DnsOptions.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayConstraints.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettings.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/TunnelOptions.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/WireguardTunnelOptions.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/CustomDns.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/SettingsListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/PreferencesFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt
android/src/main/kotlin/net/mullvad/talpid/net/wireguard/TunnelOptions.kt
mullvad-types/src/relay_constraints.rs

This PR continues the work to run the service in a separate process by splitting the `SettingsListener` class in two, one for the UI side process and one for the service side process. They communicate through the IPC channel that was configured in a [previous PR](#2463). For now, only sending events from the service side to the UI side is implemented, using a new `Event.SettingsUpdate` message. Changing individual settings by sending requests from the UI to the service will be implemented in one or more future PRs.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2496)

Split `SettingsListener` in server side and UI side classes

---

mullvad-daemon/src/logging.rs

When the log level is set to trace, there are a lot of entries logged by the `tracing` crate:
```
[2021-03-22 19:54:16.100][tracing::span][TRACE] -- FramedRead::poll_next
[2021-03-22 19:54:16.100][tracing::span][TRACE] try_reclaim_frame
[2021-03-22 19:54:16.100][tracing::span::active][TRACE] -> try_reclaim_frame
[2021-03-22 19:54:16.100][tracing::span::active][TRACE] <- try_reclaim_frame
[2021-03-22 19:54:16.100][tracing::span][TRACE] -- try_reclaim_frame
[2021-03-22 19:54:16.100][tracing::span][TRACE] pop_frame
[2021-03-22 19:54:16.100][tracing::span::active][TRACE] -> pop_frame
[2021-03-22 19:54:16.100][tracing::span::active][TRACE] <- pop_frame
[2021-03-22 19:54:16.100][tracing::span][TRACE] -- pop_frame
[2021-03-22 19:54:16.100][tracing::span][TRACE] FramedWrite::flush
[2021-03-22 …
```

Silence logs from noisy 'tracing' crate

---

android/translations-converter/src/gettext.rs
android/translations-converter/src/main.rs

The translations converter tool had a few issues:
1. It would not load the last message of a gettext messages (or template) file
2. It would not unescape double-quotes in gettext messages
3. It would build a list of missing translations based only on translations, not on the translations template file
This PR fixes those issues by, respectively:
1. Adding an empty line to the list of parsed lines so that the "else" clause of the string matching loop is executed for the last iteration
2. Unescaping double-quotes in gettext messages when normalizing it. There's no need to escape it since when they are written the code uses `{:?}` which automatically escapes the double quotes
3. The list of missing translations (messages and plurals) is now built solely based on the messages template file, …

Change missing translation detection

---

gui/src/config.json
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/ErrorBoundary.tsx
gui/src/renderer/components/Support.tsx
gui/src/renderer/containers/SupportPage.tsx
gui/src/shared/ipc-schema.ts

This PR further locks down the renderer process. The changes are:
* automatically deny any permission requests
* block navigation
* block `file://` access to files outside build directory
* limit ipc calls to `openUrl` to only allow mullvad.net URLs
* replaced `openPath` ipc method with `viewLog` which only needs the ID instead of the full path to open.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2565)

Restrict renderer process

---

CHANGELOG.md
mullvad-cli/src/cmds/tunnel.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/settings.rs
mullvad-daemon/src/wireguard.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-management-interface/src/lib.rs
mullvad-types/src/settings/migrations/mod.rs
mullvad-types/src/settings/migrations/v1.rs
mullvad-types/src/settings/migrations/v2.rs
mullvad-types/src/settings/mod.rs
mullvad-types/src/wireguard.rs

Changes:
* The minimum and maximum rotation intervals are now 1 day and 7 days, respectively.
* The CLI shows the default rotation interval now, as well as the minimum and maximum values if the provided value is out of range:
```bash
$ mullvad tunnel wireguard key rotation-interval get
Rotation interval: default (168 hours)
$ mullvad tunnel wireguard key rotation-interval set 20
error: Invalid value for '<interval>': interval must be at least 24 hours
$ mullvad tunnel wireguard key rotation-interval set 200
error: Invalid value for '<interval>': interval must be at most 168 hours
```
* The `deserialize_show_beta_releases` was removed by removing nulled values in migration code.
* The settings version was bumped to 3.
* `google.protobuf.Duration` is used instead of integers in protobufs. …

Make key rotation mandatory and at most 7 days

---

CHANGELOG.md
mullvad-daemon/src/lib.rs

Previously, the target state cache was deleted after being restored by the daemon. This means that the daemon would not enter the correct state after a crash (or restart during an upgrade) in this situation. This was fixed by caching the initial target state.
For example, this might occur if `mullvad-setup prepare-restart && net stop mullvadvpn && net start mullvadvpn` is run twice while initially connected. The second time the daemon is stopped, there is no target state. When started again, it will not immediately connect unless auto-connect is enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2608)

Save initial target state

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/GeoIpLocation.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/LocationInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/LocationInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt

This PR continues the work on splitting the code base so that the background service can run in a separate process. This PR focuses on the `LocationInfoCache` which is responsible for obtaining the Geo IP location. Now there are two classes, where the service-side `LocationInfoCache` is where the behavior is kept, and the UI side which will register and listen for `NewLocation` events from the IPC channel.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2610)

Split `LocationInfoCache` into UI-side and service-side classes

---

CHANGELOG.md
mullvad-problem-report/src/lib.rs

The top address in `api-ip-address.txt` (ie the one last used by the service) is always preferred, and the problem report tool is not allowed to replace the cache. This meant that previously `mullvad-problem-report` would always use the same IP address to contact the API even if it failed using it before. Retrying a couple of times makes sure that two random addresses are used as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2620)

Retry if sending problem reports fails

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AutomaticKeyboardResponder.swift
ios/MullvadVPN/LoginContentView.swift
ios/MullvadVPN/ProblemReportViewController.swift

Git checklist:
This PR adds a helper class that automatically handles the keyboard and adds the appropriate content insets to pad the scrollable views in order to account for the keyboard overlay.
This class also handles the formsheet presentation on iOS where the small floating modal window is displayed in the middle of the screen. This kind of presentation automatically centers the view controller above the keyboard. This class tackles this by observing the `frame` of the container view that floats around with keyboard and updating the scroll content insets accordingly.
The concept itself is described here: https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/Te …

Add automatic keyboard responder helper

---

.github/workflows/daemon.yml
.github/workflows/translations.yml
android/src/main/res/values-da/strings.xml
android/src/main/res/values-de/strings.xml
android/src/main/res/values-es/strings.xml
android/src/main/res/values-fi/strings.xml
android/src/main/res/values-fr/strings.xml
android/src/main/res/values-it/strings.xml
android/src/main/res/values-ja/strings.xml
android/src/main/res/values-ko/strings.xml
android/src/main/res/values-nb/strings.xml
android/src/main/res/values-nl/strings.xml
android/src/main/res/values-pl/strings.xml
android/src/main/res/values-pt/strings.xml
android/src/main/res/values-ru/strings.xml
android/src/main/res/values-sv/strings.xml
android/src/main/res/values-th/strings.xml
android/src/main/res/values-tr/strings.xml
android/src/main/res/values-zh-rCN/strings.xml
android/src/main/res/values-zh-rTW/strings.xml
android/translations-converter/src/gettext.rs
android/translations-converter/src/main.rs
gui/locales/messages.pot

The process to handle adding translations to the app (desktop and Android) became more complex due to the requirement of keeping gettext files and Android resources synchronized. This PR aims to help with that problem by creating a new CI workflow that will fail in some situations where the translations aren't properly synchronized. More specifically, the workflow will fail in the following scenarios:
- adding a new message to the desktop GUI but not including that message in the template file (`messages.pot`)
- adding a new Android string resource that and either:
- not adding the translations extracted from the desktop GUI locales for that message
- not adding the message to the template file
- changing a message in the desktop GUI and not updating the template file or not updating the …

Add CI job for checking translations

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/Constraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/KeygenEvent.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/LocationConstraint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/PublicKey.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettings.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/KeyStatusListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/KeyStatusListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/KeyStatusNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/KeyStatusListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt

This PR continues the work on splitting the app so that the service runs in a separate process. This PR focuses on the `KeyStatusListener` class. This class is responsible for sending verify key and (re)generate key commands while also listening for the status of the WireGuard key, i.e., if it's available or not, or if there was any error with the key generation.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2621)

Split `KeyStatusListener` in a UI-side class and a service-side class

---

CHANGELOG.md
mullvad-cli/src/cmds/bridge.rs
talpid-core/src/firewall/linux.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/tunnel_state_machine/connected_state.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs

If this setting is set to true, the firewall only permits packets with a particular fwmark to communicate outside the tunnel with the relay server. The alternative is that processes that run as root are allowed to talk to the relay.
It is no longer useful to set this to `false`, not even for bridges since we exclude `sslocal` from the tunnel. This change does mean that one must use `mullvad-exclude` (or, preferably, set the fwmark directly to `talpid_core::linux::TUNNEL_FW_MARK`) to run one's proxy server, or else the firewall will block it. But in practice, this is already the easiest way to go, because the routes are not automatically set up to deal with the other case.
--- …

Remove use_fwmark option

---

docs/split-tunneling.md

It's not immediately obvious that DNS lookups will fail for excluded apps for some setups (e.g. on Windows) iff the service is not connected or disconnected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2616)

Explain why DNS requests fail for excluded apps in some states

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/settings.rs
mullvad-daemon/src/version_check.rs

There were some blocking file operations running on worker threads in `mullvad-daemon` in the root, `settings`, and `version_check` modules. Not greatly significant, but this fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2632)

Get rid of blocking file I/O in `mullvad-daemon`

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Message.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/LoginStatus.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/AccountExpiryNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountHistoryAdapter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt
android/src/main/kotlin/net/mullvad/talpid/util/EventNotifier.kt

This PR continues the work to split the Android app into two processes, so that the service can run in a separate process. This PR focuses on the `AccountCache` class. The class is responsible for handling the account token, the account history and fetching the account expiration.
After this PR, the service side `AccountCache` will also handle the login procedure logic. It can now receive `Login`, `Logout` and `CreateAccount` requests and will respond by sending a `LoginStatus` event that contains a tuple `(accountToken, optionalExpiry, isNewFlag)` and also has a helper property `isExpired` calculated from the `optionalExpiry`.
For the account history, it's possible to send a `RemoveAccountFromHistory` request in order to remove an account token from the history list. Every change to the …

Split `AccountCache` into UI-side and service-side classes

---

ios/CHANGELOG.md
ios/MullvadVPN/ProblemReportReviewViewController.swift

Git checklist:
- Enable the "Select all" option in the popup menu when viewing app logs. This option enables user to select the entire text app log to be able to copy the entire text in clipboard.
- Update CHANGELOG to reflect the most recent release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2631)

Enable option to "Select all" when viewing app logs

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/res/values-my/strings.xml

As part of the ongoing work to split the Android app in two processes, an issue appeared where parts of the service initialization changed order and led to a few race condition problems. This PR refactors the initialization of the `ForegroundNotificationManager` so that it's done after the `ServiceEndpoint` is initialized, which will contain parts that the notification manager will use.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2638)

Refactor notification manager initialization

---

mullvad-daemon/Cargo.toml
mullvad-daemon/src/geoip.rs

It's a burden to any consumers of the daemon logs to read through 4 lines of logging about how an IPv6 address was unreachable everytime the daemon connects and the current location and exit IPs are requested. As such, I've changed the logging code to not log `libc::ENETUNREACH` errors.
As an aside, I've also witnessed `ECONNREFUSED` when running the client from within a Linux VM. And whenever I initiated a reconnect on Windows via the GUI, both geoip requests would fail. But they would succeed later on, if the location is requested via `mullvad status --location`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2635)

Stop logging ENETUNREACH errors when deducing geoip.

---

CHANGELOG.md
gui/tasks/distribution.js

This PR prevents the menubar `.ico` icons on Windows from being included in the asar archive. Previously these files were unpacked by Electron to `%TEMP%/` and Electron never removed them. By not including them in the asar archive they don't need to be unpacked to the temp-directory.
Fixes https://github.com/mullvad/mullvadvpn-app/issues/2636.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2640)

Prevent tray icons from being included in asar archive on Windows

---

gui/package-lock.json

This PR is the result of `npm run fix` and updates these transitive dependencies from vulnerable versions:
* xmldom
* plist
* y18n
These dependencies are development dependencies and only used in the build process.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2641)

Upgrade vulnerable dependencies

---

android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListAdapter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListItemHolder.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/DispatchingHandler.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/MessageDispatcher.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/DaemonInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SplitTunneling.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/persistence/SplitTunnelingPersistence.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt
android/src/test/kotlin/net/mullvad/mullvadvpn/di/AppModuleTest.kt
android/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt

This PR continues the work to split the Android app to run in two separate processes, by focusing on the `SplitTunneling` class. Now there are two `SplitTunneling` classes, one on the UI side and one on the service side.
The two classes communicate through the IPC channel. The UI can send requests to exclude an app from the tunnel, include an app in the tunnel, persist the split tunneling configuration to disk, and to enable or disable split tunneling. The service side class only sends split tunneling events which contain the list of excluded apps, or `null` if split tunneling is disabled.
The PR also contains a fix to an issue that becomes apparent with the changes included in this PR. There was previously the possibility of a race condition that ended up starting the daemon again while …

Split `SplitTunneling` into UI-side class and service-side class

---

CHANGELOG.md
Cargo.lock
README.md
mullvad-management-interface/Cargo.toml
mullvad-management-interface/src/lib.rs
talpid-core/src/tunnel/openvpn/mod.rs

By default, anyone can read or write to the management interface socket. In general (and by design), the daemon is not protected against attackers with physical access to the machine.
This PR adds an option to restrict access to the socket. The owner is set to `root:${MULLVAD_MANAGEMENT_SOCKET_GROUP}` with permissions 760.
Additionally, permissions were tightened on the OpenVPN plugin socket.
Closes #2639.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2642)

Restrict access to UDS socket using environment variable

---

ios/MullvadVPN/SettingsNavigationController.swift
ios/MullvadVPN/SettingsViewController.swift

Git checklist:
1. Move responsibility to handle the internal view controller navigation from a child `SettingsController` to parent  `SettingsNavigationController`
2. Implement `UIAdaptivePresentationControllerDelegate` on. `SettingsNavigationController` to be able to handle the interactive (swipe gesture) dismissal of the view controller. For that to work the `presentationController.delegate` has to be set to `<SettingsNavigationController>` - this change will be one from `AppDelegate` in the follow up PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2650)

Settings: rework navigation

---

ios/MullvadVPN/AccountInputGroupView.swift
ios/MullvadVPN/AccountTextField.swift

Git checklist:
This PR adds the return key to the on-screen keyboard on iPad. I picked the return type key that says "Join", seemed more suitable than others but I am open to changing this. The supported return key types are defined here https://developer.apple.com/documentation/uikit/uireturnkeytype and shortly are "return", "Go", "Google", "Join", "Next", "Route", "Send", "Yahoo", "Done", "Emergency call" and "Continue".
Note that this PR is only relevant for iPad, as on iPhone we have a numpad keyboard which does not have the return key.
--- …

AccountTextField: handle return key on iPad

---

.github/workflows/android-app.yml

This PR changes target build architecture to `x86_64`, contains new job for android instrument test running on macOS environment with HAXM hardware acceleration and create shared cache for build output to share it between jobs to prevent build native libs double.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2647)

Add CI job for Android instrument tests

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/TunnelState.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ConnectionProxy.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VpnPermission.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/tunnelstate/TunnelStateUpdater.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/TunnelStateNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ConnectionProxy.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/VpnPermission.kt
android/src/main/kotlin/net/mullvad/talpid/net/Endpoint.kt
android/src/main/kotlin/net/mullvad/talpid/net/TransportProtocol.kt
android/src/main/kotlin/net/mullvad/talpid/net/TunnelEndpoint.kt
android/src/main/kotlin/net/mullvad/talpid/tunnel/ActionAfterDisconnect.kt
android/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorState.kt
android/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt

This PR continues the work to separate the Android app in order to run the service in a separate process. This PR focuses on the `ConnectionProxy`. There are now two `ConnectionProxy` classes, one used by the UI and one used by the service. The service-side class handles the actual communication with the daemon, while the UI side class sends requests and receives events, as well as handling a custom UI state that anticipates the real tunnel state.
As part of the changes, the `ConnectionProxy` is now decoupled from both the service and from the `MullvadVpnService`. Two new `VpnPermission` helper classes (one UI-side and one service-side) were created to help with this decoupling.
Git checklist:
--- …

Split `ConnectionProxy` into a UI-side and a service-side class

---

CHANGELOG.md

Bump the binaries submodule to include OpenVPN 2.5.1. Also has the openvpn and sslocal binaries for `aarch64-apple-darwin` to enable future builds for M1 macs.
I have verified that a build with these binaries run on Windows and macOS so far. So seems good.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2657)

Upgrade OpenVPN to 2.5.1

---

CHANGELOG.md
Cargo.lock
mullvad-cli/src/cmds/relay.rs
mullvad-cli/src/format.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/proto/management_interface.proto
talpid-core/Cargo.toml
talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/tunnel_state_machine/mod.rs
talpid-types/src/net/wireguard.rs

This adds support for reaching WireGuard relays over TCP via [udp-over-tcp](https://github.com/mullvad/udp-over-tcp). Currently, this can only be configured for custom relays (that are running `Tcp2Udp`).
Usage:
```
mullvad relay set custom wireguard <IP> <PORT> tcp <PEER PUBLIC KEY> <GATEWAY> --addr <TUNNEL IP>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2537)

Support WireGuard over TCP for custom relays

---

Cargo.lock

`libc` was recently bumped from 0.2.85 to 0.2.87. There was a [regression](https://github.com/rust-lang/libc/pull/2102) in that version that removed `libc::accept4` for this build target. Fix by upgrading the `libc` crate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2660)

Fix ARMv7 build error

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/CustomDns.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/CustomDns.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsAdapter.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt

This PR continues the work to split the Android app so that the service runs in a separate process. This PR focuses on the custom DNS functionality, splitting the `CustomDns` class in two, one for the service side and one for the UI side. The UI side class sends requests to add/remove/replace custom DNS servers, and to enable or disable the functionality. The service side then handles those requests.
The service side class does not need to send any events to the UI side `CustomDns` class because they are included in settings updates sent by the `SettingsListener`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2656)

Split `CustomDns` into service-side and UI-side classes

---

gui/locales/messages.pot
gui/src/renderer/components/AdvancedSettings.tsx

This PR changes the warning message shown when a public custom DNS server is added.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2659)

Change custom DNS warning message for public IPs

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt

The UI side method returns a boolean flag indicating if the DNS server
was successfully added, which is basically a check if the DNS server
address wasn't already added to the list. Unfortunately, there was a bug
in the method that returned the negated value. This led to a weird bug
where adding a new DNS server caused it to fail first, but succeed on
the second attempt.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2663)

Fix return value of `CustomDns.addServer` method

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt

This PR refactors teh `AccountExpiryNotification` class to use some improvements from previous PRs. It now uses an `Intermittent<Daemon>`, preparing it to better handle service <-> UI reconnections. This allows the `MullvadVpnService` to create one instance of `AccountExpiryNotification`, instead of having to recreate every time the IPC connection changes.
It also uses a `LoginStatus` instead of the expiry directly, so that it can use the event to determine all the information it needs to show or not the notification.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2662)

Update `AccountExpiryNotification` code

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/CustomSplitViewController.swift
ios/MullvadVPN/UIColor+Palette.swift

Git checklist:
* [X ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)
This PR adds a `UISplitViewController` subclass from UIKit that adds the capability to change the divider color and supports our custom `RootContainment` protocol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2655)

Add CustomSplitViewController

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt

The app would previously crash when the UI side `AccountCache` class
sent a second request message to the service side `AccountCache` class.
The simplest way to reproduce this was to log out and log in again. This
was happening because the service side `AccountCache` actor
implementation was only handling one request and then stopping.
This is now fixed by having the actor run a loop to handle all incoming
requests.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2669)

Fix `AccountCache` only handling first request

---

gui/src/main/gui-settings.ts
gui/src/main/windows-pe-parser.ts
gui/src/main/windows-split-tunneling.ts
gui/src/renderer/redux/settings/reducers.ts
gui/src/shared/gui-settings-state.ts

This PR is the first in a series of PRs implementing different parts of the split tunneling UI on Windows. The changes include:
* Parse PE format to retrieve list of imported DLLs of an exe-file
* Read installed applications from the start menu and filter those based on imported DLLs
* Add support for arrays in `guiSettings`
* Add support to `guiSettings` for persisting list of manually added applications.
Information about the PE format can be found here:
https://docs.microsoft.com/en-us/windows/win32/debug/pe-format
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2665)

Find installed applications on Windows

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/AppVersionInfo.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AppVersionInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/VersionInfoNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt

This PR continues the work to make `MullvadVpnService` run in a separate process. This PR focuses on the app version information. The `AppVersionInfoCache` is now split in two classes, one for the UI side and one for the service side. The relationship between them is that the service side will keep track of the version information and then send updates to the UI side class so that the UI can use that information.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2668)

Split `AppVersionInfoCache` in a UI-side class and a service-side class

---

CHANGELOG.md
docs/security.md
talpid-core/src/firewall/linux.rs

Previously, the app only filtered packets at the output and input hooks in netfilter, ignoring the forward hook. This meant that forwarded traffic was unfiltered. So a machine/router running Mullvad was able to pass on traffic without any restrictions. For example, if "Always require VPN" was enabled, it would still forward packets from other hosts.
Perhaps more importantly, this also had consequences for virtual networks/bridges, such as when Mullvad was running on a host with virtual machines. For example, guests were able to reach the internet even though the daemon was in a blocking state. In the connected state, it was also able to resolve hostnames using any resolver. Moreover, the local network (except the host machine) could be reached from a guest, even if local network sharing …

Secure filtering of forwarded packets on Linux

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/Relay.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayList.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayListCity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayListCountry.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayTunnels.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/WireguardEndpointData.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/RelayListListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/RelayListListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt

This PR continues the work to run the `MullvadVpnService` in a separate process. The focus of this PR is to split the `RelayListListener` class in a service-side class and a UI-side class. The service side receives relay list events from the daemon, and forwards that to the UI side class.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2675)

Split `RelayListListener`

---

gui/locales/messages.pot
gui/src/renderer/components/AdvancedSettings.tsx

This PR changes the placeholder text in the custom DNS input from `e.g. 10.0.0.4` to `Enter IP` since the previous placeholder confused users.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2679)

Change placeholder in custom DNS input

---

CHANGELOG.md
gui/src/main/autostart.ts

This PR stops using a hardcoded path when symlinking `mullvad-vpn.desktop` to the autostart directory, instead it searches `XDG_DATA_DIRS` for it. This should fix https://github.com/NixOS/nixpkgs/issues/116401.
I've also replaced the promisified `fs` calls with the built in promisified versions.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2683)

Stop using hardcoded path to Linux Desktop Entry

---

Cargo.lock

As far as I could understand none of these upgrades really affected us. But best to stay with up to date software.
`rand_core`: https://rustsec.org/advisories/RUSTSEC-2021-0023
`hyper`: https://rustsec.org/advisories/RUSTSEC-2021-0020
Why `pin-project-lite` was yanked: https://github.com/taiki-e/pin-project-lite/pull/55
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2672)

Upgrading a few dependencies with cargo audit warnings

---

CHANGELOG.md
dist-assets/pkg-scripts/postinstall

Seemingly, the installer can set different file permissions for our `plist` file for the daemon on macOS (#2678) depending on, I guess, the device's serial number or maybe the locale? The root cause doesn't matter - if the permissions are not `644`, then launchctl will refuse our daemon. As such, the installer is changed to always set the permissions to `644` prior to starting the daemon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2684)

Set 644 permissions for daemon plist in installer

---

.github/workflows/cargo-audit.yml

This CI job looks for crates with vulnerabilities in the RustSec Advisory Database. Warnings (e.g. for unmaintained crates) are currently ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2682)

Add CI job for auditing Cargo.lock files

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AuthTokenCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/AccountExpiryNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/KeyStatusNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/NotificationBanner.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/UrlButton.kt

This PR continues the work to make `MullvadVpnService` run in a separate process. The focus of this PR is on the `AuthTokenCache` which will now be split into a service-side class and a UI-side class. The UI side class can be used to obtain WWW authentication tokens to access the website. It does this by sending a request to the service side class and waiting for an event with the token. The service side class has a queue to handle one request at a time.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2677)

Split `AuthTokenCache` into service side and UI side classes

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt

A bug was recently introduced after refactoring the `AccountCache` to be split into UI and service side classes (#2628). As part of the refactor, the login procedure was rewritten to happen on the service side and send `LoginStatus` events to the UI after the login procedure finished. Unfortunately, after that change the app had a bug where trying to log in with an invalid account would never finish.
This happened because even though the logging in logic on the service side would run correctly and catch the login error, it wouldn't notify the UI that the login procedure failed. This PR fixes that by making sure the `LoginStatus` event is always sent to the UI when the login procedure finishes.
Git checklist:
--- …

Fix login failure not sending login status to UI

---

.gitignore
CHANGELOG.md
README.md
build.sh
env.sh
gui/tasks/distribution.js
wireguard/build-wireguard-go.sh

This PR adds support for cross compiling the app for the M1 macs on x86 macs as well as support for making universal builds.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2673)

Add support for building universal macOS app

---

CHANGELOG.md
gui/tasks/distribution.js

This PR enables downgrades on macOS. Previously it didn't replace newer versions with older versions when installing.
From the `electron-builder` documentation:
> `isVersionChecked` = `true` Boolean - Don’t install bundle if newer version on disk?
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2688)

Enable downgrades on macOS

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/RelayListListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SettingsListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/PreferencesFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/RelayListListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt

This PR continues the work to make `MullvadVpnService` run on a separate process. The focus of this PR is to have the UI update settings values through the IPC channel. New `Request` variants were made to set specific settings, and the UI side IPC classes now have some properties that when set will send those requests so that the service side IPC classes can actually apply those changes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2685)

Use the IPC channel to update settings values

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt

Previously there could be a race condition because the
`ServiceConnection` constructor would register itself as an event
listener on the service without registering a handler for the
`ListenerReady` event sent after the registration is complete. The
`MainActivity` would then register the handler, and things would work
because the service would send multiple events before sending the
`ListenerReady`, giving time for the handler to be registered before the
event is received.
This PR changes that in order to avoid the race condition. Now the
`ServiceConnection` constructor must receive a callback as a parameter,
and this callback will be used when registering for the `ListenerReady`
event. This allows the constructor to enforce that the handler for the
event is configured before the request …

Ensure `ListenerReady` handler is registered before request is sent

---

android/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AccountCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AuthTokenCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ConnectionProxy.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/KeyStatusListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/LocationInfoCache.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/RelayListListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SettingsListener.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt

This PR includes some small improvements to the UI side IPC classes. Most classes were incorrectly using `DispatchingHandler` directly, instead of the safer `MessageDispatcher<Event>` interface. This PR fixes that by using an `EventDispatcher` type alias to `MessageDispatcher<Event>`.
The PR also includes a few improvements to constructor parameters to remove unnecessary properties and making them private by default.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2689)

Create `EventDispatcher` type alias

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt

When I was testing the VPN permission request fix, I realized that sometimes the connect screen wouldn't update after the tunnel connected. The easiest way to reproduce this was to:
1. open the app
2. disconnect
3. open the Android VPN settings
4. revoke the VPN permission for the app
5. return to the app
6. swipe down from the notification bar to show the app's notification
7. press "Connect" on the notification
8. swipe up to close the notifications
9. approve the VPN permission on the dialog
After the steps, the notification would show (correctly) that the tunnel was connected, while the UI would show (incorrectly) that the tunnel was disconnected.
The cause of this issue is that most fragments only set up event listeners in the `onSafelyStart` method, and unsubscribe those listeners …

Fix UI loses service events

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmission.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/VoucherSubmissionResult.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VoucherRedeemer.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/VoucherRedeemer.kt

This PR continues the work to run the `MullvadVpnService` in a separate process. This PR focuses on splitting the last shared class (`VoucherRedeemer`) into a UI-side class and a service-side class. The UI side sends requests to the service side, and keeps a map of incomplete requests. As responses are received from the service side, the requests are completed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2691)

Split `VoucherRedeemer` class into a service-side and a UI-side class

---

android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VpnPermission.kt

When the app runs on TVs, a different activity class (`TVActivity`) is used to make sure the UI is displayed correctly. A recent refactor (#2644) included a hard-coded reference to the non-TV class (`MainActivity`), which ended up breaking requesting the Android VPN permission when running on TVs.
This PR fixes that by detecting if the app is running on a TV device or not and selecting the appropriate class.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2681)

Use `TVActivity` class when asking for VPN permission on TVs

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrlWithToken.kt

This is a small improvement to mark the `urlId` constructor parameter with the `StringRes` annotation so that it's correctly used as a string resource.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2698)

Add `StringRes` annotation to `urlId` in `NotificationWithUrlWithToken`

---

CHANGELOG.md
android/src/main/AndroidManifest.xml
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Message.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt

This is the final PR to run the `MullvadVpnService` in a separate process. It marks the service to run as a separate process in the manifest, and it removes the `LocalBinder` and the `ServiceInstance` that was used for communication. Now, all communication only happen through the IPC channel.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2396)

Run `MullvadVpnService` on a separate process on Android

---

gui/src/renderer/components/cell/Input.tsx

This PR blurs the cell input fields when enter is pressed since there is no reason for them to stay focused.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2696)

Blur cell input field when enter is pressed

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt

Previously, it was possible to crash the app when leaving it then coming back to it. The cause was that the `ServiceConnection` scope was being recreated without first destroying the old scope. This only happened because the `serviceConnection` property was never set to `null` when intentionally unbinding from the service, because the `onServiceDisconnected` callback is only called if the service disconnects unintentionally.
This PR fixes that by setting the `serviceConnection` to `null` right after unbinding from the service. The call currently has to be done after calling `super.onStop` because the `ServiceDependentFragment` will only properly ignore the disconnection if it has detected that the state has changed to stopped.
The PR also removes a redundant `null` notification of the …

Properly destroy `ServiceConnection` scope after unbinding from service

---

ios/MullvadVPN/AutomaticKeyboardResponder.swift
ios/MullvadVPN/LoginViewController.swift
ios/MullvadVPN/ProblemReportViewController.swift

Git checklist:
1. Fix the support for automatic adjustment of UIScrollView content insets to account for keyboard overlay when in form sheet presentation style on iOS 14. This kind of presentation style is iPad specific and behaves slightly different in different versions of iOS. 
Most recent versions of iOS move the controller along with the keyboard which makes it impossible to determine the part of the view that's being covered by the keyboard at the time when keyboard is about to appear. The only solution to that problem that I could find was to track the container's `frame`. 
This works fine, however it seems that on iOS 14 the `presentationController?.containerView` is `nil` at the time …

Handle keyboard in formsheet presentation (Take 2)

---

mullvad-cli/src/cmds/relay.rs

Previously, tunnel protocol-specific constraints were set using the subcommand `mullvad relay set tunnel`:
```
mullvad relay set tunnel <vpn protocol> <port> --ipv <ip version> --protocol <transport protocol>
OPTIONS:
--ipv <ip version>                  [default: any]  [possible values: any, 4, 6]
--protocol <transport protocol>     [default: any]  [possible values: any, udp, tcp]
```
One of the options is currently only valid for OpenVPN but not WireGuard (`--protocol`), and vice versa (`--ipv`). To make things clearer, `openvpn` and `wireguard` are now treated as separate subcommands:
```
mullvad relay set tunnel openvpn <port> --protocol <transport protocol>
OPTIONS:
--protocol <transport protocol>     [default: any]  [possible values: any, udp, tcp]
```
```
mullvad relay set tunnel …
```

Improve CLI for tunnel-specific constraints

---

mullvad-problem-report/src/lib.rs

Logs sometimes contain unique identifiers for (network) devices:
> 2021-04-28 17:35:00 Succeeded in adding a temporary IP/netmask of [REDACTED]/[REDACTED] to interface {BF442ED7-B713-46A4-8ADD-058739A49735} using the Win32 IP Helper API
This is arguably sensitive and not very useful information, so it should be redacted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2711)

Redact GUIDs from problem reports

---

ios/MullvadVPN/SelectLocationViewController.swift

Git checklist:
This PR moves the instruction text in "Select Location" controller from being displayed at the top to the bottom on iPad when the controller is displayed as a child inside of the main controller, in all other instances the instruction text is displayed at the top (i.e modal presentation).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2707)

Select location: move instruction text to footer on iPad

---

gui/src/main/index.ts
gui/src/renderer/app.tsx

This PR adjusts the app height on Windows and Linux to make it correct until this is fixed in Electron. Related issue:
https://github.com/electron/electron/issues/28777
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2717)

Adjust app height to accomodate incorrect height set by Electron

---

ios/MullvadVPN/LoginViewController.swift

Git checklist:
This PR makes sure that the keyboard input accessory toolbar is only set on iPhone where we have a numpad-style keyboard (circled in red on screenshots), while on iPad we have a full-size keyboard which contains keys to log-in (via return key) or dismiss the keyboard via dedicated dismiss key. (See screenshots below)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2719)

Login: set inputAccessoryView only on iPhone

---

android/src/main/res/layout/account.xml
android/src/main/res/layout/advanced_header.xml
android/src/main/res/layout/preferences.xml
android/src/main/res/layout/problem_report.xml
android/src/main/res/layout/select_location_header.xml
android/src/main/res/layout/settings.xml
android/src/main/res/layout/split_tunneling_header.xml
android/src/main/res/layout/wireguard_key.xml

This PR add 1 line limitation for expanded header to prevent wrong calculation of height scale. 
Probable this component will be changed to `CoordinatorLayout` in future.
Fixes #2423
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2715)

Hotfix for expanded title calculation

---

ios/CHANGELOG.md
ios/MullvadVPN/TunnelManager.swift

The operation is not being finished in the event of failure to save
tunnel configuration to system preferences.
Git checklist:
This PR fixes a small omission where the operation enqueued from `TunnelManager.stopTunnel()` wasn't properly finished in the event of failure to save the VPN configuration to preferences; which in turn caused the `TunnelManager` to become unresponsive to any further requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2722)

TunnelManager: properly finish operation in stopTunnel()

---

ios/CHANGELOG.md
ios/MullvadVPN/TunnelManager.swift

Git checklist:
This PR fixes a small bug in `TunnelManager` code that caused the app to skip the tunnel settings migration from older versions of the app.
The bug boils down to the use of wrong variable (instance variable) instead of the argument to the function. Both variables carry the same name so it was easily missed during reviews. I believe this bug was introduced in one of recent refactorings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2724)

Fix tunnel manager settings migration

---

CHANGELOG.md
dist-assets/windows/installer.nsh
gui/tasks/distribution.js
windows/driverlogic/src/driverlogic.cpp

This fixes occasional failures to reuse GUIDs for Wintun interfaces:
```
[2021-05-05 11:38:07.830][talpid_core::tunnel::openvpn::windows][INFO] [Wintun] CreateAdapter: Creating adapter
[2021-05-05 11:38:08.632][talpid_core::tunnel::openvpn::windows][ERROR] [Wintun] CreateAdapter: Failed to setup adapter: Åtgärden har slutförts. (Code 0x00000000)
```
It was caused by Windows not cleaning up after itself: https://git.zx2c4.com/wintun/commit/?id=747ba7121d1d94dac982b9148076d7006e2c170f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2725)

Upgrade Wintun to 0.10.4

---

gui/locales/messages.pot
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/SecuredLabel.tsx
gui/src/shared/notifications/disconnected.ts

This PR replaces the word "unsecured" with "unsecure" in user facing texts.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2731)

Replace "unsecured" with "unsecure"

---

ios/CHANGELOG.md
ios/MullvadVPN/DisplayChainedError.swift

Git checklist:
It looks like StoreKit does not provide localized error messages which results in the following error message to be displayed to user:
> The operation couldn’t be completed. (SKErrorDomain error 2.)
This PR localises some of the well known errors to display a user friendly error to the user. The messages themselves are taken verbatim from Apple documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2735)

Localize StoreKit errors (SKError)

---

ios/CHANGELOG.md
ios/MullvadVPN/Account.swift
ios/MullvadVPN/AppStorePaymentManager.swift
ios/MullvadVPN/AutomaticKeyRotationManager.swift
ios/MullvadVPN/MullvadRest.swift
ios/MullvadVPN/ProblemReportViewController.swift
ios/MullvadVPN/RelayCache.swift
ios/MullvadVPN/TunnelManager.swift

Git checklist:
1. Tidy up the HTTP status code handling in the Rest API by replacing the `RestResponse` type with `ResponseHandler` protocol and moving the response handling outside of the response types.
2. Add HTTP caching support via ETag. Stored in `CachedRelays` on disk for further cache validation.
3. Add HTTP header and status code types to reuse as constants across the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2733)

Use HTTP caching when requesting relay list

---

ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/HeaderBarView.swift
ios/MullvadVPN/RootContainerViewController.swift

Git checklist:
When presenting the login controller in form-sheet presentation, the UIKit presents the controller in the middle of the screen and adds semi-transparent overlay beneath it, covering the header bar and settings button, effectively blocking the interaction with it and preventing user from accessing settings.
This PR adds capabilities to duplicate the settings button inside the semi-transparent overlay while in form-sheet presentation and make the settings button appear exactly above the original button inside of header bar, however enabling user interaction since the cloned button is now above the overlay.
Couple of 3D screenshots below explain the idea:
(the white rectangle on …

Make settings button accessible in formsheet presentation on iPad

---

android/build.gradle
android/src/androidTest/kotlin/net/mullvad/mullvadvpn/ipc/HandlerFlowTest.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Event.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/HandlerFlow.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/Request.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/DispatchingFlow.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt

This PR refactors the `MullvadTileService` to use a new `Flow` based setup for the IPC channel to the `MullvadVpnService`. A new `ServiceConnection` class was created inside the `ipc` package, with the purpose of being shared between the UI and the tile service later. As part of the refactoring of the tile service, the `Handler` used for receiving messages now must be unregistered from the service in order to stop receiving messages.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2727)

Use a new `Flow`-based approach to configure IPC in `MullvadTileService`

---

CHANGELOG.md
mullvad-cli/src/cmds/bridge.rs
mullvad-cli/src/cmds/relay.rs
mullvad-cli/src/format.rs
mullvad-cli/src/location.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-management-interface/src/types.rs
mullvad-types/src/relay_constraints.rs
talpid-core/src/firewall/linux.rs
talpid-core/src/firewall/macos.rs
talpid-core/src/firewall/windows.rs
talpid-core/src/tunnel/wireguard/config.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-types/src/net/mod.rs
talpid-types/src/net/wireguard.rs
windows/winfw/src/winfw/fwcontext.cpp
windows/winfw/src/winfw/fwcontext.h
windows/winfw/src/winfw/winfw.cpp
windows/winfw/src/winfw/winfw.h
windows/winfw/src/winfw/winfw.vcxproj.filters

This allows an entry endpoint to be set for WireGuard. Meaning that the user only sends/receives traffic from the entry, but all traffic eventually comes in or out at the exit endpoint (controlled by the normal location constraint). Two WireGuard peers are added: Traffic to the exit endpoint (e.g. `185.213.154.69` below) is sent via an "entry peer" (e.g. `185.213.154.67` below), and all other traffic is sent to the exit endpoint (via the entry peer):
```
peer: veGD6/aEY6sMfN3Ls7YWPmNgu3AheO7nQqsFT47YSws=
endpoint: 185.213.154.69:56783
allowed ips: 0.0.0.0/0, ::/0
latest handshake: 5 seconds ago
transfer: 235.45 KiB received, 214.04 KiB sent
peer: AtvE5KdPeQtOcE2QyXaPt9eQoBV3GBxzimQ2FIuGQ2U=
endpoint: 185.213.154.67:24343
allowed ips: 185.213.154.69/32
latest handshake: 5 seconds ago …
```

Add multi-hop, optional entry location constraint for WireGuard (CLI only)

---

ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/AutomaticKeyboardResponder.swift
ios/MullvadVPN/RootContainerViewController.swift

Git checklist:
- Since login controller is now being wrapped in `RootContainer`, we have to proxy `disablesAutomaticKeyboardDismissal` to the child controllers to make sure that user can dismiss the keyboard when in formsheet presentation on iPad.
- On iOS 12, the adaptive presentation call to `willPresentWithAdaptiveStyle` often receives `.none` as the adaptive presentation style, which means that no change to adaptive presentation should be made and we should carry on with the modal presentation style that was originally set on the presented view controller. This fix attempts to resolve the actual presentation style before deciding how to adapt the presentation. On iOS 13+ this call often …

iOS 12 fixes for iPad app

---

CHANGELOG.md
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs

`WinNet_EnsureBestMetric` sometimes fails due to `LUID [...] does not specify any IPv4 or IPv6 interfaces` (`windows/winnet/src/winnet/interfacePair.cpp:25`). The code in this PR waits for the interfaces to attach after creating the tunnel device. If the error continues to occur, it must mean that an incorrect LUID is used for setting the metric (unlikely), or that the interfaces are destroyed at some later point in time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2753)

Wait for IP interfaces to be attached before setting metrics

---

gui/src/main/gui-settings.ts

This PR corrects the condition that checks the types of array content in the GUI settings. Previously this didn't work for empty arrays.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2747)

Add length condition when parsing GUI settings array

---

CHANGELOG.md
talpid-core/src/tunnel/wireguard/mod.rs

Microsoft Store drops packets in the tunnel if the routes have no gateway address set. This can be worked around by setting that address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2748)

Set gateway address on WireGuard tunnel routes

---

CHANGELOG.md
gui/locales/messages.pot
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/Preferences.tsx
gui/src/renderer/components/PreferencesStyles.tsx
gui/src/renderer/containers/PreferencesPage.tsx
gui/src/renderer/markdown-formatter.tsx
gui/src/renderer/redux/settings/reducers.ts
gui/src/shared/daemon-rpc-types.ts

This PR adds the ad and tracker blocking settings to the desktop app. To be able to show bold text in the translations I added support for the markdown syntax for making text bold, and a very simple implementation.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2755)

Add ad/tracker blocking settings to desktop app

---

android/translations-converter/src/gettext/msg_string.rs
android/translations-converter/src/normalize.rs

My initial plan for this PR was to implement the full escape sequences supported by gettext to make this future proof, but as I dug into the details I realized that's more complicated than what initially expected. So this PR just improves the escaping to cover "most" cases.
Gettext messages follow the same escape rules as C strings. That leads to some weird situations, because C strings aren't exactly UTF-8, and things can get weird, like `"\x1FF"` is undefined behavior, `'\e'` is not standardized, and `"\u00C1"` can become one or two bytes, depending on the implementation. (Examples taken from [Wikipedia](https://en.wikipedia.org/wiki/Escape_sequences_in_C)).
Therefore, this PR only handles escaping some of the most common character sequences. The PR also improves handling single quotes, …

Improve gettext message escaping

---

ios/MullvadVPN/AccountViewController.swift
ios/MullvadVPN/AppStorePaymentManager.swift
ios/MullvadVPN/MullvadRest.swift

Git checklist:
This PR fixes the regression in REST API handling where `/v1/create-apple-payment` was not properly handling both `200` and `201` responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2757)

REST: handle HTTP 200 and 201 in /v1/create-apple-payment

---

ios/MullvadVPN/MullvadRest.swift

Git checklist:
Although undocumented, the API returns HTTP status `200` in response to `POST v1/wireguard-keys` if the given pubkey is already registered with the server. Since the app is not really interested in such subtle difference, we should just carry on with the returned associated addresses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2764)

REST: handle 200 in POST to v1/wireguard-keys

---

ios/MullvadVPN/ConnectMainContentView.swift

Git checklist:
Seems like I forgot to disable user interactions on the map. This PR fixes this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2765)

Map: disable user interaction

---

CHANGELOG.md
mullvad-rpc/src/https_client_with_sni.rs

The hostname part of a URI would always be parsed as a socket address, or when that inevitably fails, it'd be parsed into an IP address and then combined with port 443 to be turned into a socket address. URI is actually already properly parsed by hyper, thus the port is already separated and parsed, so that is now used. If a port isn't a part of the specified URI, only then is 443 used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2773)

Use port from URI instead of always using 443 when connecting to the API

---

Cargo.lock
android/src/main/res/values-ja/plurals.xml
android/translations-converter/Cargo.toml
android/translations-converter/src/gettext/match_str.rs
android/translations-converter/src/gettext/messages.rs
android/translations-converter/src/gettext/mod.rs
android/translations-converter/src/gettext/msg_string.rs
android/translations-converter/src/gettext/parser.rs
android/translations-converter/src/gettext/plural_form.rs
android/translations-converter/src/main.rs

The previous implementation of the `gettext` file parser was a bit brittle and hard to maintain. This PR refactors it so that it's a separate type implemented as a state-machine. This makes it easier for documenting each state and what input matters for each state. The parser will now also return errors to properly indicate what went wrong.
The refactor also exposed a bug in the previous implementation, where messages that were split among multiple lines weren't parsed correctly. Only the first line was considered and the rest was ignored. This is now fixed by the new parser implementation, and let to some updates to the Japanese plural translations.
One downside of the refactor is that the `match_str!` macro become a lot more complicated. I moved it to its own module, and tried to …

Refactor gettext parser in the translations converter tool

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProvider.kt
android/src/test/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProviderTest.kt

Previously, the Split Tunneling screen wasn't showing TV-only apps, like Netflix or Prime Video. The reason was that since these apps are TV-only, they don't have normal launch intents, and have leanback launch intents instead. The filtering code to determine which apps to show filtered out apps without normal launch intents.
This PR changes the filtering code to only filter out apps that have neither a normal launch intent nor a leanback launch intent.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2772)

Fix split tunneling support for TV-only apps

---

CHANGELOG.md
mullvad-daemon/src/account_history.rs

Previously, starting the daemon with a non-existent account history file resulted in the following error:
```
[2021-06-01 17:21:53.771][mullvad_daemon::account_history][WARN] Error: Failed to read+deserialize account history
Caused by: EOF while parsing a value at line 1 column 0
```
This was because it tried to parse newly created history files. The error is pretty harmless as it is ignored, though.
This PR fixes it by not trying to parse a newly created history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2780)

Fix empty account history error

---

CHANGELOG.md
Cargo.lock
talpid-core/Cargo.toml
talpid-core/src/routing/windows.rs
talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs
talpid-core/src/tunnel/windows.rs
talpid-core/src/tunnel/wireguard/connectivity_check.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/wireguard_go.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
wireguard/libwg/libwg_windows.go

Previously, the daemon had a five-second timeout for waiting on the `MibAddInstance` event (i.e., for IP interfaces to attach to the tunnel device) after setting up a new Wintun device. Early after a reboot, this can take considerably more time to occur on some machines (30 seconds or more), causing some machines to get stuck in the error state, especially with auto-connect enabled.
The previous code blocked the tunnel state machine, so it had to time out quickly. To extend/remove the timeout, the tunnel monitors were updated to do this asynchronously/on a separate thread. The blocking code was also removed from `libwg` and now uses the same code as the openvpn tunnel monitor.
--- …

Give Windows more time to init IP interfaces

---

CHANGELOG.md
gui/src/main/index.ts

This PR adds a workaround for [this Electron issue](https://github.com/electron/electron/issues/28776) which causes other menubar context menus to remain open after opening our app.
This solution doesn't allow VoiceOver to focus the window properly but VoiceOver didn't work when the other context menus were ontop of our window either. VoiceOver still works as expected if the window is opened by launching the app when already running from the dock, spotlight or other methods.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2781)

Add workaround for closing context menus on macOS 11

---

talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel_state_machine/connected_state.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-core/src/tunnel_state_machine/mod.rs
talpid-openvpn-plugin/src/lib.rs

Previously, the driver was not given the IP address of the tunnel interface until it had reached the `Connected` state. This is usually fine: All TCP connections where the destination addresses is a public IP address are redirected to the specified non-tunnel interface. Also, non-TCP (eg UDP) sockets that are bound to 0.0.0.0 (or implicitly bound) are rebound correctly. UDP sockets that were explicitly bound to the tunnel interface could still communicate inside the tunnel, though.
This PR addresses this by registering tunnel address with the driver in the `InterfaceUp`  tunnel event, before routes are set up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2785)

Fix small into-tunnel leak window for excluded apps

---

ios/MullvadVPN/ConnectMainContentView.swift
ios/MullvadVPN/DisconnectSplitButton.swift
ios/MullvadVPN/TranslucentButtonBlurView.swift

Git checklist:
This PR adds visual effect view with blur effect behind "Select location" and "Disconnect" buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2789)

Add blur behind buttons

---

build.sh
prepare-release.sh

Just doing `source env.sh` automatically passes all command line arguments from the parent script down to `env.sh`. This does not work as `env.sh` expects the target as the first argument, which is not what we have as arguments to `prepare_release.sh`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2792)

Fix broken prepare_release.sh. Don't pass args to env.sh

---

CHANGELOG.md
talpid-core/src/offline/linux.rs

This change causes the Linux offline monitor to evaluate the offline status in response to more events, namely routing table changes. This is necessary due to how the offline monitor currently responds to a suspend/resume cycle. On the affected system (Arch Linux using systemd-networkd), before suspending, the network connection is disabled which causes the offline monitor to go into a blocked state. When resuming, the network connection is restored, and the routing table recreated, which should cause the offline monitor to reevaluate the offline status and unblock. Before this change, the offline monitor does not receive these events and remains blocked.
Specifically, this PR adds …

Make linux offline monitor aware of routing table changes.

---

CHANGELOG.md
Cargo.lock
talpid-core/src/dns/android.rs
talpid-core/src/dns/linux/mod.rs
talpid-core/src/dns/linux/routing.rs
talpid-core/src/dns/linux/systemd_resolved.rs
talpid-core/src/dns/macos.rs
talpid-core/src/dns/mod.rs
talpid-core/src/dns/windows/mod.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/tunnel_state_machine/mod.rs
talpid-dbus/Cargo.toml
talpid-dbus/src/systemd_resolved.rs

Previously, only the tunnel interface had its DNS config updated when using systemd-resolved. This no longer works. Since there's no way to set a global config using D-Bus, resolvectl, etc., this PR monitors the routing table to determine the correct interfaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2761)

Assign local DNS servers to correct interfaces with systemd-resolved

---

CHANGELOG.md
mullvad-daemon/src/cli.rs
mullvad-daemon/src/main.rs
mullvad-daemon/src/system_service.rs

Sometimes, e.g. when `openvpn.exe` cannot be killed gracefully, it can take around 30 seconds to stop the service. `net stop mullvadvpn`, which was used to restart the service after resuming from "hibernation", has a timeout that is approximately 30 seconds as well, so it sometimes fails before the daemon has stopped. Rather than relying on `cmd /c "net stop mullvadvpn & net start mullvadvpn"`, a `--restart-service` option was added, and `mullvad-daemon --restart-service` is run instead. This has a timeout of two minutes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2793)

Fix issue of daemon not restarting when "fast startup" is enabled

---

talpid-core/src/tunnel/openvpn/mod.rs

The daemon closes OpenVPN by dropping a handle. OpenVPN spawns a thread that waits for this to occur, and sets a "signal" variable when it does: https://github.com/mullvad/openvpn/blob/f38b92ee84af4d3581307c3b0f13591a52c1ca3c/src/openvpn/openvpn.c#L144. Sometimes this may occur before that variable is cleared, though, causing the released handle to be ignored.
This PR works around the issue. The changes can be reverted once the patch has been fixed and OpenVPN rebuilt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2794)

Kill openvpn correctly early on

---

talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-openvpn-plugin/proto/openvpn_plugin.proto
talpid-openvpn-plugin/src/lib.rs
talpid-openvpn-plugin/src/processing.rs

This PR updates the OpenVPN tunnel monitor to stop relying on panics for error handling and execute async/sync code correctly.
Implementing all event handling in the service trait (with async methods) was a simple improvement over using a sync callback function.
Instead of panicking, errors are returned to `talpid-openvpn-plugin`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2797)

Improve OpenVPN event handling

---

talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
talpid-openvpn-plugin/proto/openvpn_plugin.proto
talpid-openvpn-plugin/src/lib.rs
talpid-openvpn-plugin/src/processing.rs

The last PR (#2797) was reverted. It turns out that returning an error in the route up event didn't *reliably* shut down the monitor. Often it would just keep going. To fix this, the event server is now told to shut down if an error occurs. This doesn't work unless the client is also dropped, so the plugin was updated to drop the client as well.
Only the last commit differs from the previous PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2799)

Refactor OpenVPN event handling

---

CHANGELOG.md
gui/src/main/notification-controller.ts

Due to [this Electron bug](https://github.com/electron/electron/issues/27088) system notifications on Windows with `timeoutType: never` calls the notification action when pressing close, e.g. pressing the "Close" button on the account expiry notification opens the account page in a browser. This PR simply disables actions for notifications with `timeoutType: never` on Windows.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2803)

Disable notification action on persistent notifications on Windows

---

CHANGELOG.md
gui/src/main/index.ts

`suggestedIsBeta` wasn't always sent to the renderer resulting in the GUI sometimes using the wrong update-URL.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2800)

Fix suggestedIsBeta propagation

---

CHANGELOG.md
mullvad-rpc/src/rest.rs

When an API request fails while the tunnel state machine is entering the connecting state, the API address cache tries to switch to a different address. It waits for the tunnel state machine to handle `TunnelCommand::AllowEndpoint`. At the same time, the tunnel state machine waits for the daemon to provide it with tunnel parameters (via `GenerateTunnelParameters`). This results in a deadlock.
To fix this, the REST request handler spawns a separate task for updating the address cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2809)

Fix deadlock when entering the connecting state

---

CHANGELOG.md
windows/winnet/src/winnet/networkadaptermonitor.cpp
windows/winnet/src/winnet/networkadaptermonitor.h

`NotifyIpInterfaceChange` is used to monitor changes to network interfaces and determine whether any of them are online. `GetIfEntry2` is then used to look up network adapter details given a LUID.
Sometimes `GetIfEntry2` is called after a network adapter has already been deleted, which logs an error and might leave behind a "ghost" adapter. If the last state of the adapter indicated that it was connected, this might cause the offline monitor to always believe that the machine is online.
The PR fixes this by handling the case where an adapter has been deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2812)

Handle deleted devices in the offline monitor

---

CHANGELOG.md
gui/src/config.json
gui/src/main/account-data-cache.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/AppButton.tsx
gui/src/renderer/components/Connect.tsx
gui/src/renderer/components/ExpiredAccountAddTime.tsx
gui/src/renderer/components/ExpiredAccountErrorView.tsx
gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx
gui/src/renderer/components/HeaderBar.tsx
gui/src/renderer/components/MainView.tsx
gui/src/renderer/components/RedeemVoucher.tsx
gui/src/renderer/containers/ExpiredAccountErrorViewContainer.tsx
gui/src/renderer/lib/transition-rule.ts
gui/src/renderer/redux/account/actions.ts
gui/src/renderer/redux/account/reducers.ts
gui/src/renderer/routes.tsx
gui/src/renderer/transitions.ts
gui/src/shared/daemon-rpc-types.ts

This PR improves the setup process by adding screens that walk users through the process of adding time and getting started. Some other changes were made to make this possible:
* Separate `Connect.tsx` into two views, one with the map and one for the out of time views
* Adding the result of `submitVoucher` to `account-data-cache.ts` instead of just storing it in the Redux state
* Save the previous expiry date when there's a new one (this is used to make it possible to show the amount of days that was added)
* Make it possible to remove all history before the current location to make it the root location
* Add callback parameter to functions in `history` that changes the location, these callbacks are then passed to listeners and in this case called when the animation is finished
* Made …

Improve out of time and new account screens

---

dist-assets/windows/installer.nsh

#2813 gives the option to decide what to do if the uninstaller returns an error or refuses to run. The default behavior is to ignore any errors, so we checked for the presence of "uninstall.log" to infer that it failed. Aside from getting rid of that hack, the installer can now always refuse to continue if some old files could not be deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2814)

Handle uninstaller errors correctly

---

README.md

This PR updates the Node.js version requirement from 12 to 14 in the readme. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2820)

Update Node.js version requirement in readme

---

CHANGELOG.md
gui/locales/messages.pot
gui/src/shared/notifications/update-available.ts

This PR changes the app update notification when the suggested version is a beta version. It then adds the fact that it's a beta and displays the version number as well.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2821)

Update the app update notification to specify if it's a beta version

---

CHANGELOG.md
gui/src/renderer/components/Login.tsx

Since the remove button in the account history is located in a form it submits the form when clicked. This PR solves this by calling `event.preventDefault()` in the callback. I've also removed the `onClick` on the submit button since that automatically submits the form and the form already has `onSubmit` specified.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2825)

Prevent login form from submitting when clearing history

---

gui/src/main/index.ts
gui/src/main/windows-pe-parser.ts
gui/src/main/windows-split-tunneling.ts

This PR contains code for retrieving an applications name from the resource tree within the exe-file. This is used when displaying the name of excluded applications that has been added with the file-picker.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2720)

Read application name from exe-file

---

talpid-core/Cargo.toml

Some recent OpenVPN changes to `talpid-core` relied on the `fs` feature of `tokio`, but the crate manifest wasn't updated to reflect these changes, so `cargo build -p talpid-core` would fail. I've added the `fs` feature now, so it should all just work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2815)

Add missing 'fs' feature to tokio

---

CHANGELOG.md
talpid-core/src/split_tunnel/windows/driver.rs
talpid-core/src/tunnel_state_machine/mod.rs

Previously, firewall initialization would fail if there filters left by the ST driver. This occurred when the daemon hadn't stopped as expected and cleaned them up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2831)

Remove filters added by the ST driver before initializing the firewall

---

CHANGELOG.md
talpid-core/src/split_tunnel/windows/driver.rs
talpid-core/src/split_tunnel/windows/windows.rs

The settings may contain excluded paths on drives that no longer exist (e.g., USB drives). This causes the daemon to fail to add new paths and to set them when starting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2832)

Ignore excluded paths on non-existent drives

---

gui/src/main/windows-split-tunneling.ts

This PR improves the offset calculation while iterating over the resource tree nodes. This was brought up here: https://github.com/mullvad/mullvadvpn-app/pull/2720#pullrequestreview-660190665.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2834)

Improve resource table parsing

---

gui/src/renderer/components/Login.tsx

This PR changes the behavior of the footer and account history on the Login page to not hide/show depending on whether or not the account number field is focused. Instead it only hides during and after log in. We talked about this long ago but since both the account history and footer didn't fit at the same time we didn't do anything then. Now when we've shortened the account history to 1 item this is much easier.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2829)

Prevent account history and Login footer from hiding

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AdvancedSettingsStyles.tsx

This PR removes the margin below the "Split Tunneling" navigation cell in advanced settings when the option isn't available. I also fixed a typo.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2836)

Remove split tunnel button margin on macOS

---

android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt

When moving to a split-process implementation, a bug was introduced due to the main activity never handling requests from the VPN service to ask for the VPN permission. I've fixed this by adding a handler for the request that does in fact ask the permission. 
Unrelatedly, I've also removed `android/.idea` because the commited config rendered my android studio unable to build anything. Since we don't rely on android studio to build our app, I've removed the config and added the directory to `.gitignore`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2807)

Fix android vpn permission request

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppStorePaymentManager.swift
ios/MullvadVPN/en.lproj/AppStoreSubscriptions.strings
ios/README.md
ios/pylintrc
ios/requirements.txt
ios/update_translations.py

Git checklist:
1. Add localization automation script that runs `genstrings` tool coming with Xcode to extract localizable string identifiers and developer comments along with default values (when provided) from source code and then merge it with existing base localization (`en.lproj`) catalogue; preserving existing translations and updating comments.
2. Extract AppStore subscription localizations from `AppStorePaymentManager.swift` as an example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2838)

iOS: localization automation

---

gui/src/renderer/components/ExpiredAccountErrorView.tsx

This PR removes the `disabled` prop on the redeem voucher button on the out of time view since API calls won't be blocked. This one was forgotten when changing the same thing on other buttons.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2840)

Make redeem voucher button always enabled

---

CHANGELOG.md
gui/src/main/account-data-cache.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/Account.tsx
gui/src/renderer/components/Settings.tsx
gui/src/renderer/containers/AccountPage.tsx
gui/src/renderer/containers/SettingsPage.tsx
gui/src/shared/account-expiry.ts
gui/src/shared/ipc-schema.ts
gui/test/account-data-cache.spec.ts

This PR improves the logic behind when we update the account data expiry. The changes include:
* Fetch account data on `focus` event instead of `show` since `show` isn't called in unpinned mode
* Only fetch on `focus` if less than 4 days left
* Lower cache validity duration to 10 seconds when out of time
* Fetch account data when opening settings and account page
* Stop fetching every minute when account has expired
* Stop using term `expiry` for cache and instead describe it as validity to avoid confusion with account `expiry`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2843)

Improve account data fetching

---

CHANGELOG.md
mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-types/src/endpoint.rs
mullvad-types/src/relay_constraints.rs
talpid-types/src/net/wireguard.rs

Previously, the WireGuard "entry peer" was always obtained after the exit (i.e., "normal") relay was decided. This could be an issue if a specific entry relay constraint were set, e.g. a hostname, that was a subset of the exit location constraint. The same peer could be selected for both exit and entry.
To fix this, the entry relay is now selected before the exit relay if the entry location constraint is more specific than the exit location constraint, and vice versa if the exit location constraint is more specific than the entry relay constraint. For example, if the entry location constraint is a city and the entry location constraint is a country, the exit peer is decided first.
Some unit tests were also added to test the changes in this PR.
--- …

Fix WireGuard entry relay selection

---

CHANGELOG.md

Upgrade OpenVPN to 2.5.3. This also includes a patch that fixes an issue where OpenVPN would not shut down gracefully, which mostly caused issues on Windows when the daemon tried to restart itself after resuming from hibernation. See https://github.com/mullvad/mullvadvpn-app-binaries/pull/86.
Related: #2793
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2846)

Update OpenVPN to 2.5.3

---

gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/shared/ipc-schema.ts

This PR fixes a bug which made the translations revert after switching to/from pinned window after changing language. The translations wasn't saved when switching language and since we create a new window when switching to/from pinned window we used the old ones.
I've also removed `locale` in `initialState` since it's redundant. We have the same value in `initialState.translations.locale`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2849)

Fix reverting translations

---

mullvad-rpc/src/tcp_stream.rs

A [previous PR](#2848) caused `poll_write` to be called even after a TCP stream had been shut down. Returning `Ok(0)` from `poll_write` does not seem to tell the caller that the stream is closed. Returning an error fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2853)

Fix `TcpStream` reset

---

gui/src/main/window-controller.ts
gui/src/renderer/app.tsx

This PR:
* Changes the initialization of `history` to be done later and to be done with the correct path
* ~~Adds possibility to listen to ipc calls for one event only~~
* Makes main process wait until fonts are loaded before calling `show()` on renderer window.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2857)

Make sure history is initialized with correct path and make frontend wait until fonts are loaded before showing window

---

ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/ConnectMainContentView.swift
ios/MullvadVPN/HeaderBarView.swift
ios/MullvadVPN/RootContainerViewController.swift

Git checklist:
1. Properly update `accessibilityElements` on the `RootContainer` view to set the order in which voice over navigates between child views.
2. Post`Accessibility.screenChanged` notification when changing view controllers in `RootContainer`. This tells accessibility runtime to update the accessibility tree and note new views etc..
3. Set `accessibilityContainerType` to `semanticGroup` on header bar and main content view (with tunnel status), which includes the marked views into "Containers" group in rotor control and enables quick navigation between them.
_Note: as the case with many standard controls, `UITableView` with relay locations is automatically marked as container so we …

Root container accessibility

---

ios/MullvadVPN/CustomTextView.swift
ios/MullvadVPN/ProblemReportViewController.swift

Git checklist:
1. Hide placeholder label from accessibility engine in `CustomTextView`. Instead announce it via `accessibilityLabel` when the text is empty.
2. Respect `roundCorners` setting in `accessibilityPath` when producing the accessibility focus shape.
3. When entering the problem report description, the text view is being expanded to fill the entire screen. Make sure to communicate that to accessibility engine to prevent it from navigating to views beneath the text view when expanded. This is achieved by raising the `accessibilityViewIsModal` flag.
--- …

Accessibility: Problem report

---

ios/MullvadVPN/AppButton.swift
ios/MullvadVPN/PreferencesViewController.swift
ios/MullvadVPN/SettingsSwitchCell.swift

Git checklist:
- Add `.link` trait on privacy policy button (`LinkButton`). This makes voice over add "Link" after announcing the button title.
- Group settings cells with switch toggle control to behave as single control; implement default accessibility action (double tap) to toggle state. Similar to how Wi-Fi cell works in System Settings app on iOS 15.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2860)

Accessibility: Preferences

---

ios/MullvadVPN/ConnectMainContentView.swift
ios/MullvadVPN/PreferencesViewController.swift
ios/MullvadVPN/SelectLocationHeaderView.swift
ios/MullvadVPN/SettingsViewController.swift
ios/MullvadVPN/UIMetrics.swift
ios/MullvadVPN/WireguardKeysContentView.swift

Git checklist:
1. Add metric for inter button spacing in static views. Normally 16pt
2. Add section spacing to pad various sections of screen or sections in table views. Usually 24pt and is the same as `contentLayoutMargins.top`, which was often used instead, but I figured it deserves an individual constant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2862)

Add more UI metrics

---

gui/locales/messages.pot
gui/src/renderer/components/ErrorBoundary.tsx
gui/src/renderer/components/HeaderBar.tsx
gui/src/renderer/components/Launch.tsx

This PR prevents `MULLVAD VPN` in the header bar from being translated. This aligns the text with Android and iOS.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2880)

Prevent header bar title from being translated

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/ConsentContentView.swift
ios/MullvadVPN/en.lproj/Consent.strings

Git checklist:
* 
This PR moves localizations found in a privacy controller displayed on the very first run, into a separate `Consent.strings` table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2870)

Consent screen localization

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/PreferencesViewController.swift
ios/MullvadVPN/en.lproj/Preferences.strings

Git checklist:
This PR moves localizable strings found in Preferences controller into a separate `Preferences.strings` table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2872)

Preferences localization

---

ios/MullvadVPN/SelectLocationViewController.swift

Git checklist:
This PR reorders accessibility elements in "Select Location" controller to ensure that the table header or footer receives the accessibility focus first before the relay list. 
This is especially important on iPad where the description is displayed at the bottom of the view before the list of relays. 
The rationale behind is that it would be really difficult to reach the description label using only horizontal swipe gesture, when it's located at the bottom, it would require going through all of the relay locations first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mull …

Select location: reorder accessibility elements

---

ios/MullvadVPN/Notifications/AccountExpiryNotificationProvider.swift
ios/MullvadVPN/en.lproj/Localizable.strings

Genstrings tool does not automatically pick up NSString.localizedUserNotificationString
Git checklist:
Add no-op `NSLocalizedString` calls for the parser to pick up the translations for system notifications. `NSString.localizedUserNotificationString` marks the string IDs for the system to pick up from `Localizable.strings` but the parser itself does not extract the identifiers from these calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2881)

Declare localizations used in system notifications 

---

ci/buildserver-upload.sh

We have a new artifact server at `releases.mullvad.net`. This patch to our upload script pushes artifacts there as well as to the older `build.mullvad.net`. When the new server has been confirmed to work well we'll deprecate `build.mullvad.net` and remove the upload to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2889)

Rsync built artifacts to releases.mullvad.net

---

CHANGELOG.md
talpid-core/src/dns/linux/systemd_resolved.rs
talpid-dbus/src/systemd_resolved.rs

If a user has enabled DNS over TLS globally in `systemd-resolved` via editing `/etc/systemd/resolved.conf` and set `DNSOverTLS` to `yes`, then our daemon will fail to configure DNS for our tunnel interface, as systemd-resolved will always try to use DoT with our interface. To remedy this, I've added a call to `SetDNSOverTLS` to disable DoT for our interface.  This should fix #2893.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2895)

Always disable DNS over TLS in systemd-resolved

---

gui/gulpfile.js
gui/tasks/distribution.js

Recursive `rmdir` is deprecated in Node 15. This PR replaces recursive `rmdir` calls with recursive `rm`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2887)

Replace recursive rmdir with rm

---

CHANGELOG.md
gui/src/renderer/app.tsx

This PR fixes the issue where the notification button didn't work for some notifications. The problem was that `openLinkWithAuth` didn't have the correct `this`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2907)

Make openLinkWithAuth arrow function to preserve this

---

android/docker/Dockerfile

I've changed the android build dockerfile to stop depending on a specific rust version and remove the dependency on nodejs. This makes the docker image buildable for now, but the dependency on the hash of the rustup installation script will break often anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2910)

Fix Android dockerfile

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/MtuCell.kt
android/src/main/res/layout/advanced_header.xml

This PR contains fix for wireguard MTU input field. In some scenarios the value was erased because of the wrong focused state of input field.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2911)

Fix wireguard mtu erase value bug

---

gui/locales/messages.pot
gui/src/main/index.ts
gui/src/shared/localization-contexts.ts

This PR removes the last instance of `Mullvad VPN` being translated since we don't want to have that translated.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2908)

Remove last translation of 'Mullvad VPN'

---

CHANGELOG.md
gui/src/main/daemon-rpc.ts
mullvad-cli/src/cmds/relay.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-management-interface/src/types.rs
mullvad-rpc/src/relay_list.rs
mullvad-types/src/relay_constraints.rs
mullvad-types/src/relay_list.rs
mullvad-types/src/settings/migrations/mod.rs
mullvad-types/src/settings/migrations/v1.rs
mullvad-types/src/settings/migrations/v2.rs
mullvad-types/src/settings/migrations/v4.rs
mullvad-types/src/settings/mod.rs

This previously existed only for custom relays. The PR adds the option for normal relays. Because the relay list does not currently include ports/TCP endpoints, all WireGuard relays are assumed to run `tcp2udp` on a set of hardcoded ports.
Usage:
> mullvad relay set tunnel wireguard any --protocol tcp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2856)

Add WireGuard transport protocol constraint

---

CHANGELOG.md
gui/src/renderer/components/NavigationBar.tsx
gui/src/renderer/components/NavigationBarStyles.tsx
gui/src/renderer/components/SelectLocationStyles.tsx

This PR changes how the navigation bar title is positioned. Previously it was done by having refs for each element in the navigation bar and then calculating the correct position of the title and updating it. With this solution we had some positioning issues that occasionally happened due to the code running before the browser had finished painting. The new solution is much simpler and only consists of CSS.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2914)

 Position navbar content with css

---

CHANGELOG.md
mullvad-daemon/src/relays.rs

Previously, on Windows, the relay selector would fail to pick a relay if the tunnel protocol constraint was `any` and the location constraint didn't match any OpenVPN relays, e.g. if a specific WireGuard hostname was used. This PR fixes that, and adds some tests for tunneling protocol preference/selection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2915)

Fix tunnel protocol preference

---

gui/src/renderer/components/NavigationBar.tsx

This PR changes the "close"-icon in the navigation bar to always be the down arrow since we didn't see a reason to have different icons when this one works in all situations.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2916)

Switch to always using icon-close-down for dismiss navigations

---

gui/locales/messages.pot
gui/src/renderer/components/SelectLocation.tsx
gui/src/renderer/components/SelectLocationStyles.tsx
gui/src/renderer/components/SettingsHeader.tsx

This PR updates the header behavior in the select location view. It's changed to have the heading scroll away but keep the filter-row and enty-/exit-location buttons fixed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2913)

Make select location heading scroll away but have controls fixed

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/AdvancedSettingsStyles.tsx
gui/src/renderer/components/SplitTunnelingSettings.tsx
gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx

This PR removes the yellow "BETA" icon in the split tunneling title and navigation cell.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2923)

Remove beta label for split tunneling on Windows

---

CHANGELOG.md
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/shared/ipc-schema.ts

This PR adds a timer that resets the navigation to the main view after the window has been hidden for two minutes. Fixes https://github.com/mullvad/mullvadvpn-app/issues/2878.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2917)

Reset navigation after window being hidden for two minutes

---

gui/src/main/daemon-rpc.ts
mullvad-cli/src/cmds/relay.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-management-interface/src/types.rs
mullvad-types/src/relay_constraints.rs
mullvad-types/src/settings/migrations/v1.rs
mullvad-types/src/settings/migrations/v2.rs
mullvad-types/src/settings/migrations/v3.rs
mullvad-types/src/settings/migrations/v4.rs

This refactors the OpenVPN relay constraints to use the `TransportPort` type introduced in #2856.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2919)

Add `TransportPort` OpenVPN constraint

---

gui/src/main/index.ts
gui/src/renderer/app.tsx

This PR moves the auto connection logic from the renderer process to the main process to prevent auto connecting when switching between pinned and unpinned window. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2924)

Prevent app from autoconnecting after changing between pinned/unpinned

---

gui/src/renderer/components/HeaderBar.tsx
gui/src/renderer/components/NavigationBarStyles.tsx
gui/src/renderer/components/SelectLocation.tsx

* Change settings button opacity to 60% which is closer to what it was before https://github.com/mullvad/mullvadvpn-app/pull/2906
* Correct incorrect opacity for some navigation bar icons.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2930)

Change settings button opacity to 60%

---

ios/CHANGELOG.md
ios/MullvadVPN/ConsolidatedApplicationLog.swift
ios/MullvadVPN/ProblemReportViewController.swift

Git checklist:
1. Add log backups (`old.log`) to problem reports
2. We include the trailing 128k of each log file. When decoding those bytes into UTF-8, the parser replaces the malformed UTF-8 sequence with a replacement character (`\u{FFFD}`). Handle this by dropping the leading replacement characters before including the log file into the final problem report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2929)

Add backup logs in report

---

mullvad-types/src/settings/migrations/v3.rs

Previously, the current settings version number was incorrectly set to `v3`, even though it should have been `v4`. https://github.com/mullvad/mullvadvpn-app/commit/53374768f9ac5b51c9a0830bc1d339aefa09c947 fixes this, but the last release still produces flawed settings. On master, all DNS options are reset if such a file is "migrated" to the newer format.
This PR updates the old migration code to not overwrite the newer fields if they exist, making it safe to run anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2933)

Don't purge DNS options if v3 settings are invalid

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Promise/AnyOptional.swift
ios/MullvadVPN/Promise/AnyResult.swift
ios/MullvadVPN/Promise/Promise+Optional.swift
ios/MullvadVPN/Promise/Promise+ReceiveOn.swift
ios/MullvadVPN/Promise/Promise+Result.swift
ios/MullvadVPN/Promise/Promise.swift
ios/MullvadVPN/Promise/PromiseCompletion.swift
ios/MullvadVPN/Promise/PromiseObserver.swift
ios/MullvadVPNTests/PromiseTests.swift

Git checklist:
This PR adds Promise implementation with the following features:
1. Promises can be chained to transform the value using `Promise.then`.
2. The state of `Promise` can be observed with `Promise.observe`. The first call to that method also starts the `Promise`'s execution.
2. Promises can either be resolved with value or cancelled. The value can be `Result` itself, so the `Error` is basically not a part of `Promise` but rather a part of `Value` it holds.
3. Promises can be cancelled. Cancelling the downstream promise does not cancel the upstream ones. This is intentional.
4. Promises do not have to be explicitly retained as `PromiseResolver` passed to the promise's body retains the …

Add promise

---

gui/src/renderer/app.tsx
gui/src/renderer/redux/connection/actions.ts

This PR replaces the outdated location information, that is displayed between pressing `connect` and receiving the daemon event with the new location, with the country, city and hostname in the location constraints. Another thing that has been changed is that the disconnect and reconnect buttons now also update the renderer state immediately to make the app feel more responsive.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2934)

Fix showing outdated connection information

---

gui/locales/messages.pot
gui/src/renderer/components/SelectLocation.tsx

This PR adds back the text explaining how the select location view works when bridge mode is on. It was erroneously removed in https://github.com/mullvad/mullvadvpn-app/pull/2905.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2935)

Add back text in Select location view when bridge mode is on

---

README.md

iOS was simply outdated. We have supported iOS 12 for a long time now. We will likely drop it sometime relatively soon, but this table should be correct until then.
For Ubuntu there was a disconnect between the readme and the support team. In practice we only support the latest non-LTS release of Ubuntu, and not the two latest ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2941)

Update platform support for Ubuntu and iOS

---

talpid-core/src/tunnel/wireguard/mod.rs

When using a TCP proxy for WireGuard, the local WireGuard endpoint was being used to create a set of routes for routing the tunnel traffic, instead of using the proxy endpoint. This only affected macOS and Android, as on Linux and Windows routing is done differently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2936)

Add appropriate routes for TCP proxy

---

CHANGELOG.md
README.md
gui/src/main/index.ts

I'm packaging Mullvad for [Solus OS](https://getsol.us/) and it'd be nice to disable the version check and GUI notification. Package updates are shipped to users every Friday, so the notice is really unnecessary, especially because they can't just "update" via a `.deb` or `.rpm`.
I've added a feature flag on the daemon, `disable-version-check`, which just replaces the app version request with an "empty" response that won't show as an update.
This seemed like the best place to disable this, as the `VersionUpdater` is pretty well tied into the daemon.
I've tested by patching this against 2021.3 and successfully did not see any version update notification. The output of `mullvad version` is:
```
Current version: 2021.3
Is supported: false
No newer version is available
```
Git checklist:
--- …

Disable GUI notification for newer version

---

gui/locales/da/messages.po
gui/locales/de/messages.po
gui/locales/es/messages.po
gui/locales/fi/messages.po
gui/locales/fr/messages.po
gui/locales/it/messages.po
gui/locales/ja/messages.po
gui/locales/ko/messages.po
gui/locales/messages.pot
gui/locales/my/messages.po
gui/locales/nb/messages.po
gui/locales/nl/messages.po
gui/locales/pl/messages.po
gui/locales/pt/messages.po
gui/locales/ru/messages.po
gui/locales/sv/messages.po
gui/locales/th/messages.po
gui/locales/tr/messages.po
gui/locales/zh-CN/messages.po
gui/locales/zh-TW/messages.po
gui/src/renderer/components/AdvancedSettings.tsx

This PR reverts the changes to `messages.pot` made in https://github.com/mullvad/mullvadvpn-app/pull/2909 and moves the existing translations instead.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2944)

Fix new settings views contexts

---

CHANGELOG.md
talpid-core/src/tunnel/wireguard/connectivity_check.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/stats.rs
talpid-core/src/tunnel/wireguard/wireguard_go.rs
talpid-core/src/tunnel/wireguard/wireguard_kernel/netlink_tunnel.rs
talpid-core/src/tunnel/wireguard/wireguard_kernel/nm_tunnel.rs

Previously, the ping monitor would take any traffic received from any peer to mean that the tunnel was up. This worked poorly with multihop, since the entry hop could respond even when the exit hop could not be reached, incorrectly causing the TSM to enter the connected state.
This was fixed by requiring data to be received from every peer before considering the tunnel to be up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2943)

Fix ping monitor when multiple peers are used

---

CHANGELOG.md
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/Connect.tsx
gui/src/renderer/components/SecuredLabel.tsx
gui/src/renderer/components/TunnelControl.tsx
gui/src/shared/ipc-schema.ts

This PR contains fixes for a bunch of issues relating to the connection info in the main view:
* Showing "SECURE CONNECTION" while disconnecting
* Showing the location of the previously connected server while disconnecting
* Showing information about the previous connection before receiving new information while connecting and reconnecting
* Having a delay when entering the disconnecting state (disconnect and reconnect). This is due to the time it takes before the frontend receives the daemon event with the new tunnel status.
To fix these issues I've made the following changes:
* Remove the status label while disconnecting
* Move all location handling code to the renderer since that's where it's used
* Use the location from when last disconnected while disconnecting
* Use location …

Improve connection info

---

mullvad-daemon/src/management_interface.rs
mullvad-management-interface/src/types.rs

There seems to be a lot of repetition when it comes to handling errors from converting GRPC types into daemon types. I've factored the reoccuring closure into a function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2947)

Improve management interface error handling

---

gui/src/renderer/app.tsx

Previously the next tunnel state variable wasn't reset which caused prevented the connect button from working after connecting/disconnecting from another frontend/instance.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2949)

Reset next tunnel state in renderer on update

---

gui/src/renderer/components/CustomDnsSettings.tsx

This PR adds a missing dependency to the `setCustomDnsEnabled` hook. It being missing made it use old data resulting in unexpected behavior hen disabling the feature after enabling it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2950)

Add missing hook dependency for setCustomDnsEnabled

---

gui/src/renderer/app.tsx
gui/src/renderer/components/CustomDnsSettings.tsx

This PR corrects a mistake I made in https://github.com/mullvad/mullvadvpn-app/pull/2940. The out-ip wasn't available since `fetchLocation` wasn't called.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2951)

Make sure fetchLocation is always called

---

CHANGELOG.md
gui/locales/messages.pot
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/WireguardSettings.tsx
gui/src/renderer/containers/WireguardSettingsPage.tsx
gui/src/renderer/redux/settings/reducers.ts
gui/src/shared/daemon-rpc-types.ts
gui/src/shared/relay-settings-builder.ts

This PR adds the WireGuard IP version setting to the frontend.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2946)

Add WireGuard IP version setting

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Operations/ExclusivityController.swift
ios/MullvadVPN/Promise/Promise+BackgroundTask.swift
ios/MullvadVPN/Promise/Promise+OperationQueue.swift
ios/MullvadVPN/Promise/Promise+Optional.swift
ios/MullvadVPN/Promise/Promise+ReceiveOn.swift
ios/MullvadVPN/Promise/Promise+Result.swift
ios/MullvadVPN/Promise/Promise.swift
ios/MullvadVPN/Promise/PromiseCompletion.swift
ios/MullvadVPNTests/PromiseTests.swift

Git checklist:
1. Add `Promise.deferred`  to be able to pass lazily resolved value
2. `Promise` won't throw exception when dropped while in `pending` state, but will continue to warn when dropped while `executing`.
3. Calls to `onSuccess` and `onFailure` will chain as any other calls to avoid calling `observe()` which triggers execution.
4. `Promise.observe()` returns `Void` and is meant to be used as the final call when composing a promise chain.
5. Add extension to request background execution time from the system. `Promise+BackgroundTask`
6. Make calls to `Promise.receive(on:)` cancellable and introduce timer type.
7. Add extension to schedule work on `OperationQueue`.
8. Add …

Promise extensions

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppStoreReceipt.swift
ios/MullvadVPN/Operations/ReceiptRefreshOperation.swift

Git checklist:
1. Make sure that `ReceiptRefreshOperation` runs on a serial `OperationQueue`, since that call triggers system Apple ID sign in prompt.
2. Handle `CocoaError.fileReadNoSuchFile` when reading AppStore receipt from disk. I am pretty sure that in the past `fileNoSuchFile` was thrown instead. Map both to `AppStoreReceipt.Error.doesNotExist`.
3. Move `ReceiptRefreshOperation` to separate source file.
4. Simplify `ReceiptRefreshOperation` since I am moving away from more complex operations for many reasons, but essentially trying to reduce complexity.
--- …

Refactor AppStoreReceipt

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AlertPresenter.swift
ios/MullvadVPN/Operations/PresentAlertOperation.swift

Git checklist:
1. Make `PresentAlertOperation` cancellable.
2. Use serial `OperationQueue` (`maxConcurrentOperationCount = 1`) when serialising alert operations instead of using `ExclusivityController`. Overall simpler and simpler way to manage mutually exclusive operations in that case.
3. Add `AlertPresenter.cancelAll` method to cancel active and pending alert presentations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2956)

Refactor alert presenter

---

mullvad-daemon/src/account.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-daemon/src/version_check.rs
mullvad-daemon/src/wireguard.rs
mullvad-rpc/src/availability.rs
mullvad-rpc/src/lib.rs
mullvad-rpc/src/rest.rs
mullvad-types/src/account.rs
talpid-core/src/offline/android.rs
talpid-core/src/offline/linux.rs
talpid-core/src/offline/macos.rs
talpid-core/src/offline/mod.rs
talpid-core/src/offline/windows.rs
talpid-core/src/tunnel_state_machine/mod.rs

New behavior:
* When the daemon starts, the account validity is checked. If the account is non-existent, expired, or invalid, automatic requests to the API are delayed until `GetAccountData` is called with a valid account (or a valid voucher is submitted). These requests include: WireGuard key rotation, initial WireGuard key push, relay list updates, version checks, API IP cache rotations, etc.
* When offline, automatic requests are delayed until the machine is back online.
* The API IP is not rotated when offline and a request fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2937)

Pause/defer automatic API requests while offline or the account is invalid

---

mullvad-types/src/relay_constraints.rs

Tiny fix: Include providers in the `fmt` output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2964)

Fix display implementation for BridgeConstraints

---

CHANGELOG.md
talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs
talpid-core/src/tunnel/windows.rs

Changes:
* Disable DAD on Wintun interfaces. On my machine, this reduces the time it takes to connect by about **2.5** seconds.
* Refactor general networking code on Windows. I've moved some generic functions to `talpid_core::tunnel::windows`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2966)

Set up OpenVPN tunnels more quickly on Windows

---

gui/.eslintrc.js
gui/package-lock.json
gui/package.json
gui/src/renderer/app.tsx
gui/src/renderer/components/AccountTokenLabel.tsx
gui/src/renderer/components/BetaLabel.tsx
gui/src/renderer/components/ExpiredAccountAddTime.tsx
gui/src/renderer/components/FilterByProvider.tsx
gui/src/renderer/components/Launch.tsx
gui/src/renderer/components/MainView.tsx
gui/src/renderer/components/NotificationArea.tsx
gui/src/renderer/components/RelayStatusIndicator.tsx
gui/src/renderer/components/SecuredLabel.tsx
gui/tasks/scripts.js
gui/tsconfig.dev.json
gui/tsconfig.json

This PR enables the new JSX transform which doesn't make a big difference but according to the React blog has these benefits:
* With the new transform, you can use JSX without importing React.
* Depending on your setup, its compiled output may slightly improve the bundle size.
* It will enable future improvements that reduce the number of concepts you need to learn React.
Here's more info: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports
I've also updated `react-dom` to the latest version.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2968)

Enable new JSX transform

---

gui/locales/messages.pot
gui/src/renderer/components/SecuredLabel.tsx

This PR changes the connectivity status label for the disconnected state from "UNSECURE CONNECTION" to "UNSECURE**D** CONNECTION".
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2974)

Change "UNSECURE" into "UNSECURED"

---

talpid-core/src/tunnel/openvpn/mod.rs
talpid-core/src/tunnel/openvpn/windows.rs
talpid-core/src/tunnel/wireguard/wireguard_go.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs
wireguard/libwg/libwg_windows.go

Changes:
* Try to create Wintun devices multiple times if an error occurs. This is to work around poorly understood races/delays that can occur when resuming from hibernation or after a reboot.
* Small amount of refactoring.
* Fix incorrect return code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2970)

Fix intermittent tunnel device errors

---

.github/workflows/ios.yml

Git checklist:
This PR suppresses an overly verbose output from Xcodebuild that makes it nearly impossible to spot errors in the CI output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2988)

CI: suppress verbose output from xcodebuild

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/version_check.rs
talpid-core/src/future_retry.rs

`GetVersionInfo` updates the version cache if there's no cache yet, but it doesn't wait on the fetch to complete, causing the first call to `mullvad version` to fail if there's no cache yet. This fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2981)

Fix initial version cache fetch

---

CHANGELOG.md
talpid-core/src/offline/linux.rs

Simply check if there's an IPv6 route to some non-private address as well. The previous monitor was very broken when setting the WG IP protocol to IPv6, as the offline monitor prevented the app from connecting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2983)

Fix offline monitor on IPv6-only networks (Linux)

---

gui/package-lock.json
gui/package.json

This PR updates NSEventMonitor to 1.0.1 and updates dependencies with known vulnerabilities. `npm audit fix` was used to update transitive dependencies.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2978)

Update NSEventMonitor to 1.0.1 and dependencies with vulnerabilities

---

mullvad-daemon/src/lib.rs

`schedule_reconnect` did not abort the previous task, if there was one. Moreover, since the receiver for the reconnect command was (reasonably) dropped, `oneshot_send` logged a warning (`Unable to send reconnect issued to the daemon command sender`) which is now suppressed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2986)

Prevent multiple reconnects from being scheduled

---

talpid-core/src/split_tunnel/windows/path_monitor.rs

It's not uncommon for the log to be flooded with these messages:
```
[talpid_core::split_tunnel::imp::path_monitor][DEBUG] Change event buffer is empty
```
This seems to be because the buffer used by the path monitor is too small.
It's not super critical, so I've just enlarged the buffer and changed the log level to `trace`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2991)

Use larger buffer for `ReadDirectoryChangesW`

---

ios/MullvadVPN/Operations/AsyncBlockOperation.swift
ios/MullvadVPN/Operations/AsyncOperation.swift
ios/MullvadVPN/Operations/PresentAlertOperation.swift
ios/MullvadVPN/Operations/ProductsRequestOperation.swift
ios/MullvadVPN/Operations/ReceiptRefreshOperation.swift
ios/MullvadVPN/Promise/Promise+OperationQueue.swift

Git checklist:
This PR changes the former behaviour of `AsyncOperation` subclass, where it used to ignore calling `main()` and `finish()` itself automatically,  if it was cancelled prior to the call to `start()`. 
The new behaviour lays the responsibility of handling early cancellations on `Operation` subclasses.
This is particularly important for operations, that accept a callback and want to provide a guarantee that it will always be called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2989)

Handle early cancellation in operation subclasses

---

ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/NotificationManager.swift

Git checklist:
1. Fix a bug where `NotificationManager.delegate` was left unset after re-login.
2. Immediately deliver all existing in-app notifications when assigning the `NotificationManager.delegate`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2995)

Fix disappearing in-app notifications after re-login

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/Notifications/TunnelErrorNotificationProvider.swift
ios/MullvadVPN/en.lproj/AppDelegate.strings
ios/MullvadVPN/en.lproj/Localizable.strings

Git checklist:
Previously we used to display modal system alerts for simplicity and this functionality has been removed in one of the recent PRs. 
This PR moves the errors associated with starting or stopping the tunnel into the in-app banner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2996)

Display tunnel errors in in-app banner

---

dist-assets/linux/mullvad-gui-launcher.sh

This PR disables the Electron renderer sandbox on Ubuntu 21.10 since it doesn't work. After upgrading to Electron 15 this workaround will no longer be needed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2997)

Disable sandbox on Ubuntu 21.10

---

CHANGELOG.md
README.md
dist-assets/linux/mullvad-gui-launcher.sh
gui/package-lock.json
gui/package.json
gui/src/main/daemon-rpc.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/components/SvgMap.tsx
gui/src/renderer/components/Switch.tsx
gui/src/renderer/components/TransitionContainer.tsx
gui/src/renderer/components/WireguardKeys.tsx

This PR updates Electron from 11.4.10 to 15.0.0. The update to 12 was held back by a change in Electron/Chromium that caused the map to become blurry during transitions. I've finally found a working workaround for this. A few other changes was required as well:
* Set map CSS zoom to `100,01%` to prevent blurriness during transitions
* Set the size of `TransitionContainer` to prevent it from growing and becoming unscrollable
* Wait until switch input has finished it's transition before calling `onChange`. This is due to the transition being glitchy when communicating with the daemon at the same time.
* Writing to clipboard is now a permission which needs to be allowed.
Improvements thanks to this version:
* Removed workaround for "uncaught error" in error messages passed between the …

Update to electron 15

---

talpid-core/src/tunnel/wireguard/wireguard_kernel/wg_message.rs

Just clarifying the unsafety here. I think we in general should be way better at documenting unsafety. It took some time to figure out why this was guaranteed to be correct.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3003)

Clarify safety around struct_as_slice function

---

mullvad-daemon/src/account.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-daemon/src/version_check.rs
mullvad-daemon/src/wireguard.rs
mullvad-problem-report/src/lib.rs
mullvad-rpc/src/lib.rs
mullvad-rpc/src/rest.rs
mullvad-setup/src/main.rs
talpid-core/src/future_retry.rs

This primarily affects these account-related RPCs:
* `CreateNewAccount`
* `GetAccountData`
* `GetWwwAuthToken`
* `SubmitVoucher`
In general, a request is sent up to 3 times. On failure, the daemon will use a different endpoint to reach the API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2982)

Retry failed API requests made indirectly by frontends

---

talpid-core/src/split_tunnel/windows/mod.rs
talpid-core/src/winnet.rs

Previously, route changes _could_ occur after the initial interfaces had been registered with the driver but before the default route change callback was created. To fix this, the callback is now created before the initial interfaces have been set, but a mutex prevents any change event from being handled until `set_tunnel_addresses` has returned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2999)

Fix potential race when initializing interfaces/addresses in the ST driver

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Promise/Cancellable.swift
ios/MullvadVPN/Promise/Promise+BackgroundTask.swift
ios/MullvadVPN/Promise/Promise+Delay.swift
ios/MullvadVPN/Promise/Promise+OperationQueue.swift
ios/MullvadVPN/Promise/Promise+ReceiveOn.swift
ios/MullvadVPN/Promise/Promise.swift
ios/MullvadVPN/TunnelManager/TunnelManager.swift
ios/MullvadVPNTests/PromiseTests.swift

Git checklist:
1. Add ability to chain Promises to be able to propagate cancellation requests from downstream promises upwards, i.e:
```swift
let parent = Promise<String> { resolver in
let timer = DispatchSource.makeTimerSource()
timer.setEventHandler {
resolver.resolve("Hello")
}
timer.schedule(deadline: .now() + .seconds(2))
timer.activate()
resolver.setCancelHandler {
timer.cancel()
resolver.resolve(.cancelled)
}    
}
let child = parent.then { str in
return str + " World!"
}
child.observe { completion in
print("Finished with \(completion)")
}
// should trigger parent.cancel() too!
child.cancel()
```
2. Add `Promise.setShouldPropagateCancellation(Bool)` to be able to prevent child promise …

Add promise cancellation chain

---

android/build.gradle
android/src/androidTest/AndroidManifest.xml

JCenter has been sunset and should no longer be relied on as per:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
The migration also required the following changes:
* Updated Koin maven group id as per the official documentation at:
https://insert-koin.io/docs/setup/v2/
* Bump MockK version due to old versions of one of its dependencies'
(dexmaker) not being available at mavenCentral.
* Fix mockK instrumentation lib issue.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3006)

Migrate from JCenter to mavenCentral

---

ios/MullvadVPN/AccountViewController.swift

Git checklist:
This PR introduces a couple of adjustments to the `AccountViewController`:
1. Adapt to using new promise based `AppStorePaymentObserver ` API.
2. Adapt to new `REST` types structure.
3. Stop re-dispatching all calls to `AppStorePaymentObserver` on main queue, since `AppStorePaymentObserver ` guarantees to call all delegate methods on main queue.
4. Use `Promise.delay()` instead of `DispatchQueue.asyncAfter`.
5. Adapt to using new `Account.logout()`  interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3007)

Adapt account controller

---

CHANGELOG.md
dist-assets/linux/mullvad-gui-launcher.sh

This PR disables the Electron sandbox on Linux
Recently the Electron sandbox was disabled on Ubuntu 21.10 beta since it
didn't work in combination with newer versions of glibc. This issue is
present in beta versions of Fedora and Kubuntu as well. This is planned
to be reverted in 2021.6 since the upgrade to Electron 15 also fixes
this issue.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3010)

Disable Electron sandbox on Linux

---

CHANGELOG.md
gui/src/renderer/components/WireguardKeys.tsx
gui/src/shared/date-helper.ts

This PR fixes a bug where the app said that a WireGuard key was generated "less than a day left". This was solved by making sure that the key generated date can't be in the future.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3009)

Make sure time since key was generated is positive

---

CHANGELOG.md
gui/src/main/index.ts

This PR prevents the app from showing when dragging the tray icon on macOS.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3011)

Prevent app from showing when dragging icon on macOS

---

ios/MullvadVPN/Promise/Promise.swift
ios/MullvadVPN/TunnelManager/TunnelManager.swift
ios/MullvadVPNTests/PromiseTests.swift

Git checklist:
1. Add `doNotPropagateCancellation()` helper that returns a `Promise` that does not propagate cancellation to the parent and instead awaits the parent to complete before passing `.cancelled` to observers.
2. Use `doNotPropagateCancellation()` in critical parts of the `TunnelManager`, especially where we push new key and then save it to Keychain, these kinds of operations should execute as transactions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3012)

Promise: add doNotPropagateCancellation()

---

gui/src/renderer/app.tsx

This PR makes the renderer process handle the `disconnect(reconnect)` tunnel state event as a `connecting` event.
When the disconnecting event is received with "reconnect"  in `details`
we want the app to act like it's already reconnecting to prevent it from
showing the disconnecting state.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3018)

Switch to connecting state when receiving reconnect disconnecting event

---

CHANGELOG.md
mullvad-daemon/Cargo.toml
mullvad-daemon/src/account.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-daemon/src/version_check.rs
mullvad-daemon/src/wireguard.rs
mullvad-problem-report/src/lib.rs
mullvad-rpc/src/address_cache.rs
mullvad-rpc/src/availability.rs
mullvad-rpc/src/lib.rs
mullvad-rpc/src/rest.rs
mullvad-setup/src/main.rs

Supersedes #3065. Main changes:
* All requests are frozen (although they can still time out) until after the TSM has been constructed.
* The listener for handling address changes is set *after* the TSM is created, and the REST client is created immediately before the TSM is created.
* The relay list updater doesn't immediately check if the relay list is outdated. This was likely the thing that triggered the deadlock in the first place, when the subsequent list updated failed, although it was pretty racy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3066)

Freeze API requests made before the TSM has spawned

---

gui/src/main/window-controller.ts

This PR adds some margin in between the app and the tray on Windows 11 since that's how other tray menus/applications look.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3069)

Add margin on Windows 11

---

CHANGELOG.md
gui/src/main/daemon-rpc.ts

This is a workaround for a bug in node which causes a segfault when we close a gRPC stream. The workaround is to wrap the `.cancel()` call in a `setImmediate()`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3074)

Fix segfault while closing app

---

CHANGELOG.md
gui/src/renderer/components/AppButton.tsx
gui/src/renderer/components/AppButtonStyles.tsx

This PR makes the transparent buttons blur the background behind them.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3076)

Add blur to transparent buttons

---

scripts/install-mullvad

Update this install helper script to use the newer `releases.mullvad.net` instead of the older and soon deprecated `build.mullvad.net`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3072)

Update the installer helper script to use releases.mullvad.net

---

.github/workflows/ios.yml

Git checklist:
This PR migrates iOS tests to iOS 13 simulator runtime and macOS 11. The change is needed because older Xcode does not recognise API introduced in iOS 15 and fails to run tests even though all calls to newer API are guarded with availability checks. 
Xcode 13 on the other side, does not have that problem, however it does not come with iOS 12 simulator runtime, so I had to bump the test suite to use iOS 13 instead. 
[The alternative solution that preserves the iOS 12 runtime](https://github.com/mullvad/mullvadvpn-app/commit/1d647738d40fc3be58abf3049ce592f2c62423aa
), involves installing it on macOS 11 image and then caching it with `actions/cache@v2`, however that alone adds about …

CI: Switch to macOS 11 and iOS 13

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsAdapter.kt

Automatically disable custom DNS when no servers have been added as this better reflect the daemon behavior (which will fallback to the default Mullvad DNS servers).
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3084)

Automatically disable custom dns when no added servers

---

ios/MullvadVPN/AppButton.swift
ios/MullvadVPN/Assets.xcassets/IconArrow.imageset/Contents.json
ios/MullvadVPN/Assets.xcassets/IconExtlink.imageset/Contents.json
ios/MullvadVPN/DisconnectSplitButton.swift
ios/MullvadVPN/SettingsCell.swift
ios/MullvadVPN/SpinnerActivityIndicatorView.swift
ios/MullvadVPN/TranslucentButtonBlurView.swift

Git checklist:
Although we don't support right-to-left per se, I figured to keep the codebase future-proof, it wouldn't hurt to fix a few outstanding issues related to supporting RTL environment in the future which as of now result in a crash `fatalError`, which is not nice.
1. Add implementation of `AppButton` layout in right-to-left languages. We're not supporting any yet but I figured to keep our code future proof, it would be great to have it in place to avoid `fatalError()` instead.
2. Remove all Interface Builder released attributes such as `@IBDesignable` and `@ IBInspectable`.
3. Remove `init(withCoder:)` initializers primarily used when loading views built with Interface Builder.
4. …

Fix RTL layouts

---

ios/MullvadVPN/CustomNavigationBar.swift
ios/MullvadVPN/CustomSplitViewController.swift
ios/MullvadVPN/SelectLocationNavigationController.swift
ios/MullvadVPN/SelectLocationViewController.swift
ios/MullvadVPN/SettingsNavigationController.swift

Git checklist:
1. Forward appearance events (viewWillAppear, viewDidAppear, etc...) on iOS 12
2. Handle statusbar style on iOS 12. Resort to default behaviour on iOS 13 and newer, which works as expected.
3. Implement `preferredStatusBarStyle` in `SelectLocationViewController`. This fixes the issue where the statusbar is half black and half white on iOS 15, when using split view controller.
1. Delegate statusbar style to the child controllers. The system queries the status bar style via `preferredStatusBarStyle` property.
2. Add missing `largeTitleTextAttributes` appearance configuration in `CustomNavigationBar`. Also default `tintColor` to `.white`.
--- …

Fix statusbar appearance

---

mullvad-daemon/src/lib.rs

Another tiny PR. `Ipv4Addr::new` has been const since 1.32, so there's no need to use `lazy_static` here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3090)

Use const instead of lazily initialized addresses

---

android/translations-converter/Cargo.toml
mullvad-cli/Cargo.toml
mullvad-daemon/Cargo.toml
mullvad-exclude/Cargo.toml
mullvad-jni/Cargo.toml
mullvad-management-interface/Cargo.toml
mullvad-paths/Cargo.toml
mullvad-problem-report/Cargo.toml
mullvad-rpc/Cargo.toml
mullvad-setup/Cargo.toml
mullvad-tests/Cargo.toml
mullvad-types/Cargo.toml
talpid-core/Cargo.toml
talpid-core/src/split_tunnel/windows/mod.rs
talpid-dbus/Cargo.toml
talpid-openvpn-plugin/Cargo.toml
talpid-platform-metadata/Cargo.toml
talpid-types/Cargo.toml

Rust 2021 edition has been out for a while. This repository always just targets the latest stable compiler. There is no reason not to upgrade as far as I'm aware. So this just bumps all the `edition` specifications. `cargo fix --edition` does not change anything. So I guess all our code is already compliant :ok_hand:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3098)

Upgrade to Rust 2021

---

ci/buildserver-upload.sh

Removing the last traces of `build.mullvad.net` in this repository. For a while we have been uploading build artifacts to two servers. But it's time to stop doing it to the old one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3080)

Stop uploading to build.mullvad.net

---

Cargo.lock
mullvad-daemon/Cargo.toml
mullvad-daemon/src/lib.rs
mullvad-daemon/src/main.rs
mullvad-daemon/src/management_interface.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/Cargo.toml
mullvad-management-interface/src/lib.rs

Previously, any instance of `ManagementInterfaceEventBroadcaster` stopped the server when dropped, i.e., it would stop after the first handle was dropped. This PR updates the code so that the server is stopped when all handles have been dropped instead, as this is more idiomatic. Other small improvements were made as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3086)

Simplify management interface server shutdown

---

.github/workflows/unicode-check.yml
ci/check-trojan-source.sh

Certain Unicode characters can be used to produce code that looks innocuous when rendered in editors, but that contains malicious code. Specifically, they may change the order in which characters appear. Details here: https://www.trojansource.codes/trojan-source.pdf.
This PR includes a script that scans all text and source code for these code points. Rust 1.56.1 already includes lints that [reject](https://blog.rust-lang.org/2021/11/01/cve-2021-42574.html) them, but other compilers may not. The PR also adds a GitHub actions workflow that runs this script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3097)

Add script that detects bidirectional Unicode text

---

build.sh

Previously, the feature was only added when passing `--dev-build` to `build.sh`. The build server builds everything in release mode, but it should also be included there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3110)

Include `api-override` feature when building dev versions in release mode

---

CHANGELOG.md
mullvad-cli/src/cmds/relay.rs

This is a tweak to make the CLI more intuitive. Previously, setting protocol-specific constraints would clear/set to default any options that weren't provided. E.g., the second command would reset the port and entry locations (to `any` and `none`, respectively) in this example:
```
mullvad relay set tunnel wireguard --protocol udp --port 1234 --entry-location se
mullvad relay set tunnel wireguard --protocol tcp
```
The updated behavior in this PR is to leave those settings alone and only change the transport protocol constraint (or whatever constraints are provided).
To avoid modifying the proto file/gRPC service, the old constraints are simply obtained from the gRPC server.
--- …

Keep unspecified constraints unchanged in the CLI when providing protocol-specific constraints

---

gui/src/renderer/components/common-styles.ts

This PR increases the line height of text with font size `32px` from `34px` to `35px` since lowercase "g" didn't fit in that line height. It was for example cut of when displaying "Gothenburg" in the connection info.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3100)

Increase line height with 1px on big text to fit lowercase "g"

---

gui/src/main/index.ts
gui/src/main/window-controller.ts

This PR switches to replacing the whole `WindowController` instead of just the `BrowserWindow` when switch between pinned and unpinned mode. It lowers the complexity and removes duplicated code as a result.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3101)

Replace window controller instead of window

---

ios/CHANGELOG.md
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/HeaderBarButton.swift
ios/MullvadVPN/HeaderBarView.swift

Git checklist:
This PR increases the hit area of the settings button (cog) by 10pt in each direction. The button is 24x24 itself and the surrounding hit area becomes 44x44 which is quite reasonable in my opinion and coincides with hit area of system navigation bar buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3112)

Increase settings button hit area

---

CHANGELOG.md
gui/src/main/index.ts
gui/src/main/window-controller.ts
gui/src/renderer/app.tsx

This PR improves (almost fixes) the issue where the app window isn't always resized properly after changing display scale factor. I still managed to reproduce the issue once with this fix active but compared to before it happens *way* less. I was able to reproduce it easily and now I've tried a lot and only managed to reproduce it once.
The fix is to resize the window when the display scale changes. I also had to switch to `setContentSize` instead of `setSize`, since `setSize` sometimes used the wrong scale factor. Always settings content size seems like a better fit for us since our UI is designed in relation to these measurements.
I also improved the debug logging for when the window is the wrong size. And we no longer need to set `minHeight`, `minWidth`, `maxHeight` and `maxWidth` …

Fix/improve window proportion after display scale factor change on windows.

---

gui/src/renderer/app.tsx
gui/src/renderer/components/LocationList.tsx
gui/src/renderer/components/TunnelControl.tsx

Prevent trying to translate translation of city and country name while connecting. This is accomplished by not storing translated locations in the Redux state and instead translating while rendering.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3103)

Store locations in english and translate for rendering

---

.github/workflows/unicode-check.yml
ci/check-trojan-source.sh

Make the script take the path to the dir to check as argument instead of being self aware.
This makes it simpler to use this script in other places. And the script is less hardcoded on where it's placed. That's instead up to the CI job to define.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3117)

Make trojan source check script more universally usable

---

mullvad-cli/src/cmds/relay.rs

Fixes bugs in #3108.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3114)

Fix CLI bug not allowing the openvpn and wireguard `relay` subcommands to work properly.

---

Cargo.lock

RUSTSEC-2021-0124 was just submitted. Looks like there is a race condition in their `oneshot` implementation. As far as I can see we don't use it. We use `oneshot` channels provided by the `futures` crate. So I think we should be fine. But upgrading to get rid of the audit warning and to not accidentally use this broken channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3118)

Upgrade tokio due to RUSTSEC-2021-0124

---

build_windows_modules.sh

Some changes to adapt a bit towards the [coding guidelines](https://github.com/mullvad/coding-guidelines/blob/master/bash.md). This script was largely written before those existed.
* Add a shebang at the start
* Change indentation to four spaces
* Compress `case` branches in some places where I felt they were more verbose than needed. This is not part of the written style guideline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3119)

More idiomatic bash in build_windows_modules.sh

---

CHANGELOG.md
talpid-core/src/split_tunnel/windows/driver.rs

The daemon filters out paths on non-existent volumes. Previously, the daemon failed to start if this resulted in an empty list. This PR fixes this by clearing the config in that case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3126)

Handle empty (filtered) ST paths correctly on Windows

---

CHANGELOG.md
talpid-core/src/process/openvpn.rs
talpid-core/src/proxy/shadowsocks.rs

Previously, `sslocal` would sometimes continue running even after the daemon had been killed. This resulted in the uninstaller failing on Windows. As the process is only explicitly killed in `OpenVpnMonitor::wait`, if anything in `OpenVpnMonitor::start` failed *after* the proxy monitor had started, the process would keep running. To fix this and to make it less likely to occur in the future, the process is now killed when a `ShadowsocksProxyMonitor` is dropped, even if `ShadowsocksProxyMonitorCloseHandle::close()` is never called.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3124)

Kill sslocal if setting up the tunnel monitor fails

---

CHANGELOG.md
dist-assets/windows/installer.nsh
gui/src/main/index.ts

This PR fixes the issue where the tray icon of the app running before upgrade remains until hovered. It's fixed by:
* Adding support for quitting the app without disconnecting.
* Quit without disconnecting from `installer.nsh` if the old version is 2021.2 or older.
The kill/quit in `customRemoveFiles` had to be moved to an earlier stage of the uninstallation to prevent the app from changing the tray icon to the disconnected one when it loses connection to the daemon.
The solution for checkign the version in `installer.nsh` has the drawback that it assumes that we won't release more than 9 versions during 2021.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadv …

Fix Windows double tray icon on update

---

gui/src/main/index.ts
gui/src/main/platform-version.ts
gui/src/main/window-controller.ts

This PR moves the macOS 11+ and Windows 11+ checks to it's own file.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3132)

Move platform version checks to it's own file

---

windows/libshared/src/libshared/network/interfaceutils.cpp
windows/libshared/src/libshared/network/interfaceutils.h
windows/windns/src/windns/windns.cpp

We previously couldn't rely on `FriendlyName` in `IP_ADAPTER_ADDRESSES_LH` to provide the correct alias on Windows 8. This PR removes that workaround since the affected driver is no longer used. Also, the interfaces are now compared using LUIDs instead of aliases, which should work regardless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3127)

Remove workaround for TAP adapter alias bug

---

dist-assets/uninstall_macos.sh

Git checklist:
This PR updates uninstall script for macOS with command to remove the login item from autostart on macOS. If the item is not there, the `osascript` command emits the following error:
> 36:67: execution error: System Events got an error: Can’t get login item "Mullvad VPN". (-1728)
If desired we could send the output to `/dev/null` as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3135)

Remove login item in uninstall script on macOS

---

mullvad-cli/src/cmds/relay.rs

Changes:
* Add missing newline to `mullvad relay get`.
* The transport protocol constraint could not be set to `any`, without explicitly setting the port to `any`, if it had previously been set to a specific protocol. I.e., `mullvad relay set tunnel wireguard --protocol any` would fail. This has been fixed.
* `mullvad relay set tunnel wireguard --protocol any` now clears any existing port constraint. That is, it has the same effect as `mullvad relay set tunnel wireguard --protocol any --port any`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3134)

Fix issues with relay constraints in the CLI

---

gui/src/renderer/components/Accordion.tsx
gui/src/renderer/components/CustomDnsSettings.tsx
gui/src/renderer/components/List.tsx
gui/src/renderer/components/SplitTunnelingSettings.tsx
gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx
gui/test/list-diff.spec.ts

This PR adds a component that renders a list with support for animated addition and removal of items. It's used in the split tunneling view and for the custom DNS list. It will also be used in the device list which will be introduced in a future PR.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3129)

Add list component

---

gui/src/renderer/components/TunnelControl.tsx
gui/src/renderer/components/common-styles.ts

In https://github.com/mullvad/mullvadvpn-app/pull/3100 the `line-height` of `bigText` was increased from `34px` to `35px` to fit the lowest row of pixels on some letters. It turns out that this wasn't enough on HiDPI displays so this PR reverts the last one and instead increases the `line-height` of the location info.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3140)

Fix location line height

---

mullvad-rpc/src/rest.rs

New addresses were still being fetched from the API even if `MULLVAD_API_ADDRESS` was set. I think it's safe to assume that this is unwanted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3149)

Don't fetch new API addresses if `MULLVAD_API_ADDRESS` is set

---

mullvad-daemon/src/lib.rs
mullvad-problem-report/src/lib.rs
mullvad-rpc/src/lib.rs
mullvad-setup/src/main.rs
talpid-core/src/dns/macos.rs
talpid-core/src/routing/unix.rs
talpid-core/src/routing/windows.rs
talpid-core/src/split_tunnel/windows/mod.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel_state_machine/mod.rs

Instead, simply use [`Handle::current()`](https://docs.rs/tokio/1.14.0/tokio/runtime/struct.Handle.html#method.current). I decided to only do this for async functions, and not just any function that happens to be called in an async context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3144)

Don't explicitly pass Tokio runtime handles to async functions or methods

---

ios/MullvadVPN/AccountInputGroupView.swift
ios/MullvadVPN/AccountTextField.swift
ios/MullvadVPN/CustomTextField.swift
ios/MullvadVPN/TranslucentButtonBlurView.swift
ios/MullvadVPN/UIMetrics.swift

Git checklist:
1. Inherit account token input field from `CustomTextField` to avoid code repetition.
1. Set horizontal compression priority on account input field and submit button to prevent text field from collapsing in compact horizontal environment.
1. Extract couple of dimensions into `UIMetrics` such as common corner radius and text field margins.
1. Fix leftover whitespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3146)

Fix account text field height in compact environment

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ipc/ServiceConnection.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/model/ServiceResult.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt

This PR aims to improve lifecycle issues introduced as part of when the following were split into to separate processes: app ui, VPN service and tile service.
- Fix Quick Settings tile showing wrong state in certain scenarios.
- Avoid running in foreground when not connected.
- Avoid removing notification when service is stopped.
- Change so that swiping the notification no longer kills the service
since that isn't a common way of handling the lifecycle in Android.
Instead rely on the following mechanisms to kill the service:
* Swiping to remove from the Recents/Overview screen.
* Android Background Execution Limits.
* The System Settings way of killing apps ("Force Stop").
Git checklist:
--- …

Fix android multi process lifecycle

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/NotificationBanner.kt

Fixes the the issue present on master and the last release where the banner sometimes didn't hide after showing information to the user. For instance, while establishing a connection the banner shows "BLOCKING CONNECTION", however the banner wasn't removed/hidden after the connection was successfully established.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3148)

Fix banner sometimes incorrectly showing

---

talpid-core/src/dns/windows/mod.rs
windows/windns/src/windns/windns.cpp
windows/windns/src/windns/windns.h

Continuation of #3127. This simplifies WinDns to use LUIDs instead of aliases. At the moment, we still derive the LUID from the alias (in Rust). We could/should eventually just obtain it from the wintun/wg-nt API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3137)

Pass interface by LUID instead of alias to WinDns

---

Cargo.lock
mullvad-setup/Cargo.toml
talpid-core/Cargo.toml
talpid-core/src/dns/windows/mod.rs
talpid-core/src/firewall/windows.rs
talpid-core/src/tunnel/openvpn/wintun.rs
talpid-core/src/tunnel/wireguard/wireguard_nt.rs

Changes:
* Update to `widestring` 0.5, which includes some `from_*_truncate` constructors that let us avoid some `unwrap`s.
* Use `WideCString` instead of `encode_wide` in modules where `widestring` was already being relied upon, since it accomplishes the same thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3163)

Refactor widestring code

---

mullvad-setup/src/main.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/firewall/windows.rs
talpid-core/src/tunnel_state_machine/mod.rs

Previously, `FirewallArguments` included an optional `allowed_endpoint` field as well as a boolean `initialize_blocked`. In reality, `allowed_endpoint` will never be `None` if `initialize_blocked` is `true`, and it will only ever be `None` if `initialize_blocked` is `false`. Moreover, setting the firewall policy to `connecting` or `blocked` after init involves a non-optional `allowed_endpoint` argument. So this PR gets rid of the "invalid" combinations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3164)

Make the initial allowed endpoint argument non-optional

---

gui/src/renderer/components/Login.tsx

This PR disables the "Create new account" button while the login field isn't empty. This is to prevent users from hitting the "Create new account" button as a submit button for the login field.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3165)

Disable account creation while entering account number

---

README.md
mullvad-rpc/Cargo.toml
mullvad-rpc/src/address_cache.rs
mullvad-rpc/src/lib.rs
mullvad-rpc/src/rest.rs

Rename `MULLVAD_API_ADDRESS` to `MULLVAD_API_ADDR` to be more like the corresponding `MULLVAD_API_HOST`.
Also doing some refactoring to allow better error handling in case their values are set in the wrong way. This feels better than silently failing. The silent failing makes it harder to figure out if a tester correctly set it or not.
Here I'm going more with `cfg!` rather than `#[cfg` because it allows the compiler/CI to catch errors in the not used path in all cases. If completely compiling out code it's easier to have errors that go undetected. The optimizer will remove all not used cases anyway when it sees `if false {}`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvad …

Refactor api addr override

---

talpid-core/src/firewall/macos.rs

As above. The log is currently filled with output from `pfctl`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3155)

Suppress output to stderr.log from pfctl

---

CHANGELOG.md
mullvad-management-interface/src/types.rs

The conversion back from the `RelayLocation` gRPC message considers an absent `location` to be invalid. This is used for the `any` location. Confusingly, a `RelayLocation` with all fields empty can also refer to the `any` location. We need to handle both, because the CLI currently panics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3166)

Handle empty relay location field (`any` location) in the CLI

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/CustomDnsSettings.tsx
gui/src/renderer/components/Switch.tsx
gui/src/renderer/components/cell/Input.tsx

This PR changes the behavior of the block when disconnected-switch which previously showed a confirmation dialog after the setting had changed and now it shows it before changing it instead. This moves part of the logic to the `Switch` component and makes it reusable.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3170)

Improve switch confirmation

---

docs/logging-and-telemetry.md

This is nothing new. The app has done exactly this for a long time.
But now it's written down in a policy that's easier for users
and developers to find and understand compared to reading the actual
code. This is added for transparency's sake and for making it easier to
point at during code review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3174)

Add initial logging and telemetry policy

---

CHANGELOG.md
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
android/src/main/kotlin/net/mullvad/mullvadvpn/ui/customdns/CustomDnsAdapter.kt

Fixes the issue with the user getting kicked out of certain views in settings when the app is brought to the foreground.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3167)

Fix android resume navigates back

---

gui/src/renderer/components/Accordion.tsx
gui/src/renderer/components/CustomDnsSettings.tsx

This PR fixes the issue where the "Add a server" button for the custom DNS setting disappears after adding the first server. It was caused by the accordion when it was collapsed and then immediately expanded to the same size and. Since the height transition hadn't started yet it switched to the same height and therefore never ran a transition. This resulted in the height never being set to `auto`. This has been solved by:
1. Not closing the accordion when adding the first custom DNS server
2. Making `Accordion` set the height to `auto` if no transition will happen when expanding.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3178)

Fix add DNS server button disappearing after adding first server

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-management-interface/src/types.rs
mullvad-types/src/location.rs

The GUI needs to be able to show which entry relay it's connecting to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3171)

Send entry WireGuard relay hostname to frontends

---

CHANGELOG.md
docs/security.md
mullvad-daemon/src/lib.rs
talpid-core/src/firewall/linux.rs
talpid-core/src/firewall/macos.rs
talpid-core/src/firewall/mod.rs
talpid-core/src/firewall/windows.rs
talpid-core/src/tunnel_state_machine/mod.rs
talpid-types/src/net/mod.rs
windows/winfw/src/winfw/fwcontext.cpp
windows/winfw/src/winfw/fwcontext.h
windows/winfw/src/winfw/rules/baseline/permitendpoint.cpp
windows/winfw/src/winfw/rules/baseline/permitendpoint.h
windows/winfw/src/winfw/winfw.cpp
windows/winfw/src/winfw/winfw.h

This adds `FWPM_CONDITION_ALE_APP_ID` conditions to the allowed endpoint firewall filter on Windows. With these changes, only `mullvad-daemon.exe` and `mullvad-problem-report.exe` can communicate with the API in the blocked state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3168)

Restrict API access to some applications on Windows

---

CHANGELOG.md
gui/src/main/daemon-rpc.ts
gui/src/main/gui-settings.ts
gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/containers/ConnectPage.tsx
gui/src/shared/gettext.ts
gui/src/shared/logging.ts

This PR improves logging of missing translations by
* Disables logging of translation errors when not running in development. This among other things prevent logging the error when translating the country in the disconnected state.
* Use `log.info` instead of `log.warn` to prevent showing the stack trace.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3179)

Improve translation logging

---

mullvad-cli/src/cmds/relay.rs
mullvad-daemon/src/migrations/mod.rs
mullvad-daemon/src/migrations/v5.rs
mullvad-daemon/src/relays.rs
mullvad-management-interface/proto/management_interface.proto
mullvad-management-interface/src/types.rs
mullvad-types/src/relay_constraints.rs

Previously, the entry location was an `Option`. This meant that it could not be turned off without losing the location, and the gRPC message worked differently than it did for relays, etc. This PR adds a separate "state" and makes the entry location non-optional.
The CLI currently behaves exactly as before. The state setting is not exposed at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3177)

Add WG entry hop "state" setting

---

Cargo.lock
mullvad-rpc/Cargo.toml
mullvad-types/Cargo.toml

I ran `cargo udeps` and found we had three unused dependencies. They are still in our dependency tree, so we don't get rid of them. But at least our crates should not specify dependencies we don't use.
I'm considering adding a CI job for `cargo udeps`, but not sure it's worth it given that one must compile it from source, which will take time in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3183)

Remove unused dependencies found by cargo-udeps

---

Cargo.lock
talpid-core/Cargo.toml

In #3138, I made `talpdi-core` depend on a git revision of `socket2`. This is no longer required, so I've upgraded it to use version `0.4.2`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3189)

Use release 0.4.2 of socket2

---

talpid-core/Cargo.toml

The `trust-dns-server` dependency should only be a dependency for macOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3192)

Make trust-dns a macOS exclusive dependency

---

mullvad-rpc/src/address_cache.rs
mullvad-rpc/src/relay_list.rs
talpid-core/src/routing/unix.rs
talpid-dbus/src/network_manager.rs
talpid-types/src/lib.rs
talpid-types/src/net/wireguard.rs

Some links were incorrect. This fixes the warnings, at least on Windows and Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3182)

Fix some `cargo doc` warnings

---

talpid-core/src/future_retry.rs

`Duration::MAX` was stabilized in [Rust 1.53](https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html), so let's use that instead of `Duration::from_secs(u64::MAX)` now (which was slightly incorrect as well).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3197)

Use `Duration::MAX` where applicable

---

gui/tasks/distribution.js

electron-builder uses [`fpm`](https://github.com/jordansissel/fpm) to generate Debian packages. In the build configuration, `iputils-ping` is currently a dependency, but this is unnecessary now since the daemon uses ICMP directly rather than a `ping` executable.
Removing `iputils-ping` causes the default dependencies to be used instead: `["gconf2", "gconf-service", "libnotify4", "libappindicator1", "libxtst6", "libnss3"]`. This is easily fixed using the argument `--no-depends`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3193)

Remove `iputils-ping` from .deb dependencies

---

ios/.gitignore
ios/CHANGELOG.md
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme
ios/MullvadVPN/Account.swift
ios/MullvadVPN/AddressCache/AddressCache.swift
ios/MullvadVPN/AddressCache/AddressCacheStore.swift
ios/MullvadVPN/AddressCache/AddressCacheStoreError.swift
ios/MullvadVPN/AddressCache/AddressCacheTracker.swift
ios/MullvadVPN/AddressCache/UpdateAddressCacheOperation.swift
ios/MullvadVPN/AppDelegate.swift
ios/MullvadVPN/AppStorePaymentManager/AppStorePaymentManager.swift
ios/MullvadVPN/ApplicationConfiguration.swift
ios/MullvadVPN/IPEndpoint.swift
ios/MullvadVPN/Info.plist
ios/MullvadVPN/Operations/ExclusivityController.swift
ios/MullvadVPN/ProblemReportViewController.swift
ios/MullvadVPN/Promise/Cancellable.swift
ios/MullvadVPN/REST/HTTP.swift
ios/MullvadVPN/REST/RESTClient.swift
ios/MullvadVPN/REST/RESTNetworkOperation.swift
ios/MullvadVPN/REST/RESTRequestAdapter.swift
ios/MullvadVPN/REST/RESTRetryStrategy.swift
ios/MullvadVPN/REST/SSLPinningURLSessionDelegate.swift
ios/MullvadVPN/RelayCache/RelayCacheTracker.swift
ios/MullvadVPN/Result+UIBackgroundFetchResult.swift
ios/MullvadVPN/TunnelManager/TunnelManager.swift
ios/MullvadVPN/WireguardKeysViewController.swift
ios/prebuild.sh
ios/update-relays.sh

Git checklist:
This PR adds support for API address cache that is used to perform REST requests to Mullvad API. The address cache is updated periodically using background task and timer based solution.
Detailed changeset:
1. Rename `update-relays.sh` to `prebuild.sh`. Update script to download API address list to `Assets/api-ip-address.json`, which is later on bundled with the app.
2. SSL pinning: return `.rejectProtectionSpace` if found that SSL certificate chain is invalid. This makes the network layer return the proper error back to caller, i.e: `The certificate for this server is invalid. You might be connecting to a server that is pretending to be "<ENDPOINT_IP>" which could put your …

Add API address cache

---

talpid-core/src/firewall/macos.rs

I think this does the exact same thing but in a much simpler manner. Allocating a vector of `Result<()>` on the heap and then mapping over them seems a bit complicated to just run three fallible methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3202)

Tiny simplification/code cleanup

---

CHANGELOG.md
gui/src/main/index.ts

Git checklist:
This PR disables the built-in DNS resolver in Electron, which was introduced with the update to Electron 15 around `2021.6`. Although GUI process does not issue any network requests, nonetheless, Electron established connections to DNS servers specified in network preferences on macOS. 
Based on documentation, built-in DNS resolver is only enabled on macOS, hence the changelog states that the fix is for Mac only, however the patch itself disables built-in DNS resolver regardless the environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3209)

Disable built-in DNS resolver

---

CHANGELOG.md
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt
android/app/src/main/res/values/strings.xml
gui/locales/messages.pot

Change Android tile title/label to "Toggle VPN" to better inform the
user about the tile action. Also set the subtitle (on Android Q and
above) to match the state shown in the notification.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3208)

Clarify Android tile text

---

prepare-release.sh
version-metadata.sh

Fixes the path to the gradle file used to handle versioning. The issue
was instroduced when the project/app module were split in the following
commit: f249bc175d21c3f732541266be9004700a913487
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3211)

Fix path to gradle file in versioning scripts

---

ios/MullvadVPN/REST/HTTP.swift
ios/MullvadVPN/REST/RESTClient.swift

Git checklist:
This PR changes the way REST API client handles HTTP status codes, by basically treating all `2xx` response codes as successful to improve resilience towards any potential changes in the API status codes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3214)

REST: handle success response codes defensively

---

gui/tasks/distribution.js

This PR prevents grpc-tools and @types/* depdendencies from being bundled in builds of the app. Those dependencies are only used for building the app and are not needed.
This PR also contains a formatting change which was applied by prettier.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3213)

Prevent bundling grpc-tools and @types/* dependencies in builds

---

build.sh

Tiny cleanup before larger refactoring of this script. Just adhering better to function style as defined in https://github.com/mullvad/coding-guidelines/
I also removed the function `buildTargets` because:
* It was only called once (no code reuse from being a function)
* It was depending on global state (`TARGET`) so sliighlty confusing
* I did not see any clear advantages of it being a function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3219)

Cleanup build.sh

---

README.md
build.sh
ci/buildserver-build.sh
gui/tasks/distribution.js

In order to make it easier to use `build.sh` while developing we make it the default to build for the current architecture only. Since currently developers type `build.sh --target ..-darwin-...` every time. Add --universal flag for building universal app for both Intel and Apple Silicon. Make the build server script use the new flag, so it keeps producing universal binaries.
Maybe it's a little strange to carry around the `TARGETS` variable now when it's only ever used to list the two macOS target triples if it should be built for both.. But maybe it's worth keeping? I guess we are not sure how we will build arm64 Linux later? Or do you have another design that you prefer?
--- …

Make build.sh produce single architecture pkg by default (add --universal)

---

build.sh

`build.sh` outputs a lot of text. Most of it is noise. Some of it is interesting some of the time. For example, when I'm looking at build server logs I want to know which branch/version it's currently building. It's also nice to be able to see approximately where in the build process it is. Currently we have ~6 `cargo run`/`cargo build` calls after each other in this script. So seeing some random cargo output does not say much about the overall progress.
Because of this I added some helper functions to log with color. And use those to have some nicer output from the script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3226)

Better build.sh logging

---

.github/workflows/daemon.yml
README.md
build-apk.sh
build-windows-modules.sh
build.sh
ci/buildserver-build.sh
ci/check-rust.sh
prepare-release.sh
update-api-address.sh
update-relays.sh

`build.sh` has since the start been focused on being used mostly for building signed release artifacts. Using it as a developer has not been a high priority. But I want to change that. This script is often being overlooked, making it not work, because developers don't use it. And we want to make it easier and faster for developers to build test artifacts for themselves and their test machines.
So here I invert the arguments and make them more flexible. Instead of passing `--dev-build` to not build a signed release artifact, one does no longer need to pass anything. And the build server instead of passing nothing will now pass `--optimize --sign` to enable compiler optimizations and binary signing.
--- …

build.sh improvements to support debug builds and be more flexible

---

CHANGELOG.md
gui/src/main/window-controller.ts

This PR fixes a bug which prevented notifications from showing on Windows if the window was unpinned and hidden (not closed). The problem was the `window.isVisible()` returns `true` when the Window is minimized. To solve this `&& !window.isMinimized()` has been added.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3225)

Fix notifications on Windows when unpinned window is hidden

---

CHANGELOG.md
talpid-core/src/tunnel/mod.rs
talpid-core/src/tunnel/wireguard/connectivity_check.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs

Previously, the timeout for establishing a WireGuard tunnel was always 15 seconds. This is very high except for very slow connections. It is bad for two reasons: 1) If a relay is down, it takes far too much time to try another relay. 2) On the device concept branch, the device validity check occurs after a couple of failed connect attempts. This means that it takes over 30 seconds to discover that the device/WireGuard key is invalid.
This PR sets the initial timeout to 4 seconds, and multiplies it by two for each reconnect attempt, up to a maximum of 15 seconds. So if a relay is down (and the relay list does not say so), it will normally take 4 seconds to try a working one. It will also "only" take about 12 seconds to discover that the device has been revoked.
--- …

Use exponential backoff for WireGuard connectivity check timeout

---

mullvad-rpc/src/lib.rs
mullvad-rpc/src/rest.rs

The daemon currently expects strict HTTP response status codes, which makes it too brittle. To fix this, the code has been changed to presume any 2XX response code to indicate success. Any unexpected response codes will still be logged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3212)

Fix HTTP status validation in daemon

---

gui/src/renderer/components/LocationList.tsx
gui/src/renderer/containers/SelectLocationPage.tsx

This PR fixes two UI bugs related to WireGuard multihop:
* Previous entry location was marked as entry location in exit selection after switching multihop off,
* Sorting of countries and cities in languages other than English.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3230)

WireGuard multihop UI improvements

---

android/app/build.gradle

Fixes the invalid path to 'keystore.properties' introduced in the
previous split of the android/root project and app module.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3233)

Fix invalid path in Android release build

---

gui/tasks/distribution.js

`compression: 'store'` apparently doesn't affect the `rpm` package, it will still be compressed which takes a lot of time. To avoid this if `--no-compression` is supplied, the fpm argument `--rpm-compression none` is added. This shaves more than 3 minutes of the build time on my computer.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3237)

Respect `--no-compression` when building rpm-package

---

android/app/build.gradle.kts

Fixes an asset inclusion issue introduced during the groovy->kotlin migration
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3241)

Fix Android build asset inclusion

---

mullvad-daemon/src/cli.rs
mullvad-daemon/src/lib.rs
mullvad-daemon/src/logging.rs
mullvad-daemon/src/main.rs
mullvad-daemon/src/relays.rs
mullvad-types/src/settings/mod.rs
talpid-core/src/dns/macos.rs
talpid-core/src/dns/windows/mod.rs
talpid-core/src/firewall/windows.rs
talpid-core/src/tunnel_state_machine/connecting_state.rs

I'm thinking about adding a section to the coding guidelines on trying to avoid importing stand alone functions and macros as much as possible. At least where prefixing with the module adds valuable information to the reader. Logging was a prime example of this. So I thought I'd take this change through review before proposing any coding guidelines changes. `log::` is very short. It makes very few lines of code expand into more lines than they already were. And it adds a lot of context to the reader IMO. Only `error!(...)` could very well be some kind of sibling to `try!(...)`. `log::error!` is very clear.
Also, we are already using `log::$macro` in a lot of places in the code. Even in the same file we mix using it qualified and unqualified, so this is also in order to make it more …

Always use logging macros prefixed with log::

---

android/app/build.gradle.kts
android/build.gradle.kts
android/buildSrc/build.gradle.kts
android/buildSrc/src/main/kotlin/Dependencies.kt
android/buildSrc/src/main/kotlin/Repositories.kt
android/buildSrc/src/main/kotlin/Versions.kt

Extracts Android dependency names/versions/repos to Kotlin constants in
source code. The purpose of this change is to minimize duplication,
unify versions and prepare the project to be split into multiple
sub-projects/modules.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3238)

Extract Android dependencies to constants

---

mullvad-rpc/src/https_client_with_sni.rs

Apparently a regression due to the tokio 1 migration. The API likely isn't reachable in blocking states on master right now. The bug had not yet made it to a release, however.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3243)

Fix socket bypass on Android

---

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/UrlButton.kt

Fixes an issue with url buttons keeping an old reference to service
dependent instances, even after the service connection is no longer
available.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3234)

Fix url buttons broken on app resume

---

Cargo.lock
mullvad-daemon/Cargo.toml
mullvad-daemon/src/migrations/mod.rs
mullvad-daemon/src/migrations/v1.rs
mullvad-daemon/src/migrations/v2.rs
mullvad-daemon/src/migrations/v3.rs
mullvad-daemon/src/migrations/v4.rs

The current settings migration is very fragile to changes. Take for example `v3` that depends on the `DefaultDnsOptions` type. If we were today to remove the `block_trackers` setting in `master`, then this migration would break. It would still migrate settings, but the `v4` settings it would output would not have this flag properly set.
The solution I opted for was to vendor all the relevant dependencies to each settings version. It did not end up being too much.
Did I miss something here, or is this a good way to make the migration more stable and less susceptible to future changes?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3246)

Stable settings migrations (vendor types that a specific version depends on)

---

Cargo.lock
mullvad-daemon/Cargo.toml
mullvad-daemon/src/migrations/v3.rs
mullvad-daemon/src/migrations/v4.rs
mullvad-daemon/src/migrations/v5.rs
mullvad-types/src/settings/mod.rs

Fixes a bug in #3245. Since these attributes were missing a missing `block_malware` was not initialized to the default, instead the entire settings deserialization failed and everything was falling back to defaults.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3249)

Add #[serde(default)] to some settings types. And clean up Android stuff from migration code

---

.github/workflows/android-app.yml
.github/workflows/android-audit.yml
.github/workflows/android-ktlint.yml
.github/workflows/android-xml-tidy.yml
.github/workflows/cargo-audit.yml
.github/workflows/daemon.yml
.github/workflows/frontend.yml
.github/workflows/ios.yml
.github/workflows/rustfmt.yml
.github/workflows/translations-converter.yml
.github/workflows/translations.yml
.github/workflows/unicode-check.yml

This PR changes all GitHub Actions workflow triggers from `push` to `pull_request` which will trigger for when the commits change in a PR, when it's opened and when it's reopened if closed. The paths that triggers a workflow will now be compared against the full list of changed files in the pull request instead of just the latest push.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3252)

Make GitHub Actions workflows trigger on all changes in pull request

---

CHANGELOG.md
gui/src/main/daemon-rpc.ts

This prevents gRPC-js from using the environment variable `http_proxy` which is used for all connections. If that variable was set our app wasn't able to connect to the daemon.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3259)

Disable gRPC http proxy

---

CHANGELOG.md
talpid-core/src/tunnel/wireguard/connectivity_check.rs
talpid-core/src/tunnel/wireguard/mod.rs
talpid-core/src/tunnel/wireguard/wireguard_go.rs
talpid-core/src/tunnel/wireguard/wireguard_nt.rs
talpid-types/src/lib.rs
wireguard/libwg/libwg_windows.go

Previously, there was a race, as the code did not make sure that any IP interfaces had been added before setting any IP interface properties. The PR fixes this by waiting for `MibAddInstance` notifications first, if necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3240)

Fix failure to set MTU on wireguard-nt interfaces

---

gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/shared/connect-helper.ts

This PR refactors how the next assumed tunnel state is handled (called optimistic tunnel state before this PR). Previously this was done both in the main and renderer processes. Now it's instead handled in the main process only.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3260)

Refactor tunnel state handling

---

CHANGELOG.md
mullvad-cli/src/cmds/relay.rs

This has been done previously for `mullvad relay set location`, but the hostname seems to have been ignored/forgotten.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3267)

Make `mullvad relay set hostname` not case sensitive to the input

---

CHANGELOG.md
mullvad-daemon/src/migrations/mod.rs
mullvad-daemon/src/migrations/v5.rs
mullvad-daemon/src/migrations/vX.rs.template
mullvad-types/src/settings/mod.rs

The settings migrations have been hard to understand, create, maintain and keep bug free. We need to clean this up so it's easy to see which settings version is in use. When it went into use. What actually changed in the format. etc.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3268)

Clarify settings migration procedure and add old migrations to changelog

---

talpid-core/src/tunnel/wireguard/mod.rs

Changes:
* Previously, `Runtime::block_on` was used all over the place to execute async code in the connectivity monitor thread. It turned out much nicer to spawn a tokio task and use `spawn_blocking` for the blocking code instead.
* Remove channel used to stop waiting on the the IP interface to be set up. It's not needed (anymore?) because we can simply rely on a sender being dropped instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3261)

Simplify WireGuard tunnel monitor

---

mullvad-rpc/src/bin/address_cache.rs
mullvad-rpc/src/bin/relay_list.rs
mullvad-rpc/src/relay_list.rs

We invalidly used `///` in a bunch of places. That's for documenting individual items, not the entire module.
I also sliightly improved the documentation in a few places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3272)

Just slight fix for the documentation `///` -> `//!` and similar

---

Cargo.lock
mullvad-problem-report/Cargo.toml
mullvad-problem-report/src/lib.rs
mullvad-problem-report/src/main.rs

I found we wrote to stdout/stderr in the *library* part of `mullvad-problem-report`. I don't think libraries should print to stdout/stderr. I guess this is a remains that was forgotten when migrating it from a binary to a library a long time ago?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3271)

Move printing to stdout/stderr out of problem-report library

---

CHANGELOG.md

The changes that disabled the built-in DNS resolver in Electron was added under the macOS category in the changelog, but there's nothing specific to macOS in the code or documentation. I haven't tested it on other platforms but it should affect those as well.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3275)

Move electron resolver changelog item

---

CHANGELOG.md
gui/src/main/index.ts
gui/src/main/tray-icon-controller.ts
gui/src/shared/connect-helper.ts

This PR improves the context menu by:
* Move code that creates the menu to `tray-icon-controller.ts`
* Change layout of context menu to not change text and action of items and instead just change `enabled`
* Update context menu when account, daemon connection or language changes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3266)

Tray context menu improvements

---

gui/src/main/index.ts

Due to #3210, the GUI crashes if `%localappdata%\Mullvad VPN` does not exist, e.g. the first time you run it after installing the app. Electron tries to create a lockfile there without ensuring that the directory exists first:
```
[22500:0118/134306.582:ERROR:process_singleton_win.cc(466)] Lock file can not be created! Error code: 3
```
This PR works around the issue by simply creating the directory if necessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3273)

Fix GUI not starting after a fresh install

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt

By default in Android, a service will be automatically killed if it
belongs to a task that was removed (i.e. from recent apps) without a
chance to run any cleanup logic.
In this case, the lack of cleanup would lead to a crash and auto-restart
(triggered by the system) resulting in a auto-connect. To fix this, a
graceful stop will be ran if the task is removed while the tunnel is
disconnected (service not running as foreground). However if the tunnel
is in other states than disconnected (service running as foreground),
the service should continue to run as it's bound by the system.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3277)

Fix auto-connect on app removed from recent apps

---

talpid-core/src/dns/windows/mod.rs

No longer needed as it can be assumed that the minimum version is 10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3283)

Remove Windows 10 check from DNS module

---

Cargo.lock
mullvad-rpc/Cargo.toml
mullvad-rpc/src/https_client_with_sni.rs

This upgrades `tokio-rustls` and `hyper-rustls` to version 0.23, and `rustls` to 0.20. These are mostly API changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3280)

Upgrade rustls crates

---

gui/locales/messages.pot
gui/src/renderer/components/OpenVPNSettings.tsx
gui/src/renderer/components/cell/Selector.tsx
gui/src/renderer/containers/OpenVPNSettingsPage.tsx

This PR:
* Changes the bridge mode selector to not allow setting `on` if `UDP` is selected as transport protocol,
* Changes the tranport protocol selector to not allow `UDP` if bridge-mode is `on`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3276)

Add requirements for OpenVPN UDP and bridge mode

---

CHANGELOG.md
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt

This PR aims to improve the general tunnel state notification behavior as there were plenty of cases where dismissed notifications ("Unsecured") would appear again, such as:
- When locking device. 
- If the notification is dismissed quick after disconnecting and putting the app to the background. The new notificaiton would not have any action buttons in this case.
These issues are fixed by:
- Hiding the the notificaiton from the lock screen.
- Avoiding updating the notification (to hide action buttons).
This PR also makes sure to clean-up the notification if the app task is removed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3288)

Fix tunnel state notification behavior

---

gui/src/main/index.ts
gui/src/renderer/app.tsx
gui/src/renderer/lib/history.tsx

This PR disabled background throttling of the renderer process during the `navigation.notifyReset` call is made. This is to allow the UI to update and perform the navigation while the window isn't visible. Without this the previous view will be visible for a split second when opening the window after resetting.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3223)

Disable background throttling while resetting navigation while in background

---

gui/src/renderer/components/AppButton.tsx
gui/src/renderer/components/AppButtonStyles.tsx
gui/src/renderer/components/TransitionContainer.tsx
gui/src/renderer/components/TunnelControl.tsx

This PR positions button content with CSS instead of JavaScript. The solution is similar to the navigation bar but a different requirement is that the text should always be centered. To accomplish this when there are icons of different width on the sides of the label, the icons are added to both sides but hidden on the one where they shouldn't be visible. This makes them take up the width and makes the widest side use up the same amount on both sides.
This made it possible to simplify the code a lot since `ref`s to the button and text aren't needed anymore.
One issue I ran into was that the `buttonRef.current?.getBoundingClientRect()` triggered a reflow which made transitions in `TransitionContainer` work. When removing the calls to `getBoundingClientRect` in `AppButton` some views lost …

Position button content with css

---

gui/src/renderer/components/AdvancedSettings.tsx
gui/src/renderer/components/Switch.tsx
gui/src/renderer/components/WireguardSettings.tsx

This PR:
* Removes the delay before calling `onChange` in the `Switch` component. This previously caused some animation lag for settings that required daemon communication. This was solved by not using `transform` for positioning. I don't know why that happened but it's now working as it should.
* Removes the dragging functionality of the `Switch` component. This functionality added a lot of complexity and was prone to race conditions. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3231)

Remove Switch drag function and onChange delay

---

gui/src/main/index.ts

Adds a comment for #3273. According to the Electron [documentation](https://www.electronjs.org/docs/v14-x-y/api/app#appsetpathname-path), one is supposed to make sure that all of the overridden paths exist. So this PR also uses `mkdir` for the remaining paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3281)

Explain Electron lock file fix

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/target_state.rs

As above. This hides all the logic in a new type/impl, which should make it easier to understand, and reduces the complexity of `lib.rs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3293)

Encapsulate persistent target state logic

---

CHANGELOG.md
android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VpnPermission.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/activities/TVActivity.kt

The main activity and tv activity are both designed to be running as
singleTask and the app would crash if both were started. This would not
be common, but possible, on a phone or tablet, however this can
potentially occur frequently on Android TV (perhaps depending on OEM),
as both categories  LAUNCHER and LEANBACK_LAUNCHER are used. E.g.the tv
launcher would use LEANBACK_LAUNCHER whereas the settings app would use
LAUNCHER.
As the tv activity isn't used for any customization atm, this was fixed
by simply removing the tv activity and adding the LEANBACK_LAUNCHER
category to the main activity.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3296)

Fix android tv startup crash

---

mullvad-daemon/src/lib.rs
mullvad-daemon/src/relays.rs
mullvad-daemon/src/relays/matcher.rs
mullvad-daemon/src/relays/mod.rs
mullvad-daemon/src/relays/updater.rs
mullvad-types/src/endpoint.rs
mullvad-types/src/relay_constraints.rs

This is a refactoring of the relay selector with a single purpose - to make the code clearer. The main issue with the previous state of the relay selector was that all relay selector functions always took all of the parameters, regardless of necessity, which made it hard to understand what bit of the parameters affected which bit of the selection process. To remedy this, yet another layer of abstraction has been added (`TunnelMatcher` trait and `RelayMatcher` struct) which are constructed only from the necessary bits of the `RelayConstraints` for each tunnel type. In the process, some new tests have been added, and the relay list updater has been moved into it's own module. Care has been taken to have the preferred constraints remain the same.
--- …

Refactor relay selector

---

CHANGELOG.md
dist-assets/linux/after-remove.sh

This PR makes `after-remove.sh`, which is run when uninstalling on Linux, remove user configuration directories and files created by the app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3302)

Remove user config files on purge

---

ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN/Operations/OperationCompletion.swift
ios/MullvadVPN/TunnelIPC/TunnelIPCError.swift
ios/MullvadVPN/TunnelIPC/TunnelIPCRequestOperation.swift
ios/MullvadVPN/TunnelIPC/TunnelIPCSession.swift
ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift
ios/MullvadVPN/TunnelManager/ReloadTunnelOperation.swift

Git checklist:
This PR puts tunnel IPC handling into `Operation` subclass which performs the following steps:
1. Handles VPN status change in order to avoid sending IPC requests in `connecting` and `disconnecting` states as those happen early/late tunnel lifecycle and may cause the tunnel process to become unresponsive, which is usually reflected in the tunnel being stuck indefinitely in `connecting` state.
2. Maintains 5 second timeout before the operation is cancelled.
3. Optionally allows the caller to wait for `reasserting` state to transition to `connected` state before issuing the IPC request. We used that to prevent flooding the tunnel with calls to reload settings.
4. Performs an IPC …

Add IPC timeout

---

.github/workflows/android-app.yml
ci/run-android-instrumented-tests.sh

Improve the Android app build and testing in GitHub in the following ways:
- Improve Gradle caching by using a dedicated action which is more efficient.
- Introduce caching of native libs (daemon/wireguard-go) to avoid rebuilding unless changed.
- Publish apks with a one day retention.
- Cache emulator.
- Split build of instrumented test apk from the emulator test execution.
The result is a reduced execution time which will depend on how much of the cached result can be re-used. For example, in case nothing needs to be rebuilt, the execution time has went from around 17min -> 6min.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3312)

Improve android app build in github actions

---

mullvad-daemon/src/relays/matcher.rs
mullvad-daemon/src/relays/mod.rs

When selecting relays, take WireGuard transport protocol constraint into account. In the recent refactor, the transport protocol for WireGuard was being disregarded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3310)

Take transport protocol into account for WireGuard.

---

mullvad-daemon/src/relays/matcher.rs
mullvad-daemon/src/relays/mod.rs

The relay selector was buggy in three ways - when selecting an entry endpoint for multi-hop, it would consider both TCP and UDP endpoints and when trying to construct a valid configuration, the endpoint protocol constraint wouldn't be taken into consideration and finally, the config construction would assume that only UDP endpoints have been selected if the transport protocol was not specified. Thus, when using multi-hop the relay selector could end up picking a UDP configuration with TCP ports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3314)

Fix port confusion when picking WG endpoints

---

ios/CHANGELOG.md
ios/MullvadVPN.xcodeproj/project.pbxproj
ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios/PacketTunnel/PacketTunnelProvider.swift

Git checklist:
This switches the WireGuardKit to [commit](https://git.zx2c4.com/wireguard-apple/commit/?h=am/ignore-set-network-settings-error-when-offline) that handles the error to change network settings on iOS 15.1 or newer while in airplane mode.
The primary difference is that the error is logged but ignored and then network settings are set anyway when the network connectivity comes back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3315)

Fix error when changing relays while in airplane mode

---

gui/src/renderer/app.tsx

This PR adds the text `via <entry location>` to the connection panel after pressing connect before the app receives the `connecting` state from the daemon. The issue was that when the location was derived from the location constraints, the entry location wasn't used.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3317)

Add entry location to connecting state before connecting event
