CHANGELOG.md, talpid-core/src/split_tunnel/windows/windows.rs
If a path `C:` (or any other drive letter + colon) is added to the list of excluded apps using `mullvad split-tunnel app add C:`, a panic occurs in `Path::strip_prefix`. This causes the split tunnel monitor thread to stop. The PR works around the issue by rejecting every `path` for which `path.is_absolute()` is false.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3320)
=> Work around `Path::strip_prefix` panic

talpid-core/src/offline/windows.rs, talpid-core/src/split_tunnel/windows/driver.rs, talpid-core/src/split_tunnel/windows/mod.rs, talpid-core/src/split_tunnel/windows/path_monitor.rs, talpid-core/src/split_tunnel/windows/volume_monitor.rs, talpid-core/src/windows/mod.rs, talpid-core/src/windows/window.rs
Excluded paths are now re-resolved to device paths when volumes are mounted, if necessary. Previously, paths that included a non-existent disk prefix were not excluded from the tunnel even if a volume was later assigned that letter prefix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3303)
=> Reapply split tunnel config if drives arrive or are removed

Cargo.lock, mullvad-daemon/Cargo.toml, mullvad-exclude/Cargo.toml, mullvad-jni/Cargo.toml, mullvad-management-interface/Cargo.toml, talpid-core/Cargo.toml
Get on the latest nix. Adds another dependency to the tree for now. But I know that other parts of our tree will upgrade to 0.23 relatively soon so we'd pay that anyway. I wish `rtnetlink` could upgrade also, then we'd get rid of 0.22 completely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3325)
=> Upgrade nix from 0.22.2 to 0.23.0

CHANGELOG.md, mullvad-cli/src/cmds/bridge.rs
We recently changed the cipher from chacha20 -> aes-256-gcm
and the password from 23#dfsbbb to mullvad
on port 443 on all our shadowsocks bridges
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3328)
=> Update the default password and cipher for the custom bridges

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt
Fixes tile service crash that occurred when the tile service tries to
unbind even though there are no binding or pending binding.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3316)
=> Fix tile service crash

Cargo.toml
The feature resolution currently used enables platform-specific features for all targets. This is [no longer true](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) for version 2 of the resolver. The old behavior can be problematic when dependencies or features depend on the build target.
Specifying 2021 as the Rust edition in the root package causes the resolver to be 2 by default. Unfortunately, the edition cannot be set in the `[workspace]` section. So this PR explicitly sets `resolver = "2"` in the `[workspace]` section instead (as is suggested [here](https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions)).
--- …
=> Explicitly set feature resolver version for workspace

ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Operations/AsyncBlockOperation.swift, ios/MullvadVPN/Operations/AsyncOperation.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift
Git checklist:
1. Add a method to assign cancellation handler for `AsyncBlockOperation`. (See `AsyncBlockOperation.addCancellationHandler`)
2. Add `operationDidFinish` hook in `AsyncOperation` to be able to do perform cleanup once operation is finished. Used in `AsyncBlockOperation` to release cancellation handlers and break any potential retain cycles, where the operation and block retain each other, therefore neither can be released from memory as they hold each other.
3. Add `Operation` extension to add multiple dependencies at once (see `Operation.addDependencies`)
4. Improve cancellation in background fetch.
5. Return `Cancellable` object from `TunnelManager.rotatePrivateKey`
---
This …
=> Improve background fetch cancellation

ios/MullvadVPN/REST/ServerRelaysResponse.swift, ios/MullvadVPN/RelaySelector.swift
Git checklist:
- Change `ServerRelay.weight` type to `UInt64`.
- Pick random relay when all relays within the list have zero weight.
- Fix roulette algorithm to skip relays with zero weight.
Similar PR for desktop: https://github.com/mullvad/mullvadvpn-app/pull/3262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3331)
=> Fix zero weight handling (iOS)

CHANGELOG.md, gui/src/main/daemon-rpc.ts, gui/src/main/index.ts, mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs, mullvad-management-interface/proto/management_interface.proto, talpid-core/src/split_tunnel/windows/mod.rs, talpid-core/src/split_tunnel/windows/volume_monitor.rs, talpid-core/src/tunnel_state_machine/mod.rs
This makes it possible to detect, for example, VeraCrypt volumes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3322)
=> Forward device arrival and removal window messages that are only received by users (not services)

gui/src/renderer/components/AdvancedSettingsStyles.tsx, gui/src/renderer/components/OpenVPNSettings.tsx, gui/src/renderer/components/WireguardSettings.tsx, gui/src/renderer/components/cell/Input.tsx
This PR improves the small text input used for OpenVPN Mssfix and WireGuard MTU by:
* Changing the background to white while focued. This improves contrast between the background and the red text when the value is invalid, as well as makes it more consistent with other inputs in the app.
* Discard invalid values on blur.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3342)
=> Make mssfix and mtu input white when focused

CHANGELOG.md, gui/locales/messages.pot, gui/src/main/index.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/ExpiredAccountAddTime.tsx, gui/src/renderer/components/RedeemVoucher.tsx, gui/src/renderer/lib/history.tsx, gui/src/renderer/lib/routes.ts, gui/src/renderer/redux/account/actions.ts, gui/src/renderer/redux/account/reducers.ts, gui/src/shared/daemon-rpc-types.ts
This PR removes the calculation of added time since it wasn't correct, and since it's not possible to do it correctly in all cases. When adding time we now show either `%(duration)s was added, account paid until %(expiry)s.` if it's a voucher payment, otherwise `Account paid until %(expiry)s.` is displayed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3339)
=> Fix time added display

gui/locales/messages.pot, gui/src/shared/notifications/error.ts
This PR updates the error message that's shown when there are no servers for the location and settings combination. The new message is `No servers in your selected location match your settings.`
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3346)
=> Update error message when there aren't any server for location/settings

CHANGELOG.md, gui/src/renderer/components/CustomScrollbars.tsx
This PR improves the event handling of the scrollbar implementation. Previously it reacted to all mouse events that intersected with the scrollbar/-track and didn't respect if it was covered by something else. Now the events `mouseenter`, `mouseleave` and `mousedown` is listened for on the track/bar instead of document.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3345)
=> Fix scrollbar responsive through modal overlay

dist-assets/windows/installer.nsh
This PR updates the Windows uninstaller to remove the auto-start registry entry. It only does it for the user who runs the uninstaller.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3350)
=> Unset launch on startup on Windows during uninstall

gui/locales/messages.pot, gui/src/renderer/components/Account.tsx, gui/src/renderer/components/AdvancedSettings.tsx, gui/src/renderer/components/FilterByProvider.tsx, gui/src/renderer/components/NavigationBar.tsx, gui/src/renderer/components/NavigationBarStyles.tsx, gui/src/renderer/components/OpenVPNSettings.tsx, gui/src/renderer/components/Preferences.tsx, gui/src/renderer/components/SelectLanguage.tsx, gui/src/renderer/components/SplitTunnelingSettings.tsx, gui/src/renderer/components/Support.tsx, gui/src/renderer/components/WireguardKeys.tsx, gui/src/renderer/components/WireguardSettings.tsx
This PR removes the back button label in the desktop app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3351)
=> Remove back button label

Cargo.lock, mullvad-cli/Cargo.toml, mullvad-cli/src/cmds/account.rs, mullvad-cli/src/cmds/auto_connect.rs, mullvad-cli/src/cmds/beta_program.rs, mullvad-cli/src/cmds/block_when_disconnected.rs, mullvad-cli/src/cmds/bridge.rs, mullvad-cli/src/cmds/connect.rs, mullvad-cli/src/cmds/disconnect.rs, mullvad-cli/src/cmds/dns.rs, mullvad-cli/src/cmds/lan.rs, mullvad-cli/src/cmds/reconnect.rs, mullvad-cli/src/cmds/relay.rs, mullvad-cli/src/cmds/reset.rs, mullvad-cli/src/cmds/split_tunnel/linux.rs, mullvad-cli/src/cmds/split_tunnel/windows.rs, mullvad-cli/src/cmds/status.rs, mullvad-cli/src/cmds/tunnel.rs, mullvad-cli/src/cmds/version.rs, mullvad-cli/src/location.rs, mullvad-cli/src/main.rs, mullvad-daemon/Cargo.toml, mullvad-daemon/src/cli.rs, mullvad-problem-report/Cargo.toml, mullvad-problem-report/src/main.rs, mullvad-setup/Cargo.toml, mullvad-setup/src/main.rs
The changes are fairly minimal. All breaking API changes and deprecated functionality are fixed. Unfortunately, clap 2.34 is still a dependency due to `udp-over-tcp`.
Closes #3305.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3353)
=> Upgrade clap to 3.0

gui/src/renderer/components/ExpiredAccountAddTime.tsx
This PR fixes an error that occured when creating a new account and switching back to the previous one with the CLI. The bug was introduced in this PR: https://github.com/mullvad/mullvadvpn-app/pull/3339.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3357)
=> Handle undefined expiry

mullvad-daemon/src/relays/updater.rs, mullvad-daemon/src/wireguard.rs, mullvad-rpc/src/availability.rs, talpid-core/Cargo.toml, talpid-core/src/future_retry.rs
This branch brings 3 small changes:
- change the missed tick behavior in intervals to skip the missed ticks
- log every API availability change
- add some timer tests to our retry logic to ensure they do not panic with the interval values we're using
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3363)
=> Log api availability and improve interval usage

talpid-core/src/tunnel/wireguard/connectivity_check.rs
`test_establish_timeout` has a great history of failing in CI for no
good reason. Whilst the _correct_ way of solving this issue would be to
mock the clock, I've added extra slack to the test to make it fail less
often.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3361)
=> Add extra slack to test_establish_timeout

android/app/build.gradle.kts, android/buildSrc/src/main/kotlin/Dependencies.kt, android/buildSrc/src/main/kotlin/Extensions.kt, android/buildSrc/src/main/kotlin/Versions.kt
Adds a new build type which can be used to identify memory leaks by using the Leak Canary dependency/tool.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3201)
=> Add canary build type for checking memory leaks

talpid-core/src/tunnel/tun_provider/android/mod.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/disconnected_state.rs, talpid-core/src/tunnel_state_machine/disconnecting_state.rs, talpid-core/src/tunnel_state_machine/error_state.rs, talpid-core/src/tunnel_state_machine/mod.rs
Seems to be a holdover from the old hacky implementation. Since `VpnService.protect()` is called for all Mullvad API sockets, it should be unnecessary to modify the routes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3358)
=> Remove allowed endpoint from Android tun provider

gui/src/renderer/components/Changelog.tsx
This PR fixes the title in the changelog dialog. This wasn't updated in https://github.com/mullvad/mullvadvpn-app/pull/3344 to have the right size and color.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3369)
=> Fix changelog title styles

gui/changes.txt, prepare-release.sh
Instead of having the changes from the last release in `gui/changes.txt` it can contain instructions on how to update it. This has a number of benefits:
* We don't need to keep backporting its contents from release branches into the main branch. It can stay static.
* Known contents allows us to sanity check it in `prepare_release.sh`, like I have done here.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3374)
=> Make gui/changes.txt include instructions on how to fill it

CHANGELOG.md, mullvad-daemon/src/lib.rs, mullvad-daemon/src/settings.rs
This prevents the app from entering the (non-blocking) disconnected state unexpectedly. For example, if "always require VPN" or auto-connect was previously enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3373)
=> Enable "Always require VPN" by default if settings cannot be parsed

CHANGELOG.md, gui/locales/messages.pot, gui/src/renderer/app.tsx, gui/src/renderer/components/Login.tsx, gui/src/renderer/components/LoginStyles.tsx, gui/src/renderer/containers/LoginPage.tsx
This PR adds warning messages for when the app is logged out and Always require vpn is on or if the app is in the blocked state.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3378)
=> Add blocking message on login page

CHANGELOG.md, gui/src/renderer/components/Account.tsx, gui/src/renderer/components/AdvancedSettings.tsx, gui/src/renderer/components/FilterByProvider.tsx, gui/src/renderer/components/KeyboardNavigation.tsx, gui/src/renderer/components/Modal.tsx, gui/src/renderer/components/NavigationBar.tsx, gui/src/renderer/components/NavigationBarStyles.tsx, gui/src/renderer/components/OpenVPNSettings.tsx, gui/src/renderer/components/Preferences.tsx, gui/src/renderer/components/SelectLanguage.tsx, gui/src/renderer/components/SelectLocation.tsx, gui/src/renderer/components/Settings.tsx, gui/src/renderer/components/SplitTunnelingSettings.tsx, gui/src/renderer/components/Support.tsx, gui/src/renderer/components/WireguardKeys.tsx, gui/src/renderer/components/WireguardSettings.tsx, gui/src/renderer/components/cell/Input.tsx
This PR changes the behavior of the escape hot key. It now navigates one step back instead of all the way to the main view. For navigating back to the main view Shift+Escape is used. To enable this I had to change how the back actions are registered.
Back actions are now registered using a `<BackAction ...>` component and both the escape listener and the back/close button uses the action registered in `BackAction`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3382)
=> Improve escape shortcut

CHANGELOG.md, talpid-core/src/tunnel/wireguard/mod.rs
The bypass feature for the API previously did not work very well in the connecting state. This is because the default/1-prefix-routes were added before connectivity had been established, so requests were sent inside a possibly non-functional tunnel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3385)
=> Improve tunnel bypass while in the connecting state

gui/src/renderer/components/ConnectionPanel.tsx
This PR shrinks the width of the connection panel header to the size of its content. Previously it was possible to click to the right of the label and chevron to open it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3393)
=> Shrink connection panel header to the size of its content

gui/package-lock.json, gui/package.json, gui/scripts/build-proto.sh, gui/src/main/daemon-rpc.ts
This PR updates gRPC and its build tools. This has the following benefits:
* We can remove the `'grpc.enable_http_proxy': 0,` option
* There's now a proper constructor for the gRPC client
* We can remove a the last `// @ts-ignore` in the app since the types are now correct. :tada:
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3396)
=> Update gRPC and related build tools

gui/src/renderer/components/ErrorBoundary.tsx, gui/src/renderer/components/ErrorView.tsx, gui/src/renderer/components/HeaderBar.tsx, gui/src/renderer/components/Login.tsx
This PR
* Disables the settings button when other input elements on login page are disabled
* Remove the settings icon from error boundary.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3403)
=> Improve settings button behavior

mullvad-rpc/src/rest.rs
The request factory does not always correctly set timeouts correctly. This PR fixes this. The issue is fairly harmless as the default timeout is 10 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3401)
=> Fix REST request factory timeouts

mullvad-daemon/src/target_state.rs
Minor cleanup. An error is logged if there's no target state file on exit. This is actually expected behavior if the target state hasn't been set at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3402)
=> Don't log an error if the target state cache cannot be removed on exit

android/build.gradle.kts, android/config/dependency-check-suppression.xml
The CVE (CVE-2022-24329) only affects "Multiplatform Gradle Projects" according to the CVE description, which this project is not, and therefore it's considered a false positive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3405)
=> Suppress false positive Android CVE

Cargo.lock
As described [here](https://rustsec.org/advisories/RUSTSEC-2022-0013), it is possible to construct regexes that take arbitrary amounts of time to compile. This PR upgrades `regex` to 1.5.5, which fixes this. Note that it doesn't affect the app, however, as all regexes are effectively constants.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3406)
=> Placate Rust audit CI job 

CHANGELOG.md, gui/locales/messages.pot, gui/src/renderer/app.tsx, gui/src/renderer/components/AdvancedSettings.tsx, gui/src/renderer/components/SplitTunnelingSettings.tsx, gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx
This PR adds a toggle for split tunneling on Windows. I've also prevented "Split tunneling" from being translated since it shouldn't be.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3415)
=> Add split tunneling toggle on Windows

ios/MullvadVPN/SimulatorTunnelProvider.swift
Git checklist:
1. Use locks directly without helpers for clarity and simplicity; release locks before calling callbacks for safety.
2. Simulate VPN connection's `connectedDate` when on simulator, which is normally available when running on device. It's not used anywhere yet, but we may need it later on.
3. Make sure that simulator tunnel switches back to `connected` state once `reasserting` is set to `false`. This is observed behaviour when running on device and we should replicate it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3410)
=> Improve simulator tunnel

CHANGELOG.md, mullvad-rpc/src/rest.rs
Since the dawn of time, the REST request service has owned a copy of its own command sender. Because of this, the actor never stops waiting for commands to process. This is made apparent by the fact that sockets remain open long after location lookups are made. Notably, it also means that the lookup RPC previously leaked some memory every time it was called.
The PR fixes this by only keeping a weak reference to the sender.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3407)
=> Shut down REST request service when all handles have been dropped

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/MullvadVPN/IPAddressRange+Codable.swift, ios/MullvadVPN/PrivateKeyWithMetadata.swift, ios/MullvadVPN/REST/RESTClient.swift, ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/TunnelSettings.swift
Git checklist:
Based on the recently merged PR:  https://github.com/mullvad/wireguard-apple/pull/2
- GUI app shall use `WireGuardKitTypes` when it needs to work with data structs used by `WireGuardKit`.
- Packet tunnel shall continue using `WireGuardKit` which links against `wg-go` that comes with go runtime. This is expected. `WireGuardKit` also re-exports `WireGuardKitTypes` so there is no need to import it individually in the packet tunnel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3423)
=> Remove go runtime from GUI process

windows/winnet/src/winnet/routing/defaultroutemonitor.cpp
The potential for this to cause any issues is probably very small, but surely the route monitoring must start before the initial default route is obtained. Otherwise there's a chance that a route change is missed immediately after fetching the initial route.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3426)
=> Begin listening to route changes before initializing the current default route

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Logging/Logging.swift, ios/PacketTunnel/PacketTunnelProvider.swift, ios/PacketTunnel/Pinger.swift, ios/PacketTunnel/TunnelMonitor.swift, ios/PacketTunnel/TunnelMonitorConfiguration.swift
Git checklist:
1. Add `TunnelMonitor` to monitor the tunnel connection by issuing ICMP requests (via `Pinger`) towards gateway and monitor WireGuard stats for the bytes received.
2. Handle when network goes offline and pause pinging. Likewise, resume pinging when network becomes available.
3. Refactor packet tunnel to follow the KISS, get rid of promises and wire up `TunnelMonitor`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3424)
=> Add tunnel monitor in Packet Tunnel

talpid-core/src/offline/windows.rs, talpid-core/src/routing/windows.rs, talpid-core/src/split_tunnel/windows/mod.rs, talpid-core/src/tunnel/wireguard/wireguard_go.rs, talpid-core/src/winnet.rs, windows/winnet/src/winnet/routing/defaultroutemonitor.cpp, windows/winnet/src/winnet/routing/defaultroutemonitor.h, windows/winnet/src/winnet/winnet.cpp, windows/winnet/src/winnet/winnet.h
If the preferred default route still uses the same interface as before but the IP address of the interface has changed, the ST driver must be notified of this. The main change made by this PR is to add a new event to the route monitor which is sent when the interface is updated in any way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3427)
=> Notify the daemon if any interface details change

talpid-core/src/split_tunnel/windows/mod.rs
It might be that we cannot obtain any addresses for the interface used for excluded apps, even if a route exists. This PR doesn't fix the issue but adds some logging that might be helpful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3421)
=> Warn if IPs cannot be obtained for default routes

mullvad-daemon/src/device.rs, mullvad-daemon/src/migrations/account_history.rs, mullvad-daemon/src/migrations/device.rs, mullvad-daemon/src/migrations/mod.rs, mullvad-daemon/src/migrations/v5.rs
This doesn't eliminate non-vendored types, but makes sure that outside modules are only imported in `migrations::device`, not in any `v{n}` module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3433)
=> Move imported types out of `v5` module

.github/workflows/daemon.yml
The nightly CI fails due to https://github.com/briansmith/ring/issues/1469. Trying to wrestle Github Actions into allowing nightly to fail but still show it as a red marker in PRs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3442)
=> Enable continue-on-error for the nightly Rust job

talpid-core/src/proxy/shadowsocks.rs, talpid-core/src/split_tunnel/linux.rs
This first caught my attention when seeing the code `T: Into<i32> + ToString`. `T` was never used as integers. It was only converted to string. So this felt like a strange way to try to encourage the user to send `i32`s instead of just taking an `&[i32]` directly. I first converted to that and tried it. But it did not work. I then realized that the code did not put any separators between the PIDs it wrote. So essentially trying to add PIDs `&[1, 2, 3]` resulted in `"123"` being written to the file.
I guess this bug was never found because we never called this method with more than one PID.
Some more possible improvements I see here that is out of scope for this PR is:
* Convert the OpenVPN Shadowsocks proxying into using our bundled Shadowsocks library, not `sslocal` as a subprocess. I …
=> Fix bug with `PidManager::add_list`

CHANGELOG.md, Cargo.lock, tunnel-obfuscation/Cargo.toml, tunnel-obfuscation/src/udp2tcp.rs
This fixes the issue where `Udp2Tcp::run` doesn't destroy sockets when dropped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3440)
=> Bump `udp-over-tcp` to 0.2

android/app/src/main/res/values/strings_non_translatable.xml
The URL is a left-over after implementing in-app account creation via the daemon.
Git checklist:
~~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3441)
=> Remove unused account creation url in Android

mullvad-daemon/src/lib.rs
Honor the `Off` setting and don't treat it as `Auto`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3446)
=> Correct the logic which guards obfuscator selection

gui/locales/messages.pot, gui/src/renderer/components/DeviceRevokedView.tsx
The device revoked view was missing parts of the text that is supposed to display. This PR adds the missing parts.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3447)
=> Fix device revoked message

Cargo.lock, tunnel-obfuscation/Cargo.toml
Upgrading `udp-over-tcp` to pull in this fix: https://github.com/mullvad/udp-over-tcp/pull/26
Allows us to shed `structopt` old `clap` from our dependency tree
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3448)
=> Upgrade udp-over-tcp to get rid of structopt dependency

talpid-core/src/firewall/mod.rs
Previously, this is only done for the blocking firewall state, but it would be useful here as well for debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3451)
=> Log allowed endpoint for the connecting firewall state

.github/workflows/android-app.yml, .github/workflows/android-audit.yml, .github/workflows/android-ktlint.yml, .github/workflows/android-xml-tidy.yml, .github/workflows/cargo-audit.yml, .github/workflows/daemon.yml, .github/workflows/frontend.yml, .github/workflows/ios.yml, .github/workflows/rustfmt.yml, .github/workflows/translations.yml
I found the list on the left hand side of https://github.com/mullvad/mullvadvpn-app/actions a bit hard to parse. With this change, all Rust-related CI jobs will start with "Rust", so hopefully they end up next to each other and are easier to spot.
I also removed "CI" at the end of all names. That felt superfluous
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3371)
=> Rename some Github Actions jobs to make them easier to find

ios/MullvadVPN/TunnelManager/TunnelManager.swift
Git checklist:
Normally the tunnel manager receives a system notification when tunnel connection status changes from `connecting` to  `connected` or `reasserting` (aka `reconnecting`) state. In response to those notifications, tunnel manager issues IPC request to fetch the relay the tunnel process is attempting to establish connection with.
However due to introduction of tunnel monitor, the tunnel process may remain in the `connecting` or `reasserting` state until VPN connection is fully established, hence no system notifications are issued. We use a timer to poll tunnel process periodically.
However if user requests to change relay during the `connecting` or `reconnecting` phase, we won't see …
=> Refresh tunnel status only when connecting or reasserting to pick up the next relay

mullvad-daemon/src/lib.rs, mullvad-daemon/src/relays/mod.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types.rs, mullvad-types/src/location.rs
The obfuscator hostname should be propagated to the frontends, which implies that it should be stored for later querying in the daemon. Since all other relays were being kept as fields in the daemon god-struct, I factored them out into a single enum containing all the individual relays that could be selected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3449)
=> Propagate selected obfuscator hostname to frontends

CHANGELOG.md, mullvad-daemon/src/relays/mod.rs
This PR updates the relay selector to use use roulette wheel selection for (Shadowsocks) bridges instead of always selecting the bridge closest to the relay location.
The "bias" constant may be adjusted. It is currently set to 3, which gives a 10% probability of selecting the closest bridge (out of approximately 40), and a 50% probability of selecting one of the 7 closest bridges.
Here is a comparison of a few different bias values (_B_), assuming there are 40 bridges:
| B | P(closest) | n for P(one of n closest servers)=0.5 | n for P(one of n closest servers)=0.75 |
|---|------------|----------------|-----------------|
| 1 | 5%         | 12             | 25              |
| 3 | 9.5%       | 7              | 13              |
| 5 | 13.9%      | 5              | 9               |
<details> …
=> Randomize bridge selection

mullvad-daemon/src/api.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/disconnected_state.rs, talpid-core/src/tunnel_state_machine/disconnecting_state.rs, talpid-core/src/tunnel_state_machine/error_state.rs, talpid-core/src/tunnel_state_machine/mod.rs
This PR fixes two bugs:
* `TunnelCommand::AllowEndpoint` updated the firewall policy twice in the connecting state, for no good reason.
* The `allowed_endpoint` field was updated regardless of whether setting the firewall policy succeeded. It now keeps using the old endpoint in case it fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3458)
=> Don't update the firewall policy twice when setting a new allowed endpoint

ios/MullvadVPN/SpinnerActivityIndicatorView.swift
Git checklist:
Previously we used software rendering for spinner using `CAShapeLayer`s. I figured there is no need for that since PDF vectors seem to be resampled and scaled with no issues when using `UIImageView`. So in this PR instead of mimicking the look of our spinner, the new code uses a PDF asset instead. The rest remains the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3454)
=> Drop software rendering in spinner

CHANGELOG.md, gui/src/main/index.ts, gui/src/renderer/components/List.tsx
This PR fixes:
* That the devtools wont open on windows
* A race condition in the `List` component which prevented items from being removed. The solution implemented is to add a fallback timeout that removes it if `onTransitionEnd` isn't triggered.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3466)
=> Fix app list race

dist-assets/uninstall_macos.sh
This might happen because the API is not reachable, or simply because the device no longer exists. Regardless of the reason, it should not prevent the app from being uninstalled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3465)
=> Don't abort the uninstallation if removing the device fails on macOS

gui/locales/messages.pot, gui/src/renderer/components/BridgeLocations.tsx
This PR changes the label on the "Closest to exit server" bridge option since it's now weighted randomness which will favor servers close to the exit server, but will not necessarily choose servers close. An info dialog that explains this has also been added.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3469)
=> Change label and add info to automatic bridge item

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Operations/AsyncBlockOperation.swift, ios/MullvadVPN/Operations/AsyncOperation.swift, ios/MullvadVPN/Operations/ResultOperation.swift
Git checklist:
1. Add `ResultOperation` base class that guarantees to emit `OperationCompletion<Success, Failure>` upon completion, but before operation is finished. This should get rid of a lot of boilerplate code in operation subclasses that often maintain its own completion handler. 
Note that calling completion handler before finishing the operation subclass opens a window of opportunity for the handler to perform some routine as a part of the task, which we leverage in few places. In contrast the standard `completionBlock`, that can be assigned on operations,  executes after operation is finished.
2. Operations should automatically finish if cancelled before starting. This should further …
=> Add result operation

gui/src/main/gui-settings.ts, gui/src/main/index.ts, gui/src/main/windows-split-tunneling.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/List.tsx, gui/src/renderer/components/SplitTunnelingSettings.tsx, gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx, gui/src/renderer/redux/settings/actions.ts, gui/src/renderer/redux/settings/reducers.ts, gui/src/shared/application-types.ts, gui/src/shared/ipc-schema.ts
This PR adds a button to remove manually added applications in the split tunneling view on Windows. I also did a small fix for accessing the ref in the `List` clean up code.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3468)
=> Add split tunneling remove button

.github/workflows/frontend.yml, .github/workflows/translations.yml, gui/package-lock.json
This PR:
* Contains an updated `package-lock.json` for the latest version of NPM
* Prevents the frontend job linter step from running on Windows, since it's already running on Linux
* Switches to using the npm cache in `actions/setup-node@v3` instead of a separate third party action.
According to my observations the action improvements save more than a minute each run.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3480)
=> Switch to using the cache function in actions/setup-node

gui/src/main/daemon-rpc.ts, gui/src/main/index.ts, gui/src/renderer/app.tsx, gui/src/shared/ipc-schema.ts
This PR makes the app wait until device info has been received before leaving the `launch` view. It also adds the `updateDevice` call since that was previously done automatically in `getDevice`, but now is a separate call.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3472)
=> Show launch view before receiving device config

gui/package-lock.json
This PR update a few dependencies with known vulnerabilities. As far as I can tell, none of these affect us. The remaining regular expression denial of service wont affect us negatively. This PR closes #3444 and #3462.
`npm audit` output before changes:
```
ansi-regex  3.0.0
Severity: moderate
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/cli-truncate/node_modules/ansi-regex
glob-parent  <5.1.2
Severity: high
Regular expression denial of service in glob-parent - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix --force`
Will install gulp@3.9.1, which is a breaking change
node_modules/glob-parent
chokidar  1.0.0-rc1 - 2.1.8
Depends on …
```
=> Update dependencies with known vulnerabilities

CHANGELOG.md, mullvad-daemon/src/migrations/account_history.rs
When updating from `2021.4` to `2022.1` and the user had never logged in, the migration stopped because the code treated an empty, valid account history as an error. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3482)
=> Don't treat an empty account history as invalid

mullvad-cli/src/cmds/version.rs
The indentation in the output of `mullvad version` isn't helpful:
```
Current version: 2022.1
Is supported: true
No newer version is available
Latest stable version: 2022.1
Latest beta version: 2022.1-beta2
```
"No newer version is available" is also not exactly correct.
I've updated it to look more like `mullvad account get`:
```
Current version      : 2022.1
Is supported         : true
Suggested upgrade    : none
Latest stable version: 2022.1
Latest beta version  : 2022.1-beta2
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3483)
=> Improve CLI version output slightly

.gitignore, Cargo.lock, Cargo.toml, README.md, docs/security.md, gui/tasks/distribution.js, mullvad-api/Cargo.toml, talpid-core/Cargo.toml, talpid-core/src/proxy/mod.rs, talpid-core/src/proxy/noop.rs, talpid-core/src/proxy/shadowsocks.rs, talpid-core/src/tunnel/mod.rs, talpid-core/src/tunnel/openvpn/mod.rs
This updates the Shadowsocks proxy monitor to use the crates instead of launching a subprocess, and removes all related binaries and references to them. It also contains some refactoring of the OpenVPN monitor.
Related PR: https://github.com/mullvad/mullvadvpn-app-binaries/pull/93
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3474)
=> Use Shadowsocks library instead of launching a subprocess

ios/MullvadVPN/AddressCache/AddressCacheTracker.swift, ios/MullvadVPN/AddressCache/UpdateAddressCacheOperation.swift, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/AppStorePaymentManager/AppStorePaymentManager.swift, ios/MullvadVPN/Operations/OperationCompletion.swift, ios/MullvadVPN/Operations/ResultOperation.swift, ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, ios/MullvadVPN/Result+UIBackgroundFetchResult.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift
Git checklist:
1. Return `OperationCompletion` from `TunnelManager.rotatePrivateKey()` instead of a pair of `KeyRotationResult?, TunnelManager.Error?`. This eliminates the need for both optional types, and for `KeyRotationResult` to contain the `cancelled` and `failed` cases, since `OperationCompletion` offers both of them.
2. Add `OperationCompletion.isSuccess: Bool` property which can be used to tell the system when background tasks complete. Drop `isTaskCompleted` extension.
3. Adapt iOS < 13 extension for producing `UIBackgroundFetchResult` from `OperationCompletion`.
4. Mark `ResultOperation.finish()` as unavailable to force subclasses to call `finish(completion:)` instead.
---
This change …
=> Return completion from key rotation

gui/locales/messages.pot, gui/scripts/extract-geo-data.py, gui/src/config.json, gui/src/renderer/components/AdvancedSettings.tsx, gui/src/renderer/components/CustomDnsSettings.tsx, gui/src/renderer/components/OpenVPNSettings.tsx, gui/src/renderer/components/SplitTunnelingSettings.tsx, gui/src/renderer/components/WireguardSettings.tsx, gui/src/shared/notifications/block-when-disconnected.ts, gui/src/shared/notifications/error.ts
This PR replaces the strings "WireGuard" and "OpenVPN" in translation strings with placeholders that will be replaced with the same strings. This is since we want to prevent technical terms and trademarks from being translated.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3486)
=> Prevent translating technical terms

CHANGELOG.md, gui/locales/messages.pot, gui/src/main/index.ts, gui/src/main/tray-icon-controller.ts, gui/src/shared/localization-contexts.ts
This PR adds a tooltip to the tray icon containing some connection info. Unfortunately it's not working on Ubuntu but it's working great on Windows and macOS. I haven't tested any other Linux distributions but due to the general tray icon support in Gnome I'm not surprised it isn't working.
Closes https://github.com/mullvad/mullvadvpn-app/issues/3368.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3490)
=> Add tray icon tooltip containing connection info.

gui/src/renderer/app.tsx
This PR fixes the bug where the gui claimed to be connecting over multihop when multihop was off. This happened if multihop had been on previously and specefic relays had been selected for entry and exit. The incorrect label was visible between the `disconnecting(reconnect)` and the `reconnecting` events. Between those events the location is calculated from the current constraints and there was a check for the multihop state missing.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3491)
=> Ignore entry location if multihop is off when using constraints for location

ios/CHANGELOG.md, ios/MullvadVPN/REST/ServerRelaysResponse.swift, ios/MullvadVPN/RelaySelector.swift, ios/MullvadVPNTests/RelaySelectorTests.swift
Git checklist:
- Improve random port distribution. Should be less biased towards port 53. See Rust code for reference: 
https://github.com/mullvad/mullvadvpn-app/blob/66ff8978f94d4ad1c8c45872de9f540cbcbcf612/mullvad-daemon/src/relays/matcher.rs#L202-L238
- Replace `CloseRange<UInt16>` in relay model with `[[UInt16]]`. Parse and validate  port ranges manually in `RelaySelector`, skip invalid ranges but don't error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3493)
=> Improve random port distribution

talpid-time/src/unix.rs
Previously, `talpid-time` refused to build for ARMv7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3499)
=> Use correct time constant type on all architectures

README.md
Both to increase discoverability and to help people go around censorship we want to add links to our Tor onion service to places where people can find it even if our website is blocked. Our Github app repository seems like a prime place for that. One of the reasons we upload the app build artifacts to Github is to help people download the app even if they are in a place where mullvad.net is blocked. This is another step in that direction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3500)
=> Add links to our website and Tor onion service to the readme

gui/src/main/index.ts
This PR adds a fallback quit handler. When logging out on Ubuntu the `quit` event is sometimes received without the preceding `before-quit` event. On most logouts the `quit` event isn't received and this won't do anything but sometimes it manages to disconnect.
Improves the issue described in https://github.com/mullvad/mullvadvpn-app/issues/3286 but is far from a solution unfortunately.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3496)
=> Add fallback quit handler

mullvad-daemon/src/relays/mod.rs
The relay selector test was testing if a WireGuard endpoint wasn't using
the same ports as TCP2UDP relays will be listening on. This doesn't make
much sense as a relay could very well be using those same ports, and in
some cases it was, thus making this test fail. The faulty assertion has
been removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3503)
=> Fix overzealous relay selector test

mullvad-cli/src/cmds/bridge.rs, mullvad-cli/src/cmds/obfuscation.rs, mullvad-cli/src/cmds/split_tunnel/linux.rs, mullvad-types/src/relay_constraints.rs
I found the following a bit confusing and uninformative:
```
$ mullvad --help
...
bridge                Manage use of bridges
obfuscation           Manage use of obfuscators
```
It is not clear what they are or what they are used for. I'm not a huge fan of the subcommand layoun we currently have. But until we fix that we can at least improve the help text. The bridge subcommand is specific to OpenVPN, so I think we should mention that. Sadly the bridge subcommand also configures a bunch of other stuff that is unrelated to bridges:
* Custom SOCKS5 proxies to use with OpenVPN
* Custom Shadowsocks endpoints to use with OpenVPN
The obfuscation subcommand is only about WireGuard even though using OpenVPN over Shadowsocks is equally much obfuscation. I'm not changing the subcommand name or …
=> Clarify cli obfuscation and bridges

CHANGELOG.md, gui/src/renderer/redux/account/reducers.ts
This PR prevents the login from being emptied when submitting an incorrect account number. This is the same behavior as on Android and iOS.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3504)
=> Prevent login input from being emptied on failed attempt

gui/src/renderer/components/Connect.tsx, gui/src/renderer/components/SecuredLabel.tsx
This PR:
* Removes the map marker in the blocking state
* Changes the connection status label color to white in the blocking state
The purpose of these changes is to prevent the blocking state from looking like everything is working perfectly.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3506)
=> Improve blocking state presentation

gui/src/renderer/components/TunnelControl.tsx
This PR:
* Changes the order of the country and city in the main view to prevent the country from jumping up and down when switching state, and to make the order more logical (country, city, hostname)
* Adds an element to make sure that the city row always takes up the same space even if no city is displayed
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3512)
=> Vertically fix location rows

gui/src/renderer/components/ConnectionPanel.tsx, gui/src/renderer/components/ConnectionPanelDisclosure.tsx, gui/src/renderer/components/Marquee.tsx, gui/src/renderer/components/TunnelControl.tsx
This PR fixes the height of the city and country containers. For some reason they added `2px` to the bottom of the container which caused everything to be bit to far apart resulting in the connection info not fitting and pushing the buttons downward.
The simplest solution was to add `vertical-align: middle` to the content.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3511)
=> Adjust margins in connection panel

CHANGELOG.md, gui/src/main/index.ts, gui/src/main/window-controller.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/AppRouter.tsx, gui/src/renderer/components/NavigationBar.tsx, gui/src/renderer/lib/history.tsx, gui/src/renderer/redux/userinterface/actions.ts, gui/src/renderer/redux/userinterface/reducers.ts, gui/src/shared/ipc-schema.ts, gui/src/shared/ipc-types.ts
This PR adds storage of the navigation history and scroll positions in the main process for reuse when the browser window is replaced or refreshed. This is useful when toggling unpinned window and when refreshing during development.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3507)
=> Remember history and scroll positions when replacing window

CHANGELOG.md, talpid-core/src/split_tunnel/windows/driver.rs, talpid-core/src/split_tunnel/windows/mod.rs
Changes:
* Deserialize the splitting event reason correctly and add some missing some flags.
* Generally reject invalid enum variants instead of unsafely initializing them.
* Rather than blindly trusting that the event buffer returned by the driver is valid, panic if the driver returns an event buffer that is too small.
* Document more unsafe code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3508)
=> Deserialize ST events correctly

android/app/build.gradle.kts, android/app/src/main/kotlin/net/mullvad/mullvadvpn/model/DeviceState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/DeviceRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt, android/app/src/main/res/layout/account.xml, android/app/src/main/res/values/strings.xml, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt, android/buildSrc/src/main/kotlin/Dependencies.kt, android/buildSrc/src/main/kotlin/Versions.kt
Refactor Android login to use a view model rather than keeping all logic in the fragment. Also fixes a few minor related account/device issues.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3505)
=> Refactor android login to use view model

CHANGELOG.md, talpid-core/src/dns/macos.rs, talpid-core/src/dns/mod.rs, talpid-core/src/tunnel_state_machine/mod.rs
These changes are an attempt to resolve  #3400. Whilst I haven't reproduced the issue itself, I do believe that only comparing the resovler IPs when comparing current and desired DNS configs should improve the thrashing, and in case it doesn't, debouncing logic has been added so that when there's too many DNS changes, the DNS monitor will just capitulate and force the daemon into the error state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3510)
=> Fix macos dns thrash

talpid-core/src/dns/macos.rs
Instead of logging the received DNS config changes, the wanted DNS config was being logged, which is the exact opposite of helpful. So I've changed it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3515)
=> Fix logging of DNS changes

README.md, ci/buildserver-build.sh, gui/package.json
This PR replaces `nvm` with [Volta](https://github.com/volta-cli/volta). This required adding a volta section to `package.json`, updating the readme, build server build script and GitHub Actions workflows.
To install Volta, run:
```
cargo install --git https://github.com/volta-cli/volta
volta setup
```
or follow the instructions in their repository.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3516)
=> Switch to volta

README.md, build.sh
This PR makes the build script use the correct node version. And also removes the instructions for how to manually install node from the readme.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3521)
=> Make build script use correct node version

CHANGELOG.md, gui/locales/messages.pot, gui/src/main/daemon-rpc.ts, gui/src/main/index.ts, gui/src/renderer/components/CustomDnsSettings.tsx, gui/src/renderer/components/Preferences.tsx, gui/src/renderer/redux/settings/reducers.ts, gui/src/shared/daemon-rpc-types.ts, mullvad-cli/src/cmds/dns.rs, mullvad-daemon/src/lib.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types.rs, mullvad-types/src/settings/mod.rs
The PR adds settings for the dns block-lists for adult conetnt and gambling. It adds it to both the CLI and the GUI frontend.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3524)
=> Add settings for blocking adult content and gambling

gui/package-lock.json, gui/package.json, gui/tasks/distribution.js
This PR fixes the macOS build server errors by upgrading `electron-builder` to `23.0.8` and adds `nseventmonitor` to the allow list for unique files in the asar bundle.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3526)
=> Fix macOS build server error

mullvad-api/src/device.rs
The previous code was actually incorrect, because the default value is `true`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3528)
=> Set `hijack_dns` to `false` explicitly

mullvad-daemon/src/logging.rs
`udp-over-tcp` makes a lot of noise when the log level is set to `trace`, logging this for every send/recv:
```
[2022-04-25 16:05:50.001][udp_over_tcp::forward_traffic][TRACE] Forwarded 112 bytes UDP->TCP
[2022-04-25 16:05:50.001][udp_over_tcp::forward_traffic][TRACE] Forwarded 112 bytes UDP->TCP
[2022-04-25 16:05:50.002][udp_over_tcp::forward_traffic][TRACE] Forwarded 112 bytes UDP->TCP
[2022-04-25 16:05:50.002][udp_over_tcp::forward_traffic][TRACE] Forwarded 1312 byte TCP->UDP
[2022-04-25 16:05:50.002][udp_over_tcp::forward_traffic][TRACE] Forwarded 1312 byte TCP->UDP
[2022-04-25 16:05:50.002][udp_over_tcp::forward_traffic][TRACE] Forwarded 1312 byte TCP->UDP
[2022-04-25 16:05:50.002][udp_over_tcp::forward_traffic][TRACE] Forwarded 1312 byte TCP->UDP
[2022-04-25 …
```
=> Make `udp-over-tcp` quieter

CHANGELOG.md, mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/matcher.rs
Previously, `get_any_tunnel_endpoint` did not return an entry/multihop endpoint when the preferred constraints failed to match any relay.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3529)
=> Never ignore the multihop setting when the tunnel protocol is set to "any"

mullvad-daemon/src/device/mod.rs
There were a couple of problems here:
1. The key rotation response was not sent back to the caller.
2. When updating the device, it was removed. The old device is only supposed to be removed when logging in to a new account or generating a new device.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3530)
=> Fix manual key rotation

gui/src/main/daemon-rpc.ts, gui/src/renderer/components/ConnectionPanel.tsx, gui/src/renderer/containers/ConnectionPanelContainer.tsx, gui/src/shared/daemon-rpc-types.ts
This PR adds the obfuscation endpoint to the endpoint state and shows that information for the `in` field in the connection panel.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3536)
=> Show obfuscation endpoint as in-data

mullvad-daemon/src/device/mod.rs
This PR fixes two issues:
* In the unlikely event of I/O errors, the device was removed in memory but no logout event nor API request was sent. I've fixed it so that it recovers properly.
* Logging out without a device set didn't return a correct result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3535)
=> Fix possible inconsistent state when logging out device

gui/tasks/distribution.js
For example, `2022.1-beta1-dev-HHHHHH` is newer than `2022.1-beta1`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3541)
=> Treat dev deb package versions as newer, all else equal

CHANGELOG.md, mullvad-api/src/availability.rs, mullvad-daemon/src/lib.rs, mullvad-types/src/states.rs
This PR makes it so that API requests are paused after some interval (currently 3 days) has elapsed, provided that no daemon commands were received during that time. This makes the daemon a bit less talkative even if the current account is still valid. The timer is only enabled when the tunnel state is not `disconnected`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3531)
=> Pause API interactions when no daemon commands are received

.github/workflows/android-app.yml, .github/workflows/daemon.yml, .github/workflows/rustfmt.yml, .github/workflows/translations-converter.yml, .github/workflows/translations.yml
Switching rust toolchain action due to some issues experienced with the internal caching of the previous action.
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (CI change)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3534)
=> Switch rust toolchain action

gui/locales/messages.pot, gui/src/renderer/components/TooManyDevices.tsx
This PR updates the message in the too many devices view. The main change is that "nickname" has been replaced with "device name".
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3543)
=> Update too many devices message

gui/locales/messages.pot, gui/src/renderer/components/AriaGroup.tsx, gui/src/renderer/components/InfoButton.tsx, gui/src/renderer/components/Preferences.tsx, gui/src/renderer/components/PreferencesStyles.tsx
This PR info-buttons for the block settings and adds a disabled toggle for the kill switch info.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3547)
=> Add block setting info

CHANGELOG.md, mullvad-cli/src/cmds/connect.rs, mullvad-cli/src/cmds/disconnect.rs, mullvad-cli/src/cmds/reconnect.rs, mullvad-cli/src/cmds/status.rs, mullvad-cli/src/format.rs
The output of the status command is reworked to show hostnames instead of IP addresses and trim the fat. The extra information (tunnel protocols, IP addrresses) are now available with the verbose flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3540)
=> Rework output of status subcommand in CLI

mullvad-daemon/src/device/mod.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/tunnel.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/mod.rs
Previously, the `TunnelParametersGenerator` trait used by the tunnel state machine was implemented in `mullvad_daemon`, and parameters were generated by passing messages to the `Daemon` instance. This PR adds a new struct, which is independent of the daemon, that takes over this responsibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3550)
=> Decouple tunnel parameters generation from daemon event handler

mullvad-daemon/src/cleanup.rs, mullvad-daemon/src/lib.rs
Some more low-hanging fruit cleanup. This only moves the directory cleanup part out of `Daemon`, since the factory reset requires mutable access to the settings instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3555)
=> Move factory reset to cleanup module

CHANGELOG.md, docs/relay-selector.md, mullvad-cli/src/cmds/bridge.rs, mullvad-cli/src/cmds/relay.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types.rs, mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/matcher.rs, mullvad-types/src/relay_constraints.rs
This adds support to the relay selector and CLI for filtering relays and bridges by server ownership. For example, you can choose to only connect to Mullvad-owned servers by running `mullvad relay set ownership owned`. To filter out all Mullvad-owned servers, run `mullvad relay set ownership rented`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3554)
=> Add server ownership relay constraint

.github/workflows/daemon.yml
Seems like the CI is failing to install `libdbus-dev-1` without updating it's package lists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3564)
=> Update package lists before installing dependency in CI

CHANGELOG.md, talpid-core/src/tunnel/wireguard/config.rs
Lowering the default MTU on Android to 1280. I tested this with 4g, 5g and WiFi, and I couldn't measure any difference that couldn't be noise, so I think this is a rather safe change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3562)
=> Lower default MTU to 1280 on Android

mullvad-daemon/src/device/mod.rs, mullvad-daemon/src/device/service.rs, mullvad-daemon/src/lib.rs
Small refactoring PR in the same vein as some earlier PRs: #3555, #3550.
Unrelatedly, this removes the `ReceiveEvents` command from the account manager, since we'll likely only need one listener.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3556)
=> Refactor device removal out of daemon struct

gui/src/main/daemon-rpc.ts, gui/src/main/errors.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/TooManyDevices.tsx
This PR makes the app stay in the login screen and show "Login failed" if there's an error fetching the device list when there are too many devices on the account.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3571)
=> Display login error if failed to fetch device list

gui/src/renderer/components/LocationRow.tsx
This PR makes the two button in each `LocationRow` look like individual buttons, and adds a separator in between them to make it more clear.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3568)
=> Add separator between buttons in LocationRow

gui/src/renderer/components/TooManyDevices.tsx
Currently it's possible to press the "Continue with login"-button multiple times when in the too many devices view. This results in telling the daemon to login multiple times. This PR fixes this by disabling the button after pressing it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3572)
=> Disable too many devices continue button when logging in

mullvad-daemon/src/device/mod.rs
As it stands currently, the daemon won't try to validate it's device data until after the 3rd time it will attempt to connect to a WireGuard relay. Without setting a tunnel protocol constraint, most users won't ever hit the third time unless they cannot connect to OpenVPN relays too. To increase the chances of a validation, I've lowered the threshold for a validation to 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3573)
=> Validate device after 2 failed WireGuard attempts

mullvad-api/src/lib.rs, mullvad-api/src/rest.rs, mullvad-daemon/src/device/service.rs
Previously, the response didn't contain a custom status code in the response body, so the device was inferred to be invalid if the HTTP status code was 404. This may cause a device to be "revoked" if an endpoint is removed/deprecated or deployed incorrectly, so this PR switches to using the custom json response code instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3574)
=> Check API response code to determine if a device is valid

mullvad-api/src/rest.rs, mullvad-daemon/src/device/mod.rs
In a reconnect loop, if a device check (after 3 attempts) fails due to a network error, it will be repeated after another 3 attempts. Otherwise, this check is not repeated. This is somewhat wrong because the tunnel transitions may drop in-flight API requests. If the check fails for this reason, it should also be repeated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3567)
=> Continue device check if the API request is aborted

gui/src/main/daemon-rpc.ts, gui/src/main/index.ts, gui/src/main/tray-icon-controller.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/Account.tsx, gui/src/renderer/components/LocationRow.tsx, gui/src/renderer/containers/AccountPage.tsx, gui/src/renderer/redux/account/actions.ts, gui/src/shared/connect-helper.ts, gui/src/shared/daemon-rpc-types.ts, gui/src/shared/ipc-schema.ts
This PR:
* Updates the frontend to use the updated device rpc call
* Initializes into the revoked view if that's the first received state
* Fixes fetching of device when logging out.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3579)
=> Improve device revoked state detection in electron app

android/translations-converter/src/gettext/match_str.rs
With the advent of the latest nightly, the unused macro expressions are
producing warnings, which fail the CI. So the unused expressions are
removed, and can be added back if they are ever required again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3584)
=> Remove unused macro expressions

build.sh, ci/buildserver-build.sh
Moves the code that tags artifacts to the buildserver and away from `build.sh`.
This means that the tagging code does not touch anything that a user interacts with and allows us to dodge having to implement the same logic in the `build-apk.sh` script.
The buildserver logic renames the artifact files that it can find inside of `/dist` and appends a cleaned tag if there is one. It only touches the artifacts that include `*-dev-*` in order to not modify release versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3577)
=> Tag artifact names only when developing

gui/src/renderer/app.tsx, gui/src/renderer/components/AppRouter.tsx, gui/src/renderer/components/KeyboardNavigation.tsx
This PR fixes a crash when the changes dialog is shown. The issue was that the back action context provider didn't wrap the changes dialog. This was solved by moving the keyboard navigation component further up the tree.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3589)
=> Fix missing back action context for changes dialog

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Account.swift, ios/MullvadVPN/AddressCache/AddressCacheStore.swift, ios/MullvadVPN/AddressCache/AddressCacheTracker.swift, ios/MullvadVPN/AddressCache/UpdateAddressCacheOperation.swift, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/AppStorePaymentManager/SendAppStoreReceiptOperation.swift, ios/MullvadVPN/AppStoreReceipt.swift, ios/MullvadVPN/Operations/AsyncBlockOperation.swift, ios/MullvadVPN/Operations/AsyncOperation.swift, ios/MullvadVPN/Operations/OperationCompletion.swift, ios/MullvadVPN/Operations/PresentAlertOperation.swift, ios/MullvadVPN/Operations/ProductsRequestOperation.swift, ios/MullvadVPN/Operations/ResultBlockOperation.swift, ios/MullvadVPN/Operations/ResultOperation.swift, ios/MullvadVPN/REST/RESTAccessTokenManager.swift, ios/MullvadVPN/REST/RESTNetworkOperation.swift, ios/MullvadVPN/RelayCache/RelayCacheTracker.swift, ios/MullvadVPN/TunnelIPC/TunnelIPCRequestOperation.swift, ios/MullvadVPN/TunnelIPC/TunnelIPCSession.swift, ios/MullvadVPN/TunnelManager/LoadTunnelOperation.swift, ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift, ios/MullvadVPN/TunnelManager/ReloadTunnelOperation.swift, ios/MullvadVPN/TunnelManager/ReplaceKeyOperation.swift, ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, ios/MullvadVPN/TunnelManager/SetTunnelSettingsOperation.swift, ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift, ios/MullvadVPN/TunnelManager/StopTunnelOperation.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift
Git checklist:
- Add `dispatchQueue` parameter to `AsyncOperation` initializer that enables developer to provide the queue used for synchronization. This queue is used to execute `main()` operation body.
- Add `operationDidCancel` and `operationDidFinish` methods that are called on the `dispatchQueue` as operation either cancelled or finished.
- Add new functional helpers to `OperationCompletion`.
- `AddressStore` will `throw` errors instead of returning `Result`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3597)
=> Pass dispatch queue to AsyncOperation and throw errors from AddressStore

CHANGELOG.md, dist-assets/windows/installer.nsh, windows/nsis-plugins/src/log/log.cpp
The NSIS installer/uninstaller leaves some files in `%TEMP%` that remain even after uninstalling:
```
mullvad-setup.exe
winfw.dll
driverlogic.exe
mullvad-split-tunnel/
nsXXX.tmp/log.dll
```
Most are straightforward to delete.
`log.dll` is not cleaned up because the module isn't freed until the process dies. NSIS normally unloads plugins after each function call. `log.dll` has global state, so it increases its own reference count by a ton to avoid being unloaded.
Unfortunately, NSIS is inconsistent and calls `FreeLibrary()` many more times than it calls `LoadLibrary()`, so we have no idea how many times to decrement the refcount. As a workaround, `FreeLibrary()` is called until the module is freed.
--- …
=> Remove temporary files used during setup

gui/src/main/index.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/Changelog.tsx, gui/src/renderer/redux/userinterface/actions.ts, gui/src/renderer/redux/userinterface/reducers.ts, gui/src/shared/ipc-schema.ts
This PR adds a command line switch (`--show-changes`) that shows the changes dialog on start.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3592)
=> Add command line switch for force display of changes dialog

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/MullvadApplication.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/di/UiModuleTest.kt
Fixes an issue with a UI specific DI module being loaded for all processes, even though it's only meant for the UI/Activity process.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3604)
=> Fix unused dependencies loaded in the Android service/tile DI graph

CHANGELOG.md, Cargo.lock, android/app/src/main/kotlin/net/mullvad/mullvadvpn/model/RemoveDeviceEvent.kt, gui/src/main/daemon-rpc.ts, gui/src/renderer/redux/account/actions.ts, gui/src/shared/daemon-rpc-types.ts, mullvad-api/src/device.rs, mullvad-cli/src/cmds/account.rs, mullvad-daemon/src/device/mod.rs, mullvad-daemon/src/device/service.rs, mullvad-daemon/src/lib.rs, mullvad-management-interface/Cargo.toml, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types.rs, mullvad-types/src/device.rs
Changes:
* Sort devices chronologically (oldest first) in the "Too many devices" view
* Sort devices chronologically when calling `mullvad list-devices`.
* Show device creation in CLI device list.
* Add `hijack_dns` and `created` fields to `device.json`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3611)
=> Sort device list by age

ios/MullvadVPN/SelectLocationCell.swift
Git checklist:
- Add multiline support to location labels to account for "System transparency [BETA]" group of relays that are currently being clipped out.
- Fix label layout where previously the trailing edge of label would stick to the leading edge of collapse button or grow past it when too long. It should actually grow until collapse button but not past it. In ASCII words: `[label] < [collapse button]` and not `[label] >= [collapse button]`.
Fixes it to look as following:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3612)
=> Fix relay location cell layout + add multiline support

CHANGELOG.md, gui/src/main/index.ts, mullvad-daemon/src/device/mod.rs, mullvad-daemon/src/management_interface.rs
The GUI did not handle errors when trying to fetch the current device state and simply failed if the device could not be updated. This PR fixes this by falling back on the last known state an error occurs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3614)
=> Fix logout not working in the GUI when the API is not reachable

android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceAwareFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/DeviceRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnection.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionContainer.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionManager.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt
This PR aims to be a step in improving the how the connection between the UI and service is managed and shared within the UI process. The improvement consist of relying on _flow_ and Android lifecycle mechanisms as well as providing a path for migration (for future PRs) of the coupling that exist in the fragment inheritance along with the service container (`ServiceConnection`  -> `ServiceConnectionContainer`).
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (skipped reason: refactor)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3610)
=> Improve android service connection management

ios/PacketTunnel/PacketTunnelProvider.swift
Git checklist:
Looks like I forgot to pass the relay selector result when starting the tunnel from GUI app. This PR fixes this omission.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3628)
=> PacketTunnel: pass relay selector on start

mullvad-daemon/src/logging.rs
I saw when trying out the PQ builds of the app that `tower` was `DEBUG` logging to `daemon.log`. I don't think these messages will be helpful in debugging issues, so I will silence it, same way we do with most other third party crates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3633)
=> Silence crate `tower` from the logs

ios/build-wireguard-go.sh, ios/prebuild.sh
Fixing #3617, #3618 and #3619.
@albin-mullvad Does it even make sense to edit `gradlew` or should we let it be?
@pronebird is the change from `exit -1` into `exit 1` going to break something? I don't think negative exit codes are very standard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3625)
=> Correct bash shebang

ios/CHANGELOG.md
We did not add any changelog header when releasing `2022.2`. I did this now. I hope this should be correct. The date is the date when we submitted the app for release-review to Apple, not the date I first uploaded it to them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3636)
=> Add 2022.2 header to changelog

talpid-core/src/routing/linux.rs, talpid-core/src/routing/mod.rs, talpid-core/src/routing/unix.rs, talpid-core/src/tunnel/mod.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs
Draft for setting the MTU of the wireguard tunnel.
When starting the Wireguard tunnel checks the MTU for the route to the connection endpoint and then sets the MTU in the Wireguard parameters to whatever is lesser between the provided MTU and 1400.  We also log when the provided MTU is different from 1500 in order to detect weirdness.
Next steps include detecting a better MTU over a real network.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3609)
=> Set mtu on wireguard

talpid-core/src/tunnel_state_machine/disconnected_state.rs
Unless "always require VPN" is enabled, there's no need to update the firewall policy when toggling allow LAN on or off, or when setting the allowed endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3637)
=> Don't reset firewall policy in disconnected state unnecessarily

talpid-core/src/split_tunnel/windows/driver.rs, talpid-core/src/split_tunnel/windows/mod.rs
This is mainly to ensure that everything is fully reset when fast startup is enabled (which is just hibernation for services, including devices/drivers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3649)
=> Rebuild ST driver process tree when the daemon starts

CHANGELOG.md, talpid-core/src/routing/linux.rs
Patches a bug caused by an incorrect assumption that a route node will only either have an IP or a device. Also turns a panic into an error to avoid future crashes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3655)
=> Detect mtu on wireguard bugfix

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragmentTest.kt, ci/run-android-instrumented-tests.sh
Fix always passing instrumented test script due to adb not returning error codes when failing. This is achived by parsing test logs.
Also fixes a test that was failing on master.
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (tests only)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3659)
=> Fix instrumented tests

README.md
Reading #3651 made me realize we haven't documented the environment variable used to specify the mount point of the `net_cls` controller,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3660)
=> Add info about net_cls env var

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionContainer.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionManager.kt
The app is not unregistering from events before unbinding from the service, which result in messages (duplicates) delivered to old message handlers after the service has been bound again. This issue has been hidden in the current implementation as the messages were not propagated further within the app.
The issue is fixed by making sure to unregister before unbinding.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3646)
=> Fix missing IPC event unregistration

talpid-core/src/offline/mod.rs, talpid-core/src/offline/windows.rs, talpid-core/src/tunnel_state_machine/mod.rs, talpid-core/src/windows/window.rs
Move the code for monitoring power events out of the offline monitor module into a general `PowerManagementListener` type. Mainly done in order to make it reusable (i.e., for `split_tunnel`) in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3650)
=> Add power management event listener

talpid-core/src/firewall/linux.rs, talpid-core/src/firewall/macos.rs, talpid-core/src/firewall/windows.rs, talpid-core/src/tunnel/wireguard/mod.rs, talpid-tunnel-config-client/src/lib.rs, talpid-types/src/net/mod.rs, windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp, windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp, windows/winfw/src/winfw/rules/shared.cpp, windows/winfw/src/winfw/rules/shared.h, windows/winfw/src/winfw/winfw.h
Since blocking non-ICMP traffic while connecting is unnecessary (worse than not doing so, even), this PR removes that option for the `AllowedTunnelTraffic` type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3663)
=> Remove ICMP protocol from options that block tunnel traffic

mullvad-problem-report/src/lib.rs, talpid-core/src/split_tunnel/windows/driver.rs
This PR updates the problem report tool to redact `*\Users\<current user>` from any path, including excluded device paths. Also, device paths are logged more nicely (using `\` instead of `\\`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3664)
=> Redact home dir for device paths

ios/MullvadVPN/AccountInputGroupView.swift, ios/MullvadVPN/LoginContentView.swift, ios/MullvadVPN/LoginViewController.swift
Git checklist:
1. Add animation to last used account row
2. Fix login container height, so that it remains the same when last used account row is collapsed
3. Drop absolute dimension (height) for last used account row and instead let the row flow naturally. Using `UIMetrics.textFieldMargins` for `contentEdgeInsets` to match the text field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3669)
=> Login: fix constraints and add animations

gui/src/renderer/components/LocationRow.tsx
Fixes a minor regression introduced in this PR: https://github.com/mullvad/mullvadvpn-app/pull/3568. Text was white for relays/locations that were already selected as the exit or entry endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3679)
=> Fix opacity for unavailable multihop endpoints

Cargo.lock
I ran `cargo deny check` and it found these two yanked crates in our dependency tree. Upgrading them was simple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3681)
=> Update yanked dependencies

mullvad-cli/src/format.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs
In practice, this means that the app will try to connect to a different server if it stumbles upon a server that does not yet support PQ, when quantum-resistant tunnels are enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3688)
=> Reconnect when connecting to the tunnel config service fails for any reason

.github/workflows/ios.yml, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Git checklist:
This PR updates the `Package.resolved` manifest to the newest which is what Xcode 13.3 (perhaps) or newer use. For CI job, there is a small `jq` script that maps v2 to v1 manifest. Hopefully we'll drop that in the future or Xcode will ship a compatibility patch. All in all the conversion is fine for CI as the `revision` is preserved and this is all we really need when pulling dependencies for CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3693)
=> Update Package.resolved (v2)

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
This PR aims to fix a few issues related to the tile service:
* Improve how/when the vpn service starts as a foreground service to avoid getting killed by the system for being too slow.
* Handle tile clicks when the device is locked, which will prompt the user to unlock the device.
* Simplify internal state handling in the tile service.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3695)
=> Fix android foreground and tile state

Cargo.lock, talpid-core/Cargo.toml, talpid-core/src/dns/linux/mod.rs, talpid-core/src/dns/linux/static_resolv_conf.rs
Switch from notify to inotify since we only used notify on Linux.
Use inotify instead of notify since we only use notify on Linux. This allows us to get rid of old dependencies that we do not need.
Transitioning required some small changes in the API usage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3705)
=> Remove notify dependency and add inotify instead

CHANGELOG.md, talpid-core/src/dns/windows/mod.rs
The output of CLI tools on Windows can basically never be trusted. They are very often localized. This simply removes the parsing of stdout from `ipconfig.exe`. Since I'm not aware of any other way to check if the call succeeded I'm just going to not check it at all. Hopefully it will never fail, and if it does I don't think it will have too much harm.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3707)
=> Don't rely on the stdout message from ipconfig, it's localized

.github/workflows/cargo-audit.yml, .github/workflows/rust-supply-chain.yml, Cargo.lock, deny.toml, talpid-dbus/Cargo.toml, talpid-tunnel-config-client/Cargo.toml, tunnel-obfuscation/Cargo.toml
More automatic help with keeping our dependency tree and supply chain in check. Longer term I want us to fix most stuff that `cargo deny check` reports. But for now that's too much, so I'll start off with just checking the sources, which are currently OK.
There is some work to be done with the licenses later. We need to figure out which ones we should just allow. And we might want to probe some upstream dependencies to add a license statement at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3692)
=> Add initial cargo deny config and CI job

Cargo.lock, mullvad-api/Cargo.toml
I was wondering why we had `openssl-probe` in our dependency tree. I looked further and saw it was pulled in as a default feature to `hyper-rustls`. I disabled that feature. Shortly after I realized that the entire crate was unused. So I ran `cargo udeps` and realized we had two unused dependencies.
I'll look at adding `cargo udeps` into our CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3712)
=> Remove dependencies reported as unused by cargo udeps

deny.toml
We use Rustls for TLS. We don't want to accidentally pull in
OpenSSL for anything. Both because it would bloat the binaries,
and because we would then potentially be vulnerable to OpenSSL
CVEs. Which is something we don't monitor since we are not actively
using it
At the time of submitting this PR, the CI will fail. Since #3712 needs to be merged first in order to get rid of `openssl-probe`. I use this as a test to see that the `cargo deny` CI job actually works :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3715)
=> Add OpenSSL related crates to deny.toml ban section

Cargo.lock
Our CI detected our version was yanked. So let's upgrade it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3720)
=> Upgrade pin-project from a yanked version

android/translations-converter/src/android/string_value.rs, mullvad-exclude/src/main.rs, talpid-types/src/lib.rs
Clippy rejects `s.push_str(&format!(...))`, due to the extra copy (see [this](https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string)). This PR fixes that.
Note: This lint was added in [Rust 1.62](https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-162).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3721)
=> Stop appending `format!(...)` to existing strings

Cargo.lock, talpid-core/Cargo.toml
Moves from mio 0.7 to 0.8 and gets rid of miow completely
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3725)
=> Upgrade tokio and all tokio-* crates to latest version

mullvad-daemon/src/migrations/v3.rs, mullvad-types/src/relay_constraints.rs, mullvad-types/src/settings/dns.rs, talpid-core/src/winnet.rs, talpid-types/src/net/mod.rs
This means `Default` doesn't have to be manually implemented for (most) enums.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3722)
=> Use derive attribute for default enum variants

CHANGELOG.md, talpid-core/src/split_tunnel/windows/mod.rs
Previously, if one had tried to update the list of apps to split but applying the config failed, that new config would still be reapplied after resuming from sleep. That's unexpected: The list should always be synchronized with the paths that are actively being split.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3719)
=> Don't update the ST paths copy if applying the config fails

android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/AccountExpiryNotification.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AccountCache.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AccountRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionAccountDataSource.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionContainer.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt
Refactor the android app account cache into a repository which makes it possible to inject and easier to test.
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (refactoring)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3718)
=> Refactor android account cache to repository

CHANGELOG.md, talpid-core/src/windows/window.rs
`PowerManagementListener` previously only retained the most recent event. Since `ResumeSuspend` is sometimes sent at the same time as `ResumeAutomatic`, receivers would potentially only see one of the events. This PR fixes this by using a broadcast channel instead of `watch`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3727)
=> Fix app occasionally getting stuck in the offline state

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AccountRepository.kt
Fixes a regression where the welcome view was skipped for new accounts.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3729)
=> Fix welcome view not showing

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt
Skip showing a app icon badge for the tunnel state and instead just keep it for expiration notifications. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3735)
=> Disable badge for tunnel state

CHANGELOG.md, talpid-core/src/routing/windows.rs, talpid-core/src/tunnel/mod.rs
This PR makes the Windows daemon look up the MTU of the default interface and use that as the default in the Wireguard tunnel.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3703)
=> Windows auto set mtu

CHANGELOG.md, mullvad-relay-selector/src/lib.rs
Previously, the IP setting was ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3739)
=> Connect to tcp2udp endpoints over IPv6 (if enabled)

CHANGELOG.md, talpid-core/src/tunnel/wireguard/mod.rs
Previously, WireGuard tunnels would break after the PQ key exchange when `udp2tcp` was in use. This was because `udp2tcp` connected the UDP socket to the source of the first incoming datagram. When updating the WireGuard config, the old endpoint socket is apparently replaced in most implementations. The new client is unable to connect to the local `udp2tcp` server because the "session" is tied to the previous source address.
This PR solves the issue by creating a new `udp2tcp` instance before updating the WireGuard config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3743)
=> Fix PQ secure tunnels not working when connecting over TCP

CHANGELOG.md, mullvad-daemon/src/lib.rs
There exists a small potential leak window when stopping the service and auto-connect is enabled:
```
[2022-07-13 11:37:45.058][talpid_core::firewall][INFO] Resetting firewall policy
[2022-07-13 11:37:45.160][mullvad_daemon][DEBUG] New tunnel state: Disconnected
[2022-07-13 11:37:45.171][talpid_core::firewall][INFO] Applying firewall policy: Blocked. Allowing LAN. Allowing endpoint 45.83.222.100:443/TCP for mullvad-problem-report.exe mullvad-daemon.exe
```
The firewall is supposed to block until the daemon has restarted, but in this particular case, the firewall state would be wiped prior to the blocking filters being added.
This is only relevant when always require VPN is disabled and auto-connect is enabled.
--- …
=> Enter blocking state atomically when service is stopped

Cargo.lock, mullvad-daemon/Cargo.toml, mullvad-jni/Cargo.toml, mullvad-jni/src/talpid_vpn_service.rs, mullvad-relay-selector/Cargo.toml, mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/matcher.rs, talpid-core/Cargo.toml, talpid-types/Cargo.toml
Upgrades `x25519-dalek` to the latest pre-release in order to get it to depend on `rand_core 0.6` instead of the old `0.5` version. We already had the newer rand crates in our dependency tree, so this does not really change much in our overall dependency tree. But this unlocks upgrading `rand` in all other crates. So this PR also upgrades `rand` to version `0.8.5` everywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3755)
=> Upgrade x25519-dalek to latest (pre) version to get newer rand

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt
Fix device list scrolling in split view by changing so that instead of just scrolling the list of device, the whole view except the header and action buttons is scrollable. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3749)
=> Fix device list split view scrolling

android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt
Fixes expiry fetching which was broken due to switching from `StateFlow` to `SharedFlow` in `MullvadDaemon`. Also ensures that the expiration notification isn't show if the account is newly created.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3752)
=> Fix expiry fetch and notification

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrl.kt
Fixes a crash occurring when in-app notifications are used to open URLs. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3762)
=> Fix in-app notification url crash

ios/CHANGELOG.md, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/ConnectContentView.swift, ios/MullvadVPN/ConnectViewController.swift
Git checklist:
1. Camera calculations rely on position of location label, since location marker should be placed above location label and different coordinate spaces are used to express positions of both location label and location marker. Sometimes when the app launches, the UI layout is not calculated immediately, which causes the camera to rely on wrong layout frames. This PR forces layout engine to lay out main view before calculating the position for camera. 
2. Update camera position when multitasking (i.e resizing app window, entering split view mode on iPad)
3. Rename `ConnectMainContentView` to `ConnectContentView`.
--- …
=> Fix camera position handling when multitasking

android/app/src/main/res/layout/advanced_header.xml
Fixes the spacing between elements in advanced settings.
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (regression)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3770)
=> Fix spacing in advanced settings

gui/src/main/index.ts, gui/tasks/electron.js
This PR adds the flag `--disable-reset-navigation` which disables the timer that is activated on blur and when fired resets the navigation to the main view. This flag is only available when running the app in development and is useful when working on the same view for a long time. Before this I had to navigate back to the view I was working on if I spent more than two minutes between each test.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3769)
=> Add flag that prevents navigation from resetting 2 minutes after blur

Cargo.lock, talpid-core/Cargo.toml, talpid-core/src/routing/linux.rs, talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, talpid-core/src/tunnel/wireguard/wireguard_kernel/nl_message.rs, talpid-core/src/tunnel/wireguard/wireguard_kernel/wg_message.rs
Signed-off-by: Emīls Piņķis <emils@mullvad.net>
The older `rtnetlink` crates that were used in `talpid-core` were not compatible with newer [kernels](https://github.com/little-dude/netlink/pull/274), so I've updated them to the latest releases. This should fix #3768.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3775)
=> Update netlink crates to support later kernels

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountInput.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountLogin.kt, android/app/src/main/res/values-da/strings.xml, android/app/src/main/res/values-de/strings.xml, android/app/src/main/res/values-es/strings.xml, android/app/src/main/res/values-fi/strings.xml, android/app/src/main/res/values-fr/strings.xml, android/app/src/main/res/values-it/strings.xml, android/app/src/main/res/values-ja/strings.xml, android/app/src/main/res/values-ko/strings.xml, android/app/src/main/res/values-my/strings.xml, android/app/src/main/res/values-nb/strings.xml, android/app/src/main/res/values-nl/strings.xml, android/app/src/main/res/values-pl/strings.xml, android/app/src/main/res/values-pt/strings.xml, android/app/src/main/res/values-ru/strings.xml, android/app/src/main/res/values-sv/strings.xml, android/app/src/main/res/values-th/strings.xml, android/app/src/main/res/values-tr/strings.xml, android/app/src/main/res/values-zh-rCN/strings.xml, android/app/src/main/res/values-zh-rTW/strings.xml, android/app/src/main/res/values/strings.xml
Fixes a regression issue where the a user wouldn't see the "Logged In" message before the transition to the Connect view.
Git checklist:
~* [ ] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (regression)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3779)
=> Fix missing logged in status

ios/MullvadVPN/NotificationBannerView.swift, ios/MullvadVPN/TermsOfServiceContentView.swift
Git checklist:
This PR resets the line break strategy to default (pre-iOS 14). Modern iOS tends to break lines in such fashion that second line has at least two words. This probably has good intentions but often results in in-app notification banner having a lot of blank space on first line. This is nothing new, we used this fix elsewhere before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3789)
=> Fix line breaks in notification banner

CHANGELOG.md, Cargo.lock, talpid-core/Cargo.toml, talpid-core/src/routing/linux.rs, talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs, talpid-core/src/tunnel/wireguard/wireguard_kernel/nl_message.rs, talpid-core/src/tunnel/wireguard/wireguard_kernel/wg_message.rs
The previous PR (#3775) updating the netlink crates was merged prematurely, as it didn't have update the changelog, and more importantly, the issue with removing the link wasn't resolved for the newer kernels - the underlying issue were the flags that were set on the delete message on our side - but this has been resolved now. This should finally close #3768.
I've tested these changes on both the current Fedora Rawhide and Ubuntu 20.04.4 LTS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3787)
=> Update netlink libraries and fix netlink message flags.

ios/MullvadVPN/CustomTextView.swift, ios/MullvadVPN/SpinnerActivityIndicatorView.swift
Git checklist:
1. Add `custom` size for spinner. It will be used in device management controller where remove buttons have slightly larger size than predefined spinners.
2. Spinner: use `UIScene` notification in place of `UIApplication` notification on iOS 13+.
3. Refactor `CustomTextView` and clean up notification observer on `deinit`. Keep forgetting to remove block based observer (https://oleb.net/blog/2018/01/notificationcenter-removeobserver/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3793)
=> Add custom size for spinner + refactor text view

CHANGELOG.md, dist-assets/linux/mullvad-gui-launcher.sh
Check if in a wayland session and add electron flags to run wayland native as explained here: #3062
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3145)
=> Add electron flags to run wayland native if in a wayland session.

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
This PR fixes an issue with the login spinner animation being slow during the transition to the device management view by switching the spinner to an error icon just before the view transition.
Git checklist:
~* [] Describe the change in **`CHANGELOG.md`** under the `[Unreleased]` header.~ (belongs to feature already in the changelog)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3799)
=> Fix slow login spinner during view transition

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Adds instructions about localization to third party contributors. We have never been able to effectively accept third party contributions to translations. But our translation company 
Also updates the format to be in comments. There is no need for any of this to be part of the visible PR description. Please leave it commented out or remove this before publishing PRs. All of this is just reminders for the author. Not something that is intended as part of the actual PR message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3804)
=> Update Github PR template (tells third party contributors about localizations and translations)

.github/workflows/ios.yml, ios/.swiftformat, ios/README.md
Git checklist:
After careful examination of [SwiftFormat](https://github.com/nicklockwood/SwiftFormat) and [Apple swift-format](https://github.com/apple/swift-format) I think I lean towards the former tool as it seems to be feature rich and well documented.
This PR adds [SwiftFormat](https://github.com/nicklockwood/SwiftFormat) support on Github actions but does not reformat the entire codebase, which I think deserves a separate PR once we're light on unmerged changes.
The latest `SwiftFormat` can be installed via Homebrew:
```brew install swiftformat```
Use the following command to format the source code within the repository:
```
cd ios
swiftformat .
```
To view the complete list of supported …
=> Add swift-format

ios/MullvadVPN/Info.plist
As the title suggests, intents should only be runnable when device is unlocked and Siri is nicely suggesting to unlock the device before performing the requested action, i.e "Stop VPN".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3810)
=> Make intents only available when device is unlocked

Cargo.lock
The update fixes a potential segfault in `chrono` due to its use of `localtime_r`, which may segfault if some other thread calls `std::env::set_var` ([RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159)). When this issue was fixed, the CVE was [unyanked](https://github.com/rustsec/advisory-db/commit/36705ccc1d51930b238e11dd9a279aed55927e3a).
This is also related to [RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071), which is the same thing problem but for `time-rs`. RUSTSEC-2020-0071 is still ignored by `cargo-audit.yml`.
It did not affect the app in practice, as it never sets environment variables.
- - - …
=> Bump chrono to 0.4.20

gui/src/renderer/components/TooManyDevices.tsx
This PR improves the error handling and information in the too many devices view by navigating back to the login view when logging in from the too many devices view.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3786)
=> Improve too many devices view

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/CustomDns.kt
The custom DNS toggle button would switch it's state back to being off after being inflated again, when the advanced settings fragment is inflated for the 2nd time in the lifecycle of the app. I presume this is because the button's state is only set when changes arrive from the daemon, and it isn't initialized to a known good state by default.
I've changed it so that a known good state is opportunistically applied, but this change might be somewhat crude.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3808)
=> Set state of custom DNS toggle button immediately

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AccountDataThrottling.swift, ios/MullvadVPN/CustomNavigationController.swift, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPN/SettingsNavigationController.swift
1. Throttle account data updates from UI with 10s cooldown when account has already expired, otherwise use 60s interval between requests.
2. Update account data as scene becomes active. If settings are on screen, do the regular update, if not then only update if account is close to expiry or already expired, otherwise do nothing. This is done this way to avoid spamming our backend when we don't really do anything with account expiry.
3. Add calls to update account data when navigating to account view and back to root settings. (See updated `SettingsNavigationController` and `SettingsNavigationControllerDelegate`)
4. Add additional method override to be able to tell when `CustomNavigationControler` is about to pop navigation item:
```swift
func willPop(navigationItem: UINavigationItem)
``` …
=> Improve account data updates

.github/workflows/daemon.yml
Makes sure that the CI job failing does not cancel the other CI jobs. Necessary right now because beta fails causing stable and nightly jobs to be cancelled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3832)
=> Always continue on error

ios/MullvadVPN/AppStorePaymentManager/AppStorePaymentManagerError.swift, ios/MullvadVPN/AppStorePaymentManager/SendAppStoreReceiptOperation.swift, ios/MullvadVPN/AppStoreReceipt.swift, ios/MullvadVPN/ConsolidatedApplicationLog.swift, ios/MullvadVPN/DisplayChainedError.swift, ios/MullvadVPN/ProblemReportViewController.swift
- Remove `AppStoreReceipt.Error` and instead return the underlying error. `AppStoreReceiptNotFound` is added to treat a special case when App Store receipt is not found on disk.
- Remove `ConsolidatedAppLog.Error` type and pass `String` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3835)
=> Trim custom errors

CHANGELOG.md, Cargo.lock, docs/relay-selector.md, mullvad-api/src/lib.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/settings.rs, mullvad-daemon/src/version_check.rs, mullvad-relay-selector/src/lib.rs, mullvad-types/Cargo.toml, mullvad-types/src/settings/mod.rs, mullvad-types/src/version.rs
Retrieve a percentage from the version check API response.
Use this percentage to decide if a user should use WG or OpenVpn as
their "automatic" default option.
Currently not implemented for windows or functioning and contains dbg
statements.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3748)
=> Migrate a given percentage of windows users to WG

CHANGELOG.md, mullvad-relay-selector/src/lib.rs
This PR causes bridges farther away than 1500 km to be pruned from selection, while always keeping the five closest bridges to the relay selection. The weights for distant bridges were also lowered somewhat.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3833)
=> Adjust bridge selection

ios/CHANGELOG.md, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AccountViewController.swift, ios/MullvadVPN/HeaderBarView.swift, ios/MullvadVPN/OutOfTimeContentView.swift, ios/MullvadVPN/OutOfTimeViewController.swift, ios/MullvadVPN/REST/RESTCreateApplePaymentResponse+Localization.swift, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPN/StatusActivityView.swift, ios/MullvadVPN/UIColor+Palette.swift
This PR introduces a new out of time view, which is shown when logged into an account with no time left. From this view, it's possible to buy more time via in-app purchase, redeem vouchers (not yet implemented!), and restore previous purchases. 
This change replaces the redirection to account settings, providing a better experience, which is especially important since it's the first view shown after creating a new account in the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3811)
=> Add out of time view

ios/MullvadVPN/LoginContentView.swift, ios/MullvadVPN/LoginViewController.swift
Replace the StatusIconView and SpinnerActivityIndicatorView in LoginViewController with StatusActivityView to handle the functionality of both.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3843)
=> Replace status icon and activity indicator with StatusActivityView

talpid-core/src/tunnel/mod.rs
Some users experienced issues when the new update increased the default MTU size for packets from 1380 to 1420. This is likely due to some program causing packets to exceed the device limit (usually 1500) and then fragmenting the packets. This PR reduces the mullvad interface MTU by a buffer of 60 bytes which means that even if some program causes a packet to be bigger as long as this increase is not bigger than 60 bytes it should not fragment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3846)
=> Add a margin to the max MTU of the tunnel

ios/CHANGELOG.md, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPN/SettingsNavigationController.swift, ios/MullvadVPN/SettingsViewController.swift
1. Use `pushViewController` when initializing `SettingsNavigationController` as or some reason `setViewControllers` ignores `prefersLargeTitles`.
2. Add CHANGELOG entry for [cell animation bug fix](https://github.com/mullvad/mullvadvpn-app/commit/cfe03f2c74e3803ea3819ae5a1e6977bbdfc191e) in location picker.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3848)
=> Fix settings title presentation

CHANGELOG.md, README.md, build.sh, env.sh, gui/scripts/build-proto.sh, gui/tasks/distribution.js, wireguard/build-wireguard-go.sh
This makes it possible to build the app for Linux ARM. It can be done either via cross-compilation or by building it on an ARM host (with the caveat that `grpc-tools` will refuse to generate code for the management interface .proto (https://github.com/mullvad/mullvadvpn-app/pull/2500) in the latter case).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3853)
=> Add support for Linux ARM64

CHANGELOG.md, dist-assets/linux/before-install.sh, dist-assets/linux/before-remove.sh, dist-assets/windows/installer.nsh, gui/src/main/index.ts
This PR changes the behavior of the electron app to not disconnect when it's killed or crashes. The only way to disconnect on quit is when the user presses the quit-button.
This made it possible to remove the `--quit-without-disconnect` flag and to kill the app before the daemon on Linux and to not force kill it on Windows. Unfortunately we still need to keep the code that kills the previous app in `before-install.sh` and the corresponding part in `installer.nsh` to support upgrading from older versions of the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3855)
=> Don't disconnect on GUI crash or when killed

CHANGELOG.md, gui/package-lock.json, gui/package.json
This PR upgrade Electron from 18.0.3 to 19.0.13. Due to an incompatibility with `nan`, which is a dependency of `nseventmonitor`, it wasn't possible to upgrade to Electron 20. I will perform that upgrade when it's possible.
Changelog for Electron 19:
https://github.com/electron/electron/releases/tag/v19.0.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3856)
=> Upgrade Electron from 18.0.3 to 19.0.13

mullvad-daemon/src/version_check.rs
It was previously set to 1.0 for dev builds. Meaning it was impossible to test the behavior, because it would always use WireGuard
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3865)
=> Lower wg_migration_threshold to 0.75 in dev builds

Cargo.lock, mullvad-api/Cargo.toml, mullvad-management-interface/Cargo.toml, mullvad-relay-selector/Cargo.toml, mullvad-types/Cargo.toml, talpid-core/Cargo.toml
Bumping chrono to a newer version to have [this](https://github.com/chronotope/chrono/pull/756). Otherwise, the daemon panics upon first attempt at logging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3863)
=> Update chrono to 0.4.21 to fix Android

gui/src/renderer/components/Login.tsx
This PR fixes a bug where the login input wasn't focused after failing after a second submit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3866)
=> Fix login not focused when submitted after failure

gui/locales/messages.pot, gui/src/renderer/components/ExpiredAccountErrorView.tsx, gui/src/renderer/components/Login.tsx, gui/src/shared/notifications/block-when-disconnected.ts
This PR replaces a the remaining occurrences of the string "Always require VPN". All other occurrances was replaced a while ago but these were forgotten about.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3871)
=> Replace the remaining mentions of Always require VPN

CHANGELOG.md, gui/src/renderer/components/Settings.tsx
This PR enables interface settings when logged out since there are no settings in that view that requires an account, and the language setting needs to be available at all times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3869)
=> Enable interface settings when logged out

CHANGELOG.md, docs/security.md, talpid-core/src/firewall/mod.rs, windows/winfw/src/winfw/rules/baseline/permitlan.cpp
All of `239.0.0.0/8` is not valid on the internet. This PR updates the firewall rules to permit that entire range. Fixes https://github.com/mullvad/mullvadvpn-app/issues/3753.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3858)
=> Allow administratively scoped v4 multicast range when LAN sharing is enabled

version-metadata.sh
Previously, `version-metadata.sh` would replace any line in the toml file matching `^version = "[^\]+"$`. This didn't work when a package version was specified in a separate section. For example, `0.36.1` would be replaced here:
```
[dependencies.windows-sys]
version = "0.36.1"
```
This PR simply updates the script to replace the first occurrence only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3874)
=> Fix incorrect version replacement in version-metadata.sh

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LocationInfo.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt
Ensures that the tunnel info expansion state is remembered across the
pause/resume flow. This is done by replacing the previous state handling
with a view model.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3880)
=> Fix tunnel info expansion state on resume

Cargo.lock, mullvad-cli/Cargo.toml, mullvad-cli/build.rs, mullvad-daemon/Cargo.toml, mullvad-daemon/build.rs, mullvad-daemon/src/exception_logging/win.rs, mullvad-daemon/src/migrations/mod.rs, mullvad-daemon/src/system_service.rs, mullvad-problem-report/Cargo.toml, mullvad-problem-report/build.rs, mullvad-setup/Cargo.toml, mullvad-setup/src/daemon_paths.rs, talpid-openvpn-plugin/Cargo.toml, talpid-openvpn-plugin/build.rs, talpid-platform-metadata/Cargo.toml, talpid-platform-metadata/src/windows.rs
Continuation of https://github.com/mullvad/mullvadvpn-app/pull/3862.
There are some missing macros in `windows-sys`. `winapi` is still used for some of these.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3873)
=> Replace winapi with windows-sys in the remaining crates

android/gradle.properties, build-apk.sh
I've changed two small things in the `build-apk.sh` script for developer (_my own_) quality of life. Firstly, the development builds won't strip debug symbols so that stack traces are actually legible. Secondly, I've changed the buildscript to use `CARGO_TARGET_DIR` to find the cargo target directory instead of assuming it will always be relative to the build script.
If you feel strongly about any of these changes, I'm open to not making them - but let's have a discussion about it then :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3864)
=> Improve android buildscripts

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ProblemReportFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragments/DeviceListFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/NavigateCell.kt
Fixes a crash during view transitions reported by some devices in the Google Play Console. The crash is caused by an attempted transition after the _instance state_ has been saved. However, as the app doesn't rely on the _instance state_ for state handling (we use view models instead), we can allow a _instance state_ loss.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3883)
=> Fix android view transition crash

CHANGELOG.md, mullvad-cli/src/format.rs
Previously, `mullvad status -v` did not include the port when obfuscation was enabled:
```
mullvad status -v
Connected to se-got-wg-101 (185.213.154.70/TCP) in Gothenburg, Sweden
```
The PR fixes this to include the port:
```
mullvad status -v
Connected to se-got-wg-101 (185.213.154.70:80/TCP) in Gothenburg, Sweden
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3887)
=> Include port in 'mullvad status -v' output when obfuscation is enabled

gui/src/renderer/components/Settings.tsx
This PR makes the large title show in settings when logged in. Previously it the small version was always displayed to make the content fit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3885)
=> Show large title in settings when logged in

android/gradle/wrapper/gradle-wrapper.properties
This is not fully supported by Android Studio due to a bug in Gradle,
however as this is an important security mechanism it should be set.
Upcoming versions of Android Studio seem to properly support the
checksum mechanism, as seen here:
https://developer.android.com/studio/releases/fixed-bugs/studio/2022.1.1#android-studio-electric-eel-canary-3-2022.1.1.3
If Android Studio complains when syncing, click the text saying:
'Use "\<checksum\>" as checksum for \<url\> and sync project'
See more:
https://github.com/gradle/gradle/issues/9361
https://issuetracker.google.com/issues/232933744
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3892)
=> Add gradle wrapper checksum

android/app/src/main/AndroidManifest.xml
Explicitly set export configuration for activity and services as it's required when targeting Android 12 and can be generally considered a good security practice.
This commit also adds brief documentation in the manifest to motivate
the export configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3890)
=> Explicitly export activity and services

gui/src/renderer/components/Account.tsx
This PR fixes the logout dialog switching to the text that should apply in the `confirm` stage when setting `logoutDialogStage` to `hidden`. It should show the text corresponding to the previous stage while closing. To solve this I separated the visibility value and the stage value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3893)
=> Fix logout dialog flickering

CHANGELOG.md, windows/driverlogic/src/driverlogic.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3889)
=> Don't fail ST driver installation if the device tree contains nameless callout driver devices

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountInput.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt
This PR aims to change/fix the behavior of the login button when a login error occurs. Rather than disabling the login button, it will now be possible to re-attempt the login. This behavior is aligned with the desktop behavior.
This PR also includes a minor flickering fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3898)
=> Fix disabled login button on login failure

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/main/res/layout/account.xml
This PR aims to trigger a device refresh when opening the account view to ensure the device hasn't been revoked and has up-to-date data. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3900)
=> Refresh device in account view

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/HeaderBar.kt
Disabling the settings button during login will prevent some strange UI behavior. It also doesn't make much sense to open it while the login is loading.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3901)
=> Disable settings button while logging in

gui/src/main/default-settings.ts, gui/src/main/settings.ts
This PR moves the default settings in the main process to its own file to make it reusable in separate main implementation for e2e tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3905)
=> Move default settings to its own file

Cargo.lock, talpid-tunnel-config-client/Cargo.toml, talpid-tunnel-config-client/src/kem.rs, talpid-tunnel-config-client/src/lib.rs
WIP. Upgrading to the (not yet released) version `2.0.0` of `classic-mceliece-rust`. This is to verify that the proposed library API is sane before publishing. See https://github.com/Colfenor/classic-mceliece-rust/pull/28
I hade to upgrade `chacha20poly1305` also. Since the version we had was pinning `zeroize` to an older version than what `classic-mceliece-rust` required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3877)
=> Upgrade the classic-mceliece-rust library to 2.0.0

Cargo.lock
Version `0.2.1` of `cpufeatures` got yanked, so it's upgraded to `0.2.5` now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3908)
=> Update cpufeatures to 0.2.5

CHANGELOG.md, mullvad-daemon/src/device/mod.rs
Previously, failing to reconnect when in the error state would not cause the daemon to check if the device was valid after a few failed attempts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3907)
=> Reset the device check counter in the error state

gui/src/renderer/app.tsx, gui/src/renderer/components/Account.tsx, gui/src/renderer/components/Modal.tsx, gui/src/renderer/components/TransitionContainer.tsx, gui/src/renderer/containers/AccountPage.tsx, gui/src/renderer/lib/will-exit.tsx, gui/src/renderer/redux/store.ts
This PR adds a transition when logging out. This initially resulted in two issue. The first issue was the the account number and expiry in the account view was cleared in the beginning of the transition. The other one was a visual glitch happening when a modal was unmounted during the view transition.
To solve this I add a context for stopping updates during transitions. This can now prevent `useSelector` from returning updated values while paused.
The visual glitch was solved by using the paused-context to prevent unmounting of modals while paused.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3913)
=> Prevent redux updates during transition

README.md, windows/driverlogic/driverlogic.sln, windows/driverlogic/driverlogic.vcxproj, windows/libshared/libshared.sln, windows/libshared/src/libshared/libshared.vcxproj, windows/nsis-plugins/nsis-plugins.sln, windows/nsis-plugins/src/cleanup/cleanup.vcxproj, windows/nsis-plugins/src/log/log.vcxproj, windows/nsis-plugins/src/pathedit/pathedit.vcxproj, windows/nsis-plugins/src/registry/registry.vcxproj, windows/nsis-plugins/src/string/string.vcxproj, windows/nsis-plugins/src/tray/tray.vcxproj, windows/winfw/extras.sln, windows/winfw/src/extras/cli/cli.vcxproj, windows/winfw/src/winfw/winfw.vcxproj, windows/winfw/src/winfw/winfw.vcxproj.filters, windows/winfw/winfw.sln, windows/winnet/extras.sln, windows/winnet/src/extras/loader/loader.vcxproj, windows/winnet/src/extras/tests/tests.vcxproj, windows/winnet/src/winnet/winnet.vcxproj, windows/winnet/winnet.sln
This PR bumps the build tools from v142 to v143, as the v142 toolset is not available for Visual Studio 2022. It also bumps the Visual Studio version to 2022.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3914)
=> Update Visual Studio build tools

talpid-core/src/process/openvpn.rs, talpid-core/src/tunnel/openvpn/mod.rs
It's not very useful to keep this option since we're only ever going to use Wintun.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3919)
=> Remove TAP driver support for openvpn

gui/src/renderer/components/Modal.tsx
Fix bug where `ModalContent` becomes scrollable during view transitions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3918)
=> Add overflow hidden to ModalContent to prevent scrollbar from appearing during transition

gui/src/renderer/app.tsx
This PR fixes a bug where two different transitions are displayed when navigating from the device revoked view to the login view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3928)
=> Fix transition when navigating from device revoked to login

CHANGELOG.md, mullvad-types/src/relay_constraints.rs, mullvad-types/src/settings/mod.rs
Since `any` cannot be selected in the GUI, and since `se` is the default location for the exit, this is a better default than `any`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3931)
=> Change the default multihop entry location to Sweden

gui/src/renderer/components/NotificationArea.tsx, gui/src/renderer/components/NotificationBanner.tsx, gui/src/renderer/index.html
This PR fixes the issues of notifications being cropped if it's shown when the app starts and consists of a few lines of text. The cause was that the font hadn't loaded yet when the `NotificaitonBanner` component measured the size of the notificaiton to figure out how big it should be.
To fix this I added the fonts to preloads. While working on this I also refactored `NotificationBanner` to make it less complicated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3930)
=> Fix cropped notification

Cargo.lock, mullvad-api/Cargo.toml, mullvad-jni/Cargo.toml, mullvad-types/Cargo.toml, talpid-core/Cargo.toml, talpid-tunnel-config-client/Cargo.toml, talpid-types/Cargo.toml
This makes the derive macro for `FromJava` work on simple enums. See https://github.com/mullvad/jnix/pull/49.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3936)
=> Update jnix to 0.5

version-metadata.sh
The [previous change](https://github.com/mullvad/mullvadvpn-app/pull/3874) to this script used a GNU extension to replace the versions. So injecting the version failed on macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3910)
=> Fix version injection script to not use GNU extensions

mullvad-daemon/src/cli.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/main.rs, mullvad-daemon/src/system_service.rs
Previously, the daemon did keep blocking rules after exit if auto-connect was enabled. This means that there's a small leak window on shutdown if auto-connect (and always require VPN) is disabled. This PR changes the behavior of the daemon to always block on exit if the system is shutting down instead.
Related: #3940.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3942)
=> MUL22-02 for Windows - maintain blocking firewall rules during system shutdown.

CHANGELOG.md, Cargo.lock, mullvad-daemon/Cargo.toml, mullvad-daemon/src/lib.rs, mullvad-daemon/src/main.rs, mullvad-daemon/src/shutdown.rs, talpid-dbus/src/lib.rs, talpid-dbus/src/systemd.rs
Due to the ordering of shutdown events, the mullvad daemon will most often be shut down while network interfaces are still configured and working, which allows for a time window where arbitrary processes can send network traffic outside of the tunnel, even if the user never intended for this. 
To fix this, the daemon will not clear it's firewall rules during shutdown if the user didn't explicitly disconnect before the daemon is being stopped, unless `systemd` is reachable over D-Bus and it's reporting that the system is not shutting down.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3940)
=> MUL22-02 for Linux - maintain blocking firewall rules during system shutdown.

ios/MullvadVPN/ConnectViewController.swift
It looks like I made a mistake assuming that map labels aren't entirely disabled when using custom overlay replacing map content. This PR adds custom overlays above labels to hide them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3949)
=> Add custom overlays above labels

mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs, mullvad-jni/src/daemon_interface.rs, mullvad-management-interface/proto/management_interface.proto
The shutdown GRPC isn't used by any client that we know of. The shutdown command itself is only useful on Android - thus the shutdown method is removed from the GRPC interface.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3944)
=> Remove shutdown GRPC.

CHANGELOG.md
Just bumps the binaries submodule to get the new split tunneling driver for Windows that fixes *MUL22-01*. See https://github.com/mullvad/mullvadvpn-app-binaries/pull/98
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3951)
=> Bump binaries subrepo to fix MUL22-01 (win-split-tunneling upgrade)

CHANGELOG.md, dist-assets/pkg-scripts/postinstall, dist-assets/uninstall_macos.sh
`/usr/local/share/fish/vendor_completions.d/` does not exist in `$fish_complete_path` on Apple Silicon Macs, as ARM binaries reside in `/opt/homebrew`. This PR creates a link to the completions in `$(brew --prefix)/share/fish/vendor_completions.d/` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3954)
=> Fix fish completions path on macOS

prepare-release.sh
This PR simply fixes `prepare-release.sh` to look for `[android/$PRODUCT_VERSION]` instead of `[$PRODUCT_VERSION]` in the changelog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3960)
=> Detect missing changelog entries for Android correctly in prepare release script

CHANGELOG.md, gui/locales/messages.pot, gui/src/main/daemon-rpc.ts, gui/src/main/relay-list.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/Filter.tsx, gui/src/renderer/components/OpenVpnSettings.tsx, gui/src/renderer/components/SelectLanguage.tsx, gui/src/renderer/components/VpnSettings.tsx, gui/src/renderer/components/WireguardSettings.tsx, gui/src/renderer/components/cell/Input.tsx, gui/src/renderer/components/cell/Selector.tsx, gui/src/renderer/redux/settings/actions.ts, gui/src/renderer/redux/settings/reducers.ts, gui/src/shared/daemon-rpc-types.ts, gui/src/shared/ipc-schema.ts, gui/src/shared/string-helpers.ts, gui/test/e2e/setup/main.ts
This PR adds the ability to add custom options to the `Selector` component and uses it for the WireGuard port selector.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3950)
=> Add custom port option for WireGuard

docs/security.md
Due to recent changes to the daemon to prevent early and late boot leaks, the security docs need to be updated to reflect the new behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3966)
=> Update security.md with regards to MUL22-02 (and MUL22-04)

gui/src/renderer/app.tsx
This PR corrects the name of the alternative for Polish in the language selector. It was reported by a user to the form provided by Alcanost.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3975)
=> Correct translation of the polish language alternative

mullvad-daemon/src/geoip.rs, mullvad-daemon/src/lib.rs
Stop sending IPv6 geolocation requests if IPv6 is disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3983)
=> Stop IPv6 geolocation requests when in-tunnel IPv6 is disabled

CHANGELOG.md, gui/src/main/index.ts, gui/src/main/linux-desktop-entry.ts
This PR fixes the issue where the app crashes while starting when trying to set the window icon to an SVG. This was the case with e.g. the Papirus icon pack. It's been solved by not using SVGs for the window icon. Fixes https://github.com/mullvad/mullvadvpn-app/issues/3981,
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3987)
=> Fix app crashing when trying to set svg to window icon

BuildInstructions.md, README.md, Release.md, android/BuildInstructions.md, android/README.md
This PR moves the build and release instructions out of `README.md` and into separate documents, and also separates the build instructions for Android from the desktop instructions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3957)
=> Move build and release instructions to separate documents

Cargo.lock, talpid-tunnel-config-client/Cargo.toml, talpid-tunnel-config-client/examples/psk-exchange.rs, talpid-tunnel-config-client/examples/tuncfg-server.rs, talpid-tunnel-config-client/proto/tunnel_config.proto, talpid-tunnel-config-client/src/classic_mceliece.rs, talpid-tunnel-config-client/src/lib.rs, talpid-types/Cargo.toml, talpid-types/src/net/wireguard.rs
Work in progress! Coming up with the new `PostQuantumSecure` proto definition for the next iteration of the post quantum secure tunnels.
The changes/improvements from the last/current iteration include:
* Change the used CME variant to `Classic-McEliece-460896f`. This has significantly smaller keys that take significantly less time to generate. Feedback from the people behind the CME algorithm tell us this is safe enough.
* Make the protocol allow multiple KEMs in the same key exchange request. This allows future apps to mix two types of PQ secure KEMs in case one of them proves to be weak over time.
The variant with the “f” at the end uses a semi-systematic matrix as part of the key generation process. Empirical benchmarking has shown that the variant with suffix "f" is slightly faster …
=> Update post quantum experiment V0 -> V1

gui/locales/messages.pot, gui/src/renderer/components/OpenVpnSettings.tsx, gui/src/renderer/components/WireguardSettings.tsx, gui/src/renderer/components/cell/Input.tsx, gui/src/renderer/components/cell/Selector.tsx
This PR fixes the remaining issues with the custom WireGuard port option. The improvements include:
- Footer has been removed since same information is shown in info-dialog
- Input is now emptied when selecting other item after writing invalid port
- Focus now remains in input if custom row is pressed when already focused.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3993)
=> Fix remaining details around custom WireGuard port

CHANGELOG.md, mullvad-cli/src/format.rs, mullvad-daemon/src/tunnel.rs
Previously, when connecting to a custom relay, the daemon would include details for the last non-custom relay when returning the location in tunnel state transitions and when responding to `GetCurrentLocation`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3999)
=> Reset known location when connecting to a custom relay

gui/test/e2e/mocked/settings.spec.ts
This PR tries to solve the issue with a flaky test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4007)
=> Add a one-second margin to flaky test

BuildInstructions.md, gui/package-lock.json, gui/package.json, gui/scripts/build-proto.sh
This PR upgrades `grpc-tools` to `1.11.3` which enables proto build on ARM64 macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4002)
=> Update grpc-tools with m1 support

CHANGELOG.md, mullvad-daemon/src/main.rs
Since some configurations mount `/var/` later in the boot process, logging will fail. To work around this, the behavior is changed so that if file logging doesn't work, it can rely solely on `stdout` logging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4008)
=> Stop logging to a file in early boot blocking service

android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/VpnServiceModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt
This PR adds the Android 13 notification permission and prevents the foreground notification from being dismissed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3970)
=> Add notification permision for android 13

gui/src/renderer/components/Modal.tsx, gui/src/renderer/components/RedeemVoucher.tsx
Since React 18 runs the state setter callback asynchronously it fires after the ref has been updated which leads to an incorrect state. I fixed it by removing the ref and including both values in a state instead to force them to update together.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4024)
=> Fix modals not closing

build-windows-modules.sh
Makes `build-windows-modules.sh` also clear output for `windows-libraries`, `libshared`, and `libwfp`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4019)
=> Clean libraries in build-windows-modules.sh

CHANGELOG.md, mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/matcher.rs, mullvad-types/src/relay_constraints.rs
If none of the relays are "included in the country", given all other constraints, then the relay selector will now select one of them anyway. Previously, the relay selector would find no matching relay in this case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4029)
=> Select a relay even if `include_in_country == false` for all matching relays

mullvad-api/Cargo.toml
Currently, `mullvad-api` doesn't build due to it's `hyper` dependency not having all the features it needs. I've added both of the features now. This didn't affect us since `tonic` would use the `full` feature of `hyper`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4039)
=> Fix hyper features

.github/workflows/android-xml-tidy.yml
This PR updates action/checkout to v3
It removes the warnings about Github Actions will stop supporting Node 12, see the output of a previous run under the Annotations section: https://github.com/mullvad/mullvadvpn-app/actions/runs/3243420568
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4045)
=> Update android-xml-tidy workflow

gui/package-lock.json, gui/package.json, gui/tasks/distribution.js
This PR switches the deb version to be generated using `mullvad-version`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4051)
=> Use mullvad-version for deb version

build-apk.sh, build.sh
This PR aims to improve the developer UX when building the desktop and Android apps by printing some feedback. Both rely on the `mullvad-version` tool that first needs to be built, which might take some time on a fresh machine as it needs to first fetch the cargo index.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4067)
=> Improve build script version computation feedback

docs/security.md
Add a small section in the security doc to acknowledge boot-up leaks on macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4061)
=> Document bootup leaks

gui/src/renderer/lib/history.tsx
This PR removes the unused code `withHistory`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4073)
=> Remove withHistory

mullvad-cli/src/cmds/block_when_disconnected.rs
This PR changes the name of the "block when disconnected"/"always require VPN" setting to "Lockdown mode" in the CLI. It was previously changed in the UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4074)
=> Change name from always require VPN to Lockdown mode in CLI

dist-assets/linux/mullvad-gui-launcher.sh
This PR adds Hyprland to the list of Wayland compatible composers since it was reported in https://github.com/mullvad/mullvadvpn-app/issues/3062 that it works fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4078)
=> Add Hyprland as wayland compatible

Dockerfile
Apparently `docker` does not accept LABELs before `FROM`, but `podman` does :shrug:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4084)
=> Move dockerfile LABEL statements to after FROM to work with docker

ios/MullvadREST/RESTAPIProxy.swift, ios/MullvadREST/RESTAuthenticationProxy.swift
1. Declare all properties of `ProblemReportRequest` as public.
2. Replace `fileprivate` with `private` ACL where it makes no difference.
3. Mark `AccessTokenData` internal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4079)
=> REST: clean up access levels

ios/Operations/AsyncBlockOperation.swift, ios/Operations/AsyncOperation.swift, ios/Operations/AsyncOperationQueue.swift, ios/Operations/BackgroundObserver.swift, ios/Operations/GroupOperation.swift, ios/Operations/InputInjectionBuilder.swift, ios/Operations/InputOperation.swift, ios/Operations/OperationCompletion.swift, ios/Operations/OperationCondition.swift, ios/Operations/OperationObserver.swift, ios/Operations/OutputOperation.swift, ios/Operations/ResultBlockOperation.swift, ios/Operations/ResultOperation+Output.swift, ios/Operations/ResultOperation.swift, ios/Operations/TransformOperation.swift
1. Remove `public extension` in favor of explicitly marking ACL for members.
2. Update source header to reflect the location of source files.
3. Add missing copyright in one of source headers.
4. Remove `Operation.operationName` as it's unused.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4080)
=> Cleanup operations interface

Dockerfile
Getting rid of populating `/root/.cargo/config.toml` to make it build for ARM64. Instead set the linker manually and set a variable that makes `pkg-config` work cross-platform automatically. Then we don't need to specify the paths to `dbus-1`, pkg-config will find it for us.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4091)
=> Make desktop build image find dbus with pkg-config

CHANGELOG.md, mullvad-daemon/src/main.rs
During early boot, the daemon will attempt to create the log directory and set the correct permissions for it - and if it fails it won't continue. In the early boot case, this is now changed so that the early boot firewall rules are still being applied.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4099)
=> Remove expectation of `/var/log/` being writeable during early boot

ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SceneDelegate.swift
This PR moves background task and app-wide routine handling back into `AppDelegate`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4098)
=> Move app wide routine handling into AppDelegate

ios/MullvadREST/AddressCache.swift, ios/MullvadREST/Info.plist, ios/MullvadVPN.xcodeproj/project.pbxproj
1. Add `isReadOnly` flag to `AddressCache` to be able to create instances of `AddressCache` that only read the on-disk cache and never persist it. This will be used in Packet tunnel process since the main bundle is responsible for keeping ip-address-cache up to date.
2. Reload address cache when selecting next endpoint in read-only mode.
3. Use file coordinator API for I/O coordination.
4. Temporarily include `ApplicationConfiguration` into `MullvadREST`. This is needed for `master` to be compilable. `AddressCache.shared` will be removed in the coming PR.
5. Breakdown `AddressCache.init()` onto more functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4096)
=> Add read-only mode for address cache

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/ConnectInteractor.swift, ios/MullvadVPN/ConnectViewController.swift, ios/MullvadVPN/CustomOverlayRenderer.swift, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift
1. Add `ConnectInteractor` class that implements the business logic of `ConnectViewController` and conceals interaction with `TunnelManager`.
2. Add `TunnelBlockObserver` implementation to be able to skip delegate methods that are of no interest to the consumer.
3. Move `CustomOverlayRenderer` into separate file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4104)
=> Add connect interactor

ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/IntentHandlers.swift
This PR removes the use of `TunnelManager.shared`  and instead provides a way to pass an instance on `TunnelManager` during initialization. For now we pass `.shared` to make master compilable, but the follow up PR will fix that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4105)
=> Intents: accept tunnel manager instance

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/ui/fragments/SplitTunnelingFragmentTest.kt, ci/run-android-instrumented-tests.sh
This PR aims to make the instrumentation more robust as it avoids any potential signature mismatch (which is acceptable in a ci environment). It also makes sure that no app data/cache is left from previous runs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4110)
=> Ensure android app is reinstalled in gh actions

ios/MullvadVPN/TransportMonitor/PacketTunnelTransport.swift, ios/MullvadVPN/TransportMonitor/TransportMonitor.swift
This PR makes `PacketTunnelTransport` and `TransportMonitor` accept `TunnelManager` input. This should eventually enable us to get rid of `.shared` instance of `TunnelManager` and pass an individual instance during initialization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4108)
=> Pass tunnel manager into transport monitor

ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SimulatorTunnelProviderHost.swift
Pass `RelayCacheTracker` when initializing `SimulatorTunnelProviderHost`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4111)
=> Tunnel sim: pass relay cache tracker during initialization

.github/workflows/clippy.yml
Seems like when `ci/check-clippy.sh` was removed this watch path was not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4114)
=> Remove unused GH path

.github/workflows/ios.yml, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/TunnelManager/TunnelManager.swift
- Run all tests but ignore screenshots UI tests bundle. This has a nice side-effect of building the entire app before running tests, because screenshots target is dependent on `MullvadVPN`.
- Fix compiler error when running on older Xcode.
- Fix letter case in `ObjCBridgingHeader.h` which was referenced as `ObjcBridgingHeader.h` in Xcode project.
- Pipe `xcodebuild` through `xcbeautify` to produce a better build log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4118)
=> Cleanup GH actions (iOS)

.github/workflows/android-app.yml
This PR aims to build if master is updated to ensure up-to-date caches are available for other builds. The main benefit is that PR builds will be quicker since it doesn't have to build wireguard-go and the daemon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4119)
=> Trigger android gh build on master updates

gui/locales/messages.pot, gui/src/main/index.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/ChevronButton.tsx, gui/src/renderer/components/CustomDnsSettings.tsx, gui/src/renderer/components/ExpiredAccountAddTime.tsx, gui/src/renderer/components/NavigationBar.tsx, gui/src/renderer/components/SplitTunnelingSettings.tsx, gui/src/renderer/components/VpnSettings.tsx, gui/src/renderer/components/WireguardSettings.tsx, gui/src/renderer/components/cell/Section.tsx, gui/src/renderer/components/cell/Selector.tsx, gui/src/renderer/lib/history.tsx, gui/src/renderer/redux/userinterface/actions.ts, gui/src/renderer/redux/userinterface/reducers.ts, gui/src/shared/ipc-schema.ts, gui/src/shared/ipc-types.ts
This PR makes the DNS content blockers section expandable/collapsible. To accomplish this I also:
* Added the expanded/collapsed state to the location state to restore it after `POP` navigation
* Moved the scroll position history to the location state as well
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4128)
=> Make DNS content blockers collapsible

ios/CHANGELOG.md, ios/MullvadREST/Duration.swift, ios/MullvadREST/ExponentialBackoff.swift, ios/MullvadREST/RESTAPIProxy.swift, ios/MullvadREST/RESTNetworkOperation.swift, ios/MullvadREST/RESTRetryStrategy.swift, ios/MullvadREST/ServerRelaysResponse.swift, ios/MullvadREST/URLSessionTransport.swift, ios/MullvadRESTTests/DurationTests.swift, ios/MullvadRESTTests/ExponentialBackoffTests.swift, ios/MullvadTypes/FixedWidthInteger+Arithmetics.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme, ios/MullvadVPN/TransportMonitor/TransportMonitor.swift, ios/PacketTunnel/TunnelMonitor/TunnelMonitor.swift
1. Add exponential backoff. This is a new implementation that aligns with what we have in Rust: https://github.com/mullvad/mullvadvpn-app/blob/master/talpid-core/src/future_retry.rs#L53
2. Add `REST.Duration` type to better express a duration of time than `DispatchTimeInterval` or similar. Unfortunately `Swift.Duration` is only available starting with iOS 16+.
3. Move saturating arithmetics for `FixedWidthInteger` to `MullvadTypes`.
4. Add Tests
5. Remove unused `Network` import in `RESTAPIProxy`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4126)
=> Add exponential backoff

gui/src/main/index.ts, gui/src/main/logging.ts, gui/src/main/user-interface.ts, gui/src/renderer/components/AppRouter.tsx, gui/src/renderer/components/Debug.tsx, gui/src/renderer/components/Settings.tsx, gui/src/renderer/lib/routes.ts
This PR adds a few features to make development easier:
- When forwarding the renderer log to the main console it now uses the webcontents console event listener instead of the ipc input. This results in regular console.log, console.error and thrown errors to show up. It also prefixes all renderer messages with "[Renderer]" in either blue or red depending on log level. This is only applicable if the app is run with `--forward-renderer-log`.
- A new view which will be used to trigger varius things while testing the app. The currently available actions are to throw errors in multiple different situations. This view is only visible when running with `npm run develop`.
- - - …
=> Improve developer tools

CHANGELOG.md, mullvad-relay-selector/src/matcher.rs
Removing per-relay endpoints caused `AnyTunnelMatcher` to sometimes use the wrong tunnel protocol. This was only noticeable after a couple of attempts since "preferred" constraints are used at first.
This PR fixes this and simplifies the relay filtering.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4130)
=> Fix "any tunnel type" relay matcher

ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift
This PR moves protocol conformance declaration to the class declaration itself and removes excessive use of extensions in `AppDelegate` and `SceneDelegate`. 
As I mentioned earlier, I think many engineers abuse extensions for the sake of code organization. However the lack of stored properties in extensions introduces unnecessary fragmentation where extension is not complete without variables stored inside of class, especially when extension is the only consumer of those variables.
Perhaps subjective, but I think that keeping implementation within the class definition is probably cleaner and `MARK` comments can be used to separate sections of class. It's also easy to glance at what protocols the class implements by looking at the class declaration.
- - - …
=> Trim down on extension galore

mullvad-daemon/src/tunnel.rs, mullvad-types/src/custom_tunnel.rs, talpid-openvpn/src/lib.rs, talpid-types/src/net/openvpn.rs
In the latest changes of splitting up `talpid-core`, the firewall mark was no longer being passed to the OpenVPN tunnel when it's being set up, which results in the tunnel not working on Linux. These changes _fix_ that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4135)
=> Use fwmark for routing in openvpn

CHANGELOG.md, dist-assets/windows/installer.nsh, windows/driverlogic/src/driverlogic.cpp
This PR updates the installer on Windows to ignore errors that occur while attempting to clean up old Wintun interfaces in `RemoveAbandonedWintunAdapter`. It also makes `driverlogic` skip adapters that appear to have no valid GUID.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4136)
=> Ignore misconfigured network adapters in the installer

CHANGELOG.md, dist-assets/linux/after-remove.sh, gui/tasks/distribution.js
RPM doesn't seem to remove our app's directories - they are left empty. This can be fixed by passing `--directories=/opt/Mullvad VPN` to `fpm` when building the package.
As a bonus, some obtuse logging is removed from the install scripts- these would normally pollute standard output during installation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4138)
=> Ensure RPM cleans up app's direcotires when removed.

CHANGELOG.md, Cargo.lock, talpid-core/src/tunnel_state_machine/connecting_state.rs, tunnel-obfuscation/Cargo.toml, tunnel-obfuscation/src/udp2tcp.rs
This PR ensures that connecting times out when the connectivity monitor times out, and also that the user can immediately cancel it by disconnecting. See https://github.com/mullvad/udp-over-tcp/pull/32.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4147)
=> Add connect timeout for udp2tcp

dist-assets/windows/installer.nsh
This PR very slightly improves `installer.nsh` by making sure that (1) all temporary files have unique paths and cannot conflict in weird ways, and (2) they're extracted to a temporary dir (`$PLUGINDIR`) that's cleaned up for us, so there's no need to list them all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4148)
=> Extract files to a unique temp dir

CHANGELOG.md, dist-assets/windows/installer.nsh
The script previously could not distinguish between upgrades and normal silent uninstalls. This change is useful for removing the app in scripts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4146)
=> Allow settings removal during silent uninstall on Windows

Cargo.lock, mullvad-paths/Cargo.toml, mullvad-paths/src/lib.rs, mullvad-paths/src/settings.rs, mullvad-paths/src/windows.rs, mullvad-setup/Cargo.toml, mullvad-setup/src/main.rs, talpid-openvpn/Cargo.toml, talpid-wireguard/Cargo.toml
Previously, the path was only correct if called from a system service. I've moved the code for impersonating `SYSTEM` from `mullvad_setup` to `mullvad_paths`, so that it always returns the correct result.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4150)
=> Return the correct settings path on Windows in `mullvad_paths`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/SdkUtils.kt
after upgrading build target sdk version from 30 to 33 app stuck on first page on android 12 devices(tested of official builds like https://releases.mullvad.net/builds/2022.2-beta2-dev-169121/), this tiny pr fix this issue
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4165)
=> Fix app stuck problem after upgrading target sdk to 33

gui/src/main/ipc-event-channel.ts, gui/src/main/user-interface.ts
This PR fixes a race condition which caused the `IpcMainEventChannel` to not have a `webContents` after toggling "Unpinned window". The issue was that the `webContents` `destroyed` event was received after the new `webContents` had been set up and therefore removing it from `IpcMainEventChannel`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4167)
=> Fix race condition when updating IPC target when recreating window

.github/workflows/cargo-audit.yml
This vulnerability in `atty` (https://rustsec.org/advisories/RUSTSEC-2021-0145) only affects custom global allocators on Windows, so we can ignore it for now.
`atty` is a dependency due to `clap` and `env_logger`. Stop ignoring the issue once they've moved away from using it:
https://github.com/clap-rs/clap/pull/4249
https://github.com/rust-cli/env_logger/pull/246
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4164)
=> Ignore RUSTSEC-2021-0145

Cargo.lock, talpid-wireguard/src/lib.rs, tunnel-obfuscation/Cargo.toml, tunnel-obfuscation/src/lib.rs, tunnel-obfuscation/src/udp2tcp.rs
Changes:
* Update `udp-over-tcp`. Lets us obtain the TCP socket file descriptor.
* Protect the remote TCP socket from going inside the tunnel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4168)
=> Exclude outbound obfuscation socket from the tunnel on Android

gui/src/renderer/app.tsx, gui/src/renderer/components/Connect.tsx, gui/src/renderer/components/ExpiredAccountAddTime.tsx, gui/src/renderer/components/HeaderBar.tsx, gui/src/renderer/components/KeyboardNavigation.tsx, gui/src/renderer/components/Settings.tsx, gui/src/renderer/components/TooManyDevices.tsx, gui/src/renderer/components/TransitionContainer.tsx, gui/src/renderer/components/select-location/SelectLocation.tsx, gui/src/renderer/components/select-location/select-location-hooks.ts, gui/src/renderer/lib/history.tsx, gui/src/shared/ipc-types.ts, gui/test/unit/history.spec.ts
This PR fixes the UI glitch that happened when pressing escape multiple time quickly. This was accomplished by:
* Preventing `onTransitionEnd` in `TransitionContainer` from firing twice for transitions where both current and next view has a CSS transition.
* Moving the transition information into the location state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4174)
=> Fix animation glitch when pressing escape multiple times

gui/src/renderer/components/SearchBar.tsx, gui/src/renderer/components/select-location/RelayListContext.tsx, gui/src/renderer/components/select-location/ScrollPositionContext.tsx
This PR fixes the scroll glitch when automatically focusing the search bar in the select location view during the view transition.
I've also moved the `scrollViewRef.current?.scrollIntoView` call to `scrollPositionContext` to keep all scroll related logic in that context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4175)
=> Fix select location transition glitch

gui/src/main/window-controller.ts
This PR hopefully improves the scaling issues on Windows when or after a DPI/scale change. The specific case I was able to reproduce was that the window became taller for each time it was opened when it was unpinned and after changing the Windows scale factor. Hopefully this fixes more issues.
My guess is that `setPosition` sets the bounds but somehow has incorrect values for height and width after a scale/DPI change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4177)
=> Fix some scaling issues on Windows

windows/nsis-plugins/nsis-plugins.sln
Previously, there was no guarantee that `libcommon.lib` had been built, so building the NSIS plugins would occasionally fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4179)
=> Make string plugin dependent on libcommon

mullvad-cli/src/format.rs, mullvad-daemon/src/lib.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/states.rs, mullvad-types/src/auth_failed.rs
This PR refactors the management interface to return structured errors instead of strings for `AuthFailed`. Failing to connect to a WireGuard relay when the account is out of time will now enter the error state due to `AuthFailed::EXPIRED_ACCOUNT`.
This PR does not touch `ErrorStateCause` in `talpid-types`, as accounts do not exist in that layer. Currently, the correct fix entails duplicating all tunnel states in `mullvad-types`. This would be somewhat pointless to do before the TSM has been refactored.
Related: #3965
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3971)
=> Refactor AuthFailed error

ios/MullvadTypes/PacketTunnelStatus.swift, ios/PacketTunnel/TunnelMonitor/TunnelMonitor.swift
1. Wait for `NWPathMonitor` to report the network path update first before starting monitoring the tunnel. The reason for that is because `NWPathMonitor.currentPath` may not be set immediately and very often the tunnel monitor starts in the state where it thinks that connection is offline which is often times false. The new `pendingStart` state was added to account for that.
2. Wait for tunnel interface `utun` to appear in the list of network interfaces, before deducing if network connection is viable.
3. Improve check for presence of physical network interface by checking the interface type (wifi, cellular, or ethernet)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn …
=> Improve network path status reporting

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt, android/app/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt
This PR aims to adds an automatic transition to the out-of-time view if there's a tunnel state error caused by the account being expired. It also removes the expiry check scheduling in the connect view.
Depends on: #3971
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4162)
=> Add transition on auth failed caused by account expiry

.github/workflows/verify-locked-down-signatures.yml, building/sigstore/.gitattributes
Sometimes git treats the `signature-x` files as text files and tries to show their content/diffs in `git diff` and `git show`. This is terribly annoying and messes up the TTY. Adding this tells git to always treat them as binary files.
Move `.gitattributes` up one level to `building/` and have the contents be `sigstore/ binary`. I have not yet published any new containers after adding this file. I hope `podman`/`docker` wont trip up if this file exists in the sigstore, but I can't guarantee it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4195)
=> Make git always treat the container sigstore as binary files

android/config/dependency-check-suppression.xml, android/e2e/e2e-suppression.xml
This CVE affects the Apache Commons Net's FTP client that this app doesn't use. https://www.openwall.com/lists/oss-security/2022/12/03/1
File names:
- commons-beanutils-1.9.4.jar
- commons-collections-3.2.2.jar
- commons-digester-2.1.jar
- commons-logging-1.2.jar
- commons-validator-1.7.jar
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4201)
=> Suppress CVE-2021-37533

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SimulatorTunnelProvider.swift, ios/MullvadVPN/SimulatorTunnelProviderHost.swift, ios/MullvadVPN/TransportMonitor/PacketTunnelTransport.swift, ios/MullvadVPN/TransportMonitor/TransportMonitor.swift, ios/MullvadVPN/TunnelManager/LoadTunnelConfigurationOperation.swift, ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift, ios/MullvadVPN/TunnelManager/Tunnel.swift, ios/MullvadVPN/TunnelManager/TunnelConfiguration.swift, ios/MullvadVPN/TunnelManager/TunnelInteractor.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/TunnelManager/TunnelStore.swift
1. Introduce `TunnelStore` to list and create VPN configurations (see `Tunnel` as well)
2. Introduce `TunnelConfiguration` as a way to apply configuration to the system VPN configuration.
3. Remove `TunnelManager.sendRequest()` since `Tunnel` already provides means for IPC.
4. Rework `PacketTunnelTransport` to accept `Tunnel`. Adapt `TransportMonitor`.
5. Listen to `UIApplication.didBecomeActiveNotification` in `TunnelManager` and automatically refresh the tunnel status.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4198)
=> Decouple system tunnels from tunnel manager

ios/MullvadTypes/PacketTunnelErrorWrapper.swift, ios/MullvadTypes/PacketTunnelStatus.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Notifications/TunnelStatusNotificationProvider.swift, ios/MullvadVPN/TransportMonitor/PacketTunnelTransport.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/PacketTunnel/PacketTunnelProvider.swift
1. Block all the traffic when tunnel cannot read the settings (Introduced empty tunnel in `TunnelConfiguration`).
2. Introduce proper error enum, wrap WireGuard error and settings migration error.
3. Report possible errors to GUI.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4173)
=> Handle application updates with settings migration

dist-assets/windows/installer.nsh
`RMDir` doesn't appear to reset the error flag if it succeeds. The error flag may be set for many reasons prior to it being called, but only reasons that we can safely ignore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4202)
=> Ignore potentially spurious errors when removing app files

mullvad-problem-report/src/main.rs
Previously, the GUI would always report that the problem report was successfully sent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4212)
=> Return non-zero status if sending a problem report fails

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/InAppNotificationController.kt
This PR fixes an issue where the incorrect notification was showing due to the amount of notification changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4220)
=> Fix incorrect in-app notification showing

ios/BuildInstructions.md, ios/Configurations/.gitignore, ios/Configurations/App.xcconfig.template, ios/Configurations/Base.xcconfig.template, ios/Configurations/PacketTunnel.xcconfig.template, ios/MullvadVPN.xcodeproj/project.pbxproj
1. Rename provisioning specifier to `Mullvad VPN Release` since this is what we use.
2. Set code signing identity (`CODE_SIGN_IDENTITY`) to generic Apple Development in debug builds and Apple Distribution in release builds. This should solve compilation issues for embedded frameworks; they don't need separate provisioning profiles.
3. Use `APPLICATION_IDENTIFIER` to form the bundle ID of embedded frameworks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4222)
=> Add build configs for embedded frameworks

.github/workflows/daemon.yml
Uses the already built and published container images for building the desktop app on Linux. More or less just a copy of what we do in `.github/workflows/android-app.yml`.
Indentation in yml is something we are very inconsistent with. We mix 2 and 4 spaces a lot. I personally prefer 2 spaces. I have tried sticking to 2 spaces here, where it did not get intermixed too much with existing code using 4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4223)
=> Use the official Linux container image to build Rust in GH actions

ios/MullvadLogging/MullvadLogging.h, ios/MullvadTypes/MullvadTypes.h, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/Operations.xcscheme, ios/MullvadVPN/SettingsManager/Migrations/MigrationFromV1ToV2.swift, ios/Operations/Operations.h
1. Fix recursive static dependencies that caused the app to crash in release. Promote MullvadLogging, MullvadTypes, Operations into frameworks.
2. Migration v1 -> v2: Log out user but migrate settings when we cannot match the pubkey with device.
3. Clean up old references of MullvadNetwork in Xcode project
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4228)
=> Fix static lib deps

ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SettingsManager/SettingsManager.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift
We used to reconnect the tunnel from `TunnelManager` in response to connection status event. However this assumption doesn't quite work, because exactly the same tunnel status is being returned on subsequent poll attempts and so we usually discard/ignore those and thus never reconnect the tuunnel.
However since we know when we do migration, we can restart the tunnel right after, somewhere from `AppDelegate`. This PR adds additional `SettingsMigrationResult` type that informs us in regards of how migration went and so if it succeeded then we restart the tunnel. In other cases, hopefully tunnel manager should discard the tunnel during initialization.
- - - …
=> Reconnect tunnel after migration from AppDelegate

ios/MullvadVPN.xcodeproj/project.pbxproj
Looks like AppStore does not like when Frameworks are included into app extensions. This PR marks all frameworks used in PacketTunnel extensions as "Do not embed"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4233)
=> Do not embed frameworks into PackeTunnel.appex

dist-assets/uninstall_macos.sh
`postinstall` puts the completions in either `/opt/homebrew/share/fish/vendor_completions.d/` or `/usr/local/share/fish/vendor_completions.d/`, so let's just keep it simple and always delete both of those paths.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4230)
=> Fix uninstall_macos.sh failing when brew is not found

ios/MullvadVPN/AccountViewController.swift
As it was discussed, there is no reason to ask for user confirmation when logging out since we store the last used account and pre-fill the login input with it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4237)
=> Remove logout confirmation

mullvad-relay-selector/src/lib.rs, mullvad-types/src/relay_constraints.rs
This PR adds the following relay selector tests:
* Verify that selected relays match the providers constraint.
* Verify that selected relays match the OpenVPN constraints.
* Verify that bridges are eventually returned when bridge mode is set to automatic.
* Verify that different ports and servers are used when there are multiple matching servers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4169)
=> Add more relay selector tests

CHANGELOG.md, gui/src/main/user-interface.ts
This PR removes the ⌘Q shortcut from app builds. The shortcut was confusing since it didn't disconnect the tunnel as when quitting with the "Disconnect & quit" button. If we were to change it to also disconnecting, then users would risk accidentally disconnecting the tunnel by pressing the shortcut.
Closes https://github.com/mullvad/mullvadvpn-app/issues/4250.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4252)
=> Remove ⌘Q (Cmd-Q) hotkey

gui/package-lock.json, gui/package.json, gui/src/renderer/app.tsx, gui/src/renderer/components/AppRouter.tsx, gui/src/renderer/components/TransitionContainer.tsx, gui/src/renderer/components/TunnelControl.tsx, gui/test/e2e/installed/requires-input/login.spec.ts, gui/test/e2e/installed/state-dependent/location.spec.ts, gui/test/e2e/mocked/mocked-utils.ts, gui/test/e2e/mocked/settings.spec.ts, gui/test/e2e/setup/main.ts, gui/test/e2e/utils.ts
This PR fixes a few race conditions related to transitions when running e2e tests.
* `startApp` now waits for initial navigation to finish.
* Function `waitForNavigation` wait's for navigation and transition to finish.
* Make sure the tests interact with the correct `webContents` when the devtools window is open.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4251)
=> Fix navigation transition raceconditions for e2e tests

gui/src/renderer/components/cell/Label.tsx
This PR makes the icon in `Label.tsx` set the hover style only to the same instance, not to all instances of the component. This error caused cell icons to be red after visiting the split tunneling view on Linux.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4260)
=> Prevent red cell icons after visiting the split tunneling view on Linux

gui/src/renderer/components/ProblemReport.tsx
This PR adds a missing dependency to the `onSend` function in the problem report view. The missing dependency caused the problem report to not send after confirming to send it without an email address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4263)
=> Fix Send Anyway button in problem report

gui/src/renderer/app.tsx, gui/src/renderer/components/Lang.tsx, gui/src/renderer/components/SettingsHeader.tsx
This PR adds hyphens to words that are broken apart in settings headers. This is done by adding the `lang` attribute to an element at the top of the tree and adding `hyphen: auto` to the title element.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4259)
=> Add word break hyphen

gui/src/renderer/components/TunnelControl.tsx
This PR fixes the overflowing of the connection panel that happens on Linux (and probably other platforms) when the window is too small.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4264)
=> Fix position of connection panel when overflowing

gui/src/main/window-controller.ts, gui/src/renderer/components/TunnelControl.tsx
This PR fixes an issue where the app isn't high enough. It seems to be improssible to set an exact height so the change here makes it default to be too big which prevents UI glitches at least.
I've also changed the `TunnelControl` `min-height` to accomodate for the IPv6 out-IP to not make the content above jump when the connection panel is expanded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4266)
=> Fix window height being too small

Cargo.lock
The CI is failing due to [RUSTSEC-2023-0001](https://rustsec.org/advisories/RUSTSEC-2023-0001) (see https://github.com/mullvad/mullvadvpn-app/actions/runs/3874655359/jobs/6606142175). Fortunately, [pipe_mode](https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/struct.ServerOptions.html#method.pipe_mode) isn't used by the app/parity-tokio-ipc, so we're unaffected by this. This PR updates tokio anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4265)
=> Fix RUSTSEC-2023-0001 by updating tokio

.github/workflows/rust-unused-dependencies.yml
Run `cargo udeps` on Windows and macOS along with Linux. We had a bunch of dependencies there that were unused, so this seems justified.
I have not spent any time doing the same for Android. We probably should however. But I'll leave that for later as it has to be some cross compile thingy and I don't want to bother right now. This will at least make things significantly better than before.
I opted to "upgrade" the Linux job here to use our build container. To be consistent with the other Rust Linux build jobs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4270)
=> Run cargo udeps on Windows and macOS also

Cargo.lock, mullvad-daemon/Cargo.toml, mullvad-paths/Cargo.toml, mullvad-problem-report/Cargo.toml, mullvad-version/Cargo.toml, talpid-core/Cargo.toml, talpid-routing/Cargo.toml, talpid-tunnel/Cargo.toml
I ran `cargo udeps` towards the `aarch64-linux-android` target and found these to be unused.
I'll prepare a separate PR for running `cargo udeps --target aarch64-linux-android` in CI to catch future unused dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4271)
=> Remove Rust dependencies from Android that were unused

.github/workflows/rust-unused-dependencies.yml
Follow up to #4271 and #4270. Make sure we catch future unused dependencies on Android by running `cargo udeps` towards `aarch64-linux-android`
I did not feel like we needed the ability to enter a custom container image for the CI here. We just really need anything that can run `cargo udeps`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4272)
=> Run cargo udeps on Android to find unused dependencies

gui/src/renderer/components/ProblemReport.tsx
Previously, the problem report tool didn't always receive the correct message from the UI as `onSend` was using a cached/outdated message. This PR fixes this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4279)
=> Update onSend function when the report message changes

ios/MullvadREST/RESTAccessTokenManager.swift, ios/MullvadVPN/AddressCacheTracker.swift, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/MapViewController.swift, ios/MullvadVPN/Operations/AlertPresenter.swift, ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift, ios/Operations/AsyncOperationQueue.swift
This is a small PR that adds a convenience method to create serial operation queue `AsyncOperationQueue.makeSerial()`. We have quite a bunch of places where we rely on serial operation queues. I also dropped names of queues in most places as we don't really use them for anything.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4283)
=> Add helper to create serial operation queue

ios/MullvadVPN/MapViewController.swift
This PR guards against potential division by zero when computing map region. Which in turn produces invalid `MKCoordinateRegion` and causes `MKMapView` to throw NSException
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4285)
=> Fix potential division by zero

CHANGELOG.md, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-tunnel/src/lib.rs, talpid-wireguard/src/lib.rs
Previously, setting the firewall rules would sometimes fail in the connecting state:
```
Error: Failed to apply firewall policy for connecting state
Caused by: Unable to translate network interface name "wg-mullvad" into index
Caused by: Failed to get index for interface wg-mullvad
Caused by: No such device (os error 19)
```
This was due to a race between the `AllowEndpoint` tunnel command and tunnel monitor shutdown. The command reapplies the current firewall rules, and if this occurs immediately after the tunnel device has been destroyed, the new rules may refer to a non-existent device.
This PR fixes this by sending `TunnelEvent::Down` to the tunnel state machine, where the tunnel metadata is cleared, and waiting for it to complete before actually destroying the tunnel device.
Closes …
=> Prevent firewall update with non-existent tunnel device in connecting state

CHANGELOG.md, talpid-core/src/split_tunnel/windows/mod.rs, talpid-routing/src/windows/mod.rs, talpid-routing/src/windows/route_manager.rs
Previously, it was possible for a deadlock to occur in `set_tunnel_addresses` if it was called *and failed* at the same time as a route change occurred (i.e., if `split_tunnel_default_route_change_handler` was called at the right time). This PR fixes this by making sure that all mutexes are always released in the correct order.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4287)
=> Fix deadlock in set_tunnel_addresses

.github/workflows/rust-unused-dependencies.yml, .github/workflows/rustfmt.yml, .github/workflows/translations.yml
Use a specific version for `udeps`, `rustfmt`, etc. so nightly updates don't [break](https://github.com/mullvad/mullvadvpn-app/actions/runs/3950411884/jobs/6762907357) them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4298)
=> Pin nightly Rust toolchain version in CI workflows

.github/workflows/daemon.yml
Follow up to #4273 basically. The `Daemon+CLI` build job was triggered on a bunch of unrelated stuff. This change should make it more exact and at the same time clean up some old stuff that no longer exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4302)
=> Use a shorter and smarter include path list for the "Daemon+CLI" job

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/ModalRootAdaptivePresentationDelegate.swift, ios/MullvadVPN/SceneDelegate.swift
Besides extracting adaptive presentation delegate for modal root, this PR also fixes issues in former implementation where `transitionCoordinator.containerView` used to return `UIWindow` when changing to split screen which made settings cog available in modal contexts above modal root.
New implementation makes a manual lookup of `UITransitionView` to ensure that the settings cog is added into the right container view.
In the future this better be replaced with `UISheetPresentationController` (iOS 15+) subclass but for now we'll keep adding the settings cog manually within the adaptivity call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4300)
=> Extract adaptive presentation delegate

.github/workflows/android-app.yml, android/scripts/run-instrumented-tests.sh
This PR switches to a self-hosted test runner for instrumented Android tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4307)
=> Switch to self-hosted runner for Android tests

.github/workflows/rustfmt.yml, rustfmt.toml
Requesting review from all Rust coders since it affects formatting / potentially the dev setup.
I still recommend you run the formatting locally with the nightly toolchain. That way we get the benefit of merging imports etc that we can't get on stable. But to avoid nightly breakages we run CI on stable. That means the CI will accept some formatting that `cargo +nightly fmt` can change. Does this feel OK? The downside is that someone will very likely merge such a change at some point (or maybe rather frequently) and then your local `cargo +nightly fmt` will change code you did not touch. The two alternatives I see include:
* Close this PR, continue using nightly on CI (this breaks from time to time)
* Use stable locally for formatting also and ignore the potential benefits that the nightly …
=> Convert rustfmt CI run to use stable rustfmt

.github/workflows/android-app.yml
This got me confused for a while. But I think this was the correct thing to do. We don't have any `dist-assets/api-ip-address.txt` anywhere any longer. That was removed a long time ago. However, the references to `$cache/api-ip-address.txt` are still valid, since we still cache the **single** last known API IP with that filename, it's just that we stopped shipping the app with a **list of** API IPs under that filename.
If the above is correct, this was the only mention of the now obsolete file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4305)
=> Remove reference to dist-assets/api-ip-address.txt as it does not exist

.gitignore, build.sh, gui/tasks/distribution.js
Follow up to #4303. Store less build time generated data in `dist-assets/` and instead use `build/` for that.
I have tested this on Linux and macOS and the shell completions still seem to install fine with artifacts from this branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4304)
=> Move shell-completions to build/

CHANGELOG.md, Cargo.lock, mullvad-cli/src/cmds/tunnel.rs, talpid-tunnel-config-client/Cargo.toml, talpid-tunnel-config-client/examples/tuncfg-server.rs, talpid-tunnel-config-client/proto/tunnel_config.proto, talpid-tunnel-config-client/src/classic_mceliece.rs, talpid-tunnel-config-client/src/kyber.rs, talpid-tunnel-config-client/src/lib.rs
This adds [`pqc_kyber`](https://crates.io/crates/pqc_kyber) as a dependency in order to be able to use the Kyber KEM algorithm alongside CME for the Post-quantum key exchange and PSK computation. The PR also upgrades to the stabilized gPRC endpoint `PskExchangeV1` and removes both experimental endpoints since they are no longer needed client side.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4312)
=> Upgrade post-quantum gRPC endpoint and add kyber1024 into the mix

Cargo.lock
Fixes https://github.com/Colfenor/classic-mceliece-rust/issues/43
Does not really improve anything except that we can download 50kiB instead of ~10MiB from crates.io every time we build this crate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4318)
=> Upgrade classic-mceliece-rust to 2.0.2

Cargo.lock, android/translations-converter/Cargo.toml, android/translations-converter/src/android/plurals.rs, android/translations-converter/src/android/string_value.rs, android/translations-converter/src/android/strings.rs, android/translations-converter/src/main.rs
We currently get a warning in `cargo audit` due to [RUSTSEC-2022-0048](https://rustsec.org/advisories/RUSTSEC-2022-0048). It does not look like `serde-xml-rs` is [interested in migrating away from `xml-rs`](https://github.com/RReverser/serde-xml-rs/issues/180) and they mention `quick-xml` as a more up to date replacement. So I migrated to `quick-xml` instead.
Some serde annotation changes were needed to make it pick up fields, which are parsed a bit differently in `quick-xml`. Their documentation on mapping XML to Rust types is here: https://docs.rs/quick-xml/0.27.1/quick_xml/de/index.html#mapping-xml-to-rust-types
The only testing I have done here is making sure `cargo test` passes and that `cargo run` does not change anything.
- - - …
=> Replace serde-xml-rs with quick-xml in translations-converter

Cargo.lock, talpid-core/Cargo.toml, talpid-core/src/resolver.rs
Main motivation is to get rid of env_logger 0.9 from dependency tree (which in turn removes yet another user of the unmaintained `atty` crate that has a CVE on it).
Another motivation is of course to get rid of `alpha` software in our dependency tree.
I have not yet tested this except making sure CI passes. I'll build a macOS installer and try it out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4323)
=> Upgrade trust-dns-server to 0.22.0

.github/workflows/cargo-audit.yml, Cargo.lock, mullvad-cli/Cargo.toml, mullvad-problem-report/Cargo.toml, mullvad-setup/Cargo.toml, talpid-core/Cargo.toml, talpid-openvpn-plugin/Cargo.toml
We do explicitly ignore `RUSTSEC-2021-0145`. But that CVE is only an info level warning, so just `cargo audit` did not trigger an error on it anyway. `--deny warnings` was needed for that. This PR makes our audit check stricter by denying all warnings.
This means that minor stuff such as unmaintained dependencies will trigger an error. That can be annoying. But I figure we can then explicitly add that CVE to this list when it happens. I think that's better than silently ignoring warnings. This way we will get flagged when something is unmaintained etc and we can act on it.
This PR fixes a warnings we had: Upgrade `bumpalo` to avoid [RUSTSEC-2022-0078](https://rustsec.org/advisories/RUSTSEC-2022-0078)
I also upgrade `env_logger`. Since we were mentioning that as a blocker for not ignoring …
=> Stricter cargo audit (deny warnings)

CHANGELOG.md, docs/allow-macos-network-check.md, talpid-core/src/resolver.rs
Since it seems like there's another captive portal domain used for macOS's connectivity check, the custom resolver has been changed to match against both domains.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4329)
=> Add extra captive portal domain to custom resolver allow-list

CHANGELOG.md, dist-assets/pkg-scripts/postinstall
If this isn't set, the name in the Login Items UI is set to the organization of the signing certificate, ie Amagicom AB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4325)
=> Add associated bundle id to launch daemon plist

Cargo.lock, talpid-core/Cargo.toml, talpid-openvpn/Cargo.toml, talpid-openvpn/src/process/openvpn.rs
Basically a follow up to #4322 and #4323. Getting rid of our direct dependencies on the unmaintained and unsound crate `atty`.
We still depend on `atty` via `clap` and `fern`. For `fern` the issue is tracked [here](https://github.com/daboross/fern/issues/113) and for `clap` "all" we have to do is to upgrade to clap 4.
I have no idea why `cargo udeps` did not catch `atty` being unused in `talpid-core` however :shrug:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4327)
=> Replace atty with is-terminal as a direct dependency

CHANGELOG.md, Cargo.lock, dist-assets/pkg-scripts/postinstall, gui/locales/messages.pot, gui/src/main/index.ts, gui/src/main/user-interface.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/ErrorView.tsx, gui/src/renderer/components/Launch.tsx, gui/src/renderer/redux/userinterface/actions.ts, gui/src/renderer/redux/userinterface/reducers.ts, gui/src/shared/ipc-schema.ts, mullvad-daemon/Cargo.toml, mullvad-daemon/src/cli.rs, mullvad-daemon/src/macos_launch_daemon.rs, mullvad-daemon/src/main.rs
This PR adds a flag to `mullvad-daemon`, `--query-service`, which returns the authorization status of the launch daemon. If it is disallowed (`SMAppServiceStatusRequiresApproval`), then the GUI displays a message and a button that opens the login items panel, where the user can allow it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4319)
=> Check the authorization status of the launch daemon on macOS

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/SimulatorTunnelProviderHost.swift, ios/PacketTunnel/PacketTunnelProvider.swift, ios/TunnelProviderMessaging/URLRequestProxy.swift
This PR extracts the implementation of URL request proxy for sending requests bypassing VPN into a separate class. This class is then used in both packet tunnel provider and tunnel provider simulator.
Additionally this PR adds missing call to completion handler in response to `.cancelURLRequest(id)` IPC message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4332)
=> Extract url request proxy

ios/MullvadREST/RESTAPIProxy.swift, ios/MullvadREST/RESTAuthorization.swift, ios/MullvadREST/RESTRequestFactory.swift
This PR migrates the last call using account number authorization (`/app/v1/create-apple-payment`) to access token based authorization. `REST.Authorization.accountNumber` is dropped too and `REST.Authorization` is simplified to be an alias to `String`, which is basically account token.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4334)
=> Drop account number authorization

Cargo.lock
Upgrading tokio due to a CVE https://rustsec.org/advisories/RUSTSEC-2023-0005.
Found by CI: https://github.com/mullvad/mullvadvpn-app/actions/runs/4101000289/jobs/7072358220
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4335)
=> Upgrade tokio to avoid RUSTSEC-2023-0005

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/ModalRootAdaptivePresentationDelegate.swift, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPN/UIPresentationController+Private.swift
This PR backports automatic tracking of presentation controller dismissal of login overlay. Hopefully that should fix any outstanding issues related to settings button disappearance.
This PR relies on private notifications issued by `UIPresentationController` which is unfortunate but they have been around since a long time ago and I think it's fair to assume they will continue working in the foreseeable future. Eventually we will switch to our custom form-sheet presentation controller but for now that should do it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4336)
=> Backport automatic tracking of login overlay

CHANGELOG.md, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_nt.rs
It's unclear how often this path is taken, so it makes sense to keep the option to use wireguard-go for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4337)
=> Remove automatic fallback to wireguard-go on Windows

.github/workflows/clippy.yml, mullvad-api/src/rest.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/migrations/mod.rs, mullvad-daemon/src/migrations/v5.rs, mullvad-setup/src/main.rs, talpid-openvpn/src/lib.rs, talpid-routing/src/linux.rs
We had a bunch of `async fn`s that did not really do anything asynchronous. This lint is for some reason at the pedantic level, but I think it's a good lint. So I propose we bring it in and make it a hard error.
I wish there was a way to deny specific lints in `clippy.toml`, but that seems not possible. This documentation only talks about doing it on the command line: https://doc.rust-lang.org/stable/clippy/configuration.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4343)
=> Deny clippy `unused_async` lint

building/container-run.sh, building/containerized-build.sh
I found it cumbersome to get a shell in or run arbitrary commands in our build containers. This can be very useful to do other stuff than just building the app. For example linting and other stuff without needing those tools on your host. I split `containerized-build.sh` up into two scripts basically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4345)
=> Create container-shell.sh script to easier get container shell

android/docker/Dockerfile, building/Dockerfile
This makes the container ~560 MiB larger (1.86 -> 2.45 GiB), but as a reward we can easily run `cargo check --target x86_64-pc-windows-gnu` and `cargo clippy --target x86_64-pc-windows-gnu` on our Linux dev machines, something at least I find pretty cumbersome at the moment.
This can potentially also help with #4344, allowing us to have a single job and container running clippy for both Linux and Windows at least, potentially speeding up the CI?
I have not done any deep research, but it seems hard to do the same thing for macOS sadly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4346)
=> Add Clippy and the Windows toolchain in the Linux build container

mullvad-daemon/src/management_interface.rs, mullvad-daemon/src/migrations/mod.rs, mullvad-daemon/src/settings.rs
Previously, only root has read access to settings.json, as it contained the account number. Since that's no longer the case, making it readable by any user is fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4342)
=> Relax permissions for settings.json

ios/MullvadREST/RESTAPIProxy.swift, ios/MullvadREST/RESTAccessTokenManager.swift, ios/MullvadREST/RESTAccountsProxy.swift, ios/MullvadREST/RESTAuthorization.swift, ios/MullvadREST/RESTDevicesProxy.swift
Requests that require authorization already implement their own retry strategy. Hence access token requests should be a part of that strategy and not behave as each having their individual strategy.
Previously a request requiring authentication configured with 3 retry attempts would perform 9 calls (3 * 3) to obtain access token in the worst case. That's because each individual request to obtain access token was configured with default retry strategy (3 retry attempts). With this change exactly 3 attempts will be made in total.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4341)
=> Disable retry strategy for access tokens

ios/BuildInstructions.md, ios/Configurations/.gitignore, ios/Configurations/Base.xcconfig.template, ios/Configurations/Version.xcconfig, ios/MullvadVPN.xcodeproj/project.pbxproj
This PR moves version configuration into `Configurations/Version.xcconfig`. This is by far much simpler option than using `agvtool`. It also should align the version across all our internal frameworks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4339)
=> Move build version into Version.xcconfig

CHANGELOG.md, gui/src/main/account.ts
This PR adds a scheduler for showing the first "close to expiry"-notification. Previously the app had to be opened after the three day limit was passed to show the notifications.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4354)
=> Add scheduler for first "close to expiry"-notification

mullvad-daemon/src/migrations/mod.rs, mullvad-daemon/src/migrations/v2.rs, mullvad-daemon/src/migrations/v3.rs, mullvad-daemon/src/migrations/v4.rs, mullvad-daemon/src/migrations/v5.rs
`NoMatchingVersion` was used for any invalid settings format as long as it could be deserialized to JSON. So it has been renamed to `InvalidSettingsContent`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4356)
=> Rename settings error variants

CHANGELOG.md, mullvad-daemon/src/cli.rs
Previously, `mullvad-daemon` would panic if, for example, the path to the settings directory could not be obtained. This was problematic in the install script, since we one user reported that it would fail to install the system service, even though that directory was irrelevant.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4360)
=> Don't panic when the default directories cannot be obtained

ios/MullvadLogging/Logging.swift, ios/PacketTunnel/PacketTunnelProvider.swift, ios/PacketTunnel/TunnelMonitor/Pinger.swift, ios/PacketTunnel/TunnelMonitor/TunnelMonitor.swift
- Remove logging from `Pinger` since we usually log all errors that it throws in `TunnelMonitor` anyway.
- Change log level from `debug` to `trace` for all connection diagnostic messages.
- Expose log level in the log builder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4362)
=> Tune down logger

ci/buildserver-build.sh
This PR fixes an issue where `buildserver-build.sh` added the tag name to the name of release build directories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4374)
=> Fix tag being included in release build directory name

gui/src/main/account.ts
The new timeout for showing account expiry notifications immediately when there is three days left had a too large duration. The duration needs to fit into a signed 32-bit integer which means that the maximum is around 24 days. I've changed the duration to max out at 24 days.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4378)
=> Fix timeout duration not fitting into 32-bit signed integer

CHANGELOG.md, gui/src/main/user-interface.ts
This PR fixes a bug where the unpinned window wasn't closed and destroyed when switching to a pinned window. This resulted in the app quit procedure not finishing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4379)
=> Fix window not closing properly after pinning window

CHANGELOG.md, Cargo.lock, gui/tasks/distribution.js, talpid-openvpn-plugin/Cargo.toml, talpid-openvpn/src/lib.rs, talpid-openvpn/src/process/openvpn.rs
Notably, this adds potential support for DCO and (as a result) removes the dependency on `iproute2`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4381)
=> Update to openvpn 2.6

.github/workflows/android-app.yml, .github/workflows/verify-locked-down-signatures.yml, README.md, ci/buildserver-build-android.sh, ci/buildserver-build.sh, ci/verify-locked-down-signatures.sh
The plan is to change all our git repos to call their default branch `main`. To make this switch in this main app repository we need to adapt some scripts, CI jobs and documentation.
Once this PR has been approved I plan on doing things in this order:
1. Get all build servers ready with the updated build scripts and stop the current build scripts.
2. Rename the default branch on Github (this will automatically change all open PRs to be based off of `main`)
3. Merge this PR
4. Restart build server build scripts so they start using `main`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4387)
=> Rename all mentions of the "master" branch to "main"

gui/src/renderer/components/KeyboardNavigation.tsx
This PR fixes two different issues with our back actions. The main issue was that back actions weren't unique (e.g. `history.pop`) causing the `removeBackAction` function to remove more actions than it should. We also need to wrap the back action in a function when setting the state since it would otherwise be called.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4388)
=> Fix back action collision

CHANGELOG.md, docs/architecture.md, mullvad-cli/src/cmds/relay.rs, mullvad-cli/src/cmds/tunnel.rs, talpid-core/Cargo.toml, talpid-core/src/firewall/linux.rs, talpid-core/src/firewall/macos.rs, talpid-core/src/firewall/windows.rs, talpid-core/src/tunnel/mod.rs, talpid-tunnel-config-client/examples/psk-exchange.rs, talpid-tunnel-config-client/src/lib.rs, talpid-types/src/net/mod.rs, talpid-wireguard/src/config.rs, talpid-wireguard/src/lib.rs, windows/winfw/src/winfw/fwcontext.cpp, windows/winfw/src/winfw/mullvadguids.cpp, windows/winfw/src/winfw/mullvadguids.h, windows/winfw/src/winfw/rules/baseline/permitvpntunnel.cpp, windows/winfw/src/winfw/rules/baseline/permitvpntunnel.h, windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.cpp, windows/winfw/src/winfw/rules/baseline/permitvpntunnelservice.h, windows/winfw/src/winfw/winfw.h
This PR makes it possible to use PQ while using wireguards multihop. It does this by modifying the firewall API and doing two PQ handshakes through the WG tunnel to establish the PQ PSKs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4353)
=> Allow quantum-resistant tunnels (PQ) to work together with multihop

CHANGELOG.md, Cargo.lock, tunnel-obfuscation/Cargo.toml, tunnel-obfuscation/src/udp2tcp.rs
Upgrades to a version of `udp-over-tcp` with https://github.com/mullvad/udp-over-tcp/pull/39. Allows us to enable `TCP_NODELAY` and get better performance for WireGuard over TCP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4395)
=> Upgrade `udp-over-tcp` nodelay and enable `TCP_NODELAY`

ci/buildserver-build-android.sh, ci/buildserver-build.sh
This PR fixes the remaining shellcheck complaints in `buildserver-build.sh`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4396)
=> Fix buildscript shellcheck complaints

mullvad-version/build.rs
A small error in `mullvad-version/build.rs` made it so that it was being rebuilt every time you ran it!
If you did `cargo run --bin mullvad && cargo run --bin mullvad` it would compile and link the entire CLI two times. SLOW!
This was because we emitted an invalid path with `cargo:rerun-if-changed`. The `.git` directory is placed one level up from this crate. Apparently cargo reruns the build script every time if the pointed to path is non-existent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4401)
=> Greatly improve build speed by not rebuilding mullvad-version every time

android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiTest.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/constant/Constants.kt, mullvad-jni/src/lib.rs
Previously, this could only be used to override the IP. This diff also takes the hostname from the `InetSocketAddress` when `api-override` is enabled.
It's not possible to specify both IP and hostname in `InetSocketAddress`, so the IP is always resolved from the hostname.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4392)
=> Override the API hostname using the InetSocketAddress

building/container-run.sh, ci/buildserver-build.sh
Updating `buildserver-build.sh` to use our official container for building on Linux.
This PR supersedes #4405 as I just rolled it up here instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4406)
=> Make buildserver-build.sh use containers to build on Linux

.github/workflows/daemon.yml, .github/workflows/rust-unused-dependencies.yml, building/linux-container-image.txt
Update the Linux build container image to include #4346 and Rust 1.67
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4349)
=> Bump linux-container-image to mullvadvpn-app-build:20d7550f1

mullvad-relay-selector/src/lib.rs
The correct fix would be to mock the PRNG. Let's just make it extremely unlikely to fail for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4409)
=> Make test_load_balancing much less likely to fail

ios/PacketTunnel/PacketTunnelProvider.swift, ios/PacketTunnel/TunnelMonitor/TunnelMonitor.swift, ios/PacketTunnel/TunnelMonitor/TunnelMonitorDelegate.swift
1. Serialize calls to reconnect the tunnel and cancel the previous one to avoid congestion.
2. Rework tunnel monitor to use locks instead of internal queue which simplified things quite a bit.
3. Rework recovery phase. Added new `.recovering` state and paused path monitor when recovering to prevent tunnel monitor from starting when reconnecting the tunnel.
4. Ignore all requests to reconnect after receiving the first call to `stopTunnel()`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4408)
=> Serialize reconnect

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/PacketTunnel/PacketTunnelProvider.swift, ios/PacketTunnel/TunnelMonitor/TunnelMonitor.swift
1. Switch tunnel monitor to use `NETunnelProvider.defaultPath` instead of `NWPathMonitor` to improve reliability.
2. Add additional guard to restrict connectivity check to `connecting` or `connected` state.
3. Switch WireGuardKit to https://github.com/mullvad/wireguard-apple/pull/6
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4412)
=> Use default path when monitoring connectivity

ci/buildserver-build-android.sh, ci/buildserver-build.sh, ci/buildserver-upload.sh
Some final touches to be able to run the Linux builds on the new Linux build server (`app-build-linux2`).
Also fixed some bash to look like our own coding guidelines.
The change here is essentially to use `./upload` as the upload dir, instead of `/home/upload/upload`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4413)
=> New build script tweaks for new linux build server

ci/buildserver-upload.sh
So it's able to upload to `$version/additional-files` even before `$version` exists on the releases server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4414)
=> Add `--mkpath` to rsync for recursively creating missing directories

ios/CHANGELOG.md, ios/MullvadVPN/TunnelControlView.swift
Displays country above city on the connection screen, bringing it to parity with the select location screen where country is displayed as top item and city as sub item. Also prevents country from jumping up and down when reconnecting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4422)
=> Swap vertical position of country and city on connection view

ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift, ios/MullvadVPN/TunnelManager/Tunnel+Messaging.swift
This is a bit of shot in the dark but we spoke about the fact that sometimes the tunnel somehow deadlocks in connecting state and that opening the UI app somehow unclogs it. So I can only assume what's really going on, but it's possible that XPC between UI <-> PacketTunnel falls into coma if the other end is being suspended. This PR attempts to remedy this assumption by adding background observer condition that will automatically request background execution before starting operation and additional guard that will make sure that we don't attempt to start IPC interaction if we have less time than anticipated for it to complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mull …
=> Add background observer for IPC operations

.github/workflows/ios.yml
After rebasing `wireguard-apple` on the latest upstream, it seems that GitHub can no longer run our tests. I'll try and fix this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4426)
=> Bump Go version in workflow to 1.19.5

ios/CHANGELOG.md, ios/MullvadVPN/CustomDateComponentsFormatting.swift, ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift
The account row on the settings screen should display remaining time in years if equal to or more than two years, otherwise days. This brings the iOS app to parity with the intended behavior for all platforms.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4424)
=> Display remaining account time in years if equal to or more than two years, otherwise display days

gui/src/main/daemon-rpc.ts, gui/src/main/index.ts, gui/src/renderer/components/AppRouter.tsx, gui/src/renderer/components/TransitionContainer.tsx
This PR makes the Electron app disconnect from the daemon when the OS is suspended and reconnect on resume. To accomplish this I had to remove the queue handling in `TransitionContainer.tsx` and make sure that transitions only start if there is no other view queued.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4430)
=> Disconnect daemon on suspend

building/Dockerfile
[Debian 10 reached end of life on 2022-09-10](https://wiki.debian.org/DebianReleases) (It's LTS-supported for another year or so, but that is not maintained by the Debian security team). We are technically held back by the old kernel and the old compilers on Debian 10. So it would be a good quality of life for developers to be able to upgrade. It will also allow simplifying the firewall rules which will affect all Linux users in a tiny but positive way (way less verbose output of `nft list ruleset`).
This means we stop supporting glibc <2.31. Both Debian 11 and Ubuntu 20.04 use 2.31. Before this PR we supported glibc 2.28 and newer.
I have tried building a container image from this new dockerfile. And I have built the Linux app in it, and it seems to work. I tried both x86 and arm64. …
=> Drop Debian 10 support (Upgrade build container to Debian 11)

building/Dockerfile, building/container-run.sh, ci/buildserver-build-android.sh, ci/buildserver-build.sh
Updates the Linux (and indirectly Android) build container to have the [`mold`](https://github.com/rui314/mold.git) linker installed in it. Then adjust the container helper scripts to be able to easily use it.
The reason for not using it [like recommended for Rust](https://github.com/rui314/mold#how-to-use) is because that requires me to install `clang`, which blows up the size of the container significantly. With this `LD_PRELOAD` hack way of running it it's much easier.
I have opted out of mold for the real builds. Partially because it does not cut down on build times anyway, and partially because it feels iffy to depend on this linker without knowing more about it.
- - - …
=> Add mold linker to container

talpid-wireguard/src/lib.rs
This is a short-term fix to MacOS users with default MTUs having issues with PQ+MH
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4441)
=> Lower the MTU for PQ+MH MacOS handshakes

android/docker/Dockerfile, building/Dockerfile
Follow up to #4439 where we realized that `ARG` is better than `ENV` for variables that are only meant to be used in the `Dockerfile` itself, and not in the container when it's running later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4442)
=> Replace usage of ENV with ARG in some containers

CHANGELOG.md, README.md, building/linux-container-image.txt
Bumps the Linux container image to use the new Debian 11 based image. Also upgrades Rust from 1.67.1 to 1.68.0.
I'm not yet toggling `USE_MOLD` over to `true` by default since the Android images does not yet have mold installed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4443)
=> Swap Linux builds over to Debian 11

ios/MullvadVPN/RESTError+Display.swift
If the server response cannot be decoded properly (defaults to nil), `REST.Error.unhandledResponse(statusCode, serverResponse) ` can cause an expection when it tries to print an error message description. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4448)
=> Fix string formatting of error message that causes exception in login view

ios/MullvadVPN/PreferencesViewController.swift, ios/MullvadVPN/PreferencesViewModel.swift, ios/MullvadVPN/SettingsCellFactory.swift
The menu names in Settings on Desktop has been changed from Preferences and Advanced to User interface settings and VPN settings.
On iOS we don't have the same amount of settings as on Desktop, so the only change that is needed is to change the name "Preferences" in settings to "VPN settings".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4450)
=> Change 'Preferences' to 'VPN Settings'

CHANGELOG.md, ios/CHANGELOG.md, ios/MullvadVPN/TunnelManager/TunnelManager.swift, mullvad-types/src/wireguard.rs
To be consistent across all platforms, the key rotation interval on iOS and Android is bumped to 7 days instead of 4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4456)
=> Change key rotation interval on Android and iOS to 7 days

building/container-run.sh
Follow up to #4443. Since both the Linux and Android builds now use the containers that have `mold` installed in them, we can enable it by default. This should speed up linking times by quite a lot *in debug builds*.
This will sadly not benefit the CI yet. The CI uses the containers, but are not executed through `container-run.sh` and mold is not the default linker in the containers. Fixing that is left as an exercise for the future.
Build servers still link with GNU ld by explicitly opting out with `USE_MOLD=false`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4457)
=> Use mold linker by default (USE_MOLD=true)

ios/MullvadVPN/PreferencesDataSource.swift
VPN settings list is empty when opening the settings view. This fixes the bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4458)
=> Fix bug where VPN settings list is empty

ios/MullvadREST/RESTRetryStrategy.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift
When the API is not available, logging out takes a very long time. Eg. going to the account screen will fetch account and device info, so if one would try to log out while those calls are in progress there will be additional retries and backoffs added to the queue. This can result in chained timeouts for get-my-account, get-device and delete-device, all in all adding minutes to the logout process. Cancelling all operations before triggering the logout action solves this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4455)
=> Cancel all pending network operations when a logout action is triggered

CHANGELOG.md, gui/src/renderer/components/WireguardSettings.tsx, mullvad-daemon/src/migrations/v6.rs, mullvad-relay-selector/src/lib.rs
We want to free up port 443 for other TCP based protocols (fake TCP). So we need to make the app stop using it asap to get people away from this port.
The plan is to backport this fix to the `prepare-2023.3` branch when it's approved, to get it out in the coming release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4467)
=> Remove port 443 from WireGuard over TCP

ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift
1. Fix logout transition so that Login appears beneath Settings on iPhone. Circumvents issue where an empty map is shown first.
2. Fix issue in router where transition from TOS > Login on iPad would assume that the route cannot be presented. Checking for `isExclusive` flag here to remedy this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4469)
=> Fix logout transition

android/docker/Dockerfile, building/Dockerfile, building/container-run.sh
Updated fix instead of #4473. With this change `cargo clean` should work without errors and non-zero exit codes in the build containers. Making them nicer to use both in interactive mode, but also makes `build.sh` not fail to make production releases.
I updated some documentation also. Since the dockerfile comments were not in line with how we used them ourselves.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4477)
=> Change build container CARGO_TARGET_DIR to allow cargo clean

building/Dockerfile
Enables Cargo's new sparse protocol for fetching the index. This saves significant amount of time in updating the crates.io index. Read more here: https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol
If this turns out to be fast enough, we could consider removing the complexity of mounting a registry cache into the containers. However, since we don't know the reliability and performance of the sparse protocol yet, let's wait with evaluating that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4478)
=> Enable Cargo's sparse protocol

.github/workflows/android-app.yml
This adds support for building the native libraries in parallel for the supported architectures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4484)
=> Add multi-arch support in android build action

ios/Assets/changes.txt, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/ChangeLog.swift, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift, ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift, ios/MullvadVPN/Extensions/Bundle+ProductVersion.swift, ios/MullvadVPN/Extensions/UIView+AutoLayoutBuilder.swift, ios/MullvadVPN/View controllers/ChangeLog/ChangeLogContentView.swift, ios/MullvadVPN/View controllers/ChangeLog/ChangeLogViewController.swift
- Add auto layout builder to simplify constraints creation. Most common constraints we have is pinning edges of one view to the parent or the other
- Show changelog when the app starts with contents of `changes.txt` file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4479)
=> Show "Changes" in app after upgrades

ios/CHANGELOG.md
This PR updates iOS changelog. Since there is no tag for `iOS/2023.1` release, I can only assume that key rotation was changed from 4 to 7 days after the release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4476)
=> Mark iOS 2023.1 release in changelog

ios/CHANGELOG.md, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift, ios/MullvadVPN/TunnelManager/ReconnectTunnelOperation.swift, ios/MullvadVPN/TunnelManager/RotateKeyOperation.swift, ios/MullvadVPN/TunnelManager/Tunnel+Messaging.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/PacketTunnel/PacketTunnelProvider.swift, ios/TunnelProviderMessaging/TunnelProviderMessage.swift
When a WireGuard key is rotated, if the user is connected, the tunnel shouldn't be reconnected immediately. Instead, it should reconnect after 120 seconds to allow for latency when relays are synched.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4497)
=> Delay tunnel reconnection after private key rotation

CHANGELOG.md, mullvad-daemon/src/device/mod.rs
Previously the account manager would not rotate the wireguard key unless any account manager command was given. This resulted in old keys not being rotated sometimes when not using the GUI. This fixes this by always starting a key rotation when the account manager starts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4490)
=> Account manager now always rotates key if needed-des-113

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/App/SafariCoordinator.swift, ios/MullvadVPN/Coordinators/App/SettingsCoordinator.swift, ios/MullvadVPN/Coordinators/App/TermsOfServiceCoordinator.swift, ios/MullvadVPN/View controllers/TermsOfService/TermsOfServiceViewController.swift
1. Move Safari handling into SafariCoordinator that can be presented modally.
2. Move Safari presentation from `TermsOfServiceViewController` into coordinator.
3. Extend `SettingsCoordinator.start()` to accept initial route.
4. Make sure that `SettingsCoordinator.navigate(to:)` always calls completion handler.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4503)
=> Move Safari related handling into its own coordinator

CHANGELOG.md, ios/CHANGELOG.md, ios/MullvadVPN/TunnelManager/TunnelManager.swift, mullvad-types/src/wireguard.rs
Basically just doing what #4456 did, but again. And this time to 14 days.
The main issue here is that we stress the API too much. The goal is to lower the rotation interval again once the API behaves better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4512)
=> Change WireGuard key rotation interval to 14 days on all platforms

ios/MullvadVPN/TunnelManager/TunnelManager.swift, mullvad-daemon/src/device/service.rs
We currently start off by retrying after 4 seconds and cap the retry interval at 24 hours. This sometimes taxes the API greatly. For now, let's change the interval to 24 hours.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4511)
=> Set retry interval to 24 hours for automatic key rotation

ios/MullvadVPN/View controllers/Settings/SettingsCell.swift
This small PR adds different set of constraints when handling subtitle layout which I think may come handy in the future. It's used in trusted networks work as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4513)
=> Handle .subtitle layout in settings cell

gui/src/main/account.ts
Currently expiry notifications aren't removed on logout. This means that the notification icon also stays in the tray menu.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4521)
=> Reset expiry notifications on logout

ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SettingsManager/Migrations/MigrationFromV1ToV2.swift, ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift, ios/MullvadVPN/TunnelManager/RotateKeyOperation.swift, ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, ios/MullvadVPN/TunnelManager/TunnelInteractor.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/TunnelManager/UpdateDeviceDataOperation.swift
If the current private key is old enough to be rotated, the app will always try to do so immediately on wake/start. If the API is down or rotation for some reason keeps failing, this can lead to more rotation attempts than the default rotation interval allows. By persisting last rotation date we can make sure that the intended interval is respected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4517)
=> Persist last key rotation date to determine next scheduled rotation

gui/standalone-tests.ts, gui/test/e2e/installed/playwright.config.ts, gui/test/e2e/installed/state-dependent/login.spec.ts
This PR fixes the issues we experienced when running the tests in the Windows VM. The cause was the responses arriving too quickly for it to have time to check the intermediate states. I've also done a bunch of other improvements. Here are the changes:
- Catch error when removing tmp directory
- Add playwright config for installed tests and increase timeouts
- Make playwright stop after first failure
- Forward playwright stdout while running
- Remove expects for intermediate states during login
- Add missing await when emptying login field in test
Closes DES-129.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4520)
=> Fix login tests on slow machines

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/VersionInfo.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SettingsFragment.kt
This PR aims to fix an issue where the app version isn't available in settings if the app can't connect to the daemon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4522)
=> Fix missing app verison in settings

ios/MullvadREST/RESTError.swift, ios/MullvadVPN/Extensions/RESTError+Display.swift
Currently in the iOS app if you try to log in, and the API returns status code 429 (TOO MANY REQUESTS), there's a message being displayed:
Login failed
Unexpected server response: THROTTLED (HTTP status: 429)
Being throttled is not unexpected, but the app should handle these status codes more gracefully. The app should also handle status code 503 (SERVICE UNAVAILABLE) in the same way. Both 503 and 429 indicate that the service is overloaded/rate limited and should inform the user that they need to try again later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4518)
=> Display human readable error messages for throttled API calls

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt
This change hides the Custom DNS warning, which is part of the content blockers, when the content blockers are not expanded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4544)
=> Hide custom dns warning

ios/MullvadREST/RESTDefaults.swift, ios/MullvadREST/RESTNetworkOperation.swift, ios/MullvadVPN/SettingsManager/SettingsManager.swift, ios/MullvadVPN/View controllers/Login/LoginViewController.swift, ios/RelaySelector/RelaySelector.swift
This PR introduces additional `REST.isStagingEnvironment` flag that makes it possible to disable API IP address cache when working on staging environment and stick to default API IP endpoint instead. This seems to work great with existing SSL certificate that we use for pinning.
In order to configure the app to work with staging environment, modify `defaultAPIEndpoint`, `defaultAPIHostname` accordingly and set `isStagingEnvironment = true` in `MullvadREST/RESTDefaults.swift`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4542)
=> Disable IP address cache for staging environment

ios/MullvadVPN/View controllers/Login/AccountTokenInput.swift, ios/MullvadVPNTests/AccountTokenInputTests.swift
This PR adds a check in `AccountTokenInput.swift` to avoid crashing the application when certain invalid characters are either input (via an external keyboard) or pasted in the account text field on the login screen.
Instead of crashing, the text field is now updated with the currently parsed formatted string that contains the account number.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4554)
=> Prevent exotic characters to be input in the account text field

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift, ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, ios/MullvadVPN/TunnelManager/Tunnel+Messaging.swift, ios/Operations/AsyncBlockOperation.swift, ios/Operations/AsyncOperation.swift, ios/Operations/AsyncOperationQueue.swift, ios/Operations/NoFailedDependenciesCondition.swift, ios/Operations/ResultBlockOperation.swift, ios/Operations/TransformOperation.swift, ios/OperationsTests/OperationCancellationTests.swift
1. Add helpers to attach operation cancellation and completion observers (`AsyncOperation.onFinish` and `AsyncOperation.onCancel`)
2. Do not fire `operationDidCancel` if operation isn't executing yet. This way `start()` can dispatch cancellation in the same order in which operations are scheduled.
3. Add cancellation related tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4553)
=> Improve operation cancellation

ios/MullvadVPN/Containers/Root/HeaderBarView.swift, ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift
Add the device name and time left labels to the header after the user has closed the in-app banner message (see referenced card), Confluence and Zeplin links in Parent card
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4564)
=> Add device name and time left to header

CHANGELOG.md, mullvad-daemon/src/lib.rs, mullvad-daemon/src/settings.rs, mullvad-types/src/relay_constraints.rs, mullvad-types/src/wireguard.rs, talpid-core/src/firewall/mod.rs, talpid-wireguard/src/config.rs, talpid-wireguard/src/lib.rs
For debugging purposes, log select settings whenever entering the connecting state.
The following settings are logged:
* mssfix/MTU
* WG over IPv6
* Multihop
* IPv6 (in tunnel)
* LAN sharing
* PQ
* Which content blockers are used and whether custom DNS is enabled
* Obfuscation state
> [mullvad_daemon][DEBUG] ovpn mssfix: unset, wg ip: any, wg mtu: 1420, multihop: off, ipv6 (tun): off, lan: on, pq: on, obfs: udp2tcp, dns: default
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4531)
=> Log settings summary when connecting

gui/src/main/notification-controller.ts
Sometimes the notification dot doesn't disappear when it should. I haven't been able to reproduce it consistently but I think this will solve the issue. The problem was that the close handler added the notification to the dismissed notifications when it should just have been removed from all lists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4563)
=> Prevent close notification close handler from running when closing by category

CHANGELOG.md, gui/src/main/daemon-rpc.ts, gui/src/main/index.ts
When disconnecting the daemon during suspend the `ConnectionObserver` wasn't removed resulting in multiple active observers. This is probably the cause of the issue where people receive multiple of the same notifications although I haven't been able to reproduce it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4566)
=> Remove daemon connection observer when disconnecting during suspend

CHANGELOG.md, gui/tasks/distribution.js
This fixes #4534. I've tested this myself with the currently available Slack RPM package, and this does fix the issue. The folder `/usr/lib/.build-id` is no longer present in our package with my changes, but it's there in our current installers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4547)
=> Fix RPM package to not include build ids

gui/locales/messages.pot, gui/src/renderer/components/VpnSettings.tsx
This PR adds an informational dialog for the local network sharing setting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4576)
=> Add informational dialog for local network sharing

gui/src/main/index.ts
Apparently the clipboard permission handling changed a bit in Electron 23. This PR addresses that and makes the copy account number button work again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4579)
=> Fix clipboard permission request after electron upgrade

gui/src/renderer/components/DeviceRevokedView.tsx, gui/test/e2e/installed/state-dependent/device-revoked.spec.ts
Thi PR adds a small GUI test for the device revoked view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4582)
=> Add GUI test for device revoked view

ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController.swift
As of 14/04/23, main has a broken text input for problem reports - none of the controls are shown. Can reproduce on iPhone Xr and an iPhone 13. The controls should be rendered as in the second screenshot.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4575)
=> Missing header in problem report view

ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController.swift
Support has reported that they always need to ask the user which country they are connecting from, which is not effective since that slows down the helping process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4574)
=> Change text hint for problem report

CHANGELOG.md, gui/src/main/command-line-options.ts, gui/src/main/index.ts, gui/src/main/user-interface.ts, gui/src/main/version.ts
This PR adds help and version output when `--help`/`-h` and `--version` is provided. Closes https://github.com/mullvad/mullvadvpn-app/issues/3161.
```
$ /opt/Mullvad\ VPN/mullvad-vpn --help
Mullvad VPN
Graphical interface for managing the Mullvad VPN daemon
OPTIONS:
--help, -h          Print this help text
--version           Print the app version
--show-changes      Show changes dialog
USEFUL ELECTRON/CHROMIUM OPTIONS:
--no-sandbox        Run without renderer process sandboxed
--disable-gpu       Run without hardware acceleration for graphics
```
```
$ /opt/Mullvad\ VPN/mullvad-vpn --version
2023.3-dev-87dab7
Electron version: 23.2.0
```
- - - …
=> Add help and version command line flags to the electron app

gui/src/renderer/components/TransitionContainer.tsx
Currently we prevent pointer events on both views when transitioning. This causes some issues on macOS where scrolling is disabled until you stop scrolling if you started scrolling on a view with `pointer-events: none`. This means that scrolling will be disabled until the user stops scrolling. I've solved this by enabling pointer events on the new view since I can only see reasons to prevent it for the previous view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4593)
=> Enable pointer events on the new view when transitioning

ios/CHANGELOG.md, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Classes/FirstTimeLaunch.swift, ios/MullvadVPN/SettingsManager/SettingsManager.swift
To wipe the settings two conditions need to be satisfied.
- UserDefaults flag `hasFinishedFirstTimeLaunch == true`
- Keychain flag `previousAppVersion == true`
`hasFinishedFirstTimeLaunch` determines - as suggested in the issue description - whether a wipe is desirable or not. However, for it to go into effect we need the user to have previously been on a compatible app version, ie that has the UserDefaults flag.
Use cases:
- User does a clean install with no previous data. `hasFinishedFirstTimeLaunch` check succeeds and `previousAppVersion` check fail - no wipe.
- User updates from a version without the UserDefaults flag. `hasFinishedFirstTimeLaunch` check succeeds and `previousAppVersion` check fails - no wipe.
- User updates from a version with the UserDefaults flag. …
=> Wipe all settings on app reinstall

ios/MullvadREST/ServerRelaysResponse.swift, ios/MullvadVPNTests/RelaySelectorTests.swift, ios/RelaySelector/RelaySelector.swift
This PR adds shadowsocks parsing from relay list and exposes a function to fetch random shadowsocks TCP bridge via `RelaySelector`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4590)
=> Add shadowsocks bridges parsing

ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationCellFactory.swift, ios/MullvadVPN/View controllers/Settings/SettingsCellFactory.swift, ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift
This is something that came up today during one of code reviews. 
We have a lot of code paths where we keep repeating ourselves. This is especially the case when it comes to dequeuing reusable cells.
This PR makes sure that data source items can return the corresponding `CellReuseIdentifiers` identifier. The code that resolves reuse identifier is located in the data source next to `CellReuseIdentifiers`.  That's because they seem to be very well connected and better be kept together for clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4595)
=> Reduce code duplication in data sources IOS-123

ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift, ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift
In the app we have some platforms that round 5.99 months to 5 months, this is misleading and we want to be clear on how much time a user has left.
It was decided that we will use days and years only to display the time left:
- If a user has more than 2 years (730 days) left of time it should be displayed in whole years rounded down. (Divide the number of days with 365 and round down)
- If a user has less than 2 years left (e.g. 729 days) then this should be displayed in days.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4586)
=> Change "Time left" on iOS to days and years

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt
Use rememberSaveable instead remember for expandContentBlockersState so that it is kept when returning from the Split tunnelling settings page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4597)
=> Remember expand content blockers state

Cargo.lock
What the title says. `cargo deny` started reporting this CVE in my other PR, so we better upgrade this asap. I do not believe the CVE affects our app in any way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4599)
=> Upgrade h2 crate to avoid RUSTSEC-2023-0034

mullvad-daemon/src/migrations/v6.rs, mullvad-paths/src/windows.rs, talpid-core/src/dns/windows/auto.rs, talpid-core/src/dns/windows/iphlpapi.rs, talpid-core/src/dns/windows/netsh.rs, talpid-core/src/dns/windows/tcpip.rs, talpid-core/src/firewall/windows.rs, talpid-core/src/split_tunnel/windows/path_monitor.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-openvpn/src/wintun.rs, talpid-routing/src/windows/route_manager.rs, talpid-tunnel/src/tun_provider/stub.rs, talpid-windows-net/src/net.rs, talpid-wireguard/src/wireguard_nt.rs
Continuation for #4598. Fixing the remaining stuff that `--fix` mostly fixed for us. And attacking a bunch of the warnings that normal `cargo clippy` emits but can't automatically fix.
This does not fix everything. I did not want the PR to grow too much. Me or someone else can look at the remaining issues later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4601)
=> Clippy fix windows 2

ios/MullvadVPN/View controllers/SelectLocation/SelectLocationViewController.swift
The screenshot script does not run well with the margins of the search field (hides part of the field). We should remove the negative top value and pin it to the safeAreaLayoutGuide instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4603)
=> Remove negative top margin for search field

gui/locales/messages.pot, gui/src/main/errors.ts
Previously the login error messages haven't been translated. This PR adds them to the localization templates to solve this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4583)
=> Add login error messages to localization templates

talpid-core/src/dns/windows/dnsapi.rs, talpid-core/src/ffi.rs, talpid-core/src/firewall/windows.rs, talpid-core/src/split_tunnel/windows/path_monitor.rs, talpid-core/src/tunnel/mod.rs, talpid-core/src/window.rs, talpid-windows-net/src/net.rs, talpid-wireguard/src/wireguard_go.rs, talpid-wireguard/src/wireguard_nt.rs
Follow up to #4601. Fixing the remaining *warnings* from Clippy when running it towards the target `x86_64-pc-windows-gnu`. There are two *errors* left that Clippy complains about. But I left those out from this PR. They should definitely be looked at.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4606)
=> Clippy fix windows 3

android/README.md
Add description to README on how to solve the issue of a lot of backup files being created while running the tidy script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4610)
=> Add workaround for tidy script issue on macOS

android/app/src/main/res/values/attrs.xml, android/app/src/main/res/values/strings.xml, android/app/src/main/res/values/strings_non_translatable.xml, android/app/src/main/res/values/styles.xml, android/scripts/tidy.sh
Change it so that the tidy script is run two times, one for files under `/values` and one for the other files. This is so that we can have a separate configuration for the files in `/values`.
Applied this new tidy configuration to the files in `/values`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4612)
=> Add separate tidy config for /values

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift, ios/MullvadVPN/Supporting Files/Assets.xcassets/IconInfo.imageset/Contents.json, ios/MullvadVPN/Supporting Files/Assets.xcassets/IconInfo.imageset/IconInfo.pdf, ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesDataSourceDelegate.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift, ios/MullvadVPN/View controllers/Settings/SettingsCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift, ios/convert-assets.rb
As the list for blocking content becomes longer, having too many toggles at once does not look good.
So the content blockers should feature a drop-down with all the blocking toggles.
Instead of informational dialogs on each toggle it will now feature a general dialog for all and a warning dialog for Malware only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4532)
=> Improve content blocker settings interface

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Containers/Root/HeaderBarView.swift, ios/MullvadVPN/Containers/Root/RootConfiguration.swift, ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Extensions/NSAttributedString+Markdown.swift, ios/MullvadVPN/Notifications/InAppNotificationDescriptor.swift, ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift, ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift, ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift, ios/MullvadVPN/Notifications/UI/NotificationController.swift, ios/MullvadVPN/SceneDelegate.swift
Add an in-app banner message that the user need to close for it to disappear, when the user has closed the in-app banner message the device name and time left are shown in the header (see referenced card), Confluence and Zeplin links in Parent card
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4608)
=> Add in-app banner message for a new device

ios/MullvadVPN/Containers/Navigation/UINavigationBar+Appearance.swift, ios/MullvadVPN/Containers/Root/HeaderBarView.swift, ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift, ios/MullvadVPN/View controllers/Account/AccountContentView.swift, ios/MullvadVPN/View controllers/ChangeLog/ChangeLogContentView.swift, ios/MullvadVPN/View controllers/DeviceList/DeviceManagementContentView.swift, ios/MullvadVPN/View controllers/DeviceList/DeviceRowView.swift, ios/MullvadVPN/View controllers/Login/LoginContentView.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeContentView.swift, ios/MullvadVPN/View controllers/ProblemReport/ProblemReportSubmissionOverlayView.swift, ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController.swift, ios/MullvadVPN/View controllers/RevokedDevice/RevokedDeviceViewController.swift, ios/MullvadVPN/View controllers/SelectLocation/SelectLocationCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsContentBlockersHeaderView.swift, ios/MullvadVPN/View controllers/Settings/SettingsDNSTextCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsStaticTextFooterView.swift, ios/MullvadVPN/View controllers/TermsOfService/TermsOfServiceContentView.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
Since iOS 11 views support directional layout margins that automatically handle RTL (right-to-left) environments. We do use writing direction agnostic UI elsewhere including in AutoLayout constraints, so it would be a quality improvement to switch from UIView.layoutMargins to UIView.directionalLayoutMargins (NSDirectionalEdgeInsets). All our UI metrics and dimensions stored in UIMetrics.swift should be migrated from UIEdgeInsets to NSDirectionalEdgeInsets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4621)
=> Change to directional layout margins

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Extensions/UIBarButtonItem+Blocks.swift, ios/MullvadVPN/Extensions/UIBarButtonItem+KeyboardNavigation.swift, ios/MullvadVPN/View controllers/ProblemReport/ProblemReportReviewViewController.swift, ios/MullvadVPN/View controllers/SelectLocation/SelectLocationViewController.swift, ios/MullvadVPN/View controllers/Settings/SettingsViewController.swift
Quality of life improvement for developers.  This PR adds `UIBarButtonItem` with block handlers on iOS. Keeping it draft because I am not entirely sure we need it nor do I have much time to spread too thin on other things right now. Sadly block based (`UIAction`) handlers are only available since iOS 14. So this is somewhat an attempt to ease pain of using Objective-C selectors in the meanwhile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4605)
=> Backport block based handler for UIBarButtonItem

ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift
Diffable data sources don't like `UITableView.performBatchUpdates`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4632)
=> Fix crash in VPN settings when footer is updated

ios/MullvadVPN/Notifications/InAppNotificationDescriptor.swift, ios/MullvadVPN/Notifications/NotificationManager.swift, ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift, ios/MullvadVPN/Notifications/UI/NotificationController.swift, ios/MullvadVPN/UI appearance/UIColor+Palette.swift
1. This PR reverts `Equatable` implementation for  `InAppNotificationDescriptor`. The same notification can be displayed many times with different attributes so checking notifications by `identifier` only does not always work. This proved to be the case with `RegisteredDeviceInAppNotification` which didn't disappear on logout and then didn't update after logging with new account. Maybe it's an edge case? In any case, please only call `invalidate()` on notification providers when external events result into new content being produced.
2. `InAppNotificationAction` implements `Equatable` but ignore block handler because there is no easy way to achieve that, but on other side we always produce new closures so it's pointless either way. In that regard let's focus equality check for properties …
=> Fix in-app notification equality and action button color

ios/MullvadVPN/Supporting Files/Info.plist
This PR disables OSLogging facility for `com.apple.VectorKit` which has been spamming our console log with huge amounts of repeated information which we can't do much with anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4634)
=> Disable VectorKit logging IOS-146

ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift, ios/MullvadVPN/View controllers/DeviceList/DeviceRowView.swift
Users has been requesting to see the device creation date in the Too many devices view and so their request has been granted. 🎉 The creation date for the device is to be shown underneath the device name.
The list-items height has been made higher, but only in this specific view!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4626)
=> Add creation date to device name in Too many devices view

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/App/TunnelCoordinator.swift, ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/NotificationConfiguration.swift, ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotification.swift, ios/MullvadVPN/Notifications/NotificationManager.swift, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift, ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/TunnelManager/TunnelObserver.swift, ios/MullvadVPN/View controllers/Account/AccountInteractor.swift, ios/MullvadVPN/View controllers/Account/AccountViewController.swift, ios/MullvadVPN/View controllers/Settings/SettingsInteractor.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewControllerInteractor.swift
1. Move constants used in notification providers into `NotificationConfiguration`
2. Change notification style to present banner with sound too. Since we use provisional push notifications, banner and sound will only happen if users toggle them in System settings for the app (via notifications section). Out of box we'll always be quite.
3. Device state observers will now receive previous device state along with the current one, which should help with business logic. Note that `DeviceState` changes are posted even when account data or device data change, that's why receiving two consecutive `DeviceState.loggedIn`  states in a row is totally possible. In that case if you really care to react to specific changes, make sure you compare current and previous device state before taking action. …
=> Handle account expiry transitions IOS-90

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ContentBlockersInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomDnsInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AdvancedSettingScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AdvancedSettingsUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AdvancedFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AdvancedSettingsViewModelState.kt, android/app/src/main/res/values/strings.xml, gui/locales/messages.pot
Add extra texts to the Content Blockers and Custom DNS  informational dialogs to inform user for latency of applying changes.
also informational toast with shorter string added for content blocker items check change.
Fixes: DROID-123, DROID-124, DROID-125, DROID-126, DROID-102
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4628)
=> Dns settings text additions

ios/CHANGELOG.md
The changelog has been updated to reflect a past release. We should always update the changelog whenever a meaningful change has been made to the app. The only reason all of you are set as reviewers is just so that the changelog is brought to your attention - you can read more about the format we want to be using [here](https://keepachangelog.com/en/1.0.0/). We should only document significant user facing changes - small UI changes don't need to be recorded here. 
If any of you feel like the log is missing something the users should know about, feel free to push changes to the branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4646)
=> Update changelog for iOS

.github/workflows/ios.yml
Life is too short to run old Xcode and dwell on the past. This PR upgrades CI to macOS 13 and iOS 16 sim along with Xcode 14.3 and Swift 5.8 coming along with it. This should enable us to use some of the most recent additions to Swift 5.8. This PR also migrates us to new GitHub Actions which make our CI script easier to understand.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4635)
=> iOS: upgrade CI to macOS 13 and latest tools IOS-148

ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift, ios/MullvadVPN/Notifications/UI/NotificationController.swift, ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift, ios/MullvadVPN/TunnelManager/StopTunnelOperation.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
When an iOS device has no connectivity, iOS won't let us start a tunnel. From a UX perspective, this looks like the app is broken - it enters the connecting state and is immediately thrown back out of it. To improve the UX, a banner tells the user that there's no network and all action buttons are disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4613)
=> Improve behavior when there's no network

ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift, ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift
When querying multiple date components, `Calendar` tends to collapse to the largest unit. That's the problem because for dates < 2 years we'd only display the number of days that's less than a year, after computing number of whole years. So when formatting a date that's exactly 365 days, we'd print 0 days instead because the largest unit a year in that case.
This PR also clamps the `end` date so that we don't have to handle "0 days" as a special case, instead when `start > end`, the `end = start`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4654)
=> Fix date interval formatting and update tests

ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeContentView.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift
When in the out-of-time view, the app will fail to update its view state on disconnect, blocking the user from accessing the add time button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4620)
=> Fix view state when disconnecting from out-of-time view

ios/MullvadREST/RESTNetworkOperation.swift, ios/MullvadREST/RESTTransport.swift, ios/MullvadREST/RESTTransportStrategy.swift, ios/MullvadRESTTests/TransportStrategyTests.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/TransportMonitor/TransportMonitor.swift, ios/PacketTunnel/TunnelTransportProvider.swift, ios/TunnelProviderMessaging/URLRequestProxy.swift
The scope of this ticket has slightly changed, this PR introduces a `TransportStrategy` that defines when to use a direct URLSession for reaching the API, or when to proxy requests via Shadowsocks.
At this moment, the selection of the Shadowsocks relay endpoint is still random, and the API is still hardcoded in the rust library.
Those modifications will come after we rework how the `AddressCache` works in IOS-149
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4641)
=> Cache known good api mode ios 133

ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/App/TunnelCoordinator.swift, ios/MullvadVPN/Notifications/UI/NotificationController.swift, ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
1. Move `NotificationController` higher into `RootContainer`.
2. Make it possible to pin notification controller to a custom layout guide so that it doesn't overflow the entire split view controller but only a primary side.
3. Generate notifications from `FormSheetPresentationController` to tell `AppCoordinator` when presentation changes from formsheet to fullscreen and vice-versa.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4661)
=> Add notification controller into root container IOS-139

.github/workflows/verify-locked-down-signatures.yml
We needed to remove part of the github workflow in order to fix a CVE, this PR investigates what the problems that appear from this are and what the best fix is.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4664)
=> Investigate and potentially fix CI cve fix

gui/changes.txt, ios/Assets/changes.txt
The instructions for making items specific to a platform was removed from the desktop template when the iOS one was added. I beleive that was a mistake and that it should have been removed from the iOS template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4673)
=> Fix changes.txt templates

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Containers/Root/HeaderBarView.swift, ios/MullvadVPN/Containers/Root/RootConfiguration.swift, ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Notifications/InAppNotificationDescriptor.swift, ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift, ios/MullvadVPN/Notifications/NotificationManager.swift, ios/MullvadVPN/Notifications/NotificationProvider.swift, ios/MullvadVPN/Notifications/NotificationProviderIdentifier.swift, ios/MullvadVPN/Notifications/NotificationProviderProtocol.swift, ios/MullvadVPN/Notifications/NotificationResponse.swift, ios/MullvadVPN/TunnelManager/TunnelBlockObserver.swift
Sometimes the device header disappears in the no time left view, possibly in others. This obviously shouldn't happen.
- Trigger device name in app banner in just case user state is changed from logged out to logged in
- Invalidate itself for hiding banner when user goes from logged in into logged out or revoked
- Take notification identifiers into enum
-  Fix spelling mistakes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4666)
=> Sometimes the device/time-left header disappears

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/dimensions/Dimensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/TypeScale.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/typeface/Typeface.kt
This is an attempt to add text styles and dimensions in a way to does not use xml but instead using something more native to compose.
It uses `List` as a proof of concept.
Also it tries to migrate away from using static colors and instead use colors defined in the theme. This is enable support for things like dark/light theme in the future.
**Dimensions**
Dimensions are setup in a data class called dimensions. There's also a default implementation called `defaultDimensions`. The dimensions file that is actually used is called `Dimen` and that can depending on what configurations we want to use use different implementations of `Dimensions`. This should be more or less be similar to how `dimensions.xml` works. If we feel lik it we can support for more configurations in the future. …
=> Add text style and dimensions to use in compose

mullvad-types/src/relay_constraints.rs
The mode was incorrectly named `udp2-tcp`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4701)
=> Fix incorrect obfuscation mode name in CLI

CHANGELOG.md, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SettingsFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/VpnSettingsFragment.kt, android/app/src/main/res/layout/settings.xml
Change the split tunneling menu entry to the settings fragment
Fixes: DROID-137
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4702)
=> Move split tunneling to the settings

mullvad-version/src/main.rs
This PR aims to fix the automatically generated version code which is used to build the Android app.
The current behavior sets the last two digits of the version code to `00` for stable builds, which results in the stable code being lower than the beta code and therefore preventing upgrades beta->stable:
```
Version: 2021.34-beta5
versionCode: 21340005
Version: 2021.34
versionCode: 21340000
```
This fix sets the last two digits to `99` for stable builds which is the same used prior to using `mullvad-version` to generate the version code:
```
Version: 2021.34-beta5
versionCode: 21340005
Version: 2021.34
versionCode: 21340099
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mul …
=> Fix stable Android version code

.github/workflows/daemon.yml
To relive ourselves of situations like [these](https://github.com/mullvad/mullvadvpn-app/actions/runs/5007859154/jobs/8975025001#step:11:1263), I've set the `CARGO_TARGET_DIR` to `C:\cargo-target`. Otherwise, our Windows runner runs out of space on the `D:\` drive and it fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4713)
=> Use C drive for build artifacts in CI

dist-assets/pkg-scripts/postinstall, dist-assets/pkg-scripts/preinstall
This PR updates the macOS installer scripts to run the new CLI before blocking the internet during upgrades. We hope that it may force macOS to check the validity of the certificate.
Fixes DES-210.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4699)
=> Run new CLI before stopping old daemon on macOS

android/translations-converter/src/android/plurals.rs, android/translations-converter/src/android/string_value.rs, android/translations-converter/src/android/strings.rs, android/translations-converter/src/gettext/msg_string.rs, android/translations-converter/src/main.rs
Just a small PR to make all crates deny the `rust_2018_idioms` rule and honor it.
This is a cherry-pick from the stale old `stricter-rustc-flags` branch that I now aim to make something useful out of. I believe I might get somewhere if I break it up into some smaller chunks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4678)
=> Fix Rust 2018 idioms in `translations-converter`

mullvad-cli/src/format.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/net.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-types/src/net/mod.rs
With this change, `mullvad status -v` will print the name of the tunnel interface when the app is in a connected state. This PR aims to implement the feature requested in #4676.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4726)
=> Add tunnel interface to output of `mullvad status -v`

ios/MullvadVPN/Containers/Root/HeaderBarView.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift
1. Hide brand name in header bar when buttons container frame intersects with it. This is implemented by using a simple frame intersection check and should work universally in RTL and LTR environment from what I understand.
2. Refactor header bar a bit by using standard spacing where possible, we had 7pt, 8pt and 9pt spacing hardcoded which is roughly speaking about what standard spacing is (8pt) so it's reasonable to use that instead of hardcoded constants. A few constants were moved into `UIMetrics` as well.
3. Remove calls to `translatesAutoresizingMaskIntoConstraints`. This is not needed when using `addConstrainedSubviews` or when using `UIStackView`.
4. Many `UIView` subclasses support default `init()` initializer which has the same effect as `init(frame: CGRect.zero)`. Replaced as …
=> Hide brand name in header bar when buttons overlap it IOS-166

ios/MullvadVPN/Coordinators/App/TunnelCoordinator.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
If the app has no network access and the user disconnects the tunnel, the "Secure my connection" and "Switch location" buttons will be disabled until network access is restored. This puts the user in a vulnerable state and leaking traffic. To make sure the user understands this and does not accidentally disconnect, a new alert will be shown before disconnecting the tunnel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4709)
=> Add alert if user disconnects when there's no connectivity

build.sh, mullvad-daemon/Cargo.toml
I have realized that our `build.sh` for building the desktop app builds more Rust code than needed. It builds the entire workspace. Historically this has not really mattered much at all since basically all Rust crates/code was used on desktop anyway. But that is becoming less and less true. For example the Android `translations-converter` is one binary we don't need. And recently added is the `ios/MullvadREST/shadowsocks-proxy` which we don't need on desktop. The dependencies overlap a lot, so the actual **compile** part is not shortened a lot by not building them. But each binary that we need to **link** cost significant amount of time.
By specifying just what we need to build here, we save a bunch of time. On my laptop, when building in debug mode, the `cargo build ...` part goes down …
=> Only build the Rust artifacts we need on desktop

ios/MullvadREST/ShadowSocksProxy.swift, ios/MullvadREST/URLSessionTransport.swift, ios/MullvadREST/shadowsocks-proxy/include/shadowsocks.h, ios/MullvadREST/shadowsocks-proxy/src/bin/run.rs, ios/MullvadREST/shadowsocks-proxy/src/bin/run_unsafe.rs, ios/MullvadREST/shadowsocks-proxy/src/ffi.rs, ios/MullvadREST/shadowsocks-proxy/src/lib.rs, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/TransportMonitor/TransportMonitor.swift, ios/PacketTunnel/PacketTunnelProvider.swift, ios/PacketTunnel/TunnelTransportProvider.swift
This PR removes hardcoding the API address in the Shadowsocks proxy crate, and instead gets it at runtime from the `AddressCache` in the Swift part, and forwards it to the Rust part
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4722)
=> Pass the API endpoint to Shadowsocks instead of hardcoding it

mullvad-daemon/Cargo.toml
`cargo build -p mullvad-daemon` fails without this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4739)
=> Add derive feature for clap in daemon

ci/buildserver-build.sh
The commit message says it all :shrug:
Fixes DES-194 :package:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4735)
=> Exclude `android/` and `ios/` tags from desktop builds

env.sh, gui/package-lock.json, gui/package.json, gui/tasks/distribution.js, wireguard/build-wireguard-go.sh
Previously, this was only possible on Intel Macs.
Fixes DES-136.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4732)
=> Enable universal builds on M1/M2 Macs

ios/MullvadVPN/Extensions/NSLayoutConstraint+Helpers.swift, ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift, ios/MullvadVPN/UI appearance/UIColor+Palette.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift
1. Update constraints that pin the body label to the trailing layout margin when no action provided, otherwise pin the trailing edge to the leading edge of action button.
2. Add helper to store constraint into array `NSLayoutConstraint.store(into: inout [NSLayoutConstraint])` that provides chained call semantics.
3. Modernize constraint creation by using `addConstrainedSubviews` and autolayout helpers we use to reduce amount of boilerplate code.
4. Add missing trailing anchor for title label.
5. Set action button opacity to 80%
6. Add system spacing button the body label and action button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4695)
=> Hide action button when no action provided in notification banner IOS-168

gui/src/renderer/components/TooManyDevices.tsx
The icon was previously 24x24 when it should be 18x18.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4681)
=> Make close icon smaller in too many devices view

gui/src/renderer/components/OpenVpnSettings.tsx, gui/src/renderer/components/WireguardSettings.tsx
The multihop and bridge mode dialogs that warns the user about latency had the info icon when it should have the alert icon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4683)
=> Change dialog type to caution for bridge mode and multihop warnings

windows/driverlogic/driverlogic.vcxproj, windows/libshared/src/libshared/libshared.vcxproj, windows/nsis-plugins/src/cleanup/cleanup.vcxproj, windows/nsis-plugins/src/log/log.vcxproj, windows/nsis-plugins/src/pathedit/pathedit.vcxproj, windows/nsis-plugins/src/registry/registry.vcxproj, windows/nsis-plugins/src/string/string.vcxproj, windows/nsis-plugins/src/tray/tray.vcxproj, windows/winfw/src/extras/cli/cli.vcxproj, windows/winfw/src/winfw/winfw.vcxproj
Using the latest standard causes STL modules to be built, which doesn't play nicely with precompiled headers. Let's disable this for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4752)
=> Set explicit C++ standard to C++20

.github/workflows/android-audit.yml
This PR aims to change when the gradle owasp audit check runs. Rather than running on any changes in the android sub-tree, it will now trigger daily and on changes to the gradle lockfile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4754)
=> Trigger audit check daily and on lockfile changes

Cargo.lock
Just upgrading the dependency to fix [RUSTSEC-2023-0041](https://rustsec.org/advisories/RUSTSEC-2023-0041). I don't think this could have affected our users to any serious degree, so not going to mention in the changelog unless there is good reason to. Our DNS resolver should only be accessible on localhost anyway. So worst case a local program could have DoSed the local machine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4761)
=> Upgrade trust-dns-server to avoid RUSTSEC-2023-0041

ios/MullvadTypes/RelayConstraints.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Extensions/UITextField+Appearance.swift, ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift, ios/MullvadVPN/UI appearance/UIColor+Palette.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesDataSourceDelegate.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesInteractor.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift, ios/MullvadVPN/View controllers/SelectLocation/SelectLocationViewController.swift, ios/MullvadVPN/View controllers/Settings/SelectableSettingsCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift, ios/MullvadVPN/View controllers/Settings/SettingsInputCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsInteractorFactory.swift, ios/MullvadVPN/View controllers/Settings/SettingsStaticTextFooterView.swift, ios/MullvadVPNTests/RelaySelectorTests.swift, ios/RelaySelector/RelaySelector.swift
Allow users to select which port to connect to the WireGuard server over. On mobile the port is currently chosen randomly as the port constraint is set to Any and we don't expose any way to change it.
Mimic desktop port selection. It should be possible to select between "Automatic", a few hardcoded known good ports, and custom where the user enters what port they want to use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4656)
=> Add custom port selection to settings

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Type.kt
1. This PR simplifies the handling of typography within the Android code by removing the need for hard coded values such fontsize, fontweight, and fontfamily.
2. It is the start of the collaborative project between me and Jonatan for Hack day!
-----
Note: This **_only_** changes the components within the Android code that uses Material3, and most components within the code uses Material 1 or 2. For instance many imports are of:
`import androidx.compose.material` instead of `import androidx.compose.material3`.
So the typography changes will not affect the former components, they would need to be changed or the theme in `Theme.kt` would need to be changed to `import androidx.compose.material.MaterialTheme` instead of `import androidx.compose.material3.MaterialTheme`. 
However, this might …
=> Add Mullvad VPN typography font styles

mullvad-cli/src/cmds/status.rs, mullvad-cli/src/cmds/tunnel_state.rs
If the user is *not* logged in to an active account, we will from now on issue a warning if they try to connect to a relay using `mullvad-cli`. Intention is to improve upon the feedback in https://github.com/mullvad/mullvadvpn-app/issues/1112.
Previously, we would start blocking all internet traffic. This is well and good. The issue is that this happened silently, so the user would be unaware about the current status of their connection without running further CLI commands or checking the GUI. We might as well try to help the user if they run into this frustrating edge case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4767)
=> Improve UX of CLI when tries to connect while not logged in

ios/MullvadTypes/RelayConstraints.swift
The addition of port field broke backward compatibility with the existing serialized data. A custom `init(from decoder: Decoder) throws` is implemented to handle that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4773)
=> Add custom deserialiser for RelayConstraints

talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_go.rs
The old WireGuard endpoint socket is discarded when the WireGuard config is updated. This means we need to call `VpnService::protect` on the new socket to prevent it from be routed via the tunnel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4776)
=> Exclude tunnel sockets after PSK exchange

.github/workflows/verify-locked-down-signatures.yml, ci/verify-locked-down-signatures.sh
The locked-down CI script will complain that a single commit modifies a bunch of locked down files at the same time. The commit it complains about isn't responsible for modifying these and it likely has to do with there being a folded commit for the entire git history.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4766)
=> Investigate CI issue where it complains that folded commit is unsigned

ios/MullvadLogging/Logging.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Supporting Files/Info.plist, ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift, ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift, ios/PacketTunnel/Info.plist, ios/PacketTunnel/PacketTunnelProvider.swift, ios/Shared/ApplicationConfiguration.swift, ios/Shared/ApplicationTarget.swift
1. Add `ApplicationTarget` that can be used to query bundle identifier or log file `URL` (via `ApplicationConfiguration`)
2. Store main bundle identifier in `Info.plist`s under `MainApplicationIdentifier` key to be able to access main bundle identifier without making additional assumptions. Note that `Bundle.main` within packet tunnel points to the packet tunnel's bundle and not the UIKit app bundle.
3. Access shared container URL via `ApplicationConfiguration.containerURL` instead of `FileManager` in code where it's strictly not necessary to do so in any other way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4779)
=> Formalize application targets IOS-194

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/BackgroundTask.swift, ios/MullvadVPN/Supporting Files/Info.plist, ios/Shared/ApplicationConfiguration.swift
1. Add `BackgroundTask` to formalize all background tasks that the app defines.
2. Use `$(APPLICATION_IDENTIFIER)` variable supplied via `Configurations/Base.xcconfig` and in place of hardcoded string `net.mullvad.MullvadVPN` in `BGTaskSchedulerPermittedIdentifiers` key in `Info.plist`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4780)
=> Formalize background tasks IOS-195

ios/MullvadVPN/Coordinators/App/SelectLocationCoordinator.swift
Selecting a relay in location selection view overwrites whatever port selection has been made prior. We need to update current relay constraints rather than overwriting them with new.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4795)
=> Prevent overwriting relay constraints when selecting a relay location

ios/MullvadVPN/Classes/CustomAlertViewController.swift, ios/MullvadVPN/Operations/PresentAlertOperation.swift
When the number of device is exceeded and we are trying to revoke a device from the `Too many devices view`,nothing happens.
after checking the code I figured out we are removing the buttons handlers in `viewDidDisappear` while after dismissing the controller(the `viewDidDisappear ` will be called by view lifecycle sooner than dismiss's `completion `) we are looking for them at `completion`, therefore It causes the button callbacks never be accessible.
for solving the problem I did this step :
- removing handlers at `dismiss` callback
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4796)
=> When trying to revoke a device from the `Too many devices view`, it doesn't happen 

CHANGELOG.md, mullvad-cli/src/cmds/account.rs
`mullvad account get` will now print the old account number, even when the device has revoked. A minor QOL thing for the CLI users out there.
Previously:
```
$ mullvad account get
The current device has been revoked
```
Now:
```
$ mullvad account get
The current device has been revoked
Mullvad account: xxxxxxxxxxxxxxxx
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4800)
=> Print the old account number even if device is revoked

CHANGELOG.md, mullvad-cli/src/cmds/bridge.rs, mullvad-cli/src/cmds/relay.rs
This PR merges the functionallity of `mullvad relay set hostname` into the `mullvad relay set location` command.
The `relay set location` command used to require the full format of `<COUNTRY> <CITY> <HOSTNAME>` to select a specific relay, while `relay set hostname`  only received a hostname and figured the country and city out. 
Now, the arguments to `relay set location` are *either* a geographical location or a hostname: `relay set location <COUNTRY> <CITY> <HOSTNAME> | <HOSTNAME>` . The command will keep working as it used to, while being a bit smarter about hostnames.
E.g., here I select one of the relays in Gothenburg:
```bash
$ mullvad relay set location se-got-wg-004
Relay constraints updated
$ mullvad status
Connected to se-got-wg-004 in Gothenburg, Sweden
```
This logic also …
=> Join `set location` and `set hostname` into one command

dist-assets/pkg-scripts/postinstall, dist-assets/pkg-scripts/preinstall
Closing the GUI shows the disconnected and unsecure notification and the tray icon switches to the unlocked state when it loses the connection to the daemon. For versions where the GUI don't disconnect when killed (`2022.5` and later) we want to kill the GUI first, but we want to keep it like it currently is when upgrading from older versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4799)
=> Close GUI before daemon is killed when upgrading app version

build.sh
The arguments here were in the wrong order, so the read would not work. Since this has been like this since forever, obviously we don't execute this code path very much :sweat_smile: But now I fix it so it's possible to do `./build.sh --sign` without running it from `ci/buildserver-build.sh`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4811)
=> Fix argument to `read` in build.sh that did not work

ios/MullvadVPN/TunnelManager/SetAccountOperation.swift
We use retry strategy when creating new device during log-in. In some cases it's possible that the server managed to process the request but the client hasn't been able to receive the response (timeout error). When that happens, the next retry attempt usually results in `pubkey-in-use` error since the same key that we attempt to push is already assigned to the device that had been created during the previous attempt.
In order to recover from that error, this PR introduces additional fetch request that attempts to find the previously created device by public key.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4820)
=> Handle pubkey-in-use error IOS-204

Cargo.lock, mullvad-api/Cargo.toml, mullvad-cli/Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-management-interface/Cargo.toml, mullvad-management-interface/src/types/conversions/account.rs, mullvad-management-interface/src/types/conversions/device.rs, mullvad-management-interface/src/types/conversions/wireguard.rs, mullvad-types/Cargo.toml
Fix time zone being ignored on Android, incorrectly outputting UTC timestamps. A fix is included in `chrono >= 4.25`.
This issue is recognized in `chrono`'s issue tracker: https://github.com/chronotope/chrono/issues/922, and the fix seems to be to extract timezone info from a tzdata file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4809)
=> Fix time zone being ignored on Android

building/linux-container-image.txt
This uses the newly produced build container. Bringing Rust up from 1.68.1 to 1.70.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4812)
=> Bump Linux build container to mullvadvpn-app-build:cf1a3c951

gui/locales/messages.pot, gui/src/renderer/components/AppRouter.tsx, gui/src/renderer/components/ExpiredAccountAddTime.tsx, gui/src/renderer/components/HeaderBar.tsx, gui/src/renderer/components/RedeemVoucher.tsx, gui/src/renderer/components/Settings.tsx, gui/src/renderer/components/SettingsStyles.tsx, gui/src/renderer/lib/routes.ts, gui/src/shared/account-expiry.ts, gui/src/shared/date-helper.ts, gui/src/shared/notifications/close-to-account-expiry.ts, gui/test/e2e/installed/state-dependent/login.spec.ts, gui/test/e2e/mocked/settings.spec.ts, gui/test/unit/date-helper.spec.ts
This PR makes further improvements to the presentation of device and account info. The account view is now accessed from a button in the header bar and the device name and time left is displayed in the header bar under the logo.
To accomplish this I also refactored the time formatting functions to be a bit simpler. We still supported formatting time that was in the past which hasn't been necessary since we removed the wireguard key view.
Fixes DES-137, DES-139, DES-140.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4792)
=> Add device and account to header

.github/PULL_REQUEST_TEMPLATE.md
In an attempt to help promote testing, I've changed the template to nudge people to include instructions on how to test their changes in their PR description.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4815)
=> Update PR template to recommend adding testing instructions

CHANGELOG.md, talpid-openvpn/src/process/openvpn.rs
Make the logs less verbose and easier to read by silencing 'replay attack' warnings.
There are lots of false positives showing up in regular UDP connections, and since we don’t act on potential replays or warn our users (it’s pretty hidden in the logs) they don’t really serve much purpose to be there. The warning should not pose any threat to the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4830)
=> Silence OpenVPN 'replay attack' warnings

gui/test/e2e/utils.ts
nit: Change the type signature of `currentRoute` to return a `string` rather than `void`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4838)
=> Fix type signature of function in GUI testing utils

gui/test/e2e/installed/state-dependent/too-many-devices.spec.ts, gui/test/e2e/utils.ts
Fix a failing end-to-end test that was caused due to missing navigation events.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4842)
=> Fix `too-many-devices` end-to-end test

.github/workflows/cargo-vendor.yml
Add a CI job for checking if `cargo vendor` works. Since it's part of cargo upstream there is no need to install anything except the Rust toolchain. Vendoring is nothing we use at Mullvad ourselves. But it can help third party package maintainers to build and package stuff.
My main motivation for adding this is the dependency tree cleanliness checks it implicitly imposes. Vendoring will fail if a dependency comes from multiple sources. Something we have had an issue with in for example version `2023.4` (see linked issue)
I think it's enough to run this on a single platform. It looks like `cargo vendor` on Linux also vendors macOS and Windows specific dependencies. So hopefully this very simple CI job should be enough.
Fixes DES-264
Fixes #4848
- - - …
=> Add CI job for vendoring Rust dependencies

.github/workflows/cargo-audit.yml
I found there are multiple actually updated dedicated Github Actions for Rust dependency auditing. The ones I found so far are: https://github.com/rustsec/audit-check and https://github.com/actions-rust-lang/audit. The latter seems to have a bit more configurability, but the former comes from the official `rustsec` organization, so I will try that out first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4852)
=> Use rustsec's own github action to run cargo audit

.github/workflows/cargo-audit.yml
Fixes the temporary "flaw" introduced in 37ffc541b in order to test the CI.
The action did not run at 12:00 UTC as I expected it to. But when I manually triggered it via workflow_dispatch it did create an issue, so that part works.
Fixes #4854
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4855)
=> Revert the temporary test on the cargo audit CI

Cargo.lock, deny.toml, ios/MullvadTransport/shadowsocks-proxy/Cargo.toml
We still had clap 3 in our dependency tree. Only because of a build dependency in the iOS crate. Afaict this is not at all needed. In the one other place where we depend on `cbindgen` we disable default features and get rid of clap 3.
This in turn removes another transitive link to the unwanted crate `atty`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4850)
=> Remove default features from cbindgen to get rid of clap 3

Cargo.lock, talpid-openvpn/Cargo.toml, talpid-types/Cargo.toml, talpid-types/src/net/wireguard.rs
I just saw that this dependency had some updates. Nothing we really need. But it's nicer to be on a release candidate compared to a `pre` release. We can also rely on the library to pick a suitable CSPRNG instead of having us do that.
The zeroize part is not related to the upgrade. I just felt it was nice to add. It's good practice to clear private keys from memory as much as possible.
This upgrade removes the clamping of the private key material used for WireGuard. See [`x25519-dalek` changelog](https://github.com/dalek-cryptography/x25519-dalek/blob/main/CHANGELOG.md#200-rc3). We don't believe this should hurt in any way:
* Public keys generated with the new code will still be clamped in the pubkey generation code
* Old private keys read from `device.json` will still work, they are …
=> Upgrade `x25519-dalek` to `2.0.0-rc.3`

gui/package.json, gui/src/renderer/components/ConnectionPanel.tsx, gui/test/e2e/installed/playwright.config.ts, gui/test/e2e/installed/state-dependent/disconnected.spec.ts, gui/test/e2e/installed/state-dependent/login.spec.ts, gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts, gui/test/e2e/mocked/tunnel-state.spec.ts, gui/test/e2e/shared/tunnel-state.ts
The tunnel state tests included a few race conditions which led to them failing every now and then. This PR fixes those race conditions.
I've also made sure the playwright config is used when running the tests with `npm` and improved the config a bit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4857)
=> Fix app tunnel state tests

Cargo.lock
The upgrade is not important for us, since we don't target RustyHermit. But it's needed to keep `cargo audit` silent, and it's good hygiene.
The hermit-abi crate did not have a changelog. But the change is just a ffi function linking name change
https://github.com/hermitcore/rusty-hermit/issues/436
Fixes #4869
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4870)
=> Upgrade hermit-abi to avoid yanked crate

ios/CHANGELOG.md
Add missing changelog entry for WireGuard port selection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4865)
=> Add WireGuard port selection to settings changelog

CHANGELOG.md, gui/package-lock.json, gui/package.json, gui/src/main/user-interface.ts
This PR upgrades Electron from 23.2.0 to 25.2.0. In the latest stable release we had a few issues related to the Electron version. At least the many tray icon issues seem to be improved in 25.2.0. I've also updated 
Changelog for major versions:
https://github.com/electron/electron/releases/tag/v24.0.0
https://github.com/electron/electron/releases/tag/v25.0.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4879)
=> Update Electron to 25.2.0

docs/relay-selector.md, mullvad-relay-selector/src/lib.rs
The relay selector docs didn't have a notion of an obfuscator, so I updated them.
I also found that a public method in the relay selector module was used solely in tests, so I made it private and only compiled for tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4834)
=> Update relay selector docs to include udp2tcp

ios/MullvadVPN/Containers/Root/HeaderBarView.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift, ios/MullvadVPN/Views/IncreasedHitButton.swift
Since the settings and account buttons both reside in a stackview, their increased touch targets are limited by the size of the stackview. This should be reworked so that both buttons still get a 44x44 pixel touch target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4871)
=> Fix increased touch areas for buttons in header bar view

Cargo.lock, talpid-core/Cargo.toml, talpid-openvpn/Cargo.toml, talpid-openvpn/src/process/openvpn.rs
Upgrades `duct` to latest version. This makes it use `os_pipe ^1` and `shared_child ^1` instead of `0.x` versions.
Then upgrade `os_pipe` as direct dependency also, to end up with the same version as duct (latest). Keeps our dependency tree tidier and brings us up to the latest versions.
Also found we had one unused instance of `os_pipe`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4876)
=> Upgrade duct and os_pipe

ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/View controllers/ChangeLog/ChangeLogViewController.swift
in some views like `Change log` we don't aim to show in-app notification bar.for excluding some views we've decided to add the flag `prefersNotificationBarHidden` into `RootContainment` protocol  that defines whether the container prefers to hide that or not.
for preventing from reworking the default value for the flag was set `false`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4835)
=> Hide notification bar at change log

ios/MullvadREST/ServerRelaysResponse.swift, ios/MullvadTransport/TransportProvider.swift, ios/MullvadTypes/RelayConstraints.swift, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPNTests/RelayCacheTests.swift, ios/MullvadVPNTests/RelaySelectorTests.swift, ios/PacketTunnel/PacketTunnelProvider.swift, ios/RelaySelector/RelaySelector.swift
This PR introduces the ability for `RelaySelector` to select a Shadowsocks bridge that is filtered using the User's prefered relay chosen via the UI.
Due to how we propagate `relayConstraints` in the application, as long as the users do not choose a relay, a Shadowsocks bridge close to Sweden will be chosen by default.
I tried to implement filtering by Haversine distance (as the desktop clients do) but I decided to do that in a future work instead as to keep the PR impact minimal for `RelaySelector` 
How to test ?
This will only affect Shadowsocks bridges, so it's not immediately obvious how to test this. 
I would recommend forcing Shadowsocks transports to be used by default (set the `connectionAttempts` to `1` in `TransportStrategy`) and then select a Relay.
Due to how we cache the …
=> Enable Shadowsocks bridges selection via RelaySelector

Cargo.lock, Cargo.toml, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/TunnelObfuscationTests.xcscheme, ios/TunnelObfuscation/Info.plist, ios/TunnelObfuscation/TunnelObfuscation.h, ios/TunnelObfuscation/TunnelObfuscator.swift, ios/TunnelObfuscation/module.private.modulemap, ios/TunnelObfuscation/tunnel-obfuscator-proxy/Cargo.toml, ios/TunnelObfuscation/tunnel-obfuscator-proxy/build.rs, ios/TunnelObfuscation/tunnel-obfuscator-proxy/include/tunnel_obfuscator_proxy.h, ios/TunnelObfuscation/tunnel-obfuscator-proxy/src/ffi.rs, ios/TunnelObfuscation/tunnel-obfuscator-proxy/src/lib.rs, ios/TunnelObfuscationTests/TCPConnection.swift, ios/TunnelObfuscationTests/TCPListener.swift, ios/TunnelObfuscationTests/TCPUnsafeListener.swift, ios/TunnelObfuscationTests/TunnelObfuscationTests.swift, ios/TunnelObfuscationTests/UDPConnection.swift
This PR adds the `TunnelObfuscator.framework` in both targets so it can be found when loading the network extension.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4890)
=> Add bindings for tunnel obfuscator and a test

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Containers/Root/HeaderBarView.swift, ios/MullvadVPN/Containers/Root/RootConfiguration.swift, ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift, ios/MullvadVPN/Coordinators/App/AccountRedeemingVoucherCoordinator.swift, ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift, ios/MullvadVPN/Coordinators/App/SettingsRedeemVoucherCoordinator.swift, ios/MullvadVPN/Coordinators/App/SetupAccountCompletedCoordinator.swift, ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift, ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift, ios/MullvadVPN/TunnelManager/RedeemVoucherOperation.swift, ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift, ios/MullvadVPN/View controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift, ios/MullvadVPN/View controllers/CreationAccount/Completed/SetupAccountCompletedViewController.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeViewController.swift, ios/MullvadVPN/View controllers/Login/LoginViewController.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherSucceededViewController.swift, ios/Shared/ApplicationConfiguration.swift
this pr enables users to redeem voucher code when they create account through the app.
after pressing `Create account ` on `Login` view, the app is been transmitted to `Welcome` page the shows  `account number`  and `device name` beside some informative data , such as : 
-  more info about device name  can be shown with  ⓘ
- add more credit via redeeming voucher code
- buy more credit via in-app purchase(I didn't work on it yet, just the button is aligned on the UI and I'm gonna work on it for the future PR )
when user is successful to expand the time through redeeming voucher code, the succeeded page with the added time is shown.when user presses `Next` button at the page, a confirmation page is shown to user that is included `Start using the app` that takes him into the app and an …
=> Implement redeeming voucher on creation account

Cargo.toml, ios/MullvadTransport/shadowsocks-proxy/Cargo.toml, ios/TunnelObfuscation/tunnel-obfuscator-proxy/Cargo.toml, mullvad-api/Cargo.toml, mullvad-cli/Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-fs/Cargo.toml, mullvad-jni/Cargo.toml, mullvad-management-interface/Cargo.toml, mullvad-problem-report/Cargo.toml, mullvad-relay-selector/Cargo.toml, mullvad-setup/Cargo.toml, talpid-core/Cargo.toml, talpid-dbus/Cargo.toml, talpid-openvpn-plugin/Cargo.toml, talpid-openvpn/Cargo.toml, talpid-routing/Cargo.toml, talpid-time/Cargo.toml, talpid-tunnel-config-client/Cargo.toml, talpid-tunnel/Cargo.toml, talpid-wireguard/Cargo.toml, tunnel-obfuscation/Cargo.toml
Trying out the `[workspace.dependencies]` functionality of Cargo. It's pretty neat to be able to declare dependencies at the workspace level. Then we only have a single place to bump the version when we upgrade dependencies.
You could argue that we are almost never going to bump tokio. And when we do, it will be such a large re-write anyway that this "optimization" is not important. And that's correct. But there are plenty of other crates that we do upgrade fairly regularly that might benefit more from this. So maybe starting with `tokio` was wrong. For `tonic` it makes more sense. Because we will need to upgrade it (there is already `0.9` out), and there are a bunch of related crates that goes with it. So there is one place to bump all the five crates.
- - - …
=> Use workspace dependencies for Rust

CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrl.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/VersionInfoNotification.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AppVersionCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/UrlCell.kt
Disable click and hide external link icon from App version cell on google play version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4907)
=> Disable App version cell click on release version

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoadingScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt
This PR aims to migrate the header/top bar of the connect/main view to compose.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4912)
=> Migrate connect view header bar to compose

.github/workflows/ios.yml, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme, ios/TestPlans/MullvadVPNApp.xctestplan, ios/TestPlans/MullvadVPNCI.xctestplan, ios/build.sh
The MullvadVPNScreenshot test target only works in the CI environment, or with an install of MullvadVPN that has never been interacted with. 
It's also configured to always run, which takes a lot of time (only to fail), which creates a frustrating development experience.
We should switch to using [test plans](https://developer.apple.com/documentation/xcode/organizing-tests-to-improve-feedback) instead so that we can have a test plan that does not run UI automated tests by default when we are doing daily work on our local machines.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4872)
=> Move tests into test plans

ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift
This PR introduces a custom `init(from decoder: Decoder)` in `StoredAccountData` that doesn't fail if the `isNew` flag is missing. 
When upgrading from the current release (2023.3) or lower, this will lead to a log out / reset of the settings when upgrading the app.
This PR fixes this issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4918)
=> Fix the settings being reset when upgrading from 2023.3 or lower

.github/workflows/cargo-audit.yml, Cargo.lock, deny.toml
We have long ignored [`RUSTSEC-2021-0145`](https://rustsec.org/advisories/RUSTSEC-2021-0145.html) in our `cargo-audit.yml` action. And even if our app is not really affected by this vulnerability at all, it has been  a bit irritating. I have been somewhat on the hunt to get rid of `atty` for a long while. Opening issues on some of our dependencies that in turn depend on `atty`. And finally we have reached the point where the [last dependency using it](https://github.com/daboross/fern/issues/113) has released an upgraded version, switching to `is-terminal`.
I now ban `atty` from our dependency tree completely via `deny.toml`, so we don't accidentally add it again.
- - - …
=> Remove atty dependency

Cargo.lock
We have loads of dependencies where we pull in multiple versions. It's kind of impossible to not have that in a mid-sized Rust project. But at least some work can be put into somewhat reducing the numbers. This PR upgrades some of our dependencies.
The result is that we at least get rid of one (out of four!) versions of `windows-sys` from our dependency tree. We also gain and lose some other dependencies. The net change is fewer dependencies at least.
I also created a PR on our only dependency pulling in `windows-sys 0.36`. When that is merged and released we might get rid of another instance. https://github.com/zonyitoo/tokio-tfo/pull/6
- - - …
=> Reduce duplicate windows-sys versions

Cargo.lock, mullvad-api/Cargo.toml
I saw `rustls-pemfile` had a significant version bump available. So I went ahead and upgraded it. Also saw that other rustls related crates (including rustls itself) had some semver incompatible upgrades available. So I went ahead and upgraded all of them.
I usually check changelogs when doing semver incompatible upgrades. Sadly I have a hard time checking what changed in `tokio-rustls` due to https://github.com/rustls/tokio-rustls/issues/8. But I suppose it should be fine. I downloaded both packages from crates.io and compared the sources there. I did not immediately see anything sticking out.
I have tried this upgrade on Linux, Windows and macOS quickly and the app seems to work.
- - - …
=> Upgrade rustls related crates

Cargo.lock, mullvad-daemon/Cargo.toml, mullvad-daemon/src/migrations/mod.rs, mullvad-problem-report/Cargo.toml, mullvad-problem-report/src/lib.rs
Ironically the `dirs`-fork `dirs-next` is unmaintained, but the original is maintained :sweat_smile: 
So this PR migrates back to `dirs`. There is no direct win or benefit for our app in doing this. Just some healthy cleanup/dependency management. One positive thing is that we get rid of one link to the unmaintained `winapi` crate. One tiny step closer towards getting it out of our dependency tree.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4941)
=> Replace unmaintained dirs-next with maintained dirs

Cargo.toml, mullvad-cli/Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-paths/Cargo.toml, mullvad-problem-report/Cargo.toml, talpid-core/Cargo.toml, talpid-openvpn-plugin/Cargo.toml, talpid-openvpn/Cargo.toml, talpid-platform-metadata/Cargo.toml, talpid-routing/Cargo.toml, talpid-tunnel-config-client/Cargo.toml, talpid-tunnel/Cargo.toml, talpid-windows-net/Cargo.toml, talpid-wireguard/Cargo.toml
Sort of a continuation of #4902. `windows-sys` is one of those dependencies that we depend in in a massive amount of crates, but we really only ever want to pull in a single version, and there are semver incompatible releases fairly often. So it makes a lot of sense to make this a workspace dependency. Will making upgrading to version `0.48` and later versions way easier later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4943)
=> Move windows-sys to a workspace dependency

Cargo.lock, talpid-core/Cargo.toml, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs
As part of my dependency cleanup/upgrade spree today I found this little possible improvement. So we used `cfg_if!` macro where we could easily get by without it. I'd argue the code is better now, and we have one dependency less to clobber up our `Cargo.toml` files.
Why is it better? After macro evaluation the code previously looked like this:
```rust
// On Android:
Ok(()) => {
self.disconnect(shared_values, AfterDisconnect::Reconnect(0))
}
// On desktop:
Ok(()) => {
SameState(self.into())
}
```
After this PR the code after macro evaluation looks like this (the only thing different between Android and non-Android is the true/false constant:
```rust
Ok(()) => {
if true/false {
self.disconnect(shared_values, AfterDisconnect::Reconnect(0))
} else {
SameState(self.into())
}
}
```
This might …
=> Remove cfg-if and use regular cfg! macro

android/docker/Dockerfile
Bumping the container JDK is the first step of migrating to newer versions of the Android Gradle Plugin including Gradle and Kotlin.
Also updates `ca-certificates-java` since the jdk installation would fail otherwise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4948)
=> Bump container jdk to 17

Cargo.toml, mullvad-api/Cargo.toml, mullvad-cli/Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-management-interface/Cargo.toml, mullvad-relay-selector/Cargo.toml, mullvad-types/Cargo.toml, talpid-core/Cargo.toml, talpid-wireguard/Cargo.toml
I noticed today that if I do `cd talpid-core; cargo build` it would fail. Because there is a difference between building the entire workspace and building one crate. `talpid-core` depend on the `clock` feature of `chrono` but did not specify it. This is a regression due to #4938.
This PR moves `chrono` to a workspace dependency. This eliminates the need to repeat `default-features = false` way too many times. We probably only ever want one version of `chrono` in this workspace anyway. And the PR also of course adds the `clock` feature to `talpid-core`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4950)
=> Make chrono a workspace dependency and fix features

Cargo.lock, android/translations-converter/Cargo.toml, android/translations-converter/src/gettext/messages.rs, android/translations-converter/src/gettext/parser.rs, android/translations-converter/src/gettext/plural_form.rs
On my dependency excursion lately I found out that we use `derive_more` in `translations-converter` to derive the standard `Error` macro for us. We do the same but with the `err_derive` crate everywhere else. So I figured if I migrate this tool to also use that things would be more uniform and we would drop a few dependencies along the way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4954)
=> Migrate translation-converter to err_derive

Cargo.lock
Thanks to https://github.com/zonyitoo/tokio-tfo/pull/6, we can now get rid of `windows-sys 0.36` also :partying_face: 
This PR does add a new package as well: `socket2 0.5`.. But the net total is still minus five packages. And it was just a matter of time before `socket2 0.5` entered our dependency tree anyway. I have another upcoming PR where I'll start using it directly in our code as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4963)
=> Upgrade tokio-tfo to get rid of windows-sys 0.36

ios/CHANGELOG.md, ios/MullvadREST/RESTAccountsProxy.swift, ios/MullvadREST/RESTRequestFactory.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AutomaticKeyboardResponder.swift, ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift, ios/MullvadVPN/Coordinators/App/AccountDeletionCoordinator.swift, ios/MullvadVPN/Presentation controllers/FormsheetPresentationController.swift, ios/MullvadVPN/TunnelManager/DeleteAccountOperation.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift, ios/MullvadVPN/View controllers/Account/AccountContentView.swift, ios/MullvadVPN/View controllers/Account/AccountViewController.swift, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionContentView.swift, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionInteractor.swift, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionViewController.swift, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionViewModel.swift, ios/MullvadVPN/View controllers/Login/AccountTextField.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift
This PR aims to enable users to delete their accounts, giving them more control over the data they have shared with the service. To achieve this, several steps have been implemented:
1. Addition of an `Account Delete` button on the `Account` view to facilitate the account deletion process.
2. Implementation of a warning message to inform the user about the consequences of deleting their account. This step ensures users are fully aware of the actions they are taking.
3. User verification is required to delete the account. To prevent accidental deletions, users are asked to input the four last digits of their account number. This ensures that the user is making a deliberate decision and minimizes the chances of accidental deletions.
4. Service revocation is performed to notify the backend …
=> Implement account deletion

Cargo.lock
A very tiny insignificant change to our dependency tree. Removes one dependency and adds another one. But we lose one link to `winapi`, which is nice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4968)
=> Upgrade ipconfig (gets rid of one direct dep on winapi)

ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift
We forgot a warning when deprecating iOS 13. This PR fixes the warning by using the Xcode suggested setting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4970)
=> Fix deprecation warning

mullvad-daemon/src/device/mod.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/migrations/v1.rs, mullvad-daemon/src/migrations/v3.rs, mullvad-daemon/src/migrations/v4.rs, mullvad-daemon/src/migrations/v5.rs, mullvad-daemon/src/migrations/v6.rs, mullvad-nsis/build.rs
I found these "extern crate .." statements laying around. They should no longer be needed. Those are from a prehistoric Rust era. Let's remove them! That means the macros are not globally available and we need to import them explicitly. But this is cleaner anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4978)
=> Remove extern crate

Cargo.lock, mullvad-fs/Cargo.toml, mullvad-problem-report/Cargo.toml, mullvad-types/Cargo.toml, talpid-openvpn/Cargo.toml
No issues with version 0.8 as far as I know. But nice to use the latest version. Since it's "stable" in the sense of being >=1.0 it's also a bit more future proof.
Upgrade was trivial. The *only* thing we use from this crate is `uuid::Uuid::new_v4()` (and the to_string + serialization support)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4977)
=> Upgrade uuid from 0.8 to 1.4.1

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableObfuscationView.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt
Fixed: DROID-240, DROID-241
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4951)
=> Fix copy button scaling issue

Cargo.lock, Cargo.toml, mullvad-paths/src/windows.rs, talpid-core/src/dns/windows/auto.rs, talpid-core/src/dns/windows/iphlpapi.rs, talpid-core/src/dns/windows/netsh.rs, talpid-core/src/split_tunnel/windows/driver.rs, talpid-core/src/split_tunnel/windows/path_monitor.rs, talpid-core/src/split_tunnel/windows/volume_monitor.rs, talpid-core/src/split_tunnel/windows/windows.rs, talpid-openvpn/src/wintun.rs, talpid-routing/src/windows/default_route_monitor.rs, talpid-routing/src/windows/get_best_default_route.rs, talpid-routing/src/windows/route_manager.rs, talpid-tunnel-config-client/src/lib.rs, talpid-types/src/error.rs, talpid-types/src/lib.rs, talpid-windows-net/Cargo.toml, talpid-windows-net/src/net.rs, talpid-wireguard/src/wireguard_nt.rs, windows/nsis-plugins/src/cleanup/cleanup.vcxproj
The `windows-sys` ecosystem moves along. A lot of our dependencies already use version 0.48. It was about time to upgrade. I'm not the most familiar with the win32 APIs, but I did my best.
This is mostly constants changing which module they are defined in.
But then it's also the fact that a lot of fallible functions now return `WIN32_ERROR` (== `u32`) instead of the previous `NTSTATUS` (== `i32`). We used this return code to instantiate `io::Error`s. But the constructor `io::Error::from_raw_os_error` takes a `i32` and we now have a `u32`. The simplest thing would just be to cast it. But I don't know if any of these Windows functions could return an error code `> i32::MAX`. If they ever do we will cast it to an invalid value and get a bogus error. That's fine maybe. But I thought it was …
=> Upgrade `windows-sys` to 0.48

Cargo.lock, mullvad-daemon/src/exception_logging/unix.rs, mullvad-daemon/src/exception_logging/win.rs, mullvad-daemon/src/macos_launch_daemon.rs, mullvad-daemon/src/system_service.rs, talpid-core/src/firewall/windows.rs, talpid-routing/src/unix/macos/data.rs, talpid-windows-net/Cargo.toml, talpid-windows-net/src/net.rs, talpid-wireguard/src/logging.rs, talpid-wireguard/src/wireguard_go.rs
This PR is related to #4956. In that PR I managed to actually get rid of a dependency because of the migration. That's not the case in this PR. But it might be nice to be consistent with what FFI types we use. Since Rust 1.64 the `std::ffi` module was expanded with char and int type definitions.
The motivation for this PR is just a tiny cleanup. But it has no known downsides either afaict, so why not.
If you approve of this, I might add to our coding guidelines to prefer `std::ffi` where possible. Most packages will depend on `libc` in one way or another anyway. But why pollute `Cargo.toml` for no reason.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4957)
=> Use C FFI types from `std::ffi` instead of `libc`

Cargo.lock, mullvad-daemon/Cargo.toml
Little follow up to the last commit in #4957. This enables the exception safety of `objc`. I'm not sure if any of the calls we make into the Objective-C runtime actually can throw exceptions. But since the result of them doing so is UB we should definitely be cautious. Performance is not a concern at all here. This code is not performance critical in any way. Stability is way more important.
I wish I could also enable the `verify_message` feature of `objc`. But sadly that makes `msg_send!` enforce message verification on all messages, with no easy way of opting out of a few that does not adhere to the `: Encode` bound. Sadly `NSOperatingSystemVersion` does not implement `Encode` here. It would be possible to manually verify messages or the other way around. But that would be combersome …
=> Enable more safety around calling into the Objective-C runtime

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/MigrationManager/MigrationManager.swift, ios/MullvadVPN/SettingsManager/SettingsManager.swift, ios/MullvadVPN/SettingsManager/SettingsStore.swift, ios/MullvadVPN/SettingsManager/TunnelSettings.swift, ios/MullvadVPN/SettingsManager/TunnelSettingsV2.swift
Refactoring settings part 3, introducing a `MigrationManager` object.
This PR does very little. It takes away the `SettingsManager.migrateStore` function and places it in `MigrationManager.migrateSettings` instead. 
No actual code has been changed, however `SettingsKey` have been moved to `SettingsStore.swift`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4992)
=> Introduce MigrationManager

ios/PacketTunnel/PacketTunnelProvider.swift, ios/PacketTunnel/TunnelMonitor/TunnelMonitor.swift
Regression was introduced 6 months ago in https://github.com/mullvad/mullvadvpn-app/commit/faece927955044c84bee84208c5cd95ddc22944c#diff-c503a02421ff9c96816ad57be865788af955bd8f706ef4ab177eda75158c6745L277-L281. This PR fixes it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4994)
=> Add missing call to completion handler in sleep()

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift, ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift
Part 2 of adding UDP-over-TCP obfuscation.
This PR only creates a UI for the upcoming WireGuard obfuscation settings.
There is no change to the `PreferencesViewModel` yet because I first want to refactor
`TunnelSettingsV2` to become generic in a different pull request.
The same goes for disabling the port selection when obfuscation is turned off.
It will all come in different PRs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4929)
=> Add a UI for wireguard obfuscation preferences

ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift
On older iOS versions (iOS14 tested) the action button in the notification window doesn't hug its own content.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5000)
=> Fix notification action button layout priority on iOS14

Cargo.lock, talpid-openvpn/Cargo.toml, talpid-windows-net/Cargo.toml, talpid-windows-net/src/net.rs, talpid-wireguard/Cargo.toml
I just realized I had this cleanup PR laying around since last week. This had to be done after the `windows-sys 0.48` upgrade, #4966, so that's why it was left behind.
This upgrades all our direct dependencies to `socket2` to the latest version. This in turn allows us to drop one direct dependency to `winapi`. None of this has any practical difference. It's mostly a dependency tree maintenance task.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5006)
=> Upgrade socket2 from 0.4 to 0.5 in our own crates (removes one winapi dependency)

.github/workflows/ios.yml, ios/.swiftlint.yml, ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift, ios/MullvadVPN/View controllers/TermsOfService/TermsOfServiceContentView.swift
This PR adds a  `swiftlint` configuration file, a github action file to run `swiftlint` automatically on new pull requests, and silences some errors, for now, in order to keep having green builds on pull requests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5005)
=> Enable swiftlint ios 182

ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift, ios/MullvadVPN/Coordinators/App/ChangeLogCoordinator.swift, ios/MullvadVPN/Coordinators/Base/ModalPresentationConfiguration.swift
- This PR promotes changelog to modal route and updates `evaluateRoute() -> AppRoute` to return multiple routes that can be presented simultaneously.
- `ChangeLogCoordinator` is promoted to `Presentable`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5012)
=> Promote changelog to modal route IOS-277

ios/MullvadVPN/Coordinators/App/WelcomeCoordinator.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeInteractor.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeViewController.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeInteractor.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift
Since it's possible to pay for account time in many ways in the app, and it's possible to do it on a completely different device, when in the new account flow, the app should try to pro-actively deduce if time has been added. So, whenever it enters a new account flow view, it should fetch new account data from the API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4998)
=> Ensure the app fetches account data whenever it enters the new account flow view

ios/MullvadVPN/Coordinators/App/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/App/ApplicationRouter.swift
This PR makes app router more abstract. 
Changes:
- Add abstractions for describing routes and groups of routes via `AppRouteProtocol` and `AppRouteGroupProtocol` protocols.
- Add generic constraint `<RouteType: AppRouteProtocol>` for `ApplicationRouter` and all related types.
- Add `var modalLevel: Int` requirement for groups (enforced via `AppRouteGroupProtocol`), which is used to restrict modal presentation. Previously it was implemented exclusively via `Comparable`, however Swift provides default imp of that protocol so to avoid confusion, the new requirement was introduced. In addition to that the default impl of `Comparable` is provided and it calls `modalLevel` internally.
- - - …
=> Make app router more abstract 

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/PacketTunnelCore/Pinger/Pinger.swift, ios/PacketTunnelCore/Pinger/PingerProtocol.swift, ios/PacketTunnelCoreTests/Mocks/MockDefaultPathObserver.swift, ios/PacketTunnelCoreTests/Mocks/MockPinger.swift, ios/PacketTunnelCoreTests/Mocks/MockTunnelDeviceInfo.swift, ios/PacketTunnelCoreTests/Mocks/NetworkCounters.swift, ios/PacketTunnelCoreTests/TunnelMonitorTests.swift
This PR adds the very first tests for `TunnelMonitor` and mock objects that can be used to simulate network activity, ping client, and other dependencies:
1. `MockDefaultPathObserver` and `MockNetworkPath` introduced in order to be able to simulate default route changes.
2. `MockPinger` - a mock implementation of a ping client which doesn't do any networking but offers tools to simulate network transmission errors and delays.
3. `MockTunnelDeviceInfo` - a mock that can be used to access simulated tunnel statistics and interface name.
4. `NetworkCounters` - is a glorified `WgStats` and acts as a conduit for sharing simulated network activity stats (bytes received and sent) with `MockTunnelDeviceInfo`. `MockPinger` updates the stats each time the virtual ping is sent or received.
- - -
This …
=> TunnelMonitor: add initial connection test

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/PacketTunnel/PacketTunnelProvider.swift, ios/PacketTunnel/StartOptions.swift
Small refactoring that extracts the result of parsing packet tunnel options into `StartOptions` struct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5014)
=> PacketTunnel: refactor parsing of start options

.github/workflows/ios.yml, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadREST.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadTransport.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNScreenshots.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNTests.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/Operations.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/PacketTunnel.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/RelaySelector.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/TunnelObfuscation.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/TunnelObfuscationTests.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/TunnelProviderMessaging.xcscheme, ios/TestPlans/MullvadVPNApp.xctestplan, ios/TestPlans/MullvadVPNCI.xctestplan
The CI tests have been broken since introduction of test plans. This PR fixes the GH integration with the following amends:
- Disable: MullvadVPNScreenshots -- this is the target used by fastlane snapshot. This won't work on CI and needs further discussion
- Add PacketTunnelCoreTests to test plan
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5017)
=> CI: use xcode test-plan

mullvad-cli/src/cmds/bridge.rs, mullvad-cli/src/cmds/relay.rs, mullvad-cli/src/cmds/tunnel.rs, mullvad-cli/src/format.rs, mullvad-relay-selector/src/lib.rs, mullvad-types/src/relay_constraints.rs, mullvad-types/src/settings/mod.rs
This PR makes the output more readable and consistent with 'mullvad tunnel get' and fixes incorrect indentation:
```
$ mullvad relay get
Generic constraints
Location:               city sto, se
Tunnel protocol:        any
Provider(s):            any
Ownership:              any
OpenVPN constraints
Port:                   any
Transport:              any
WireGuard constraints
Port:                   any
IP protocol:            any
Multihop state:         disabled
Multihop entry:         country se
```
Previously, the above constraints gave the following output:
```
$ mullvad relay get
Current constraints: 
Tunnel protocol: Any
OpenVPN constraints: any port
Wireguard constraints: 
Port: Any
Protocol: IPv4 or IPv6
Location: location - city sto, se
Provider: Any
```
- - - …
=> Fix CLI output for 'mullvad relay get'

ios/MullvadREST/RESTError.swift, ios/MullvadREST/RESTNetworkOperation.swift, ios/MullvadREST/RESTResponseHandler.swift
Changes:
- Eliminate force cast from `URLResponse` to `HTTPURLResponse` and report a `.transport` error in that case.
- Introduce `InternalTransportError`, move `REST.NoTransportError` into internal one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5035)
=> Eliminate force cast for HTTP response

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt
Ensures the account page button is hidden in release builds. The fact that it was visible is a regression from the compose migration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5042)
=> Hide account page button in release builds

ios/CHANGELOG.md, ios/MullvadREST/AddressCache.swift, ios/MullvadVPNTests/AddressCacheTests.swift
Recently we received a number of reports in regards of persistent communication errors with the API, namely SSL errors and timeouts. 
In <= 2023.2 we used to shuffle a list of IPs and manage them as a stack, first IP in array of endpoints was used to talk to the API. If it didn't work, we picked next by moving the first IP to the end of the list. From >= 2023.3 we always use the first IP in the list.
It's quite likely that the app that ended up using the broken API IP would remain stuck using it after update 2023.3 which always relies on the first IP in the list. I also confirmed that one of API IPs hasn't been working for a while.
I think the most logical and simplest would be to modify the cache schema to store a single endpoint IP instead of array of them, which should then fail to …
=> Change address cache schema IOS-282

Cargo.lock
Avoids the CVE. We were not affected by the CVE to begin with.
Fixes #5036
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5054)
=> Update rustls-webpki to avoid RUSTSEC-2023-0053

Cargo.lock, Cargo.toml, ios/MullvadTransport/shadowsocks-proxy/Cargo.toml, ios/MullvadTransport/shadowsocks-proxy/src/lib.rs, mullvad-api/Cargo.toml, talpid-core/Cargo.toml, talpid-core/src/resolver.rs, talpid-openvpn/Cargo.toml, talpid-openvpn/src/proxy/shadowsocks.rs
Since `shadowsocks` has a release that includes all the changes we need, I've gone and updated our dependencies to use the _crates.io_ release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5055)
=> Update shadowsocks to 1.16

Cargo.lock, talpid-types/Cargo.toml
I just saw that `x25519-dalek` was recently published as stable. As far as I can tell there is no notable difference. Just nicer to get onto stable and off of release candidates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5057)
=> Update x25519-dalek to get stable version instead of rc3

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNScreenshots.xcscheme, ios/Snapfile, ios/TestPlans/MullvadVPNApp.xctestplan, ios/TestPlans/MullvadVPNCI.xctestplan, ios/TestPlans/MullvadVPNScreenshots.xctestplan
Fixes automatic screenshot test/script compatibility with testplans. This PR creates a separate testplan for screenshots, since all tests in the same testplan will run otherwise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5060)
=> Fix screenshot script and testplan

ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift
As discussed, we want to temporarily disable some GUI elements for the next Test Flight build
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5070)
=> Remove temporarily Wireguard obfuscation options for test flight build

talpid-core/src/firewall/linux.rs
I'm using mullvad and tailscale together on the same server. Using [Split tunneling with Linux (advanced)](https://mullvad.net/en/help/split-tunneling-with-linux-advanced/), I'm able to add ip-based exceptions to the input and output chains to exclude tailscale traffic and they both work.
What does _not_ work is incoming tailscale connections to exposed docker ports, because the current firewall table does not have a similar ability to mark exceptions in the forward chain. This PR adds that ability.
With this PR applied, the following tailscale nft table allows all tailscale connections, docker or otherwise:
```
table inet mullvad-ts {
chain prerouting {
type filter hook prerouting priority -100; policy accept;
ip saddr 100.64.0.0/10 ct mark set 0x00000f41 meta mark set 0x6d6f6c65
}
chain …
```
=> Add mark based accept rule for forward chain as well

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomPortTextField.kt
1. Use `toIntOrNull` instead of `toInt` to avoid NumberFormatException.
2. Limit the number of characters in the custom port dialogue input to 5 since numbers that large are not valid port numbers anyway.
3. Add a test that checks for this crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5079)
=> Fix custom port input crash

ios/MullvadTypes/RESTTypes.swift, ios/MullvadVPNTests/DeviceCheckOperationTests.swift, ios/MullvadVPNTests/WgKeyRotationTests.swift
In sympathy with https://github.com/mullvad/mullvadvpn-app/pull/5074, it's time to drop forwarded ports as those were decommissioned anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5078)
=> Remove forwarded ports on iOS

ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionContentView.swift, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionViewController.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift
When the app attempts to display an alert on top of the keyboard, `UIKit` may trigger `[UIKeyboardTaskQueue waitUntilAllTasksAreFinished]`. To prevent interference with keyboard notifications, I set `isEditing` to `false` before making an API call.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5092)
=> Fix UIKit nagging regarding to present alert top of keyboard

ci/ios/upload-app.sh
One last fix - when testing this script out, I passed a `--dry-run` argument to fastlane. This clearly didn't have the effect I wanted as it didn't fail when testing :see_no_evil:. The _production_ copy of this script already has the quotes paths.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5097)
=> Quote paths in upload script

CHANGELOG.md, talpid-platform-metadata/src/lib.rs, talpid-platform-metadata/src/windows.rs
We do not officially support Windows Server, but we could still distinguish between it and the desktop OSes. Currently, we incorrectly assume that the user is necessarily on the desktop version.
This code simply returns "Windows Server" and does not bother to detect the specific version/year. This is fine because we log the build number as well, and the main point is to distinguish between desktop and server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5089)
=> Detect whether OS is Windows Server

ios/MullvadVPN/View controllers/Account/AccountViewController.swift
This PR disables the buttons for deleting the account and redeeming a voucher on the account page when the app is restoring purchases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5095)
=> the-buttons-for-deleting-the-account-and-redeeming-a-voucher-ios-294

CHANGELOG.md, talpid-routing/src/unix/macos/interface.rs, talpid-routing/src/unix/macos/mod.rs, talpid-routing/src/unix/macos/routing_socket.rs, talpid-routing/src/unix/macos/watch.rs
The fix is simply to not ignore the tunnel route if it's being deleted. The PR also adds a timeout for waiting for responses to messages sent on the socket, since we have observed that they occasionally never arrive. Without the timeout, the route monitor becomes completely unresponsive in that case.
Fixes DES-313.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5096)
=> Fix tunnel default route being missing after waking from hibernation

Release.md, build.sh, ci/buildserver-build.sh, gui/package-lock.json, gui/package.json, gui/tasks/distribution.js
`altool` is deprecated and will stop working soon. This PR switches to `notarytool` by upgrading to the latest `@electron/notarize`. Additionally the notarization credentials are now all stored in the keychain.
Since notarization now is a lot quicker it's been enabled for all builds on the buildserver. While doing this I've reveres the notarization-flag in `build.sh`. You now provide `--notarize` when you want it to notarize the build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5088)
=> Switch to notarytool

android/app/build.gradle.kts, android/app/src/test/kotlin/net/mullvad/mullvadvpn/applist/ApplicationsProviderTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SettingsViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt, android/buildSrc/src/main/kotlin/Dependencies.kt, android/lib/common-test/build.gradle.kts, android/lib/common-test/src/main/java/net/mullvad/mullvadvpn/lib/common/test/TestCoroutineRule.kt, android/lib/common-test/src/main/java/net/mullvad/mullvadvpn/lib/common/test/TestUtils.kt, android/settings.gradle.kts
This is to enable unit tests in other modules to use those classes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5083)
=> Move test utils to its own module

CHANGELOG.md, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
Current behaviour is in the fragment, since we want to remove fragments I have moved it to the viewModel.
This replicate the view action pattern that is used elsewhere and in the other connect PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5049)
=> Move out of time behaviour to view model

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/VpnSettingsFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt
Also made some improvements to the mtu dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5102)
=> Fix wireguard mtu selection showing again after closing it

ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5110)
=> Fix Swiftlint warnings in LocationDataSource

ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5108)
=> Fix Swiftlint warnings in MapConnectionStatusOperation

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomDnsInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/LocalNetworkSharingInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MalwareInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ObfuscationInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/QuantumResistanceInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/UdpOverTcpPortInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/WireguardPortInfoDialog.kt
Fixes inconsistencies between different dialogs and aligns it closer to the current design.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5129)
=> Fix dialogs padding and spacing

Cargo.lock, mullvad-daemon/Cargo.toml, mullvad-daemon/src/management_interface.rs, mullvad-daemon/src/migrations/mod.rs, talpid-core/src/dns/windows/iphlpapi.rs, talpid-core/src/split_tunnel/linux.rs
This PR removes or fixes a few minor TODO comments.
Fixes DES-347.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5137)
=> Fix a few TODO comments

ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionContentView.swift
When entering the last 4 digits of the account number on the account deletion screen, the OK button lights up even if the number is incorrect. When pressing the OK button an error message is displayed, saying that the number is indeed incorrect. The process has now been simplified by having the OK button itself function as validation instead and only enabling it if input is valid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5069)
=> On delete account screen, add account number validation during input

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt
This pull requests fixes the animations on the Split tunneling view in 3 ways:
- Removes alpha on list items causing them to overlap and look weird.
- Adds animateItemPlacement on missing items
- Fixes modifier on BaseCell so it is applied on top most item
Note: Animations only fully work in release mode and thus might look a bit choppy or incorrect when using emulator and/or debug mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5145)
=> Fix list animations for split tunneling

ios/MullvadVPN/Containers/Root/RootContainerViewController.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5105)
=> Fix Swiftlint warnings in RootContainerViewController

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/BaseFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SelectLocationFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SettingsFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SettingsViewModel.kt
Color phone status bar after fragment transition in following screens:
- select location screen
- account screen
- settings screen
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5003)
=> Paint status bar after screen enter animation end

android/BuildInstructions.md, android/docs/BuildInstructions.macos.md
This PR splits out and updates the build instructions for macOS. 
The current instructions branch depending on if the user have Linux or macOS, which gets confusing for the user. It was also not able to run on a ARM based macbook for several reasons:
- Updated environmental variables caused AVD in Android Studio to crash
- Links to `ndk` would pull the Linux version of `ndk` for mac user that would not work.
- `./build-apk --dev-build` spits out error `optional_android_credentials_volume[@]: unbound variable` and the image wouldn't work on ARM-based macbook if it proceeded.
The new instructions are a bit more opinionated by requiring android studio, and not using stand-alone `sdkmanager`. Considering android-studio basically the only IDE android developer's I don't believe this is too …
=> Update android build instructions for macOS

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
Quick fix for headline size to look the same as rest of app bars. Right now the[ font size is hardcoded](https://github.com/mullvad/mullvadvpn-app/blob/e05cc2afab256b7997a9c4a10125ff417c34d31a/android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt#L63) for the top bar and not in the compose theme so once we move away from the CollapsingTopBar we should update all these fonts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5148)
=> Fix Select Location headline size

ios/MullvadVPN/AppDelegate.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5162)
=> Fix REST.AccessTokenManager being used before initialisation in AppDelegate

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/PacketTunnel/PacketTunnelProvider.swift, ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift, ios/PacketTunnelCore/TunnelMonitor/TunnelMonitorTimings.swift, ios/PacketTunnelCoreTests/TunnelMonitorTests.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5160)
=> Fix reliability and time consumption of testInitialConnectionTimings test

CHANGELOG.md, talpid-core/src/offline/macos.rs, talpid-routing/src/unix/macos/interface.rs, talpid-routing/src/unix/macos/mod.rs
Fix issues:
* Unscoped default routes were not restored after disconnecting after a switching to a different network.
* We now filter out default routes with "inactive" interfaces. Fixes timeouts when switching from a network lower to one higher in the network service order, and other strange behavior.
* Fix nearly useless offline monitor.
Closes DES-344, DES-343.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5122)
=> Fix macOS route monitor bugs

android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/DefaultDnsOptions.kt, mullvad-cli/src/cmds/dns.rs, mullvad-daemon/src/dns.rs, mullvad-daemon/src/settings.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/settings.rs, mullvad-types/src/settings/dns.rs
When infra has deployed these block lists to the relays, this setting will allow blocking social media domains directly with the app.
I intentionally left it out of the changelog for now. This should not go into production before it's added to the UI anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5163)
=> Add social media blocklists to daemon+CLI

mullvad-api/src/rest.rs
This function has been superfluous for ages - I wonder what other dead code we could remove.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5167)
=> Remove deadcode from mullvad-api

ci/buildserver-build-android.sh
The scripts deviated some time ago so this commits aims to unify the android script with the desktop equivalent in terms of its structure as well as how it handles versioning and artifacts.
When running this in a local environment, the `buildserver-build-android.sh` generates the following type of output in the `upload` directory (updated from the original PR description):
```
upload
├── 2023.5-beta1-dev-a8bcc8+androiddummy-signed-tag-6+myhost123.sha256
├── 2023.5-beta1-dev-b60c95+androiddummy-signed-tag-7+myhost123.sha256
├── MullvadVPN-2023.6-beta1-dev-a8bcc8+androiddummy-signed-tag-6.aab
├── MullvadVPN-2023.6-beta1-dev-a8bcc8+androiddummy-signed-tag-6.apk
├── MullvadVPN-2023.6-beta1-dev-b60c95+androiddummy-signed-tag-7.aab
└── …
```
=> Unify android build server script with the desktop equivalent

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Coordinators/CreateAccountVoucherCoordinator.swift, ios/MullvadVPN/Coordinators/ProfileVoucherCoordinator.swift, ios/MullvadVPN/UI appearance/UIEdgeInsets+Extensions.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift, ios/MullvadVPN/View controllers/RedeemVoucher/AddCreditSucceededViewController.swift, ios/MullvadVPN/View controllers/RedeemVoucher/LogoutDialogueView.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewConfiguration.swift
This PR makes the voucher view closer to the originally intended design.
A title has been added, a switch for a `compactMode` where the view is now shown fully (when presented from the account view) 
Fonts and font weights have been changed, as well as some margins.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5165)
=> Make the Voucher view more comforming to designs

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/WelcomeFragment.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5179)
=> Replace remaining release build checks with play build checks

ios/CHANGELOG.md, ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift
As the title says, we remove the "block" word from the content blockers to align with other platforms.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5182)
=> Align copy with design for content blockers

android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/constant/Actions.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/constant/Classes.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/constant/ClassesAndActions.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VpnPermission.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt, android/tile/src/main/kotlin/net/mullvad/mullvadvpn/tile/MullvadTileService.kt, android/tile/src/main/kotlin/net/mullvad/mullvadvpn/tile/ServiceConnection.kt
This PR aims to make sure the android app can run under build variant specific app ids, such as `net.mullvad.mullvadvpn.devmole`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5184)
=> Support running under build variant app ids

ios/MullvadVPN/Notifications/UI/NotificationController.swift
Notification banner animations might get choppy if many notifications are fired quickly after each other.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5170)
=> Improve notification banner transitions

ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift
If redeem voucher view is canceled before its presentation transition is done, the view will be removed prematurely and we end up with a black screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5187)
=> Fix black screen bug if redeem voucher view if canceled to early

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt
In some cases (TextField) the constriantlayout would steal focus when user uses right arrow. This commit removes the use of ConstraintLayout so it won't interfere with input.
This is a requirement before we merge https://github.com/mullvad/mullvadvpn-app/pull/5164
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5171)
=> Replace ConstraintLayout with Row
