android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/NotificationWithUrl.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/VersionInfoNotification.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AppVersionCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/UrlCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4808)
=> Add ?hide_nav variants to all mullvad.net links

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/CustomAlertViewController.swift, ios/MullvadVPN/Coordinators/App/AccountCoordinator.swift, ios/MullvadVPN/Coordinators/App/OutOfTimeCoordinator.swift, ios/MullvadVPN/Extensions/RESTCreateApplePaymentResponse+Localization.swift, ios/MullvadVPN/Notifications/Notification Providers/RegisteredDeviceInAppNotificationProvider.swift, ios/MullvadVPN/View controllers/Account/AccountContentView.swift, ios/MullvadVPN/View controllers/Account/AccountViewController.swift, ios/MullvadVPN/View controllers/Account/PaymentAlertPresenter.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift
To help users further to understand the device concept, an info button next to the device name in the account view is added. It opens an info dialog that explains the device concept.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4731)
=> Add info button next to device name in account view

BuildInstructions.md
It's not obvious which MingW build works, what C runtime to use, etc. So this PR documents this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4827)
=> Document where to get MingW

building/README.md
Just found myself needing this link last week. Figured adding it here will make this process way smoother in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4825)
=> Document how to log in to ghcr.io when publishing packages

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/PrivacyDisclaimerFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/SettingsFragment.kt
Also append hide nav for policy link in disclaimer fragment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4833)
=> Hide faqs and guides button for release builds

ios/MullvadVPN.xcodeproj/project.pbxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4839)
=> Enable APPLICATION_EXTENSION_API_ONLY for MullvadTransport

talpid-routing/src/unix/macos/watch.rs
This is currently not possible because the `PF_ROUTE` socket demurs when a route is added if its destination IP equals its gateway.
The use case is pretty strange, but we do rely on it for testing. So let's quick fix it by ignoring such routes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4837)
=> Fix inability to use router/gateway as the custom WireGuard endpoint

mullvad-setup/src/main.rs
Sometimes when removing a device when uninstalling the app, a `404` is returned if the device has already been revoked from the account. However, removing a non-existent device should not be considered an error if the end goal _is_ to not have the device on the account. That goal has clearly already been achieved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4828)
=> Do not consider removing a revoked device to be an error.

CHANGELOG.md
This PR adds a few missing changelog items related to the device concept UX improvements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4840)
=> Update changelog with device improvements

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/DnsCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/InformationComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/MtuComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Button.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Chevron.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/List.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoadingScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Theme.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/VpnSettingsFragment.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4832)
=> Migrate most compose components to material 3

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingToolbarScaffold.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
Fixes: DROID-76
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4843)
=> Add collapsible toolbar component with dynamic body height

ios/MullvadVPN/Extensions/SKError+Localized.swift, ios/MullvadVPN/Extensions/StorePaymentManagerError+Display.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4880)
=> Hotfix for presenting cancelled payment in a nicer way

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoadingScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/DeviceListFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/DeviceRevokedFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/PrivacyDisclaimerFragment.kt
This affects the following screens:
- Loading
- Device Revoked
- Privacy Policy
- Too many devices
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4882)
=> Replace scaffold with material 3 scaffold

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/Finders.kt, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/MtuComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4878)
=> Remove subtitle from base cell

ios/MullvadVPN/TunnelManager/TunnelManager.swift
When a user deletes the account via another device, it is important to ensure that all devices are informed about the changes and the account data is wiped to prevent any issues or inconsistencies. To address this problem, the following steps can be taken:
1. Inform current device about the account deletion and changes made.
2. Wipe all account data from the device to ensure no remnants of the account is left.
3. Transition the user to a revoked state, where they no longer have access to the account and its features.
To handle this scenario, the app should be obtaining an authorization token error with a status code of 400, specifically indicating "INVALID_ACCOUNT." When the app encounters the INVALID_ACCOUNT error, it should transition the user to the revoked view, where they are made …
=> Handle logged in account no longer existing

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4910)
=> Fix incorrect version formatting in settings

android/app/src/main/res/values/dimensions.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4913)
=> Fix lint error for unused resources

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ConnectionButton.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4915)
=> Fix disconnect button text alignment

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationInfo.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4917)
=> Reduce location info flickering

android/app/src/main/res/layout/notification_banner.xml
This PR fixes an alignment regression which was introduced when fixing RTL lint errors. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4923)
=> Fix in-app notification alignment

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/AnimatedIconButton.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableObfuscationView.kt
Fixes: DROID-171
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4934)
=> Add copy icon feedback on click

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ConnectionButton.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4924)
=> Reduce location flickering in the connect view

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ConnectionButton.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/theme/Color.kt
Fixes: DROID-231
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4939)
=> Fix Disconnect Button color alpha value

android/app/src/main/res/layout/connect.xml
Fixes: DROID-232
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4945)
=> Fix Connect view DPAD navigation

android/app/build.gradle.kts, android/build.gradle.kts, android/lib/common/build.gradle.kts, android/lib/endpoint/build.gradle.kts, android/lib/ipc/build.gradle.kts, android/lib/model/build.gradle.kts, android/lib/resource/build.gradle.kts, android/lib/talpid/build.gradle.kts, android/service/build.gradle.kts, android/test/common/build.gradle.kts, android/test/e2e/build.gradle.kts, android/test/mockapi/build.gradle.kts, android/tile/build.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4972)
=> Cleanup gradle configuration

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4982)
=> Fix split tunneling content alignment

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4987)
=> Secure account screen aginst screenshot an screen record

talpid-core/src/dns/windows/dnsapi.rs
Using run-time linking is overly defensive here. It seems very unlikely that this function will be removed, even though it's not documented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4985)
=> Simplify dnsapi module

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4997)
=> Add scroll to account screen

ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Containers/Navigation/UINavigationBar+Appearance.swift, ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionContentView.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift, ios/MullvadVPN/View controllers/DeviceList/DeviceManagementContentView.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift, ios/MullvadVPN/View controllers/SelectLocation/SelectLocationCell.swift, ios/MullvadVPN/View controllers/TermsOfService/TermsOfServiceContentView.swift
This PR drops code branch supporting iOS 13 or before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/4996)
=> Remove iOS 13 code

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5001)
=> Change focus order in select location screen

.github/workflows/android-app.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5025)
=> Temporarily disable android instrumental tests

ios/MullvadVPN/Notifications/NotificationManager.swift, ios/MullvadVPN/View controllers/Login/AccountTextField.swift, ios/MullvadVPN/View controllers/Settings/SettingsSwitchCell.swift, ios/MullvadVPN/Views/CustomTextView.swift, ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift
Fix `swiftlint` violation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5030)
=> Fix computed_accessors_order swiftlint violation

mullvad-cli/src/cmds/custom_lists.rs, mullvad-cli/src/cmds/relay.rs, mullvad-cli/src/main.rs, mullvad-types/src/relay_list.rs
This PR overhauls the UX of the custom lists CLI to bring it up on par with other parts of the CLI. It includes a number of changes (and hopefully improvements!):
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5002)
=> Improve custom lists CLI UX

ios/MullvadVPN/Containers/Root/RootContainerViewController.swift, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionContentView.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherContentView.swift
Fix `swiftlint` violations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5028)
=> Fix void_function_in_ternary violation

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialog.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5037)
=> Check that the custom port is valid when submitting from the keyboard

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5038)
=> Increase spacing between spinner and location info

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CollapsingTopBar.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5043)
=> Remove text next to back button in collapsings toolbar

mullvad-cli/src/cmds/relay.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/main.rs, mullvad-daemon/src/management_interface.rs, mullvad-daemon/src/migrations/v1.rs, mullvad-daemon/src/migrations/v2.rs, mullvad-daemon/src/migrations/v3.rs, mullvad-daemon/src/migrations/v4.rs, mullvad-daemon/src/migrations/v5.rs, mullvad-daemon/src/migrations/v6.rs, mullvad-management-interface/src/lib.rs, mullvad-problem-report/src/lib.rs, mullvad-relay-selector/src/lib.rs, talpid-core/src/dns/linux/mod.rs, talpid-core/src/dns/linux/static_resolv_conf.rs, talpid-core/src/dns/macos.rs, talpid-core/src/firewall/macos.rs, talpid-core/src/resolver.rs, talpid-core/src/split_tunnel/windows/driver.rs, talpid-core/src/split_tunnel/windows/windows.rs, talpid-core/src/tunnel/mod.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-openvpn/src/lib.rs, talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_go.rs, talpid-wireguard/src/wireguard_kernel/wg_message.rs
New clippy dropped sometime last month, this is the aftermath. Mostly reverting needlessly async functions back to being synchronous.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5058)
=> Remove superfluous async functions

talpid-openvpn/src/proxy/shadowsocks.rs
Same code as https://github.com/mullvad/mullvadvpn-app/pull/5063.  Shadowsocks has become a lot better so now there's no need to do a dance of binding a local socket to _reserve_ a local socket address anymore - we can just specify `127.0.0.1:0` and fetch the port after it's been bound.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5071)
=> Get proxy's local address after binding

Cargo.lock, talpid-openvpn/Cargo.toml, talpid-openvpn/src/proxy/shadowsocks.rs
Cleaning up after my own negligence again, by removing unused imports and removing an unused dependency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5072)
=> Remove unused socket2 dependency

CHANGELOG.md
Add a changelog entry for #5011.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5076)
=> Mention forward chain exception in the changelog

ios/MullvadVPN/Supporting Files/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5086)
=> Override ATS for our API endpoint and Shadowsocks

ios/MullvadLogging/CustomFormatLogHandler.swift, ios/MullvadLogging/OSLogHandler.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5098)
=> Fix swiftlint warning function_parameter_count

gui/src/renderer/app.tsx, gui/test/e2e/installed/state-dependent/login.spec.ts
This PR fixes a few regressions in the automated tests that were introduced in https://github.com/mullvad/mullvadvpn-app/pull/5045.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5090)
=> Fix login tests

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5101)
=> Stop filtering null locations to avoid bugs with connection errors

android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SettingsViewModelTest.kt, android/lib/common-test/src/main/java/net/mullvad/mullvadvpn/lib/common/test/TestCoroutineRule.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5115)
=> Replace deprecated TestCoroutineDispatcher

android/app/lint-baseline.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5121)
=> Remove lint baseline issues for already removed files

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NotificationBanner.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5130)
=> Fix the click area of the notification banner

gui/src/renderer/app.tsx
This PR adds logging of the account expiry when running tests. This is to easily identify tests sometimes fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5131)
=> Add logging of account expiry when running tests

ios/MullvadVPN/View controllers/DeviceList/DeviceManagementContentView.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5111)
=> Fix Swiftlint warnings in DeviceManagementContentView

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/LocationInfoCache.kt
This should be more in line on how it is done one desktop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5134)
=> Change reconnect location behavior to fix multiple bugs

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProvider.swift, ios/MullvadVPN/TunnelManager/VPNConnectionProtocol.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5135)
=> Move VPNConnectionProtocol to its own file

ios/MullvadVPN/TunnelManager/TunnelManager.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5143)
=> Make TunnelManager dispatch to the main queue after deleting an account

ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5112)
=> Fix Swiftlint warnings in TunnelMonitor

ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5106)
=> Fix Swiftlint warnings in ProblemReportViewController

ios/MullvadVPN/AppDelegate.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5104)
=> Fix Swiftlint warnings in AppDelegate

ios/PacketTunnel/PacketTunnelProvider.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5107)
=> Fix Swiftlint warnings in PacketTunnelProvider

ios/build-wireguard-go.sh
This tiny patch fixes the documentation generator for the project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5172)
=> Fix wg-go script to make docs build

ios/MullvadSettings/DNSSettings.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift, ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift
This PR adds a toggle for blocking social media via DNS, and does a small refactoring of `PreferencesCellFactory` to avoid repetition 
avoid repetition
avoid repetition
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5176)
=> Add a toggle to block social media

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt
Also make the dialog implement theme for colors and text styles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5202)
=> Fix incorrect text styles in info dialog

gui/locales/messages.pot, gui/src/main/daemon-rpc.ts, gui/src/main/default-settings.ts, gui/src/renderer/components/CustomDnsSettings.tsx, gui/src/renderer/components/VpnSettings.tsx, gui/src/renderer/redux/settings/reducers.ts, gui/src/shared/daemon-rpc-types.ts
Fix DES-331.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5209)
=> Add social media blocking to GUI

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/DnsCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceRemovalDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoadingScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt
This is part of the design system overhaul.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5215)
=> Replace all remaining color resource with theme colors

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5219)
=> Fix broken android test

.github/workflows/ios.yml
Successful build and test available [here](https://github.com/mullvad/mullvadvpn-app/actions/runs/6406660819)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5237)
=> Use Xcode15 on github CI

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Text.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5226)
=> Fix text color in account view

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5227)
=> Too much spacing between text and button in local network dialog

gui/locales/messages.pot, gui/src/renderer/components/select-location/CustomListDialogs.tsx
This PR adds "(Added)" to a custom list where the location is already present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5247)
=> Add label to custom list row in add dialog

gui/package-lock.json
This PR updates a few TS/JS dependencies with known vulnerabilities reported by `npm audit`. None of the vulnerabilities affect us. The changes were made by running `npm audit fix`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5265)
=> Update dependencies with known vulnerabilities

building/android-container-image.txt
This PR aims to use the newly built Android image for building the Android app: https://github.com/orgs/mullvad/packages/container/mullvadvpn-app-build-android/136405778?tag=9504b914a
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5272)
=> Use new Android container image

.github/workflows/android-app.yml, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5274)
=> Fix some unit tests not running after adding flavors

ios/MullvadVPN/View controllers/Account/AccountContentView.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5278)
=> Remove voucher buttons account and new account views

scripts/install-mullvad
After changing the structure on the releases-server this script needs updating.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5286)
=> Update URL for downloading app from releases server

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5281)
=> Fix DPAD navigation for Welcome and OutOfTime screen

CHANGELOG.md
This was never added to the changelog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5318)
=> Update changelog for social media content block list

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Device.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/DeviceState.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5308)
=> Fix device name in DeviceList not formatted correctly

android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ChangelogViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5316)
=> Replace deprecated runblockingtest

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/BaseFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ConnectFragment.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5311)
=> Fix navigation bar animation

ios/MullvadVPN/View controllers/Account/AccountContentView.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift
This PR restricts voucher redemption exclusively to the development environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5322)
=> remove voucher redemption on production

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/OutOfTimeFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/RedeemVoucherDialogFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/WelcomeFragment.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5296)
=> Add redirection callback to voucher dialog

ci/buildserver-build-android.sh
This PR aims to fix tag formatting and inclusion in artifact names.
Fixes: DROID-361, DROID-397
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5319)
=> Fix artifact naming in tagged builds

ci/buildserver-upload.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5321)
=> Add build server support for additional android artifacts

build-apk.sh
This commit adds stagemole and devmole builds in the android builds script. This includes both bundles and apks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5338)
=> Build stage and dev builds in build script

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/RelayListListener.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Ownership.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayConstraints.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/RelayConstraintsUpdate.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/RelayListListener.kt, mullvad-jni/src/classes.rs, mullvad-types/src/relay_constraints.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5336)
=> Add relay ownership enum to relay constraints

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5343)
=> Information dialogs not scrollable

Cargo.lock, mullvad-jni/Cargo.toml, mullvad-types/Cargo.toml, talpid-core/Cargo.toml, talpid-tunnel/Cargo.toml, talpid-types/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5360)
=> Update jnix to version 0.5.1

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/VpnSettingsFragment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelState.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5332)
=> Show popup when enabling custom dns server

android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AccountRepository.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5342)
=> App header can show previous account remaining time

.github/workflows/ios.yml
- Bump Xcode to 15.0.1 which should improve performance.
- Switch sim to generic `platform=iOS Simulator,name=iPhone 15`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5364)
=> Bump CI to Xcode 15.0.1

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Relay.kt, mullvad-types/src/relay_list.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5369)
=> Expose ownership and provider for relays

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/SecureScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt
This PR removes some logic from the MainActivity to make it a bit easier to migrate to compose navigation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5362)
=> Prepare for compose navigation

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5355)
=> Add scroll to privacy disclaimer screen

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5375)
=> Fix incorrect login success string

.github/workflows/desktop-e2e.yml, build.sh, test/ci-runtests.sh
This is done by building the app if the ref points neither to `main` nor a tag.
Fix DES-436.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5382)
=> Run E2E tests for any branch

mullvad-api/src/access.rs, mullvad-api/src/device.rs, mullvad-api/src/lib.rs, mullvad-api/src/relay_list.rs, mullvad-api/src/rest.rs, mullvad-daemon/src/geoip.rs, mullvad-daemon/src/version_check.rs
This PR gets rid of a lot of repetition surrounding authentication, error handling, deserialization, and other things, in `mullvad-api`.
Fix DES-416.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5340)
=> Refactor mullvad-api

.github/workflows/android-audit.yml, android/config/dependency-check-suppression.xml
This PR aims to push the suppression date for some of the unfixed non-critical CVEs that haven't yet been addressed by upstream dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5397)
=> Push suppression date for unfixed non-critical CVEs

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ChangelogDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5388)
=> Fix button spacing on android

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt, android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, gui/locales/messages.pot
- Fixes duplicate dividers
- Adds alpha to the buttons
- Updates tunneling description according to design.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5386)
=> Split tunneling UI fixes

ios/CHANGELOG.md
I've updated the changelog to be somewhat current. Do tell me if it's missing some recent changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5404)
=> Update iOS changelog

CHANGELOG.md, android/app/build.gradle.kts, android/app/src/main/res/resources.properties
This PR adds the support for app languages. It uses the automatic way of adding languages:
https://developer.android.com/guide/topics/resources/app-languages#auto-localeconfig
If we want more finer control, we can add a custom list of languages but that would also require us to maintain that list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5389)
=> Add support for app languages

mullvad-daemon/src/migrations/v1.rs, mullvad-daemon/src/migrations/v2.rs, mullvad-daemon/src/migrations/v3.rs, mullvad-daemon/src/migrations/v4.rs, mullvad-daemon/src/migrations/v5.rs, mullvad-daemon/src/migrations/v6.rs, talpid-wireguard/src/wireguard_nt.rs
Fixes a few clippy lints in tests, which seem to have been missed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5428)
=> Clippy lints in tests

.github/workflows/android-app.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5429)
=> Fix firebase job condition

android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/AccountCache.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5401)
=> Skip sending account expiry missing events when failing to fetch

build-apk.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5423)
=> Remove release flag for apk builds with --dev-build flag

gui/src/renderer/components/DeviceRevokedView.tsx
The "Go to login" button was incorrectly green and has now been changed to blue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5413)
=> Fix button color in revoked view

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt
This PR aims to add a test tag that can be used by automated tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5450)
=> Add login input test tag

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/ReportProblemNoEmailDialog.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5456)
=> Fix report problem on email dialog text color

android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/LoginConstant.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5459)
=> Add timeout to login screen

build-apk.sh, ci/buildserver-upload.sh
This PR aims to publish the `play` flavor apk in addition to the bundle that is already published. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5467)
=> Publish play apk

ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
This PR fixes the flakiness in `testCannotReconnectAfterStopping`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5451)
=> Fix flaky reconnecting test

android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5469)
=> Fix crash when getting a billing disconnect callback

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5472)
=> Fix collapsible toolbar flickering

android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AccountRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5465)
=> Fix issue with the welcome screen showing up after buying time

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5471)
=> Reset purchase state when automatically leaving a screen

ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
This PR fixes the test that was always broken on the CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5447)
=> Fix flaky actor tests

.github/workflows/android-static-analysis.yml, android/app/src/androidTest/AndroidManifest.xml, android/app/src/debug/AndroidManifest.xml, android/app/src/devmole/AndroidManifest.xml, android/app/src/stagemole/AndroidManifest.xml, android/config/config.mobsf, android/scripts/tidy.sh
This PR aims to fix or suppress all issues reported by `mobsfscan`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5483)
=> Fix or suppress mobsfscan issues

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5508)
=> Show out of time instead of negative days in the top bar

android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/net/mullvad/mullvadvpn/provider/MullvadFileProvider.kt
This PR aims to make sure there are no conflicting file providers between the available build variants.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5510)
=> Fix conflicting file provider between build variants

.github/workflows/desktop-e2e.yml
Add Ubuntu 23.10 as a target for the testing framework.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5515)
=> Add Ubuntu 23.10 to testing framework

.github/workflows/desktop-e2e.yml
Add Fedora 39 as a target for the testing framework.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5519)
=> Add Fedora 39 to testing framework

dist-assets/linux/after-install.sh, dist-assets/linux/before-install.sh
Do not fail installation in containers without systemd init.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5431)
=> Do not fail installation in containers without systemd init

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ConnectionButton.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5538)
=> Fix button spacing

.github/workflows/check-changelog.yml, CHANGELOG.md
Fix some incorrect changelog entries and add workflow for checking if the line length limit is respected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5518)
=> Add checks for changelog

CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
This PR aims to update the release notes for `android/2023.9`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5556)
=> Update changelog for android/2023.9

ios/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5563)
=> Mention UDP-over-TCP obfuscation in changelog

CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
This PR aims to update the release notes for `android/2023.10-beta1`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5579)
=> Update changelog for android/2023.10-beta1

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
Scroll to the selected country in SelectLocationScreen
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5551)
=> Scroll to selected country

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5616)
=> Fix background color on welcome screen

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/InfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RemoveDeviceConfirmationDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/WireguardCustomPortDialog.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5614)
=> Align dialog titles

CHANGELOG.md, mullvad-api/src/lib.rs, mullvad-cli/src/cmds/account.rs, mullvad-daemon/src/device/mod.rs, mullvad-daemon/src/device/service.rs, mullvad-daemon/src/lib.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/account.rs, mullvad-types/src/account.rs
Closes DES-534.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5629)
=> Add account UUID to verbose 'mullvad account get' output

mullvad-api/src/rest.rs, mullvad-daemon/src/access_method.rs, mullvad-daemon/src/migrations/account_history.rs, mullvad-daemon/src/migrations/mod.rs, mullvad-exclude/src/main.rs, talpid-openvpn/src/proxy/shadowsocks.rs, talpid-routing/src/windows/get_best_default_route.rs, talpid-routing/src/windows/mod.rs, talpid-routing/src/windows/route_manager.rs, talpid-tunnel-config-client/src/lib.rs
The CI is failing due to an update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5633)
=> Fix clippy lints

mullvad-daemon/src/geoip.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5652)
=> Remove debug logging for geoip

BuildInstructions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5653)
=> Update the go version in the build instructions to 1.21

gui/locales/messages.pot, gui/src/renderer/components/select-location/CustomListDialogs.tsx, gui/src/renderer/components/select-location/CustomLists.tsx, gui/src/renderer/components/select-location/LocationRow.tsx
This PR makes a few GUI improvements:
- Prevent creating custom lists with empty names
- Show disabled chevron for custom lists without items
- Align custom list buttons
Fixes DES-531.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5624)
=> Custom list UI improvements

android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt, android/test/mockapi/build.gradle.kts, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/CreateAccountMockApiTest.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/constant/Constants.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/util/JsonUtils.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5683)
=> Add mockapi tests for successful and failed account creation

build.sh, env.sh, gui/tasks/distribution.js, scripts/utils/host
This PR changes `distribution.js` to look for the Rust binaries in the correct location.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5670)
=> Fix binaries paths in mac build

mullvad-api/src/lib.rs
If the `api-override` feature is enabled, we allow overriding the ip address to the Mullvad API by settings the `MULLVAD_API_ADDRESS` env variable or have it be resolved automatically if `MULLVAD_API_HOST` is overriden.
This commit fixes a bug where we would try to resolve the API address when `MULLVAD_API_ADDRESS` was not set even if `MULLVAD_API_ADDRESS` was not set either. This would cause the daemon to panic when starting, potentially being unable to start up on consecutive retry attempts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5691)
=> Do not try to resolve API address if `MULLVAD_API_HOST` is not set

.github/workflows/android-app.yml, android/app/build.gradle.kts, android/buildSrc/src/main/kotlin/BuildVariants.kt, android/scripts/run-instrumented-tests.sh, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/annotation/SkipForFlavors.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/constant/AppConstants.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt, android/test/e2e/build.gradle.kts, android/test/e2e/e2e.properties, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/EndToEndTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LaunchAppTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LoginTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LogoutTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/WebLinkTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/constant/ConnCheckConstants.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/constant/Constants.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/constant/UrlConstants.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/AccountTestRule.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/SimpleMullvadHttpClient.kt, android/test/firebase/e2e-play-stagemole.yml, android/test/firebase/mockapi-oss.yml, android/test/mockapi/build.gradle.kts, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiTest.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/constant/Constants.kt
This PR aims to add support for running e2e tests in stagemole using on-the-fly created accounts by supplying a stagemole partner account. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5698)
=> Run stagemole tests in firebase

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/StartupConstant.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/PrivacyDisclaimerViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplashViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5672)
=> Block Accept Privacy until service is ready

gui/src/main/daemon-rpc.ts, gui/src/shared/daemon-rpc-types.ts, gui/src/shared/notifications/error.ts, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/states.rs, talpid-core/src/tunnel/mod.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-openvpn/src/lib.rs, talpid-routing/src/unix/mod.rs, talpid-routing/src/windows/mod.rs, talpid-types/src/tunnel.rs, talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_go.rs, talpid-wireguard/src/wireguard_nt.rs
This is useful for giving more informative error messages.
Fix DES-594.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5734)
=> Forward tunnel device errors to frontends

CHANGELOG.md, gui/locales/messages.pot, gui/src/main/index.ts, gui/src/main/notification-controller.ts, gui/src/renderer/components/Launch.tsx, gui/src/renderer/components/Modal.tsx, gui/src/renderer/components/NotificationArea.tsx, gui/src/shared/notifications/daemon-disconnected.ts, gui/src/shared/notifications/notification.ts
This PR improves the information towards the user when the Electron app has lost contact with the Daemon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5741)
=> Improve info when disconnected from daemon

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountExpiryMockApiTest.kt
This has essentially two potential success states since I was not able to figure out a way to make sure either of them happen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5720)
=> Add account expiry mockapi test

android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/Color.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/ColorTokens.kt
Part of material 3 hack day thingy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5732)
=> Replace secondary container with solid color

android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5744)
=> Increase timeout for ensure account creation failure

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/CheckboxCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/InformationComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/SearchTextField.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/Color.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/ColorTokens.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5733)
=> Remove all direct usages of mullvad colors

.github/workflows/android-app.yml
This PR increases the android artifact retention to 7 days.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5764)
=> Increase actions retention to 7 days

android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt
Add some extra time to for the login page to show to improve stability of the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5786)
=> Fix flaky account history mockapi test

.github/workflows/daemon.yml, .github/workflows/rust-unused-dependencies.yml, Cargo.lock, talpid-types/Cargo.toml, test/Cargo.lock
This reverts commit 682d2c27c64022bc064b5418bd8be338471a1c50.
Fixes DES-621
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5785)
=> Re-enable Rust nightly CI builds

ios/BuildInstructions.md
I thought I had merged these - I had not. @acb-mv tested these and found no issues, so let's keep them in `main` before they become outdated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5789)
=> Update build instructions

talpid-core/src/tunnel/mod.rs, talpid-windows/src/net.rs, talpid-wireguard/Cargo.toml, talpid-wireguard/src/lib.rs
Fixes DES-583.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5759)
=> Automatic MTU detection Windows

.github/ISSUE_TEMPLATE/1-bug-desktop.yml, .github/ISSUE_TEMPLATE/2-bug-android.yml, .github/ISSUE_TEMPLATE/3-bug-ios.yml, .github/ISSUE_TEMPLATE/config.yml, CHANGELOG.md, CONTRIBUTING.md, android/src/main/play/contact-email.txt, gui/package.json, gui/src/config.json
This PR updates all mentiones of the support email address to the new address.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5793)
=> Update support email address to new one

Cargo.lock, talpid-core/src/tunnel/mod.rs, talpid-wireguard/Cargo.toml, talpid-wireguard/src/lib.rs, talpid-wireguard/src/mtu_detection.rs, talpid-wireguard/src/unix.rs
Fixes DES-582.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5767)
=> MTU detection macos

.github/workflows/frontend.yml, .github/workflows/translations.yml
This PR fixes an error due to a new release of https://github.com/zoexx/github-action-json-file-properties
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5815)
=> Fix `github-action-json-file-properties` version

.github/workflows/ios-validate-build-schemas.yml
This PR forces a build of the `MullvadVPNUITests` target post merge on `main` to make sure no changes accidentally break it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5817)
=> Build MullvadVPNUITests post merge to guarantee it is not accidentally broken

mullvad-api/src/lib.rs
Access modes were disabled by default when compiling with the `api-override` feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5821)
=> Don't force direct access mode by default

ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideTextViewController.swift, ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5851)
=> Enable IP Override, and fix text color in it

ios/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5853)
=> Include IP Overrides in changelog

ci/ios/test-router/raas.nix, ci/ios/test-router/raas/Cargo.lock, ci/ios/test-router/raas/Cargo.toml, ci/ios/test-router/raas/src/block_list/rule.rs, ci/ios/test-router/raas/src/capture/mod.rs, ci/ios/test-router/raas/src/main.rs, ci/ios/test-router/raas/src/web/capture.rs, ci/ios/test-router/raas/src/web/mod.rs, ci/ios/test-router/raas/src/web/routes.rs
Close IOS-443.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5877)
=> Add packet capturing to iOS test router service

.github/workflows/android-app.yml
This PR aims to our slow jobs to a faster GitHub managed runner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5883)
=> Use faster GH runners for slow jobs

.github/workflows/android-app.yml
The purpose of this is to allow all ongoing lint and test jobs to continue even though one has failed. This will make sure that developers get feedback for all jobs in the matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5884)
=> Change test and lint matrix strategy

android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/DeviceRepository.kt
Make deviceState Eagerly to prevent missing of LoggedOut messages from Daemon. See linear for more information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5880)
=> Fix Revoked sometimes showing after logging in

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
Adds the missing margin that accidentally got removed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5895)
=> Fix margin on ConnectScreen

.github/workflows/desktop-e2e.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5926)
=> Add target list to end-to-end workflow description

CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5830)
=> Add MTU detection to changelog

test/.gitignore
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5923)
=> Add `.container` to `.gitignore`

test/Cargo.lock, test/Cargo.toml, test/test-manager/Cargo.toml, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/mod.rs, test/test-manager/src/tests/tunnel_state.rs, test/test-manager/src/vm/network/linux.rs, test/test-rpc/src/client.rs, test/test-rpc/src/lib.rs, test/test-runner/Cargo.toml, test/test-runner/src/main.rs, test/test-runner/src/net.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5891)
=> MTU detection integration test on Linux and Windows

.github/workflows/shellcheck.yml
It currently displays as `.github/workflows/shellcheck.yml / Shellcheck (pull_request)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5924)
=> Add name to shellcheck workflow

talpid-routing/src/unix/mod.rs, talpid-routing/src/windows/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5933)
=> Minor Unix route manager cleanup

talpid-core/src/tunnel_state_machine/mod.rs, talpid-routing/src/unix/mod.rs, talpid-routing/src/windows/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5934)
=> Remove `block_on` from route manager drop impl

test/Cargo.lock, test/test-manager/Cargo.toml, test/test-manager/src/tests/mod.rs, test/test-manager/test_macro/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5943)
=> Update test-manager dep `inventory`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/transitions/LoginTransition.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5948)
=> Add transition to DeviceListScreen

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/PrivacyDisclaimerViewModel.kt
Restores the behavior that were removed when we migrated to compose destinations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5957)
=> Fix privacy policy link not working

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt
Fixed by copying the internal implementation of `BasicTextField` but with a slight adjustment so that we get the expected cursor behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5953)
=> Fix endless loop on gboard on TV for custom text fields

CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
This PR aims to update the changelog for the upcoming `android/2024.1-beta1`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5972)
=> Update changelog for android/2024.1-beta1

CHANGELOG.md, talpid-core/src/resolver.rs
Fix DES-680.
Related: #5947, #5949.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5950)
=> Restart DNS resolver if it unexpectedly dies

ios/MullvadSettings/SettingsManager.swift
Deleting the custom lists upon every logout or app reinstallation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5970)
=> Remove custom list on reset settings

ios/MullvadVPN/Coordinators/AccountCoordinator.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5984)
=> Fix paragraphs spacing in alert views

ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme, ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift, ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift, ios/MullvadVPN/TunnelManager/StopTunnelOperation.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift, ios/PacketTunnelCore/Actor/ObservedState.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5988)
=> Remove debug statements

mullvad-daemon/src/cli.rs, mullvad-daemon/src/logging.rs, mullvad-daemon/src/main.rs
Refactor code in the daemon that handles cli boolean flags that trigger oneshot commands (i.e. commands that do something then exit, instead of starting the daemon like normal).
The flags are
- `--initialize-early-boot-firewall` (linux)
- `--run-as-service` (windows)
- `--register-service` (windows)
- `--launch-daemon-status` (macos)
This fixes issue where daemon uniqueness check interfered with these commands, and also makes the control flow and logging behaviour in main.rs a bit more obvious.
TODO: Test that CLI flags and logging is working as intended on
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5978)
=> Refactor daemon oneshot commands

.github/workflows/cargo-audit.yml, test/Cargo.lock, test/deny.toml
Upgrade `plist` to remedy  `RUSTSEC-2023-0081`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6019)
=> Upgrade `plist` to address `RUSTSEC-2023-0081`

mullvad-daemon/src/main.rs, mullvad-daemon/src/version.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6003)
=> Warn when running --launch-daemon-status on dev

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/CheckboxCell.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6057)
=> Fix provider text color

mullvad-relay-selector/src/relay_selector/mod.rs
Bridges are no longer filtered out solely based on their distance from the 'origin'. Instead, we simply order them by distance from 'origin' and consider the closest 5 bridges. They will still be assigned weights proportional to the distance from the origin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6082)
=> Fix all bridges being discarded before selection

test/connection-checker/src/main.rs, test/connection-checker/src/net.rs, test/socks-server/src/lib.rs, test/test-manager/src/main.rs, test/test-manager/src/network_monitor.rs, test/test-manager/src/run_tests.rs, test/test-manager/src/tests/account.rs, test/test-manager/src/tests/dns.rs, test/test-manager/src/tests/install.rs, test/test-manager/src/tests/relay_ip_overrides.rs, test/test-manager/src/tests/settings.rs, test/test-manager/src/tests/test_metadata.rs, test/test-manager/src/tests/tunnel.rs, test/test-manager/src/tests/ui.rs, test/test-manager/src/vm/provision.rs, test/test-manager/src/vm/ssh.rs, test/test-manager/src/vm/tart.rs, test/test-manager/src/vm/update.rs, test/test-manager/test_macro/src/lib.rs, test/test-runner/src/forward.rs, test/test-runner/src/logging.rs, test/test-runner/src/sys.rs
Manually run the nightly formatter on the integration test folder, which mainly affects import statements and comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6093)
=> Run nighlty formatter on tests folder

README.md
This PR aims to update the `README.md` copyright year.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6076)
=> Update README copyright

.github/workflows/check-changelog.yml, CHANGELOG.md, android/CHANGELOG.md, audits/2022-10-14-atredis.md, prepare-release.sh
This PR aims to add a new Android specific `android/CHANGELOG.md` and move all historic changes to it.
TODO:
TODO after merging:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6098)
=> Move android changes to `android/CHANGELOG.md`

android/config/dependency-check-suppression.xml, android/test/test-suppression.xml
Suppressing since the affected function isn't used in this project. No upstream fixes are available at the time of adding this suppression.
https://nvd.nist.gov/vuln/detail/CVE-2024-23080
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6118)
=> Suppress Joda-Time CVE-2024-23080

android/src/main/play/listings/en-US/full-description.txt
This PR makes sure the F-Droid description is aligned with the one used in the Play store. The only difference is that we here refer to our website rather than in-app purchases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6117)
=> Update F-Droid description

Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6137)
=> Remove duplicate workspace member

gui/locales/messages.pot, gui/src/renderer/components/WireguardSettings.tsx
This PR removes the beta label on the DAITA setting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6139)
=> Remove DAITA beta label

ios/MullvadVPNTests/LogRotationTests.swift
This PR fixes formatting issues
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6138)
=> Fix formatting issues with swiftformat

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
This PR aims to update the changelog, changes dialog and F-Droid metadata for the upcoming `android/2024.2-beta1`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6142)
=> Update changelog for android/2024.2 beta1

.github/workflows/daemon.yml, windows/driverlogic/driverlogic.vcxproj, windows/driverlogic/driverlogic.vcxproj.filters, windows/driverlogic/src/driverlogic.cpp, windows/driverlogic/src/wireguard.h
Fix DES-855.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6146)
=> Point to new wireguard header in driverlogic

android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/RelayListUseCase.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
Bug introduced in a previous PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6147)
=> Fix missing cities and relays in custom list

CHANGELOG.md, Cargo.lock, talpid-core/Cargo.toml, talpid-core/src/firewall/macos.rs
Fix DES-794.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6145)
=> Flush PF states on tunnel state transitions

.github/workflows/clippy.yml, .github/workflows/daemon.yml, .github/workflows/desktop-e2e.yml, .github/workflows/rust-unused-dependencies.yml, .github/workflows/testframework-clippy.yml, .github/workflows/testframework.yml
Fix DES-904.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6170)
=> Bump setup-protoc action to v3

talpid-core/src/split_tunnel/windows/path_monitor.rs
Fix DES-33.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6171)
=> Add TODO comment about removing symlink monitor

mullvad-daemon/src/lib.rs, mullvad-daemon/src/version_check.rs
Some minor code cleanup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6150)
=> Refactor version checker slightly

Cargo.lock, Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-daemon/src/migrations/mod.rs, mullvad-management-interface/src/types/conversions/account.rs, mullvad-management-interface/src/types/conversions/device.rs, mullvad-management-interface/src/types/conversions/wireguard.rs, mullvad-paths/src/windows.rs, talpid-core/src/dns/windows/iphlpapi.rs, talpid-core/src/split_tunnel/windows/windows.rs, talpid-openvpn/src/wintun.rs, talpid-types/Cargo.toml, talpid-types/src/net/wireguard.rs, talpid-wireguard/Cargo.toml, talpid-wireguard/src/ping_monitor/icmp.rs, talpid-wireguard/src/wireguard_nt/mod.rs, test/Cargo.lock, test/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6177)
=> Run `cargo update`, fix base64 + chrono

CHANGELOG.md, dist-assets/linux/after-install.sh, dist-assets/linux/after-remove.sh, dist-assets/linux/apparmor_mullvad, gui/tasks/distribution.js
Disable restrictions for unprivileged user namespaces. See [this](https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890) for details.
Fix #6128.
Fix DES-924.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6196)
=> Add apparmor profile on Ubuntu 24.04 or later

.github/workflows/android-app.yml
This PR aims to fix the e2e test report dir.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6176)
=> Fix e2e report dir

android/config/dependency-check-suppression.xml, android/test/test-suppression.xml
This PR aims to update our suppression rules.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6225)
=> Update android supressions

build.sh, ci/buildserver-build.sh, gui/tasks/distribution.js
This PR updates the build scripts to use our new Windows signing certificate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6226)
=> Update build scripts to use new windows signing cert

gui/tasks/distribution.js
This stops CI from trying to publish artifacts. Recently, this caused some jobs to fail. For example: https://github.com/mullvad/mullvadvpn-app/actions/runs/9064425611/job/24902664712#step:6:587
Fix DES-929
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6249)
=> Disable publishing of electron-builder artifacts

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
This PR fixes some UI quirks when expanding and retracting list items in the vpn settings view. Not perfect, but a lot better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6265)
=> Improve UI of list items in vpn settings view

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6267)
=> Make vpn settings page not crash in release mode

ios/CHANGELOG.md, ios/Configurations/Version.xcconfig
Bump changelog and version number.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6268)
=> Bump changelog and version number.

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6269)
=> Remove spacing in VPN settings page

.github/workflows/ios-screenshots-tests.yml, .github/workflows/ios-validate-build-schemas.yml, ios/BuildInstructions.md, ios/MullvadVPNUITests/README.md
This PR adds `protobuf` installation where required for our CI environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6285)
=> Add required protobuf dependencies

CHANGELOG.md, gui/tasks/distribution.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6234)
=> Include apisocks5 in application bundle

gui/locales/messages.pot, gui/src/main/daemon-rpc.ts, gui/src/shared/notifications/error.ts, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/states.rs, talpid-core/src/split_tunnel/macos/mod.rs, talpid-core/src/split_tunnel/macos/process.rs, talpid-core/src/split_tunnel/macos/tun.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/mod.rs, talpid-types/src/tunnel.rs
Fix: DES-992.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6289)
=> Add error state cause for full disk access error

android/BuildInstructions.md
I also updated the suggested cmd tools to the latest version at the same time (and tested them).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6290)
=> Fix filename in Android build instructions

ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift
It's all in the title.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6297)
=> Use the same DNS blockers order as the other clients

gui/src/main/macos-split-tunneling.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6294)
=> Ignore non-existent directories when listing apps for split tunneling

test/test-manager/src/tests/split_tunnel.rs
Fix DES-1001.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6291)
=> Run UI tests for macOS split tunneling

mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs
Tiny PR to fix the formatting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6303)
=> Run cargo fmt

dist-assets/pkg-scripts/postinstall
Fix DES-1009.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6307)
=> Remove noise from postinstall.log

building/linux-container-image.txt
Needed for building maybenot-ffi. Follow up for #6273
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6274)
=> Swap the Linux build container to the one with make

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6322)
=> Update package dependency to include all routes in network settings

test/test-manager/src/tests/account.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/install.rs, test/test-manager/src/tests/mod.rs, test/test-manager/src/tests/ui.rs
Fails somewhat often: https://github.com/mullvad/mullvadvpn-app/actions/runs/9375970495/job/25815088882#step:4:1278
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6323)
=> Retry DNS lookups in test manager

mullvad-types/src/constraints/constraint.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6329)
=> Add `Constraint::and_then` method

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6318)
=> Prevent loading when logging out

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt
- Always shows the account history if present
- Disables clear history & account history while logging in.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6340)
=> Always show account history on login screen if present

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, gui/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6345)
=> Update auto-connect for TV users to legacy and update description

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6350)
=> Prevent title from being multiple lines

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6351)
=> Fix text overflow and max lines on connection screen

android/lib/resource/src/main/res/values/strings_non_translatable.xml
This PR aims to update the in-app guide URL to the lockdown documentation on our website.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6354)
=> Update lockdown guide URL

README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6337)
=> Add macOS split tunneling to features table

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6355)
=> Update changelog for android/2024.3 beta1

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CustomListNameTextField.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6368)
=> Add auto-capitalization to custom list name input

gui/locales/relay-locations.pot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6373)
=> Update translations 2024-06-18

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6379)
=> Fix navigation mixup in settings

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelState.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6384)
=> Ignore case when ordering split tunneling apps

talpid-routing/src/unix/macos/interface.rs
Fix a regression due to 9c257c424a5ed4d531fec8e813f44a4ede0baaee.
Close DES-1035.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6367)
=> Fix interface IPv6 address filtering

mullvad-daemon/src/lib.rs
Refactor away this small state machine and simplify shutdown logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6386)
=> Remove `DaemonExecutionState`

mullvad-daemon/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6394)
=> Fix on_prepare_restart

mullvad-daemon/src/lib.rs
This is not only logged during system shutdown.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6395)
=> Fix log during shutdown

README.md
Add new DAITA row to the feature table, and check the box for windows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6382)
=> Add DAITA to feature table

android/fdroid-build/init.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6396)
=> Fix path to goruntime patch

.github/workflows/desktop-e2e.yml, mullvad-relay-selector/src/relay_selector/query.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/tunnel.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6392)
=> Add simple e2e test for connecting with DAITA

README.md
Fix DES-845
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6399)
=> Add DAITA for Linux to feature table

wireguard-go-rs/libwg/libwg_daita.go
Fix DES-1054.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6400)
=> Pass padding and blocking byte parameters from libwg

android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/Delay.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditApiAccessMethodViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModelTest.kt
Also replace the login delay code with this function since the behavior is identical.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6387)
=> Add delay at least wrapper and apply to test api method

test/scripts/build-runner-image.sh
This is a temporary solution until we're able to transfer the files directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6401)
=> Increase Windows test image size

.github/workflows/desktop-e2e.yml, test/README.md, test/container-run.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6258)
=> Run integration tests on Fedora 40

README.md
Add a tick for quantum resistance and WireGuard over TCP for iOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6404)
=> Update feature matrix for iOS

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/DeviceUpdateError.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6426)
=> Handle status exception for updateDevice

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LifecycleExtensions.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6429)
=> Fix broken dropUnlessResumed

android/.gitignore
New data folder added with K2 that should be ignored. See https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6427)
=> Add .kotlin to gitignore

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6431)
=> Fix logs card color regression

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplashScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6436)
=> Add missing inclusive

.github/workflows/android-app.yml
This PR aims to fix CI test account arguments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6432)
=> Fix test account arguments

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6441)
=> Compose crash when sending problem report

test/test-manager/src/tests/dns.rs
The DNS e2e tests all seem to [fail](https://github.com/mullvad/mullvadvpn-app/actions/runs/9865964454). Seems like it fails to negotiate an ephemeral peer, which makes sense since we are connecting to a local wg relay without that functionality for those tests.
At some point, the local wg relay should be updated with the same functionality as the regular relays (to ensure a realistic testing environment). That would be a bigger task though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6457)
=> Fix dns e2e tests on linux

CHANGELOG.md
The mentioned fix is not included in the beta release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6492)
=> Move unreleased fix to `Unreleased` section of changelog

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6504)
=> Fix initial expands

mullvad-api/src/lib.rs, mullvad-management-interface/src/client.rs, mullvad-relay-selector/src/relay_selector/detailer.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/src/relay_selector/query.rs, mullvad-types/src/constraints/mod.rs, mullvad-types/src/version.rs, talpid-wireguard/src/connectivity_check.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6506)
=> Fix `doc list item missing indentation`

ios/MullvadVPN/View controllers/VPNSettings/CustomDNSCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift
This PR updates DNS copy to follow what the desktop client has.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6495)
=> Follow desktop copy for DNS warnings

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt
Related to: https://github.com/raamcosta/compose-destinations?tab=readme-ov-file#--do-not-call-navcontrollernavigate-function-anywhere
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6526)
=> Fix crash when removing the NoDaemonScreen

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6527)
=> Prepare android 2024.4 beta1

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6531)
=> Add "DAITA" to macOS in feature table

test/Cargo.toml, test/test-manager/src/tests/helpers.rs, test/test-manager/test_macro/src/lib.rs, test/test-rpc/src/client.rs
* Lower priority for lint group
* doc list item missing indentation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6528)
=> Rust verson 1.80 fixes for e2e tests

ios/MullvadVPN/Views/StatusActivityView.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6525)
=> Fix the spinner spinning round like a record

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/AppVersionInfoRepository.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/GetVersionInfoError.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6537)
=> Allow error on getVersionInfo

mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs
Propagate the underlying error which caused the version check to fail, instead of converting it to an Option::None and constructing an ad-hoc status message in case it did fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6536)
=> Handle version check error more loudly

android/CHANGELOG.md, android/app/src/main/AndroidManifest.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6538)
=> Enable predictive back animations

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6549)
=> Prevent calling unbind when privacy policy is not accepted

ios/MullvadVPNUITests/README.md
Added more information to the end to end tests README(`ios/MullvadVPNUITests/README.md`). To review this it would be great if looking over the README as a whole, not only what was added by this PR. 
The aim is for the README to explain everything one would need to know to set up a runner, new test device, set up test environment locally and develop tests. 
Some things in this README are introduced by https://github.com/mullvad/mullvadvpn-app/pull/6445 which has not been merged to `main` yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6446)
=> Update iOS end to end tests README

test/test-manager/src/config.rs, test/test-manager/src/main.rs
This is slightly more convenient on new setups.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6550)
=> Create test dir if it does not exist

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6557)
=> Reset the backoff and start/stop management service in proper order

CHANGELOG.md, mullvad-daemon/src/lib.rs
Steps to reproduce issue:
- Select Sweden as location
- Enable DAITA
- Disable DAITA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6572)
=> Fix blocked state on disabling DAITA

CHANGELOG.md, Cargo.lock, Cargo.toml, android/translations-converter/Cargo.toml, mullvad-api/Cargo.toml, mullvad-cli/Cargo.toml, mullvad-cli/src/cmds/status.rs, mullvad-daemon/Cargo.toml, mullvad-relay-selector/Cargo.toml, mullvad-types/Cargo.toml, mullvad-types/src/device.rs, talpid-core/Cargo.toml, talpid-types/Cargo.toml, test/Cargo.lock, test/connection-checker/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6569)
=> Add --json flag to `mullvad status`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6575)
=> Always align scrollbar to the right in view logs

wireguard-go-rs/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6578)
=> Fix conversion from libwg error codes

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
This PR aims to prepare the changelog and changes dialog for `android/2024.4-beta2`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6584)
=> Update changelog for `android/2024.4-beta2`

android/scripts/run-instrumented-tests.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6576)
=> Do not accept 0 tests passed for instrumental tests

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6585)
=> Move divider to below header

ci/ios/create-vm/README.md, ci/ios/create-vm/install-build-dependencies.pkr.hcl, ci/ios/create-vm/install-vanilla-ventura.pkr.hcl, ci/ios/create-vm/scripts/add-apple-certs.sh, ci/ios/create-vm/scripts/cleanup.sh, ci/ios/create-vm/scripts/install-brew-dependencies.sh, ci/ios/create-vm/scripts/install-brew.sh, ci/ios/create-vm/scripts/install-go.sh, ci/ios/create-vm/scripts/install-rustup.sh, ci/ios/create-vm/scripts/install-xcode.sh, ci/ios/create-vm/scripts/link-zprofile.sh, ci/ios/create-vm/scripts/run-xcode-first-launch.sh, ci/ios/create-vm/variables.pkrvars.hcl
This PR adds packer scripts that can create a VM and install Xcode on it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5359)
=> Add packer scripts to create VMs and install Xcode on them.

ci/ios/create-vm/README.md, ci/ios/create-vm/install-build-dependencies.pkr.hcl, ci/ios/create-vm/install-vanilla-ventura.pkr.hcl, ci/ios/create-vm/scripts/add-apple-certs.sh, ci/ios/create-vm/scripts/cleanup.sh, ci/ios/create-vm/scripts/install-brew-dependencies.sh, ci/ios/create-vm/scripts/install-brew.sh, ci/ios/create-vm/scripts/install-go.sh, ci/ios/create-vm/scripts/install-rustup.sh, ci/ios/create-vm/scripts/install-xcode.sh, ci/ios/create-vm/scripts/link-zprofile.sh, ci/ios/create-vm/scripts/run-xcode-first-launch.sh, ci/ios/create-vm/variables.pkrvars.hcl
Redo the PR (no changes to the content) for fixing git timeline history
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6598)
=> Add packer scripts to create VMs and install Xcode on them

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
Copy of https://github.com/mullvad/mullvadvpn-app/pull/6585
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6599)
=> Move divider to below header (Fix)

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SelectLocationUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt, android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, gui/locales/messages.pot
Copy of: https://github.com/mullvad/mullvadvpn-app/pull/6589
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6600)
=>  Show the name of the custom list in remove location bottom sheet (Fix)

mullvad-exclude/src/main.rs
Fix new rustc warning for `unreachable_patterns`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6597)
=> Remove unreachable pattern

mullvad-jni/src/talpid_vpn_service.rs
Tiny refactor that splits `try_sending_random_udp` into a few functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6595)
=> Refactor TalpidVpnService JNI

CHANGELOG.md, android/CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6619)
=> Move changelog entry for Android

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6620)
=> Fix expanded select location items collapsing on resume

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/FromDomain.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6649)
=> Set empty shadowsocks port when setting obfuscation settings

CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6659)
=> Fix changelog for 2024.5-beta1

building/android-container-image.txt
This PR aims to start building the Android app using the updated build container: `mullvadvpn-app-build-android:63e6d7303`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6665)
=> Start building with mullvadvpn-app-build-android:63e6d7303

talpid-wireguard/src/wireguard_go/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6646)
=> Remove unwraps in start_daita

CHANGELOG.md, docs/relay-selector.md, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/tests/relay_selector.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6674)
=> Add Shadowsocks to retry order

android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6687)
=> Fix resource dependency

android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, gui/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6681)
=> Update split tunneling description to include block connections without vpn

.github/workflows/android-validate-gradle-wrapper.yml
This PR aims to add a gradle wrapper validation action.
Fixes: DROID-774
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6705)
=> Add action to validate gradle wrapper

gui/src/renderer/components/KeyboardNavigation.tsx, gui/src/renderer/components/main-view/ConnectionPanel.tsx
This PR adds a `BackAction` to the connection panel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6708)
=> Add ConnectionPanel back action

android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationManager.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/tunnelstate/TunnelStateNotificationProvider.kt, android/tile/src/main/kotlin/net/mullvad/mullvadvpn/tile/MullvadTileService.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6709)
=> Fix toggletunnel crash in tile

CHANGELOG.md, gui/locales/messages.pot, gui/src/main/daemon-rpc.ts, gui/src/main/default-settings.ts, gui/src/renderer/components/AppRouter.tsx, gui/src/renderer/components/Shadowsocks.tsx, gui/src/renderer/components/UdpOverTcp.tsx, gui/src/renderer/components/WireguardSettings.tsx, gui/src/renderer/components/cell/Selector.tsx, gui/src/renderer/components/cell/SideButton.tsx, gui/src/renderer/components/cell/index.ts, gui/src/renderer/components/cell/styles.ts, gui/src/renderer/components/select-location/CustomLists.tsx, gui/src/renderer/components/select-location/LocationRow.tsx, gui/src/renderer/components/select-location/LocationRowStyles.tsx, gui/src/renderer/components/select-location/SpecialLocationList.tsx, gui/src/renderer/lib/routes.ts, gui/src/renderer/redux/settings/reducers.ts, gui/src/shared/daemon-rpc-types.ts, gui/test/e2e/installed/state-dependent/obfuscation.spec.ts, gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts
This PR adds settings for WireGuard over Shadowsocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6706)
=> Add WireGuard over Shadowsocks settings to GUI

mullvad-cli/src/cmds/proxies.rs, mullvad-daemon/src/api.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/migrations/device.rs, mullvad-problem-report/src/main.rs, talpid-dbus/src/network_manager.rs, talpid-openvpn/src/lib.rs, talpid-tunnel/src/tun_provider/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6716)
=> Fix nightly `rustc` and `clippy` warnings

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6718)
=> Update changelog for Android 2024.4

ios/Configurations/Version.xcconfig
This PR updates the marketing version to the latest marketing version we released on the app store
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6728)
=> Update the Marketing version to the latest release

android/gradle/osv-scanner.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6735)
=> Bump agp related vulnerabilities one month

.github/PULL_REQUEST_TEMPLATE.md
We already have as an internal rule that we should get better and better at adding tests. And that no new feature is regarded as complete without tests. This just codifies this even more by updating the pull request template (that has not received any love in a long time)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6730)
=> Add to the PR template that new features require tests

ci/publish-app-to-repositories.sh
This script was only publishing the app to *one* repository. Either stable or beta. This meant that whenever we published a stable app, superseding the previous beta, the stable repos would receive it, but the beta repos would not. So people on the beta repos would be stuck on the beta, which would be older than the stable release.
This change makes it so that `publish-app-to-repositories.sh` always publish the app to the beta repos. And then conditionally, if it's a stable release, *also* publishes it to the stable repositories.
I extracted most of the logic into a function. To make it easier to call it twice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6737) …
=> Fix bug in publish-app-to-repositories so stable are published to beta

CHANGELOG.md
I forgot to add a changelog entry for the main view redesign and feature indicators. This PR adds that to the changelog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6726)
=> Add feature indicators to changelog

deny.toml
Temporarily silence RUSTSEC-2024-0370. See https://github.com/mullvad/mullvadvpn-app/pull/6748 for details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6749)
=> Silence RUSTSEC-2024-0370

android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6746)
=> Try catch establish in createTun

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelState.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SetAutoConnectError.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/Settings.kt
Note that this will not be merged into main yet until we have released `2024.4`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6720)
=> Remove auto-connect feature from ui

.github/workflows/cargo-audit.yml
Related: #6749, #6755
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6765)
=> Ignore RUSTSEC-2024-0370 in audit workflow

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
When enabling DAITA, users should be made aware that their battery and network data usage will increase significantly.
The copy has been updated in Figma, we should add the text to the popups now.
https://www.figma.com/design/Ajrzm7teuANVDEdAZPPXxR/IOS-765-Adapt-DAITA-UI-elements-for-iOS?node-id=2640-11003&t=bQZJdrMeIrP2qAWL-4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6773)
=> Update info about data and battery usage

android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6780)
=> Fix crash in billing repository

Cargo.lock, tunnel-obfuscation/Cargo.toml, tunnel-obfuscation/src/shadowsocks.rs
Currently, reconnecting fails on Android because it tries to connect inside the tunnel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6781)
=> Run `VpnService.protect()` on Shadowsocks socket before connecting

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6791)
=> Fix permission dialog launch

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/WireguardCustomPortDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WireguardCustomPortDialogViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6779)
=> Refactor port dialog to use a view model

android/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6805)
=> Update changelog with DAITA

CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6807)
=> Add DAITA Smart Routing to changelog

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt
Fix the IME hiding the text view input on the report problem screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6796)
=> Fix report problem screen text view scroll

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/PrivacyDisclaimerViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6795)
=> Prevent multiple clicks on accept in privacy screen

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ConnectUiStatePreviewParameterProvider.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6814)
=> Fix connect screen ui parameters

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/FeatureIndicator.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6817)
=> Align feature indicator order with other platforms

talpid-wireguard/src/lib.rs, talpid-wireguard/src/obfuscation.rs
There is a lot left to do here, but this lifts some of the obfuscation setup out into its own module and hides much of it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6816)
=> Refactor WG obfuscation setup

android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ChangelogRepository.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/repository/ChangelogRepositoryTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6824)
=> Add support for hypens in a changelog entry

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6823)
=> Update changelog for android/2024.5-beta1

ios/MullvadVPN/View controllers/Settings/SettingsDNSTextCell.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6812)
=> Make VPN settings DNS edit respect dark mode

ios/BuildInstructions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6827)
=> Bump required Go version in ios/BuildInstructions.md

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ObfuscationModeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Chevron.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6820)
=> Refactor and fix chevron

android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, gui/locales/messages.pot
Change all references to screens in the app text are changed from bold text to quotation marks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6818)
=> Use quotation marks instead of bold text

talpid-wireguard/src/lib.rs
Generalize error that could occur while negotiating an ephemeral peer. The old error only considered that one could negotiate a PQ secure psk, but we have since added DAITA to the request.
Fixes: DES-1260
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6829)
=> Generalize error that could occur while negotiating an ephemeral peer

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6845)
=> Fix select server navigation on TV

android/docker/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6838)
=> Update android container

android/app/build.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6854)
=> Fix bundle task binary path

talpid-openvpn/src/wintun.rs
This is an attempt to fix the elusive "Failed to create Wintun adapter" bug. Our workaround is to open an existing adapter with name "Mullvad" as a fallback. We cannot reproduce the bug, so our only option is to release this patch and investigate if the bug-reports for the issue stop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6840)
=> Add fallback when failing to create `wintun` adapter

android/BuildInstructions.md, android/app/build.gradle.kts, android/buildSrc/src/main/kotlin/Versions.kt, android/docs/BuildInstructions.macos.md, android/lib/billing/build.gradle.kts, android/lib/common-test/build.gradle.kts, android/lib/common/build.gradle.kts, android/lib/daemon-grpc/build.gradle.kts, android/lib/endpoint/build.gradle.kts, android/lib/intent-provider/build.gradle.kts, android/lib/map/build.gradle.kts, android/lib/model/build.gradle.kts, android/lib/payment/build.gradle.kts, android/lib/resource/build.gradle.kts, android/lib/shared/build.gradle.kts, android/lib/talpid/build.gradle.kts, android/lib/theme/build.gradle.kts, android/service/build.gradle.kts, android/test/arch/build.gradle.kts, android/test/common/build.gradle.kts, android/test/e2e/build.gradle.kts, android/test/mockapi/build.gradle.kts, android/tile/build.gradle.kts, building/android-container-image.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6837)
=> Update ndk to version 27b

.github/workflows/desktop-e2e.yml
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/11014925524/job/30587175360
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6857)
=> Add Ubuntu 24.10 VM to end-to-end tests

.github/workflows/desktop-e2e.yml, test/docs/BUILD_OS_IMAGE.md
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/11010152970/job/30571785625
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6855)
=> Add Fedora 41 beta VM to test VMs

.github/workflows/android-app.yml
Run local mockapi tests 10 times nightly to catch test flakiness earlier.
These changes are difficult to try out before merge:ing the PR. Have verified that specifying number of test runs when manually triggering works, and verified that mockapi tests run once when triggered by PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6877)
=> Run mockapi tests 10 times nightly

scripts/localization
This PR updates the localization script to also upload translations (in addition to sources) when the `upload` subcommand is run. I've tested this against Crowdin and it seems to work great!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6894)
=> Upload translations when we upload sources to crowdin

Cargo.lock, Cargo.toml, test/Cargo.toml
resolves #6896 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6899)
=> Bump tonic to 0.12.3

test/Cargo.lock
Oops
resolves #6900 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6901)
=> Bump tonic to 0.12.3 in test/Cargo.lock also

ios/MullvadSettings/AccessMethodRepository.swift
I am presuming this is all that is required to get encrypted DNS working in release?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6909)
=> Enable encrypted DNS proxy in release

CHANGELOG.md
These were incorrectly placed under the release header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6906)
=> Move changelog entries

android/config/dependency-check-suppression.xml, android/gradle/osv-scanner.toml
Fixes: DROID-1405
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6927)
=> Suppress CVE-2024-47554

README.md
We've got DAITA and multihop on iOS - yet we did not update the feature matrix in the readme. So here I am adding the two ticks for these features.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6931)
=> Update feature table for iOS with DAITA and mh

CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6939)
=> Update changelog entry on apple services fix to mention OpenVPN

ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewController.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6907)
=> Fix title not having opaque background in relay filter view

ios/MullvadVPN/View controllers/DeviceList/DeviceRowView.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6926)
=> Increase touch target size the 'log out device' button

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DaitaConfirmationDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DiscardChangesDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/InfoConfirmationDialog.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6947)
=> Create info confirm dialog base component

android/gradle/verification-metadata.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6949)
=> Add trust for gradle wrapper src

android/CHANGELOG.md, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6948)
=> Fix re-subscribe crash

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ConnectUiStatePreviewParameterProvider.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/TunnelStatePreviewData.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/RelayListRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/WireguardConstraintsRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/FromDomain.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/GeoIpLocation.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/WireguardConstraints.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6945)
=> Add support for mutlihop communication with daemon

.github/workflows/android-static-analysis.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6971)
=> Fix image to ubuntu 22.04

ios/Configurations/Api.xcconfig.template
This PR uses a slightly different IP address to temporarily help the UITests run smoothly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6968)
=> Use a different IP temporarily to fix UITests

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6975)
=> Always set feature indicator to empty list

gui/locales/messages.pot, gui/src/renderer/components/DaitaSettings.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6961)
=> Update DAITA info texts

BuildInstructions.md
What the title says: minor improvements to the build instructions.
To have correct instructions for external users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6973)
=> Docs - Minor improvements to build instructions

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7005)
=> Update changelog for `android/2024.7`

ios/MullvadRustRuntime/include/mullvad_rust_runtime.h
This PR adds missing comments in an autogenerated file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7014)
=> Add missing header comment in autogenerated file

.github/workflows/desktop-e2e.yml, test/scripts/ci-runtests.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7019)
=> Update Rust before running E2E tests

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/connectioninfo/ConnectionDetailPanel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/connectioninfo/FeatureIndicatorsPanel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
Fixes animations for feature indicators where it could flicker when connecting in certain conditions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7026)
=> Fix feature indicator flicker

talpid-wireguard/src/lib.rs, talpid-wireguard/src/obfuscation.rs, tunnel-obfuscation/src/lib.rs, tunnel-obfuscation/src/shadowsocks.rs, tunnel-obfuscation/src/udp2tcp.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7016)
=> Take obfuscation overhead into account when setting MTU

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7033)
=> Update changelog for android `2024.8-beta1`

talpid-core/src/firewall/macos.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7011)
=> Add comment about not flushing LAN pf states

gui/locales/messages.pot, gui/src/main/default-settings.ts, gui/src/renderer/components/select-location/SelectLocation.tsx, gui/src/renderer/components/select-location/SelectLocationStyles.tsx, gui/test/e2e/mocked/select-location.spec.ts
This PR disables entry-selection when both DAITA and multihop is enabled unless "Direct only" is enabled. A test is also included to test this behaviour.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7031)
=> Implement multihop daita entry selection GUI

android/app/src/main/AndroidManifest.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6991)
=> Set mullvad vpn service exported to false

talpid-core/src/tunnel/mod.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-wireguard/src/lib.rs
Fix DES-1354.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7046)
=> Clamp tunnel MTU after obfuscation overhead adjustment

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/UriHandlerExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/ContextExtensions.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7054)
=> Fail with log if device doesn't have a browser

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Keyboard.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7047)
=> Use KeyboardType.Number on Amazon FireStick

CHANGELOG.md
Add changelog entry for #7042 since it does affect desktop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7075)
=> Mention roaming fix in changelog

android/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7088)
=> Update changelog with Encrypted DNS Proxy

CHANGELOG.md
Follow-up to #7030 and #7083.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7097)
=> Mention maybenot 2.0.1 in changelog

README.md
This PR updates the minimum iOS version specified in the README file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7099)
=> Update minimum iOS version in the README file

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ExternalActionButton.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/AccountUiStatePreviewParameterProvider.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt
Fixes: DROID-1473
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7066)
=> Show loading spinner when clicking Manage account

android/gradle/osv-scanner.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7094)
=> Update osv scanner ignore dates and remove outdated ignores

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/connectioninfo/ConnectionDetailPanel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/StringConstant.kt, android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, gui/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7110)
=> Fix connection detail translations

ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7112)
=> Fix relay tests

android/config/dependency-check-suppression.xml
Pushing suppression since the issue hasn't been addressed upstream and we're still not affected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7111)
=> Push suppression of CVE-2022-24329

.github/workflows/android-audit.yml, android/scripts/update-lockfile.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7124)
=> Exclude maybenot bundle check in lockfile script

CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7142)
=> Add changelog entry for "Disable fault handler in release builds"

ios/MullvadVPN/View controllers/SelectLocation/DAITAInfoView.swift
Updating copy for the entry selection view when DAITA+Multihop are enabled but _Direct only_ is not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7154)
=> Update copy in entry selection

android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryInAppNotificationUseCase.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryInAppNotificationUseCaseTest.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryTickerFlow.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7145)
=> Fix account expiry in app notif not resetting

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7156)
=> Fix in app notification constraint layout

android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/OutOfTimeUseCaseTest.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ErrorStateCause.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7167)
=> Fix incorrect parsing of auth failed error

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7164)
=> Fix extra top bar showing up on some devices

android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/ErrorStateExtension.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ErrorStateCause.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7170)
=> Clarify expired account message

deny.toml, osv-scanner.toml, test/deny.toml, test/osv-scanner.toml
A very small PR that add notes about what files need to be kept in sync when silecing CVEs. Lex #7157/#7163
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7180)
=> How to silence RUSTSEC advisories

test/connection-checker/src/cli.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7194)
=> Fix connection checker CLI

android/gradle/osv-scanner.toml
Updated ignores so that they follow the template.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7193)
=> Clarify osv-scanner ignores

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7203)
=> Use last known location instead of null when tunnel state is error

README.md
The current instructions don't work when SIP is enabled.
Fix DES-1306.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7205)
=> Update instructions for setting environment vars on macOS

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7224)
=> Move snackbar above import button in server ip override

android/config/dependency-check-suppression-agp-fixes.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7217)
=> Suppress CVE-2024-47535

ios/CHANGELOG.md, ios/Configurations/Version.xcconfig
Updating changelog and version as we have released 2024.10 already.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7235)
=> Update changelog and iOS version

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7246)
=> Fix custom Wireguard port not being persisted

docs/known-issues.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7243)
=> Add MLLVD-CR-24-03 as known issue of Android

desktop/packages/mullvad-vpn/src/renderer/components/select-location/SelectLocationContainer.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7259)
=> Fix hidden Entry view when using bridge mode

.github/workflows/daemon.yml, windows/nsis-plugins/src/cleanup/cleanup.vcxproj, windows/nsis-plugins/src/log/log.vcxproj
This works around the linker errors until this issue has been resolved in rustc/cc: https://github.com/rust-lang/cc-rs/issues/1308
Fix DES-1511
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7262)
=> Fix linker error in `build-windows-modules.sh`

android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/ConnectPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/Page.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/PrivacyPage.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LoginTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7270)
=> Implement basic of page object pattern

android/lib/billing/build.gradle.kts, android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt, android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepository.kt, android/lib/billing/src/test/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepositoryTest.kt, android/lib/billing/src/test/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingRepositoryTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7269)
=> Add check for empty play purchase payment token

ios/Shared/LaunchArguments.swift
This PR fixes UI Tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7275)
=> Fix UITest builds

desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json, desktop/packages/mullvad-vpn/src/renderer/components/Accordion.tsx, desktop/packages/mullvad-vpn/src/renderer/components/Filter.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SelectLanguage.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7274)
=> Upgrade styled-components to 6.1.13

desktop/packages/mullvad-vpn/src/renderer/components/ApiAccessMethods.tsx, desktop/packages/mullvad-vpn/src/renderer/components/DaitaSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx, desktop/packages/mullvad-vpn/src/renderer/components/MultihopSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SettingsHeader.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettingsStyles.tsx, desktop/packages/mullvad-vpn/src/renderer/components/cell/Container.tsx, desktop/packages/mullvad-vpn/src/renderer/components/common/layout/Flex.tsx, desktop/packages/mullvad-vpn/src/renderer/components/common/layout/Layout.tsx
Use spacing tokens in multihop, api access and split tunneling settings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7281)
=> Use spacing tokens in multihop, api access and split tunneling settings

desktop/packages/mullvad-vpn/scripts/osv-scanner.toml
Extend ignore for CVEs in scripts folder
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7286)
=> Extend ignore for CVEs in scripts folder

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
Address a warning in Google Play console warning us not to use the legacy way of enables edge to edge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7306)
=> Use new enableEdgeToEdge helper function

mullvad-types/src/wireguard.rs
To align android behaviour with all other platforms now that multihop also works on android.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7305)
=> Set direct only default to false on android

desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7315)
=> Update mocha to 10.8.2

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/InformationComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/Udp2TcpSettingsScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7317)
=> Fix click action on headers in obfuscation sub-settings screens

desktop/packages/mullvad-vpn/locales/da/messages.po, desktop/packages/mullvad-vpn/locales/de/messages.po, desktop/packages/mullvad-vpn/locales/es/messages.po, desktop/packages/mullvad-vpn/locales/fi/messages.po, desktop/packages/mullvad-vpn/locales/fr/messages.po, desktop/packages/mullvad-vpn/locales/it/messages.po, desktop/packages/mullvad-vpn/locales/ja/messages.po, desktop/packages/mullvad-vpn/locales/ko/messages.po, desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/locales/my/messages.po, desktop/packages/mullvad-vpn/locales/nb/messages.po, desktop/packages/mullvad-vpn/locales/nl/messages.po, desktop/packages/mullvad-vpn/locales/pl/messages.po, desktop/packages/mullvad-vpn/locales/pt/messages.po, desktop/packages/mullvad-vpn/locales/ru/messages.po, desktop/packages/mullvad-vpn/locales/sv/messages.po, desktop/packages/mullvad-vpn/locales/th/messages.po, desktop/packages/mullvad-vpn/locales/tr/messages.po, desktop/packages/mullvad-vpn/locales/zh-CN/messages.po, desktop/packages/mullvad-vpn/locales/zh-TW/messages.po, desktop/packages/mullvad-vpn/src/renderer/components/Shadowsocks.tsx, desktop/packages/mullvad-vpn/src/renderer/components/WireguardSettings.tsx
Fix DES-1505.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7322)
=> Fix Shadowsocks port range in GUI

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7328)
=> Remove select location horizontal pager on TV

android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7334)
=> Add logging to connectivity listener

.github/workflows/android-app.yml, android/app/build.gradle.kts, android/config/lint-baseline.xml, android/config/lint.xml
This PR aims to enable the AGP lint option `checkAllWarnings` that enables a range of warnings that are disabled by default. It also generates a baseline that will be cleaned up over time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7337)
=> Enable lint option `checkAllWarnings`

desktop/packages/mullvad-vpn/locales/da/messages.po, desktop/packages/mullvad-vpn/locales/de/messages.po, desktop/packages/mullvad-vpn/locales/es/messages.po, desktop/packages/mullvad-vpn/locales/fi/messages.po, desktop/packages/mullvad-vpn/locales/fr/messages.po, desktop/packages/mullvad-vpn/locales/it/messages.po, desktop/packages/mullvad-vpn/locales/ja/messages.po, desktop/packages/mullvad-vpn/locales/ko/messages.po, desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/locales/my/messages.po, desktop/packages/mullvad-vpn/locales/nb/messages.po, desktop/packages/mullvad-vpn/locales/nl/messages.po, desktop/packages/mullvad-vpn/locales/pl/messages.po, desktop/packages/mullvad-vpn/locales/pt/messages.po, desktop/packages/mullvad-vpn/locales/ru/messages.po, desktop/packages/mullvad-vpn/locales/sv/messages.po, desktop/packages/mullvad-vpn/locales/th/messages.po, desktop/packages/mullvad-vpn/locales/tr/messages.po, desktop/packages/mullvad-vpn/locales/zh-CN/messages.po, desktop/packages/mullvad-vpn/locales/zh-TW/messages.po, desktop/packages/mullvad-vpn/src/renderer/components/DaitaSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/select-location/SelectLocation.tsx
Fix DES-1572.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7341)
=> Fix text for opening DAITA settings

prepare-release.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7347)
=> Fix incorrect version code generation

ios/MullvadVPN/Coordinators/TunnelCoordinator.swift
Temporarily remove the new connection view until more ready.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7360)
=> Temporarily remove new connection view

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx, desktop/packages/mullvad-vpn/src/shared/notifications/error.ts, desktop/packages/mullvad-vpn/src/shared/notifications/notification.ts
Fixes DES-1521
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7321)
=> Allow users to disable split tunneling when FDA is off

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7370)
=> Update changelog for `android/2024.10-beta1`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7377)
=> Fix missing animation on expand on card

CHANGELOG.md, desktop/packages/mullvad-vpn/changes.txt
Changelog and changes.txt updates for 2024.9-beta2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7376)
=> Release preparation for 2024.9 beta2

android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt
We get other events than just available and unavailable for networks, each right now results in a print. We only care for the cases were it actually changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7378)
=> Minimize logs of "number of networks"

android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/OutOfTimeUseCaseTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7383)
=> Fix flaky test in OutOfTimeUseCaseTest

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7395)
=> Update changelog for `android/2014.10-beta2`

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/CustomDnsSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/OpenVpnSettings.tsx
- Remove dialog for enabling bridge mode
- Remove dialogs for adding custom dns
- Streamline adding custom dns logic
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7359)
=> Remove dialogs for enabling bridge mode and adding custom dns

BuildInstructions.md
Remove the "Experimental" phrasing - we support Windows on Arm at this point, even though it is yet to be released. :tada:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7405)
=> Update Windows ARM build instructions

mullvad-cli/Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-problem-report/Cargo.toml, talpid-openvpn-plugin/Cargo.toml
This PR backports #7406 to the 2024.9 release branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7407)
=> [2024.9 release] Update LegalCopyright year to 2025

CHANGELOG.md, desktop/packages/mullvad-vpn/changes.txt
This PR updates the changelog & changes.txt in preparation for the next desktop release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7409)
=> [2024.9 release] Update changes

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7402)
=> Show map behind nav bar

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7422)
=> Add missing chevrons in settings

android/build.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7436)
=> Fix issue with fdroid builds in android/build.sh

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7456)
=> Fix constraint for banner

desktop/packages/mullvad-vpn/src/renderer/components/Settings.tsx
Changes order of DAITA and multihop in settings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7463)
=> Change order of Multihop and DAITA in settings

ios/CHANGELOG.md, ios/Configurations/Version.xcconfig
We released 2025.1 - so I'm bumping the changelog and the version in `main`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7471)
=> Update changelog and version after release

desktop/osv-scanner.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7477)
=> Extend ignore for CVE-2024-21528

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/Launch.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7475)
=> Add disable antivirus to troubleshooting steps

desktop/packages/mullvad-vpn/src/renderer/components/ApiAccessMethods.tsx, desktop/packages/mullvad-vpn/src/renderer/components/DaitaSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/InfoButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/VpnSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/app-navigation-header/components/AppNavigationHeaderBackButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/app-navigation-header/components/AppNavigationHeaderInfoButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/cell/Selector.tsx, desktop/packages/mullvad-vpn/src/renderer/components/cell/SideButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/main-view/ConnectionActionButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/main-view/SelectLocationButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/select-location/SpecialLocationList.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/changelog/ChangelogView.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/molecules/Button.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/molecules/IconButton.tsx
Update size and spacing of info button in daita view
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7466)
=> Update info button size and spacing

android/config/lint-baseline.xml, android/config/lint.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7485)
=> Fix lint on release

talpid-tunnel-config-client/src/classic_mceliece.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7493)
=> Restart mceliece keygen worker if it stops

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/config.json, desktop/packages/mullvad-vpn/src/renderer/components/views/changelog/ChangelogView.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7490)
=> Remove see full changelog button from changelog view

test/test-manager/docs/config.md, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/mod.rs
Also clean up the logs a bit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7501)
=> Document default test locations

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7500)
=> Update changelog for `android/2025.1`

android/build.sh, wireguard-go-rs/libwg/Android.mk
Fixes: DROID-1748
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7509)
=> Fixes needed to make the build reproducible

talpid-wireguard/src/wireguard_go/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7513)
=> Fix connection loop bug

talpid-wireguard/src/wireguard_go/mod.rs
Backport of https://github.com/mullvad/mullvadvpn-app/pull/7513 to release branch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7514)
=> backport fix connection loop

talpid-wireguard/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7523)
=> Refactor wireguard implementation picker

.github/workflows/android-app.yml
This PR aims to fix the missing default infra workflow variable. The problem was caused by the lack of default value since input variable default values are not used unless the workflow is manually triggered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7537)
=> Fix missing default infra workflow variable

desktop/packages/mullvad-vpn/test/e2e/shared/tunnel-state.ts
Link to workflow that runs the test https://github.com/mullvad/mullvadvpn-app/actions/runs/12951589297
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7521)
=> Fix `test_disconnected_state`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ConnectUiStatePreviewParameterProvider.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7543)
=> Fix blocking text color

desktop/packages/mullvad-vpn/src/renderer/components/Settings.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7552)
=> Move DAITA and Multihop to top of settings

talpid-tunnel-config-client/proto/ephemeralpeer.proto, talpid-tunnel-config-client/src/lib.rs
Fix DES-1644
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7570)
=> Set correct DAITA platform on Windows

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt
Fixes:
- Empty custom lists shown as blocked by entry/exit
- Disabled relay name not being greyed out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7571)
=> Fix incorrect display of custom list without locations

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/lib/resource/src/main/res/values/strings.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7564)
=> Remove unnecessary html parsing

android/lib/resource/src/main/res/values/strings.xml
Since the translation script uses it for the translated string files regardless if it is used for the english string files this should not matter that much, but it is nice to have it consistent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7561)
=> Use ordered string substitutions

CHANGELOG.md
Some things slipped in that shouldn't have. My bad for not catching this!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7575)
=> Fix backported changelog entries

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/DnsDialogResult.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/DeleteCustomDnsUseCase.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DnsDialogViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7567)
=> Do not show add server when custom dns server list is empty

docs/known-issues.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7589)
=> Add section on Windows Sandbox to `known-issues.md`

desktop/scripts/print-package-versions.sh
This PR adds a script that prints the package versions of the packages in the Linux repositories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7560)
=> Add script that prints the package versions in our Linux repositories

test/test-manager/src/config/vm.rs, test/test-manager/src/vm/qemu.rs, test/test-manager/src/vm/tart.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7591)
=> Make memory amount configurable in test framework

desktop/scripts/make-release
This PR adds a bash scripts that creates a draft release on GitHub.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7568)
=> Add desktop github release script

ios/MullvadVPNUITests/ConnectivityTests.swift
This PR changes the status of below tests:
- Disable testAPIReachableWhenBlocked
- enable testAPIConnectionViaBridgee
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7576)
=> Modify tests status

desktop/packages/mullvad-vpn/src/renderer/lib/foundations/variables/color-variables.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7598)
=> Fix darker blue variable assignment

.github/workflows/android-app.yml
This PR aims to address how we configure some of the e2e test workflow variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7608)
=> Fix e2e test workflow variables

ios/MullvadVPN/Coordinators/Settings/APIAccess/AboutViewController.swift, ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift
This PR fixes the copyrights in server ip override.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7604)
=> Server IP override subtitle text is the one from API access

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionView.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionViewViewModel.swift
This PR fixes the broken test in `RelayTests`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7584)
=> Fix RelayTests

CHANGELOG.md, desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json
This PR simply ports https://github.com/mullvad/mullvadvpn-app/pull/7611 to the main branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7616)
=> Upgrade Electron to 33.4.0

.github/workflows/android-app.yml
This PR aims to increase the nightly mockapi repetition to `100` times in order to quicker detect introduced flakiness.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7630)
=> Incease nightly mockapi test repeat

mullvad-cli/src/format.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7631)
=> Sort alphabetically as a fallback

android/build.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7632)
=> Add warning if CARGO_TARGETS is set

android/scripts/run-instrumented-tests.sh
This PR bumps the `androidx.test.orchestrator` to `1.5.1` (same as our gradle dependency) in our instrumentation test script. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7637)
=> Bump orchestrator in instrumentation test script

Cargo.lock, Cargo.toml, test/Cargo.lock
Fix https://rustsec.org/advisories/RUSTSEC-2025-0006. Note that this doesn't currently affect the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7642)
=> Update hickory to fix RUSTSEC-2025-0006

CHANGELOG.md, Cargo.lock, Cargo.toml, desktop/package-lock.json, desktop/packages/mullvad-vpn/gulpfile.js, desktop/packages/mullvad-vpn/package.json, desktop/packages/mullvad-vpn/src/main/index.ts, desktop/packages/mullvad-vpn/src/main/windows-split-tunneling.ts, desktop/packages/mullvad-vpn/tasks/distribution.js, desktop/packages/mullvad-vpn/tasks/scripts.js, desktop/packages/win-shortcuts/.gitignore, desktop/packages/win-shortcuts/Cargo.toml, desktop/packages/win-shortcuts/README.md, desktop/packages/win-shortcuts/eslint.config.mjs, desktop/packages/win-shortcuts/package.json, desktop/packages/win-shortcuts/src/index.cts, desktop/packages/win-shortcuts/src/index.mts, desktop/packages/win-shortcuts/src/load.cts, desktop/packages/win-shortcuts/tsconfig.json, desktop/packages/win-shortcuts/win-shortcuts-rs/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7634)
=> Implement shortcut parser for node

.github/workflows/daemon.yml
See https://github.com/actions/cache/discussions/1510
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7647)
=> Update actions/cache to v4

CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7652)
=> Update changelog with 2025.4-beta1 section

android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7645)
=> Update the first paragraph in the daita information message

desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/Progress.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/ProgressContext.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/components/ProgressFooter.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/components/ProgressPercent.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/components/ProgressRange.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/components/ProgressText.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/components/ProgressTrack.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/components/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/index.ts
Add progress component to component library
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7610)
=> Add Progress component

desktop/scripts/release/3-verify-build
This PR automates the repository version check when doing a release
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7667)
=> Automate repository version check

ios/CHANGELOG.md, ios/Configurations/Version.xcconfig
This PR backports changes from release 2025.2 to main.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7666)
=> Backport from release-2025.2

.github/workflows/android-app.yml, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt
This PR aims to fix the e2e test repeat variable usage and increase the scheduled repeat count to 10.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7670)
=> Fix scheduled e2e test repeat variable

talpid-core/src/firewall/macos.rs
This PR fixes https://github.com/mullvad/mullvadvpn-app/issues/7677
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7680)
=> Clean up NAT workaround rules when disconnecting

talpid-core/src/firewall/macos.rs
Fix Vec capacity which is set to 4 but only inserts 2 elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7682)
=> Fix capacity value

CHANGELOG.md
This was rebased incorrectly in #7651.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7684)
=> Move changelog entry

android/build.sh
This PR ensures that the `local.properties` check in the build script better handles cases when the local.properties file doesn't exist.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7695)
=> Fix `local.properties` check

.github/workflows/ios-end-to-end-tests.yml, .github/workflows/ios.yml, .gitmodules, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/build-wireguard-go.sh
as required towards locking down `maybenot-ffi` (IOS-1025)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7679)
=> Replace wireguard-apple package with a Git submodule

mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/relay_selector/matcher.rs, mullvad-relay-selector/src/relay_selector/mod.rs, test/test-manager/src/tests/daita.rs, test/test-manager/src/tests/dns.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/mod.rs, test/test-manager/src/tests/tunnel.rs, test/test-manager/src/tests/tunnel_state.rs
Full test run https://github.com/mullvad/mullvadvpn-app/actions/runs/13429747744
Fixes DES-1744
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7694)
=> Stop overwriting relay location in test framework

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
For more info see:
https://github.com/grpc/grpc-java/issues/11922
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7715)
=> Fix gRPC not working with WiFi proxy

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7712)
=> Fix navigation in report problem screen for Firestick

android/app/build.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7716)
=> Always set --locked for all gradle cargo builds

talpid-tunnel/src/tun_provider/android/mod.rs, talpid-wireguard/src/wireguard_go/mod.rs
Fixes for missed remarks https://github.com/mullvad/mullvadvpn-app/pull/7703#pullrequestreview-2640640753
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7721)
=> Clean up android tun

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LifecycleExtensions.kt
Add logging for skipped navigation events in order to simplify debugging of flaky tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7722)
=> Add logging for dropped nav events

android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt
This is a fix for a recent regression.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7727)
=> Fix spamming of connectivity changed events

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7719)
=> Fix fonts and spacing in privacy disclaimer screen

android/BuildInstructions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7725)
=> Document how to reproducibly build the app

.github/workflows/ios-end-to-end-tests.yml, .github/workflows/ios-rust-ffi.yml, .github/workflows/ios-screenshots-creation.yml, .github/workflows/ios-screenshots-tests.yml, .github/workflows/ios-validate-build-schemas.yml, .github/workflows/ios.yml, ios/.swiftformat, ios/BuildInstructions.md
This fixes some oversights in IOS-1025
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7713)
=> Add submodule checkout to ios-validate-build-schemas and README

.github/CODEOWNERS, .github/workflows/unicop.yml, .github/workflows/verify-locked-down-signatures.yml
Run the recently released in-house developed tool [`unicop`](https://github.com/mullvad/unicop/) on this repository!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7566)
=> Run the unicop tool on this repository

android/app/build.gradle.kts, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/talpid/util/ConnectivityManagerUtilKtTest.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/CommonFlowUtils.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/ConnectivityManagerUtil.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7752)
=> Filter for the correct events in ConnectivityListener

CHANGELOG.md, docs/relay-selector.md, mullvad-cli/src/cmds/relay.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/migrations/v9.rs, mullvad-daemon/src/settings/mod.rs, mullvad-management-interface/src/types/conversions/relay_constraints.rs, mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/relay_selector/matcher.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/src/relay_selector/query.rs, mullvad-relay-selector/tests/relay_selector.rs, mullvad-types/src/relay_constraints.rs, talpid-types/src/net/mod.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/relay_ip_overrides.rs, test/test-manager/src/tests/tunnel.rs, test/test-manager/src/tests/ui.rs
Fix DES-1788
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7753)
=> Remove automatic tunnel type option

android/app/build.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7756)
=> Include native symbols when building Android Application Archive

desktop/packages/mullvad-vpn/src/renderer/components/InfoButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/Login.tsx, desktop/packages/mullvad-vpn/src/renderer/components/Settings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/TooManyDevices.tsx, desktop/packages/mullvad-vpn/src/renderer/components/main-view/ConnectionActionButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/main-view/SelectLocationButton.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/Button.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/ButtonBase.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/ButtonContext.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/ButtonIcon.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/ButtonText.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/index.ts
- Makes button component in component library composable
- Updates existing usages of Button component
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7734)
=> Make button composable

.github/workflows/rust-supply-chain.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7757)
=> Fix cargo deny action failing

ios/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7764)
=> Update changelog for making account number copyable

android/build.sh
This PR aims to introduce automatic alpha devmole play publishing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7765)
=> Enable automatic alpha devmole play publishing

mullvad-update/meta/src/platform.rs
Fix DES-1805.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7770)
=> Pin TLS certificate in metadata tool

Cargo.lock, mullvad-update/Cargo.toml, mullvad-update/src/format/key.rs
Fix DES-1808
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7773)
=> Zeroize ed25519 secret when dropped

android/app/build.gradle.kts
This PR aims to fix the devmole play publishing by enabling the gradle task for the devmole infrastructure flavor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7772)
=> Fix devmole publishing

desktop/scripts/release/4-make-release, mullvad-update/meta/src/main.rs
Fix DES-1810
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7778)
=> Remove `--secret` argument from metadata tool

android/scripts/update-lockfile.sh
This is done to earlier detect lint issues and fail early due to the full lockfile generation taking a long time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7812)
=> Improve lockfile task order

android/build.gradle.kts, android/buildSrc/src/main/kotlin/Repositories.kt
This PR aims to clean up a redundant gradle plugin portal repo configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7816)
=> Clean up redundant gradle repo

Cargo.lock, installer-downloader/Cargo.toml, installer-downloader/assets/Info.plist, installer-downloader/build.rs, installer-downloader/build.sh, installer-downloader/src/main.rs, installer-downloader/src/resource.rs
Fix DES-1851.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7806)
=> Add downloader version

.github/workflows/android-reproducible-builds.yml, android/fdroid-build/env.sh, android/fdroid-build/metadata/net.mullvad.mullvadvpn.yml
This workflow aims to ensure that reproducibility between fdroid builds and container builds.
It does this by:
1. Build a containerized-build
2. Build a fdroid build using fdroidserver. There are a couple of deviations to a "real" fdroid build:
A) Gradle is installed directly, this is because fdroidserver will use the "global" installation of gradle by default. There are a way to make fdroidserver use the gradle wrapper, but in my view that would make this even more complex.
B) Uses a faked meta data file copied from the repository. This is primarily so that we can adjust the metadata file immediately if we make any changes to the build process on `main`
C) All dependencies in the `sudo` block is added a build step as the `sudo` block is not executed unless fdroidserver is run with the …
=> Add workflow to ensure reproducibility

desktop/scripts/release/4-make-release, desktop/scripts/release/5-update-and-publish-metadata, desktop/scripts/release/download-release-artifacts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7825)
=> Split publishing of metadata from 4-make-release

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, desktop/packages/mullvad-vpn/src/renderer/components/NotificationBanner.tsx, desktop/packages/mullvad-vpn/src/renderer/components/NotificationSubtitle.tsx, desktop/packages/mullvad-vpn/src/renderer/components/VpnSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/new-version.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/no-open-vpn-server-available.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/open-vpn-support-ending.ts, desktop/packages/mullvad-vpn/src/shared/constants/urls.ts, desktop/packages/mullvad-vpn/src/shared/notifications/notification.ts
Adds warnings to app related to OpenVPN being removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7814)
=> Implement OpenVPN warnings

mullvad-management-interface/proto/management_interface.proto
Updates the `.proto` file according to the specification in DES-1811
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7871)
=> Implement communication specification in Management interface

desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/ListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemFooter.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemLabel.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemText.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7873)
=> Update list item types

README.md
Since [2025.1](https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2025.1) Android now has stable release with multihop
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7878)
=> Add android support for multihop to read me

docs/known-issues.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7890)
=> Broaden issue of android reconfiguration leaks

desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/ListItem.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7883)
=> Add margin bottom to ListItem

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/UriHandlerExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AppInfoScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AppInfoViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7900)
=> Handle open app page when no app store is installed

docs/known-issues.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7903)
=> Document `NetFirewallHyperVProfile` in known issues for Hyper-V WSL firewall

desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json
https://osv.dev/vulnerability/GHSA-x574-m823-4x7w
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7904)
=> Upgrade vite to 6.2.3 to fix CVE

CHANGELOG.md, talpid-routing/src/unix/macos/interface.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7906)
=> Fix incorrect decoding of macOS SCDynStore value

android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/SelectLocationViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/location/SelectLocationViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7928)
=> Always open select location on exit tab

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, desktop/packages/mullvad-vpn/src/renderer/components/NotificationSubtitle.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/app-upgrade-available.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/app-upgrade-error.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/app-upgrade-progress.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/app-upgrade-ready.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/index.ts, desktop/packages/mullvad-vpn/src/shared/notifications/notification.ts, desktop/packages/mullvad-vpn/src/shared/notifications/update-available.ts
Fixes DES-1906
Fixes DES-1904
Fixes DES-1903
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7921)
=> Add in app upgrade notifications

android/CHANGELOG.md, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/connectioninfo/ConnectionDetailPanel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/TunnelStatePreviewData.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelEndpoint.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7957)
=> Show correct in ip when using multihop

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/ExternalLink.tsx, desktop/packages/mullvad-vpn/src/renderer/components/InternalLink.tsx, desktop/packages/mullvad-vpn/src/renderer/components/NotificationSubtitle.tsx, desktop/packages/mullvad-vpn/src/renderer/components/VpnSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/link/Link.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/link/components/LinkIcon.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/link/components/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/no-open-vpn-server-available.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7953)
=> Only show openvpn notifications when using openvpn

android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7959)
=> Update titles for ip version settings

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ObfuscationModeCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/extension/UiAutomatorExtensions.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/Page.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/Story.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/VpnSettingsPage.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/router/firewall/DropRule.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7947)
=> Add shadowsocks obfuscation e2e test

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7961)
=> Update changes dialog and F-Droid metadata for android/2025.2-beta1

installer-downloader/src/controller.rs, installer-downloader/tests/snapshots/controller__download.snap
This must be a leftover from testing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7965)
=> Remove pointless sleep

docs/known-issues.md, docs/split-tunneling.md
Fix DES-1975
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7952)
=> Mention limitations related to IPC and split tunneling

ios/MullvadMockData/MullvadREST/AccountsProxy+Stubs.swift, ios/MullvadMockData/MullvadTypes/NewAccountDataMock.swift, ios/MullvadREST/ApiHandlers/RESTAPIProxy.swift, ios/MullvadREST/ApiHandlers/RESTAccountsProxy.swift, ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift, ios/MullvadREST/MullvadAPI/APIHandlers/MullvadAPIProxy.swift, ios/MullvadREST/MullvadAPI/APIHandlers/MullvadAccountProxy.swift, ios/MullvadREST/MullvadAPI/APIRequest/APIRequest.swift, ios/MullvadREST/MullvadAPI/MullvadApiRequestFactory.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadTypes/NewAccountData.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift, ios/MullvadVPN/StorePaymentManager/StorePaymentManager.swift, ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, ios/MullvadVPN/TunnelManager/UpdateAccountDataOperation.swift, ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInfoButtonItem.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/PacketTunnel/DeviceCheck/DeviceCheckRemoteService.swift, mullvad-api/src/lib.rs, mullvad-ios/src/api_client/account.rs, mullvad-ios/src/api_client/completion.rs, mullvad-ios/src/api_client/mod.rs, mullvad-ios/src/api_client/response.rs
All API calls should use the mullvad-api client, without replacing existing implementation.
The account proxy should be implemented using mullvad-api, allowing us to move to the new implementation without removing the old code.
There is a AccountsProxy implementation that uses mullvad-api.
**How to test**
Replace impl in `RESTProxyFactory -> createAccountsProxy()` with:
```
MullvadAccountProxy(
transportProvider: APITransportProvider(requestFactory: MullvadApiRequestFactory(apiContext: apiContext)),
dispatchQueue: DispatchQueue(label: "MullvadAPIProxy.dispatchQueue"),
responseDecoder: Coding.makeJSONDecoder()
)
```
- - - …
=> Use mullvad api instead of urlsession in accounts proxy

Cargo.lock, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ParameterGenerationError.kt, android/lib/resource/src/main/res/values/strings.xml, android/lib/ui/component/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/component/NotificationData.kt, desktop/packages/mullvad-vpn/locales/messages.pot, mullvad-daemon/src/tunnel.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/states.rs, mullvad-relay-selector/src/error.rs, mullvad-relay-selector/src/relay_selector/mod.rs, talpid-types/src/tunnel.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7976)
=> Improve error message when an unavailable ip version is selected

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/DeviceIpInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7983)
=> Replace subtext with info dialog for device ip version setting

Cargo.lock, installer-downloader/src/controller.rs, mullvad-daemon/Cargo.toml, mullvad-daemon/build.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs, mullvad-daemon/src/version/check.rs, mullvad-daemon/src/version/downloader.rs, mullvad-daemon/src/version/mod.rs, mullvad-daemon/src/version/router.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/version.rs, mullvad-paths/src/cache.rs, mullvad-paths/src/lib.rs, mullvad-paths/src/logs.rs, mullvad-paths/src/settings.rs, mullvad-paths/src/windows.rs, mullvad-types/src/version.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7945)
=> Add download events

mullvad-masque-proxy/examples/masque-client.rs, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/lib.rs, mullvad-masque-proxy/src/stats.rs
Increases throughput from ~800Mbps to ~2Gbps
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7979)
=> Add basic multithreading to masque proxy

mullvad-masque-proxy/tests/proxy.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7977)
=> Add E2E test for masque fragmentation

mullvad-masque-proxy/src/fragment.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7973)
=> Add FIFO queue to handle packet fragments

mullvad-masque-proxy/Cargo.toml, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/fragment.rs, mullvad-masque-proxy/src/lib.rs, mullvad-masque-proxy/src/server/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7997)
=> Add multithreading to masque proxy server

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceListViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceListViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7988)
=> Add DeviceListViewModel test

mullvad-management-interface/src/types/conversions/states.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8003)
=> Support ip availability error in the cli

android/gradle.properties
This PR aims to enable gradle caching.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8002)
=> Enable gradle caching

Cargo.lock, mullvad-masque-proxy/Cargo.toml, mullvad-masque-proxy/examples/masque-client.rs, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/tests/proxy.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8014)
=> Add client config builder to `mullvad-masque-proxy`

mullvad-masque-proxy/examples/masque-client.rs, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/tests/proxy.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8009)
=> Add idle_timeout and bind_addr args to masque examples

mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/server/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8023)
=> Fix panic on fragment_id overflow

ios/MullvadVPN/Extensions/UIImage+Assets.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8025)
=> Resize device list remove button to 24x24

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
When switching locations on Android TV when the app goes back to the connect screen, focus was sometimes incorrectly put on the navigation drawer, which caused it to expand when it shouldn't.
This commit fixes that by detecting when we navigate back to the connect screen from the select location screen, and when that is the case we manually focus the select location button.
We check if we get a FocusDirection.Down event to detect if we navigated back from the select location screen, which isn't optimal, but I couldn't find a better way to detect this. This works because if we return from the account or settings screens we get a FocusDirection.Enter event.
- - - …
=> Fix nav drawer wrong focus on Android TV

android/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8021)
=> Update changelog with clickable feature indicators

desktop/package-lock.json, desktop/package.json, desktop/packages/mullvad-vpn/package.json
Fixes CVE-2025-32395
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8039)
=> Update vite to 6.2.6

ci/linux-repository-builder/build-linux-repositories-config.sh
Fix DES-1955
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8026)
=> Add Ubuntu Plucky repository

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipFeature.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/FeatureIndicatorsViewModel.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8044)
=> Decouple Multihop feature indicator from settings

deny.toml
Not trying to be pedantic, I just found the wording to be confusing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8041)
=> Tweak wording in deny.toml

.github/workflows/android-reproducible-builds.yml
- Fetch tags so that release builds get the correct version
- Reduce logs for fdroid server builds
- Add support for using a specific commit instead of always using latest
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8047)
=> Improve android repro workflow

mullvad-api/src/lib.rs, mullvad-api/src/relay_list.rs
This is a follow-up to #7958. I think some new stuff slipped in since then.
Fix DES-1716.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8056)
=> Fix clippy/build errors on macOS for Rust 2024

Cargo.lock, installer-downloader/src/ui_downloader.rs, installer-downloader/tests/mock.rs, mullvad-update/Cargo.toml, mullvad-update/src/client/api.rs, mullvad-update/src/client/app.rs, test/Cargo.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8059)
=> Replace `async-trait` macro

talpid-routing/src/unix/macos/data.rs, talpid-routing/src/unix/macos/default_routes.rs, talpid-routing/src/unix/macos/interface.rs, talpid-routing/src/unix/macos/ip_map.rs, talpid-routing/src/unix/macos/mod.rs, talpid-routing/src/unix/macos/routing_socket.rs, talpid-routing/src/unix/macos/watch.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7933)
=> Gracefully handle primary interface changes

CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8066)
=> Add changelog entry about default route grace time

desktop/packages/mullvad-vpn/locales/google_play.pot, desktop/packages/mullvad-vpn/locales/ru/google_play.po
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8061)
=> Add google_play.pot file to locales

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8078)
=> Update changelog for android 2025.2

desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeDownloadProgressValue/useAppUpgradeDownloadProgressValue.ts, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/hooks/useAppUpgradeLastProgress.ts, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/reducers.ts, desktop/packages/mullvad-vpn/src/renderer/redux/store.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/app-upgrade.spec.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/app-upgrade/app-upgrade.spec.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/app-upgrade/helpers.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7991)
=> Add mocked e2e test for app upgrade view

installer-downloader/CHANGELOG.md, installer-downloader/build.sh, installer-downloader/loader.manifest, installer-downloader/src/cacao_impl/mod.rs, installer-downloader/src/log.rs, installer-downloader/src/resource.rs
Fix DES-2074
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8080)
=> Rename Mullvad VPN installer to loader

installer-downloader/src/controller.rs, mullvad-api/src/version.rs, mullvad-daemon/Cargo.toml, mullvad-daemon/src/lib.rs, mullvad-daemon/src/version/check.rs, mullvad-daemon/src/version/downloader.rs, mullvad-daemon/src/version/router.rs, mullvad-update/mullvad-release/src/main.rs, mullvad-update/mullvad-release/src/platform.rs, mullvad-update/src/client/app.rs, mullvad-update/src/version.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8015)
=> Add tests for in app upgrade tests in daemon

ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift
this PR removes Same IP logging in the codebase.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8089)
=> Remove special Same IP logging

mullvad-masque-proxy/examples/masque-server.rs, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/lib.rs, mullvad-masque-proxy/src/server/mod.rs, mullvad-masque-proxy/tests/proxy.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8083)
=> Handle 308 redirects in masque proxy

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8093)
=> Update changelog for android 2025.3

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt
Fixes DES-2021
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8096)
=> Add `SuggestedUpgrade` gRPC mapper type

desktop/packages/mullvad-vpn/src/main/app-upgrade.ts, dist-assets/windows/installer.nsh
Fix DES-2058.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8094)
=> Add more helpful instructions when in-app upgrade fails on Windows

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8102)
=> Update changelog for android/2025.4-beta1

android/gradle/osv-scanner.toml
This PR aims to push `osv-scanner` suppression rules for a few Android dependencies that doesn't have direct impact on our production builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8103)
=> Push android `osv-scanner` vulns

.github/workflows/android-reproducible-builds.yml
This PR aims to add triggers for our reproducible build checks to release related PRs, branches and tags.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8106)
=> Trigger reproducible builds on release branches

mullvad-masque-proxy/examples/masque-client.rs, mullvad-masque-proxy/examples/masque-server.rs, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/server/mod.rs, mullvad-masque-proxy/tests/proxy.rs, tunnel-obfuscation/src/quic.rs
Fix DES-2100
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8097)
=> Make authorization configurable in mullvad-masque-proxy

mullvad-api/src/device.rs, mullvad-api/src/lib.rs, mullvad-daemon/src/device/service.rs, mullvad-daemon/src/lib.rs, mullvad-jni/src/lib.rs, mullvad-problem-report/src/lib.rs
This PR fixes DES-1715.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8118)
=> Prepare Android for Rust 2024

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/ContextExtensions.kt, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
- Do not show the action on devices without vpn settings
- Handle exceptions when starting vpn settings activity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8117)
=> Fix go to vpn settings on devices without system vpn settings

CHANGELOG.md
This PR adds a `2025.6-beta2` section to the changelog in preperation of the next beta release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8130)
=> Update changelog with `2025.6-beta2` section

android/lib/ui/tag/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/tag/TestTagConstants.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/VpnSettingsPage.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8129)
=> Fix test tag mismatch

.github/workflows/android-reproducible-builds.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8132)
=> Fix reproducible builds failing on PR builds

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/main/daemon-rpc.ts, desktop/packages/mullvad-vpn/src/main/grpc-type-convertions.ts, desktop/packages/mullvad-vpn/src/renderer/components/WireguardSettings.tsx, desktop/packages/mullvad-vpn/src/shared/daemon-rpc-types.ts, mullvad-daemon/src/logging.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/net.rs, mullvad-management-interface/src/types/conversions/relay_constraints.rs, mullvad-masque-proxy/examples/masque-client.rs, mullvad-masque-proxy/src/client/mod.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/src/relay_selector/query.rs, mullvad-relay-selector/tests/relay_selector.rs, mullvad-types/src/relay_constraints.rs, talpid-types/src/net/mod.rs, talpid-types/src/net/obfuscation.rs, talpid-wireguard/src/obfuscation.rs, tunnel-obfuscation/src/quic.rs
This will be gated behind `window.env.development` (GUI) and `debug_assertions` (CLI) until it's complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8107)
=> Add QUIC obfuscation support to desktop app

desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/AppUpgradeView.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/footer/Footer.tsx, desktop/packages/mullvad-vpn/src/renderer/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useMeasure.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8128)
=> Fix animations after app upgrade UI refactor

android/scripts/run-instrumented-tests.sh, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/extension/UiAutomatorExtensions.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/AccountPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/DeviceManagementPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/Page.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/ManageDevicesMockApiTest.kt
This PR fixes some of the test flakiness we see on the e2e and mockapi tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8147)
=> Improve test flakiness

android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/router/packetCapture/PacketCapture.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8155)
=> Double router capture request timeouts

.github/workflows/android-reproducible-builds.yml, android/gradle/wrapper/UpdateInstructions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8154)
=> Update gradle version in reproducible build workflow

android/gradle/wrapper/UpdateInstructions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8159)
=> Fix path typo

Cargo.lock, installer-downloader/CHANGELOG.md, mullvad-update/Cargo.toml, mullvad-update/src/client/app.rs, mullvad-update/src/client/fetch.rs, test/Cargo.lock
Add timeouts and retry logic to the in app upgrades
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8149)
=> Add download timeout and retry logic

.github/workflows/ios-screenshots-tests.yml, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme, ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNScreenshotTests.xcscheme, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift, ios/Snapfile
This PR enables us to automate the screenshot test to be run with `MockRelease`.
<div id="byLanguage" class="tabContent" style="display: block;">
<h2 id="en-US" style="font-weight: bold;">en-US</h2>
<hr>
<table>
<tr>
<th colspan="6">
<a class="deviceName" href="#en-US-iPhone 15 Pro" style="display: block; font-size: 30px; padding-bottom: 24px; padding-top: 45px;">iPhone 15 Pro</a>
</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/3adcd761-8f7f-46ca-b363-70271ae77a3c" style="width: 100%; border: 1px #EEE solid; cursor: pointer;" alt="iPhone 15 Pro"></td>
<td><img src="https://github.com/user-attachments/assets/a8ca5786-8210-450e-bfd0-2d5dbb406e63" style="width: 100%; border: 1px #EEE solid; cursor: pointer;" alt="iPhone 15 Pro"></td>
<td><img …
=> Build Screenshots with MockRelease configuration

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8158)
=> Add content type password to login textfield

installer-downloader/CHANGELOG.md, installer-downloader/src/winapi_impl/ui.rs
Fix DES-2150.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8163)
=> Fix installer-downloader arrow

Cargo.lock, installer-downloader/CHANGELOG.md, installer-downloader/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8164)
=> Bump installer-downloader version to 1.0.0

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/TunnelStateNotificationUseCase.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/TunnelStateNotificationUseCaseTest.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ErrorStateCause.kt, android/lib/resource/src/main/res/values/strings.xml, android/lib/tv/src/main/kotlin/net/mullvad/mullvadvpn/lib/tv/NotificationBannerTv.kt, android/lib/ui/component/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/component/AnimatedNotificationBanner.kt, android/lib/ui/component/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/component/NotificationData.kt, desktop/packages/mullvad-vpn/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8161)
=> Show a specific error if selected port is not in the port range

desktop/packages/mullvad-vpn/src/renderer/components/NotificationSubtitle.tsx
Update Subtitle links using the `run-function` action to make them look the same as other links.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8173)
=> Update Subtitle link styling to conform to other links

test/scripts/utils/lib.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8177)
=> Filter installer loader from fetch /releases

ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
This PR fixes the issue of `CustomListsTests`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8181)
=> Fix CustomListsTests failure

talpid-routing/src/unix/macos/default_routes.rs
Previously, this resulted in brief jump to the offline state if IPv6 was unavailable and the daemon connected within `NO_ROUTE_GRACE_TIME` seconds after starting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8175)
=> Fix early jump to offline state on macOS

desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/download-progress/hooks/useDisabled.ts
Do not disable progress bar if update is already downloaded
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8170)
=> Do not disable progress bar if update is already downloaded

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8166)
=> Fix password prompt showing multiple times

.github/workflows/rust-unused-dependencies.yml, mullvad-daemon/src/runtime.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8169)
=> Enable one worker thread per CPU core/thread

android/README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8196)
=> Fix broken link

desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json, desktop/packages/mullvad-vpn/tasks/distribution.js
Fixes: DES-1969
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7951)
=> Disable EnableNodeCliInspectArguments fuse

mullvad-paths/src/cache.rs, mullvad-paths/src/lib.rs, mullvad-paths/src/logs.rs, mullvad-paths/src/settings.rs, mullvad-paths/src/unix.rs, mullvad-paths/src/windows.rs
This fixes DES-2131.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8186)
=> Remove cache directory if it has unexpected permissions or ownership

ios/MullvadREST/Relay/RelaySelectorWrapper.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8227)
=> Fix ios release build failure

android/lib/endpoint/src/main/kotlin/net/mullvad/mullvadvpn/lib/endpoint/ApiEndpointOverride.kt, android/service/build.gradle.kts, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/di/VpnServiceModule.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/api/mullvad/MullvadApi.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/api/relay/RelayApi.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiTest.kt, mullvad-jni/src/api.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8230)
=> Supply IP address when using API override

desktop/packages/mullvad-vpn/src/shared/notifications/update-available.ts
Make "Update available" system notification navigate to upgrade route in the app
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8225)
=> Make "Update available" system notification navigate to upgrade route

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/shared/notifications/error.ts
We should probably backport this.
Fix DES-2204.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8234)
=> Fix incorrect format string for IP version error

android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/constant/Relays.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8243)
=> Fix wrong country and city for stagemole daita relay

android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/constant/Relays.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8246)
=> Fix e2e test

android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8250)
=> Increase timeout for long test

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8264)
=> Update changelog for android/2025.4

desktop/packages/mullvad-vpn/src/renderer/components/NavigationListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/Support.tsx, desktop/packages/mullvad-vpn/src/renderer/components/UserInterfaceSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/VpnSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/cell/CellButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/settings/components/api-access-methods-list-item/ApiAccessMethodsListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/settings/components/app-info-list-item/AppInfoListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/settings/components/daita-list-item/DaitaListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/settings/components/debug-list-item/DebugListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/settings/components/split-tunneling-list-item/SplitTunnelingListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/settings/components/support-list-item/SupportListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/settings/components/user-interface-settings-list-item/UserInterfaceSettingsListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/settings/components/vpn-settings-list-item/VpnSettingsListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/ListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/list-item-icon/ListItemIcon.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/list-item-icon/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/list-item-item/ListItemItem.tsx
Uses new ListItem component for navigation items in settings view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8277)
=> Use NavigationListItem in setting views

.github/workflows/ios-screenshots-tests.yml, ios/Configurations/UITests.xcconfig.template
This makes sure that the results of "test screenshots" tests are uploaded for forensic examination. Additionally, the UITests.xcconfig template is fleshed out with comments to disambiguate it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8284)
=> Fix "test screenshots" test result uploading

desktop/packages/mullvad-vpn/scripts/build-test-executable.sh, test/test-manager/src/tests/ui.rs
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/15415501959
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8291)
=> Fix `test_settings_ui`  E2E test

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/talpid/util/ConnectivityManagerUtilKtTest.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/ConnectivityManagerUtil.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8293)
=> Fix connectivity manager util tests

desktop/packages/mullvad-vpn/test/e2e/installed/state-dependent/vpn-settings/vpn-settings.spec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8297)
=> Move check for auto-start path on Linux before tests

ios/CHANGELOG.md, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AppRoutes.swift, ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/Multihop/MultihopSettingsCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift, ios/MullvadVPN/Coordinators/TunnelCoordinator.swift, ios/MullvadVPN/Coordinators/VPNSettingsCoordinator.swift, ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipContainerView.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipFeature.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipModel.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipView.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipViewModelProtocol.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/FeatureIndicatorsViewModel.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift, ios/MullvadVPN/View controllers/VPNSettings/CustomDNSCoordinator.swift, ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
Feature indicators are now clickable and open their corresponding settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8280)
=> Implement quick access design

Cargo.lock, Cargo.toml, mullvad-cli/Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-exclude/Cargo.toml, mullvad-jni/Cargo.toml, mullvad-leak-checker/Cargo.toml, mullvad-leak-checker/src/traceroute/unix/linux.rs, mullvad-management-interface/Cargo.toml, talpid-core/Cargo.toml, talpid-net/Cargo.toml, talpid-routing/Cargo.toml, talpid-routing/src/unix/macos/routing_socket.rs, talpid-time/Cargo.toml, talpid-tunnel/src/tun_provider/android/mod.rs, talpid-tunnel/src/tun_provider/unix.rs, talpid-wireguard/Cargo.toml, talpid-wireguard/src/boringtun/mod.rs, talpid-wireguard/src/mtu_detection.rs, talpid-wireguard/src/wireguard_go/mod.rs, talpid-wireguard/src/wireguard_kernel/parsers.rs, talpid-wireguard/src/wireguard_kernel/wg_message.rs, test/Cargo.lock, test/Cargo.toml, tunnel-obfuscation/Cargo.toml, tunnel-obfuscation/src/shadowsocks.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8283)
=> Clean up workspace deps and promote nix

desktop/package-lock.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8324)
=> Bump `brace-expansion` to fix `CVE-2025-5889`

talpid-tunnel/src/tun_provider/windows.rs
TODO:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8261)
=> Add IPv6 support to Windows tun provider

android/docker/Dockerfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8328)
=> Bump container sdk to 36

building/README.md
This PR makes the instructions around Linux/Android container image creation a bit clearer. In order to make it easier for other people to carry out these steps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8327)
=> Improve container image instructions

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelState.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8344)
=> Sort split tunneling apps in the correct order

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8348)
=> Update changelog for `android/2025.5-beta1`

Cargo.lock, desktop/packages/mullvad-vpn/tasks/distribution.js, mullvad-daemon/src/lib.rs, mullvad-daemon/src/system_service.rs, mullvad-setup/Cargo.toml, mullvad-setup/src/main.rs, mullvad-setup/src/service.rs
This also makes the installer unpack `mullvad-setup.exe` to the resource directory on Windows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8355)
=> Add `start-service` command to mullvad-setup

talpid-wireguard/src/boringtun/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8389)
=> Fix bad fd on android when using boringtun

ios/Assets/changes.txt, ios/MullvadVPN/View controllers/Account/AccountNumberRow.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8387)
=> Fix account number

android/app/build.gradle.kts, android/build.sh
This PR enables publishing of prod flavor alpha builds to the internal test track on Google Play. Permissions for the account used for publishing have also been updated accordingly.   
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8395)
=> Enable alpha publishing of prod app

android/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8398)
=> Add MTE flag to changelog

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AddTimeBottomSheet.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AddTimeViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AddTimeViewModelTest.kt
- Immediately update expiry date after successful purchase
- Immediately retry verification after failed verification
- Always reset purchase state when closing the bottom sheet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8394)
=> Cleanup AddTimeBottomSheet behavior

android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AddTimeViewModelTest.kt
Fixes: DROID-2069
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8401)
=> Fix failing unit tests in AddTimeViewModelTest

android/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8403)
=> Update changelog for android/2025.5

wireguard-go-rs/build.rs
This PR updates the `wireguard-go-rs` build script to not assume target ABI to be glibc when cross-compiling. The current solution is not directly extensible by the user, but it easily could be if we really wanted to. At least we don't break cross-compilation to musl targets though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8425)
=> Add musl as a target ABI for `wireguard-go-rs`

.github/workflows/android-reproducible-builds.yml, android/gradle/wrapper/UpdateInstructions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8432)
=> Fix reproducible workflow gradle version

.github/workflows/android-reproducible-builds.yml
Improves readability and changes to a more generic approach of handling multiple artifacts, which allows for extending the range of artifacts we compare.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8419)
=> Clean up reproducible workflow

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/component/AddTimeBottomSheetTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/AddMoreTimeUiStatePreviewParameterProvider.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AddTimeUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AddTimeViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AddTimeViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8443)
=> Fix test flakiness

android/translations-converter/src/android/string_value.rs, mullvad-ios/src/api_client/access_method_settings.rs, mullvad-ios/src/api_client/account.rs, mullvad-ios/src/api_client/address_cache_provider.rs, mullvad-ios/src/api_client/api.rs, mullvad-ios/src/api_client/cancellation.rs, mullvad-ios/src/api_client/completion.rs, mullvad-ios/src/api_client/device.rs, mullvad-ios/src/api_client/helpers.rs, mullvad-ios/src/api_client/mod.rs, mullvad-ios/src/api_client/problem_report.rs, mullvad-ios/src/api_client/response.rs, mullvad-ios/src/api_client/retry_strategy.rs, mullvad-ios/src/api_client/shadowsocks_loader.rs, mullvad-ios/src/api_client/storekit.rs, mullvad-ios/src/ephemeral_peer_proxy/mod.rs, mullvad-ios/src/lib.rs, mullvad-ios/src/shadowsocks_proxy/ffi.rs, mullvad-ios/src/tunnel_obfuscator_proxy/ffi.rs, mullvad-nsis/src/lib.rs, mullvad-types/src/auth_failed.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8445)
=> Fix rust warnings in preparation for 2024 edition

CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8446)
=> Add start daemon button to changelog

talpid-openvpn/src/lib.rs
Fix new nightly lint
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8450)
=> Fix lint `unused_parens`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/IconCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AddTimeBottomSheet.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/PlayPayment.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/LocationBottomSheet.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/RelayListContent.kt, android/lib/ui/component/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/component/relaylist/CheckableRelayListItem.kt, android/lib/ui/component/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/component/relaylist/SelectableRelayListItem.kt, android/lib/ui/designsystem/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/designsystem/RelayListItem.kt
Fixes some of the last changes that was done to the design after we merged the initial PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8449)
=> Select location follow up fixes

talpid-core/src/firewall/windows/winfw/mod.rs, windows/winfw/src/winfw/objectpurger.cpp, windows/winfw/src/winfw/objectpurger.h, windows/winfw/src/winfw/winfw.cpp
Fix DES-2309
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8456)
=> Fix passing of dangling pointer to WinFw

mullvad-api/src/access.rs, mullvad-api/src/proxy.rs, mullvad-api/src/relay_list.rs, mullvad-api/src/rest.rs, mullvad-cli/src/cmds/tunnel_state.rs, mullvad-daemon/src/account_history.rs, mullvad-daemon/src/custom_list.rs, mullvad-daemon/src/device/mod.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/main.rs, mullvad-daemon/src/migrations/v1.rs, mullvad-daemon/src/migrations/v3.rs, mullvad-daemon/src/migrations/v5.rs, mullvad-daemon/src/migrations/v6.rs, mullvad-daemon/src/migrations/v7.rs, mullvad-daemon/src/migrations/v9.rs, mullvad-daemon/src/settings/mod.rs, mullvad-leak-checker/src/traceroute/unix/linux.rs, mullvad-masque-proxy/src/server/mod.rs, talpid-core/src/firewall/linux.rs, talpid-core/src/logging/mod.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-dbus/src/network_manager.rs, talpid-future/src/retry.rs, talpid-openvpn/src/lib.rs, talpid-openvpn/src/mktemp.rs, talpid-platform-metadata/src/linux.rs, talpid-routing/src/unix/linux.rs, talpid-wireguard/src/wireguard_kernel/mod.rs, wireguard-go-rs/build.rs
This PR fixes a bunch of nightly `clippy` warnings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8461)
=> Fix clippy nightly warnings

.github/workflows/android-reproducible-builds.yml, .github/workflows/verify-locked-down-signatures.yml, android/BuildInstructions.md, android/flake.lock, android/flake.nix, android/lib/daemon-grpc/build.gradle.kts, android/nix/env-vars.nix
This PR aims to add a nix devshell flake that can be used to build our Android app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8452)
=> Add initial android devshell

.github/workflows/android-reproducible-builds.yml, android/BuildInstructions.md, android/docs/BuildInstructions.macos.md, android/flake.nix, android/nix/env-vars.nix
This PR aims to add macOS support to our Android devshell.
TODO:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8469)
=> Add macos devshell support

android/BuildInstructions.md, android/flake.nix
This PR aims to add some initial commands (`tasks` & `build`) to the Android devshell. Unfortunately the way we define the current shell doesn't allow for rich menus with package, description and category.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8475)
=> Add devshell commands

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8476)
=> Update changelog for `android/2025.6-beta1`

desktop/package-lock.json
Updates dependencies to fix [CVE-2025-7783](https://osv.dev/vulnerability/GHSA-fjxv-7rqg-78g4). This is a dev dependency so should not affect app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8491)
=> Update dependencies to fix `CVE-2025-7783`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/RelayListContent.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8500)
=> Enable long press context menu for recents

mullvad-types/src/settings/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8501)
=> Add current relay to recents if selected

android/docs/BuildInstructions.macos.md, android/fdroid-build/metadata/net.mullvad.mullvadvpn.yml, android/flake.lock, android/gradle/libs.versions.toml, building/android-container-image.txt
Upgrades to use new container image that has the new LTS NDK included and bumps the NDK of the app to the same version. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8510)
=> Fix ndk not found fdroid

android/lib/billing/src/main/kotlin/net/mullvad/mullvadvpn/lib/billing/BillingPaymentRepository.kt
These were missing before
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8519)
=> Add some basic logging for the play purchase verification process

android/app/src/main/AndroidManifest.xml
We need to set this in order for a release build of the app to the profileable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8518)
=> Enable profileable tag in AndroidManifest.xml

android/gradle/osv-scanner.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8532)
=> Update android osv vulns

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Drawable.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8533)
=> Handle app icons with negative size without crashing

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/location/RelayItemListCreator.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8537)
=> Fix crash with DAITA and multihop recents

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8539)
=> Add additional logging on login failure

.github/workflows/android-app.yml
We are hitting the wall of running for 6 hours when doing 100 iterations to find flakiness, this PR lowers the number of iterations to 80.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8541)
=> Update scheduled run to 80 iterations

.github/workflows/desktop-e2e.yml, test/test-manager/src/vm/provision.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8502)
=> Add macOS 26 to E2E test workflow

mullvad-exclude/src/main.rs
Fix DES-2224
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8552)
=> Improve error message for missing cgroups v1

docs/architecture.md
The current description is outdated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8498)
=> Update architecture docs for macOS offline monitor

android/lib/ui/component/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/component/relaylist/CheckableRelayListItem.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8570)
=> Custom list locations has a redundant square for relays

README.md, mullvad-daemon/src/version/check.rs
This adds an environment variable for enabling version checks in dev builds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8564)
=> Add MULLVAD_ENABLE_DEV_UPDATES for enabling version checks in dev builds

.github/workflows/desktop-e2e.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8582)
=> Skip Linux app build when running E2E tests for tag

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8584)
=> Update changelog for android 2025.6

android/app/src/main/kotlin/net/mullvad/mullvadvpn/MullvadApplication.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8579)
=> Move expiry notification handling to application

android/CHANGELOG.md, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/DefaultLocationTest.kt, mullvad-daemon/src/lib.rs, mullvad-daemon/src/settings/mod.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/settings.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-types/src/location.rs, mullvad-types/src/relay_list.rs, mullvad-types/src/settings/mod.rs, mullvad-types/src/states.rs
Sets the default relay selection to the current country (as determined by am.i.mullvad.net).
In non-release builds of the Android app we do not bundle a relay list in the APK, and the relay list is fetched when the user logs in.
So one of the following can happen:
1. Geolocation request returns, we have a relay list.
2. Geolocation request returns, we do not yet have a relay list.
3. Relay list request returns, we have a geolocation.
4. Relay list request returns, we do not have a geolocation.
In 1. and 3. we can update the default locaiton. In 2. we have to wait until the relay list is fetched from the api until we can update the default location. 4. is unlikely to happen but could happen if am.i.mullvad is down.
If the user's country doesn't have a relay the closest country that has a …
=> Set relay to current country on first start

android/gradle/osv-scanner.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8602)
=> Ignore CVE-2025-55163 as it only affects http2

tunnel-obfuscation/src/quic.rs
The issue here is that `Client::connect` never returns in some cases where one does not have IPv6 connectivity. Rather than adding a timeout, I changed it back so that the "obfuscator" does not wait for the connection to be established, which is more in line with how the other obfuscators are implemented.
Fix DES-2384
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8615)
=> Fix tunnel-obfuscation eternally waiting to establish QUIC connection 

test/test-manager/src/main.rs, test/test-manager/src/tests/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8630)
=> Add --skip flag to test-manager

android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/DateExtensions.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8632)
=> Catch exception in toExpiryDateString()

talpid-wireguard/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8634)
=> Set QUIC MTU based on route only

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/ConnectOnStartupInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/InfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingItem.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/ContextExtensions.kt, android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
Move all extra information into info dialog. Add warning that it will not work if the app is installed on SD card.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8633)
=> Improve connect on start up information

ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/ListCellContentView.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentView.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift, ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift, ios/MullvadVPN/Views/SplitMainButton.swift
This PR fixes minor layout issues when dynamic text size is enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8631)
=> Fix dynamic size issues

ios/MullvadREST/ApiHandlers/RESTProxyFactory.swift, ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift
Switch from URLSession to Rust api client for all build configurations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8653)
=> Enable rust api client for all builds

desktop/packages/mullvad-vpn/tasks/distribution.js, desktop/packages/mullvad-vpn/test/e2e/installed/state-dependent/vpn-settings/vpn-settings.spec.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/vpn-settings/vpn-settings-route-object-model.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8637)
=> Fix failing tests related to auto-connect and launch on startup settings

BuildInstructions.md
This PR updates the build instructions to instruct the user to install Volta from their website or via brew for Linux and macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8662)
=> Update volta install instructions

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/RedeemVoucher.tsx, desktop/packages/mullvad-vpn/src/renderer/components/RedeemVoucherStyles.tsx, desktop/packages/mullvad-vpn/src/shared/utils.ts, desktop/packages/mullvad-vpn/test/unit/account-number.spec.ts
This PR adds an error message that shows if the user inputs an account number into the voucher field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8658)
=> Add error message when account number is inputted into voucher field

mullvad-masque-proxy/src/fragment.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8659)
=> Add test to masque proxy for interleaved fragments

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8665)
=> Update changelog for android/2025.7-beta1

mullvad-types/src/wireguard.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8534)
=> Enable PQ by default on Android

.github/workflows/daemon.yml, build-windows-modules.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8672)
=> Allow caping concurrent processes when building Windows modules

installer-downloader/src/controller.rs, mullvad-daemon/src/version/check.rs, mullvad-update/src/client/snapshots/mullvad_update__client__api__test__http_version_provider.snap, mullvad-update/src/snapshots/mullvad_update__version__test__version_unsupported_filtering-2.snap, mullvad-update/src/snapshots/mullvad_update__version__test__version_unsupported_filtering.snap, mullvad-update/src/version.rs, mullvad-update/test-version-response.json
Fix DES-2366
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8680)
=> Ignore versions with zero rollout in Mullvad loader and app

CHANGELOG.md, Cargo.lock, mullvad-masque-proxy/Cargo.toml, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/lib.rs, mullvad-masque-proxy/src/server/mod.rs
Fix DES-2425.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8697)
=> Add UDP GSO for MASQUE client

Cargo.lock, mullvad-masque-proxy/Cargo.toml, talpid-windows/Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8704)
=> Add missing feature for talpid-windows

android/gradle/osv-scanner.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8705)
=> Ignore CVE-2025-58057 on android

android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/RecentsUseCase.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/RecentsUseCaseTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8719)
=> Daita direct only shows non daita recents

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8722)
=> Update changelog for android 2025.7

Cargo.lock, Cargo.toml, talpid-core/Cargo.toml, talpid-tunnel/src/tun_provider/android/ipnetwork_sub.rs, talpid-types/Cargo.toml, test/Cargo.lock, test/connection-checker/Cargo.toml, test/connection-checker/src/main.rs, test/connection-checker/src/net.rs, test/test-manager/Cargo.toml, test/test-manager/src/container.rs, test/test-manager/src/network_monitor.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/relay_ip_overrides.rs, test/test-manager/src/tests/tunnel.rs, test/test-manager/src/vm/network/linux.rs, test/test-runner/src/net.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8726)
=> Add IPv6 to e2e tests

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8772)
=> Update changelog for android/2025.8-beta1

desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json
Updates styled components to 6.1.19
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8774)
=> Update styled-components to 6.1.19

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/translation/scripts/Readme.md, ios/translation/scripts/localizations.sh, scripts/localization
This reverts commit 32a2024a1d3c4a593e9f134f38babc881b49e7cb that added iOS localization to the shared scripts. We decided to revert the change due to how it interferes with the other platforms.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8775)
=> Revert "Add iOS localization to the pipeline"

desktop/osv-scanner.toml, desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json
- Upgrade `vite` to `7.1.7`
- Upgrade `@vitejs/plugin-react` to `4.7.0` to fix TS errors in plugin format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8831)
=> Upgrade vite to fix vulnerabilities found by OSV scanner

mullvad-management-interface/src/types/conversions/relay_constraints.rs, mullvad-relay-selector/src/relay_selector/helpers.rs, mullvad-relay-selector/src/relay_selector/matcher.rs, mullvad-types/src/relay_list.rs
Fix DES-2550
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8838)
=> Select random in-address for QUIC

CHANGELOG.md, mullvad-cli/src/cmds/reset.rs, mullvad-cli/src/main.rs, mullvad-daemon/src/settings/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8829)
=> Add reset-settings command to CLI

android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/ConnectivityManagerUtil.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/UnderlyingConnectivityStatusResolver.kt
- Clarify comment for why we need to listen for all non-VPN network events.
- Log default network event types in production build.
- Add log for when we try to check connectivity status.
- Improve logging of when we can't access the internet via socket.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8858)
=> Improve documentation and logging of connectivity status

CHANGELOG.md, desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/main/daemon-rpc.ts, desktop/packages/mullvad-vpn/src/renderer/components/EditApiAccessMethod.tsx, desktop/packages/mullvad-vpn/src/renderer/components/ProxyForm.tsx, desktop/packages/mullvad-vpn/src/renderer/components/cell/SettingsRow.tsx, desktop/packages/mullvad-vpn/src/renderer/components/cell/SettingsTextInput.tsx, desktop/packages/mullvad-vpn/src/shared/daemon-rpc-types.ts, desktop/packages/mullvad-vpn/src/shared/ipc-schema.ts, mullvad-api/src/access_mode.rs, mullvad-daemon/src/access_method.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/settings/mod.rs, mullvad-management-interface/src/client.rs, mullvad-management-interface/src/lib.rs, mullvad-types/src/access_method.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8686)
=> Dont allow duplicate names for api access methods

desktop/packages/mullvad-vpn/src/renderer/components/ProxyForm.tsx
The API access method e2e tests failed when #8686 was merged.
Passing E2E tests: https://github.com/mullvad/mullvadvpn-app/actions/runs/18141493152
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8872)
=> Fix api access method e2e tests

.github/workflows/desktop-e2e.yml, test/scripts/ssh-setup.sh
This PR adds a Ubuntu 25.10 (Beta) VM to the e2e test workflow.
https://github.com/mullvad/mullvadvpn-app/actions/runs/18007584591/job/51233089217
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8840)
=> Add Ubuntu 25.10 VM to E2E tests

mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/tests/relay_selector.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8890)
=> Enable quic in the relay selector for android
