mullvad/mullvadvpn-app

- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
It seems we have sufficient handling of cases where we cannot load the config we need. The current path does not allow the load config operation to return a failure/error, so we cannot end up with a thrown fatalError unless there's an implementation error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5188)
> Update tunnel manager to not return error for configuration loading

- .github/workflows/android-app.yml
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/DaemonInstance.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/FileResourceExtractor.kt
This PR aims to restore the `relays.json` asset->file extraction that was removed by accident in #4449. The remaining file migration logic will not be re-introduced.
This partially reverts commit e64abbb94ae641d05ee3cf8dc0f4340b17cdc033.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5194)
> Partially revert "Remove android file migration"

- mullvad-jni/src/lib.rs
It's not possible to distinguish between used and invalid vouchers at the moment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5195)
> Convert voucher errors correctly in mullvad-jni

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/WelcomeUiState.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt
- android/lib/resource/src/main/res/values-da/strings.xml
- android/lib/resource/src/main/res/values-de/strings.xml
- android/lib/resource/src/main/res/values-es/strings.xml
- android/lib/resource/src/main/res/values-fi/strings.xml
- android/lib/resource/src/main/res/values-fr/strings.xml
- android/lib/resource/src/main/res/values-it/strings.xml
- android/lib/resource/src/main/res/values-ja/strings.xml
- android/lib/resource/src/main/res/values-ko/strings.xml
- android/lib/resource/src/main/res/values-my/strings.xml
- android/lib/resource/src/main/res/values-nb/strings.xml
- android/lib/resource/src/main/res/values-nl/strings.xml
- android/lib/resource/src/main/res/values-pl/strings.xml
- android/lib/resource/src/main/res/values-pt/strings.xml
- android/lib/resource/src/main/res/values-ru/strings.xml
- android/lib/resource/src/main/res/values-sv/strings.xml
- android/lib/resource/src/main/res/values-th/strings.xml
- android/lib/resource/src/main/res/values-tr/strings.xml
- android/lib/resource/src/main/res/values-zh-rCN/strings.xml
- android/lib/resource/src/main/res/values-zh-rTW/strings.xml
- android/lib/resource/src/main/res/values/strings.xml
This commit adds device name to the welcome screen and a InfoDialog to clarify it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5173)
> Add DeviceName to Welcome Screen

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/AccountNumberView.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableObfuscationView.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Clipboard.kt
Add the copy icon to make it clean that the user can copy the account number.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5141)
> Add copy icon button account created screen

- gui/src/config.json
- gui/src/renderer/components/ProblemReport.tsx
- gui/src/renderer/components/Settings.tsx
- gui/src/shared/notifications/unsupported-version.ts
- gui/src/shared/notifications/update-available.ts
- gui/src/shared/version.ts
This PR adds support for including the platform in the download url to make it work with spoofed user agents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5197)
> Add platform to download urls

- android/lib/resource/src/main/res/values/strings_non_translatable.xml
This PR changes the Android download URL to include the platform to avoid showing the wrong download page if the user-agent is spoofed. It will now lead to: https://mullvad.net/download/vpn/android
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5205)
> Include platform in Android download URL

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeviceNameInfoDialog.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/AccountUiState.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/AccountFragment.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5204)
> Fix incorrect content of device name info dialog

- CHANGELOG.md
- ci/buildserver-build.sh
In preparation for providing deb and yum repositories we should start signing the corresponding Linux artifacts. This PR adds the signing. This is a prerequisite for providing the repositories, but is also good even without the repositories. Just adds more integrity to all produced artifacts.
At first, I wanted to do the signing in `build.sh` where we do other signing. But since that runs in a container on Linux, we can't. The keys are not available there.
So I moved it up one level and instead sign in the buildserver specific script, running outside the container.
The dependencies/changed build server setup requirements include:
* Installing RPM signing tools: `dnf install rpm rpmsign`
* Configure RPM to use the correct GPG key:
```
echo "%_signature gpg
%_gpg_name …
```
> Add signatures in all deb and rpm artifacts produced by build server

- BuildInstructions.md
- building/Dockerfile
This PR updates protoc to 24.3 (from 3.12.4) and bumps the minimum to 3.15.
Fix DES-368.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5207)
> Update protoc in build containers

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Color.kt
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt
This is part of the design system overhaul.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5216)
> Replace primary container color with primary with alpha

- ios/PacketTunnel/PacketTunnelProvider.swift
- ios/Shared/ApplicationConfiguration.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5228)
> Log if Same IP is used when starting a tunnel

- ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift
When adding the social media blocking option, we missed a check to verify that turning it on correctly disables custom DNS. This PR fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5235)
> Make social media block setting conflict with custom DNS

- mullvad-daemon/src/tunnel.rs
Desktop+Android equivalent of #5228. Logs when the known Same IP IPs are being used for a WireGuard tunnel. Should aid in debugging any issues that might arise during the rollout of Same IP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5236)
> Log if Same IP is being used or not

- ios/MullvadVPN/TunnelManager/TunnelManager.swift
This PR fixes a regression introduced after switch to `Duration`. Just noticed today that logs state:
```
Start polling tunnel status every Duration(components: (seconds: 3, attoseconds: 0)) second(s).
```
Since `Duration` supports `logFormat()` we should use that function to output durations in log file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5229)
> Fix duration logging

- talpid-core/src/offline/macos.rs
- talpid-routing/src/debounce.rs
- talpid-routing/src/lib.rs
- talpid-routing/src/unix/macos/mod.rs
- talpid-routing/src/unix/mod.rs
- talpid-routing/src/windows/default_route_monitor.rs
The route monitor currently *immediately* reacts to any route change. What happens is somewhat unpredictable because we're likely changing the routing table at the same time as the OS. We're also making many unnecessary changes to the routing table, and we might potentially end up constantly updating routes in a tight loop.
The PR fixes these issues by triggering route changes only after a minimum interval of time has elapsed.
Close DES-384.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5225)
> Add burst guard to macOS route monitor

- talpid-routing/Cargo.toml
- talpid-routing/src/unix/macos/data.rs
- talpid-routing/src/unix/macos/interface.rs
- talpid-routing/src/unix/macos/mod.rs
macOS prefers scoped default routes on the same interface as that of the *unscoped* default route. This currently breaks if the scoped route has the wrong gateway. Let's fix this by removing up any scoped routes that we've added ourselves.
Close DES-382.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5224)
> Remove old scoped route when the default route changes

- Cargo.lock
- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/tunnel.rs
Just backport of #5236. making a PR since the verbatim copy of the same solution on `main` did not work on this branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5238)
> Log when same ip is being used (backport to release branch)

- ci/verify-locked-down-signatures.sh
This PR aims to fix a problem with the path extraction logic in the signature verification script where it would only extract paths up until any path containing a `*` character, resulting in a subset of all paths being verified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5241)
> Fix signature verification path extraction

- ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/PacketTunnel/PacketTunnelProvider/BlockedStateErrorMapper.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5239)
> Add UI for blocked state

- ci/buildserver-upload.sh
This PR updates the `buildserver-upload.sh` script to refer to the upload server as a ssh-config host.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5246)
> Refer to ssh config hosts in buildserver-upload.sh

- CHANGELOG.md
- talpid-core/src/offline/macos.rs
- talpid-core/src/resolver.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-routing/src/debounce.rs
- talpid-routing/src/unix/macos/interface.rs
- talpid-routing/src/unix/macos/mod.rs
- talpid-routing/src/unix/mod.rs
- talpid-routing/src/windows/default_route_monitor.rs
This PR makes a few changes:
* Use the primary interface as the "best (scoped) default route", or else the first active interface in the network service order. (Same as before, but the flow is much easier to understand.)
* Check whether the "best default route" has changed in response to any changes to network services in the dynamic store.
* Check whether the "best default route" has changed when the user tries to connect in the offline state.
* Log all the things.
Fix DES-398
Fix DES-396
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5254)
> Detect changes to interfaces in the dynamic store

- mullvad-daemon/src/tunnel.rs
Just backports #5236 to the (previous) Android release branch. So we can expedite a quick release with this logging included.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5260)
> Log if Same IP is being used or not [Android backport]

- android/app/build.gradle.kts
- android/buildSrc/src/main/kotlin/BuildVariants.kt
This PR aims to add a `stagemole` flavor in the infrastructure dimension.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5258)
> Add stagemole flavor

- ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
We should synchronise presentations for the settings and account modals. Using the style of settings modal also ensures conformance to the "Reduce Motion" accessibility setting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5248)
> Synchronise presentations for settings and account modals

- ios/MullvadVPN/Coordinators/AccountCoordinator.swift
- ios/MullvadVPN/Coordinators/AlertCoordinator.swift
- ios/MullvadVPN/Coordinators/ChangeLogCoordinator.swift
- ios/MullvadVPN/View controllers/Alert/AlertPresentation.swift
- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
- ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift
- ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift
Fixes device name not appearing in device logout screen. Also, adds icon to device info modal in account screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5251)
> Fix device name not appearing in device logout screen

- gui/package-lock.json
- gui/package.json
- gui/src/main/index.ts
This PR updates electron from 25.2.0 to 26.3.0, as well as NodeJS to 18.16.1 and npm to 10.2.0.
For some reason registering the `powerMonitor` listeners before the `ready` event now restults in a crash on Linux so those have been moved to the `onReady` function.
Changelog for Electron 26:
https://github.com/electron/electron/releases/tag/v26.0.0
Fixes DES-397
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5255)
> Update to Electron 26

- CHANGELOG.md
When adding custom lists and updating Electron I forgot to add the changes to the changelog. This PR corrects that by adding them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5267)
> Add missing changelog entries about custom lists and electron update

- building/linux-container-image.txt
Getting with the times. Most importantly having access to the newer protoc that will allow significant Rust code cleanups.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5268)
> Bump Linux build container to one with Rust 1.73 and newer protoc

- ios/MullvadREST/HTTP.swift
- ios/MullvadREST/RESTRequestFactory.swift
- ios/PacketTunnel/PacketTunnelProvider.swift
Our app won't be receiving the _same IP_ address unless we set the user agent string. And, in case the packet tunnel lives forever, it's best to log about using the _same IP_ every time a new config is generated. So I've added these changes with hopes of merging them into the release branch. Once that is done, I'll rebase these changes for the `main` as well :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5269)
> Prep iOS for same ip

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LoginMockApiTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5276)
> Fix login uiautomator flakiness

- ios/MullvadREST/RESTTransportStrategy.swift
- ios/MullvadRESTTests/TransportStrategyTests.swift
- ios/MullvadTransport/TransportProvider.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
This work was done in the `ios-prepare-2023.4` branch, but was never back ported to main.
This PR fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5262)
> Cache the transportStrategy in the UserDefaults

- ios/MullvadREST/HTTP.swift
- ios/MullvadREST/RESTRequestFactory.swift
Backporting a fix from the release branch - without the user agent, our client won't be receiving a _same-ip_ IP from the API when rotating keys/creating devices.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5280)
> Add user agent header for all requests on iOS

- gui/src/main/daemon-rpc.ts
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/types/conversions/custom_list.rs
- mullvad-management-interface/src/types/conversions/custom_tunnel.rs
- mullvad-management-interface/src/types/conversions/location.rs
- mullvad-management-interface/src/types/conversions/mod.rs
- mullvad-management-interface/src/types/conversions/net.rs
- mullvad-management-interface/src/types/conversions/relay_constraints.rs
- mullvad-management-interface/src/types/conversions/relay_list.rs
- mullvad-management-interface/src/types/conversions/settings.rs
- mullvad-management-interface/src/types/conversions/states.rs
- mullvad-management-interface/src/types/conversions/version.rs
Instead of mapping default values of strings and integers to 0/"", we can just set them to optional. `optional` was reintroduced in protobuf 3.15.
Closes DES-367.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5191)
> Use optional modifier for scalars in protobuf

- ios/MullvadVPN/TunnelManager/LoadTunnelConfigurationOperation.swift
`SettingsManager.readSettings()` throws `ReadSettingsVersionError` which should not be logged when the underlying error points at item not being found in Keychain.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5284)
> Prevent logging error when settings are not found in Keychain

- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift
This PR ensures that same-ip message is printed on each connect by exposing tun addresses over `ConnectionState`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5277)
> Print same-ip message on each connect

- .github/workflows/android-app.yml
This PR aims to fix a problem where konsist tests would be skipped due to caches. The problem is fixed by forcing a task re-run. This problem has been communicated to the upstream konsist project by @Rawa .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5288)
> Fix skipped konsist tests due to caches

- ios/PacketTunnelCore/Actor/Actor+ConnectionMonitoring.swift
- ios/PacketTunnelCore/Actor/Actor.swift
- ios/PacketTunnelCore/Actor/Command.swift
- ios/PacketTunnelCore/Actor/State.swift
- ios/PacketTunnelCoreTests/ActorTests.swift
- ios/PacketTunnelCoreTests/Mocks/TunnelMonitorStub.swift
Currently reconnection is a two fold operation:
- First we increment attempt counter
- Then schedule command for reconnect to leverage coalescing system.
This approach produces two individual changes to `state` which can be misleading when observed from the outside. For instance:
-  If the tunnel is currently in `.connected` state, the first mutation increments attempt counter updating it to `1`.
- The observer then receives a `.connected` state with attempt counter updated to `1`. 
- The second mutation changes `state` to `.reconnecting` with attempt counter set to `1`.
- The observer then receives a `.reconnecting` state with attempt counter set to `1`.
Because `connected`, `reconnecting`, `connecting` were handled the same way, the tunnel losing connectivity also starts connection …
> Ensure atomicity between (re)connection attempts

- .github/workflows/android-app.yml
- android/lib/endpoint/src/debug/kotlin/net/mullvad/mullvadvpn/lib/endpoint/CustomApiEndpointConfiguration.kt
- android/lib/endpoint/src/main/kotlin/net/mullvad/mullvadvpn/lib/endpoint/CustomApiEndpointConfiguration.kt
- android/service/build.gradle.kts
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/di/ApiEndpointModule.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiTest.kt
This PR aims to use custom flavor endpoints for development and testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5294)
> Use custom flavor endpoints

- gui/src/renderer/redux/account/reducers.ts
When implementing https://github.com/mullvad/mullvadvpn-app/pull/4790 I mistakenly made the new device banner only show after creating a new account. This PR makes sure that the banner is always shown after logging in.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5299)
> Fix device banner not showing after logging in

- ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
- ios/MullvadVPN/View controllers/ChangeLog/ChangeLogInteractor.swift
When there are no meaningful changes we do not want to advertise anything in the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5297)
> Do not show change log when it is empty

- ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
On tunnel start, if no valid relay can be selected app-side we let the packet tunnel take care of it instead. This will put the app in blocked state.
This PR takes care of issue the following issue as well:
https://linear.app/mullvad/issue/IOS-351/removing-relay-filters-does-not-exit-blocked-state
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5300)
> Put app in blocked state on tunnel start if relay constraints cannot be satisfied

- gui/src/renderer/components/Filter.tsx
- gui/src/renderer/components/select-location/SelectLocation.tsx
This PR solves a bug where the provider filter count in the select location view included providers which wasn't compatible with the selected ownership filter. This resulted in an higher than expected number. This is now solved by using a provider list filtered by the selected ownership option when calculating the number of selected filters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5304)
> Make sure filter count is correct when using multiple filters

- gui/src/renderer/components/SearchBar.tsx
- gui/src/renderer/components/select-location/LocationRow.tsx
Both the search input and location row didn't fit descenders on Linux. This PR fixes that by increasing the line height.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5306)
> Fix LocationRow and search input line height

- gui/locales/messages.pot
- gui/src/renderer/components/VpnSettings.tsx
This PR adds an info dialog to the "Enable IPv6" feature and removes the now redundant footer text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5303)
> Add IPv6 info dialog

- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/disconnected_state.rs
- talpid-core/src/tunnel_state_machine/disconnecting_state.rs
- talpid-core/src/tunnel_state_machine/error_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
Minor cleanup that gets rid of the `state_wrapper` macro in favor of boxing the `TunnelState` trait.
```rust
enum EventConsequence {
NewState((Box<dyn TunnelState>, TunnelStateTransition)),
SameState(Box<dyn TunnelState>),
Finished,
}
trait TunnelState: Send {
fn handle_event(
self: Box<Self>,
runtime: &tokio::runtime::Handle,
commands: &mut TunnelCommandReceiver,
shared_values: &mut SharedTunnelStateValues,
) -> EventConsequence;
}
```
replaces
```rust
enum EventConsequence {
NewState((TunnelStateWrapper, TunnelStateTransition)),
SameState(TunnelStateWrapper),
Finished,
}
trait TunnelState: Into<TunnelStateWrapper> + Sized {
type Bootstrap;
fn enter(
shared_values: &mut SharedTunnelStateValues,
bootstrap: Self::Bootstrap,
) -> (TunnelStateWrapper, TunnelStateTransition);
fn handle_event( …
```
> Remove tunnel state wrapper

- ci/buildserver-build-android.sh
- ci/buildserver-build.sh
- ci/buildserver-upload.sh
Since we're now uploading files into platform specific directories we need to know which platform a build is for in the upload script. This also allows for running just one instance of the upload script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5287)
> Detect platform when uploading builds from buildserver

- dist-assets/windows/installer.nsh
Rebooting is always suggested when upgrading fails, which typically occurs because there's some inexplicable file handle preventing it. This PR adds that suggestion to the installer.
Fixes DES-400.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5312)
> Suggest reboot if upgrade fails on Windows

- CHANGELOG.md
- mullvad-types/src/custom_tunnel.rs
Show the actual IP address when running `mullvad relay get` instead of `0.0.0.0`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5315)
> Fix CLI output for custom relays

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/ComposeRuleExtensions.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangelogDialogTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreenTest.kt
- android/scripts/run-instrumented-tests-locally.sh
- Add small script to more easily run all the instrumented tests locally
- Wrap all the tests in AppTheme
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5313)
> Instrumented tests not using the app theme

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift
- ios/PacketTunnelCore/Actor/ObservedState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+Extensions.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActorProtocol.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
- ios/PacketTunnelCore/Actor/State.swift
- ios/PacketTunnelCore/IPC/AppMessageHandler.swift
- ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift
- ios/PacketTunnelCoreTests/Mocks/PacketTunnelActorStub.swift
- ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
As we discussed the other day, actor `State` contains class references and some internal data which should not be retained outside of actor nor of any interest to client code.
This PR adds `ObservedState` which is a value type with all private data stripped out. It's also implements `Equatable, Codable`. In essence it mirrors `State` stripping metadata that should not be shared with the client code.
Worth to note: this work is a stepping stone to sharing actor state over IPC because since iOS 16.5 Apple introduced timeout for `NE.startTunnel()` and therefore we will have to switch the tunnel into `connected` state immediately upon start to avoid being forcefully stopped by the system while in reconnection loop. 
On the tunnel manager side we'd have to work with actor state directly and …
> Introduce observed state IOS-343

- CHANGELOG.md
- mullvad-api/src/access.rs
- mullvad-api/src/bin/relay_list.rs
- mullvad-api/src/device.rs
- mullvad-api/src/lib.rs
- mullvad-api/src/rest.rs
- mullvad-daemon/src/device/service.rs
- mullvad-daemon/src/geoip.rs
- mullvad-daemon/src/management_interface.rs
Currently, multiple concurrent API calls will all send an `auth` request for the current account, if there is no valid access token. This PR fixes this by waiting for the in-flight request to complete if there already is one.
Fix DES-311.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5323)
> Coalesce concurrent access token requests

- ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift
- ios/PacketTunnel/PacketTunnelProvider/DeviceCheck+BlockedStateReason.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
- ios/PacketTunnelCore/Actor/State.swift
Currently tunnel actor enters endless reconnection loop when configured with expired account number. Instead it should recognize why connection is broken during the device check and enter blocked state immediately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5301)
> Add blocked state due to account expiration

- ios/MullvadVPN/Containers/Root/RootContainerViewController.swift
- ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift
- ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift
When starting a payment flow from the new account view, the user can navigate away. Instead, we should block the view and show a spinner, not unlike how we currently handle the voucher redemption in the account view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5328)
> Prevent user from navigation while requesting in-app purchase

- CHANGELOG.md
- gui/src/shared/logging.ts
This PR adds error handling around console output. If `console.log` throws an error we now disable the console logger and writes the error to the file logger.
Fixes https://github.com/mullvad/mullvadvpn-app/issues/4188
Fixes DES-89
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5330)
> Add console.log error handling

- CHANGELOG.md
- gui/package-lock.json
- gui/package.json
This PR updates `@grpc/grpc-js` from `1.7.1` to `1.9.6`, and `grpc-tools` from `1.11.3` to `1.12.4`. The main reason for this is that it fixes an issue where gprc threw an exception which we weren't able to catch, resulting in a dialog with a stack trace.
Fixes DES-184
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5331)
> Update grpc-js and grpc-tools

- .github/workflows/frontend.yml
- .github/workflows/translations.yml
The volta action has been failing a lot and from what I can find there is no good solution. I'm replacing the volta action with the `setup-node` one and specify the node version from `package.json`. This also means we get dependency caching automatically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5305)
> Replace volta-cli/action with actions/setup-node

- ci/buildserver-build.sh
- ci/buildserver-config.sh
- ci/prepare-apt-repository.sh
- ci/publish-linux-repositories.sh
Add to `buildserver-build.sh` so that it upon finishing building a *release* (stable or beta) do the following:
* Construct a deb repository locally at `deb/$app_version` where the just built artifacts are added to
* Upload the constructed repository to staging repository server and **replacing** the existing repository there at `/deb/beta` and if it's a stable release also to `/deb/stable`.
The prepared repo is kept locally. So once this has been tested to work the person doing the release can publish it to production with the help of `publish-linux-repositories.sh`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5240)
> Create and upload a deb repository to staging automatically

- Cargo.lock
- mullvad-api/Cargo.toml
- mullvad-api/src/rest.rs
- mullvad-daemon/src/geoip.rs
This PR adds `mullvad_api::rest::Error::is_offline`, which returns `true` for (and only for) network errors that were due to `ENETUNREACH` (i.e., there's no route to the host). Unlike the previous code in `geoip`, it also works if an error is cloned.
Fix DES-413.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5339)
> Improve error handling for API requests that failed due to being offline

- .github/workflows/desktop-e2e.yml
- test/ci-runtests.sh
- test/test-manager/src/tests/dns.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/install.rs
- test/test-manager/src/vm/network/macos.rs
- test/test-runner/src/logging.rs
Changes:
* Fetch tags when checking out code in GH Actions (so that `ci-runtests.sh` can recognize tags).
* Make sure tests don't leave any lingering tokio tasks that were spawned.
* Cache UI runners.
* Truncate log files before transferring them and ignore `.old.log` files.
* Fix failing DNS leak tests on macOS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5346)
> Fix failing macOS DNS tests, and truncate log files in tests

- .github/workflows/desktop-e2e.yml
- test/test-manager/src/summary.rs
Upload e2e-test report matrix as an `.html` file and submit it to github actions job summary: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/
Example test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/6615036798
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5347)
> Upload End-to-end test report matrix to Github Actions

- mullvad-cli/Cargo.toml
I accidentally stumbled upon `cd mullvad-cli; cargo check` failing. It did not have all the required features on its dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5352)
> Add missing macros feature to tokio

- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/tunnel.rs
Clean up some older test cases: 
* relax (too restrictive) relay location constraints
* Use types from `mullvad_types` instead of the auto-generated gRPC types. These are generally easier to work with, and reflects how code in the rest of the app is written.
* Add some docs à la boy scout rule
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5351)
> Relax relay location constraints in some end-to-end tests

- mullvad-api/src/rest.rs
- mullvad-daemon/src/device/mod.rs
- mullvad-daemon/src/management_interface.rs
Minor cleanup that removes `Error::ResponseFailure` from `device`. It was easy to forget about it while matching, as you had to remember to "unwrap" it, so removing it makes it harder to introduce bugs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5349)
> Remove 'ResponseFailure' error variant

- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5344)
> Fix app settings string resources capitalization 

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/UnitConversion.kt
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
We had an invalid privacy policy string that contained `\n` our translations-converter tool does not support this. This PR fixes this string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5356)
> Update privacy strings

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/TextFieldColors.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5353)
> Round textfield unless showing dropdown

- ios/MullvadVPN/UI appearance/UIMetrics.swift
- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
Alert views should be scrollable, which is especially important for the change log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5354)
> Make alert view scrollable

- gui/src/renderer/components/HeaderBar.tsx
This PR increases the hitarea of the settings button and account button in the header bar. It also makes the icon light up when the surrounding button is hovered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5379)
> Increase hitarea of settings and account icons in headerbar

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CopyableObfuscationView.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/InformationView.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt
Align Account Screen with design after design review. Each value row (device name, account number & paid until) is minimum 48dp (instead of about 40 according to design) to adhere to min touch target size due to us having clickable items in some of the value rows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5372)
> Fix row paddings and backbutton orientation

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/StorePaymentManager/StorePaymentEvent.swift
- ios/MullvadVPN/StorePaymentManager/StorePaymentManager.swift
- ios/MullvadVPN/StorePaymentManager/StorePaymentManagerDelegate.swift
- ios/MullvadVPN/StorePaymentManager/StoreTransactionLog.swift
This PR introduces a transaction log to keep track of already processed transactions and prevent handling the same transaction more than once.
It turned out that a call to `SKPaymentQueue.finishTransaction()` may silently fail and then pump the same transaction back on the queue. When that happens we shouldn't upload the AppStore receipt again, instead we should only attempt to finish such transaction immediately.
Transaction log introduced in this PR stores transactions IDs in the text file as a list of newline separated strings. It is made to be thread safe in anticipation that the payment manager could be taken off the main queue and into background queue to offload the main thread, but I didn't want to go into heavy refactoring, nor introduce more asynchronous code paths. Hopefully …
> Prevent handling already processed transactions ios-365

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Chevron.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationInfo.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/VerticalDivider.kt
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/color/Color.kt
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt
- Adds alpha to chevron
- Simplifies chevron animation 
- Add missing vertical divider
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5384)
> Select location UI fixes

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt
Adjust the top bar colors according to design. Before merging we need final answer from design whether or not the Mullvad text should be tinted or not. Design currently does not have it but both Android and Desktop do.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5377)
> Review top bar

- ios/MullvadREST/RESTAuthorization.swift
- ios/MullvadREST/RESTProxy.swift
- ios/MullvadSettings/MigrationManager.swift
- ios/MullvadSettings/SettingsManager.swift
- ios/MullvadSettings/StoredWgKeyData.swift
- ios/MullvadSettings/TunnelSettings.swift
- ios/MullvadSettings/TunnelSettingsV1.swift
- ios/MullvadSettings/TunnelSettingsV2.swift
- ios/MullvadSettings/TunnelSettingsV3.swift
- ios/MullvadSettings/WireGuardObfuscationSettings.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift
- ios/MullvadVPN/SceneDelegate.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPNTests/InMemorySettingsStore.swift
- ios/MullvadVPNTests/MigrationManagerTests.swift
This PR introduces a version 3 of the settings that includes UDP over TCP obfuscation settings.
This PR also introduces back the migration scheme.
I took a couple of decisions in this PR that we already discussed beforehand, but for the sake of documentation
- We do not handle a special migration from V1 to V2 anymore, because there's a very low chance we still have users running on settings V1.
- V1 to V2 upgrade is just taking the compatible settings forward (such as DNS options and Relay Filter)
How do we want to handle version downgrade ? That's mostly a question for ourselves since users cannot downgrade the app. 
I decided to go for nothing to migrate, but we can also trigger a reset of the settings. I think it wouldn't be convenient for us though.
This PR is mostly done, but there …
> Migrate settings to Version3 and introduce incremental migration scheme.

- .github/ISSUE_TEMPLATE.md
Hello Mullvad.
I hope this small suggestion can help regarding the number of non-app related issue you are getting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5395)
> GitHub issue template: Tell users to contact support if their request is not app related

- mullvad-api/src/https_client_with_sni.rs
- mullvad-api/src/proxy.rs
- mullvad-cli/src/cmds/api_access.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/types/conversions/access_method.rs
- mullvad-types/src/access_method.rs
This change aims to make the intent of the different fields of the `Socks5Local` datastructures more clear
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5368)
> Clarify naming of variables in `Socks5Local` datastructures

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Switch.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5334)
> Move "Content blockers" closer to "Custom Dns" setting

- build-apk.sh
This PR aims to allow API override for non-release tag builds. The purpose of this is to allow the build server to easily produce devmole/stagemole builds that use the respective infrastucture environment.
Fixes: DROID-482
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5402)
> Allow api override for non-release tag builds

- android/app/src/debug/AndroidManifest.xml
- android/app/src/devmole/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/stagemole/AndroidManifest.xml
This PR aims to use the Devmole and Stagemole flavors as app label to easily distinguish the two in the launcher.
Fixes: DROID-473
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5399)
> Use infra flavor as app label

- mullvad-api/src/lib.rs
- mullvad-api/src/proxy.rs
- mullvad-api/src/rest.rs
- mullvad-cli/src/cmds/api_access.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/types/conversions/access_method.rs
- mullvad-types/src/access_method.rs
- talpid-core/src/firewall/linux.rs
- talpid-core/src/firewall/macos.rs
- talpid-types/src/net/mod.rs
Previously, the API access method "SOCKS5 running on localhost" assumed that the transport protocol used for configuring the firewall should be TCP. This covers the majority of obfuscation protocols, but far from all. If we support both TCP and UDP we should cover ~99% of all use cases.
This PR allows outgoing API traffic to be _configured_ to be either TCP or UDP. For now, only the "SOCKS5 running on localhost" access method uses this configuration option.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5320)
> Add ability to select TCP/UDP for localhost SOCKS5 API access method

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/Provider.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/RelayListListener.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionContainer.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionManager.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/ServiceConnectionManagerExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PortRangeUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/RelayListFilterUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/RelayListUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt
- android/lib/ipc/src/main/kotlin/net/mullvad/mullvadvpn/lib/ipc/Request.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/RelaySettings.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/RelayListListener.kt
- Update app RelayListener to use events and state flows instead of the old system.
- Update service RelayListener to use parsed messages instead.
- Add use cases for relay list and port ranges.
- Add filter to relay list based on ownership and selected providers.
- Add the ability to set ownership and providers and send it to the daemon.
- Get the selected ownership and providers from the daemon.
- Get a list of all providers from the relay list and if they are Mullvad owned or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5383)
> Update both RelayListeners and add use cases

- ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
- ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift
- ios/MullvadVPN/TunnelManager/TunnelState.swift
When an account expires the app sometimes go into blocked state (with banner) instead of routing to the "out of time" view. This typically happens when the tunnel is connected, but not when eg. entering app without time left on the account.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5403)
> Fix expired account UI showing blocked state instead of out of time view

- android/app/build.gradle.kts
- android/buildSrc/src/main/kotlin/VerificationConstants.kt
The check will fail unless the version code is less than 30000000. This means that all version codes up until the year 2030 are valid. The check runs before the preBuild task.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5414)
> Add version code check

- ios/MullvadVPN/View controllers/RevokedDevice/RevokedDeviceViewController.swift
This pull request updates the font weights in the `Revoked Device View` to match the design.
<table style="height: 568px; width: 600px; border-collapse: collapse; margin-left: auto; margin-right: auto;" cellspacing="20" cellpadding="28">
<tbody>
<tr>
<th>Before</th>
<th colspan="5">After</th>
</tr>
<tr>
<td style="width: 50%;"><img src="https://github.com/mullvad/mullvadvpn-app/assets/129863230/fc31494d-9bfe-4216-a0dc-1b76258a2968"  width="160" height="284" /></td>
<td style="width: 50%;"><img src="https://github.com/mullvad/mullvadvpn-app/assets/129863230/9f834764-9130-415c-97a8-3d14a8c15f61"  width="160" height="284" /></td>
</tr>
</tbody>
</table>
- - - …
> fix-font-weights-in-the-device-revoked-view-ios-377

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/CustomDateComponentsFormatting.swift
- ios/MullvadVPN/Notifications/Notification Providers/AccountExpiry.swift
- ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift
- ios/MullvadVPNTests/AccountExpiryTests.swift
- ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5391)
> Change account expiry text to display 'less than a day'

- .github/workflows/ios.yml
- ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
This is me trying to fix GitHub CI issues, by _following some random dude on the internet_. https://github.com/actions/runner-images/discussions/8651#discussioncomment-7393444
In addition to that, I have switched over to M1 instances, which are significantly faster and have more cores and I have chosen to remove the faulty test as per @buggmagnet instructions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5390)
> Remove broken test and speed up iOS CI

- mullvad-nsis/include/mullvad-nsis.h
- mullvad-nsis/src/lib.rs
- mullvad-paths/Cargo.toml
- mullvad-paths/src/cache.rs
- mullvad-paths/src/lib.rs
- mullvad-paths/src/logs.rs
- mullvad-paths/src/settings.rs
- mullvad-paths/src/windows.rs
- windows/nsis-plugins/src/cleanup/cleaningops.cpp
- windows/nsis-plugins/src/log/log.cpp
- windows/nsis-plugins/src/log/log.vcxproj
Move a bit of the C++ code to rust and make sure that log directory is protected with admin permissions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5398)
> Set permissions on log directory

- CHANGELOG.md
- mullvad-cli/src/cmds/mod.rs
- mullvad-cli/src/cmds/relay.rs
- mullvad-cli/src/cmds/reset.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/client.rs
- mullvad-management-interface/src/types/conversions/relay_constraints.rs
- mullvad-management-interface/src/types/conversions/settings.rs
- mullvad-relay-selector/src/lib.rs
- mullvad-relay-selector/src/matcher.rs
- mullvad-relay-selector/src/updater.rs
- mullvad-types/src/relay_constraints.rs
- mullvad-types/src/relay_list.rs
- mullvad-types/src/settings/mod.rs
This adds a new subcommand `mullvad relay override` that can be used to override values in the relay list. The fields that can be overridden (as of this PR) are `ipv4_addr_in` and `ipv6_addr_in`.
Fix DES-421.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5410)
> Add ability to override in-IPs to the CLI

- .github/workflows/android-app.yml
- android/test/firebase-test-lab.yml
This PR aims to add initial support for running tests in firebase test lab using github actions. The idea is to start with triggering the workflow just nightly and manually to avoid big costs.
Here's a run of the firebase job since that one doesn't run on PRs:
https://github.com/mullvad/mullvadvpn-app/actions/runs/6829209406/job/18575224767
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5416)
> Run mockapi tests in firebase test lab

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/settings.rs
Currently, we manually notify the management interface, relay selector, and parameters generator of changes to (some subset of) the settings. This is easy to forget about, so I've replaced it with a simple change event in this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5411)
> Add change listener to SettingsPersister

- .github/workflows/android-app.yml
Only run firebase tests nightly and when explicitly enabled while manually triggering a workflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5424)
> Limit firebase test execution

- ios/.swiftformat
Disable `enumNamespaces` since it seems to be broken right now and we're not sure we want to use this feature of `swiftformat`. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5426)
> Disable enumNamespace in swfitlint

- ios/.swiftlint.yml
- ios/MullvadVPN/AppDelegate.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5412)
> Exclude build folder from Swiftlint

- ios/MullvadVPN/TunnelManager/TunnelState.swift
- ios/MullvadVPN/View controllers/RevokedDevice/RevokedDeviceViewController.swift
[The designs](https://app.zeplin.io/project/5f928a32fdc9962af9018d70/screen/619ccb73de7defaada71e553) specify that if the device enters the revoked state when connected to a VPN, we should also display the following text:
"Going to login will unblock the internet on this device"
After adding blocked state this doesn't happen anymore since that isn't supported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5430)
> Add missing text about unblocking Internet on device revoked view

- gui/tasks/distribution.js
Same fix as #2266 but for RPM instead of DEB.
Basically the Linux package managers compares versions in such a way that `YYYY.NN-betaX` is regarded as a later version than `YYYY.NN`. But in our case it's the other way around. A beta is a pre-release to the corresponding stable. And for both deb and rpm this is denoted with a tilde:
> The tilde symbol ('\~') is used before a version component which must sort earlier than any non-tilde component. It is used for any pre-release versions which wouldn't otherwise sort appropriately.
For example, with upstream releases 0.4.0, 0.4.1, 0.5.0-rc1, 0.5.0-rc2, 0.5.0, the two "release candidates" should use 0.5.0\~rc1 and 0.5.0\~rc2 in the Version: field.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_complex_versioning
- - - …
> Change - to ~ before beta in rpm version to make dnf treat it as upgrade

- ci/buildserver-build.sh
- ci/buildserver-config.sh
- ci/buildserver-upload.sh
Move a few variables that were previously hardcoded in `buildserver-build.sh` on some build machines to the config file. This allows easier upgrading the build script without manually copying over bespoke config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5436)
> Configure upload dir and container cache volumes in buildserver-config

- ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift
In this PR, we check that the tunnel is not already in an error state when pressing the disconnect button.
If it is, we keep disconnecting instead of telling the user that the device has network issues.
https://github.com/mullvad/mullvadvpn-app/assets/129761703/84d0e68e-2430-46c4-a1c0-05f32e025a2a
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5437)
> Avoid showing network banners when disconnecting from an error state

- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/ServiceEndpoint.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/VoucherRedeemer.kt
This PR includes a temporary workaround to allow VoucherRedeemer to update the AccountCache (expiryTime) once the user has redeemed a voucher through the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5345)
> Add refresh AccountCache from VoucherRedeemer

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/StringConstant.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/TimingConstant.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ViewLogsViewModel.kt
Fixes crash that could happen if we render too many lines in the textfield.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5373)
> Fix view logs crash

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AccountRepository.kt
Fixes a regression from previous bugfix where we set flowables to be eagerly started, however, this specific flow uses a `onStart` that would execute before the Daemon connection is setup and ready thus not getting a reply. I've now changed it to be lazily loaded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5440)
> Fix missing account history on new start

- ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5439)
> Show success alert when making purchase from "out of time"-view

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
- ios/MullvadVPN/Coordinators/TunnelCoordinator.swift
- ios/MullvadVPN/GeneralAPIs/OutgoingConnectionData.swift
- ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift
- ios/MullvadVPN/SceneDelegate.swift
- ios/MullvadVPN/UI appearance/UIMetrics.swift
- ios/MullvadVPN/View controllers/Tunnel/ConnectionPanelView.swift
- ios/MullvadVPN/View controllers/Tunnel/OutgoingConnectionService.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelViewControllerInteractor.swift
- ios/MullvadVPNTests/MockURLProtocol.swift
- ios/MullvadVPNTests/OutgoingConnectionProxy+Stub.swift
- ios/MullvadVPNTests/OutgoingConnectionProxyTests.swift
- ios/MullvadVPNTests/OutgoingConnectionServiceTests.swift
- ios/MullvadVPNTests/XCTest+Async.swift
this PR introduces a valuable feature that enhances the user experience by showing outgoing addresses in the connection view. This information is especially useful when access to exit IPs is available, and the implementation ensures the accuracy and completeness of the displayed data by making two network requests and waiting for their successful completion.these actions are taken to achieve the result :
1.**Network Requests for IP Addresses**: To gather the necessary information, two network requests are initiated, one for IPv4 and the other for IPv6 addresses. These requests are essential for determining the exit IP address associated with the established tunnel.
2. **Wait for Completion:** The system intelligently waits for both of these requests to be completed successfully, ensuring …
> show outgoing connection on map

- gui/src/renderer/components/OpenVpnSettings.tsx
Issue introduced in https://github.com/mullvad/mullvadvpn-app/pull/5376. When changing the OpenVPN transport protocol the port isn't reset resulting in the blocked state if connected. This is fixed by resetting the port when changing transport protocol.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5445)
> Reset port when chaning transport protocol

- ci/buildserver-build.sh
- ci/buildserver-config.sh
- ci/prepare-rpm-repository.sh
- ci/publish-linux-repositories.sh
With this PR the build server now generates an RPM repository and publish it to the development repository servers (and staging if this is a release build, just like we do for deb).
Just like for deb, production repos are manually published later by running:
```
./publish-linux-repositories.sh --production $app_version deb/$app_version rpm/$app_version
```
This also fixes a bug where we previously called `publish_linux_repositories` on all platforms. That's now guarded behind a `if [[ "$(uname -s)" == "Linux" ]]; then`. This was not caught earlier because these build scripts have not been updated on the non-linux machines since it was added a few weeks ago.
- - - …
> Publish RPM repository on build servers

- ios/OperationsTests/OperationSmokeTests.swift
This test is flaky when the system is under a lot of pressure due to the usage of the global dispatch queue.
Use a local queue instead to avoid that problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5448)
> Do not use global dispatch queue in tests

- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/mod.rs
- test/test-manager/src/tests/tunnel.rs
- test/test-manager/src/tests/tunnel_state.rs
- test/test-manager/src/tests/ui.rs
Delegate the task of picking entry & exit nodes to the relay selector in `test_bridge` because of latency concerns. 
We have seen `test_bridge` fail due to high latency if slow + far-away servers were
selected, even with a generous timeout of 10 seconds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5442)
> Remedy connection check timeouts in `test_bridge`

- CHANGELOG.md
- mullvad-cli/src/cmds/import_settings.rs
- mullvad-cli/src/cmds/mod.rs
- mullvad-cli/src/main.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/settings/mod.rs
- mullvad-daemon/src/settings/patch.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/client.rs
This adds a command `mullvad import-settings` for applying patches to the settings. It takes a positional argument that should bet set either to a path (for reading from a file) or `-` (from stdin).
Currently, only changes to relay overrides are recognized. Changes to other settings are unrecognized/rejected by the daemon.
Here is an example of a valid patch:
```bash
$ mullvad import-settings -
{
"relay_overrides": [
{
"hostname": "se-got-wg-001",
"ipv4_addr_in": "1.2.3.4"
}
]
}
```
Related: #5410
Fixes DES-445
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5435)
> Add CLI support for applying settings patches

- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
As part of a timeboxed issue I looked through Play Store crashes and found that we have the wrong signature on this JNI calling function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5365)
> Fix getDevice method signature

- CHANGELOG.md
- gui/src/renderer/components/TransitionContainer.tsx
This PR decreases the risk of the app freezing due to race conditions in `TransitionContainer` by using `isCycling` instead of `isTransitioning` to know weather a navigation is in progress. `isTransitioning` is set to true when the actual transition starts and `isCycling` is set to true when the navigation is being acted on, i.e. a lot earlier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5458)
> Decrease risk of app freezing due to race conditions in transition animations

- gui/src/main/daemon-rpc.ts
This PR adds the `grpc.client_idle_timeout_ms` option and sets a high value to prevent the connection from going into the idle state. This option was introduce in `@grpc/grpc-js@1.9.0` which we upgraded to in https://github.com/mullvad/mullvadvpn-app/pull/5331.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5460)
> Prevent gRPC channel from entering the idle state

- gui/src/shared/logging.ts
This PR removes a line of code that was used for debugging failures in the console logger, that was forgotten about before merging. It was added in this PR: https://github.com/mullvad/mullvadvpn-app/pull/5330.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5461)
> Remove debug code in logging function

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ProblemReportRepository.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/fragment/ProblemReportFragment.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ReportProblemViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ReportProblemModelTest.kt
Also restore secure view behaviour for Send report problem success screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5457)
> Fix problem reports not being kept correctly

- CHANGELOG.md
- android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5468)
> Update changelog for `android/2023.8-beta1`

- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Providers.kt
- android/lib/payment/src/main/kotlin/net/mullvad/mullvadvpn/lib/payment/PaymentProvider.kt
- android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/classes/ValueClassTests.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5474)
> Add value class assertion test

- ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift
For the packet tunnel to receive traffic, it needs to have a peer configured so that the system configures routes for it. Otherwise, no routes are applied and all traffic leaks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5477)
> Fix leak in blocked state

- .github/workflows/android-static-analysis.yml
This PR aims to add an action that runs the static analysis tool `mobsfscan`. It's currently not configured to fail on warnings since we first need to address those. 
More info about the tool here: https://github.com/MobSF/mobsfscan 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5480)
> Add static analysis tool mobsfscan

- android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/SdkUtils.kt
To fix issue caused in firebase
```
Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5479)
> Add allow implicit flag

- android/lib/ipc/src/main/kotlin/net/mullvad/mullvadvpn/lib/ipc/DispatchingHandler.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5476)
> Fix account history events being lost because of buffer overflow

- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-types/src/access_method.rs
This PR solves a bug where the daemon could end up in an irrecoverable error state due to missing access methods.
If the user disable all of their configured access methods, the daemon would suddenly crash and be unable to start up again due to it expecting there to always be at least one enabled access method.
Fixes DES-475
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5482)
> Fix daemon ending up in irrecoverable error state due to missing access methods

- .github/workflows/desktop-e2e.yml
- mullvad-daemon/src/lib.rs
- mullvad-management-interface/src/client.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/disconnected_state.rs
- talpid-core/src/tunnel_state_machine/disconnecting_state.rs
- talpid-core/src/tunnel_state_machine/error_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- test/test-manager/src/tests/account.rs
- test/test-manager/src/tests/dns.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/install.rs
- test/test-manager/src/tests/mod.rs
- test/test-manager/src/tests/settings.rs
- test/test-manager/src/tests/tunnel.rs
- test/test-manager/src/tests/tunnel_state.rs
- test/test-rpc/src/client.rs
- test/test-rpc/src/lib.rs
- test/test-runner/src/main.rs
- test/test-runner/src/net.rs
Main changes:
* Fix potential races in the management interface by returning from the following commands only after the tunnel state has been updated: `set_allow_lan`, `set_dns_options`, `set_block_when_disconnected`.
* Obtain tunnel interface from management interface instead of hardcoding it. This was too fragile, particularly on macOS.
* Work around bug involving `fetch-tags` in the GHA e2e workflow. Use `git fetch --tags` directly.
* Simplify `test_multihop` and `test_udp2tcp` (analogously to #5442).
Fix DES-443.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5441)
> Fix tests that fail on macOS 14

- ios/MullvadSettings/WireGuardObfuscationSettings.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/View controllers/Preferences/CustomDNSCellFactory.swift
- ios/MullvadVPN/View controllers/Preferences/CustomDNSDataSource.swift
- ios/MullvadVPN/View controllers/Preferences/CustomDNSViewController.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesDataSourceDelegate.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesInfoButtonItem.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesInteractor.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift
This PR is mostly accomplishing 2 goals:
- Wiring up the WireGuard obfuscation settings to be saved in the tunnel settings
- Separating the WireGuard settings and the DNS settings into 2 different screens
The PR looks big, but most of the code is just being moved around.
The aim was to declutter `PreferencesDataSource`, parts of it were moved to `CustomDNSDataSource`
- We are thinking of adding a "WireGuard settings" title below the cell that goes to the DNS settings for better visual separation of sections
Here's what it looked like before the changes
Here's what it looks like after the changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5433)
> Save WireGuard obfuscation settings choice and move DNS settings to a custom view

- mullvad-daemon/src/settings/patch.rs
Fix some uncaught clippy lints in tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5491)
> Fix uncaught clippy warnings and a typo.

- CHANGELOG.md
- Cargo.lock
- mullvad-cli/Cargo.toml
- mullvad-cli/src/cmds/bridge.rs
- mullvad-cli/src/cmds/custom_list.rs
- mullvad-cli/src/cmds/debug.rs
- mullvad-cli/src/cmds/mod.rs
- mullvad-cli/src/cmds/relay.rs
- mullvad-cli/src/cmds/relay_constraints.rs
- mullvad-cli/src/main.rs
- mullvad-types/src/relay_list.rs
Make the CLI arguments that parse `LocationArgs` validate the input. Specifically, make sure that the country or host exists and, if hostname is given, then validate the server type (e.g. only bridge host for the bridge command).
Some braking changes to the CLI were done, see the changelog.
You can no longer enter the blocked state through `mullvad relay set location xx`. Instead a hidden command `mullvad debug block-connection` was added. See issue https://linear.app/mullvad/issue/DES-453/update-test-instructions-to-use-new-block-command about updating test instruction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5462)
> Error handling for location argument in CLI DES-435

- ios/MullvadVPN/Supporting Files/Info.plist
After iOS 14 Apple have added a new Property List Key called `NSPinnedDomains` in `NSAppTransportSecurity` that holds a collection of certificate that `App Transport Security` expects when connecting to named domains.
This pull request leverages the newly introduced capability to pin the public keys of certificates associated with exit IP addresses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5443)
> tls-pinning-via-infoplist-if-thats-easier-to-do-for-ios-386

- build-apk.sh
This PR aims to make sure that devmole and stagemole builds are enabled when the daemon api-override flag is set to enable overriding the api endpoint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5504)
> Only build devmole and stagemole builds when api-override supported

- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/tile/src/main/kotlin/net/mullvad/mullvadvpn/tile/MullvadTileService.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5492)
> Fix crash with auto-connect and no permission

- gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts
Fix the failing test `test_ui_tunnel_settings` that invoked `mullvad relay set location xx`, which is no longer valid syntax.
Replace it with `mullvad debug block-connection`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5505)
> Update test with new CLI command

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5487)
> Add payment verification to Connect Screen

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/provider/MullvadFileProvider.kt
- android/app/src/main/res/xml/provider_paths.xml
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
Attempt of sharing text through share intent don't work due to the text being too long, this PR replaces it by sharing it as a file instead. This PR also offers the option to directly copy the logs into clipboard.
It is possible to crash system UI with this PR since the new Copy dialog from system also offers a "share" functionality which will share the logs in a similar fashion as we did before, thus causing `intentChooser` to fail due to the text being too long.. To reproduce this add, `repeat(5)` in `ViewLogsUiState` to the `text()` function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5485)
> Replace text share with file share

- android/lib/endpoint/src/main/kotlin/net/mullvad/mullvadvpn/lib/endpoint/CustomApiEndpointConfiguration.kt
This PR enables forced API direct connection as well as disables API address caching to improve testing against the devmole and stagemole environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5509)
> Enable forced direct connection for devmole and stagemole builds

- mullvad-api/src/lib.rs
- mullvad-daemon/src/geoip.rs
- mullvad-daemon/src/lib.rs
Add periodic retry for `GetCurrentLocation`.
~~I can not reproduce the original error so I haven't been able to make the new code actually run. We need to see if this fixes the problem, and decide what an appropriate retry interval and max attempts are.~~
I tested by blocking traffic to am.i.mullvad.net, and it seems to work as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5486)
> Retry fetching out IP DES-118

- .github/workflows/desktop-e2e.yml
This lets us run tests on only a subset of supported OSes.
Fix DES-484.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5507)
> Select targets to run tests on in GitHub Actions

- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelPathObserver.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
We should throttle the updates we receive from monitoring the default path via KVO. Since flopping back and forth can be detrimental and causes the tunnel to thrash, the changes should be throttled. Finding the optimal parameters and throttling strategy is subject to discussion.
Current implementation removes duplicate updates and throttles the remaining for 2 seconds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5511)
> Throttle network path updates in packet tunnel

- talpid-tunnel-config-client/Cargo.toml
Fixes the build error:
```
$ cargo build --example psk-exchange
error[E0433]: failed to resolve: could not find `main` in `tokio`
--> talpid-tunnel-config-client/examples/psk-exchange.rs:7:10
|
7 | #[tokio::main]
|          ^^^^ could not find `main` in `tokio`
error[E0752]: `main` function is not allowed to be `async`
--> talpid-tunnel-config-client/examples/psk-exchange.rs:8:1
|
8 | async fn main() {
| ^^^^^^^^^^^^^^^ `main` function is not allowed to be `async`
Some errors have detailed explanations: E0433, E0752.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `talpid-tunnel-config-client` (example "psk-exchange") due to 2 previous errors
```
- - - …
> Fix error when building psk-exchange example

- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+NetworkReachability.swift
- ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift
- ios/PacketTunnelCore/TunnelMonitor/TunnelMonitorProtocol.swift
- ios/PacketTunnelCoreTests/Mocks/TunnelMonitorStub.swift
- ios/PacketTunnelCoreTests/TunnelMonitorTests.swift
The packet tunnel provider supplies both the actor and tunnel monitor with its own network path observer, which isn't ideal and makes the code harder to follow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5514)
> Refactor packet tunnel to use only a single network path observer

- ios/MullvadSettings/WireGuardObfuscationSettings.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnel/PacketTunnelProvider/RelaySelectorWrapper.swift
- ios/PacketTunnel/PacketTunnelProvider/SettingsReader.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift
- ios/PacketTunnelCore/Actor/Protocols/RelaySelectorProtocol.swift
- ios/PacketTunnelCore/Actor/Protocols/SettingsReaderProtocol.swift
- ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift
- ios/PacketTunnelCoreTests/Mocks/PacketTunnelActor+Mocks.swift
- ios/PacketTunnelCoreTests/Mocks/ProtocolObfuscationStub.swift
- ios/PacketTunnelCoreTests/Mocks/RelaySelectorStub.swift
- ios/PacketTunnelCoreTests/Mocks/SettingsReaderStub.swift
- ios/PacketTunnelCoreTests/Mocks/TunnelObfuscationStub.swift
- ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
- ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift
- ios/TunnelObfuscation/UDPOverTCPObfuscator.swift
- ios/TunnelObfuscationTests/TunnelObfuscationTests.swift
This PR makes the `PacketTunnelActor` use the `UDPOverTCPObfuscator` via the generic `ProtocolObfuscator`
The following considerations were taken into account:
- We plan to have multiple obfuscators in the future (Hence the generic `ProtocolObfuscator`)
- The retry logic is based on the desktop's [RelaySelector logic](https://github.com/mullvad/mullvadvpn-app/blob/main/mullvad-relay-selector/src/lib.rs) and [documentation](https://github.com/mullvad/mullvadvpn-app/blob/main/docs/relay-selector.md#default-constraints-for-tunnel-endpoints)
- I decided to not implement the logic inside our `RelaySelector` to avoid code bloat
- Build the app
- Go to Settings > VPN Settings
- Select any of the options in WireGuard Obfuscation and UDP-over-TCP port
- Connect your debugger to the packet tunnel
- …
> Have the PacketTunnel use UDP-over-TCP Obfuscation

- mullvad-api/src/lib.rs
- mullvad-api/src/rest.rs
- mullvad-cli/src/cmds/api_access.rs
- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/client.rs
- mullvad-management-interface/src/types/conversions/net.rs
- mullvad-types/src/access_method.rs
Move access method testing logic to `mullvad-daemon`, which means that the implementation details of how the test works is opaque to whatever frontend which wants to issue a test of some (configured) access method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5370)
> Move access method testing logic to `mullvad-daemon`

- CHANGELOG.md
- talpid-routing/Cargo.toml
- talpid-routing/src/lib.rs
- talpid-routing/src/unix/linux.rs
- talpid-wireguard/src/config.rs
- talpid-wireguard/src/lib.rs
- talpid-wireguard/src/wireguard_kernel/nm_tunnel.rs
- talpid-wireguard/src/wireguard_kernel/wg_message.rs
- talpid-wireguard/src/wireguard_nt.rs
This prevents fragmentation when multihop is enabled.
Fix DES-483.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5501)
> Set default route MTU when using multihop on Linux

- ios/MullvadSettings/WireGuardObfuscationSettings.swift
We've introduced breaking changes in the current main that necessitate a new settings schema version. We should add a migration and bump the schema version for this. This can currently be verified by installing a main version over 2023.7.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5543)
> Update settings schema to V4 to fix a migration bug in obfuscation settings

- ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift
A banner with a blocked state reason (unable to authenticate account) is shown when on the account revoked screen. This is superfluous information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5531)
> Do not show account revoked banner when on account revoked screen

- ci/buildserver-config.sh
Mantic has been out since ~2 months. We really should have it in our DEB repository. Requested here: https://github.com/mullvad/mullvadvpn-app/issues/3049#issuecomment-1840264691
We officially only support the latest non-LTS release, not further back. But I feel like it would cause a lot of issues for users if we immediately on an Ubuntu release unsupport one version when we switch to the new one. So I propose we have a ~6 month overlap. Meaning we technically support the two latest non-LTS releases in the DEB repository.
We could remove "lunar" (release N-1) earlier than when the next version comes out. But then we would need to change this file more often. Easier to just change it once on every Ubuntu release.
- - - …
> Add Ubuntu 23.10 (Mantic) to DEB repository

- ios/MullvadTypes/TransportLayer.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlViewModel.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
- ios/PacketTunnelCore/Actor/ObservedState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift
- ios/PacketTunnelCore/Actor/State.swift
- ios/PacketTunnelCoreTests/Mocks/ProtocolObfuscationStub.swift
- ios/PacketTunnelCoreTests/Mocks/TunnelObfuscationStub.swift
- ios/TunnelObfuscation/UDPOverTCPObfuscator.swift
Final part of the UDP-over-TCP obfuscation feature. 
This PR :
- Refactors `TunnelControlViewModel`
- Unifies how `TunnelControlView` gets its data source (more could be done, but the PR was already big enough)
- Resurfaces the port and protocol layer used by the Packet Tunnel to connect to an endpoint
- Introduces an `ObfuscateConnection` method that will take a `MullvadEndpoint` and seamlessly create an obfsucator to use
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5548)
> Reflect obfuscation protocol in UI ios 398

- mullvad-daemon/src/target_state.rs
- test/test-manager/src/tests/account.rs
- test/test-manager/src/tests/tunnel_state.rs
- test/test-rpc/src/client.rs
- test/test-rpc/src/lib.rs
- test/test-runner/Cargo.toml
- test/test-runner/src/app.rs
- test/test-runner/src/main.rs
- test/test-runner/src/net.rs
- test/test-runner/src/sys.rs
Add regression test which checks that the daemon successfully recovers from a corrupt target state cache. 
If the target state cache is corrupt, the daemon should default to the `Connecting` target state on startup.
Fixes DES-460
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5513)
> Add regression test: Default to connecting state on corrupt state cache

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/PaymentConstant.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/LongExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
1) Add exponential back off for purchase verification
2) Add purchase verification after a purchase flow has failed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5512)
> Improve Purchase api verification

- .github/workflows/ios-screenshots.yml
- .github/workflows/ios.yml
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNScreenshots.xcscheme
- ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift
- ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift
- ios/Snapfile
Fixes the broken screenshots test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5558)
> Fix screenshots test

- CHANGELOG.md
- mullvad-relay-selector/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5574)
> Block OpenVPN relays from being selected on android

- docs/relay-selector.md
- mullvad-daemon/src/device/mod.rs
- mullvad-daemon/src/lib.rs
- mullvad-relay-selector/src/lib.rs
This PR adds a unit tests for device validity checks. It also removes some outdated or incorrect documentation for the relay selector.
Fix DES-500.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5557)
> Add unit test for device validity check

- .github/workflows/ios-screenshots.yml
The screenshots creation step in Github fails becuase fastlane build cannot find the spm packages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5583)
> Add spm dir to ios screenshots Github action

- docs/relay-selector.md
- mullvad-daemon/src/device/mod.rs
- mullvad-relay-selector/src/lib.rs
- talpid-types/src/net/mod.rs
This PR changes the default constraints somewhat. WireGuard is used three times instead of two: once on a random port, once on port 53, and once using udp2tcp (if obfuscation is `auto`).
In general, when the tunnel protocol is WireGuard and no port is set, the relay selector simply alternates between a random port and port 53.
The device validity check occurs on every third attempt instead of on every other attempt.
Fix DES-486.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5567)
> Check if the device is valid on every third connection attempt

- test/build.sh
- test/test-runner/src/sys.rs
The new image used for building the test framework (since #5569) overrode `CARGO_TARGET_DIR`, which lead to the `test-runner` artifact being output in an unexpected target directory. This PR sets the expected `CARGO_TARGET_DIR` explicitly.
This PR also drive-by fixes an issue with the macOS test-runner not being able to start the mullvad-daemon after it has been stopped by a test case, causing the test suite to halt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5585)
> Fix missing test runner binary in CI

- mullvad-daemon/src/settings/mod.rs
Verify that the app enables "Always require VPN" by default if the settings cannot be parsed.
These changes/additions aims to guard against regressions to this behavior. This behavior was introduced in the 2022.1 desktop release: https://github.com/mullvad/mullvadvpn-app/blob/main/CHANGELOG.md#security-7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5565)
> Test for expected app state if settings can not be parsed

- android/app/lint-baseline.xml
- android/app/src/debug/AndroidManifest.xml
- android/test/e2e/src/main/AndroidManifest.xml
- android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/EndToEndTest.kt
Add new permission instead of READ/WRITE _EXTERNAL_STORAGE on android api level 33+.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5314)
> Replace EXTERNAL_STORAGE permissions on android api level 33+

- .github/workflows/android-app.yml
- .github/workflows/testframework-clippy.yml
- .github/workflows/testframework-rustfmt.yml
- .github/workflows/testframework.yml
- test/Dockerfile
- test/test-manager/src/mullvad_daemon.rs
- test/test-manager/src/run_tests.rs
- test/test-rpc/src/transport.rs
- test/test-runner/src/main.rs
- test/test-runner/src/net.rs
- test/test-runner/src/sys.rs
The testing framework living in `test/` historically had no CI checks. It didn't use to have it while it was developed in a separate repository, nor did it get any during its adoption into the app repository.
This PR introduces some basic CI checks when application logic is touched in the `test` workspace:
- `rustfmt --check` is run on all Rust source files
- `clippy` is run with the same configuration as the main app
- `test-runner` is compiled for all supported platforms (Linux, Windows & macOS)
- `test-manager` is compiled for all supported host platforms (Linux & macOS)
This should hopefully stabilize the development done to the testing framework. There is still more to be done on the CI front in the testing framework, but this is a good start.
Fixes DES-502
- - - …
> Add CI workflows for `test` workspace

- android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/extension/UiAutomatorExtensions.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LoginMockApiTest.kt
This PR aims to make sure the mockapi tests handle the case of the changes dialog being show. This has only been a "problem" on release branches etc where we bundle release notes in the build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5593)
> Fix changes dialog dismissal in mockapi tests

- .github/workflows/ios-screenshots-creation.yml
- .github/workflows/ios-screenshots-tests.yml
- .github/workflows/ios.yml
Currently, the screenshot test is executed right after all other unit tests in the ios GH workflow. This is slow, and we'd like to get our CI job to run for 5-6 minutes instead of 7 to 9 minutes. 
To get the CI job to be faster, we should create a separate GH workflow that runs the screenshot tests exclusively, only after merge commits on main and only if ios/ directory was changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5589)
> Execute screenshot tests after merging to main

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationBanner.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/notificationbanner/NotificationData.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/ConnectUiState.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SettingsUiState.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SettingsViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SettingsViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt
We use IS_PLAY_BUILD directly in ViewModel's and UI, this makes it unnecessarily hard to do testing when one is not able to set it easily. This PR lifts the property up so it is injected instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5598)
> Lift IS_PLAY_BUILD to DI

- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNMockRelease.xcscheme
We should make it easy to see how the app will look in a proper release without going through our build servers. This PR adds a new scheme called `MullvadVPNMockRelease` that runs the app in release mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5600)
> Create build profile that resembles Release but without signing

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/Containers/Root/HeaderBarView.swift
- ios/MullvadVPN/Coordinators/ChangeLogCoordinator.swift
- ios/MullvadVPN/Coordinators/WelcomeCoordinator.swift
- ios/MullvadVPN/View controllers/Account/AccountContentView.swift
- ios/MullvadVPN/View controllers/Account/AccountDeviceRow.swift
- ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionContentView.swift
- ios/MullvadVPN/View controllers/Alert/AlertPresentation.swift
- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
- ios/MullvadVPN/View controllers/CreationAccount/Completed/SetupAccountCompletedContentView.swift
- ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift
- ios/MullvadVPN/View controllers/Login/LoginContentView.swift
- ios/MullvadVPN/View controllers/Login/LoginViewController.swift
- ios/MullvadVPN/View controllers/Preferences/CustomDNSCellFactory.swift
- ios/MullvadVPN/View controllers/Preferences/CustomDNSDataSource.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift
- ios/MullvadVPN/View controllers/RelayFilter/RelayFilterCellFactory.swift
- ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewController.swift
- ios/MullvadVPN/View controllers/SelectLocation/SelectLocationCell.swift
- ios/MullvadVPN/View controllers/Settings/SettingsCell.swift
- ios/MullvadVPN/View controllers/Settings/SettingsCellFactory.swift
- ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift
- ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift
- ios/MullvadVPN/View controllers/TermsOfService/TermsOfServiceContentView.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift
Our screenshots script queries UI elements using hardcoded string identifiers assigned via the `accessibilityIdentifier` property. We should formalize all of those into an enum and use it instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5599)
> Export identifiers for accessibility elements

- wireguard/libwg/go.mod
- wireguard/libwg/go.sum
While Windows support was removed, wireguard-go still indirectly require wintun. This causes `go mod vendor` to fail on libwg (which is what some package managers currently use) with the following error:
```
github.com/mullvad/mullvadvpn-app/wireguard/libwg imports
golang.zx2c4.com/wireguard/tun imports
golang.zx2c4.com/wintun: missing go.sum entry for module providing package golang.zx2c4.com/wintun (imported by golang.zx2c4.com/wireguard/tun); to add:
go get golang.zx2c4.com/wireguard/tun@v0.0.0-20220703234212-c31a7b1ab478
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5621)
> libwg: Revert wintun removal from go.sum/go.mod

- gui/src/renderer/components/VpnSettings.tsx
Fix IPv6 address format in "Local network sharing" info dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5623)
> Fix format of IPv6 addresses in allow lan info dialog

- gui/locales/messages.pot
- gui/src/renderer/components/Settings.tsx
We don't want names of technologies to be translated, this includes "Split tunneling". This was by mistake added to be translated for the navigation button in the settings view.
Fixes DES-348
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5626)
> Prevent translation of Split tunneling in settings view

- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/api.rs
- mullvad-types/src/access_method.rs
If all access methods are manually disabled, the daemon should gracefully enable the built-in `Direct` access method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5617)
> Prevent all access methods from being disabled at once

- talpid-routing/src/unix/macos/interface.rs
This ends up being logged whenever a default is added or removed, if there's no primary IPv6 interface:
```
[2024-01-01 01:05:08.494][talpid_routing::imp::imp::interface][DEBUG] Found primary interface for V4
[2024-01-01 01:05:08.495][talpid_routing::imp::imp::interface][DEBUG] No primary interface for V6. Checking service order
[2024-01-01 01:05:08.495][talpid_routing::imp::imp::interface][DEBUG] No V6 dict for [REDACTED]
[2024-01-01 01:05:08.495][talpid_routing::imp::imp::interface][DEBUG] No V6 dict for [REDACTED]
[2024-01-01 01:05:08.495][talpid_routing::imp::imp::interface][DEBUG] No V6 dict for [REDACTED]
[2024-01-01 01:05:08.495][talpid_routing::imp::imp::interface][DEBUG] No V6 dict for [REDACTED]
[2024-01-01 01:05:08.495][talpid_routing::imp::imp::interface][DEBUG] No V6 dict for …
```
> Remove excessive logging of interfaces on macOS

- building/Dockerfile
Also removes the enabling of sparse as it is now default.
https://github.com/rust-lang/rust/blob/master/RELEASES.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5644)
> Bump go version to 1.21.3 in linux docker file

- android/docker/Dockerfile
- android/docker/goruntime-boottime-over-monotonic.diff
Go patch taken from here: https://git.zx2c4.com/wireguard-android/plain/tunnel/tools/libwg-go/goruntime-boottime-over-monotonic.diff?id=01e72064d440036157bde5947fec23157beb8bfe
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5646)
> Update base linux image and go patch

- talpid-core/src/firewall/macos.rs
Previously, only the first SYN packet was allowed in the firewall. If the connection to the custom proxy server was initiated before connecting to the VPN, this packet was never seen, so PF blocked the connection.
Note: This prevents PF from blocking connections to the first hop that were initiated before the rules were added.
Introduced in [#5587](https://github.com/mullvad/mullvadvpn-app/pull/5587)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5647)
> Fix local proxy not working if started before connecting

- .github/workflows/daemon.yml
- .github/workflows/desktop-e2e.yml
- android/fdroid-build/init.sh
- building/README.md
- building/android-container-image.txt
- building/linux-container-image.txt
- wireguard/libwg/Android.mk
- wireguard/libwg/go.mod
- wireguard/libwg/go.sum
- wireguard/libwg/goruntime-boottime-over-monotonic.diff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5559)
> Update go to version 1.21.3 and wireguard go to 20230223181233

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt
This PR handles the event of a device being revoked on the Connect screen, a regression from migrating to compose navigation. It also makes sure that we properly logout the user when "Go to login" is pressed in DeviceRevoked screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5604)
> Handle Device revoked on connect screen

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt
This is so that we stop showing the error while the user tries to change the voucher code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5608)
> Remove error message when changing the voucher input

- build.sh
Fixes DES-193.
An issue with the `--target` flag to cargo build caused caching not to work properly on macOS slowing down the CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5602)
> Speed up builds on macOS

- ios/TunnelObfuscation/tunnel-obfuscator-proxy/src/ffi.rs
- ios/TunnelObfuscation/tunnel-obfuscator-proxy/src/lib.rs
- mullvad-api/src/lib.rs
- mullvad-api/src/proxy.rs
- mullvad-cli/src/cmds/api_access.rs
- mullvad-cli/src/cmds/import_settings.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/device/mod.rs
- mullvad-daemon/src/exception_logging/unix.rs
- mullvad-daemon/src/migrations/mod.rs
- mullvad-daemon/src/migrations/v7.rs
- mullvad-daemon/src/settings/mod.rs
- mullvad-daemon/src/tunnel.rs
- mullvad-nsis/src/lib.rs
- mullvad-paths/src/windows.rs
- mullvad-types/src/account.rs
- talpid-core/src/dns/windows/iphlpapi.rs
- talpid-core/src/firewall/macos.rs
- talpid-core/src/firewall/windows.rs
- talpid-openvpn/src/lib.rs
- talpid-openvpn/src/process/openvpn.rs
- talpid-routing/src/unix/macos/mod.rs
- talpid-windows/src/net.rs
Fix Clippy lints and format with `+nightly`.
These lints where missed since Clippy doesn't check tests by default, it needs the  `--all-targets` flag. This is fixed in #5659.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5658)
> Lints and formatting

- CHANGELOG.md
- gui/assets/css/global.css
- gui/src/renderer/components/SvgMap.tsx
This PR adds support for `prefer-reduced-motion` by disabling movement transitions when that setting is on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5628)
> Respect prefer-reduced-motion

- mullvad-api/src/bin/relay_list.rs
- mullvad-api/src/lib.rs
- mullvad-api/src/proxy.rs
- mullvad-api/src/rest.rs
- mullvad-cli/src/cmds/status.rs
- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-jni/src/jni_event_listener.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/client.rs
- mullvad-management-interface/src/types/conversions/access_method.rs
- mullvad-problem-report/src/lib.rs
- mullvad-setup/src/main.rs
- test/test-manager/src/tests/account.rs
This PR changes how the `AccessModeSelector` interacts with the daemon. A new internal daemon (`AccessMethodEvent`) event has been added in order for the `AccessModeSelector` to properly be able to delegate the job of applying the correct firewall rules for any given access method. This allowed us to get rid of `ApiEndpointUpdateCallback` from the `RequestService`.
Fixes DES-521
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5605)
> Broadcast API access method changes

- ios/MullvadREST/Transport/Socks5/AnyIPEndpoint+Socks5.swift
- ios/MullvadREST/Transport/Socks5/Socks5Authentication.swift
- ios/MullvadREST/Transport/Socks5/Socks5Configuration.swift
- ios/MullvadREST/Transport/Socks5/Socks5Connection.swift
- ios/MullvadREST/Transport/Socks5/Socks5Constants.swift
- ios/MullvadREST/Transport/Socks5/Socks5Error.swift
- ios/MullvadREST/Transport/Socks5/Socks5ForwardingProxy.swift
- ios/MullvadREST/Transport/Socks5/Socks5UsernamePasswordCommand.swift
- ios/MullvadREST/Transport/Socks5/URLSessionSocks5Transport.swift
- ios/MullvadREST/Transport/TransportProvider.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
This PR implements username password authentication for our `Socks5Connection` object.
This authentication method is following
- [RFC-1928](datatracker.ietf.org/doc/html/rfc1928) for the socks protocol
- [RFC-1929](https://datatracker.ietf.org/doc/html/rfc1929) for the username / password authentication system.
In order to use username / password authentication, we need to declare that our client supports that method.
We do so here.
```swift
/// Start handshake with the socks proxy.
private func sendHandshake() {
var handshake = Socks5Handshake()
if configuration.username != nil && configuration.password != nil {
handshake.methods.append(.usernamePassword)
}
```
Once we have exchanged the handshake, and the server has decided to use that handshake, we send a `Socks5Authentication` …
> Add username password command

- test/test-manager/src/config.rs
- test/test-manager/src/main.rs
- test/test-manager/src/run_tests.rs
- test/test-manager/src/summary.rs
- test/test-manager/src/tests/config.rs
- test/test-manager/src/tests/install.rs
- test/test-manager/src/tests/test_metadata.rs
- test/test-manager/src/tests/tunnel.rs
- test/test-manager/src/tests/ui.rs
- test/test-manager/test_macro/src/lib.rs
- test/test-rpc/src/client.rs
- test/test-rpc/src/lib.rs
- test/test-rpc/src/meta.rs
- test/test-runner/src/main.rs
This PR makes it possible to write tests that only run on a specific OS, either Linux, macOS, or Windows. The "OS under test" was also moved to `TEST_CONFIG`, since it's a constant and we know it in advance.
Closes DES-533.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5650)
> Add `target_os` attribute to test framework

- ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionContentView.swift
This PR changes the "OK" button into a "Delete account" button when deleting an account.
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5657)
> Change OK text into Delete Account text

- .github/workflows/clippy.yml
- .github/workflows/testframework-clippy.yml
Make Clippy lints in the CI pipeline capture problems inside tests by using the `--all-targets` flag.
Note that "targets" does not refer to OS/architectures, it has the same meaning as for `cargo build`:
```
> cargo build --help
...
Target Selection:
--lib               Build only this package's library
--bins              Build all binaries
--bin [<NAME>]      Build only the specified binary
--examples          Build all examples
--example [<NAME>]  Build only the specified example
--tests             Build all test targets
--test [<NAME>]     Build only the specified test target
--benches           Build all bench targets
--bench [<NAME>]    Build only the specified bench target
--all-targets       Build all targets
```
Also remove outdated explicit warn flags that are not needed …
> Lint all targets in CI

- CHANGELOG.md
- talpid-routing/src/unix/macos/data.rs
- talpid-routing/src/unix/macos/interface.rs
Previously, the default route failed to be restored when disconnecting: 
```
[2024-01-05 15:44:25.339][talpid_routing::imp::imp::interface][DEBUG] Found primary interface for V4
[2024-01-05 15:44:25.340][talpid_routing::imp::imp::interface][DEBUG] Found primary interface for V6
[2024-01-05 15:44:25.341][talpid_routing::imp::imp][TRACE] Failed to add unscoped default V6 route: Destination unreachable
```
Fixes DES-520.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5662)
> Fix default route not being restored when the gateway address is link-local IPv6

- docs/patch-examples/override-relay-ips.json
- docs/settings-patch-format.md
- mullvad-daemon/src/settings/patch.rs
- mullvad-management-interface/proto/management_interface.proto
This PR adds a spec for the patch format to `./docs/settings-patch-format.md`. It also adds an example of a working patch file to `./docs/patch-examples`, along with a unit test that fails if the patch is rejected.
Closes DES-545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5664)
> Document and test patch format

- .github/workflows/android-app.yml
This PR aims to start running e2e tests nightly. Apart from running on a schedule, it's also possible to trigger the e2e tests using a manual dispatch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5667)
> Run e2e tests nightly in GH actions

- test/Cargo.lock
- test/scripts/ssh-setup.sh
- test/test-manager/src/vm/provision.rs
Currently, this script silently fails. This is pretty frustrating, as you don't notice when packages cannot be installed, etc. The output is also logged now.
Close DES-551.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5669)
> Exit if `ssh-setup.sh` fails

- android/lib/endpoint/src/main/kotlin/net/mullvad/mullvadvpn/lib/endpoint/ApiEndpoint.kt
- android/lib/endpoint/src/main/kotlin/net/mullvad/mullvadvpn/lib/endpoint/CustomApiEndpointConfiguration.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiTest.kt
- mullvad-api/src/access.rs
- mullvad-api/src/address_cache.rs
- mullvad-api/src/lib.rs
- mullvad-api/src/rest.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-jni/src/lib.rs
- test/test-manager/src/tests/account.rs
This PR fixes an issue with the daemon not configuring the firewall correctly in case the `api-override` feature is enabled.  
More specifically, this PR moves the responsibility for using overridden API endpoints for API calls from `mullvad-api::rest` to `mullvad_daemon::api`. This is in line with how the interaction between the two crates work for a normal release build , i.e. when the `api-override` feature is disabled.
This commit also removes the `force_direct_connection`, since it was always true when the `api-override` feature was enabled. This change also affects the Android client code. Since the flag does not exist in the `mullvad-api` or `mullvad-jni` rust crates anymore, it would be erroneous to try to serialize/deserialize the value in the Android client.
The boy scout rule …
> Respect custom API endpoint when the `api-override` feature is enabled

- mullvad-cli/Cargo.toml
- mullvad-cli/src/cmds/patch.rs
Follow-up to #5668. I realized that things could be made even slightly simpler by using `io::read_to_string` instead of `Read::read_to_string`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5676)
> Minor CLI improvement

- test/README.md
- test/build.sh
- test/scripts/build-runner-image.sh
- test/scripts/ssh-setup.sh
- test/test-manager/src/tests/mod.rs
- test/test-manager/src/tests/software.rs
This PR adds a test that runs `podman run docker.io/curlimages/curl:latest https://am.i.mullvad.net/connected` (and `sudo docker` on Ubuntu and Debian) on Linux.
This makes sure that containers have working DNS and connectivity (at least using the default network setup).
Closes DES-59.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5651)
> Test container connectivity on Linux

- .github/workflows/frontend.yml
At the time of writing the Windows runner doesn't have an up-to-date installation of Rust which caused the frontend job to fail. This PR adds an update step to the beginning of that workflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5673)
> Make frontend workflow update Rust

- Cargo.lock
- mullvad-api/src/https_client_with_sni.rs
- mullvad-cli/Cargo.toml
- mullvad-cli/src/cmds/api_access.rs
- mullvad-cli/src/cmds/bridge.rs
- mullvad-cli/src/cmds/proxies.rs
- mullvad-daemon/src/migrations/v7.rs
- mullvad-management-interface/src/types/conversions/access_method.rs
- mullvad-management-interface/src/types/conversions/net.rs
- talpid-openvpn/src/lib.rs
- talpid-types/src/net/proxy.rs
Validate SOCKS credentials by checking that both `username` and `password` both have a length between 1 and 255 bytes.
Link to RFC detailing SOCKS5 username/password authentication: https://datatracker.ietf.org/doc/html/rfc1929
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5681)
> Validate SOCKS5 credentials when authentication is used

- test/clippy.toml
- test/test-manager/README.md
- test/test-manager/src/mullvad_daemon.rs
- test/test-manager/src/run_tests.rs
- test/test-manager/src/tests/account.rs
- test/test-manager/src/tests/dns.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/install.rs
- test/test-manager/src/tests/mod.rs
- test/test-manager/src/tests/settings.rs
- test/test-manager/src/tests/software.rs
- test/test-manager/src/tests/tunnel.rs
- test/test-manager/src/tests/tunnel_state.rs
- test/test-manager/src/tests/ui.rs
- test/test-manager/test_macro/src/lib.rs
Re-write some code in the test framework to prefer the type safe wrapper around the Mullvad app gRPC client instead of its auto-generated dito.
`ManagementServiceClient` is automatically generated from the protobuf definitions found in `management_interface.proto`, and contains some very crude types. The `MullvadProxyClient` is a type-safe wrapper around `ManagementServiceClient` which performs conversions & validation of the data types from the gRPC server (the daemon) to their respective mappings in the `talpid-*` and `mullvad-*` crates. These types are more ergonomic to work with, and since we already have the conversions in place we should prefer those.
This PR also adds a `clippy.toml` to the test framework workspace. The only configuration for now is the lint `disallowed-types` …
> Use type safe protobuf client in test framework

- CHANGELOG.md
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-routing/src/lib.rs
- talpid-routing/src/unix/macos/mod.rs
- talpid-routing/src/unix/macos/watch.rs
Previously, the app would get stuck in the error state when a default route was removed while connecting. Specifically, this occurred if the default was missing while adding tunnel routes, but before the offline monitor had had time to catch it. That caused adding routes to fail due to `ENETUNREACH`.
This PR fixes it by simply retrying/reconnecting when adding routes fails due to an unreachable destination.
Closes DES-496.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5687)
> Fix app getting stuck in error state on macOS

- ios/Configurations/UITests.xcconfig.template
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNUITests.xcscheme
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/Containers/Root/HeaderBarView.swift
- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
- ios/MullvadVPN/View controllers/Login/AccountInputGroupView.swift
- ios/MullvadVPN/View controllers/Login/LoginContentView.swift
- ios/MullvadVPN/View controllers/TermsOfService/TermsOfServiceContentView.swift
- ios/MullvadVPNUITests/AccountTests.swift
- ios/MullvadVPNUITests/BaseUITestCase.swift
- ios/MullvadVPNUITests/Info.plist
- ios/MullvadVPNUITests/Pages/Alert.swift
- ios/MullvadVPNUITests/Pages/LoginPage.swift
- ios/MullvadVPNUITests/Pages/Page.swift
- ios/MullvadVPNUITests/Pages/TermsOfServicePage.swift
- ios/TestPlans/MullvadVPNUITests.xctestplan
The first basic login tests. Will implement more login-related tests later on to cover more of the login flow(more tests documented in https://linear.app/mullvad/document/tests-09cbefd4a4a6). Using Page Object Pattern(AKA Page Object Model) where code looking for elements, tapping them etc is abstracted away into page classes. So the test cases are very high level and easy to read, making it easy to verify that the tests are testing what they should and it's easier to maintain and create new tests reusing existing page classes.
A new `.xcconfig` file template has been added under `Configurations` so you need to copy the template for example by `cd Configurations ; cp UITests.xcconfig.template UITests.xcconfig` or Xcode might complain. To run the tests the variables on the configuration …
> Add login UI tests

- gui/package-lock.json
- gui/package.json
This PR updates `react-router` to `5.3.4` to fix some dependency issues causing warning when running `npm install`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5696)
> Update React router to 5.3.4

- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/install.rs
- test/test-manager/src/tests/mod.rs
The test currently fails when the daemon is not logged in. This always happens since `test_login` runs after this test.
This PR fixes it by failing whenever the daemon starts in the `disconnected` state instead.
Close DES-565.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5699)
> Fix test_installation_idempotency

- CHANGELOG.md
- mullvad-types/src/custom_tunnel.rs
- mullvad-types/src/wireguard.rs
- test/test-manager/src/tests/tunnel_state.rs
When the setting is set to `auto`.
Close DES-556.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5692)
> Enable quantum-resistant tunnels by default on Linux

- Cargo.lock
- test/Cargo.lock
The CI warned about a vulnerable dependency: https://github.com/mullvad/mullvadvpn-app/actions/runs/7566202666
This PR does the minimal to fix that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5703)
> Upgrade h2 to fix RUSTSEC-2024-0003

- CHANGELOG.md
- mullvad-cli/src/cmds/status.rs
- mullvad-cli/src/format.rs
- mullvad-daemon/src/device/mod.rs
- mullvad-daemon/src/lib.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/types/conversions/states.rs
- mullvad-types/src/states.rs
- talpid-core/src/tunnel_state_machine/disconnected_state.rs
- talpid-types/src/tunnel.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/settings.rs
- test/test-manager/src/tests/tunnel_state.rs
Fixes DES-535
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5656)
> Make `mullvad status` print if lockdown mode is enabled while disconnected

- android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/CreateAccountMockApiTest.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LoginMockApiTest.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LogoutMockApiTest.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiDispatcher.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/TooManyDevicesMockApiTest.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/constant/Constants.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/util/JsonUtils.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5689)
> Add mockapi test for handling too many devices

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/FilterConstrainExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SelectLocationUiState.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/RelayListListener.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/RelayListUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt
This PR tries to make situations where a user would see an empty relay list rarer by trying to mitigate some potential sources for this error in the app layer.
The two changes are:
1. Change from `SharingStarted.Eagerly` to `SharingStarted.WhileSubscribed()`. This, according to my tests, delays the call to fetch the relay list by around 400 ms. This in my opinion could make things less likely to break since the call is made later and thus the call (or the answer) is less likely be lost.
2. Make a call to get the relay list again when entering the `SelectLocationScreen`. This would mean that if the user still encounters this error it _can_ be resolved when they opening the actual screen. It still would cause them to see an empty list for a second.
- - - …
> Try to mitigate missing relay list errors

- mullvad-cli/src/cmds/api_access.rs
- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/lib.rs
This PR moves the logic for toggling a disabled access method to be enabled if it is actively used from the clients (only the CLI at the moment) to the daemon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5693)
> Move logic of toggling disabled access methods on use to the daemon

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- mullvad-cli/Cargo.toml
- mullvad-cli/src/main.rs
Fix shell completions for subcommands.
`clap_complete` incorrectly used package name instead of binary name for bash, causing completions to break for subcommands. I fixed this in an upstream PR, see https://github.com/clap-rs/clap/pull/5256 and https://github.com/clap-rs/clap/issues/5255. The PR is now merged and included in `clap_complete` version `4.4.8`.
Test this by building and installing the app on linux or mac, then verify completions for subcommands in a bash terminal.
Fixes DES-506
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5710)
> Fix bash completions in subcommands

- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/client.rs
- mullvad-management-interface/src/types/conversions/access_method.rs
Add a new RPC call `TestAccessMethod` for testing access methods on the fly, without having to save them to the daemon settings first. This only works for custom access method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5705)
> Allow testing access methods before saving them

- mullvad-api/src/rest.rs
`HeaderValue` in hyper support a multitude of `From` traits, which are infallible for primitives such as `usize` but fallible for strings. This minor refactoring PR removes the need for going via string when setting the `Content-Length` header.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5715)
> Use infallible HeaderValue::from() when converting from usize

- ios/MullvadREST/Transport/AccessMethodIterator.swift
- ios/MullvadREST/Transport/Shadowsocks/ShadowsocksConfiguration.swift
- ios/MullvadREST/Transport/Socks5/Socks5Configuration.swift
- ios/MullvadREST/Transport/TransportProvider.swift
- ios/MullvadREST/Transport/TransportStrategy.swift
- ios/MullvadRESTTests/AccessMethodRepositoryStub.swift
- ios/MullvadRESTTests/TransportStrategyTests.swift
- ios/MullvadSettings/AccessMethodRepositoryProtocol.swift
This pull request optimizes performance by enabling the reuse of the current connection, eliminating the necessity for a new connection with each incoming request. However, exceptions are made in cases such as request failures or modifications to the active configuration by other processes (e.g., Packet tunnel, UI part).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5704)
> reusing existing connection for requests

- ios/MullvadREST/Transport/TransportStrategy.swift
- ios/MullvadRESTTests/TransportStrategyTests.swift
- ios/MullvadSettings/PersistentAccessMethod.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel+Persistent.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/PersistentProxyConfiguration+ViewModel.swift
We don't necessarily need a switch-case for SOCKS authentication that involves retrieving credentials in the `TransportStrategy` when we can achieve the same outcome using an optional value for the authentication part. This pull request transforms the `SocksAuthentication` enum into a struct and makes it an optional variable in `SocksConfiguration`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5708)
> Remove socks5 authentication check from the TransportStrategy layer

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift
- ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift
- ios/MullvadVPN/View controllers/Settings/SettingsCellFactory.swift
- ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift
- ios/MullvadVPN/View controllers/Settings/SettingsViewController.swift
Currently, there is no bespoke iOS design for this, but that will not stop us. We should follow the desktop UI mockups for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5688)
> Add preliminary settings page for relay IP overrides

- ios/Configurations/UITests.xcconfig.template
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/Preferences/CustomDNSDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/SelectLocationViewController.swift
- ios/MullvadVPN/View controllers/Settings/SettingsViewController.swift
- ios/MullvadVPN/View controllers/Tunnel/ConnectionPanelView.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPN/Views/CustomSwitch.swift
- ios/MullvadVPNUITests/BaseUITestCase.swift
- ios/MullvadVPNUITests/Info.plist
- ios/MullvadVPNUITests/Pages/Alert.swift
- ios/MullvadVPNUITests/Pages/LoginPage.swift
- ios/MullvadVPNUITests/Pages/Page.swift
- ios/MullvadVPNUITests/Pages/SelectLocationPage.swift
- ios/MullvadVPNUITests/Pages/SettingsPage.swift
- ios/MullvadVPNUITests/Pages/TermsOfServicePage.swift
- ios/MullvadVPNUITests/Pages/TunnelControlPage.swift
- ios/MullvadVPNUITests/RelayTests.swift
- ios/MullvadVPNUITests/XCUIElementQuery+Extensions.swift
Implemented test covering the ad blocking functionality. This PR introduces the attributes `MULLVAD_IOS_DEVICE_PIN_CODE` and `MULLVAD_AD_SERVING_DOMAIN` which need to be added to your `Configurations/UITests.xcconfig` file.
The test assumes a blank state, so the app should be uninstalled before running the test. It can be tried out by running the test `testAdBlockingViaDNS`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5701)
> Add ad blocking test for iOS

- ios/MullvadREST/ApiHandlers/APIAvailabilityTestRequest.swift
- ios/MullvadREST/ApiHandlers/HTTP.swift
- ios/MullvadREST/Transport/ProxyConfigurationTransportProvider.swift
- ios/MullvadREST/Transport/RESTTransportProvider.swift
- ios/MullvadRESTTests/HeadRequestTests.swift
- ios/MullvadRESTTests/Mocks/RESTTransportStub.swift
- ios/MullvadRESTTests/RequestExecutorTests.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift
- ios/MullvadVPN/SceneDelegate.swift
This PR implements the "Test" button for testing our API via a custom configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5713)
> Enable testing API access with a given configuration

- Cargo.toml
- build.sh
I found this neat little blog post: https://kobzol.github.io/rust/cargo/2024/01/23/making-rust-binaries-smaller-by-default.html
On nightly Rust cargo will now by default strip debuginfo (coming to stable later). However symbols are still there. We have a more complex solution where we manually invoke `strip` on the produced binaries to yield the same result as we can get by setting `strip = true` in `Cargo.toml`.
This project fixes that, and simplifies build.sh. We also get stripping for anyone manually invoking `cargo build --release`. I see no downsides.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5723)
> Strip binaries with cargo instead of build.sh

- CHANGELOG.md
- talpid-tunnel-config-client/src/lib.rs
- talpid-wireguard/src/lib.rs
This works around PQ connectivity issues caused by the actual MTU being lower than the tunnel MTU.
Close DES-573.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5707)
> Hardcode a low MTU/MSS for the tunnel config client socket

- CHANGELOG.md
- talpid-routing/src/lib.rs
- talpid-routing/src/unix/macos/data.rs
- talpid-routing/src/unix/macos/mod.rs
- talpid-wireguard/src/lib.rs
Follow-up to #5501. This PR makes the same change but for macOS.
Fix DES-465.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5721)
> Prevent fragmentation in tunnel when using multihop on macOS

- .github/workflows/cargo-audit.yml
As part of the effort to run better CI on the testingframework I here add Cargo audit checking.
Replacing `inventory` was a non-trivial task, so I ignore that RUSTSEC for now. Better to have some audit checking in place and ignoring a few issues than having no audit checking at all.
At the time of posting this PR it will fail on `RUSTSEC-2020-0168` against `mach` dependency being unmaintained. But a separate PR tries to upgrade that. This PR will be rebased and tested against `main` once that is done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5725)
> Run cargo audit in test framework also

- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/AccountHistoryMockApiTest.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LoginMockApiTest.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LogoutMockApiTest.kt
- android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/TooManyDevicesMockApiTest.kt
Tests that the last account number is shown after logging out of an account. Also checks that clicking on that number will log the user into the account again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5711)
> Add mock api test for testing the account history feature

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AccessMethodRepository/LocalNetworkProbe.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Add/AddAccessMethodCoordinator.swift
- ios/MullvadVPN/Supporting Files/Info.plist
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5729)
> Add a local network probe to trigger local network privacy dialog

- gui/src/renderer/components/EditApiAccessMethod.tsx
This PR fixes two bugs in the API access method view.
1. The titles were swapped between add and edit pages
2. New names weren't picked up when editing a method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5738)
> Fix API access methods bugs in GUI

- CHANGELOG.md
- gui/locales/messages.pot
- gui/src/shared/notifications/error.ts
This PR adds information around the VMWare incompatibility and instructions on how to solve it.
Thread about the issue in the VMware forums: https://communities.vmware.com/t5/VMware-Workstation-Player/Unable-to-uninstall-VMware-Bridge-Protocol/td-p/2683023
This is how the info is presented:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5743)
> Add VMWare error message and troubleshooting instructions

- ios/CHANGELOG.md
- ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodInteractor.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodInteractorProtocol.swift
- ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift
API access methods are currently only enabled for debug builds. We need to remove this limitation to publicly release the feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5739)
> Enable API access methods for release builds

- .github/workflows/cargo-audit.yml
- test/Cargo.lock
- test/Cargo.toml
- test/test-manager/src/run_tests.rs
- test/test-runner/src/main.rs
This PR does not look like much, but it has a bunch of nice outcomes:
* Gets rid of a git dependency. Git dependencies are not good, since the availability of a specific git repo or commit is harder to maintain than crates.io dependencies. Especially since we have not (yet) pushed any tag to the pinned commit even :see_no_evil: (we really should do that in order to be able to build older versions of the testframework)
* Fixes `RUSTSEC-2020-0168` by getting rid of the transitive dependency `mach` that is unmaintained.
* Getting rid of some *really* outdated and unmaintained macOS bindings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5726)
> Don't pin serialport to a fork. Use upgraded upstream version 4.3.0

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift
- ios/MullvadVPN/en.lproj/Localizable.strings
We have an old and unused file for localisations that go against our current way or translating strings. We should remove it to uphold consistency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5747)
> Remove old and unused Localizible file

- ci/buildserver-config.sh
- ci/buildserver-upload.sh
- ci/publish-linux-repositories.sh
The file hosting is now anycasted and available on `cdn.mullvad.net`. So I'm changing the config to match this.
I'm also finally updating `buildserver-upload.sh` to use the same variable and not its own hardcoded upload ssh profile. It's currently hardcoded to production. But nowhere are we uploading these things to dev/staging, so it does not matter.
The variable name `PRODUCTION_LINUX_REPOSITORY_SERVERS` is now not optimal, since it's used for more than just Linux repository uploads. We can fix it if you think we should. Ideas for a better name? If we go down that route I suggest
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5749)
> Upload to cdn servers

- ios/MullvadVPNUITests/Pages/Page.swift
- ios/MullvadVPNUITests/RelayTests.swift
In the ad blocking test there's a race condition when enabling ad blocking and then verifying that an ad blocking domain cannot be reached. The problem is that changing the setting triggers a reconnect and there is no visual update in the app to wait for in order to make sure we're connected again before verifying that the ad blocking domain no longer can be reached. 
We decided to modify the test flow to:
1. Log into an account
2. Enable the ad blocking relay
3. Connect
4. Verify if the ad-serving domain is not reachable
See issue in Linear https://linear.app/mullvad/issue/IOS-466/race-condition-in-ad-blocking-test
The changes in this PR can be tested by running the `testAdBlockingViaDNS` test.
- - - …
> Modified ad blocking test flow

- .github/workflows/ios.yml
- ios/build-rust-library.sh
When quoting the RELFlAG variable, an empty argument will get passed and confuse the buildscript.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5755)
> Stop quoting RELFLAG in buildscript

- build-apk.sh
The `build-apk.sh` script broke in b6e0545e1b5ae2fbcb6655bd4d28739cf9f943d6 due to quoting a variable containing a string with space seperated arguments. While it is best practice to quote variables to prevent word splitting, word splitting was the behavior that we wanted in this particular case.
This commit fixes this issue by building an array of arguments instead, which when expanded will pass along the arguments to `cargo build` properly as multiple strings. The script now works, and `shellcheck` is happy!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5756)
> Properly pass arguments to Cargo in `build-apk.sh`

- mullvad-daemon/src/migrations/mod.rs
- mullvad-types/src/settings/mod.rs
`settings.json` always uses `7` as the version number. This caused the migration code for V7 -> V8 to always run.
Fix DES-615, DES-616.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5760)
> Fix settings version

- android/app/build.gradle.kts
This PR fixes a gradle task dependency that would cause some lint tasks to fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5768)
> Fix gradle asset task dependency

- CHANGELOG.md
I went through the git history since 2023.6 and updated the changelog with some missing changes, and also improved a few messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5746)
> Improve changelog and add some missing changes

- ios/MullvadVPN/Coordinators/AccountCoordinator.swift
- ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/View controllers/Account/AccountInteractor.swift
- ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionInteractor.swift
- ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionViewController.swift
- ios/MullvadVPN/View controllers/Login/LoginInteractor.swift
- ios/MullvadVPN/View controllers/Login/LoginViewController.swift
- ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherInteractor.swift
- ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift
This PR replaces public methods in TunnelManager, and their downstream consumers, which have used callbacks with versions using async instead, in the interest of modernising the codebase to use modern Swift concurrency.
The affected code deals with logging in, creating new accounts, deleting accounts, logging out and being bumped out due to device deletion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5748)
> Refactor TunnelManager account setting methods replacing callbacks with async

- .github/workflows/daemon.yml
Temporarily disable nightly builds due to an issue with curve25519-dalek. This should be reverted once it has been fixed: https://github.com/dalek-cryptography/curve25519-dalek/pull/619
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5772)
> Temporarily disable Rust nightly builds for the daemon

- mullvad-management-interface/build.rs
- talpid-core/build.rs
- talpid-openvpn-plugin/build.rs
- talpid-openvpn/build.rs
- talpid-tunnel-config-client/build.rs
It seems that `tonic_build::compile_protos()` already injects "cargo:rerun-if-changed" statements for cargo: https://github.com/hyperium/tonic/blob/v0.10.0/tonic-build/src/prost.rs#L40
If you run `cargo build -vv` you'll see the following statements already added by `tonic_build`:
```
[mullvad-management-interface 0.0.0] cargo:rerun-if-changed=proto/management_interface.proto
[mullvad-management-interface 0.0.0] cargo:rerun-if-changed=proto
```
Hence no need to do that manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5750)
> Remove manual cargo:rerun-if-changed when building protos

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/View controllers/RedeemVoucher/RedeemVoucherViewController.swift
- ios/PacketTunnelCore/TunnelMonitor/PingStats.swift
- ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift
- ios/PacketTunnelCore/TunnelMonitor/TunnelMonitorState.swift
This PR just moves structures definition out of `TunnelMonitor` into their own file `TunnelMonitorState` and renames it accordingly. 
It also fixes a warning in `RedeemVoucherViewController.swift`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5770)
> Get rid of swiftlint warnings and move files around

- test/test-manager/src/run_tests.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/mod.rs
We can use `Settings::default()` directly now since we have `MullvadProxyClient`. This means that we also no longer default to using `any` for the relay location.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5773)
> Simplify how settings are reset in tests

- ios/MullvadSettings/IPOverride.swift
- ios/MullvadSettings/IPOverrideRepository.swift
- ios/MullvadSettings/SettingsStore.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatusView.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideTextViewController.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewControllerDelegate.swift
- ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift
- ios/MullvadVPN/Extensions/URL+Scoping.swift
- ios/MullvadVPN/UI appearance/UIMetrics.swift
- ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionContentView.swift
- ios/MullvadVPNTests/IPOverrideRepositoryTests.swift
- ios/MullvadVPNTests/IPOverrideTests.swift
Allow users to paste a JSON override into the app, which should then be saved. If the JSON blob contains extraneous keys, it should be rejected and the user should be notified with an error. When any override is active, the UI should indicate that overrides are in use, not necessarily show which overrides those might be. The user should be able to clear all overrides via the appropriate button.
Includes `allow-users-to-import-json-files-ios-453`as well:
Allow users to import JSON files. It should work the same way as pasting JSON files, but use a file picker instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5722)
> Allow users to import settings by pasting json blobs

- ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift
- ios/MullvadREST/Relay/AnyRelay.swift
- ios/MullvadREST/Relay/IPOverrideWrapper.swift
- ios/MullvadREST/Relay/RelayCache.swift
- ios/MullvadREST/Relay/RelaySelector.swift
- ios/MullvadSettings/IPOverride.swift
- ios/MullvadSettings/IPOverrideRepository.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideTextViewController.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift
- ios/MullvadVPN/Coordinators/Settings/SettingsCoordinator.swift
- ios/MullvadVPN/Extensions/URL+Scoping.swift
- ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift
- ios/MullvadVPN/SceneDelegate.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/View controllers/Settings/SettingsInteractorFactory.swift
- ios/MullvadVPNTests/IPOverrideRepositoryStub.swift
- ios/MullvadVPNTests/IPOverrideRepositoryTests.swift
- ios/MullvadVPNTests/IPOverrideWrapperTests.swift
- ios/MullvadVPNTests/RelayCacheTests.swift
- ios/MullvadVPNTests/RelayCacheTracker+Stubs.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnel/PacketTunnelProvider/RelaySelectorWrapper.swift
The relay selector should use the overridden IP address for relays which have overrides. The correct IP address should be shown in the connection details in the UI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5724)
> Relay selector should use overridden ip addresses for relays

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceListScreen.kt
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/dimensions/Dimensions.kt
- Display loading state with a spinner
- Fix alignment of success icon when the device list is empty
- Fix remove icon size
- Remove alpha from remove icon
- Add more preview cases
- Fix dates not showing in preview
Compared to previous version:
New loading state:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5754)
> Improve DeviceListScreen

- ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift
Let's always stop the tunnel before applying a new config to it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5783)
> Always destroy tunnel when reconfiguring

- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportReviewViewController.swift
The report view controller's background color was not appearing correctly on certain platforms. 
This PR fixes that
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5781)
> Fix background color in report view controller

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/TunnelManager/Tunnel.swift
- ios/MullvadVPNTests/Mocks/MockTunnel.swift
- ios/MullvadVPNTests/Mocks/MockTunnelInteractor.swift
- ios/MullvadVPNTests/StartTunnelOperationTests.swift
- ios/Shared/ApplicationTarget.swift
This is the first step in an ongoing process of adding unit tests for logic. This creates a unit test class for StartTunnelOperation and a (currently incomplete) mock of TunnelInteractor for use in it. The two tests currently implemented check that establishing tunnels fails if not logged in, and that in the disconnecting state, the next operation is set to reconnect. Additional logic will need to be tested, though this will involve teasing out intertwined logic and isolating it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5758)
> Added the beginning of unit tests fro StartTunnelOperation

- .github/workflows/ios-validate-build-schemas.yml
This is another test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5766)
> Exercise custom schemas in ci ios 448

- test/Cargo.lock
- test/Cargo.toml
- test/socks-server/Cargo.toml
- test/socks-server/src/lib.rs
- test/test-manager/Cargo.toml
- test/test-manager/src/main.rs
- test/test-manager/src/vm/network/mod.rs
- test/test-rpc/src/client.rs
- test/test-rpc/src/lib.rs
- test/test-rpc/src/net.rs
- test/test-runner/src/forward.rs
- test/test-runner/src/main.rs
This lets us test API access methods and custom bridges more conveniently.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5771)
> Add SOCKS5 server to test-manager

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
We have a crash on Google Play that throws android.app.BackgroundServiceStartNotAllowedException.
Now this exception is thrown when a background service is started by an app in the background.
Since we are attempting to start our service in `onStart` the app should be in the foreground when the service is starting so it is a bit unclear under which conditions this exception is thrown. Even more so since there's a grace period of about 30 seconds after the app is moved to the background that the app is still allowed to start a background service.
I have thought about two possible scenarios:
1. The app is started up and for some reason the app is for some reason not yet considered to be in the foreground when start service is called. This is mitigated by only running the coroutine when the …
> Bind to the service in a coroutine to avoid a crash

- test/docs/BUILD_OS_IMAGE.md
Add instructions to ensure that the Windows time service is enabled in the test runners. This should prevent the test runner clock from getting out of sync.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5769)
> Add instructions to enable Windows time service in Windows test runners

- test/test-manager/src/tests/tunnel.rs
Closes DES-609.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5779)
> Add tests for custom SOCKS bridges

- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/src/future_retry.rs
- talpid-core/src/tunnel/mod.rs
- talpid-tunnel/src/lib.rs
- talpid-wireguard/Cargo.toml
- talpid-wireguard/src/config.rs
- talpid-wireguard/src/connectivity_check.rs
- talpid-wireguard/src/lib.rs
- talpid-wireguard/src/ping_monitor/icmp.rs
- talpid-wireguard/src/unix.rs
- talpid-wireguard/src/wireguard_kernel/netlink_tunnel.rs
Fixes DES-581.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5736)
> Automatic MTU detection linux

- Cargo.lock
- mullvad-nsis/Cargo.toml
- mullvad-nsis/include/mullvad-nsis.h
- mullvad-nsis/src/lib.rs
- windows/nsis-plugins/src/log/log.cpp
Get Windows version using `talpid-platform-metadata`, which is the way that `mullvad-problem-report` reports the correct build number.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5787)
> Fix `install.log` reporting wrong Windows version

- talpid-tunnel/src/tun_provider/unix.rs
An unused function suddenly caused CI to fail when bumping the version of the nightly Rust compiler https://github.com/mullvad/mullvadvpn-app/pull/5785. This PR simply removes the offending function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5791)
> Fix CI by removing unused function

- mullvad-daemon/src/api.rs
- mullvad-types/src/access_method.rs
- talpid-core/src/offline/android.rs
- talpid-core/src/offline/linux.rs
- talpid-core/src/offline/macos.rs
- talpid-core/src/offline/mod.rs
- talpid-core/src/offline/windows.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/disconnected_state.rs
- talpid-core/src/tunnel_state_machine/disconnecting_state.rs
- talpid-core/src/tunnel_state_machine/error_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- talpid-routing/src/lib.rs
- talpid-types/src/net/mod.rs
Try to detect available IP versions by looking at the available routes on the host.
* On Linux, we check if there exists IPv4 and/or IPv6 routes to some public IP addresses. 
* On macOS and Windows, we check if there exists default routes for IPv4 and/or IPv6.
The intention is to be able to generate better default constraints for tunnel endpoints. If we can detect "working" IPv4 and/or IPv6 and forward this information to a `TunnelParametersGenerator`, we may choose to connect to a Wireguard relay using IPv6 as part of our retry-strategy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5761)
> Detect available IP versions

- .github/workflows/cargo-audit.yml
Temporarily ignore `RUSTSEC-2023-0079` in `cargo-audit` CI job. This should be reversed ASAP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5794)
> Ignore RUSTSEC-2023-0079

- gui/src/renderer/app.tsx
- gui/test/e2e/installed/state-dependent/login.spec.ts
- gui/test/e2e/mocked/expired-account-error-view.spec.ts
From what I could find the app doesn't redirect to the out of time view when the account expires. It
redirected first when the app received focus or navigating to the account view or main view. I've
also added a test that verifies this.
I've also improved the logging for debugging account expiry issues in the test framework.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5751)
> Add out of time redirect

- gui/src/renderer/components/Map.tsx
The e2e tests are run headless and we're seeing some errors in the test logs. Since the map isn't useful for that view I'm disabling it in this PR. It is now conditionally rendered when not running tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5777)
> Disable map in e2e tests

- ios/MullvadSettings/QuantumResistanceSettings.swift
- ios/MullvadSettings/TunnelSettings.swift
- ios/MullvadSettings/TunnelSettingsV4.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
This PR cherry-picks the TunnelSettings version bump (`TunnelSettingsV4`) from the quantum resistance branch, adding a quantum resistance setting with three states (`automatic`, `off`and `on`) and making V4 the new version of settings. The purpose of this backport is to unblock any other possible changes to settings and avert merging issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5795)
> Backport TunnelSettingsV4 from quantum resistance exploratory branch

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController+ViewManagement.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewModel.swift
- ios/MullvadVPNTests/StartTunnelOperationTests.swift
This PR fixes the `swiftlint` warning in `ProblemReportViewController` 
No functionality is changed, just code is being reorganized
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5796)
> Reorder ProblemReportViewController and get rid of swiftlint warnings

- ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift
- ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/Protocols/TunnelAdapterProtocol.swift
This PR resurfaces the list of allowed IP address ranges passed to wireguard.
We need to do this in order to change the range when configuring wireguard for doing post quantum key exchange.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5804)
> Resurface the list of allowedIPs to make it configurable

- talpid-windows/src/net.rs
- talpid-wireguard/src/mtu_detection.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5805)
> Fix MTU detection below 1280 with IPv6 on windows

- gui/src/renderer/components/ApiAccessMethods.tsx
- gui/src/renderer/components/ContextMenu.tsx
- gui/src/renderer/components/EditApiAccessMethod.tsx
- gui/src/renderer/components/cell/SettingsSelect.tsx
- gui/test/e2e/installed/state-dependent/api-access-methods.spec.ts
This PR adds tests for the API access methods feature. It tests the following:
* Listing methods
* Adding a functioning method
* Adding a non functioning method
* Using a functioning method
* Trying to use a non functioning method
* Deleting methods
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5775)
> Add GUI test for API access methods

- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesCellFactory.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesDataSource.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesInfoButtonItem.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesInteractor.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesViewController.swift
- ios/MullvadVPN/View controllers/Preferences/PreferencesViewModel.swift
This adds a "Quantum resistance" menu to the VPN options with three modes: On, Off and Automatic. It is disabled if DEBUG is not set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5806)
> Add quantum resistance settings to preferences view if DEBUG is set

- ios/Configurations/UITests.xcconfig.template
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNUITests.xcscheme
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPNUITests/ConnectivityTests.swift
- ios/MullvadVPNUITests/Info.plist
- ios/MullvadVPNUITests/Networking/FirewallAPIClient.swift
- ios/MullvadVPNUITests/Networking/FirewallRule.swift
- ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift
- ios/MullvadVPNUITests/Networking/Networking.swift
- ios/MullvadVPNUITests/Pages/LoginPage.swift
- ios/MullvadVPNUITests/Pages/Page.swift
- ios/MullvadVPNUITests/Pages/ProblemReportPage.swift
- ios/MullvadVPNUITests/Pages/SettingsPage.swift
- ios/MullvadVPNUITests/Pages/TunnelControlPage.swift
- ios/MullvadVPNUITests/RelayTests.swift
- ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift
This PR introduces the test `testAPIConnectionViaBridges` which blocks API access and makes sure the app can still successfully function. It also contains some more or less related improvements:
* The connectivity check for ad blocking test now checks whether host is connectable on port 80 instead of attempting to send HTTP requests
* Waiting for successful connection to relay in `testAdBlockingViaDNS` - sometimes the connectivity check happened before connected to relay
* Dropped `MULLVAD_` and `Mullvad` prefix before configuration and plist entries.
To test running `testAPIConnectionViaBridges` introduced in this PR you have to be connected to the `app-team-ios-tests` wifi at the office. It's a wifi running on the NUC where the firewall API is also running. The tests use the wifi and …
> Add iOS test for connecting to API via bridges

- Cargo.lock
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPNUITests/BridgingHeader.h
- ios/MullvadVPNUITests/MullvadApi.swift
- mullvad-api/Cargo.toml
- mullvad-api/build.rs
- mullvad-api/include/mullvad-api.h
- mullvad-api/src/address_cache.rs
- mullvad-api/src/ffi/device.rs
- mullvad-api/src/ffi/error.rs
- mullvad-api/src/ffi/mod.rs
- mullvad-api/src/lib.rs
- mullvad-api/src/rest.rs
- mullvad-daemon/src/device/service.rs
- talpid-time/src/unix.rs
This is a small change to `mullvad-api` to expose an FFI that can be consumed by Rust. As such, I expect the reviewers to review their respective half of the changes - @dlon  and @MarkusPettersson98 can review the Rust changes, and @buggmagnet and @niklasberglund should be reviewing the Swift changes.
I expect that this will not be ideal Swift code and it'll be somewhat clunky FFI code for Rust, do not be gentle.  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5780)
> Expose mullvad-api to iOS UI tests

- mullvad-api/src/bin/relay_list.rs
- mullvad-api/src/lib.rs
- mullvad-api/src/rest.rs
- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-problem-report/src/lib.rs
- mullvad-setup/src/main.rs
- mullvad-types/src/access_method.rs
- test/test-manager/src/tests/account.rs
- test/test-manager/src/tests/install.rs
As the code comment says: `get_next_inner` will skip the `start` position, which means that by starting from the back of the available access methods we effectively look for candidates starting from index 0, i.e. the position of the `direct` access method. It's probably a good idea to not default users to bridges/proxies to reach the API.
Edit: The solution was found elsewhere. As it turns out, `mullvad-api` always forced a rotation of access methods whenever `MullvadRestHandle` was initialized, which means that `get_next_inner`/`select_next_active` was called twice at startup. This was subsequently solved by passing along an initial access method to the constructor of `MullvadRestHandle`, as is done with the tunnel state machine.
- - - …
> Fix off-by-one error when choosing access method candidates

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPNUITests/MullvadApi.swift
- mullvad-api/src/ffi/mod.rs
This PR fixes the mullvad-api ffi mod for building on iOS, and makes sure to consume the generated header file after building it.
It also removes some unused code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5816)
> Fix the mullvad API ffi, consume the header after building it

- CHANGELOG.md
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SplitTunnelingUiState.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/serviceconnection/SplitTunneling.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelState.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SplitTunnelingViewModelTest.kt
- android/lib/resource/src/main/res/values/strings.xml
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/endpoint/SplitTunneling.kt
- gui/locales/messages.pot
Preview:
To align with desktop.
This is continued from: https://github.com/mullvad/mullvadvpn-app/pull/5554
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5641)
> Add enable/disable button to Split Tunnelling

- test/test-manager/src/tests/ui.rs
As the title suggests, this PR enables `settings-import.spec.ts` to be run in the test framework.
Link to a complete E2E test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/7918451759
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5819)
> Run settings import UI tests in test framework

- ios/MullvadSettings/CustomList.swift
- ios/MullvadSettings/CustomListRepository.swift
- ios/MullvadSettings/CustomListRepositoryProtocol.swift
- ios/MullvadSettings/SettingsStore.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPNTests/CustomListRepositoryTests.swift
Storing custom lists in settings enhances the app's ability to access user preferences for relay connections.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5782)
> storing custom list into settings

- mullvad-api/src/bin/relay_list.rs
- mullvad-api/src/lib.rs
- mullvad-api/src/proxy.rs
- mullvad-api/src/rest.rs
- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-problem-report/src/lib.rs
- mullvad-setup/src/main.rs
- mullvad-types/src/access_method.rs
- test/test-manager/src/tests/account.rs
Fix DES-635.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5822)
> Refactor API access mode rotation

- mullvad-api/src/rest.rs
The new method shouldn't be rotated until it has been used. This was particularly annoying with the default settings when an even number of requests failed, as the current (broken) method would keep being used.
Fix DES-636.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5823)
> Fix pointless API method rotations when concurrent requests fail

- CHANGELOG.md
- mullvad-api/src/address_cache.rs
- mullvad-api/src/lib.rs
- mullvad-api/src/rest.rs
- mullvad-daemon/src/api_address_updater.rs
- mullvad-daemon/src/lib.rs
Previously, the API IP updater spawned as a side effect when creating a Mullvad REST client/handle. This forced users of the API client to be aware of this (usually unwanted) behavior.
The PR moves this logic to `mullvad-daemon` and forces the daemon explicitly instantiate the updater.
Fixes DES-637.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5825)
> Move API IP updater out of mullvad-api

- mullvad-daemon/src/api_address_updater.rs
This PR fixes build error due to referring to a value which was not imported/qualified.
This regression was introduced in df37a0da43149c63e60ae604d4d7fefba2de9b5c.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5829)
> Fix build error due to missing import

- mullvad-api/src/bin/relay_list.rs
- mullvad-daemon/src/exception_logging/unix.rs
- mullvad-daemon/src/geoip.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/settings/mod.rs
- mullvad-relay-selector/src/lib.rs
- mullvad-setup/src/main.rs
- mullvad-types/src/version.rs
- mullvad-types/src/wireguard.rs
- talpid-core/src/firewall/linux.rs
- talpid-core/src/offline/linux.rs
- talpid-core/src/split_tunnel/windows/mod.rs
- talpid-core/src/tunnel/mod.rs
- talpid-dbus/src/systemd_resolved.rs
- talpid-openvpn-plugin/src/processing.rs
- talpid-openvpn/src/lib.rs
- talpid-openvpn/src/process/openvpn.rs
- talpid-routing/src/windows/route_manager.rs
- talpid-wireguard/src/connectivity_check.rs
- talpid-wireguard/src/wireguard_kernel/wg_message.rs
- test/test-manager/src/tests/account.rs
Remove redundant imports found when compiling with nightly `rustc`.
Fix DES-639.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5828)
> Remove redundant imports

- mullvad-daemon/src/custom_list.rs
The relay selector will be notified about settings changes already, so there is no need to apply the changes twice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5832)
> Remove redundant relay selector updates

- .github/workflows/clippy.yml
- .github/workflows/testframework-clippy.yml
Run `clippy` with `all-features`, (and `--tests` & `benches` where applicable) in CI to get more coverage and catch more mistakes earlier. This is in addition to the old behavior to cover all possible combinations of feature flags.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5831)
> Run `clippy` with `all-features` in CI

- Cargo.lock
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/relay_list/mod.rs
- mullvad-daemon/src/relay_list/updater.rs
- mullvad-relay-selector/Cargo.toml
- mullvad-relay-selector/src/lib.rs
- mullvad-relay-selector/src/updater.rs
- test/Cargo.lock
This PR is one in a series of PRs which aims to make working with the relay selector easier.
The goal of this PR is to strip the relay selector of some dependencies & code where possible, trying to focus its purpose.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5837)
> Remove lots of dependencies from mullvad relay selector

- ios/MullvadREST/Relay/RelaySelector.swift
- ios/MullvadTypes/RelayConstraints.swift
- ios/MullvadTypes/RelayLocation.swift
- ios/MullvadVPN/Coordinators/SelectLocationCoordinator.swift
- ios/MullvadVPNTests/MigrationManagerTests.swift
- ios/MullvadVPNTests/MullvadSettings/TunnelSettingsUpdateTests.swift
- ios/MullvadVPNTests/RelaySelectorTests.swift
- ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift
When a custom list enabled, the relay selector should match relays by location using the custom list - if a relay matches any of the location constraints in a custom list, it should be added to the list of eligible relays to be picked by the roulette selection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5788)
> Adjust relay selector to support custom lists

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/ComposeRuleExtensions.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/CustomPortDialogTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialogTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialogTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/PaymentDialogTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ChangelogDialogTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/DeviceRevokedScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/RedeemVoucherDialogTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreenTest.kt
This PR aims to make sure all compose tests use edge-to-edge drawing in order to replicate how the `MainActivity` works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5854)
> Fix compose tests not drawing edge-to-edge

- .github/workflows/ios-end-to-end-tests.yml
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNUITests.xcscheme
- ios/MullvadVPNUITests/README.md
- ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift
- ios/TestPlans/MullvadVPNUITestsAll.xctestplan
- ios/TestPlans/MullvadVPNUITestsSmoke.xctestplan
GitHub workflow and related changes for running login tests when pull requests are merged to `main`. Started adding information to README which should be relevant for this PR, more information will also be added to README according to the ticket https://linear.app/mullvad/issue/IOS-479/write-readme-for-ui-tests
The workflow is not runnable until after this has been merged. After merge it can be manually triggered from https://github.com/mullvad/mullvadvpn-app/actions and will also be automatically triggered for each PR merge into `main`.
Failed test runs are reported in the form of a comment on the PR with the failed merge. Link to the failed run is included.
- - - …
> GitHub actions workflow for iOS end to end tests

- .github/workflows/cargo-audit.yml
Temporarily ignore `RUSTSEC-2023-0081` in `cargo-audit` CI job. This should be reversed ASAP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5869)
> Ignore RUSTSEC-2023-0081

- mullvad-exclude/src/main.rs
- talpid-core/src/split_tunnel/linux.rs
- test/test-runner/src/sys.rs
This PR fixes `clippy` lint [suspicious_open_options](https://rust-lang.github.io/rust-clippy/master/index.html#/suspicious_open_options) added in `1.75`.
`truncate(false)` is supposedly the default behavior, but maybe we want to change this to `true`. Thoughts?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5862)
> Fix `clippy` lint 'suspicious_open_options'

- talpid-wireguard/Cargo.toml
- talpid-wireguard/src/mtu_detection.rs
Split MTU detection into an inner pure function `max_ping_sized`
and an io-dependent outer function `detect_mtu`. Add unit and prop-testing to
`max_ping_sized`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5863)
> Add unit tests to MTU detection

- ios/Configurations/UITests.xcconfig.template
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportSubmissionOverlayView.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController+ViewManagement.swift
- ios/MullvadVPNUITests/AccountTests.swift
- ios/MullvadVPNUITests/Pages/ProblemReportPage.swift
- ios/MullvadVPNUITests/Pages/ProblemReportSubmittedPage.swift
- ios/MullvadVPNUITests/SettingsTests.swift
- ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift
Created test for submitting problem reports. On stagemole all problem reports are ignored and not sent to support, therefor the current implementation fails if not running against stagemole in order to avoid spamming support. Please let me know if you have feedback on this approach. Without any safeguard it would be easy to accidentally run the test against production.
This PR includes some fixes to the `MullvadVPNUITests` build configuration to make the `Staging` configuration run - before it was only set up for `Debug` configuration . `continueAfterFailure = false` was also moved from `AccountTests` to `BaseUITestCase` so that it is set for all tests, not only tests under `AccountTests`.
To test this PR run `testSendProblemReport` under `SettingsTests`. Note that you need to change to …
> Add problem report test

- CHANGELOG.md
- mullvad-daemon/src/migrations/mod.rs
- mullvad-daemon/src/migrations/v6.rs
- mullvad-daemon/src/migrations/v8.rs
- mullvad-daemon/src/migrations/vX.rs.template
- mullvad-types/src/relay_constraints.rs
- mullvad-types/src/settings/mod.rs
- Change default obfuscation setting to `auto`.
- Add settings v9 and migrate existing users settings from `off` to `auto`
- Tweak migration template
- Fix incorrect doc comment in v6.rs
`auto` should arguably have been the default from the start, so this PR intends to address that. We believe the benefit to Mullvad users from defaulting obfuscation to `auto` (which in practice will mean `on`) outweighs the potential consequences of turning obfuscation on after they have explicitly decided to turn it off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5870)
> Change wireguard obfuscation default from off to auto and migrate users

- mullvad-cli/src/cmds/debug.rs
Previously, `mullvad debug block-connection` did not cause you to enter the blocked state until you tried to connect (or if you were already connected).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5875)
> Make `block-connection` block even if disconnected

- .github/workflows/android-app.yml
- android/app/build.gradle.kts
This PR aims to improve build speed by running most jobs in parallell. This is achieved by no longer re-using build results between steps and instead running some of the common gradle tasks in a redundant parallall way. Also makes use of a third-party action called wait-for-jobs to pause at a step in the middle of a job and awaiting artifacts from other jobs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5881)
> Improve GH actions build speed

- .github/workflows/ios-end-to-end-tests.yml
The configuration options `NO_TIME_ACCOUNT_NUMBER` and `HAS_TIME_ACCOUNT_NUMBER` are specified per configuration in `UITests.xcconfig` now. This PR reflects this change in the names of GitHub action secrets.
For now only login tests run and should run in production environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5882)
> Update to use production secrets

- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
In `setRelays(_ response: REST.ServerRelaysResponse, filter: RelayFilter)` we construct a list of item lists by looking at the number of data sources (2) and then try to index match with all section cases (1). This causes an index overflow.
Fix for the above, plus fix for row scrolling being slightly off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5886)
> Fix LocationDataSource crash in MockRelease build

- android/app/build.gradle.kts
- android/gradle.properties
- android/lib/endpoint/build.gradle.kts
- android/lib/map/build.gradle.kts
- android/service/build.gradle.kts
- android/test/e2e/build.gradle.kts
Perform migration of buildconfig in `gradle.properties` to use `buildFeatures` block instead
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5887)
> Remove buildconfig from properties

- ios/MullvadREST/Relay/RelaySelector.swift
- ios/MullvadVPNTests/RelaySelectorTests.swift
- ios/MullvadVPNTests/ServerRelaysResponse+Stubs.swift
Fixes the bug by evaluating all locations before returning the result.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5874)
> Relay selector evaluates only first location constraint when a custom list is selected

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/InformationComposeCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Chevron.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/LocationInfo.kt
This PR applies `canFocus = false` on some rows to enable each sub item to be selected, this due to limitations in how compose focus management works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5890)
> Fix VpnSettingsScreen DPAD navigation

- .github/workflows/shellcheck.yml
- ci/ios/buildserver-build-ios.sh
- ci/ios/run-in-vm.sh
- dist-assets/linux/before-remove.sh
- dist-assets/linux/mullvad-gui-launcher.sh
- dist-assets/pkg-scripts/postinstall
- dist-assets/pkg-scripts/preinstall
- dist-assets/uninstall_macos.sh
- ios/build-wireguard-go.sh
- scripts/localization
- test/ci-runtests.sh
- wireguard/libwg/build-android.sh
`shellcheck` lints scripts for common footguns. This PR adds `shellcheck` as a GitHub action, and also attempts to fix all the warnings we currently have.
Scripts are finnicky, and `shellcheck` has a tendency to give false positives, so the changed scripts should be tested before merging if the changes are non-trivial. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5876)
> Run shellcheck as a github workflow

- ios/MullvadVPNUITests/MullvadApi.swift
- mullvad-api/src/ffi/mod.rs
This PR tricks rust into believing environment variables have been set properly when running on iOS. 
With this, we can then add the `--features` flag when building crates for iOS to allow overriding the API when running in a staging environment for example.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5899)
> Force environment variables when running on iOS

- ios/MullvadSettings/CustomListRepository.swift
- ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift
- ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift
- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
It should be possible to delete a custom list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5820)
> Allow deleting custom lists

- .github/workflows/ios-end-to-end-tests.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5910)
> Fix end to end test build script

- ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCellFactory.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift
- ios/MullvadVPNTests/Location/AllLocationsDataSourceTests.swift
- ios/MullvadVPNTests/Location/CustomListsDataSourceTests.swift
- ios/MullvadVPNTests/Location/LocationNodeTests.swift
After doing some changes on the UI for custom lists, we broke our UI Automated tests. Also improves location node matching to avoid possibly duplicated node codes in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5916)
> Fix broken UI tests

- Cargo.lock
- talpid-routing/Cargo.toml
- talpid-routing/src/unix/macos/interface.rs
- talpid-routing/src/unix/macos/routing_socket.rs
This PR bumps nix to the latest 0.28 and also fixes `OwnedFd` to `File` fiddling as Rust now supports the relevant `From` trait. Also replaced esoteric `std::os::unix::prelude` includes with `std::os::fd`, hope that doesn't break Linux builds in any way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5913)
> routing: update nix

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/FilterConstrainExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
This PR fixes a regression where entering the filter screen did not select all provider by default when `Constraint` was `Any`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5920)
> Fix filter screen selection

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt
This PR splits a bunch of long methods that result in detekt linting issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5898)
> Fix long method

- talpid-routing/src/unix/macos/data.rs
- talpid-routing/src/unix/macos/mod.rs
- talpid-routing/src/unix/macos/routing_socket.rs
- talpid-routing/src/unix/macos/watch.rs
Mainly to print all of the source errors. This includes some other minor cleanup as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5929)
> Improve error handling in macOS routing module

- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideInteractor.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift
Currently, the button is always active. According to the specs, we should make sure it is not active if there are no overrides being enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5912)
> Make the 'Clear all overrides' button only active when there are overrides

- .github/workflows/ios-end-to-end-tests.yml
- .github/workflows/ios-screenshots-tests.yml
- .github/workflows/ios-validate-build-schemas.yml
- .github/workflows/ios.yml
- ios/build.sh
To improve supply chain security we should add the flag -disableAutomaticPackageResolution to xcodebuild command. This will ensure all swift dependencies (currently very few) are integrity verified against the checksums commited to the ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5928)
> Add -disableAutomaticPackageResolution to xcodebuild command

- .github/workflows/ios-end-to-end-tests.yml
Adapted to changes that have been merged to `main` which affect the workflow:
* `MULLVAD_IOS_DEVICE_PIN_CODE` has been renamed to `IOS_DEVICE_PIN_CODE `
* In `UITests.xcconfig.template` `HAS_TIME_ACCOUNT_NUMBER` and `NO_TIME_ACCOUNT_NUMBER` are specified per configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5918)
> Updated workflow to be compatible with xcconfig changes in main

- talpid-routing/src/unix/mod.rs
Couldn't find any references for them, seems like a leftover from a prior work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5922)
> Remove unused error variants in routing::unix::Error

- talpid-routing/src/windows/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5932)
> Minor Windows route manager cleanup

- talpid-routing/src/unix/mod.rs
As described in https://github.com/tokio-rs/tokio/issues/5843, current implementation of `Drop` in `RouteManager` would typically lead to panic. 
In a multi-threaded runtime the better approach would be to use `tokio::task::block_in_place`. In essence, even better approach would be to avoid doing async calls from `Drop` and call `stop()` somewhere in the clean up routine of a parent scope, but such change would encompass a larger scope and beyond what I am currently looking to fix.
I scanned the code for `current_thread_runtime` and found none in the way of that `Drop`, so I think it should work but don't take my word for it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullv …
> routing: use block_in_place() in drop impl

- CHANGELOG.md
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt
Fixes: DROID-720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5911)
> Increase ripple contrast

- CHANGELOG.md
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SwitchComposeCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
Revert so that we once again are showing the Auto-connect option on non-TV devices, but mark it as legacy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5945)
> Revert and rename the auto connect option on non tv devices

- android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/GeneralTest.kt
- android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/JUnitTest.kt
This PR removes the workaround that was fixed in `0.14.0` of Konsist.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5940)
> Remove konsist workaround

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/Scaffolding.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt
This PR aims to fix the missing copy-to-clipboard snackbar shown when copying the account number in the account screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5951)
> Fix missing copy snackbar in account screen

- .github/workflows/testframework-rust-supply-chain.yml
- test/deny.toml
This PR adds a new CI job for the test framework CI - run `cargo deny` to guard against supply chain vulnerabilities.
This is one step towards bringing the CI for the test framework on par with main workspace CI.
~~In some sense it would be nice to have a separate `deny.toml` in the `test` workspace, but on the other hand it would be hard to keep them in sync with everything that should be shared across them. For now, I put the `test` workspace specific `RUSTSEC` advisories to allow temporarily in the main `deny.toml` :shrug:~~
Answer: Duplicate `deny.toml` in the `test` workspace and modify as needed :scroll: :pen: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app …
> Run `cargo deny` in the test framework

- Cargo.lock
- talpid-core/src/dns/macos.rs
- talpid-core/src/offline/macos.rs
- talpid-routing/src/debounce.rs
- talpid-routing/src/unix/macos/mod.rs
- talpid-routing/src/unix/macos/routing_socket.rs
- talpid-types/Cargo.toml
- talpid-types/src/error.rs
Fix DES-683.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5903)
> Log when certain functions are called an excessive number of times

- talpid-routing/src/unix/macos/routing_socket.rs
- talpid-routing/src/unix/macos/watch.rs
Previously, we would just continue trying to receive data from it, but failing every time. This fix just replaces the socket when necessary.
Fix DES-682.
Related: #5949  
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5947)
> Handle `PF_ROUTE` socket being unexpectedly closed

- talpid-future/src/retry.rs
`'static` lifetimes in `retry::retry_future()` prevent borrowing in async contexts and strictly unnecessary as I believe compiler can figure out lifetimes on its own. For example retry in its current impl will not allow this:
```rs
#[async_trait]
impl MyAsyncTrait for MyType {
async fn foo(
&self,
addr: &SocketAddr,
) -> Result<u32> {
retry::retry_future(
|| self.bar(addr),  // this will not compile with static lifetime as addr has its own lifetime.
|result| { true }, 
RETRY_BACKOFF_STRATEGY
).await
}
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5941)
> retry: remove unnecessary 'static lifetimes

- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
- ios/MullvadVPNUITests/AccountTests.swift
- ios/MullvadVPNUITests/MullvadApi.swift
- ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift
Note that this PR builds upon changes from https://github.com/mullvad/mullvadvpn-app/pull/5855 so not ready for review until it has been merged and marked as draft for now.
Introduced log out test which validates that device is created when logging in and removed when logging out. Note that the implementation slightly differs from the issue description in Linear because the issue mentions reading the device name but the implementation don't. I think it wouldn't serve any purpose since the test makes sure that one device is created and then removed?
To test the changes run `testLogOut` under `AccountTests`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5878)
> Test logging out

- ios/build-rust-library.sh
This PR will enable us building rust crate features by passing a second argument to the `build-rust-library.sh` script. 
For example
`build-rust-library.sh mullvad-api api-override`
If we need to build more than one feature flag, we can pass in a single argument, all the features separated by spaces
`build-rust-library.sh mullvad-api "featureA featureB featureC"`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5944)
> Enable building features in crates on iOS

- .github/workflows/git-commit-message-style.yml
Add CI checks to constrain git commit messages to our [preferred style](https://github.com/mullvad/coding-guidelines/?tab=readme-ov-file#commit-messages). There just happened to be an existing Github action that do the checking more or less according to our existing guidelines.
I wish the imperative form verb check could be disabled. Even though it is the preferred style, I'm afraid it's overly nitpicky. But we can try and see if we think it's OK or too annoying.
Added separate check with regex that catches any whitespace that is not a space, tab (`\t`) or newline (`\n`). Prevents non-visible unexpected whitespaces.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/ …
> Check git commit message style

- android/lib/resource/src/main/res/values/strings_non_translatable.xml
This PR aims to fix the format of IPv6 addresses in the allow lan info dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5958)
> Fix format of ipv6 addresses in the allow lan info dialog

- talpid-core/src/offline/macos.rs
- talpid-core/src/offline/windows.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- talpid-openvpn/src/lib.rs
- talpid-routing/src/lib.rs
- talpid-routing/src/unix/mod.rs
- talpid-routing/src/windows/mod.rs
- talpid-wireguard/src/lib.rs
Follow up to #5934. `RouteManager` and `RouteManagerHandle` are both handles that interact with the same actor. The main difference is that `RouteManager` calls `stop` when dropped. This is unnecessary since the manager is also stopped when all copies of the sender are dropped, which is a pattern that we rely on a lot, so this PR merges them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5937)
> Remove `RouteManagerHandle`

- ios/MullvadSettings/CustomListRepository.swift
- ios/MullvadSettings/CustomListRepositoryProtocol.swift
- ios/MullvadTypes/RelayConstraints.swift
- ios/MullvadTypes/RelayLocation.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListInteractor.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift
- ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/ListCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/ListCustomListViewController.swift
- ios/MullvadVPN/Coordinators/LocationCoordinator.swift
- ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift
- ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/InMemoryCustomListRepository.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift
- ios/MullvadVPNTests/Location/CustomListRepositoryTests.swift
- ios/MullvadVPNTests/Location/CustomListsDataSourceTests.swift
- ios/MullvadVPNTests/MigrationManagerTests.swift
- ios/MullvadVPNTests/Mocks/CustomListsRepositoryStub.swift
- ios/MullvadVPNTests/MullvadSettings/TunnelSettingsUpdateTests.swift
- ios/MullvadVPNTests/RelayConstraintsTests.swift
- ios/MullvadVPNTests/RelaySelectorTests.swift
- ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift
When a user decides to edit a custom list they will be sent to a view with all available custom lists. It should look like the view with similar functionality in api access methods. Clicking on one of lists will take the user to an edit screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5909)
> Create view with custom lists to edit

- ios/MullvadVPN.xcodeproj/project.pbxproj
When we added the privacy manifest to our project, it seems we forgot to include it in the bundle, which triggered Apple's automatic emails letting us know we are missing it.
This PR fixes that. The `PrivacyInfo.xcprivacy` is now added both to the main target, and the network extension bundle.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5959)
> Add the PrivacyInfo manifest to both target bundles

- ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift
It seems that maintaining a strong reference from a parent to a location node can cause a memory leak. Making that reference weak allows the automatic reference counting (ARC) system to release the memory when the object is no longer needed or exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5962)
> Fix memory leak at LocationNode

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt
Moves padding inside of scrolled content
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5966)
> Fix privacy policy paddings

- android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt
This PR aims to increase the e2e connection timeout from 3s -> 30s. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5973)
> Increase e2e test connection timeout

- CHANGELOG.md
- Cargo.lock
- deny.toml
- mullvad-daemon/src/logging.rs
- talpid-core/Cargo.toml
- talpid-core/src/resolver.rs
This PR simply upgrades `hickory-dns` to its latest commit on `main`. This is needed for two reasons:
* Fix a bug that resulted in 100% CPU usage (https://github.com/hickory-dns/hickory-dns/pull/2023).
* Handle unexpectedly closed sockets more gracefully. Previously, we would pointlessly read from these and quickly fill up the log with errors. Related: #5950.
Fix DES-664
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5965)
> Fix macOS CPU usage bug

- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/src/dns/macos.rs
- talpid-core/src/dns/mod.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- talpid-routing/src/debounce.rs
- talpid-routing/src/lib.rs
Replace the change counter with a burst guard. Since the daemon no longer fights furiously over controlling DNS, the error state transition has been removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5964)
> Simplify DNS monitor on macOS

- .github/workflows/git-commit-message-style.yml
Feel free to suggest even more verbs that you think you might have good use for. But we can also extend it later as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5975)
> Add more allowed git commit message verbs

- gui/src/main/window-controller.ts
- gui/src/renderer/components/Map.tsx
- gui/src/renderer/lib/3dmap.ts
- gui/src/renderer/lib/utilityHooks.ts
- gui/src/shared/ipc-helpers.ts
- gui/src/shared/ipc-schema.ts
We've had multiple issues with the scaling of the new WebGL map.
1. The map wasn't scaled properly under Wayland with a fractional scaling level. This was solved by rounding the `devicePixelRatio` up to the next integer since that is how Wayland handles fractional scaling.
2. When the dimensions or scale changed the map didn't scale properly. This was fixed by resetting the viewport when size or scale changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5977)
> Fix incorrect map scale

- CHANGELOG.md
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/config/config.mobsf
This is achieved by enabling `filterTouchesWhenObscured` on the main decor view.
The validity was tested using this application:
https://github.com/carlospolop/Tapjacking-ExportedActivity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5981)
> Prevent some forms of tapjacking

- ios/PacketTunnel/PacketTunnelProvider/SettingsReader.swift
- ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift
- ios/PacketTunnelCore/Actor/Protocols/SettingsReaderProtocol.swift
- ios/PacketTunnelCoreTests/Mocks/SettingsReaderStub.swift
- ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
- ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift
This PR enables reading the Quantum Resistance settings from the `SettingsReader` object, which will help deciding when to request Post Quantum key exchange.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5993)
> Enable reading Quantum Resistance settings from SettingsReader

- ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift
- ios/MullvadVPNTests/Location/CustomListsDataSourceTests.swift
Selecting a location in a custom list in location view is not retained when closing and opening the view again. This is due to a bug in how the node tree is created with incorrect parent nodes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5995)
> Fix selection of custom list location not being retained

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialogTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/MtuDialog.kt
- Hides "Reset to default" when already at default
- Makes "Reset to default" button red
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5994)
> Fix "Reset to default" inconsistency

- gui/src/main/account.ts
- gui/src/main/index.ts
- gui/src/main/notification-controller.ts
- gui/src/main/tray-icon-controller.ts
- gui/src/main/user-interface.ts
This PR adds dismissal of tunnel state notification in the beginning of `onDaemonConnected` and `onDaemonDisconnected`. This prevents the notification dot from remaining in this state if it shouldn't.
I've also added logging to easier find the cause of the notification dot being displayed when it shouldn't.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5999)
> Reduce risk of notification icon displaying when it shouldn't and improve logging

- Cargo.lock
- test/Cargo.lock
We already check our Rust dependency tree against vulnerabilities posted to RUSTSEC. However, there are Rust package vulnerabilities not posted there. I found these known vulnerabilities via the osv.dev database.
I will work independently of this to integrate the `osv-scanner` into our CI to catch these things earlier in the future.
See individual commit messages for more details.
Fixes DES-707
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6000)
> Upgrade vulnerable rust deps (found with osv-scanner)

- .github/workflows/git-commit-message-style.yml
The combined diff is not the easiest way to view this PR. Per commit is way more logical.
Commit 1: Change `max-subject-line-length` from 74 to 72. This was just an error when I initially added the job. I invalidly thought 74 was the default body line length (this is where vim and other git aware editors automatically insert a line break), but it is of course 72! So I'm just correcting this. Nothing major really.
Commit 2: Move the `Check for unicode whitespaces` step to run first. This is because the mristin/opinionated-commit-message action can sometimes fail on things we don't consider blocking/hard errors. Such as a correct imperative verb that does not happen to be in the action's wordlist. In these cases the job is aborted and the whitespace checking step is never executed, leading …
> Improve git commit message check

- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnelCore/Actor/ObservedState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+NetworkReachability.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
- ios/PacketTunnelCore/Actor/State.swift
This replaces recurring cascades of case statements that mutate `State`'s associated values with one utility method on State: `mutateAssociatedData`, which take a function that might modify the appropriate associated value, and if the current state has such a value, applies it and returns whether a modification took place.  The function is given a `StateAssociatedData` type, which is a protocol encompassing both the connection and blocked state data's common fields.
The benefit of this change is increased separation of concerns: code that cares only about the connection/error state no longer needs to know which states exist, which will make changing the logic of the state machine simpler, as there will be fewer places where changes are needed.
- - - …
> Replace duplicated cascades of case statements with utility methods on State

- test/test-manager/src/tests/split_tunnel.rs
Noticed that the timeout when reading the result from the connection checker process was lower that the timeout we passed to the process by argument.
Here the test failed with a misleading error message because of this: https://github.com/mullvad/mullvadvpn-app/actions/runs/8367587113/job/22910252989
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6005)
> Fix wonky timeouts in test_split_tunnel

- ios/MullvadREST/Transport/AccessMethodIterator.swift
When "Direct" is disabled and "Mullvad bridges" is in use, if app is then removed and reinstalled, "Direct" is enabled again (correct) and "Mullvad bridges" in use (wrong, should be "Direct").
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6004)
> Fix not showing the correct api access method in use on app reinstall

- android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/CameraAnimation.kt
- android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/Constants.kt
- android/lib/map/src/main/kotlin/net/mullvad/mullvadvpn/lib/map/internal/MapGLRenderer.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/LatLong.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/Latitude.kt
- android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/model/LatLongTest.kt
This PR implements a new algorithm to evaluate the distance between two location that is then used to decide which type of animation we are using.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5991)
> Improve animation duration calculation

- Cargo.toml
- android/docker/Dockerfile
- building/android-container-image.txt
- building/linux-container-image.txt
- test/Cargo.toml
Upgrade build containers. The new containers have already been built and their signatures has been push to main already in 18622145f371cce037e385e37b614a5b28b6ea2b and 0bda1107d189189298aaf989baa13d4099f7c164.
This PR can be merged once we have verified the apps can be properly built from these new containers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6010)
> Upgrade build containers to use Rust 1.77

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Navigation.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5986)
> Do not show a toast after dismissing the dns dialog

- test/Cargo.lock
- test/Cargo.toml
- test/test-manager/src/tests/account.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/tunnel.rs
- test/test-rpc/src/client.rs
This PR adds a test to verify that the app can connect to a VPN server and get working internet even if the API is unavailable. As long as the user has managed to log in to the app, the rest should just work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6013)
> Add test that makes sure connecting works without the API

- talpid-openvpn/src/lib.rs
Fix `dead-code` warning introduced by new nightly version of `rustc`: https://github.com/mullvad/mullvadvpn-app/actions/runs/8417884935/job/23047218528
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6020)
> Remove unused field - fix dead code warning on nightly

- ios/Configurations/UITests.xcconfig.template
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
- ios/MullvadVPN/View controllers/Settings/SettingsViewController.swift
- ios/MullvadVPN/View controllers/Tunnel/ConnectionPanelView.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
- ios/MullvadVPNUITests/Info.plist
- ios/MullvadVPNUITests/Networking/FirewallAPIClient.swift
- ios/MullvadVPNUITests/Networking/FirewallRule.swift
- ios/MullvadVPNUITests/Networking/Networking.swift
- ios/MullvadVPNUITests/Pages/Page.swift
- ios/MullvadVPNUITests/Pages/SelectLocationPage.swift
- ios/MullvadVPNUITests/Pages/SettingsPage.swift
- ios/MullvadVPNUITests/Pages/TunnelControlPage.swift
- ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift
- ios/MullvadVPNUITests/RelayTests.swift
- ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift
In this PR the following tests have been implemented:
* `testWireGuardOverTCPManually` - https://linear.app/mullvad/issue/IOS-431/test-wireguard-over-tcp-manually
* `testWireGuardOverTCPAutomatically` - https://linear.app/mullvad/issue/IOS-429/test-wireguard-over-tcp-works-automatically
* `testWireGuardPortSettings` - https://linear.app/mullvad/issue/IOS-434/test-wireguard-port-settings
To test it out you can run the three tests, they are all under `RelayTests`. Another configuration property `SHOULD_BE_REACHABLE_DOMAIN = mullvad.net` has been introduced so make sure to set it in your `UITests.xcconfig` file. You must be connected to the `app-team-ios-tests` wifi to be able to run tests interacting with the firewall running on the NUC.
- - - …
> Add WireGuard tests for iOS app

- Cargo.lock
- deny.toml
- talpid-core/Cargo.toml
We should avoid depending on git repositories outside our own control. The hickory-dns organization or repository can go away at any point in time. That will make it way harder to re-build old versions of the app.
I also asked the maintainers if they could publish a patch release, because we should avoid git dependencies altogether when we can :pray:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6015)
> Point the hickory-dns dependency to our own fork of the repo

- test/test-manager/src/tests/install.rs
`mullvad relay set location xx` no longer works (https://github.com/mullvad/mullvadvpn-app/actions/runs/8420230971/job/23054624667#step:4:850). The PR switches to using `mullvad debug block-connection` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6026)
> Enter blocking state correctly in upgrade test

- .github/workflows/verify-locked-down-signatures.yml
- deny.toml
- test/deny.toml
This PR does a bunch of housekeeping around our usage of `cargo deny`. I saw that running `cargo deny` produced a bunch of warnings, since we use deprecated fields. This PR fixes that and more.
This PR is probably easiest to review per commit!
* Add `version = 2` where suitable and remove deprecated fields
* Remove fields which were set to default values anyway. No need to explicitly set them, just noisy.
* Require signatures to changes to `test/deny.toml` - Arguably way less important than the main `deny.toml` but still in some ways affect supply chain security and licenses, so should be signed.
* Adds more targets. Since we do build this software for Android and iOS also, we should check it strictly
* No need to explicitly deny `atty` I feel. That crate has a CVE registered against it …
> Update `deny.toml` files for new `version = 2` format, and other cleanups.

- mullvad-daemon/src/device/mod.rs
This PR changes how and when device checks are being performed.
Perform a device check after 3 failed connection attempts and a new connection-loop* begins, regardless of when the next Wireguard connection attempt happens. The device check counter is only reset if the app is able to connect to a Wireguard relay. Otherwise, the counter is either persisted through multiple tunnel connections (OpenVPN) or incremented on successive failures to connect to a Wireguard relay.
*A connection-loop is initiated when the user starts connecting to a relay and ends when any of the following states are reached:
- Connected
- Disconnected
- Error
- - - …
> Change how & when device checks are performed

- talpid-core/src/tunnel_state_machine/disconnected_state.rs
- talpid-core/src/tunnel_state_machine/disconnecting_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
Currently, its effect is to always enter the error state, regardless of the current state. Its new behavior is to do nothing when disconnected or leaving a secured state. This shouldn't affect any existing code since we do not rely on entering the blocked state when disconnected.
Related: #5844
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6032)
> Ignore "block" tunnel command except in secured states

- .github/workflows/git-commit-message-style.yml
Includes our contributions to the action with ~185 more allowed imperative verbs. That's also why we no longer need to specify any `additional-verbs`.
Pins the action to a commit hash rather than tag. For supply chain security. We might want to do this with way more third party actions, but this is mostly a test to try this out for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6034)
> Bump opinionated-commit-message github action to version with more verbs

- .github/workflows/git-commit-message-style.yml
This allows commits to start with "Tidy"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6037)
> Add "tidy" as an imperative verb

- .github/workflows/git-commit-message-style.yml
Allowing commit messages to start with "Tidy"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6038)
> Add tidy as commit message verb

- mullvad-daemon/src/tunnel.rs
- mullvad-relay-selector/src/relay_selector/detailer.rs
- mullvad-relay-selector/src/relay_selector/matcher.rs
- mullvad-relay-selector/src/relay_selector/mod.rs
- mullvad-types/src/relay_constraints.rs
- mullvad-types/src/relay_list.rs
Do not panic when getting public key of relay due to unwrapping an unexpected relay type. The unwrap happened if an OpenVPN relay was selected on Android, which should not happen in the first place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6033)
> Do not panic when reading public key of relay

- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
A user has reported a crash in LocationDataSource, when appending items to the diffable data source. It's not very clear as to what the problem is, since it points to the Apple framework function NSDiffableDataSourceSnapshot.appendItems.
The fix in this PR is mostly a half-baked guess at solving the problem and something that looks nicer in our code anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5987)
> Queue all updates to snapshot in LocationDataSource asynchronously

- wireguard/libwg/go.mod
We already use go 1.21 in our build containers and build servers. So this does not change what version we actually use, only makes go.mod reflect reality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6040)
> Upgrade go to 1.21 in `go.mod`

- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/TunnelManager/SetAccountOperation.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
We should not remove any settings when a user logs out or explicitly deletes an account. Or rather, only app uninstall should trigger a removal of app settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6024)
> Remove settings only on app uninstall

- .github/workflows/verify-locked-down-signatures.yml
- Cargo.toml
- test/Cargo.toml
A small but nice step towards preventing [homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack). We always use English in code and variable names anyway. We have no reason to use non-ascii characters in identifiers (variable and function names) so we can easily forbid them.
Since this makes `Cargo.toml` contain supply chain security related config, I mark it as needing signatures to be changed.
Ideally I'd like a linter/code scanning tool that is language aware and can make sure everything that is not a comment or a string literal is ascii only. Those are the only places where I see legitimate use for non-ascii code points in our product.
- - - …
> Forbid unicode identifiers in rust

- Cargo.toml
- test/Cargo.toml
I went through the list at https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html and decided to warn/deny a few more lints. Mostly for cleanliness and consistency. The intention is to keep the code more modern, consistent and get rid of unused code.
* `macro_use_extern_crate` - Forbid #[macro_use] to bring macros into global scope. Even using `extern crate` is deprecated by now, so just extra protection against that
* `explicit_outlives_requirements` - Warn aginst explicit lifetime bounds that can be inferred from the code. Keeps noise away.
* `absolute_paths_not_starting_with_crate` - Catches Rust 2015 style absolute paths and denies them.
* `missing_abi` - Force explicitly stating the ABI of `extern` items. Less implicit code
* `unused_lifetimes` - Warn if you have …
> Enable more of the Allowed-by-default lints in rustc

- mullvad-api/src/abortable_stream.rs
The contract of [`FusedFuture`](https://docs.rs/futures/latest/futures/future/trait.FusedFuture.html) says that a future implementing the trait keeps track of when it has been resolved, but not that it is safe to poll it afterwards. As it turns out, it is safe to poll `oneshot::Receiver` when it has been resolved, but this is arguably an implementation detail. `Fuse`, however, [promises](https://docs.rs/futures/latest/futures/future/trait.FutureExt.html#method.fuse) to always return `Pending`.
Close DES-688.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6052)
> Wrap AbortableStream abort receiver in Fuse

- Cargo.toml
- android/translations-converter/src/gettext/msg_string.rs
- mullvad-cli/src/cmds/api_access.rs
- mullvad-cli/src/cmds/custom_list.rs
- mullvad-cli/src/cmds/proxies.rs
- mullvad-daemon/src/settings/mod.rs
- mullvad-jni/src/is_null.rs
- mullvad-types/src/relay_constraints.rs
- talpid-core/src/dns/windows/tcpip.rs
- talpid-dbus/src/systemd_resolved.rs
- talpid-routing/src/unix/macos/data.rs
- talpid-windows/src/net.rs
- test/Cargo.toml
Removes superfluous lifetime definitions. Simplifying the code. Here is the docs for this lint: https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#single-use-lifetimes
Since we obviously had a pretty large number of these, I think the lint can help us keep code simpler. The only potential red flag I see is the lint docs saying "Also, there are some known false positives". I did not stumble over any false positives (that I noticed) when doing this small refactoring. If it turns out to be too troublesome we can disable the lint again. Or add `#[allow(single_use_lifetimes)]` to the places where it does not work as intended.
- - - …
> Lint against single use lifetimes

- ios/PacketTunnelCore/Actor/ObservedState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+NetworkReachability.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
- ios/PacketTunnelCore/Actor/State.swift
- ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
This involves:
* defining a protocol, `StateAssociatedData`, which encompasses common fields of the connection data for connected states and blockage data for error states
* implementing a method, `mutateAssociatedData`, which applies a mutating function to the data, if present, and replacing a lot of case statements with this
* renaming `ConnectionState` and `BlockedState` to `State.ConnectionData` and `State.BlockingData`, for clarity and namespace hygiene
* making `State` `Èquatable` (within reason), and using equality testing in lieu of keeping track of whether a change was made
The result: a lot of business logic that acts on/modifies connection/blockage data is now considerably shorter, as it no longer needs to know about what the state is or which states may exist.
This was made in …
> Refactor PacketTunnelActor State, decoupling state from ancilliary data

- .github/workflows/git-commit-message-style.yml
@dlon You recently used "wrap" and this job triggered. So let's add it! A perfectly fine verb I think
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6068)
> Add "wrap" to list of allowed imperative verbs in git commit messages

- ios/PacketTunnelCore/Actor/Task+Duration.swift
- ios/PacketTunnelCoreTests/TaskSleepTests.swift
This PR fixes a subtle bug where a `DispatchSourceTimer` is used alongside swift async code in an unsafe way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6045)
> Fix a race condition bug involving timers and async tasks

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6058)
> Fix blocked connection text color

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
This fixes items, especially "All locations" title, being obscured when expanding the custom list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6056)
> Fix custom list expand animations

- .github/actions/ios-end-to-end-tests/action.yml
- .github/workflows/ios-end-to-end-tests-settings-migration.yml
- .github/workflows/ios-end-to-end-tests.yml
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNUITests.xcscheme
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/Settings/SettingsDNSTextCell.swift
- ios/MullvadVPN/View controllers/VPNSettings/CustomDNSCellFactory.swift
- ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
- ios/MullvadVPNUITests/ConnectivityTests.swift
- ios/MullvadVPNUITests/Pages/DNSSettingsPage.swift
- ios/MullvadVPNUITests/Pages/SettingsPage.swift
- ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift
- ios/MullvadVPNUITests/README.md
- ios/MullvadVPNUITests/RelayTests.swift
- ios/MullvadVPNUITests/SettingsMigrationTests.swift
- ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift
- ios/MullvadVPNUITests/XCUIElement+Extensions.swift
- ios/TestPlans/MullvadVPNUITestsAll.xctestplan
- ios/TestPlans/MullvadVPNUITestsChangeDNSSettings.xctestplan
- ios/TestPlans/MullvadVPNUITestsChangeSettings.xctestplan
- ios/TestPlans/MullvadVPNUITestsVerifyDNSSettingsChanged.xctestplan
- ios/TestPlans/MullvadVPNUITestsVerifySettingsChanged.xctestplan
This PR adds tests for verifying that settings are successfully migrated when updating from an older app version to the current app version. Also nightly test runs have been configured.
For running settings migration tests there's a new workflow iOS settings migration tests(`ios-end-to-end-tests-settings-migration.yml`). It installs an old app version, runs test changing settings, installs current app version and runs a test verifying that the settings are still changed. Since custom DNS cannot be set when DNS blockers are activated there has to be two runs where settings are changed and it's verified that they're still changed on new app version - one run for "use custom DNS" setting and one run for all other settings.
All tests are scheduled to run nightly(`ios-end-to-end-tests.yml` and …
> Test updating between app versions and nightly test runs

- CHANGELOG.md
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SplitTunnelingCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Bitmap.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/PackageManagerExtensions.kt
Also add a out of memory check for even larger app icons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6071)
> Avoid rendering bitmaps above 100MB

- ios/MullvadREST/Relay/RelaySelector.swift
Steps to reproduce the issue:
1. Connect to a relay
2. Filter providers, select 31173
3. Tap switch location
4. Select USA as a country
5. Enter blocked mode
6. Tap switch location again
7. Add 100 TB as a provider
8. Select USA
9. Enter blocked connection, despite having locations match in the USA
The underlying issue is that relays can be set to not be included in a country when a user sets a country location constraint, i.e. there are relays that should not be considered for selection even though they'd match a location constraint. However, it can be the case that all relays provided by a specific provider are marked to not be included in a country, which is the case for 100TB and US. In this case, the relay selector should disregard the flag and allow the relays anyway. The iOS …
> Fix Relayselector not resolving locations under certain constraints

- talpid-platform-metadata/src/android.rs
- talpid-platform-metadata/src/command.rs
- talpid-platform-metadata/src/lib.rs
- talpid-platform-metadata/src/linux.rs
- talpid-platform-metadata/src/macos.rs
Add `MacosVersion`, which is analogous to the `WindowsVersion` struct on Windows.
Related: #5844 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6072)
> Add helper for parsing the current macOS version

- mullvad-types/src/constraints/constraint.rs
- mullvad-types/src/relay_constraints.rs
- test/test-manager/src/config.rs
- test/test-manager/src/tests/mod.rs
- test/test-manager/src/tests/relay_ip_overrides.rs
- test/test-rpc/src/net.rs
- test/test-runner/src/main.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6028)
> Add relay ip override e2e tests

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
This fixes the effect of custom list description text "floating" above other items during the expand/collapse animation for custom lists in the select location screen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6061)
> Fix floating effect for custom list description

- mullvad-relay-selector/src/relay_selector/detailer.rs
- mullvad-relay-selector/src/relay_selector/helpers.rs
- mullvad-relay-selector/src/relay_selector/mod.rs
This PR addresses a [recent regression](https://github.com/mullvad/mullvadvpn-app/pull/6082) where if all bridges would be discarded before random selection, the tunnel parameters would still be generated. We should instead fail loudly and don't attempt to establish a tunnel in that case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6083)
> Fix connection being made without bridge if there are no bridges

- ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
- ios/PacketTunnelCore/Actor/State.swift
This continues the refactoring merged to main earlier. In this:
- `KeyPolicy` becomes `State.KeyPolicy`
- `ReconnectReason` becomes `PacketTunnelActor.ReconnectReason`
- `TargetStateForReconnect` moves under `State`
- `StatePriorToBlockedState` becomes `State.BlockingData.PriorState`
All these types have been evaluated to be structurally subordinate to the namespaces they have been moved under, meaning that these changes do not introduce any ambiguities, but merely declutter the namespace. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6070)
> Additional refactoring of PacketTunnelActor State; mostly placing clearly subordinate types under appropriate namespaces

- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPNUITests/Networking/FirewallRule.swift
- ios/MullvadVPNUITests/Pages/SelectLocationPage.swift
- ios/MullvadVPNUITests/Pages/TunnelControlPage.swift
- ios/MullvadVPNUITests/RelayTests.swift
Implemented connection retry logic test which blocks all connections to a relay then let the app connect to it and observes the connection attempts made by the app in order to verify that they're done in the correct order.
Note that there's a UI bug which most of the time prevent one of the first two UDP connection attempts from being shown in the app even though the attempt is actually made. Therefor the test also allows for this incorrect flow of attempts where only one UDP connection attempt is displayed instead of two.
To test the changes in this PR your phone must be on the `app-team-ios-tests` wifi. Run `testConnectionRetryLogic` under `RelayTests`.
- - - …
> Add connection retry logic test

- ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
When a location is selected in the location list, it is not highlighted in the list. Instead, the previously selected location remains highlighted. This should not be the case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6069)
> Fix location selection bug on iPad

- .github/workflows/ios-end-to-end-tests.yml
- ios/MullvadVPNUITests/Networking/Networking.swift
- ios/MullvadVPNUITests/RelayTests.swift
- ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift
Implemented test for custom DNS server. The test specifies a custom DNS server and verifies that it is actually used. To test this PR run the test `testCustomDNS` under `RelayTests`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6041)
> Test custom DNS

- talpid-platform-metadata/src/windows.rs
- test/test-manager/src/run_tests.rs
- test/test-rpc/src/client.rs
- test/test-rpc/src/lib.rs
- test/test-rpc/src/meta.rs
- test/test-runner/src/main.rs
- test/test-runner/src/sys.rs
This can be expanded as needed. Currently, we only need to obtain the major version on macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6087)
> Add OS version RPC to test framework

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt
- android/lib/resource/src/main/res/values-da/strings.xml
- android/lib/resource/src/main/res/values-de/strings.xml
- android/lib/resource/src/main/res/values-es/strings.xml
- android/lib/resource/src/main/res/values-fi/strings.xml
- android/lib/resource/src/main/res/values-fr/strings.xml
- android/lib/resource/src/main/res/values-it/strings.xml
- android/lib/resource/src/main/res/values-ja/strings.xml
- android/lib/resource/src/main/res/values-ko/strings.xml
- android/lib/resource/src/main/res/values-my/strings.xml
- android/lib/resource/src/main/res/values-nb/strings.xml
- android/lib/resource/src/main/res/values-nl/strings.xml
- android/lib/resource/src/main/res/values-pl/strings.xml
- android/lib/resource/src/main/res/values-pt/strings.xml
- android/lib/resource/src/main/res/values-ru/strings.xml
- android/lib/resource/src/main/res/values-sv/strings.xml
- android/lib/resource/src/main/res/values-th/strings.xml
- android/lib/resource/src/main/res/values-tr/strings.xml
- android/lib/resource/src/main/res/values-zh-rCN/strings.xml
- android/lib/resource/src/main/res/values-zh-rTW/strings.xml
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6060)
> Remove Split tunneling disabled description

- mullvad-daemon/src/main.rs
- mullvad-daemon/src/runtime.rs
- mullvad-daemon/src/system_service.rs
- mullvad-jni/src/lib.rs
Fix DES-776.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6088)
> Initialize logging properly when starting Windows service

- .github/workflows/ios-end-to-end-tests.yml
Nightly iOS end-to-end tests should've ran last night since the PR introducing them was merged yesterday, but they were skipped because of the `if` condition for the workflow. This PR has a modified `if` condition to run tests when triggered by schedule as well. Tested this on a fork to verify that the workflow is not skipped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6074)
> Fix nightly iOS end-to-end tests not ran

- test/test-manager/src/main.rs
- test/test-manager/src/run_tests.rs
- test/test-manager/src/summary.rs
- test/test-manager/src/tests/mod.rs
This PR
- sorts the E2E test result matrix in the same order as the tests are run,
- and adds the `test-manager list-tests` command, which I found helpful when testing :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6097)
> Sort e2e test summary and add list-tests command

- ios/MullvadVPN/Coordinators/LocationCoordinator.swift
To enhance the differentiation between enabled and disabled actions, we've opted for a more distinct color that ensures better visibility. This PR implements this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6096)
> Change action sheet tint color

- ios/CHANGELOG.md
We've made custom lists available in release builds - our changelog should reflect that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6104)
> Add custom lists to iOS changelog

- ios/MullvadVPN/Coordinators/CustomLists/ListCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/ListCustomListViewController.swift
When the last custom list is deleted, it's preferable to navigate the user to the "select location" view instead of displaying an empty list. This PR introduces this functionality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6103)
> Revise navigation for empty Custom Lists

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Containers/Navigation/UINavigationBar+Appearance.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/ListCellContentConfiguration.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/TextCellContentConfiguration.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideHeaderView.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewController.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideViewControllerDelegate.swift
- ios/MullvadVPN/UI appearance/UIColor+Palette.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
In the Server IP Override section, the title should be at the same level as other top level titles in pages such as API Access or VPN Settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5983)
> Move the title 'Server IP Override' up

- mullvad-management-interface/src/client.rs
- test/test-manager/src/tests/account.rs
Fixes DES-774.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6090)
> Fix flaky wireguard key rotation test

- mullvad-types/src/wireguard.rs
As requested by services team
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6112)
> Change WireGuard key rotation interval to 30 days for desktop + Android

- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/Account/AccountExpiryRow.swift
- ios/MullvadVPNUITests/AccountTests.swift
- ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift
- ios/MullvadVPNUITests/Pages/AccountPage.swift
Implemented test verifying that time left is properly displayed. To test the changes in this PR run the test `testTimeLeft` under `AccountTests`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6049)
> Add time left properly displayed test

- ios/MullvadVPN/TunnelManager/WgKeyRotation.swift
We're updating the key rotation interval to 30 days across all clients now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6113)
> Bump key rotation interval to 30 days on iOS

- gui/locales/messages.pot
- gui/src/renderer/components/ApiAccessMethods.tsx
- gui/src/renderer/components/EditApiAccessMethod.tsx
This PR makes some strings translatable that weren't. "SOCKS5" and "Shadowsocks" has been marked in Crowdin as `translatable: false`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6115)
> Add missing translations in Api Access views

- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/custom_list.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/client.rs
- mullvad-types/src/access_method.rs
- mullvad-types/src/custom_list.rs
- test/test-manager/src/tests/mod.rs
I noticed the `cleanup_after_test` seemed to omit a few settings, namely:
- `api_access_methods`
- `relay_overrides`
- `custom_lists`
So I added those to the cleanup function.
I also noticed that `clear_split_tunnel_processes` and `clear_split_tunnel_apps` were gated behind `#[cfg(target_os)]`, which doesn't seem right since that only checks the host machine, not the test runner. So I removed the cfg gate, hopefully that doesn't break anything.
Lastly, I added a GRPC call to clear all the custom API access methods, mostly to support the cleanup function. This may be overkill.
Update: Added a GRPC call to clear custom lists as well
- - - …
> Make sure all settings are cleared in between E2E tests.

- test/Cargo.lock
- test/socks-server/src/lib.rs
- test/test-manager/Cargo.toml
- test/test-manager/src/mullvad_daemon.rs
- test/test-manager/src/run_tests.rs
- test/test-manager/src/tests/access_methods.rs
- test/test-manager/src/tests/dns.rs
- test/test-manager/src/tests/mod.rs
- test/test-manager/test_macro/src/lib.rs
- test/test-rpc/src/client.rs
- test/test-rpc/src/lib.rs
- test/test-runner/src/main.rs
- test/test-runner/src/sys.rs
This PR addresses an issue in the test framework where some test would mess with the daemon's environment variables without resetting them to their expected default values. 
This could lead to subsequent tests failing for unforeseen reasons, which was very confusing.
After each test is finished, we check whether the daemon's environment variables deviate from the one's specified by the current test configuration. If so, we restart the daemon with the 'expected values'. This all happens in the existing clean up routine, which means that no tests *should* have to clean up this particular mess themselves.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6108)
> Fix flaky tests caused by messed up daemon environment

- ios/MullvadVPN/View controllers/SelectLocation/CustomListLocationNodeBuilder.swift
This pull request introduces functionality to display the locations of a custom list in alphabetical sorting within each location group. To achieve this, the following steps were taken:
1. Grouping the locations of a custom list based on `Country` `City`, and `Host`.
2. Implementing alphabetical sorting for each location group.
3. Concatenating them together to create a flat array.
4. Disabling custom lists that have no children, making them unselectable.
<table >
<tr>
<th height="30" bgcolor="#002387">before</th>
<th height="30" bgcolor="#002387">after</th>
</tr>
<tr>
<td><img src = "https://github.com/mullvad/mullvadvpn-app/assets/129863230/554f11bd-48a8-42a4-9b64-9110c1c6432c" width = "200"/></td>
<td><img src = "https://github.com/mullvad/mullvadvpn-app/assets/129863230/71dd4642-c145-4 …
> Alphabetical sorting for custom list locations ios 604

- ios/MullvadSettings/CustomListRepository.swift
It shouldn't be possible to save a custom list with an already existing list name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6105)
> Prevent duplicate list names in custom lists

- deny.toml
- test/deny.toml
This PR adds Zlib to the list of allowed licenses in `deny.toml`, since it is compatible with GPL-3.
Reference:
https://www.gnu.org/licenses/license-list.html#ZLib
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6124)
> Add Zlib to allowed licences

- gui/src/renderer/components/ProxyForm.tsx
Our automatic tests notified us that the Add/Save button was showing Save sometimes when adding a new access method or custom bridge. This PR fixes that by using the correct variable to decide if the proxy is new or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6126)
> Fix Add/Save button in ProxyForm

- talpid-openvpn/Cargo.toml
- talpid-windows/Cargo.toml
While investigating issues with Wintun, I stumbled upon 2 cases where `talpid-*` crates would not compile correctly on Windows due to missing Cargo features.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6127)
> Fix Windows compile errors due to missing features

- ios/MullvadVPN/AppDelegate.swift
We wipe all settings when the app is deleted and then installed again. Currently no default settings are stored after that, which puts the tunnel into blocked state since it cannot read any settings. We should add the default settings right after the wipe to remedy this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6123)
> Add default settings when app is uninstalled

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/InterceptibleNavigationController.swift
- ios/MullvadVPN/Coordinators/CustomLists/AddCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/AddLocationsCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift
- ios/MullvadVPN/Coordinators/CustomLists/AddLocationsViewController.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListViewModel.swift
- ios/MullvadVPN/Coordinators/CustomLists/EditCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/EditLocationsCoordinator.swift
- ios/MullvadVPN/Coordinators/CustomLists/ListCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/LocationCoordinator.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationSectionHeaderView.swift
Due to the complexity of changes that can be applied to a custom list, it's best to have the users confirm their changes with a deliberate save action.
Thus, when  a user is clicking to go back from editing a custom list and the list has not been saved yet, the user should be prompted if they want to discard their changes or to go back to editing.
We also need to take menu navigation (long press on back button) into consideration by enforcing the same behaviour when eg. the user tries to navigate directly from add locations view to the list of custom lists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6079)
> Intercept back button when leaving an unsaved custom list

- ios/MullvadVPN/Coordinators/CustomLists/CustomListCellConfiguration.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
We must limit the name of the name of a custom list to 30 UTF-8 characters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6131)
> Limit the name of a custom list to 30 characters

- CHANGELOG.md
- talpid-core/src/dns/macos.rs
Also, add tests for the macOS DNS monitor.
Fix DES-823.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6130)
> Restore DNS properly when using custom DNS

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/TwoRowCell.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6132)
> Fix overflow & max lines for custom list name

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/data/DummyRelayItems.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListAction.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListResult.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/CustomListNameTextField.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/CustomListExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItem.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/CustomListsRepository.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/customlists/CustomListActionUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CreateCustomListDialogViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditCustomListNameDialogViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/repository/CustomListsRepositoryTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/CustomListActionUseCaseTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/EditCustomListViewModelTest.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/model/CustomListName.kt
This PR limits the CustomListName to 30 characters and trims the name of white spaces.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6134)
> Trim custom list name and limit to 30 characters

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/PaymentUseCase.kt
This is to reduce the flickering in the ui.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6084)
> Show loading states in purchasing flow an extra minimum amount of time

- ios/MullvadLogging/Date+LogFormat.swift
- ios/MullvadLogging/LogRotation.swift
- ios/MullvadLogging/Logging.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift
- ios/MullvadVPNTests/LogRotationTests.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/Shared/ApplicationConfiguration.swift
Currently we only keep one .old.log, meaning we have the current log and the previous log. The logs are rotated on every app/process start, which is often on iOS. It would really help debugging thing if we had logs a bit further back in time.
We should therefore improve the current state by keeping as many logs as our filesystem budget allows for, eg.:
- never have more than 5MB of log files of any one type (application or packet tunnel)
- never have any single log file be larger than 500KB
Instead of suffixing log files with an .old.log when they're rotated, all log files should be named $loggingTarget.$currentDate.log, eg. PacketTunnel.2024.03.03-21:32:01.log.
- - - …
> Change log rotation to a quota based system

- gui/src/renderer/components/select-location/ScrollPositionContext.tsx
This PR enforces the stored scroll position when navigating back to the select location view. The behavior before this PR was that the select location view would scroll to the currently selected item when navigating back from either the filter view or the custom bridge view. This PR prevents that by suppressing that logic for `POP` navigations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6129)
> Prevent SelectLocation view from reseting scroll position on back navigation

- android/lib/resource/src/main/res/values-da/strings.xml
- android/lib/resource/src/main/res/values-de/strings.xml
- android/lib/resource/src/main/res/values-es/strings.xml
- android/lib/resource/src/main/res/values-fi/strings.xml
- android/lib/resource/src/main/res/values-fr/strings.xml
- android/lib/resource/src/main/res/values-it/strings.xml
- android/lib/resource/src/main/res/values-ja/strings.xml
- android/lib/resource/src/main/res/values-ko/strings.xml
- android/lib/resource/src/main/res/values-my/strings.xml
- android/lib/resource/src/main/res/values-nb/strings.xml
- android/lib/resource/src/main/res/values-nl/strings.xml
- android/lib/resource/src/main/res/values-pl/strings.xml
- android/lib/resource/src/main/res/values-pt/strings.xml
- android/lib/resource/src/main/res/values-ru/strings.xml
- android/lib/resource/src/main/res/values-sv/strings.xml
- android/lib/resource/src/main/res/values-th/strings.xml
- android/lib/resource/src/main/res/values-tr/strings.xml
- android/lib/resource/src/main/res/values-zh-rCN/strings.xml
- android/lib/resource/src/main/res/values-zh-rTW/strings.xml
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
This PR aims to align the server IP override title with the desktop app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6140)
> Align server IP override title with desktop

- ios/MullvadLogging/LogFileOutputStream.swift
- ios/MullvadLogging/Logging.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPNTests/LoggingTests.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
This PR adds a header line to the start of each log file at creation time; this contains the product version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6101)
> Add app version to start of each log file

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/data/DummyRelayItems.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditCustomListScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/PreviewData.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItem.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/RelayListUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/customlists/CustomListActionUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/relaylist/RelayNameComparatorTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/CustomListActionUseCaseTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt
This is to avoid unexpected behavior. The locations are not shown in the select location screen, to align ux with desktop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6135)
> Show all locations for custom lists in edit locations and detail view

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/version_check.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6119)
> Make sure to query app version every 24 hours

- ios/MullvadLogging/Logging.swift
There's a small bug in the log rotation. We should fix this before the release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6143)
> Remove logs older than 7 days, instead all of them

- mullvad-daemon/src/custom_list.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/settings/mod.rs
- mullvad-management-interface/src/lib.rs
- mullvad-types/src/custom_list.rs
I've gone and added a limitation on the length of the name of a custom list to 30 UTF-8 graphemes. And accidentally also reworked how custom lists are saved. Feel free to dismiss the changes in their entirety because of that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6141)
> Limit the size of custom list names to 30 graphemes

- Cargo.lock
- talpid-core/Cargo.toml
The patch for handling shut down sockets is included, so let's dispense with the git dependency.
Fix DES-813.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6155)
> Bump hickory-dns version to 0.24.1

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt
Ensure that when adding a parent of an already existing item in a custom list we remove the descendants. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6156)
> Fix duplicate entries when adding through bottom sheet

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
- android/lib/resource/src/main/res/drawable/ic_remove.xml
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
Adds a custom list sheet for the direct children of the custom list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6157)
> Add delete custom list entry bottom sheet

- gui/locales/messages.pot
- gui/src/renderer/components/EditCustomBridge.tsx
- gui/src/renderer/components/OpenVpnSettings.tsx
- gui/src/renderer/components/cell/Selector.tsx
- gui/src/renderer/components/select-location/SpecialLocationList.tsx
- gui/src/renderer/components/select-location/select-location-hooks.ts
- gui/test/e2e/installed/state-dependent/custom-bridge.spec.ts
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/ui.rs
This PR adds tests for the custom bridge GUI. When implementing the tests I also noticed that the bridge type wasn't set to normal when "Automatic was selected". This has also been fixed in this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6136)
> Add tests for custom bridge GUI

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt
Before we showed the tunnel state colors, according to the design we should only show the blue colors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6159)
> Only show blue top bar in the welcome screen

- mullvad-api/src/lib.rs
- mullvad-api/src/relay_list.rs
- mullvad-cli/src/cmds/api_access.rs
- mullvad-cli/src/cmds/proxies.rs
- mullvad-daemon/src/api.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/migrations/v1.rs
- mullvad-management-interface/src/client.rs
- mullvad-management-interface/src/types/conversions/access_method.rs
- mullvad-relay-selector/src/lib.rs
- mullvad-relay-selector/src/relay_selector/helpers.rs
- mullvad-relay-selector/src/relay_selector/mod.rs
- mullvad-types/src/access_method.rs
- mullvad-types/src/constraints/mod.rs
- mullvad-types/src/location.rs
- talpid-routing/src/lib.rs
- talpid-routing/src/windows/default_route_monitor.rs
- talpid-routing/src/windows/mod.rs
- talpid-types/src/net/proxy.rs
- talpid-wireguard/src/wireguard_nt/mod.rs
I ran `cargo doc` and fixed as many broken links as I could find.
Fixes DES-899.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6160)
> Fix broken links in rustdocs

- test/test-manager/src/tests/install.rs
This PR limits the execution time of `test_installation_idempotency`. We've had some issues with it where it got stuck waiting for a daemon state that would never arrive, thus halting the test framework execution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6162)
> Limit execution of `test_installation_idempotency`

- Cargo.lock
- test/Cargo.lock
https://github.com/mullvad/mullvadvpn-app/actions/runs/8763182344
Reported CVE against rustls. We are not vulnerable since we only use rustls via tokio-rustls which do not call complete_io, but we should still always upgrade instead of ignore reported issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6167)
> Upgrade rustls to avoid RUSTSEC-2024-0336

- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/version_check.rs
- talpid-time/Cargo.toml
- talpid-time/src/lib.rs
Fix DES-870.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6153)
> Add tests for version checker

- CHANGELOG.md
- build.sh
- dist-assets/pkg-scripts/postinstall
- dist-assets/pkg-scripts/preinstall
- gui/package-lock.json
- gui/package.json
- gui/tasks/distribution.js
This PR contains dependency updates for packages with known vulnerabilities, most of them were fixed by just running `npm audit fix`, but `electron-builder` had to be updated manually.
Most of the vulnerabilities doesn't affect our app, but the one in the dependency tree of `electron-builder` does. It enables privilege escelation on Windows by utilizing the following vulnerability in the installer: https://github.com/advisories/GHSA-r4pf-3v7r-hh55
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6166)
> Update Electron app dependencies with known vulnerabilities

- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift
Currently, the iPad location selection view doesn't unmark previously selected locations when a user selects a new location.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6174)
> Fix iPad location selection entries not being unmarked as selected

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/Coordinators/CustomLists/AddLocationsViewController.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListCellConfiguration.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift
- ios/MullvadVPN/Coordinators/CustomLists/ListCustomListViewController.swift
- ios/MullvadVPN/Coordinators/LocationCoordinator.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationSectionHeaderView.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift
- ios/MullvadVPNUITests/CustomListsTests.swift
- ios/MullvadVPNUITests/Pages/CustomListPage.swift
- ios/MullvadVPNUITests/Pages/EditCustomListLocationsPage.swift
- ios/MullvadVPNUITests/Pages/ListCustomListsPage.swift
- ios/MullvadVPNUITests/Pages/Page.swift
- ios/MullvadVPNUITests/Pages/SelectLocationPage.swift
- ios/MullvadVPNUITests/XCUIElementQuery+Extensions.swift
This PR adds support for writing UI Tests for custom lists.
As this is a rather large feature, this PR only adds a simple, single test case for the moment, creating a custom list, and verify that it still exists.
This PR also disables animations in the application for all UI Tests scenarios, and adds a new shorthand syntax for accessing elements from UITests.
More refactor to come later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6148)
> Add UITest for creating a custom list Part 1

- gui/src/main/daemon-rpc.ts
Whenever the app returns from suspend mode, it throws away old `ManagementServiceClient`s, but `ManagementServiceClient.waitForReady` is still resolved/rejected for the older clients. This results in the daemon being spammed with requests when it finally reconnects.
Fix DES-808.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6179)
> Ignore `waitForReady` for stale clients

- talpid-wireguard/src/lib.rs
- talpid-wireguard/src/wireguard_nt/mod.rs
- wireguard-go-rs/Cargo.toml
- wireguard-go-rs/src/lib.rs
This PR also drive-by fixes the `wireguard-go-rs` crate messing up compilation of the app on Windows :sweat_smile:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6200)
> Enable constant packet size for entry peer

- test/Cargo.lock
Seems like this version has been yanked. Apparently, downgrading helps. I chose to do that since that's the same version that's used in the app repo.
See https://github.com/mullvad/mullvadvpn-app/actions/runs/8894943512/job/24424260453?pr=5844
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6201)
> Fixed yanked dependency in test workspace

- gui/src/renderer/components/WireguardSettings.tsx
- mullvad-cli/src/cmds/relay.rs
- mullvad-cli/src/cmds/tunnel.rs
- mullvad-cli/src/format.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-management-interface/src/client.rs
- mullvad-management-interface/src/types/conversions/custom_tunnel.rs
- mullvad-management-interface/src/types/conversions/net.rs
- mullvad-management-interface/src/types/conversions/settings.rs
- mullvad-management-interface/src/types/conversions/wireguard.rs
- mullvad-relay-selector/src/relay_selector/detailer.rs
- mullvad-types/src/wireguard.rs
- talpid-types/src/net/mod.rs
- talpid-types/src/net/wireguard.rs
- test/test-manager/src/tests/dns.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/tunnel_state.rs
*Note that there is a typo in the branch name, please ignore that*
To make the review process easier, this first PR just merges the changes needed to enable DAITA in the CLI, GUI and settings.
Fixes DES-843 and DES-844
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6184)
> Enable DAITA settings on linux

- test/ci-runtests.sh
The previous code was trying to be too clever and incorrectly deleted packages in some cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6207)
> Simplify cleanup of testing CI cache

- CHANGELOG.md
- talpid-core/src/offline/linux.rs
- talpid-core/src/offline/mod.rs
- talpid-core/src/tunnel_state_machine/mod.rs
Moreover, the daemon will no longer refuse to start when the offline monitor cannot be initialized.
Fix DES-948.
Fix #6198.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6210)
> Fix daemon not starting with IPv6 disabled

- Cargo.lock
The previous version was yanked due to a performance regression in `pest`, which seems to be used indirectly for parsing shadowsocks JSON configs. That's not something we do, so this does not affect the app in any way.
See:
https://github.com/mullvad/mullvadvpn-app/actions/runs/8965105119/job/24617974511?pr=6210
https://github.com/pest-parser/pest/issues/1009
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6223)
> Bump pest to 2.7.10

- ios/MullvadLogging/CustomFormatLogHandler.swift
- ios/MullvadLogging/Date+LogFormat.swift
- ios/MullvadLogging/LogFileOutputStream.swift
- ios/MullvadLogging/LogRotation.swift
- ios/MullvadLogging/Logging.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift
- ios/MullvadVPN/StorePaymentManager/SendStoreReceiptOperation.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift
- ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift
- ios/MullvadVPNTests/MullvadLogging/LoggingTests.swift
- ios/MullvadVPNUITests/RelayTests.swift
- ios/Shared/ApplicationConfiguration.swift
We should limit log files to not be larger than a certain threshold (currently 16kB) when writing to disk. If limit is exceeded, create a new file with a "_<partial count>" suffix and keep writing to it instead. Repeat if necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6151)
> Ensure log file sizes stay below a certain threshold

- ios/MullvadSettings/CustomListRepository.swift
List names should have their trailing and leading whitespace removed when they are saved. Trailing and leading whitespace should also be ignored when checking if a list already exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6193)
> Trim whitespace from list names on save

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/Account/AccountDeviceRow.swift
- ios/MullvadVPN/View controllers/RelayFilter/RelayFilterCellFactory.swift
- ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift
- ios/MullvadVPN/View controllers/Settings/SettingsHeaderView.swift
- ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift
- ios/MullvadVPNUITests/ConnectivityTests.swift
- ios/MullvadVPNUITests/CustomListsTests.swift
- ios/MullvadVPNUITests/Pages/AccountPage.swift
- ios/MullvadVPNUITests/Pages/SelectLocationFilterPage.swift
- ios/MullvadVPNUITests/Pages/SelectLocationPage.swift
Implemented test verifying that API can still be reached when the app is in blocked state. A change affected the screenshot test so did a tiny modification of it as well.
To test the changes in this PR run `testAPIReachableWhenBlocked` under `ConnectivityTests`. Also `testScreenshots` was affected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6154)
> Add iOS test verifying API can be reached in blocked state

- talpid-wireguard/build.rs
This fixes builds failing on nightly rustc due to [`unexpected_cfgs`](https://blog.rust-lang.org/2024/05/06/check-cfg.html). See, for example, https://github.com/mullvad/mullvadvpn-app/actions/runs/8970591493/job/24634481519
Fix DES-952.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6228)
> Fix nightly Rust build

- gui/src/renderer/components/cell/Label.tsx
When adding the DAITA toggle, the alignment on cell labels were incorrectly set to centered. This PR fixes that by just removing the CSS rule.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6230)
> Fix label alignment

- android/CHANGELOG.md
- android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
- talpid-tunnel/src/tun_provider/android/mod.rs
This PR aims to fix DNS leaks in blocking states or when no valid DNS has been configured due to an underlying OS issue. In these cases a dummy DNS will be set to prevent leaks.
More information on this issue:
https://issuetracker.google.com/issues/337961996
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6233)
> Prevent DNS leaks in blocking states or when no valid DNS has been configured

- gui/src/renderer/components/ConnectionPanel.tsx
Due to an error the hostname line shows as "<exit> via undefined" when using a custom bridge. This is now fixed by removing old code that shouldn't be needed anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6183)
> Fix hostname line for custom bridge

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/Coordinators/LocationCoordinator.swift
- ios/MullvadVPN/UI appearance/UIColor+Palette.swift
- ios/MullvadVPN/View controllers/RelayFilter/RelayFilterView.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift
The wrapper should have a segmented control. The child will be updated through the wrapper, keeping most of the previous implementation intact.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6181)
> Add a new container view to wrap the whole location selection

- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift
- ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift
- ios/MullvadVPNTests/MullvadLogging/LoggingTests.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/Shared/ApplicationConfiguration.swift
Some problem reports get duplicated when displaying logs in the problem report view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6235)
> Fix problem report logs being duplicated

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/Coordinators/AccountCoordinator.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentConfiguration.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentView.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Common/SocksSectionHandler.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsCellConfiguration.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsViewController.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodTestingStatusCellContentView.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewController.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Pickers/AccessMethodProtocolPicker.swift
- ios/MullvadVPN/View controllers/Login/LoginViewController.swift
- ios/MullvadVPN/Views/CustomSwitchContainer.swift
- ios/MullvadVPNUITests/ConnectivityTests.swift
- ios/MullvadVPNUITests/Pages/APIAccessPage.swift
- ios/MullvadVPNUITests/Pages/AccountPage.swift
- ios/MullvadVPNUITests/Pages/AddAccessMethodPage.swift
- ios/MullvadVPNUITests/Pages/EditAccessMethodPage.swift
- ios/MullvadVPNUITests/Pages/LoginPage.swift
- ios/MullvadVPNUITests/Pages/Page.swift
- ios/MullvadVPNUITests/Pages/SettingsPage.swift
- ios/MullvadVPNUITests/Test base classes/BaseUITestCase.swift
- ios/MullvadVPNUITests/XCUIElement+Extensions.swift
Implemented test verifying that app is still functioning and can connect to a relay when the API is down. The simulation of API being down is not optimal. We have discussed it and decided to go for this way of simulating it for now. Might be improved in the future.
To test the changes run the test `testAppStillFunctioningWhenAPIDown` under `ConnectivityTests`. To simulate the the API being down all access methods are disabled and then a dummy access method is created to make API unreachable.
Duo to the extra setup and teardown steps the test function violates `function_body_length`(function body shouldn't be over 50 lines of code) so it is disabled for this test function.
- - - …
> Add iOS test making sure app functioning when API is down

- ios/MullvadMockData/MullvadMockData.h
- ios/MullvadMockData/MullvadREST/APIProxy+Stubs.swift
- ios/MullvadMockData/MullvadREST/AccessTokenManager+Stubs.swift
- ios/MullvadMockData/MullvadREST/AccountsProxy+Stubs.swift
- ios/MullvadMockData/MullvadREST/DevicesProxy+Stubs.swift
- ios/MullvadMockData/MullvadREST/MockProxyFactory.swift
- ios/MullvadMockData/MullvadREST/RESTRequestExecutor+Stubs.swift
- ios/MullvadMockData/MullvadTypes/AccountMock.swift
- ios/MullvadMockData/MullvadTypes/DeviceMock.swift
- ios/MullvadREST/ApiHandlers/RESTProxyFactory.swift
- ios/MullvadRESTTests/Mocks/TimeServerProxy.swift
- ios/MullvadRESTTests/RequestExecutorTests.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPNScreenshots/MullvadVPNScreenshots.swift
- ios/MullvadVPNTests/MullvadVPN/PacketTunnel/DeviceCheck/DeviceCheckOperationTests.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift
- ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift
- ios/Shared/LaunchArguments.swift
This PR introduces mocking data for snapshot testing with the following key assumptions:
- Login button must just proceed to the next screen
- The account view must refresh instantly and display `37 days` of remaining time.
- The device name is set to `Secure Mole`.
- The app is always connected to `se-got-wg-101`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6227)
> Mock data for screenshot test

- ios/MullvadSettings/AccessMethodRepository.swift
- ios/MullvadSettings/CustomListRepository.swift
- ios/MullvadSettings/PersistentAccessMethod.swift
- ios/MullvadTypes/NameInputFormatter.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Coordinators/CustomLists/CustomListCellConfiguration.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListDataSourceConfiguration.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListValidationError.swift
- ios/MullvadVPN/Coordinators/CustomLists/CustomListViewController.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/MethodSettings/MethodSettingsCellConfiguration.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodValidationError.swift
- ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel+Persistent.swift
Currently, API connection method names are neither trimmed nor validated appropriately. And custom list names are also validated by the text entry and not the data object itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6247)
> Fix user input string validation

- gui/src/renderer/components/SmallButton.tsx
This PR fixes the previous incorrect handling of text overflow in the `SmallButton` component. If the text doesn't fit in a button that takes up half of the width, it will now expand to a full size button. If that isn't enough either, it will wrap the text to use multiple rows.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6236)
> Fix handling of SmallButton overflow

- ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationNode.swift
- ios/MullvadVPNTests/MullvadVPN/View controllers/SelectLocation/LocationNodeTests.swift
Small cleanup in LocationNode. We don't need the subclasses for country, city and hostname, so they have been removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6250)
> Remove some unnecessary LocationNode subclasses

- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
This PR is about removing the tunnel state from the task removal lifecycle log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6252)
> Remove tunnel state from lifecycle log

- ios/MullvadVPN/UI appearance/UIColor+Palette.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationSectionHeaderView.swift
When we added custom lists we also added a title list item (All locations) which made the countries/cities/servers in the location view move down one step in the hierarchy. So we had to add a new color (Blue10%). This PR updates all related colors to their correct values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6246)
> Fix cell colors in location view

- mullvad-version/build.rs
Fixes DES-950
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6211)
> Don't rebuild daemon every time new git refs are fetched

- test/test-manager/src/vm/qemu.rs
Fix some timeouts seen recently on Windows 10.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6260)
> Increase start/boot timeout for testing VMs

- .github/workflows/desktop-e2e.yml
- .github/workflows/frontend.yml
- .github/workflows/translations.yml
- .gitignore
- gui/.gitignore
- gui/package-lock.json
- gui/package.json
- gui/scripts/build-test-executable.sh
- gui/standalone-tests.sea.json
- gui/standalone-tests.ts
Since the latter is deprecated.
Fix DES-949.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6242)
> Use SEA for test executable instead of pkg

- CHANGELOG.md
- gui/package-lock.json
- gui/package.json
Here are the changelogs for versions 29 and 30:
https://github.com/electron/electron/releases/tag/v30.0.0
https://github.com/electron/electron/releases/tag/v29.0.0 
Fix DES-867.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6253)
> Update Electron to version 30

- gui/package-lock.json
- gui/package.json
When switching over to Node SEA for building the test executable (https://github.com/mullvad/mullvadvpn-app/pull/6242) we forgot to add `postject` as a dev dependency. This causes `buildserver-build.sh` to prompt and wait for the user to accept installing postject when running `npx postject ...`. This PR just adds postject as a dependency to resolve this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6262)
> Add postject dependency

- building/Dockerfile
This PR adds the `make` tool to the Linux container image, which will be used when building `libmaybenot.a`, which in turn will be used to build `wireguard-go` with DAITA support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6256)
> Add `make` to container image

- test/docs/BUILD_OS_IMAGE.md
Mention that the `test-runner` and standalone e2e test executable should be excluded from being flagged by Windows Security. We have experienced some false positives lately, and we do indeed trust what we upload to the test runner VMs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6275)
> Update documentation on how to add new Windows VMs

- dist-assets/linux/mullvad-gui-launcher.sh
https://github.com/YaLTeR/niri/
niri doesn't come with xwayland by default, so enabling wayland is required for the gui to work
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6282)
> Add niri as a supported wayland compositor

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPNTests/MullvadVPN/PacketTunnelCore/PacketTunnelActorReducerTests.swift
- ios/PacketTunnelCore/Actor/EventChannel.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+ConnectionMonitoring.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+NetworkReachability.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+Public.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift
- ios/PacketTunnelCoreTests/EventChannelTests.swift
This is a refactoring of the PacketTunnelActor state machine, which splits the state processing logic into two stages: a stateless function (a Reducer) which takes incoming events (Events) and existing state and produces updated state and zero or more Effect values, and stateful code within the actor that executes the Effect values, producing effects. This is an instance of the Reducer architecture, and has the effect of making the state transition logic purely stateless and allowing it to be tested and reasoned about without concern for side effects.
As part of this, the `Command` type has been renamed to `Effect`, for accuracy: a value of this type can represent not only a user command (such as `.start`, `.stop` or `.reconnect`) but non-user events such as key rotations and network …
> Refactor PacketTunnelActor to use a Reducer

- ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewController.swift
`ListAccessMethodViewController`'s data source was getting out of sync with `fetchedItems`, which was caused by reloading items (useful when existing items have changed, catastrophic for when items have been removed from the middle of the list). Only reloading if the number of items is the same fixes the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6287)
> IOS-699: fix crash on deletion of access method

- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportReviewViewController.swift
- ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController.swift
The problem report view freezes when pressing the "view app logs" button, if many logs need to be consolidated. We should add a spinner to let the user know that everything's alright.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6255)
> Show spinner when consolidating logs for problem reports

- .github/workflows/git-commit-message-style.yml
This PR adds the word "obfuscate" to the list of allowed verbs in commit messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6298)
> Add the word obfuscate to the list of allowed verbs

- gui/locales/messages.pot
- gui/src/main/daemon-rpc.ts
- gui/src/main/user-interface.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/shared/daemon-rpc-types.ts
- gui/src/shared/ipc-schema.ts
- gui/src/shared/notifications/error.ts
- gui/src/shared/notifications/notification.ts
Split tunneling on macOS requires the app to have "Full Disk Access". This PR adds an error informing the user when it is off and a troubleshoot dialog with instructions for how to enable it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6301)
> Show error and troubleshoot dialog when lacking full disk access

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
Fix an issue where we forgot to introduce DeviceRepository in AppModule resulting in missing dep when using a notification.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6305)
> Fix TunnelStateProvider missing dep

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialogTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DnsDialogViewModel.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
Fixes bug where one would remove based on the current text entry instead of the index.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6308)
> Remove by custom DNS by index

- mullvad-daemon/src/migrations/v9.rs
The test was effectively disabled because of an invalid cfg. It was caught thanks to `cargo:rustc-check-cfg`.
I also removed the version number test. It was failing since we don't actually increment the version yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6311)
> Enable v9 migration test

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialogTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DnsDialog.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DnsDialogViewModel.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
Blocked by other PR, up for opinions about how we solve the prevention of the Error appearing on re-rendering with new data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6309)
> Fix DnsDialog shortly showing error after adding new DNS entry

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This PR updates the checked package dependency to commit `15242e1698fc45261285d7417ed2cd5130d7332e` on mullvad's wireguard fork.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6321)
> Update package dependency to include all routes in network settings

- gui/src/main/index.ts
I noticed that it is not possible to remove manually added applications in macOS split tunneling. This is because the path that is saved to `gui_settings.json` is the application bundle path and when we remove it we try to remove the executable path. This PR changes the behavior to save the executable path in `gui_settings.json` instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6316)
> Save executable path instead of application bundle path for manually added macOS split tunneling applications

- .github/workflows/ios-screenshots-tests.yml
When we changed the screenshot test to run in a different target, we forgot to update the screenshot tests to use the configuration used by said target. 
This PR fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6327)
> Add the UITests xcconfig file when running screenshot tests

- android/config/dependency-check-suppression.xml
- android/test/test-suppression.xml
This PR aims to update our OWASP audit suppression rules due to some new being reported and some being outdated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6328)
> Update android suppressions

- ios/Configurations/Api.xcconfig.template
- ios/MullvadVPN/GeneralAPIs/OutgoingConnectionProxy.swift
- ios/MullvadVPN/SceneDelegate.swift
- ios/MullvadVPN/Supporting Files/Info.plist
- ios/MullvadVPNTests/MullvadVPN/GeneralAPIs/OutgoingConnectionProxyTests.swift
- ios/PacketTunnel/Info.plist
- ios/Shared/ApplicationConfiguration.swift
This PR removes hard coded mentions of `mullvad.net` to replace them by a hostname defined in `Api.xcconfig` instead.
This enables conncheck (`am.i.mullvad.net`) working on both debug and staging environments.
@niklasberglund : I've tagged you because I explicitly didn't touch the `mullvad.net` mentions in the UITests (`Networking.swift`). 
Let's discuss this to see if we want to make changes there as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6302)
> Fix conncheck to work on staging environment

- talpid-time/Cargo.toml
This PR fixes `cargo udeps` which started to detect some unused dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6334)
> Fix `cargo udeps`

- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatus.swift
- ios/MullvadVPN/Coordinators/Settings/IPOverride/IPOverrideStatusView.swift
- ios/MullvadVPN/UI appearance/UIColor+Palette.swift
- ios/MullvadVPN/View controllers/Account/AccountViewController.swift
- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
- ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift
- ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift
Many small bugs were squashed:
- [IOS-706 : Can use the `Done` button to escape from the account view during payment](https://linear.app/mullvad/issue/IOS-706/can-use-the-done-button-to-escape-from-the-account-view-whilst-making)
- [IOS-126 : Change and add text in Content blockers informational dialog](https://linear.app/mullvad/issue/IOS-126/change-and-add-text-in-content-blockers-informational-dialog)
- [IOS-697 : Truncated text on successful import of Server IP override](https://linear.app/mullvad/issue/IOS-697/truncated-text-on-successful-import-of-server-ip-override)
- [IOS-709 : Colours fade too much when testing API access methods](https://linear.app/mullvad/issue/IOS-709/colours-fade-too-much-when-testing-api-access-methods)
- [IOS-124 : Remove disable text when DNS content …
> Fix many small bugs

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
- android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/DeviceRepository.kt
This PR aims to fix an issue where the UI doesn't trigger automatic device updates/refresh. Instead, the app would rely on other mechanisms such as the tunnel connection or purchase flows to update/refresh the device. The consequence of this is that users could end up in strange scenarios such as a device being revoked immediately after purchasing time.
The new behavior is that we update/refresh the device similar to how we handle purchase verification as part of a few screens. This is a bit similar to how it's handled on desktop where they are even more aggressive on updating/refresh the device. On desktop it's done every time a gRPC connection is established.
- - - …
> Fix missing device refresh

- ios/MullvadREST/Transport/Shadowsocks/ShadowsocksLoader.swift
- ios/MullvadREST/Transport/Shadowsocks/ShadowsocksRelaySelector.swift
- ios/MullvadSettings/MultihopSettings.swift
- ios/MullvadSettings/TunnelSettingsUpdate.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift
- ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift
- ios/MullvadVPNTests/MullvadREST/Shadowsocks/ShadowsocksLoaderTests.swift
- ios/MullvadVPNUITests/Pages/MultihopPromptAlert.swift
- ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift
- ios/MullvadVPNUITests/SettingsMigrationTests.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnel/PacketTunnelProvider/RelaySelectorWrapper.swift
- ios/PacketTunnelCore/Actor/ObservedState+Extensions.swift
- ios/PacketTunnelCore/Actor/Protocols/SettingsReaderProtocol.swift
- ios/PacketTunnelCore/Actor/TunnelSettingsManager.swift
- ios/PacketTunnelCoreTests/TunnelSettingsManagerTests.swift
This PR allows users to change the multi-hop state in the settings view.
<table style="width:50%">
<tr>
<th>Before</th>
<th>After</th> 
</tr>
<tr>
<td><img src = "https://github.com/mullvad/mullvadvpn-app/assets/129863230/b5f560ca-9086-43b8-9297-55c9aa2dfafc" width = 320  height = 720 /></td>
<td>
/>
</td>
</tr>
</table>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6335)
> Add multi-hop toggle to settings view

- android/CHANGELOG.md
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt
- android/lib/resource/src/main/res/values-da/strings.xml
- android/lib/resource/src/main/res/values-de/strings.xml
- android/lib/resource/src/main/res/values-es/strings.xml
- android/lib/resource/src/main/res/values-fi/strings.xml
- android/lib/resource/src/main/res/values-fr/strings.xml
- android/lib/resource/src/main/res/values-it/strings.xml
- android/lib/resource/src/main/res/values-ja/strings.xml
- android/lib/resource/src/main/res/values-ko/strings.xml
- android/lib/resource/src/main/res/values-my/strings.xml
- android/lib/resource/src/main/res/values-nb/strings.xml
- android/lib/resource/src/main/res/values-nl/strings.xml
- android/lib/resource/src/main/res/values-pl/strings.xml
- android/lib/resource/src/main/res/values-pt/strings.xml
- android/lib/resource/src/main/res/values-ru/strings.xml
- android/lib/resource/src/main/res/values-sv/strings.xml
- android/lib/resource/src/main/res/values-th/strings.xml
- android/lib/resource/src/main/res/values-tr/strings.xml
- android/lib/resource/src/main/res/values-zh-rCN/strings.xml
- android/lib/resource/src/main/res/values-zh-rTW/strings.xml
- android/lib/resource/src/main/res/values/strings.xml
- android/lib/resource/src/main/res/values/strings_non_translatable.xml
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/constant/BuildConstant.kt
- gui/locales/messages.pot
This PR aims to clarify the lockdown information in the in-app guide.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6293)
> Clarify lockdown limitations in guide

- mullvad-jni/Cargo.toml
- mullvad-nsis/Cargo.toml
`cargo` is warning that `crate_type` is deprecated. It's trivial to fix since it just has to be changed to `crate-type`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6353)
> Change crate_type into crate-type since the first is deprecated

- talpid-dbus/src/network_manager.rs
- talpid-dbus/src/systemd_resolved.rs
The aim is for the never type to be stabilized in Rust 2024 (:partying_face: YAY, finally!). But for that to happen some of the current automatic fallback from never (`!`) to unit (`()`) must be changed. And as a result any code relying on the current fallback to unit behavior must be changed to not rely on this automatic fallback, but rather be explicit unit type.
This PR fixes the two instances we had of this automatic fallback, as pointed out by the latest nightly compiler.
The tracking issue for never types: https://github.com/rust-lang/rust/issues/123748
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6352)
> Adapt to new never type fallback by explicitly stating unit types

- README.md
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/PathConstant.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/AppModule.kt
- android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/constant/DiConstant.kt
- android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/constant/PathConstant.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/main.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-jni/Cargo.toml
- mullvad-jni/src/lib.rs
- mullvad-management-interface/src/client.rs
- mullvad-management-interface/src/lib.rs
- mullvad-paths/Cargo.toml
- mullvad-paths/src/cache.rs
- mullvad-paths/src/lib.rs
- mullvad-paths/src/logs.rs
- mullvad-paths/src/resources.rs
- mullvad-paths/src/rpc_socket.rs
- mullvad-paths/src/settings.rs
- mullvad-problem-report/src/lib.rs
Remove `APP_PATH` from `mullvad-paths` on Android since it should not be a constant value. Instead, it is passed down from the Android app startup. As it turns out, it is really ever used for pointing to the RPC socket in use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6342)
> Get data directory value at app startup (Android)

- .github/workflows/git-commit-message-style.yml
- talpid-core/src/split_tunnel/macos/tun.rs
Fix issues related to split tunneling, primarily these:
* Use of blocking I/O in async context.
* Race condition involving an abort channel. This could cause the tunnel monitor to get stuck.
This does not affect any released version of the app.
Close DES-1036.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6359)
> Fix connecting issue on macOS

- ios/MullvadPostQuantum/PostQuantumKeyNegotiator.swift
- ios/MullvadPostQuantum/talpid-tunnel-config-client/include/talpid_tunnel_config_client.h
- ios/MullvadPostQuantumTests/MullvadPostQuantum+Stubs.swift
- ios/MullvadPostQuantumTests/PostQuantumKeyExchangeActorTests.swift
- ios/MullvadREST/RetryStrategy/RetryStrategy.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadPostQuantumTests.xcscheme
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnel/PostQuantumKeyExchangeActor.swift
- ios/PacketTunnelCore/NEPacketTunnelProvider+Extensions.swift
- ios/TestPlans/MullvadVPNApp.xctestplan
- ios/TestPlans/MullvadVPNCI.xctestplan
- talpid-tunnel-config-client/src/ios_ffi/ios_runtime.rs
- talpid-tunnel-config-client/src/ios_ffi/ios_tcp_connection.rs
- talpid-tunnel-config-client/src/ios_ffi/mod.rs
This PR adds an exponential backoff timeout when negotiating post quantum keys.
The timeout plays 2 important part :
- Trigger a reset of the key exchange process if the in-tunnel TCP connection does not become ready in time
- Trigger a reset of the key exchange process if it takes too long to exchange keys.
This PR was co-authored by @pinkisemils  and @buggmagnet
@MarkusPettersson98's approval is required for the rust side changes
@acb-mv's approval is required for the swift side changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6343)
> Add timeout to the tcp connection for the pq key negotiation ios 701

- .github/workflows/android-audit.yml
- android/scripts/update-lockfile.sh
This PR aims to add an action which ensure that the lockfile is in a clean state. It also makes it possible to run the lockfile script without `podman`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6361)
> Add action to ensure clean lockfile

- android/scripts/update-lockfile.sh
This PR aims to automatically use temp dirs in the lockfile script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6365)
> Use temp dirs in lockfile script

- .github/workflows/ios-screenshots-creation.yml
- .github/workflows/ios-screenshots-tests.yml
- ios/Configurations/Screenshots.xcconfig.template
- ios/Configurations/UITests.xcconfig.template
- ios/MullvadVPN/Supporting Files/Info.plist
- ios/MullvadVPNUITests/Networking/PartnerAPIClient.swift
- ios/MullvadVPNUITests/Pages/SelectLocationPage.swift
- ios/Snapfile
This PR addresses screenshot tests failing, especially after the staging PR was merged to main but they were also failing prior to that.
* Removed usage of partner API client for creating accounts
* Issue with ellipsis button again. There's a race condition even though there shouldn't be. Added a wait for the ellipsis button to show before tapping it.
* Removed `MULLVAD_ACCOUNT_TOKEN` which is no longer used
* Made screenshot tests workflow store Xcode test report as artefact,similar to end to end tests
* Specified simulator iOS version. Fastlane was defaulting to 17.0 without specifying a version, and the runner image have very few 17.0 simulators.
* Not producing screenshots for iPad as the tests do not support the iPad UI
- - - …
> Fix screenshot tests failing

- Cargo.lock
- test/Cargo.lock
Fix [RUSTSEC-2024-0344](https://rustsec.org/advisories/RUSTSEC-2024-0344) by bumping `curve25519-dalek` to the latest version.
> Timing variability of any kind is problematic when working with potentially secret values such as elliptic curve scalars, and such issues can potentially leak private keys and other secrets.
It doesn't appear to be problematic with respect to the app's threat model. An attacker would need local access to the machine.
Close DES-1049.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6383)
> Fix RUSTSEC-2024-0344

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6375)
> Add disconnect button to Welcome Screen

- Cargo.lock
- gui/tasks/distribution.js
- mullvad-daemon/build.rs
- talpid-wireguard/Cargo.toml
- wireguard-go-rs/Cargo.toml
- wireguard-go-rs/build-wireguard-go.sh
- wireguard-go-rs/build.rs
- wireguard-go-rs/src/lib.rs
Use `Cargo.toml` to link against `maybenot-ffi` on desktop. This solves the issue of LTO breaking when using a separate archive file, as well as some issues of some scripts failing due to `libwg.so` not being found.
Fix DES-1038.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6374)
> Link statically against libwg

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/main.rs
The cleanup in `Daemon::finalize` is at the wrong abstraction level, since `Daemon` is agnostic about how `EventListener` is implemented. It technically doesn't have to rely a UDS at all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6388)
> Move all UDS cleanup to `main`

- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/main/tunnel-state.ts
- mullvad-cli/src/format.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/client.rs
This PR fixes an issue where the `mullvad-daemon` would not automatically restart after the user had granted "Mullvad VPN" application Full Disk Access. This is needed to make split tunneling work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6381)
> Restart `mullvad-daemon` after user grants Full Disk Access (macOS)

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/ChangelogRepository.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/StringExtensions.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/repository/ChangelogRepositoryTest.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6389)
> Add support for bullets in changes file

- gui/test/e2e/installed/state-dependent/tunnel-state.spec.ts
After changing the default obfuscation value to "Auto", the `tunnel-state` test has started failing occasionally due to trying udp2tcp when failing to connect on the first try. This PR disables obfuscation during that test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6402)
> Disable obfuscation in WireGuard port GUI test

- gui/src/renderer/components/NotificationArea.tsx
- gui/test/e2e/mocked/notifications.spec.ts
This PR adds an e2e test to verify the output of notifications when an account is close to expire.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/3947)
> Add e2e test for account expiry notifications

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift
- ios/MullvadVPN/Coordinators/CustomLists/ListCustomListCoordinator.swift
- ios/MullvadVPN/Coordinators/LocationCoordinator.swift
- ios/MullvadVPN/UI appearance/UIColor+Palette.swift
- ios/MullvadVPN/View controllers/RelayFilter/RelayFilterView.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationDiffableDataSourceProtocol.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift
- ios/MullvadVPN/View controllers/SelectLocation/RelaySelection.swift
- ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift
This PR contains two closely related issues:
1. https://linear.app/mullvad/issue/IOS-631/update-view-model-when-switching-between-entry-and-exit-location
The view location selection view must be able to work with both entry and exit locations. If a user has selected a single relay as an entry, the user should not be able to select the same relay as an exit, and vice versa. Edge cases around countries/cities containing a single relay don't have to be accounted for.
2. https://linear.app/mullvad/issue/IOS-610/allow-selecting-entry-location
The user must be able to specify what locations should be used for the entry relay when multi-hop is enabled. The UI for this should follow the design from [IOS-504](https://linear.app/mullvad/issue/IOS-504/design-ui-for-toggling-multihop). 
The first …
> Update view model when switching between entry and exit location

- ios/MullvadMockData/Extensions/TimeInterval+Timeout.swift
- ios/MullvadPostQuantumTests/PostQuantumKeyExchangeActorTests.swift
- ios/MullvadRESTTests/HeadRequestTests.swift
- ios/MullvadRESTTests/RequestExecutorTests.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPNTests/MullvadSettings/MigrationManagerTests.swift
- ios/MullvadVPNTests/MullvadVPN/GeneralAPIs/OutgoingConnectionProxyTests.swift
- ios/MullvadVPNTests/MullvadVPN/PacketTunnel/DeviceCheck/DeviceCheckOperationTests.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/StartTunnelOperationTests.swift
- ios/MullvadVPNTests/MullvadVPN/View controllers/Tunnel/OutgoingConnectionServiceTests.swift
- ios/MullvadVPNUITests/Screenshots/SnapshotHelper.swift
- ios/OperationsTests/AsyncBlockOperationTests.swift
- ios/OperationsTests/AsyncResultBlockOperationTests.swift
- ios/OperationsTests/OperationConditionTests.swift
- ios/OperationsTests/OperationObserverTests.swift
- ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift
- ios/PacketTunnelCoreTests/EventChannelTests.swift
- ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
- ios/PacketTunnelCoreTests/PingerTests.swift
- ios/PacketTunnelCoreTests/TunnelMonitorTests.swift
- ios/PacketTunnelCoreTests/TunnelSettingsManagerTests.swift
After a discussion we came to the conclusion that 1 second timeout would not help us see if the unit tests ever enter a dead lock situation.
Having a 60 seconds timeout would point that out by having tests fail after 1 minute.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6398)
> Replace all maximum timeout values to 60 seconds

- gui/src/main/index.ts
This PR makes sure all devtools requests are allowed during development. This was forgotten about in https://github.com/mullvad/mullvadvpn-app/pull/6356.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6372)
> Allow requests to all development URI:s during development

- gui/scripts/README.md
This PR updates the readme in `gui/scripts` to reflect the changes made to the localization scripts in https://github.com/mullvad/mullvadvpn-app/pull/6241.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6370)
> Update README in gui/scripts

- talpid-routing/Cargo.toml
This PR removes an unused dependency in `talpid-routing`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6407)
> Remove unused `libc` dependency in `talpid-routing`

- .github/workflows/desktop-e2e.yml
- .github/workflows/rust-unused-dependencies.yml
- CHANGELOG.md
- gui/src/renderer/components/WireguardSettings.tsx
- gui/tasks/distribution.js
- mullvad-cli/build.rs
- mullvad-daemon/build.rs
- mullvad-management-interface/build.rs
- mullvad-relay-selector/build.rs
- mullvad-types/build.rs
- talpid-types/build.rs
- talpid-wireguard/build.rs
- test/test-manager/src/tests/dns.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/tunnel.rs
- test/test-manager/src/tests/tunnel_state.rs
- wireguard-go-rs/Cargo.toml
- wireguard-go-rs/build.rs
See #6408 for more details.
Fix DES-785.
Fix DES-784.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6410)
> Add DAITA on macOS

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/TunnelManager/Tunnel+Settings.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/TunnelManager/TunnelState+UI.swift
- ios/MullvadVPN/TunnelManager/TunnelState.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlViewModel.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
- ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift
- ios/PacketTunnelCore/Actor/StartOptions.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
This PR enables multi-hop tunneling support in Swift.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6378)
> Apply multi-hop settings into tunnel

- .github/workflows/ios-screenshots-tests.yml
- ios/Configurations/UITests.xcconfig.template
- ios/MullvadVPNUITests/Pages/Page.swift
- ios/Snapfile
Re-enable screenshots for iPad, since the iPad specific UI is now gone and screenshot tests should work on iPad again. The changes can be tested by running the iOS create screenshots workflow on this branch.
Also updated configuration so that `HAS_TIME_ACCOUNT_NUMBER` is properly set and partner API is not used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6403)
> Re-enable screenshots for iPad

- talpid-wireguard/src/config.rs
- talpid-wireguard/src/lib.rs
When PQ or DAITA is enabled, the firewall state is updated twice to allow only traffic to `ipv4_gateway` inside the tunnel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6416)
> Remove pointless firewall update

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/util/Effect.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6435)
> Fix duplicate navigateBack

- gui/src/renderer/components/select-location/CustomListDialogs.tsx
- gui/src/renderer/components/select-location/CustomLists.tsx
- mullvad-cli/src/cmds/custom_list.rs
Trim trailing and preceeding whitespace in custom list names in both Electron GUI and CLI.
Also enforce max 30 characters in CLI.
Only applies when creating/renaming custom lists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6425)
> Enforce max length and trim whitespace of custom list names

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/PacketTunnelCore/Pinger/ICMP.swift
- ios/PacketTunnelCore/Pinger/Pinger.swift
This moves `createICMPPacket` and `parseICMPResponse` out of the `Pinger` implementation to their own namespace (an instance-free struct named ICMP). This will be useful for reusing them in a new Pinger implementation that uses the IAN tunnel rather than `CFSocket`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6438)
> Move ICMP packet creation and parsing out of Pinger implementation

- .github/workflows/android-app.yml
- .github/workflows/daemon.yml
- .github/workflows/osv-scanner-pr.yml
- .github/workflows/osv-scanner-scheduled.yml
- .github/workflows/testframework.yml
- .github/workflows/translations.yml
- android/gradle/osv-scanner.toml
- gui/osv-scanner.toml
- gui/scripts/osv-scanner.toml
- osv-scanner.toml
- test/osv-scanner.toml
Adding (yet another) scanner for known vulnerabilities in our dependency tree(s). This one actually checks some places we have not looked at before.
Draft until we have figured out what lockfiles we want to check (if not all) and fixed or ignored all existing reported vulns.
The vulns it reports can be found here: https://github.com/mullvad/mullvadvpn-app/security/code-scanning?page=1&query=pr%3A6001+is%3Aopen
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6001)
> Add vulnerability scanning with OSV scanner

- ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationDiffableDataSourceProtocol.swift
- ios/MullvadVPN/View controllers/SelectLocation/RelaySelection.swift
When displaying either the entry or exit location lists, any location (country, city or relay) shouldn't be selectable if, after apply all other constraints, the location item resolves to a single candidate that is already selected by the entry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6455)
> Prevent user from selecting same entry and exit relay for multihop

- talpid-tunnel-config-client/examples/tuncfg-server.rs
- talpid-tunnel-config-client/proto/ephemeralpeer.proto
- talpid-tunnel-config-client/src/kyber.rs
We had not stated what exact version of the Kyber KEM we were using for the quantum-resistant tunnels. The dependency we rely on for the implementation ([`pqc_kyber`](https://crates.io/crates/pqc_kyber)) is also very vague on this point. This makes it near impossible to figure out what protocol spec we use just by looking at the app code. I synchronized with the relay software team just to make sure I got it right. We use round3 of Kyber. I figured it's very valuable to have this documented in the app as well. Important when we evaluate potential replacements for `pqc_kyber` (a nearly dead create we should probably swap from in the near future?)
- - - …
> Document that it is round3 of the Kyber KEM we are using

- .github/workflows/daemon.yml
- .github/workflows/testframework.yml
I noticed in #6469 that it triggered heavy Rust CI jobs. These should not be needed. So I went ahead and excluded the `ci/` dir from the list of files that trigger those jobs. However `ci/check-rust.sh`, is a dependency on the main CI job, so that is included again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6470)
> Exclude ci/ directory from triggering heavy Rust CI jobs

- ci/mullvad-browser/download-mullvad-browser.sh
A missing `-f` made the `ln` command exit with a `File exists` error. I don't think this script was ever tested with upgrades when the destination already existed :sweat_smile:
Except from crippling the download script from actually publishing new browsers, this also left a ton of temporary downloads in `/tmp/mullvad-browser-tmp-.....`. I fixed this my moving the cleanup to a signal trap. This means the cleanup code always run on script exit, even if it exits prematurely due to a failing command.
I took the opportunity to do two other minor cleanups of the scripts here also:
1. Stop `wget` from printing very verbose progress. This filled up the systemd logs. The progress is not needed.
2. Store the latest known browser artifacts in the script dir instead of `/tmp`. This keeps the data …
> Fix browser download script

- Cargo.lock
- test/Cargo.lock
The `cargo audit` CI job failed on its scheduled job and told me `bytes` is yanked. So this PR simply upgrades it.
https://github.com/tokio-rs/bytes/blob/master/CHANGELOG.md#161-july-13-2024
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6471)
> Upgrade the `bytes` dependency away from a yanked version with a bug

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
This PR ensure that we actually bind the `ServiceConnectionManager` to each instance of an Activity. Previously, we could accidentally use the same instance to bind with multiple activities. Now each ServiceConnectionManager is scoped to an Activity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6443)
> Investigate lifecycle of activity

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/UriHandlerExtensions.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
Open the account screen not logged in with we are unable to get the webiste auth token.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6460)
> Fix manage account button not working when offline

- .github/workflows/ios-screenshots-creation.yml
- ci/ios/upload-vm/Gemfile.lock
- ios/Gemfile.lock
Updating `rexml` dependency to `3.3.2` due to [[CVE-2024-39908](https://osv.dev/vulnerability/CVE-2024-39908)](https://osv.dev/vulnerability/GHSA-4xqq-m2hx-25v8).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6478)
> Update rexml to 3.3.2 for fastlane

- CHANGELOG.md
- mullvad-cli/src/cmds/status.rs
The daemon event stream was reset between every item, which caused events to be missed if they arrive while the previous item was being handled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6479)
> Fix burst daemon events being missed

- ci/mullvad-browser/download-mullvad-browser.sh
Follow up to #6469 from yesterday. I noticed further issues. The hard linking with `ln` stopped working when we moved the working directory off of `/tmp` as hard links do not work cross filesystems. So I tried to be less "smart" and just copy the file instead. This means we don't have the implicit requirement that workdirs and tmp dirs have to be on the same filesystem.
I also made it so we publish apps from the WORKDIR instead of the tmp dir. This ensures that all our "latest known browsers" are published at all times. For example with the old script. If it downloaded only the deb and not the rpm for some reason (this should not happen) then it would only publish the deb and remove the rpm from the repos. This is not desired. Instead if we always publish from WORKDIR we will be sure to …
> Fix more browser download bugs

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/RelayLocationCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/FilterChip.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/PrivacyDisclaimerScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/ApiAccessMethodTextField.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/SearchTextField.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6452)
> Clean up invalid uses of Image

- android/CHANGELOG.md
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelState.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepositoryTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
This replaces the "auto-connect" feature on TV and other devices without vpn settings.
Not currently in scope, will be added in a later pr to the `android-auto-start-migration`:
- Removing the old auto-connect feature completely for phone users .    
- Remove the auto-connect feature from daemon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6371)
> Add auto-start on launch to devices without always-on setting

- test/README.md
- test/ci-runtests.sh
- test/scripts/ssh-setup.sh
- test/test-manager/src/container.rs
- test/test-manager/src/logging.rs
- test/test-manager/src/main.rs
- test/test-manager/src/package.rs
- test/test-manager/src/tests/config.rs
- test/test-manager/src/tests/install.rs
- test/test-manager/src/tests/mod.rs
- test/test-manager/src/tests/ui.rs
- test/test-manager/src/vm/provision.rs
Includes a few quality of life improvments, most importantly making previous app and GUI e2e test packages optional.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6475)
> Make test-manager CLI simpler

- .github/CODEOWNERS
- .github/workflows/android-app.yml
- .github/workflows/daemon.yml
- .github/workflows/verify-locked-down-signatures.yml
Limits a bit who has to approve changes to what files. This is far from complete, but rather testing out the system. Some of the more important files have been added for the sake of evaluating this in this repository.
You can read more about CODEOWNERS here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
The idea here is to use security features built into github for further protecting certain more important files. It can also help someone submitting a PR finding a suitable reviewer/automatically assigning a suitable reviewer.
Once we have this in place I intend to add to our branch protection rules that the CODEOWNERS must be respected in order to allow merges of PRs. By default it is not.
- - -
This …
> Add initial github CODEOWNERS file

- .github/workflows/desktop-e2e.yml
Add a precondition which checks if there are any VMs to test for the given OS. Without this check, the parsing of the VM names assumed that there would exist at least one, causing the parsing to fail if there were none. This would show up in the GitHub summary view as a failure.
Also, add some more descriptive names to other steps
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6491)
> Fix desktop e2e GitHub action false negatives

- talpid-wireguard/Cargo.toml
Fix `cargo test -p talpid-wireguard` by adding missing `test-util` feature for `tokio`. `cargo test` would not compile the crate otherwise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6497)
> Add missing feature in `talpid-wireguard`

- Cargo.lock
- Cargo.toml
- mullvad-api/Cargo.toml
- mullvad-jni/Cargo.toml
- mullvad-relay-selector/Cargo.toml
- mullvad-types/Cargo.toml
- talpid-core/Cargo.toml
- talpid-routing/Cargo.toml
- talpid-tunnel/Cargo.toml
- talpid-tunnel/src/tun_provider/android/ipnetwork_sub.rs
- talpid-types/Cargo.toml
- talpid-wireguard/Cargo.toml
Upgrade all our direct usage of `ipnetwork` to the latest version, and makes it a workspace dependency. Nothing new we need, but nice to have the latest version.
~We still have `ipnetwork 0.16` in our dependency tree until we cut a release of `pfctl`, but that can come later and does not need to block this upgrade of all direct upgrades.~.. pfctl 0.5.0 has been released! Fixing this blocker.
I manually reviewed the diff from 0.16 to 0.20 and it looks sane. A bunch of idiomatic improvements to the API, some constification and some other small stuff.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6276)
> Upgrade ipnetwork to 0.20 and make it a workspace dependency

- .github/workflows/check-changelog.yml
- .github/workflows/git-commit-message-style.yml
- .github/workflows/shellcheck.yml
- .github/workflows/unicode-check.yml
- .github/workflows/verify-locked-down-signatures.yml
- .github/workflows/yamllint.yml
Locks down what permissions some of our Github actions has. Limits the risk of them doing something malicious against us. We don't build anything trusted in any of our actions. But with enough permissions set, the actions can write stuff back into the repository or cause other issues. So by default we should try to limit them as much as possible.
I wish Github defaulted to no permissions and explicitly required an action to specify if they needed more permissions than that.
This is in accordance with OpenSSF best practices: https://github.com/ossf/scorecard/blob/b48bdbf250dedadedb42934480bb885d756ead0c/docs/checks.md#token-permissions
- - - …
> Add GitHub actions permissions

- CHANGELOG.md
- talpid-core/src/firewall/macos.rs
- talpid-core/src/firewall/mod.rs
The first connection attempt frequently fails when we do this. Fixing this requires *not* clearing states relating to the VPN connection, as doing so interferes with ephemeral peer exchange.
Fix DES-984.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6420)
> Don't flush PF states associated with VPN connection

- ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift
- ios/MullvadREST/Relay/MultihopDecisionFlow.swift
- ios/MullvadREST/Relay/RelayPicking.swift
- ios/MullvadREST/Relay/RelaySelectorProtocol.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift
- ios/MullvadVPN/TunnelManager/Tunnel+Settings.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/TunnelManager/TunnelState+UI.swift
- ios/MullvadVPN/TunnelManager/TunnelState.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlViewModel.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
- ios/MullvadVPNTests/MullvadVPN/PacketTunnelCore/PacketTunnelActorReducerTests.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift
- ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift
- ios/PacketTunnel/WireGuardAdapter/WireGuardAdapter+Async.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift
- ios/PacketTunnelCore/Actor/Protocols/TunnelAdapterProtocol.swift
- ios/PacketTunnelCore/Actor/StartOptions.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
- ios/PacketTunnelCore/Actor/State.swift
- ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift
- ios/PacketTunnelCoreTests/Mocks/TunnelAdapterDummy.swift
The relay selector is now smart enough to choose relays for `entry` and `exit` peers. It is time to apply multihop on the tunnel. This PR introduces the ability to establish multihop connections without PQ. Implementing multihop with PQ will be addressed in another PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6474)
> Consolidate retry attempts in a single location

- Cargo.toml
`clippy` complains about `rust_2018_idioms` having the same priority as other lints, being a lint group, since the list of lints is unordered: https://rust-lang.github.io/rust-clippy/master/index.html#/lint_groups_priority
This fixes the issue by giving the group a lower priority.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6502)
> Fix clippy error for `rust_2018_idioms`

- CHANGELOG.md
- mullvad-types/src/wireguard.rs
Fix DES-557.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6501)
> Enable quantum-resistant tunnels by default on macOS

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
Sometimes, `isVisible` will return true, this will cause the bottom sheet to never be fully removed and the user stuck with an invisible overlay until they press back.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6510)
> Avoid isVisible check, fixes DROID-1209

- android/CHANGELOG.md
- android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6511)
> Prepare android 2024.4 beta1

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Effectively, these changes imply we're not using any of the IAN code so it'll work just as good as it did in the last release for singlehop - that should be the only difference between the previous commit and this one. This
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6513)
> Bump wireguard-apple to use latest changes.

- ios/MullvadRustRuntimeTests/MullvadPostQuantum+Stubs.swift
- ios/MullvadRustRuntimeTests/MullvadPostQuantumTests.swift
- ios/MullvadTypes/LocalNetworkIPs.swift
- ios/MullvadTypes/Protocols/PostQuantumKeyReceiving.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnel/PostQuantum/MultiHopPostQuantumKeyExchanging.swift
- ios/PacketTunnel/PostQuantum/PostQuantumKeyExchangeActor.swift
- ios/PacketTunnel/PostQuantum/PostQuantumKeyExchangingPipeline.swift
- ios/PacketTunnel/PostQuantum/SingleHopPostQuantumKeyExchanging.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+Public.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift
- ios/PacketTunnelCore/Actor/PostQuantumKey.swift
- ios/PacketTunnelCore/Actor/PostQuantumNegotiationState.swift
- ios/PacketTunnelCore/Actor/Protocols/PostQuantumKeyExchangingProtocol.swift
- ios/PacketTunnelCoreTests/KeyExchangingResultStub.swift
- ios/PacketTunnelCoreTests/Mocks/PostQuantumKeyExchangingUpdaterStub.swift
- ios/PacketTunnelCoreTests/MultiHopPostQuantumKeyExchangingTests.swift
- ios/PacketTunnelCoreTests/PostQuantumKeyExchangeActorStub.swift
- ios/PacketTunnelCoreTests/PostQuantumKeyExchangingPipelineTests.swift
- ios/PacketTunnelCoreTests/SingleHopPostQuantumKeyExchangingTests.swift
- ios/TestPlans/MullvadVPNApp.xctestplan
- mullvad-ios/src/post_quantum_proxy/ios_runtime.rs
In the current implementation, the Post-Quantum key is negotiated only with the exit peer. To enhance security, we proposed an implementaion  to be sure that no traffic is leaked until PQ key exchanges have been completed with both the entry and exit peers.this PR support PQ key exchanging for both peers when multihop is enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6509)
> Negotiate with both peers when using multihop and pq ios 746

- ios/MullvadVPN.xcodeproj/project.pbxproj
Do not embed WireGuardKit Types into MullvadRustRuntime
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6516)
> Do not embed WireguardKitTypes into the MullvadRustRuntime Framework

- .github/workflows/rust-unused-dependencies.yml
This PR reverts a workaround which pinned `cargo-udeps` to `0.1.48` due to missing binaries for macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6530)
> Use latest `cargo-udeps`

- mullvad-management-interface/src/types/conversions/states.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/disconnected_state.rs
- talpid-core/src/tunnel_state_machine/disconnecting_state.rs
- talpid-core/src/tunnel_state_machine/error_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- talpid-tunnel/src/tun_provider/android/mod.rs
- talpid-types/src/tunnel.rs
This PR fixes a bug in the Android split tunnel implementation where the daemon would fail to reconnect when the split tunnel settings changed. This could case the tunnel to become stale, blocking internet traffic for some apps in the process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6540)
> Reconnect if split tunnel state changed

- CHANGELOG.md
- mullvad-api/src/lib.rs
- mullvad-relay-selector/src/relay_selector/helpers.rs
- mullvad-relay-selector/src/relay_selector/mod.rs
- mullvad-relay-selector/src/relay_selector/query.rs
- mullvad-relay-selector/tests/relay_selector.rs
Change the behavior of the relay selector to ignore obfuscation-specific settings (e.g., udp2tcp settings) when the obfuscation protocol is set to `auto`.
Fix DES-1105.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6542)
> Ignore obfuscation settings when obfuscation mode is set to auto

- android/scripts/run-instrumented-tests-locally.sh
- android/scripts/run-instrumented-tests.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6541)
> Match on success message for instrumented tests

- test/test-manager/src/tests/cve_2019_14899.rs
Another minor fix. Replaced code works most of the time, but occasionally the iface name can mismatch the constant.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6551)
> Fix hardcoded tunnel interface name in test

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/settings/mod.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-management-interface/src/client.rs
- test/test-manager/src/tests/mod.rs
The DAITA setting was not being reset during cleanup. The PR fixes this by adding an RPC that resets all settings without logging out.
Fix DES-1108.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6553)
> Reset all settings between tests

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListActionResultData.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/communication/CustomListSuccess.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CreateCustomListDialog.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/DeleteCustomListConfirmationDialog.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/EditCustomListNameDialog.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/CustomListLocationsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/CustomListsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/EditCustomListScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/RelayListRepository.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/customlists/CustomListActionUseCase.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CreateCustomListDialogViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DeleteCustomListConfirmationViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/EditCustomListNameDialogViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/CustomListActionUseCaseTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/CreateCustomListDialogViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeleteCustomListConfirmationViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/EditCustomListNameDialogViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModelTest.kt
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6380)
> Add more detailed snackbars when adding and removing a location in a custom list

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/MullvadApp.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6556)
> Fix splash screen freeze

- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/resolver/DummyNameResolver.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/resolver/DummyNameResolverFactory.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Workaround for slow & unreliable gRPC connection. This will avoid doing DNS lookup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6567)
> Add dummy name resolver

- mullvad-daemon/src/access_method.rs
- mullvad-daemon/src/custom_list.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/main.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-jni/src/lib.rs
- mullvad-management-interface/src/lib.rs
This PR refactors the dameon a bit to properly shut down the management interface server. Previously, it would die when the tokio runtime was tore down due to the tokio task it was run on being dropped. Since we already spawn the `tonic` server with [`serve_with_incoming_shutdown`](https://docs.rs/tonic/latest/tonic/transport/server/struct.Router.html#method.serve_with_incoming_shutdown), it was just a matter of actually using the shutdown signal future that we already had before awaiting the management interface server future.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6559)
> Gracefully shutdown gRPC server

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This PR bumps the wireguard dependency to commit `e3fdc2e95ccd7a30284ec78f3bdf4f9a252a1ed2` in our fork of `wireguard-apple` which fixes multihop related crashes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6566)
> Use a wireguard commit that reduces multihop crashes

- android/gradle/osv-scanner.toml
Added a shorter deadline for `jose4j` since that one is hopefully fixed by upgrading the AGP plugin.
See this google issue:
https://issuetracker.google.com/issues/299134781
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6565)
> Bump dates for all osv scanner ignored vulns and added reasons

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/dialog/EditCustomListNameDialogTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/repository/CustomListsRepositoryTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/CustomListActionUseCaseTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/EditCustomListNameDialogViewModelTest.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/UpdateCustomListError.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6573)
> Restore name already exists error for update custom list

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/main.rs
- mullvad-jni/src/lib.rs
This PR fixes an issue encountered when shutting down the Android app. The daemon never received the shutdown event, causing it to never actually triggering a shutdown. This was fixed by actually using the correct `DaemonCommandChannel` to send the shutdown event.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6577)
> Fix shutdown issue on Android

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/ExpandableComposeCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/SelectableCell.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6562)
> Animate expand in filter screen

- test/test-manager/src/tests/account.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6582)
> Clean up test_automatic_wireguard_rotation

- test/test-manager/src/vm/network/linux.rs
The debug flag was causing DHCP to fail to reboot. Also, dnsmasq output is now also logged after the initial setup, so that `DHCPACK` is logged on each reboot.
Fix DES-871.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6579)
> Fix DHCP server breaking tests

- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/ForegroundNotificationManager.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/ShouldBeOnForegroundProvider.kt
- android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/tunnelstate/TunnelStateNotificationProvider.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6581)
> Fix tunnel state notification behavior when logged out

- .github/actions/build-ios-e2e-tests/action.yml
- .github/actions/run-ios-e2e-tests/action.yml
- .github/workflows/ios-end-to-end-tests-api.yml
- .github/workflows/ios-end-to-end-tests-merge-to-main.yml
- .github/workflows/ios-end-to-end-tests-nightly.yml
- .github/workflows/ios-end-to-end-tests-settings-migration.yml
- .github/workflows/ios-end-to-end-tests.yml
- .github/workflows/ios.yml
- ios/Configurations/UITests.xcconfig.template
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNUITests.xcscheme
- ios/MullvadVPNUITests/Base/BaseUITestCase.swift
- ios/MullvadVPNUITests/ConnectivityTests.swift
- ios/MullvadVPNUITests/Info.plist
- ios/MullvadVPNUITests/Pages/SelectLocationPage.swift
- ios/MullvadVPNUITests/tests.json
This PR changes how iOS end to end test workflows are set up because we ran into some issues. The test iPhone was changed. First it was changed to an iPad and then to another iPhone. The new iPhone is running iOS 17 which don't reinstall the app when launched from tests. So the workflow instead invoke multiple test jobs which run one test suite each. This way we have more control of what we want to do in between test suite runs in CI(uninstall app).
This PR also adds support for running tests on iPad, some minor changes were needed. There's a new configuration property `TEST_DEVICE_IS_IPAD ` which should be set in `UITests.xcconfig`. Also it can now be configured in `UITests.xcconfig` whether app should be uninstalled in test suite teardown. This is by default true(`1`) for running …
> iOS end to end workflow changes related to iOS 17 and iPad

- .github/workflows/ios-end-to-end-tests-api.yml
- .github/workflows/ios-end-to-end-tests-merge-to-main.yml
- .github/workflows/ios-end-to-end-tests-nightly.yml
This PR adds the following permissions
```yaml
permissions:
contents: read
issues: write
pull-requests: write
```
to actions calling into `ios-end-to-end-tests`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6588)
> Enable permissions when calling sub workflow

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SelectLocationScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/SelectLocationUiState.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/SelectLocationViewModel.kt
- android/lib/resource/src/main/res/values-da/strings.xml
- android/lib/resource/src/main/res/values-de/strings.xml
- android/lib/resource/src/main/res/values-es/strings.xml
- android/lib/resource/src/main/res/values-fi/strings.xml
- android/lib/resource/src/main/res/values-fr/strings.xml
- android/lib/resource/src/main/res/values-it/strings.xml
- android/lib/resource/src/main/res/values-ja/strings.xml
- android/lib/resource/src/main/res/values-ko/strings.xml
- android/lib/resource/src/main/res/values-my/strings.xml
- android/lib/resource/src/main/res/values-nb/strings.xml
- android/lib/resource/src/main/res/values-nl/strings.xml
- android/lib/resource/src/main/res/values-pl/strings.xml
- android/lib/resource/src/main/res/values-pt/strings.xml
- android/lib/resource/src/main/res/values-ru/strings.xml
- android/lib/resource/src/main/res/values-sv/strings.xml
- android/lib/resource/src/main/res/values-th/strings.xml
- android/lib/resource/src/main/res/values-tr/strings.xml
- android/lib/resource/src/main/res/values-zh-rCN/strings.xml
- android/lib/resource/src/main/res/values-zh-rTW/strings.xml
- android/lib/resource/src/main/res/values/strings.xml
- gui/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6589)
> Show the name of the custom list in remove location bottom sheet

- .github/actions/run-ios-e2e-tests/action.yml
yaml is really a great language.
The tests were not running anymore because of `|` being changed to `>` in a previous PR.
[This article](https://kodekloud.com/blog/yaml-multiline-string/) explains the difference between those two characters
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6591)
> Change everything with a single character

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/BaseCell.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6601)
> Fix crash when focusing remove button in device list screen

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/NavigateButton.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessListScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/CustomListsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ReportProblemScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ServerIpOverridesScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SplitTunnelingScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ViewLogsScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt
This seems to be caused by the app going through all the different items in the lazy list and then checking them one by one if they can be focused.
This is a workaround for this, I guess we should check if this is fixed by future updates to compose.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6603)
> Fix view logs crash on TV

- ios/MullvadMockData/MullvadREST/AccessMethodRepository+Stub.swift
- ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift
- ios/MullvadRESTTests/TransportStrategyTests.swift
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift
- ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift
- ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift
- ios/MullvadVPN/SimulatorTunnelProvider/SimulatorVPNConnection.swift
- ios/MullvadVPN/StorePaymentManager/StorePaymentManager.swift
- ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift
- ios/MullvadVPN/TunnelManager/SendTunnelProviderMessageOperation.swift
- ios/MullvadVPN/TunnelManager/Tunnel+Messaging.swift
- ios/MullvadVPN/TunnelManager/Tunnel.swift
- ios/MullvadVPN/TunnelManager/TunnelInteractor.swift
- ios/MullvadVPN/TunnelManager/TunnelManager.swift
- ios/MullvadVPN/TunnelManager/TunnelStore.swift
- ios/MullvadVPN/TunnelManager/UIApplication+Extensions.swift
- ios/MullvadVPNTests/MullvadREST/Shadowsocks/ShadowsocksLoaderTests.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/MockTunnel.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/MockTunnelInteractor.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelStore+Stubs.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/UIApplication+Stubs.swift
- ios/MullvadVPNUITests/ConnectivityTests.swift
- ios/Operations/BackgroundObserver.swift
- ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
- ios/PacketTunnelCore/Actor/ObservedState.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift
- ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- ios/PacketTunnelCoreTests/Mocks/PostQuantumKeyExchangingUpdaterStub.swift
The app gets stuck in a blocked state after these transitions:
- The packet tunnel is Connected, then Airplane mode is toggled.
- The packet tunnel is Connected, then no relay constraints are satisfied.
This problem might also occur due to other reasons that result in a blocked state. To solve this issue, we need to refresh the tunnel status after reconnecting tunnel when the block state occurs. This pull request (PR) addresses the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6552)
> Fix getting stuck after blocked state

- mullvad-daemon/src/tunnel.rs
- mullvad-management-interface/src/types/conversions/device.rs
- mullvad-types/src/device.rs
- test/test-manager/src/run_tests.rs
- test/test-manager/src/tests/account.rs
- test/test-manager/src/tests/install.rs
- test/test-manager/src/tests/mod.rs
- test/test-rpc/src/client.rs
This PR overhauls `test_automatic_wireguard_rotation` to use `anyhow` to propagate error values instead of panicking, which is a commonly used strategy in other end-to-end tests. These are the fruits of some work investigating flakiness related to the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6490)
> Structure error handling in `test_automatic_wireguard_rotation`

- talpid-platform-metadata/Cargo.toml
- talpid-platform-metadata/src/linux.rs
- test/Cargo.lock
- test/test-runner/Cargo.toml
Add `network-manager` as a feature so that `talpid-platform-metadata` does not have to depend on `talpid-dbus`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6614)
> Add `network-manager` feature to `talpid-platform-metadata`

- .gitignore
- test/scripts/Dockerfile
- test/scripts/build-manager.sh
- test/scripts/build.sh
- test/test-manager/build.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6615)
> Build `test-manager` as a standalone executable

- .github/workflows/desktop-e2e.yml
Only the last two major Fedora versions are supported. See https://docs.fedoraproject.org/en-US/releases/eol/
Same for Ubuntu 23.10 and 23.04: https://ubuntu.com/about/release-cycle, https://fridge.ubuntu.com/2023/12/15/ubuntu-23-04-lunar-lobster-reaches-end-of-life-on-january-25-2024/
This should speed things up a bit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6616)
> Remove unsupported distros from e2e tests

- ios/.swiftlint.yml
- ios/MullvadREST/ApiHandlers/RESTRequestFactory.swift
- ios/MullvadSettings/SettingsManager.swift
- ios/MullvadVPN/StorePaymentManager/StorePaymentManager.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift
- ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
- ios/MullvadVPNTests/MullvadSettings/APIAccessMethodsTests.swift
- ios/MullvadVPNTests/MullvadSettings/IPOverrideRepositoryTests.swift
- ios/MullvadVPNTests/MullvadSettings/MigrationManagerTests.swift
- ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift
- ios/PacketTunnelCore/Pinger/Pinger.swift
this PR fixes some Swiftlint  warnings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6612)
> Fix swiftlint warnings

- test/test-manager/src/config.rs
- test/test-manager/src/main.rs
- test/test-manager/src/vm/mod.rs
- test/test-manager/src/vm/provision.rs
Add flag to explicitly specify the test runner dir. This is not used as of now, but is a preliminary step towards reusing the same `test-runner` for multiple VMs (e.g. all `x86_64-unknown-linux-gnu` targets).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6618)
> Add `--test-runner-dir` flag

- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/util/ManagedChannel.kt
I am not sure this happens in the actual app, but it is good to prevent future issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6563)
> Fix potential crash in connection state flow

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/DnsDialogViewModel.kt
Changed it so that settings is only fetched at the creation of the dialogue.
This fixes all issues with the state being wrong for a short while after pressing submit.
Tested cases that are fixed:
- "Add DNS server" changed to "Update DNS server"
- Remove button showing briefly (related to the above bug)
- "This address has already been entered" showing briefly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6617)
> Fix issues with dns dialog showing wrong state after submitting

- .github/workflows/desktop-e2e.yml
- test/scripts/test-utils.sh
This makes it possible to run only a subset of all tests during a manually triggered test run.
Fix DES-825.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6625)
> Add test filters field to E2E workflow_dispatch

- gui/osv-scanner.toml
We're not affected by the elliptic CVEs. This PR suppresses the warnings in OSV scanner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6626)
> Suppress elliptic CVEs

- android/build.gradle.kts
This PR aims to fix an issue with the dependency version check plugin introduced in #6607 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6627)
> Fix dependency version check plugin

- .github/workflows/desktop-e2e.yml
This PR adds macOS Sequoia to the end-to-end test GHA workflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6633)
> Add macOS 15 to end-to-end test GHA workflow

- test/scripts/ssh-setup.sh
- test/scripts/test-utils.sh
- test/test-manager/src/logging.rs
- test/test-manager/src/main.rs
- test/test-manager/src/network_monitor.rs
- test/test-manager/src/package.rs
- test/test-manager/src/run_tests.rs
- test/test-manager/src/summary.rs
- test/test-manager/src/tests/account.rs
- test/test-manager/src/tests/helpers.rs
- test/test-manager/src/tests/install.rs
- test/test-manager/src/tests/mod.rs
- test/test-manager/src/tests/test_metadata.rs
- test/test-manager/src/tests/ui.rs
- test/test-manager/src/vm/mod.rs
- test/test-manager/src/vm/provision.rs
- test/test-manager/test_macro/src/lib.rs
Currently, the cleanup code only resets a small subset of the daemon state, and many tests implicitly rely on being left in a certain state by the previous. This is inherently flaky, as one test failing may cause the following ones to also fail. It is also very inflexible, as it doesn't allow testing arbitrary single tests, or changing the order of tests.
- Refactor the cleanup to completely and deterministically make sure the correct daemon version is installed, logged in and disconnected with all setting cleared before each test
- Allow reordering tests
Fixes DES-1137
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6493)
> Refactor test manager cleanup logic

- test/scripts/build.sh
- test/scripts/container-run.sh
- test/scripts/test-utils.sh
- test/test-by-version.sh
This commit enables the usage of the dist/ directory, and also adds mullvad-version to it so that test-by-version.sh can operate without rust installed at all.
Also added a /dev/null redirect of a cd output so that one's able to use CDPATH while running the tests.
I would like to be able to run the e2e tests on a VM without having to compile the binaries at all, since that increases the disk size necessary for running the tests. The disk space needed drops by 20-30G this way.
1. Build all executables with `scripts/container-run.sh scripts/build.sh`.
2. Clone mullvadvpn-app on a system without rust installed.
3. Copy the dist folder that was created in step 1 to mullvadvpn-app/test/dist
4. Run the end to end tests using test-by-version.sh, which should not fail due to cargo missing.
- - - …
> E2E tests: remove cargo dependency

- .github/workflows/ios-rust-ffi.yml
- mullvad-ios/src/tunnel_obfuscator_proxy/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6635)
> Add CI job for mullvad-ios

- .github/workflows/ios-rust-ffi.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6637)
> Specify Rust target in iOS workflow

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Coordinators/AccountCoordinator.swift
- ios/MullvadVPN/View controllers/Account/AccountContentView.swift
- ios/MullvadVPN/View controllers/Account/AccountViewController.swift
- ios/MullvadVPN/View controllers/Account/RestorePurchasesView.swift
- ios/MullvadVPN/View controllers/Alert/AlertViewController.swift
The restore purchases button should be replaced with a bit of clickable text in the account description, alongside a info icon that opens an alert containing copy suggesting to the user that one can only restore purchases to the account that they are currently logged in.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6624)
> Rework the Restore Purchases button to decrease user confusion

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AutoConnectAndLockdownModeScreen.kt
- android/lib/resource/src/main/res/values/strings.xml
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt
- android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/typeface/TypeScale.kt
- gui/locales/messages.pot
- Remove string with newline in it since it was not treated properly by the translation script
- Change the line break strategy so that the title looks better in the Auto-connect screen.
- Make the title bold as other titles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6630)
> Fix Auto connect lockdown mode title

- CHANGELOG.md
- talpid-core/src/split_tunnel/macos/process.rs
Another split tunneling bug. The issue can be reproduced by excluding `test` and running `./test` from a shell with its directory as the working dir.
Fix DES-1152.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6644)
> Exclude relative paths properly

- mullvad-daemon/src/lib.rs
- mullvad-types/src/features.rs
- mullvad-types/src/states.rs
Feature indicators were missing during the connecting state. This was
because they were calculated using the endpoint of the previous tunnel
state.
This commit fixes the bug and restructures the access to feature
indicators to be more readable.
Fixes DES-1140
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6643)
> Fix feature indicators missing during connecting state

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- talpid-core/Cargo.toml
- talpid-core/src/split_tunnel/macos/mod.rs
- talpid-core/src/split_tunnel/macos/tun.rs
- talpid-net/Cargo.toml
- talpid-net/src/lib.rs
- talpid-net/src/unix.rs
- talpid-routing/src/unix/macos/data.rs
- talpid-routing/src/unix/macos/mod.rs
- talpid-routing/src/unix/mod.rs
- talpid-wireguard/Cargo.toml
- talpid-wireguard/src/lib.rs
- talpid-wireguard/src/mtu_detection.rs
- talpid-wireguard/src/unix.rs
Fixes the following error:
```
Failed to forward to tun device: Message too long (os error 40)
```
There were a couple of issues:
* The MTU of the ST utun was potentially higher than that of the VPN tunnel. We now keep track of and sync the MTUs.
* Outbound packets weren't correctly filtered. `Capture::direction` seems to handle it correctly but doesn't work on macOS 13. Instead, we must discard packets with the wrong source IP.
Close DES-1115.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6640)
> Fix split tunneling packet loss

- android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/AccountTestRule.kt
- android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/SimpleMullvadHttpClient.kt
Firebase tests are failing because of rate limiting, the issue is that `AccountTestRule`'s setup code runs for all tests even ignored ones. Moving code from `init` to `beforeEach` solves this.
Also added logging of response status code when `SimpleMullvadHttpClient` receives error response.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6645)
> Fix e2e tests failing on Firebase due to rate limiting

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VoucherDialogViewModelTest.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/RedeemVoucherError.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/VoucherCode.kt
- android/lib/model/src/test/kotlin/net/mullvad/mullvadvpn/lib/model/VoucherCodeTest.kt
- android/lib/resource/src/main/res/values/strings.xml
- android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/VoucherRepository.kt
- gui/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6571)
> Add better Voucher Code validation

- ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift
- ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift
- ios/MullvadREST/Relay/AnyRelay.swift
- ios/MullvadREST/Relay/MultihopDecisionFlow.swift
- ios/MullvadREST/Relay/NoRelaysSatisfyingConstraintsError.swift
- ios/MullvadREST/Relay/RelayPicking.swift
- ios/MullvadREST/Relay/RelaySelector+Shadowsocks.swift
- ios/MullvadREST/Relay/RelaySelector+Wireguard.swift
- ios/MullvadREST/Relay/RelaySelector.swift
- ios/MullvadREST/Relay/RelaySelectorWrapper.swift
- ios/MullvadVPN/Coordinators/LocationCoordinator.swift
- ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift
- ios/MullvadVPNTests/MullvadREST/ApiHandlers/ServerRelaysResponse+Stubs.swift
- ios/MullvadVPNTests/MullvadREST/Relay/MultihopDecisionFlowTests.swift
- ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift
- ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorTests.swift
- ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift
- ios/MullvadVPNTests/MullvadSettings/IPOverrideWrapperTests.swift
- ios/PacketTunnel/PacketTunnelProvider/BlockedStateErrorMapper.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
- ios/PacketTunnelCore/Actor/State.swift
- ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift
- ios/PacketTunnelCoreTests/MultiHopPostQuantumKeyExchangingTests.swift
- ios/PacketTunnelCoreTests/PostQuantumKeyExchangingPipelineTests.swift
- ios/PacketTunnelCoreTests/SingleHopPostQuantumKeyExchangingTests.swift
When DAITA is enabled, the relay selector should only match DAITA enabled relays for the entry location when using multihop. If no DAITA relays can be matched, the packet tunnel should enter the blocked state - ideally with an error message displayed to the user that makes it obvious that no relays were matched due to none of the eligible ones allowing DAITA.
When using single-hop and DAITA is enabled only DAITA enabled relays should be considered first - the best suitable DAITA relay should be picked if at all possible. Otherwise, if the exit constraints do not match any DAITA enabled relay, the relay selector should use multihop to select a valid DAITA relay for the entry.
- - - …
> Allow relay selector to filter daita enabled relays

- android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LoginTest.kt
- android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/misc/SimpleMullvadHttpClient.kt
- android/test/firebase/e2e-play-stagemole.yml
- android/test/firebase/mockapi-oss.yml
e2e tests on Firebase are still sometimes failing due to rate limiting. This PR include some improvements related to failing tests in Firebase:
* Disable `testLoginWithInvalidCredentials` because the requests it generates are highly rate limited
* Logging broke in some bases because the response object was null
* Configure Firebase to re-run failing tests once
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6653)
> Fixes for firebase e2e still sometimes failing

- mullvad-management-interface/src/types/conversions/features.rs
- mullvad-types/src/features.rs
Add simple test that modifies the settings and endpoint with one variable at a time and verifies that the corresponding indicator is activated. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6648)
> Add feature indicator test

- test/test-manager/src/tests/helpers.rs
Minor fix for a test helper function. It is only relevant for `test_mul_02_002`. We assumed that the function would constrain the relay to use a specific port, but this wasn't the case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6650)
> Constrain relay port with `constrain_to_relay` helper

- talpid-openvpn/src/lib.rs
The test was inherently racy. The "process" exited immediately and the future would sometimes resolve before the close handle had the time to stop the monitor. PR fixes it by having the process "run forever".
Fix DES-1042.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6651)
> Fix flaky wait_closed test

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Coordinators/LocationCoordinator.swift
- ios/MullvadVPN/View controllers/RelayFilter/RelayFilterChipView.swift
- ios/MullvadVPN/View controllers/RelayFilter/RelayFilterView.swift
- ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationRelays.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift
- ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift
- ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorTests.swift
- ios/MullvadVPNTests/MullvadVPN/View controllers/SelectLocation/AllLocationsDataSourceTests.swift
- ios/MullvadVPNTests/MullvadVPN/View controllers/SelectLocation/CustomListsDataSourceTests.swift
When DAITA is enabled, the app should only list DAITA enabled entry locations in the locations view.
If the user has enabled both DAITA & multihop and the relay selector fails to match an entry, when the location view is opened, it should default to showing the entry location view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6609)
> List only DAITA enabled entry locations in locations view

- CHANGELOG.md
Point to the latest tag which fixes a panic.
Fix DES-1154.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6657)
> Bump wireguard-go submodule to wg-go-daita 0.1.1

- .github/workflows/android-app.yml
- .github/workflows/android-audit.yml
- .github/workflows/android-kotlin-format-check.yml
- .github/workflows/android-static-analysis.yml
- .github/workflows/android-xml-format-check.yml
- .github/workflows/cargo-audit.yml
- .github/workflows/cargo-vendor.yml
- .github/workflows/clippy.yml
- .github/workflows/daemon.yml
- .github/workflows/desktop-e2e.yml
- .github/workflows/frontend.yml
- .github/workflows/ios-end-to-end-tests-api.yml
- .github/workflows/ios-end-to-end-tests-merge-to-main.yml
- .github/workflows/ios-end-to-end-tests-nightly.yml
- .github/workflows/ios-screenshots-creation.yml
- .github/workflows/ios-screenshots-tests.yml
- .github/workflows/ios-validate-build-schemas.yml
- .github/workflows/ios.yml
- .github/workflows/proto-format-check.yml
- .github/workflows/rust-supply-chain.yml
- .github/workflows/rust-unused-dependencies.yml
- .github/workflows/rustfmt.yml
- .github/workflows/testframework-clippy.yml
- .github/workflows/testframework-rust-supply-chain.yml
- .github/workflows/testframework-rustfmt.yml
- .github/workflows/testframework.yml
- .github/workflows/translations-converter.yml
- .github/workflows/translations.yml
The default permission on the repository is already set to read only. So in practice this makes no difference. But this makes that more explicit, and less relying on the repository being correctly configured.
This also makes security scanning tools such as OpenSSF scorecard happier about the overall security of our repository.
I think we should start *always* defining `permissions` on our actions. However, we currently don't have anything that enforces it, and given how little actual security it gives us right now it's definitely not worth automating. I just wanted to do this little manual sweep to "improve" the current state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mull …
> Add top level `permissions` to all Github Actions workflows

- test/scripts/ssh-setup.sh
- test/test-manager/src/vm/provision.rs
- test/test-rpc/src/lib.rs
- test/test-runner/Cargo.toml
- test/test-runner/src/main.rs
- test/test-runner/src/util.rs
`test-runner` now spawns all processes as an unprivileged user.
Fix DES-1131
Fix DES-1129
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6656)
> Spawn `connection-checker` as an unprivileged user

- mullvad-api/src/relay_list.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/tunnel.rs
- mullvad-management-interface/src/types/conversions/relay_list.rs
- mullvad-relay-selector/src/relay_selector/matcher.rs
- mullvad-relay-selector/tests/relay_selector.rs
- mullvad-types/src/features.rs
- mullvad-types/src/relay_constraints.rs
- mullvad-types/src/relay_list.rs
It was trigger by any overrides existing in the settings, not by the current endpoint being overridden.
Add flag to `Relay` to specify if its IPv4 and/or IPv6 has been overridden and use that in combination with the endpoint IP version to derive if the current connection is overridden.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6654)
> Fix IP-override feature indicator

- android/docker/Dockerfile
- building/linux-container-image.txt
Bump both the container used for Linux builds, as well as the base used to build Android to the newly built container with Rust 1.80.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6662)
> Bump linux container to `mullvadvpn-app-build:0186b645c`

- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/AccountScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/WelcomeScreen.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/AccountViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/DeviceRevokedViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModelTest.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ClearAccountHistoryError.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/LogoutAccountError.kt
- android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/AccountRepository.kt
- android/test/arch/src/test/kotlin/net/mullvad/mullvadvpn/test/arch/ManagementServiceTest.kt
This is so the app will not crash if an error occured.
Added konsist test so that all calls needs to be wrapped in Either.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6500)
> Wrap all management service calls in Either

- ci/ios/upload-vm/osv-scanner.toml
- gui/osv-scanner.toml
- ios/osv-scanner.toml
`osv-scanner` has started complaining about `micromatch` and `rexml` (one in desktop frontend, and one in iOS helper scripts). Both are regular expression DoS attacks which does not affect us, since we won't run untrusted input in it.
This is not the first time `rexml` has been having these silly[1] issues. It has proven to be problematic to just upgrade `rexml` (thank you ruby package management). So this time I opted for just ignoring it... For now :shrug: 
[1]: Silly as in they don't affect us, and basically all regular expression libraries have a metric ton of DoS all the time. So it's taxing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6669)
> Ignore micromatch CVE-2024-4067 and rexml CVE-2024-43398

- docs/macos-signing.md
Fix Typo issue from `passprase` to `passphrase` at `docs/macos-signing.md`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6670)
> [docs] Fix Typo issue from `passprase` to `passphrase`

- building/container-run.sh
This PR aims to disable `mold` by default in the container wrapper script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6671)
> Disable mold by default in container wrapper script

- CHANGELOG.md
- mullvad-cli/src/cmds/obfuscation.rs
Close DES-1145.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6629)
> Add CLI for shadowsocks obfuscation

- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt
- android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreenTest.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/ConnectionButton.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/OutOfTimeScreenPreviewParameterProvider.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/TunnelStatePreviewData.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/TunnelStatePreviewParameterProvider.kt
- android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/OutOfTimeScreen.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/OutOfTimeUseCaseTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt
- android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModelTest.kt
- android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/FeatureIndicator.kt
- android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/TunnelState.kt
Also cleaned up some previews.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6677)
> Add support for feature indicators for tunnel state

- ios/MullvadREST/ApiHandlers/SSLPinningURLSessionDelegate.swift
- ios/MullvadVPN/SceneDelegate.swift
- ios/MullvadVPN/Supporting Files/Info.plist
This PR disables ATS entirely from our application. 
This requires justifying to apple why we do this, and we feel we have a good explanation in hand : 
- We do not trust DNS systems
- We do SSL pinning so we cannot do insecure connections to our API (we already validate the TLS connection ourselves)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6642)
> Disable ATS entirely

- ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift
- ios/PacketTunnelCore/Actor/State+Extensions.swift
- ios/PacketTunnelCore/Actor/Timings.swift
- ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
When the reason for the blocked state is a tunnel adapter error, we need to automatically recover the connection to attempt reconnection to the current relay, keeping the tunnel up to date. This PR introduces that functionality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6647)
> Packet Tunnel stuck in blocked state after Airplane mode is toggled.

- talpid-core/src/split_tunnel/macos/mod.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
In the current split tunnel design, the split tunnel interface is never destroyed once it has been created. This PR removes the split tunnel interface when split tunneling is disabled, since any potential issues with split tunneling should not affect anyone who disables the feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6666)
> Remove split tunnel interface if split tunneling is disabled

- deny.toml
It appears to be GPL-3 compatible: https://spdx.org/licenses/Unicode-3.0.html
Needed due to dependency updates: https://github.com/mullvad/mullvadvpn-app/actions/runs/10559185495/job/29250107186
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6680)
> Add Unicode-3.0 to approved licenses

- ci/linux-repository-builder/build-linux-repositories-config.sh
We already support `testing`. So this is not a big deal. Just that when you install/upgrade to trixie then `lsb_release -cs` will return `trixie` and not `testing`. So if we intend to support Debian versions in testing, we should probably add the names of the distros as soon as they are decided/used by the OS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6683)
> Add trixie to list of debian versions to generate deb repositories for

- android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt
- android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/rule/ForgetAllVpnAppsInSettingsTestRule.kt
- android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt
This PR enables `testConnectAndVerifyWithConnectionCheck` and adds a wait for the out IP address to show before attempting to extract it. It is valid that it in some cases take a while for it to show.
There is also a small fix for login button sometimes being pressed before it has been enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6663)
> Re-enable and fix testConnectAndVerifyWithConnectionCheck

- .github/workflows/daemon.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/5860)
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- CHANGELOG.md
- mullvad-daemon/src/lib.rs
- mullvad-relay-selector/src/error.rs
- mullvad-relay-selector/src/relay_selector/matcher.rs
- mullvad-relay-selector/src/relay_selector/mod.rs
- mullvad-relay-selector/src/relay_selector/query.rs
- mullvad-relay-selector/tests/relay_selector.rs
- mullvad-types/src/wireguard.rs
- test/test-manager/src/tests/helpers.rs
WireGuard will always be preferred, when any of these features is enabled, even when the tunnel protocol is set to auto.
Core privacy features include PQ, multihop, and DAITA.
Close DES-1066.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6668)
> Match no OpenVPN relays when core privacy features are enabled

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Classes/AccessbilityIdentifier.swift
- ios/MullvadVPN/View controllers/Login/LoginContentView.swift
- ios/MullvadVPN/View controllers/Login/LoginViewController.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInfoButtonItem.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
- ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift
- ios/MullvadVPNUITests/AccountTests.swift
- ios/MullvadVPNUITests/Pages/DaitaPromptAlert.swift
- ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift
- ios/MullvadVPNUITests/SettingsMigrationTests.swift
This PR introduces the ability to toggle `Daita` in settings:
<table width = "200">
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/4ec06358-2f9b-4e90-8f90-9a968718a6ad"/></td>
<td><img src ="https://github.com/user-attachments/assets/7d0162c7-c440-4656-bbd1-7297478ca65e" /></td>
</tr>
</table>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6667)
> Add UI for DAITA in VPN settings

- .github/workflows/android-app.yml
Change the scheduling of android-app.yml so it runs at UTC 00:00(GMT+01 02:00) every day instead of GMT+01 08:20.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6688)
> Change schedule of android-app.yml

- android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt
`testConnect` already have this longer(30 seconds) timeout in place but it was missing in `testConnectAndVerifyWithConnectionCheck`. This caused some test failures in last night's test run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6689)
> Increase timeout when waiting for connection

- ci/ios/upload-vm/Gemfile.lock
- ci/ios/upload-vm/osv-scanner.toml
- ios/Gemfile.lock
- ios/osv-scanner.toml
This PR updates the `rexml` dependency we use for running screenshots to a version not known to be vulnerable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6695)
> Update rexml for vulnerability issues

- test/connection-checker/src/cli.rs
- test/connection-checker/src/main.rs
- test/connection-checker/src/net.rs
- test/scripts/ssh-setup.sh
- test/test-manager/src/tests/helpers.rs
`ping` uses raw sockets rather than `SOCK_DGRAM` by default. This only works as root.
Related test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/10593508501
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6682)
> Fix test_split_tunnel

- gui/src/renderer/components/main-view/ConnectionPanel.tsx
- gui/src/renderer/components/main-view/FeatureIndicators.tsx
- gui/test/e2e/mocked/feature-indicators.spec.ts
- Improve math for calculating whether or not an indicator should show.
- Fix connection panel closing without any actions
- Defer making feature indicators visible to ensure elements rendered
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6664)
> Fix issues in new connection panel
