tunnel-obfuscation/src/shadowsocks.rs
If the wg device MTU is set too high, the log is filled with the following error:
```
[2024-08-29 10:00:41.937][tunnel_obfuscation::shadowsocks][ERROR] Failed to write to Shadowsocks client: Message too long (os error 90)
[2024-08-29 10:00:41.937][tunnel_obfuscation::shadowsocks][ERROR] Failed to write to Shadowsocks client: Message too long (os error 90)
[2024-08-29 10:00:42.068][tunnel_obfuscation::shadowsocks][ERROR] Failed to write to Shadowsocks client: Message too long (os error 90)
[2024-08-29 10:00:42.447][tunnel_obfuscation::shadowsocks][ERROR] Failed to write to Shadowsocks client: Message too long (os error 90)
[2024-08-29 10:00:42.447][tunnel_obfuscation::shadowsocks][ERROR] Failed to write to Shadowsocks client: Message too long (os error 90)
```
PR simply lowers the log …
=> Lower log level of shadowsocks write errors

Cargo.toml
I took some measurements with this change. Here are the results:
**Build time (`cargo build --release`):** 624s -> 488s = 22% drop in compile time
**Binary size (`mullvad-daemon`):** 22.9 MiB -> 15.9 MiB = 31% drop in binary size
**Binary size (`mullvad` (cli)):** 7.5 MiB -> 5.7 MiB = 24% drop in binary size
**Build time (`./build.sh --optimize --universal`)**: 3970s -> 3142s = 21% drop in compile time
**Binary size (`mullvad-daemon`):** 19.5 MiB -> 13.9 MiB = 29% drop in binary size
**Build time (`./build.sh --optimize`):** 17m33s -> 11m19s = 35% drop in compile time
**Binary size (`mullvad-daemon`):** 22.3 MiB -> 14.5 MiB = 35% drop in binary size
As you can see, both the compile times and produced binary size goes down significantly on all desktop platforms. This change will also …
=> Change Rust opt-level from 3 to "s" to optimize for binary size

test/scripts/ssh-setup.sh, test/test-runner/src/package.rs
Seems to be working: https://github.com/mullvad/mullvadvpn-app/actions/runs/10616373857
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6712)
=> Fix `test-runner` bootstrap failing if `apt` lock is already held

mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/src/relay_selector/query.rs, mullvad-relay-selector/tests/relay_selector.rs, mullvad-types/src/constraints/constraint.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/tunnel.rs, tunnel-obfuscation/src/shadowsocks.rs
Close DES-1025.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6338)
=> Add integration tests for WG over Shadowsocks

CHANGELOG.md, talpid-core/src/split_tunnel/macos/mod.rs, talpid-core/src/tunnel_state_machine/disconnected_state.rs
This breaks existing connections in the disconnected state, but hopefully it should be more stable, since split tunneling will be completely disabled.
Fix DES-1206.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6700)
=> Disable split tunneling when disconnected

talpid-tunnel-config-client/examples/psk-exchange.rs, talpid-tunnel-config-client/src/lib.rs, talpid-wireguard/src/lib.rs
This is a further cleanup following some discoveries I made when working with your PSK exchange.
As already written during PR #6477, calling `psk-exchange` or more specifically `talpid_tunnel_config_client::request_ephemeral_peer` with an IPv6 resulted in an `EAFNOSUPPORT` error.
With the current program it never makes sense to pass an `Ipv6Addr` to `request_ephemeral_peer`, since it can't handle an IPv6 connection even if the tunnel configuration service was listening to an IPv6.
There are two locations where `request_ephemeral_peer` is called. One of them is in `talpid-wireguard/src/lib.rs`, the other one is in the `psk-exchange` example.
Since the address is statically set to the IPv4 gateway in the former case, presently the only possible case for problems to happen was if someone …
=> Use narrower type to fix possible panic with IPv6 address argument

gui/test/e2e/utils.ts
This PR stops waiting for transitions to end if the page closes. This could potentially fix flakiness in the tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6723)
=> Stop waiting for transition if failed

test/scripts/test-utils.sh, test/test-by-version.sh
This PR adds the `OPENVPN_CERTIFICATE` argument to `test-by-version`, which really just exposes the `--openvpn-certificate` option of `test-manager`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6729)
=> Expose option for changing OpenVPN CA certificate in `test-by-version` script

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift, ios/MullvadVPNUITests/XCUIElement+Extensions.swift
Due to the increasing number of items in VPN settings, our current UI test struggles to locate elements that are off-screen. This update resolves the issue by implementing scrolling to find the targeted elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6696)
=> Fix off-screen element detection issue

build.sh
Pretty self-explanatory. The incorrect wrong path was signed here.
Fix DES-1215.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6733)
=> Fix signing of `talpid_openvpn_plugin.dll` for arm64

test/scripts/ssh-setup.sh, test/test-runner/src/package.rs
`apt` seems to get stuck at times due interactive use (missing `-y`): https://github.com/mullvad/mullvadvpn-app/actions/runs/10692668900/job/29641524336
I also switched to `apt-get` to get rid of this warning: "WARNING: apt does not have a stable CLI interface. Use with caution in scripts."
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6741)
=> Force install of deb packages in tests

gui/osv-scanner.toml, gui/scripts/osv-scanner.toml
This is only for desktop frontend and python helper scripts.
These should be safe to ignore still. I don't think anything changed that would make them dangerous to us now. The ideal would of course to get rid of the python scripts and eventually upgrade the npm dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6743)
=> Extend ignoreUntil for CVEs that still don't affect us

ios/MullvadVPN/View controllers/Tunnel/ConnectionPanelView.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
Currently, when we turn on multihop and Daita on, the label "server abc using Daita via server xyz" is too long, and cut in the middle.
This fix may seem unintuitive in that it uses a stackview with label and image rather than the previous custom buttom. However, adding multiline support to button titles requires extra constraints to align text with button bounds, plus opens up a world of headache when trying to freely position the button image. With the stackviews we can move things around freely while still keeping the original look and feel by emulating button pressing behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6739)
=> Fix selected relay label being too long when multihoping with Daita

ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift, ios/MullvadREST/Relay/RelaySelectorProtocol.swift, ios/MullvadREST/Relay/RelaySelectorWrapper.swift, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift, ios/MullvadVPNTests/MullvadVPN/PacketTunnelCore/PacketTunnelActorReducerTests.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
This PR changes `RelaySelectorWrapper` to not create tunnel settings instances by itself anymore.
Instead, we now pass tunnel settings when we need to select a relay to always rely upon settings that were read from cache.
This fixes a bug where saved user settings would otherwise not be respected when upgrading the app to a new version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6721)
=> Inject tunnel settings in RelaySelectorWrapper

ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift, ios/MullvadREST/Relay/IPOverrideWrapper.swift, ios/MullvadREST/Relay/RelayCache.swift, ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift
This PR fixes the problem with old installs not having daita information in cache when upgrading to a new version.
- Delete the app from your device
- Install a previous version `2024.5` or earlier
- Launch the installed version (no need to do anything, just launch it once)
- Install this fix
- Log in
- Turn on Daita
- Try to select a Daita relay
- You should be able to see daita enabled relays in the list with this fix, otherwise, you would see nothing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6744)
=> Fix the cached relays to include daita information in new app version

talpid-core/src/split_tunnel/windows/mod.rs, talpid-core/src/tunnel_state_machine/mod.rs
Replace `map_err` with `inspect_err`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6753)
=> Fix clippy lint

ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift
When DAITA is being used, the main view should indicate as much. 
The main view should be updated to follow desktop and add extra text to the relay line to indicate if DAITA is being used. For now, multihop and singlehop cases shouldn't be differentiated.
Whether DAITA is used or not should be inferred from the communication between the client and the packet tunnel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6719)
=> Update connection details on main view to indicate that DAITA is used

wireguard-go-rs/libwg/libwg.go, wireguard-go-rs/libwg/libwg_android.go, wireguard-go-rs/libwg/libwg_daita.go, wireguard-go-rs/libwg/libwg_default.go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6727)
=> Replace GoString with our own function to fix mte issue

osv-scanner.toml
Temporary fix until https://github.com/mullvad/mullvadvpn-app/pull/6748 is merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6755)
=> Silence `RUSTSEC-2024-0370` in `osv-scanner`

ios/Configurations/Version.xcconfig
We released 2024.5, now we must bump the version in `main`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6722)
=> Bump iOS version to 2023.5

ios/MullvadVPN/TunnelManager/MapConnectionStatusOperation.swift, ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift, ios/MullvadVPN/TunnelManager/TunnelState+UI.swift, ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
This PR changes the "creating secure connection" label to correctly reflect when a connection is PQ enabled or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6766)
=> Do not display post quantum label for daita non pq connections

ios/MullvadSettings/DAITASettings.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInfoButtonItem.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
After discussing with the stakeholders, and the design team, we want to ship Daita with an improved UX, which will behave as following:
- If the single hop selected location already supports Daita, there is no warning shown when Daita is enabled, it just works
- If the single hop selected location does not support Daita, the "Enable anyway" warning is shown, and if the user accepts, they enter the blocked state.
- If the multihop entry selected location already supports Daita, there is no warning, it just works
- If the multihop entry selected location does not support Daita, the "Enable anyway" warning is shown
The copy that is shown for the warning text is aware of multihop, and will have a different text accordingly.
- - - …
=> Upgrade the UX in Daita scenarios

ios/CHANGELOG.md, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
This PR enables Daita in release builds, and adds an entry to the changelog about Daita.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6770)
=> Enable daita in release and add a changelog entry ios 777

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6772)
=> Fix VPN settings not being persisted

Cargo.lock, Cargo.toml, test/Cargo.lock, test/Cargo.toml, tunnel-obfuscation/src/shadowsocks.rs
This updates shadowsocks-rust to 1.20.3. Unblocks #6672.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6760)
=> Expose Shadowsocks fd on Android

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModelTest.kt
Also added a test that should cover the crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6777)
=> Fix crash in CustomListLocationViewModel when adding exactly one location to an existing list

ios/MullvadREST/ApiHandlers/RESTAPIProxy.swift, ios/MullvadREST/Relay/CachedRelays.swift, ios/MullvadREST/Relay/IPOverrideWrapper.swift, ios/MullvadREST/Relay/RelayCache.swift, ios/MullvadREST/Relay/StoredRelays.swift, ios/MullvadREST/Transport/Shadowsocks/ShadowsocksRelaySelector.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayCacheTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift, ios/MullvadVPNTests/MullvadSettings/IPOverrideWrapperTests.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
Instead of storing the parsed relays to disk we should store the raw json response. This will help us avoid old structure being read when doing migration to new object properties in our relay related data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6767)
=> Store the raw JSON payload from the getRelays API call

.github/workflows/rust-unused-dependencies.yml
Install `cbindgen` in `rust-unused-dependencies` workflow, which is missing since https://github.com/mullvad/mullvadvpn-app/pull/6684
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6757)
=> Install `cbindgen` in `rust-unused-dependencies` workflow

test/test-manager/src/tests/ui.rs
This PR simply adds `obfuscation.spec` to the arsenal of GUI e2e tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6756)
=> Run `obfuscation.spec.ts` in e2e tests

talpid-wireguard/build.rs
This PR removes `declare_libs_dir("../dist-assets/binaries");` for Android builds, which would add an unnecessary `rerun-if-changed` directive to `cargo`. This would cause `talpid-wireguard` to always rebuild on Android, since there are no android specific binaries which we should watch for changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6711)
=> Do not always rebuild `talpid-wireguard` on Android

android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/constant/TimeoutConstants.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/extension/UiAutomatorExtensions.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LoginTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/WebLinkTest.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/LoginMockApiTest.kt
Renamed test timeout constants to have more generic names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6764)
=> Rename test timeout constants

gui/src/renderer/components/main-view/FeatureIndicators.tsx
Currently feature indicators are presented sorted alphabetically (1, 11, 2 etc.). This PR changes the sorting to be numerically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6790)
=> Fix feature indicator sorting

gui/osv-scanner.toml, gui/package-lock.json
This PR updates `path-to-regexp` to `1.9.0` due to [GHSA-9wv6-86v2-598j](https://osv.dev/vulnerability/GHSA-9wv6-86v2-598j). We're not affected by this since we control the input.
I've also suppressed [GHSA-g974-hxvm-x689](https://osv.dev/vulnerability/GHSA-g974-hxvm-x689) due to there being no fix available. We're vulnerable to this since we have external translators that produce the input to `addTranslations()`. We will inspect translations thoroughly until this is fixed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6797)
=> Handle path-to-regexp and node-gettext-vulnerabilities

.github/workflows/osv-scanner-scheduled.yml
This job should only run on a daily schedule. There is a separate workflow for running on PRs.
The reason for disabling it is that it currently runs on every merge, but even if it fails, the PR owner is not notified anyway. And even if it does, it might not be related to their PR. The separate PR workflow should catch newly introduced CVE issues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6799)
=> Don't run the *scheduled* OSV scanner on pushes

gui/osv-scanner.toml
In https://github.com/mullvad/mullvadvpn-app/pull/6797 I forgot to set the correct CVE id, this PR fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6798)
=> Update node-gettext CVE id in gui/osv-scanner.toml

gui/src/renderer/components/main-view/ConnectionPanel.tsx
This fixes a bug where `toggleExpanded` doesn't check if the connection panel can be expanded. This was previously only done for `expand`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6803)
=> Only allow toggling connection island when connected/connecting

wireguard-go-rs/libwg/osv-scanner.toml
As far as I can tell, wireguard-go does not use any of affected code. The affected code is mostly just parsing of golang code anyway, which it makes no sense that wiregurad-go would use internally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6809)
=> Ignore GO-2024-3105, GO-2024-3107 and GO-2024-3106

mullvad-daemon/src/dns.rs, mullvad-daemon/src/lib.rs, talpid-core/src/dns/android.rs, talpid-core/src/dns/linux/mod.rs, talpid-core/src/dns/macos.rs, talpid-core/src/dns/mod.rs, talpid-core/src/dns/windows/auto.rs, talpid-core/src/dns/windows/iphlpapi.rs, talpid-core/src/dns/windows/mod.rs, talpid-core/src/dns/windows/netsh.rs, talpid-core/src/dns/windows/tcpip.rs, talpid-core/src/firewall/linux.rs, talpid-core/src/firewall/macos.rs, talpid-core/src/firewall/mod.rs, talpid-core/src/firewall/windows.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/disconnected_state.rs, talpid-core/src/tunnel_state_machine/disconnecting_state.rs, talpid-core/src/tunnel_state_machine/error_state.rs, talpid-core/src/tunnel_state_machine/mod.rs, windows/winfw/src/winfw/winfw.cpp, windows/winfw/src/winfw/winfw.h
This PR makes the tunnel state machine DNS configuration more flexible:
```rust
enum DnsConfig {
/// Use tunnel config gateway addresses
Default,
/// Use the specified addresses for DNS resolution
Override {
/// Addresses to configure on the tunnel interface
tunnel_config: Vec<IpAddr>,
/// Addresses to allow on non-tunnel interfaces
non_tunnel_config: Vec<IpAddr>,
},
}
```
Previously, the configuration consisted simply of a list of IPs (`Option<Vec<IpAddr>>`), and whether an IP was configured for the tunnel device or not was decided based on whether IPs were private/public.
Motivation: This makes it possible to ensure that certain private IPs, like IPv6 content blockers, are only allowed on the tunnel interface, without making the `talpid` universe aware of these IP ranges.
- - -
This …
=> Refactor tunnel state machine DNS configuration

ios/MullvadREST/Transport/Shadowsocks/ShadowsocksRelaySelector.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/View controllers/VPNSettings/CustomDNSViewController.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInfoButtonItem.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsPromptAlertItem.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift, ios/MullvadVPNTests/MullvadSettings/IPOverrideWrapperTests.swift, ios/PacketTunnelCore/Actor/ConnectionConfigurationBuilder.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
This PR resolves several build warnings by addressing issues related to `Swiftlint`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6792)
=> Build warnings

talpid-wireguard/src/lib.rs
Address a race condition in `WireguardMonitor::start` where a Wireguard-GO tunnel would be started but try to serve traffic before actually being ready to do so. This is probably a latent issue on all platforms using Wireguard-GO, but it was mostly noticeable on Android.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6806)
=> Fix negotiation of ephemeral peer failing due to timeout

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift, ios/PacketTunnel/WireGuardAdapter/WireGuardAdapterError+Localization.swift, ios/PacketTunnelCore/Pinger/Pinger.swift, ios/PacketTunnelCore/Pinger/PingerProtocol.swift, ios/PacketTunnelCore/Pinger/TunnelPinger.swift, ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift, ios/PacketTunnelCoreTests/Mocks/PingerMock.swift, ios/PacketTunnelCoreTests/PingerTests.swift
This depends on the IAN changes to `wireguard-apple`, and implements a Pinger named `TunnelPinger` which uses the tunnel's WireGuard-based ICMP ECHO capabilities to send and receive pings. The Pinger protocol has been modified, moving the address to the setup phase in accordance with how WireGuard ICMP sockets like it. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6802)
=> Add IAN-based TunnelPinger, refactoring the pinger protocol accordingly.

android/docker/Dockerfile
This PR aims to add `cbindgen` as part of the Android build container. This is an improvement to how it was added in multiple build scripts and workflows in #6684 as well as #6808 and #6757 (which will be partially reverted after the new container image has been published). We also aim to improve this further as part of our internal issue: DROID-1328.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6811)
=> Add cbindgen to the android build container

mullvad-cli/src/format.rs
Fixes a regression in the CLI since last stable release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6815)
=> Fix `mullvad status -v` not printing udp2tcp port and transport protocol

ios/MullvadVPNTests/MullvadVPN/PacketTunnel/DeviceCheck/DeviceCheckOperationTests.swift, ios/PacketTunnel/DeviceCheck/DeviceCheckOperation.swift, ios/PacketTunnel/PacketTunnelProvider/DeviceChecker.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
This PR makes sure that when a device check error happens on each connection of the Packet Tunnel,  we do enter the error state instead of silently logging the issue and doing nothing.
When this happens, the users will be told via the in app banner that they will have to log out and log in again because their device's integrity couldn't be checked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6813)
=> Make the packet tunnel enter error state when failing device check

.github/workflows/cargo-audit.yml, Cargo.lock, deny.toml, osv-scanner.toml, talpid-core/Cargo.toml, talpid-core/src/split_tunnel/windows/driver.rs
This PR resolves #6747.
Fix `cargo deny` complaining about `proc-macro-error` being unmaintained by upgrading `nftnl` to a version which no longer depends on `err-derive`, which in turn depended on `proc-macro-error`.
This PR also upgrades `bitflags` to `2.6.0` from `2.5.0` in `talpid-core`. Version `2.6.0` is pinned by `nftnl` for some reason, and `cargo` was unhappy with having both `2.5.0` and `2.6.0` in the same crate.
With this change we also drop 5 direct dependencies, and even more indirect dependencies! :tada:
Fixes DES-1228
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6748)
=> Upgrade `nftnl` to fix `cargo deny` error

gui/src/renderer/components/main-view/FeatureIndicators.tsx
Feature indicators and the ellipsis could remain if they went from visible to hidden without switching views. This was because we didn't set `visibility: hidden`. When the `StyledFeatureIndicatorLabel` component is rendered it's set to `hidden` but since the visibility is updated with plain JS the react virtual dom doesn't reflect that update and doesn't reset the visibility to hidden on rerenders.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6819)
=> Fix hide feature indicators

ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/View controllers/Settings/SettingsCell.swift, ios/MullvadVPN/View controllers/VPNSettings/CustomDNSCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift
Currently there is no way to know that you have content blockers enabled unless you expand the tree.
This first iteration would have an "All" switch that activates all toggles - and the number of activated toggles would be shown at the top level. 
Toggling "All" would activate all the other toggles. But if the user then deactivates a toggle, "All" would have to be deactivated as well since all of them are not activated. Only by actively deactivating "All" does the user deactivate all the other toggles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6800)
=> Add counter and 'all' switch to DNS content blockers

.github/workflows/android-app.yml, .github/workflows/rust-unused-dependencies.yml, android/BuildInstructions.md, android/docs/BuildInstructions.macos.md, build-apk.sh, building/android-container-image.txt
This PR aims to bump the android container to a new version that includes `cbindgen`. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6826)
=> Bump android container to 7b4ffb683

Cargo.lock, Cargo.toml, mullvad-encrypted-dns-proxy/Cargo.toml, mullvad-encrypted-dns-proxy/examples/forwarder.rs, mullvad-encrypted-dns-proxy/src/config/mod.rs, mullvad-encrypted-dns-proxy/src/config/plain.rs, mullvad-encrypted-dns-proxy/src/config/xor.rs, mullvad-encrypted-dns-proxy/src/config_resolver.rs, mullvad-encrypted-dns-proxy/src/forwarder.rs, mullvad-encrypted-dns-proxy/src/lib.rs, mullvad-ios/Cargo.toml
I've added a crate that will enable us to use `apisocks5` from our Rust code. It can:
- Resolve configs from arbitrary domain names
- Create proxy configurations form IPv6 addresses
- Use said proxy configurations to proxy data to our API
The `rustls` client configuration looks eerily similar to that of the `mullvad-api`'s client config, but I am not sure if it should be reused. I half-expect this crate to be a dependency of `mullvad-api` in one way or another, but I can also remove the AsyncRead and AsyncWrite impls for the `Forwarder`. I also expect my crusty rust code to not be quite up to spec with the best way to write code in September of 2024, so you needn't be gentle. 
Also, this is a sign to have a healthy discussion as to why this crate _shouldn't_ be named …
=> Add mullvad-encrypted-dns-proxy crate for API obfuscation

android/config/dependency-check-suppression.xml, android/gradle/osv-scanner.toml, android/test/test-suppression.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6830)
=> Suppress CVE-2024-7254

test/test-manager/src/logging.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/tunnel_state.rs
Use the same format everywhere. Also add timestamps to test result output.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6835)
=> Clean up timestamps in test logs

ios/MullvadVPN/Notifications/Notification Providers/AccountExpiry.swift, ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/NotificationConfiguration.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPNTests/MullvadVPN/Notifications/NotificationProviders/AccountExpiryTests.swift
Currently the iOS app sends but a single notification about running out of time. 
We should schedule 4 in-app notifications, with improved copy:
- "You have 3 days left on this account."
- “You have 2 days left on this account.”
- “You have 1 day left on this account.”
- "You have less than a day left on this account. Please add more time to continue using the VPN.”
We should also schedule 3 system notifications, with improved copy:
- "You have 3 days left on this account. Please add more time to continue using the VPN.."
- “You have one day left on this account. Please add more time to continue using the VPN.”
- "Blocking internet: Your time on this account has expired. To continue using the internet, please add more time or disconnect the VPN.”
- - - …
=> Fix out-of-time notifications

ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
As discussed, we should not force the Packet Tunnel Actor to enter the blocked state if the device checker
encounters a generic network error, because this request already went through the tunnel.
Unreliable networks should not make the app enter the blocked state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6856)
=> Do not enter blocked state if device check has network errors

ios/MullvadVPNUITests/AccountTests.swift, ios/MullvadVPNUITests/Base/BaseUITestCase.swift, ios/MullvadVPNUITests/Networking/MullvadAPIWrapper.swift
End to end test runs on PR updates were hitting the app API rate limit because accounts were created too often from the office IP address. With the changes in this PR accounts will be created using partner API if a partner API token is available, else fall back to app API. Also fail messages have been improved.
The changes in this PR can be tested by running end to end tests, especially the tests under `AccountTests`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6788)
=> Create accounts using partner API when available

android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/OutOfTimeUseCaseTest.kt
The awaitItem() method from Turbine is used which causes delays to be skipped. This causes some tests to behave incorrectly where we want to assert that a given value is emitted after a specific delay. The solution is to instead use the expectMostRecentItem() method when we want to assert that an item has been emitted at a given point in time.
Further reading:
https://medium.com/@hi.enricog/explore-testing-coroutines-with-runtest-by-examples-4c4274a86a83
https://github.com/cashapp/turbine/issues/265
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6842)
=> Fix out of time use case virtual time tests

talpid-tunnel-config-client/Cargo.toml, talpid-tunnel-config-client/src/lib.rs, talpid-tunnel-config-client/src/socket.rs, talpid-wireguard/Cargo.toml, talpid-wireguard/src/ephemeral.rs, talpid-wireguard/src/lib.rs
`IP_USER_MTU` doesn't work like MSS, which can cause PQ negotiation to fail on Windows when the MTU is incorrectly configured (see https://github.com/mullvad/mullvadvpn-app/actions/runs/10975572685/job/30475498014).
This PR fixes this by lowering the tunnel interface MTU during ephemeral peer negotiation.
Fix DES-1257.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6836)
=> Lower MTU during ephemeral peer negotiation

CHANGELOG.md, mullvad-types/src/wireguard.rs
Close DES-559.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6804)
=> Enable quantum resistant tunnels by default on Windows

Cargo.lock, Cargo.toml, mullvad-api/Cargo.toml, mullvad-cli/Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-ios/Cargo.toml, mullvad-ios/src/ephemeral_peer_proxy/ios_runtime.rs, mullvad-jni/Cargo.toml, mullvad-management-interface/Cargo.toml, mullvad-management-interface/src/lib.rs, talpid-core/Cargo.toml, talpid-openvpn-plugin/Cargo.toml, talpid-openvpn-plugin/src/processing.rs, talpid-openvpn/Cargo.toml, talpid-routing/Cargo.toml, talpid-tunnel-config-client/Cargo.toml, talpid-tunnel-config-client/src/lib.rs, talpid-tunnel/Cargo.toml, talpid-windows/Cargo.toml, talpid-wireguard/Cargo.toml, test/Cargo.lock, test/Cargo.toml, test/test-manager/Cargo.toml, test/test-manager/src/mullvad_daemon.rs
Upgrade `tonic` to version 0.12, as a prerequisite to later on upgrading `hyper`.
As of version 1, `hyper` no longer uses tokios `AsyncWriter` and `AsyncReader` traits, instead defining its own versions, see <https://github.com/hyperium/hyper/issues/3110>. As tonic `0.12` is updated to use the `hyper 1.0` ecosystem, it changed some of its trait-bounds to the new `hyper` traits. The `hyper-utils` crate provides the wrapper `TokioIo`, which converts between the two.
`prost` had to be upgraded as well, for compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6847)
=> Upgrade `tonic` and `prost`

CHANGELOG.md, talpid-core/src/dns/macos.rs
If the resolver is set to (e.g.) `127.0.0.1`, don't replace it with `10.64.0.1`. Hopefully prevents some fighting with other software.
This does not change affect any of the firewall rules.
Close DES-1227.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6861)
=> Don't hijack DNS config when localhost is used

CHANGELOG.md, gui/locales/messages.pot, gui/src/main/daemon-rpc.ts, gui/src/main/default-settings.ts, gui/src/main/index.ts, gui/src/main/platform-version.ts, gui/src/main/settings.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/Settings.tsx, gui/src/renderer/redux/settings/actions.ts, gui/src/renderer/redux/settings/reducers.ts, gui/src/renderer/redux/userinterface/actions.ts, gui/src/renderer/redux/userinterface/reducers.ts, gui/src/shared/daemon-rpc-types.ts, gui/src/shared/ipc-schema.ts, gui/test/e2e/setup/main.ts, mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/settings.rs, mullvad-types/src/settings/mod.rs, talpid-core/src/firewall/macos.rs, talpid-core/src/firewall/mod.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/disconnected_state.rs, talpid-core/src/tunnel_state_machine/disconnecting_state.rs, talpid-core/src/tunnel_state_machine/error_state.rs, talpid-core/src/tunnel_state_machine/mod.rs
This is a temporary mitigation of the MacOS 15 issues with iMessage, etc. It works by simply allowing packets through the firewall on the physical interface if the destination is one of a few specific apple-owned networks. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6859)
=> Add setting for unblocking APNS networks

.github/workflows/android-validate-gradle-wrapper.yml
This prevents the following possible ways of commiting a malicious gradle-wrapper.jar to the repository:
* Commiting to another path than the one previously specified
* Pushing to `main` without going through a PR
Please see these three comments for context: https://github.com/ossf/scorecard/pull/4097#issuecomment-2371193844
I have not yet verified if scorecard will treat this new setup as a warning or not. But my impression was that the `scorecard` contributor in the comments sort of agreed that their verifier should be updated anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6863)
=> Run android-validate-gradle-wrapper on every matching push

mullvad-api/src/availability.rs, mullvad-api/src/lib.rs, mullvad-api/src/rest.rs, mullvad-daemon/src/api.rs, mullvad-daemon/src/device/service.rs, mullvad-daemon/src/relay_list/mod.rs, mullvad-daemon/src/version_check.rs
This PR consolidates two mutexes found in the `ApiAvailability` struct into a single one. We managed to run into a deadlock once where `mullvad-daemon` would not progress from the `Disconnecting` state due to us trying to acquire a mutex which was never released by another task. Reproducing the exact issue is of course very hard, but this PR aims to make it easier to reason about deadlocks in `ApiAvailability` by consolidating multiple mutexes into a single one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6860)
=> Avoid potential deadlock in `mullvad-api`

ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, mullvad-encrypted-dns-proxy/src/config/mod.rs, mullvad-encrypted-dns-proxy/src/config_resolver.rs, mullvad-ios/src/encrypted_dns_proxy.rs, mullvad-ios/src/ephemeral_peer_proxy/mod.rs, mullvad-ios/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6846)
=> Use encrypted dns proxy in `mullvad-ios`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/AccountExpiryNotificationUseCase.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/OutOfTimeViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/WelcomeViewModel.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryConstant.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6822)
=> Align internal and external notification expiry

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
We've made some small changes to fix DAITA and the makefile. Let's use them in `main`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6867)
=> Bump wireguard-apple to include multihop fix

test/Cargo.lock, test/Cargo.toml, test/test-manager/Cargo.toml, test/test-rpc/Cargo.toml, test/test-rpc/src/net.rs
First step and proof of concept before upgrading `hyper` in the app repo.
Multiple other crates had to be updates for compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6858)
=> Upgrade to `hyper` version 1 in test framework

CHANGELOG.md, mullvad-types/src/settings/mod.rs
Fix DES-449.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6853)
=> Enable IPv6 by default on macOS

android/CHANGELOG.md, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreenTest.kt, android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/VpnSettingsUiStatePreviewParameterProvider.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/VpnSettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/VpnSettingsUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/BootCompletedReceiver.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/SettingsRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModel.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelState.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/repository/AutoStartAndConnectOnBootRepositoryTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/VpnSettingsViewModelTest.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/SetAutoConnectError.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/Settings.kt, android/lib/resource/src/main/res/values/strings.xml, gui/locales/messages.pot, mullvad-daemon/src/settings/mod.rs
This PR does three things:
1. Add a connect on boot feature for devices that does not vpn settings (mostly TV)
2. Disables the auo-connect feauture for all devices.
3. Remove the auto-connect feature from the ui for all devices.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6761)
=> Add autostart on TV and remove auto connect feature on android

mullvad-api/Cargo.toml, mullvad-api/src/availability.rs, mullvad-api/src/lib.rs
This fixes the issue introduced yesterday where API requests are incorrectly paused.
Also, some unit tests were added. 🎉 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6872)
=> Fix API request timer regression

mullvad-relay-selector/src/relay_selector/helpers.rs, mullvad-relay-selector/src/relay_selector/mod.rs
All other helper methods for selecting random relays are there. So I thought it would be easier to read if we have them all in one place. Renaming the function to align more consistently with the others at the same time.
I also added tiny amount of docs. And "fixed" a lifetime nitpick.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6873)
=> Move pick_random_relay_excluding to helpers module for consistency

dist-assets/linux/before-install.sh
This PR removes an old workaround in the `before-install.sh` script which is supposedly not required any longer :broom:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6878)
=> Address TODO comment in `before-install.sh`

ios/CHANGELOG.md, ios/MullvadTypes/AnyIPAddress.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel+Persistent.swift, ios/MullvadVPNTests/MullvadTypes/AnyIPAddressTests.swift
Acceptance criteria:
- Adding IPv6 addresses should work, whilst the app should still reject any arbitrary unsigned 32 bit integer instead of interpreting that as an IPv4 address.
- Custom DNS and API access method code should use the same validation for IP addresses.
- Using IPv6 addresses in custom API methods and custom DNS works.
- The validation code must be unit tested.
- When this is fixed, it should be mentioned in the changelog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6852)
=> Fix IPv6 parsing in API access methods and custom DNS

ci/linux-repository-builder/build-linux-repositories-config.sh
This PR prepares the repository generation for the upcoming Ubuntu release "Oracular Oriole" with code name `oracular` which is due to be released in the coming weeks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6883)
=> Add oracular to list of ubuntu versions to generate deb repositories for

ios/MullvadREST/Transport/ProxyConfigurationTransportProvider.swift, ios/MullvadREST/Transport/TransportProvider.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
This PR makes it so that only a single instance of `EncryptedDNSTransport` is ever used in either process.
This should only be merged after https://github.com/mullvad/mullvadvpn-app/pull/6874
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6875)
=> Fix connection method test ios 843

wireguard-go-rs/libwg/Android.mk
Without this, go will try to include version control information in Go binaries, which won't work in certain build environments (e.g. container builds with docker).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6889)
=> Add flag buildvcs=false when building libwg

mullvad-ios/src/encrypted_dns_proxy.rs
On a lazy Thursday evening, I let my neuroticism have the wheel and out came this small improvement in legibility for the encrypted DNS proxy configuration picker.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6882)
=> Simplify configuration selection for encrypted dns

gui/gulpfile.js, gui/src/renderer/app.tsx
This PR enables React Strict mode. When I first enabled it I noticed that it was on in production as well, which led me to find out that we never compiler the app with the environment set to production. This has been fixed in this PR as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6892)
=> Enable React Strict mode

ios/BuildInstructions.md, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPNUITests/Screenshots/SnapshotHelper.swift, ios/build-rust-library.sh
This PR removes all references to the x86_64 architecture from the iOS CI pipeline and build scripts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6868)
=> Remove all x86_64 mentions from iOS CI and build scripts

windows/driverlogic/driverlogic.vcxproj
Previously, the precompiled header was incorrectly created for every source file. This caused the build to fail sometimes. The PR fixes it by only building it for `stdafx.cpp`.
Fix DES-1241.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6902)
=> Fix build of precompiled header in driverlogic

mullvad-api/src/lib.rs
I'm trying to run the daemon against stagemole. I found a bug! :partying_face: 
When the override is done with only `MULLVAD_API_HOST` it should look up the IP via DNS. This part works but, it uses the wrong hostname. In this code path we never update `api.host`, resulting it in falling back to the default (`api.mullvad.net`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6893)
=> Fix bug when overriding API with only MULLVAD_API_HOST

ci/buildserver-build.sh, gui/tasks/distribution.js, test/scripts/test-utils.sh
Until we have the universal Windows installer we want to upload the x64 installer but without the architecture suffix. This is to avoid making changes to other parts of the release process in the meanwhile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6885)
=> Rename x86 windows installer to not include the architechture in the name

ios/MullvadREST/Relay/RelayPicking.swift, ios/MullvadSettings/DAITASettings.swift, ios/MullvadVPN/Coordinators/LocationCoordinator.swift, ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift, ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift, ios/MullvadVPNTests/MullvadREST/Relay/MultihopDecisionFlowTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift, ios/MullvadVPNTests/MullvadSettings/TunnelSettingsUpdateTests.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6870)
=> Add smart routing to daita settings data

CHANGELOG.md, Cargo.lock, Cargo.toml, talpid-core/Cargo.toml, talpid-core/src/firewall/macos.rs, talpid-core/src/firewall/mod.rs, talpid-core/src/lib.rs, talpid-core/src/resolver.rs, talpid-core/src/split_tunnel/macos/mod.rs, talpid-core/src/split_tunnel/macos/process.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/disconnected_state.rs, talpid-macos/Cargo.toml, talpid-macos/src/lib.rs, talpid-macos/src/process.rs
This allows us to force queries to be sent on the tunnel interface. It will also let us control whether to return IPv6 addresses regardless of whether the primary interface has enabled them.
Fix DES-1279.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6890)
=> Proxy DNS lookups through a local resolver on macOS

building/linux-container-image.txt
We usually don't bump to the latest Rust version this fast. But Rust 1.81 will be needed for the dependency we want to use for ML-KEM (#6915).
We also need to build and bump the Android container. But desktop comes first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6917)
=> Bump Linux container to 2301dbd5b with Rust 1.81

CHANGELOG.md, talpid-core/src/firewall/macos.rs, talpid-core/src/firewall/mod.rs, talpid-core/src/split_tunnel/macos/tun.rs
This PR prevents incoming packets from private IPs from being forwarded to the VPN tun, which previously caused incoming packets on the LAN (notably/noticeably ICMP) to be duplicated.
The correct implementation would be to forward only packets that weren't originally sent via the VPN utun. For simplicity, the proposed implementation discards packets destined for private IP ranges. This is so we don't have to rely on the routing table.
Unrelatedly, don't kill states related to API traffic (`allowed_endpoint`) when flushing PF states.
Fix DES-1217.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6924)
=> Fix duplicated incoming packets when split tunneling is enabled

Cargo.lock, test/Cargo.lock
This PR closes https://github.com/mullvad/mullvadvpn-app/issues/6932
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6933)
=> Bump `futures-util` since the previous version was yanked

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CreateCustomListDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomListNameTextField.kt
I could not reproduce the bug with using KeyboardType.Text on Android TV with gboard so this change should be safe. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6925)
=> Fix non-English IME input in custom list input

.github/workflows/ios-end-to-end-tests-settings-migration.yml
One `$` too many breaks the settings migration test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6937)
=> Fix yaml typo in settings migration test

android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/ManagementService.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/FeatureIndicator.kt, gui/locales/messages.pot, gui/src/main/daemon-rpc.ts, gui/src/main/grpc-type-convertions.ts, gui/src/main/settings.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/DaitaSettings.tsx, gui/src/renderer/components/main-view/FeatureIndicators.tsx, gui/src/renderer/components/select-location/RelayListContext.tsx, gui/src/renderer/components/select-location/SelectLocation.tsx, gui/src/renderer/lib/filter-locations.ts, gui/src/shared/daemon-rpc-types.ts, gui/src/shared/ipc-schema.ts, mullvad-cli/src/cmds/tunnel.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/client.rs, mullvad-management-interface/src/types/conversions/features.rs, mullvad-management-interface/src/types/conversions/wireguard.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/src/relay_selector/query.rs, mullvad-relay-selector/tests/relay_selector.rs, mullvad-types/src/features.rs, mullvad-types/src/wireguard.rs, test/test-manager/src/tests/daita.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6935)
=> Replace "smart routing" with "direct only"

gui/locales/messages.pot, gui/src/renderer/components/DaitaSettings.tsx
This PR improves the strings in the DAITA view by referencing the translation for "Direct only" where it is reused in help-texts, and references the non-translatable string "WireGuard" correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6940)
=> Improve strings in the DAITA view

ios/MullvadREST/Relay/MultihopDecisionFlow.swift, ios/MullvadREST/Relay/RelayPicking.swift, ios/MullvadREST/Relay/RelaySelector+Wireguard.swift, ios/MullvadREST/Relay/RelaySelectorWrapper.swift, ios/MullvadSettings/DAITASettings.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPNTests/MullvadREST/Relay/MultihopDecisionFlowTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorWrapperTests.swift, ios/MullvadVPNTests/MullvadSettings/DAITASettingsTests.swift
Currently, smart routing picks a random DAITA relay. It should pick the closest relay using the haversine distance. It should group relays that are the same distance away and use the roulette wheel selection algorithm to pick one between the group of closest relays.
Also includes: [update-the-relay-selector-wrapper-to-enable-smart-routing-ios-832](https://linear.app/mullvad/issue/IOS-832/update-the-relay-selector-wrapper-to-enable-smart-routing-for-multihop)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6871)
=> Fix smart routing algorithm to select closest relay

ios/MullvadLogging/LogFileOutputStream.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift, ios/MullvadVPNTests/MullvadLogging/LoggingTests.swift
The test `testRotatingActiveLogWhenSizeLimitIsExceeded` has been failing on the CI for a while. This PR enables forced synchronization of the asynchronous writes in that tests and similar to it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6936)
=> Fix failing log rotation test

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionPanelView.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift, ios/MullvadVPNUITests/Pages/TunnelControlPage.swift, ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift, ios/MullvadVPNUITests/RelayTests.swift
This PR adds an end-to-end test for Multihop and fixes minor issues, such as the shrinking of the collapse button in the connection view. Additionally, after changing the data type for the collapse view, we forgot to update the UI tests to ensure compatibility in finding elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6914)
=> Add end to end connection tests for multihop ios 778

ios/MullvadREST/RetryStrategy/RetryStrategy.swift, ios/MullvadSettings/MigrationManager.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPNTests/MullvadSettings/MigrationManagerMultiProcessUpgradeTests.swift, ios/MullvadVPNTests/MullvadSettings/MigrationManagerTests.swift, ios/MullvadVPNTests/MullvadTypes/FileCacheTests.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
This PR adds the ability for the PacketTunnel settings to perform settings migration.
The net benefit of this is that users that have automatic app updates turned on won't have to manually disconnect and reconnect from the VPN when the updates itself, the upgrade should be transparent for them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6938)
=> Allow settings migration from packet tunnel

ios/MullvadSettings/TunnelSettingsV6.swift, ios/MullvadVPN/Coordinators/LocationCoordinator.swift
Reproduction steps:
- Launch the app, make sure all options are off
- Select a Sweden relay and connect normally
- Disconnect
- Turn on both Daita and Direct connection
- Tap on Secure connection and enter blocked state
- Tap on Select location
What happens
- The location list is empy, and the user cannot select any relays to exit blocked state
- If the user disconnects, and tries to select a relay when the VPN is not running, the Daita + Direct mode filter works as intended
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6952)
=> Fix no relays when in blocked state triggered by Daita

ios/PacketTunnelCore/Pinger/TunnelPinger.swift
This PR fixes a race condition where we would get parse error from the pinger due to pending reads when closing its socket.
The fix is to look at whether the `destAddress` is still valid (i.e. socket is still open) before sending the parsing error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6953)
=> Ignore parse errors from pinger when its socket is closed

.github/workflows/frontend.yml, gui/test/e2e/mocked/mocked-utils.ts
This PR disables the chromium sandbox when running the e2e tests in GitHub actions on Linux runners. This is due to AppArmor restrictions.
Fixes DES-1161.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6970)
=> Disable chromium sandbox when running e2e tests on Linux in GitHub actions

gui/locales/messages.pot, gui/src/renderer/components/Filter.tsx, gui/src/renderer/components/VpnSettings.tsx, gui/src/renderer/components/select-location/RelayListContext.tsx, gui/src/renderer/lib/filter-locations.ts, gui/src/renderer/lib/utilityHooks.ts
This PR makes the OpenVPN alternative in VPN settings unavailable when a core privacy feature is enabled (DAITA, Multihop, Quantum-resistant tunnel). Texts aren't finished yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6959)
=> Disable OpenVPN option when a core privacy feature is enabled

ios/MullvadREST/ApiHandlers/RESTURLSession.swift, ios/MullvadREST/ApiHandlers/SSLPinningURLSessionDelegate.swift, ios/MullvadREST/Transport/ProxyConfigurationTransportProvider.swift, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
This PR adds the ability for `SSLPinningURLSessionDelegate` to also check for addresses in the `AddressCache` 
which means that rotating the IP address of the API endpoint shouldn't result in invalid SSL errors anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6978)
=> Check AddressCache as well when overriding hostname for SSL validation

.github/workflows/ios-end-to-end-tests-api.yml, .github/workflows/ios-end-to-end-tests-merge-to-main.yml, .github/workflows/ios-end-to-end-tests-nightly.yml
If secrets are not passed explicitly to the called reused action, the called action will not have access to them. Since the secrets contain the device UUID and the partner API token, the tests which invoke the end-to-end action should allow it access to the secrets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6984)
=> Pass secrets to reused workflow

android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/misc/CaptureScreenRecordingsExtension.kt, android/test/e2e/README.md, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/EndToEndTest.kt
Added video recording for all end to end tests. The videos are stored in `/sdcard/Download/test-attachments/video` on the test device. To try out the changes run any test(s) and see produced videos in this directory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6912)
=> Add video recording of e2e tests

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/CreateAccountConfirmationDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/LoginScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/LoginViewModelTest.kt, android/lib/resource/src/main/res/values/strings.xml, android/lib/shared/src/main/kotlin/net/mullvad/mullvadvpn/lib/shared/AccountRepository.kt, gui/locales/messages.pot
Now showing a confirmation dialog when creating an account when the user has already logged in on another account on the device. The text is a placeholder and needs to be decided on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6951)
=> Show create account confirm when user has account

Cargo.lock, Cargo.toml, mullvad-api/Cargo.toml, mullvad-api/src/abortable_stream.rs, mullvad-api/src/https_client_with_sni.rs, mullvad-api/src/lib.rs, mullvad-api/src/proxy.rs, mullvad-api/src/relay_list.rs, mullvad-api/src/rest.rs, mullvad-api/src/tls_stream.rs, mullvad-daemon/src/geoip.rs, test/Cargo.lock, test/Cargo.toml, test/connection-checker/Cargo.toml, test/test-rpc/src/net.rs
Fixes DES-1270
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6898)
=> Upgrade to Hyper version 1

gui/osv-scanner.toml
This PR extends the OSV scanner suppression for `node-gettext` by three months and updates the reason to include that we are not affected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7002)
=> Update node-gettext osv-scanner suppression

.github/workflows/cargo-audit.yml
Our cargo audit CI job breaks for some reason: https://github.com/mullvad/mullvadvpn-app/actions/runs/11398684502/job/31716118294. I saw we were not on the latest version. So I figured just upgrading the action could help
Pin to commit since that's best practice. We might eventually start doing that for all third party actions, but that's a separate discussion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7009)
=> Upgrade cargo audit CI action ta latest version

ios/CHANGELOG.md, ios/MullvadVPN/AppDelegate.swift
On first-time install the app fails the check for wiping all settings (unlike when launching app after being reinstalled). This leads to no default settings being written and - as a result - the blocked state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7006)
=> Fix app going into blocked state on first-time installs

gui/test/e2e/installed/state-dependent/settings.spec.ts, gui/test/e2e/utils.ts, test/Cargo.lock, test/scripts/ssh-setup.sh, test/test-manager/src/tests/ui.rs, test/test-runner/Cargo.toml, test/test-runner/src/main.rs
Add settings e2e test that tests:
- That the auto-connect and launch on start-up settings work as expected and together toggles the daemon auto-connect
- That the Local network sharing toggle toggles the daemon setting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6776)
=> Add settings e2e test

talpid-core/src/dns/mod.rs, talpid-core/src/firewall/macos.rs, talpid-core/src/tunnel_state_machine/connected_state.rs
This allows custom DNS to point to localhost without our resolver hijacking all of the things.
Fix DES-1309.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7001)
=> Disable DNS redirect rule when custom DNS is set to localhost

mullvad-encrypted-dns-proxy/src/lib.rs, mullvad-encrypted-dns-proxy/src/state.rs, mullvad-ios/src/encrypted_dns_proxy.rs
Move the Encrypted DNS config selection algorithm to the `mullvad-encrypted-dns-proxy` crate where both `mullvad-ios` and `mullvad-daemon` can consume it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7008)
=> Move encrypted DNS state to crate shared between iOS and everyeone else

ios/MullvadREST/Relay/MultihopDecisionFlow.swift, ios/MullvadREST/Relay/RelayPicking.swift, ios/MullvadREST/Relay/RelaySelectorWrapper.swift, ios/MullvadSettings/DAITASettings.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AppRoutes.swift, ios/MullvadVPN/Coordinators/AccountCoordinator.swift, ios/MullvadVPN/Coordinators/LocationCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift, ios/MullvadVPN/View controllers/SelectLocation/DAITAInfoView.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift, ios/MullvadVPN/View controllers/Settings/SettingsInfoButtonItem.swift, ios/MullvadVPN/View controllers/Settings/SettingsInteractor.swift, ios/MullvadVPNTests/MullvadREST/Relay/MultihopDecisionFlowTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift, ios/MullvadVPNTests/MullvadSettings/DAITASettingsTests.swift
When smart routing and multihop are enabled, the entry selection view should be updated to explain to the user that they cannot change an entry location when DAITA is on and Direct only is off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6950)
=> Update the select location view

gui/osv-scanner.toml
This PR suppresses the osv-scanner `elliptic` vulnerability. We are not affected by the vulnerability since we don't use the signing capabilites of `browserify`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7015)
=> Ignore elliptic vulnerability

docs/known-issues.md, docs/security.md
This PR adds a dedicated known security and privacy issues document. This takes the known issues we had in the `security.md` document along with issues spread out in various other places and aims to consolidate them in one publicly accessible document.
The aim of doing this is to:
* Be more transparent to our users about known problems affecting our app and service. We usually blog about these things. But blogs are more ephemeral. All known privacy and security issues should be kept in this document for as long as they still affect the app and its users.
* Consolidate a bunch of spread out sources into one easier to digest list of issuses.
* Gather all known information on an issue in a single place. Such as links to blog posts about it and upstream bug reports.
- - - …
=> Add known issues documentation

CHANGELOG.md, mullvad-daemon/src/lib.rs, mullvad-relay-selector/src/error.rs, mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/relay_selector/helpers.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/src/relay_selector/query.rs, mullvad-relay-selector/src/relay_selector/relays.rs, mullvad-relay-selector/tests/relay_selector.rs
This PR includes changes to `mullvad-relay-selector` for making Smart routing override Multihop. It also includes some drive-by changes intended to make it easier to follow what's happening in the relay selector.
If both multihop and DAITA (with smart routing) is enabled, a DAITA-enabled entry relay will be selected. If the user has selected an entry relay which is not DAITA-enabled, the relay selector will override the user's choice and force a DAITA-enabled relay as entry. If smart routing is subsequently disabled, the user's selected entry will always be selected even if this means that the user will end up in a blocked state.
- - - …
=> Make Smart routing override Multihop

.github/workflows/ios-screenshots-creation.yml, .github/workflows/ios-screenshots-tests.yml, .github/workflows/ios-validate-build-schemas.yml, .github/workflows/ios.yml, ios/BuildInstructions.md, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/MullvadVPNUITests/README.md, ios/build-wireguard-go.sh
I've recently added changes to `wireguard-apple` to use the multihop tunnel implementation from our fork of `wireguard-go`. Incidentally, our fork of `wireguard-go` has bumped their dependency of go to `1.21`. So, along with the commit bump, come changes to the build scripts, CI scripts and READMEs.
When building this locally, remember to clear your build folder, otherwise the build will fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6999)
=> Bumping wireguard-apple

.github/actions/run-ios-e2e-tests/action.yml, .github/workflows/ios-end-to-end-tests.yml
It seems that our tests sometimes fail to find json files that should be there. This might be due to checking out files via git in a previous execution context that isn't then passed over to the next GitHub actions step. So, I am throwing a `sync` at the wall and trying to see if it helps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7000)
=> Force a sync of the whole system before reading config

mullvad-encrypted-dns-proxy/src/forwarder.rs
I noticed while working on https://github.com/mullvad/mullvadvpn-app/pull/7010 that for Android, we would like to access the underlying socket used by `Forwarder` because we would like to propagate its raw file descriptor back to the Android client before actually connecting. This PR adds `Forwarder::from_stream`, which allows you to bring your own TCP socket.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7025)
=> Generalize Encrypted DNS proxy forwarder

ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
The whole Daita section should be hidden when the user is logged out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7027)
=> Hide Daita section in settings when logged out

ios/MullvadVPN/Extensions/UIImage+Helpers.swift, ios/MullvadVPN/Views/AppButton.swift, ios/MullvadVPN/Views/CustomButton.swift
The issue was that the `AppButton` was messing with the button's alpha when switching between normal and disabled states to keep a nice look for the disabled mode. At the same time, the disconnectButton was getting shown and hidden using its alpha value. This conflicts in how we were handling alpha values caused the problem.
To fix it, I added a function that creates a new image with the opacity for the UIButton's background. Now, I apply the alpha to that image instead of changing the UIButton's alpha directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7035)
=> resolve alpha button override issues in configuration

ios/MullvadVPN/UI appearance/UIColor+Palette.swift, ios/MullvadVPN/Views/AppButton.swift, ios/MullvadVPN/Views/CustomButton.swift
This PR sets the color to white with 0.2 opacity for the disabled state of the AppButton.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7040)
=> Fix text color for disabled state

.github/workflows/desktop-e2e.yml, test/scripts/test-utils.sh
This PR fixes a few issue regarding how the test framework used tags when constructing the path to the build artifact.
* The regex which parsed the build version was broken because it included quotation marks. 
* The test framework never pruned tags, which made it use local tags even when they were outdated.
* The buildserver scripts remove forbidden characters from the "+$tag" suffix , which is now mirrored by the test framework.
I also split the parsing of build version regex from the function that decides if a build is a dev version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6993)
=> Fix parsing of build tags

gui/locales/messages.pot, gui/src/main/default-settings.ts, gui/src/main/grpc-type-convertions.ts, gui/src/renderer/components/ApiAccessMethods.tsx, gui/src/renderer/components/ContextMenu.tsx, gui/src/renderer/components/InfoButton.tsx, gui/src/renderer/components/cell/Label.tsx, gui/src/shared/daemon-rpc-types.ts, gui/test/e2e/installed/state-dependent/api-access-methods.spec.ts
This PR adds the GUI bits of https://github.com/mullvad/mullvadvpn-app/pull/7010.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7013)
=> Implement encrypted dns proxy in Electron GUI

tunnel-obfuscation/src/shadowsocks.rs
`connect` apparently binds the socket to a particular interface, breaking roaming. PR fixes this by using `sendto`/`recvfrom`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7042)
=> Use sendto and recvfrom instead of connecting Shadowsocks socket

.github/workflows/ios.yml
Store Xcode test report as artefact for unit tests in `ios.yml`. Can be tested by running the "iOS app" workflow with this branch https://github.com/mullvad/mullvadvpn-app/actions/workflows/ios.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6966)
=> Store unit test report

ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7044)
=> Remove explanatory text for Direct only in settings

.github/workflows/android-app.yml
Don't trigger instrumented e2e tests by PR updates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7018)
=> Disable e2e tests for PR updates

Cargo.lock, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/FromDomain.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ApiAccessMethod.kt, gui/locales/messages.pot, gui/src/main/default-settings.ts, gui/src/main/grpc-type-convertions.ts, gui/src/renderer/components/ApiAccessMethods.tsx, gui/src/renderer/components/ContextMenu.tsx, gui/src/renderer/components/InfoButton.tsx, gui/src/renderer/components/cell/Label.tsx, gui/src/shared/daemon-rpc-types.ts, gui/test/e2e/installed/state-dependent/api-access-methods.spec.ts, mullvad-api/Cargo.toml, mullvad-api/src/https_client_with_sni.rs, mullvad-api/src/proxy.rs, mullvad-daemon/Cargo.toml, mullvad-daemon/src/api.rs, mullvad-encrypted-dns-proxy/Cargo.toml, mullvad-encrypted-dns-proxy/src/config/mod.rs, mullvad-encrypted-dns-proxy/src/config/xor.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/access_method.rs, mullvad-types/src/access_method.rs
This PR tracks the progress of adding Encrypted DNS as an access method in the daemon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7010)
=> Add Encrypted DNS proxy as an access method

ios/MullvadREST/Relay/RelayPicking.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift
When exit constraints match a DAITA relay, multihop is off, direct only is off and DAITA is turned on, the app should connect via singlehop to the eligible DAITA relays.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7050)
=> Fix relay selector for smart routing

talpid-wireguard/src/lib.rs
These must be saved before calling `patch_endpoint`. #7046 moved it around, messing up the route on non-Linux.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7052)
=> Fix endpoint addr patch

docs/known-issues.md
As we discussed briefly AFK. Since Microsoft treats Application Guard as deprecated, we see very little value in spending a large effort into fixing it. Instead we should just accept the state of things and recommend users to not use Application Guard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7062)
=> Add note about Application Guard being deprecated

CHANGELOG.md
This PR adds "Encrypted DNS Proxy" access method to the changelog. It was implemented for Desktop and Android in this PR: https://github.com/mullvad/mullvadvpn-app/pull/7010
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7067)
=> Add Encrypted DNS Proxy access method to the changelog

.github/workflows/osv-scanner-pr.yml, .github/workflows/osv-scanner-scheduled.yml
Contains, among other things, stricter validation of osv-scanner.toml config files. Ignores invalid config files, making their ignores not ignored. This solves our previous small issue where we invalidly used `ignoreUntil` in sections where the config were supposed to use `effectiveUntil`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7065)
=> Upgrade osv-scanner to 1.9.0

ios/MullvadVPN/View controllers/Tunnel/DisconnectSplitButton.swift
The size of the secondary button wasn't being used to adjust the insets of the disconnect button. I've gone and done did make it do it now. Feel free to reject or suggest a better solution.
Since the inset rectangle is RTL aware, I presume this change would work there too? Or do we not display the reconnect button on the left in RTL locales?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7061)
=> Correctly set insets for primary button

CHANGELOG.md, talpid-core/src/dns/macos.rs, talpid-core/src/dns/mod.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/disconnected_state.rs, talpid-core/src/tunnel_state_machine/error_state.rs
Works around an issue where the PF redirect rule is ignored.
This PR only makes the minimal changes required. The redirect rule is still kept, though we may wish to remove it later.
Fix DES-1372.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7070)
=> Configure DNS resolver port in SCDynamicStore

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7073)
=> Prepare android/2024.8-beta2

mullvad-encrypted-dns-proxy/Cargo.toml
As the title suggests, this PR adds a missing `serde` feature to `mullvad-encrypted-dns-proxy`. Currently, the crate fails to build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7074)
=> Add missing `serde` feature in `mullvad-encrypted-dns-proxy`

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/LocalNetworkSharingInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/constant/StringConstant.kt, android/lib/resource/src/main/res/values/strings.xml, gui/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7076)
=> Add always on warning to local network sharing info dialog

README.md
Reflect platforms that support WireGuard over Shadowsocks in the feature table presented in the README.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7085)
=> Add WireGuard over Shadowsocks to feature table

talpid-core/src/firewall/macos.rs
Context is in the comment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7084)
=> Document "raison d'être" of some NAT rules in macOS firewall module

mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs, mullvad-daemon/src/settings/mod.rs, mullvad-management-interface/src/types/conversions/settings.rs, mullvad-management-interface/src/types/conversions/states.rs, mullvad-types/src/features.rs, mullvad-types/src/settings/mod.rs, mullvad-types/src/states.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/disconnected_state.rs, talpid-core/src/tunnel_state_machine/disconnecting_state.rs, talpid-core/src/tunnel_state_machine/error_state.rs, talpid-core/src/tunnel_state_machine/mod.rs, talpid-types/src/tunnel.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7007)
=> Remove `block_when_disconnected` setting on Android

gui/test/e2e/installed/state-dependent/api-access-methods.spec.ts
Did an oopsie and forgot to update some values in the `api-access-methods` end-to-end GUI test. I could have sworn that I ran these tests before merging, but supposedly I didn't.. :thinking:
Here is a test run to prove that it works as intended: https://github.com/mullvad/mullvadvpn-app/actions/runs/11559889398
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7090)
=> Fix `api-access-methods.spec` - counting of access methods was off

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/EncryptedDnsProxyInfoDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/ApiAccessMethodDetailsUiStatePreviewParameterProvider.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ApiAccessMethodDetailsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/ApiAccessMethodDetailsUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ApiAccessMethodDetailsViewModel.kt, android/lib/resource/src/main/res/values/strings.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7087)
=> Add info dialog to Encrypted DNS proxy access method

ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift, ios/MullvadREST/Relay/IPOverrideWrapper.swift, ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift, ios/MullvadVPN/View controllers/Settings/SettingsInteractor.swift, ios/MullvadVPNTests/MullvadREST/ApiHandlers/ServerRelaysResponse+Stubs.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayCacheTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorTests.swift, ios/MullvadVPNTests/MullvadSettings/IPOverrideWrapperTests.swift
The relay list should contain a couple of new fields for shadowsocks proxying:
- `shadowsocks_extra_addr_in` - a list of additional IP addresses that can be used to reach a specific relay over shadowsocks.  This field will be added to a relay struct (`wireguard.relays.[*].shadowsocks_extra_addr_in`). These IP addresess will have shadowsocks listening on literally every port. These addresses will all be backed by the same relay. 
- `shadowsocks_port_ranges` - a field in the toplevel wireguard object that represents all the port ranges that shadowsocks will be listening on the default entry IPs for relays. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7096)
=> Add shadowsocks fields to relay list response from the API

CHANGELOG.md, gui/locales/messages.pot, gui/src/main/daemon-rpc.ts, gui/src/main/index.ts, gui/src/renderer/app.tsx, gui/src/renderer/components/SmallButton.tsx, gui/src/renderer/components/SplitTunnelingSettings.tsx, gui/src/renderer/components/SplitTunnelingSettingsStyles.tsx, gui/src/shared/ipc-schema.ts, mullvad-daemon/src/management_interface.rs, mullvad-management-interface/proto/management_interface.proto, talpid-core/src/split_tunnel/macos/mod.rs, talpid-core/src/split_tunnel/macos/process.rs
Previously, the app wouldn't detect this and end up in the blocked state. It will now show this information before split tunneling can be enabled:
Fix DES-1185.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7098)
=> Detect whether full-disk access is enabled in the split tunneling view

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift, ios/MullvadVPN/View controllers/Settings/CheckableSettingsCell.swift, ios/MullvadVPN/View controllers/Settings/SelectableSettingsCell.swift, ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsAddDNSEntryCell.swift, ios/MullvadVPN/View controllers/Settings/SettingsCell.swift, ios/MullvadVPN/View controllers/VPNSettings/CustomDNSCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDetailsButtonItem.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInfoButtonItem.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift, ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift
For each cell that needs it (udp2tcp, shadowsocks):
- the cell should display the current port setting
- the cell should have an action button that will eventually navigate to a new view
- there should be a divider
- It should use the correct background color when selected/unselected
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7020)
=> Update cell layout and behavior for obfuscation methods

ios/build-wireguard-go.sh
This PR enables building SwiftUI views without failing wireguard-go builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7086)
=> Enable building with SwiftUI

.github/workflows/ios-end-to-end-tests.yml
This PR enables iOS end-to-end tests to receive a commit_hash as an input, allowing the workflow to check out that specific commit. This input is optional, and if no value is provided, the workflow will use the latest commit from the branch that triggered it. The primary reason for this change is that iOS settings migration tests require an older commit version. By reusing iOS end-to-end tests for these cases and consolidating workflows and jobs in one place, it becomes necessary to fetch the repository at a specific reference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7093)
=> Add commit_hash to end to end test

ios/MullvadSettings/MigrationManager.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
This PR fixes a deadlock that was triggered by rebooting the phone when the VPN was connected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7089)
=> Avoid deadlocking the Packet Tunnel after a reboot

mullvad-encrypted-dns-proxy/src/config_resolver.rs
Don't both print the contained error in the Display impl and also return it in source.
The error, as it was before, would print an error chain like this:
```
Error: Resolution error something something
Caused by: Resolution error something something
```
An error should avoid including its source error in its own `Display` impl. Or, if it is included, it should not return that from the `source` method.
If you want to dive more into how long I have cared about this, you can follow this URL :D https://github.com/rust-lang/api-guidelines/pull/210
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7105)
=> Stop duplication in error source chain

mullvad-api/src/proxy.rs, mullvad-daemon/src/api.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/tunnel.rs, mullvad-relay-selector/src/relay_selector/detailer.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-types/src/relay_list.rs, test/Cargo.lock, test/test-manager/src/tests/ui.rs
This PR addresses an issue in the logic for testing access methods whre if an access methods fails to resolve to a set of connection details (e.g. if the relay selector / mullvad encrypted dns cache is empty) the daemon would fall back to making a direct API connection. The current behaviour is straight up misleading.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7091)
=> Do not fallback to making direct API connections when testing access methods

talpid-wireguard/src/wireguard_go/mod.rs, talpid-wireguard/src/wireguard_nt/daita.rs, wireguard-go-rs/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7107)
=> Add unit test for parsing maybenot machines

.github/workflows/desktop-e2e.yml, README.md
This PR removes Debian 11 and macOS 12 from the test runs (unless explicitly requested).
Fix DES-1410.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7123)
=> Remove old E2E test VMs, and bump minimum supported Debian version

ios/MullvadSettings/WireGuardObfuscationSettings.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift, ios/MullvadVPNTests/MullvadSettings/MigrationManagerTests.swift, ios/MullvadVPNTests/MullvadSettings/TunnelSettingsUpdateTests.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift, ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift, ios/PacketTunnelCoreTests/Mocks/SettingsReaderStub.swift, ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7064)
=> Update data structure to support new obfuscation selection

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/PacketTunnel/WireGuardAdapter/WgAdapter.swift, ios/PacketTunnelCore/Actor/ConfigurationBuilder.swift, ios/PacketTunnelCore/Actor/ConnectionConfigurationBuilder.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift, ios/PacketTunnelCore/Actor/Protocols/TunnelAdapterProtocol.swift, ios/PacketTunnelCore/Pinger/PingerProtocol.swift, ios/PacketTunnelCore/Pinger/TunnelPinger.swift, ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift, ios/PacketTunnelCoreTests/Mocks/PingerMock.swift
This PR removes the concept of opening and closing a socket for pinging the gateway address, that functionality has been moved into WireGuardKit.
Which address to ping is now passed via the `ConfigurationBuilder` 
⚠️ This PR requires https://github.com/mullvad/wireguard-apple/pull/31 to be merged first, the commit hash used for wireguard-go will need to be updated to point to the `mullvad-master` branch instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7113)
=> When phone loses connectivity it fails to reconnect ios 889

mullvad-daemon/src/exception_logging/unix.rs
Also add a reentrancy-guard to the fault handler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7137)
=> Disable `fault_handler` logging in release builds

test/scripts/container-run.sh
Very minor fix. Just making the script consistent in whether or not it hardcodes the container runner. I opted for making it configurable even if no one has tried using it with docker.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7144)
=> Replace hardcoded usage of "podman" with configurable version

CHANGELOG.md, README.md, talpid-core/src/firewall/linux.rs
Prevent attackers able to send ARP requests to the device running Mullvad from figuring out the in-tunnel IP.
Fixes 2024 audit issue `MLLVD-CR-24-03`.
Please note that this only fixes the issue on Linux. The issue also exists on Android, but this PR does not touch that.
Documentation about `arp_ignore` and what the different config values mean can be found here: https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt
A 2019 report about something very related, that brings up the `arp_ignore=2` solution can be found here: https://seclists.org/oss-sec/2019/q4/123
It should be noted that `arp_ignore=1` seems to be enough to solve the immediate issue. But I don't see any downside in being slightly stricter than that. And the blog post linked above used `2` also.
TODO: Add an …
=> Set net.ipv4.conf.all.arp_ignore=2 when bringing up tunnels on Linux (MLLVD-CR-24-03)

dist-assets/windows/installer.nsh, gui/tasks/distribution.js
Since there is currently a separate build for ARM Windows.
Close DES-187.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7149)
=> Prevent install of x86 app on arm64 Windows, and vice versa

mullvad-daemon/src/exception_logging/win.rs
This PR adds some fixes and comments that was found during my investigation of our exception handler on Windows that spawned from https://github.com/mullvad/mullvadvpn-app/pull/7137. It contributes the following:
* Don't redefine Windows API function signatures, import them from `windows_sys`
* Get rid of `unsafe` where safety comments were missing and there were safe alternatives
* Add `SAFETY` comments to `unsafe` code where there exists documentation around what properties that need to be upheld. Add appropriate checks of properties if they were missing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7146)
=> Upstream findings from investigation of windows fault handler

test/deny.toml
This is a follow up to #7157 which only silenced `RUSTSEC-2024-0384` for the `osv-scanner` tool, but [I was made aware](https://github.com/mullvad/mullvadvpn-app/actions/runs/11792740683/job/32846900264?pr=7119) that we also need to silence the `cargo-deny` security advisory for our CI to be happy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7163)
=> Silence `RUSTSEC-2024-0384` in `cargo-deny` / test framework

mullvad-relay-selector/src/relay_selector/query.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/mod.rs, test/test-manager/src/tests/tunnel.rs
This PR introduces some changes to end-to-end test cases which has been shown to be particularly prone to timeout issues during the connecting phase. In an attempt to reduce the perceived flakiness, we restrict what relays may be selected to relays which are geographically close to the client under test in order to reduce the amount of latency in the system.
Looks promising: https://github.com/mullvad/mullvadvpn-app/actions/runs/11659693517/job/32460901751
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7119)
=> Fix connection timeout errors caused by far away relays

ios/MullvadREST/Extensions/UInt+Counting.swift, ios/MullvadREST/Relay/ObfuscationMethodSelector.swift, ios/MullvadREST/Relay/ObfuscatorPortSelector.swift, ios/MullvadREST/Relay/RelaySelector.swift, ios/MullvadREST/Relay/RelaySelectorWrapper.swift, ios/MullvadSettings/WireGuardObfuscationSettings.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPNTests/MullvadREST/ApiHandlers/ServerRelaysResponse+Stubs.swift, ios/MullvadVPNTests/MullvadREST/Extensions/UIntTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/ObfuscationMethodSelectorTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor.swift, ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift, ios/PacketTunnelCoreTests/Mocks/ProtocolObfuscationStub.swift, ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift
When shadowsocks should be used, the relay selector should only select relays that match the port settings for shadowsocks. 
When selecting candidates for a given selection, only candidates able to provide the ports should be considered. In the case that there is no port specified, this filtering will do nothing. 
- If a user selects a port within the port range defined in shadowsocks_port_range on the god object, all relays should be considered
- If a user selects a port outside of that port range, only the relays that provide an shadowsocks_extra_addr_in should be considered in the relay selection
- If the WireGuard over Shadowsocks obfuscation is automatic then we first select a relay, then we select a port based on whether the relay has a shadowsocks_extra_addr_in available (1-65000) …
=> Update relay selector for shadowsocks obfuscation

ios/MullvadRustRuntime/TunnelObfuscator.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadRustRuntimeTests/TCPConnection.swift, ios/MullvadRustRuntimeTests/TunnelObfuscationTests.swift, ios/MullvadRustRuntimeTests/UDPConnection.swift, ios/MullvadRustRuntimeTests/UnsafeListener.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift, ios/PacketTunnelCoreTests/Mocks/TunnelObfuscationStub.swift, mullvad-ios/src/lib.rs, mullvad-ios/src/tunnel_obfuscator_proxy/ffi.rs, mullvad-ios/src/tunnel_obfuscator_proxy/mod.rs
This PR adds Shadowsocks obfuscation capabilities to the Packet Tunnel.
It cannot be used as of yet, but there is a test called `testRunningShadowsocksObfuscatorProxy` that makes use of the newly introduced obfuscation protocol.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7132)
=> Add udp shadowsocks proxy support to mullvad ios

dist-assets/pkg-scripts/preinstall
This PR cleans up some workarounds present in the preinstall script for macOS which supposedly can be removed because we no longer support the app versions that these workarounds target. I only noticed this because of log output when running the end-to-end tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7162)
=> Clean up workarounds in macOS preinstall script

ios/MullvadVPN/Coordinators/CustomLists/AddLocationsDataSource.swift, ios/MullvadVPN/View controllers/SelectLocation/AllLocationDataSource.swift, ios/MullvadVPN/View controllers/SelectLocation/CustomListsDataSource.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationCellViewModel.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationDataSourceProtocol.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationDiffableDataSourceProtocol.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationViewController.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift
This PR fixes the carsh we have on UITableViewDiffableDataSource.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7150)
=> Investigate crash in DiffableDataSource

desktop/packages/mullvad-vpn/test/e2e/installed/state-dependent/tunnel-state.spec.ts, mullvad-daemon/src/custom_list.rs, mullvad-daemon/src/lib.rs, mullvad-relay-selector/src/relay_selector/matcher.rs, mullvad-relay-selector/src/relay_selector/mod.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/ui.rs
Fixes a bug where `test_ui_tunnel_settings` failed on macOS since it has IPv6 enabled by default, which caused the parsing of the outbound IP to fail. 
The PR also sets the "LowLatency" custom list for the test, since it connects multiple times with different settings, including multihop and OpenVPN, and thus is highly dependent on connection stability.
CI job which ran the test 10 times in a row: https://github.com/mullvad/mullvadvpn-app/actions/runs/11838399382.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7166)
=> Reduce flakiness of `test_ui_tunnel_settings`

test/connection-checker/src/cli.rs, test/connection-checker/src/main.rs, test/scripts/test-utils.sh, test/test-by-version.sh, test/test-manager/src/main.rs, test/test-manager/src/tests/helpers.rs
Fix DES-1051.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7182)
=> Add flag for overriding API environment in E2E tests

ios/MullvadSettings/WireGuardObfuscationSettings.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/View controllers/Settings/Obfuscation/TunnelObfuscationSettingsWatchingObservableObject.swift, ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsView.swift, ios/MullvadVPN/View controllers/Settings/Obfuscation/UDPTCPObfuscationSettingsViewModel.swift, ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift, ios/MullvadVPN/View controllers/Settings/SwiftUI components/StatefulPreviewWrapper.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInteractor.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
This implements a SwiftUI-based settings page for selecting the port for UDP->TCP WireGuard obfuscation. The page's ViewModel couples its state directly into the TunnelManager's Settings, bypassing the UIKit-based structure of ViewModel/DataSource objects. Additionally, there is an abstraction for a styled choice list and a a helper class for stateful previews.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7143)
=> IOS-880 SwiftUI settings page for UDP/TCP obfuscation port

ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSource.swift, ios/MullvadVPN/View controllers/RelayFilter/RelayFilterViewController.swift
When switching between ownership at filter view, the apply button is enabled while no providers are selected and the provider pile shows wrong number for providers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7159)
=> Fix filter apply button being enabled with zero providers

build.sh
This PR updates `build.sh` to not output audit and fund info when running `npm ci`. We rely on osv-scanner for dependency vulnerability auditing.
This only applies to the build-script. To disable the audit and fund output when running `npm install` manually, run the following:
```
npm config set audit false
npm config set fund false
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7190)
=> Disable fund and audit output for npm install in build script

desktop/osv-scanner.toml, desktop/package-lock.json, desktop/package.json
This PR updates these dependencies due to them having known vulnerabilities. All changes to `package-lock.json` were generated by `npm audit fix`. The osv-scanner ignore for `elliptic` has also been removed. None of these vulnerabilities affected the app or users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7191)
=> Update elliptic, @eslint/plugin-kit and cross-spawn to non-vulnerable versions

.github/workflows/android-app.yml
Disable nightly firebase e2e and mockapi tests. They can still optionally run when manually triggering the workflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7202)
=> Disable nightly firebase tests

mullvad-relay-selector/src/relay_selector/query.rs, test/test-manager/src/tests/helpers.rs, test/test-manager/src/tests/mod.rs, test/test-manager/src/tests/ui.rs
Add to `prepare_daemon` a step where the default location, including entry for multihop (but not bridges as it turned out to be problematic), is set to the `Nordic` custom list.
Link to full test run https://github.com/mullvad/mullvadvpn-app/actions/runs/11892409373/job/33137399707. I left in a `dbg!()` statement by accident, so the logs are a little cluttered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7184)
=> Use low latency servers for all tests

BuildInstructions.md, scripts/vcvars.sh
Add a convenience script that sets up `INCLUDE` and `PATH` for Git Bash correctly by running `vcvarsall.bat <arch>` and converting and exporting those variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7181)
=> Add helper script for configuring VS/Windows build environment

test/test-manager/src/tests/tunnel.rs
`test_daita` sets each relay manually, so we skip setting the `Any` location constraint for it.
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/11934895345
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7209)
=> Make `test_wireguard_tunnel` use `location: Any`

desktop/packages/mullvad-vpn/src/main/index.ts, desktop/packages/mullvad-vpn/src/main/tunnel-state.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7189)
=> Always restart daemon when full-disk access message has been shown

.github/workflows/android-app.yml
Upload instrumentation test report no matter whether tests failed or ran successfully. Before it not uploaded if tests fail because by default a step's `if` have a `successful()` condition steps following a failing test not to run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7071)
=> Upload instrumentation report regardless if tests failed

.github/workflows/ios-build-xcode-16.yml
This PR adds a new workflow that will run build validation schemas with Xcode 16 on macOS 15
It is mostly a copy of `ios-validate-build-schemas.yml`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7215)
=> Add a github workflow to build on Xcode 16

.github/workflows/ios-build-xcode-16.yml
The last part needed to have builds on Xcode 16, build on a device that is supported in iOS 16.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7218)
=> Use iPhone 16 as a build destination

desktop/packages/nseventforwarder/package.json
This PR fixes an issue introduced in https://github.com/mullvad/mullvadvpn-app/pull/7211 where a an extra dash (`-`) snuck into the `build-x86` npm command in the `nsventforwarder` workspace. This messed up the variable substitution, which tripped up `cp` because we provided it with a nonsensical path.
* Bad `build-x86`:  `cp ${CARGO_TARGET_DIR:--../../../target}`
* Good `build-x86`: `cp ${CARGO_TARGET_DIR:-../../../target}`
The consequence of this is that we can not package the `x86`-version of the macOS app, which subsequently disallows us from producing universal installers.
I've double-checked that this PR actually fixes the problem, and here is the proof:
```bash
$ ./build.sh --optimize --universal
..
• building        target=pkg arch=universal …
```
=> Fix `npm run build-x86` command in `nsventforwarder`

.github/CODEOWNERS
This PR adds code owners for `.github/workflows/verify-locked-down-signatures.yml`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7221)
=> Add codeowners for the actions workflow that verifies commit signatures

test/test-manager/src/main.rs, test/test-manager/src/run_tests.rs, test/test-manager/src/summary.rs, test/test-manager/src/tests/mod.rs, test/test-manager/src/tests/test_metadata.rs, test/test-manager/test_macro/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7219)
=> Fix test matrix

.github/workflows/ios-rust-ffi.yml, mullvad-api/include/mullvad-api.h, mullvad-api/src/ffi/device.rs, mullvad-api/src/ffi/mod.rs, mullvad-api/src/lib.rs
Also, build mullvad-api in the CI workflow.
Close IOS-950.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7238)
=> Fix mullvad-api for iOS

ios/Configurations/Api.xcconfig.template, ios/MullvadREST/ApiHandlers/RESTDefaults.swift, ios/MullvadREST/Info.plist, ios/MullvadREST/Transport/EncryptedDNS/EncryptedDNSTransport.swift, ios/MullvadRustRuntime/EncryptedDNSProxy.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift, ios/MullvadVPN/TransportMonitor/TransportMonitor.swift, ios/MullvadVPNTests/Info.plist, ios/MullvadVPNUITests/ConnectivityTests.swift, ios/MullvadVPNUITests/Info.plist, mullvad-daemon/src/api.rs, mullvad-encrypted-dns-proxy/src/config_resolver.rs, mullvad-encrypted-dns-proxy/src/state.rs, mullvad-ios/src/encrypted_dns_proxy.rs
This PR fixes 3 tests that were constantly failing on the CI runner
- `testAPIConnectionViaBridges`
- `testAPIReachableWhenBlocked`
- `testAppStillFunctioningWhenAPIDown`
`testAPIConnectionViaBridges` Is skipped at the moment, the only shadowsocks bridge provided by the staging environment is declared as inactive, hence the app cannot use shadowsocks bridges to connect to the API.
`testAPIReachableWhenBlocked` This was a bug, we never updated the `TransportMonitor` to let API calls go through the packet tunnel when entering the blocked state. 
`testAppStillFunctioningWhenAPIDown` was failing because an accessibility element was put on the wrong item in API access methods. 
On top of that, since we added encrypted DNS proxy methods, we never added an encrypted DNS resolver for staging …
=> Fix connectivity tests ios 873

Cargo.lock, test/Cargo.lock
Upgrade `rustls` to avoid [`RUSTSEC-2024-0399`](https://osv.dev/vulnerability/RUSTSEC-2024-0399).
We were not affected by the vulnerability, since we don't `accept()` incoming TLS connections with rustls anywhere at all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7237)
=> Upgrade rustls to silence RUSTSEC-2024-0399

README.md, mullvad-daemon/src/exception_logging/mod.rs, mullvad-daemon/src/exception_logging/unix.rs, mullvad-daemon/src/main.rs
Other changes:
- Re-enable the signal handler in release-builds.
- Disable backtrace printing by default since it's not signal-safe.
- Add `MULLVAD_BACKTRACE_ON_FAULT` env variable to enable backtracing (Yes, that makes it not signal safe! But something we are willing to have as opt-in due to how it can help us debug stuff).
- Remove the alternate signal stack. The reasons for this are:
- Setting up an alt-stack in a safe way is not trivial, our previous
attempt was unsound in the presence of stack overflows. It can be
done safely with mmap, but would require careful review.
- The alt-stack is thread-local, meaning it would need to be
initialized on a per-thread basis. We would need to hook into tokio
and std::thread::spawn to be able to get good coverage, and even
then there would no …
=> Make unix signal-handler signal-safe

desktop/osv-scanner.toml
Extend ignore for CVE-2024-4067 since it has expired.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7241)
=> Extend ignore for CVE-2024-4067

.github/workflows/android-app.yml, .github/workflows/android-audit.yml, .github/workflows/android-kotlin-format-check.yml, .github/workflows/android-static-analysis.yml, .github/workflows/android-xml-format-check.yml, .github/workflows/check-changelog.yml, .github/workflows/clippy.yml, .github/workflows/daemon.yml, .github/workflows/desktop-e2e.yml, .github/workflows/frontend.yml, .github/workflows/ios-build-xcode-16.yml, .github/workflows/ios-rust-ffi.yml, .github/workflows/ios-screenshots-creation.yml, .github/workflows/ios-screenshots-tests.yml, .github/workflows/ios-validate-build-schemas.yml, .github/workflows/ios.yml, .github/workflows/proto-format-check.yml, .github/workflows/rust-supply-chain.yml, .github/workflows/rust-unused-dependencies.yml, .github/workflows/rustfmt.yml, .github/workflows/shellcheck.yml, .github/workflows/testframework-clippy.yml, .github/workflows/testframework-rust-supply-chain.yml, .github/workflows/testframework-rustfmt.yml, .github/workflows/testframework.yml, .github/workflows/translations-converter.yml, .github/workflows/translations.yml, .github/workflows/unicode-check.yml, .github/workflows/verify-locked-down-signatures.yml, .github/workflows/yamllint.yml
Fixes some deprecation warnings in GHA.
```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/download-artifact@v4, actions/upload-artifact@v4.
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "fedora40_report", "linux-build", "summary.html".
Please update your workflow to use v4 of the artifact actions.
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.
```
- - - …
=> Update GHA Dependencies

desktop/packages/nseventforwarder/nseventforwarder-rs/lib.rs, desktop/packages/nseventforwarder/src/index.cts
This PR improves the `nseventforwarder` implementation in the following ways:
* Use clearly named variables
* Add some more documentation to distinguish what's happening on the nodejs vs rust side
* Get rid of the static `Mutex`, effectively allowing multiple nsevent-callback to be running at once. Because why not
This is not critical in any way, but especially the static `Mutex` bothered me since it didn't seem necessary :-)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7229)
=> Improve `nseventforwarder`

docs/relay-selector.md, ios/MullvadREST/Relay/ObfuscatorPortSelector.swift, ios/MullvadREST/Relay/RelaySelector.swift, ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorTests.swift, ios/MullvadVPNUITests/Networking/FirewallAPIClient.swift, ios/MullvadVPNUITests/Networking/FirewallRule.swift, ios/MullvadVPNUITests/Networking/Networking.swift, ios/MullvadVPNUITests/Pages/TunnelControlPage.swift, ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift, ios/MullvadVPNUITests/RelayTests.swift, ios/MullvadVPNUITests/SettingsMigrationTests.swift
This PR does the following things:
- Amend the documentation about the algorithm governing the automatic port selection
- In particular, it adds an iOS specific section as it's quite different from other platforms
- Changes how local IP discovery is done in UITests (it used to be based on the interface name, which is not a reliable method on iOS)
- Adds a UITest for Shadowsocks obfuscation
- Updates the automatic reconnection algorithm for iOS based on the [official documentation](https://github.com/mullvad/mullvadvpn-app/blob/main/docs/relay-selector.md#default-constraints-for-tunnel-endpoints)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7213)
=> Fix broken retry strategy tests ios 938

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7244)
=> Update changelog for android `2024.9-beta1`

CHANGELOG.md, desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/main/index.ts, desktop/packages/mullvad-vpn/src/renderer/app.tsx, desktop/packages/mullvad-vpn/src/renderer/components/Layout.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SplitTunnelingSettingsStyles.tsx, desktop/packages/mullvad-vpn/src/renderer/components/common-styles.ts, desktop/packages/mullvad-vpn/src/shared/ipc-schema.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7201)
=> Add daemon restart button to split tunneling settings on MacOS

CHANGELOG.md, desktop/packages/mullvad-vpn/src/renderer/components/select-location/SelectLocation.tsx, desktop/packages/mullvad-vpn/src/renderer/components/select-location/SelectLocationContainer.tsx
Since the `directOnly` boolean is separate from the multihop setting we need to check the multihop setting as well before disabling the entry selection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7242)
=> Fix daita and multihop warning being shown when multihop is disabled

ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift, ios/MullvadREST/Relay/MultihopDecisionFlow.swift, ios/MullvadREST/Relay/ObfuscatorPortSelector.swift, ios/MullvadREST/Relay/RelayPicking.swift, ios/MullvadREST/Relay/RelaySelectorWrapper.swift, ios/MullvadSettings/TunnelSettingsStrategy.swift, ios/MullvadTypes/MullvadEndpoint.swift, ios/MullvadVPNTests/MullvadREST/Relay/MultihopDecisionFlowTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift
Currently, the obfuscation port is applied to the exit configuration at all times. Instead, it should be applied to the entry configuration when using multihop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7199)
=> Apply the obfuscation port to the entry configuration only

ios/MullvadLogging/Logging.swift
This PR reduces the maximum log file size from 5MB to 2MB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7254)
=> Reduce the maximum log file size to 2MB

mullvad-version/src/lib.rs, mullvad-version/src/main.rs, prepare-release.sh
This PR adds support for the new version code format that we want to start using for the Android app. This code should only affect the Android version parsing and not the other platforms.
The point of the new version code format is to enable use to tag alpha releases and have the build server build them and to have a more flexible format for the future.
The format looks as the following:
```
/// The format of the code is:                    YYVVXZZZ
///   Last two digits of the year (major)---------^^
///   Incrementing version (minor)------------------^^
///   Build type (0=alpha, 1=beta, 9=stable/dev)------^
///   Build number (000 if stable/dev)-----------------^^^
///
/// # Examples
///
/// Version: 2021.1-alpha1
/// versionCode: 21010001
///
/// Version: 2021.34-beta5
/// …
```
=> Support Android app's new version code format

talpid-core/src/dns/linux/mod.rs
Might make it a bit easier to diagnose DNS issues on linux.
Example output:
```
[2024-11-28 11:25:05.950][talpid_core::dns][INFO] Setting DNS servers: Tunnel DNS: {10.64.0.1} Non-tunnel DNS: {}
[2024-11-28 11:25:05.951][talpid_core::dns::imp][DEBUG] Can't manage DNS using systemd-resolved: systemd-resolved operation failed
[2024-11-28 11:25:05.952][talpid_dbus::network_manager][DEBUG] /etc/resolv.conf differs from reference resolv.conf, therefore NM is not managing DNS
[2024-11-28 11:25:05.952][talpid_core::dns::imp][DEBUG] Can't manage DNS using network manager: NetworkManager is not managing DNS
[2024-11-28 11:25:05.952][talpid_core::dns::imp][DEBUG] Can't manage DNS using resolveconf: Failed to detect 'resolvconf' program
[2024-11-28 …
```
=> Log failure reason when trying DNS managers

ios/MullvadREST/Relay/ObfuscatorPortSelector.swift, ios/MullvadSettings/WireGuardObfuscationSettings.swift, ios/MullvadVPN/View controllers/Settings/Obfuscation/ShadowsocksObfuscationSettingsView.swift, ios/MullvadVPN/View controllers/Settings/Obfuscation/ShadowsocksObfuscationSettingsViewModel.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift
The type name `WireGuardObfuscationShadowsocksPort` was misspelled as `WireGuardObfuscationShadowsockPort`. A minor annoyance, but this PR fixes it. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7260)
=> Replace misspelling of WireGuardObfuscationShadowsocksPort type name

mullvad-api/src/https_client_with_sni.rs, mullvad-encrypted-dns-proxy/src/forwarder.rs
This PR cleans up `mullvad_encrypted_dns_proxy::forwarder` a bit by correcting the `Forwarder::from_stream` type signature and importing `ProxyConfig`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7267)
=> Make `EncryptedDNSForwarder::from_stream` infallibe

talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_go/mod.rs
Fixes a bug on Android where we would get into a blocked state when an error occurred during a connection attempt (for example when all UDP traffic to the relay was blocked).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7250)
=> Make tunnel connection errors recoverable

.github/workflows/daemon.yml
This PR doesn't include clippy, since those are (probably) not architecture-dependent, or the `test` workspace for now. It also does not include GUI or full E2E tests.
Close DES-1120
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7258)
=> Add daemon CI job for Windows ARM64

ios/CHANGELOG.md, ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
This PR adds WireGuard over Shadowsocks obfuscation in `Release` and `MockRelease` builds.
It also amends the Changelog to mention said change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7257)
=> Make shadowsocks obfuscation ready for production ios 879

CHANGELOG.md, talpid-core/src/dns/macos.rs, talpid-core/src/firewall/macos.rs, talpid-core/src/resolver.rs, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/error_state.rs
This PR gates the NAT filter rules that we introduced in https://github.com/mullvad/mullvadvpn-app/pull/6911 to only the affected macOS versions, since we don't need them otherwise. They were added to mitigate the problem of Apple services not working properly together with the Mullvad VPN app as reported in https://github.com/mullvad/mullvadvpn-app/issues/6521.
This PR additionally disables our local DNS resolver by default for the same macOS versions, which has been enabled since https://github.com/mullvad/mullvadvpn-app/pull/6890. We found an issue with some services such as Orbstack setting the pf flag `skip` on loopback, which would mess with our redirect of DNS to our local DNS resolver. Hopefully this can help fix https://github.com/mullvad/mullvadvpn-app/issues/7058 (at least …
=> Remove Apple services workarounds for unaffected macOS versions

mullvad-api/src/address_cache.rs, mullvad-api/src/bin/relay_list.rs, mullvad-api/src/https_client_with_sni.rs, mullvad-api/src/lib.rs, mullvad-api/src/rest.rs, mullvad-daemon/src/android_dns.rs, mullvad-daemon/src/lib.rs, mullvad-problem-report/src/lib.rs, mullvad-setup/src/main.rs, test/test-manager/src/tests/account.rs
* Implement `DnsResolver` for the `AddressCache`. This decouples it from the REST client.
* Remove "fallback on DNS resolution" logic. Only give the geoip client an actual DNS resolver. Let the main client fail if it tries to resolve anything that isn't `api.mullvad.net`.
* Use URI host for SNI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7248)
=> Refactor address cache in mullvad-api

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift
If you select any Wireguard port except custom port, then select custom port, then toggle any of the other sections, you will have multiple selections in the Wireguard section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7264)
=> Fix multiple Wireguard port selection in settings view

ios/CHANGELOG.md, ios/MullvadSettings/SettingsManager.swift, ios/MullvadTypes/StringConversionError.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/ConsolidatedApplicationLog.swift, ios/MullvadVPN/View controllers/ProblemReport/ProblemReportInteractor.swift, ios/MullvadVPN/View controllers/ProblemReport/ProblemReportReviewViewController.swift, ios/MullvadVPN/View controllers/ProblemReport/ProblemReportViewController.swift, ios/MullvadVPNTests/MullvadVPN/Log/ConsolidatedApplicationLogTests.swift, ios/Shared/LaunchArguments.swift
this PR take log redaction out of main thread which caused blocking UI when working around it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7233)
=> Fix log redaction loading issue

ios/MullvadVPN/Views/InfoHeaderView.swift
This PR makes the entire text in InfoHeaderView clickable and disables text selection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7247)
=> Disable selectable text

ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift
This adds the ability to add `accessibilityIdentifier`s to tappable rows and custom entry controls in a `SingleChoiceList`, preparing it for UI tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7273)
=> Add accessibility identifiers to SingleChoiceList rows and text fields

ios/MullvadVPN/View controllers/Settings/SettingsCellFactory.swift, ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift, ios/MullvadVPN/View controllers/Settings/SettingsInteractor.swift, ios/MullvadVPN/View controllers/Settings/SettingsViewController.swift, ios/MullvadVPN/View controllers/Settings/SettingsViewModel.swift, ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift, ios/MullvadVPNUITests/Pages/SettingsPage.swift, ios/MullvadVPNUITests/RelayTests.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7272)
=> Add trailing status indicators for daita and multihop cells

ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/View controllers/Settings/SelectableSettingsDetailsCell.swift, ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift
... in VPN Settings
This creates a new `AccessibilityIdentifier` named `.openPortSelectorMenuButton` and sets the "..." button, for calling up the port selector menu in obfuscation method cells, to have it. It also refactors `VPNSettingsPage`, combining the logic for tapping disclosure cells with that for tapping this button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7282)
=> Add the openPortSelectorMenuButton accessibility identifier to ... buttons

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/TopBar.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/SettingsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/test/ComposeTestTagConstants.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/ConnectPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/LoginPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/PrivacyPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/SelectLocationPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/SettingsPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/SystemVpnConfigurationAlert.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/TopBar.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/VpnSettingsPage.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/ConnectionTest.kt
Migrated the e2e test cases in `ConnectionTest` to follow Page Object Pattern, similar to how we implemented it in `LoginTests`. The changes can be tested by running all test cases under `ConnectionTest`.
Also implemented Wireguard obfuscation set to automatic with UDP traffic to relay blocked connection test(`testWireGuardObfuscationAutomatic`).
Fixes DROID-1600, DROID-1622
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7283)
=> Migrate ConnectionTest e2e tests to use POP

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7307)
=> Update changelog for `android/2024.9`

android/buildSrc/src/main/kotlin/Utils.kt
This PR aims to fix the deprecated gradle `exec` calls previously used to execute `mullvad-version`. This fix is also needed to enable configuration cache.
Documentation: https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:external_processes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7309)
=> Fix unsupported `mullvad-version` gradle execution

test/Cargo.lock
This PR is a follow up to https://github.com/mullvad/mullvadvpn-app/pull/7318 which just updates the lock file slightly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7325)
=> Lock `hickory-resolver` to version 0.24.2 in `test` workspace

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Extensions/UIColor+Helpers.swift, ios/MullvadVPN/UI appearance/UIMetrics.swift, ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift, ios/MullvadVPN/Views/MainButton.swift, ios/MullvadVPN/Views/MainButtonStyle.swift, ios/MullvadVPN/Views/SplitMainButton.swift, ios/MullvadVPN/Views/VisualEffectView.swift
In order to work incrementally and in parallel we should first create a basic implementation that can act as a foundation for coming work. It doesn't have to be stateful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7290)
=> Add foundation for new connection view

.github/workflows/android-app.yml, android/app/build.gradle.kts, android/scripts/update-lockfile.sh, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt, build-apk.sh, desktop/packages/mullvad-vpn/tasks/distribution.js, talpid-tunnel-config-client/examples/tuncfg-server.rs, talpid-tunnel-config-client/proto/ephemeralpeer.proto, talpid-tunnel-config-client/src/lib.rs, talpid-wireguard/src/connectivity/mock.rs, talpid-wireguard/src/ephemeral.rs, talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_go/mod.rs, talpid-wireguard/src/wireguard_kernel/netlink_tunnel.rs, talpid-wireguard/src/wireguard_kernel/nm_tunnel.rs, wireguard-go-rs/libwg/libwg_daita.go, wireguard-go-rs/src/lib.rs
This PR enables DAITA V2 for all platforms that use wireguard go (except on iOS).
Related PR: https://github.com/mullvad/wireguard-go/pull/18.
Fix DES-1386.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7158)
=> Add DAITA V2 support for wireguard-go

audits/2024-12-10-X41-D-Sec.md
Small addition to the text about the audit added yesterday (#7323). Since then, X41 D-Sec has posted a public announcement about the audit. I felt it was relevant to link directly to that as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7331)
=> Add link to X41's announcement about the audit

CHANGELOG.md, android/CHANGELOG.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7335)
=> Update changelog for DAITA v2

wireguard-go-rs/libwg/go.mod, wireguard-go-rs/libwg/go.sum
Note that this vuln doesn't actually affect us. See https://github.com/mullvad/wireguard-go/pull/20
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7333)
=> Update wireguard-go (fix GO-2024-3321)

docs/security.md
Enhance naming of Unix and JavaScript at security.md
- unix => Unix
- Javascript => JavaScript
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7330)
=> [docs] Enhance naming of Unix and JavaScript at security.md

mullvad-encrypted-dns-proxy/src/config_resolver.rs, mullvad-types/src/constraints/constraint.rs, mullvad-types/src/relay_constraints.rs, talpid-core/src/dns/linux/mod.rs, talpid-core/src/tunnel/mod.rs, talpid-openvpn/src/lib.rs, talpid-types/src/tunnel.rs, talpid-wireguard/src/connectivity/check.rs
These redundant refs have become a hard error in rust 2024.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7336)
=> Remove some deprecated ref patterns

Cargo.lock, Cargo.toml, test/Cargo.lock, test/Cargo.toml
This version bumps `tokio` to version 1.42. We were already on a fairly recent version (1.39), but to implement https://github.com/mullvad/mullvadvpn-app/pull/7338 in a simple way it would be nice to have access to [SimplexStream](https://docs.rs/tokio/latest/tokio/io/struct.SimplexStream.html) which was introduced after version 1.39.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7339)
=> Bump `tokio` to version 1.42

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Coordinators/TunnelCoordinator.swift, ios/MullvadVPN/Extensions/Color+Helpers.swift, ios/MullvadVPN/TunnelManager/TunnelState+UI.swift, ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ActivityIndicator.swift, ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionView.swift, ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/ConnectionViewViewModel.swift, ios/MullvadVPN/View controllers/Tunnel/FeatureIndicators/FI_TunnelViewController.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelControlView.swift, ios/MullvadVPN/Views/BlurView.swift, ios/MullvadVPN/Views/MainButton.swift, ios/MullvadVPN/Views/MainButtonStyle.swift, ios/MullvadVPN/Views/SplitMainButton.swift, ios/MullvadVPN/Views/VisualEffectView.swift
Connection details and buttons should change depending on the tunnel state, just like the old connection view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7302)
=> Add state to new connection view

android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/AccountPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/ConnectPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/MullvadWebsite.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/SettingsPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/VpnSettingsPage.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/WireGuardCustomPortDialog.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LeakTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LogoutTest.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/WebLinkTest.kt
`LoginTest` and `ConnectionTest` was migrated since before. This PR migrates remaining end to end tests to use Page Object Pattern.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7332)
=> Migrate remaining e2e tests to POP

.github/workflows/desktop-e2e.yml
Strip architecture-specific suffix. The remaining steps assume that the windows installer has no arch-suffix.
Here is a test run to verify that it works: https://github.com/mullvad/mullvadvpn-app/actions/runs/12318721071
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7345)
=> Fix `build-windows` step in `desktop-e2e.yml`

ci/linux-repository-builder/prepare-rpm-repository.sh
Restrict the packages that our RPM repo may install/update.
Close DES-1553.
Close #6270.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7342)
=> Pin packages in RPM repo (using `includepkgs`)

talpid-core/Cargo.toml, talpid-core/src/split_tunnel/macos/process.rs
This PR touches up the FDA check code just a little bit more to ensure that no obvious bugs are still present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7338)
=> Add more tests to FDA check

desktop/package-lock.json, desktop/package.json, desktop/packages/mullvad-vpn/package.json
This PR upgrades Electron from 30.0.4 to 31.7.5, along with node to 20.18.0, TypeScript to 5.6.3 and gRPC dependencies to latest.
Relevant changelogs:
[Electron 31 changelog](https://github.com/electron/electron/releases/tag/v31.0.0)
[Electron 31 breaking changes](https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-310)
[Electron 32 changelog](https://github.com/electron/electron/releases/tag/v32.0.0)
[Electron 32 breaking changes](https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-320)
[Electron 33 changelog](https://github.com/electron/electron/releases/tag/v33.0.0)
[Electron 33 breaking changes](https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-330)
- - - …
=> Upgrade Electron to 33

test/test-manager/docs/config.md, test/test-manager/src/config.rs, test/test-manager/src/main.rs, test/test-manager/src/package.rs, test/test-manager/src/vm/provision.rs
This PR upstreams changes in preparation of running a Windows ARM guest in the test framework. None of these changes should break any existing VMs, they should be strict improvements upon the current code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7316)
=> Upstream changes from "Windows ARM in test framework"-investigation

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/info/ObfuscationInfoDialog.kt, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7352)
=> Implement increased power consumption warning

talpid-wireguard/src/wireguard_go/mod.rs
This caused a panic during the final connection check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7353)
=> Do not drop connection checker when switching between single-hop and multi-hop tuns

ios/CHANGELOG.md, ios/Configurations/Version.xcconfig
Since we've released 2024.11, I'm updating the changelog and, very optimistically, the build version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7356)
=> Bump iOS changelog and version

CHANGELOG.md, talpid-wireguard/build.rs, talpid-wireguard/src/connectivity/check.rs, talpid-wireguard/src/connectivity/mod.rs, talpid-wireguard/src/ephemeral.rs, talpid-wireguard/src/lib.rs
Fix DES-1563
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7348)
=> Force WG handshake each time the config is updated

.dockerignore, building/Dockerfile
Adding `libarchive-tools` package to base Linux container. Needed to experiment with Arch Linux package building.
Also fixes an issue in the container building since `package.json` has moved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7364)
=> Add `libarchive-tools` to container

wireguard-go-rs/libwg/osv-scanner.toml
This PR updates the osv-scanner config for `libwg` to silence [GO-2024-3105](https://osv.dev/vulnerability/GO-2024-3105), [GO-2024-3106](https://osv.dev/vulnerability/GO-2024-3106) and [GO-2024-3107](https://osv.dev/vulnerability/GO-2024-3107) for 3 more months. All of these have been fixed in go 1.23.1, so we should consider bumping our go version and unsilence these advisories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7361)
=> Silence GO-2024-{3105,3106,3107} in osv-scanner

talpid-tunnel/src/tun_provider/android/mod.rs
We messed up when refactoring before merging the rework of the new permissions system. This fixes the JNI class name matching.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7365)
=> Fix jni names

android/docker/Dockerfile, building/linux-container-image.txt
The new version of the Linux build container contains:
* Rust upgraded to 1.83
* Added package `libarchive-tools` (needed for experimenting with Arch Linux packaging
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7367)
=> Bump Linux build container to mullvadvpn-app-build:124ce3fef

talpid-wireguard/src/connectivity/check.rs
Partially revert #7348. `establish_connectivity` only works on the first attempt when enabling PQ, multihop, and udp2tcp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7368)
=> Revert reset of pinger establish timeout

mullvad-version/src/main.rs, prepare-release.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7372)
=> Add support for overriding Android version

CHANGELOG.md, talpid-wireguard/build.rs, talpid-wireguard/src/connectivity/mod.rs, talpid-wireguard/src/ephemeral.rs
This is due to #7348. Previously, this could panic since some `Tunnel` implementations use `block_on`. This was due to a bug where a blocking function was called during ephemeral peer exchange.
Since `spawn_blocking` demands a static lifetime, the fix involves using `block_in_place`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7374)
=> Do not block during ephemeral peer exchange

wireguard-go-rs/libwg/osv-scanner.toml
This PR silences yet another security advisory in the go standard library. We are unaffected by the vulnerability itself since we never parse HTML in any of our go code. As stated in https://github.com/mullvad/mullvadvpn-app/pull/7361, we could look into bumping our version of go when the fix has been released, but we don't need to worry about it atm.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7375)
=> Silence security advisory `GO-2024-3333` in osv-scanner

deny.toml
In order to somewhat keep our dependency tree, compile times and bugs down, we should avoid certain crates. We already do this, but the list was very short. Here are some more crates that it would be good if we avoided (accidentally?) depending on. As long as there are viable alternatives we should never use these crates.
If we come to a situation where we really have no option, entries here can be discussed of course.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7380)
=> Ban async-std and old hyper and tokio versions

mullvad-daemon/src/exception_logging/win.rs
We still pull in `winapi` as a transitive dependency via a bunch of crates. But this PR at least tries to remove the last usage of it as a direct dependency. This makes very little difference in practice, but is a step towards only using a single binding for the Windows API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7382)
=> Remove direct winapi dependency from mullvad-daemon exception handling

ios/MullvadRustRuntimeTests/MullvadPostQuantum+Stubs.swift
When adding last changes to IAN to use real names instead of abbreviations of runes, I forgot to extend those changes to the unit tests too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7391)
=> Fix borked unit test

android/CHANGELOG.md, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/data/DummyRelayItems.kt, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/CheckboxCell.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/FilterUiStatePreviewParameterProvider.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/RelayItemPreviewData.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/SelectLocationsUiStatePreviewParameterProvider.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/FilterConstrainExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayFilterUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/ProviderToOwnershipsUseCase.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCaseTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/CustomListLocationsViewModelTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModelTest.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/daemon-grpc/src/test/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/RelayNameComparatorTest.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/Provider.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/ProviderId.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/RelayItem.kt, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
This PR changes the one-to-one relationship to one-to-many between provider and ownership.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7386)
=> Disconnect provider and ownership

Cargo.lock, talpid-core/Cargo.toml, talpid-core/src/firewall/macos.rs
Just as the title says: Remove the use `duct` in the macOS firewall module in favor of using an equivalent function in the `pfctl` crate. This finally reverts https://github.com/mullvad/mullvadvpn-app/pull/3046 :tada:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7392)
=> Remove `duct` as a macOS dependency in `talpid-core`

Cargo.lock, talpid-tunnel-config-client/Cargo.toml, talpid-tunnel-config-client/src/lib.rs, talpid-wireguard/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7396)
=> Improve-ephemeral-peer-error-logs

desktop/packages/mullvad-vpn/src/renderer/components/EditApiAccessMethod.tsx, desktop/packages/mullvad-vpn/src/renderer/components/EditCustomBridge.tsx, desktop/packages/mullvad-vpn/src/renderer/components/ProxyForm.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7362)
=> Fix spacing in proxy form

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
Moved the tapjacking one step below in the view hierarchy. This is to allow full functionality for some other apps, while still preventing tapjacking attacks on affected Android versions.
This was tested using: https://github.com/carlospolop/Tapjacking-ExportedActivity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7393)
=> Improve tapjacking prevention to not block other apps

ios/CHANGELOG.md, ios/MullvadRustRuntime/EphemeralPeerReceiver.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadTypes/Protocols/DaitaV2Parameters.swift, ios/MullvadTypes/Protocols/EphemeralPeerReceiver.swift, ios/MullvadTypes/Protocols/EphemeralPeerReceiving.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, ios/PacketTunnel/PostQuantum/EphemeralPeerExchangingPipeline.swift, ios/PacketTunnel/PostQuantum/MultiHopEphemeralPeerExchanger.swift, ios/PacketTunnel/PostQuantum/SingleHopEphemeralPeerExchanger.swift, ios/PacketTunnelCore/Actor/EphemeralPeerNegotiationState.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor.swift, ios/PacketTunnelCore/Actor/Protocols/EphemeralPeerExchangingProtocol.swift, ios/PacketTunnelCore/Daita/Maybenot.swift, ios/PacketTunnelCoreTests/EphemeralPeerExchangingPipelineTests.swift, ios/PacketTunnelCoreTests/Mocks/EphemeralPeerExchangeActorStub.swift, ios/PacketTunnelCoreTests/Mocks/KeyExchangingResultStub.swift, ios/PacketTunnelCoreTests/MultiHopEphemeralPeerExchangerTests.swift, ios/PacketTunnelCoreTests/SingleHopEphemeralPeerExchangerTests.swift, mullvad-ios/src/ephemeral_peer_proxy/ios_tcp_connection.rs, mullvad-ios/src/ephemeral_peer_proxy/mod.rs, mullvad-ios/src/ephemeral_peer_proxy/peer_exchange.rs, talpid-tunnel-config-client/src/lib.rs
On the back of @buggmagnet and @dlon work, I've gone and rebased things and touched everything up. These changes enable DAITAv2 on iOS. It seems to work :shrug:.
These changes depend on https://github.com/mullvad/wireguard-apple/pull/34 being merged first. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7387)
=> Add DAITAv2 on iOS

Cargo.lock, android/app/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/di/UiModule.kt, android/lib/endpoint/src/main/kotlin/net/mullvad/mullvadvpn/lib/endpoint/ApiEndpointOverride.kt, android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/MockApiTest.kt, ios/MullvadVPNUITests/MullvadApi.swift, mullvad-api/Cargo.toml, mullvad-api/include/mullvad-api.h, mullvad-api/src/address_cache.rs, mullvad-api/src/bin/relay_list.rs, mullvad-api/src/ffi/error.rs, mullvad-api/src/ffi/mod.rs, mullvad-api/src/https_client_with_sni.rs, mullvad-api/src/lib.rs, mullvad-api/src/rest.rs, mullvad-daemon/src/api.rs, mullvad-daemon/src/api_address_updater.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/main.rs, mullvad-jni/src/api.rs, mullvad-jni/src/lib.rs, mullvad-jni/src/problem_report.rs, mullvad-problem-report/src/lib.rs, mullvad-problem-report/src/main.rs, mullvad-setup/src/main.rs, test/test-manager/src/tests/account.rs
This particular changeset started off with adding a unit test to see why the iOS end-to-end API client is failing. I fixed it and added a test to ensure it doesn't get broken again. Adding a test implied removing some _global state_, namely the global `ApiEndpoint`.  The test itself is using `httpmock` and exercising the FFI that the Swift test client is using.  I have tested these changes with various Android builds, will try out the app with stagemole later too. I am not entirely certain if removing the global state has made the code any more readable or better, but it certainly has improved the testability. 
This then bubbled over into refactoring the daemon parameters just one slight bit - I am not certain it is a change we need, and thus can drop the last commit.
- - -
This change …
=> Remove global API endpoint

mullvad-cli/Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-problem-report/Cargo.toml, talpid-openvpn-plugin/Cargo.toml, windows-installer/Cargo.toml
This PR updates `LegalCopyright` year to 2025 for all applicable `mullvad-` & `talpid-` crates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7406)
=> Update LegalCopyright year to 2025

Cargo.lock, talpid-tunnel/Cargo.toml, talpid-tunnel/src/tun_provider/android/mod.rs, talpid-tunnel/src/tun_provider/unix.rs, talpid-wireguard/src/wireguard_go/mod.rs
This PR removes `duct` from the `talpid-tunnel` crate. While doing so, I refactored some code that is responsible for configuring tun devices to use `tun 0.7`, up from the previous dependency on `tun 0.5`. This allowed me to remove spawning an `ip` subprocess on Linux and instead use syscalls (under the hood).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7410)
=> Remove `duct` from `talpid-tunnel`

Cargo.lock, Cargo.toml, talpid-tunnel/Cargo.toml, talpid-tunnel/src/tun_provider/mod.rs, talpid-tunnel/src/tun_provider/unix.rs
This PR is a follow up to https://github.com/mullvad/mullvadvpn-app/pull/7410 which just cleans up code in the `talpid-tunnel` by leveraging the `async` feature of `tun`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7411)
=> Cleanup talpid tunnel `unix` module

Cargo.lock, Cargo.toml, test/Cargo.lock, test/Cargo.toml
Simple bump of `thiserror` to version 2. We already have it in our tree, and it requires no modification to our code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7414)
=> Upgrade `thiserror` to version 2

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SearchLocationScreen.kt
Request focus to the search input when opening the search view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7403)
=> Open keyboard immediately on opening search

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/component/ConnectionStatusText.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/FlowUtils.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModelTest.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/NotificationTunnelState.kt, android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/tunnelstate/TunnelStateNotificationAction.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/tunnelstate/TunnelStateNotificationProvider.kt, desktop/packages/mullvad-vpn/locales/messages.pot
This PR correctly shows the tunnel state in some fast transient states. E.g when disconnecting, we previously showed disconnected but the state has not fully reached disconnected yet. Same goes for blocking, (going from Connected to Blocked state), the UI would still show Connected while in fact we are migrating to another state. 
This has no security implication just being more accurate and transparent with what actual state that is happening. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7401)
=> Be more clear with connection state

CHANGELOG.md, talpid-wireguard/src/lib.rs
This PR fixes a regression introduced in the 2025.1 release. The fix is simple enough, simply call `log_tunnel_data_usage` from a thread where blocking is acceptable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7425)
=> Fix bug where `block_on` was called from an async context

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreenTest.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/preview/FilterUiStatePreviewParameterProvider.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/FilterScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/FilterConstrainExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/state/RelayFilterUiState.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCase.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModel.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/repository/RelayListFilterRepositoryTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/FilterChipUseCaseTest.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/viewmodel/FilterViewModelTest.kt, android/lib/common-test/src/main/java/net/mullvad/mullvadvpn/lib/common/test/TestUtils.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/FromDomain.kt, android/lib/daemon-grpc/src/main/kotlin/net/mullvad/mullvadvpn/lib/daemon/grpc/mapper/ToDomain.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/Providers.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7389)
=> Use constraints in UI state for FilterScreen

README.md
This PR updates the README file to indicate that Wireguard over Shadowsocks is available on iOS.
Much thanks goes to @tunadreno for pointing out that we had missed that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7431)
=> Update README indicating wireguard over shadowsocks availability on iOS

test/test-manager/src/main.rs, test/test-manager/src/tests/access_methods.rs, test/test-manager/src/tests/audits/cve_2019_14899.rs, test/test-manager/src/tests/audits/mllvd_cr_24_03.rs, test/test-manager/src/tests/config.rs, test/test-manager/src/tests/dns.rs, test/test-manager/src/tests/relay_ip_overrides.rs, test/test-manager/src/tests/tunnel.rs, test/test-manager/src/vm/network/linux.rs, test/test-manager/src/vm/network/macos.rs, test/test-manager/src/vm/network/mod.rs
The IP of the bridge interface was incorrectly assumed to be constant, but has at some point changed. This broke the algorithm  or finding the bridge interface.
Replace the algorithm with one based on the guest IP, which is given by `tart`. As the bridge IP is no longer constant, we also  expose it through the `TEST_CONFIG`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7429)
=> Use bridge interface IP from `tart`

CHANGELOG.md
This PR recognizes this user-facing change in the changelog: https://github.com/mullvad/mullvadvpn-app/pull/7312.
This changelog addition should also be ported to the release branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7435)
=> Add new "changelog view" to the changelog

test/test-runner/src/logging.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7423)
=> Do not truncate `settings.json`

talpid-tunnel/src/tun_provider/unix.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7438)
=> Use `ip -6 addr` command for setting ipv6 addr on linux.

CHANGELOG.md
This PR documents https://github.com/mullvad/mullvadvpn-app/pull/7432 in the changelog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7441)
=> Add "pre-computing McEliece keys" to changelog

ios/MullvadSettings/KeychainSettingsStore.swift, ios/MullvadSettings/KeychainSettingsStoreMigration.swift, ios/MullvadSettings/SettingsManager.swift, ios/MullvadSettings/SettingsStore.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPNTests/MullvadSettings/InMemorySettingsStore.swift
This PR excludes keychain items from backups.
From now on, when a user migrates their phone to a new phone from a backup, Mullvad's settings will not migrate and the user will have to re-log in on their new devices.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7430)
=> Exclude keychain items from backups

desktop/packages/mullvad-vpn/tasks/distribution.js
Enable the `signAndEditExecutable` electron-builder option, which allows electron-builder to add metadata to the produced binary / app installer. Without this option enabled, the electron app was missing the Mullvad app icon. This option was disabled by accident, and the default value is also true.
Here are the relevant electron-builder docs: https://www.electron.build/win.html#signandeditexecutable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7448)
=>  Add back missing app icon on Windows

.github/workflows/android-app.yml, android/app/build.gradle.kts
The plugin would not correctly realize changes made to the native code. Related issue:
https://github.com/mozilla/rust-android-gradle/issues/118#issuecomment-1569407058
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7446)
=> Fix gradle rust android plugin

ios/MullvadVPN/Coordinators/Settings/DAITA/DAITASettingsPromptItem.swift, ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift
This PR updates the copyright text and replaces the info icon with a warning icon in the popup displayed when a user enables 'Direct Only' while the selected location does not support Daita.
<table style="width: 100%; max-width: 828px; table-layout: fixed; border-collapse: collapse; text-align: center;">
<tr>
<th style="width: 50%; padding: 10px; font-size: 18px; font-family: Arial, sans-serif; background-color: #f2f2f2;">
Before
</th>
<th style="width: 50%; padding: 10px; font-size: 18px; font-family: Arial, sans-serif; background-color: #f2f2f2;">
After
</th>
</tr>
<tr>
<td style="width: 50%; text-align: center; padding: 10px;">
</td>
<td style="width: 50%; text-align: center; padding: 10px;">
</td>
</tr>
</table>
- - - …
=> Update Direct only pop up design

CHANGELOG.md, talpid-types/src/net/mod.rs, talpid-types/src/net/obfuscation.rs, talpid-types/src/net/wireguard.rs, talpid-wireguard/src/lib.rs
This PR fixes a bug where the wrong route(s) would be added when Shadowsocks obfuscation with extra in IPs where used. Previously, we would always add a route to the relay's public IP, but not to the obfuscator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7459)
=> Add route to obfuscator on relay (if applicable)

desktop/packages/mullvad-vpn/src/renderer/components/NavigationScrollbars.tsx, desktop/packages/mullvad-vpn/src/renderer/components/cell/Section.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/history.tsx
This PR fixes the saving of the scroll position and section expanded state when navigating. When navigating back the previous scroll position should still apply for users not to lose context. This regressed in [This PR](https://github.com/mullvad/mullvadvpn-app/pull/6972) where the state was saved to the new location instead of the previous one when navigating.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7462)
=> Fix saving scroll and expanded state to correct location object

wireguard-go-rs/build.rs
See https://github.com/mullvad/mullvadvpn-app/actions/runs/12792796100/job/35664092183?pr=7457.
```
error: variant name ends with the enum's name
```
This error doesn't make any sense in this case, but renaming it was nicer than disabling the warning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7469)
=> Fix enum variant lint error

android/app/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
This fixes a leak of the service connection reference that was introduced when migrating to DataStore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7470)
=> Rely on connectionState to decide if to unbind the service

ios/CHANGELOG.md, ios/MullvadVPN/Coordinators/Settings/Views/SettingsInfoContainerView.swift, ios/MullvadVPN/Coordinators/Settings/Views/SettingsInfoView.swift
DAITA settings view was broken on iOS 15 devices due to SwiftUI List bug. This PR fixes the issue by using ScrollView instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7465)
=> Fix daita settings view on ios 15

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/HeaderView.swift
The chevron in the connection view was a little squeezed to one side. Now it follows the figma design
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7476)
=> Use padded chevron image to follow figma design

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipView.swift
The feature indicators were slightly clipped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7474)
=> Fix clipped feature indicators

ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
This PR makes sure the Activity Indicator is in front of the Connection View when connecting to a relay.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7492)
=> Move the spinner in front of the Connection View

.github/workflows/clippy.yml, Cargo.toml, android/app/build.gradle.kts, build.sh, ci/check-rust.sh
We included almost every crate in `default-members`. All crates except `windows-installer` which could not build without specific inputs as to what installers to include (it built a full universal installer, bundling arch specific installers at build time). This list had a lot of duplication and seems like a bit of a mess to maintain.
Since our workspace also contained virtually everything, a simple `cargo build` built everything, which might not be desired from a build time perspective. This PR reduce the `default-members` to some "sane default" bare minimum. It includes `mullvad-daemon` and `mullvad-cli` because those are the main binaries, and anyone building this project is most likely after those binaries. It also includes `mullvad-version` since we have a ton of invocations to …
=> Remove most `default-members` to speed up builds and reduce duplication

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AppRoutes.swift, ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/LocationCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/DAITA/DAITASettingsCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift
When the user has enabled DAITA and multihop, the entry location view should have a button that takes the user straight to the DAITA settings. Currently, said button takes the user to the root of the settings view instead.
To reproduce:  Enable DAITA and multihop, go to entry locations, and tap the Open DAITA settings button.
Expected result: the user is taken to DAITA settings
Actual result: the user is taken to the top-level VPN settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7491)
=> Fix target destination of DAITA button in location view

CHANGELOG.md, desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, mullvad-daemon/src/lib.rs, mullvad-daemon/src/settings/mod.rs
Fix daemon ending up in blocked state if the user toggled split tunneling without having granted Full Disk Access to `mullvad-daemon`. This could only ever be accomplished from the CLI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7473)
=> Fix ending up in blocked state when disabling split tunnel

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionView.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionViewViewModel.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift, ios/MullvadVPN/Views/BlurView.swift
The blurred background in the connection view is transparent in iOS15. We should fix it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7479)
=> Fix connection view background in iOS15

ios/MullvadVPN/Coordinators/LocationCoordinator.swift, ios/MullvadVPN/Extensions/UIAlertController+InAppPurchase.swift, ios/MullvadVPN/UI appearance/UIColor+Palette.swift
This pr fixes the crash problem in showing alert for adding more time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7499)
=> Fix crash on showing alert for in-app purchase

ios/CHANGELOG.md, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/Classes/AppRoutes.swift, ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/ChangeLogCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/SettingsViewControllerFactory.swift, ios/MullvadVPN/Notifications/InAppNotificationDescriptor.swift, ios/MullvadVPN/Notifications/Notification Providers/LatestChangesNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/NewDeviceNotificationProvider.swift, ios/MullvadVPN/Notifications/NotificationProviderIdentifier.swift, ios/MullvadVPN/Notifications/UI/NotificationBannerView.swift, ios/MullvadVPN/Notifications/UI/NotificationController.swift, ios/MullvadVPN/SceneDelegate.swift, ios/MullvadVPN/View controllers/ChangeLog/ChangeLogView.swift, ios/MullvadVPNUITests/Base/BaseUITestCase.swift, ios/MullvadVPNUITests/Base/LoggedInWithTimeUITestCase.swift, ios/MullvadVPNUITests/Base/LoggedOutUITestCase.swift, ios/MullvadVPNUITests/SettingsMigrationTests.swift
This PR adds in-app notification once app is updated. in addition, It shows the changes when user taps whole notification bar.
<table style="width: 100%; max-width: 828px; table-layout: fixed; border-collapse: collapse; text-align: center;">
<tr>
<th style="width: 50%; padding: 10px; font-size: 18px; font-family: Arial, sans-serif; background-color: #f2f2f2;">
First
</th>
<th style="width: 50%; padding: 10px; font-size: 18px; font-family: Arial, sans-serif; background-color: #f2f2f2;">
Second
</th>
</tr>
<tr>
<td style="width: 50%; text-align: center; padding: 10px;">
</td>
<td style="width: 50%; text-align: center; padding: 10px;">
</td>
</tr>
</table> 
- - - …
=> Add in-app notification for latest changes

desktop/packages/mullvad-vpn/src/renderer/app.tsx
The ErrorBoundary is currently outside of the Theme component which causes it to not have access to all css variables. This PR fixes the issue by wrapping the ErrorBoundary inside the Theme.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7505)
=> Move ErrorBoundary into Theme

Cargo.lock, talpid-wireguard/Cargo.toml, talpid-wireguard/src/connectivity/check.rs, talpid-wireguard/src/connectivity/constants.rs, talpid-wireguard/src/connectivity/mock.rs, talpid-wireguard/src/connectivity/mod.rs, talpid-wireguard/src/connectivity/monitor.rs, talpid-wireguard/src/connectivity/pinger/android.rs, talpid-wireguard/src/connectivity/pinger/icmp.rs, talpid-wireguard/src/connectivity/pinger/mod.rs, talpid-wireguard/src/ephemeral.rs, talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_go/mod.rs, talpid-wireguard/src/wireguard_kernel/netlink_tunnel.rs, talpid-wireguard/src/wireguard_kernel/nm_tunnel.rs, talpid-wireguard/src/wireguard_nt/mod.rs
This rewrites the pinger/connectivity checker, and some other pieces of `talpid-wireguard` to be async.
One benefit is that tests run faster, since we can mock time now. Running the tests for `talpid-wireguard` take about 1 ms instead of 20 seconds.
I only intend on making it *less* bad than before. There is still room for more refactoring. A lot of mixing of async/sync in places surrounding the `Tunnel` trait mixes sync and async, still.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7390)
=> Refactor connection check to be async

ios/MullvadVPNUITests/RelayTests.swift, ios/MullvadVPNUITests/tests.json
The above tests are failing after merging feature indicator views, which is reason enough to fix them. 
https://github.com/mullvad/mullvadvpn-app/actions/runs/12871536677/job/35885195591
The running theory is that these tests rely on the connection view being expanded, but you might need to do further investigation.
- testWireGuardOverTCPAutomatically passes in CI
- testConnectionRetryLogic passes in CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7502)
=> Fix testWireGuardOverTCPAutomatically and testConnectionRetryLogic

ios/Snapfile
Screenshot tests fail due to using the wrong iPad models. We should use `iPad Pro (11-inch) (M4)` and `iPad Pro (13-inch) (M4)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7503)
=> Update screenshot tests to use correct iPad models

android/app/build.gradle.kts, android/buildSrc/src/main/kotlin/Utils.kt, building/rustc-remap-path-prefix.sh
This is needed for reproducible builds. The script  gets the file paths to the user's Cargo and Rustup home dirs, as well as the path to the Mullvad app source dir. These paths are then remapped to fixed values which is needed to make the build reproducible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7512)
=> Add script to generate rustc --remap-path-prefix

ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift, ios/MullvadVPN/TunnelManager/BackgroundTaskProvider.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPNTests/MullvadVPN/RelayCacheTracker/RelayCacheTracker+Stubs.swift, ios/Operations/ResultOperation.swift
This PR should fix the crash we've been encountering in the latest beta version of the app.
It does so by forcing the registered tasks completion handlers to run on the main thread of the application.
It also removes some of the `nonisolated(unsafe)` markers that were added in those completion handlers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7510)
=> Fix crash in dispatch queue assertion with background tasks

ios/MullvadREST/Relay/RelaySelector+Shadowsocks.swift, ios/MullvadREST/Relay/RelaySelector+Wireguard.swift, ios/MullvadREST/Relay/RelaySelector.swift, ios/MullvadREST/Relay/RelayWithLocation.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionViewComponentPreview.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionViewViewModel.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/DestinationDescriber.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift, ios/MullvadVPNTests/MullvadVPN/View controllers/Tunnel/DestinationDescriberTests.swift
This updates the Connect button to show the name of the selected destination. If the user has selected a custom list, this will be the list name, otherwise depending on the relays chosen, it will be in the format "Country", "City, Country" or "City (hostname)".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7495)
=> IOS-995 Show exit constraints in connect view

.github/workflows/clippy.yml, .github/workflows/daemon.yml, .github/workflows/desktop-e2e.yml, .github/workflows/rust-unused-dependencies.yml, .gitignore, BuildInstructions.md, CHANGELOG.md, Cargo.lock, build.sh, desktop/packages/mullvad-vpn/tasks/distribution.js, talpid-tunnel-config-client/src/lib.rs, talpid-wireguard/Cargo.toml, talpid-wireguard/build.rs, talpid-wireguard/src/connectivity/mock.rs, talpid-wireguard/src/ephemeral.rs, talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_go/mod.rs, talpid-wireguard/src/wireguard_nt/mod.rs, wireguard-go-rs/Cargo.toml, wireguard-go-rs/build.rs, wireguard-go-rs/libwg/README.md, wireguard-go-rs/libwg/libwg.go, wireguard-go-rs/libwg/libwg_android.go, wireguard-go-rs/libwg/libwg_daita.go, wireguard-go-rs/libwg/libwg_default.go, wireguard-go-rs/libwg/libwg_windows.go, wireguard-go-rs/libwg/logging/logging.go, wireguard-go-rs/libwg/tunnelcontainer/tunnelcontainer.go, wireguard-go-rs/src/lib.rs
This PR updates Windows DAITA to v2 by reintroducing wireguard-go.
- Remove wireguard-nt code for DAITA
- Use the multihop implementation of wireguard-go instead of WireguardNT
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7457)
=> Update DAITA to v2 on Windows

.github/workflows/daemon.yml
Not supported at the moment. I've installed it on the runner itself for now.
Fix DES-1675
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7527)
=> Disable `setup-zig` on Windows Arm

android/app/build.gradle.kts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7520)
=> Remove debug symbols for aab bundles

android/app/build.gradle.kts
Fdroid builds should be the same as release build when it comes to bulding cargo, eg. setting the --release flag. This is currently not true as we only check for "release" in gradle tasks and the task we use to build for fdroid `createOssProdFdroidDist[Apk/Bundle]` does not contain this keyword.
This is a stop-gap measure that just treats "fdroid" the same "release" until we can figure out a better solution for release builds.
The longterm solution is tracked in DROID-1696.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7531)
=> Treat fdroid builds the same as release builds

wireguard-go-rs/libwg/libwg_windows.go
`C.CString` allocates a new string, but there was no corresponding call to `C.free`. This is recent: It slipped in with https://github.com/mullvad/mullvadvpn-app/commit/654de1cd2d3cdde6a3c26fe0cf5f26a4b0d1a89c
I'm sure there's a way to do this without allocating, but this seemed like the simplest approach.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7529)
=> Fix memory leak in libwg_windows.go

building/rustc-remap-path-prefix.sh
This PR aims to add remapping support for `CARGO_TARGET_DIR` instead of relying on it existing under the project root. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7533)
=> Add support for target dir in rustc remapping

mullvad-types/src/wireguard.rs
As the interval wasn't inclusive, `MAX_ROTATION_INTERVAL - 1 hr` was the maximum value that could be set.
Close #7526
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7532)
=> Allow maximum rotation interval to be set in CLI

wireguard-go-rs/libwg/osv-scanner.toml
This PR silences [`CVE-2024-45336`](https://osv.dev/vulnerability/GO-2025-3420) and [`CVE-2024-45341`](https://osv.dev/vulnerability/GO-2025-3373) which are both vulnerabilities found in the go standard library. The affected functions are not used in `wireguard-go`, so we are unaffected. Upgrading to `go 1.24` (when it is released) will allow us to un-silence these CVEs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7538)
=> Silence `CVE-2024-45336` and `CVE-2024-45341` in osv-scanner

.github/workflows/android-app.yml, android/app/build.gradle.kts, android/buildSrc/src/main/kotlin/Utils.kt, android/scripts/update-lockfile.sh, android/service/build.gradle.kts, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/util/ContextExtensions.kt, prepare-release.sh
For dev builds we rely on the app to download the relay list from the api. This will make the app behave a bit weird if it is not able to download the relay list
For release builds on release branches we will generate a relay list and commit it to the branch. This will then be used by the app and thus release builds will have a bundled `relays.json`.
This is required for reproducible builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7518)
=> Bundle a pre-generated relay list instead of generating one on android

CHANGELOG.md, android/CHANGELOG.md, ios/CHANGELOG.md, mullvad-encrypted-dns-proxy/src/config_resolver.rs
What is says on the tin - remove Google's resolvers from `mullvad-encrypted-dns-proxy`.  Maybe the changelog should say _stop using_ Google's resolvers?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7539)
=> Remove Google's resolvers from encrypted DNS proxy

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionView.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionViewViewModel.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/HeaderView.swift
This PR toggles the visibility of the connection detail info base on tunnel state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7534)
=> Hide connection details view based on tunnel status

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
This bumps wireguard-apple so that we have the latest changes, which hopefully improves the amount of go crashes we're seeing. And there's a stray xcodeproj change removing the last reference to `ProductState.swift`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7540)
=> Bump wireguard-apple

ios/MullvadVPN/Notifications/Notification Providers/AccountExpiryInAppNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/AccountExpirySystemNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/LatestChangesNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/NewDeviceNotificationProvider.swift, ios/MullvadVPN/Notifications/Notification Providers/TunnelStatusNotificationProvider.swift, ios/MullvadVPN/Notifications/NotificationManager.swift, ios/MullvadVPN/Notifications/NotificationProvider.swift, ios/MullvadVPN/Notifications/NotificationProviderIdentifier.swift, ios/MullvadVPN/Notifications/NotificationProviderProtocol.swift
This PR adds priority to notifications. In addition, notifications with same priorities are shown based on the creation date.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7530)
=> Add priority for notifications

.github/workflows/android-kotlin-format-check.yml, android/build.gradle.kts, android/buildSrc/build.gradle.kts, android/buildSrc/settings.gradle.kts, android/buildSrc/src/main/kotlin/BuildVariants.kt, android/buildSrc/src/main/kotlin/Extensions.kt, android/buildSrc/src/main/kotlin/Utils.kt
To format `buildSrc` it is required to run `:buildSrc:ktfmtFormat` separately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7541)
=> Implement detekt and ktfmt for buildSrc

ios/MullvadLogging/LogFileOutputStream.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPNTests/MullvadLogging/LogFileOutputStreamTests.swift, ios/MullvadVPNTests/MullvadLogging/LogRotationTests.swift
This PR changes the way we handle log files.
Instead of splitting a log file in several subfiles, we now truncate the logfile in half
when reaching a maximum file size
The old split files (`file_1.log`,`file_2.log`, etc...) will naturally be pruned over time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7519)
=> Truncate the current log file in half when reaching size limit

.github/workflows/android-app.yml
This PR aims to move the `debug.keystore` used in GitHub actions workflows for test and verification into a secret in order to simplify and speed up our workflow. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7555)
=> Move actions `debug.keystore` to secret

.github/workflows/testframework.yml, build.sh, desktop/packages/nseventforwarder/package.json, windows/nsis-plugins/src/cleanup/cleanup.vcxproj, windows/nsis-plugins/src/log/log.vcxproj
We want to exit with an error if we try to produce a release build with an outdated lockfile. Such builds could be really hard to reproduce later, and is a supply chain risk. Being strict in CI is a good way of making sure we don't merge changes that require lockfile updates, but that were forgotten.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7524)
=> Add locked to various cargo build invocations for desktop

ios/MullvadVPN/AppDelegate.swift
Even though the signature for `expirationHandler` has no meniton of sendability and there's a distinct lack of documentation about where exactly the expiration handler would be invoked, whatever is invoked there is checked at runtime to be dispatched on the main thread. Unless it's marked as sendable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7556)
=> Use a sendable closure for task expiry

ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift
This ensures that the "what's new" notice does not appear in the "Too many devices" screen as the user is logging in.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7545)
=> Configure device management screen to hide notification bar

test/Cargo.lock, test/deny.toml, test/osv-scanner.toml, test/test-manager/Cargo.toml
Since `ssh2 0.9.5` was released this weekend, we no longer have to silence `RUSTSEC-2024-0384` in osv-scanner nor cargo-deny! :tada:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7572)
=> Unsilence `RUSTSEC-2024-0384` in osv-scanner & cargo-deny

android/gradle/osv-scanner.toml
Actually manually ran a scheduled scan this time:
https://github.com/mullvad/mullvadvpn-app/actions/runs/13130795543/job/36635362299
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7588)
=> Restore osv scanner vuln ignore that is still required

test/test-manager/src/config/vm.rs, test/test-manager/src/main.rs, test/test-manager/src/vm/qemu.rs, test/test-manager/src/vm/tart.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7586)
=> Add CPU count configuration to test framework

.github/workflows/desktop-e2e.yml
Too many PRs. Apparently, this broke when adding wireguard-go-rs (except on `main`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7592)
=> Fix E2E build task for Windows

test/docs/BUILD_OS_IMAGE.md
It turns out that shutting down the VM with the test runner image mounted results in a weird state. I've added this to the documentation.
This explains why the Windows 11 VM was failing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7590)
=> Document mounting issue for the testing framework

talpid-wireguard/src/wireguard_go/mod.rs
This PR removes a lot of excess calls to `openTun` during the tunnel setup by re-using the same tunnel FD while restarting wireguard-go. This is accomplished by not changing the routes in the tunnel configuration, as Kotlin will avoid _actually_ calling `createTun` if the configuration doesn't change across calls to `openTun`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7596)
=> Fix excess `createTun` calls with multihop and PQ/DAITA

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadButton.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/button/MullvadSegmentedButton.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/cell/NavigationComposeCell.kt, android/lib/theme/src/main/kotlin/net/mullvad/mullvadvpn/lib/theme/Theme.kt
This is because snack bars uses body medium and we want snack bars to have the standard look.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7599)
=> Replace usage of body medium with title medium

ios/MullvadVPN/View controllers/Settings/SettingsCellFactory.swift, ios/MullvadVPN/View controllers/Settings/SettingsDataSource.swift
Cells in the settings page would fluctuate on view appearance between subtitle and regular styles. This was due to all cells having the same reuse identifier, despite changelog cells being created with the `subtitle` style while others had the `default` style.  This change gives changelog cells their own reuse identifier, fixing this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7585)
=> Split cell reuse identifiers to segregate subtitle cells

ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift
Earlier the spinner in the map view was visible until the map reached the connected location. Now the spinner disappears as soon as the connected state is reached.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7578)
=> Hide loading spinner immediatly on connect

ios/Configurations/UITests.xcconfig.template, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPNUITests/Base/BaseUITestCase.swift, ios/MullvadVPNUITests/ConnectivityTests.swift, ios/MullvadVPNUITests/Info.plist, ios/MullvadVPNUITests/LeakTests.swift, ios/MullvadVPNUITests/Networking/FirewallClient.swift, ios/MullvadVPNUITests/Networking/FirewallRule.swift, ios/MullvadVPNUITests/Networking/LeakCheck.swift, ios/MullvadVPNUITests/Networking/Networking.swift, ios/MullvadVPNUITests/Networking/PacketCapture.swift, ios/MullvadVPNUITests/Networking/TestRouterAPIClient.swift, ios/MullvadVPNUITests/Networking/TrafficGenerator.swift, ios/MullvadVPNUITests/RelayTests.swift, ios/MullvadVPNUITests/tests.json
Adds basic leak tests which makes sure that traffic to a specific host goes through tunnel. There's a lot of room for improvement in how the window for packet capture is determined. Since local APIs cannot be accessed once connected to a relay the packet capture is started before connecting to relay, and stopped after disconnecting. Then a few seconds is trimmed from the beginning and end of the packet capture in order to not get any packet capture from when the tunnel connection was not up.
The changes in this PR can be tested by running the end to end tests `testNoLeak` and `testShouldLeak`.
Note: there's a known issue with the traffic generation. After setting up a tunnel connection all the connections for dummy traffic are blocked.
- - - …
=> Add negative leak test for iOS

ios/MullvadVPN/View controllers/Settings/SwiftUI components/SingleChoiceList.swift
This fixes IOS-1052 and IOS-1055. The former by separating the logic behind row selection from input field focus, the latter by removing system list item separators that somehow were still around.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7613)
=> IOS-1052/IOS-1055 SingleChoiceList wonkiness fixes

desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json
This PR bumps electron to a new patch version in order to fix a bug where the app would crash on launch due to the `shell.readShortcutLink` electron API crashing when parsing some app shortcuts on Windows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7611)
=> Update electron to 33.4.0

talpid-wireguard/src/wireguard_go/mod.rs
This PR simply backports https://github.com/mullvad/mullvadvpn-app/pull/7596 to the 2025.1 android release branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7618)
=> Backport "Fix excess opentun calls" to `prepare-android/2025.1`

.github/workflows/android-app.yml, .github/workflows/clippy.yml, .github/workflows/daemon.yml, .github/workflows/desktop-e2e.yml, .github/workflows/ios-rust-ffi.yml, .github/workflows/osv-scanner-pr.yml, .github/workflows/osv-scanner-scheduled.yml, .github/workflows/rust-unused-dependencies.yml, README.md, android/BuildInstructions.md, android/docker/Dockerfile, android/docs/BuildInstructions.macos.md, ci/buildserver-build-android.sh, ci/buildserver-build.sh, wireguard-go-rs/Cargo.toml, wireguard-go-rs/build.rs, wireguard-go-rs/libwg/Android.mk, wireguard-go-rs/src/lib.rs
This PR is a sibling-PR to https://github.com/mullvad/wireguard-go/pull/22.
This switches to a version of the `wireguard-go` submodule where `maybenot-ffi` is not included and built as a submodule. Instead there is a local crate in `wireguard-go` that acts as a simple wrapper around `maybenot-ffi`, with helper files to build it for static linking. This allows us to include the wrapper (and transitively all its dependencies) in our main workspace and track all dependency versions and checksums here. This simplifies dependency management, reproducible builds and supply chain security checks.
This PR is going to be colliding a bit with DAITA v2 for Windows (#7457), we have to discuss which one to get merged first.
Fixes DES-1360 and DES-1645
- - - …
=> Take control over maybenot dependencies and verification

.github/workflows/android-app.yml
This PR aims to enable using two e2e test accounts on separate e2e test runners/devices. This approach can also easily be expanded to add more runner/device connected accounts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7614)
=> Enable using two accounts for e2e tests

mullvad-version/src/lib.rs
The formatted string was missing the "20" prefix, as the `year` field only includes the last two digits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7619)
=> Fix `Display` implementation on `mullvad_version::Version`

CHANGELOG.md, Cargo.lock, Cargo.toml, talpid-core/Cargo.toml, talpid-tunnel/src/tun_provider/unix.rs
`tun` tries to set up routes for us by running `route` commands, which we do not want. This PR fixes this by downgrading to 0.5. We need to make it possible to disable this behavior before upgrading to 0.7 again.
Related PR: https://github.com/mullvad/mullvadvpn-app/pull/7649
Close DES-1725
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7651)
=> Downgrade to tun 0.5.5

ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
Going by Eskimo's recommendations, let's log an entry as soon as our logger is configured.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7663)
=> Log as soon as the logger is up

talpid-core/src/tunnel_state_machine/disconnecting_state.rs
Refactor `DisconnectingState::handle_commands` to reduce code duplication.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7664)
=> Refactor `DisconnectingState::handle_commands`

mullvad-daemon/src/android_dns.rs
We only want a single lookup attempt for `*.am.i.mullvad.net`, since we already have retry logic for these lookups, and `getaddrinfo` doesn't retry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7612)
=> Remove retry attempts from hickory resolver

.github/workflows/git-commit-message-style.yml, desktop/packages/mullvad-vpn/test/e2e/installed/state-dependent/openvpn-tunnel-state.spec.ts, desktop/packages/mullvad-vpn/test/e2e/installed/state-dependent/tunnel-state.spec.ts, test/test-manager/src/tests/ui.rs
This PR improves the tunnel state test by:
* Splitting out OpenVPN specific tests to a separate file
* Removes some redundant OpenVPN tests
* Better matches the "In" label in the connection panel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7615)
=> Improve tunnel state test

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/dialog/RedeemVoucherDialog.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomListNameTextField.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomPortTextField.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/CustomTextField.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/DnsTextField.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/textfield/MtuTextField.kt
They were using `bodyMedium` and that was changed to the default value.
This PR set it explicitly to `titleMedium` to make it look like it was before the change of `bodyMedium`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7633)
=> Set font size of dialog inputs to be title medium

android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/TooManyDevicesMockApiTest.kt
This PR aims to a fix a mockapi test wait condition in the device list screen. The code didn't do what the related code comment suggested.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7681)
=> Fix mockapi device list test wait condition

.github/workflows/android-kotlin-format-check.yml, android/buildSrc/settings.gradle.kts
This PR aims to fix the kotlin formatting workflow that runs in GH actions by adding the path for `*.kts` files.
Fixes: DROID-1815
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7683)
=> Fix kotlin formatting paths in ci

ios/MullvadREST/Transport/TransportProvider.swift, ios/MullvadRustRuntime/EncryptedDNSProxy.swift
The access method now rotates after encrypted dns failed.
Can be testes by blocking all traffic from a device and then trying log in.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7678)
=> Fix access method rotation after dns proxy failure

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/DetailsView.swift, ios/MullvadVPNUITests/Networking/TrafficGenerator.swift, ios/MullvadVPNUITests/Pages/TunnelControlPage.swift, ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift, ios/MullvadVPNUITests/RelayTests.swift
This PR adds an end to end test that connects to a relay using UDP-over-TCP obfuscation on port80.
The test also verifies using packet capture that the traffic sent to the relay during its course is happening exclusively on port 80 using a TCP connection.
The PR also fixes an innocent mistake in `DetailsView.swift` and makes the chevron icon accessibility tap action actually expand the connection details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7668)
=> Add an end to end test for UDP-over-TCP on port 80

ios/MullvadSettings/TunnelSettings.swift, ios/MullvadSettings/TunnelSettingsStrategy.swift, ios/MullvadSettings/TunnelSettingsUpdate.swift, ios/MullvadSettings/TunnelSettingsV6.swift, ios/MullvadSettings/TunnelSettingsV7.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/TunnelManager/StartTunnelOperation.swift, ios/MullvadVPN/TunnelManager/StopTunnelOperation.swift, ios/MullvadVPN/TunnelManager/TunnelConfiguration.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsCellFactory.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSource.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsDataSourceDelegate.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsInfoButtonItem.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewModel.swift, ios/MullvadVPNTests/MullvadSettings/MigrationManagerTests.swift, ios/MullvadVPNTests/MullvadSettings/TunnelSettingsUpdateTests.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelSettingsStrategyTests.swift, ios/MullvadVPNUITests/ConnectivityTests.swift, ios/MullvadVPNUITests/Networking/Networking.swift, ios/MullvadVPNUITests/Pages/VPNSettingsPage.swift
Add toggles for includeAllNetwork and excludeLocalNetwork in VPN Settings in debug builds. IAN kept false by default since there are issues with app updates when the tunnel is active with IAN enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7655)
=> Add setting for ian and update excludelocalnetwork flag from ios 246

BuildInstructions.md, android/BuildInstructions.md, ios/BuildInstructions.md, scripts/setup-rust, scripts/setup-rust-post-checkout
The setup-rust helper script installs the default targets and components that each platform needs with rustup.
The setup-rust-post-checkout script is a git hook (needs to be copied to .git/hooks/post-checkout, which can be done manually or by running `setup-rust install-hook`) that detects when the rust-toolchain.toml file has changed and installs the default targets/components (and/or extra targets/components that the user has specified in the hook script).
So say we have a new desktop developer and they are setting up their environment. They could run the following:
`scripts/setup-rust desktop && scripts/setup-rust install-hook desktop` after which things Should Just Work.
- - - …
=> Add setup-rust script and git hook

ci/mullvad-browser/download-mullvad-browser.sh
There are alpha builds of the Mullvad Browser now, and we want them in our Linux repositories. It is only needed in the production environment, and it should be available on both the stable and beta repositories.
This PR is related to #7686, which would be good to have merged also, because it makes it easier to print and debug the repository content.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7687)
=> Add `mullvad-browser-alpha` to our linux repositories

CHANGELOG.md, desktop/packages/mullvad-vpn/tasks/distribution.js
This PR stops bundling `apisocks5` with the app. `apisocks5` is no longer needed since Encrypted DNS proxy has been released as stable since [2025.1](https://github.com/mullvad/mullvadvpn-app/blob/main/CHANGELOG.md#20251---2025-01-02).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7690)
=> Remove `apisocks5` binary

ios/MullvadVPN/Coordinators/Settings/DAITA/SettingsDAITAView.swift, ios/MullvadVPN/Coordinators/Settings/Views/SettingsInfoView.swift
This implements IOS-1017. The text has been revised as in the ticket. Also, `SettingsInfoView` has been extended to optionally allow the copy to be marked up in Markdown, which is used to bold the warning.
A screenshot is attached:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7638)
=> Make DAITA warning more prominent (also bold)

mullvad-version/src/lib.rs
Follow up to your PR #7600 
I saw some potential simplifications of the tests. Please tell me what you think of this version of testing stuff!
I also found a minor error in the `test_version_ordering_and_equality_dev` test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7688)
=> Simplify version parsing tests

ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift
The Settings view has separators, but sets them to the background colour. VPN Settings neglects to set them, causing them to appear in an ugly shade of grey. This PR fixes this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7700)
=> IOS-1053 Harmonise VPN Settings' cell separators with its parent Settings view

ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelPathObserver.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, ios/PacketTunnelCore/Actor/NetworkPath+NetworkReachability.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+ConnectionMonitoring.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+NetworkReachability.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+PostQuantum.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor.swift, ios/PacketTunnelCore/Actor/PacketTunnelActorCommand.swift, ios/PacketTunnelCore/Actor/PacketTunnelActorReducer.swift, ios/PacketTunnelCore/TunnelMonitor/DefaultPathObserverProtocol.swift, ios/PacketTunnelCore/TunnelMonitor/TunnelMonitor.swift, ios/PacketTunnelCore/TunnelMonitor/TunnelMonitorProtocol.swift, ios/PacketTunnelCoreTests/Mocks/DefaultPathObserverFake.swift, ios/PacketTunnelCoreTests/Mocks/TunnelMonitorStub.swift, ios/PacketTunnelCoreTests/PacketTunnelActorTests.swift
This PR does the following things :
- Modify the `PacketTunnelPathObserver` by using an `NWPathMonitor` to provide network path updates instead of relying on the deprecated `defaultPath` property from `NEProvider`
- Does not stop anymore observing network path updates when reconnecting the tunnel
- Adds idempotency to `PacketTunnelPathObserver`
- Removes `NetworkPath` hack
- Removes dead code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7699)
=> Upgrade PacketTunnelPathObserver

Cargo.lock, ios/MullvadMockData/MullvadREST/APIProxy+Stubs.swift, ios/MullvadMockData/MullvadREST/MockProxyFactory.swift, ios/MullvadREST/ApiHandlers/MullvadApiRequestFactory.swift, ios/MullvadREST/ApiHandlers/RESTAPIProxy.swift, ios/MullvadREST/ApiHandlers/RESTDefaults.swift, ios/MullvadREST/ApiHandlers/RESTProxy.swift, ios/MullvadREST/ApiHandlers/RESTProxyFactory.swift, ios/MullvadREST/ApiHandlers/RESTResponseHandler.swift, ios/MullvadREST/ApiHandlers/RESTRustNetworkOperation.swift, ios/MullvadRESTTests/RequestExecutorTests.swift, ios/MullvadRustRuntime/MullvadApiCancellable.swift, ios/MullvadRustRuntime/MullvadApiCompletion.swift, ios/MullvadRustRuntime/MullvadApiContext.swift, ios/MullvadRustRuntime/MullvadApiResponse.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AddressCacheTracker/AddressCacheTracker.swift, ios/MullvadVPN/AppDelegate.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, mullvad-api/src/lib.rs, mullvad-api/src/rest.rs, mullvad-ios/Cargo.toml, mullvad-ios/src/api_client/api.rs, mullvad-ios/src/api_client/cancellation.rs, mullvad-ios/src/api_client/completion.rs, mullvad-ios/src/api_client/mod.rs, mullvad-ios/src/api_client/response.rs, mullvad-ios/src/lib.rs
We should test out if using the mullvad-api crate is feasible. An FFI that allows for calling out to https://api.mullvad.net/app/documentation/#/paths/~1v1~1api-addrs/get 
We should then see if this works when:
- Connected over 4g
- Connected over WiFi
- Connected to a VPN when IAN is set up
- Blocked state when IAN is set up
- Proxies?
Code can be throwaway for now, but if we can make it production ready, we should.
The Swift interface should look similar to the one below:
```
protocol AddressFetching {
func fetchApiAddresses() async throws -> [MullvadEndpoint]
}
```
Said interface would probably have to be implemented by passing a continuation to Rust for when the result is fetched.
```
/// Swift side for the continuation
struct FFIContinuation {
let callback: UnsafeMutable<...>
} …
```
=> Implement an FFI to fetch API IP addresses using mullvad-api

Cargo.lock, mullvad-version/Cargo.toml, mullvad-version/src/lib.rs, test/Cargo.lock
* Implement `Serialize` and `Deserialize` for `mullvad_version::Version` (optionally). This will be used for updates (#7583)
* Use `regex-lite` instead of `regex` for `mullvad-version`. This is slower but compiles faster and is smaller than `regex`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7707)
=> Use regex-lite for mullvad-version

ios/MullvadVPNUITests/RelayTests.swift
This PR fixes the UDP over TCP port that uses capture traffic to guarantee that the correct stream is captured before asserting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7691)
=> Filter by destination port before asserting

ios/MullvadVPNUITests/RelayTests.swift
This PR adds a test for custom shadowsocks port selection.
It also refactors a bit `testWireGuardOverTCPCustomPort80` to use a common method to assert that traffic went to the expected destination.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7714)
=> Add end to end test for custom shadowsocks port selection

android/app/src/test/kotlin/net/mullvad/talpid/TalpidVpnServiceFallbackDnsTest.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/ConnectivityManagerUtil.kt, talpid-core/src/tunnel_state_machine/connected_state.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-routing/src/unix/android.rs, talpid-routing/src/unix/mod.rs, talpid-tunnel/src/tun_provider/android/mod.rs, talpid-tunnel/src/tun_provider/mod.rs, talpid-wireguard/src/connectivity/check.rs, talpid-wireguard/src/lib.rs, talpid-wireguard/src/wireguard_go/mod.rs
This PR prevent unwanted leaks when invoking establish, it minimizes calls to `VpnService.establish` and waits for android to report back on that new routes have been setup. It also clears DNS servers, to avoid reporting it incorrectly to the daemon when we know they will be invalid because of a call to `close` or `establish`
Fixes DROID-1793
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7703)
=> Avoid unnecessary calls to establish

.github/workflows/desktop-e2e.yml, test/README.md, test/scripts/build.sh, test/scripts/build/runner-image.sh, test/scripts/build/test-manager.sh, test/scripts/build/test-runner.sh, test/scripts/run/ci.sh, test/scripts/utils/download.sh, test/scripts/utils/lib.sh, test/test-by-version.sh, test/test-manager/src/main.rs
This PR changes the desktop end-to-end test workflow to build the `test-manager` and `test-runner` binaries before running the tests. The binaries are then re-used in the step running the test cases, which means that we don't spend time rebuilding stuff for every target platform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7674)
=> Re-use builds `test-manager` and `test-runner` accross target platforms

desktop/scripts/release/print-package-versions
The original issue I fixed here is that the script was not compatible with Fedora 41, which my `fedora:latest` image pointed to. It needed the newer argument format to add repositories.
I then realized the script became very noisy. Seems like Fedora 41 print more stuff to stdout/stderr. So I had to update parts of the silencing code.
I then wanted to prepare for the `mullvad-browser-alpha` package soon being added. So I list and show all packages having `mullvad-` in its name instead of just the vpn and browser.
Lastly, I pinned the container images to fixed releases, to avoid things breaking in the future because `latest` is a moving target.
- - - …
=> Update `print-package-versions` script for Linux repositories

desktop/packages/mullvad-vpn/src/renderer/components/select-location/custom-list-helpers.ts, desktop/packages/mullvad-vpn/src/renderer/components/select-location/select-location-helpers.ts
If multihop is enabled and the user has a custom list consisting of a single relay then the list will be disabled in the other view if used as Entry or Exit. However, its label will not display the `(Entry)` or `(Exit)` suffix. Additionally, the single relay in the custom list is not disabled in the other view if the user has expanded the custom list and selected the single relay inside it manually.
Improvements:
- In single relay custom lists the relay is disabled if the custom list has already been used as Entry or Exit.
- Add blocked reason suffix in label for custom lists.
Fixes: DES-1348
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7702)
=> Improve single relay custom list blocked handling and presentation

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/WireguardSettings.tsx
Fixes typo in Wireguard obfuscation info text. Note that the typo is still present in the android app and as such the old translation is still present in the `messages.pot` file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7704)
=> Fix typo in Wireguard obfuscation info text

desktop/packages/mullvad-vpn/src/main/window-controller.ts
Platform: Windows
When the taskbar is hidden the tray icon's position can't be established the pinned window is opened in the center of the screen as the fallback position. This PR changes the fallback position to be the lower right of the screen instead of the center of the screen.
Adds feature requested in discussion in #5114.
Note that even though the application can be pinned/unpinned on both Windows and Mac OS, the tray position can only be `'none'` on Windows, as on Mac OS the tray position is always statically set to `'top'` and as such will not be affected by this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7711)
=> Open pinned window on bottom right if tray position is unknown

Cargo.toml
When connecting, a firewall exception is made to the current relay for `mullvad-problem-report.exe`. The daemon expects this binary to be located in the same folder as itself, else it fails and enters the error state. As of 379e4539120dd4aebdc30d7195f9b61cee09b24b, `mullvad-problem-report` is no longer built by default (when running e.g. `cargo build`), so running the local build of the daemon from the target folder will fail unless the problem report tool is manually built prior. We should add it to the workspace default members so it automatically builds again, to improve the developer experience.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7745)
=> Add `mullvad-problem-report` to default workspace members

android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/InternetAvailableUseCase.kt
Previously we had to detect internet connectivity on the active network, if we couldn't fetch the active network we assumed it to be offline. This PR inverts that behavior so if we are not able to fetch it we assume to be connected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7739)
=> Assume connectivity if we are unable to fetch it

Cargo.lock, ios/MullvadREST/ApiHandlers/MullvadApiRequestFactory.swift, ios/MullvadREST/ApiHandlers/RESTAPIProxy.swift, ios/MullvadREST/ApiHandlers/RESTRustNetworkOperation.swift, ios/MullvadREST/RetryStrategy/RetryStrategy.swift, ios/MullvadRustRuntime/MullvadApiResponse.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadTypes/Duration+Extensions.swift, mullvad-ios/Cargo.toml, mullvad-ios/src/api_client/api.rs, mullvad-ios/src/api_client/mod.rs, mullvad-ios/src/api_client/response.rs, mullvad-ios/src/api_client/retry_strategy.rs
Adding the ability to retry api calls to Rust. It uses the same retry strategy as the previous URLSession calls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7708)
=> Urlsession retry strategy

ios/MullvadVPN.xcodeproj/project.pbxproj
This fixes release builds for the iOS app, otherwise symbols are not being resolved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7730)
=> Make REST framework depend on Rust framework

android/test/mockapi/src/main/kotlin/net/mullvad/mullvadvpn/test/mockapi/TooManyDevicesMockApiTest.kt
Wait until the application is idle to avoid skipping input events in the device list screen test that are filtered out depending on lifecycle state (`dropUnlessResumed`).
It's unclear whether this will help so the goal here is to merge it and observe future test runs due to how rare the issue has been.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7748)
=> Add `waitForIdle` to device list test

ios/MullvadMockData/MullvadREST/MockProxyFactory.swift, ios/MullvadREST/APIRequest/APIError.swift, ios/MullvadREST/APIRequest/APIRequest.swift, ios/MullvadREST/APIRequest/APIRequestProxy.swift, ios/MullvadREST/ApiHandlers/MullvadApiNetworkOperation.swift, ios/MullvadREST/ApiHandlers/MullvadApiRequestFactory.swift, ios/MullvadREST/ApiHandlers/RESTAPIProxy.swift, ios/MullvadREST/ApiHandlers/RESTProxy.swift, ios/MullvadREST/ApiHandlers/RESTProxyFactory.swift, ios/MullvadREST/ApiHandlers/RESTResponseHandler.swift, ios/MullvadREST/RetryStrategy/RetryStrategy.swift, ios/MullvadREST/Transport/APITransport.swift, ios/MullvadREST/Transport/APITransportProvider.swift, ios/MullvadRESTTests/RequestExecutorTests.swift, ios/MullvadRESTTests/RetryStrategyTests.swift, ios/MullvadRustRuntime/MullvadApiCancellable.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift, ios/MullvadVPN/TransportMonitor/PacketTunnelTransport.swift, ios/MullvadVPN/TransportMonitor/TransportMonitor.swift, ios/MullvadVPN/TunnelManager/Tunnel+Messaging.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, ios/PacketTunnelCore/IPC/AppMessageHandler.swift, ios/PacketTunnelCore/IPC/TunnelProviderMessage.swift, ios/PacketTunnelCore/URLRequestProxy/ProxyURLResponse.swift, ios/PacketTunnelCore/URLRequestProxy/URLRequestProxyProtocol.swift, ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift, ios/PacketTunnelCoreTests/Mocks/URLRequestProxyStub.swift
To use the new rust client in both processes, we can no longer send URLRequest objects around to execute them in the process we want. 
We should introduce a new packet tunnel command that will execute requests on behalf of the app process.  Then, when changing our API proxies, the proxy itself will need to decide if the request is to be executed locally or passed on to packet tunnel.
In short, the packet tunnel should handle a new message type, e.g. enum ApiRequest { Login(…), FetchApiAddresses(…), …
Requests can be proxied from the app to the packet tunnel
**Tests**
We can enable the e2e test that is able to log out when in the blocked state. If the app is already using the Rust client, then the tests should …
=> Transport api requests across app/packet tunnel boundary

ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift
Reproduce:
- Create new account
- Purchase time in welcome view
- Close app (do not click Start using the app
- Start app again
- Now the user is back on the Welcome view and needs to purchase more time to continue.
It can be solved by logging out and back in, but this is not a good first experience.
`isShownOnboarding` in AppPreferences should be set to true as soon as the user has been past the Welcome view.
~~Check if the user has time before presenting WelcomeView.~~
Acceptance criteria
Reproducing the above steps should lead the user to the main view instead of back to the welcome view.
- - - …
=> Fix users getting stuck on welcome screen

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/ButtonCellContentConfiguration.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/ButtonCellContentView.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodItem.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/List/ListAccessMethodViewController.swift, ios/MullvadVPNUITests/AccessMethodsTests.swift, ios/MullvadVPNUITests/Pages/APIAccessPage.swift, ios/MullvadVPNUITests/Pages/EditAccessMethodPage.swift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/6886)
=> Add end-to-end tests for access methods

android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/CommonFlowUtils.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt
ConnectivityManager on Android is not the easiest to work with. Providing the current state of networks turns out to be quite a challenge. This PR addresses 2 issues with the current implementation
1. Our old implementation relied on subscribing to all non-vpn network updates and then get the initial state through `ConnectivityManager.allNetworks`. However, the listener may not emit event about a network even if it is `allNetworks`. E.g in a scenario where we would turn on Airplane Mode and then start our VPN we would be stuck with a networks in our initial state that we never would get events for and thus it would be stuck in.
2. Our fetch of initial networks, did not guard against vpn networks, thus a VPN network could also get stuck in our accumulator.
The new implementation has the …
=> Fix broken connectivitylistener

ios/PacketTunnel/PostQuantum/MultiHopEphemeralPeerExchanger.swift, ios/PacketTunnelCoreTests/MultiHopEphemeralPeerExchangerTests.swift
Our multihop peer exchanger was receiving 2 private keys, first with daita paremeters, and then 2nd time around with `nil` daita parameters. This then resulted in the peer exchanging pipeline overwriting the stored DAITA parameters. This changeset fixes that and adds a test to see that the daita parameters persist.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7747)
=> Stop overwriting daita params with 

.github/workflows/desktop-e2e.yml, test/scripts/build/runner-image.sh, test/scripts/utils/lib.sh, test/test-by-version.sh
This PR fixes some regressions introduced in https://github.com/mullvad/mullvadvpn-app/pull/7674:
- Windows and macOS invoking the wrong script
- The Linux container used in some workflow steps was not always available/prepared
- Build step was gated on the wrong condition for some binaries
- `test-manager` was wrongly assumed to be in `$PATH`
- Test binaries (for linux) were always built, regardless if the tested platform was Linux or not
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7744)
=> Fix `desktop-e2e.yml` workflow

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/DaitaSettings.tsx
DAITA warning has been moved to the top of the first carousel page in the DAITA submenu. This change is due to users not noticing that DAITA increases network usage and on limited plans one might very quickly reach the plan's cap.
The DAITA warning has also been updated to make it clear that network speed, latency and the device's battery life will be affected when the setting is enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7746)
=> Move DAITA warning to first page & update text

ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeContentView.swift, ios/MullvadVPN/View controllers/CreationAccount/Welcome/WelcomeViewController.swift
The text says: Here is your account number. Save it!
But it is not possible to select it and there is no copy to clipboard button.
Add a copy to clipboard button next to the account number.
There is a copy to clipboard button and it copies the account number to the clipboard
**Tests**
None
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7755)
=> Make account number in welcome view copyable

android/app/src/main/kotlin/net/mullvad/mullvadvpn/viewmodel/ConnectViewModel.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/ContextExtensions.kt, android/lib/common/src/main/kotlin/net/mullvad/mullvadvpn/lib/common/util/VpnServiceUtils.kt, android/lib/model/src/main/kotlin/net/mullvad/mullvadvpn/lib/model/PrepareError.kt, android/lib/resource/src/main/res/values-da/strings.xml, android/lib/resource/src/main/res/values-de/strings.xml, android/lib/resource/src/main/res/values-es/strings.xml, android/lib/resource/src/main/res/values-fi/strings.xml, android/lib/resource/src/main/res/values-fr/strings.xml, android/lib/resource/src/main/res/values-it/strings.xml, android/lib/resource/src/main/res/values-ja/strings.xml, android/lib/resource/src/main/res/values-ko/strings.xml, android/lib/resource/src/main/res/values-my/strings.xml, android/lib/resource/src/main/res/values-nb/strings.xml, android/lib/resource/src/main/res/values-nl/strings.xml, android/lib/resource/src/main/res/values-pl/strings.xml, android/lib/resource/src/main/res/values-pt/strings.xml, android/lib/resource/src/main/res/values-ru/strings.xml, android/lib/resource/src/main/res/values-sv/strings.xml, android/lib/resource/src/main/res/values-th/strings.xml, android/lib/resource/src/main/res/values-tr/strings.xml, android/lib/resource/src/main/res/values-zh-rCN/strings.xml, android/lib/resource/src/main/res/values-zh-rTW/strings.xml, android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7754)
=> Improve error text for other always on apps

Cargo.lock, Cargo.toml, installer-downloader/Cargo.toml, installer-downloader/src/controller.rs, mullvad-update/Cargo.toml, mullvad-update/meta/Cargo.toml, mullvad-update/meta/src/platform.rs, mullvad-update/src/client/api.rs, mullvad-update/src/format/deserializer.rs, mullvad-update/src/format/key.rs, mullvad-update/src/format/mod.rs, mullvad-update/src/format/serializer.rs
Close DES-1802.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7767)
=> Add support for verifying version metadata with (one of) multiple keys

android/CHANGELOG.md, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/talpid/util/ConnectivityManagerUtilKtTest.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/model/Connectivity.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/ConnectivityManagerUtil.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/UnderlyingConnectivityStatusResolver.kt, mullvad-jni/src/classes.rs, talpid-core/src/connectivity_listener.rs, talpid-types/src/net/mod.rs
Exposes the availability of IPv4 and IPv6 to the daemon.
This is done by creating a dummy socket on the uderlying network.
This aligns android with other platforms.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7577)
=> Track IPv6 connectivity on Android

android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/UnderlyingConnectivityStatusResolver.kt
We are using `connect(address, port)` but we should use `connect(address)` this is because the `connect(address, port)` does not throw SocketException if the public address is not reachable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7774)
=> Use the correct connect function to detect online status

mullvad-daemon/src/migrations/mod.rs, mullvad-daemon/src/migrations/v1.rs, mullvad-daemon/src/migrations/v10.rs, mullvad-daemon/src/migrations/v1_settings.json, mullvad-daemon/src/migrations/v9.rs, mullvad-types/src/settings/mod.rs
The tunnel protocol migration (any -> wireguard) was incorrectly added to the V9 -> V10 migration, even though V10 was the current settings version, causing it to be missed for users already on V10. This PR bumps the current setting version to V11 and moves the tunnel protocol change to the new V10 -> V11 migration.
Also simply tests and improve their coverage by using the `json!` macro to test all the affected sub-setting json objects individually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7776)
=> Fix tunnel protocol setting migration

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/main/default-settings.ts, desktop/packages/mullvad-vpn/src/main/grpc-type-convertions.ts, desktop/packages/mullvad-vpn/src/renderer/app.tsx, desktop/packages/mullvad-vpn/src/renderer/components/DaitaSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/Filter.tsx, desktop/packages/mullvad-vpn/src/renderer/components/MultihopSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/OpenVpnSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/VpnSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/select-location/RelayListContext.tsx, desktop/packages/mullvad-vpn/src/renderer/components/select-location/SelectLocation.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/constraint-updater.ts, desktop/packages/mullvad-vpn/src/renderer/lib/filter-locations.ts, desktop/packages/mullvad-vpn/src/renderer/lib/relay-settings-hooks.ts, desktop/packages/mullvad-vpn/src/renderer/redux/settings/reducers.ts, desktop/packages/mullvad-vpn/src/shared/daemon-rpc-types.ts, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/types/conversions/relay_constraints.rs
Fixes: DES-1791
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7762)
=> Remove automatic tunnel option from GUI and protobuf

test/Cargo.lock
Follow up to https://github.com/mullvad/mullvadvpn-app/pull/7769, this PR bumps `ring` to a version unaffected by RUSTSEC-2025-0009. The same argument as provided in https://github.com/mullvad/mullvadvpn-app/pull/7769 for why we are currently unaffected applies to the `test` workspace as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7789)
=> Bump `ring` to `0.7.13` to mitigate `RUSTSEC-2025-0009`

.github/workflows/osv-scanner-pr.yml, .github/workflows/osv-scanner-scheduled.yml
Fixes bug introduced in https://github.com/mullvad/mullvadvpn-app/pull/7515.
When we patched the CI job to allow checking out git submodules, I accidentally copy-pasted the wrong workflow yaml file. This made the nightly scheduled scan use the PR workflow. This workflow does not work in this setting, and it always just reported green status
Moving back to consuming the workflow from google instead of our fork again, since the PR with the needed changes have been merged upstream
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7786)
=> Fix bug in nightly osv-scanner CI job

ci/linux-repository-builder/build-linux-repositories.sh, ci/mullvad-browser/download-mullvad-browser.sh
Please review per commit. We hit two issues with the update of `mullvad-browser` yesterday.
The first issue was that `download-mullvad-browser.sh` first successfully downloaded the stable browser, saw that it was different, moved it into `WORKDIR/`. Then it went on to download the alpha. But downloading the alpha failed, so the script exited. On the subsequent run, 15 minutes later, the script could not see any update to the browser, so it skipped notifying the repository service altogether. This is because the script had already copied the new stable browser release into `WORKDIR/`, so on subsequent runs, the service saw that the browser was just the same. This fix saves the move of the browsers into `WORKDIR/` until the very end, after all downloading and verification has completed. …
=> Improve browser download script

Cargo.lock, Cargo.toml, mullvad-leak-checker/Cargo.toml, mullvad-leak-checker/examples/leaker-cli.rs, test/Cargo.lock, test/Cargo.toml, test/deny.toml, test/osv-scanner.toml
Another day, yet another unmaintained crate. One of the transitive dependencies of `env_logger` and `tarpc` called `humantime` is unmaintained, which is what [RUSTSEC-2025-0014](https://rustsec.org/advisories/RUSTSEC-2025-0014) highlights.
`env_logger` dropped `humantime` in favor of `jiff` recently, so I took the opportunity to bump `env_logger` to a version which doesn't depend on `humantime`. `tarpc` still has a hard dependency on `humantime`, so there's not much we can do *right now*. I will open an issue upstream to let them know about the `RUSTSEC-2025-0014`, but in the meantime we will have to silence it. AFAICT, there is no reason to believe that `humantime` is vulnerable in any way. Also, it is limited to the `test` workspace.
- - - …
=> Start mitigating `RUSTSEC-2025-0014` - `humantime` is unmaintained

desktop/packages/mullvad-vpn/scripts/osv-scanner.toml
Just regular bump of the issues `osv-scanner` finds in our python dependencies. Bumping the ignores for six months instead of three to lower the rate at which we have to do this work. As the comment says, it only runs on developer machines on trusted input anyway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7800)
=> Bumping the ignoreUntil on our python code

wireguard-go-rs/libwg/osv-scanner.toml
Another day, yet more CVEs in go libs.
This PR renews the `ignoredUntil` date for a bunch of already-silenced-CVEs for another 3 months. It also silences new CVEs as needed. As usual, we aren't affected by these CVEs in practice, since `wireguard-go` either doesn't use the affected functions or we don't deploy to the affected CPU architectures.
- `GO-2025-3487` - Potential denial of service in `golang.org/x/crypto` (for SSH server implementations)
- `GO-2025-3447` - Timing sidechannel for P-256 on ppc64le in `crypto/internal/nistec`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7799)
=> [`osv-scanner`] Silence CVEs in `libwg`

desktop/scripts/release/4-make-release, desktop/scripts/release/publish-metadata-to-api
This PR adds a script which uploads metadata to the CDN servers via the build server. It needs to be integrated in `desktop/scripts/release/4-make-release` and might need to upload artifacts as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7736)
=> Add script which uploads metadata to CDN servers

.github/workflows/desktop-e2e.yml
This PR fixes an issue with the `desktop-e2e.yml` GHA workflow where the `test-manager` binary wouldn't be built if no tested platforms were Linux. However, it always needs to be built because it will be used in the very last workflow step where the test matrix is compiled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7801)
=> Fix regressions for non-Linux platforms in E2E desktop workflow

CHANGELOG.md, Cargo.lock, mullvad-cli/Cargo.toml, mullvad-cli/src/main.rs
This PR fixes https://github.com/mullvad/mullvadvpn-app/issues/7689. I've provided sources to the problem and suggested solution as comments in the code. Please have a look.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7802)
=> Fix `mullvad-cli` panicking if writing to a closed pipe

desktop/scripts/release/4-make-release
This PR adds a bit of text to the output of the `4-make-release` script. This addresses confusion that occured the first time it was used to publish a release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7807)
=> Improve information in 4-make-release script

android/gradle/osv-scanner.toml
This PR aims to add and push a few netty CVEs that doesn't affect our app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7809)
=> Suppress netty CVEs

ios/README.md, ios/relays-prebuild.sh
This PR changes the `relays-prebuild.sh` script to :
- Cache a relay list per configuration
- Automatically switch the `relays.json` file to the correct configuration
- Not download the relays list when the build scheme specifies a `Release` build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7797)
=> Build and cache relay list per configuration excluding Release

ios/MullvadVPN/View controllers/VPNSettings/CustomDNSDataSource.swift
With this change, the explanatory message for custom DNS in the DNS Settings will always be visible when the switch is disabled, as opposed to being hidden when the content blockers list is collapsed. 
This closes IOS-1051.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7791)
=> Decouple DNS server info from content-blockers UI expansion

desktop/osv-scanner.toml, desktop/package-lock.json, desktop/package.json
- Extend CVEs ignores which has expired
-  CVE-2025-27789 was introduced in version 7.26.9, a dependency for several packages. Since overriding the version had no effect, we’re now adding these packages as dev dependencies to lock in a fixed version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7803)
=> Extend ignores for CVEs and add babel packages as dev dependencies

desktop/packages/mullvad-vpn/src/renderer/app.tsx
When a user creates an account in the app and
then adds time to the account outside of the app
the user should then be shown the
`"/main/time-added"` route.
Whenever an account is created in the app, it's
`expiredStatus` is set immediately to `"expired"`,
which makes the app show the `"/main/expired"`
route. When time is added to the account its
`expiredStatus` changes to `"time_added"` and this
should show the `"/main/time-added"` route.
However, due to an overly broad condition
in the logic to determine when the
`"/main/expired"` route should be shown, this
caused the `"main/time-added"` route to never be
shown, as the overly broad condition effectively
prevented the logic to determine when to show the
`"/main/time-added"` route from ever being called.
This overly broad condition …
=> Fix logic keeping users on expired route even after time has been added

android/scripts/update-lockfile.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7813)
=> Only use lint when generating a new verification metadata file

desktop/packages/mullvad-vpn/src/main/load-translations.ts
Due to the vite migration the path to load resources from is different between the production and development environments. This change ensures that the same fix which is already applied to geo files and images is applied to locales.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7819)
=> Ensure locales are loaded from the correct path

mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/src/relay_selector/query.rs, mullvad-relay-selector/tests/relay_selector.rs, test/test-manager/src/tests/audits/mul_02_002.rs, test/test-manager/src/tests/daita.rs, test/test-manager/src/tests/tunnel.rs, test/test-manager/src/tests/tunnel_state.rs, test/test-manager/src/tests/ui.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7792)
=> Remove "Any" tunnel protocol from query builder

desktop/scripts/release/meta.toml, mullvad-update/meta/src/artifacts.rs, mullvad-update/meta/src/platform.rs
`meta` was also updated to append `/{version}/` to the base URL.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7823)
=> Add release meta.toml

android/app/build.gradle.kts
This will keep the debug symbols when doing debug builds.
This will increase the size of a full debug build (all architectures) APK from about 90 MB to about 400 MB.
Prod APKs are not affected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7805)
=> Keep native debug symbols for debug builds

ios/MullvadREST/Relay/MultihopDecisionFlow.swift, ios/MullvadVPNTests/MullvadREST/Relay/MultihopDecisionFlowTests.swift
This PR fixes an issue where, if Daita with smart routing is enabled and the user selects a location without a Daita relay, the app goes into a blocked state instead of attempting to find a relay server from the remaining available relays.
You can reproduce this issue on main by following these steps:
1. Set the provider to Tzulo in the Filter view and apply.
2. Select Canada → The app goes into a blocked state, even though a `Daita` relay is available in USA.
3. Select USA → The VPN successfully connects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7820)
=> Fix the issue in smart routing when selecting one to many relays

ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipFeature.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/FeatureIndicatorsViewModel.swift
The Multihop feature chip has been modified to appear if the settings enable multihop, or if the current tunnel state is multihop (i.e., if this has been enabled due to DAITA)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7815)
=> Make Multihop feature chip appear if settings or current state say so

ios/MullvadVPN.xcodeproj/project.pbxproj
This PR disables embedding wireguard-kit in most targets (except MullvadVPN)
It is required to do so in order to ship the app.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7831)
=> Do not embed wireguard-kit in sub targets

Cargo.toml, mullvad-cli/src/cmds/proxies.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/version_check.rs, mullvad-relay-selector/src/relay_selector/parsed_relays.rs, mullvad-update/meta/src/platform.rs, mullvad-version/build.rs, talpid-core/src/split_tunnel/macos/default.rs, talpid-core/src/split_tunnel/macos/process.rs, talpid-core/src/split_tunnel/windows/mod.rs, talpid-dbus/src/systemd_resolved.rs, talpid-openvpn/src/wintun.rs, talpid-wireguard/src/wireguard_kernel/wg_message.rs, test/Cargo.toml, test/test-manager/src/tests/helpers.rs, test/test-manager/src/vm/network/macos.rs
I stumbled on this lint from the pedantic series of clippy lints. I found it to be quite valid thing to lint about. Sometimes it can just be seen as a stylistic choice between `to_owned` or `clone` maybe. But what the lint wants to communicate is that `to_owned` should be used when you have a `&str` and want a `String`. While if you have a `&String` and need a `String` you should clone it. Being more explicit with the intentions.
I don't think it hurts to enable. Will make the code slightly more consistent. I saw no "false positives" where this just caused annoying noise. But tell me what you think.
There are also two "trophy cases" here. You can see in one commit I'm able to completely get rid of cloning in two places. Not that it's going to affect our performance in any way at all, but …
=> Forbid `implicit_clone` clippy lint

desktop/packages/mullvad-vpn/src/renderer/components/ExternalLink.tsx, desktop/packages/mullvad-vpn/src/renderer/components/InternalLink.tsx, desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/ButtonText.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/filter-chip/components/FilterChipText.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/navigation-header/components/NavigationHeaderTitle.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/components/ProgressPercent.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/components/ProgressText.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/BodySmall.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/BodySmallSemiBold.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/FootnoteMini.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/Label.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/LabelTiny.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/Link.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/Text.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/TitleBig.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/TitleLarge.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/typography/TitleMedium.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/new-version.ts, desktop/packages/mullvad-vpn/src/renderer/lib/types/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/types/polymorphic-props.ts, desktop/packages/mullvad-vpn/src/shared/notifications/notification.ts
Moves app specific logic from `Link` component to two separate components, `ExternalLink` and `InternalLink`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7784)
=> Add support for external links in link component

CHANGELOG.md, talpid-openvpn/src/wintun.rs, talpid-tunnel/src/windows.rs, talpid-wireguard/src/wireguard_go/mod.rs, talpid-wireguard/src/wireguard_nt/mod.rs
Previously, this caused an error if an MTU below 1280 was set.
Fix DES-1870.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7832)
=> Only set IPv6 MTU if IPv6 is enabled for wireguard-nt

CHANGELOG.md, desktop/packages/mullvad-vpn/tasks/distribution.js
Fix DES-1780
Fix https://github.com/mullvad/mullvadvpn-app/issues/7735
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7845)
=> Fix native module being unpacked to temp dir

mullvad-update/src/format/key.rs
`ThreadRng` uses chacha12, seeded by `OsRng`. This might be slightly better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7851)
=> Use thread rng to generate ed25519 secret

android/CHANGELOG.md, android/src/main/play/release-notes/en-US/default.txt
This PR aims to update the changelog for `android/2025.1`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7853)
=> Update changelog for `android/2025.1`

ci/buildserver-upload.sh
Some `.sha256` include extra whitespace for whatever reason. This PR trims surrounding whitespace for all filenames.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7857)
=> Trim surrounding whitespace in checksum files in `buildserver-upload.sh`

mullvad-daemon/src/tunnel.rs, mullvad-relay-selector/src/error.rs, mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/tests/relay_selector.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7849)
=> Refactor android ipv6 fix

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/ConnectScreen.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7855)
=> Add action to go to VPN settings from snackbar

installer-downloader/src/temp.rs
The previous comment implied that it fixed ("mitigated") the underlying issue.
Fix DES-1914.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7858)
=> Update misleading documentation regarding random temp dir

desktop/packages/mullvad-vpn/src/renderer/lib/components/dot/Dot.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/dot/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7848)
=> Add Dot component

desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/ListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/ListItemContext.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemContent.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemFooter.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemGroup.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemItem.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemLabel.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemText.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/ListItemTrigger.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/components/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/list-item/levels.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7844)
=> Add ListItem component

CHANGELOG.md
Adds an entry in the changelog with a mention of the bugfix for new users stuck after payment.
This fix was merged in this PR:  https://github.com/mullvad/mullvadvpn-app/pull/7796
Checking Linear I also found the following issue which will be resolved by the same fix. Linking the Linear issue and related Github issue below:
Fixes: DES-1347
Fixes: https://github.com/mullvad/mullvadvpn-app/issues/7028
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7868)
=> Update changelog with mention of bugfix for new users stuck after payment

desktop/packages/mullvad-vpn/src/main/gui-settings.ts, desktop/packages/mullvad-vpn/src/main/settings.ts, desktop/packages/mullvad-vpn/src/renderer/app.tsx, desktop/packages/mullvad-vpn/src/renderer/redux/settings/reducers.ts, desktop/packages/mullvad-vpn/src/shared/gui-settings-state.ts, desktop/packages/mullvad-vpn/src/shared/ipc-schema.ts, desktop/packages/mullvad-vpn/test/e2e/setup/main.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7861)
=> Add dismiss update functionality

Cargo.lock, desktop/packages/windows-utils/Cargo.toml, desktop/packages/windows-utils/src/index.cts, desktop/packages/windows-utils/windows-utils-rs/fs.rs, desktop/packages/windows-utils/windows-utils-rs/lib.rs, talpid-windows/Cargo.toml, talpid-windows/src/fs.rs, talpid-windows/src/lib.rs
The actual function was added to `talpid-windows` since the CLI will probably want to use this.
Fix DES-1889.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7846)
=> Add helper function to check named pipe ownership to `windows-utils` module

Cargo.lock, mullvad-api/Cargo.toml, mullvad-api/src/lib.rs, mullvad-api/src/rest.rs, mullvad-api/src/version.rs, mullvad-daemon/src/version_check.rs, mullvad-ios/Cargo.toml, test/Cargo.lock
This adds a method for fetching version info from the new endpoint to `AppVersionProxy`. This isn't actually used anywhere yet, so it should be fine to merge this into `main`.
Fix DES-1677
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7874)
=> Add function for fetching version info from new endpoint to `mullvad-api`

mullvad-update/meta/src/main.rs, mullvad-update/src/format/key.rs
The only way to retrieve the pubkey currently is by signing something. The PR prints it during generation for convenience.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7880)
=> Print public key when running 'meta generate-key'

android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/extensions/LazyListExtensions.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/CustomListLocationsScreen.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/compose/screen/location/SelectLocationList.kt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7870)
=> Scroll to first checked custom location on open

desktop/packages/mullvad-vpn/src/main/version.ts, desktop/packages/mullvad-vpn/src/renderer/app.tsx, desktop/packages/mullvad-vpn/src/renderer/redux/version/reducers.ts, desktop/packages/mullvad-vpn/src/shared/daemon-rpc-types.ts, desktop/packages/mullvad-vpn/src/shared/notifications/unsupported-version.ts, desktop/packages/mullvad-vpn/src/shared/notifications/update-available.ts, desktop/packages/mullvad-vpn/test/unit/notification-evaluation.spec.ts
When the `AppVersionInfo.suggestedUpgrade` property is updated, due to the changes in [DES-1811](https://linear.app/mullvad/issue/DES-1811/create-specification-for-communication-between-electron-and-the-daemon) we need to make some changes in the code to handle the new format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7881)
=> Implement changes to suggestedUpgrade in Electron

CHANGELOG.md
:pick: The user facing option is/was called "Automatic". This change is made to prevent confusion in the next beta release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7888)
=> Use the user facing term "Automatic" instead of "Any" in `CHANGELOG.md`

installer-downloader/src/temp.rs
Further clarify why the potential same-user TOCTOU attack on the installer downloader on macOS is not in scope for our threat model.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7889)
=> Clarify documentation about TOCTOU attack on installer downloader

CHANGELOG.md, android/CHANGELOG.md, android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/talpid/util/ConnectivityManagerUtilKtTest.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/model/Connectivity.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/model/IpAvailability.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/ConnectivityManagerUtil.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/UnderlyingConnectivityStatusResolver.kt, mullvad-daemon/src/tunnel.rs, mullvad-jni/src/classes.rs, mullvad-relay-selector/src/error.rs, mullvad-relay-selector/src/lib.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/tests/relay_selector.rs, talpid-core/src/connectivity_listener.rs, talpid-core/src/offline/linux.rs, talpid-core/src/offline/macos.rs, talpid-core/src/offline/windows.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/mod.rs, talpid-types/src/net/mod.rs
This PR tries to do two things:
1. Throw an error if the user device IP setting does not align with the available ip version on the network
2. Prevent the app from trying to connect using an unavailable ip version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7777)
=> Avoid using an unavailable ip version to connect to a relay

desktop/packages/mullvad-vpn/src/renderer/lib/components/animate/Animate.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/animate/components/AnimatePresentVertical.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/animate/components/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/animate/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7854)
=> Add Animate component

android/BuildInstructions.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7901)
=> Add instructions for release APK reproducibiltiy

CHANGELOG.md
This PR backports the changelog from the `2025.5` release to `main` :tada:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7905)
=> Add `2025.5` changelog entry

.github/workflows/osv-scanner-scheduled.yml
I'm disabling scanning of submodules for osv-scanner, since it is currently too noisy. Our submodules get false positives (unrelated golang CVEs) all the time. Getting rid of them is a pain since we would need to fix/ignore them in the submodule and then bump the submodule. This creates a lot of churn just to silence this tool.
This is not optimal since there *can* be real vulnerabilities, and we would miss them easier this way. But this is not worse than where we were a couple of months back, before we even had the submodule scanning at least.
I left the submodule scanning on in the PR version of this CI job. There it's not as problematic. If a PR does something to a submodule so that a new CVE is introduced, we want to know.
- - - …
=> Stop checking out submodules when running scheduled osv-scanner CI

desktop/packages/mullvad-vpn/src/renderer/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeDownloadProgressValue/constants.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeDownloadProgressValue/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeDownloadProgressValue/hooks/useGetValueDownloadProgress.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeDownloadProgressValue/hooks/useGetValueError.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeDownloadProgressValue/index.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeDownloadProgressValue/useAppUpgradeDownloadProgressValue.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeEventType.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useHasAppUpgradeError.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useHasAppUpgradeEvent.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useHasAppUpgradeVerifiedInstallerPath.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useIsAppUpgradeInProgress.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useShouldAppUpgradeInstallManually.ts, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/hooks/useAppUpgradeError.ts, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/hooks/useAppUpgradeEvent.ts, desktop/packages/mullvad-vpn/src/renderer/redux/hooks/index.ts
- Adds reusable hooks for common AppUpgrade logic.
- Also adds missing selectors to `app-upgrade` Redux namespace.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7915)
=> Add reusable AppUpgrade hooks

mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs, mullvad-management-interface/src/types/conversions/version.rs
This PR implements 3 new functions on the `ManagementService` trait: `app_upgrade`, `app_upgrade_abort` and `app_upgrade_events_listen`. This allow any Mullvad client to start a new version upgrade, abort an ongoing upgrade and subscribe to upgrade events.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7916)
=> Implement new `ManagementService`

desktop/package-lock.json, desktop/package.json
A CVE exists in the 6.2.0 version of vite. We have already upgraded the dependency on vite to 6.2.3 where this CVE has been fixed.
However, npm resolves the @vitejs/plugin-react package's dependency on vite to 6.2.0 even after we have upgraded it for some reason. To ensure the old 6.2.0 version is not resolved we add an override to 6.2.3 until we can bump the @vitejs/plugin-react package.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7914)
=> Add npm override to fix vite CVE

ci/ios/test-router/flake.lock, ci/ios/test-router/flake.nix, ci/ios/test-router/raas/Cargo.lock, ci/ios/test-router/raas/Cargo.toml, ci/ios/test-router/raas/src/block_list/mod.rs, ci/ios/test-router/raas/src/block_list/rule.rs, ci/ios/test-router/raas/src/capture/mod.rs, ci/ios/test-router/raas/src/capture/parse.rs, ci/ios/test-router/raas/src/web/routes.rs, ci/ios/test-router/router-config.nix
Fixes DROID-1566
Adds a new boolean field to the the `rule` endpoint called `block_wireguard`. If this is true we drop only wireguard traffic. Also adds the ability to block IP networks and not just single IP addresses, e.g. `192.168.0.0/16`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7850)
=> Add ability to block IP networks and wireguard to test router

desktop/package-lock.json, desktop/package.json, desktop/packages/mullvad-vpn/package.json
Patches the following vulnerability: https://osv.dev/GHSA-4r4m-qw57-chr8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7932)
=> Upgrade vite to 6.2.4

mullvad-version/src/lib.rs
This verifies that `dist-assets/desktop-product-version.txt` contains a valid version by adding a little unit test.
Side-note: Maybe we ought to parse the string instead.
Fix DES-1503
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7918)
=> Validate product version in mullvad-version

talpid-core/src/tunnel_state_machine/mod.rs
By generating 2 PQ keys on start we slow the start up of the android app with out about 20%. On android we don't have the daemon running continously and by default PQ nor Multihop is enabled, thus all our users doing a cold start of the app will be 20% slower. 
Ideally the solution would be to conditionally & dynamically change the buffer size depending on what features are active, e.g PQ gives buffer of 1, PQ and Multihop gives a buffer of 2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7929)
=> Disable pre-generation of PQ keys on Android

CHANGELOG.md
This PR simply notes the added warnings for the upcoming sunsetting of OpenVPN in the changelog
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7935)
=> Add OpenVPN warnings to changelog

desktop/packages/mullvad-vpn/src/main/daemon-rpc.ts, desktop/packages/mullvad-vpn/src/main/index.ts
The Electron app should verify that the socket/named pipe which is used to communicate with the daemon is owned by the correct user before it starts communicating with the daemon. This PR verifies that ownership or throws an error. See issue on Linear for details about ownership check failing.
Fixes: DES-1881
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7930)
=> Verify ownership of socket/named pipe before communicating with daemon

wireguard-go-rs/libwg/osv-scanner.toml
This PR silences a CVE filed against `golang.org/x/net/http/httpproxy` and `golang.org/x/net/proxy`  that was detected by `osv-scanner`: https://osv.dev/vulnerability/GO-2025-3503.
Wireguard-go does not use any of these libraries, so it is safe to simply ignore these CVE warnings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7931)
=> Silence `GO-2025-3503` in `libwg/wireguard-go`

mullvad-daemon/src/version/downloader.rs, mullvad-daemon/src/version/mod.rs
Linux and Android does not have the in-app upgrade feature, thus exposing the errors related to that feature does not make any sense.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7939)
=> Hide in-app upgrade errors on Linux and Android

.github/workflows/verify-locked-down-signatures.yml
This file is extremely important to the installer downloader (and soon in app upgrades). When adding these keys we put strict codeowners permissions on it. But we should also make sure the file is always signed when changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7942)
=> Mark trusted-metadata-signing-pubkeys as needing signatures to be edited

mullvad-daemon/build.rs
This PR fixes an issue in the build script for `mullvad-daemon` - check for the actual target OS instead of the target for the build script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7944)
=> Fix build target for `mullvad-daemon` build script

installer-downloader/src/controller.rs, mullvad-api/src/version.rs, mullvad-update/meta/src/platform.rs, mullvad-update/src/client/api.rs, mullvad-update/src/client/snapshots/mullvad_update__client__api__test__http_version_provider.snap, mullvad-update/src/defaults.rs, mullvad-update/src/format/deserializer.rs, mullvad-update/src/keys.rs, mullvad-update/src/lib.rs
This hides certificate pinning and pubkeys (mostly) in `mullvad-update`. Details are still somewhat duplicated in `mullvad-api`, since it has its own HTTP client.
Fix DES-1944.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7940)
=> Add public signing keys for metadata to `mullvad-update`

mullvad-cli/src/cmds/debug.rs, mullvad-daemon/src/lib.rs, mullvad-daemon/src/management_interface.rs, mullvad-management-interface/proto/management_interface.proto, mullvad-management-interface/src/client.rs, mullvad-types/src/relay_list.rs
Implement new debug commands: `relay disable` and `relay enable`
Add two new `mullvad debug` subcommands:
- `mullvad debug relay enable <country|city|hostname|openvpn|wireguard>`
- `mullvad debug relay disable <country|city|hostname|openvpn|wireguard>`
These commands are used to update the state of relays the current relay list. This is useful to mock relays going offline or coming online from an offline state.
These new debug commands were conceived during the development of the feature for adding warnings for the upcoming OpenVPN deprecation, as there wasn't a convenient way of mocking this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7817)
=> Add `mullvad debug relay enable|disable` commands

Cargo.lock, Cargo.toml, mullvad-masque-proxy/Cargo.toml, mullvad-masque-proxy/examples/client.rs, mullvad-masque-proxy/examples/server.rs, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/fragment.rs, mullvad-masque-proxy/src/lib.rs, mullvad-masque-proxy/src/server/mod.rs
This is a small PoC implementation of a [masque](https://datatracker.ietf.org/doc/rfc9298/). We could use a masque proxy almost as is, if it wasn't for the exorbitant header sizes which interfere with multihop. For the larger packet sizes for multihop, which then enables DAITA, we are looking to extend the protocol to support fragmented packets. 
We are looking to use masque to obfuscate our traffic to make it appear as though it was regular QUIC traffic.  I'm laying this here so that we have a clear path towards implementing a QUIC Masque proxy for ourselves in the upcoming quarter - we don't need to merge this code as is.
In terms of libraries, I've had to extend `h3` to make use of it, namely, exposing QUIC datagrams to client connections. Other than that, we should be able to use …
=> PoC for a masque proxy

mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/server/mod.rs
This fixes the following issues:
* The server never fragments due to not checking packet length correctly.
* The client reads the context ID twice (and so skips the first bytes when receiving fragments).
Fix DES-1986
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7970)
=> Fix incorrect fragmentation/reassembly logic in masque proxy

desktop/package-lock.json, desktop/package.json, desktop/packages/mullvad-vpn/package.json
Addresses this CVE: https://osv.dev/GHSA-xcj6-pq6g-qj4x
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7974)
=> Upgrade vite to 6.2.5 to fix CVE

desktop/scripts/release/4-make-release, desktop/scripts/release/5-update-and-publish-metadata, desktop/scripts/release/download-release-artifacts, desktop/scripts/release/release-config.sh
I think this PR is easiest reviewed one commit at a time.
1. Removes the check for the `gh` command in a script that (no longer?) uses it.
2. The `ARTIFACT_DIR` variable was defined in three scripts and they depended on having the same value, but this was not obvious at all. I moved the definition into a config file that we source, and then use that single definition.
3. Fix bug in `5-update-and-publish-metadata` where the rollout percentage was passed on an invalid format to `mullvad-release`
4. Use `xclip -sensitive` to read the ed25519 signing key from the clipboard, instead of expecting the person running the script from manually pasting it. Removes a manual step and helps avoid accidentally pasting the key in the wrong place.
- - - …
=> Small cleanups in desktop release scripts

ci/ios/test-router/raas/Cargo.lock
This PR is a follow-up to https://github.com/mullvad/mullvadvpn-app/pull/7971 - it addresses the same CVE in the `raas` workspace!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7980)
=> Bump `tokio` to `1.44.2`

desktop/packages/mullvad-vpn/src/renderer/components/ProblemReport.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-info/components/update-available-list-item/UpdateAvailableListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-info/components/update-available-list-item/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/app-info/components/update-available-list-item/hooks/useHandleClick.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-info/components/update-available-list-item/hooks/useIsLinux.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/report-problem-button/ReportProblemButton.tsx, desktop/packages/mullvad-vpn/src/renderer/history/hooks/usePushProblemReport.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useIsPlatformLinux.ts, desktop/packages/mullvad-vpn/src/renderer/lib/history.tsx, desktop/packages/mullvad-vpn/src/shared/ipc-types.ts
- Makes the modal optional so it can be disabled when navigating to it from the AppUpgrade view.
- Conditionally sets the "Upgrade app" button to navigate to an external URL or the AppUpgrade route, depending on platform.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7963)
=> Update ProblemReport view to integrate better with in app upgrade feature

CHANGELOG.md, dist-assets/linux/apparmor_mullvad
The executable path must be quoted instead of using an escape character.
See man apparmor.d(5), under "Unquoted Profile Name" - "Rules with embedded spaces or tabs must be quoted."
Before this commit, running `aa-enforce /opt/Mullvad\ VPN/mullvad-gui` (as root) returned an error:
```
ERROR: Syntax Error: Unknown line found in file /etc/apparmor.d/mullvad line 5:
profile mullvad /opt/Mullvad\ VPN/mullvad-gui { userns,
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7876)
=> Fix syntax error in Apparmor profile

ios/MullvadVPN/View controllers/Account/AccountContentView.swift, ios/MullvadVPN/View controllers/Account/AccountInteractor.swift, ios/MullvadVPN/View controllers/Account/AccountViewController.swift, ios/MullvadVPN/View controllers/Account/PaymentAlertPresenter.swift, ios/MullvadVPN/View controllers/Account/PaymentState.swift
Services needs a button to test refunds in StoreKit 2. This is a debug only button that refunds the last made purchase.
**Note: This PR introduces code that is only for testing.**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7978)
=> Create button for StoreKit 2 refunds

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipFeature.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionViewComponentPreview.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/FeatureIndicatorsViewModel.swift, ios/MullvadVPN/View controllers/Tunnel/TunnelViewController.swift, ios/MullvadVPNTests/MullvadVPN/PacketTunnelCore/PacketTunnelActorReducerTests.swift, ios/PacketTunnelCore/Actor/ObservedState.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor.swift, ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift, ios/PacketTunnelCore/Actor/State.swift, ios/PacketTunnelCoreTests/Mocks/ProtocolObfuscationStub.swift, ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift
This captures the chosen obfuscation method and stores it in `ObservedState`, and uses this for displaying the feature chip. Currently it just reads "Obfuscation" if it is enabled, though the logic exists to display the method used and whether it was automatically chosen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7984)
=> Display actual obfuscation method in feature chips

mullvad-daemon/src/macos_launch_daemon.rs, mullvad-daemon/src/migrations/v10.rs, mullvad-daemon/src/relay_list/mod.rs, talpid-core/src/split_tunnel/macos/tun.rs, talpid-routing/src/unix/mod.rs
This makes `cargo check` succeed on Rust edition 2024. There's probably lints that fail, so this is not intended to be complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7958)
=> Fix compilation errors for 2024 edition on macOS

mullvad-masque-proxy/examples/masque-client.rs, mullvad-masque-proxy/examples/masque-server.rs, mullvad-masque-proxy/src/client/mod.rs
The offsets are unchanged for now (they're wrong anyway).
Fix DES-1959
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7992)
=> Set max UDP payload size in masque client

mullvad-masque-proxy/examples/masque-client.rs, mullvad-masque-proxy/examples/masque-server.rs, mullvad-masque-proxy/src/client/mod.rs, mullvad-masque-proxy/src/fragment.rs, mullvad-masque-proxy/src/lib.rs, mullvad-masque-proxy/src/server/mod.rs, mullvad-masque-proxy/tests/proxy.rs
Fix all relative size calculations, including taking into account IPv4 vs. IPv6. This currently bases the fragment size on the maximum datagram size for the QUIC endpoint, and uses a constant QUIC header overhead of 41 bytes if that's not available.
Fix DES-1967
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7993)
=> Fix maximum packet size calculations

android/lib/resource/src/main/res/values/strings.xml, desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/main/grpc-type-convertions.ts, desktop/packages/mullvad-vpn/src/shared/daemon-rpc-types.ts, desktop/packages/mullvad-vpn/src/shared/notifications/error.ts
This adds support for the same error message to the desktop frontend as was introduced on android in the following PR:
https://github.com/mullvad/mullvadvpn-app/pull/7976
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7987)
=> Show ip unavailble error message on desktop

test/Cargo.lock
This PR bumps `crossbeam-channel` from `0.5.12` to `0.5.15` in the test workspace to fix a memory corruption error present in `crossbeam-channel [0.5.12, 0.5.15)` : https://osv.dev/vulnerability/RUSTSEC-2025-0024
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8007)
=> Bump `crossbeam-channel` to `0.5.15` to mitigate RUSTSEC-2025-0024

wireguard-go-rs/libwg/osv-scanner.toml
This PR silences [GO-2025-3563](https://osv.dev/vulnerability/GO-2025-3563) which `osv-scanner` flagged this morning. Neither `libwg` nor `wireguard-go` uses the affected library, so we may safely ignore this CVE for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7985)
=> Silence CVE `GO-2025-3563` in `libwg`

.github/workflows/desktop-e2e.yml
This PR adds a Fedora 42 beta VM to the desktop end-to-end test CI workflow. This means that it will be automatically tested every night and that we can manually trigger tests with a Fedora 42 VM.
Here is a run with the new VM: https://github.com/mullvad/mullvadvpn-app/actions/runs/14400552518
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8010)
=> Add Fedora 42 beta VM to end-to-end tests

ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipFeature.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/FeatureIndicatorsViewModel.swift
This makes the DAITA and Quantum Resistance feature indicators appear iff the current `TunnelState` is connected with the feature active, rather than the settings being configured to enable the feature. This should cover all the feature indicators other than DNS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8001)
=> Make DAITA/Quantum feature indicators show actual tunnel state

ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift, ios/MullvadRESTTests/ServerRelayTests.swift, ios/MullvadVPN.xcodeproj/project.pbxproj
Shadowsocks obfuscation was in some cases not using the ip provided by an ip override. This PR fixes that bug.
To test add an ip override like this
```
{
"relay_overrides": [
{
"hostname": "se-got-wg-001",
"ipv4_addr_in": "127.0.0.1",
"ipv6_addr_in": "::"
}
]
}
and try connecting to that relay. It should now use the provided ip for shadowsocks both in automatic and user selected mode with both automatic and user defined port.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8027)
=> Fix shadowsocks not using ip override

desktop/osv-scanner.toml
Extend ignore for [CVE-2024-21528](https://osv.dev/vulnerability/GHSA-g974-hxvm-x689) as there is no fix yet and we don't send untrusted input to the first argument of addTranslations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8050)
=> Extend ignore for CVE-2024-21528

wireguard-go-rs/libwg/osv-scanner.toml
This PR silences [GO-2025-3595](https://osv.dev/vulnerability/GO-2025-3595) in `libwg/osv-scanner.toml`. Neither `libwg` nor `wireguard-go` uses the affected parse/tokenize functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8049)
=> Silence `GO-2025-3595` in libwg

ios/README.md
Correct the wording at ios/README.md
- Prerequisitives => Prerequisites
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7956)
=> Correct wording for `Prerequisites` at iOS Readme.md

ci/ios/buildserver-build-ios.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/7864)
=> Update build script to work with submodules

android/app/src/main/kotlin/net/mullvad/mullvadvpn/repository/CustomListsRepository.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/usecase/customlists/CustomListActionUseCase.kt, android/app/src/test/kotlin/net/mullvad/mullvadvpn/usecase/CustomListActionUseCaseTest.kt
Current implementation would always hold of 5 seconds if we are trying to get a custom list that doesn't exist.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8046)
=> Fix incorrect getCustomListById

desktop/packages/mullvad-vpn/src/renderer/app.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-info/components/update-available-list-item/UpdateAvailableListItem.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/AppUpgradeView.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/download-progress/DownloadProgress.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/download-progress/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/download-progress/hooks/useDisabled.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/download-progress/hooks/useMessage/useMessage.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/upgrade-label/components/installer-ready/InstallerReady.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/upgrade-label/components/starting-installer/StartingInstaller.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/upgrade-label/components/upgrade-error/UpgradeError.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/upgrade-label/components/verifying-installer/VerifyingInstaller.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/hooks/useShowDownloadProgress.ts, desktop/packages/mullvad-vpn/src/renderer/hooks/useAppUpgradeDownloadProgressValue/useAppUpgradeDownloadProgressValue.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/progress/Progress.tsx, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/actions.ts, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/hooks/useAppUpgradeLastProgress.ts, desktop/packages/mullvad-vpn/src/renderer/redux/app-upgrade/reducers.ts
- Makes progress bar visible most steps of app upgrade flow after initialization
- Animates label and progress bar separately to make animations stutter less
- Removes disable from app upgrade list item when connection is blocked
This also adds a state in app upgrades redux state which currently keeps track of the latest progress percentage number. This is used to prevent some cases where the progress could be set to 0 when toggling the connection on and off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8037)
=> Improvements to app upgrade implementation

.github/workflows/desktop-e2e.yml
This PR adds Ubuntu 25.04 to the arsenal of VMs used in our desktop E2E tests.
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/14517104044
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8051)
=> Add Ubuntu 25.04 VM to end-to-end tests

desktop/packages/mullvad-vpn/src/renderer/components/ProblemReport.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/report-problem-button/ReportProblemButton.tsx, desktop/packages/mullvad-vpn/src/shared/ipc-types.ts
Refactor location state to use objects instead of a string array.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8058)
=> Refactor location state options to use objects

Cargo.lock, test/Cargo.lock
Bump quinn-proto to 0.11.11. This fixes the panic seen in the version we currently use.
~See the comment in `Cargo.toml`. Temporarily switch to using the `main` git branch for `quinn`, as the last release occasionally panics when using `mullvad-masque-proxy`.~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8011)
=> Fix quinn panic

desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/no-open-vpn-server-available.ts, desktop/packages/mullvad-vpn/src/shared/constants/urls.ts
Ensure OpenVPN ending notification only displays for associated relays. The notification should only be displayed if the user has selected a bridge or openvpn relay.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8052)
=> Fix issue with "No OpenVPN servers" warning being displayed erroneously

ios/MullvadMockData/MullvadREST/DevicesProxy+Stubs.swift, ios/MullvadREST/ApiHandlers/RESTDevicesProxy.swift, ios/MullvadREST/ApiHandlers/RESTProxyFactory.swift, ios/MullvadREST/MullvadAPI/APIHandlers/MullvadDeviceProxy.swift, ios/MullvadREST/MullvadAPI/APIRequest/APIRequest.swift, ios/MullvadREST/MullvadAPI/MullvadApiRequestFactory.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadTypes/RESTTypes.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/TunnelManager/SetAccountOperation.swift, mullvad-api/src/device.rs, mullvad-ios/src/api_client/device.rs, mullvad-ios/src/api_client/mod.rs, mullvad-ios/src/api_client/problem_report.rs
This PR introduces support for using mullvad-api when device APIs are revoked. Since mullvad-api is not yet fully implemented, For testing purposes, you can simply replace the relevant snippet in ProxyFactory for `createDevicesProxy()`.
```
MullvadDeviceProxy(
transportProvider: configuration.apiTransportProvider,
dispatchQueue: DispatchQueue(label: "MullvadDeviceProxy.dispatchQueue"),
responseDecoder: Coding.makeJSONDecoder()
)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8048)
=> Implement DeviceProxy to use Mullvad API

mullvad-daemon/src/version/downloader.rs, mullvad-daemon/src/version/router.rs
This simply wipes the directory every time the daemon starts.
Fix DES-1981
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8069)
=> Clean up downloads from in-app upgrades

ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift
This PR adds another conditional compilation check that was forgotten and killed release builds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8082)
=> Add another forgotten conditional compilation check

BuildInstructions.md, scripts/setup-rust, scripts/setup-rust-post-checkout
This PR aims to properly support all desktop platforms in the `setup-rust` helper script and hook.
Targets to try installing before we merge:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8088)
=> Support windows, linux and macos in setup-rust

desktop/package-lock.json, desktop/package.json, desktop/packages/mullvad-vpn/package.json
This fixes `CVE-2025-46565`: https://osv.dev/vulnerability/GHSA-859w-5945-r5v3
Note: This only seems to potentially affect the development server only, so it doesn't have any implications for end users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8105)
=> Update vite to 6.2.7

.github/workflows/android-reproducible-builds.yml, android/snapshot/manifest-permissions-oss.txt
This PR aims to add a CI job to catch unwanted manifest permissions changes introduced by dependencies. It does this by extracting built release artifacts.
It was added to the reproducible/F-Droid workflow since that's the only place where we build release artifacts at the time of adding this job. However, it should be moved to a more suitable place once we expand and refactor our CI setup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8111)
=> Add CI permission check

desktop/packages/mullvad-vpn/vite.config.ts
This PR adds forwarding of command line arguments to the vite config to enable passing command line arguments to the Electron app when running `npm run develop`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8113)
=> Add forwarding of command line args in vite

desktop/packages/mullvad-vpn/package.json, desktop/packages/mullvad-vpn/tasks/build.js, desktop/packages/mullvad-vpn/tasks/utils.js
Adds type checking before building `production` and `test` builds. `standalone` builds were already type checked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8114)
=> Re introduce type checking before builds

Cargo.lock, installer-downloader/CHANGELOG.md, installer-downloader/Cargo.toml
This PR bumps installer downloader to 0.3.0 and updates the changelog with the release section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8127)
=> Bump installer downloader to 0.3.0

ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, mullvad-ios/src/api_client/account.rs, mullvad-ios/src/api_client/api.rs, mullvad-ios/src/api_client/device.rs, mullvad-ios/src/api_client/problem_report.rs, mullvad-ios/src/api_client/storekit.rs
Following the pinky promise we made, this PR updates all the documentation mentioning `SwiftRetryStrategy`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8140)
=> Add documentation for instances of SwiftRetryStrategy

ios/MullvadRustRuntime/EphemeralPeerReceiver.swift, ios/MullvadRustRuntime/MullvadApiCompletion.swift
Now demangled symbols exported to non-Swift code will use the C calling convention, rather than still using the Swift one. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8090)
=> Replace @_silgen_name with _cdecl

ios/MullvadVPN/View controllers/SelectLocation/LocationSectionHeaderFooterView.swift
This fix aligns the '…' in the locations Custom Lists header with the disclosure chevrons below it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8141)
=> Adjust trailing edge inset of location section header/footer view

test/test-manager/src/tests/relay_ip_overrides.rs
There were two versions of `constrain_to_relay`, and then one used by the test was outdated after the addition of relay white-listing for e2e tests.
The function did not consider the mullvad clients current relay settings, i.e. the custom list that the test is initiated with. It could choose any OpenVPN relay in Sweden, even if it wasn't pickable.
Test run:
~https://github.com/mullvad/mullvadvpn-app/actions/runs/14910156898/job/41883686408~
~https://github.com/mullvad/mullvadvpn-app/actions/runs/14924636786/job/41927213348~
https://github.com/mullvad/mullvadvpn-app/actions/runs/14929831581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8143)
=> Fix `test_openvpn_ip_override`

installer-downloader/src/controller.rs
This was logged unconditionally instead of only in the error case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8148)
=> Fix incorrect error log in installer-downloader

ios/MullvadVPN/View controllers/SelectLocation/LocationCell.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationDataSource.swift, ios/MullvadVPN/View controllers/SelectLocation/LocationViewControllerWrapper.swift
This PR improves accessibility support for the Select Location cell. VoiceOver users can now:
- Double-tap the cell to toggle its expanded/collapsed state, if the location has child items.
- Use the custom "Select" action via swipe up/down to select the current location directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8145)
=> Add custom action at select location for accessibility

ios/CHANGELOG.md, ios/MullvadVPN/SimulatorTunnelProvider/SimulatorTunnelProviderHost.swift, ios/MullvadVPN/TunnelManager/Tunnel+Messaging.swift, ios/MullvadVPN/TunnelManager/TunnelManager.swift, ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPNTests/MullvadSettings/APIAccessMethodsTests.swift, ios/MullvadVPNTests/MullvadSettings/IPOverrideRepositoryTests.swift, ios/MullvadVPNTests/MullvadSettings/InMemorySettingsStore.swift, ios/MullvadVPNTests/MullvadSettings/MigrationManagerTests.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/MullvadVPNTests/MullvadVPN/View controllers/SelectLocation/CustomListRepositoryTests.swift, ios/MullvadVPNTests/MullvadVPN/View controllers/Tunnel/DestinationDescriberTests.swift, ios/PacketTunnelCore/IPC/AppMessageHandler.swift
This PR makes the app look more responsive when reconnecting, especially when using Post Quantum keys.
It does so by doing the following: 
- Forcing the reconnect operation to give a status update from the tunnel
- Lower the time interval to poll the tunnel from every 3 seconds to every second when connecting, or reconnecting
- Fix a bug that did prevent the timer to switch to a lower value when the app was started with the tunnel already connected
- Make the simulator being able to fake reconnection, and show it on screen, for 600 milliseconds
- Due to the last fix, this created a crash in Unit Tests where the `SettingsManager.unitTestStore` would be read after the tests are ran, instead, the store is reset and never set to nil to avoid said crash
- `SimulatorTunnelProviderHost` can now …
=> Increase app response time when reconnecting

ios/MullvadRustRuntime/MullvadApiCancellable.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, mullvad-ios/src/api_client/cancellation.rs
This PR modifies the signature of `mullvad_api_cancel_task` and `mullvad_api_cancel_task_drop`
to make them take a reference to a `SwiftCancelHandle`
We need to do this in order to avoid passing a copy of the struct to the FFI which would not clear out correctly the pointer contained in it, hence creating double free issues when cancelling and dropping immediately after a `SwiftCancelHandle`.
Big thanks to @hulthe for helping out on this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8179)
=> Make the API cancellation handle safe, and properly clear out pointers

test/test-runner/src/logging.rs
See above. Test logs only included the 100 first log entries. The last entries are typically more useful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8176)
=> Truncate test framework to show the most recent logs, not the oldest

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/views/app-upgrade/components/footer/components/error-footer/hooks/useMessage.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/app-upgrade-error.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/app-upgrade/app-upgrade.spec.ts
The UX designers wanted to tweak the error messages after a QA session.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8182)
=> Update copy after QA testing

desktop/packages/mullvad-vpn/src/renderer/components/views/settings/SettingsView.tsx
Adjust position of `Split tunneling` list item in Settings view
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8184)
=> Adjust position of `Split tunneling` list item in Settings view

audits/2025-03-20-assured-installer-downloader.md
Just adding a link to the same report, but hosted on Assured's website as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8194)
=> Add link to installer downloader audit on Assured's website

.github/workflows/daemon.yml
By default, the longest path a filename can have in git on Windows is 260 character. We recently made a change on the Windows build server to allow for filenames up to 4096 characters (which is git's limit). We need to introduce the same change on our Windows Github runners.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8198)
=> Allow long filenames in git for the windows GitHub runners

CHANGELOG.md, ci/linux-repository-builder/build-linux-repositories-config.sh, ci/linux-repository-builder/build-linux-repositories.sh, ci/linux-repository-builder/prepare-apt-repository.sh, desktop/scripts/release/print-package-versions
As discussed previously, it can be a hassle for users on Linux distribution other than Ubuntu or Debian to install our repository. Because our instructions include the use of `lsb_release -cs` to compute what "codename" to fetch the repository for. And we don't publish the repository for codenames of distributions we don't support. It is also a maintenance burden to have to update supported codenames as new Debian and Ubuntu releases come out.
We publish the exact same `.deb` file regardless of distro and codename anyway. We only have one deb file. So we decided that it would be much more pragmatic, easier for us to maintain and easier for the users to use if the codenames were just "stable" and "beta".
We have to keep the old codenames for now, since all existing repo users use them. We …
=> Add static deb repo codenames "stable" and "beta"

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, desktop/packages/mullvad-vpn/src/renderer/components/WireguardSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/notifications/unsupported-wireguard-port.ts, desktop/packages/mullvad-vpn/src/shared/utils.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/notifications.spec.ts
Adds notification that shows when the user is connected to WireGuard with a port that is not supported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8187)
=> Add unsupported WireGuard port notification

CHANGELOG.md
This PR adds https://github.com/mullvad/mullvadvpn-app/pull/8187 to the changelog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8200)
=> Mention "Add unsupported WireGuard port notification" in changelog

desktop/packages/mullvad-vpn/package.json
It has been deprecated and replaced by the `develop` command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8205)
=> Remove develop:vite command

Cargo.toml
Saw a ~7% improvement in wireguard+masque benchmarks with this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8201)
=> Set opt-level=3 for libs that improve quic performance

desktop/packages/mullvad-vpn/test/e2e/mocked/user-interface-settings/user-interface-settings.spec.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/index.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/main/index.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/main/main-route-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/main/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/routes-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/select-language/index.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/select-language/select-language-route-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/select-language/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/settings/index.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/settings/settings-route-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/user-interface-settings/index.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/user-interface-settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/user-interface-settings/user-interface-settings-route-object-model.ts
Adds e2e test for testing language selection in the user interface view.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8138)
=> Add e2e tests for language selection

desktop/packages/mullvad-vpn/src/main/grpc-type-convertions.ts, desktop/packages/mullvad-vpn/src/main/index.ts, desktop/packages/mullvad-vpn/src/main/notification-controller.ts, desktop/packages/mullvad-vpn/src/main/tunnel-state.ts, desktop/packages/mullvad-vpn/src/main/user-interface.ts, desktop/packages/mullvad-vpn/src/renderer/app.tsx, desktop/packages/mullvad-vpn/src/renderer/components/Login.tsx, desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, desktop/packages/mullvad-vpn/src/renderer/components/main-view/ConnectionStatus.tsx, desktop/packages/mullvad-vpn/src/renderer/redux/connection/actions.ts, desktop/packages/mullvad-vpn/src/renderer/redux/connection/reducers.ts, desktop/packages/mullvad-vpn/src/shared/daemon-rpc-types.ts, desktop/packages/mullvad-vpn/src/shared/notifications/block-when-disconnected.ts, desktop/packages/mullvad-vpn/src/shared/notifications/disconnected.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/tunnel-state.spec.ts, desktop/packages/mullvad-vpn/test/e2e/setup/main.ts, desktop/packages/mullvad-vpn/test/unit/notification-evaluation.spec.ts
This PR replaces the use of the lockdown mode setting with the `lockedDown` field in the disconnected tunnel state, when deciding whether the app is locked down or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8139)
=> Use lockedDown field in disconnected state

.github/workflows/daemon.yml
This PR switches over to using GitHub hosted Windows ARM runner(s) instead of our self-hosted ditto (which we've had a flaky experience with). Currently we only make use of Windows ARM runner(s) in the `daemon.yml` workflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8212)
=> Use GitHub hosted Windows ARM runner

ios/MullvadVPN/TransportMonitor/TransportMonitor.swift, ios/MullvadVPN/TunnelManager/WgKeyRotation.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+KeyPolicy.swift
_Originally Mojgan's PR_
The device checker keeps failing with a network error when the packet tunnel starts. Using mullvad api should solve this.
The device checker is responsible to rotate the key when there is a mismatch with the server. Fixing this should solve the login/logout issue.
To reproduce the issue, try the steps in acceptance criteria.
Use the new mullvad api device proxy and account proxy for the device checker. This is being used in Debug.
There is also dead code related to key switching that should be removed:
- switchToCurrentKey()
- switchToCurrentKeyInner()
- private func setCurrentKeyPolicy(_ keyPolicy: inout State.KeyPolicy)
Write a document about this relating it to Login / Logout issue on Confluence. Make sure …
=> Remove dead code and add some more comments

mullvad-masque-proxy/examples/masque-client.rs, mullvad-masque-proxy/src/client/mod.rs
This prevents `SSLKEYLOGFILE` from being used to dump keys to a file. I've kept it enabled in the example client.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8228)
=> Disable `SSHKEYLOGFILE` by default in masque client

desktop/packages/mullvad-vpn/src/main/notification-controller.ts, desktop/packages/mullvad-vpn/src/renderer/components/ExternalLink.tsx, desktop/packages/mullvad-vpn/src/renderer/components/NotificationArea.tsx, desktop/packages/mullvad-vpn/src/shared/notifications/account-expired.ts, desktop/packages/mullvad-vpn/src/shared/notifications/close-to-account-expiry.ts, desktop/packages/mullvad-vpn/src/shared/notifications/notification.ts, desktop/packages/mullvad-vpn/src/shared/notifications/unsupported-version.ts, desktop/packages/mullvad-vpn/src/shared/notifications/update-available.ts
- Migrates in app banners from using 'open-url' to 'navigate-external'
- Splits up the system and in app notifications to have separate but mostly equal types.
- Renames system notification 'open-url' to 'navigate-external'
- Add support to ExternalLink component to open links with auth.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8217)
=> Rename system notification action `'open-url'` to `'navigate-external'`

ios/MullvadVPN/Coordinators/LoginCoordinator.swift, ios/MullvadVPN/View controllers/DeviceList/DeviceManagementContentView.swift, ios/MullvadVPN/View controllers/DeviceList/DeviceManagementViewController.swift
The too-many–devices view now gets presented instead of pushed. Swipe down to dismiss is disabled since the view contains a scroll view and therefore might dismiss unexpectedly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8209)
=> Change too many devices view to sheet

CHANGELOG.md, talpid-core/src/offline/windows.rs, talpid-core/src/tunnel_state_machine/connecting_state.rs, talpid-core/src/tunnel_state_machine/error_state.rs, talpid-types/src/net/mod.rs
Currently, if an IP version is set, the tunnel state machine fails to connect and gets stuck until users manually reconnect. The daemon now reconnects automatically in that case.
Also, this fixes an issue where the daemon got stuck connecting using a particular IP family on Windows.
Fix DES-2198
Fix DES-2201
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8231)
=> Fix failure to connect when IP version does not match offline monitor state

ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSource.swift, ios/MullvadVPN/View controllers/RelayFilter/RelayFilterDataSourceItem.swift, ios/MullvadVPNUITests/Screenshots/ScreenshotTests.swift
This makes the Filters view start in expanded state, though it remains collapsible. Some changes were made to where in the lifecycle the current selection is set due to the previous method not working correctly with a view that is visible at start. Additionally, some duplication was factored out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8172)
=> Modify Filters view to start in expanded state; also, some refactoring

ios/MullvadMockData/MullvadREST/APIProxy+Stubs.swift, ios/MullvadREST/ApiHandlers/RESTAPIProxy.swift, ios/MullvadREST/MullvadAPI/APIHandlers/MullvadAPIProxy.swift, ios/MullvadREST/MullvadAPI/APIRequest/APIRequest.swift, ios/MullvadREST/MullvadAPI/MullvadApiRequestFactory.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadTypes/Storekit2.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Extensions/StorePaymentManagerError+Display.swift, ios/MullvadVPN/StorePaymentManager/SendStoreReceiptOperation.swift, mullvad-api/src/lib.rs, mullvad-ios/src/api_client/storekit.rs
We are still using the legacy Storekit payment flows (v1) for purchasing time in the app. When running the app in debug mode we currently cannot test purchases anymore since we forgot to migrate this functionality.
Migrate legacy storekit payment to Mullvad API. It should be very similar to the implementation of Storekit v2.
When making in-app purchases in debug mode, calls should use Mullvad API rather than URLSession (and the current stub).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8232)
=> Migrate legacy storekit payment to Mullvad API

CHANGELOG.md, mullvad-daemon/src/early_boot_firewall.rs, mullvad-daemon/src/settings/mod.rs
We currently do not run any migration logic in this service. Instead, we just fetch the current settings, and overwrite them it this fails. This PR updates the early blocking code path to never overwrite existing settings.
Fix DES-2178
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8233)
=> Do not overwrite settings in `mullvad-early-boot-blocking.service`

ios/MullvadREST/ApiHandlers/AddressCache.swift, ios/MullvadRESTTests/MullvadApiTests.swift, ios/MullvadRustRuntime/MullvadAddressCacheProvider.swift, ios/MullvadRustRuntime/MullvadApiContext.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadTypes/AddressCacheProviding.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, mullvad-ios/src/api_client/access_method_resolver.rs, mullvad-ios/src/api_client/address_cache_provider.rs, mullvad-ios/src/api_client/mod.rs
This PR adds a reference to the `AddressCache` in the `MullvadApiContext` object.
This fixes an issue where the tokio runtime would panic in the past on trying to unwrap an Optional value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8202)
=> Fix API breaking down when used without connectivity

ios/MullvadVPNTests/MullvadREST/Relay/ObfuscatorPortSelectorTests.swift, ios/MullvadVPNUITests/Base/BaseUITestCase.swift, ios/MullvadVPNUITests/Networking/FirewallRule.swift, ios/MullvadVPNUITests/Networking/Networking.swift, ios/MullvadVPNUITests/Pages/TunnelControlPage.swift, ios/MullvadVPNUITests/RelayTests.swift
This PR adds tests for QUIC settings and UI Tests that guarantee that QUIC is working properly by blocking all Wireguard traffic when the test is running.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8215)
=> Add UITests for QUIC, add ability to block Wireguard traffic

ios/MullvadRustRuntime/MullvadAddressCacheProvider.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, mullvad-ios/src/api_client/address_cache_provider.rs
This PR removes a small hack to use something not relying on runloop internals to work, and ultimately gives us more control when a pointer is freed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8245)
=> Remove the DispatchQueue use to clear the cached address pointer

ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentConfiguration.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentView.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodInteractor.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodSectionIdentifier.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodViewController.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Models/AccessMethodViewModel.swift, ios/MullvadVPNUITests/AccessMethodsTests.swift, ios/MullvadVPNUITests/Pages/EditAccessMethodPage.swift
Earlier all access methods could be disabled in the UI. 
Now, the last enabled access method can not be disabled.
When the last enabled access method is a custom method and it gets deleted, `direct` will be enabled again.
This is the same behavior as on android.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8239)
=> Fix access method disable logic

desktop/package-lock.json, desktop/packages/mullvad-vpn/package.json, desktop/packages/mullvad-vpn/tasks/distribution.js
This reverts commit 2ea8801957c79ad81ec3d7d0048f1ae632654f84, reversing changes made to 84f7346714930ed7306253315b93f59a60a23b3b.
This change is done because Playwright cannot use the installed app
when the fuse is disabled. Quote from Playwright's documentation:
> Known issues:
> If you are not able to launch Electron and it will end up in timeouts during launch, try the following:
> Ensure that nodeCliInspect (FuseV1Options.EnableNodeCliInspectArguments) fuse is not set to false.
Link: https://playwright.dev/docs/api/class-electron
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8259)
=> Revert merge of `disable-enablenodecliinspectarguments-fuse-des-1969`

Cargo.lock, Cargo.toml, android/app/build.gradle.kts, android/gradle.properties, building/container-run.sh, mullvad-daemon/Cargo.toml, mullvad-jni/Cargo.toml, talpid-core/Cargo.toml, talpid-core/src/tunnel/mod.rs, talpid-tunnel/Cargo.toml, talpid-tunnel/src/tun_provider/mod.rs, talpid-tunnel/src/tun_provider/stub.rs, talpid-tunnel/src/tun_provider/unix.rs, talpid-tunnel/src/tun_provider/windows.rs, talpid-wireguard/Cargo.toml, talpid-wireguard/build.rs, talpid-wireguard/src/boringtun/mod.rs, talpid-wireguard/src/connectivity/check.rs, talpid-wireguard/src/connectivity/mod.rs, talpid-wireguard/src/connectivity/monitor.rs, talpid-wireguard/src/ephemeral.rs, talpid-wireguard/src/lib.rs, talpid-wireguard/src/logging.rs, talpid-wireguard/src/wireguard_go/mod.rs, talpid-wireguard/src/wireguard_nt/mod.rs
Test run (without `--features boringtun`, i.e. using `wireguard-go`): https://github.com/mullvad/mullvadvpn-app/actions/runs/15116240090.
Opening the tunnel device works the first time, but fails the second time with the following error on Windows
```
[2025-05-14 13:13:02.693][talpid_core::tunnel_state_machine::connecting_state][ERROR] Error: Failed to start tunnel
Caused by: Failed while listening for events from the Wireguard tunnel
Caused by: Tunnel failed
Caused by: Failed to create tunnel device
Caused by: Unable to open a tunnel device
Caused by: WintunStartSession failed "Failed to register rings: An attempt was made to perform an initialization operation when initialization has already been completed. (Code 0x000004DF)"
```
The error originates in the `wintun-bindings` crate: …
=> Add Boringtun

CHANGELOG.md, windows/driverlogic/driverlogic.vcxproj, windows/nsis-plugins/src/cleanup/cleanup.vcxproj, windows/nsis-plugins/src/log/log.vcxproj, windows/nsis-plugins/src/pathedit/pathedit.vcxproj, windows/nsis-plugins/src/registry/registry.vcxproj, windows/nsis-plugins/src/string/string.vcxproj, windows/nsis-plugins/src/tray/tray.vcxproj, windows/winfw/src/winfw/winfw.vcxproj
This PR enables control flow guard (https://learn.microsoft.com/en-us/windows/win32/secbp/control-flow-guard) for all C++ code. This does not include Electron-supplied binaries, any of the drivers, anything in the binaries repository, or OpenVPN.
Todo:
Fix DES-2172
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8214)
=> Enable control flow guard for C++ code

Cargo.lock, talpid-wireguard/Cargo.toml
This fixes the issue where reconnecting fails every time, because not all spawned tasks were aborted.
Close DES-2161
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8278)
=> Fix boringtun device not being closed when disconnecting

android/app/src/androidTest/kotlin/net/mullvad/mullvadvpn/talpid/util/ConnectivityManagerUtilKtTest.kt, android/lib/talpid/src/main/kotlin/net/mullvad/talpid/util/ConnectivityManagerUtil.kt
Default network is not updated on Android 9 (and presumably Android 8 as well) if the VPN is connected and the internetet connection goes from offline to online. This fixes the issue by checking the online status on all network events.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8286)
=> Listen for all network events to fix missing default network events

ios/MullvadMockData/MullvadREST/APIProxy+Stubs.swift, ios/MullvadREST/ApiHandlers/RESTAPIProxy.swift, ios/MullvadREST/MullvadAPI/APIHandlers/MullvadAPIProxy.swift, ios/MullvadREST/MullvadAPI/APIRequest/APIRequest.swift, ios/MullvadREST/MullvadAPI/MullvadApiRequestFactory.swift, ios/MullvadRustRuntime/MullvadConnectionModeProvider.swift, ios/MullvadRustRuntime/include/mullvad_rust_runtime.h, ios/MullvadTypes/PersistentAccessMethod.swift, ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTester.swift, ios/MullvadVPN/AccessMethodRepository/ProxyConfigurationTesterProtocol.swift, ios/MullvadVPN/Coordinators/ApplicationCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/APIAccess/Edit/EditAccessMethodInteractor.swift, mullvad-ios/src/api_client/api.rs, mullvad-ios/src/api_client/response.rs
This PR adds the ability to `Test` the API in AccessMethods using the Rust API client.
The client will only be used in Debug builds, we still rely on `URLSession` for release builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8282)
=> Move api access method test call to mullvad api ios 1195

ios/MullvadVPN/UI appearance/Color+Mullvad.swift
Uses correct base color for disabled button text color
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8298)
=> Fix disabled button text color

ios/MullvadVPNUITests/Pages/TunnelControlPage.swift
Feature indicators were changed from text to buttons which broke the ui tests. Now they are fixed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8323)
=> Fix ios ui tests after quick access buttons

osv-scanner.toml, wireguard-go-rs/libwg/osv-scanner.toml
Note: We cannot get rid of `paste` yet since `rtnetlink` transitively depends on it: https://github.com/rust-netlink/rtnetlink/pull/102
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8325)
=> Bump `ignoreUntil` in libwg

talpid-core/src/tunnel_state_machine/mod.rs, talpid-tunnel/src/tun_provider/android/mod.rs, talpid-wireguard/src/boringtun/mod.rs, talpid-wireguard/src/obfuscation.rs, talpid-wireguard/src/wireguard_go/mod.rs, wireguard-go-rs/src/lib.rs
We accidentally borrowed the file descriptor when we should have moved it. This commit adds more `OwnedFd` and friends to help handle ownership correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8326)
=> Fix tun file descriptor ownership.

ios/MullvadREST/Relay/RelayPicking/SinglehopPicker.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Coordinators/LoginCoordinator.swift, ios/MullvadVPN/Coordinators/Settings/DAITA/DAITAMultihopNotice.swift, ios/MullvadVPN/Coordinators/Settings/DAITA/DAITATunnelSettingsViewModel.swift, ios/MullvadVPN/Coordinators/Settings/DAITA/SettingsDAITAView.swift, ios/MullvadVPN/View controllers/InAppPurchase/InAppPurchaseViewController.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift, ios/MullvadVPN/View controllers/RelayFilter/ChipViewCell.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipFeature.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/FeatureIndicatorsViewModel.swift, ios/MullvadVPN/View controllers/VPNSettings/VPNSettingsViewController.swift, ios/MullvadVPN/Views/List/MullvadList.swift, ios/MullvadVPNUITests/Pages/TunnelControlPage.swift, ios/MullvadVPNUITests/RelayTests.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift, ios/PacketTunnelCoreTests/MultiHopEphemeralPeerExchangerTests.swift
We want to clarify to users that multihop is being used because of "smart routing" with DAITA.
- Combine DAITA and Multihop to one pill when "smart routing" is active. It should say "DAITA: Multihop".
- Add info to the DAITA subview by using the navigation header subtitle space: "(i) Multihop is being used to enable DAITA for your selected location."
- Investigate styling that makes this more visible // Talk to @carl 
- This info disappears if Direct Only is enabled or if DAITA is disabled.
- Feature indicator should say "DAITA: Multihop" when "smart routing" is on.
- New info added to the DAITA subview when "smart routing" is on.
Tests
UI tests.
- - - …
=> Combine DAITA and Multihop to one pill when smart routing is active

ios/MullvadMockData/MullvadREST/ServerRelaysResponse+Stubs.swift, ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift, ios/MullvadRESTTests/ServerRelayTests.swift, ios/MullvadVPN/RelayCacheTracker/RelayCacheTracker.swift, ios/MullvadVPN/View controllers/RelayFilter/FilterDescriptor.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorTests.swift, ios/MullvadVPNTests/MullvadSettings/IPOverrideWrapperTests.swift
This adds `masque_extra_addr_in` and an optional `features` structure, which will hold substructures for `quic` and `daita`. It also replaces the logic that checks the soon-to-be-deprecated boolean `daita` field with one which accepts the presence of a `features.daita` structure (which is currently uninhabited), and updates tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8330)
=> Add QUIC/Masque fields and Features structure to ServerRelay

android/app/src/main/AndroidManifest.xml
android:memtagMode="async"
to the <application> element in the AndroidManifest.xml.
Why this is wanted
Catch memory safety issues early. Asynchronous MTE allows the system to tag heap allocations and check pointer usage at runtime, helping detect buffer overflows and use-after-free bugs in native code without significant performance overhead.
Improve security. Mullvad relies on native libraries (e.g. for crypto). MTE hardens these components against memory-corruption exploits on supported devices.
Align with platform defaults. Newer Android versions (Android 13+) ship with MTE support; opting into async mode ensures we’re taking advantage of platform improvements.
How it’s implemented
Open app/src/main/AndroidManifest.xml.
In the <application> tag, add the attribute:
<application …
=> Enable opt-in to MTE async mode

CHANGELOG.md, dist-assets/pkg-scripts/postinstall, dist-assets/uninstall_macos.sh
Following how `fish` completions are installed in `/opt/homebrew`, this does the same for `zsh` completions by editing the macOS installer's postinstall and uninstall scripts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8313)
=> macOS: use `/opt/homebrew` for zsh completions if available

ios/MullvadVPN/TunnelManager/TunnelState.swift, ios/MullvadVPN/View controllers/Account/AccountInteractor.swift, ios/MullvadVPN/View controllers/Account/AccountViewController.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeContentView.swift, ios/MullvadVPN/View controllers/OutOfTime/OutOfTimeViewController.swift
Time cannot be added to account when in blocked state. Since the calls to Apple's servers are handled through the Storekit API we cannot circumvent this by eg. proxying the calls to the packet tunnel process. Instead we need to handle this in the UI.
The add time button on account page needs to be disabled if the app is in blocked state.
Add time button cannot be interacted with in blocked state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8359)
=> Disable add time button when app is in blocked state

mullvad-update/mullvad-release/src/platform.rs
This PR addresses an issue in the the `mullvad-release` tool where the bumped metadata version never was comitted to the new metadata.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8374)
=> Fix metadata version not being bumped

desktop/scripts/release/publish-metadata-to-api
This PR fixes a bug that prevented upload of release metadata to build server if someone else did the previous release. The problem was that a directory owned by the previous person remained and prevented the current release from being uploaded due to missing permission. Removing the top level release directory solves this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8384)
=> Fix cleanup of metadata on build server

ios/MullvadMockData/MullvadREST/ServerRelaysResponse+Stubs.swift, ios/MullvadREST/ApiHandlers/ServerRelaysResponse.swift, ios/MullvadREST/Relay/ObfuscatorPortSelector.swift, ios/MullvadREST/Relay/RelaySelectorWrapper.swift, ios/MullvadRESTTests/ServerRelayTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelaySelectorTests.swift, ios/MullvadVPNTests/MullvadSettings/IPOverrideWrapperTests.swift
The RelaySelectorneeds to correctly filter out relays without QUIC support when QUIC is enabled. The new field addr_in will contain extra addresses for QUIC to use. The behavior should be very similar to what we do with Shadowsocks.
The RelaySelector needs to be updated to filter out relays without QUIC support when QUIC is enabled. Look at ObfuscatorPortSelector.obfuscateShadowsocksRelays() for how this is done for Shadowsocks.
RelaySelector correctly filters out relays without QUIC support when QUIC is enabled.
**Tests**
Update existing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvad …
=> Update RelaySelector to handle extra addresses

desktop/scripts/release/2-create-and-push-tag, desktop/scripts/release/3-verify-build
This PR adds a `--wait` flag to  release script 2 and 3, that waits until the process has completed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8070)
=> Add --wait flag to desktop release scripts

mullvad-update/src/client/api.rs, mullvad-update/src/format/deserializer.rs
This PR fixes some failing Rust tests by making tests, for verifying `mullvad-update` metadata, run with mocked time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8416)
=> Fix Rust CI failing due to expired metadata

CHANGELOG.md, dist-assets/pkg-scripts/postinstall, dist-assets/uninstall_macos.sh
This PR reverts https://github.com/mullvad/mullvadvpn-app/pull/8313, since the motivation for adding it was too vague in hindsight. Sorry to the original author.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8429)
=> Revert "use /opt/homebrew for zsh completions if available"

test/test-manager/src/tests/mod.rs, test/test-manager/src/tests/windows.rs, test/test-rpc/src/client.rs, test/test-rpc/src/lib.rs, test/test-runner/src/main.rs, test/test-runner/src/sys.rs
Test run: ~https://github.com/mullvad/mullvadvpn-app/actions/runs/16170030641/job/45642313111~
~https://github.com/mullvad/mullvadvpn-app/actions/runs/16196025240~
https://github.com/mullvad/mullvadvpn-app/actions/workflows/desktop-e2e.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8438)
=> Add e2e test for clearing upgrade firewall rules on reboot

.github/workflows/android-app.yml
Moving the dummy debug keystore to an enviornment variable to make it accessible for forks. The dummy `debug.keystore` is not considered a secret and is only used for test and verification.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8451)
=> Fix debug keystore usage in fork jobs

talpid-core/src/firewall/macos.rs
For reasons we don't understand, blocking mDNS queries can result in the tunnel breaking
Fix DES-2311
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8460)
=> Do not flush mDNS states on macOS

mullvad-daemon/src/android_dns.rs
Reading /etc/hosts causes OOM issues if the hosts files on the device is large (e.g. > 10 MB). We should not need to read the hosts files because the only lookups we do with hickory are to our own servies which should not be resolved from /etc/hosts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8457)
=> Prevent hickory-resolver from reading the /etc/hosts file

CHANGELOG.md, desktop/packages/mullvad-vpn/src/main/daemon-rpc.ts, desktop/packages/mullvad-vpn/src/main/grpc-client.ts, desktop/packages/mullvad-vpn/src/main/index.ts
This fixes some races, e.g. when the file is opened as the gRPC server is shutting down, by retrying.
Fix DES-2314
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8466)
=> Check named pipe/UDS ownership when connecting to gRPC server

android/lib/ui/component/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/component/relaylist/SelectableRelayListItem.kt
This fix ensures that non-selectable entry or exit locations, due to already being selected in the other list, are unclickable. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8477)
=> Make current entry non-selectable in exit list

desktop/osv-scanner.toml
It has not yet been patched according to https://osv.dev/vulnerability/GHSA-g974-hxvm-x689.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8479)
=> Bump ignore date for node-gettext CVE

desktop/package-lock.json, desktop/package.json
Updates `eslint` to `9.31.0` to fix [GHSA-xffm-g5w8-qvg7 ](https://osv.dev/vulnerability/GHSA-xffm-g5w8-qvg7).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8490)
=> Update eslint to `9.31.0`

mullvad-daemon/src/migrations/v7.rs, mullvad-daemon/src/migrations/v9.rs
In a sense a follow-up to #8461. I noticed the addition of `#[allow(unused)]` here and was curious as to why this code was unused and why we should ignore it rather than delete it.
Turns out all these structs were unused already when they were introduced. I checked out the commit that first created `v7.rs` and built it with the latest nightly compiler. It complains about these structs being unused already back then. So this must have been a mistake at the creation of this migration, and not caught since the compiler was not as good at finding those back then.
The comment in the commit message from @MarkusPettersson98 is that we should not touch closed migration code. In general I agree. We should ideally not touch this code. But removing code that sits completely unused is different from …
=> Remove unused code in settings migration

docs/security.md
We got questions about the security of the connection to `api.mullvad.net` during some audits. This PR adds some more information about that connection to our existing security document. Should help security researchers and users understand the security properties of the app in the future.
Please suggest more things we can add that could be helpful, but without going into too much details that risk becoming outdated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8494)
=> Improve security docs around TLS connection to API server

.github/CODEOWNERS, .github/workflows/verify-locked-down-signatures.yml
1. `/ci/verify-locked-down-signatures.sh` was not defined in `CODEOWNERS`. Meaning any non-teamlead could modify it. This sort of nullifies the security guarantees we tried to uphold by protecting `verify-locked-down-signatures.yml`, since it relies on the bash script for its check.
2. Add names to the CI jobs. This seems required to be able to refer to them in github rulesets regarding what CI jobs *must* pass for a PR to be mergable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8504)
=> Make the git signature verification CI stricter

android/lib/ui/component/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/component/relaylist/SelectableRelayListItem.kt, android/lib/ui/tag/src/main/kotlin/net/mullvad/mullvadvpn/lib/ui/tag/TestTagConstants.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/SelectLocationPage.kt
Previously it would look for the first location cell and try to expand that one. Since this can in some cases be a recents cell the test would fail as it is not possible to expand a recents cell.
~This PR instead changes this behaviour to instead look for all matching location cells and then try to expand all of them. It will not throw an error if it can find any which is expandable.~
Instead we will add a type of cell tag to all names so that we can check for both name and tag and avoid trying to click on the expand cell of recent location items.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8511)
=> Check for location cells matching name and tag in e2e tests

android/app/src/main/AndroidManifest.xml
This means that if an app on a TV device has connect on start up turned on, it will connect around 10-15 seconds after the device starts, instead of 1-2 minutes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8522)
=> Set max priority on the boot receiver

android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/interactor/AppInteractor.kt, android/test/common/src/main/kotlin/net/mullvad/mullvadvpn/test/common/page/PrivacyPage.kt, android/test/e2e/src/main/kotlin/net/mullvad/mullvadvpn/test/e2e/LoginTest.kt
Sometimes the allow notification dialog will not show. We should still proceed with the test if that is the case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8524)
=> Only log failures to allow notifications in mock api and e2e tests

android/app/src/main/kotlin/net/mullvad/mullvadvpn/receiver/NotificationAlarmReceiver.kt, android/app/src/main/kotlin/net/mullvad/mullvadvpn/util/BroadcastReceiverExtensions.kt, android/service/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/accountexpiry/AccountExpiryNotificationProvider.kt
In onReceive in NotificationAlarmReceiver onBlocking() was used which could potentially take too much time and cause an ANR. This PR changes the onBlocking() call to instead use the goAsync() API so that the onReceive method can return immediately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8542)
=> Attempt to fix potential ANR

ios/MullvadVPN/Coordinators/Settings/Views/SettingsInfoView.swift
I have adjusted the amount of spacing above the page indicator for multi-page help views from 72 to 36. This has been empirically tested in the simulator to be a good compromise between not being overly cluttered on spacious screens and allowing the controls to be visible at the bottom on smaller screens (or with larger font sizes).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8521)
=> Reduce spacing above page indicator

ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift
When adding .quic to obfuscation the debug mode was changed and obfuscation = .off was missed. This fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8557)
=> Fix obfuscation not handling .off in release mode

building/Dockerfile, building/container-run.sh, ci/buildserver-build-android.sh, ci/buildserver-build.sh
Since the mold version in the container is very old, we should either upgrade it or remove it. I benchmarked mold version 2.40.2 (much newer than what we currently have in the container). The result was that it was just a few percent faster than the default linker. So there is no strong argument for keeping mold. Developers can still use mold outside of the containers if they want to.
Since mold was disabled by default, and no one I have spoken to seems to enable mold, this change should not really have any impact at all, except making building the containers faster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8563)
=> Remove mold from build container

wireguard-go-rs/libwg/osv-scanner.toml
wireguard-go does not use database/sql.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8569)
=> Ignore GO-2025-3849 affecting database/sql

test/test-manager/docs/config.md
This is a follow up to https://github.com/mullvad/mullvadvpn-app/pull/8454
Only 2 relays have QUIC enabled in production: One in Sweden and one in Canada. Canadian relays are not included in the default set of relays used for our e2e tests. This PR updates the test manager config to fix that for the QUIC tests that need 2 relays to work due to multihop constraints. 
First test run where this change was applied: https://github.com/mullvad/mullvadvpn-app/actions/runs/16875507172/job/47799801853. All previous test runs used the default custom list of the nordic countries. :cry: :violin: :iceland: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8577)
=> Update custom list for `test_quantum_resistant_multihop_quic_tunnel`

ci/buildserver-config.sh, ci/buildserver-upload.sh
Fixes artifacts not being updated when release tags are replaced.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8591)
=> Invalidate CDN cache after uploading release artifacts

ios/MullvadVPN/View controllers/ChangeLog/ChangeLogView.swift
This adjusts the structure of the changelog view to move the horizontal padding to list items, and thus within the implicit scroll view that they are created inside.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8593)
=> Move padding to within the changelog's implicit scroll view

.github/workflows/daemon.yml
Our CI started failing recently due to a type error showing up when using the rust compiler from the nightly channel: https://github.com/mullvad/mullvadvpn-app/actions/runs/16933448883/job/47984313311
This has been confirmed to be a regression in the compiler itself, and a fix has seemingly been merged already. Pinning the nightly compiler to the last known working version in our CI for now, but this should be reverted ASAP.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8598)
=> Pin Rust nightly compiler to 2025-08-11 to avoid compiler regression

desktop/packages/mullvad-vpn/src/renderer/components/select-location/RelayListContext.tsx, desktop/packages/mullvad-vpn/src/renderer/components/select-location/SelectLocation.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/filter-locations.ts
This PR fixes a bug of the relay selection screen filtering logic when QUIC and multihop was enabled. The filter was applied to both entry and exit relays, while the filter should've only been applied to the entry relay in the first place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8595)
=> Do not filter exit relays when multihop and QUIC is enabled

mullvad-daemon/src/lib.rs
If the user has managed to log in we unconditionally set update_default_location = false. This is done to prevent an edge case where the geolocation request completes after the user has logged in and then the default location could change while the user is in the process of clicking the select location/connect buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8606)
=> Set the default location set flag at login

.github/workflows/git-commit-message-style.yml, mullvad-relay-selector/src/relay_selector/matcher.rs, mullvad-relay-selector/src/relay_selector/mod.rs, mullvad-relay-selector/tests/relay_selector.rs
This PR fixes an issue where the user would be blocked by selecting a country with very few relays that had the `include_in_country` flag set to `true` and the the relay selector somehow managed to filter out all candidate relays. This would manifest itself in a multihop constraint.
Added a small test case that would demonstrate the relay selector being too dumb to pick a valid multihop circuit. Revert the last commit to see it fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8626)
=> Fix `include_in_country` flag filtering out relays too aggresively

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/Supporting Files/de.lproj/InfoPlist.strings, ios/MullvadVPN/Supporting Files/fr.lproj/InfoPlist.strings, ios/MullvadVPN/Supporting Files/sv.lproj/InfoPlist.strings, ios/PacketTunnel/de.lproj/InfoPlist.strings, ios/PacketTunnel/fr.lproj/InfoPlist.strings, ios/PacketTunnel/sv.lproj/InfoPlist.strings, ios/translation/locales/de.xliff, ios/translation/locales/en.xliff, ios/translation/locales/fr.xliff, ios/translation/locales/sv.xliff, ios/translation/scripts/localizations.sh
This PR removes localization from the plist file in the packet tunnel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8625)
=> Remove string plist from packet tunnel

test/docs/BUILD_OS_IMAGE.md
`unattended-upgrades` can block a VM from installing the app when running end-to-end tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8639)
=> Add instruction to remove `unattended-upgrades` from Ubuntu test VMs

.github/workflows/daemon.yml
This PR reverts https://github.com/mullvad/mullvadvpn-app/pull/8598 since the bug in `rustc` has been fixed. Nightly compilers from `2025-08-17` and newer should be fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8642)
=> Revert "Pin Rust nightly compiler to 2025-08-11 to avoid compiler regressions"

test/test-manager/src/tests/relay_ip_overrides.rs
`test_wireguard_ip_override` is failing with port 443 not being in the retry order for WG anymore. Another fix was forcing IPv4 to be used, since it could otherwise succeed by not using the override and instead connecting over IPv6. Constraining the port in the relay constraints should also make it a bit faster
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/17159041587
Fix DES-2399
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8649)
=> Update ports in IP override tests

.github/actions/ios/setup-project-toolchain/action.yml, .github/workflows/ios-screenshots-tests.yml, .github/workflows/ios-validate-build-schemas.yml, .github/workflows/ios.yml
This PR removes the hotfix we added to force using Xcode 16.4 on the CI while Github was making it the default install.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8657)
=> Remove hotfix to force Xcode 16.4

ios/Assets/Localizable.xcstrings, ios/MullvadVPN/Classes/AccessbilityIdentifier.swift, ios/MullvadVPN/Coordinators/LoginCoordinator.swift, ios/MullvadVPN/View controllers/Login/AccountInputGroupView.swift, ios/MullvadVPN/View controllers/Login/LoginInteractor.swift, ios/MullvadVPN/View controllers/Login/LoginViewController.swift, ios/MullvadVPNUITests/AccountTests.swift, ios/MullvadVPNUITests/Pages/LoginPage.swift
Adds a confirmation dialog before the saved last used account number gets removed from the device. This happens when creating a new account and when the user actively removes the number.
This is a draft for now since the copy is not decided on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8588)
=> Add confirmation dialogs when removing saved account number

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/renderer/components/AppRouter.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/login/ClearAccountHistoryDialog.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/login/CreateAccountDialog.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/login/Login.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/login/LoginStyles.tsx, desktop/packages/mullvad-vpn/src/shared/ipc-helpers.ts, desktop/packages/mullvad-vpn/src/shared/ipc-schema.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/login.spec.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/mocked-utils.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/login/index.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/login/login-route-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/login/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/routes-object-model.ts
This PR adds confirmaiton dialogs when clearing account history and when creating a new account if there is an account in the history.
I've also added a new utility to in a type safe way get the ipc event keys.
Fixes DES-2228.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8674)
=> Add confirmation dialogs when clearing/replacing account history

CHANGELOG.md, mullvad-daemon/src/version/check.rs, mullvad-daemon/src/version/router.rs
This prevents the app from erroneously being labeled unsupported after upgrades/downgrades.
I've solved it by just adding a version to the cache itself (like we did have previously), as this seemed simpler and more robust than relying totally on the install scripts.
Fix DES-2408
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8687)
=> Link version cache (and the `supported` bool) to app version

desktop/packages/mullvad-vpn/tasks/utils.js
Changed so that if a npm command exits with an error when we are building the desktop application we will terminate the entire build process and exit with exit code 1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8694)
=> Terminate build process with an exit code when an npm command exits with an error

Cargo.lock, Cargo.toml, desktop/scripts/release/5-update-and-publish-metadata, mullvad-update/Cargo.toml, mullvad-update/mullvad-release/Cargo.toml, mullvad-update/mullvad-release/src/main.rs, mullvad-update/mullvad-release/src/platform.rs, mullvad-update/src/client/api.rs, mullvad-update/src/format/mod.rs, mullvad-update/src/version.rs
This PR adds a `mullvad-release` command for generating a file containing the latest versions, and a script for uploading it.
`latest.json` can be produced by running `mullvad-release query-latest [platform...]`, and the format is 
```
{
"linux": {
"stable": {
"version": "2025.8"
},
"beta": {
"version": "2025.9-beta1"
}
},
"windows": {
"stable": {
"version": "2025.8"
},
"beta": {
"version": "2025.9-beta1"
}
},
"macos": {
"stable": {
"version": "2025.8"
},
"beta": {
"version": "2025.9-beta1"
}
}
}
```
The `beta` fields are nullable.
This data will not be consumed by the app. It is a source for other clients, and the format must be simple and stable.
During a release, running `./desktop/scripts/release/6-update-latest-versions` should take care of keeping this up to date.
Fix DES-2367
- - - …
=> Add script for generating and uploading `latest.json` metadata

ios/MullvadVPN/Supporting Files/Info.plist
This PR disables the Liquid Glass design on iOS 26 when building with Xcode26
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8701)
=> Disable liquid glass design when building with Xcode 26

ci/ios/test-router/raas/src/capture/parse.rs, ios/MullvadVPNUITests/Networking/PacketCapture.swift, ios/MullvadVPNUITests/Pages/TunnelControlPage.swift, ios/MullvadVPNUITests/RelayTests.swift
This PR adds a test that asserts that, on average, turning on DAITA will lead to an increased packet mean size.
To do this, I did the following : 
- Add a `size` property in the captured packets object we get from our custom capture API.
- Add a test that generates traffic with and without DAITA
- Once the results are in, we compute the mean size of packets and we assert that DAITA traffic should see increased mean packet size. 
If this is too flaky on the long run, we can use the [`t-test` method](https://en.wikipedia.org/wiki/Student%27s_t-test) instead which should indicate that the two data sets are significantly different statistically speaking (i.e. DAITA does have an effect on the traffic size)
The changes for the router API have already been deployed as part of this test.
- - - …
=> Add a test that asserts DAITA increases packet size on average

desktop/osv-scanner.toml
Ignore CVE-2025-55305 since we're not affected. We use neither of the two fuses described in the vulnerability description: https://osv.dev/vulnerability/GHSA-vmqv-hx8q-j7mg
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8711)
=> Ignore CVE-2025-55305

desktop/packages/mullvad-vpn/test/e2e/installed/state-dependent/login.spec.ts, test/test-manager/src/tests/ui.rs
This PR fixes the broken `login.spec.ts` test by clearing the account history before running it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8712)
=> Start login ui test with clear account history

Cargo.lock, test/Cargo.lock
This PR mitigates RUSTSEC-2025-0056 by getting rid of the unmaintained `adler` crate from our dependency tree.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8724)
=> Mitigate `Rustsec-2025-0056`

CHANGELOG.md, talpid-core/src/resolver.rs, talpid-routing/src/lib.rs, talpid-routing/src/unix/macos/data.rs, talpid-routing/src/unix/macos/mod.rs, talpid-routing/src/unix/macos/routing_socket.rs, talpid-routing/src/unix/macos/watch.rs, test/test-manager/src/tests/macos.rs
This ensures that the loopback interface alias (used by the local DNS resolver) is recreated if it is removed for whatever reason.
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/17464404532
Test fails on main: https://github.com/mullvad/mullvadvpn-app/actions/runs/17464879908
Fix DES-2401
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8675)
=> Recreate the resolver loopback interface alias/IP if it is removed

.github/CODEOWNERS
As new team lead for the Android team I re-assign most of the team lead code ownership responsibilities from Albin to @Rawa.
I kept Albin on the only file tightly related to Android building: The container name file. But please suggest other files where you think it makes sense that Albin keeps code owner status as well, if any.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8713)
=> Make David G code owner for a lot of the stuff Albin had

Cargo.toml, deny.toml
I saw in the output of `cargo deny check license` that our `GPL-3.0` license identifier is deprecated. So this PR updates it to the new equivalent. This should mean the same thing according to my understanding. See https://spdx.org/licenses/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8735)
=> Change license identifier from `GPL-3.0` to `GPL-3.0-only`

mullvad-relay-selector/src/error.rs, mullvad-relay-selector/src/relay_selector/mod.rs
Add print the relay query that caused all relays to be filtered out. The error message still isn't great, but should be slightly more usable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8696)
=> Improve no matching relay error

desktop/packages/mullvad-vpn/test/e2e/mocked/mocked-utils.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/select-location/helpers.ts
Fixes the type signature of the mock IPC handle. The mock handle should receive the IPC handle's response as the argument of the first parameter, in line with the actual implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8745)
=> Fix mock ipc handle type

ios/MullvadMockData/MullvadREST/RelaySelectorStub.swift, ios/MullvadMockData/MullvadREST/SelectedRelaysStub+Stubs.swift, ios/MullvadMockData/MullvadREST/ServerRelaysResponse+Stubs.swift, ios/MullvadREST/Relay/MultihopDecisionFlow.swift, ios/MullvadREST/Relay/Obfuscation/RelayObfuscator.swift, ios/MullvadREST/Relay/Obfuscation/ShadowsocksObfuscator.swift, ios/MullvadREST/Relay/ObfuscationMethodSelector.swift, ios/MullvadREST/Relay/RelayPicking/MultihopPicker.swift, ios/MullvadREST/Relay/RelayPicking/SinglehopPicker.swift, ios/MullvadREST/Relay/RelaySelectorProtocol.swift, ios/MullvadREST/Relay/RelaySelectorWrapper.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ChipView/ChipContainerView.swift, ios/MullvadVPNTests/MullvadREST/Relay/MultihopDecisionFlowTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/ObfuscationMethodSelectorTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayObfuscatorTests.swift, ios/MullvadVPNTests/MullvadREST/Relay/RelayPickingTests.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor+ErrorState.swift, ios/PacketTunnelCore/Actor/PacketTunnelActor.swift, ios/PacketTunnelCore/Actor/ProtocolObfuscator.swift, ios/PacketTunnelCore/Actor/Protocols/TunnelAdapterProtocol.swift, ios/PacketTunnelCore/Actor/State.swift, ios/PacketTunnelCoreTests/AppMessageHandlerTests.swift, ios/PacketTunnelCoreTests/EphemeralPeerExchangingPipelineTests.swift, ios/PacketTunnelCoreTests/Mocks/ProtocolObfuscationStub.swift, ios/PacketTunnelCoreTests/ProtocolObfuscatorTests.swift
This PR introduces a bias in the `ObfuscationMethodSelector` that lets us bypass the chosen obfuscation, in specific scenarios where the relay selector would select obfuscation that certain servers would not support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8760)
=> Bypass obfuscation when not supported

.github/workflows/desktop-e2e.yml
This PR adds Fedora 43 to the arsenal of VMs used in our desktop E2E tests.
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/17788352428/job/50560906769
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8790)
=> Add Fedora 43 VM to end-to-end tests

Cargo.lock, Cargo.toml, talpid-routing/Cargo.toml, talpid-routing/src/lib.rs, talpid-routing/src/unix/linux.rs, talpid-wireguard/Cargo.toml, talpid-wireguard/src/wireguard_kernel/mod.rs, talpid-wireguard/src/wireguard_kernel/nl_message.rs, talpid-wireguard/src/wireguard_kernel/parsers.rs, talpid-wireguard/src/wireguard_kernel/wg_message.rs
This PR started out as a quick fix for getting rid of `paste` from our dependency tree, but it kind of spiraled when I had to update the `netlink-packet-*` crates in order to do so. We were quite far behind on this, but this PR fixes that! The changes are contained to `talpid-routing` and `talpid-wireguard`, but they require careful inspection to make sure nothing broke. Most changes were straight forward.
- Upgrade `netlink-packet-core` to `0.8.0`
- Upgrade `netlink-packet-route` to `0.25.1`
- Upgrade `netlink-proto` to `0.12.0`
- Upgrade `rtnetlink` to `0.18.1`
- Remove `netlink-packet-utils`
- Promote `netlink-*` crates & `rtnetlink` to workspace dependencies
E2E test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/17737929406
- - - …
=> Bump netlink crates

desktop/packages/mullvad-vpn/src/main/grpc-type-convertions.ts, desktop/packages/mullvad-vpn/src/shared/daemon-rpc-types.ts
The GUI misbehaves a bit when LWO is enabled. This isn't too bad since it's hidden behind a feature flag, but preventing this exception fixes it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8777)
=> Add LWO to UI obfuscation types

desktop/packages/mullvad-vpn/locales/messages.pot, desktop/packages/mullvad-vpn/src/main/daemon-rpc.ts, desktop/packages/mullvad-vpn/src/main/index.ts, desktop/packages/mullvad-vpn/src/renderer/app.tsx, desktop/packages/mullvad-vpn/src/renderer/components/SearchBar.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/LinuxSettings.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/LinuxSettingsContext.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/header-description/HeaderDescription.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/header-description/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/header-description/hooks/use-show-unsupported-dialog.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/header-description/index.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/index.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/linux-application-list/LinuxApplicationList.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/linux-application-list/components/linux-application-row/hooks/use-disabled.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/linux-application-list/components/linux-application-row/hooks/use-launch-application.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/open-file-picker-button/OpenFilePickerButton.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/open-file-picker-button/hooks/index.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/open-file-picker-button/hooks/use-disabled.ts, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/unsupported-dialog/UnsupportedDialog.tsx, desktop/packages/mullvad-vpn/src/renderer/components/views/split-tunneling/components/linux-settings/components/unsupported-dialog/index.ts, desktop/packages/mullvad-vpn/src/shared/ipc-schema.ts, desktop/packages/mullvad-vpn/test/e2e/mocked/split-tunneling/split-tunneling.spec.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/routes-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/settings/settings-route-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/split-tunneling-settings/index.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/split-tunneling-settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/split-tunneling-settings/split-tunneling-settings-route-object-model.ts
**Note: Must be merged after `refactor-split-tunneling`. Change base branch to `main` before merge.**
Add information in the Split tunneling view regarding Split tunneling being unsupported due to lack of `cgroup v1` support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8732)
=> Add information on Linux if Split tunneling is not supported

ios/MullvadVPN/Coordinators/Settings/APIAccess/Cells/SwitchCellContentView.swift
This PR guarantees that switches in API access methods are always fully displayed
Video demo
https://github.com/user-attachments/assets/c1c3e179-03dd-4151-a6c2-02b4cfe67ca6
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8800)
=> Set content compression to maximum for switches in API methods

ios/MullvadREST/Transport/Shadowsocks/ShadowsocksCacheCleaner.swift, ios/MullvadRESTTests/MullvadApiTests.swift, ios/MullvadRESTTests/ShadowsocksCacheCleanerTests.swift, ios/MullvadRustRuntime/MullvadApiContext.swift, ios/MullvadSettings/AccessMethodRepository.swift, ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/AppDelegate.swift, ios/MullvadVPNTests/MullvadVPN/TunnelManager/TunnelManagerTests.swift, ios/PacketTunnel/PacketTunnelProvider/PacketTunnelProvider.swift
This PR adds a new routine that will clear the shadowsocks cache when an API rotation occurs, and `Mullvad Bridges` was the last selected method. 
This only happens when the UI process is running to follow the same logic as decided with `AddressCache`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8799)
=> Add routine that clears shadowsocks caches on API rotation and failure

ios/MullvadVPN.xcodeproj/project.pbxproj, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionView.swift, ios/MullvadVPN/View controllers/AccountDeletion/AccountDeletionViewModel.swift
This PR removes the target from localization for unnecessary targets
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8812)
=> Remove unnecessary targets from iOS localization

Cargo.lock, Cargo.toml, mullvad-daemon/Cargo.toml, mullvad-problem-report/Cargo.toml, test/Cargo.lock, test/Cargo.toml, test/test-manager/Cargo.toml, test/test-runner/Cargo.toml
Very minor dependency upgrade. `dirs` seems to be unmaintained, given that the git repository is archived since February. But they have released a 6.0.0 release, which transitively upgrades the `windows-sys` dependency. This does not really help us much in practice. It neither removes, nor adds, any duplicate `windows-sys` version to our dependency tree. But just minor cleanup to use the latest version and get newer windows bindings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8832)
=> Make `dirs` a workspace dependency and upgrade to 6.0.0

Cargo.lock, mullvad-api/Cargo.toml, mullvad-api/src/version.rs, mullvad-daemon/src/version/check.rs, mullvad-update/src/version.rs, test/Cargo.lock
This PR is not ready to be merged. It needs to be manually tested first.
This PR replaces the use of the remaining uses of the old version check endpoint for the desktop app with the new one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8681)
=> Stop using old version check endpoint

desktop/packages/mullvad-vpn/src/renderer/lib/components/button/Button.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/button-icon/ButtonIcon.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/button-icon/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/button-text/ButtonText.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/button-text/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/button/components/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/icon-button/IconButton.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/icon-button/components/IconButtonIcon.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/icon-button/components/icon-button-icon/IconButtonIcon.tsx, desktop/packages/mullvad-vpn/src/renderer/lib/components/icon-button/components/icon-button-icon/index.ts, desktop/packages/mullvad-vpn/src/renderer/lib/components/icon-button/components/index.ts
Fix hover and active states for IconButton to check that data-disabled is actually set to true on an element, not just existing.
Also refactors IconButton and Button components to use new structure from our style guide and remove forwardRef.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8824)
=> Fix hover and active states for disabled IconButton component

Cargo.lock, mullvad-daemon/Cargo.toml, mullvad-daemon/src/migrations/mod.rs, mullvad-daemon/src/migrations/snapshots/mullvad_daemon__migrations__v11__test__v11_to_v12_migration_access_method_name_duplicates.snap, mullvad-daemon/src/migrations/v11.rs, mullvad-types/src/settings/mod.rs
- Renames `block_when_disconnected` to `lockdown_mode`
- Renames custom API access methods with non-unique names
- Adds snapshot testing with the `insta` crate
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8817)
=> Add v11 settings migration

ios/MullvadREST/Relay/RelaySelectorWrapper.swift
When both DAITA smart routing and multihop are enabled we add obfuscation to the exit list. This is not correct, it should show all relays.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8853)
=> Fix exit selection for multhihop and smart routing combination

.github/CODEOWNERS, .github/workflows/code-owner-approval.yml, .github/workflows/verify-locked-down-signatures.yml, code-owners.json
We have agreed to run a code ownership experiment during 2025-Q4. That's just around the corner and I see no reason to not start earlier. During the meeting we seemed to agree that some automation around making sure the relevant code owners have actually reviewed changes etc was important. So this PR adds that automation.
This is a workflow that runs on all PRs, and every time a new review is submitted to an existing PR. It checks what files the PR changes, and which teams' ownership file patterns it matches. Then it checks all reviews and matches the reviewer with what team they are in. I created new subteams for this purpose: @mullvad/appteam-desktop, @mullvad/appteam-ios and @mullvad/appteam-android.
This PR adds a code ownership mapping (`code-owners.json`). The intention is not that …
=> Add github actions workflow for enforcing code ownership approval

desktop/packages/mullvad-vpn/src/renderer/components/views/wireguard-settings/components/obfuscation-settings/ObfuscationSettings.tsx, desktop/packages/mullvad-vpn/test/e2e/installed/state-dependent/obfuscation.spec.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/daita-settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/multihop-settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/routes-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/shadowsocks-settings/index.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/shadowsocks-settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/shadowsocks-settings/shadowsocks-settings-route-object-model.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/udp-over-tcp-settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/vpn-settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/wireguard-settings/selectors.ts, desktop/packages/mullvad-vpn/test/e2e/route-object-models/wireguard-settings/wireguard-settings-route-object-model.ts
Fixes tests that broke during the implementation of quick access to feature settings and the refactors that were done related to that.
Fixes DES-2555
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8862)
=> Fix e2e tests after refactors when implementing quick access to feature settings

test/test-manager/src/tests/mod.rs, test/test-manager/src/tests/test_metadata.rs, test/test-manager/test_macro/src/lib.rs
Add a new attribute to the `test_function` macro: `skip`. If `skip` is set, the test will not be run by default.
This is useful if we want to check in test cases that are either expensive to run by default, or when we are stuck waiting for relay features to be rolled out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8855)
=> Add `skip` attribute to `test_function` macro

.github/workflows/code-owner-approval.yml
This is an attempt to fix an issue with the new code owner check workflow. It ran first on `pull_request` and failed obviously. Then it ran again on `pull_request_review` when the first review came in. The problem was that the runs count as different jobs, since they have different triggers. So even if the later succeeded, the former stayed in the status check as failed.
I'm trying to fix this by not triggering on the `pull_request` at all. This means the job will not run until the first review is submitted. But by adding this job to the branch protection ruleset, saying it *must* pass for a PR to be mergable, I think we still enforce it. This implicitly requires that any PR must have at least one review, but that makes sense.
I also renamed the workflow job name to a more logical name. …
=> Fix code owner double trigger

desktop/packages/mullvad-vpn/test/e2e/installed/installed-utils.ts
Override by setting environment variable TEST_START_BUILD=1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8873)
=> Allow to run state-dependent tests against current build using env

Cargo.lock, installer-downloader/CHANGELOG.md, installer-downloader/Cargo.toml
The only meaningful change since the last release is this PR: https://github.com/mullvad/mullvadvpn-app/pull/8680
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8859)
=> Bump Mullvad VPN loader version

ios/MullvadVPN/Views/StatusActivityView.swift
For some reason, on large accessibility sizes, the status image assets' intrinsic widths are doubled. Which doesn't affect the status image (which is centred), but wrought havoc with the spinner. This PR changes the spinner's width constraint to depend on its superview, fixing this issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8844)
=> Fix login spinner weirdness on large sizes

CHANGELOG.md, dist-assets/linux/after-install.sh
Allow the AppArmor profile to be installed on Linux distros that use AppArmor. Previously, we only installed the AppArmor profile that we do already provide on Ubuntu >=24.04. This change will install the AppArmor profile on all Linux distros with AppArmor, for example Linux mint as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8880)
=> Add AppArmor profile for Linux distros with AppArmor enabled

ios/MullvadREST/Relay/RelayPicking/MultihopPicker.swift, ios/MullvadREST/Relay/RelayPicking/SinglehopPicker.swift
Ways to reproduce:
- Turn on Link conditioner to 100% loss
- Set shadowsocks port to 1
- Select automatic obfuscation
- Select a relay without extra shadowsocks ip e.g. se-got-wg-002
- Click connect
- Expand the connection view
- In-IP will show :1 TCP eventually
After fix:
Test with e.g. se-got-wg-002, which is a relay that supports QUIC. The connection view should show TCP fallback with correct port (80 or 5001) for shadowsocks retry (since it's not supported), but not for other obfuscation methods (or .off).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8879)
=> Fix bug where relay pickers would mix obfuscations when creating relay configs

android/app/src/main/AndroidManifest.xml, android/tile/src/main/kotlin/net/mullvad/mullvadvpn/tile/MullvadTileService.kt
- Set category as toggleable
- Set title as the app name when active to align more with how other tiles look on newer versions of Android
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8876)
=> Improve the quick setting tile

Cargo.lock, mullvad-daemon/Cargo.toml, talpid-core/Cargo.toml, talpid-wireguard/Cargo.toml, talpid-wireguard/src/boringtun/mod.rs
if compiled with `--features pcap`, the daemon will create a unix socket when connecting with multihop, and dump all traffic to the exit peer on that socket. This is useful for debugging userspace multihop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8882)
=> Add a UDS for wiresharking gotatun multihop traffic 

.github/DISCUSSION_TEMPLATE/feature-requests-ideas.yml, .github/ISSUE_TEMPLATE/config.yml
This PR aims to change our workflow in terms of how we handle feature requests. Feature requests should no longer be "Issues" but rather Discussions.
We do this by:
- Moving the issue template into discussion template. 
- Remove the "I've searched for similar issues" since that is handled automatically by discussions.
- Add link in "New issue" to lead users wanting to post a feature request to the correct discussion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8907)
=> Migrate feature request issues to github discussions

ios/MullvadVPN/View controllers/Tunnel/ConnectionView/ConnectionView.swift, ios/MullvadVPN/View controllers/Tunnel/ConnectionView/HeaderView.swift
Now everything under the CONNECTED indicator is scrollable. 
As a bonus: the Country/City and Server info lines are truncated to one line when not expanded, but expand as needed if the view is scrollable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8884)
=> Move ConnectionView place/server indicators into scroll view

desktop/packages/mullvad-vpn/test/e2e/installed/state-dependent/login.spec.ts
The title that were previously checked is only visible for one second which leads to flakiness due to playwright sometimes not polling the expect during that second.
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/18274540322 :crossed_fingers: 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8968)
=> Remove test for login screen title when account is created

test/test-manager/src/tests/daita.rs
This makes `test_daita` not fail if first connection attempt fails
Test run: https://github.com/mullvad/mullvadvpn-app/actions/runs/18313376305
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/8985)
=> Fix reconnect check in tests
