- CHANGELOG.md
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/containers/AdvancedSettingsPage.tsx
- gui/src/renderer/redux/settings/actions.ts
- gui/src/renderer/redux/settings/reducers.ts
- gui/src/shared/ipc-event-channel.ts
I've added the RPC calls from the GUI to the Daemon to set the bridge state from the UI, and fleshed out the UI work that was already started for this feature. This allows the user to change the bridge mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/891)
> Add shadowsocks toggle to UI

- CHANGELOG.md
- gui/package-lock.json
- gui/package.json
- gui/src/main/index.ts
Git checklist:
This PR fixes the misplaced gray line rendered above the app window on macOS. The upgrade to Electron 4.2.3 was necessary due to some PRs that landed in the release and made it possible to workaround the issue.
v2019.4:
this patch:
Please make sure that you can quit the app by clicking the "quit" button in Settings, this is due to some internal workarounds that temporarily make window non-closable to be able to hide the traffic lights in titlebar.
Closes https://github.com/mullvad/mullvadvpn-app/issues/541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/894) …
> Fix gray line defect

- CHANGELOG.md
- talpid-core/src/dns/linux/systemd_resolved.rs
The way the daemon detects `systemd-resolved` has been improved. Previously, we'd only detect a single mode of operation, whereas now we detect all 3 active modes of operation. This is because we only checked for a single symlink path for `/etc/resolv.conf`, but there can be two.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/896)
> Fix systemd-resolved resolv.conf detection

- talpid-core/src/process/openvpn.rs
- talpid-core/src/tunnel/openvpn.rs
During debugging my woes with Shadowsocks, it became very obvious that whilst refactoring the proxy settings out of the tunnel settings, the code that would set the proxy parameters for OpenVPN got removed. This PR adds back the setter for proxy settings and sets the proxy settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/897)
> Actually set proxy parameters

- Cargo.toml
We should check what effects this has on build time and size of the result on macOS and Windows as well before we go ahead with anything like this. But some (very statistically unsecure) numbers point to strict improvements for Linux.
My numbers on current master branch doing `./build.sh --dev-build` after a `cargo clean`:
```
68M	dist/MullvadVPN-2019.4-dev-3e9d2fcf_amd64.deb
69M	dist/MullvadVPN-2019.4-dev-3e9d2fcf_x86_64.rpm
4.5M	dist-assets/mullvad
17M	dist-assets/mullvad-daemon
6.5M	dist-assets/problem-report
real	16m49.443s
user	27m20.172s
sys	0m31.170s
```
Same test as above, but with this LTO + opt-level change:
```
66M	dist/MullvadVPN-2019.4-dev-3e9d2fcf_amd64.deb
68M	dist/MullvadVPN-2019.4-dev-3e9d2fcf_x86_64.rpm
2.7M	dist-assets/mullvad
13M	dist-assets/mullvad-daemon
5.2M …
```
> Activate LTO and size optimization

- gui/package-lock.json
- prepare_release.sh
Run `npm install` after updating the version in `package.json` in order to make npm sync the version in `package-lock.json`. Does this have any downside? I see on master `npm install` also changes some other stuff, but I'm not sure if that's because the master lockfile is out of sync or if `npm install` usually upgrade dependencies.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/889)
> Make prepare_release.sh sync the version in package-lock.json

- gui/src/main/daemon-rpc.ts
- gui/src/shared/daemon-rpc-types.ts
- mullvad-cli/src/cmds/status.rs
- talpid-core/src/tunnel/openvpn.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-types/src/net/mod.rs
- talpid-types/src/net/openvpn.rs
- talpid-types/src/net/proxy.rs
- talpid-types/src/net/wireguard.rs
I've added a `bridge` field to `TunnelEndpoint` so that we can provide information about bridges to our user interfaces. I've updated the GUI schemas and I've made the CLI print the status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/900)
> Add bridge status to CLI

- Cargo.toml
Enabling LTO optimizations break builds on Windows. For now, reverting the LTO optimizations is the easiest fix. I suspect that the underlying issue is the fact that we don't compile `openssl` with LTO flags, or maybe some other statically linked dependency is not compiled appropriately. But it's somewhat telling that the daemon seemingly fails during around the time it would try to load TLS certs for HTTPS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/902)
> Revert "Activate LTO and size optimization"

- README.md
- gui/src/main/daemon-rpc.ts
- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/ConnectionInfo.tsx
- gui/src/renderer/components/ConnectionInfoDisclosure.tsx
- gui/src/renderer/components/TunnelControl.tsx
- gui/src/renderer/redux/connection/reducers.ts
- gui/src/shared/daemon-rpc-types.ts
- gui/test/components/NotificationArea.spec.tsx
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/relays.rs
- mullvad-types/src/location.rs
I've updated the GUI to show more information about the current tunnel - it now shows the tunnel type, a bridge type if there is one, the bridge entry IP if a bridge is used, and the bridge hostname. Showing the bridge hostname required some changes in the daemon - namely sending the bridge hostname and keeping track of the previously selected bridge relay. The extra information shown requires the `TunelControl`'s top margin to be decreased to squeeze in another line to display the tunnel and bridge types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/903)
> Show bridge info in GUI

- CHANGELOG.md
- gui/src/main/index.ts
- mullvad-problem-report/src/main.rs
If people are having frontend issues they sometimes can't send problem reports via the GUI. Then they need to either manually find all the logs, or they need to use the CLI problem report tool. The problem with the tool is that it does not include the frontend logs automatically. Since the user is having frontend issues that's usually the logs we need in that situation, so it becomes a bit useless. This PR tries to automatically find and include the frontend logs in problem reports even when ran directly from a terminal.
I also added some helpful output from `problem-report collect` to help the user understand what happens and to understand the next step they need to take.
I have so far only tested this on Linux myself.
Git checklist:
--- …
> Problem report automatically include frontend logs

- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/shared/daemon-rpc-types.ts
Richard brought up a couple of issues around naming in the GUI:
- the advanced setting _Shadowsocks bridge_ actually sets the bridge state. Calling it _Shadowsocks_ could lead the user into thinking that forcing it _on_ would imply that shadowsocks would be used, which wouldn't be the case if the user had set custom bridge settings.
- the line that informs the user about what protocols are being used in the tunnel would just say _Custom_ for the bridge part when custom bridge settings were used, .i.e. _OpenVPN via Custom_. This isn't all too clear, so it has been changed to _OpenVPN via custom bridge_.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/904)
> Improve naming w.r.t. bridges in the GUI.

- gui/src/renderer/app.tsx
Currently, the bridge state controls in the GUI won't be initialized or updated from the GUI settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/905)
> Update bridge state when new settings are published in GUI

- android/build.gradle
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
- mullvad-jni/src/into_java.rs
- talpid-core/build.rs
- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-core/src/tunnel/wireguard/ping_monitor.rs
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
This PR implements Wireguard support on Android. To do so, it uses the binaries that have been recently uploaded to `mullvadvpn-app-binaries`, and also retrieves the underlying sockets so that their packets can bypass the tunnel set-up by Android. The `ping_monitor` was also updated so it could be executed on Android.
The first two commits of this PR include fixes that were supposed to be included in previous PRs.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/899)
> Enable Wireguard on Android

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/lib.rs
Previously, the Connect screen would always start showing the "Disconnected" state and only change when the daemon sends a tunnel state change event. However, that meant that if the user is connected and left the app and then returned to it, it would incorrectly show the current state as "Disconnected".
This PR changes that so that every time the Connect screen is created it fetches the current tunnel state. Priority is still given to tunnel state change events, so if a state transition event is received at the same time the fetch initial state job is scheduling to update the screen, the operations are synchronized so that either the view is updated to the event state (and the fetch job doesn't schedule a view update) or the view is updated to the fetched state first but then updated …
> Fetch the current tunnel state when Connect activity resumes

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/LocationInfo.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/GeoIpLocation.kt
- android/src/main/res/layout/connect.xml
- android/src/main/res/values/strings.xml
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/into_java.rs
- mullvad-jni/src/lib.rs
This PR implements showing the current location in the Connect screen on Android. To prevent lag, now the connect screen anticipates changing to the disconnecting tunnel state. Because when disconnecting the connection is blocked (well, actually it's more that there's an offline period while the tunnel is being teared down), the real location is cached when possible to prevent querying the API for a location when we know it will take a while or fail.
A `LocationInfo` helper class is responsible for fetching, caching and updating the UI when appropriate.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/911)
> Show current location in the Connect screen on Android

- gui/locales/messages.pot
- gui/src/renderer/components/NotificationArea.tsx
- mullvad-cli/src/cmds/status.rs
I've added an appendix to the message that's shown to the user when the daemon enters the blocked state due to a failure to set firewall rules to inform Linux users that their kernel might be terribly outdated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/916)
> Improve Linux specific message about firewall errors

- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/src/offline/linux.rs
Bumps the netlink dependency to use another branch which has been freshly forked off of the master. The changes made to the `netlink-packet` crate make it so that it no longer expects kernel defined data structures of a certain length inside netlink messages. This is expected to greatly increase stability of the daemon, as we should panic less often when running on kernels the library wasn't built for.
The changes can be seen [here](https://github.com/little-dude/netlink/compare/master...mullvad:remove-dependence-on-kernel-structures).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/917)
> Use patched netlink libraries to be more kernel agnostic

- android/src/main/kotlin/net/mullvad/mullvadvpn/model/Relay.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt
- mullvad-daemon/src/relays.rs
- mullvad-jni/src/into_java.rs
Previously, the Android app would show all relays, even though it only supports Wireguard relays. This PR changes the UI to filter out non-Wireguard relays and locations and updates the relay selection code in the daemon to prefer Wireguard relays on Android.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/919)
> Limit Android app to Wireguard relays

- talpid-core/src/offline/linux.rs
I've changed the linux offline check so that if/when the nelink connection used to listen for changes does fail, it would fail into an online state. This way, even if we do fail, we fail open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/918)
> Let Linux offline check fail into an online state

- android/src/main/kotlin/net/mullvad/mullvadvpn/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/LoginFragment.kt
- android/src/main/res/layout/account.xml
- android/src/main/res/values/strings.xml
This PR adds a logout button to the Account settings screen. The button clears the account number configured in the daemon, and returns to the login screen while clearing the back stack.
The login screen was also updated to refetch the settings from the daemon so that it includes the new account number.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/923)
> Log out button on Android

- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListAdapter.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListListener.kt
- android/src/main/res/anim/fade_in.xml
- android/src/main/res/anim/fade_out.xml
- android/src/main/res/layout/select_location.xml
- mullvad-jni/src/jni_event_listener.rs
This PR introduces a `RelayListListener` helper class that listens for relay list update events from the daemon. It is used for providing the relay list information to the `RelayListAdapter`. The adapter was changed to start empty and support relay list updates. The Select Location screen can then use these changes to show a spinner when the relay list is empty (i.e., while it hasn't been downloaded yet), and show the relay list as soon as it becomes available.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/925)
> Listen for relay list updates

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/LocationInfo.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/LocationInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/RelayListListener.kt
This PR started out as an attempt to reduce the number of fetches to get the current location information. In order to do so, I decoupled it from the Connect fragment, so that it is cached in a `LocationInfoCache` helper class while the activity is running. While doing so, I also reorganized and cleaned up some code, moving all classes that proxy data between the UI and the daemon thread to a separate `dataproxy` package.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/926)
> Cache location info

- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectivityListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/lib.rs
Previously, the app would crash if connecting right after a disconnect. It would only do so without crashing if the user waited about 4-5 seconds between attempts. This happens because it is taking some time for the VPN tunnel to be disabled by Android. The cause of this issue is not yet known, but this PR implements a mitigation.
A new `ConnectivityListener` helper class was created to listen for connectivity status changes. A `vpnDisconnected` `Deferred` job is used to notify when the VPN tunnel is finally disconnected. An external class can then simply do `vpnDisconnected.await()` to block while the VPN tunnel is connected.
`MullvadVpnService` then uses the `ConnectivityListener`, and blocks creating a new tunnel until the previous VPN tunnel is disconnected.
Two other changes are also …
> Improve connectivity

- android/src/main/kotlin/net/mullvad/mullvadvpn/AccountFragment.kt
- android/src/main/res/layout/account.xml
- android/src/main/res/values/strings.xml
This PR makes the account number row clickable in the Account screen. When it is clicked, the account number is copied to the clipboard, and a toast message is shown.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/931)
> Allow copying account number to clipboard

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConfirmNoEmailDialogFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ProblemReportFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt
- android/src/main/res/drawable/dialog_background.xml
- android/src/main/res/layout/confirm_no_email.xml
- android/src/main/res/values/strings.xml
This PR extends the Problem report screen so that when the user tries to send a report with no email to reply to, a confirmation dialog is shown. The `MullvadProblemReport` class is used to hold a `confirmNoEmail` field used by the dialog to notify the user's selection back to the `ProblemReportFragment`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/937)
> Add "Confirm no email" dialog

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SwitchLocationButton.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/Relay.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItem.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt
This PR updates the Connect screen slightly so that the "Switch location" button behaves as in the desktop app. Now, when disconnected the button will show the currently selected location, and will only show "Switch location" when connected.
In order to show the same information as the desktop app, the city name was added to the `Relay` class.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/939)
> Show selected location on "Switch location" button

- android/src/main/kotlin/net/mullvad/mullvadvpn/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/LaunchFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/LoginFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/RemainingTimeLabel.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/RelayListListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/SettingsListener.kt
- mullvad-jni/src/jni_event_listener.rs
This PR fixes a bug that was happening because of a sequence of events.
1. The first relay list fetch returned an empty list;
2. When the fetch finished, an attempt was made to find the relay item that matches the configured relay constraints;
3. Since the list was empty, the selected relay item was set to `null`;
4. The setter for that field would recalculate the relay constraints, setting it to `Any`;
5. When a non-empty relay list was received, the search for the selected relay would always be `null`, since the constraint was set to `Any`.
The fix was to simply ignore the initial fetch if it resulted in an empty relay list.
Git checklist:
--- …
> Fix country not being selected on first run

- Cargo.lock
- mullvad-problem-report/Cargo.toml
- mullvad-problem-report/src/lib.rs
On Android, the GUI logs messages to Android's default "logcat" (a syslog equivalent). A `logcat` command can be used to access it. Running it without special privileges limits access to the logs of the current process, so this should keep out any sensitive data from other processes.
This PR changes `mullvad-problem-report` so that on Android it runs the `logcat` command to generate a file with the log contents and include it in the problem report.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/935)
> Include logcat in collected problem report logs

- Cargo.lock
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/shared/daemon-rpc-types.ts
- mullvad-cli/src/cmds/status.rs
- mullvad-cli/src/cmds/tunnel.rs
- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/wireguard.rs
- mullvad-ipc-client/src/lib.rs
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/jni_event_listener.rs
- mullvad-jni/src/lib.rs
- mullvad-types/src/lib.rs
- mullvad-types/src/wireguard.rs
This PR changes the daemon to generate wireguard keys automatically in case the currently selected account does not have a key. A key will be generated and the daemon will repeatedly attempt to publish it to our API until it fails because the account already has enough keys or it succeeds. In any case, the daemon then publishes a key event signalling whether the key generation was a success or not to all the daemon event subscribers. 
Since the API can fail in distinct ways, the CLI is also updated to display the key generation result somewhat more appropriately.
As far as the GUI goes, I've only updated the schema so that a key event wouldn't crash it. But further integration will come soon.
--- …
> Automatic wireguard keys

- mullvad-jni/src/into_java.rs
- mullvad-jni/src/jni_event_listener.rs
- mullvad-jni/src/lib.rs
This PR removes Java local reference leaks that would eventually lead to a full local reference frame, causing the thread to crash. There were basically two types of leaks:
1. Leaking of objects created and sent to the `MullvadDaemon` instance listener methods;
2. Leaking of `Class` instances when creating `jni::objects::JList`.
The first cause was fixed by wrapping the objects in an `AutoLocal` before sending them to the `MullvadDaemon` object.
The second cause is actually inside the `jni` crate, so a pull request was opened upstream ([#190](https://github.com/jni-rs/jni-rs/pull/190)). Until the fix is integrated and a new version released, this PR
works around the issue by not using `JList`.
Git checklist:
--- …
> Fix `JniEventListener` crash after running for a while

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/ConnectionProxy.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/LocationInfoCache.kt
This PR moves the connection handling code to a new `ConnectionProxy` helper class, so that it's not specific to the `ConnectFragment`. This is then used to allow the `SelectLocationFragment` to request a connection when a location is selected.
When moving around the code to change the UI before an actual state is received, it became hard to do it the same way, so the state had to be split in two. There's the "real state" that comes from the daemon, and the "UI state" that anticipates the real state based on the requests started from the UI.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/940)
> Connect when selecting location

- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/ConnectionPanel.tsx
- gui/src/renderer/components/ConnectionPanelDisclosure.tsx
- gui/src/renderer/components/TunnelControl.tsx
- gui/src/renderer/containers/ConnectPage.tsx
- gui/src/renderer/containers/ConnectionPanelContainer.tsx
- gui/src/renderer/redux/userinterface/actions.ts
- gui/src/renderer/redux/userinterface/reducers.ts
Git checklist:
* [X ] Check that commits follow the [Mullvad coding guidelines](https://github.com/mullvad/coding-guidelines)
A bit of tech debt was accumulated when more and more props were added to the React components. This PR refactors the `ConnectionInfo` into a container directly connected to Redux to avoid passing props all the way down from `Connect` -> `TunnelControl` -> `ConnectionInfo`. I think we should do the same with `TunnelControl` and `NotificationArea`. This would make the top level components less heavy on props.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadv …
> Refactor connection panel into container

- CHANGELOG.md
- gui/locales/messages.pot
- gui/src/main/gui-settings.ts
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/Preferences.tsx
- gui/src/renderer/containers/PreferencesPage.tsx
- gui/src/renderer/redux/settings/reducers.ts
- gui/src/shared/gui-settings-state.ts
- gui/src/shared/ipc-event-channel.ts
Git checklist:
This PR adds a switch to turn off system notifications. Only tunnel notifications are suppressed, the rest of critical notifications like updates, inconsistent version etc.. will be displayed anyway. To turn off notifications completely, users can switch them off in the OS settings I suppose. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/946)
> Add notification settings

- talpid-core/Cargo.toml
I've added another commit to our changes to the netlink library to further remove kernel structs.
https://github.com/mullvad/netlink/commit/b367ac9c012e6c2a5e065e201384ec20d9708109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/950)
> Use newer commit for netlink libraries

- talpid-core/src/tunnel/wireguard/wireguard_go.rs
Updating wireguard-go to `v0.0.20190518` and adjusting `talpid-core` to link a different function for Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/951)
> Update wireguard-go to  v0.0.20190518

- gui/src/main/gui-settings.ts
Git checklist:
Seems like I've omitted the `typeof` keyword which caused the notification setting being reset on each launch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/954)
> Fix a bug in the notifications configuration loading

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/ConnectionProxy.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/LocationInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/TunnelState.kt
- mullvad-jni/src/into_java.rs
This PR changes the `LocationInfoCache` to use the relay location that's included in the tunnel state change event when possible. This removes the location fetch when the app is in the `connecting` state, and anticipates the location when in the `connected` state. However, in the `connected` state the relay out address isn't available, so the fetch has to be kept.
The `TunnelState.Connecting` class representation allows the location to be `null`. This is similar to the desktop UI, because when anticipating a state change without waiting for the appropriate event to arrive, there is no relay information yet.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn- …
> Use relay location included in tunnel state broadcast on Android

- android/src/main/kotlin/net/mullvad/mullvadvpn/model/TunnelState.kt
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/shared/daemon-rpc-types.ts
- mullvad-daemon/src/lib.rs
- mullvad-types/src/states.rs
This PR fixes a bug introduced in a recent PR, where using custom tunnels would cause the daemon to crash when broadcasting tunnel state changes. The daemon was assuming that there would always be a relay location set when reaching the `connecting` or `connected` states, but that's not true for custom tunnels.
The fix was to allow the relay location to be wrapped in an `Option` type, so that it may or may not be present. The code for the GUI was updated to handle the change.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/957)
> Make relay location parameter in tunnel state broadcast optional

- mullvad-problem-report/src/lib.rs
- mullvad-problem-report/src/metadata.rs
- mullvad-rpc/src/lib.rs
Follow up to #960 from yesterday. Now adding a test making sure the parsing code works on a newly serialized version. And that the metadata collection seems idempotent, except for the `id` field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/961)
> Add metadata parse test

- CHANGELOG.md
- dist-assets/pkg-scripts/postinstall
Support asked if we can make the CLI easier to find. So not every guide have to start with how to find/run it. This PR solves that for macOS specifically. We create a symlink to our two CLI tools in `/usr/local/bin`. From what I have gathered online this path should be in all users default `PATH` *but* the directory itself might not exist. So we should hopefully be good if we try to create it and then add the symlinks.
I'll make sure to test this on an untouched macOS computer before merging. But can have it reviewed now.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/964)
> Make symlinks in /usr/local/bin

- gui/src/renderer/components/AdvancedSettings.tsx
Quite a few users misunderstand the "Block when disconnected" setting. They activate it and then don't understand why their internet "breaks" when they disconnect/quit Mullvad. This improved version of the text was written some time back.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/966)
> Improve help text shown around "Block when disconnected"

- CHANGELOG.md
- gui/src/config.json
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/main/notification-controller.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/components/WireguardKeysStyles.tsx
- gui/src/renderer/containers/AdvancedSettingsPage.tsx
- gui/src/renderer/containers/WireguardKeysPage.tsx
- gui/src/renderer/redux/settings/actions.ts
- gui/src/renderer/redux/settings/reducers.ts
- gui/src/renderer/routes.tsx
- gui/src/shared/ipc-event-channel.ts
- mullvad-daemon/src/lib.rs
This PR adds a new settings page for managing WireGuard keys. This allows the user to manually generate and verify their keys with our API. The user will be able to verify if previously generated key is valid, and re-generate one if it isn't. If key generation fails because their account has too many keys already, the user will be shown a button that takes him to the website. If the app window is closed when automatic key generation fails, a notification will be shown. The notification support is a bit crude as they won't take the user to the appropriate key management screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/965)
> Add GUI page for managing WireGuard key

- Cargo.lock
- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/relays.rs
- talpid-core/Cargo.toml
While looking at something completely unrelated I saw the `self.tx.lock().unwrap()`  in our management interface code. I first thought to replace the `unwrap` with an `expect` in order to introduce better error messages. But I then realized I could just "upgrade" to `parking_lot` and get rid of poisoning altogether. We only lock this lock in a single place anyway and just call a single method on the `Sender`.
When I added the dependency anyway I made sure to change the remaining synchronization primitives in `mullvad-daemon` to use `parking_lot` as well. Simplified a few things.
Unrelated to the Mutex change, I also managed to get rid of one layer of boxing in most management interface calls. `send_command_to_daemon` boxed its return value, but most callees did some operation on the …
> Upgrade locks

- gui/src/renderer/transitions.ts
Add transition rules for wireguard keys page so that the transition to said page is animated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/972)
> Add transition rule for wireguard-keys page

- CHANGELOG.md
- mullvad-cli/src/cmds/bridge.rs
The CLI command `mullvad bridge set state` caused a panic. Because the argument to this subcommand was not marked as required, but we `unwrap` it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/973)
> Fix cli panic

- build.sh
Building the app installers takes a long time. A pretty large part of that time is spent compressing the installers. Especially on Linux. For dev builds we don't really need compression, and can shave something like 40% off of the deb/rpm compression time without it.
I enable this only when the build script is invoked with an explicit `--dev-build`. This so all non-release builds on the build servers will still have full compression. We don't need/want them to produce larger installers. They have plenty of spare time. It's mostly for improving local dev-test iteration speed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/977)
> Make build.sh disable compression on --dev-build builds

- CHANGELOG.md
Err. Forgot this when updating the submodule :/
I'm aware this is not yet completely true for all platforms. But I assume we will be able to build the OpenSSL libraries for Windows before the release comes.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/974)
> Add forgotten changelog entry about upgrading Open{SSL,VPN}

- gui/package-lock.json
During our build I still saw npm complaining about vulnerabilities even after #975. Seems like `npm` uses a different database for known vulnerabilities compared to github. Running `npm audit fix` resulted in the following diff. I have tried it on Linux and macOS and it works. Seems pretty innocent of an upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/976)
> Upgrade vulnerable npm dependencies

- gui/src/renderer/containers/ConnectPage.tsx
We properly translated the "switch location" button in all cases except when a specific hostname was selected as the location constraint. Then we forgot to translate the city. This PR fixes that.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/979)
> Translate city on switch location button

- .travis.yml
- README.md
- android/build.gradle
- dist-assets/windows/installer.nsh
- env.bat
- env.ps1
- env.sh
- gui/electron-builder.yml
- talpid-core/build.rs
- windows/nsis-plugins/src/cleanup/cleanup.vcxproj
- windows/nsis-plugins/src/driverlogic/driverlogic.vcxproj
- windows/nsis-plugins/src/log/log.vcxproj
- windows/nsis-plugins/src/registry/registry.vcxproj
- windows/nsis-plugins/src/tray/tray.vcxproj
This PR updates the `mullvadvpn-app-binaries` submodule to the new version which uses target triplets as the names of the directories of the binaries for each platform. This prepares the app to support the same operating system on multiple architectures.
In order to support the new paths, the build scripts have been updated. The `*.vcxproj` files were updated using `sed`, to simply use the new path for the Windows binaries.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/978)
> Use binaries in target triplet directories

- .travis.yml
- README.md
This PR tweaks the Android build in Travis CI so that it matches the steps outlined in the README. The steps also have been updated so that the API target is downgraded in order to support more devices.
More specifically, the NDK version used was bumped from `r19b` to `r20`, and the target platform to build the binaries from API version 28 to API version 21.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/980)
> Update Android build in Travis

- .gitignore
- README.md
- android/build.gradle
- android/proguard-rules.pro
- build-apk.sh
This PR creates a script to help build the Android APKs. The script will automatically build `mullvad-jni` for all supported ABIs, and copy the resulting shared library along with `libwg.so` to a directory where Gradle can pack them into the APK. The final APK is then copied to the `dist` directory with the version name.
The `README` was updated to describe how to set-up the environment for all supported ABIs and to use the script.
The script supports building development builds using `--dev-build`. These are built faster and are automatically signed with a debug key, making the development process simpler. The generated APKs have a `-debug` suffix.
In order to build a "release" APK, it has to be signed. This is done automatically, as long as the signing keys are configured according to …
> Create build script for Android release builds

- CHANGELOG.md
- mullvad-cli/src/cmds/mod.rs
- mullvad-cli/src/cmds/reset.rs
- mullvad-daemon/src/account_history.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-ipc-client/src/lib.rs
- mullvad-types/src/settings.rs
Add CLI command to remove daemon settings, clear the cache and logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/983)
> Add reset command

- talpid-core/src/tunnel/wireguard/wireguard_go.rs
This PR is a simple fix for a memory alignment issue on 32-bit platforms. It replaces a cast to `i64` with a cast to `isize`, which maps correctly to the expected `int` Go type in `wireguard-go`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/989)
> Fix crash on 32-bit platforms when opening Wireguard tunnel

- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/lib/relay-settings-builder.ts
- gui/src/renderer/redux/settings/reducers.ts
- gui/src/shared/daemon-rpc-types.ts
- gui/test/relay-settings-builder.spec.ts
- mullvad-cli/src/cmds/relay.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/relays.rs
- mullvad-jni/src/from_java.rs
- mullvad-types/src/relay_constraints.rs
- mullvad-types/src/settings/migrations/mod.rs
- mullvad-types/src/settings/migrations/v1.rs
- mullvad-types/src/settings/mod.rs
To better support different tunnel protocols, the daemon should be capable of storing the tunnel specific constraints in a persistent fashion. This PR achieves that with a non-backwards-compatible settings file format change. As such, this PR also implements a simple migration from the old format to the new one.
Whilst the settings schema has changed, none of the user facing tools are aware, they will be updated in the following PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/982)
> Persistent tunnel constraints

- android/build.gradle
- android/src/main/AndroidManifest.xml
This PR updates the Android application label, so that in the Android Settings app, the app name is actually `Mullvad VPN` instead of `net.mullvad.mullvadvpn`.
The version information of the app was also updated.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/990)
> Update Android app metadata

- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/KeyStatusListener.kt
- mullvad-jni/src/lib.rs
This PR is a minor UX improvement. If the user has too many keys registered to his account, he currently has to go to the web-site to revoke some keys. After doing so, when he returns the app it would previously still think there are too many keys, so the user would have to log out and log in again for the changes to take effect.
This PR implements automatic retries to generate the WireGuard key if it had previously failed because there were too many keys. The retries occur every time the app is resumed, so this aligns with the user returning to the app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/991)
> Automatically retry key generation when Android app resumes

- mullvad-daemon/src/relays.rs
- mullvad-types/src/relay_constraints.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
This PR changes the `Default` implementation of `RelayConstraints` on Android so that the `tunnel_protocol` is configured to only support Wireguard. This fixes the issue where the app tried to connect to OpenVPN relays.
This PR also removes some `cfg` attributes that aren't necessary anymore.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/992)
> Fix default relay constraints on Android

- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/disconnecting_state.rs
This PR handles the newly introduced `-2` error code returned from `wireguard-go` by retrying to connect. In order to do so in a clean manner, it now enters the `Disconnecting` state but without providing the tunnel close handle. Therefore, this PR changed the tunnel state machine so that the `Disconnecting` state uses an optional tunnel close handle and tunnel close event receiver.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/993)
> Retry to connect when WireGuard encounters a bad file descriptor

- android/src/main/res/layout/connect.xml
- android/src/main/res/layout/relay_list_item.xml
- android/src/main/res/layout/select_location.xml
- android/src/main/res/layout/settings.xml
This PR does some minor changes to the UI. The most noticeable change is that the active touch areas of some buttons has increased to improve the UX. But it also fixes an alignment issue with the relay status indicator icon.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/995)
> Android UI tweaks

- android/src/main/kotlin/net/mullvad/mullvadvpn/LocationInfo.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/LocationInfoCache.kt
With the crash in `wireguard-go` mitigated and the `ConnectivityListener` removed, disconnection happens a lot faster. Sometimes, it happens in less than a single UI frame (less than 16 ms). In these cases, the UI would skip handling the `Disconnecting` state and skip directly to the `Disconnected` state.
The problem is that the `LocationInfoCache` was relying on the `Disconnecting` state to update the UI to show the last known real location. So when disconnection happens too quickly the location isn't updated, and the UI keeps showing the tunnel location for a few seconds until the RPC call to get the real location finishes.
This PR removes the delay by setting the UI location to the last known real location also when entering the `Disconnected` state.
Also in this PR is a slight cleanup …
> Fix UI delay when disconnecting too quickly

- android/src/main/res/layout/login.xml
Even though the account input view was configured to only accept numbers, it could still accept number related characters, like `-`, `.` and `,` (to enter for example `-1,000.00`). This PR adds a further restriction so that the input only accepts digits (`0-9`).
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/999)
> Only allow number digits in account input

- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SettingsFragment.kt
- android/src/main/res/drawable/icon_extlink.xml
- android/src/main/res/layout/settings.xml
- android/src/main/res/values/strings.xml
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/lib.rs
This PR adds the `App version` entry in the `Settings` screen on Android. The version is obtained from `mullvad-daemon`. When the entry is pressed, it opens the web page to download the app. This might need to be revisited in the future, maybe opening the link to the app on Google Play.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1000)
> Show version in Settings

- gui/src/renderer/app.tsx
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/AdvancedSettingsStyles.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/components/WireguardKeysStyles.tsx
- gui/src/renderer/containers/AdvancedSettingsPage.tsx
- gui/src/renderer/lib/relay-settings-builder.ts
- gui/src/renderer/redux/settings/reducers.ts
This PR updates the GUI to allow the user to specify a tunnel protocol constraint on MacOS and Linux. Depending on the selected tunnel protocol constraint, different tunnel constraint options are shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/997)
> Allow setting TunnelProtocol constraint from GUI

- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoFetcher.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/AppVersionInfo.kt
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/into_java.rs
- mullvad-jni/src/lib.rs
This PR implements the periodic version check that's also present in the desktop app. The `AppVersionInfoFetcher` runs once a day and retrieves the version information. This information isn't used yet, as the UI will handle it in a separate PR.
The fetcher class is handled by the `MullvadVpnService` so that it can run in the background without depending on the activity running.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1003)
> Periodically check for new Android version

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/NotificationBanner.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoFetcher.kt
- android/src/main/res/drawable/icon_alert.xml
- android/src/main/res/drawable/icon_notification_warning.xml
- android/src/main/res/layout/settings.xml
- android/src/main/res/values/colors.xml
- android/src/main/res/values/strings.xml
This PR implements UI feedback for when the app detects there's a new version available. The `AppVersionInfoCache` is responsible for reading the version information that's stored by the `AppVersionInfoFetcher` and comparing it with the current version in order to determine additional information.
The "App version" settings entry can now show when there's a newer version. The "Connect" screen can show a notification for a newer version. Two notifications exist, one for a simple upgrade (shown as a warning) and one where the user is informed that the current version isn't supported anymore (shown as an error).
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvp …
> Show notification for new app versions

- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SettingsFragment.kt
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/lib.rs
This PR implements the behavior that pressing the "Quit" button will also request the background service (running the daemon thread) to stop. Previously the service would continue running indefinitely.
Due to some weird Android behavior related to services, the service only stops after the daemon thread has finished. Therefore, this fix required implementing a way for the UI to notify the service that it should stop (and shutdown the daemon thread). Otherwise, just calling `context.stopService(...)` wouldn't actually do anything.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1007)
> Fix "Quit" button not stopping the background service

- mullvad-types/src/settings/migrations/mod.rs
- talpid-core/src/dns/linux/static_resolv_conf.rs
There's an issue on barebones Debian installs where our DNS config doesn't last a lot longer than a day. I suspected this was because of DHCP clients overwriting `/etc/resolv.conf` occasionally. Whilst the daemon was checking for tools that would edit the file directly, the daemon wasn't checking for the file being swapped in place `mv /etc/resolv.conf.staging /etc/resolv.conf`, which is what `dhclient` does on Debian. I've improved changed the code to listen for all the changes in `/etc/` and only react to changes that affect `/etc/resolv.conf`, which does allow us to catch more filesystem events.
And I've also included a small formatting fix for `mullvad-types`.
--- …
> Linux - improve static file DNS management resiliency against DHCP clients.

- gui/src/renderer/components/AdvancedSettings.tsx
Since OpenVPN tunnel constraints will be taken into account even when using automatic relay selection, they should always be shown in the settings, so this PR enables this behavior. Once we start selecting WireGuard relays with automatic relay selection, then we should show those settings all of the time as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1010)
> Show OpenVPN tunnel constraints options all of the time

- mullvad-types/src/auth_failed.rs
Bumping the binaries submodule to get newer OpenSSL on Windows (1.1.1c) and a non-crashing version of wireguard-go for MacOS - v0.0.20190805.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1014)
> Bump binaries submodule

- CHANGELOG.md
- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
This PR updates the tunnel state machine to retry to connect when some known WireGuard issues occur. The two errors right now are when a bad file descriptor is provided to `wireguard-go` and when bypassing the tunnel socket on Android fails.
I added a new `StartTunnelResult` type to help with the `cfg` specific error handling in order to not have to repeat the retry code. Hopefully, this new type can implement the `Try` trait when it becomes stable, and the `ConnectingStart::start_tunnel` method can return it directly.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1012)
> Retry after specific WireGuard connection errors

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
This is a minor bug-fix for a race condition where the current version is known before the next update version. When that happens, the `target` variable would be `null`, which is always different than the current version, and the new version banner would appear. This happens only on the first run after installation.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1015)
> Fix initial version fetch race condition

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/ConnectionProxy.kt
This is a small fix for the "Cancel" button not working immediately after entering the "Connecting" state. This was happening because the `ConnectionProxy` class was using the state from the daemon thread to filter out repeated commands. This meant that when a `Connect` command was sent, it took a while before the daemon actually changed into the "Connecting" state, but the UI would already have shown the "Cancel" button. If it was pressed, it wouldn't work until the daemon thread entered the "Connecting" state.
The fix was to use the `uiState` instead of the daemon thread state, which then allows sending the "Disconnect" command right after the "Connect" command before the daemon actually entering the "Connecting" state.
Git checklist:
--- …
> Use UI state for action anticipation check

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SwitchLocationButton.kt
- android/src/main/res/layout/connect.xml
- android/src/main/res/values/dimensions.xml
- android/src/main/res/values/styles.xml
This PR changes the "Switch location" button to detect when the text it contains doesn't fit. It will then attempt to expand the button to fit two lines. If a third line is necessary, the text will be ellipsized.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1017)
> Allow "Switch location" button to grow taller

- mullvad-problem-report/src/metadata.rs
This PR changes slightly the Android system information present in the problem report. The idea is to make it clearer what version of Android it is and what ABI it's running on.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1018)
> Include Android version and ABI list in report

- ci/buildserver-upload.sh
When I was gone the upload script failed. All builds still worked, but they were not uploaded. Now when I started it all installers got the mtime of when they were uploaded. I found we can simply add `-p` to `scp` to make it persist them, making the metadata about the installers slightly better.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1021)
> Preserve mtime and other metadata when uploading installers

- mullvad-daemon/src/relays.rs
- mullvad-types/src/relay_constraints.rs
The extra tunnel protocol constraint I introduced a couple of weeks ago was not implemented as far as relay selection goes. The couple of subtle bugs that I did introduce are rectified with this PR.
The underlying issue was that the relay filtering code assumed that if any tunnel protocol was ok, then no tunnel constraints were to be applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1023)
> Fix auto relay selection

- mullvad-daemon/src/lib.rs
I'm disabling wireguard key generation on Windows as currently there is no use for wireguard keys on Windows. The `unreachable_code` warnings are disabled for this function since I think it'd be more pragmatic to disable this lint once for Windows rather than to compile all the fields and modules that are involved with the automatic key generation conditionally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1024)
> Disable wireguard key generation on Windows

- gui/src/renderer/components/NotificationArea.tsx
A slight improvement to the no-matching-relay error message in the GUI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1025)
> Improve no-matching-relay error message in GUI

- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/WireguardKeys.tsx
The "WireGuard port" setting is only visible when the VPN protocol is explicitly set to WireGuard. But the OpenVPN settings are shown no matter what. This felt inconsistent. And also, there is no need to configure the OpenVPN transport protocol or port when Wireguard is exclusively going to be used.
Also changed "protocols" into "protocol" to make it consistent with the other settings.
Also added "OpenVPN" in front of "UDP port" and "TCP port" to make it clear, and also consistent with "WireGuard port" and the other protocol specific settings.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1026)
> Simplify protocol constraint selection

- build-apk.sh
- build.sh
- ci/buildserver-build.sh
- ci/buildserver-upload.sh
Updating build server scripts to automatically build the Android APK on the Linux build machine.
Also various small improvements to the `build-apk.sh` script. Most of them just to make it work more like `build.sh` and to print more useful info while building.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1022)
> Build android on buildservers

- CHANGELOG.md
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/relays.rs
- mullvad-types/src/custom_tunnel.rs
- mullvad-types/src/relay_constraints.rs
- mullvad-types/src/settings/mod.rs
A couple of improvements w.r.t. bridge mode:
- when new relay constraints are applied, they will change the bridge state if they enforce constraints that don't support bridges
- when bridge mode is set to _On_, then relay constraints will be cleared to auto
- take bridge mode into account when determining preferred relay constraints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1028)
> Fix interactions between relay and bridge settings.

- mullvad-problem-report/src/metadata.rs
This PR came about in multiple steps.
* First I saw `unwrap_or_else(String::new)` and thought that it would be more idiomatic with `unwrap_or_default()`.
* I then saw `format!("Android {}{}{} - {} {} {}", ...)` - I usually think a formatting string with multiple `{}` next to each other is an indication that formatting is done somewhere else than the formatting string. From this formatting string it's hard to see what the final text will actually look like. And I felt having `"API: N/A"` would be more clear than just a missing API. Then it's more obvious that we failed to get the API level.
Then I saw a final produced problem report and realized both that the email topic was very very long (the generated problem report has the full `os` metadata content in the topic), and that it contained …
> Android version formatting and included data

- CHANGELOG.md
- Cargo.lock
- gui/src/main/daemon-rpc.ts
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/shared/daemon-rpc-types.ts
- gui/test/components/NotificationArea.spec.tsx
- mullvad-daemon/src/lib.rs
- mullvad-jni/src/into_java.rs
- talpid-core/Cargo.toml
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- talpid-types/Cargo.toml
- talpid-types/src/tunnel.rs
I've changed the block-reason struct in `talpid-types` and added an error type for tunnel parameter generation failures to pass on more information to the user when tunnel parameter generation fails. The extra cases are:
- no wireguard key
- hostname resolution failure in case of custom tunnel endpoints
- failure to select a matching bridge relay.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1030)
> Add elaborate tunnel params error

- CHANGELOG.md
- mullvad-types/src/settings/migrations/v1.rs
Since the migration struct wasn't defined exactly the same as it was in `2019.6`, it was missing some serde attributes and it did not have a `Default` implementation. As such, older versions of the settings with missing fields that were defined only in the `2019.6` wouldn't deserialize. This PR fixes that. I've also added a test to verify that we can deserialize from at least `2019.3`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1033)
> Fix settings migration from versions older than 2019.6

- mullvad-cli/src/cmds/relay.rs
- mullvad-cli/src/location.rs
- mullvad-daemon/build.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/wireguard.rs
- mullvad-rpc/src/cached_dns_resolver.rs
- mullvad-rpc/src/event_loop.rs
- mullvad-tests/src/lib.rs
- mullvad-types/src/auth_failed.rs
- mullvad-types/src/settings/migrations/mod.rs
- talpid-core/src/dns/mod.rs
- talpid-core/src/firewall/linux.rs
- talpid-core/src/firewall/macos.rs
- talpid-core/src/routing/linux/change_listener.rs
- talpid-core/src/routing/macos.rs
- talpid-core/src/tunnel/openvpn.rs
- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-types/src/net/mod.rs
Since we mentioned `::std` vs just `std` in another PR I went ahead and checked if we used this older way in more places. Turned out we did. So I replaced them. When checking the diff I also saw two other potential improvements that I choose to include here.
One is replacing an `unsafe` `mem::transmute` with much safer conversion to and from integers for an enum with a given `repr`. This type of conversion is what we use in [windows-service](https://github.com/mullvad/windows-service-rs/blob/master/src/service.rs#L89). Ultimately I would like to replace this with some third party proc macro that does this automatically. Eliminating further risk of making an error and reduces a lot of boilerplate.
Git checklist:
--- …
> Simplify unimported std usage

- ios/MullvadVPN/AccountExpiryRefresh.swift
Git checklist:
The `RepeatProcedure` created during the call to `makePeriodicUpdateProcedure`, synchronously invokes the block given via constructor, which consults the `shouldKeepRefreshing` before producing the network request to refresh the account data. During the very first call, the `observers` list is empty, hence no network request is created. This PR simply adds the observer first before producing the periodic update procedure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1036)
> Fix addObserver bug in AccountExpiryRefresh on iOS

- .travis.yml
- talpid-types/src/tunnel.rs
The recently extended block reason for tunnel parameter generation error used a deprecated way of printing the inner error, these changes fix that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1039)
> Fix error message for block reason

- gui/src/renderer/components/LoginStyles.tsx
Git checklist:
This PR extends the clickable area of the the account token labels in the account history dropdown on Login view. The new hot area also includes the margins surrounding the label with the account token making it easier to select the item. Previously clicking anywhere around the small text label would be a no-op..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1040)
> Make margins around the account label clickable

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/NotificationBanner.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
A crash was reported when opening the app. While analyzing the stack trace, the cause seems to be related to the initialization sequence of the `AppVersionInfoCache`. In `MainActivity`, it is the only data proxy class that is initialized differently, by being instantiated later in the life-cycle. This led to the crash when an attempt to use the cache before it was initialized.
This PR attempts to fix the crash by refactoring the way `AppVersionInfoCache` is initialized, to be more consistent with the other classes. Now it is instantiated earlier, but an `onCreate` method is added to actually configure the shared preferences listener and to load the initial values.
As part of the refactor, the `MainActivity.currentVersion` property was removed, and in its place the `AppVersionInfoCache` …
> Refactor `AppVersionInfoCache` initialization to avoid crash

- android/src/main/res/layout/settings.xml
This is a tiny UI fix so that the app version isn't capitalized. It's okay for something like `2019.6`, but it fails when it's `2019.7-BETA1`, which should actually be `2019.7-beta1`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1043)
> Don't force version label to be capitalized

- gui/locales/messages.pot
- gui/src/main/account-data-cache.ts
- gui/src/main/errors.ts
- gui/src/main/index.ts
- gui/src/main/window-controller.ts
- gui/src/renderer/app.tsx
- gui/src/shared/ipc-event-channel.ts
- gui/test/account-data-cache.spec.ts
Git checklist:
1. Move account verification and log in and log out functions into the main process. Expose `login` and `logout` IPC methods for the renderer process and account data events.
1. Localize "Invalid account number" error. Since the `Error` has to travel through the IPC there is no way to preserve the type, so I figured the best way is to localise it in the main process and simply throw it into the IPC. This is not exactly beautiful but given that we only have 1 error there, I guess it's reasonable.
1. Update messages.pot with missing localizations from the past PRs.
1. Wrap window-shape related events into the IPC event channel. (Used for the arrow pointer that points to the menubar …
> Move login functions to the main process

- gui/scripts/serve.js
Git checklist:
This PR makes sure that aborting the `npm run develop` using `SIGTERM`, `SIGINT` or by closing the Electron app, properly terminates the `tsc-watch` which supposedly creates a `node` subprocess, that used to hang in the system until it hit the error in attempt to talk to the parent process in response to source code changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1044)
> Add SIGINT and SIGTERM handlers to properly clean up the watch script

- android/src/main/kotlin/net/mullvad/mullvadvpn/ProblemReportFragment.kt
The email input in the problem report screen allows entering spaces. The spaces are then forwarded to email used in the problem report. That causes the server to not detect the email correctly. This situation is more common on mobile since auto-complete can add a space after completing the email address.
This PR mitigates the issue by trimming leading and trailing whitespace from the email address before it is used in the problem report.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1046)
> Trim user email address for problem report

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/WireguardKeyFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/KeyStatusListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/KeygenEvent.kt
- android/src/main/res/layout/settings.xml
- android/src/main/res/layout/wireguard_key.xml
- android/src/main/res/values/strings.xml
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/into_java.rs
- mullvad-jni/src/lib.rs
This PR adds a fragment to the Android app that allows the end user to generate a new wireguard key if one doesn't exist or is invalid, and to verify an existing key. To do this, I've extended `mullvad-jni` to expose a method to verify the currently set key, and the `KeygenEvent.NewKey` has a new field - `verified` which indicates whether a user has verified the key. This fragment also displays the public key if one exists, allowing the user to identify which key is used for the specific device.
For completion sake, the notification that is shown when the app fails to automatically generate keys should take the user to the key management fragment rather than the website directly, but this is not part of the PR.
--- …
> Add fragment to manage WireGuard keys in Android app

- CHANGELOG.md
- talpid-core/src/tunnel/wireguard/config.rs
Current default MTU is too high for 4G networks, which essentially ruins the Android app. I've lowered it so that we can send a wireguard packet in a single _physical_ network packet on 4G. Long term, we should allow users to set their MTU from the Android app and also try and do MTU detection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1050)
> Lower default MTU to increase quality of life on 4G

- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/main/jsonrpc-client.ts
- gui/src/shared/ipc-event-channel.ts
Git checklist:
This PR makes sure that we unsubscribe from the daemon events when the app is about to terminate, right after we tell the daemon to disconnect the tunnel. Since the app is one step away from being terminated, it does not make any sense to keep handling the daemon events, besides any of the events that may be received during the shutdown may cause the app to attempt to talk to the renderer process via IPC which can be long gone by then.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1052)
> Unsubscribe from daemon events on exit

- gui/src/main/index.ts
Git checklist:
The app window remains visible when alt-tabbing or calling any action that opens the external app to either follow the web link or view app logs. This is not intended on macOS.
This PR also makes sure that switching between the dev tools and the menubar window does not hide the app window, since we often do that when inspecting the UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1054)
> Hide the menubar window when other program captures the focus

- gui/src/renderer/components/Support.tsx
- gui/src/renderer/components/SupportStyles.tsx
Git checklist:
This PR makes sure that the action buttons are disabled while collecting a problem report. This should prevent users from clicking the "View app logs" button many times in anticipating that the app didn't get it in the first place. My assumption that it takes long time to run the log collection tool, hence blocking the buttons when running it should solve the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1055)
> Prevent opening multiple report logs

- gui/src/renderer/app.tsx
Git checklist:
I've noticed that `Skip autoconnect in development` appears twice in logs. I ran tests and found that the `daemon-connected` IPC event can still be dispatched even after the constructor finished execution. 
Since we call the same function (`onDaemonConnected`) from both the IPC event handler and from the constructor (when `initialState.isConnected == true`), it's basically possible that we execute the same logic twice, which is not desired, but probably has insignificant side effects. 
This PR makes sure we don't execute the logic inside of `daemonConnected` if the renderer process has already registered that the app is connected to the daemon.
--- …
> Filter out the repeating calls to onDaemonConnected

- android/src/main/kotlin/net/mullvad/mullvadvpn/AccountInput.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/LoginFragment.kt
- android/src/main/res/layout/login.xml
- android/src/main/res/values/strings.xml
This PR adds a button to the login page to create a new account. When the button is pressed, the user is sent to the web page to create a new account.
If the user copies the account number from the web page to the account input field, the HTML formatting would also be pasted, and the text size would be larger than expected. Therefore, this PR also changes the account input so that it removes any formatting.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1060)
> Add "Create account" button to login screen

- android/src/main/res/layout/wireguard_key.xml
Previously, the public key was displayed in all caps, even though the key would be different depending on the case. This changes it so that the key is displayed case sensitively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1063)
> Display public key case sensatively on Android

- gui/package-lock.json
- gui/package.json
- gui/tasks/scripts.js
Git checklist:
This PR replaces `gulp-envify` with a simple search and replace using `inject.replace` plugin. Since the string we replace is very specific, I believe it should not cause any side effects.
The reason for removing `gulp-envify` is because it has vulnerable deps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1065)
> Replace gulp-envify with inject.replace

- Cargo.lock
- talpid-core/Cargo.toml
Bumping our netlink dependencies to include the changes [here](https://github.com/mullvad/netlink/compare/b367ac9c012e6c2a5e065e201384ec20d9708109...mullvad:remove-dependence-on-kernel-structures) - more kernel structs have been removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1064)
> Update netlink dependencies

- build.sh
- prepare_release.sh
This PR changes `prepare_release.sh` so it computes the correct Android version numbers/codes and inserts them into `build.gradle`.
I made the version matching regex stricter than before. Making sure the year starts with `20`, and only accepts the range `[1,99]` for release and beta numbers.
I also removed the possibility of doing `alpha` releases. We have so far never used them, have no plan on using them, and they would cause collisions with how we compute the code anyway.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1066)
> Compute android version code

- build.sh
Follow up to #1066. Makes sure to set the `versionName` even in `build.sh` so dev builds get a correct name inside them.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1067)
> Update build.gradle with product version on build

- Cargo.lock
- android/build.gradle
- build-apk.sh
- build.sh
- dist-assets/windows/version.h
- prepare_release.sh
- talpid-openvpn-plugin/Cargo.toml
- version_metadata.sh
Finally refactoring the injecting of versions into various project metadata files. Moving all such code into `version_metadata.sh` that allows injecting a version as well as restoring backups.
Also committing the changes that the script did to a few of our metadata files that just had dummy values up until now.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1068)
> Refactor version injection

- android/src/main/kotlin/net/mullvad/mullvadvpn/WireguardKeyFragment.kt
- android/src/main/res/layout/wireguard_key.xml
- android/src/main/res/values/strings.xml
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- mullvad-cli/src/cmds/tunnel.rs
After comparing the WireGuard key view on desktop and mobile I found a few differences. We should keep the look/content as consistent as possible at least three reasons:
* Familiarity to users/consistency - It just looks better if the apps are the same.
* Guides - We can't say "click the verify key button" if it's not called that on all platforms.
* Localization - If we use even the slightest different strings, we will end up having to double translate everything, which will be more painful than it has to be.
Whenever adding or changing any GUI element, please make sure it's consistent across platforms.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/ …
> Change text/visibility on elements in WireGuard key view

- build-apk.sh
- build.sh
We have a funky situation that different OSes figure out different hash lengths. Probably because they use different git versions. This is a bit messy and makes the same commit generate apps with different names. This PR locks the amount of chars from the git hash to a fixed number. Keeping the number low since it does not have to be strictly unique globally, just for the current version.
We could increase it from 6 to 8 chars if you want to. 8 is what we currently have, except for slightly older git where it sometimes chooses 9 chars.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1071)
> Make the amount of chars from the git hash in version string constant

- dist-assets/uninstall_macos.sh
Git checklist:
The existing uninstaller for macOS does not unregister the PKG file from the system after wiping the files.
```
$ /Applications/Mullvad\ VPN.app/Contents/Resources/uninstall.sh 
Are you sure you want to stop and uninstall Mullvad VPN? (y/n) y
Uninstalling Mullvad VPN ...
Stopping GUI process ...
No GUI process found
Stopping and unloading mullvad-daemon system daemon ...
Removing app from /Applications ...
Do you want to delete the log and cache files the app has created? (y/n) n
Do you want to delete the Mullvad VPN settings? (y/n) n
$ pkgutil --pkgs | grep net.mullvad.vpn                         
net.mullvad.vpn
```
This PR makes sure that the package is cleaned up from the …
> Unregister uninstalled pkg from the system

- .travis.yml
- appveyor.yml
- ci/ci-rust-script.sh
- ci/travis-rust-script.sh
We can't go forever with a broken CI. That will make us ignore the CI results completely after a while. And it will be very easy to miss formatting errors that would end up in the nightly test, but hidden by other errors. So since the actual fix for making it build on nightly seem a bit further away, let's just disable it for now.
And in order to not have to figure out if statements in `appveyor.yml` I decided to make both CI environments run the same script. Reduced some other duplication as a bonus and made the build more uniform across platforms.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1076)
> Disable nightly rust ci

- CHANGELOG.md
- gui/src/renderer/components/WireguardKeys.tsx
I've added a label to the top of the WireGuard key page in the desktop client to inform the user that keys can't be managed whilst in a blocked state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1077)
> Add offline-state label to WireGuard key page

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectionStatus.kt
- android/src/main/res/values/strings.xml
This PR fixes the status message shown when the tunnel is blocking connections. It would previously say "secure connection", but this PR changes it so that it says "blocked connection", which is more accurate and mirrors the behavior of the desktop app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1078)
> Show "Blocked connection" status message

- CHANGELOG.md
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/components/WireguardKeysStyles.tsx
- gui/src/renderer/containers/WireguardKeysPage.tsx
- gui/src/renderer/redux/settings/actions.ts
- gui/src/renderer/redux/settings/reducers.ts
- gui/src/shared/daemon-rpc-types.ts
- gui/src/shared/ipc-event-channel.ts
- mullvad-daemon/src/account_history.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/wireguard.rs
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/into_java.rs
- mullvad-jni/src/lib.rs
- mullvad-rpc/src/lib.rs
- mullvad-types/src/wireguard.rs
This PR enhances the functionality of the wireguard key page in the GUI  in two ways  - 
- show the currently set key's creation date
- allow user to regenerate a key.
To allow users to regenerate a key, a new RPC is introduced to allow the daemon to replace an old public key with a new one. This master RPC will be used whenever a key generation takes place. An extra button is shown in the wireguard key page in the GUI that allows the user to regenerate a key. The button is only enabled when a key is set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1075)
> Implement manual key rotation.

- Cargo.lock
- talpid-types/Cargo.toml
I saw the `cargo-udeps` tool mentioned in this week in rust. It finds unused dependencies. So I ran it on our code. Sadly the tool only works on nightly rust, due to the way it integrates with the compiler. And most of our code can't build on nightly Rust at the moment. So catch 22 :man_shrugging: . But I was able to run it on some of our smaller crates and found one tiiiiny unused dep at least.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1084)
> Remove unused hex dependency

- android/src/main/kotlin/net/mullvad/mullvadvpn/ForegroundNotificationManager.kt
- android/src/main/res/values/strings.xml
This PR fixes the notification on Android Oreo (API 26) and later. On newer versions, notifications on Android must be assigned to a channel so that the user can control how groups of notifications are presented. This PR creates a channel for the VPN status messages and assigns it to the foreground notification.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1088)
> Use notification channel for service notification

- gui/src/renderer/components/NavigationBar.tsx
Git checklist:
This PR adds a support for a sticky content view which remains fixed at the top of visible scroll bounds when it collides the top edge as user scrolls. 
Basic usage:
```jsx
<StickyContentContainer>
<NavigationScrollbars>
<View>
<SettingsHeader>
<HeaderTitle>Select location</HeaderTitle>
<HeaderSubTitle>While connected, your real location is masked with a private and secure location in the selected region</HeaderSubTitle>
</SettingsHeader>
<StickyContentHolder>
<ScopeBar>
<ScopeBarItem>Exit</ScopeBarItem>
<ScopeBarItem>Entry</ScopeBarItem>
</ScopeBar>
</StickyContentHolder>
{ /* a bunch of content */ }
</View>
</NavigationScrollbars>
</StickyContentContainer>
```
The way it works, …
> Add support for sticky content within scrollable area

- CHANGELOG.md
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/renderer/containers/SettingsPage.tsx
- gui/src/renderer/redux/version/actions.ts
- gui/src/renderer/redux/version/reducers.ts
- gui/src/shared/daemon-rpc-types.ts
- gui/test/components/NotificationArea.spec.tsx
- mullvad-cli/src/cmds/version.rs
- mullvad-types/src/version.rs
Our version check API call now contains a flag telling the app if it's outdated or not. So we let the API decide that instead of letting the app just compare it's current version with the latest version returned from the API.
This allows us to tell the app there is no relevant update for it, even if it's not running the latest. This allows us to release apps for specific platforms without annoying users on unchanged platforms.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1089)
> Version check outdated

- CHANGELOG.md
- mullvad-cli/src/cmds/status.rs
Fixes #617 
Would be nice to be able to query the daemon state without relying on a working internet connection. So I removed the mandatory GeoIP lookup in `mullvad status`. Makes it way easier to use this command in scripts and some other scenarios.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1091)
> Don't talk to API by default in `mullvad status`

- talpid-core/src/firewall/windows.rs
- talpid-core/src/offline/windows.rs
- talpid-core/src/winnet.rs
- windows/shared/logsink.h
- windows/shared/logsinkadapter.h
- windows/winnet/src/winnet/netmonitor.cpp
- windows/winnet/src/winnet/netmonitor.h
- windows/winnet/src/winnet/winnet.cpp
- windows/winnet/src/winnet/winnet.h
Formalize logging types and structure files for reuse between DLLs.
Minimize global namespace pollution.
Add logging of network adapters whenever the logic decides the machine is offline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1092)
> Win log offline

- Cargo.lock
- mullvad-daemon/Cargo.toml
- mullvad-jni/Cargo.toml
- mullvad-types/Cargo.toml
- talpid-core/Cargo.toml
- talpid-core/src/firewall/linux.rs
- talpid-types/Cargo.toml
One crate depended on a fork of `ipnetwork` that fixed a bug in its deserialization. That has been merged upstream into `ipnetwork` for a long time, but they did not do any release on crates.io until now. So here I upgrade it so we get rid of the git based dependency.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1098)
> Upgrade ipnetwork to 0.15 to get rid of git dependency

- android/src/main/kotlin/net/mullvad/mullvadvpn/model/Relay.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/Relay.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayCity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayCountry.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItem.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemHolder.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt
- android/src/main/res/drawable/icon_relay_inactive.xml
- build.sh
- gui/scripts/extract-geo-data.py
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/LocationList.tsx
- gui/src/renderer/components/RelayRow.tsx
- gui/src/renderer/redux/settings/reducers.ts
- gui/src/shared/daemon-rpc-types.ts
- mullvad-cli/src/cmds/bridge.rs
- mullvad-cli/src/cmds/relay.rs
- mullvad-daemon/src/relays.rs
- mullvad-jni/src/into_java.rs
- mullvad-rpc/src/lib.rs
- mullvad-types/src/relay_list.rs
Update the daemon/build scripts to use new `relay_list_v3` that will always include all relays, even the inactive ones in maintenance mode. But with the extra `active` flag on the relays. This allows us to properly know which servers should exist and what types they are. So we can show inactive cities under the correct relay type (OpenVPN, WireGuard or a Bridge)
DONT merge until `relay_list_v3` is actually deployed, which it is not at the time of writing this. Also remove the TMP commit disabling daemon downloading of the relay list.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1096)
> Use new relay_list_v3 to properly know relay types and which cities have what type of relays

- android/src/main/kotlin/net/mullvad/mullvadvpn/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
This PR refactors how the Android app quits in order to become more robust. Sometimes Android may reuse the service while it's shutting down, attaching it to a new instance of the app UI. When that happened, the app would crash because the daemon thread would have been stopped. The changes in this PR makes it handle that case, by manually restarting and the daemon thread and delaying the connection to the new UI until the thread is running successfully.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1097)
> Refactor app quit procedure

- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/net/mullvad/mullvadvpn/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
- android/src/main/res/drawable/icon_notification_connect.xml
- android/src/main/res/drawable/icon_notification_disconnect.xml
This PR updates the Mullvad notification to include two action buttons that are shown when the notification is expanded (i.e., dragged down with two fingers). One button allows the user to quickly quit the app. The other button contains the "tunnel action", which reproduces the behavior of the "action button" in the Connect screen. Depending on the tunnel state, the tunnel action may be to connect or disconnect the tunnel or cancel a connection attempt.
In order to implement quiting from the notification, the app shutdown code was refactored. A consequence of this is that the quit behavior should become more robust.
Git checklist:
--- …
> Implement notification action buttons

- mullvad-jni/src/vpn_service_tun_provider.rs
The Android `VpnService` sometimes provides a tun device with a bad file descriptor. This was previously handled correctly in `wireguard-go`, where a special error code was returned and the tunnel state machine's `ConnectingState` would automatically retry to connect.
When the Android blocking state was implemented, the tun file descriptor is duplicated in order to keep the tunnel open. However, calling `dup` on a bad file descriptor leads to an error and the connection fails, entering the blocked state.
Unfortunately, since the tunnel creation code is handled by a trait object (`&mut dyn TunProvider`), only a `BoxedError` instance can be returned to the `ConnectingState`. Therefore, returning a special error code to indicate that the connection should be reattempted would require …
> Retry to create tunnel on bad file descriptor

- CHANGELOG.md
- mullvad-cli/src/cmds/relay.rs
We got a panic when running `mullvad relay set custom` without a subcommand under it. This fixes that.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1105)
> Require the "mullvad relay set custom" command to have a subcommand

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/ConnectionProxy.kt
This PR changes which parts of the UI change on predicted tunnel state changes, and which parts change on real tunnel state change events. A quick summary is:
1. Predicted tunnel state
- Action button
- Switch location button text
2. Real tunnel state
- Notification banner (showing "Blocking connections" when in Connecting state)
- Location information
- In/Out IP address
- Connection status message
- Header bar color
- Notification (both button and text)
As part of this PR, the race condition prevention code was slightly refactored. The code exists so that fetching the tunnel state for the first time doesn't overwrite any tunnel state that was received by an event from the daemon. Previously the real state would be set to `null` until an event changed it or the initial fetch successfully …
> Update how the UI responds to predicted and real tunnel state changes

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/ConnectionProxy.kt
The UI will anticipate certain tunnel states (Connecting and Disconnecting) when certain UI actions are performed in order to provide feedback as fast as possible. However, if any issue occurs when sending the command or when the daemon is handling the command, the anticipated state will never arrive. Therefore, this PR adds a timeout after setting the UI state to an anticipated state. If the time expires without receiving a tunnel state event from the daemon, the UI state is restored to the previous known tunnel state.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1106)
> Reset state if anticipated state doesn't arrive

- mullvad-jni/src/into_java.rs
The app would previously crash after being left running in a connect/disconnect loop overnight. The cause was that the local reference buffer would get filled with references to `Class<InetAddress>` objects. The cause was that `JNIEnv::call_static_method_unchecked` would create a local reference if provided with a class name instead of a class reference. This PR changes the call to use a class reference.
As part of the investigation, I also noticed that there was a situation that could also leak a local reference, so the PR also wraps up a parameter conversion with an `AutoLocal` to make sure it's freed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app …
> Fix local reference leaks

- mullvad-jni/src/into_java.rs
The previous PR led to a situation where the JNI code would crash because it would try get the class of a `Class` object instead of using it directly. This PR changes the code so that it uses a different work-around in order to bypass the strict lifetime limitation.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1110)
> Change lifetime limitation workaround

- gui/src/renderer/components/Account.tsx
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/CustomScrollbars.tsx
- gui/src/renderer/components/NavigationBar.tsx
- gui/src/renderer/components/Preferences.tsx
- gui/src/renderer/components/SelectLocation.tsx
- gui/src/renderer/components/SelectLocationStyles.tsx
- gui/src/renderer/components/Settings.tsx
- gui/src/renderer/components/SettingsHeader.tsx
- gui/src/renderer/components/Support.tsx
- gui/src/renderer/components/WireguardKeys.tsx
Git checklist:
1. Change the highlight in the selected scope item (tab item) from blue to green because different shades of blue caused confusion regarding which item is currently selected
2. Add `NavigationItems` to group the regular bar items into a horizontal layout and be able to stack more custom views below. This enables us to extend the navigation bar with custom views.
3. Remove sticky content and replace it with the content attached to the navigation bar. There was a lot of confusion regarding the UI being jumpy when switching tabs
4. Make `SettingsHeader` automatically put `8pt` spacers between children so we could reuse `HeaderSubtitle` view without messing with its margin.
5. …
> Select location UX improvements

- Cargo.lock
- mullvad-cli/Cargo.toml
- mullvad-cli/src/cmds/tunnel.rs
- mullvad-ipc-client/src/lib.rs
The currently unreleased changes to the WireGuard key handling did not propagate to the CLI, as such the `mullvad tunnel wireguard key check` command failed since the response from the daemon would fail to deserialize. This PR updates the IPC client code to expect and deserialize the new structure properly and changes the CLI to print the date of creation of a the currently set key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1111)
> Display age of creation for WireGuard key in CLI

- CHANGELOG.md
- Cargo.lock
- gui/src/renderer/app.tsx
- mullvad-cli/Cargo.toml
- mullvad-cli/src/cmds/bridge.rs
- mullvad-cli/src/cmds/relay.rs
Sorting of relays was brought up a while back. And we implemented sorting in our frontends. One problem that remained was the classical problem of just sorting strings alphabetically when they contain numbers. Ending up with an order like `["se1", "se10", "se2"]`. This PR removes sorting from the frontends and instead sorts using a natural sorting algorithm directly in the daemon. Meaning all frontends get this benefit without having to pull is such a sorting library in all frontends. Now relays should show up as `["se1", "se2", "se10"]`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1114)
> Sort locations naturally in daemon

- CHANGELOG.md
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/relays.rs
When constructing relay parameters, there were cases where the daemon wouldn't enforce TCP tunnels and would also allow for using UDP bridges. I've added changes so that TCP is used whenever a bridge is forced if the transport protocol is not constrained to any specific protocol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1115)
> Ensure that only TCP relays are used when using a bridge

- android/src/main/kotlin/net/mullvad/mullvadvpn/ConnectActionButton.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/NotificationBanner.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayItemHolder.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayListAdapter.kt
This PR is an attempt to fix the error where the UI would lock up after some reconnection attempts. The number of reconnections varies, but it is a large number (smallest I've seen was around 80).
UI views will now cache the drawables they use instead of specifying drawable IDs and letting Android allocate them. This should prevent using too much GPU memory, which is a probably cause to the issue. As a consequence, this PR also has the advantage that UI should be more responsive due to the removal of allocations in the UI thread.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1116)
> Reuse UI drawables

- android/build.gradle
- android/proguard-rules.pro
This PR disables all minification and obfuscation done by ProGuard. This will make it easier to read the stack traces in the problem reports.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1118)
> Disable obfuscation

- CHANGELOG.md
- talpid-core/src/tunnel/wireguard/mod.rs
Previously the ping monitor thread would enter the ping loop even if the first ping had failed. This could lead to a situation where there might be two ping monitor threads active at the same time for a while. This PR fixes that by only entering the loop if the first ping succeeds.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1121)
> Stop ping monitor thread if first ping fails

- android/src/main/kotlin/net/mullvad/mullvadvpn/NotificationBanner.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoFetcher.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/AppVersionInfo.kt
- mullvad-jni/src/into_java.rs
Making sure Android respects the new `current_is_outdated` flag in the version check. Should making notifying users about upgrades more correct. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1125)
> Fix android outdated check

- gui/src/renderer/components/TransitionContainer.tsx
Git checklist:
When transitioning between views in Settings. If the mouse position coincides with the hoverable element, such as cell, the hover is not activated at the end of transition. Even moving mouse does not fix this unless the mouse goes outside of the element underneath the mouse. I've spotted this only happens when using `z-index` to block the transition container interactions during transitions. However, using `pointer-events` works just fine and hovered cell re-activates successfully at the end of transition. I should add that in the newer versions of ReactXP this is implemented as a part of `blockPointerEvents` prop for the web platform, however there was no stable release yet.
--- …
> Use pointer-events instead of z-index to fix the hover state

- Cargo.lock
- talpid-core/Cargo.toml
I just released new versions of these two libraries to crates.io. So we can depend on them there instead of git. Way more stable for long term reproducibility. And good to get the latest features out to potential other users of the crates
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1130)
> Bump nftnl and mnl dependencies to crates.io versions

- gui/tasks/hotreload.js
Git checklist:
Seems like running any actions from redux-devtools requires `unsafe-eval` CSP. This PR adds the CSP permissions when in development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1132)
> Allow CSP: unsafe-eval in development because redux-devtools use eval

- mullvad-jni/src/vpn_service_tun_provider.rs
I left the device running a test version to see if it still ran into the bad file descriptor error, but it crashed after about an hour due to a filled local reference buffer. Apparently, we were leaking the `TunConfig`s we created to send to the Java side. This PR just wraps it in an `AutoLocal` so that it is freed after we've finished using it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1137)
> Fix local reference leak of `TunConfig`

- mullvad-types/src/relay_constraints.rs
This corrects a typo (protcol >> protocol) in the output of the "relay get" command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1143)
> Fixed a typo in relay get command response

- CHANGELOG.md
- mullvad-daemon/src/relays.rs
We had a bug so when running `mullvad relay update` it would just trigger a check of the cache age. And if the cache was newer than the set limit, it would not actually download anything. The point of the command is to trigger a list update even when the cache is new.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1144)
> Fix relay update CLI command to always trigger download

- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
On Android, sometimes attempting to connect would lead to a start tunnel error due to an `EBADF` error when calling `dup`. This PR changes the code around `dup` to not assume `EBADF` is macOS specific, so either `EBADFD` or `EBADF` can occur on Linux and Android too.
As part of the PR, the error message was reworded as well to avoid confusion.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1145)
> Handle EBADF on Linux and Android

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/SettingsListener.kt
Previously the Android notification would always show an action button that allows the user to connect or disconnect the tunnel, even if the app had no account set. This PR changes that so that the button is only shown if the user is logged in.
The solution implemented here isn't the ideal one. It would be best to not touch `MullvadDaemon` and move the `AccountCache` to `MullvadVpnService`. However, that would require a lot of changes, and I think it would be best to refactor this later on anyway. For an initial stable release this should be fine, but afterwards we should refactor parts of the code to have a better solution.
Git checklist:
--- …
> No action button when logged out

- version_metadata.sh
I was not very careful when writing #1146. I forgot to only restore/delete the backup on the subset of systems where we make the backup...
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1150)
> Put condition on restore commands as well, not just backup

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/WireguardKeyFragment.kt
Previously, the WireGuard key's age was displayed in UTC, which is suboptimal. This PR changes is so that the device's configured timezone will be used to display the age of the key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1152)
> Show key age in local timezone

- CHANGELOG.md
- android/src/main/res/drawable/icon_notification_connect.xml
- android/src/main/res/drawable/icon_notification_disconnect.xml
Android requires icons to be set in order to create notification action buttons. However, on recent Android versions the icons aren't shown. Therefore, the images that were included for the icons weren't actually tested as being displayed on a notification. On older versions of Android, where the icons are showed, they appeared to be incorrect.
This PR fixes the icons, by making sure the sizes are correct and by translating the image to the center of the viewport.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1156)
> Fix icons for notification action button

- android/src/main/kotlin/net/mullvad/mullvadvpn/ForegroundNotificationManager.kt
The `stopForeground` method was being passed the notification ID, but it's parameter required a flags argument instead. Luckily, this hadn't appeared as a bug before because the hard-coded notification ID (`1`) was the value required for the flags.
However, on Android Lollipop there's only one overload of `stopForeground`, which receives a `boolean` as parameter instead of an `int`. So this issue ended up appearing as a crash while stopping the service.
This PR fixes the issue by using the overload present on Lollipop (which is also available on later versions).
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1158)
> Fix usage of `stopForeground`

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-rpc/src/lib.rs
This PR adds an RPC to the daemon that creates WWW auth tokens so that the GUI can create URLs to log users in directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1159)
> Add get_www_auth_token RPC in daemon

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/LocationInfo.kt
Previously, collapsing the tunnel information box and expanding it again would reveal the tunnel information without the out IP address that was previously shown. This was caused because the location information that was fetched wasn't stored in the class for future use, so it would only be shown right after the information is received.
This PR fixes the issue by storing the value in the correct field in the class.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1162)
> Fix tunnel out IP address disappears after collapsing tunnel information

- CHANGELOG.md
- mullvad-cli/src/cmds/account.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-ipc-client/src/lib.rs
- mullvad-rpc/src/lib.rs
To allow users to create a new account from the GUI, firstly the daemon has to support this. This PR adds a new RPC to the daemon that will call the `create_account` RPC on the API to create a new account. I have also added a new subcommand to the CLI to allow creating accounts with it.
Since after creating an account, there's no _money_ on it, I've made it so that whilst the new account is set, the daemon will not try to connect as it would fail, and then the user wouldn't be able to pay for time on the account without unblocking anyway. Maybe this should be changed so that we fail shut anyway, as it would be the more secure thing to do.
--- …
> Add RPC to create accounts in daemon

- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/AdvancedSettingsStyles.tsx
- gui/src/renderer/components/Cell.tsx
- gui/src/renderer/components/Preferences.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/components/WireguardKeysStyles.tsx
Git checklist:
This is a tiny PR that fixes a couple of visual issues on our UI. 
1. Fix the appearance of a warning message displayed when block when disconnected is on. Maybe we should make the message in red, but I didn't want to stress much on that right now. Too much red can be depressing for eyes. 😖👁 Let me know what you think. 
2. Align Wireguard view styles with the Account vew presentation, so both views have equal margins across the board. Move the key 🔑 validation result on the opposite side of the "Public Key"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/117 …
> Refine visual styles in Advanced Settings

- gui/src/renderer/app.tsx
- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/renderer/containers/AccountPage.tsx
- gui/src/renderer/containers/AdvancedSettingsPage.tsx
- gui/src/renderer/containers/ConnectPage.tsx
- gui/src/renderer/containers/LaunchPage.tsx
- gui/src/renderer/containers/LoginPage.tsx
- gui/src/renderer/containers/NotificationAreaContainer.tsx
- gui/src/renderer/containers/PreferencesPage.tsx
- gui/src/renderer/containers/SelectLanguagePage.tsx
- gui/src/renderer/containers/SelectLocationPage.tsx
- gui/src/renderer/containers/SettingsPage.tsx
- gui/src/renderer/containers/SupportPage.tsx
- gui/src/renderer/containers/WireguardKeysPage.tsx
- gui/src/renderer/context.tsx
- gui/src/renderer/routes.tsx
Git checklist:
So as you know all containers use `connect()` from `react-redux` in order to subscribe to the redux store. This drives the render cycle of all of our top level react components as changes settle in the redux store.
All this time we used to pass the reference to the `AppRenderer` using the `CustomRoute` (`routes.ts`) which basically appended an extra prop called `app` which we later received in `mapStateToProps` and such.
This worked very well until I've added a container for `NotificationArea` which is rendered inside of the `Connect` view and is not a direct descendant of the `CustomRoute`, hence there is no parent that can share an `app` with it which we'll eventually need given …
> Add app context

- CHANGELOG.md
- gui/src/config.json
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/Account.tsx
- gui/src/renderer/components/AppButton.tsx
- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/renderer/components/NotificationBanner.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/containers/AccountPage.tsx
- gui/src/renderer/containers/ConnectPage.tsx
- gui/src/renderer/containers/NotificationAreaContainer.tsx
- gui/src/renderer/containers/WireguardKeysPage.tsx
- gui/src/shared/ipc-event-channel.ts
- gui/test/components/NotificationArea.spec.tsx
This PR changes the GUI so that the URLs for the account and wireguard keys pages will be opened with the `token` URL parameter populated with a token received from the daemon. The net result is that the user will already be logged in when they will open these links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1161)
> Use authentication tokens for account and wireguard keys pages.

- ci/ci-rust-script.sh
It is very annoying having the CI error out just because there is no `rustfmt-preview` available for nighly Rust. When this happens and we can't check formatting, is it better the CI becomes green so we know everything else worked? Or do we want it to keep failing, forcing us to open up the CI logs and check that the fail actually was just the formatting, or something else?
This seems a bit more sane to me. Keeping the CI alive and giving us usable results even when things we can't affect goes up and down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1173)
> Ignore error while installing rustfmt-preview

- CHANGELOG.md
- windows/winnet/src/winnet/netmonitor.cpp
This change enables us to detect network disconnects quicker. For some reason the logic did not previously consider the `HardwareInterface` flag. That had the effect that we were waiting for the TAP adapter to disconnect before concluding that all adapters were indeed disconnected. And this could take quite some time, before OpenVPN determines that the tunnel is non-functional and terminates it.
By correcting this we lose support for BT tethering. See comment in code. This can be worked around but not supporting BT may actually be better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1176)
> Windows: Detect network disconnects quicker

- CHANGELOG.md
- gui/src/main/index.ts
Don't log the arguments to the problem report binary if it fails to be sent. Protects users from having their email included in the otherwise redacted logfiles.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1179)
> Don't log args when a problem report send fails

- .gitignore
Do you agree it would be nice to get rid of these from `git status`? As soon as one starts working with the geoIP stuff the git status becomes very dirty. As far as I know we don't do and don't want to version them anyway, so they should be ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1185)
> Add all the stuff generated as geoip metadata to gitiginore

- dist-assets/windows/installer.nsh
A tiny update to get rid of the popup when installing the TAP driver.
Depends on https://github.com/mullvad/mullvadvpn-app-binaries/pull/39.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1184)
> Silently approve TAP driver certificate on Windows

- build-apk.sh
- build.sh
- ci/ci-rust-script.sh
- prepare_release.sh
Inspired by #1183 
Making sure distribution builds are built frozen. Meaning the lockfile in the repo has to be up to date. Doing the same in CI. If we change something and we don't commit the corresponding lockfile change to the repo we should fail.
Also adding `+stable` to the `build-apk.sh` script. Since that's what we use in `build.sh`. To better ensure we use the same toolchain.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1190)
> Add --locked to all cargo build invocations

- CHANGELOG.md
- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/ExpiredAccountErrorView.tsx
- gui/src/renderer/containers/ConnectPage.tsx
There was still a component that did not use authenticated URLs when opening links to the account, so I went ahead and added it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1188)
> Use authenticated URLs in ExpiredAccountErrorView

- build-apk.sh
- build.sh
I screwed up back in #1190 
Obviously the lockfile will change, we explicitly inject new versions into the crates upon build.
So we have to limit usage of `--locked` to release build.
Reason for renaming `CARGO_FLAGS` to `CARGO_ARGS` in `build-apk.sh` was that we already had variables named `_ARGS` in `build.sh` so it felt most consistent to use the same. We could of course change all of them the other way if you think `_FLAGS` make more sense. But flags are a subset of possible args, so `_ARGS` is more generic and would allow us to pass non-flag args.
The `cargo +stable clean` that I added is to become equivalent to `build.sh`. On a production build we probably want to build everything from scratch. This won't slow down things in practice since we run `build.sh` before `build-apk.sh` …
> Fix invalid usage of --locked

- .gitignore
- CHANGELOG.md
- README.md
- build.sh
- dist-assets/linux/after-install.sh
- dist-assets/linux/before-remove.sh
- dist-assets/pkg-scripts/postinstall
- dist-assets/uninstall_macos.sh
- gui/src/main/index.ts
- gui/tasks/distribution.js
- mullvad-problem-report/Cargo.toml
- mullvad-problem-report/src/main.rs
Thanks to #1160 we now finally have the CLI tools on the PATH. Meaning they are easy to find for users. Downside is that the problem report tool is named just `problem-report`. A very generic name that can't be connected to us.
Also, on Linux we still did not have the problem report tool in the PATH, still making it hard to find there as well.
This PR goes ahead and renames the problem report tool so it's always and everywhere called `mullvad-problem-report`. Then it makes sure it's going to be available under exactly that name on the terminal for all OSes where this was not already true.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1192)
> Rename problem report binary

- mullvad-daemon/src/version_check.rs
Fixing what I screwed up in #1167 
I only bumped `self.next_update_time` if the newly downloaded `app_version_info` was different from the cached one. Meaning as long as it did not change server side, we did one version check every 5 minutes instead of every 24 hours.
Also making sure we log every time we actually download it. So we can see in logs when it's actually downloaded and not just when we broadcast it to frontends.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1196)
> Fix: Bump next_update_time correctly every time

- gui/scripts/extract-geo-data.py
- gui/scripts/integrate-into-app.py
- gui/scripts/prepare-rtree.ts
Git checklist:
1. Merge `relay-locations.pot` to make sure we preserve the old locations and include the new ones
1. Sort `countries.po`, `cities.po`, `relay-locations.po`, `relay-locations.pot` output to reduce amount of diffs in git
The generator behaviour for `relay-locations` was change to:
1. Generate `relay-locations.pot` from `relays.json`
1. Auto-translate the produced `relay-locations.pot` and produce `relay-locations.po` for each language
1. Merge the existing `locales/relay-locations.pot` with the generated one `out/locales/relay-locations.pot` using `msgcat`. Which basically puts together two files so that we hvae old relays + new relays to preserve all of the relays we ever …
> Fix gettext integration

- gui/src/renderer/components/Account.tsx
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/ErrorBoundary.tsx
- gui/src/renderer/components/HeaderBar.tsx
- gui/src/renderer/components/Launch.tsx
- gui/src/renderer/components/Preferences.tsx
- gui/src/renderer/components/SelectLanguage.tsx
- gui/src/renderer/components/Settings.tsx
- gui/src/renderer/components/Support.tsx
PR on what I brought up on Slack a while back. Reducing translating the same string multiple times when there is virtually zero chance any language would actually want them to be different in different places, because the context is the same in all locations.
All `'Settings'` strings are moved to the new `'navigation-bar'` context. There is one instance of this string per page that can navigate back to the settings view, plus the header on the actual settings view (when you are logged out)
All `'MULLVAD VPN'` strings are moved to the new `'generic'` context. This is the name of our product, and I doubt it should be translated at all actually. I could not find any of our existing languages actually changing it to anything else currently. So maybe we could move it out of gettext altogether? …
> Less duplicated translations

- CHANGELOG.md
- dist-assets/windows/installer.nsh
- windows/nsis-plugins/src/driverlogic/context.cpp
- windows/nsis-plugins/src/driverlogic/context.h
- windows/nsis-plugins/src/driverlogic/driverlogic.cpp
- windows/nsis-plugins/src/driverlogic/driverlogic.def
- windows/nsis-plugins/src/driverlogic/driverlogic.vcxproj
- windows/nsis-plugins/src/log/log.cpp
- windows/nsis-plugins/src/log/logger.h
* Remove the Mullvad TAP adapter if there are multiple adapters. Also delete the driver if it's not being used by any other adapter.
* Add `registry::WriteString` (to nsis plugin).
* Add `TapAdapterCount` and `RemoveMullvadTap` to driverlogic plugin.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1207)
> Remove TAP adapter on Windows

- .travis.yml
The rustfmt checks on Travis has failed for about a week now. Very annoying. I tried fixing it yesterday with no success. To make the CI not fully red all the time I opted to disable the nightly builds for now. Will look into fixing the formatting check later again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1214)
> Disable Rust nightly temporarily until rustfmt issues are resolved

- talpid-core/src/tunnel_state_machine/connecting_state.rs
A small fix to a logging call to be tunnel agnostic. This has previously confused some of us whilst debugging WireGuard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1215)
> Use tunnel agnostic log message when disconnecting from the connecting state.

- .travis.yml
Reverts #1214 and fixes the running of rustfmt on nightly. The core of the problem was not rustfmt related at all. It was that nightly rust/cargo recently switched syscall from `stat` to `statx` for checking files. And `statx` is so new that it's not a whitelisted syscall in the version of docker running on travis. As such it was denied, and `cargo fmt` could not find the corresponding `cargo-fmt` binary. Even if I directly used `cargo-fmt` that binary in turn could not find `Cargo.toml` because it also used `statx`. The solution here was to just add `--privileged` to docker. Usually not a good approach from a security perspective, but there is nothing that requires any security in our Travis runs anyway.
Git checklist:
--- …
> Fix nightly rust in docker

- .travis.yml
- ci/ci-rust-script.sh
- mullvad-jni/src/lib.rs
While I was tinkering with #1216 I also thought it was quite inconsistent to install rustup so far from each other depending on platform. When we did it directly in `.travis.yml` for Windows that was still going to be done in a git bash shell, so it could just as well be moved to our CI script to make things more even.
The `-c rustfmt` part is moved from the rustup install to the `rustup toolchain install` step. Apparently this is where the flag can automatically backtrack to last known good toolchain with said component. It did not do that if provided directly to the rustup install script I learned from some IRC conversations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullv …
> Perform installation of Rust in one place

- CHANGELOG.md
David L had sharp eyes and spotted three places where we had merged things adding changelog entries for 2019.9 *after* that was released. These should all be under `[Unreleased]`.
Not sure exactly how we best mitigate this in the future.
Also did a formatting fix, one line was longer than 100 chars.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1219)
> Move things under 2019.9 that is not yet released to Unreleased

- CHANGELOG.md
- windows/winnet/src/winnet/interfaceutils.cpp
- windows/winnet/src/winnet/interfaceutils.h
winnet would cache the name of the TAP adapter and only report an error if it wasn't found the first time it was looked up, resulting in perpetual reconnection attempts if it were removed or renamed. Easily fixed by not caching the lookup.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1218)
> Detect removal of TAP adapter when daemon reconnects

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/WireguardKeyFragment.kt
- android/src/main/res/values/strings.xml
I've addressed some small inconsistencies with the WireGuard key fragment in the Android app:
- Only 20 characters of the public key are shown
- The public key is copied to the clipboard when clicked
- Use the term _regenerate_ instead of _repalce_ to generate a new key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1220)
> Android improve keygen fragment.

- talpid-core/src/process/stoppable_process.rs
The daemon can get stuck sometimes when disconnecting. We are not sure exactly what it is, but we suspect it's a bug in the subprocess handling. Maybe related to our other filedescriptor issues.
To easier detect if it's the killing of OpenVPN that is stuck or not I add this logging. We still can't reliably reproduce this error. But if we get this merged, then maybe we can get some slightly more helpful logs about this sometime in the future.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1221)
> Log after forcefully killing OpenVPN

- mullvad-types/src/settings/mod.rs
The relay settings struct `Display` impl can be very very long. Which makes two in a row just reparated by " to " hard to see clearly. Adding newlines and other formatting to make it clearer how things change.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1224)
> Add newlines+tabs to relay settings change log entry

- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/src/tunnel/openvpn.rs
The `which` crate quite recently made `failure` optional. I then also managed to add so when not using `failure` its errors correctly implemented the standard library error trait. Now there has been a release with these changes. So I upgraded `which` and got rid of the `failure::Compat` layer. :tada: 
https://github.com/harryfei/which-rs/pull/16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1227)
> Upgrade the which crate to 3.1 to get rid of failure dependency

- CHANGELOG.md
- windows/nsis-plugins/src/pathedit/pathedit.cpp
We decided to abort the installation when the type of the PATH value in registry was not set to REG_EXPAND_SZ (#1160). It turns out that some applications are not as careful and will overwrite this with a value of type REG_SZ, so I've added this as fallback in case it fails.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1228)
> Add workaround for failure on PATH value having an incorrect type

- CHANGELOG.md
- mullvad-jni/src/vpn_service_tun_provider.rs
- talpid-core/src/tunnel/tun_provider/mod.rs
- talpid-core/src/tunnel/tun_provider/stub.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
Sometimes, the `tun` that is opened and used for the connection attempts seems to simply discard all packets. When this happens, the app would previously get stuck in an endless reconnecting loop.
This PR implements a workaround to the issue, by closing and opening the `tun` device after a specified number of reconnection attempts. This number is currently hard-coded in the code.
The `TunProvider` already had a `create_tun_if_closed` method that's specific to Android. This PR adds a new `create_tun` method that opens a new tunnel whether or not there already is an open tunnel. The common code was moved to a new `open_tun` private helper method.
When the tunnel state machine's `ConnectingState` detects it has tried to connect with the same tunnel as many times as the maximum number, it …
> Recreate tun when stuck in reconnect loop

- CHANGELOG.md
- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
Previously, the `wireguard-go` glue library would use as log output a file descriptor received through FFI. This led to some weird issues, where sometimes the process would run into EBADF errors in different places.
This PR changes the logging setup to use an updated version of the `wireguard-go` glue library. The new version doesn't receive a file descriptor anymore, but a file path instead and the file is handled inside the Go library.
The code in `talpid-core` is updated in this PR to only send the file path, and to not handle the log file anymore.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1230)
> Handle wireguard log file inside `wireguard-go`

- CHANGELOG.md
Correct me if I'm wrong. But I interpret this change as being mostly(only?) for fixing the infinite reconnect loop. If true, it's a bugfix. It's true that bugfixes are changes, but after all this is a changelog. Anything that does not fit into any more specific category can go in `### Changed` but this felt like it was more of a `### Fixed` thing?
The release tag is already published and all. But does not hurt to fix this after either. If we get this approved very soon, I can use the new formulation in the github release post.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1234)
> Move around one Android changelog entry

- ci/ci-rust-script.sh
- talpid-core/src/tunnel_state_machine/connecting_state.rs
Apparently we lost our strict check of `unused_imports` and `dead_code` somewhere along the way. `export`ing the variable makes sure it's valid during the actual `cargo` runs later in the script.
Also fixes the dead code warning(now error) that made me find this :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1233)
> Respect rustflags and fix dead code

- CHANGELOG.md
- mullvad-daemon/src/system_service.rs
- talpid-core/src/routing/mod.rs
- talpid-core/src/tunnel/wireguard/mod.rs
There are issues with deadlocking when running the routing code on the same event loop as the tunnel state machine. Thus, I've moved the routing code into it's own thread which resolves the issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1242)
> Run the routing manager in it's own thread

- Cargo.lock
- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/system_service.rs
This fixes the formatting error on https://travis-ci.com/mullvad/mullvadvpn-app/jobs/258138656#L230
And it also tries to be a bit more idiomatic on storing times as structured types instead of integers. That way the variable name can reflect what the time is supposed to represent, instead of the time unit and how long time it is. I'm not sure if the current names are perfect. Because I did not know exactly what they represented, which is exactly the problem I'm trying to address here :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1247)
> Idiomatic duration constants

- dist-assets/windows/installer.nsh
The TAP driver would sometimes attempt to call `update` instead of `install`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1249)
> Fix installer/updater regression

- CHANGELOG.md
- talpid-core/src/process/openvpn.rs
We already specify only secure ciphers for TLS <=1.2. But since layers upon layers of security is our usual method I felt we could just as well specify `--tls-version-min` as well. Later when more servers are upgraded we can even set it to 1.3.
The `--tls-client` argument should force the control channel to use TLS. It already did that from before given the combination of server+client options anyway, but this makes it more explicit, and it tells it to act as the client half of said TLS handshake from the start.
There are not really any insecure ciphers allowed in TLS 1.3 by default. But specifying the two strongest ones rules out the 128 bit AES one. Mostly because why not. The servers currently support that 128 bit AES cipher, but they plan on setting the same `tls-ciphersuites` as us …
> Limit OpenVPN to use TLS >=1.2 and limit 1.3 ciphers

- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/main.rs
- mullvad-daemon/src/windows_exception_logging.rs
To help determine why the daemon crashed. E.g.
```
[2019-11-21 09:16:00.510][mullvad_daemon::windows_exception_logging][ERROR] Unhandled exception at RVA 0x177093 in winnet.dll: EXCEPTION_ACCESS_VIOLATION (wrote to inaccessible address, VA 0xbbe194)
Context:
SegSs: 0x2b
Rsp: 0x5a002f7790
SegCs: 0x33
Rip: 0x7ff83a2c7093
EFlags: 0x10206
Rax: 0xbbe194
Rcx: 0x7ff83a557205
Rdx: 0x1b1dd05c250
Rbx: 0x5a002fa060
Rbp: 0x5a002f77b0
Rsi: 0x5a002fa098
Rdi: 0x5a002f7be0
R8: 0x7ff652a83b10
R9: 0x0
R10: 0x5a002f7db0
R11 0x5a002f7d88
R12: 0x0
R13: 0x0
R14: 0x1b1dcf3b3c0
R15: 0x0
SegDs: 0x2b
SegEs: 0x2b
SegFs: 0x53
SegGs: 0x2b
```
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mull …
> Log unhandled exceptions on Windows

- talpid-core/build.rs
To elude a rather heavy handed `cargo clean` when trying out different changes in any of the binary artifacts we link against, I've added a small change to `build.rs` of `talpid-core` to rebuild the library any time any of the binary artifacts for the target platform change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1256)
> Rerun build scripts if binary artifacts have changed

- mullvad-daemon/src/windows_exception_logging.rs
I didn't want to comment on this in your original PR. Because your code worked and it was nothing wrong with it. But I felt I wanted to experiment a bit with the matching and see if I could do it a bit less verbose. See if you like it or not and feel free to ask questions or come with feedback :)
My main goal here was to reduce duplication of `Some(Cow::Borrowed(`. But I also employed the wildcard import trick I mentioned in your PR. These things together allows all match arms to be a single line.
The early return in the match allows us to abort on invalid code and make the type of `name` a `&'static str`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1257)
> Simpler code for converting ExceptionCode to a string

- CHANGELOG.md
- talpid-core/src/dns/linux/resolvconf.rs
`dnsmasq` can be configured to ignore any externally configured DNS servers, which breaks `resolvconf` integration with it. Since there's no way to externally verify this (`resolvconf -l` will return the list of DNS servers that _should be set_), when using `resolvconf`, the daemon will verify if `dnsmasq` is running and whether it's configured to ignore external configurations. In case it is misconfigured and running, the daemon will not use `resolvconf` to manage DNS and will fall back to managing DNS by just manipulating `/etc/resolv.conf` manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1255)
> Verify if dnsmasq is running and misconfigured when using resolvconf

- .travis.yml
- ci/ci-rust-script.sh
- talpid-core/src/routing/mod.rs
- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-core/src/winnet.rs
We got a warning about unused `mut` on non-Windows platforms. Because we only need mutable access to the `route_handle` on Windows. I first added a stricter check for this in the CI. Then I fixed this particular instance.
Since it does indeed look correct that we need to mutate the instance on Windows I went with the simplest solution. Simply marking the warning/error as acceptable on non-Windows platforms. I wanted to make it as specific as possible, so if we ever stop mutating it on Windows we will get the warning back and thus be able to remove the `mut` altogether.
I also renamed `set_default` to `add_default` since it does look like one can add an arbitrary amount of callbacks, not just set one. Please tell me if this is wrong :)
--- …
> Deny unused mut

- dist-assets/windows/installer.nsh
- windows/nsis-plugins/src/driverlogic/context.cpp
Some return values were incorrectly treated as errors. Also, log more information when TAP identification fails.
There may be an additional problem here left related to identifying the new adapter. Hopefully the logs will be more informative if it appears again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1261)
> Fix driver error handling in Windows installer

- mullvad-daemon/src/lib.rs
- talpid-core/src/offline/dummy.rs
- talpid-core/src/offline/linux.rs
- talpid-core/src/offline/macos.rs
- talpid-core/src/offline/mod.rs
- talpid-core/src/offline/windows.rs
- talpid-core/src/routing/windows.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- talpid-core/src/winnet.rs
Currently, the daemon simply kills the tunnel state machine thread, which means that some cleanup functions aren't performed. This is because the channel for the state machine isn't closed, as one sender to it in `OfflineMonitor` is kept around until the tunnel thread exits. I fixed this using a weak reference.
There should be enough time for it to stop on its own now, but probably one should also join the other thread.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1263)
> Close tunnel thread when the daemon exits

- CHANGELOG.md
- talpid-core/src/routing/linux/mod.rs
- talpid-core/src/routing/mod.rs
These changes indirectly decrease the chance of Go's runtime panicking due to memory corruption - this is achieved by not using `tokio-subprocess`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1268)
> Linux routing use sync subprocess

- CHANGELOG.md
- mullvad-cli/src/cmds/relay.rs
I've added another subcommand to the `mullvad relay set` command to allow users to specify which tunnel protocol to use. I'm unsure if `mullvad relay set tunnel` to `mullvad relay set tunnel-constraints` to better signify that the command only sets constraints by which the tunnel is selected rather than selecting a specific tunnel type to be used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1270)
> Add tunnel-protocol subcomand to CLI

- talpid-core/src/routing/macos.rs
This is me fixing a clear case of me applying the infamous CtrlC-CtrlP methodology.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1271)
> Fix error message for routing in MacOS

- Dockerfile
- README.md
Fixes #1269 
Seems gconf is indeed not a dependency of Electron any more: https://github.com/electron/electron/pull/19498
So we can safely remove it from our readme and docker file. This should have no impact on actual releases since they have not depended on gconf for a long time. But this makes the documentation more in sync with reality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1272)
> Remove gconf2 cruft from readme

- CHANGELOG.md
- mullvad-cli/src/cmds/mod.rs
- mullvad-cli/src/cmds/reconnect.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-ipc-client/src/lib.rs
- mullvad-jni/src/daemon_interface.rs
I had an idea a long time ago. But I did not bring it up with anyone until today. To have a button to allow reconnects without ever opening up the firewall. So the same as hitting disconnect/cancel and then "secure my connection" again directly after, but without having a small window of possible leaks.
Jan and Richard liked the idea.
* Allows you to cycle to a new server at any point
* Allows you to retry a connection attempt if stuck in the blocked state
* Allows aborting connection attempts that take longer than you expect them to take etc.
I did nothing in the GUI yet. This is more of a side-feature, so I did not want to spend much time on it suddenly. But implementing it in the CLI was very very simple. So I went ahead and did so. Now we have the feature here. We can add it to the …
> Implement reconnect cli command

- talpid-core/src/winnet.rs
The function signature for `WinNet_ActivateRouteManager` was wrong Rust-side of the daemon, so the daemon code wasn't checking if an invocation was successful. This fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1280)
> Check if WinNet_ActivateRouteManager succeeds

- windows/winutil/src/winutil/migration.cpp
The backup created by Windows update may be owned by "built-in administrators" rather than SYSTEM.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1278)
> Fix ownership check in settings migration after Windows updates

- README.md
For VS2019 the path to MSBuild.exe was wrong. It seems to now be under `Current` rather than `<VERSION>`. I don't know if it was correct or wrong before either, but at the moment it's definitely not pointing to where the binary is :)
Anything else we have realized we need to update?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1290)
> Update to correct PATH for MSBuild.exe

- mullvad-daemon/src/lib.rs
While rebasing the offline monitor for Android, I noticed that the offline events weren't properly sent to the tunnel state machine after the tunnel was connected for the first time. After investigating the issue, I think the cause is that `Arc::make_mut` ensures that it is the sole owner of the inner data (the channel sender), so the `Weak` reference used in the offline monitor is closed.
This PR tries to fix that by not closing other references, and manually cloning the inner type so that the sink can use its own handle to the sender channel.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1295)
> Fix channel closing prematurely when sending tunnel command

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/ConnectionProxy.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/LocationInfoCache.kt
- android/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt
- android/src/main/kotlin/net/mullvad/talpid/util/EventNotifier.kt
Previously, the code to fetch the location based on the IP address would retry in case of failure. This did not consider if the app new that all attempts would fail because the device had no connectivity. The consequence was that it entered an infinite retry loop, which kept the device awake and kept writing error messages to the log file.
This PR makes sure the location fetch is only performed if there is connectivity.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1299)
> Stop location fetch when offline

- android/src/main/kotlin/net/mullvad/mullvadvpn/model/Relay.kt
This PR fixes an inverted condition check that led to only WireGuard relays not being displayed in the relay list.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1301)
> Fix check if relay has WireGuard tunnels

- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/RelaySelectorTests.xcscheme
- ios/MullvadVPN/MullvadEndpoint.swift
- ios/MullvadVPN/RelaySelector+RelayCache.swift
- ios/MullvadVPN/RelaySelector.swift
- ios/MullvadVPNTests/Info.plist
- ios/MullvadVPNTests/RelaySelectorTests.swift
Git checklist:
1. Add naive implementation of `RelaySelector`
1. Add `MullvadEndpoint` struct with all information needed to establish the connection with a single relay.
1. Add basic tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1297)
> Add naive relay selector on iOS

- mullvad-jni/src/lib.rs
- talpid-core/src/offline/android.rs
- talpid-core/src/tunnel/tun_provider/android.rs
- talpid-types/src/android/mod.rs
This PR implements a small improvement following the suggestion given in https://github.com/jni-rs/jni-rs/issues/217
Instead of working around the missing `Clone` implementation for `JavaVM`, it wraps the `JavaVM` with an `Arc`. This allows replacing the custom `Clone` implementation with a `derive(Clone)`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1302)
> Use `Arc<JavaVM>` in `AndroidContext`

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/NotificationBanner.kt
Previously, if the app was showing the `ConnectFragment` and a new version event is received, the app would try to update the `NotificationBanner` from the wrong thread (i.e., out of the UI thread). This led to a crash.
This PR makes sure the update is scheduled on the main UI thread.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1304)
> Fix `NotificationBanner` update on wrong thread

- CHANGELOG.md
This PR just moves a change log entry to the correct location, since it was accidentally placed in the `Security` section instead of the `Fixed` section.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1307)
> Fix position of change log entry

- ios/MullvadVPN/NEVPNStatus+Debug.swift
- ios/MullvadVPN/TunnelManager.swift
Git checklist:
This PR adds `TunnelManager` for the GUI app. 
The `TunnelManager` responsibilities:
- Create and destroy system VPN tunnels (`NETunnelProviderProtocol`). Primarily we maintain a single VPN tunnel
- General tunnel management, i.e: start and stop
- Map system `NEVPNStatus` to `TunnelState` enum. `TunnelState` provides additional information about the state of the tunnel including the hostname and relay IP. This information is normally received from the packet tunnel process using IPC before the `TunnelState` is propagated to the rest of the app. (The packet tunnel code is coming in the later PRs)
- Maintain tunnel configuration and share it with the system VPN tunnel using a …
> Add TunnelManager

- CHANGELOG.md
- mullvad-daemon/src/relays.rs
To improve the chances of connecting, attempt connecting using port 53 after 2 failed connection attempts, when using WireGuard without any port constraints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1308)
> Improve wireguard port selection

- CHANGELOG.md
- mullvad-daemon/src/relays.rs
Fixing the new and improved relay selection algorithm to actually use port 53 when we fail after the 2nd attempt (on 3rd and 4th) rather than the 6th and 7th.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1310)
> Fix improved port selection for WireGuard

- ios/MullvadVPN/Bundle+MullvadVersion.swift
- ios/MullvadVPN/Info.plist
- ios/MullvadVPN/SettingsAccountCell.swift
- ios/MullvadVPN/SettingsCell.swift
- ios/MullvadVPN/SettingsViewController.swift
Git checklist:
1. Store version suffix `MullvadVersionSuffix` (i.e dev1, dev2, etc..) in `Info.plist`. Use it to display the exact version in the UI.
1. Hot fix the tintColor of the system disclosure view. For some reason, the disclosure arrow would change the tint color when switching between apps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1311)
> Add version suffix on iOS

- CHANGELOG.md
- talpid-core/src/firewall/linux.rs
Stops an attacker on the same network from discovering the tunnel IP of the device running this app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1315)
> Stop CVE-2019-14899 by dropping packets to tunnel IP

- CHANGELOG.md
- Cargo.lock
- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/system_service.rs
Notably, two configuration items are changed:
- The list of dependencies (adding `NSI`).
- The service SID info (set as `UNRESTRICTED`).
The code that handles service installation is also updated so ensure the configuration on an existing service is refreshed. This, however, turned out to not be required since in practice we always remove the previous service before installing the new one, during an update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1313)
> Windows: Fix service config

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
A bug was detected when a user updates the app. It takes a while for the update version to update the app version info cache. In the meantime, the daemon still sends the stale app version info to the UI. This means that the UI handles a state where `isOutdated == true` but the upgrade target version is the same as the current version. It would then show the notification banner, but include `null` as the target upgrade version.
This PR fixes that by overriding the "app version info" to make sure `isOutdated` is always `false` if the target update version is the same as the current version.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1316)
> Fix upgrade to null message

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/talpid/ConnectivityListener.kt
Apparently, not every connectivity related intent will contain the network information. Therefore, requesting such information from the `Intent` will return `null` and lead to a crash when trying to use that information.
This PR fixes the issue by checking if the information is `null` first. If it is, connectivity is rechecked manually. Otherwise, the previous behavior is kept.
This PR also includes an extra precaution by filtering out `null` `NetworkInfo` objects when obtaining the information of all networks in the `checkConnectionState` method.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1317)
> Fix crash in `ConnectivityManager` due to missing `NetworkInfo`

- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/PacketTunnel.xcscheme
- ios/MullvadVPN/AutoDisposableSink.swift
- ios/MullvadVPN/Data+HexCoding.swift
- ios/MullvadVPN/IPEndpoint.swift
- ios/MullvadVPN/MullvadEndpoint.swift
- ios/MullvadVPN/MullvadVPN.entitlements
- ios/MullvadVPN/PacketTunnelIpc.swift
- ios/MullvadVPN/RelaySelector.swift
- ios/PacketTunnel/AnyIPEndpoint+DNS64.swift
- ios/PacketTunnel/AnyIPEndpoint+Wireguard.swift
- ios/PacketTunnel/Info.plist
- ios/PacketTunnel/PacketTunnel.entitlements
- ios/PacketTunnel/PacketTunnelProvider.swift
- ios/PacketTunnel/PacketTunnelSettingsGenerator.swift
- ios/PacketTunnel/WireguardCommand.swift
Git checklist:
1. Add DNS 6-ot-4 resolver
1. Add extension to convert `NWEndpoint` to the string representation expected by Wireguard
1. Add tunnel settings generator:
1. Network configuration: DNS, IP
1. Wireguard configuration
1. Add Packet tunnel implementation that has the following responsibilities:
1. Load tunnel configuration from Keychain
1. Use relay selector to pick a relay
1. Set up network configuration: DNS, IP
1. Bootstrap Wireguard
1. Handle network changes , resolve the relay IPs (DNS 6-to-4) since iOS does not do that automatically, update Wireguard configuration accordingly
1. Handle IPC messages (see `handleAppMessage`)
--- …
> Add packet tunnel

- Cargo.lock
- android/src/main/kotlin/net/mullvad/mullvadvpn/MullvadDaemon.kt
- mullvad-jni/Cargo.toml
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/lib.rs
Previously, a single global `DaemonInterface` instance was used to communicate with the daemon thread. This meant that multiple `MullvadDaemon` class instances would eventually communicate with the same daemon thread.
This PR refactors that, so that the Rust and Java sides are better aligned. The `DaemonInterface` instance is now stored in the `MullvadDaemon` daemon. While in theory this allows multiple daemon threads to execute at the same time, the Java side treats the `MullvadDaemon` as a singleton object. It is only recreated when restarting the daemon thread.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1318)
> Store `DaemonInterface` inside `MullvadDaemon` Java object

- mullvad-jni/src/jni_event_listener.rs
- mullvad-jni/src/lib.rs
This PR enables the `#![deny(rust_2018_idioms)]` attribute, so that the Rust 2018 edition idioms are enforced. A few elided lifetimes are made more explicit to comply with the attribute.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1327)
> Use Rust 2018 edition idioms in `mullvad-jni`

- CHANGELOG.md
- talpid-core/src/firewall/macos.rs
When going through the security docs I'm writing I noticed how the documentation we had did not specify protocol for the DHCP related rules. And since it should only use UDP I added that to the documentation to make it stricter.
At the same time I noticed that on macOS we did not limit the rules for acting as a DHCP server in the case `allow_lan` was enabled to only UDP. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1321)
> Limit DHCPv4 server firewall rules to UDP only

- CHANGELOG.md
- talpid-core/src/routing/linux/change_listener.rs
- talpid-core/src/routing/linux/mod.rs
- talpid-core/src/routing/macos.rs
- talpid-core/src/routing/mod.rs
- talpid-core/src/routing/unix.rs
- talpid-core/src/routing/windows.rs
To better maintain both codebases, I've separated out Windows' routing manager from
the unix routing implementations to better ensure correctness. This allows for a trivial fix for lifetime issues with the route manager on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1325)
> Separate Windows routing implementation from Unix

- windows/winfw/src/winfw/fwcontext.cpp
- windows/winfw/src/winfw/mullvadguids.cpp
- windows/winfw/src/winfw/mullvadguids.h
- windows/winfw/src/winfw/rules/restrictdns.cpp
- windows/winfw/src/winfw/rules/restrictdns.h
Add extra permissive filter in the blacklist sublayer to allow packets going to
the tunnel host if the daemon is trying to connect to the tunnel over port 53.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1338)
> HACK: Allow relays on port 53 in WinFw

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/LocationInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
Previously, the `LocationInfoCache` would retry to fetch the location after each failure immediately. If the device had some connectivity issues (that weren't detected by the `ConnectivityListener`), the retries would occur very quickly in a tight loop. This meant that the device wouldn't get the chance to idle, and would drain battery quickly.
This PR fixes that by implementing an exponential back-off strategy for delaying the retries, limited to a maximum of 30 minutes.
The PR also fixes another scenario where closing the UI still kept fetching the location information.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1339)
> Throttle geo. IP location fetch retries

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/RelayListListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/SettingsListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
This PR creates two `ServiceConnection` classes in the `ui` and the `service` packages. 
The `MullvadVpnService` is refactored so that it sends `service.ServiceConnection` instances every time it has finished setting up. When it is stopping, it will send a `null` marker.
The `service.ServiceConnection` class contains the objects exported by the service, which include the daemon, the connection proxy and the connectivity listener.
The `MainActivity` handles service connection events by wrapping it with a `ui.ServiceConnection`, which initializes the extra helper classes from the `dataproxy` package.
Future PRs will forward this `ui.ServiceConnection` object to the UI fragments, but currently it is only used as the source of the classes exported from the `MainActivity` to the fragments.
The …
> Create `ServiceConnection` classes

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
- talpid-core/Cargo.toml
- talpid-core/src/tunnel/tun_provider/android.rs
I've added code that waits for the tunnel device to be readable before it is returned to be used in the connecting and connected and blocked states of the tunnel state machine. This ensures that higher up the stack, we can rely on the existence of the tunnel device to ensure that traffic is being routed through it.
I've also added some small fixups to the refactor that was merged yesterday - pretty much everything to do with class names that have now changed not being changed everywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1332)
> Verify tunnel device is up on Android

- dist-assets/windows/installer.nsh
- windows/nsis-plugins/nsis-plugins.sln
- windows/nsis-plugins/src/cleanup/cleanup.cpp
- windows/nsis-plugins/src/driverlogic/driverlogic.cpp
- windows/nsis-plugins/src/error.h
- windows/nsis-plugins/src/pathedit/pathedit.cpp
- windows/nsis-plugins/src/registry/registry.cpp
- windows/nsis-plugins/src/tray/tray.cpp
Most functions simply return 0 for failure and 1 for success. We can simplify things by sharing defined constants for functions like these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1336)
> Get rid of duplicate NSIS constants

- mullvad-cli/src/cmds/tunnel.rs
This was named `generate` when you had to run this manually. It should probably be called `regenerate` now, consistent with the GUI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1349)
> Rename 'key generate' to 'key regenerate' in the CLI

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RemainingTimeLabel.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceAwareFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
This PR refactors the fragments so that they have a consistent way to access the functionalities provided by the service. The common code is abstracted away in two super classes.
`ServiceAwareFragment` handles attaching the fragment to the `MainActivity` and registering for service connection events. These events can then be handled by sub-classes with two methods, `onNewServiceConnection` and `onNoServiceConnection`.
`ServiceDependentFragment` is a sub-class of `ServiceAwareFragment` for fragments that require the service connection in order to be shown. It assumes that the service connection will be available as long as the fragment is active, and provides properties for all functionalities exported by the service connection. In future PRs, there will be code for handling what should be …
> Create fragment helper classes

- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
This PR is a clean-up PR, refactoring a few things that became unnecessary after adding the `ServiceConnection`.
It does contain a small fix, since now the reset of the service is improved so that `onRebind` only restarts it if the service is actually stopping. Previously, that would only be true for the first time, and since the `resetComplete` variable was never reset to `null`, it would execute `onRebind` multiple times even if it wasn't stopping afterwards.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1351)
> Clean-up unnecessary code after deploying `ServiceConnection`

- windows/nsis-plugins/src/driverlogic/context.cpp
There's been one report of `NciGetConnectionName` failing. Unknown why. But there's no reason to fail everything in this case, since it may be that some errors only affect network adapters irrelevant to us. Thus, we should simply log the error and skip the adapter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1354)
> Increase robustness of network adapter iteration

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/IPEndpoint.swift
- ios/MullvadVPN/MullvadEndpoint.swift
- ios/PacketTunnel/PacketTunnelProvider.swift
- ios/PacketTunnel/PacketTunnelSettingsGenerator.swift
- ios/PacketTunnel/WireguardCommand.swift
- ios/PacketTunnel/WireguardConfiguration.swift
- ios/PacketTunnel/WireguardDevice.swift
Git checklist:
1. Move all WireGuard related routine to a separate class `WireguardDevice`
1. Add `WireguardConfiguration` to hold private key and peers and methods to transition between different configurations by generating a set of `WireguardCommand`s.
1. Retry DNS64 resolution for peers on failure (only once)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1360)
> Move WireGuard related routine to WireguardDevice

- ios/MullvadVPN/JsonRpc.swift
- ios/MullvadVPN/MullvadAPI.swift
- ios/MullvadVPN/MutuallyExclusive.swift
- ios/MullvadVPN/RelayCache.swift
- ios/MullvadVPN/TunnelManager.swift
- ios/MullvadVPN/WireguardPrivateKey.swift
Git checklist:
1. Add generic `ResponseCode` to `JsonRpcResponseError`. Ergonomic change to automate decoding of `Int` error codes into `enum`s.
1. Scope `MullvadAPIError` into `MullvadAPI` as `Error`.
1. Rework `MutuallyExclusivePublisher` to use `Subscription`. This improves thread safety, cancellation handling and fixes the issue when the publisher going out of scope was taking down the downstream subscribers along with it. This was spotted when using `receive(on:)` publishers in the circumstance where the upstream publisher failed with error.
1. Add `creationDate` metadata to `WireguardPrivateKey` and introduce `WireguardPublicKey` structure.
1. Add `TunnelManager` facilities to obtain the …
> Regenerate private key on iOS

- ios/MullvadVPN/Assets.xcassets/Palette/Contents.json
- ios/MullvadVPN/Assets.xcassets/Palette/Danger.colorset/Contents.json
- ios/MullvadVPN/Assets.xcassets/Palette/Primary.colorset/Contents.json
- ios/MullvadVPN/Assets.xcassets/Palette/Secondary.colorset/Contents.json
- ios/MullvadVPN/Assets.xcassets/Palette/SubCell.colorset/Contents.json
- ios/MullvadVPN/Assets.xcassets/Palette/SubSubCell.colorset/Contents.json
- ios/MullvadVPN/Assets.xcassets/Palette/Success.colorset/Contents.json
- ios/MullvadVPN/Base.lproj/LaunchScreen.storyboard
- ios/MullvadVPN/Base.lproj/Main.storyboard
- ios/MullvadVPN/UIColor+Palette.swift
Git checklist:
This PR formalises the color palette on iOS by introducing:
1. Formalize color palette using color assets
1. An extension for `UIColor` to access those colors.
1. Update to Storyboard to switch from absolute color values to color assets. You'd likely inspect the diff and find that Storyboard holds a copy of absolute colors values defines in color assets. This is surprising but I guess Xcode syncs those between each other.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1362)
> Formalize color palette on iOS

- CHANGELOG.md
- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/winnet.rs
This PR addresses a couple of issues related to error messages:
* `TunnelMonitor::start` (through `WinNet_GetTapInterfaceIpv6Status()`) looks for the TAP adapter alias while attempting to enable IPv6 (using `ensure_ipv6_can_be_used_if_enabled`), but the block reason becomes simply `EnableIpv6Error` even if the underlying error is that the TAP adapter is missing. It should be `TapAdapterProblem`.
\
**Fix**: Distinguish between IPv6 being disabled and failure to obtain IPv6 status, so we can handle the missing TAP case differently.
* Separately from the above issue: If `ConnectingState::enter` fails to start the tunnel due to a TAP problem, it doesn't pass the specific block reason to `ErrorState::enter`, i.e. `TapAdapterProblem`. Instead, it sets the block reason to `StartTunnelError`. …
> Fix TAP error message regression on Windows

- ci/buildserver-build.sh
We're missing symbols for the daemon, CLI, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1365)
> Include additional debug symbols (.pdb) in builds

- CHANGELOG.md
- talpid-core/src/dns/linux/static_resolv_conf.rs
Some users have reported issues with running our daemon when no `/etc/resolv.conf` exists. As such, I've changed it so that when we're reading it, if the file does not exist, we assume an empty config and continue on as usual. The side effect is that after disconnecting from our tunnel, there will exist an empty `/etc/resolv.conf` file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1373)
> Create empty dns config if /etc/resolv.conf doesn't exist

- talpid-types/src/lib.rs
- talpid-types/src/net/mod.rs
Remove deprecated uses of `Error::description()`.
I've only removed the implementations and uses of `description()` in our types, but I've not checked if this breaks any logging in our case. I doubt it does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1370)
> Remove deprecated use of Error::description()

- .travis.yml
- ci/ci-rust-script.sh
- talpid-core/src/tunnel/tun_provider/android.rs
We got an unused variable warning on Android. This seems like the type of warning we want to guard ourselves against.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1358)
> Deny unused variables in Rust on CI

- ios/PacketTunnel/Logging.swift
Git checklist:
Not sure if it's a victim of rogue rebase or I simply forgot to commit that file, but this has to be a part of PacketTunnel and I am pretty sure that Xcode project references this file.
This file simply mentions the log categories used in PacketTunnel, there are three separate categories:
1. WireGuard-go log (aka `WireGuard`)
1. Tunnel Provider log
1. `WireguardDevice` class log
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1375)
> Add log categories

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RemainingTimeLabel.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
Previous PRs added the `ServiceDependentFragment` super class for fragments that required a connection to the service to operate correctly. This PR continues that work by specifying what should be done when there is no service connection or when it is lost.
Two alternatives are available, the app can go back to the previous fragment, or it can return to the launch screen to await a new service connection.
Most fragments simply had to specify which fallback alternative it used, but the `SettingsFragment` needed some refactoring to make sure no proxy classes were used while there was no service connection.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app …
> Handle no service connection in fragments

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/version_check.rs
- mullvad-daemon/src/wireguard.rs
- talpid-core/src/mpsc.rs
This PR changes the version updater so that it can be stopped when the daemon is stopped.
It does this by using an `UnboundedSender` instead of a closure to notify of version updates. The `UnboundedSender` has a helpful `is_closed` method that can determine if the receiving end has been closed. If it has, the daemon has stopped, and therefore the version updater should stop as well.
In order to use an `UnboundedSender` the `std::sync::mpsc::Sender` that was used for internal daemon events had to replaced. In general, the change is pretty similar for all cases, where `.send` becomes `.unbounded_send`. `IntoSender` was also updated to use `UnboundedSender`, which makes the conversion even simpler.
The only additional complexity is in the receiving end, since `UnboundedReceiver` is a …
> Stop version updater on shutdown

- ci/buildserver-build.sh
- ci/buildserver-upload.sh
This PR basically addresses two issues with the build servers. The main thing I'm fixing here is to make it automatically upload pdb files for Windows debugging to the build server artifact host. But while doing so I found we got the wrong hash when doing `git rev-parse $ref` where `$ref` was a tag. Apparently one has to do `git rev-parse $ref^{commit}` to get the hash of the *commit*. `rev-parse` is a strange low level command. I realized later I could have used `git show-ref -s $ref` instead which is a higher level command. But I found that out after getting this to work so I did not feel like fixing what already was fixed.
I also changed so instead of sending a second argument to `build_ref()` being either tag or branch. I instead made the single argument `ref` the "full path" to the …
> Upload PDB files to built artifact host

- CHANGELOG.md
- talpid-core/src/process/openvpn.rs
20 seconds is already long. But multiple users report
that their tunnels drop out more frequently than
on vanilla OpenVPN. So let's see if increasing this helps
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1378)
> Increase OpenVPN ping timeout from 20 to 25 seconds

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNTests.xcscheme
- ios/MullvadVPN/Account.swift
- ios/MullvadVPN/AccountExpiry.swift
- ios/MullvadVPN/AccountViewController.swift
- ios/MullvadVPN/Base.lproj/Main.storyboard
- ios/MullvadVPN/ConnectViewController.swift
- ios/MullvadVPN/LoginViewController.swift
- ios/MullvadVPN/MullvadAPI.swift
- ios/MullvadVPN/SettingsAccountCell.swift
- ios/MullvadVPN/TunnelManager.swift
- ios/MullvadVPN/UIAlertController+Error.swift
Git checklist:
This PR focuses around showing user friendly errors to the user. Implementing `LocalizedError` protocol for custom `Error`s is a standardised way to provide error descriptions, failure reasons and even suggestions how to fix the error.
1. Implement `LocalizedError` for the errors presented to users.
1. Present some of errors using alert view
1. Make `AccountExpiry.formattedRemainingTime` fallible to avoid crash on unwrapping, delegate the error handling to the caller.
1. Add `UIAlertController` to simplify showing `LocalizedError`s. 
`errorDescription` is used as a title, and `failureReason` as a description in alerts. In some cases one or another is not provided. Some of the …
> Localize errors

- CHANGELOG.md
- mullvad-daemon/src/wireguard.rs
Currently, the daemon will execute an RPC against master every 5 seconds if there are too many keys added to an account, as part of automatic key replacement. This is incredibly noisy. To fix this, I've added some code to distinguish between different error kinds and in the case that there are too many keys added to an account, the daemon will not try to replace the key. Notably, the fact that the API returns this specific error means that the key that the client has has been manually removed from the account by the user, so the client should probably not try to automatically add a new one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1371)
> Stop automatic key rotation when account has too many keys

- CHANGELOG.md
- talpid-core/src/tunnel/wireguard/mod.rs
Bumping WireGuard ping tmieout from 7 to 15 seconds in hopes of increasing stability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1383)
> Bump WireGuard ping timeout

- CHANGELOG.md
- dist-assets/windows/installer.nsh
- windows/nsis-plugins/nsis-plugins.sln
- windows/nsis-plugins/src/string/dllmain.cpp
- windows/nsis-plugins/src/string/stdafx.cpp
- windows/nsis-plugins/src/string/stdafx.h
- windows/nsis-plugins/src/string/string.cpp
- windows/nsis-plugins/src/string/string.def
- windows/nsis-plugins/src/string/string.vcxproj
- windows/nsis-plugins/src/string/string.vcxproj.filters
- windows/nsis-plugins/src/string/targetver.h
Changes:
* Occasionally when upgrading, the existing service cannot be deleted (resulting in the error "service marked for deletion" (1072) when the service is registered). The root cause appears to be that the running daemon process refuses to quit. Ideally, whatever the cause of that is should be fixed. As a fallback, though, it makes sense to kill the old process, which is what the changes in this PR do.\
I cannot reproduce the issue easily, but I have a VM session where this reliably occurs.
* Add NSIS plugin for extra string manipulation. Existing functions like `StrStr` or `IndexOf` refuse to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1382)
> Fix "service marked for deletion" issue

- CHANGELOG.md
I already merged the submodule bump to master. But I realized this should really be in the changelog. So here comes the PR for the changelog entry. Does this explanation of the issue/fix sound reasonable to you?
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1384)
> Add changelog entry about openssl.cnf escalation attack

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- mullvad-jni/src/lib.rs
Previously, the daemon could crash in certain situations and the UI would still be presented, but in a stale state and all requests to the daemon would fail.
This PR changes the `MullvadVpnService` so that it can detect when the daemon thread stops and handle it accordingly. If it has stopped unexpectedly, the service is restarted so that the UI is notified that the connection to the service has been lost and can then reconnect to it when it's available with a new daemon thread running.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1385)
> Restart service on daemon crash

- CHANGELOG.md
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/version_check.rs
Fixes a minor version check problem where the app mistakenly claimed that the version was still outdated following an update. It was caused by the "outdated" flag being cached.
(This should have cleared after five minutes, since that was when the cache was first updated. But if that failed, it would linger for six hours or more.)
Cf. #1342.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1388)
> Fix incorrect "update available" notifications

- CHANGELOG.md
- talpid-core/src/tunnel/mod.rs
Connecting to the tunnel could fail if using IPv6 and WireGuard on Windows with a broken or non-existent TAP adapter, because the IPv6 check would unconditionally look up the IPv6 status of the (OpenVPN) TAP adapter. Fixed by only doing this when using OpenVPN.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1391)
> Fix WireGuard IPv6 issue on Windows

- ios/PacketTunnel/WireguardDevice.swift
Git checklist:
Previously when setting up a global logger for WireGuard, I used to dispatch the call to `wgSetLogger` on a `loggingQueue` which caused the first messages emitted by WireGuard-go to not be delivered at all.
This PR makes sure that logger access happens on a background queue, however calls `wgSetLogger` immediately, since it's supposed to be thread safe and even if the closure given to it is called right after, it will be scheduled on a serial `loggingQueue` and will happen after the `WireguardDevice.wireguardLogHandler` is set.
--- …
> Fix race condition when setting up a global WireGuard logger

- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
- android/src/main/res/layout/missing_service.xml
This PR performs a few fixes to avoid some crashes that occurred when certain conditions where right.
First of all, the `MainActivity` now requests the service to stop earlier. 
Secondly, the service will now notify a loss of connection immediately after it realizes that the daemon thread has stopped.
And lastly, the `ServiceDependentFragment` was refactored so that the lifecycle methods are guarded correctly. Previously, the initialization code would detect that the service connection was missing, but the lifecycle methods still had to be called before handling the missing connection by (for example) switching to a new fragment. Since the sub-class always assumed that the connection was available, the lifecycle methods would perform some calls that lead to crashes due to the missing …
> Fix some race conditions when restarting the app

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
The VPN permission granted to the app by the user can be revoked at any time, either when the user manually revokes it or when the user grants the permission to a different VPN app.
Previously, when the permission was revoked nothing was done, which led to a crash when certain operations were attempted when reconnecting. This PR changes that so that when the permission is revoked, the service is stopped.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1392)
> Handle loss of VPN permission

- mullvad-daemon/src/lib.rs
Attempt to reconnect immediately after the key has been replaced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1333)
> Reconnect to tunnel after WireGuard key has been replaced

- CHANGELOG.md
- Cargo.lock
- mullvad-jni/Cargo.toml
- mullvad-types/Cargo.toml
- talpid-core/Cargo.toml
- talpid-types/Cargo.toml
Previously, converting an `IpAddr`, `Ipv4Addr` or `Ipv6Addr` into a Java `InetAddress` object would leak a `Class` object reference in the local reference table. After a while, the app could crash due to overflowing the local reference table.
This PR updates the `jnix` dependency to a version that includes a fix for the local reference leak.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1394)
> Update `jnix` dependency to fix JNI local reference leak

- mullvad-daemon/src/wireguard.rs
futures::sync::mpsc::UnboundedSender::<T>::send': renamed to `unbounded_send`, with the latter version being deprecated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1396)
> Use unbouded_send() instead of send()

- mullvad-cli/Cargo.toml
- mullvad-daemon/Cargo.toml
- mullvad-ipc-client/Cargo.toml
- mullvad-jni/Cargo.toml
- mullvad-paths/Cargo.toml
- mullvad-problem-report/Cargo.toml
- mullvad-rpc/Cargo.toml
- mullvad-tests/Cargo.toml
- mullvad-types/Cargo.toml
- talpid-core/Cargo.toml
- talpid-ipc/Cargo.toml
- talpid-openvpn-plugin/Cargo.toml
- talpid-types/Cargo.toml
The email address used in the author field is slowly being phased away, so it should be removed from all places it appears in.
This PR updates all package manifests to remove the email from the authors' field.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1397)
> Remove usage of Mullvad email in crate manifests

- dist-assets/windows/installer.nsh
- windows/nsis-plugins/nsis-plugins.sln
- windows/nsis-plugins/src/msiutil/dllmain.cpp
- windows/nsis-plugins/src/msiutil/msiutil.cpp
- windows/nsis-plugins/src/msiutil/msiutil.def
- windows/nsis-plugins/src/msiutil/msiutil.vcxproj
- windows/nsis-plugins/src/msiutil/msiutil.vcxproj.filters
- windows/nsis-plugins/src/msiutil/stdafx.cpp
- windows/nsis-plugins/src/msiutil/stdafx.h
- windows/nsis-plugins/src/msiutil/targetver.h
Some users have had issues with Wintun. By default, the log ends up in the temp directory, and `msiexec` only lets you specify a new file for output. The API was used so that the logging could be directed to install.log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1395)
> Log Wintun install

- dist-assets/windows/installer.nsh
- windows/nsis-plugins/src/pathedit/pathedit.cpp
On some systems, our changes to the system PATH are not reflected in `cmd` when it is run from Win+R. In this case, PATH is inherited from `explorer.exe` rather than read directly from the registry. We already notify `explorer.exe` of the change, which works for some users but not others.
The main reason seems to be that the installer would sometimes restart `explorer.exe` before the PATH was updated, which could result in a race condition. There may also have been a problem relating to Unicode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1401)
> Fix system PATH update

- README.md
- build.sh
- ci/buildserver-build.sh
This is desirable to prove authorship, and because some AV/firewall software complains about unsigned executables. Electron builder signs too many files, including files that are already signed by Microsoft, etc., so select files are signed in `build.sh` instead.
More files could be signed, eg Windows modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1402)
> Sign select binaries for release builds (Windows)

- Cargo.lock
- mullvad-jni/Cargo.toml
- mullvad-types/Cargo.toml
- talpid-core/Cargo.toml
- talpid-types/Cargo.toml
This PR bumps the version of `jnix` in order to include another fix for a local reference leak when converting an `IpAddr` (or its related types) to an `InetAddress`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1411)
> Update `jnix` dependency to version `0.1.2`

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/wireguard.rs
The existing timer didn't account for computers being suspended, potentially delaying key replacement by a long period of time. Fixed by using a repeating timer with a short interval.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1410)
> Fix suspend issue for WG key rotation

- ios/MullvadVPN/AccountViewController.swift
- ios/MullvadVPN/MullvadAPI.swift
- ios/MullvadVPN/TunnelManager.swift
Git checklist:
1. Add a call to master to remove the WireGuard key from our servers during log out. 
1. Show a modal alert message that blocks the interface until the log out is done.
1. Ignore Keychain errors when reading the WireGuard public key during log out. This ensures that the user would be able to log out, if for some reason, the app crashed half way through after removing the keychain record. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1412)
> iOS: Remove WireGuard key on logout

- dist-assets/windows/installer.nsh
- windows/nsis-plugins/src/msiutil/msiutil.cpp
This PR addresses two problems. Firstly, the installer fails on Windows 7 when setting up Wintun. This is because file system redirection is disabled, which causes the MSI library to fail. Secondly, the NSIS stack is messed up if an error occurs while an MSI installer is run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1413)
> Fix Wintun file redirection issue on Windows 7

- README.md
With the merging of `add-wireguard-go`, the README wasn't updated that `gcc` or `clang` is a requirement to build `wireguard-go` on all platforms - a C compiler is necessary for CGo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1414)
> Add gcc to CGo requirements in README.md

- wireguard/wireguard-go/build-android.sh
Change the `wireguard-go` buildscripts for Android to cleanup after themselves a bit better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1418)
> Fix android buildscript

- gui/package-lock.json
- gui/package.json
- gui/src/main/index.ts
- gui/src/main/notification-controller.ts
- gui/src/shared/logging.ts
Git checklist:
This PR updates Electron from 6.x to 7.1.10 which should fix a number of issues including crash during the app termination. 
Due to API changes in Electron some of the calls had to be changed, highlight mode on tray icon on macOS is no longer handled by Electron so there is no way to control it anymore, so I had to remove the call to `tray.setHightlightMode()`, but that doesn't look bad on macOS so it's fine that we let the system to highlight the item on click, the highlight does not stay when the window is open.
Breaking changes document:
https://www.electronjs.org/docs/api/breaking-changes
Notable changes since v6:
- [Fixed potential hang when sending syncronous IPC messages on …
> Update to electron 7

- CHANGELOG.md
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/AdvancedSettingsStyles.tsx
- gui/src/renderer/components/Selector.tsx
- gui/src/renderer/containers/AdvancedSettingsPage.tsx
The WireGuard option in Settings > Advanced > Tunnel Protocol is now disabled if there is no wireguard key and an error message is shown below.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1419)
> Disable wireguard if no key

- CHANGELOG.md
- Cargo.lock
- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/system_service.rs
These changes allow the daemon to detect, using heuristics, that there's a pending system hibernation. It then remembers this until the machine is resumed, at which point the daemon initiates a restart of itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1405)
> Restart daemon after system hibernation

- CHANGELOG.md
- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/src/ping_monitor/mod.rs
- talpid-core/src/ping_monitor/unix.rs
- talpid-core/src/ping_monitor/win.rs
- talpid-core/src/tunnel/wireguard/connectivity_check.rs
- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-core/src/tunnel/wireguard/stats.rs
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
This PR reworks the ping monitor to use traffic data from `wireguard-go` to infer whether a WireGuard tunnel is actually working.
This brings about extra timeouts:
- timeout for seeing an increase in received traffic over the tunnel - 5 seconds
- timeout for seeing any traffic in the tunnel - 120 seconds
- ICMP timeout - 15 seconds
The new connectivity checker will infer that the tunnel is working fine by _analyzing_ the traffic data. If there seems to be an issue, an ICMP packet will be sent to the gateway. No response will be waited for, connectivity will be infered by observing whether there was an increase in received traffic after the ICMP packet was sent. To aid in delivery, an ICMP packet is being sent every 3 seconds. 
ICMP packets will be sent to the server to see if the tunnel …
> Improve connectivity check

- wireguard/wireguard-go/build-android.sh
Fix the Android WireGuard buildscript to output the 32bit x86 libraries to the correct output directory for Android builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1423)
> Fix wireguard-go buildscript for Android

- docs/security.md
Oskar noticed that the security docs make it sound like the GUI can send problem reports at will at any point in time. So we improved it to explicitly state that the user has to do this.
I also renamed the blocked state to error, since it's named that in the code since a while back. I also added that if the error state fails it will warn the user a lot. This is not true yet. But there is a card on it. So I hope the GUI part of this is implemented relatively soon.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1420)
> Improve security docs

- CHANGELOG.md
- mullvad-daemon/src/account_history.rs
- mullvad-daemon/src/lib.rs
- mullvad-rpc/src/lib.rs
Accounts can be removed manually (in the GUI), using `mullvad factory-reset`, or by logging into a new account if the account history size exceeds a defined maximum (3). When an account is removed from the local account history, the WireGuard key attached to the account is currently not removed, which may result in too many keys being generated (e.g. if the history is cleared multiple times).
This update makes an RPC request to remove the key from the account whenever it is removed from the history.
Related PR for iOS: https://github.com/mullvad/mullvadvpn-app/pull/1412
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1424)
> Remove WireGuard keys from accounts when they're removed from history

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
Previously, `MainActivity` would unsubscribe all service listeners when it was stopping (i.e., going to the background). However, that meant that once it resumed all UI fragments that were sub-classes of `ServiceAwareFragment` would still reference the old service, which might have been stopped or replaced, and wouldn't receive any updates if the service connection is dropped or replaced.
This PR makes sure the listeners are only unsubscribed when the activity is being destroyed, so that `ServiceAwareFragment`s can keep receiving service connection events.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1426)
> Only unsubscribe listeners if destroying activity

- mullvad-jni/src/lib.rs
This PR fixes the name of the function implementing the JNI method that's called when the garbage collector destroys `MullvadDaemon`.
In theory, having the JNI entrypoint with a wrong name should cause the app to crash, but such behavior hasn't been noticed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1427)
> Fix JNI method entrypoint name for destructor

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
These changes ensure the deamon will attempt to connect to a tunnel on startup if the VPN service was started by the system. This allows the application to honor the _Always On_ system setting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1429)
> Use system settings to conenct on startup

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
Previously, the app could enter a state where the notification would still be visible even after the service had stopped. In this state, the information would be stale and the buttons wouldn't work.
This PR fixes that by forcefully dismissing the notification when the service stops.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1431)
> Dismiss notification after service has stopped

- CHANGELOG.md
- gui/src/renderer/components/Account.tsx
- gui/src/renderer/components/ClipboardLabel.tsx
- gui/src/renderer/components/WireguardKeys.tsx
This PR adds functionally to copy WireGuard key when clicking on it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1428)
> Copy WireGuard key when clicking

- CHANGELOG.md
- gui/src/renderer/app.tsx
- gui/src/renderer/containers/SettingsPage.tsx
- gui/src/renderer/redux/userinterface/actions.ts
- gui/src/renderer/redux/userinterface/reducers.ts
This fixes the display of "System default" when selected in languages. The issue before was that the name selected language was saved to the redux state before the translations switched to the new language. Now only the locale code is saved in the state and is translated to a language name when needed. 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1434)
> Fix translation of "System default" after selecting that in language settings

- gui/src/renderer/components/ConnectionPanel.tsx
Text components are 1px higher now than before to make room for characters reaching below the baseline.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1435)
> Fix graphical glitch when ConnectionPanel labels overflowing

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Previously, the notification would always be visible so that the service wouldn't get prematurely killed by Android. The only way to dismiss the notification was to quit the app manually.
This PR changes that so that the notification can be swiped away when the tunnel is down and the UI is not shown. The service will still be running, but it may be killed at any time by the Android system. If the tunnel is connected or if the Mullvad app is in the foreground, the service will stay in the foreground and hence the notification will be kept always visible. As soon as the user switches to a different app, the notification may be dismissed if/when the tunnel is disconnected.
Git checklist:
--- …
> Allow notification to be dismissed when disconnected and UI is not shown

- CHANGELOG.md
- Cargo.toml
Adding `opt-level=s` to fix issues on Windows with newer CPUs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1438)
> Use `opt-level=s` for the release profile

- ios/MullvadVPN/Info.plist
Git checklist:
This PR drops the `dev1` suffix key from `Info.plist` so that the app would display `2020.1` instead of `2020.1-dev1` under the version field in Settings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1439)
> Drop dev1 suffix

- CHANGELOG.md
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
- talpid-core/src/winnet.rs
- windows/winnet/src/winnet/converters.cpp
- windows/winnet/src/winnet/converters.h
- windows/winnet/src/winnet/routing/helpers.cpp
- windows/winnet/src/winnet/routing/helpers.h
- windows/winnet/src/winnet/routing/routemanager.cpp
- windows/winnet/src/winnet/routing/routemanager.h
- windows/winnet/src/winnet/routing/types.cpp
- windows/winnet/src/winnet/routing/types.h
- windows/winnet/src/winnet/winnet.cpp
- windows/winnet/src/winnet/winnet.h
- windows/winnet/src/winnet/winnet.vcxproj
- windows/winnet/src/winnet/winnet.vcxproj.filters
These changes primarily address how routes are being installed. We're now more aggressive with overwriting existing routes.
The old logic in `addRoutes()` was a little flawed because the `Route` type doesn't map 1:1 to the `RegisteredRoute` type. Also, the `Node` type's `operator==` was flawed.
There are also a number of changes that improve and simplify the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1437)
> Windows: Improve route installation

- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
This PR fixes a `NullPointerException` that happens when the service is restarted by Android after a crash. The `Intent` that is sent to `onStartCommand` is `null` when that happens.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1441)
> Fix NPE when the service is restarted by Android

- ios/MullvadVPN/LoginViewController.swift
- ios/MullvadVPN/SelectLocationController.swift
- ios/MullvadVPN/UIColor+Palette.swift
Git checklist:
System colors on iOS adapt based on the UI mode (light or dark). We mostly use fixed colors except for placeholder in the account text field. This PR addresses this issue. Unfortunately there is no dedicated property for placeholder color so I had to use attributed string which accepts a payload with text rendering attributes to override.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1445)
> Fix placeholder color in dark mode

- ios/MullvadVPN/SelectLocationController.swift
Git checklist:
I have noticed that when leaving the Select location controller, the relay list fetch is not being cancelled. This is due to `loadDataSubscriber` being retained by the controller itself and `handleEvents` closures retaining `self` too. Therefore, the controller instance will not be deallocated until after `handleEvents` executed. This PR changes the retain policy to `weak` enabling controller to go away earlier, i.e when user dismisses it manually, and in turn cancel the relay list fetch, i.e. if there was a networking request happening, it would get cancelled.
--- …
> Use weak references in handleEvents

- dist-assets/windows/installer.nsh
- windows/driverlogic/src/driverlogic.cpp
Update to add a removal function to `driverlogic` and get rid of `tapinstall.exe`. Most driver setup code has already been moved into `driverlogic.exe`, but currently we still use `tapinstall`/`devcon` to remove drivers/devices. Also, some cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1446)
> Move all driver setup code into driverlogic

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/KeyStatusListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/KeygenEvent.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
Previously, two issues were happening. The first one was that when the tunnel was up and the user requested to regenerate the key, an error message would quickly flash while the tunnel reconnected. The message wasn't actually reporting an error, because the reconnection was expected. This PR fixes this first issue by only showing the error message if the reconnection isn't expected. A reconnection is expected right after generating a key. If the reconnection doesn't happen within 20 seconds, the connectivity error is allowed to be shown.
The second issue was that when regenerating the key, the screen would show the new key as `Invalid`. This happened because when converting the Rust type to Java, the default value for `verified` was `false`, when it should've been `null`.
Git checklist: …
> Fix WireGuard key errors in key management screen

- CHANGELOG.md
- mullvad-daemon/src/lib.rs
Changes:
* Reconnect when WireGuard key is replaced only if the protocol is WG.
* Reconnect when the WG MTU setting is changed only if using WG.
* Reconnect when mssfix is changed only if using OpenVPN.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1448)
> Only reconnect if using relevant tunnel protocol

- CHANGELOG.md
`master` moved fast when we did the last release. So a lot of stuff eventually ended up under the wrong release header.
This should hopefully fix it. Please check so this seems correct.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1449)
> Move changelog entries invalidly ending up under 2019.10

- .travis.yml
Allow "Windows, frontend" travis job to fail while we look into what's causing it to fail.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1450)
> Allow failures on windows frontend

- mullvad-cli/src/main.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/main.rs
- mullvad-problem-report/src/lib.rs
- mullvad-problem-report/src/main.rs
- mullvad-rpc/src/lib.rs
- mullvad-types/src/lib.rs
- talpid-core/src/lib.rs
- talpid-core/src/offline/windows.rs
- talpid-ipc/src/lib.rs
- talpid-openvpn-plugin/src/lib.rs
- talpid-types/src/lib.rs
According to the license, anyone who copies the source
must attach the header anyway is my understanding.
They are mostly a burden to update. And the vast majority of our files was already missing this header.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1454)
> Remove license headers from Rust source code

- Cargo.toml
This setting is very much a workaround where the code itself is very hard to relate to the problem or the fix for the problem. It's the type of code/setting where anyone could easily remove it -> test it and see that it works well and commit it. Since the bug only happens for a very specific combination of computers.
As such, it's important to document. We have to remember that the repository should be understood by other people than us, and us a couple of months into the future :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1459)
> Document why we have mysteriously set a specific opt-level

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
A recent change to allow the notification to be dismissed introduced a call to `stopForeground` with a signature that's only present on API level 24 onwards. This PR changes the call so that it is compatible with the minimum API level 21 again.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1462)
>  Make sure `stopForeground` works on API 21 

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/RelayListListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
In a few situations, the `getRelayLocations` call to the daemon can return `null`. This usually happens if the daemon has stopped. If this happens during an initial relay list fetch, the app crashes. This PR fixes the `RelayListListener` so it doesn't crash. The fix makes it also more transparent that the returned relay list may be `null`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1455)
> Fix `null` pointer exception in `RelayListListener`

- Cargo.lock
- mullvad-daemon/src/wireguard.rs
- talpid-core/src/tunnel/wireguard/config.rs
- talpid-types/Cargo.toml
- talpid-types/src/net/wireguard.rs
There is still a type `PrivateKey` that wraps `x25519_dalek::StaticSecret`, as it should be base64-encoded when serialized, and also implement `Debug` and `Display`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1458)
> Use x25519_dalek::StaticSecret for private keys

- .gitignore
- wireguard/build-wireguard-go.sh
I currently have two files in my git list of untracked files. This PR aims to make the build process not scatter untracked files. It seems like we don't need the header, so I'll just ignore it. Do you think this is a viable solution?
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1463)
> Less dirty working directory

- wireguard/build-wireguard-go.sh
- wireguard/wireguard-go/Android.mk
- wireguard/wireguard-go/build-android.sh
- wireguard/wireguard-go/go.sum
Use newer android docker image to build wireguard-go libraries in CI to
speed up builds. The main change is that NDK toolchains will now be
installed at runtime to decrease the size (and thus the time it takes to
download) the Docker image.
Seems like the newer Go version for Android also pulls in a newer dependency - this shouldn't be an issue, unless this becomes a common occurrence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1465)
> Use newer android docker image to build wireugard-go for Android

- CHANGELOG.md
- gui/src/main/index.ts
- gui/src/main/notification-controller.ts
- gui/src/renderer/components/Account.tsx
- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/renderer/components/Settings.tsx
- gui/src/renderer/containers/ConnectPage.tsx
- gui/src/renderer/containers/NotificationAreaContainer.tsx
- gui/src/shared/account-expiry.ts
- gui/test/components/NotificationArea.spec.tsx
This PR adds a system notification which is shown when the account credit is about to run out. The notification will show once every 12 hours or when the app is restarted.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1472)
> Add account expiry warning notification

- CHANGELOG.md
- talpid-core/src/tunnel/wireguard/mod.rs
Previously, if a ping timeout occurred when connecting the tunnel state machine would not receive an event indicating that the connection attempt failed. This led the app to get stuck in the connecting state, and in some cases the tunnel would eventually start working, leading some users to think that the connecting state was leaking data.
This PR fixes the issue by making sure a ping error is sent to the `WireguardTunnelMonitor`, so that it can close and the tunnel state machine realize the connection attempt failed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1478)
> Fix missing ping timeout event

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountInput.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
- android/src/main/res/drawable/account_history_background.xml
- android/src/main/res/drawable/account_history_list_divider.xml
- android/src/main/res/layout/account_history_entry.xml
- android/src/main/res/layout/login.xml
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/lib.rs
These changes add a `ListView` containing the account history as fetched from the daemon in the login fragment when the user sends a touch event to the account number input view.
Some deficiencies which should be addressed in future PRs:
- the history list won't be dismissed by pressing the _back_ button
- there's no way to delete individual items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1475)
> Add account history drop-down in login fragment.

- CHANGELOG.md
The changelog entry was missing that it was related to only WireGuard. It was also a bit vague how/when the issue happened. Adding "sometimes" makes it more clear it was a bug showing up randomly for just a subset of users.
Fixes entry added in #1478
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1481)
> Explain changelog entry on connection fix a bit more

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/ConnectionProxy.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
A few problem reports contained a crash that happened when the service was initialized. The crash occurred when the `ForegroundNotificationManager` was used before it was initialized. This race condition is fixed by this PR through a refactor of the initialization code.
The `ForegroundNotificationManager` is now initialized with the service, and doesn't have to wait until the daemon thread has started. It will listen for service events and use the `ConnectionProxy` created when the daemon is started.
The `ConnectionProxy` is no longer an asynchronous promise, and will only be created when the daemon thread has started.
Git checklist:
--- …
> Fix service initialization race condition

- CHANGELOG.md
- talpid-core/src/firewall/linux.rs
- talpid-core/src/firewall/macos.rs
My proposed solution for the DNS leak during non-connected states that are supposed to block.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1485)
> Fix dns leaks on linux + macos

- CHANGELOG.md
- dist-assets/windows/installer.nsh
- windows/driverlogic/src/driverlogic.cpp
This works around the "exhausted namespace" issue. Renaming the TAP adapter no longer depends on standard output, which didn't work well with UTF-16, at least not in NSIS. This is not necessarily a complete fix, since error messages are still sent over stdout/stderr, so Unicode strings probably won't be logged accurately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1480)
> Fix stdout issue for driverlogic and NSIS

- CHANGELOG.md
- android/build.gradle
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/FileResourceExtractor.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- build-apk.sh
- build.sh
- update-relays.sh
This PR changes the Android build to include the relay list as an extra resource asset in the APK. The code is also updated to extract that resource and save it as the `relays.json` file in the expected path.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1486)
> Bundle initial relay list inside Andorid APK

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/SettingsListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/PreferencesFragment.kt
- android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
- android/src/main/res/layout/preferences.xml
- android/src/main/res/values/strings.xml
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/lib.rs
- mullvad-types/src/settings/mod.rs
- talpid-core/src/tunnel/tun_provider/android/mod.rs
I've added a slider in the preferences fragment to enable auto-connecting in the daemon for Android.
This involves a change in the daemon on Android to enter the error state when the daemon attempts to auto-connect on start after the OS has revoked our VPN permission. The current solution only enables auto-connecting when the app starts - to start the VPN connection on boot, the user has to manually change the setting in Android's system settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1488)
> Add auto-connect setting on Android

- android/src/main/res/layout/connect.xml
On Android, when showing the location, the country was previously shown above the city. This is different from the desktop, which shows the country below the city. This PR fixes that by swapping the two text views in the layout file.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1495)
> Swap country and city text labels on Android

- windows/nsis-plugins/src/log/log.cpp
- windows/nsis-plugins/src/log/logger.cpp
- windows/nsis-plugins/src/log/logger.h
Use UTF-8 instead of CP-1252 (or ANSI). Unicode symbols are now displayed correctly instead of replaced with "?"s. E.g.
```
[2020-02-18 11:38:43.681] Failed to create virtual adapter: error 0
[2020-02-18 11:38:43.681]     Enumerable network TAP adapters
[2020-02-18 11:38:43.681]         Adapter
[2020-02-18 11:38:43.681]             Guid: {2763D6AD-A42D-4FAF-8089-C5E2E0151762}
[2020-02-18 11:38:43.681]             Name: Mullvad VPN TAP Adapter
[2020-02-18 11:38:43.681]             Alias: 汉字 åäö
[2020-02-18 11:38:43.681]             Device instance ID: ROOT\NET\0000
[2020-02-18 11:38:43.681]     Identified more TAP adapters than expected (driverlogic.cpp: 718)
```
Non-ASCII characters (127 < value < 256) in CP-1252 from old log entries may be screwed up, but these only occurred rarely (eg …
> Update install.log encoding

- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPNScreenshots.xcscheme
Git checklist:
- Add pre-action to UI Testing target to override the status bar on iOS simulator so that it always displays "9:41" time, Wi-Fi (all bars) on, battery 100% charged
- Add post-action to undo the statubar overrides.
- Remove dangling reference to `RelaySelectorTests` that was incorporated into `MullvadVPNTests` long ago
It's hard to read those scripts in Xcode project file as they are escaped, here is the source bash scripts:
Pre-action:
```
xcrun simctl boot "${TARGET_DEVICE_IDENTIFIER}"
xcrun simctl status_bar "${TARGET_DEVICE_IDENTIFIER}" override \
--time "9:41" \
--dataNetwork wifi \
--wifiMode active \
--wifiBars 3 \
--cellularMode notSupported \
--batteryState charged \ …
```
> Clean status bar when taking screenshots

- CHANGELOG.md
- mullvad-daemon/src/wireguard.rs
The wireguard key rotation relies on two timers - both of which are used like recursive futures. This means that every time the resulting future is polled and it doesn't return `Async::Ready(())`, a new timer is created and allocated on the stack. This eventually results in a stack overflow since the times are allocated on the stack. Had they been allocated on the heap, we'd leak one timer object every tick. The solution here is to use the timer as a stream of ticks.
I've also fixed some small clippy lints, nothing serious.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1507)
> Fix stack-overflow caused by recursive timers

- gui/src/main/account-data-cache.ts
- gui/src/main/daemon-rpc.ts
- gui/src/main/jsonrpc-client.ts
- gui/src/main/window-controller.ts
- gui/src/renderer/components/AppButton.tsx
- gui/src/renderer/components/LocationList.tsx
- gui/src/renderer/components/SvgMap.tsx
- gui/src/renderer/redux/store.ts
- gui/src/shared/gettext.ts
- gui/src/shared/ipc-event-channel.ts
- gui/types/validated/index.d.ts
This PR fixes the code causing @typescript-eslint/no-explicit-any warnings.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1513)
> Fix linter problems caused by @typescript-eslint/no-explicit-any

- windows/windns/src/windns/windns.cpp
- windows/winfw/src/winfw/winfw.cpp
- windows/winfw/src/winfw/winfw.h
- windows/winnet/src/winnet/winnet.cpp
I had noticed `winfw` was using references in its public functions, in several instances. So I created a branch to address this, but turns out `winfw` was the only module with this issue. Anyway, this branch also adds parameter validation on all public functions in the C++ modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1510)
> Windows: Fix module interfaces

- windows/winfw/src/winfw/rules/baseline/permitdhcp.cpp
- windows/winfw/src/winfw/rules/baseline/permitndp.cpp
This changeset brings in an updated `libwfp` that has better validation on the filters that are being installed.
It also addresses missing initialization on a couple of IPv6 filters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1516)
> Windows: fix filter initialization

- windows/winfw/src/winfw/fwcontext.cpp
- windows/winfw/src/winfw/rules/baseline/permitping.cpp
- windows/winfw/src/winfw/rules/baseline/permitping.h
- windows/winfw/src/winfw/rules/dns/permitnontunnel.cpp
- windows/winfw/src/winfw/rules/dns/permittunnel.cpp
- windows/winfw/src/winfw/rules/shared.cpp
- windows/winfw/src/winfw/rules/shared.h
- windows/winfw/src/winfw/winfw.vcxproj
- windows/winfw/src/winfw/winfw.vcxproj.filters
The PermitPing rule had a weird design using only a single host. Naturally we want to install the filter once and include a set of hosts in the conditions, in the case there are more than one host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1517)
> Windows: Update PermitPing rule

- mullvad-daemon/src/wireguard.rs
The current key rotation code doesn't log when the rotation future stops, which makes it hard to debug, and it doesn't actually stop when the RPC fails because there are too many keys in an account. These changes fix said issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1520)
> Improve WIreGuard key rotation

- CHANGELOG.md
Porting the 2020.3[-beta1] changelog entries from the release branch back to `master`
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1522)
> Add 2020.3[-beta1] to changelog

- prepare_release.sh
Slightly improve the `prepare_release.sh` script. This script is used to bump the version in all relevant files and add a signed git tag.
The `cargo build` part was only needed because it indirectly updates `Cargo.lock` with the new versions. But we did not actually need to build anything. So having it behind a timer solves the issue of having to wait a long time. Ugly, but I don't have a better solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1518)
> Improve prepare release

- dist-assets/windows/installer.nsh
- windows/driverlogic/src/driverlogic.cpp
- windows/nsis-plugins/src/msiutil/msiutil.cpp
Some small improvements. E.g., several error messages were including a generic error code (e.g., `X failed: error 0`). There was also redundancy.
One helpful string was `Fatal error during Wintun installation: Failed to install Wintun: error 0`. Now it shows something like `Failed to install Wintun: Det här installationspaketet kan inte installeras av tjänsten Windows Installer. Du måste installera ett Windows Service Pack som innehåller en nyare version av tjänsten Windows Installer.`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1523)
> Improve installer error messages

- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel/wireguard/config.rs
- talpid-core/src/tunnel/wireguard/connectivity_check.rs
- talpid-core/src/tunnel/wireguard/logging.rs
- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-core/src/tunnel/wireguard/stats.rs
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
I've done 2 cleanup things here:
- document all the public types in `talpid-core::tunnel::wireguard` and decrease visibility of types that don't need to be as public
- factor out the error types better so that `talpid-core::tunnel::wireguard::Error` is more `WireguardMonitor` specific, and have each submodule define it's own error type. Additionally, the `trait Tunnel` now returns it's own error type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1515)
> Cleanup talpid-core's WireGuard module

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/SettingsListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountInput.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/PreferencesFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
Small changes inspired by the kotlin compiler warnings. The only left-over lints stem from the fact that we use deprecated functions to get the color resource IDs and deprecated ways of listening for network changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1528)
> Fix kotlin lints

- mullvad-daemon/src/relays.rs
I saw some unnecessary mutability in the relay selector when I was lurking around figuring out requirements for the new relay list format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1529)
> Use shared references instead of mutable ones in relay selector

- build.sh
Sign also dependencies that are only used during install. This should hopefully mitigate some false alarms from AV.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1537)
> Sign all DLLs

- docs/architecture.md
This PR adds some documentation for the tunnel state machine inside Talpid.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1502)
> Document the tunnel state machine

- windows/nsis-plugins/src/msiutil/msiutil.cpp
The Wintun installation log contains somewhat sensitive information, some of which is not redacted. This PR removes all of the "Property" log entries, which contain all of the sensitive information I've seen (e.g. computer name and user name).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1521)
> Log less sensitive info in install.log

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectActionButton.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectionStatus.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/NotificationBanner.kt
- android/src/main/res/values/strings.xml
This PR tweaks the UI to show that there is a critical error if the app detects that blocking the network connections fails. The main objective is to make it very clear to the user that if this happens the app is in a critical state and it may be leaking data.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1536)
> Show appropriate error screen when Android fails to block the network

- android/src/main/AndroidManifest.xml
- ci/ci-android-xml.sh
I realized that the `AndroidManifest.xml` file wasn't formatted because it's not in the `res` sub-directory. I updated the script to also format it, but I also tweaked the script a bit hoping to make it simpler. Let me know what you think.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1546)
> Format AndroidManifest.xml

- CHANGELOG.md
- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
Previously, the app would only act on intents it received to connect or disconnect if it came from inside the app. This PR removes that check, so that other apps can control the tunnel connection.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1548)
> Remove permission check for tunnel action intents

- CHANGELOG.md
- talpid-core/src/firewall/windows.rs
- windows/winfw/src/extras/cli/commands/winfw/deinit.cpp
- windows/winfw/src/extras/cli/commands/winfw/policy.cpp
- windows/winfw/src/winfw/fwcontext.cpp
- windows/winfw/src/winfw/fwcontext.h
- windows/winfw/src/winfw/sessioncontroller.cpp
- windows/winfw/src/winfw/sessioncontroller.h
- windows/winfw/src/winfw/winfw.cpp
- windows/winfw/src/winfw/winfw.h
These changes make the `winfw` deinitialization more flexible. It's now possible to instruct `winfw` to leave the `blocked` policy behind, if this happens to be the active policy.
The default caller (code inside `talpid-core`) is mostly stateless and doesn't know which policy is active, or we might have used a different design for this.
NOTE: This fixes the accidental removal of the `blocked` policy during shutdown, but more fixes are needed in the Rust code to ensure a correct shutdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1549)
> Windows: Fix WINFW deinitialization

- CHANGELOG.md
- Cargo.lock
- docs/relay-selector.md
- mullvad-daemon/Cargo.toml
- mullvad-daemon/src/relays.rs
The relay selector is changed to prefer WireGuard on Linux and MacOS, whilst not changing any behavior on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1550)
> Prefer WireGuard on Unix platforms

- gui/src/main/window-controller.ts
…nts on already destroyed window
Git checklist:
After running a couple of tests I found that `BrowserWindow.webContents` accessor throws an exception when accessed after the window is already destroyed. 
Since all of the IPC code is already guarded with `webContents.isDestroyed()` checks, the simplest solution was to obtain the reference to `webContents` once in `WindowController.constructor` and use it directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1551)
> Fix unhandled exception error thrown by desktop GUI

- CHANGELOG.md
- talpid-core/src/winnet.rs
If adding the routes failed, the `RouteManager` was not destroyed. This caused all subsequent connection attempts to fail:
```
[WinNet][ERROR] Cannot activate route manager twice (winnet.cpp: 238)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1556)
> Fix daemon getting stuck in blocked state

- CHANGELOG.md
- talpid-core/src/firewall/macos.rs
Git checklist:
DNS requests over TCP time out when "Local network sharing" is disabled. The reason for that seems to lay in fact that we don't allow the inbound reply traffic for DNS over TCP. 
The reason why DNS over TCP worked with "Local network sharing" enabled is because the LAN rules allow the inbound traffic from LAN networks, the `10.x.x.x` is normally used for relays.
~This PR adds a "keep state" flag to the corresponding firewall rules which automatically allows the inbound traffic on permitted outbound DNS connections towards the relay IP on both IPv4 and IPv6 protocols.~
~I didn't add the "keep state" for UDP requests though as I don't fully understand how PF handles them and why …
> Properly handle the DNS over TCP when "Local network sharing" is disabled

- CHANGELOG.md
- gui/src/main/notification-controller.ts
- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/renderer/components/SecuredLabel.tsx
- gui/src/renderer/components/TunnelControl.tsx
This PR implements the new design and logic for the non-blocking error state. To test it out, apply this patch and then connect:
```
diff --git a/talpid-core/src/tunnel_state_machine/connecting_state.rs b/talpid-core/src/tunnel_state_machine/connecting_state.rs
index 77608c4c..b7ceefcf 100644
--- a/talpid-core/src/tunnel_state_machine/connecting_state.rs
+++ b/talpid-core/src/tunnel_state_machine/connecting_state.rs
@@ -319,9 +319,7 @@ impl TunnelState for ConnectingState {
shared_values: &mut SharedTunnelStateValues,
retry_attempt: u32,
) -> (TunnelStateWrapper, TunnelStateTransition) {
-        if shared_values.is_offline {
-            return ErrorState::enter(shared_values, ErrorStateCause::IsOffline);
-        }
+        return ErrorState::enter(shared_values, …
```
> Better present the error state when blocking has failed

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/ConnectViewController.swift
- ios/MullvadVPN/Location.swift
- ios/MullvadVPN/PacketTunnelIpc.swift
- ios/MullvadVPN/RelayCache.swift
- ios/MullvadVPN/RelayList.swift
- ios/MullvadVPN/RelaySelector.swift
- ios/MullvadVPN/SimulatorTunnelProviderHost.swift
- ios/MullvadVPNTests/RelaySelectorTests.swift
- ios/PacketTunnel/PacketTunnelProvider.swift
Git checklist:
1. Pick relays based on weight, inspired by https://github.com/mullvad/mullvadvpn-app/blob/master/mullvad-daemon/src/relays.rs#L597
1. Align some of the types and their names to match mullvad-daemon implementation
1. Rename `GeoLocation` to `Location` and corresponding fields where this type is used
1. Rename `RelayList.Hostname` to `RelayList.Relay` for better similarity with the daemon
1. Add `countryCode` and `cityCode` fields to `Location` struct
1. Rework relay selector to produce a flat list of relays instead of walking the tree structure. Greatly simplifies everything.
--- …
> Pick relay based on weight

- talpid-core/src/firewall/macos.rs
This reverts commit 3c375dcfd8a37ad7d1b49510f90e4359f9478ff9.
Git checklist:
This PR reverts the stateless DNS/TCP rules in favour or stateful as discussed on slack. This makes it simpler in terms of firewall rules management.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1558)
> Revert stateless DNS over TCP rules in favour of stateful ones

- CHANGELOG.md
- Cargo.lock
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/renderer/containers/SettingsPage.tsx
- gui/src/renderer/containers/SupportPage.tsx
- gui/src/renderer/redux/settings/actions.ts
- gui/src/renderer/redux/settings/reducers.ts
- gui/src/renderer/redux/version/reducers.ts
- gui/src/shared/daemon-rpc-types.ts
- mullvad-cli/src/cmds/beta_program.rs
- mullvad-cli/src/cmds/mod.rs
- mullvad-cli/src/cmds/version.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/version.rs
- mullvad-daemon/src/version_check.rs
- mullvad-ipc-client/src/lib.rs
- mullvad-jni/Cargo.toml
- mullvad-types/src/settings/migrations/v1.rs
- mullvad-types/src/settings/mod.rs
- mullvad-types/src/version.rs
Small update to allow users to receive notifications about beta releases. If the option is not set explicitly and a beta version is run, then it remains enabled even if the program is later replaced by a stable version.
The GUI is unaffected. The can only be seen in the CLI (`mullvad version`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1560)
> Add beta program option

- gui/src/renderer/components/WireguardKeys.tsx
This PR improves the error message shown when the user tries to replace the current wireguard key but there's too many wireguard keys and the current key is invalid.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1566)
> Improve error message shown when there's too many wireguard keys

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/AppVersionInfo.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
- mullvad-jni/Cargo.toml
Previously, the conversion of the `AppVersionInfo` Rust type into the `AppVersionInfo` Java class would fail. This PR fixes that by removing an obsolete property and also replacing the usage of that property.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1568)
> Fix crash when converting `AppVersionInfo` into a Java class

- docs/security.md
- talpid-core/src/firewall/mod.rs
- windows/winfw/src/winfw/rules/baseline/permitlan.cpp
- windows/winfw/src/winfw/rules/baseline/permitlanservice.cpp
Changes:
* Allow broadcasts to `255.255.255.255/32`.
* Fewer restrictions to IPv6 multicasting.
* Allow traffic to and from unique-local IPv6 addresses, i.e. `fd00::/8`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1440)
> Changes to firewall rules with "Allow LAN" enabled

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- build.sh
- dist-assets/windows/installer.nsh
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-ipc-client/src/lib.rs
- mullvad-setup/Cargo.toml
- mullvad-setup/build.rs
- mullvad-setup/src/main.rs
- version_metadata.sh
Save the target tunnel state in a file, and restore this state when the daemon starts again. If the state is saved while connected, the daemon will block until restarted. Then it will automatically connect.
It only works for Windows, but it should be very easy to use it for other desktop OSes. Everything but the installers is platform-independent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1554)
> Prevent leaks when upgrading on Windows

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AccountViewController.swift
- ios/MullvadVPN/Base.lproj/Main.storyboard
- ios/MullvadVPN/CancellableDelayPublisher.swift
- ios/MullvadVPN/WireguardKeysViewController.swift
- ios/MullvadVPN/WireguardPrivateKey.swift
Git checklist:
1. Trim the displayed WireGuard public key to 20 symbols only and add `...` to it.
1. Fix copy to clipboard in account view which previously when tapped more than once would produce random flickering due to multiple delay timers executing at the same time. It seems that in Combine, the `.delay` operator is not cancellable, so the best solution I can come up with is to roll out a custom publisher that respects the cancellation requests.
1. Implement `CancellableDelay` publisher that mimics standard `Delay` publisher from Combine. Based on documentation `Delay`:
> Delay: A publisher that delays delivery of elements and completion to the downstream receiver.
Hence the custom …
> Copy public key to clipboard

- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/containers/WireguardKeysPage.tsx
Improvement to the message shown when reconnecting with a newly generated wireguard key. Instead of an error message telling the user about being in a blocked state, it shows a green text saying "Reconnecting with new WireGuard key..."
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1565)
> Change message shown when reconnecting with new wireguard key

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/LocationInfoCache.kt
The `LocationInfoCache` subscribes to connectivity events on a `ConnectivityListener` instance. This happens every time the UI connects to the service. However, there was no explicit unsubscribe event, so the `LocationInfoCache` would only unsubscribe if the service stopped.
Since the UI connects to the service every time the app is opened, many `LocationInfoCache`s would subscribe to `ConnectivityListener` events. After connectivity is lost and restored, all listeners would schedule to fetch the current geo IP location. This would result in unnecessary repeated requests to be sent.
This PR adds an unsubscribe request that is sent when the `LocationInfoCache` is destroyed when the UI disconnects from the service.
Git checklist:
--- …
> Fix leak of connectivity listener subscribers

- CHANGELOG.md
- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Previously, the notification action button would send an intent that's only received by the `MullvadVpnService` if it's already running. That wasn't an issue before, since the notification would only be shown if the service was running. However, recent changes made the service not be in "foreground mode" while in the disconnected state, so that the notification could be dismissed. This means that the service could be killed and the notification would still be visible. One user has already ran into the issue and sent a problem report. With the recent inclusion of a quick-settings tile, the issue is now worse since the tile is always visible, even if the service isn't running.
This PR changes how the notification actions and the quick-settings tile actions are sent. They are now sent as …
> Change tunnel action intents to start the service if necessary

- gui/test/components/NotificationArea.spec.tsx
This fixes a compilation error in the tests which was introduced when the `currentIsOutdated` prop was removed from `NotificationArea`. Compilation errors seems to make the test fail silently.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1589)
> Update GUI tests for beta program changes

- android/src/main/AndroidManifest.xml
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/SettingsListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Previously, the notification action button would only be present if there was an account token set. This prevented connect commands to be sent to the daemon which would've caused it to block the connection instead. With the introduction of the quick-settings tile, it's not possible to hide the tile when there is no account set, so the issue of sending the connect command when an account token isn't set resurfaced.
This PR handles the issue by checking if the account token is set when handling the received intent. If it's not set, then the main activity is launched so that the user can log in. The PR also makes the quick settings tile launch the main activity if the tile is long-pressed.
Git checklist:
--- …
> Handle intents when there's no account token set

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
- mullvad-daemon/src/settings.rs
- mullvad-types/src/settings/mod.rs
Because on Android the security is not handled by a firewall but by configuring the tunnel routes, it's important to make sure the routes are broad enough to block any leaks. Unfortunately, the IPv6 routes were only configured if IPv6 was enabled, and by default they are disabled.
This PR changes that so that on Android the IPv6 routes are added even if IPv6 is disabled.
The PR also fixes the address prefix assigned to the tunnel for when IPv6 is enabled. Previously the prefix was only assumed to be for IPv4, but now it detects the type of the address correctly and uses the respective prefix.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1585)
> Fix possible IPv6 traffic leak on Android

- gui/package-lock.json
- gui/package.json
Update to electron-mocha since the older version didn't return an error code on compilation errors
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1595)
> Upgrade electron-mocha dependency

- gui/src/renderer/components/Modal.tsx
- gui/src/renderer/components/Support.tsx
This PR adds a container for modals to be rendered in and renders them in that element using portals.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1594)
> Render ModalAlert in portal

- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
An extra `Intent` flag is required when starting the `MainActivity` from the background service. This PR adds that flag.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1592)
> Add missing flag to start the main activity

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppStoreReceipt.swift
- ios/MullvadVPN/MullvadAPI.swift
- ios/MullvadVPN/SKRequestPublisher.swift
Git checklist:
1. Add Mullvad API call to submit the AppStore receipt to the backend
1. Add custom Combine publishers for working with `SKRequest` and its subclasses:
1. `SKProductsRequest` - a request to load the list of available in-app purchases from the AppStore that includes a lot of metadata including the localized price for the in-app purchase
1. `SKReceiptRefreshRequest` - a request to load the most recent and up-to-date App Store receipt from Apple servers.
1. Add `AppStoreReceipt` helper to be able to read the receipt from disk, or load it from AppStore. `AppStoreReceipt.fetch` does 2-in-1, it would automatically pull the receipt from the Apple servers if the one is not found on disk. …
> Appstore receipt handling

- ios/MullvadVPN/SpinnerActivityIndicatorView.swift
Git checklist:
We use a variety of sizes and visual appearance configurations for custom spinner. This PR attempts to bring this in order by introducing three size classes for the spinner: small, medium, large and associated spinner thickness etc.. It's still possible to use custom sizes however in most cases this is unnecessary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1599)
> Formalize spinner sizes and visual appearance

- gui/src/renderer/components/Account.tsx
- gui/src/renderer/components/AccountTokenLabel.tsx
- gui/src/renderer/components/ClipboardLabel.tsx
- gui/src/renderer/components/Login.tsx
- gui/src/renderer/lib/account.ts
This PR adds formatting the the account token displays. It's now displayed in groups of four with a space in between each group. When clicking to copy, the token is copied without the spaces.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1603)
> Format account token when displaying it

- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Previously, the app would follow the default behavior when handling the `onRevoke` call. The method is called in different situations, when "Always-On VPN" is disabled, when another VPN app is granted permission to connect, or when the user manually removes the permission to the app. The default behavior was to stop the background service.
However, this led to an issue with the recent "Auto-Connect" feature. The background service is registered to be restarted if stopped unless it is killed by the Android system. Therefore, when `onRevoke` is called, the background service would stop but then restart, and if "Auto-Connect" was configured it would try to connect again. However, in some situations the app would be too fast and Android would not grant a tunnel for the connection to continue. …
> Don't stop the service when VPN permission is revoked

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
One of the problem reports showed that a crash caused the service to restart, and then crash right after it restarted. The cause of the second crash was that a `null` `Intent` was passed to `onStartCommand`. The body of the method was ready to handle a `null` value, but the method signature did not specify that the parameter could be `null`. Apparently, when the signature requires non-null values, Kotlin adds null checks to the start of the method, which will throw a `NullPointerException` if the argument is `null`.
This PR fixes the method signature to accept a `null` `Intent` parameter.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1606)
> Fix NPE when `null` `Intent` is passed to `onStartCommand`

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Account.swift
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/AppStorePaymentManager.swift
- ios/MullvadVPN/AppStorePaymentPublisher.swift
- ios/MullvadVPN/SKPaymentQueuePublisher.swift
Git checklist:
1. The app obtains the `SKProduct` for the given in-app purchase using the in-app purchase ID (hardcoded in the app and on the AppStore servers)
1. The app creates `SKPayment` for the given `SKProduct` with the specified quantity (default: 1) and adds it to `SKPaymentQueue` - a payment queue
1. The system takes care of the payment flow
1. As user proceeds through the payment flow, the app receives updates as `SKPaymentTransaction` objects. In order to receive those updates, the app has to add the `SKPaymentTransactionObserver` to the `SKPaymentQueue`
1. Once the payment has `failed` or succeeded (`purchased`), the transaction has to be removed by calling …
> Add payments

- .travis.yml
- ci/ci-rust-script.sh
- mullvad-daemon/src/relays.rs
I noticed we had a warning during compile. And it felt like the type we can avoid but can be easy to miss. So I added it to the list of warnings that the CI will deny having.
```
warning: unnecessary parentheses around block return value                                                                                                  
--> mullvad-daemon/src/relays.rs:362:13
|                                                                                                                                                       
362 | /             (self                           
363 | |                 .pick_random_bridge(&relay)                                                                                                          
364 | |                 .map(|bridge| (bridge, …
```
> Deny unused parens

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/LocationInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/LocationInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/tunnelstate/TunnelStateUpdater.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
Previously, some race conditions could occur that led to incorrect location information being shown. Also, many requests were sent, which led to some delays.
This PR tries to fix those issues by changing how the fetches are handled and moving the `LocationInfoCache` to be managed by the background service. Moving the class means that the UI can reuse the same instance, instead of creating a new one every time the UI starts. This should reduce the number of requests.
The fetch queue was rewritten to track each fetch individually, and discarding the fetch result if a more recent fetch was requested.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1607)
> Improve fetching and caching the location information

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AccountViewController.swift
- ios/MullvadVPN/Base.lproj/Main.storyboard
- ios/MullvadVPN/InAppPurchaseButton.swift
- ios/MullvadVPN/JsonRpc.swift
- ios/MullvadVPN/SKProduct+Formatting.swift
- ios/MullvadVPN/UserInterfaceInteractionRestriction.swift
Git checklist:
1. Rename "Active until" -> "Paid until" on Account view (to align with desktop app)
1. Add buttons to purchase more time and restore purchases in Account view
1. Add a set of simple (counter based) classes to be able to prevent user interactions while multiple asynchronous jobs are executing, such as: 
1. When user goes to account view, the controller will request the price in local currency from AppStore. The buy button will be blocked and will display a spinner until the in-app purchase information is loaded.
1. At the same time user is able to restore the existing purchases. When user hits "Restore purchases" the entire user interface is being blocked during the system …
> Add in-app purchases UI

- build-apk.sh
- ci/buildserver-build.sh
- ci/buildserver-upload.sh
To publish to the Play store, Android App Bundles are needed. This PR updates the `build-apk.sh` script to add an `--app-bundle` flag that.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1616)
> Update `build-apk.sh` script to also build Android App Bundle

- gui/src/main/expectation.ts
- gui/src/main/index.ts
This PR ensures that the app is started with the correct menubar icon by delaying the `TrayIconController` initialization until the tunnel state is known.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1613)
> Start app with correct menubar icon

- dist-assets/linux/before-install.sh
Somehow I only caught this when installing the RPM. `mullvad-setup` will be executed even if it does not exist, causing it to fail on upgrades from versions that don't have it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1615)
> Fix upgrade script on Linux

- ios/MullvadVPN/Account.swift
- ios/MullvadVPN/AccountExpiry.swift
- ios/MullvadVPN/AccountViewController.swift
- ios/MullvadVPN/AppStorePaymentManager.swift
- ios/MullvadVPN/ConnectViewController.swift
- ios/MullvadVPN/LoginViewController.swift
- ios/MullvadVPN/MullvadAPI.swift
Git checklist:
1. Retry IAP request 10 times
1. Swift from consumable IAP to non-renewable subscription
1. Move IAP products titles into the app for easier localisation and workaround issues when AppStore decides to not return the localised titles from their servers because the IAP was rejected
1. Disable "buy" button and display "Cannot connect to AppStore"  label instead upon failure to obtain the list of IAPs from AppStore
1. Disable "buy" button when device cannot make payments (i.e restricted by parental control)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1624)
> Handle IAP fetch failure and switch to non-renewable subscription

- CHANGELOG.md
- dist-assets/windows/installer.nsh
This should fix some packet loss/speed issues that Windows 7 users are having.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1625)
> Use NDIS 5 TAP adapter driver on Windows 7

- CHANGELOG.md
- docs/security.md
- talpid-core/src/firewall/mod.rs
- windows/winfw/src/winfw/rules/baseline/permitlan.cpp
- windows/winfw/src/winfw/rules/baseline/permitlanservice.cpp
We previously allowed `fd00::/8` as the IPv6 "Unique-local range" when local network sharing was enabled. This is the "defined" half of the ULA (unique local address) space. But all of `fc00::/7` is actually the ULA space even if the first half is "undefined" in a sense. However, the entire `/7` space should not be used on the public internet and is reserved for private networks. So allowing this other half of the space should be fine.
https://en.wikipedia.org/wiki/Reserved_IP_addresses
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1627)
> Allow fc00::/7 instead of fd00::/8 for unique local addresses

- gui/src/main/account-data-cache.ts
Things get funky when `this.fetchAttempt >= 63`, see this:
```
> 1 << 63
-2147483648
> 1 << 64
1
> 1 << 65
2
```
`Math.pow` works fine though, or straight limit on `fetchAttempt` to cap the result at 2048 is even safer/cheaper.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1629)
> Fix overflow bug when using shift operator

- CHANGELOG.md
- gui/package-lock.json
- gui/package.json
- gui/src/main/index.ts
- gui/src/shared/ipc-event-channel.ts
- gui/src/shared/logging.ts
- gui/tasks/distribution.js
- gui/test/setup/main.js
- gui/test/setup/renderer.ts
This PR upgrades Electron from version 7.1.10 to 8.2.0. electron-log is also updated to 4.1.1 which fixes deprecation warnings for electron 8.x
The upgrade to Electron 8 changed the tray icon behavior in Ubuntu and to make everything work smoothly the tray icon context menu has been added to all Linux distributions. It is still possible to open the app immediately by double clicking the icon (at least on Ubuntu).
electron changelog:
https://www.electronjs.org/blog/electron-8-0
electron-log changelog
https://github.com/megahertz/electron-log/blob/HEAD/docs/migration.md
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1620)
> Upgrade to electron 8

- gui/src/shared/account-expiry.ts
This PR changes the time format for the account expiry on the settings page to show the remaining time in days if it's less than 3 months.
The time format in the account view has been changed to `lll` to make it more apparent what date format is used. More info on the format can be found here https://momentjs.com/docs/#/displaying/format/.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1633)
> Change time format

- ios/MullvadVPN/AccountExpiry.swift
- ios/MullvadVPN/AccountViewController.swift
- ios/MullvadVPN/InAppPurchaseButton.swift
Git checklist:
1. Drop seconds from account expiry
1. Rework `InAppPurchaseButton` to display the spinner on the right-hand side
1. Display the in-app purchase title on the buy button while loading the list of in-app purchases from AppStore. This should additionally cover the case that happened during the last review when we forgot to submit the in-app purchase for review which caused the product request to succeed but return no in-app purchases as obviously the IAP in subject was not registered. The button remained disabled however showed the placeholder label which should never appear.
--- …
> Improve account view

- gui/test/account-data-cache.spec.ts
Adds test for the refetch that is performed in account-data-cache.ts if the account has expired.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1637)
> Account data cache refetch test

- CHANGELOG.md
- README.md
There has been discussions about what versions of operating systems we should test on and which ones we should say we support. We should of course not say we support something we have not tested ourselves. And we can't test every combination of everything. The general rule of thumb is that we support the versions that the OS vendor still supports. But there are deviations from that rule.
Assigning @richard-mullvad since he is head of the testing. Assigning @jvff since this means we drop support for two Android versions. Assigning @pinkisemils since this means we drop some Fedora support and will soon drop Ubuntu 16.04. Ping @dlon, might be worth for you to know when you get back :)
Git checklist:
--- …
> Formalize what OS versions we support in the README

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/relays.rs
On MacOS and Linux, automatic relay selection prefers WireGuard over OpenVPN even if the user has no WireGuard key. This results in the user ending up in the error state. These changes introduce a new parameter to the relay generation to signify whether WireGuard key exists or not, which is only taken into account when the tunnel protocol is not strictly specified - so WireGuard will only be preferred on MacOS and Linux only if a key is set, otherwise OpenVPN will be used. This means that if the user explicitly somehow specifies the tunnel protocol to be WireGuard without having a key set, the daemon will still end up in the error state.
--- …
> Select OpenVPN relays when no WG key exists

- mullvad-setup/Cargo.toml
- prepare_release.sh
`prepare_release.sh` was not updated when the `mullvad-setup` binary was added. So its version bump was not commited as part of making a release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1644)
> Update forgotten mullvad-setup version

- CHANGELOG.md
- gui/tasks/distribution.js
This PR makes `electron-builder` exclude native node modules from the asar archive on macOS. They are instead placed in a directory called `app.asar.unpacked` next to `app.asar`. Including the native module in the asar forces Electron to unpack it before executing it and running the extracted executable on macOS resulted in the OS making requests to Apple servers. My guess is that the unpacked executable was placed somewhere outside the app bundle and that made macOS confused.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1643)
> Exclude native modules in asar packaging on macOS

- ios/ExportOptions.plist
- ios/MullvadVPN.xcodeproj/project.pbxproj
Also: disable release certificates configuration for screenshots and
unit tests which are never compiled in release mode
Git checklist:
- Change Xcode project configuration to the new Apple ID
- Disable release certificates configuration for screenshots and unit tests which are never compiled in release mode. We don't even have release certificates for those so no point in having the fields pre-filled with anything but blank configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1648)
> Change Xcode project configuration to the new Apple ID

- ios/CHANGELOG.md
- ios/MullvadVPN/Account.swift
Git checklist:
As the title says, in a rush a must have introduced the regression just before the release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1652)
> Fix invalid account error being mistakenly reported as network error

- ios/CHANGELOG.md
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AccountTextField.swift
- ios/MullvadVPN/AccountTokenInput.swift
- ios/MullvadVPN/Base.lproj/Main.storyboard
- ios/MullvadVPN/LoginViewController.swift
- ios/MullvadVPNTests/AccountTokenInputTests.swift
Git checklist:
This PR adds account token input formatting that very much supports free editing and copy-and-paste function.
The account token is formatted by adding a space separator between each of 4 digits in the account token, i.e:
```
1
12
123
1234
1234 5
1234 56
1234 567
1234 5678
[and so forth]
```
The principle how it works boils down to a few steps:
1. Modify the formatted string applying user manipulation disregarding if user removed the separator characters (space) or not
1. Loop through each character in the string and add or remove space separators as needed, adjusting the caret position
1. Update the text field with the new text and caret position
There is only one exception I …
> Add account token text input formatting

- ios/CHANGELOG.md
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/ConnectViewController.swift
- ios/MullvadVPN/NEProviderStopReason+Debug.swift
- ios/MullvadVPN/TunnelManager.swift
- ios/PacketTunnel/PacketTunnelProvider.swift
Git checklist:
1. Enable on-demand VPN and add a single rule to connect the tunnel when on Wi-Fi or cellular
1. Disable on-demand VPN when disconnecting the tunnel from GUI to prevent the tunnel from coming back up
1. Log tunnel stop reason. This is something I will need later on for debugging when we start saving logs on disk. This should greatly help to figure out when and why the tunnel is being stopped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1656)
> Enable on-demand VPN

- windows/winnet/src/winnet/networkadaptermonitor.cpp
As above. The struct needs to be cleared to ensure the `InterfaceIndex` field doesn't contain random garbage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1657)
> Fix uninitialized struct

- CHANGELOG.md
- android/src/main/res/layout/confirm_no_email.xml
Change the colors of the buttons for the no email confirmation dialog for the problem report fragment to match the colors on desktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1669)
> Andriod: change no email confirmation dialog buttons

- gui/src/main/index.ts
Add option for reloading and forceReloading window in development mode on macOS.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1664)
> Add reload and force reload to macOS application menu in dev mode

- gui/src/main/account-data-cache.ts
- gui/src/main/index.ts
- gui/src/shared/scheduler.ts
- gui/test/account-data-cache.spec.ts
This PR adds some checks in `account-data-cache.ts` to prevent multiple fetches to happen if:
1. There's already a fetch in progress
2. A fetch has been performed while a scheduled fetch has been waiting
It also adds tests for those two cases.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1667)
> Prevent running multiple fetches when not neccesary

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/FileMigrator.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/FileResourceExtractor.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- mullvad-cli/src/cmds/auto_connect.rs
- mullvad-cli/src/cmds/beta_program.rs
- mullvad-cli/src/cmds/block_when_disconnected.rs
- mullvad-cli/src/cmds/bridge.rs
- mullvad-cli/src/cmds/lan.rs
- mullvad-cli/src/cmds/tunnel.rs
- mullvad-cli/src/cmds/version.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/main.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/settings.rs
- mullvad-jni/src/lib.rs
- mullvad-problem-report/src/lib.rs
- mullvad-types/src/settings/mod.rs
The app would previously crash on Android if it was installed on an SD card or on a container (using for example Android For Word). This happened because the app relied on hard-coded paths for certain things like the settings file, the relay list file, and the log files.
This PR fixes the issue by using the app's cache directory and the app's files directory (as determined by the Android system).
As part of the change, the `Settings` type was refactored so that the file operations were moved from `mullvad-types` to `mullvad-daemon`, and the settings file path can now be specified through a parameter.
If a settings file is found in the old location, it is moved to the new location before the daemon is started.
Still to be done before sending the PR to review:
Git checklist:
---
This change …
> Fix crash when running from SD card or from container

- Cargo.lock
- talpid-core/Cargo.toml
We recently released `nftnl 0.3` that deals with a number of things. It adds support for a lot of stuff we need for Linux split tunneling, but it also fixes compilation errors on ARM.
... And it upgrades the broken `err-derive` dependency to the newer `0.2` series. This however also caused a lot of headache as that series is also broken on a bit older combination of dependencies. I had to do `cargo update -p $dep` for every dep of `err-derive` in order to make it build again. It needed the very latest `syn`, `quote` etc to work.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1673)
> Upgrade nftnl to 0.3 and all dependencies needed to make it build

- CHANGELOG.md
- talpid-core/src/tunnel/wireguard/config.rs
When investigating IPv6 issues on MacOS, I noticed that I had to change the MTU to get IPv6 to work, even if it was originally set above the minimum MTU for IPv6.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1671)
> Lower the MTU limit for WireGuard/IPv6

- CHANGELOG.md
- talpid-core/src/tunnel/mod.rs
- talpid-core/src/winnet.rs
- windows/winnet/src/winnet/netconfig.cpp
- windows/winnet/src/winnet/netconfig.h
- windows/winnet/src/winnet/winnet.cpp
- windows/winnet/src/winnet/winnet.def
- windows/winnet/src/winnet/winnet.h
- windows/winnet/src/winnet/winnet.vcxproj
- windows/winnet/src/winnet/winnet.vcxproj.filters
The changes are intended to address a couple of things:
* Currently when IPv6 is enabled in the app (i.e., in the tunnel), it fails to connect if no IPv6 interface is available for the network adapter itself. Now we try to enable it before connecting.
* It's not possible to connect using WireGuard if the IPv6 interface is disabled for the adapter, even using only IPv4. The updates work around the issue by *always* attempting to enable the IPv6 interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1676)
> Automatically enable IPv6 interface for TUN/TAP adapter on Windows

- ios/CHANGELOG.md
- ios/MullvadVPN/RelaySelector.swift
Git checklist:
If user has `country` constraint set, then servers with `include_in_country: false` should be ignored. This PR fixes this omission in relay selector logic.
Rust source: https://github.com/mullvad/mullvadvpn-app/blob/2489837d85d914852cc0740987d9b6ab4f26d256/mullvad-daemon/src/relays.rs#L544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1678)
> Respect includeInCountry when handling country constraints

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/NotificationBanner.kt
- android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
- android/src/main/kotlin/net/mullvad/talpid/tunnel/ErrorStateCause.kt
- android/src/main/res/values/strings.xml
- mullvad-jni/src/classes.rs
- talpid-core/src/tunnel/tun_provider/android/mod.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-types/src/tunnel.rs
Sometimes, when the app started with the "Auto-Connect" setting enabled, it would fail to create the tunnel device and enter the non-blocking error state. This happened because the `VpnService.prepare()` method wasn't called before trying to create the tunnel.
This is usually not an issue because the `MainActivity` will use the `ConnectionProxy` to connect, which does call `VpnService.prepare()` before sending a `connect` command to the daemon. However, if the daemon decides to connect by itself (like when the "Auto-Connect" setting is enabled), the method isn't called.
This PR fixes the issue by always calling `VpnService.prepare` when connecting. This means it does get called twice when connecting, but if the permission is already granted the calls just return `null`. However, if the …
> Fix traffic leak when the app starts with "Auto-Connect" enabled

- talpid-core/src/routing/linux.rs
I noticed that the daemon would sometimes not identify the default routes, so that I could not connect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1684)
> Find all default routes in RouteManager

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- mullvad-jni/src/lib.rs
- mullvad-problem-report/src/lib.rs
In the recent change to parameterize all the paths in the app, the problem report was left out, and as such, the root cert for the API were being sought in the wrong directory. I've made it so that the problem report sender takes the resource directory as an extra argument.
In an unrelated note, maybe the `mullvad-paths` module should be slimmed down to not contain any of the functions that are now moot on Android? This would involve a lot of ugly `#[cfg(not(target_os = "android"))]`, but these functions really do not make much sense anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1687)
> Pass resource directory to problem report

- talpid-core/src/routing/android.rs
- talpid-core/src/routing/linux.rs
- talpid-core/src/routing/macos.rs
- talpid-core/src/routing/mod.rs
- talpid-core/src/routing/unix.rs
- talpid-core/src/routing/windows.rs
- talpid-core/src/tunnel/wireguard/mod.rs
Changes:
* Track routes in tables other the main table in `RouteManager`.
* Explicitly remove default routes when the route manager is destroyed (necessary when they aren't routed through a tunnel interface).
* Replace `HashMap<IpNetwork, super::NetNode>` with `HashSet<RequiredRoute>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1683)
> Support different routing tables in the route manager on Linux

- mullvad-jni/src/lib.rs
With the recent change to the REST API, the error that is used to determine if an account is invalid changed. This PR updates the `mullvad-jni` crate to properly handle the new error status code.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1688)
> Fix login with invalid account error

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/util/JobTracker.kt
- android/src/main/res/layout/login.xml
- android/src/main/res/values/strings.xml
- mullvad-jni/src/daemon_interface.rs
- mullvad-jni/src/lib.rs
Previously, the `Create account` button on the login screen would open the web browser in order to create an account. This PR changes that so that the Android app behaves like the desktop app by using the API to create a new account number.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1685)
> Implement creating a new account from the Android app

- CHANGELOG.md
- mullvad-daemon/src/account_history.rs
- mullvad-daemon/src/lib.rs
The account history file contains a cache of the most recently used accounts and their WireGuard keys. The file was previously stored in the cache directory, which in general is not a problem since the data is ephemeral. However, every time the cache is cleared the WireGuard key is lost. This means the app has to regenerate the key the next time it runs. After regenerating a few times, the maximum key limit is reached, and the user has to manually clean-up the stale keys.
This PR improves the UX by moving the account history file to the settings directory, where it isn't cleared periodically. This should considerably reduce the number of times the user has to clean-up the stale keys.
Git checklist:
--- …
> Move account history into the settings directory

- CHANGELOG.md
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/ExpiredAccountErrorView.tsx
- gui/src/renderer/components/Modal.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/shared/scheduler.ts
- mullvad-cli/src/cmds/block_when_disconnected.rs
This PR aims to clarify the "Block when disconnected" setting, this is accomplished by:
1. Rename the setting to "Always require VPN"
2. Change the text below the setting in the Advanced Settings view
3. Add a confirmation dialog when enabling the setting which further explains it
4. Add an explanation to the in app notification when internet is blocked due to this setting
The setting should be renamed in all user facing texts but not in in the code.
When pressing the setting it is first enabled when the confirmation dialog appears and if the user presses "Enable anyway" the settings is left on and if the user presses "Back" it is disabled. Let me know if we want to wait with enabling it until after the confirmation.
This PR also includes added support for multiple messages in `Modal.tsx` …
> Clarify "Block when disconnected" setting

- gui/src/main/index.ts
- gui/src/main/notification-controller.ts
- gui/src/renderer/components/NotificationArea.tsx
This PR removes the notification that is displayed when the app fails to publish/generate a wireguard key and is left without a key. It also improves the current notification that is displayed when the app fails to connect due to not having a valid wireguard key.
All notifcations about connectivity being blocked has been changed from `blocked all connections` to `blocking internet` to align it with the in-app notification.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1694)
> Remove wireguard key generation error

- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/shared/daemon-rpc-types.ts
The fields of `AppVersionInfo` were recently changed, but the GUI was not updated. This caused deserialization of the struct to fail when the frontend tried to update the version state. A false update notification was seen in Settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1699)
> Fix deserialization of AppVersionInfo in GUI

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/util/JobTracker.kt
Some crash reports contains an `IllegalStateException` in the WireGuard Key screen. When checking the backtrace, it looked like the view was being updated after the fragment was detached (i.e., after the user left the screen). This shouldn't have happened because the background jobs should be cancelled when leaving the screen.
However, it turns out there was a bug in the `JobTracker`. It was cancelling a wrapper "reaper" job instead of cancelling the actual job. This PR fixes that by making sure both jobs are cancelled.
Since the crash happened when calling `getResources()` in the fragment for retrieving a color, the PR also takes a second mitigation of caching the color value so that the call isn't necessary anymore.
Git checklist:
--- …
> Fix crash when leaving WireGuard Key screen

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/RelayListListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadDaemon.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/SettingsListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
Previously, some crash in the app (or a panic in the daemon) could cause the app to crash with a `null` pointer exception because it assumed that the daemon would always return a valid `Settings` object. However, `null` is returned instead if the daemon is in an error state, like right after a panic and before it has restarted.
This PR fixes the issue by changing the app architecture a bit. The `SettingsListener` was moved to the `service` package, and now requires a valid `Settings` object in its constructor. This means that the `MullvadVpnService` is now responsible for fetching the initial settings from the daemon. If that fails, the service can safely restart the initialization.
As part of this PR, the service was also refactored to make it simpler to handle the initialization and …
> Fix crash in `SettingsListener` that happens with other crashes

- mullvad-types/src/account.rs
- mullvad-types/src/auth_failed.rs
- mullvad-types/src/location.rs
- mullvad-types/src/relay_constraints.rs
- mullvad-types/src/relay_list.rs
- talpid-types/src/lib.rs
- talpid-types/src/net/mod.rs
- talpid-types/src/net/openvpn.rs
- talpid-types/src/net/proxy.rs
- talpid-types/src/net/wireguard.rs
- talpid-types/src/tunnel.rs
Adds documentation to most of the remaining types in these crates. The comments should ideally explain what they're for, where they're being used, and why.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1698)
> Document types in {mullvad,talpid}-types

- dist-assets/windows/installer.nsh
`C:\ProgramData\Mullvad VPN` is not deleted upon a full uninstall. This is because the void logger isn't initialized correctly due to a typo, and the file `install.log` is in use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1704)
> Fix cleanup of log files

- CHANGELOG.md
- android/build.gradle
Previously, the minimum supported Android version was specified as `7.0` in the `README` file but the generated app was supporting Android versions from `4.4` (API level 19) onwards (which we weren't testing). This PR updates the app so that it becomes unsupported on versions below `7.0` (API level 24).
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1705)
> Increase minimum supported Android API level

- talpid-core/src/routing/linux.rs
`ipnetwork::IpNetwork::size()` overflows if `prefix == 0` since it tries to compute `(2u32).pow(ADDRESS_SIZE_BITS - prefix)`. Avoid this by checking the prefix first.
Cf. test failures here: https://travis-ci.com/github/mullvad/mullvadvpn-app/builds/162446557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1692)
> Prevent overflow in RouteManager

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/FileResourceExtractor.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Now the Mullvad VPN service will compare the date it was last installed with the last modification date of the relay list to ensure that it ends up using the most recent relay list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1708)
> Unpack relay list from APK when upgraded

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/SettingsListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
Some previous changes broke how the `loggedIn` property could be used to determine if the app should connect or open the UI for the user to log in. Since the service would check if it was logged in before the property was correctly set, it would always assume that the user wasn't logged in and open the UI instead of connecting.
This PR fixes that by refactoring how the property is updated and only checking it after it is known that the latest value was set by settings listener.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1709)
> Fix handling of connect command when starting service

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt
A few crashes with an `IllegalStateException` when starting the service were reported on newer Android versions. Apparently, the cause is that a service can't be requested to be started without either being the result of a user interaction or having a promise that the service will be a foreground service. In theory, this rule is not applied for apps in a dynamic whitelist. This whitelist seems to be getting stricter with every release, since the crashes appear with the frequency increasing with the Android version.
This PR fixes the issue by promising on those newer Android versions that the service will be a foreground service.
Git checklist:
--- …
> Fix crash when starting the service to handle a connect request

- windows/nsis-plugins/src/log/log.cpp
- windows/nsis-plugins/src/log/logger.cpp
Some sensitive information used to be logged here. This was fixed in https://github.com/mullvad/mullvadvpn-app/pull/1521. But it could still end up in problem reports since updating the app only appended to the existing log. Fix by overwriting the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1706)
> Overwrite install.log instead of appending to it

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/relaylist/RelayList.kt
As the new endpoints no longer return a sorted relay list, the relay list should now be sorted in the client. The GUI already did this, but the Android app did not, with these changes it will. Eventually the sorting will have to be lifted to a higher level anyway, if/when the app becomes internationalized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1713)
> Sort relay list alphabetically

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/AppVersionInfo.kt
- mullvad-rpc/src/lib.rs
With the recent update to the REST API, there's a small change in the behavior of one of the returned values. The app. version information's `latest_stable` field can now be `null`. This currently only happens on Android since we haven't released a stable version yet.
This PR fixes that by allowing the field to be optional when deserializing. The UI code for desktop and Android was updated to support the nullable value.
The PR also fixes the order of the fields in the `AppVersionInfo` class to match the order in the Rust type so that the conversion is correct.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1714)
> Fix deserialization of app version information from API

- gui/src/renderer/components/ExpiredAccountErrorView.tsx
- gui/src/renderer/components/NotificationArea.tsx
This PR changes a few quotes to regular ones (") to make quote usage consistent throughout the GUI.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1716)
> Make quote usage consistent in GUI

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
Previously, after leaving the app (by going to the home screen or opening another app, for example) the `SettingsListener` would prematurely unsubscribe for settings events. When the user returned to the app, no further settings events would be received. This led to for example the user logging out and logging in with a different account but the Account page showing the previous account number.
This PR fixes the issue by removing the call to `SettingsListener.onDestroy()` in the `ServiceConnection`. There was already a correct `onDestroy` call in the `ServiceInstance` class.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1721)
> Fix settings listener unsubscribing prematurely to settings changes

- gui/src/renderer/components/Accordion.tsx
- gui/src/renderer/components/BridgeLocations.tsx
- gui/src/renderer/components/CityRow.tsx
- gui/src/renderer/components/CountryRow.tsx
- gui/src/renderer/components/CustomScrollbars.tsx
- gui/src/renderer/components/ExitLocations.tsx
- gui/src/renderer/components/LocationList.tsx
- gui/src/renderer/components/SelectLocation.tsx
This PR adds automatic scroll when expanding countries and cities in the location list to make as much of the content as possible fit into the scroll view.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1712)
> Scroll to expose expanded items in location list

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
Previously, the app would lose track of the account expiration date on various circumstances. For example, when network connection was lost, when leaving the app and returning to it, or when the expiration date was reached.
This PR fixes the separate causes for the issue. First, it doesn't overwrite a valid expiration with a `null` value when fetching an updated expiration fails. Second, it moves the account cache to the service, so that when the user leaves the UI the account cache (and its cached value) is destroyed.
The PR also performs a small refactor in the account cache. The class now uses the `JobTracker` helper class, and the fetch isn't started if the current account number is `null` (i.e., when an account number isn't set).
Git checklist:
--- …
> Fix account expiration disappearing

- ios/MullvadVPN/CancellableDelayPublisher.swift
Git checklist:
I found a way to rework the complex CancellableDelay using a combination of `FlatMap` + `PassthroughSubject`. `PassthroughSubject` acts as a conduit and it properly handles cancellation unlike the standard `.delay` operator.
The only downside is that `Scheduler.schedule` does not return a `Cancellable` object so we can't cancel the timer, however it has no side-effect as `PassthroughSubject` simply ignores any events or values sent (`.send`) after it has already been cancelled. Given that we don't have many delays used across the app, I figured it's a good trade off vs. complexity we had before.
--- …
> Rework cancellable delay

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Account.swift
- ios/MullvadVPN/AppStorePaymentManager.swift
- ios/MullvadVPN/MullvadRpc.swift
- ios/MullvadVPN/RelayCache.swift
- ios/MullvadVPN/WireguardKeysViewController.swift
Git checklist:
1. Rename `MullvadAPI` to `MullvadRpc`
1. Rework `MullvadRpc.Error` to include server error as a part of it; automatically unpack the `JsonRpcResponse.result` for that purpose. This makes it much easier to work with API. Less code duplication across the board.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1726)
> Rename MullvadAPI -> MullvadRpc and rework MullvadRpc.Error type

- CHANGELOG.md
- mullvad-cli/src/location.rs
- mullvad-rpc/src/relay_list.rs
Currently when setting a country code, city code, or hostname in the CLI, the selected location (or hostname) is case-sensitive. In practice, this means it will not match an available location unless all characters are lowercase.
This was improved by converting the inputs to lowercase strings. E.g., this will work now:
```
mullvad relay set location Se gOt se9-WireGuard
```
The parsing of the relay list was also updated to ensure that these fields must be lowercase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1724)
> Ignore case when setting locations in the CLI

- mullvad-daemon/src/settings.rs
Changes:
* Use `fs::read` instead of `BufReader`.
* Log causes of failures to load the settings.
* Reorganize Windows Update backup code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1729)
> Refactor settings module in mullvad-daemon

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Previously, sometimes quitting the app would leave the notification still visible, or causing it to reappear a few moments later. This happened because the `ForegroundNotificationManager` would still listen for tunnel events and update the notification when needed after its `onDestroy` method was called. This meant that when stopping the manager would remove the notification, but shortly afterwards a disconnected event would be received, causing the manager to crate a new notification.
This PR fixes the issue by properly unsubscribing from tunnel events when the manager is stopping.
The PR also refactors how the manager knows if there is an account set or not. Previously it would depend on the service to notify when there is a user logged in or not. However, the service could notify the …
> Fix notification reappearing after quitting the app

- CHANGELOG.md
- build-apk.sh
- build.sh
- ci/ci-rust-script.sh
- env.sh
- prepare_release.sh
- talpid-core/src/proxy/shadowsocks.rs
Main repo PR bumping the binary submodule. In relation to https://github.com/mullvad/mullvadvpn-app-binaries/pull/65.
The Android builds were broken. So I had to update some stuff around that. As such I bring @jvff in for review as well.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1740)
> Upgrade OpenVPN to 2.4.9, OpenSSL to 1.1.1g and shadowsocks-rust to 1.8.10

- talpid-core/src/routing/android.rs
- talpid-core/src/routing/linux.rs
- talpid-core/src/routing/macos.rs
- talpid-core/src/routing/unix.rs
- talpid-core/src/routing/windows.rs
- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- talpid-core/src/winnet.rs
- windows/winnet/src/winnet/routing/routemanager.cpp
- windows/winnet/src/winnet/routing/routemanager.h
- windows/winnet/src/winnet/winnet.cpp
- windows/winnet/src/winnet/winnet.h
This makes a few changes to the routing module, mostly in order to simplify code in the split tunneling branch.
The main change is that the `RouteManager` is stored in `SharedTunnelStateValues`. This enables routes to be added later on in the `ConnectedState`, etc., instead of only when the route manager is initialized.
The changes resulted in an issue on Linux where new routes weren't detected sufficiently quickly after the offline monitor recognized the machine to be online, which was worked around by reloading the routes if they're stale.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1743)
> Update the route manager

- mullvad-rpc/src/bin/relay_list.rs
- mullvad-rpc/src/rest.rs
The ops team would like to be able to monitor the relay list endpoint for trouble. So if we modify our relay list fetching binary in the following way they can differentiate between different types of errors on the process exit code.
I found that the `DeserializationError` was completely unused. It was very close that I submitted this PR with the code matching for an error that would never happen :( But I removed the more vaguely named `Serde` error variant and instead started using the (renamed) `DeserializeError`.
I also found that two error variants were never used :( So I cleaned these up.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1749)
> Exit with different exit codes in relay_list binary depending on error

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/model/Settings.kt
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/components/Preferences.tsx
- gui/src/renderer/redux/settings/actions.ts
- gui/src/renderer/redux/settings/reducers.ts
- gui/src/shared/daemon-rpc-types.ts
- mullvad-cli/src/cmds/beta_program.rs
- mullvad-cli/src/cmds/version.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/settings.rs
- mullvad-types/src/settings/migrations/v1.rs
- mullvad-types/src/settings/mod.rs
And prevent them from being disabled, so that users don't receive notifications advising them to download the latest stable version if it's older than the last beta version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1751)
> Always enable beta update notifications in beta versions

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
Previously, if fetching the account data (which is mostly the account expiration date) fails, the UI would simply consider that the account had no expiry. This PR changes that so that the `AccountCache` class retries to fetch the data if it fails, using an exponential backoff between each attempt.
The retries only happen if there's a listener attached to handle the data. Otherwise the retries stop. Therefore, the Account screen now will attempt to fetch the account data if it sees that the expiry is `null`. This is because previously the Account screen would never fetch the data since the Settings screen would fetch it first. However, if the fetch started in the Settings screen fails and the user enters the Account screen, the retries are cancelled when the listener from the Settings …
> Retry fetching account expiry on Android

- mullvad-rpc/src/rest.rs
The master API can contain a string that specifies the type of error that was encountered when processing a request, which can be helpful to distinguish between different types of errors, when the HTTP response status code remains the same. But for the code to be helpful, it needs to be logged - these changes achieve just that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1753)
> Display the supplied error code in the logs

- mullvad-daemon/src/relays.rs
- mullvad-daemon/src/wireguard.rs
Previously they were 5 minutes and 5 seconds respectively.
This risked both filling up the logs and sort of DDoS our own API.
There is no need to do it that often.
The long term solution is to have a nice exponential backoff in place when we have upgraded all the network code to cleaner modern async/await. But for now we bump the intervals to something a bit more conservative.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1754)
> Increase both relay list and wg key rotation retry interval to 15 min

- ios/CHANGELOG.md
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AccountExpiry.swift
- ios/MullvadVPN/CustomDateComponentsFormatting.swift
- ios/MullvadVPN/MullvadRpc.swift
- ios/MullvadVPN/WireguardKeysViewController.swift
- ios/MullvadVPNTests/CustomDateComponentsFormattingTests.swift
Git checklist:
This PR introduces the following changes:
1. "Time added" for IAP purchases is not constraint to displaying the largest unit. This solves the possible issue with displaying the rounded numbers, as 1.5 days of time would be displayed as 2 days which is not correct and it's better to display "1 day 12 hours" instead so we're not lying to the user on the amount of time being added on their accounts. This hasn't been the case before as we always add VPN time in 30 day chunks but I figured I'd like to avoid even a possibility of that happening.
1. Fix date interval formatting and add tests
1. Intervals between 23h 30m - 23h 59m are rounded to 1 day to fix the iOS SDK bug which results …
> Fix date interval formatting

- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/AdvancedSettingsStyles.tsx
- gui/src/renderer/components/Cell.tsx
- gui/src/renderer/components/CellStyles.tsx
- gui/src/renderer/components/CityRow.tsx
- gui/src/renderer/components/CountryRow.tsx
- gui/src/renderer/components/LocationList.tsx
- gui/src/renderer/components/Login.tsx
- gui/src/renderer/components/LoginStyles.tsx
- gui/src/renderer/components/RelayRow.tsx
- gui/src/renderer/components/SelectLanguage.tsx
- gui/src/renderer/components/Selector.tsx
- gui/src/renderer/components/Settings.tsx
- gui/src/renderer/components/SettingsStyles.tsx
- gui/src/renderer/components/Switch.tsx
This PR converts all components in `Cell.tsx` to styled components and all usages of those components to extending them if necessary.
This also fixes the issue where it wasn't possible to expand countries and cities in the location picker on Surface Pro devices.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1738)
> Convert Cell to Styled components

- gui/src/renderer/components/CustomScrollbars.tsx
- gui/src/renderer/components/ExpiredAccountErrorView.tsx
- gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx
- gui/src/renderer/components/NavigationBar.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/components/WireguardKeysStyles.tsx
This PR makes the wireguard-key view and the out-of-time view scrollable if the content doesn't fit. This happens when the app is set to some languages as can be seen in the screenshots below. When everything fits this looks exactly as before.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1741)
> Add scroll to wireguard-key and out-of-time views

- gui/src/renderer/components/Launch.tsx
This PR centers the text in Launch.tsx. The text was previously centered as long as the text was just one line.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1757)
> Align subtitle in Launch.tsx

- ios/MullvadVPN/AutomaticKeyRotationManager.swift
- ios/PacketTunnel/PacketTunnelProvider.swift
Git checklist:
After doing some testing we figured that `DispatchTime` relies on device uptime which doesn't tick when the device is hibernated causing timers to fire much later than expected. With `DispatchWallTime` the timers that are due would fire immediately on wake up.
1. `DispatchTime` is relative to system clock that ticks since boot
1. `DispatchWallTime` - An absolute point in time according to the wall clock, with microsecond precision.
I also decided to go with `DispatchSourceTimer` instead of `DispatchQueue.asyncAfter` because I am not entirely sure that the timer created internally by `DispatchQueue.asyncAfter` is cancelled upon the work item (`DispatchWorkItem`) cancellation.
--- …
> Switch to using DispatchWallTime and DispatchSourceTimer in key rotation

- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
Minor fix. "Failed to clear routes" was shown twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1756)
> Fix error message shown when routes cannot be removed

- gui/src/renderer/components/Account.tsx
- gui/src/renderer/components/AccountStyles.tsx
- gui/src/renderer/components/ExpiredAccountErrorView.tsx
- gui/src/renderer/components/RedeemVoucher.tsx
- gui/src/renderer/components/RedeemVoucherStyles.tsx
This PR adds the "Redeem Voucher" button and the redeem voucher alert to the account page. The alert itself has been moved to `RedeemVoucher.tsx` to enable reusing it in `Account.tsx`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1763)
> Add voucher payment to account view

- ios/CHANGELOG.md
- ios/PacketTunnel/AnyIPEndpoint+DNS64.swift
- ios/PacketTunnel/PacketTunnelProvider.swift
- ios/PacketTunnel/PacketTunnelSettingsGenerator.swift
- ios/PacketTunnel/WireguardCommand.swift
- ios/PacketTunnel/WireguardConfiguration.swift
- ios/PacketTunnel/WireguardDevice.swift
Git checklist:
1. Ensure that all relay IPs are resolved against DNS64 when the tunnel starts. Previously that was only done on network interface changes, i.e wifi -> cell or vice versa.
1. Remove `excludedRoutes` when setting up iOS routes. Previously we used to add the relay IP in there but I think it's not necessary.
1. Cap IPv6 prefix at `/120` due to issues described at https://github.com/WireGuard/wireguard-apple/blob/112545248eaae2d56c0ff7ab7bfc6265f9c38e03/WireGuard/WireGuardNetworkExtension/PacketTunnelSettingsGenerator.swift#L131
1. Enable IPv6 with the following wireguard configuration: `allowed_ip=::0/0`
1. Fix a bug where the relay IPs were re-resolved against the previously …
> Fix IPv6 support

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
On recent Android versions, a service can only be started with a promise that it will run on the foreground. A previous PR added this promise to a few places by calling the `startForegroundService` API. However, the `MainActivity` wasn't updated because it was incorrectly assumed that since the service runs on the same process as the `MainActivity`, it didn't need to promise to run on the foreground.
This led to some crashes on Android 10 when the activity tried to start the service. This PR fixes that by also changing the code to start the service in the `MainActivity`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1769)
> Fix start service in main activity

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Previously, a bind counter was introduced to keep track of when the UI is connected to the service. This allowed the service to keep the foreground notification up while the UI was shown. However, there's a strange issue where sometimes the app doesn't quit correctly, where it keeps running after quitting.
After reading through Android's documentation, it appears that the service's `onUnbind` is only called _after all client connections have been disconnected_. This means that the counter is unnecessary and incorrect. Therefore, this PR removes it.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1770)
> Remove service bind counter

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/KeyStatusListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
There have been some issues on the WireGuard Key screen where stale information is shown. This seems to happen when WireGuard key events sent from the daemon aren't received by the listener in `WireguardKeyFragment`.
It's not clear why this is happening, but one guess is a race condition when changing the listener callback when the Connect screen pauses after the WireGuard Key screen has resumed.
This PR tries to eliminate that scenario by changing the key listener to use an `EventNotifier` to manage the active listeners. This avoids having a single callback that can be changed by more than one screen.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1 …
> Use an `EventNotifier` for WireGuard key events

- windows/driverlogic/src/error.cpp
Exceptions logged in Windows modules only contain formatted strings at the moment, no error codes. These can be indecipherable since the encoding is often wrong.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1777)
> Include error code in Windows error exception strings

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
A previous PR added retries if fetching the account expiry fails. An optimization was also added, where the idea was that it would only retry if there was a listener attached to receive the results. However, the implementation checked for that condition before running any fetch attempt, including the first attempt.
This condition impacted the settings screen, since it requested the fetch before setting up the listener. Therefore, what ended up happening was that the check was made before the listener was configured, and therefore it decided to not actually fetch the account expiry ever.
This PR fixes the issue with two changes. First, the settings screen configures the listener before requesting the account cache to fetch the account expiry. Second, the condition check was changed so that …
> Fix account expiry not showing up in settings

- CHANGELOG.md
- windows/winnet/src/winnet/networkadaptermonitor.cpp
- windows/winnet/src/winnet/networkadaptermonitor.h
Add mutex to deal with multiple simultaneous calls to callback. MSDN says that calls to the NotifyIpInterfaceChange() callback are serialized, but that's not accurate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1778)
> Add lock in NotifyIpInterfaceChange() callback

- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/Cell.tsx
- gui/src/renderer/components/CellStyles.tsx
- gui/src/renderer/components/Preferences.tsx
- gui/src/renderer/components/Switch.tsx
- gui/src/renderer/containers/PreferencesPage.tsx
- gui/src/renderer/redux/version/actions.ts
- gui/src/renderer/redux/version/reducers.ts
- gui/test/components/NotificationArea.spec.tsx
This PR makes the following changes:
* disables the beta program toggle when running a beta
* adds call for `setLatestVersion` when the "showBetaReleases` setting is changed
* makes sure that `nextUpgrade` is "reset" when there's no new versions. Properties that are undefined seems to be filtered from the object when sending it over the Electron IPC. When we then applied the new version data to the redux state using the spread operator, `nextUpdate` wasn't replaced by undefined since that property was missing.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1772)
> Improve beta program toggle in GUI

- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/AppVersionInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/LocationInfoCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/SettingsListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/tunnelstate/TunnelStateUpdater.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/PreferencesFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RedeemVoucherDialogFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceAwareFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
- android/src/main/kotlin/net/mullvad/talpid/util/EventNotifier.kt
Previously, the `EventNotifier` would keep an internal subscription counter and return the value as subscription IDs that could later be used to unsubscribe a listener. This worked well, however keeping track of the ID was an ergonomic issue.
This PR refactors the `EventNotifier` so that any object can be used as an ID (as long as the `hashCode` and `equals` method of the object ID aren't overridden). This makes it simpler to use, and also allowed two instances of incorrect ID tracking to be fixed (in the `PreferencesFragment` and in the `AdvancedFragment`).
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1779)
> Refactor subscription IDs in `EventNotifier`

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
When the notification button or the quick-settings tile is used to start a connection when the user hasn't granted the VPN permission, the app should start the UI in order to request for the VPN permission.
This isn't working sometimes, and there were multiple causes:
1. Opening the UI crashes on Android 9 and Android 10, because the request to open the UI is incorrect but a bug on Android allowed it work on older versions.
2. After the permission is granted, a connection attempt is retried but is ignored since the connection proxy thinks it's already connecting.
3. If the UI was previously open, the connection proxy thinks it is still open, and refuses to open it.
This PR fixes each of the issues above, by respectively:
1. Adding the missing flag that's required to start an activity from …
> Fix connect request without VPN permission not behaving as expected

- ios/PacketTunnel/WireguardConfiguration.swift
- ios/PacketTunnel/WireguardDevice.swift
Git checklist:
This PR simplifies the WireGuard configuration (back to what we had long ago):
1. Always swap the entire WireGuard configuration when changing relays or/and private keys.
1. Use a separate set of commands to update peer endpoints when roaming between networks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1783)
> Simplify WireGuard configuration

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
We've previously been stuck to an old Gradle version because we could only update it together with the Android Gradle plugin. When we attempted to upgrade the build stopped working, so that ended up being postponed.
Now, In order to use the Gradle Play Publisher plugin, we need to update. Luckily, it seems that whatever caused the build to break in the past is either fixed or not an issue anymore. The upgrade was therefore rather trivial.
I also took the opportunity to remove some old lint and format plugins that we weren't using.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1787)
> Upgrade Gradle and the Android Gradle plugin

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AdvancedFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/PreferencesFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ProblemReportFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceAwareFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
Previously, the `JobTracker` helper class was extended to have some easier to use methods that allows spawning UI and background tasks. New and updated fragments started using it instead of locally launching with `GlobalDispatch` and having to manage the `Job` instances.
This PR continues that work to refactor all fragments to use the same pattern. Since all the fragments now use a `JobTracker`, a property was added to the `ServiceAwareFragment`, which is a parent class to most fragments. The jobs are also automatically cancelled when the views are destroyed, which is also the most common behavior. Some tasks still need to be manually cancelled when the UI pauses, though.
Git checklist:
--- …
> Use `JobTracker` in all fragments

- CHANGELOG.md
- Cargo.lock
When the access rights of a named pipe was polled with
`accesschk.exe` the daemon crashed. This was fixed in miow 0.3.4
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1790)
> Upgrade miow and mio to fix named pipes crash

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RemainingTimeLabel.kt
Previously, the app would show the remaining account time in the Settings screen using the most significant unit available. However, this led to some confusion when the remaining time is more than a month but less than three months. If the user had for example 59 days remaining, the screen would say the user had "1 month left".
This PR changes that so that the app behaves like the desktop version, where it shows the remaining time in days if it's less than 90 days. Here the implementation is slightly different, since it checks if there is less than 3 months instead, and that means that it can show "91 days remaining" or "3 months remaining" when it has 89 days remaining, depending on the months.
Git checklist:
--- …
> Change how remaining time in account is shown

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/InformationView.kt
This PR adds a `displayFormatter` property to the `InformationView` and uses that in the Account screen so that it can show the account number with spaces separating every 4 digits. This makes it show the account number like it is shown in the desktop.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1792)
> Show account number with spaces on Android

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
On other platforms, the account expiration timestamp doesn't include seconds (since it's always zero). This PR updates the Android app to behave the same.
An expiry formater is configured to show shorter time information. The formater is now stored in the fragment so that it can be reused if needed without having to create a new temporary object.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1793)
> Remove seconds from displayed account expiration timestamp

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
It might be a security issue to allow the app notification or the quick-settings tile to disconnect the tunnel while the device is locked. And it might be an undesired behavior if the device connects the VPN tunnel while it's locked (for example by false touch events while the device is in a pocket).
This PR detects if the device is locked or not in order to improve the behavior. If the device is locked, connect and disconnect commands are ignored when sent by the notification or the quick-settings tile. Also, the notification manager now listens for device lock and unlock events in order to hide the notification action button when the device is locked.
Git checklist:
--- …
> Disable tunnel actions when the device is locked

- CHANGELOG.md
- gui/src/main/index.ts
This PR adds WireGuard servers to the location picker when the tunnel protocol is set to automatic on Linux and macOS.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1799)
> Show WireGuard servers on Linux and macOS when automatic protocol

- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/Map.tsx
This PR speeds up the map loading by using `componentDidMount` instead of `onLayout`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1795)
> Improve map loading times

- android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
- android/src/main/kotlin/net/mullvad/talpid/util/EventNotifier.kt
This PR replaces the account data callback in the `AccountCache` with two `EventNotifier`s, one for the account number and one for the account cache. This makes it more straightforward to handle the listeners, and also allows multiple listeners while also avoiding any race condition when swapping the callback. In some cases, usage of the callback is replaced with two listeners to keep the behavior, but in many places only one listener is necessary.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1791)
> Use `EventNotifier` in `AccountCache`

- android/src/main/res/layout/connect.xml
- android/src/main/res/values/styles.xml
This PR fixes the padding in the Select Location button. Previously the chevron was placed too close to the right button edge, and with the appropriate padding some space is added.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1802)
> Fix right chevron position in Select Location button

- gui/src/renderer/components/Marquee.tsx
- gui/src/renderer/components/TunnelControl.tsx
This PR converts `Marquee` to a styled component. It also converts `Location`, `Country` and `City` in `TunnelControl` to styled components. These components where previously declared as functional components in `render` resulting in new components being created and mounted/unmounted on each render of `TunnelControl`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1800)
> Convert Marquee to styled component

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/KeyStatusListener.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
When the `KeyStatusListener` was refactored to use an `EventNotifier`, a small bug was introduced. The `setUp` function expects the notifier object to be initialized so that it can use it, but the notifier is only initialized after the `setUpJob` co-routine is spawned. That means that if the daemon is fast enough when returning the key, there will be an attempt to access the notifier before it is initialized.
The simple fix would have been to simply change the order of operations, but I figured that it would be better to have the initialization code run on the same thread. In order to do this, the class was moved into the `service` package, and now it's created by the service and reused by the UI while the service is running.
Git checklist:
--- …
> Fix race condition in `KeyStatusListener`

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/dataproxy/MullvadProblemReport.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
Apparently, when entering split-screen mode the `Activity.onCreate` method is called with o non-null `savedInstanceState: Bundle`, and this makes the `super.onCreate` initialize the previously shown fragments and call their `Fragment.onAttach` methods.
The issue is that when this happens, the `ProblemReportFragment.onAttach` expects the `MainActivity.problemReport` object to be initialized, but it's only initialized *after* the `super.onCreate` call finishes.
This means that (for example) when you enter split-screen mode whilst on the Report a Problem screen, the steps described above will be executed and the app will crash because the fragment will try to access an uninitialized `MullvadProblemReport`.
This PR fixes that by making sure that the `problemReport` object is initialized …
> Fix crash when entering split-screen mode whilst in the Report a Problem screen

- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/build.rs
- talpid-core/src/tunnel/openvpn.rs
- talpid-openvpn-plugin/Cargo.toml
- talpid-openvpn-plugin/build.rs
- talpid-openvpn-plugin/proto/openvpn_plugin.proto
- talpid-openvpn-plugin/src/lib.rs
- talpid-openvpn-plugin/src/processing.rs
This replaces the use of JSON-RPC in `talpid-openvpn-plugin` with gRPC using `tonic`. `tokio` 0.2 was also used instead of 0.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1788)
> Use gRPC for the OpenVPN plugin

- ios/CHANGELOG.md
- ios/MullvadVPN/Account.swift
- ios/MullvadVPN/AppStorePaymentManager.swift
- ios/MullvadVPN/AutomaticKeyRotationManager.swift
- ios/MullvadVPN/MullvadRpc.swift
- ios/MullvadVPN/RelayCache.swift
- ios/MullvadVPN/RelaySelector+RelayCache.swift
- ios/MullvadVPN/SelectLocationController.swift
- ios/MullvadVPN/TunnelManager.swift
- ios/MullvadVPN/WireguardKeysViewController.swift
Git checklist:
Disable `URLSession` cache by switching to ephemeral configuration. As per docs the main advantage of using the ephemeral configuration is privacy to avoid any API responses to be cached on disk.
>An ephemeral session configuration object is similar to a default session configuration (see default), except that the corresponding session object doesn’t store caches, credential stores, or any session-related data to disk. Instead, session-related data is stored in RAM. The only time an ephemeral session writes data to disk is when you tell it to write the contents of a URL to a file.
https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1410529-ephemeral 
--- …
> Switch to using ephemeral URLSession configuration

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
When the app loses the connection to the service, it returns to the launch screen while it waits for a reconnection. However, previously the back stack wasn't cleared, which meant that the user could press back and enter an invalid state. This PR fixes that by clearing the back stack when returning to the launch screen.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1807)
> Clear back stack when returning to the Launch screen after service connection is lost

- CHANGELOG.md
- android/src/main/AndroidManifest.xml
Previously, when entering split-screen mode, Android would handle it with the default behavior for a configuration change. This led to the `MainActivity` being destroyed and recreated. When this happened, the activity was created to quickly for it to reestablish connection to the service. That led the active fragment to fallback to return to the launch screen.
This PR changes that so that the activity isn't recreated, and the current active fragment can stay operational.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1809)
> Don't allow Android to recreate the Activity when entering split-screen mode

- CHANGELOG.md
- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/src/firewall/linux.rs
Send an ICMP reject message or TCP reset packet back to the origin. This can prevent slow timeouts.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1797)
>  Reject outgoing traffic instead of dropping it on Linux 

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
Previously, sometimes the app would leave the Welcome screen right after creating a new account. It would then show the Connect screen but advance to the Out Of Time screen shortly afterwards.
This happened because of an inconsistency when comparing time instants generated with different clocks. A newly created account's expiration time is the account's expiration time, as registered by the API server's clock. The Welcome screen decides the account has been paid for when it detects that the account expiration is after the current time, as registered by the device's clock. That means that an inconsistency of a few seconds can lead the Welcome screen to think that the account has been paid for.
This PR fixes that by adding a margin of error of one day. In most cases the user adds 30 days to …
> Fix Welcome screen closing prematurely because of clock mismatch

- CHANGELOG.md
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/renderer/containers/PreferencesPage.tsx
- gui/src/renderer/redux/version/actions.ts
- gui/src/renderer/redux/version/reducers.ts
- gui/test/components/NotificationArea.spec.tsx
A few places were missed when renaming it a while ago. `currentIsBeta` has
also been renamed for more consistent naming.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1816)
> Rename all usages of currentIsSupported to just supported

- android/src/main/res/values/styles.xml
A previous PR removed an attribute from the Button style. The attribute cleared the button's default padding values and reset them all to zero. This was necessary because that forced the chevron on the Select Location button to be pushed to the right edge of the button. However, removing the attribute to fix the chevron position caused another UI glitch: a part of the descenders of the letters inside the button were chopped off.
This PR partially restores the style attribute to reset the button padding. It now only clears the vertical padding, which doesn't affect the Select Location button chevron. By removing the vertical padding, the font descenders now render correctly.
Git checklist:
--- …
> Remove button's default vertical padding

- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/src/firewall/linux.rs
Restrict the rule allowing traffic to the relay server to match on uid 0, since the daemon and its subprocesses run as root.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1819)
> Improve firewall rules on Linux

- CHANGELOG.md
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
This PR disables the automatic connect on login for expired accounts. The code performing the auto-connect has been moved to the main process to easier depend on the account verification result.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1820)
> Prevent autoconnect on login when account is expired

- gui/src/renderer/redux/account/reducers.ts
- gui/src/renderer/redux/connection/reducers.ts
- gui/src/renderer/redux/version/reducers.ts
This PR replaces the use of the spread operator for the action data in reducers. This is to workaround this design limitation of typescript: https://github.com/microsoft/TypeScript/issues/17422
There are two properties that are sent to the reducer which aren't part of the state and have therefore been omitted:
* `latestBeta` in the `'UPDATE_LATEST'` action
* `mullvadExitIP` in the `'NEW_LOCATION'` action
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1821)
> Remove use of spread operator for action data in reducers

- Cargo.lock
- mullvad-daemon/src/lib.rs
- talpid-core/Cargo.toml
- talpid-core/src/lib.rs
- talpid-core/src/routing/android.rs
- talpid-core/src/routing/linux.rs
- talpid-core/src/routing/macos.rs
- talpid-core/src/routing/mod.rs
- talpid-core/src/routing/unix.rs
I've changed the MacOS routing code to not use old futures and rely on tokio 0.2 and also fixed an issue with default route handling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1817)
> Fix routing on MacOS

- CHANGELOG.md
- android/src/main/res/layout/main.xml
Some Android UI elements from other apps can be shown over part of the Mullvad app's UI. This can open up the possibility of an attack called [tapjacking](https://blog.trendmicro.com/trendlabs-security-intelligence/tapjacking-an-untapped-threat-in-android/). This PR mitigates such possibility by telling Android to ignore touch events when the app UI is obscured by something.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1823)
> Ignore touch events when app has its UI obscured

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ProblemReportFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceAwareFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
Some screens show sensitive information such as the account number, the WireGuard key or the user's reply-to email address after sending a problem report. This information might be accidentally recorded by a screenshot or shown in the recent apps view. This PR makes sure to configure the `FLAG_SECURE` window flag when such information might be shown, to prevent this information to be recorded somewhere.
The Problem Report screen will only set the flag if the user's reply-to email is shown in the screen after the problem report has been sent successfully. The WireGuard Key screen and the Account screen are both marked with flag every time they are visible.
In order to make it simpler and less error-prone to mark screens as secure, the `MainActivity` holds a counter of currently visible …
> Secure screens with potentially sensitive data

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/NotificationBanner.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/RemainingTimeLabel.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/util/TimeLeftFormatter.kt
- android/src/main/res/values/strings.xml
Previously, the app did not notify the user that the account's time was close to its expiration. This lead to some users losing connectivity and taking a while to understand why that happened. This PR adds an in-app notification to let the user know when the remaining time in the account is less than three days.
The notification is clickable and opens the account page in the website that allows the user to buy more time.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1824)
> Show in-app warning when account time is running out

- CHANGELOG.md
- Cargo.lock
- mullvad-daemon/Cargo.toml
- mullvad-jni/Cargo.toml
- mullvad-rpc/Cargo.toml
- mullvad-types/Cargo.toml
- talpid-core/Cargo.toml
- talpid-core/src/firewall/macos.rs
- talpid-types/Cargo.toml
Some applications may hang if packets are silently blocked. The changes will send a rejection message back when outgoing packets are blocked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1828)
> Reject outgoing packets instead of dropping them on macOS

- talpid-core/src/firewall/macos.rs
Only allow root to send data to the tunnel endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1829)
> Only allow root to send tunnel traffic

- Cargo.lock
- talpid-ipc/Cargo.toml
- talpid-ipc/src/lib.rs
- talpid-ipc/src/win.rs
In some limited circumstances, daemon commands could be sent to a host in a local network, if a user was authenticated or if authentication had been disabled, and if "Allow LAN" was enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1830)
> Limit security identifiers with access to the management interface pipe

- CHANGELOG.md
- Cargo.lock
- talpid-core/Cargo.toml
- talpid-core/src/offline/macos.rs
Use `SCNetworkReachability` to determine whether host is offline. Watching the dynamic store for changes to the primary interface is still useful as that change is triggered faster than the reachability callback, but it's only useful for establishing lack of connectivity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1831)
> MacOS - improve offline detection

- build-apk.sh
A recent update of Gradle and the Android Gradle Plugin apparently changed the file name of the final bundle build artifact. This PR updates the build script to use the new path.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1832)
> Fix updated file name of the generated bundle

- gui/src/renderer/components/AppButton.tsx
This PR fixes a bug introduced in https://github.com/mullvad/mullvadvpn-app/pull/1784 where the buttons in notifications weren't clickable.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1834)
> Fix in-app notification button onclick

- mullvad-daemon/src/lib.rs
- mullvad-setup/src/main.rs
- talpid-core/src/firewall/mod.rs
- talpid-core/src/firewall/windows.rs
- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
- windows/winfw/src/winfw/fwcontext.cpp
- windows/winfw/src/winfw/fwcontext.h
- windows/winfw/src/winfw/rules/multi/permitvpnrelay.cpp
- windows/winfw/src/winfw/rules/multi/permitvpnrelay.h
- windows/winfw/src/winfw/winfw.cpp
- windows/winfw/src/winfw/winfw.h
On Windows 7, the firewall rules are not correctly interpreted. If the daemon is approved to send packets to the server at the same time as openvpn.exe is, packets from the OpenVPN process are blocked anyway. Only one process needs to be permitted to communicate with the server at a time, so with the updates, the daemon does that instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1839)
> Fix OpenVPN being unable to send packets to the relay on Windows 7

- android/src/main/kotlin/net/mullvad/mullvadvpn/service/KeyStatusListener.kt
A previous PR that fixed the WireGuard key verification on Android changed the location where null-events were filtered. However, this introduced a warning about an unnecessary null-check. And this is valid, since the daemon doesn't send `null` as a WireGuard key event.
The `keyStatus` property is only `null` if the account doesn't have a WireGuard key. No other actions in the `KeyStatusListener` will generate a `null` key status, so the filtering isn't necessary.
The only location `null` could be returned and directly set to the property was in an unused private method (probably some left-over code from some refactors). This method is now also removed by this PR.
Git checklist:
--- …
> Fix unnecessary null-check warning

- talpid-ipc/src/win.rs
In #1830, [`OsStrExt::encode_wide`](https://doc.rust-lang.org/std/os/windows/ffi/trait.OsStrExt.html#tymethod.encode_wide) was used, but a null terminator was not added to the resulting vector. In practice, the string must have been null-terminated anyway, but this PR adds one explicitly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1840)
> Fix null termination in talpid-ipc

- CHANGELOG.md
- windows/driverlogic/src/driverlogic.cpp
In order to rename the new TAP adapter created during an installation, a GUID is read from a registry value called `NetCfgInstanceId`. This isn't created *immediately* when the new device is set up, which very rarely can cause it to be read too soon. These changes monitor updates to the registry key and allow 10 seconds for the value to be created before failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1843)
> Allow some time for NetCfgInstanceId to be created

- CHANGELOG.md
- gui/src/main/index.ts
This PR makes the app wait for a WireGuard key-event before starting to connect. Connecting before the api request was done resulted in fallbacking to OpenVPN and leaving unused keys.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1849)
> Wait for WireGuard key-event before auto-connecting

- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/wireguard.rs
- mullvad-rpc/src/lib.rs
To inform the UI clients of failures to generate the first key, the daemon will now receive key generation events about all attempts of the first key generation, both failures and successes. The key generation timeout for the first key generation is also lowered to 5 seconds. This should help with the UX when the user first starts the app and tries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1848)
> Report key generation failures

- mullvad-daemon/src/logging.rs
h2 is a dependency of hyper. It logs a lot of very verbose stuff that ends up in daemon.log due to the `talpid-openvpn-plugin` crate indirectly depending on it:
```
[2020-06-16 14:45:09.713][h2::codec::framed_write][DEBUG] send; frame=Settings { flags: (0x0), initial_window_size: 1048576 }
[2020-06-16 14:45:09.713][h2::codec::framed_write][DEBUG] send; frame=WindowUpdate { stream_id: StreamId(0), size_increment: 983041 }
[2020-06-16 14:45:17.450][h2::codec::framed_read][DEBUG] received; frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152 }
[2020-06-16 14:45:17.450][h2::codec::framed_write][DEBUG] send; frame=Settings { flags: (0x1: ACK) }
[2020-06-16 14:45:17.450][h2::codec::framed_read][DEBUG] received; frame=WindowUpdate { stream_id: StreamId(0), size_increment: …
```
> Silence h2 crate in `logging`

- android/src/main/play/release-notes/en-US/beta.txt
This was submitted too late. But now at least they can
be correct in the repo :shrug: 
This was forgotten before the release. But not the end of the world. I will also update the release app docs to include doing this *before* a release next time.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1853)
> Change android release notes to 2020.5-beta2 notes

- android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ForegroundNotificationManager.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadTileService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotification.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/TunnelStateNotificationAction.kt
- android/src/main/kotlin/net/mullvad/talpid/util/EventNotifier.kt
Previously, the Android app only showed one system notification, which showed the current tunnel state and allowed the user to connect or disconnect the tunnel. In the near future, more notifications will be shown, so this PR lays the groundwork to make the notification code more modular and reusable.
This is PR is in draft-mode because a lot of the refactor work is experimental, and should probably go through a few iterations.
Previously, all of the code was handled in the `ForegroundNotificationManager` class. It handled everything from determining what message to show, how to build the notification, and if it should be on the foreground or not. Now, the class is still responsible for the same things, but it relies on other classes for help, and by itself only manages if the …
> Refactor code to manage the Android notification

- talpid-core/src/tunnel/openvpn.rs
- talpid-openvpn-plugin/proto/openvpn_plugin.proto
Instead of defining an `Empty` message in the proto file, use a well-known type that is appropriately converted into `()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1857)
> Remove unneeded Empty type

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/NotificationChannel.kt
- android/src/main/res/values/plurals.xml
- android/src/main/res/values/strings.xml
This PR implements the same behavior present in the desktop app, where a system notification is shown when the account time will expire in less than two days.
Clicking on the notification will open the web page to buy more credit. However, if the user takes too long to open the notification, the authentication token will have expired. I think that the worst case is that he'll have to enter his account number again on the website, which I think isn't a big problem.
If the notification is dismissed by the user, it will reappear twelve hours later if no credit was added.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1854)
> Show Android notification when account time is running out

- android/src/main/play/listings/en-US/full-description.txt
It seems F-Droid does not handle this as markdown. Any newline actually becomes a newline when rendered in their store listing. This made the text break the lines in very strange places. We need to keep each paragraph as a single line in this txt file it seems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1865)
> Don't manually wrap lines in Android description

- docs/security.md
This fixes audit finding MUL-02-002 and MUL-02-004.
Does this documentation update reflect the current implementation and do you agree with the formulation?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1866)
> Update security document with restrictions to allow relay rule

- gui/tasks/distribution.js
Tries to fix #1861. Also it seems more correct to not use `/usr/local` for this.
I tried it only on Fedora 31 so far but the completions work after this move.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1869)
> Install zsh shell completions to /usr/share instead of /usr/local/share

- CHANGELOG.md
- README.md
- gui/package-lock.json
- gui/package.json
- gui/src/main/index.ts
- gui/tasks/distribution.js
- gui/test/setup/main.js
This PR upgrade the Electron version from 7.1.10 to 8.3.3 which contains the tray-icon fix.
Electron 8.0 changelog:
https://www.electronjs.org/blog/electron-8-0
Electron 8.3.2 changelog wich includes tray icon fix:
https://github.com/electron/electron/releases/tag/v8.3.2
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1867)
> Upgrade to Electron 8 again

- CHANGELOG.md
- build.sh
- dist-assets/pkg-scripts/postinstall
- gui/tasks/distribution.js
Generate fish shell completions at build time. Empower fish users with
completions.
Completions are copied in the [recommended directory](https://fishshell.com/docs/current/#where-to-put-completions).
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1860)
> Add fish shell completions

- dist-assets/pkg-scripts/postinstall
- dist-assets/uninstall_macos.sh
- gui/tasks/distribution.js
This PR updates the fish shell completions directory on macOS since this seems to be the one in use. [Both directories are mentioned in the docs](https://fishshell.com/docs/current/#where-to-put-com). It also prevents adding the completions if the directory doesn't exist since that made `postinstall.sh` fail.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1888)
> Change fish completions directory and only symlink if directory exists

- CHANGELOG.md
- talpid-core/src/ping_monitor/unix.rs
- talpid-core/src/tunnel/wireguard/connectivity_check.rs
Improve the resiliency of the connectivity monitor against suspension.
To help improve the resiliency of WireGuard connections during sleep/darkwake on MacOS and in general on other platforms, the connectivity monitor will reset it's traffic data every time it detects that it's been sleeping for far too long.
I'll test this out on Android and under load on desktop platforms to see how this affects the time it takes to detect an unconnectable relay, since now the connetivity check will potentially be more lenient when it tries to establish connectivity on a new connection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1878)
> Improve conncheck resilience

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
The app has long had a weird bug where sometimes it wouldn't quit properly, restarting itself a few seconds later. There has been a few attempts at fixing that, but it is still present in the latest release. From recent problem reports that have extra debug information, it seems that Android is rebinding the service temporarily while it is shutting down. This causes the service to think that the UI is connected to it, and cancels the shutdown (or rather, effectively restarts after the shutdown is complete).
This PR changes that so that to add a flag to store if the service was requested to stop. Now, if it is temporarily rebound it will still restart, but it will continue the shutdown process by scheduling itself to stop later on when it becomes unbound again.
In effect, this means that …
> Fix app restarting if service is rebound temporarily

- gui/src/renderer/components/AppButton.tsx
- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/NotificationArea.tsx
- gui/src/renderer/components/NotificationBanner.tsx
This PR converts the components in `NotificationBanner.tsx` from ReactXP to React and Styled components. Some other things have been improved as well:
* The transition distance/duration calculation now produces the same speed in all situations.
* The notification content will now be visible during the hide-transition as well, as can be seen in these GIFs:
Before:
After:
The GIFs are played at 50% speed. I don't know why github does this :/
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1890)
> Convert Notification Area components from ReactXP

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/NotificationBanner.kt
In-app notifications appear by sliding out from behind the header bar. They disappear by sliding back into the header bar. However, if the notification changes, it is immediately updated, without any animation. This PR changes that so that if the notification changes, the old notification will slide back behind the header bar, change its contents and then slide back out.
The animation is implemented with an `ObjectAnimator`. It is started whenever the notification must be shown. Before starting the animation, the UI is updated, but still kept invisible. After a delay of 20ms (which should be enough for a new frame to be drawn and therefore for the layout to be complete) the animation starts by making the banner visible and sliding it down.
When the notification changes, the animation is …
> Animate in-app notification changes on Android

- CHANGELOG.md
- dist-assets/linux/before-remove.sh
- dist-assets/uninstall_macos.sh
- dist-assets/windows/installer.nsh
- mullvad-cli/src/cmds/account.rs
- mullvad-daemon/src/account_history.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/wireguard.rs
- mullvad-ipc-client/src/lib.rs
- mullvad-rpc/src/lib.rs
- mullvad-rpc/src/rest.rs
- talpid-core/src/future_retry.rs
This PR adds a new RPC to the daemon to clear the account history, which in turn attempts to remove all WireGuard keys. This is then used in the uninstallation scripts before the daemon is shut down.
Originally, I had intended to change `mullvad-setup` and just execute `account_history.clear()` there. This would've allowed clearing of the keys even if the daemon wouldn't be running. The issue with this approach is that `mullvad-setup` would have to resolve the cache and settings directories when being ran as an administrator on Windows - the cache and settings directories are different between the admin user and the _service_ user.
And somewhere along the way, the account history and the wireguard modules in the daemon were updated to use the new style futures.
--- …
> Remove WireGuard keys when uninstalling.

- android/src/main/res/values/strings.xml
Changed the notification text for when the account has already expired to match the desktop version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1897)
> Use correct expiry notification text on Android

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/UnderNotificationBannerBehavior.kt
Previously, the padding inside the Connect screen below the header bar is updated immediately after the in-app notification was changed. This caused the Connect screen view to jump a bit when the view is in scrolling mode (for example when the app is in split-screen mode). This PR animates the padding change so that it becomes smooth. There is still a lag between the animations (probably due to extra layouts required), but removing the lag would probably require a much more complex solution.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1894)
> Smoothen padding change in the Connect screen

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/notification/VersionInfoNotification.kt
- android/src/main/res/values/strings.xml
If the user is running an unknown version (which is probably a custom development version), an in-app notification appears to say that the version is not supported. However, the notification would previously say that the user should upgrade to a `null` version. This is because the code was previously assuming that an unsupported version always had a more recent version to upgrade to. This is not true for unknown versions, so this PR fixes that by removing the upgrade part of the message.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1895)
> Change message for unknown unsupported version

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/ChainedError.swift
- ios/MullvadVPN/DisplayChainedError.swift
Git checklist:
The idea behind is to be able to automatically traverse the error tree to be able to log errors effortlessly. Consider the following common example of Error type:
```swift
enum MyError: Error {
case myFault
case systemFault(SystemError)
}
```
It's common to implement `LocalizedError` to produce error descriptions:
```swift
extension MyError: LocalizedError {
var errorDescription: String? {
switch self {
case .myFault:
return "It's my fault!"
case .systemFault(let systemError):
return "I blame 🍎 because \(systemError.errorDescription)"
}
}
}
```
However as the Error tree grows and the more efforts are needed to print error messages. it becomes obvious that there should be a more or …
> Add ChainedError and DisplayChainedError protocols

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/Operations/AnyOperationObserver.swift
- ios/MullvadVPN/Operations/AssociatedValue.swift
- ios/MullvadVPN/Operations/AsyncBlockOperation.swift
- ios/MullvadVPN/Operations/AsyncOperation.swift
- ios/MullvadVPN/Operations/DelayOperation.swift
- ios/MullvadVPN/Operations/ExclusivityController.swift
- ios/MullvadVPN/Operations/InputOperation.swift
- ios/MullvadVPN/Operations/OperationBlockObserver.swift
- ios/MullvadVPN/Operations/OperationObserver.swift
- ios/MullvadVPN/Operations/OperationProtocol.swift
- ios/MullvadVPN/Operations/OutputOperation.swift
- ios/MullvadVPN/Operations/ResultOperation.swift
- ios/MullvadVPN/Operations/RetryOperation.swift
- ios/MullvadVPN/Operations/TransformOperation.swift
- ios/MullvadVPN/Operations/TransformOperationObserver.swift
Git checklist:
This PR brings back the advanced operations based off `Operations` classes found in `Foundation` framework. Previously we used a 3rd-party framework called `ProcedureKit`, however it seems to be abandoned and not without issues. 
In this PR I attempt at building my own mini-framework that addresses the pain points of building custom operations in the past using other frameworks.
1. `OperationProtocol` - defines the basic shape of any custom operation
1. `OperationObserver` - a protocol that defines the contract between `AsyncOperation` and the concrete implementation of observer for communicating operation lifecycle stages with the interested party.
`AsyncOperation` - the base …
> Add operations

- android/fdroid-build/env.sh
- android/fdroid-build/init.sh
- wireguard/libwg/Android.mk
- wireguard/libwg/build-android.sh
Previously, the Android build process required setting up cross-compilation toolchains in separate directories to work correctly. This also required a few workarounds to make it compile successfully.
This PR changes that to use the prebuilt tools from the NDK, which simplifies the build process.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1904)
> Build Android without using standalone toolchains

- ios/.gitignore
- ios/BuildInstructions.md
- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN.xcodeproj/xcshareddata/xcschemes/MullvadVPN.xcscheme
- ios/MullvadVPN/MullvadRpc.swift
- ios/MullvadVPN/ObserverList.swift
- ios/MullvadVPN/RelayCache.swift
- ios/MullvadVPN/RelayList.swift
- ios/update-relays.sh
Git checklist:
1. "Un-combine" `MullvadRpc` and adds `MullvadRpc.Request` along with `MullvadRpc.Operation` both of which can be used depending on the preferred way of executing tasks, but ultimately `MullvadRpc.Request` runs the network requests.
1. "Un-combine" `RelayCache`
1. Add observation support to `RelayCache` to be able to pick up events when relays are being updated. In the future, the GUI app will only update relays once when started while the majority of work will be done by the tunnel. Nevertheless in future PRs SelectLocation controller will listen to updates and react accordingly, just in case if the initial load takes longer than expected once the app started.
1. Add …
> Bundle relays with the app

- README.md
This PR updates the README so that the build setup doesn't install standalone toolchains, since the Android app can now be built without them.
It also updates the recommended NDK version to `r20b`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1906)
> Update build setup steps for Android in the README

- android/src/main/AndroidManifest.xml
This PR disables a feature that was introduced on a newer Android Gradle plugin version that creates the release APK with uncompressed native binaries, causing it to have an increased size.
With the feature disabled, the final APKs should be smaller.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1908)
> Force JNI libraries to be compressed

- mullvad-daemon/src/cli.rs
Maybe about time to get rid of the annoying:
```
warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
--> mullvad-daemon/src/cli.rs:69:17
|
69 |         .author(crate_authors!(", "))
|                 ^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
= note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
I have realized that `clap` will never fix the warning. Simply because that would bump the MSRV, and `clap 2` has apparently stated that it should remain at 1.24 :man_shrugging:  :( (https://github.com/clap-rs/clap/pull/1988)
So I rearranged the code a little bit in order to be able to stick an `#[allow(deprecated)]` on the problematic code, but just as little of it as possible. …
> Ignore deprecation warning in clap macro invocation

- gui/src/renderer/components/AccountStyles.tsx
- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/AdvancedSettingsStyles.tsx
- gui/src/renderer/components/AppButtonStyles.tsx
- gui/src/renderer/components/Cell.tsx
- gui/src/renderer/components/CellStyles.tsx
- gui/src/renderer/components/ChevronButton.tsx
- gui/src/renderer/components/CityRow.tsx
- gui/src/renderer/components/ConnectionPanel.tsx
- gui/src/renderer/components/CountryRow.tsx
- gui/src/renderer/components/ErrorBoundary.tsx
- gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx
- gui/src/renderer/components/HeaderBar.tsx
- gui/src/renderer/components/Launch.tsx
- gui/src/renderer/components/LoginStyles.tsx
- gui/src/renderer/components/Modal.tsx
- gui/src/renderer/components/NotificationBanner.tsx
- gui/src/renderer/components/RelayRow.tsx
- gui/src/renderer/components/RelayStatusIndicator.tsx
- gui/src/renderer/components/Selector.tsx
- gui/src/renderer/components/Settings.tsx
- gui/src/renderer/components/SettingsHeader.tsx
- gui/src/renderer/components/SettingsStyles.tsx
- gui/src/renderer/components/SupportStyles.tsx
- gui/src/renderer/components/Switch.tsx
- gui/src/renderer/components/TunnelControl.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/components/WireguardKeysStyles.tsx
- gui/src/renderer/components/common-styles.ts
This PR scales down the desktop UI a bit and makes font sizes and paddings more consistent. Letter spacing has also been removed since it was inconsistently used and probably isn't used on the other platforms.
Before and after screenshots:
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1913)
> Scale down desktop UI

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
Some recent change caused a bug, where starting the `MullvadVpnService` with a command to connect would only open the UI instead of actually connecting in the background. This happened because the service used an internal `loggedIn` flag to keep track if there was an account token set. However, when the service is started and requested to connect, the flag was checked before it had enough time to be initialed with the value from the initial settings, causing the service to think it wouldn't be able to connect because there is no account set. It would then open the UI so that the user could log in before connecting, but by the time the UI opened the flag would have been set but the connection would have been cancelled.
This PR fixes that by removing the flag and checking for the presence …
> Fix quick-settings tile connect action

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/talpid/util/EventNotifier.kt
Sometimes the Android notification would stay in the foreground when it shouldn't. This happened because the notification manager would use tunnel state events to update the foreground status in an unexpected way. Instead of using the tunnel state provided by the callback, it would manually get the state through the `EventNotifier.latestEvent` property. This is because it would call a common `updateNotification` method, that is also called in scenarios that aren't tunnel state changes. To be able to use the tunnel state in different scenarios, the decision was made to query the tunnel state stored in the `EventNotifier` instead of storing the tunnel state in the `ForegroundNotificationManager` class.
This eventually led to a bug, since the `EventNotifier` would only update the …
> Fix notification not becoming dismissible

- gui/locales/da/messages.po
- gui/locales/de/messages.po
- gui/locales/es/messages.po
- gui/locales/fi/messages.po
- gui/locales/fr/messages.po
- gui/locales/it/messages.po
- gui/locales/ja/messages.po
- gui/locales/ko/messages.po
- gui/locales/messages.pot
- gui/locales/nb/messages.po
- gui/locales/nl/messages.po
- gui/locales/pl/messages.po
- gui/locales/pt/messages.po
- gui/locales/ru/messages.po
- gui/locales/sv/messages.po
- gui/locales/th/messages.po
- gui/locales/tr/messages.po
- gui/locales/zh-CN/messages.po
- gui/locales/zh-TW/messages.po
- gui/src/renderer/components/RedeemVoucher.tsx
This PR fixes a typo with the word `occurred` in the Redeem Voucher screen. This also led to changing the `msgid` to the respective translations.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1919)
> Fix typo in `occurred`

- gui/src/renderer/components/LocationList.tsx
This PR adds margin around the icon next to the bridge entry location "Closest to exit server".
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1923)
> Fix icon margin for closest bridge entry location icon

- gui/src/renderer/components/AdvancedSettings.tsx
- gui/src/renderer/components/AdvancedSettingsStyles.tsx
- gui/src/renderer/components/CustomScrollbars.tsx
- gui/src/renderer/components/ExpiredAccountErrorView.tsx
- gui/src/renderer/components/ExpiredAccountErrorViewStyles.tsx
- gui/src/renderer/components/HeaderBar.tsx
- gui/src/renderer/components/NavigationBar.tsx
- gui/src/renderer/components/NavigationBarStyles.tsx
- gui/src/renderer/components/ScopeBar.tsx
- gui/src/renderer/components/SelectLanguage.tsx
- gui/src/renderer/components/SelectLocation.tsx
- gui/src/renderer/components/SelectLocationStyles.tsx
- gui/src/renderer/components/Settings.tsx
- gui/src/renderer/components/SettingsHeader.tsx
- gui/src/renderer/components/SettingsStyles.tsx
- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/components/WireguardKeysStyles.tsx
This PR converts `NavigationBar` and `SettingsHeader` from ReactXP to pure React and Styled components. Additionally a hover effect has been added to back buttons.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1922)
> Convert NavigationBar and SettingsHeader from ReactXP

- gui/tasks/distribution.js
This PR moves the fish completions into `vendor_completions.d` instead of trying to replace it. This solves the following error message during install:
```
Unpacking mullvad-vpn (2020.5.0-dev-e906ab) over (2020.5.0) ...
dpkg: error processing archive /home/oskar/mullvadvpn-app/dist/MullvadVPN-2020.
5-dev-e906ab_amd64.deb (--unpack):
trying to overwrite directory '/usr/share/fish/vendor_completions.d' in packag e fwupd 1.3.9-4ubuntu0.1 with nondirectory
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1926)
> Fix fish completions location on linux

- .travis.yml
To make CI work I used this quick fix. The problem is hopefully gone as soon as we get rid of the jsonrpc dependency which brings in the super old `parity-tokio-ipc` dependency that is messing with the lockfile currently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1931)
> Allow Rust beta builds to fail on Travis temporarily

- CHANGELOG.md
- mullvad-daemon/src/lib.rs
I've added a daemon command to reconnect a WireGuard tunnel after receiving a new key. This should apply to both first time key regeneration and key rotation. I've done this by spawning a future on the RPC runtime. This can be changed once we migrate everything to new tokio. I've also changed the way the previous delayed reconnect works to use tokio instead of spawning a thread - this enables us to share the cancellation logic between both cases, as the circumstances where each would be used I believe are mutually exclusive. 
The cancellation of the delayed reconnection is issued when changes to the tunnel state are issued - technically this leaves a race condition where there reconnect might be issued as the tunnel state machine is already transitioning to a new state. This is fine as …
> Reconnect WireGuard tunnels after key rotation

- CHANGELOG.md
- talpid-core/src/ping_monitor/mod.rs
- talpid-core/src/ping_monitor/unix.rs
- talpid-core/src/ping_monitor/win.rs
- talpid-core/src/tunnel/wireguard/connectivity_check.rs
I've left a horrible bug where the WireGuard connectivity monitor won't disconnect from a relay once connectivity has been lost. The fix is rather simple.
I've also added some tests which require some invasive refactoring. Ideally, we'd be able to mock the OS timers and sleeps to test this robustly, but that is not the case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1920)
> Stop the connectivity monitor after ping times out

- android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
- android/src/main/kotlin/net/mullvad/talpid/tun_provider/InetNetwork.kt
- mullvad-jni/Cargo.toml
- mullvad-jni/src/lib.rs
- mullvad-jni/src/talpid_vpn_service.rs
- talpid-core/Cargo.toml
- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel/tun_provider/android/mod.rs
In order to prepare for the Android split-tunnelling behavior, the tunnel handling code must be able to recreate the tunnel and reconnect when the split-tunnelling configuration changes. This PR lays some ground work to make that simpler, by moving the "tunnel device cache" from Rust to Kotlin. It's not completely moved, since route calculation is still done in the Rust side, so it needs to recalculate the `TunConfig` when `allowLan` changes and send that updated configuration to the Java side.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1932)
> Manage tun from java side

- android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListAdapter.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListItemHolder.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ServiceInstance.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/SplitTunnelling.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceConnection.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SplitTunnellingFragment.kt
- android/src/main/kotlin/net/mullvad/talpid/TalpidVpnService.kt
This PR continues the implementation of split tunnelling on Android. This PR implements the actual split tunnelling configuration to make it work. The only missing part is persisting the configuration, which will be done in the next PR.
A `SplitTunnelling` helper class was added to be used by the UI to configure split tunnelling. It can enable or disable the feature as a whole, and add and remove apps that are excluded from the tunnel. Every time these settings change, the list of excluded apps in `TalpidVpnService` is updated, the tunnel is marked as stale and a reconnect is requested. This forces the tun device to be recreated with the updated exclusion list.
Git checklist:
--- …
> Android split tunnelling behavior

- dist-assets/windows/installer.nsh
Correct stack imbalance caused by insufficient popping in the NSIS uninstallation path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1939)
> Windows: Fix ExecToStack calls

- Cargo.lock
I ran `cargo audit` on our project and found a rather newly reported security vulnerability in `tokio-rustls`. I don't think this affects us in any noticeable way really. But does not hurt to upgrade.
https://rustsec.org/advisories/RUSTSEC-2020-0019
I skipped listing it in the changelog since I don't think it can really impact our users :thinking: 
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1940)
> Upgrade tokio-rustls to 0.13.1 due to security vulnerability

- CHANGELOG.md
- talpid-core/src/tunnel/mod.rs
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
- wireguard/libwg/libwg_windows.go
Effectively, only wait on the IPv6 interface when IPv6 is enabled in the settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1941)
> Fix WireGuard not connecting if IPv6 is disabled

- CHANGELOG.md
- gui/src/main/index.ts
- gui/src/main/notification-controller.ts
- gui/src/shared/notifications/account-expired.ts
- gui/src/shared/notifications/close-to-account-expiry.ts
- gui/src/shared/notifications/notification.ts
- gui/src/shared/notifications/unsupported-version.ts
This PR changes the behavior notifications to:
* Not close critical notifications after 4s
* Show a button for actions in macOS instead of making the whole notification clickable
* Clicking on notifications that doesn't have an action (or all on macOS) opens the app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1930)
> Improve notification timeout

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/applist/AppListAdapter.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/SplitTunnelling.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SplitTunnellingFragment.kt
This PR completes the split-tunnelling feature implementation on Android by adding persistence to the configuration. Whether the feature is enabled or not is stored as a shared preference, and the list of apps that are excluded from tunnel is stored in a separate text file. The configuration is persisted every time the user leaves the split tunnelling settings screen.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1938)
> Implement persistence of split-tunnelling configuration on Android

- CHANGELOG.md
- mullvad-exclude/src/main.rs
- talpid-core/src/split_tunnel/linux.rs
- talpid-types/src/cgroup.rs
- talpid-types/src/lib.rs
People have been issues due to the daemon mounting (#1893), but that's only due to a bug in `crun`. To aid such cases, I've added a way to force the daemon to mount the `net_cls` controller in a user controlled location via setting the `TALPID_NETCLS_MOUNT_DIR` environment variable. This should be set via the systemd unit file for the daemon. 
Since the mount point can be wherever, the daemon and `mullvad-exclude` will read `/proc/mounts` to determine the mount path of the controller. Technically, there can be  a race condition between reading the mount path and someone unmounting the controller, but root can unmount the controller at any point in time anyway - the daemon will just gracefully shut down anyway.
--- …
> Determine net cls mount at runtime

- mullvad-types/src/account.rs
A format string that's supposed to contain an error code only outputs `_0`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1957)
> Fix format string in VoucherError

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ProblemReportFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
- android/src/main/res/layout/out_of_time.xml
- android/src/main/res/layout/problem_report.xml
- android/src/main/res/layout/welcome.xml
- android/src/main/res/values/strings.xml
This PR changes some Android strings so that they can be matched with their equivalents in the desktop app. Some of them contain minor wording changes, some became capitalized, and some had to have their display code changed so that the format parameters also match the desktop version.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1958)
> Update Android strings to better match desktop strings

- Cargo.lock
- mullvad-tests/Cargo.toml
- mullvad-tests/build.rs
- mullvad-tests/src/lib.rs
- mullvad-tests/tests/connection.rs
- mullvad-tests/tests/startup.rs
- mullvad-types/src/location.rs
- mullvad-types/src/states.rs
Running `./integration_tests.sh` failed for a few reasons:
* The relay list was downloaded when the daemon was started, replacing the fake list.
* The relay list format had changed.
* `talpid-openvpn-plugin` hosts a gRPC server, but `mullvad-tests` tried to connect using JSON-RPC.
* Other types had changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1953)
> Fix mullvad-tests crate

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountCell.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AppVersionCell.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/Cell.kt
- android/src/main/res/layout/account_history_entry.xml
- android/src/main/res/layout/app_list_item.xml
- android/src/main/res/layout/confirm_no_email.xml
- android/src/main/res/layout/connect.xml
- android/src/main/res/layout/header_bar.xml
- android/src/main/res/layout/information_view.xml
- android/src/main/res/layout/launch.xml
- android/src/main/res/layout/login.xml
- android/src/main/res/layout/mtu_edit_text.xml
- android/src/main/res/layout/notification_banner.xml
- android/src/main/res/layout/out_of_time.xml
- android/src/main/res/layout/problem_report.xml
- android/src/main/res/layout/redeem_voucher.xml
- android/src/main/res/layout/relay_list_item.xml
- android/src/main/res/layout/select_location_header.xml
- android/src/main/res/layout/settings_back_button.xml
- android/src/main/res/layout/split_tunnelling_header.xml
- android/src/main/res/layout/welcome.xml
- android/src/main/res/layout/wireguard_key.xml
- android/src/main/res/values/dimensions.xml
- android/src/main/res/values/styles.xml
This PR consolidates the text sizes used on the Android UI, and tweaks them a little to look more like the desktop app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1962)
> Tweak text sizes on Android

- CHANGELOG.md
- gui/src/main/daemon-rpc.ts
- gui/src/main/index.ts
- gui/src/renderer/app.tsx
- gui/src/renderer/components/Connect.tsx
- gui/src/renderer/components/TunnelControl.tsx
- gui/src/shared/daemon-rpc-types.ts
- gui/src/shared/notifications/error.ts
- mullvad-cli/src/cmds/status.rs
- talpid-core/src/firewall/windows.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-core/src/tunnel_state_machine/error_state.rs
- talpid-types/src/tunnel.rs
- windows/winfw/src/winfw/winfw.cpp
- windows/winfw/src/winfw/winfw.h
This makes a couple of improvements to firewall error handling:
* Detect whether the firewall failed due to being unable to acquire the transaction lock on Windows. Usually this is due to third-party software, so this will allow the backend to pass the process (PID, and application name) responsible to the GUI and display it. (The detection is not yet implemented.)
* If blocking fails in the error state, display the cause in the GUI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1959)
> Improve handling of firewall errors

- CHANGELOG.md
- talpid-core/src/dns/linux/systemd_resolved.rs
Address some of the issues raised in #1952. The underlying issue is that the daemon would attempt to parse `/etc/resolv.conf` by a rather strict parser that would fail due to there being an unknown option being added to the file. The file is parsed to check if it contains the local resolver address  to address cases where the user might've changed the file. This behavior has been removed, but we should test this out more extensively to see what happens on older distributions. The DNS management has also been simplified with systemd-resolved by not using it when the stub `resolv.conf` file is not symlinked. This is because in case the _real_ `resolv.conf` file is being used, the glibc resolver will be used, and it will query the first 3 DNS servers listed in `resolv.conf` in order, …
> Fix systemd-resolved DNS management

- .travis.yml
- windows/nsis-plugins/src/tray/trayparser.cpp
This was causing CI to fail.
Presumably it is due to a change in the VC headers. This header (`iterator`) must have been imported indirectly before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1969)
> Add missing header

- CHANGELOG.md
- talpid-core/src/dns/linux/mod.rs
- talpid-core/src/dns/linux/network_manager.rs
Currently the DNS manager using NetworkManager applies the DNS configuration globally, so it persists if the daemon dies. This was fixed by setting the DNS servers only on the tunnel interface.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1965)
> Set DNS servers on the tunnel link only with NM

- gui/src/renderer/components/AdvancedSettingsStyles.tsx
- gui/src/renderer/components/SettingsHeader.tsx
This PR changes the horizontal margin of `SettingsHeader` to `22px` from `20px` which was left there by mistake.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1973)
> Fix page margin in SettingsHeader

- gui/src/renderer/components/AdvancedSettingsStyles.tsx
- gui/src/renderer/components/CustomScrollbars.tsx
- gui/src/renderer/components/PreferencesStyles.tsx
This PR fixes an issue where some screens didn't fill the viewport due to the `className` prop in `CustomScrollbars` being overridden.
This PR also changes the page bottom margin to `22px` in `Settings` and `AdvancedSettings`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1979)
> Prevent override of CustomScrollbar className prop

- ios/MullvadVPN/Operations/AssociatedValue.swift
Git checklist:
This PR fixes a segfault in swiftc. Somehow Swift is not able to infer `Self` in the context of class method of generic `AssociatedValue<T>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1980)
> Fix Swift compiler segfault in release build

- gui/src/renderer/components/CityRow.tsx
- gui/src/renderer/components/CountryRow.tsx
- gui/src/renderer/components/RelayRow.tsx
Some previous change removed the transparancy of disabled rows in the location picker. This PR fixes that.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1970)
> Make disabled location text color 80% transparent

- gui/package-lock.json
- gui/package.json
- gui/src/renderer/components/TransitionContainer.tsx
This PR upgrades `typescript` and `tsc-watch` to latest versions.
The changelog for `typescript` 3.9 mentions improved compilation speed for projects using `styled-components` among other things: https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1972)
> Upgrade to typescript 3.9.7

- Cargo.lock
- mullvad-daemon/src/cli.rs
Upgrade `clap` to a just released version that suppresses the deprecation warning. As a result we can remove the hack that I introduced in #1910 to get rid of it by ourselves.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1985)
> Upgrade clap to 2.33.3 and remove deprecated warning hack

- gui/package-lock.json
- gui/package.json
This PR upgrades some dependencies to fix vulnerabilities further down the dependency tree. The affected dependencies are `browser-sync`, `electron-builder` and `electron-mocha`.
`npm audit` still reports one vulnerability in `gulp`'s dependency tree which looks like we'll have to wait for gulp 5 for it to be fixed.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1971)
> Upgrade npm dependencies

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/notifications/AccountExpiryNotification.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
Previously, when a user creates a new account a notification would appear saying that the account time had expired. Since the account is new, that's rather obvious and the notification is unhelpful (if not confusing). This PR changes the app to not show the notification after creating an account.
Because the notification is handled by the service, it had no knowledge of whether the current account is new or not. The UI needed a way to tell the service that it was creating an account. There are a few options on how to do this, but I ended up choosing the simplest one, using the `AccountCache` as a proxy between the UI and the service. It already serves that purpose when providing to the UI the account number and the expiration, and now it also provides to the service if the UI requested a …
> Don't show account time expired notification for new accounts

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/MainActivity.kt
The issue where trying to quit the app fails because it restarts by itself still seems to happen sometimes. The cause is still unknown, but there was a weird log sequence in a recent reproduction of the issue. Apparently `MainActivity.onStart` was called while the app was quitting (without a `MainActivity.onStop` call since the previous `MainActivity.onStart`). This might've been just some other weird issue, but in case it is related this PR changes the `onStart` method to not start the service if it knows the app is quitting.
The PR also adds extra log messages to the `MainActivity` in order to trace the connection between the service and the UI, since part of the issue might be one trying to start the other in a non-ending cycle.
Git checklist:
--- …
> New attempt to fix app restarting by itself when quitting

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/CellSwitch.kt
- android/src/main/res/values/dimensions.xml
Previously the cell switch widget used on Android could get stuck in an intermediate position. This would happen when a user manually drags the knob to a position that's not far enough from its initial position to cause a state change.
This PR fixes that by making sure to call the animation handler method every time the state is set (even if it is set to the same value). However, this led to an issue where the animation could start twice, and if it was reversed it would be reversed again restoring the default animation direction and ending up in the wrong state. The fix for this was to track if the animation was already running in a reversed state.
The PR also shrinks the widget size to better match the desktop component dimensions.
Git checklist:
--- …
> Fix cell switch widget for Android

- gui/src/renderer/components/CityRow.tsx
- gui/src/renderer/components/CountryRow.tsx
- gui/src/renderer/components/LinuxSplitTunnelingSettings.tsx
- gui/src/renderer/components/RelayRow.tsx
- gui/src/renderer/components/Selector.tsx
This PR changes the font weight to "normal" in list item labels such as countries/cities/relays in `SelectLocation`, items in `Selector` and items in the the language selector.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1989)
> Change font weight to normal in list item labels

- ios/MullvadVPN/PacketTunnelIpc.swift
- ios/MullvadVPN/SimulatorTunnelProviderHost.swift
- ios/PacketTunnel/PacketTunnelProvider.swift
…mitive types without top level container
Git checklist:
The JSON serialiser on iOS < 13 only supports arrays and objects as top-level elements. This PR wraps the IPC response in `PacketTunnelResponse<T>` generic container to satisfy such constraint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1994)
> Fix IPC response serialisation on iOS < 13

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConfirmNoEmailDialogFragment.kt
- android/src/main/res/layout/confirm_no_email.xml
This PR updates the dialog for the user to confirm that they want to send a problem report without a way for support to contact them back. The dialog now matches the dialog on the desktop app.
The major change is that the dialog now occupies the full width of the devices (with a side margin) and has a warning image above the text.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1990)
> Update confirm no email dialog to match the desktop app

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
- android/src/main/res/layout/out_of_time.xml
- android/src/main/res/values-da/strings.xml
- android/src/main/res/values-de/strings.xml
- android/src/main/res/values-es/strings.xml
- android/src/main/res/values-fi/strings.xml
- android/src/main/res/values-fr/strings.xml
- android/src/main/res/values-it/strings.xml
- android/src/main/res/values-ja/strings.xml
- android/src/main/res/values-ko/strings.xml
- android/src/main/res/values-nb/strings.xml
- android/src/main/res/values-nl/strings.xml
- android/src/main/res/values-pl/strings.xml
- android/src/main/res/values-pt/strings.xml
- android/src/main/res/values-ru/strings.xml
- android/src/main/res/values-sv/strings.xml
- android/src/main/res/values-th/strings.xml
- android/src/main/res/values-tr/strings.xml
- android/src/main/res/values-zh-rCN/strings.xml
- android/src/main/res/values-zh-rTW/strings.xml
- android/src/main/res/values/strings.xml
- android/translations-converter/src/main.rs
Some string resources on Android had more than one ID, which meant that translations didn't work for them. This PR updates the translation conversion tool to report such issues, and fixes the two issues that were previously present.
One of the strings was repeated because one variant was used in the UI and another was used as meta-data for the clipboard. The meta-data for the clipboard was updated to be clearer.
The other string was repeated due to a refactor which split a long string in two and created a new resource for the first part instead of reusing the previously existing resource.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1996)
> Remove repeated strings resources on Android

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LocationInfo.kt
- android/src/main/res/values-da/strings.xml
- android/src/main/res/values-de/strings.xml
- android/src/main/res/values-es/strings.xml
- android/src/main/res/values-fi/strings.xml
- android/src/main/res/values-fr/strings.xml
- android/src/main/res/values-it/strings.xml
- android/src/main/res/values-ja/strings.xml
- android/src/main/res/values-ko/strings.xml
- android/src/main/res/values-nb/strings.xml
- android/src/main/res/values-nl/strings.xml
- android/src/main/res/values-pl/strings.xml
- android/src/main/res/values-pt/strings.xml
- android/src/main/res/values-ru/strings.xml
- android/src/main/res/values-sv/strings.xml
- android/src/main/res/values-th/strings.xml
- android/src/main/res/values-tr/strings.xml
- android/src/main/res/values-zh-rCN/strings.xml
- android/src/main/res/values-zh-rTW/strings.xml
- android/src/main/res/values/strings.xml
The Android app would previously use string formatting parameters to create the endpoint information strings in the Connect screen. That was different from the desktop app, which used separate elements for the label and the value. This meant that the translation for the string resource couldn't be used.
This PR removes the formatting parameters and manually adds the parameters to the end of the string, so that the string resource can have a translation imported from the desktop app.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1997)
> Remove In/Out address string resource parameters

- .travis.yml
It looks like the Travis jobs "Daemon, Windows - beta Rust" and "Daemon, Linux - beta Rust" has been succeeding for the last 27 days. They have been reenabled in this PR.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1998)
> Require Travis jobs for beta Rust to succeed

- Cargo.lock
- mullvad-management-interface/Cargo.toml
- mullvad-tests/Cargo.toml
- talpid-core/Cargo.toml
- talpid-openvpn-plugin/Cargo.toml
Due to a bug causing connection errors to not be detected, tonic 0.2 was still being used. This has been fixed in tonic 0.3.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2001)
> Bump tonic from 0.2 to 0.3

- android/src/main/res/values-da/strings.xml
- android/src/main/res/values-de/strings.xml
- android/src/main/res/values-es/strings.xml
- android/src/main/res/values-fi/strings.xml
- android/src/main/res/values-fr/strings.xml
- android/src/main/res/values-it/strings.xml
- android/src/main/res/values-ja/strings.xml
- android/src/main/res/values-ko/strings.xml
- android/src/main/res/values-nb/strings.xml
- android/src/main/res/values-nl/strings.xml
- android/src/main/res/values-pl/strings.xml
- android/src/main/res/values-pt/strings.xml
- android/src/main/res/values-ru/strings.xml
- android/src/main/res/values-sv/strings.xml
- android/src/main/res/values-th/strings.xml
- android/src/main/res/values-tr/strings.xml
- android/src/main/res/values-zh-rTW/strings.xml
- android/src/main/res/values/strings.xml
- android/translations-converter/src/android.rs
- android/translations-converter/src/main.rs
Some strings aren't translatable. More specifically, the account number hint (`0000 0000 0000 0000`) and the voucher hint (similar but with `X`s) don't need to be translated. Android supports having string resources with a `translatable="false"` attribute. This PR adds that attribute and updates the translation conversion helper tool to ignore those string resources.
One URL was also updated to have a locale so that it can be translated instead of being marked as not translatable.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1999)
> Ignore untranslatable Android strings

- gui/src/renderer/components/Cell.tsx
- gui/src/renderer/components/CellStyles.tsx
- gui/src/renderer/components/CityRow.tsx
- gui/src/renderer/components/CountryRow.tsx
- gui/src/renderer/components/RelayRow.tsx
This PR adds disabled styles to cells.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2017)
> Add styles for disabled Cell

- version-metadata.sh
`mullvad-exclude` was missing from this script, so its version was not being updated. Also define in one place all the crates whose .toml files to update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2014)
> Add mullvad-exclude to version-metadata.sh

- Cargo.lock
- mullvad-daemon/Cargo.toml
- mullvad-rpc/Cargo.toml
- mullvad-types/Cargo.toml
I used the third party `cargo-udeps` tool on our repository. Turns out we had quite a few unused dependencies. Most common `mullvad-paths` and `talpid-ipc` that were left on crates that no longer used them.
The real world difference here is very small since the total dependency tree only got rid of `tokio-service`. But crates should not depend on crates they don't need anyway so...
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/1944)
> Remove unused dependencies found with cargo-udeps

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt
The recently released `2020.6-beta1` version of the Android app is showing an unusually high number of crashes caused by `UnsatisfiedLinkError`. They seem to happen when calling `TalpidVpnService.defaultTunConfig`, which seems to indicate it's failing when trying to call a JNI method. One possible explanation is that the `TalpidVpnService` is calling the method before the `mullvad-jni` library is loaded (because it seems to be loaded only when the daemon is starting).
This PR tries to fix that by loading the JNI library sooner. It is now also requested to be loaded when the `MullvadVpnService` class is loaded.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadv …
> Load JNI library sooner to try to avoid crashes when starting

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/util/SegmentedInputFormatter.kt
Some crashes have been seen for a while in the Redeem Voucher dialog. The log always shows that it is caused by having an out-of-bounds value when updating the text selection. However, the logs didn't actually show the value that caused it, so the way to reproduce it was unknown.
Today I managed to reproduce the error by selecting the whole text and deleting it. The cause was that the new selection was `0..0`, and the separator handling code tried to update the selection to `-1..-1`. This PR fixes the issue but not updating the selection boundary if it's at the start of the string.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2016)
> Fix crash when removing selected text in Redeem Voucher dialog

- CHANGELOG.md
- mullvad-cli/src/cmds/relay.rs
- mullvad-daemon/src/relays.rs
- mullvad-types/src/relay_constraints.rs
As the title says. The command is `mullvad relay set relay <hostname>`. This can make setting the location constraints more convenient.
Additionally, output a warning if a relay in cannot be found when using `mullvad relay set location ...`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2009)
> Set hostname constraint directly in the CLI

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SplitTunnellingFragment.kt
Previously, entering the "Split Tunneling" screen with split tunneling enabled wouldn't show the "Exclude applications" header. It would only appear after disabling and enabling split tunneling again. This happened because the "Exclude applications" header wasn't set up when the `ListView` header view was set-up . This PR fixes that by scheduling the header to be made visible if needed when setting up the `ListView` header.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2006)
> Fix exclude applications header not shown when entering "Split Tunneling" screen

- android/src/main/res/values/plurals.xml
- android/translations-converter/src/android.rs
- android/translations-converter/src/gettext.rs
- android/translations-converter/src/main.rs
The Android app uses a few plural string resources to handle relative time. The desktop app uses the `moment` library to handle that appropriately with localization. That means that the Android app can't import the necessary relative time plural strings from the desktop app. The solution in this PR is to append the Android plurals to the desktop app's gettext localization messages template file so that they can be sent for translation later on.
The helper translation conversion tool was updated to be able to parse Android plural resource files and to be able to represent and write gettext plural messages. The tool can then just read the Android plural resources and append their gettext plural message templates to the messages template file.
Git checklist:
--- …
> Append plural messages from the Android app to the gettext messages template

- gui/src/renderer/components/ConnectionPanel.tsx
This PR fixes a graphical issue where the ipv4 and ipv6 addresses where places on the same line. This changes it to on line each.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2022)
> Make addresses use one line each

- CHANGELOG.md
- mullvad-daemon/src/version_check.rs
The newly release Android version wasn't performing any checks for new version updates or if the current version is still supported. This happened because the globaly `IS_DEV_BUILD` flag was initialized to the incorrect value.
This PR fixes that, and also makes it so that all development builds are marked as unsupported. A log message was also added so that if a similar issue occurs in the future, it is easier to narrow the root cause.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2019)
> Fix version update checks on release builds

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
The `SelectLocationFragment` was overriding the incorrect view destructor from the `ServiceDependentFragment` base class. This led to two crashes being reported in the Play store. This PR fixes the code to override the correct destructor.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2021)
> Fix crash leaving Select Location screen

- dist-assets/windows/installer.nsh
electron-builder recently [reverted](https://github.com/electron-userland/electron-builder/pull/4443) where the NSIS install/uninstall information is stored. This causes upgrades from version 2020.5 of the app to fail.
As was done before, this PR simply moves the registry key in `customInit` to its new path, fixing upgrades from older versions. This does break downgrades, though. The app has to be fully uninstalled before an older version can be installed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2023)
> Migrate old uninstall registry key

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/AccountCache.kt
Previously, the app would always show a notification when the account time ran out or was close to running out. The previous version (2020.6-beta1) changed that to not show the notification for newly created accounts in order to improve the user experience. However, that change had a bug in it. The account would be marked as not new as soon as the service could read the account expiry time. Since the "Welcome" screen checks for a new expiry every 15 seconds, the notification would reappear after 15 seconds or so.
This PR fixes the issue by only marking the account as not new after the expiry changes from the initial value. In order to do this, the first valid expiry value for the newly created account is stored and used to compare future account expiry values. This "cached" value is reset …
> Don't show out-of-time notification for new accounts

- CHANGELOG.md
- mullvad-cli/src/cmds/bridge.rs
- mullvad-cli/src/cmds/relay.rs
- mullvad-cli/src/location.rs
- mullvad-daemon/src/lib.rs
- mullvad-daemon/src/management_interface.rs
- mullvad-daemon/src/relays.rs
- mullvad-management-interface/proto/management_interface.proto
- mullvad-types/src/relay_constraints.rs
- mullvad-types/src/settings/migrations/v1.rs
- mullvad-types/src/settings/mod.rs
These changes introduce a constraint to restrict the relay selector to choosing servers matching a given hosting provider. These CLI commands were added:
`mullvad relay set provider <provider>`
`mullvad bridge set provider <provider>`
`mullvad relay list` and `mullvad bridge list` were also updated to include the hosting provider of each server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2018)
> Add provider constraint

- dist-assets/linux/before-install.sh
Kill Electron app before upgrade on Linux. Without this an old version of the app will continue to run after the upgrade which might result in issues when communicating with the newer daemon.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2024)
> Kill Electron app before upgrade on Linux

- CHANGELOG.md
- mullvad-daemon/src/relays.rs
Introduced by commit `753164546`:
```
loop {
let mut check_interval = tokio02::time::interval(UPDATE_CHECK_INTERVAL).fuse();
let mut download_future = Box::pin(Fuse::terminated());
futures::select! {
_check_update = check_interval.next() => {
if !download_future.is_terminated() && self.should_update() {
download_future = Box::pin(Self::download_relay_list(self.rpc_client.clone()).fuse());
self.earliest_next_try = Instant::now() + UPDATE_INTERVAL;
}
},
...
```
Since `check_interval` is assigned inside the loop, it is resolved every time this loops. (The first tick completes immediately.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2025)
> Fix relay update timer

- gui/src/main/index.ts
My guess is that the switch to gRPC changed `relay.bridges` from being undefined to `{ shadowsocks: [] }` if the current relay isn't a bridge server and therefore the previous logic here fails.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2027)
> Only show bridge servers in location entry list

- mullvad-types/src/relay_constraints.rs
This PR removes an infinite recursion in the implementation of `Default` for the `RelayConstraints` type. Unfortunately, that means that each field must be manually specified.
The PR also marks the `provider` field as to be skipped during the conversion to the Java `RelayConstraints` class because there is no equivalent field there yet.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2032)
> Fix infinite recursion in `Default` implementation for `RelayConstraints`

- .travis.yml
- ci/ci-rust-script.sh
Previously we had some deprecation warnings we could not easily get rid of. We have now gotten rid of those. And we hit a new bad problem due to a warning we did not catch:
```
warning: function cannot return without recursing                                                                                                            
--> mullvad-types/src/relay_constraints.rs:199:5
|                                                                                                                                                        
199 |     fn default() -> Self {      
|     ^^^^^^^^^^^^^^^^^^^^ cannot return without recursing                                                                                               
...                               
202 | …
```
> Deny all Rust warnings

- mullvad-types/src/relay_constraints.rs
A previous PR marked a field related to the relay provider as to be skipped by `jnix` because it's not used yet on Android, but I managed to miss another type that also had the field. This PR also marks that field in order to prevent a crash when changing the relay constraints.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2034)
> Fix crash when Selecting Location

- dist-assets/pkg-scripts/postinstall
- dist-assets/pkg-scripts/preinstall
- mullvad-daemon/src/lib.rs
- mullvad-types/src/states.rs
Fixes a leak during upgrade due to mullvad-setup no longer being compatible with old daemon
Not mentioned in changelog as a fix, since upgrading between any existing versions does not have this leak. It's only from any existing release to anything after the gRPC migration that causes the leak.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2036)
> Run mullvad-setup prepare-restart in preinstall script instead of postinstall

- ci/ci-rust-script.sh
The jsonrpc stuff is finally gone. According to this fixme comment that was the only thing stopping us from building on nightly. And I tested now, it works to build on nightly. So let's run the full CI there as before, fewer special cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2033)
> Build all Rust code on nighly, since the blocker (jsonrpc) is gone

- windows/winfw/src/winfw/winfw.cpp
`WinFw_Deinitialize()` incorrectly returned `false` even if it succeeded (and vice versa).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2037)
> Fix return value for WinFw_Deinitialize

- gui/src/renderer/components/CityRow.tsx
- gui/src/renderer/components/CountryRow.tsx
- gui/src/renderer/components/LocationList.tsx
- gui/src/renderer/components/RelayRow.tsx
- gui/src/renderer/components/RelayStatusIndicator.tsx
- gui/src/renderer/components/SelectLocation.tsx
- gui/src/renderer/components/SelectLocationStyles.tsx
This PR converts all components related to the location picker from ReactXP. It also includes a small fix which makes the text in special location cells non-bold.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2035)
> Convert components related to the location list from ReactXP

- CHANGELOG.md
- dist-assets/windows/installer.nsh
When always-require-vpn is enabled, the WFP filters should be cleared upon a full uninstall. Currently they're not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2039)
> Purge WFP filters upon a full uninstall when always-require-vpn is enabled

- gui/src/renderer/components/WireguardKeys.tsx
- gui/src/renderer/components/WireguardKeysStyles.tsx
This PR converts the WireGuard key view from ReactXP. It also contains some visual improvements to make it both look better and more aligned with the mobile apps:
1. The `Key is valid`, `Key is invalid` and validation spinner has been moved to the end of the line next to the `Public key` label.
2. All error messages are shown between the page content and the buttons. No error message is displayed on the public key value row.
3. The spinner on the `Generate key` button has been removed since there's already a spinner in the place of the public key.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2040)
> Convert WireGuard keys view from ReactXP

- gui/assets/css/global.css
- gui/package-lock.json
- gui/package.json
- gui/src/renderer/components/PlatformWindow.tsx
- gui/src/renderer/index.html
- gui/src/renderer/index.ts
This PR converts `PlatformWindow` from ReactXP along with the React app initialization in `renderer/index.ts`.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2045)
> Convert PlatformWindow and React initialization code from ReactXP

- mullvad-daemon/src/exception_logging/unix.rs
I played around with some lints and somewhat unrelated to the lints I stumbled upon this code. Turned out it was not that many items we needed from this namespace, and I'm personally not a fan of wildcard imports. So I did this change. What do you think?
The main reason why I'm not a fan of wildcard imports is that when you see a type/function in code, you can't immediately trace where it comes from if it comes from a wildcard import. Wildcard imports can also bring in a bunch of traits without the reader noticing, these can affect the behaviour of any type and introduce new functionality. Too much magic for my taste.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/ …
> Remove a use of wildcard imports in favor of importing used items

- ios/CHANGELOG.md
- ios/MullvadVPN/LogStreamerViewController.swift
- ios/PacketTunnel/WireguardDevice.swift
Git checklist:
1. Make sure that the packet tunnel turns off WireGuard backend when there are no active network interfaces available. This is essentially the case when using airplane mode or simply switching off Wi-Fi and cellular internet. Previously WireGuard backend would indefinitely attempt to handshake with the relay and hit "send: no route" error, draining the device battery.
1. Duplicate the tunnel file descriptor (via `dup()`) because `wgTurnOff` closes the file descriptor and we should not be doing this to the system tun fd which in fact the iOS holds ownership of.
--- …
> Conditionally turn off WireGuard

- gui/src/renderer/components/ClipboardLabel.tsx
This PR moves a `messages.gettext` which was previously run before gettext was initialized which resulted in the message not being translated and a warning log.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2051)
> Initialize ClipboardLabel translation after gettext has been initialized

- mullvad-jni/src/lib.rs
- mullvad-rpc/src/lib.rs
I could not find any usage for the `MISSING_ARGUMENT` constant. So I removed it. I moved the other constants to the top of the file, where constants are usually defined, and gave them documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2047)
> Remove unused MISSING_ARGUMENT constant and document remaining constants

- gui/package-lock.json
- gui/package.json
The React devtools hasn't worked for a week or two and updating `electron-devtools-install` seems to fix this.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2052)
> Update electron-devtools-installer to 3.1.1

- gui/src/renderer/components/LinuxSplitTunnelingSettings.tsx
This PR changes the dialog messages in the Linux split tunneling view.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2053)
> Improve Linux split tunneling dialog messages

- CHANGELOG.md
- Cargo.lock
- docs/security.md
- talpid-core/Cargo.toml
- talpid-core/src/dns/linux/network_manager.rs
- talpid-core/src/firewall/linux.rs
- talpid-core/src/firewall/mod.rs
- talpid-core/src/linux.rs
- talpid-core/src/process/openvpn.rs
- talpid-core/src/routing/linux.rs
- talpid-core/src/routing/unix.rs
- talpid-core/src/tunnel/wireguard/config.rs
- talpid-core/src/tunnel/wireguard/connectivity_check.rs
- talpid-core/src/tunnel/wireguard/mod.rs
- talpid-core/src/tunnel/wireguard/wireguard_go.rs
- talpid-core/src/tunnel/wireguard/wireguard_kernel/mod.rs
- talpid-core/src/tunnel/wireguard/wireguard_kernel/nl_message.rs
- talpid-core/src/tunnel/wireguard/wireguard_kernel/parsers.rs
- talpid-core/src/tunnel/wireguard/wireguard_kernel/wg_message.rs
- talpid-core/src/tunnel_state_machine/connected_state.rs
- talpid-core/src/tunnel_state_machine/connecting_state.rs
- talpid-types/src/net/mod.rs
Add support to the daemon to use the WireGuard kernel implementation on Linux.
This is achieved by just using a netlink socket to query the system for the WireGuard neltink message type (it's a different value on different distributions), and then send various messages to create and configure a WireGuard interface. Some of the messages that are being sent and received don't have support in the libraries we're using, so I've implemented that in `talpid-core`. The Netlink library also has a nasty habit of tying a netlink connection to a message type - whilst this could be worked around, for simplicity's sake the new code spawns 3 netlink connections  every time it connects successfully.
--- …
> Linux use wg kernel module

- ios/MullvadVPN.xcodeproj/project.pbxproj
- ios/MullvadVPN/AppDelegate.swift
- ios/MullvadVPN/ApplicationConfiguration.swift
- ios/MullvadVPN/AutomaticKeyRotationManager.swift
- ios/MullvadVPN/ConnectViewController.swift
- ios/MullvadVPN/Operations/AsyncOperation.swift
- ios/MullvadVPN/Optional+DispatchQueue.swift
- ios/MullvadVPN/RelayCache.swift
- ios/PacketTunnel/PacketTunnelProvider.swift
- ios/PacketTunnel/WireguardDevice.swift
Git checklist:
1. Rework packet tunnel state management and fix the issue with the tunnel hanging during the call to set network settings.
1. Stream packet tunnel logs to stdout in the main process when in DEBUG. Makes it easier to observe what's happening in the tunnel without hooking up the packet tunnel process.
1. AsyncOperation: avoid locking the KVO calls to `willChangeValue` and `didChangeValue` to prevent the deadlock that happens when the base `Operation` class synchronously calls to `isFinished` in response to KVO notification while locking the current thread.  I have added another lock (`transactionLock`) to ensure that `start`, `finish` and `cancel` calls execute in one piece to …
> Rework packet tunnel state and fix occasional hanging

- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountInput.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountInputController.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/widget/AccountInput.kt
- android/src/main/res/layout/account_input.xml
- android/src/main/res/layout/login.xml
The previous `AccountInput` class became a little too complex and hard to change, so this PR lays some groundwork for future changes. It renames the old class into `AccountInputController`, which better fits its purpose. A new `AccountInput` class was created, but it acts as a custom widget and can be used in the XML layout files.
Most of the functionality remained the same, except that touch event were replaced by focus events, which are now properly handled. Previously, the input view had a few focus bugs. First, it would keep focused while disabled which would prevent the history from opening up after a login failure. And second, it didn't properly request focus when login failed, and the `findFocus()` call that was there was used incorrectly. With this now properly handled, the border …
> Create `AccountInput` widget

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/service/ConnectionProxy.kt
There was a single report with a crash happening when the `ConnectionProxy` was initialized. Through the stack trace it was possible to see that there was a `NullPointerException` while fetching the initial state. If fetching the state was quick enough, it would try to notify the tunnel state listeners before the notifiers had been initialized.
This PR fixes that issue by changing the initialization order. It also refactors the state properties to use the delegate provided by the notifiers.
Git checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2059)
> Fix race conditions during initialization of `ConnectionProxy`

- talpid-core/src/dns/linux/network_manager.rs
The changes made to NM to get it to work with the kernel WireGuard implementation broke it for OpenVPN. If the address that's already set for an interface is local to the link, then it shouldn't be reset by NM - it will complain and return an error. So I changed the code to only append the IPv6 addresses to the config if the link does not have link local addresses. I did not bump the changelog because this bug hasn't been released yet.
Makes me think whether it'd be better to set the IP address as link local for WireGuard too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2061)
> Fix NM for IPv6 with OpenVPN

- CHANGELOG.md
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/AccountFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ConnectFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LaunchFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/LoginFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/OutOfTimeFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SelectLocationFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/ServiceDependentFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SettingsFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/SplitTunnelingFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WelcomeFragment.kt
- android/src/main/kotlin/net/mullvad/mullvadvpn/ui/WireguardKeyFragment.kt
I've been overly conservative regarding the fragment lifecycles. They always wait for the window to gain focus before they start updating. This works for most cases, but it fails to work on split-screen mode when the user is using another app (i.e., our app's window loses focus). This becomes more apparent with configuration changes (like changing the text size in the accessibility options), where the app would return to the launch screen and wait until it receives focus again.
This PR changes all fragments to use `onStart`/`onStop` instead of `onResume`/`onPause`. This improves the situation in split screen mode with little impact on normal usage.
Git checklist:
--- …
> Update UI even when window doesn't have focus

- CHANGELOG.md
- mullvad-daemon/src/lib.rs
- mullvad-setup/src/main.rs
- talpid-core/src/firewall/mod.rs
- talpid-core/src/firewall/windows.rs
- talpid-core/src/tunnel_state_machine/disconnected_state.rs
- talpid-core/src/tunnel_state_machine/disconnecting_state.rs
- talpid-core/src/tunnel_state_machine/error_state.rs
- talpid-core/src/tunnel_state_machine/mod.rs
Previously, after upgrading, there always existed a small leak window where the firewall was reset to a non-blocking state for a very brief period of time. There were two causes for this:
- the firewall was initialized to a non-blocking state unless the daemon was configured to block when disconnected
- the tunnel state machine would always start from a disconnected state which would always reset the firewall
The first problem is resolved by having the daemon specify the firewall arguments, using the cached target state and the _block when disconnected_ setting to deduce whether the firewall should be initialized to a blocked state.
The second is resolved by allowing to specify whether the tunnel state machine should start in the disconnected or connecting state.
--- …
> Start tunnel state machine in appropriate state.

- ios/MullvadVPN/ConnectViewController.swift
…count has insufficient funds
Git checklist:
I forgot to undo the change that suppressed the account view from appearing when account has insufficient funds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mullvad/mullvadvpn-app/2066)
> Enable account view on insufficient funds
